### ISSUE TITLE
JDK8-openj9 builds failures : method addFlagAliasesFor in class BytecodeGenerator cannot be applied to given types

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#10012]
JDK8-openj9 builds failed
jdk8u-aix-ppc64-openj9
jdk8u-linux-ppc64le-openj9
jdk8u-linux-ppc64le-openj9-linuxXL
jdk8u-linux-s390x-openj9
jdk8u-linux-s390x-openj9-linuxXL
jdk8u-linux-x64-openj9
jdk8u-linux-x64-openj9-linuxXL
jdk8u-windows-x64-openj9
jdk8u-windows-x64-openj9-windowsXL
jdk8u-windows-x86-32-openj9

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/650/console

`Compiling tools to generate DDR pointer classes and structure stubs 18:46:01 c:\workspace\openjdk-build\workspace\build\src\openj9\debugtools\DDR_VM\src\com\ibm\j9ddr\BytecodeGenerator.java:88: error: method addFlagAliasesFor in class BytecodeGenerator cannot be applied to given types; 18:46:01 return addFlagAliasesFor(new HashMap<>(), className); 18:46:01 ^ 18:46:01 required: Map<String,String>,String 18:46:01 found: HashMap<Object,Object>,String 18:46:01 reason: actual argument HashMap<Object,Object> cannot be converted to Map<String,String> by method invocation conversion 18:46:01 1 error 18:46:01 make[3]: *** [/cygdrive/c/workspace/openjdk-build/workspace/build/src/closed/make/DDR.gmk:103: /cygdrive/c/workspace/openjdk-build/workspace/build/src/build/windows-x86-normal-server-release/jdk/ddr/tools.marker] Error 1 18:46:01 make[2]: *** [/cygdrive/c/workspace/openjdk-build/workspace/build/src/closed/make/Images.gmk:48: openj9.ddr-gen] Error 2 18:46:01 make[2]: *** Waiting for unfinished jobs.... 18:46:02 make[1]: *** [BuildJdk.gmk:102: images] Error 2 18:46:02 make: *** [/cygdrive/c/workspace/openjdk-build/workspace/build/src//make/Main.gmk:141: images-only] Error 2 18:46:02 Execution error: null`

**Comment by adamfarley** [comment]
This issue appears to have been caused by this PR:

https://github.com/eclipse/openj9/pull/9992

Keith and Peter S identified the failure and submitted a fix for it here:

https://github.com/eclipse/openj9/pull/10005

This issue should not be present in the next nightly.

**Comment by pshipton** [comment]
I'll go ahead and close. Pls reopen or comment if it's still a problem in the next nightly.
