### ISSUE TITLE
Remove remnants of JVMPI from JIT

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#10022]
The JIT still has remnants of JVMPI support which was deprecated in Java 5.0.  The following code should be removed:
1) https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/runtime/compiler/control/CompilationThread.cpp#L9440
This code should be folded assuming the JVMPI conditional is always false.

2) https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/runtime/compiler/control/CompilationThread.cpp#L9490
And remove all calls to it.

3) https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/runtime/compiler/control/CompilationThread.cpp#L9958
And remove all calls to it.

4) https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/runtime/compiler/x/codegen/J9TreeEvaluator.cpp#L784
Fold all code that uses this macro assuming it will always evaluate to `1` .

5) https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/runtime/compiler/ilgen/Walker.cpp#L6519
Remove and fold code assuming the `TR_OldJVMPI` is never set (i.e., evaluates to `0`)

6) https://github.com/eclipse/openj9/blob/1e504101295ed6f569a29741466546bb9cdcfa3a/runtime/compiler/control/J9Options.cpp#L2268
Delete these two jvmpi functions and fold the code that calls them assuming they return `0` or `false`.

**Comment by gacholio** [comment]
+1000

I suspect we'll be able to remove a few flags from the VM as well that are hanging around just to keep the obsolete code compiling (look for any bit constant defined as 0).
