### ISSUE TITLE
Build failure using Docker image due to git repack on Ubuntu

### ISSUE THREAD

**Issue by darshitpp** [eclipse/openj9#10025]
I am following the instructions provided at https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V11.md#setting-up-your-build-environment-with-docker-whale

But the script at the seemingly last step throws out the following error:
```
 * [new branch]      v0.21.0-release -> openj9/v0.21.0-release
 * [new branch]      v0.8.0-release -> openj9/v0.8.0-release
 * [new branch]      v0.9.0-release -> openj9/v0.9.0-release
Shrinking repository cache...
error: unknown option `threads=1'
usage: git repack [<options>]

    -a                    pack everything in a single pack
    -A                    same as -a, and turn unreachable objects loose
    -d                    remove redundant packs, and run git-prune-packed
    -f                    pass --no-reuse-delta to git-pack-objects
    -F                    pass --no-reuse-object to git-pack-objects
    -n                    do not run git-update-server-info
    -q, --quiet           be quiet
    -l, --local           pass --local to git-pack-objects
    -b, --write-bitmap-index
                          write bitmap index
    --unpack-unreachable <approxidate>
                          with -A, do not loosen objects older than this
    --window <n>          size of the window used for delta compression
    --window-memory <bytes>
                          same as the above, but limit memory size instead of entries count
    --depth <n>           limits the maximum delta depth
    --max-pack-size <bytes>
                          maximum size of each packfile
    --pack-kept-objects   repack objects in packs marked with .keep

The command '/bin/sh -c mkdir /home/jenkins/openjdk_cache  && cd /home/jenkins/openjdk_cache  && git init --bare  && git remote add jdk8 https://github.com/ibmruntimes/openj9-openjdk-jdk8.git  && git config remote.jdk8.tagopt --no-tags  && git remote add jdk11 https://github.com/ibmruntimes/openj9-openjdk-jdk11.git  && git config remote.jdk11.tagopt --no-tags  && git remote add jdk14 https://github.com/ibmruntimes/openj9-openjdk-jdk14.git  && git config remote.jdk14.tagopt --no-tags  && git remote add jdk15 https://github.com/ibmruntimes/openj9-openjdk-jdk15.git  && git config remote.jdk15.tagopt --no-tags  && git remote add jdknext https://github.com/ibmruntimes/openj9-openjdk-jdk.git  && git config remote.jdknext.tagopt --no-tags  && git remote add omr https://github.com/eclipse/openj9-omr.git  && git config remote.omr.tagopt --no-tags  && git remote add openj9 https://github.com/eclipse/openj9.git  && git config remote.openj9.tagopt --no-tags  && echo Fetching repository cache...  && git fetch jdk15  && git fetch --all  && echo Shrinking repository cache...  && git repack -a -d -f --depth=50 --window=250 --threads=1' returned a non-zero code: 129
```
I tried to verify what version of git was being used for the image, and as per `mkdocker.sh`, it uses v`2.5.3`.
While I could not find the docs online for that specific version, the [latest docs](https://git-scm.com/docs/git-repack) do suggest that `git repack` has the `--threads=<n>` option.

Adding the following text for better searchability (in case someone faces the same problem):

The command returned a non-zero code: 129

**Comment by pshipton** [comment]
What parameters did you use to create the docker script?

**Comment by pshipton** [comment]
I also note the link in the build instructions is wrong.

https://github.com/eclipse/openj9/blob/master/buildenv/mkdocker.sh
Should be
https://github.com/eclipse/openj9/blob/master/buildenv/docker/mkdocker.sh

**Comment by darshitpp** [comment]
> What parameters did you use to create the docker script?

I did not create the script, but used the command mentioned on the build instructions which uses `wget` to fetch the script. Would using a different local shell cause a problem? I use zsh, but followed exactly the same commands as mentioned in the instructions.

**Comment by pshipton** [comment]
Ok, I meant the Dockerfile. The docs mention `bash mkdocker.sh --tag=openj9 --dist=ubuntu --version=16.04 --build`.

As a workaround you can use `--print` instead of `--build`, and redirect the result to a file.
i.e. `bash mkdocker.sh --tag=openj9 --dist=ubuntu --version=16.04 --print > Dockerfile`.
Then modify the Dockerfile to remove the `--threads` option and use `docker build` to build it.

**Comment by pshipton** [comment]
Note git 2.5.3 is the version loaded on centos. Ubuntu just loads the git package, no specific version. I'm not sure what version Keith tested the `--threads` option with, possibly using `--dist=ubuntu --version=18` would work.

**Comment by pshipton** [comment]
My Ubuntu 16 image has git 2.7.4, which doesn't show a `--threads` option for `git repack`.

**Comment by pshipton** [comment]
Checked Ubuntu 18, which has git 2.17.1 and does show a `--threads` option.

**Comment by pshipton** [comment]
Incidentally, the OS used to build will affect the OSes where the resulting JVM can run. If you only want to run it in the docker image, the OS you choose doesn't much matter. If you want to run it elsewhere, you need to build on an OS with the same or lower glibc level. Basically, if you choose `--dist=centos --version=6.9` you'll have the most compatibility. A little less so with `--dist=centos --version=7`, and then lesser still with the ubuntu versions.

**Comment by darshitpp** [comment]
That worked -- creating and using the dockerfile worked and resulted in a successful output. 

However, I noticed that jdk11 and 14 weren't installed. Note that the same thing happened when I was trying to install it yesterday, and the build didn't result in any error whatsoever. I'm not sure how/when this occurs, but it didn't actually raise a failure while during `docker build`. I would be happy to create a separate issue regarding this if you suggest. For now, I am manually installing the additional jdks inside the container.
