### ISSUE TITLE
openj9.cuda, openj9.gpu, openj9.dataaccess not included in JRE

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10030]
The openj9.cuda and openj9.gpu modules are not include in the JRE image, we could consider including them.

**Comment by keithc-ca** [comment]
The fix for jdknext is pending #10450 and acceptance of the staging branch.

**Comment by keithc-ca** [comment]
On second thought, we don't need to wait to fix jdknext: ibmruntimes/openj9-openjdk-jdk#228

**Comment by pshipton** [comment]
The changes have been merged.

**Comment by pshipton** [comment]
Seems I missed openj9.dataaccess, so I'll reopen this.

**Comment by keithc-ca** [comment]
`openj9.dataaccess` has been added - closing.
