### ISSUE TITLE
Startup Times are significanlty worse on OS startup with SCC

### ISSUE THREAD

**Issue by Caranthir** [eclipse/openj9#10087]
Java -version output
--------------------
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Linux amd64-64-Bit Compressed References 20200416_574 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)

Summary of problem
------------------
I have 4 Java Spring Boot applications that start when the OS starts automatically. 
I run these applications with the following command:
`ExecStart=/usr/bin/java -Xshareclasses:groupAccess,persistent -Dlog4j.configurationFile=***** -jar /usr/share/******`

But these applications need about 48 seconds to 65 seconds to startup when shared classes cache is enabled when they startup with the OS. When I restart the applications without restarting the OS, they only need about 12 seconds to startup.

When SCC is disabled they need about 26 to 42 seconds to startup when they start with the OS automatically. 

I thought that a persistent cache stays even after an OS reboot. Why do I have so high startup times at OS startup with SCC? Do I need to set another property?

**Comment by pshipton** [comment]
@hangshao0

**Comment by hangshao0** [comment]
> I thought that a persistent cache stays even after an OS reboot.

Yes, they should be there even after an OS reboot. Running `java -Xshareclasses:groupAccess,persistent,printStats` after reboot should be able to verify. If the cache is not there, you will see a cache does not exist error. 


Not sure why starting OS would impact the SCC performance. Could you please try with these options: 
1. `-Xshareclasses:groupAccess,persistent,readOnly`
2. `-Xshareclasses:groupAccess,persistent,mprotect=none`
3. `-Xshareclasses:groupAccess,persistent,noTimestampChecks`

**Comment by Caranthir** [comment]
When I run `java -Xshareclasses:groupAccess,persistent,readOnly`
I get the following output: 

```
Current statistics for cache "sharedcc_arrowhead": 

Cache created with:
	-Xnolinenumbers                      = false
	BCI Enabled                          = true
	Restrict Classpaths                  = false
	Feature                              = cr

Cache contains only classes with line numbers

base address                         = 0x00007F8F88059000
end address                          = 0x00007F8F8C000000
allocation pointer                   = 0x00007F8F89E1DE00

cache layer                          = 0
cache size                           = 67108256
softmx bytes                         = 67108256
free bytes                           = 0
Reserved space for AOT bytes         = -1
Maximum space for AOT bytes          = -1
Reserved space for JIT data bytes    = -1
Maximum space for JIT data bytes     = -1
Metadata bytes                       = 2244240
Metadata % used                      = 3%
Class debug area size                = 5337088
Class debug area used bytes          = 4799568
Class debug area % used              = 89%

ROMClass bytes                       = 31217032
AOT bytes                            = 27404280
JIT data bytes                       = 541680
Zip cache bytes                      = 0
Startup hint bytes                   = 0
Data bytes                           = 363936

# ROMClasses                         = 35081
# AOT Methods                        = 5027
# Classpaths                         = 25
# URLs                               = 0
# Tokens                             = 0
# Zip caches                         = 0
# Startup hints                      = 0
# Stale classes                      = 0
% Stale classes                      = 0%


Cache is 100% full

Cache is accessible to current user = true
```

I tried the 3 options you named. With the first option I get the following error:
```

Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain
Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: IBM Java[727]: JVMSHRC226E Error opening shared class cache file
Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: IBM Java[727]: JVMSHRC336E Port layer error code = -108
Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: IBM Java[727]: JVMSHRC337E Platform error message: No such file or directory
Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: IBM Java[727]: JVMSHRC840E Failed to start up the shared cache.
Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: Error: Could not create the Java Virtual Machine.
Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: Error: A fatal exception has occurred. Program will exit.
Jul 06 23:30:02 arrowheadtest-VirtualBox systemd[1]: arrowhead-serviceregistry.service: Main process exited, code=exited, status=1/FA
Jul 06 23:30:12 arrowheadtest-VirtualBox systemd[1]: arrowhead-serviceregistry.service: Failed with result 'exit-code'.
Jul 06 23:30:12 arrowheadtest-VirtualBox systemd[1]: Failed to start arrowhead-serviceregistry.
```
With the second option, I get the same results as the initial ones. 

With the third option I also get the same results as the initial ones.

**Comment by hangshao0** [comment]
> With the first option I get the following error:
> ...
> Jul 06 23:30:02 arrowheadtest-VirtualBox java[727]: IBM Java[727]: JVMSHRC337E Platform error message: No such file or directory

With `readOnly` on in the first option, the JVM will only attempt to open an existing SCC. The No such file error means no exiting SCC is found. I guess the SCC is deleted somehow by the OS reboot. 

Can you verify the creation time of the cache file to see it is before or after the OS reboot time ? You can find the cache file under $HOME/javasharedresources or by running: `java -Xshareclasses:groupAccess,persistent:printCachefileName`

**Comment by Caranthir** [comment]
Yes, you are right. The creation time of the cache is the OS reboot time. I also added a test file to tmp folder to see if it survives the reboot. It was deleted automatically. I am using Ubuntu 18.04 and as far as I can see it is the default behaviour and can't be changed (easily). Maybe it would be better to put this cache file somewhere else then tmp folder in the next release?

**Comment by hangshao0** [comment]
> Maybe it would be better to put this cache file somewhere else then tmp folder in the next release?

That is a good idea.

**Comment by pshipton** [comment]
Is the cache not created in $HOME?

**Comment by hangshao0** [comment]
> Is the cache not created in $HOME?

They are using `groupAccess`, so it is under /tmp.

**Comment by pshipton** [comment]
Ok, as it needs to be in a shared location. Seems the https://www.eclipse.org/openj9/docs/xshareclasses/#cachedir option should be used to set a shared location outside of the /tmp dir.

**Comment by hangshao0** [comment]
I should be more clear about my previous reply here: https://github.com/eclipse/openj9/issues/10087#issuecomment-654503929

I mean it is a good idea to put the cache under somewhere else, not changing default cache directory (/tmp/javasharedresources/ with groupAccess option on) in OpenJ9's next release. `-Xshareclasses:cacheDir=<dir>` can be used to set the cache directory.

**Comment by Caranthir** [comment]
Thanks for your answers. I also think it would be a good idea to change the default cache location for groupAccess, since many people will have similar problems like me and /tmp folder shouldn't be used for permenant storage anyway.

**Comment by hangshao0** [comment]
Yes, it is a valid point. My main concern is that changing the default cache directory will impact our existing users.

**Comment by pshipton** [comment]
Also, what default location would be used that is visible to all the group users? It seems a documentation problem. I'll create a PR to update the groupAccess doc to call out that the default location is /tmp and the cacheDir option should be used to change it.

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9-docs/pull/596

**Comment by pshipton** [comment]
Is there anything else remaining to do for this? I think it can be closed now.
