### ISSUE TITLE
.map files are discarded but not in the debugimage

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10099]
Re https://github.com/eclipse/openj9/pull/10053, .map files are removed, but are not part of the debugimage.

**Comment by keithc-ca** [comment]
I assume you're asking that `.map` files be included in debug images rather than re-included in JDK images.

**Comment by pshipton** [comment]
Correct.

**Comment by keithc-ca** [comment]
The pull requests above add `.map` files that were previously in JDK images to debug images.

I intend to adjust the OpenJ9 build so it produces `.map` files with the right names in the right places for future inclusion in debug images, so this should stay open until that work is done.

**Comment by keithc-ca** [comment]
Now that the above two pull requests are merged, OMR and OpenJ9 produce `.map` files with the desired names.
Additional changes are required to the extension repos to copy those files to the right places so they will be included in debug images.

**Comment by keithc-ca** [comment]
The new pull requests above add Windows `.map` files from OpenJ9 artifacts to debug images.

**Comment by keithc-ca** [comment]
I believe this is now complete.
