### ISSUE TITLE
Move Windows jdk8 compiles to VS2013

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10129]
As VS2010 is going out of support July 14, we should change the compiler used to build Windows jdk8. The highest supported level atm is VS2013 according to https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/common/autoconf/toolchain_windows.m4

We'll need the compiler installed on the build machines, and check if any changes are needed for OpenJ9 to compile (we know it works with VS2017).

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
We aren't going to have enough space for builds unless we can either delete vs2010 or get more hard disk.  Current systems have between 17-21G free which is what is available for compile/test jobs.

**Comment by pshipton** [comment]
Seems to me the current installations are bloated, installing all VS components instead of just the subset required to compile and link. While we can delete VS2010 once VS2013 is working, during the transition we'll need both. How about removing VS2010 on one machine and installing VS2013 instead. We'll need to adjust the labels and build requirements to manage it. Once we prove the build is working on the single machine, the same change can be done to the rest.

**Comment by jdekonin** [comment]
Can this be closed?

**Comment by pshipton** [comment]
Yup, we've successfully transitioned to VS2013. Thanks for making this happen.
