### ISSUE TITLE
jenkins testing pipelines, set JDK_REPO and JDK_BRANCH for tests

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10123]
As per https://github.com/AdoptOpenJDK/openjdk-tests/issues/1872, the pipeline scripts should start passing JDK_REPO and JDK_BRANCH to test jobs. Some tests (such as openjdk tests) need the information in order to run the testing which matches the JDK.

**Comment by pshipton** [comment]
@smlambert @llxia @AdamBrousseau

**Comment by pshipton** [comment]
@vsebe with the merge of #10184, is there anything else to do for this or can it be closed?

**Comment by vsebe** [comment]
It can be closed since https://github.com/eclipse/openj9/pull/10184 and https://github.com/AdoptOpenJDK/openjdk-tests/pull/1876 are merged.
