### ISSUE TITLE
Calling hashClassTableAtString first to avoid verifying duplicate class names by verifyQualifiedName

### ISSUE THREAD

**Issue by ChengJin01** [eclipse/openj9#10125]
Currently, we tend to call `internalFindClassString` after calling `verifyQualifiedName`, both of which call `copyStringToUTF8WithMemAlloc`.   Normally, `internalFindClassString` has a fast path which checks the classHashTable to see if the class has already been loaded via `hashClassTableAtString`.  So we propose to move the `verifyQualifiedName` call into `internalFindClassString` and do the check after the `hashClassTableAtString` so as to avoid calling `verifyQualifiedName` when duplicated classes being checked.

e.g.
```
internalFindClassString(J9VMThread* currentThread, j9object_t moduleName, j9object_t className, J9ClassLoader* classLoader, UDATA options)
{
    J9CfrConstantPoolInfo classNameInfo = {0, 0, 0, 0, 0, NULL, 0};
      ...
	result = hashClassTableAtString(classLoader, (j9object_t) className); <-------
	if (!fastMode) {
		omrthread_monitor_exit(vm->classTableMutex);
	}

	if (NULL == result) {
        ...
        classNameInfo.bytes= copyStringToUTF8WithMemAlloc(currentThread, className,...., &utf8Length)
        classNameInfo.slot1 = (U_32)utf8Length;
        if (CLASSNAME_INVALID == verifyQualifiedName(_currentThread, classNameInfo)) {  <--------------------
    ...
```
To avoid calling `copyStringToUTF8WithMemAlloc` twice,  we can replace the parameters of `verifyQualifiedName` called ` j9object_t className` with `J9CfrConstantPoolInfo classNameInfo` so as to pass it over to `verifyQualifiedName` after  `classNameInfo` is set up with `copyStringToUTF8WithMemAlloc`, in which case the results from `copyStringToUTF8WithMemAlloc` can be shared by both `verifyQualifiedName` and the remaining code in `internalFindClassString`.

Now the question is whether there is any potential issue or technical obstacle we are not aware of.

The proposal includes the following PRs:
(1) step `[1]`: the changes of `moving verifyQualifiedName into internalFindClassString` at https://github.com/eclipse/openj9/pull/10188
(2) step `[2]` & `[3]`: the changes of `Move verifyQualifiedName to jvmDefineClassHelper & defineClassCommon` at https://github.com/eclipse/openj9/pull/10226
(3) step `[4]`:  the changes of `share the memory allocated  by
     copyStringToUTF8WithMemAlloc between verifyQualifiedName and its callers` at https://github.com/eclipse/openj9/pull/10324

FYI:  @DanHeidinga , @gacholio, @pshipton

**Comment by ChengJin01** [comment]
I have a couple of questions for this proposal:

[1] What if the class name is a bogus one?  in such case, no class is found at `hashClassTableAtString` and it moves forward to  check the validity of the class name in `verifyQualifiedName`. Is this logically reasonable?

[2] Suppose we eventually removed the memory allocation in verifyQualifiedName. Do we still need to move the `verifyQualifiedName` call into `internalFindClassString` in this way?

**Comment by ChengJin01** [comment]
Looking at the code in `internalFindClassString` as follows:
```
internalFindClassString(J9VMThread* currentThread, j9object_t moduleName, j9object_t className, J9ClassLoader* classLoader, UDATA options)
{
		utf8Name = copyStringToUTF8WithMemAlloc(currentThread, className, 
J9_STR_NULL_TERMINATE_RESULT | J9_STR_XLAT,  <-------- J9_STR_XLAT is set up for copyStringToUTF8WithMemAlloc
"", 0, localBuf, J9VM_PACKAGE_NAME_BUFFER_LENGTH, &utf8Length);


```
J9_STR_XLAT  is used in internalFindClassString when allocating memory for the class name,
against the `copyStringToUTF8WithMemAlloc` call  in `verifyQualifiedName`
```
verifyQualifiedName(J9VMThread *vmThread, j9object_t string)
{
...
	classNameInfo.bytes = (U_8*)copyStringToUTF8WithMemAlloc(vmThread, string,
									J9_STR_NULL_TERMINATE_RESULT, <---- J9_STR_XLAT is not specified
                                                                         "", 0,
									utf8NameStackBuffer, ....)

```
The reason for this was explained at https://github.com/eclipse/openj9/pull/6414#issuecomment-535223807 based on the failing test cases:
```
The test failures with the changes on Java 8 indicate that the changes failed to address the illegal case of `/` 
(already covered in the original implementation) as all `/`s in the class name are converted to `.` 
with `J9_STR_XLAT` specified before calling checkNameImpl (it treats `/` as legal and `.` as illegal, 
which is totally opposite to `verifyQualifiedName`).
 In such case, there is no way to detect the the illegal case of `/` without any changes in checkNameImpl.
...
```
So it seems troublesome to share `copyStringToUTF8WithMemAlloc` between `verifyQualifiedName` and `internalFindClassString` in terms of the `J9_STR_XLAT` option.

**Comment by ChengJin01** [comment]
@gacholio,  any other concern & suggestion on this proposal?

**Comment by gacholio** [comment]
What is the purpose of this? The vast majority of callers of `internalFindClassString` are in fact not calling `verifyQualifiedName`.

**Comment by ChengJin01** [comment]
@gacholio , 

We refactored the code of `verifyQualifiedName` last year to address all invalid class names detected by https://github.com/eclipse/openj9/issues/5225. The initial intention was to call `copyStringToUTF8WithMemAlloc` to allocate memory  (or use an buffer on the stack)  for the class name so as to leverage the existing code in `checkNameImpl` (`/runtime/verutil/chverify.c`) to verify the class name.

However, `copyStringToUTF8WithMemAlloc` will be called twice in loading classes in such case (one from `verifyQualifiedName` and later from `internalFindClassString`),  regardless of duplicate classes being loaded.

To avoid this case, we can take advantage of `hashClassTableAtString` in `internalFindClassString` to avoid verifying duplicate classes by moving `verifyQualifiedName` to `internalFindClassString` (after the check of `hashClassTableAtString`). Meanwhile, the allocated memory by `copyStringToUTF8WithMemAlloc` can be shared by  both `verifyQualifiedName` and `internalFindClassString`.

**Comment by gacholio** [comment]
Is there an identified performance issue this is trying to fix? If not, I'd be tempted to simply leave this alone.

**Comment by ChengJin01** [comment]
Talked to @gacholio offline, there are still a bunch of details in there to figure out as we have no idea what is the impact with these changes. 

We probably have to fix the regression issue first without the proposal (e.g. simply remove `copyStringToUTF8WithMemAlloc` in `verifyQualifiedName`  for a temp solution (In theory, the proposal will work but not sure whether it entirely solves all issues as expected.... / or something else gets introduced in this way...)

In addition, not all callers of `verifyQualifiedName` are calling `internalFindClassString` but still calling `copyStringToUTF8WithMemAlloc` e.g.
```
jclass JNICALL
JVM_DefineClassWithSource(JNIEnv *env, const char * className, jobject classLoader, const jbyte * classArray, jsize length, jobject domain, const char * source)
{
...
	if (CLASSNAME_INVALID == vmFuncs->verifyQualifiedName(currentThread, J9_JNI_UNWRAP_REFERENCE(classNameString))) {
    ...

	return jvmDefineClassHelper(env, classLoader, classNameString, (jbyte*)classArray, 0, length, domain, 0);
}

jvmDefineClassHelper(JNIEnv *env, jobject classLoaderObject,
	jstring className, jbyte * classBytes, jint offset, jint length, jobject protectionDomain, UDATA options)
{
...
	if (NULL != className) {
		utf8Name = (U_8*)vmFuncs->copyStringToUTF8WithMemAlloc(currentThread, J9_JNI_UNWRAP_REFERENCE(className), J9_STR_NULL_TERMINATE_RESULT | J9_STR_XLAT, "", 0, utf8NameStackBuffer, J9VM_PACKAGE_NAME_BUFFER_LENGTH, &utf8Length);
		if (NULL == utf8Name) {
			vmFuncs->setNativeOutOfMemoryError(currentThread, 0, 0);
			goto done;
		}
	}
...
```

**Comment by ChengJin01** [comment]
Given `verifyQualifiedName` is invoked at various places,  The proposed improvement will be split to a couple of PRs to address different situations:
```
[1] /runtime/vm/BytecodeInterpreter.hpp
move verifyQualifiedName into internalFindClassString
<1> inlClassLoaderFindLoadedClassImpl
    Fast_java_lang_Classloader_findLoadedClassImpl at /runtime/vm/FastJNI_java_lang_ClassLoader.cpp
<2> inlVMFindClassOrNull
    Fast_java_lang_VMAccess_findClassOrNull at /runtime/vm/FastJNI_com_ibm_oti_vm_VM.cpp
<3> inlClassForNameImpl
    Fast_java_lang_Class_forNameImpl at /runtime/vm/FastJNI_java_lang_Class.cpp

[2]JVM_DefineClassWithSource at /runtime/jcl/common/clsldr.cpp
move verifyQualifiedName into jvmDefineClassHelper

[3]Java_java_lang_ClassLoader_defineClassImpl at /runtime/jcl/common/clsldr.cpp
move verifyQualifiedName into defineClassCommon

[4]figure out whether it is reasonable to share the memory allocated 
    by copyStringToUTF8WithMemAlloc between verifyQualifiedName and callers
```
As for [4], there are two things to be considered for sharing the memory between `verifyQualifiedName` and its new callers:
[1] J9_STR_XLAT is set up in`copyStringToUTF8WithMemAlloc` to convert `.` to `/`, which is totally opposite to the criteria of `verifyQualifiedName` (`/` is treated as illegal there).
[2] VM needs to call `copyStringToUTF8WithMemAlloc` first to allocate memory for use in `verifyQualifiedName`, which make senses only when there is no invalid class name; otherwise, it might be a waste of time on memory allocation.

Will first address steps from [1]~[3] before get back to see how we deal with step [4].

**Comment by ChengJin01** [comment]
PR for all code mentioned in `[1]` has been created at https://github.com/eclipse/openj9/pull/10188 for review.

**Comment by ChengJin01** [comment]
I will get started to look at the following step `[2]` & `[3]` to see what  we can do with the existing code.

```
[2]JVM_DefineClassWithSource at /runtime/jcl/common/clsldr.cpp
move verifyQualifiedName into jvmDefineClassHelper

[3]Java_java_lang_ClassLoader_defineClassImpl at /runtime/jcl/common/clsldr.cpp
move verifyQualifiedName into defineClassCommon
```

**Comment by gacholio** [comment]
I very much doubt either or those will have any impact on performance, as they run exactly once per class, unlike the lookups.

**Comment by ChengJin01** [comment]
@gacholio,  the step `[4]` is based on whether we can fix all the similar issue with verifyQualifiedName at step `[1]`, `[2]` and `[3]`. If not the case, we have to stop here.

**Comment by ChengJin01** [comment]
I already finished the changes of step `[2]` & `[3]` but a couple of test failures related to the changes was detected in personal builds. Will investigate to see what happened to the code there.

**Comment by ChengJin01** [comment]
Already fixed all test failures in the personal builds and PR for `part5_fix_v2` for step `[2]` & `[3]` has been created at https://github.com/eclipse/openj9/pull/10226 for review.

**Comment by ChengJin01** [comment]
Will get started to figure out how to deal with step `[4]` as #10226 was approved:
```
[4] figure out whether it is reasonable to share the memory allocated  by
     copyStringToUTF8WithMemAlloc between verifyQualifiedName and its callers
```

**Comment by ChengJin01** [comment]
PR for step [4] has been created at https://github.com/eclipse/openj9/pull/10324 for review.

**Comment by ChengJin01** [comment]
Close the issue as all fixes at step `[1]`, `[2] & [3]` and `[4]` with the expected results have been merged.
