### ISSUE TITLE
JDK 15 : Basic.java Identical buffers not equal: java.nio.ByteBufferAsShortBufferB[pos=2 lim=5 cap=3584], java.nio.HeapShortBuffer[pos=2 lim=5 cap=3584]

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10150]
Failure link
------------

From an internal build `Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/8`:
```
22:31:31  openjdk version "15-internal" 2020-09-15
22:31:31  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15ppc64lelinuxNightly)
22:31:31  Eclipse OpenJ9 VM (build master-d8cd2a6fb35, JRE 15 Linux ppc64le-64-Bit Compressed References 20200707_19 (JIT enabled, AOT enabled)
22:31:31  OpenJ9   - d8cd2a6fb35
22:31:31  OMR      - 281f29d31a6
22:31:31  JCL      - 8e963ae8ecc based on jdk-15+30)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
23:07:05  --------------------------------------------------
23:07:05  TEST: java/nio/Buffer/Basic.java
23:07:05  TEST JDK: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image
23:07:05  
23:07:05  STDERR:
23:07:05  java.nio.HeapByteBuffer[pos=0 lim=7168 cap=7168] 55c48001
23:07:05    java.nio.ByteBufferAsShortBufferB[pos=0 lim=3584 cap=3584] ab6d216d
23:07:05  [2] 1 != 0
23:07:05  [3] 32767 != 0
23:07:05  [4] -32768 != 0
23:07:05  java.lang.RuntimeException: Identical buffers not equal: java.nio.ByteBufferAsShortBufferB[pos=2 lim=5 cap=3584], java.nio.HeapShortBuffer[pos=2 lim=5 cap=3584]
23:07:05  	at Basic.fail(Basic.java:76)
23:07:05  	at BasicShort.test(BasicShort.java:756)
23:07:05  	at BasicByte.testViews(BasicByte.java:273)
23:07:05  	at BasicByte.test(BasicByte.java:937)
23:07:05  	at BasicByte.test(BasicByte.java:1139)
23:07:05  	at Basic.main(Basic.java:135)
23:07:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:07:05  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
23:07:05  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:07:05  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
23:07:05  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
23:07:05  	at java.base/java.lang.Thread.run(Thread.java:851)
23:07:05  
23:07:05  JavaTest Message: Test threw exception: java.lang.RuntimeException
23:07:05  JavaTest Message: shutting down test
23:07:05  
23:07:05  
23:07:05  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Identical buffers not equal: java.nio.ByteBufferAsShortBufferB[pos=2 lim=5 cap=3584], java.nio.HeapShortBuffer[pos=2 lim=5 cap=3584]
23:07:05  --------------------------------------------------
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk11_tier1_buffer_0

**Comment by JasonFengJ9** [comment]
Another similar failure at https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix_Nightly/26/consoleFull
```
02:42:06    java.nio.ByteBufferAsShortBufferL[pos=0 lim=3584 cap=3584] e61d46ab
02:42:06  [2] 1 != 0
02:42:06  [3] 32767 != 0
02:42:06  [4] -32768 != 0
02:42:06  java.lang.RuntimeException: Identical buffers not equal: java.nio.ByteBufferAsShortBufferL[pos=2 lim=5 cap=3584], java.nio.HeapShortBuffer[pos=2 lim=5 cap=3584]
02:42:06  	at Basic.fail(Basic.java:76)
02:42:06  	at BasicShort.test(BasicShort.java:756)
02:42:06  	at BasicByte.testViews(BasicByte.java:273)
02:42:06  	at BasicByte.test(BasicByte.java:947)
02:42:06  	at BasicByte.test(BasicByte.java:1139)
02:42:06  	at Basic.main(Basic.java:135)
02:42:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:42:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
02:42:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:42:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
02:42:06  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
02:42:06  	at java.base/java.lang.Thread.run(Thread.java:851)
02:42:06  
02:42:06  JavaTest Message: Test threw exception: java.lang.RuntimeException
02:42:06  JavaTest Message: shutting down test
02:42:06  
02:42:06  
02:42:06  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Identical buffers not equal: java.nio.ByteBufferAsShortBufferL[pos=2 lim=5 cap=3584], java.nio.HeapShortBuffer[pos=2 lim=5 cap=3584]
```

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this

**Comment by JasonFengJ9** [comment]
@tajila sure, will investigate and determine if this is a stop-shipping issue for Java 15.

**Comment by JasonFengJ9** [comment]
**Update:**

Built a standalone testcase based on `java/nio/Buffer/Basic.java`, and reproduced the `RuntimeException`:
```
Exception in thread "main" java.lang.RuntimeException: Identical buffers not equal: java.nio.ByteBufferAsShortBufferB[pos=2 lim=5 cap=3584], java.nio.HeapShortBuffer[pos=2 lim=5 cap=3584]
	at a.se.openjdk.TestBasicShort.fail(TestBasicShort.java:127)
	at a.se.openjdk.TestBasicShort.test(TestBasicShort.java:547)
	at a.se.openjdk.TestBasicShort.testAll(TestBasicShort.java:96)
	at a.se.openjdk.TestBasicShort.main(TestBasicShort.java:10)
```

For this particular testcase, `RI JDK15` passes, so does `OpenJ9 JDK14` (built around mid of August) as well.

The test code snippet in question are as following [1]:
```
		ShortBuffer b2 = ShortBuffer.allocate(b.capacity());
		b2.put(b);  ----------------> this method doesn't produce expected result.
		b2.flip();
		b.position(2);
		b2.position(2);
		if (!b.equals(b2)) {
			for (int i = 2; i < b.limit(); i++) {
				short x = b.get(i);
				short y = b2.get(i);
				if (x != y
				) {
					out.println("[" + i + "] " + x + " != " + y);
				}
			}
			fail("Identical buffers not equal", b, b2);
		}
```

The method `b2.put(b)` produced incorrect result through following APIs:
```
ShortBuffer.put(ShortBuffer) -> 
UNSAFE.copySwapMemory(srcBase, srcAddr, base, addr, len, (long)1 << 1) -->
Java_jdk_internal_misc_Unsafe_copySwapMemory0()
```

There is no obvious `JDK15` specific PR suspect from code history at `sun_misc_Unsafe.cpp`. It might be related to new JCL level and object shape changes.

Based on this is a regression from `JDK14` and the problem area is in the proximity of `Unsafe` memory copying, I think this is a potential stop-ship issue.
Will continue digging if this just affects a small corner case or apply to broader usages.


[1] https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/ad829e12c8f52c9774b8b8705fe438cb7a9d58cb/test/jdk/java/nio/Buffer/BasicShort.java#L676-L760

**Comment by DanHeidinga** [comment]
@JasonFengJ9 does it fail `-Xint`?  It might help to narrow down whether this is likely due to the interpreter or the JIT

**Comment by JasonFengJ9** [comment]
@DanHeidinga yeah, it still fails with `-Xint`.

**Comment by JasonFengJ9** [comment]
`JDK14` has a different code path for `b2.put(b)`:
```
	at java.base/java.nio.HeapShortBuffer.put(HeapShortBuffer.java:212)
	at java.base/java.nio.ShortBuffer.put(ShortBuffer.java:952)
	at java.base/java.nio.HeapShortBuffer.put(HeapShortBuffer.java:271)
	at a.se.openjdk.TestBasicShort.simplecase(TestBasicShort.java:43)
	at a.se.openjdk.TestBasicShort.main(TestBasicShort.java:9)

HeapShortBuffer.put(ShortBuffer src) -->
super.put(src) --> 
ShortBuffer.put(ShortBuffer src)  -->
put(src.get()) -->
HeapShortBuffer.put(short x) -->
hb[ix(nextPutIndex())] = x;
```

In this case `JDK14` takes a pure Java approach while `JDK15` uses `UNSAFE.copySwapMemory()` native(s).
So the issue with `Unsafe` native probably just was exposed by `JDK15` usage, not a newly introduced regression since `JDK14` (from the perspective of this test).

To summarize, this is not a VM code regression, and the JTReg test failure can be addressed in later releases, I would not categorize this as a stop-ship issue.

@tajila does this make sense?

**Comment by JasonFengJ9** [comment]
**Further updates:**

The problem is clearly in `sun_misc_Unsafe.cpp: Java_jdk_internal_misc_Unsafe_copySwapMemory0` and its helper friends such as https://github.com/eclipse/openj9/blob/5aad64266fb5457e66168fb39755b5dd0ea2bb4e/runtime/jcl/common/sun_misc_Unsafe.cpp#L1118-L1140

For this particularly testcase, returning `JNI_TRUE` (for **no** memory overlap which is correct) can make the test pass however it returns `JNI_FALSE`. Trying to understand the rational behind these methods.

**Comment by DanHeidinga** [comment]
It looks like the case checking for the same object (sourceObject == destObject) is missing.  Does adding it resolve the failure?

**Comment by JasonFengJ9** [comment]
> It looks like the case checking for the same object (sourceObject == destObject) is missing.

Assuming the same object means there is memory overlap hence `memOverlapIsNone` returns `JNI_FALSE`, in that case it won't resolve the failure.

Returning `JNI_TRUE` when `(sourceObject != destObject)` which assume no memory overlap can pass this test.

**Comment by JasonFengJ9** [comment]
Opened #10556 which passes the testcase in this issue, and also tested in a personal build (`Java 8/11/15` `xa64` `sanity.functional`).

**Comment by hzongaro** [comment]
Sorry that reference was a typo.
