### ISSUE TITLE
plinux failing to curl jtreg

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10166]
I've seen this a few times. Is there a dependency job that needs to be re-run?

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/109 - ub16-ppcle-1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Release/7 - ub16-ppcle-2
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8/12 - ub16-ppcle-3
```
18:29:19  getJtreg:
18:29:19      [mkdir] Created dir: /home/****/****-agent/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8/jvmtest/openjdk
18:29:19       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
18:32:24       [exec] curl: (18) transfer closed with 1598752 bytes remaining to read
```

**Comment by pshipton** [comment]
@smlambert @llxia @jdekonin

**Comment by smlambert** [comment]
At present we pull last successful artifacts from the jtreg job directly, not from a getDependencies job:
https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg/.  The artifact is present, so this is a networking issue.

From [StackOverflow](https://stackoverflow.com/questions/1759956/curl-error-18-transfer-closed-with-outstanding-read-data-remaining): 

> The error string is quite simply exactly what libcurl sees: since it is receiving a chunked encoding stream it knows when there is data left in a chunk to receive. When the connection is closed, libcurl knows that the last received chunk was incomplete. Then you get this error code.

> There's nothing you can do to avoid this error with the request unmodified, but you can try to work around it by issuing a HTTP 1.0 request instead (since chunked encoding won't happen then) but the fact is that this is most likely a flaw in the server or in your network/setup somehow.

**Comment by smlambert** [comment]
And before its asked, we do [retry](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/build.xml#L43) to get this artifact.

**Comment by smlambert** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1841

**Comment by smlambert** [comment]
Will close as a dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1894
