### ISSUE TITLE
Should Trc_VM_sidecarInvokeReflectMethod_Entry/Exit be a level2 tracepoint

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1016]
The Trc_VM_sidecarInvokeReflectMethod_Entry/Exit traces are level2 tracepoints which means they are on by default. There are cases where these tracepoints can account for up to 75% percent of the snaptrace output. 

These tracepoints do not provide any information other than the currentThread and the fact that the tracepoint was triggered. 

Should these tracepoints be level2?

**Comment by pshipton** [comment]
I suppose the tracepoints could help diagnostics if a crash occurred inside sidecarInvokeReflectMethodImpl(), although a native debugger should be able to show the same.

@gacholio any opinion on lowering the tracepoint levels?

**Comment by gacholio** [comment]
Im my experience, tranepoints have rarelry been significant in resolving issues.  It's easy to up the TP level if problems are being encountered, so I say let's go for the performance by default (i.e. up the TPs to level2).
