### ISSUE TITLE
zlinux sanity.functional tests hanging during compile

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10171]
zlinux sanity.functional tests hanging during compile in OMR acceptance.

First seen in https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/2025/
https://github.com/eclipse/omr/compare/7a0b420...9a797cc

It's possible the problem was not introduced by OMR changes. There were no nightly builds last night due to 0.21.0 release testing.
OpenJ9 changes are https://github.com/eclipse/openj9/compare/01cb796...4a10ff03
Started nightly testing on zlinux for triage
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/971/ - passed
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All-11/241/ - passed

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_0/46
The hang occurs in the following spot. Sometimes when the job is interrupted it continues and runs tests.
```
06:01:08  compile:
06:01:08       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018
06:01:08       [echo] ============COMPILER SETTINGS============
06:01:08       [echo] ===executable:                   /home/****/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_0/openjdkbinary/j2sdk-image/bin/javac
06:01:08       [echo] ===destdir:                      /home/****/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_0/openjdk-tests/TKG/../../jvmtest/functional/JavaAgentTest
06:01:08      [javac] Compiling 16 source files to /home/****/workspace/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_0/openjdk-tests/functional/JavaAgentTest/bin
Aborted by Peter Shipton
```

Also seen here
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_s390x_linux_xl_OMR_testList_1/45
```
16:44:40  compile:
16:44:40       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018
16:44:40       [echo] ============COMPILER SETTINGS============
16:44:40       [echo] ===fork:				yes
16:44:40       [echo] ===executable:			/home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_xl_OMR_testList_1/openjdkbinary/j2sdk-image/bin/javac
16:44:40       [echo] ===debug:				on
16:44:40       [echo] ===destdir:				/home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_xl_OMR_testList_1/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/locale_matching
16:44:40      [javac] Compiling 6 source files to /home/****/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_xl_OMR_testList_1/openjdk-tests/functional/MBCS_Tests/locale_matching/bin
Aborted by Peter Shipton
```

**Comment by pshipton** [comment]
Originally thought this was specific to the rh7-390 machines, but the following occurred on ub16-390.

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_s390x_linux_OMR_testList_1/46 - ub16-390-1

**Comment by pshipton** [comment]
@RSalman So far I haven't seen this hang outside of OMR acceptance, could https://github.com/eclipse/omr/pull/5336 be causing this problem.
@amicic fyi

**Comment by amicic** [comment]
There is some possibility, but I would not say it's particularly likely.
Is this intermittent? If so, it could be due to earlier changes (build 2024)?

**Comment by RSalman** [comment]
Doesn't seem likely it's this change, I would expect to see the same issue on other platforms.

**Comment by pshipton** [comment]
@amicic it is somewhat intermittent, but happens quite often, in particular on the rh7-390 machines. As the OpenJ9 builds are working, I think we're limited to OMR changes which aren't yet accepted, limited to the first occurrance, which is https://github.com/eclipse/omr/compare/7a0b420...9a797cc

**Comment by pshipton** [comment]
There was also another hang in the latest OMR acceptance build.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OMR_testList_0/51/
```
06:51:55  Testing: evmoa001
06:51:55  Test start time: 2020/07/15 07:51:55 Atlantic Standard Time
06:51:55  Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OMR_testList_0/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xshareclasses:cacheRetransformed,name=retransformenabled -Xnocompressedrefs  -Xdump    -agentlib:jvmtitest=test:evmoa001 -cp "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_xl_OMR_testList_0/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
06:51:55  Time spent starting: 2 milliseconds
06:56:04  ***[TEST INFO 2020/07/15 07:55:55] ProcessKiller detected a timeout after 240000 milliseconds!***
06:56:04  INFO: getUnixPID() has failed indicating this is not a UNIX System.'Debug on timeout' is currently only supported on Linux.
06:56:04  Output from test:
Aborted by Peter Shipton
```

**Comment by RSalman** [comment]
Reverting change while I look into it. These changes look more suspicious than the other changes https://github.com/eclipse/omr/compare/7a0b420...9a797cc

**Comment by RSalman** [comment]
Confirmed that it's caused by this change, investigating further
