### ISSUE TITLE
Remove unnecessary use of getOptimizationPhaseIsComplete()

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#10180]
This is the only use of the `getOptimizationPhaseIsComplete()` query in OpenJ9 and it is asked in a place that is obviously after the optimizer has completed and well into the code generator.  Remove it and fold code assuming it answers `true`:

https://github.com/eclipse/openj9/blob/ee1f3d1ae159643f5cf8d3b3554224ee6282f082/runtime/compiler/z/codegen/InMemoryLoadStoreMarking.cpp#L55

The only place where the `OptimizerPhaseIsComplete` flag is set is in the LateSequentialConstantStoreSimplificationPhase, which runs before InMemoryLoadStoreMarking and will itself be eliminated.

**Comment by rudy2steiner** [comment]
Only need to remove if and assume always true?

**Comment by rudy2steiner** [comment]
please assign to me, i will try to clean up the code!

**Comment by 0xdaryl** [comment]
Thanks for offering to help out!  Yes, in the code linked above you should assume `getOptimizationPhaseIsComplete()` always returns true and you can fold the conditional accordingly.  Please be sure to read through the [Contributor Guidelines](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md) before your first PR, in particular the section on signing the ECA.

**Comment by 0xdaryl** [comment]
Oops.  I linked the OMR Contributor Guidelines above by mistake (the OpenJ9 CG is [here](https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md)), but the process for signing the ECA is the same in both.
