### ISSUE TITLE
Remove LateSequentialConstantStoreSimplification CodeGenerator phase

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#10181]
The only purpose of this CodeGenerator phase is to call `setOptimizationPhaseIsComplete()`.  In the code generator this must be true and this phase should be eliminated.  As a start, grep through the code for `LateSequentialConstantStoreSimplification` and delete/fold as appropriate.

**Note:** `getOptimizationPhaseIsComplete()` is queried in a couple places in the code and those must be folded first before this phase can be eliminated.  See eclipse/omr#5402 and #10180 which should be completed first.

**Comment by rudy2steiner** [comment]
I'd like to work on this and #10180
