### ISSUE TITLE
TestOpenJ9DiagnosticsMXBean hanging on cent7-x64-6

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10197]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/51
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/52
TestOpenJ9DiagnosticsMXBean
cent7-x64-6
```
00:56:55  [TestOpenJ9DiagnosticsMXBean] [INFO] Starting Remote Server to Monitor!
00:56:55  [TestOpenJ9DiagnosticsMXBean] [INFO] [/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/openjdkbinary/j2sdk-image/jre/bin/java, -Xdump:dynamic, -classpath, /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../../jvmtest/TestConfig/resources:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../TKG/lib/testng.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../TKG/lib/jcommander.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/openjdk-tests/TKG/../../jvmtest/functional/JLM_Tests/jlm_tests.jar, -Xint, -Xgcpolicy:optthruput, -Xnocompressedrefs, -Dcom.sun.management.jmxremote.port=9999, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Djava.lock.file=/tmp/tmp1613305794846300943.lock, org.openj9.test.java.lang.management.RemoteProcess]
Cancelling nested steps due to timeout
08:51:05  Sending interrupt signal to process
```

**Comment by pshipton** [comment]
@jdekonin seems there is a network setup issue on at least cent7-x64-6.

**Comment by pshipton** [comment]
Disabled the machine for now.

**Comment by jdekonin** [comment]
We'll need more information than that.  cent7-x64-5 and cent7-x64-6 should be identical to cent7-x64-4 from which they were cloned.  fyi @rajdeepsingh1

**Comment by pshipton** [comment]
I'm guessing the IP address of the machine is set incorrectly.

**Comment by rajdeepsingh1** [comment]
I don't see any issue with the IP address on cent7-x64-6 . I've rebooted the machine, let me know thanks @pshipton

**Comment by pshipton** [comment]
I've re-enabled the machine for the builds.

**Comment by pshipton** [comment]
Still happening https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly_testList_0/58/
I've disabled the machine again until we can figure this out. If nothing else, we could discard this machine and create a new one.

**Comment by rajdeepsingh1** [comment]
@pshipton machine has been rebuilt. I've also disabled ipv6 on the Cent7 machines to prevent any address conflicts. Enabled in Jenkins.

**Comment by pshipton** [comment]
Now seeing a similar problem on cent7-ppcle-5
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_xl_Nightly_testList_1/57/

Do we have a duplicate IP address?

**Comment by rajdeepsingh1** [comment]
Do not see any duplicate IPs, however I've now disabled ipv6 on cent7 machines. Let me know if there are any further issues @pshipton  thanks

**Comment by pshipton** [comment]
I haven't seen this again.
