### ISSUE TITLE
 cent7-x64-1 and  cent7-x64-3 offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10199]
`load pubkey "/run/secrets/jenkins/ssh/id_rsa.openj9": invalid format`

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
@rajdeepsingh1 can you please look into this, thanks.

**Comment by rajdeepsingh1** [comment]
Images are supposed to be created in /images instead of /instances in order to have ample space for the VMs to function. I'll move them over to /images on the hosts and they should be online. Updates to follow.

**Comment by rajdeepsingh1** [comment]
@pshipton This has been resolved. cent7-x64-1 and cent7-x64-3 are now online in Jenkins.
