### ISSUE TITLE
Docker Hub: wrong tag name shown for "x86_64-debianslim-jre"

### ISSUE THREAD

**Issue by ksilz** [eclipse/openj9#10204]
The Docker Hub page for [AdoptOpenJDK 11 OpenJ9](https://hub.docker.com/r/adoptopenjdk/openjdk11-openj9) shows a wrong tag name for the `x86_64-debianslim-jre`. It shows it with an `-jre`at the end that's wrong:

![Wrong Docker tag](https://user-images.githubusercontent.com/1061209/88045731-e77b7b00-cb46-11ea-924b-da714475c950.png)

The "Tags" tab has it right - no `-jre` at the end:

<img width="663" alt="Correct Docker tag" src="https://user-images.githubusercontent.com/1061209/88045959-40e3aa00-cb47-11ea-8c26-175fe2816687.png">

Pulling doesn't work either, as expected:

````
~/workspaces % docker pull adoptopenjdk/openjdk11-openj9:x86_64-debianslim-jre-11.0.8_10_openj9-0.21.0-jre                                                                  11:42:57
Error response from daemon: manifest for adoptopenjdk/openjdk11-openj9:x86_64-debianslim-jre-11.0.8_10_openj9-0.21.0-jre not found: manifest unknown: manifest unknown
~/workspaces %
````

**Comment by pshipton** [comment]
@dinogun fyi

**Comment by pshipton** [comment]
Actually @ksilz, I think this issue should be raised at the AdoptOpenJDK project. 
https://github.com/AdoptOpenJDK/openjdk-support or https://github.com/AdoptOpenJDK/openjdk-docker

**Comment by dinogun** [comment]
Fixed now, thanks !

**Comment by pshipton** [comment]
Awesome, thanks.
