### ISSUE TITLE
OpenJ9 version information contains "build 2.9"

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1020]
The java.vm.version system property contains 2.9, which doesn't make much sense for OpenJ9. The "2.9" also ends up in the system property java.fullversion. The -version output prints "build ${java.vm.version}"

**Comment by pshipton** [comment]
All the VM/JIT/GC shared libraries also use a 29 suffix.

**Comment by pshipton** [comment]
Note that changing this is not a trivial effort (but not major either). There is testing that expects the 2.9, or 29 shared library suffix which all needs to be fixed, although it should mostly use a variable.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you take a look a this?

**Comment by JasonFengJ9** [comment]
Working on it ...

**Comment by JasonFengJ9** [comment]
Discussed with @pshipton, the share library suffix are not going to be changed for now before a conclusion is reached about the new suffix via an issue.

**Comment by pshipton** [comment]
#1095 has been merged
