### ISSUE TITLE
Enabling JProfiling?

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#10201]
In the JIT, what is the intended use and interaction of the "enableJProfiling/disableJProfiling" options (both of which toggles the `TR_EnableJProfiling` flag) and the "disableJProfilingInProfilingCompilations" option (which toggles the `TR_DisableJProfilingInProfilingCompilations` flag)?

As far as I can tell, no platform enables JProfiling via the `TR_EnableJProfiling` flag (it is always disabled), yet JProfiling seems to be enabled because it is "not disabled" by the `TR_DisableJProfilingInProfilingCompilations` flag.  This seems like a confusing way of enabling this feature.  Just wondering if there is a higher purpose here and why the first flag isn't sufficient?

There are a small number of queries in the code on the `TR_EnableJProfiling` flag setting.  So even if JProfiling is "enabled" by the "disableJProfilingInProfilingCompilations" option, the "TR_EnableJProfiling" flag won't be set and hence those queries may not be answering correctly.

@r30shah

**Comment by r30shah** [comment]
@0xdaryl  `TR_EnableJProfiling` name is a misleading. Purpose for that option is to enable patchable instrumentation (Which is WIP atm). I opened up the issue to rename and refactor use of that to something else.
https://github.com/eclipse/omr/issues/4265. 

Right now in Profiling Compilation, JProfiling is enabled by default, and can be disabled by option `TR_DisableJProfilingInProfilingCompilations` . Profiling Compilations occurs at hot/very-hot opt level if optimizer sees a benefit by switching to profiling.  

I have WIP changes for Patchable Instrumentation that can be applied in other opt level methods.

**Comment by 0xdaryl** [comment]
Thanks, that helps.  Once that issue is complete, would `TR_DisableJProfilingInProfilingCompilations` be renamed to something simpler (like `TR_DisableJProfiling`) ?

**Comment by r30shah** [comment]
Yes, solution I have in mind is to replace `TR_DisableJProfilingInProfilingCompilations` with `TR_DisableJProfiling` and rename `TR_EnableJProfiling` to something which resonates with idea of patchable profiling.
