### ISSUE TITLE
Missing check of static jfield in Check:jni option

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10210]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------

OpenJ9's Check:jni debug feature does not properly check jfield (static) object when calling Get<'type'>Field and Set<'type'>Field JNI functions. 

For example, passing static fieldID when calling GetCharField JNI function does not cause any error on OpenJ9.
The program normally executed without any errors.

On the other hand, Hotspot 11 throws following error messages which seems better behavior.
```
FATAL ERROR in native method: Static field ID passed to JNI
```

It would be good if OpenJ9 also catch such buggy code.

Similar problem occurs on GetStatic<'type'>Field SetStatic<'type'>Field functions.
If non-static jfieldID is passed on GetStatic<'type'>Field SetStatic<'type'>Field functions,
Hotspot 11 throws below error message.
```
Non-static field ID passed to JNI
```

However, openj9 does not display errror messages.

Diagnostic files
----------------
[test5.zip](https://github.com/eclipse/openj9/files/4954999/test5.zip)

hotspot throws following error message.
```
java -Xcheck:jni -esa HelloJNI
FATAL ERROR in native method: Static field ID passed to JNI
        at HelloJNI.sayHello(Native Method)
        at HelloJNI.main(HelloJNI.java:14)
```
OpenJ9 does not throw error message.

**Comment by JasonFengJ9** [comment]
Will take this one as well.

**Comment by JasonFengJ9** [comment]
It appears there is no `static` type info within `jfieldID`.

@gacholio any insights about performing JNI check to detect mismatching `jfieldID`?

**Comment by gacholio** [comment]
The field shape within the ID has a modifiers field that can be checked.

**Comment by gacholio** [comment]
It may also be worth adding a couple of tests to verify the two new errors (instance field passed to static, static field passed to instance).
