### ISSUE TITLE
Functional test targets need updates to not fail against hotspot impls

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#10227]
There are test targets defined in the functional set of tests that need to be updated, either with:

-  `<impls>` section as they use openj9 specific command line options (-Xdump has been added to a bunch of test cases making the tests no longer able to be run against non-openj9 implementations 
OR
- in the case of the presence of -Xdump that is included in the `<command>` it could be placed in an OPENJ9_SPECIFIC_OPTIONS variable to keep more test targets generic enough for testing all implementations.  We need to ensure these tests can continued to be used against non-openj9 implementations.

Examples: 
[cmdLineTester_ProxyFieldAccess_SE80](https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/proxyFieldAccess/playlist.xml#L27) does not have a subset tag, but uses an openj9 specific tag (-Xdump), (target will try to run and [fail](https://github.com/AdoptOpenJDK/run-aqa/runs/900181367#step:4:2259))
[cmdLineTester_bootstrapMethodArgumentTest](https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/bootstrapMethodArgumentTest/playlist.xml#L27) included in jdk11 [fails](https://github.com/AdoptOpenJDK/run-aqa/runs/900181558#step:4:2601) against hotspot

[loadLegacyLibrary](https://github.com/AdoptOpenJDK/run-aqa/runs/908190215?check_suite_focus=true#step:4:2211) - jdk8/macOS/hotspot

**Comment by sophia-guo** [comment]
Thanks @smlambert will look into that.

**Comment by smlambert** [comment]
Latest [run-aqa](https://github.com/AdoptOpenJDK/run-aqa/actions) runs of functional tests against hotspot are all running green, so this issue can be closed.
