### ISSUE TITLE
Negative number is not checked in Check:jni option

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10231]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------
Passing negative number to EnsureLocalCapacity JNI function does not cause any errors.
For example, below function call does not cause any error, but executed normally.
```
(*env)->EnsureLocalCapacity(env,-5);
```

On the other hand, Hotspot throws below error message.
```
FATAL ERROR in native method: negative capacity
        at HelloJNI.sayHello(Native Method)
        at HelloJNI.main(HelloJNI.java:14)
Aborted (core dumped)
```
Similar issue occurs when negative number is passed to PushLocalFrame JNI function.
It would be good if OpenJ9 also catches mis-usage of negative numbers.

Diagnostic files
----------------

[test6.zip](https://github.com/eclipse/openj9/files/4967637/test6.zip)

**Comment by JasonFengJ9** [comment]
since I have been this area recently, will take this as well.
