### ISSUE TITLE
Reminder to re-enable Java 15 preview tests for Java 16

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#10243]
See https://github.com/eclipse/openj9/issues/10241#issuecomment-663617465

Currently the Jep360 test suite in functional/Java15andUp is running for Java 15 only, if this feature moves out of preview or onto 16 tests should also run on later Java versions.

**Comment by theresa-m** [comment]
This also applies to the Jep384 test suite for records preview.

**Comment by theresa-m** [comment]
This has been addressed by #10835

**Comment by pshipton** [comment]
#10835 was never merged.

**Comment by pshipton** [comment]
This should get resolved by https://github.com/eclipse/openj9/pull/11606

**Comment by pshipton** [comment]
JEP 360 tests have been enabled by https://github.com/eclipse/openj9/pull/11807

**Comment by pshipton** [comment]
Jep384Tests has been enabled by https://github.com/eclipse/openj9/pull/11678
