### ISSUE TITLE
XCheck:jni cannot detect non-throwable object

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10272]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------

OpenJ9's Xcheck:jni cannot detect non-throwable object in the situation where the object must be throwable.
For example, below code is error because java/lang/Object is not throwable. 
However, OpenJ9's Xcheck:jni does not throw any error message.

```
jclass class1;
class1 = (*env)->FindClass(env, "[Ljava/lang/Object;");
(*env)->ThrowNew(env,class1,"test")
```

On the other hand, Hotspot 11 shows below error message.
```
FATAL ERROR in native method: JNI Throw or ThrowNew received a class  
argument that is not a Throwable or Throwable subclass
```

Diagnostic files
----------------
[test7.zip](https://github.com/eclipse/openj9/files/4989259/test7.zip)

**Comment by JasonFengJ9** [comment]
Will have a look.
