### ISSUE TITLE
Missing checks on class descriptor when Xcheck:jni is enabled 

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10286]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------

It seems that OpenJ9's Xcheck:jni does not check class descriptor as incorrect descriptor is successfully passed to FindClass JNI function. Consider below code:
```
(*env)->FindClass(env, "Ljava/lang/Object;");
```

"Ljava/lang/Object;" is incorrect class descriptor as JNI specification stated as follow:
```
For example, the fully-qualified class name for the java.lang.String class is:
                   "java/lang/String"
```
reference : https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#wp9502

Hotspot 11 correctly detects incorrect class descriptor. 
Hotspot 11 shows below error message.
```
WARNING in native method: JNI FindClass received a bad class descriptor 
"Ljava/lang/Object;".  A correct class descriptor has no leading "L" or trailing ";".  
Incorrect descriptors will not be accepted in future releases.
```

However, OpenJ9 accepts incorrect class descriptor and does not throw error message.

Diagnostic files
----------------
[test8.zip](https://github.com/eclipse/openj9/files/4996122/test8.zip)

**Comment by gacholio** [comment]
@JasonFengJ9

**Comment by JasonFengJ9** [comment]
will take this one as well.

**Comment by JasonFengJ9** [comment]
> WARNING in native method: JNI FindClass received a bad class descriptor 

This is a warning message. By default `OpenJ9 -Xcheck:jni` only check/show fatal errors. With `-Xcheck:jni:warn`, `OpenJ9` shows following:
```
JVMJNCK059W JNI warning in FindClass: Argument #2 is a malformed identifier ("Ljava/lang/Object;")
JVMJNCK078W Warning detected in HelloJNI.sayHello()I
```

**Comment by sjmini** [comment]
@JasonFengJ9 
If IBM think it is enough to show warning for this buggy code, I am fine with it. Please close the issue.
