### ISSUE TITLE
JEP 358 NullPointerException messages enabled by default for jdk 15

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10296]
From OpenJDK 15 release notes.
"
Enable ShowCodeDetailsInExceptionMessages by default (JDK-8233014)
hotspot/runtime
The default of the flag ShowCodeDetailsInExceptionMessages was changed to 'true'. The helpful NullPointerException messages of JEP 358 are now printed by default. The messages contain snippets of the code where the NullPointerException was raised.

App deployers should double check the output of their web applications and similar usage scenarios. The NullPointerException message could be included in application error messages or be displayed by other means in the app. This could give remote attackers valuable hints about a potential vulnerable state of the software components being used.

An example message is 'Cannot read field "c" because "a.b" is null'. The attacker knows that field b of a contains null which might be unintended and offer an opportunity for an attack. For more details of what the message can contain see above mentioned JEP 358.
"

**Comment by pshipton** [comment]
@DanHeidinga fyi

**Comment by gacholio** [comment]
This is a terrible idea.

**Comment by DanHeidinga** [comment]
> This is a terrible idea.

Can you expand on that?

**Comment by gacholio** [comment]
We know exceptions are too often used for control flow in java - this will significantly slow down any thrown NPE.

**Comment by gacholio** [comment]
Not to mention the supposed security concern - that alone should make this off by default.

**Comment by JasonFengJ9** [comment]
> We know exceptions are too often used for control flow in java - this will significantly slow down any thrown NPE.

The cost of retrieving the extended NPE message applies when `NullPointerException.getMessage()` is invoked, otherwise it is same as previous Java version.
If such control flow does rely on NPE message instead of just NPE itself, yeah, there is an additional cost when the extended message is on by default.

**Comment by gacholio** [comment]
I guess if the exception is caught with no logging, there won't be any penalty.

**Comment by JasonFengJ9** [comment]
Recent `JDK15 java.lang. NullPointerException` change [1] caused `OpenJ9` unexpected NPE stacktrace. For a simple testcase `new NullPointerException("JDK15 NPE").printStackTrace()`:
```
java.lang.NullPointerException: JDK15 NPE
	at java.base/java.lang.NullPointerException.fillInStackTrace(NullPointerException.java:91)
	at java.base/java.lang.Throwable.<init>(Throwable.java:90)
	at java.base/java.lang.Throwable.<init>(Throwable.java:101)
	at java.base/java.lang.Exception.<init>(Exception.java:67)
	at java.base/java.lang.RuntimeException.<init>(RuntimeException.java:63)
	at java.base/java.lang.NullPointerException.<init>(NullPointerException.java:70)
	at a.se.java_lang_npe_jdk15.TestJDK15NPESimple.testAll(TestJDK15NPESimple.java:11)
```
Instead it should be as following:
```
java.lang.NullPointerException: JDK15 NPE
	at a.se.java_lang_npe_jdk15.TestJDK15NPESimple.testAll(TestJDK15NPESimple.java:11)
```

It appears `NullPointerException` overrides `java.lang.Throwable.fillInStackTrace()`, when `Throwable` constructor invokes `NullPointerException.fillInStackTrace()` which invokes `super.fillInStackTrace()`, however the child class instance is not initialized yet, hence NPE occurred there instead.
RI probably does instance initialization differently hence works w/o NPE though it doesn't seem a good practice to override parent class `Throwable` method `fillInStackTrace()` which invokes child class `NullPointerException.fillInStackTrace()` within its constructor.


[1] https://github.com/ibmruntimes/openj9-openjdk-jdk15/commit/ae40270b5b6058e455c10cc8d635cb9e78fd01ca

**Comment by JasonFengJ9** [comment]
Further about JDK15 `java.lang. NullPointerException` extra internal stacktrace frames above, I am going to propose skip those 6 java frames besides usual INL frame.
The code snippet looks like following:
```
#if JAVA_SPEC_VERSION >= 15
	J9Class *receiverClass = J9OBJECT_CLAZZ(_currentThread, receiver);
	if (receiverClass == _vm->nullPointerExceptionClass) {
		walkState->skipCount = 7;	/* skip the INL & constructor frames */
	}
#else /* JAVA_SPEC_VERSION >= 15 */
	walkState->skipCount = 1;	/* skip the INL frame */
#endif /* JAVA_SPEC_VERSION >= 15 */
```

**Comment by DanHeidinga** [comment]
Detailed NPE messages aren't going to make this release - moving out
