### ISSUE TITLE
jdk15 Lookup::defineClass should link the class

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10297]
From OpenJDK release notes.
"
Lookup::defineClass should link the class (JDK-8238195)
core-libs/java.lang.invoke
Lookup::defineClass is specified to throw LinkageError if a linkage error occurs, but the implementation was not actually linking the class. In this release, the implementation is changed to link the class before returning, so conforming to the specification. If Lookup::defineClass is called to define a class that fails linking, LinkageError will be thrown.
"

**Comment by pshipton** [comment]
@DanHeidinga fyi

**Comment by DanHeidinga** [comment]
Partially addressed by #10471.  Non-hidden classes are not yet handled

**Comment by DanHeidinga** [comment]
Likely needs a `J9VMInternals.prepare(theClass)` to be added
