### ISSUE TITLE
Missing NULL check leads to segmentation fault

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10318]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------
DefineClass JNI function receives a name of the class as a second argument.
However, a NULL value can be passed as a second argument when calling DefineClass, and this leads to segmentation fault.
OpenJ9 cannot detect the usage of NULL value even when the -Xcheck:jni is enabled.

It would be great if OpenJ9 throws an error message on such buggy code if -Xcheck:jni option is enabled.

**Comment by gacholio** [comment]
The JNI specification pretty much says "if you pass bad data, you'll crash", but I agree JNI check should be detecting as much as possible.

**Comment by JasonFengJ9** [comment]
Will take this.
