### ISSUE TITLE
Deleted references are not checked in Xcheck:jni feature

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10310]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------
GetObjectRefType JNI function returns the reference type of the java object.
The JNI specification stated that GetObjectRefType cannot be used on deleted references.
However, OpenJ9 accepts passing deleted reference to GetObjectRefType function.
The openJ9 cannot also detects the usage of deleted references even with the Xcheck:jni option is enabled.

On the other hand, hotspot's Xcheck:jni shows below error message.

```
FATAL ERROR in native method: Bad global or local ref passed to JNI 
```

Note that hotspot also allows deleted references to be passed to GetObjectRefType.
But, hotspot prevents usage of deleted reference only if -Xcheck:jni option is enabled.

Diagnostic files
----------------
[test9.zip](https://github.com/eclipse/openj9/files/5012266/test9.zip)

**Comment by gacholio** [comment]
There's no reliable way to detect this in normal mode, but JNI check could avoid freeing references for re-use and mark them as stale.

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by sjmini** [comment]
@JasonFengJ9 
It seems that OpenJ9 properly checks deleted object when SetObjectArrayElement function is used.
For example, if deleted object is passed as fourth argument of SetObjectArrayElement function, OpenJ9 throws error message.
```
JNI error in SetObjectArrayElement: Argument #4 (0x000000000120F950) is not a valid object reference. It's type is: freed local reference
```
Maybe similar approach can be adopted for GetObjectRefType function.
Hope this help.

**Comment by JasonFengJ9** [comment]
That's a good suggestion, @sjmini
