### ISSUE TITLE
jlink created jdk shows error of JVMJ9VM011W Unable to load j9vrb29

### ISSUE THREAD

**Issue by toshiona** [eclipse/openj9#10335]
Java -version output
--------------------

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200715_677 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)

Summary of problem
------------------

jlink created jdk shows an error at launching.

`JVMJ9VM011W Unable to load j9vrb29: dlopen(/Users/nakamuratoshio/Documents/java/work/myjava/lib/compressedrefs/libj9vrb29.dylib, 2): Library not loaded: @rpath/libj9shr29.dylib   Referenced from: /Users/nakamuratoshio/Documents/java/work/myjava/lib/compressedrefs/libj9vrb29.dylib   Reason: image not found`

Recreate steps
----------------
% jlink --add-modules jdk.charsets --output myjava
% myjava/bin/java -version
JVMJ9VM011W Unable to load j9vrb29: dlopen(/Users/nakamuratoshio/Documents/java/work/myjava/lib/compressedrefs/libj9vrb29.dylib, 2): Library not loaded: @rpath/libj9shr29.dylib   Referenced from: /Users/nakamuratoshio/Documents/java/work/myjava/lib/compressedrefs/libj9vrb29.dylib   Reason: image not found
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200715_677 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)

Environment
----------------
MacOSX Catalina 10.15.5

**Comment by ChengJin01** [comment]
I tried on Linux_X64 with the latest nightly build at https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-08-04-06-22/OpenJDK11U-jdk_x64_linux_openj9_2020-08-04-06-22.tar.gz and still ended up with pretty much the same failure as detected above:
```
 jdk_11_0_8_10_openj9/bin/java  -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10-202008032347)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-1c194db6e, JRE 11 Linux amd64-64-Bit Compressed References 20200803_718 (JIT enabled, AOT enabled)
OpenJ9   - 1c194db6e
OMR      - 7b76a160b
JCL      - 94b9d6d2c6 based on jdk-11.0.8+10)

$ jdk_11_0_8_10_openj9/bin/jlink  --add-modules jdk.charsets --output myjava

 myjava/bin/java -version
-----> JVMJ9VM011W Unable to load j9vrb29: libj9shr29.so: cannot open shared object file: No such file or directory
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10-202008032347)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-1c194db6e, JRE 11 Linux amd64-64-Bit Compressed References 20200803_718 (JIT enabled, AOT enabled)
OpenJ9   - 1c194db6e
OMR      - 7b76a160b
JCL      - 94b9d6d2c6 based on jdk-11.0.8+10)
```

**Comment by keithc-ca** [comment]
The problem seems to be that `j9vrb29` links against `j9shr29` (see [CMakeLists.txt](https://github.com/eclipse/openj9/blob/master/runtime/verbose/CMakeLists.txt#L68)): this problem does not occur in a UMA-based build.

There are other unwanted dependencies: the problematic ones are those that refer to libraries from one (optional) module to another that depends on the first module.

**Comment by sharon-wang** [comment]
As a temporary workaround, you can add `--add-modules openj9.sharedclasses` to the jlink command, i.e.
```
jlink --add-modules jdk.charsets --add-modules openj9.sharedclasses --output myjava
```
so that j9shr29 gets included in the image.
