### ISSUE TITLE
Crash running java -version 0.18.1 ppc64le on Cent7

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#10342]
Java -version output
--------------------

Output from `java -version`.

```
[jenkins@cent7-ppcle-6 ~]$ /usr/lib/jvm/adoptojdk-java-11/bin/java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux ppc64le-64-Bit Compressed References 20200122_428 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
```

Summary of problem
------------------

Crash running java -version during the configure step of a compile job
```
22:08:06  configure: Found potential Boot JDK using configure arguments
22:08:52  configure: Potential Boot JDK found at /usr/lib/jvm/adoptojdk-java-11 is incorrect JDK version (JVMDUMP039I Processing dump event "corruptcache", detail "" at 2020/08/05 23:08:04 - please wait.); ignoring
22:08:52  configure: (Your Boot JDK version must be one of: 10 11)
22:08:52  configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
22:08:52  configure exiting with result code 1
```

I see corrupt cache in the one javacore and gpf in the other

Diagnostic files
----------------

https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_Nightly/471/console
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_ppc64le_linux_Nightly/471/Build_JDK11_ppc64le_linux_Nightly-471-20200806-020453-diagnostics.tar.gz

**Comment by AdamBrousseau** [comment]
[javacore.20200805.230831.8712.0005.txt](https://github.com/eclipse/openj9/files/5032266/javacore.20200805.230831.8712.0005.txt)
[javacore.20200805.230804.8712.0002.txt](https://github.com/eclipse/openj9/files/5032267/javacore.20200805.230804.8712.0002.txt)

**Comment by AdamBrousseau** [comment]
Is this expected? Should I simply remove the javasharedresources directory?

**Comment by hangshao0** [comment]
The corruption is detected very early at the startup phase, over 600 JVMs has attached to it before. I guess it is an existing one on that machine, not a newly created one. 
Yes, you can remove the cache or javasharedresources directory, there is no point keeping an corrupted cache there.

**Comment by AdamBrousseau** [comment]
It was also interesting to me that it wasn't reproducible. I can close if there is no concern here.
