### ISSUE TITLE
JDK8 OpenJ9 Modded Minecraft 1.12 performance issue

### ISSUE THREAD

**Issue by gatoborrachon** [eclipse/openj9#10363]
I heard that with this JVM (https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9) i can improve a lot the performance, but with these arguments: 
-XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

i get a worse performance than the HotSpot JVM, why this happens?
the specs of my computer are in the screenshots

![2020-08-10_13 34 08](https://user-images.githubusercontent.com/61126174/89824871-5ed67600-db19-11ea-9af3-c8fdcaeeb667.png)
*HotSpot*
-----------------------------------------------------------------------------------------------------
![2020-08-10_11 29 36](https://user-images.githubusercontent.com/61126174/89824892-6433c080-db19-11ea-87fb-8fcca76a08bb.png)
*OpenJ9*
-----------------------------------------------------------------------------------------------------

**Comment by krolik-exe** [comment]
The flags you are using are made for HotSpot and have mostly no effect on OpenJ9. I suggest taking a look at this article below for some info regarding OpenJ9 tuning.



https://steinborn.me/posts/tuning-minecraft-openj9/

**Comment by gatoborrachon** [comment]
you are right, with this new arguments that i found it works better:

-XX:+UseG1GC -Xmx5G -Xms5G -XX:+UseStringDeduplication -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=50 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=2 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1HeapRegionSize=32M -Dsun.rmi.dgc.server.gcInterval=2147483646

![openj9 + nuevos args](https://user-images.githubusercontent.com/61126174/89954109-18a31480-dbf6-11ea-93ee-0e372e8f669a.png)
