### ISSUE TITLE
osx1011-x86-2 - UnsatisfiedLinkError: fontmanager

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10375]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/120/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:29:38  STATUS:Failed.`main' threw exception: java.lang.UnsatisfiedLinkError: fontmanager (dlopen(/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib, 2): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib Referenced from: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib Reason: Incompatible library version: libfontmanager.dylib requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0)
```

This is an infra issue.

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
Also osx1013-x86-4
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8/15

**Comment by jdekonin** [comment]
Ran a `brew update` on each of these systems; osx1011-x86-1, osx1011-x86-2, osx1013-x86-3 and osx1013-x86-4

We'll see if that makes a difference.

**Comment by jdekonin** [comment]
Appears that didn't resolve anything.

```
Incompatible library version: libfontmanager.dylib requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0
```

I suspect we might need to either (a) have a precompiled freetype version on the system or (b) add a pull and compile of a fixed freetype version as part of the compile.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/154/
