### ISSUE TITLE
Cannot find symbol "method dataEA()" relating to J9UTF8Pointer

### ISSUE THREAD

**Issue by austin0** [eclipse/openj9#10418]
Assuming this is related to https://github.com/eclipse/openj9/pull/10404 @gacholio 

Failure link
------------

Compilation failed for two AIX builds:

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-openj9/202/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-aix-ppc64-openj9/7/console

Failure output
---------------------------------------------
```
05:11:12  /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-aix-ppc64-openj9/workspace/build/src/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/pointer/helper/J9UTF8Helper.java:38: error: cannot find symbol
05:11:12  		utf8pointer.dataEA().getBytesAtOffset(0, buffer);
05:11:12  		           ^
05:11:12    symbol:   method dataEA()
05:11:12    location: variable utf8pointer of type J9UTF8Pointer
05:11:12  /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-aix-ppc64-openj9/workspace/build/src/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/VmCheckCommand.java:498: error: cannot find symbol
05:11:12  		U8Pointer utf8Data = utf8.dataEA();
05:11:12  		                         ^
05:11:12    symbol:   method dataEA()
05:11:12    location: variable utf8 of type J9UTF8Pointer
05:11:16  Note: Some input files additionally use or override a deprecated API.
05:11:16  Note: Some input files additionally use unchecked or unsafe operations.
05:11:16  2 errors
```

**Comment by gacholio** [comment]
@keithc-ca Some problem with parsing FAM on AIX?

**Comment by keithc-ca** [comment]
Silly me for assuming AIX would play nice. :-(

**Comment by keithc-ca** [comment]
My guess is that the compiler is simply omitting the debug information for empty arrays and do `ddrgen` can't know to generate the `data` and `dataEA` methods. I'll have to investigate to confirm.
