### ISSUE TITLE
How to build openj9 core

### ISSUE THREAD

**Issue by rudy2steiner** [eclipse/openj9#10417]
I'm new to oepnj9 and try to build it,with following command :
```
 cmake -DBOOT_JDK=/export/installment/bootjdk/bootjdk8 ..
```
but get some exception:

```
CMake Error at runtime/cmake/options.cmake:23 (include):
  include could not find load file:

    OmrAssert
Call Stack (most recent call first):
  runtime/CMakeLists.txt:38 (include)


CMake Error at runtime/cmake/options.cmake:34 (omr_assert):
  Unknown CMake command "omr_assert".
Call Stack (most recent call first):
  runtime/cmake/options.cmake:52 (j9vm_shadowed_option)
  runtime/CMakeLists.txt:38 (include)


-- Configuring incomplete, errors occurred!
```

so how to build the openj9 core independently!
OS: macOS 10.13.1

**Comment by rudy2steiner** [comment]
@0xdaryl would you mind giving me some guide

**Comment by rudy2steiner** [comment]
And how to join openj9.slack.com, who can invite me: rudy_steiner@163.com

**Comment by smlambert** [comment]
The "[Join Openj9 Slack link](https://openj9.slack.com/join/shared_invite/enQtNDU4MDI4Mjk0MTk2LWVhNTMzMGY1N2JkODQ1OWE0NTNmZjM4ZDcxOTBiMjk3NGFjM2U0ZDNhMmY0MDZlNzU0ZjAyNzQ1ODlmYjg3MjA#/)" can be found on openj9.org (but I hyperlinked it in this comment for convenience).

Are you following the build instructions from the readme's found in this doc directory, https://github.com/eclipse/openj9/tree/master/doc/build-instructions for your build trial and getting stuck at a particular stage?

**Comment by DanHeidinga** [comment]
@rudy2steiner typically a build starts from the "Extensions" repos which are a clone of the OpenJDK code with minimal changes to support the OpenJ9 JVM and uses the same build process as the rest of OpenJDK.  Shelley's link above provides details.

Cmake is only used in the background to compile the OpenJ9 part of the build. It's triggered by running `make` after doing the OpenJDK `configure`.

**Comment by smlambert** [comment]
I believe there is also a script that helps set up a docker based build here: https://github.com/eclipse/openj9/blob/master/buildenv/docker/mkdocker.sh that may be useful (at least as reference, if not to use outright).

**Comment by rudy2steiner** [comment]
I intend to build only openj9，not include openjdk，using https://github.com/eclipse/openj9/blob/master/CMakeLists.txt ，but failed with the exception.

**Comment by DanHeidinga** [comment]
Building openj9 on its own isn't a typical usecase as it needs class libraries, launchers, etc to be fully functional JDK.

If you can expand on your usecase, we may be able to help point you in the right direction

**Comment by rudy2steiner** [comment]
> Building openj9 on its own isn't a typical usecase as it needs class libraries, launchers, etc to be fully functional JDK.
> 
> If you can expand on your usecase, we may be able to help point you in the right direction

ok，thanks！in case，we only make trivial changes，if we can build and test it only with some necessary dependencies，it would be more easy to understand.

**Comment by DanHeidinga** [comment]
We use incremental builds in that case.  The base code is compiled to start with and as you make changes, you rebuild the code periodically and continue to test it.  The subsequent builds should be fairly fast

**Comment by rudy2steiner** [comment]
> We use incremental builds in that case. The base code is compiled to start with and as you make changes, you rebuild the code periodically and continue to test it. The subsequent builds should be fairly fast

ok i will try it later，thanks again！
