### ISSUE TITLE
macOS: JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata.  200M requested

### ISSUE THREAD

**Issue by kgibm** [eclipse/openj9#10416]
Java -version output
--------------------

$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200728_646 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)

Summary of problem
------------------

Reviewed issues #3795 and #3861 but I just downloaded the latest macOS JDK release (20200728) and still have the issue. Running with the "Large Heap" JDK does not have the problem.

Diagnostic files
----------------

Reproduction steps (for IBMers only; I've only seen this with GCMV so far):

```
$ cd /tmp
$ git clone git@github.ibm.com:runtimes/gcmv.git
[...]
$ cd gcmv
$ git fetch origin pull/5/head:tycho
[...]
$ git checkout tycho
[...]
$ cd gcmv.target
$ mvn clean install
[...]
$ cd ../gcmv.build
$ mvn clean install
[...]
$ cd ../gcmv.repository/target/products/
$ tar xzf com.ibm.java.diagnostics.visualizer.product-macosx.cocoa.x86_64.tar.gz
$ cd Eclipse.app/Contents/MacOS 
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200728_646 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
$ ./gcmv
JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata.  200M requested
$ export PATH=/Users/kevinaccount/Downloads/largeheap/jdk8u265-b01/Contents/Home/bin/:${PATH}
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Mac OS X amd64-64-Bit 20200728_470 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
$ ./gcmv                                                                                          
[Works]
```

I don't think this is GCMV-related because I can run the Linux build with compressed references.

My macOS: Mac OS X 10.15.6 (Build 19G73)

**Comment by dmitripivkine** [comment]
OSX assigns system `pagezero` (low virtual memory range) size 4GB by default. But Compressed Refs JVM needs this memory to allocate Suballocator default size is 200 MB so it is exactly what you observe.
So to prevent this an application should be built with `-pagezero_size 0x1000` option for Linker. It assigns `pagezero` to 4K.
See https://github.com/eclipse/omr/blob/2f7db34f45d5825579b194ae192f2824a11912e3/cmake/modules/platform/os/osx.cmake#L35

**Comment by kgibm** [comment]
@dmitripivkine Interesting, thank you. So you think this is something in the Eclipse build process?

**Comment by dmitripivkine** [comment]
> @dmitripivkine Interesting, thank you. So you think this is something in the Eclipse build process?

Probably. I am not familiar how all this thing builds together but seems when executable binary has been linked this option was missed

**Comment by kgibm** [comment]
@dmitripivkine That makes sense, I'll investigate on the Eclipse side. Thank you so much!
