### ISSUE TITLE
Change default branch for openj9-omr to openj9

### ISSUE THREAD

**Issue by Hello71** [eclipse/openj9#10423]
```
/tmp/portage/dev-java/openj9-openjdk-15.9999/work/openj9-openjdk-jdk15/build/linux-x86_64-server-release/vm/compiler/../compiler/codegen/CodeGenGPU.cpp:1284:39: error: static assertion failed: Number of elements in nvvmOpCodeNames does not match the value of TR::NumIlOps
 1284 | static_assert(sizeof(nvvmOpCodeNames) == (TR::NumIlOps*sizeof(char*)), "Number of elements in nvvmOpCodeNames does not match the value of TR::NumIlOps");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I guess this was caused by https://github.com/eclipse/openj9-omr/commits/master/compiler/optimizer/OMRSimplifierTableEnum.hpp, but those changes were made 6 days ago, so I'm not sure why they haven't been caught by CI since then?

**Comment by Hello71** [comment]
ah, I was misled by the fact that openj9-omr's default branch is master, not openj9. maybe that should be changed?

**Comment by gacholio** [comment]
master is a direct mirror of OMR master - the openj9 branch is updated from master once the code has been verified through the builds.

**Comment by 0xdaryl** [comment]
This will very likely be fixed after the next successful OMR Acceptance build.  #10388 was just merged which I believe may be the source of the error.

**Comment by Hello71** [comment]
> master is a direct mirror of OMR master - the openj9 branch is updated from master once the code has been verified through the builds.

right, I'm saying that I just went to https://github.com/eclipse/openj9-omr and assumed that that was the openj9 omr code (since I remembered that it is *not* at https://github.com/eclipse/omr), but in fact it is at https://github.com/eclipse/openj9-omr/tree/openj9. I'm suggesting that the default branch (HEAD) should be changed to openj9, to avoid some confusion for future users, even if minor. I think it will not affect developers, because as the repo description says, "PRs should be opened against the upstream OMR project whenever possible."

**Comment by Hello71** [comment]
> This will very likely be fixed after the next successful OMR Acceptance build. #10388 was just merged which I believe may be the source of the error.

I see that now, thanks!

**Comment by gacholio** [comment]
@jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
I don't think changing the default branch will cause any infra/build issues so I have no objections but we'd have to keep an eye out. I think it would be up to the team leads to make a decision and we'd have to raise it with the Eclipse Admins since committers don't have permissions change it.

**Comment by DanHeidinga** [comment]
I don't have an issue with changing the default branch to openj9.  @AdamBrousseau if you open a bugzilla, I'll +1 it

**Comment by AdamBrousseau** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566231

**Comment by DanHeidinga** [comment]
Closing as the default branch has been updated
