### ISSUE TITLE
[Proposal] Create an "openj9-utils" repo for utility programs not yet part of an OpenJ9 release

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#10444]
There have been various discussions with groups that have developed useful tools and utilities for working with classes, jar files, modules, etc. that need a common place for continued collaborative development.

I propose we create a new OpenJ9 repo (tentatively named: `openj9-utils`) to hold these tools as an interim home for them.  Tools may end up with this new repo as their long term home or they may grow into something that should be delivered as a part of the regular OpenJ9 builds.  In the later case, they would likely migrate to the `openj9` repo.

This lowers the barrier to accept code contributions to the project that may not have yet demonstrated their "fit" to the regular OpenJ9 builds and allows community to form around these utilities and continue their development while finding their final forms.

As an example, the tool presented during last Wednesday's OpenJ9 Community call would be good fit for this repo.

If there are no objections before the Aug 26 community call, I'd like to discuss there and move forward with the creation of this repo. 

Please voice any concerns in this issue or during the call.

**Comment by DanHeidinga** [comment]
Raised bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566420

**Comment by pshipton** [comment]
Repo is created https://github.com/eclipse/openj9-utils
