### ISSUE TITLE
OpenJ9 JVM terminates with Illegal instruction - AIX 7200-04-01-1939 (even java -version)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10448]
Copied from https://github.com/AdoptOpenJDK/openjdk-support/issues/166

Summary
======
In our AIX environment the OpenJ9 JVM will (in some scenarios) refuse to run if max heap size is default, or set too high.
This affects 11.0.6, 11.0.7 and 11.0.8 OpenJ9 JVM.

Hotspot JVM 11.0.7 and Java 8 does not seem to exhibit this behaviour.

Steps to reproduce
============
Here is where it gets tricky. I don't have a reproducable case for you because it seems isolated to one specific LPAR (for now).

I will also mention we are awaiting to get IBM Runtime for business support on this but it is a few weeks away.

We are using Progress Openedge software, and with their version 12.2 they no longer supply the jdk. Any AdoptOpenJdk version 11 is certified to work with it. We have been running this with 11.0.7 Hotspot JVM for a few months without trouble.

We have two nodes in this cluster, and it only seems to affect one of the nodes (for now) - a failover to the other node does allow the software and java to be run without apparent issues. We have other clusters running on the same IBM hardware in other LPARs running other Progress Openedge versions using Java8 (see -version below) and we have never seen a jvm crash like this.

Trying to run java -version
```
$ java/bin/java -version
openjdk version "11.0.8" 2020-07-14Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=0000001e
Handler1=09001000A05775D0 Handler2=09001000A04C4828
R0=00000000FFFF0C72 R1=00000100255CABF0 R2=000000000000002A R3=00000007FFF86390
R4=000000003002EE00 R5=0000000000000015 R6=0000000000000015 R7=0000000000000000
R8=00000007FFF86390 R9=00000000FFF86380 R10=0000000000000000 R11=0000000000000038
R12=0000000022000222 R13=00000100255D5800 R14=000000003016CA80 R15=000000003016CE00
R16=00000100246E4578 R17=FFFFFFFFFFFFFFFF R18=00000100255CAE40 R19=0000000080000007
R20=0900000001223E2C R21=09001000A04CF4D8 R22=00000100255CAED0 R23=09001000A04C5308
R24=0900000001172312 R25=0000000000000003 R26=0000000000000000 R27=0000000000000001
R28=0000000000000015 R29=00000007FFF86308 R30=00000007FFF86380 R31=0000000000000015
IAR=0000010013ACC9B4 LR=0900000001451EEC MSR=A00000000200D032 CTR=0000010013ACC854
CR=840002220000000C FPSCR=8202000000000000 XER=0000000C82020000
FPR0 0000000000000055 (f: 85,000000, d: 4,199558e-322)
FPR1 c3e0000000000000 (f: 0,000000, d: -9,223372e+18)
FPR2 3fc734b81082677c (f: 276981632,000000, d: 1,812964e-01)
FPR3 3f50546e40000000 (f: 1073741824,000000, d: 9,966923e-04)
FPR4 bf90ecf58ddc7f4a (f: 2380037888,000000, d: -1,652893e-02)
FPR5 40a6b00000000000 (f: 0,000000, d: 2,904000e+03)
FPR6 4070b2e1c3abb439 (f: 3282809856,000000, d: 2,671801e+02)
FPR7 bfb62e42fefa4000 (f: 4277813248,000000, d: -8,664340e-02)
FPR8 3f6069c0ff9e20ca (f: 4288553216,000000, d: 2,003552e-03)
FPR9 402f22a87ca8fb20 (f: 2091449088,000000, d: 1,556769e+01)
FPR10 412e848000000000 (f: 0,000000, d: 1,000000e+06)
FPR11 43300000000f4240 (f: 1000000,000000, d: 4,503600e+15)
FPR12 4530000000000000 (f: 0,000000, d: 1,934281e+25)
FPR13 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR14 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR15 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR16 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR17 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR18 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR19 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR20 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR21 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR22 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR23 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR24 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR25 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR26 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR27 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR28 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR29 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR30 0000000000000000 (f: 0,000000, d: 0,000000e+00)
FPR31 0000000000000000 (f: 0,000000, d: 0,000000e+00)

Compiled_method=java/lang/String.([BIIZZ)V]
Target=2_90_20200715_695 (AIX 7.2)
CPU=ppc64 (16 logical CPUs) (0x1e00000000 RAM)
----------- Stack Backtrace -----------
runJavaThread+0x1d4 (0x0900000000FF2338 [libj9vm29.so+0x6c338])
javaProtectedThreadProc+0x11c (0x0900000000F88AA0 [libj9vm29.so+0x2aa0])
omrsig_protect+0x488 (0x090000000125544C [libj9prt29.so+0x5744c])
javaThreadProc+0x68 (0x0900000000F8888C [libj9vm29.so+0x288c])
thread_wrapper+0x33c (0x0900000000C1B700 [libj9thr29.so+0x4700])
_pthread_body+0xe8 (0x09000000005AEFEC [libpthreads.a+0x3fec])
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/08/19 22:57:49 - please wait.
```
However if i run it with a smaller max heap size - it works fine:
```
$ java -Xmx1g -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 AIX ppc64-64-Bit Compressed References 20200715_695 (JIT enabled, AOT enabled)
OpenJ9 - 34cf4c075
OMR - 113e54219
JCL - 95bb504fbb based on jdk-11.0.8+10)
```
Now - it needs more details.. the cluster has nothing running on it after a failover to the other cluster node. The node has 120GB ram on it and ~66GB is reported by nmon in use - there was a lot of left over semaphores on the system.

We started up our software using the hotspot jvm (11.0.7) and ram usage up to ~95% - leaving about 5GB free.
We checked some semaphores that earlier was unmatched and they now have a PID attached, so reuse? We did not clear any semaphores before starting up the software using the Hotspot JVM

It has internally been suggested that the JVM crashing could be related to the continuity of available RAM segments.

Now, after all this - we tried the OpenJ9 JVM (both 11.0.7 and 11.0.8) - this is after 160-170 processes of the software has been started and the avaiable ram on the LPAR is < 10 GB.
```
$ jdk-11.0.7+10/bin/java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 AIX ppc64-64-Bit Compressed References 20200428_580 (JIT enabled, AOT enabled)
OpenJ9 - 05fa2d3
OMR - d4365f3
JCL - 838028f based on jdk-11.0.7+10)

$ jdk-11.0.8+10/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 AIX ppc64-64-Bit Compressed References 20200715_695 (JIT enabled, AOT enabled)
OpenJ9 - 34cf4c075
OMR - 113e54219
JCL - 95bb504fbb based on jdk-11.0.8+10)
```
Does any of this make any sense to anyone?

Expected results
==========
Actual results
=========
Triaging info
========
Java version: OpenJ9 11.0.6, 11.0.7, 11.0.8

What is your operating system and platform? AIX 7200-04-01-1939 on Power9

How did you install Java? gunzip and tar xvf from the adoptopenjdk.net site.

Did it work before? No.

Did you test with other Java versions? Yes, see above.

**Comment by pshipton** [comment]
@gita-omr pls take a look.

**Comment by matsremman** [comment]
Hello, i'm the poster of this issue in AdoptOpenJDK. We'll be trying to answer any question you might have, and supply any additional information you may require. We're in the process of upgrading our software stack, and we are waiting for the IBM Support for Runtime to be signed, so we can pursue the issue from that angle as well if that makes any difference.

**Comment by gita-omr** [comment]
@matsremman thanks for all the info. Would it be possible to get:

1) system core file
2) tracefile generated by adding this option: -Xjit:'{java/lang/String.([BIIZZ)V]}(traceFull),log=tracefile.txt'

**Comment by matsremman** [comment]
I will try to get the environment available for downtime and see if i can recreate it. I don't have any existing system core files, but i do believe we have some jitdump files from earlier (these are from version 11.0.6 but it's the same symptoms of illegal instruction). Would these be of interest/help until we can get fresh ones?

**Comment by gita-omr** [comment]
@matsremman , yes, please provide those jitdumps meanwhile.

**Comment by matsremman** [comment]
[3x_jitdumps.zip](https://github.com/eclipse/openj9/files/5134942/3x_jitdumps.zip)
Here's 3 jit dumps

**Comment by gita-omr** [comment]
Consulting with experts but I afraid these jitdumps don't tell me much since they contain traces not for the method that crashed. I think core and a tracfile will be more useful.

**Comment by matsremman** [comment]
We managed to get the system in a state where we can reproduce the illegal instruction. Java -version still works but once it's called through the software it's crashing (in a different method call):

Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=0000001e
Handler1=09001000A05FD5D0 Handler2=09001000A05D5828
...
Compiled_method=java/util/Hashtable.addEntry(ILjava/lang/Object;Ljava/lang/Object;I)V
Target=2_90_20200715_695 (AIX 7.2)
CPU=ppc64 (16 logical CPUs) (0x1e00000000 RAM)
----------- Stack Backtrace -----------
sendLoadClass+0x1a8 (0x0900000003270ACC [libj9vm29.so+0x66acc]).

I'm working on trying to get the necessary information out of this.
I have core.xxxx.dmp files (350MB each), javacore files, jitdumps are 1kb so i need to try to get the -Xjit info proper, and Snap.xxx.trc files. I'm not sure which of these i can safely upload to a public space.

**Comment by matsremman** [comment]
Progress Openedge runs with a custom jvmStart - i checked the script and extracted the exact command:

/path/progress/dlc/bin/jvmStart -w /path/tmp/prowrk -a /path/progress/dlc/properties/AdminServerPlugins.properties::PluginPolicy.Progress.ProAdsv /path/progress/java/bin/java -Xjit:'{java/util/Hashtable.addEntry(ILjava/lang/Object;Ljava/lang/Object;I)V}(tracefull),log=/path/tmp/prowrk/tracefileXjit.txt' -DInstall.Dir=/path/progress/dlc -DWork.Dir=/path/tmp/prowrk -Dlogback.configurationFile=/path/progress/dlc/properties/oeauth-logback-settings.xml -Djvmstart.debug=0 -Djava.command=java -Dadmsrv.jvm=/path/progress/java/bin/java com.progress.chimera.adminserver.AdminServerType

I added the -Xjit:'' but it does not generate anything in the tracefiles:
tracefileXjit.txt.40632736.59184.20200827.221304.40632736
<?xml version="1.0" standalone="no"?>
<jitlog>

I might be doing it wrong.

Originally the script has -o stderr -m silent in the script - when i run it with that my terminal was repeatedly flooded with the following text:

000000003000E700: Object neither in heap nor stack-allocated in thread main
000000003000E700:       O-Slot=00000000300B8170
000000003000E700:       O-Slot value=0000000000017801
000000003000E700:       PC=0A000100076C8D61
000000003000E700:       framesWalked=0
000000003000E700:       arg0EA=00000000300F3F60
000000003000E700:       walkSP=00000000300F3F20
000000003000E700:       literals=00000000300910A0
000000003000E700:       jitInfo=0000000000000000
000000003000E700:       method=00000000300910A0 (java/util/Hashtable.rehash()V) (Interpreted)
000000003000E700:       stack=00000000300EE6E8-00000000300F45F0
000000003000E700: Object neither in heap nor stack-allocated in thread main
000000003000E700:       O-Slot=00000000300B8168
000000003000E700:       O-Slot value=09001000A05DE0B0
000000003000E700:       PC=0A000100076C8D61
000000003000E700:       framesWalked=0
000000003000E700:       arg0EA=00000000300F3F60
000000003000E700:       walkSP=00000000300F3F20
000000003000E700:       literals=00000000300910A0
000000003000E700:       jitInfo=0000000000000000
000000003000E700:       method=00000000300910A0 (java/util/Hashtable.rehash()V) (Interpreted)
000000003000E700:       stack=00000000300EE6E8-00000000300F45F0

I'm going to try to see if i can provoke this error in other ways as well.

**Comment by fjeremic** [comment]
That method looks totally bogus by the way:

> Compiled_method=java/lang/String.([BIIZZ)V]

That is not a valid method signature, so something weird is going on.

**Comment by fjeremic** [comment]
I just hopped on a quick call after an invite from @matsremman via the OpenJ9 Slack. We debugged the issue live since it was so reproducible. We started off by isolating this to being a JIT issue (`-Xint`). The `-Xjit:verbose` log sowed a bunch of JIT compiles along with a bunch of AOT loads. AOT is always suspicious to me so next thing we did is verify there is an existing shared class cache in his home directory and afterwards we ran with `-Xnoaot` which did not exhibit the problem.

This isolates the issue to an AOT load problem. I'm not sure why the problem occurred symptom wise, but we cleared the cache via `-Xsharedclasses:destroyAll` and re-ran to re-populate the cache. The issues then went completely away.

I spoke to Mats and his associate about their environment and use case for the JVM. It sounded like startup performance was not important or relevant to them at all. My recommendation therefore was to continue using the JVM normally (with shared class cache + AOT enabled) for now and look out for these problems in the next two weeks. If all is well then things can continue. If problems arise again they have a workaround via `-Xshareclasses:none -Xnoaot` and we can further investigate the issue.

For determining the cause of the original problem we would require the system core file which may contain sensitive information and would have to go through the proper service channels. It should be fairly straightforward to identify the instruction sequences which caused the issues. Some further AOT tracing may be required then. I leave this to the service folks if such a service ticket gets created.

@matsremman if all this sounds reasonable feel free to close off the issue.

**Comment by gita-omr** [comment]
> 
> 
> That method looks totally bogus by the way:
> 
> > Compiled_method=java/lang/String.([BIIZZ)V]
> 
> That is not a valid method signature, so something weird is going on.

Yes, just wanted to say the same. No need to use the -Xjit option I suggested above. Unlikely it will produce anything.

**Comment by matsremman** [comment]
I agree this issue can be closed, but i would like to know how to raise an issue to get a service ticket so we can provide core files (we have a few of these).

**Comment by pshipton** [comment]
> i would like to know how to raise an issue to get a service ticket so we can provide core files (we have a few of these).

That is outside of the scope of the Eclipse OpenJ9 open source project, please directly contact the company you have a support contract with.

**Comment by matsremman** [comment]
Ok, i'll wait for our support contract to be finalized and then raise an issue and refer to this issue. Thanks for your help.
