### ISSUE TITLE
jdk8 acceptance failing to compile ExtendedOptionsImpl.c on AIX

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10452]
This is blocking the JDK8 acceptance build. 

The build failure is due to https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/2a70fb17f0364949ed86460d11c06a6e42d4e2d2

https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_OpenJDK8/55
```
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 467.47: 1506-045 (S) Undeclared identifier TCP_KEEPCNT.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 467.60: 1506-045 (S) Undeclared identifier SOCK_OPT_LEVEL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 479.38: 1506-276 (S) Syntax error: possible missing ')'?
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 478.47: 1506-045 (S) Undeclared identifier SOCK_OPT_NAME_KEEPIDLE.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 478.71: 1506-045 (S) Undeclared identifier SOCK_OPT_LEVEL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 489.47: 1506-045 (S) Undeclared identifier TCP_KEEPINTVL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 489.62: 1506-045 (S) Undeclared identifier SOCK_OPT_LEVEL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 500.46: 1506-045 (S) Undeclared identifier TCP_KEEPCNT.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 500.59: 1506-045 (S) Undeclared identifier SOCK_OPT_LEVEL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 512.45: 1506-276 (S) Syntax error: possible missing ')'?
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 511.46: 1506-045 (S) Undeclared identifier SOCK_OPT_NAME_KEEPIDLE.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 511.70: 1506-045 (S) Undeclared identifier SOCK_OPT_LEVEL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 522.46: 1506-045 (S) Undeclared identifier TCP_KEEPINTVL.
05:46:53  "/home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/jdk/src/solaris/native/java/net/ExtendedOptionsImpl.c", line 522.61: 1506-045 (S) Undeclared identifier SOCK_OPT_LEVEL.
05:46:53  gmake[2]: *** [lib/NetworkingLibraries.gmk:62: /home/jenkins/workspace/Build_JDK8_ppc64_aix_OpenJDK8/build/aix-ppc64-normal-server-release/jdk/objs/libnet/ExtendedOptionsImpl.o] Error 1
```

**Comment by DanHeidinga** [comment]
See https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/438

**Comment by DanHeidinga** [comment]
And @keithc-ca's PR: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/440 which we chose not to merge as OpenJDK had a fix in progress - https://bugs.openjdk.java.net/browse/JDK-8251546 - which appears to have been merged ~8 hours ago

**Comment by JasonFengJ9** [comment]
There is no new OpenJDK8 acceptance build yet at https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK8-Acceptance/. Does the mirror job need a kick?

**Comment by pshipton** [comment]
New content is only merged when there is a new build level. We are at jdk8u272-b04, so if the change gets into jdk8u272-b05, we'll get the change when this level is available. Discussed a plan to wait until Wed Sep 2 for this new level to appear, and if it doesn't appear then @keithc-ca will fix it manually.

**Comment by keithc-ca** [comment]
The compile errors on AIX and OSX seem to be fixed, however, there is a new issue on Linux which #10496 should fix.

Also, there's a test failure on OSX:
```
22:51:59  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.UnsatisfiedLinkError: fontmanager (dlopen(/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib, 2): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib Referenced from: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib Reason: Incompatible library version: libfontmanager.dylib requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0)
```
It's not immediately clear to me whether the solution is to simply upgrade the version of `libfontmanager.dylib`.

**Comment by JasonFengJ9** [comment]
> 22:51:59  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.UnsatisfiedLinkError: fontmanager (dlopen(/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib, 2): Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib Referenced from: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_OpenJDK8/openjdkbinary/j2sdk-image/jre/lib/libfontmanager.dylib Reason: Incompatible library version: libfontmanager.dylib requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0)
It's not immediately clear to me whether the solution is to simply upgrade the version of libfontmanager.dylib.

This is a machine specific issue as per https://github.com/eclipse/openj9/issues/10375

**Comment by keithc-ca** [comment]
New content from upstream fixed this problem; see https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_OpenJDK8/56/.
