### ISSUE TITLE
Crash in Eclipse IDE with Sonarlint plugin

### ISSUE THREAD

**Issue by calle2010** [eclipse/openj9#10472]
Java -version output
--------------------

    openjdk version "11.0.8" 2020-07-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
    Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 
    20200715_679 (JIT enabled, AOT enabled)
    OpenJ9   - 34cf4c075
    OMR      - 113e54219
    JCL      - 95bb504fbb based on jdk-11.0.8+10)

Summary of problem
------------------

I run Eclipse IDE on OpenJ9 with class sharing enabled. When I execute a Sonarlint Analysis on a project Eclipse crashes. Without class sharing the analysis works without issues.

Both crashes are in the same module and offset according to javacore file:

    1XHEXCPMODULE  Module: C:\Apps\openj9-11\bin\compressedrefs\j9vm29.dll
    1XHEXCPMODULE  Module_base_address: 00007FF9EFB70000
    1XHEXCPMODULE  Offset_in_DLL: 000000000001C750

Diagnostic files
----------------

Files for two crashes are attached. I can share the dmp files privately if required.

[dump.20200827.174543.19800.zip](https://github.com/eclipse/openj9/files/5137585/dump.20200827.174543.19800.zip)
[dump.20200827.172635.13808.zip](https://github.com/eclipse/openj9/files/5137586/dump.20200827.172635.13808.zip)

**Comment by calle2010** [comment]
Between the two crashes I destroyed the class cache. After destroying the cache I started Eclipse ran the analysis, stopped it and then did the same again. The crash happened on the second run.

Also worth noting that this crash doesn't happen on AdoptOpenJDK Hotspot 11.0.8.

**Comment by pshipton** [comment]
@calle2010 pls share a core dump with @hangshao0 privately.

**Comment by calle2010** [comment]
I've sent an email.

**Comment by hangshao0** [comment]
Can you try these 2 options to see if this crash disappears ?
1. `-XX:-ShareAnonymousClasses`
2. `-XX:-ShareUnsafeClasses`

**Comment by calle2010** [comment]
If I keep the cache that has failed before then I can reproduce the crash with both options.

If I destroy the cache before starting Eclipse then I can still reproduce the crash with ```-XX:-ShareAnonymousClasses```.
With ```-XX:-ShareUnsafeClasses``` I can't reproduce it.

Just to let you know, the other workaround I found was to use ```-Xaot:exclude={/org/sonar/java/*}```.

**Comment by hangshao0** [comment]
```
Just to let you know, the other workaround I found was to use
-Xaot:exclude={/org/sonar/java/*}.
```

@dsouzai

**Comment by dsouzai** [comment]
@hangshao0 did you get a chance to look at the stack trace? Do you know what exactly is happening when the seg fault happens?

**Comment by hangshao0** [comment]
```
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at org/sonar/java/checks/ModifiersOrderCheck.getFirstBadlyOrdered(ModifiersOrderCheck.java:79)
4XESTACKTRACE                at org/sonar/java/checks/ModifiersOrderCheck.visitNode(ModifiersOrderCheck.java:61)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.lambda$visit$6(VisitorsBridge.java:311)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner$$Lambda$2508/0000000000000000.accept(Bytecode PC:8)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.lambda$forEach$9(VisitorsBridge.java:326)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner$$Lambda$2507/0000000000000000.run(Bytecode PC:8)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge.runScanner(VisitorsBridge.java:189)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge.access$100(VisitorsBridge.java:66)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.forEach(VisitorsBridge.java:326)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visit(VisitorsBridge.java:313)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visitChildren(VisitorsBridge.java:297)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visit(VisitorsBridge.java:317)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visitChildren(VisitorsBridge.java:297)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visit(VisitorsBridge.java:317)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visitChildren(VisitorsBridge.java:297)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.visit(VisitorsBridge.java:317)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge$IssuableSubsciptionVisitorsRunner.run(VisitorsBridge.java:288)
4XESTACKTRACE                at org/sonar/java/model/VisitorsBridge.visitFile(VisitorsBridge.java:171)
4XESTACKTRACE                at org/sonar/java/ast/JavaAstScanner.simpleScan(JavaAstScanner.java:98)
4XESTACKTRACE                at org/sonar/java/ast/JavaAstScanner.scan(JavaAstScanner.java:64)
4XESTACKTRACE                at org/sonar/java/JavaSquid.scanSources(JavaSquid.java:120)
4XESTACKTRACE                at org/sonar/java/JavaSquid.scan(JavaSquid.java:113)
4XESTACKTRACE                at org/sonar/plugins/java/JavaSquidSensor.execute(JavaSquidSensor.java:103)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/analyzer/sensor/SensorsExecutor.executeSensor(SensorsExecutor.java:80)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/analyzer/sensor/SensorsExecutor.execute(SensorsExecutor.java:71)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/container/analysis/AnalysisContainer.doAfterStart(AnalysisContainer.java:134)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/container/ComponentContainer.startComponents(ComponentContainer.java:126)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/container/ComponentContainer.execute(ComponentContainer.java:111)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/container/standalone/StandaloneGlobalContainer.analyze(StandaloneGlobalContainer.java:155)
4XESTACKTRACE                at org/sonarsource/sonarlint/core/StandaloneSonarLintEngineImpl.analyze(StandaloneSonarLintEngineImpl.java:91)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/engine/StandaloneEngineFacade.runAnalysis(StandaloneEngineFacade.java:84)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJob.runAnalysis(AnalyzeStandaloneProjectJob.java:65)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJob.runAnalysis(AnalyzeStandaloneProjectJob.java:1)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/jobs/AbstractAnalyzeProjectJob.run(AbstractAnalyzeProjectJob.java:396)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/jobs/AbstractAnalyzeProjectJob.runAnalysisAndUpdateMarkers(AbstractAnalyzeProjectJob.java:199)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/jobs/AbstractAnalyzeProjectJob.doRun(AbstractAnalyzeProjectJob.java:161)
4XESTACKTRACE                at org/sonarlint/eclipse/core/internal/jobs/AbstractSonarProjectJob.run(AbstractSonarProjectJob.java:45)
4XESTACKTRACE                at org/eclipse/core/internal/jobs/Worker.run(Worker.java:63(Compiled Code))
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007FF9F5B0C750 [j9vm29+0x1c750])
4XENATIVESTACK               (0x0000000000000001)
4XENATIVESTACK               (0x0000000003C4A030)
4XENATIVESTACK               (0x0000000000000018)
4XENATIVESTACK               (0x000000476F9FF700)
4XENATIVESTACK               (0x0000000000000020)
```

The native stack value does not seem to be correct.

**Comment by dsouzai** [comment]
Ok, are you able to get a valid native stack? I ask because given the version of OpenJ9 being used, it's possible it's related to https://github.com/eclipse/openj9/issues/9710 which was fixed recently(ish).

**Comment by calle2010** [comment]
I don't know how I could help to retrieve a valid nativ stack. 

The description in #9710 rings a bell: "with a different version of some of the classes"

I can trigger the crash when I switch between the standalone and the connected mode of Sonarlint. As far as I understand it retrieves the checks from the server in connected mode. Also I see classpaths in the cache that look like temporary paths of the plugin. 

Is the fix already in the nightly build? Then I could try this.

**Comment by dsouzai** [comment]
> Is the fix already in the nightly build? Then I could try this.

Yeah it is, if you can give a go that would be helpful. If it still fails, could you run with `-Xaot:log=/path/to/log,aotrtDebugLevel=30,rtLog=/path/to/rtLog` and send over the generated files along with the coredump? Might also be worth sending over the SCC.

**Comment by calle2010** [comment]
Unfortunately I can't reproduce the crash anymore. I tried to create the same conditions again, but the crash doesn't happen anymore. I'd suggest to close this for now. I will continue to run Eclipse with the configuration that crashed before and, if I have the same situation again, will try the AOT log and the nightly build.

**Comment by dsouzai** [comment]
Closing as per previous comment
