### ISSUE TITLE
Xcheck:jni misses NULL checks of char type of destination buffer causes segfault

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10477]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------
The last parameter of GetStringRegion JNI function is char type of destination buffer.
If NULL is used for destination buffer, the segmentation fault occurs on OpenJ9.
OpenJ9 does not validate the NULL buffer when Xcheck:jni is enabled.

On the other hand, Hotspot throws following error message:
```
FATAL ERROR in native method: Bad global or local ref passed to JNI
```
OpenJ9 should also validates such buggy code.

Same problem occurs for GetStringUTFRegion JNI function.

Diagnostic files
----------------

[test12.zip](https://github.com/eclipse/openj9/files/5138148/test12.zip)

**Comment by gacholio** [comment]
Note the spec says the buffer can be NULL if the length is 0.
