### ISSUE TITLE
Xcheck:jni does not validate the usage of incompatible type object in FromReflectedMethod

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10479]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------

According to the JNI documentation, only java.lang.reflect.Method or java.lang.reflect.Constructor type of objects should be passed to FromReflectedMethod JNI function.
Passing incompatible type of objects such as java.lang.Throwable leads to a segmentation fault on OpenJ9.

The Xcheck:jni should validate the objects are of the correct type. 

Diagnostic files
----------------
[test13.zip](https://github.com/eclipse/openj9/files/5138244/test13.zip)

**Comment by JasonFengJ9** [comment]
Working on this.

**Comment by gacholio** [comment]
Suggest using the non-null object type and adding the class checks in the checking code itself, rather than adding a new type. FromReflectedField should be updated as well (instance of Field).
