### ISSUE TITLE
Deleted Weak Global References are not validated by Xcheck:jni

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10481]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------

Similar to issue #10310, OpenJ9 does not validate the deleted reference object when using Call<'type'>Method.
It seems that the problem only occurs for the objects with weak global reference.
If the object is a local reference, OpenJ9 properly catches the usage of deleted reference.
However, if the object is a weak global reference, it cannot catches the use of deleted reference.

On the contrary, Hotspot throws following error message:

```
FATAL ERROR in native method: Bad global or local ref passed to JNI
```

The same problem occurs on other JNI functions such as IsSameObject, Call<'type'>MethodV, and CallNonvirtual<'type'>Method

Diagnostic files
----------------
[test15.zip](https://github.com/eclipse/openj9/files/5138595/test15.zip)

**Comment by gacholio** [comment]
J9 uses pools for references, so if a ref is deleted and a new one created, they may well share the same address. This is definitely not something we are going to change.

Can you provide some example code to illustrate the problem? Wondering if it's the re-use suggested above.

**Comment by sjmini** [comment]
@gacholio 
Below is the code snippet.
The code causes a segmentation fault on OpenJ9. (Xcheck:jni does not validate it).
On other JVMs such as Hotspot, throws JNI error message when Xcheck:jni is enabled with the same code.

```
...
local_ref = (*env)->NewWeakGlobalRef(env, tmp_1);
(*env)->DeleteWeakGlobalRef(env,local_ref);
(*env)->CallBooleanMethod(env,local_ref,tmp_3,1);
...
```

But, if the local reference is used as follow, OpenJ9 properly validate the problematic code when Xcheck:jni is enabled.
The error message is "JNI error in CallBooleanMethod/CallBooleanMethodV: Argument #2 is NULL"
```
//local_ref = (*env)->NewWeakGlobalRef(env, tmp_1);
//(*env)->DeleteLocalRef(env, local_ref);
```

Maybe OpenJ9 treats weak global references in different ways?

**Comment by gacholio** [comment]
For some reason, this works fine for strong global references. The crash is in `jniIsGlobalRef` when checking to see if a global ref is actually one of the fake references we use to pass `jclass` for static natives.
