### ISSUE TITLE
zero capacity of local reference frame is allowed

### ISSUE THREAD

**Issue by sjmini** [eclipse/openj9#10484]
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------

According to the JNI document, the second argument of PushLocalFrame JNI function must be greater than 0.
https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#newlocalref

However, it seems that OpenJ9 does not mind receiving 0 value as a second argument, and it does some operations internally, and returns 0 which indicates the success of the function call.

Enabling Xcheck:jni option does not catch the problem.

problem code:
```
(*env)->PushLocalFrame(env,0);
```

Is this correct behaviors from OpenJ9? This is not consistent with the JNI document.
Maybe Xcheck:jni should validate and prevent 0 value in this situation.

Similarly, RegisterNatives function receives number of methods as a 4th argument.
According to the JNI document, this value also must be greater than 0.
However, OpenJ9 does not throw any error messages when 0 is passed to RegisterNatives function.

**Comment by pshipton** [comment]
@gacholio any comments?

**Comment by gacholio** [comment]
I see nothing in the specification about 0 being illegal.

https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#pushlocalframe
https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#registernatives

**Comment by sjmini** [comment]
@gacholio 
I have raised the issue because of below statements.
Below statements indicates that the value must not be 0.

PushLocalFrame
capacity: the minimum number of required local references. Must be > 0.

RegisterNatives
nMethods: the number of native methods in the class, must be greater than zero.

**Comment by gacholio** [comment]
Yep, sorry, I only read the synopsis for each. In that case, my vote is we update JNI check to make these warnings, and leave the VM code as it is.

**Comment by mikezhang1234567890** [comment]
Looking into it.

**Comment by mikezhang1234567890** [comment]
I've created a pull request, but Hotspot also doesn't care if the arguments are 0 under `-Xcheck:jni`
