### ISSUE TITLE
OpenJ9 android port? (Discussion)

### ISSUE THREAD

**Issue by Malaska678** [eclipse/openj9#10515]
OpenJDK has android port but what open J9. Open J9 android port can be nice. Porters that port java pc games to android benefits the most. If its impossible close the issue.
A discussion contains:
Developer Response
People's Reaction
And solving some problems

**Comment by Malaska678** [comment]
Same discussion happen graalvm

**Comment by Malaska678** [comment]
So a developer accept that this would be a discussion.

**Comment by Malaska678** [comment]
So why turn thiz to a discussion if there's no response?

**Comment by Adriankhl** [comment]
What do you mean by OpenJDK has android port?

Also, be more patient, people are not obliged to response to your question unless you pay for them.

**Comment by Malaska678** [comment]
> What do you mean by OpenJDK has android port?
> 
> Also, be more patient, people are not obliged to response to your question unless you pay for them.

An OpenJDK working for android.
Ooops sorry.

**Comment by Malaska678** [comment]
I mean make openJ9 work on android

**Comment by Malaska678** [comment]
In software engineering, porting is the process of adapting software for the purpose of achieving some form of execution in a computing environment that is different from the one that a given program (meant for such execution) was originally designed for (e.g., different CPU, operating system, or third party library).

**Comment by Adriankhl** [comment]
> > What do you mean by OpenJDK has android port?
> > Also, be more patient, people are not obliged to response to your question unless you pay for them.
> 
> Someone make open jdk work for android

Where?

I am not an expert, but I think you misunderstand something. Do you mean Java ME? Android Runtime (Dalvik)? Hotspot? GraalVM? Or simply an JDK for Android Studio/Intellij/Gradle build of Android project?

**Comment by Malaska678** [comment]
Nope i mean someone port openjdk to android. Example a software only work for linux, its possible that u can port it to android. Understand now developer. Im not even a developer.

**Comment by Malaska678** [comment]
No one is interested for making openj9 work android which is sad because i want to openj9 for android for my project when i learn programming. :(

**Comment by Adriankhl** [comment]
Based on what you are saying, I don't think you have sufficient understanding of what you want to request/discuss. I suggest that you should learn the distinction between jvm, openjdk, openj9, hotspot, java (maybe also kotlin if you want to do android), Android Runtime (and Dalvik).

**Comment by khanhduytran0** [comment]
He means want to port OpenJ9 to Android that compitable with Bionic libc (lacking some syscall compared with GLIBC).

**Comment by Malaska678** [comment]
Why u go here? hmmm

**Comment by Malaska678** [comment]
Btw thanks for explaining to that guy

**Comment by Malaska678** [comment]
Sorry for very small knowledge on java and such things, but i know what im saying

**Comment by Malaska678** [comment]
This is non-sense. So closing. Tell to me if u want to reopen this.

**Comment by BryleHelll** [comment]
Oh this issue is freaking stupid

**Comment by BryleHelll** [comment]
Im malaska

**Comment by BryleHelll** [comment]
I hate this
