### ISSUE TITLE
vrfyhelp.c failed to compile on all Mac-OpenJ9 builds

### ISSUE THREAD

**Issue by austin0** [eclipse/openj9#10522]
Assuming this is related to https://github.com/eclipse/openj9/pull/10520 @hangshao0

Failure link
------------

Compilation failing for `vrfyhelp.c` on all Mac-OpenJ9 builds since 04/09/20.

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/685/console

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9-macosXL/509/console

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-mac-x64-openj9-macosXL/26/console

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-mac-x64-openj9/24/console

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9-macosXL/677/consoleFull

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/731/consoleFull

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-openj9/106/consoleFull

Failure output (captured from console output)
---------------------------------------------
```
18:13:12 vrfyhelp.c:1046:24: error: passing 'U_8 []' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
18:13:12                                                 || (0 != strncmp(J9UTF8_DATA(currentClassName), targetClassName, targetClassLength))
18:13:12                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:13:12 ../oti/j9.h:169:36: note: expanded from macro 'J9UTF8_DATA'
18:13:12 #define J9UTF8_DATA(j9UTF8Address) (((struct J9UTF8 *)(j9UTF8Address))->data)
18:13:12                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:13:12 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:84:26: note: passing argument to parameter '__s1' here
18:13:12 int      strncmp(const char *__s1, const char *__s2, size_t __n);
18:13:12                              ^
18:13:12 vrfyhelp.c:1046:55: error: passing 'U_8 *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
18:13:12                                                 || (0 != strncmp(J9UTF8_DATA(currentClassName), targetClassName, targetClassLength))
18:13:12                                                                                                 ^~~~~~~~~~~~~~~
18:13:12 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:84:44: note: passing argument to parameter '__s2' here
18:13:12 int      strncmp(const char *__s1, const char *__s2, size_t __n);
18:13:12                                                ^
```

**Comment by austin0** [comment]
Issue is also affecting two AIX builds:

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-aix-ppc64-openj9/23/console

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-openj9/218/console

**Comment by keithc-ca** [comment]
I have a fix for this.
