### ISSUE TITLE
Handled NullPointerException in J9VMInternals.getClassInfoStrings

### ISSUE THREAD

**Issue by ajohnson1** [eclipse/openj9#10535]
Java -version output
--------------------

OpenJDK8U-jdk_x64_windows_openj9_8u265b01_openj9-0.21.0\jdk8u265-b01\bin\java.exe -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)

Summary of problem
------------------

Running Eclipse Memory Analyzer with DTFJ under OpenJ9 (or IBM Java) V8 under a debugger shows a NullPointerException at the location below when parsing a heap dump.
This is harmless as the code handles this, but a bit annoying stepping through with a debugger - as I would have to step resume each time, or ignore a NullPointerException in that particular place. The class being examined was [I loaded by the bootstrap class loader.

If the code could avoid the null pointer exception for what I presume is a normal code flow then that would be nice. 
It doesn't cause a problem when not running with a debugger, though might cause a problem if a user has arranged for a dump to trigger on a null pointer exception.

This is a low priority bug for me.

Diagnostic files
----------------
```
Thread [Worker-1: Parsing heap dump from 'C:\Users\Username\Downloads\dumps\core.20151119.173648.10500.0001.dmp'] (Suspended (exception NullPointerException))	
	J9VMInternals.getClassInfoStrings(Class<?>, String) line: 431	
	J9VMInternals.formatNoSuchMethod(String, Class<?>, String, Class<?>, String) line: 462	
	ObjectStreamClass.hasStaticInitializer(Class<?>) line: not available [native method]	
	ObjectStreamClass.computeDefaultSUID(Class<?>) line: 1955	
	ObjectStreamClass.access$100(Class) line: 79	
	ObjectStreamClass$2.run() line: 275	
	ObjectStreamClass$2.run() line: 273	
	AccessController.doPrivileged(PrivilegedAction<T>) line: 678	
	ObjectStreamClass.getSerialVersionUID() line: 272	
	ObjectStreamClass.writeNonProxy(ObjectOutputStream) line: 819	
	ObjectOutputStream.writeClassDescriptor(ObjectStreamClass) line: 668	
	ObjectOutputStream.writeNonProxyDesc(ObjectStreamClass, boolean) line: 1282	
	ObjectOutputStream.writeClassDesc(ObjectStreamClass, boolean) line: 1231	
	ObjectOutputStream.writeArray(Object, ObjectStreamClass, boolean) line: 1322	
	ObjectOutputStream.writeObject0(Object, boolean) line: 1174	
	ObjectOutputStream.defaultWriteFields(Object, ObjectStreamClass) line: 1548	
	ObjectOutputStream.writeSerialData(Object, ObjectStreamClass) line: 1509	
	ObjectOutputStream.writeOrdinaryObject(Object, ObjectStreamClass, boolean) line: 1432	
	ObjectOutputStream.writeObject0(Object, boolean) line: 1178	
	ObjectOutputStream.defaultWriteFields(Object, ObjectStreamClass) line: 1548	
	ObjectOutputStream.writeSerialData(Object, ObjectStreamClass) line: 1509	
	ObjectOutputStream.writeOrdinaryObject(Object, ObjectStreamClass, boolean) line: 1432	
	ObjectOutputStream.writeObject0(Object, boolean) line: 1178	
	ObjectOutputStream.defaultWriteFields(Object, ObjectStreamClass) line: 1548	
	ObjectOutputStream.writeSerialData(Object, ObjectStreamClass) line: 1509	
	ObjectOutputStream.writeOrdinaryObject(Object, ObjectStreamClass, boolean) line: 1432	
	ObjectOutputStream.writeObject0(Object, boolean) line: 1178	
	ObjectOutputStream.writeObject(Object) line: 348	
	HashMapIntObject<E>.writeObject(ObjectOutputStream) line: 461	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 498	
	ObjectStreamClass.invokeWriteObject(Object, ObjectOutputStream) line: 1154	
	ObjectOutputStream.writeSerialData(Object, ObjectStreamClass) line: 1496	
	ObjectOutputStream.writeOrdinaryObject(Object, ObjectStreamClass, boolean) line: 1432	
	ObjectOutputStream.writeObject0(Object, boolean) line: 1178	
	ObjectOutputStream.writeObject(Object) line: 348	
	SnapshotImpl.create(XSnapshotInfo, String, IObjectReader, HashMapIntObject<ClassImpl>, HashMapIntObject<XGCRootInfo[]>, HashMapIntObject<HashMapIntObject<XGCRootInfo[]>>, BitField, IndexManager, IProgressListener) line: 294	
	SnapshotImplBuilder.create(ParserRegistry$Parser, IProgressListener) line: 95	
	SnapshotFactoryImpl.parse(File, String, Map<String,String>, IProgressListener) line: 286	
	SnapshotFactoryImpl.openSnapshot(File, Map<String,String>, IProgressListener) line: 167	
	SnapshotFactory.openSnapshot(File, Map<String,String>, IProgressListener) line: 147	
	HeapEditor$2(ParseHeapDumpJob).run(IProgressMonitor) line: 95	
	Worker.run() line: 60	
```

**Comment by gacholio** [comment]
@ajohnson1 As you're stepping in the debugger, can you tell us where the NPE originates?
```
path = clazz.getProtectionDomain().getCodeSource().getLocation().toString();
```

**Comment by ajohnson1** [comment]
It's actually:
```
			classLoader = clazz.getClassLoader().toString();
```

**Comment by ajohnson1** [comment]
I'm not sure why the line numbers don't quite match, so here are some links matching to the GitHub code based on me looking at the source of the code that was running on my machine.

https://github.com/eclipse/openj9/blob/be26f51d1bed0614d99b996c1a4aaee3c789a67b/jcl/src/java.base/share/classes/java/lang/J9VMInternals.java#L500

Start of method: https://github.com/eclipse/openj9/blob/be26f51d1bed0614d99b996c1a4aaee3c789a67b/jcl/src/java.base/share/classes/java/lang/J9VMInternals.java#L494
```
arg0=class [I
arg1=null
```

so the problem seems to be that the class is loaded by the bootstrap loader, but arg1 has not been set.
That method is called from
https://github.com/eclipse/openj9/blob/be26f51d1bed0614d99b996c1a4aaee3c789a67b/jcl/src/java.base/share/classes/java/lang/J9VMInternals.java#L531

The start of that method was:
https://github.com/eclipse/openj9/blob/be26f51d1bed0614d99b996c1a4aaee3c789a67b/jcl/src/java.base/share/classes/java/lang/J9VMInternals.java#L527
The arguments were:
```
[I.<clinit>()V
class [I
null
class java.io.ObjectStreamClass
C:\Users\Username\Downloads\OpenJDK8U-jdk_x64_windows_openj9_8u265b01_openj9-0.21.0\jdk8u265-b01\jre\lib\rt.jar
```

That was called from `ObjectStreamClass.hasStaticInitializer(Class<?>) line: not available [native method]` but I don't have the source for that.

It is called from https://github.com/eclipse/openj9/blob/40acc6f1e9395313a0d05273fb0f9b42b665527c/runtime/vm/lookupmethod.c#L856-L914 but I don't know if that is relevant.

**Comment by ajohnson1** [comment]
Thank you
