### ISSUE TITLE
jdk15+36: MBCS unicode specifial.functional failures

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#10590]
Failure link
------------
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_special.functional_x86-64_linux/42/console
tests failing: 
MBCS_Tests_unicode_linux_0
MBCS_Tests_codepoint_linux_0

Failure output (captured from console output)
---------------------------------------------
```
13:44:47  mkdir -p "/home/jenkins/workspace/Test_openjdk15_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_1599828051242/MBCS_Tests_unicode_linux_0"; \
13:44:47  cd "/home/jenkins/workspace/Test_openjdk15_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_1599828051242/MBCS_Tests_unicode_linux_0"; \
13:44:47  sh /home/jenkins/workspace/Test_openjdk15_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/unicode/test.sh; \
13:44:47  if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_unicode_linux_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk15_j9_special.functional_x86-64_linux/openjdk-tests/TKG/..;  else echo ""; echo "MBCS_Tests_unicode_linux_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk15_j9_special.functional_x86-64_linux/openjdk-tests/TKG/../TKG/test_output_1599828051242/TestTargetResult";
13:44:48  Checking UnicodeData-12.1.0.txt
13:44:51    Checked 277510 characters
13:44:51  5930 characters were not checked
13:44:52  Checking Blocks-12.1.0.txt
13:44:52    Checked 281392 characters
13:44:52    Undefined 3730 characters
13:44:52  Checking Scripts-12.1.0.txt
13:44:54    Checked 137994 characters
13:44:54  589; [COMMON]<->[ARMENIAN]
13:44:54  Checking PropertyValueAliases
13:44:54    Total 157 enums are defined
13:44:54    Checking PropertyValueAliases-12.1.0.txt
13:44:54    Missing code(expected): Hrkt
13:44:54    Missing value(expected): KATAKANA_OR_HIRAGANA
13:44:54    Checked 154 items
13:44:55  Checking NormalizerTest
13:44:56    Phase1   Inspection times : 112920
13:44:56    Phase1   Test is Passed.
13:44:57    Phase2   Defined Unicode characters : 283440
13:44:57    Phase2   Ignored characters :  16896
13:44:57  Error at AB69
13:44:57  Error at 11938
13:44:57  Error at 1FBF0
13:44:57  Error at 1FBF1
13:44:57  Error at 1FBF2
13:44:57  Error at 1FBF3
13:44:57  Error at 1FBF4
13:44:57  Error at 1FBF5
13:44:57  Error at 1FBF6
13:44:57  Error at 1FBF7
13:44:57  Error at 1FBF8
13:44:57  Error at 1FBF9
13:44:57    Phase2   Error : 12
13:44:57    Phase2   Test is Failed.
13:44:57  Test Failed
13:44:57  
13:44:57  MBCS_Tests_unicode_linux_0_FAILED
```

**Comment by DanHeidinga** [comment]
We need a stop-ship decision on this for 0.22.0

**Comment by tajila** [comment]
@hangshao0 can you please take a look at this

**Comment by hangshao0** [comment]
@andrew-m-leonard, do you know if this test ever pass before ? I was looking at the history, but it has history of only 1 day before this failure, https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_special.functional_x86-64_linux/40/ is already gone.

**Comment by andrew-m-leonard** [comment]
@hangshao0 I don't, i've not seen this fail before from memory. Probably worth re-running a few iterations in a grinder

**Comment by hangshao0** [comment]
This does not look like an OpenJ9 issue to me. 

MBCS_Tests_unicode_linux_0 failed at: 
```
if (str1.equals(NFC(str1)) &&
       str1.equals(NFD(str1)) &&
       str1.equals(NFKC(str1)) &&
       str1.equals(NFKD(str1))) {
       good ++;
} else {
        System.err.println(String.format("Error at %04X", i));   <------------- Failed here.
        err ++;
}
```
The `NFC()/NFD()/NFKC()/NFKD()` functions are just a wrapper of `Normalizer.normalize()`.
OpenJ9 does not own the implementation of `Normalizer.normalize()`.

Tried the latest OpenJDK 15 nightly build from Adopt, RI is also failing `MBCS_Tests_unicode_linux_0` and `MBCS_Tests_codepoint_linux_0`

https://ci.adoptopenjdk.net/job/Grinder/3868/tapResults/
https://ci.adoptopenjdk.net/job/Grinder/3869/tapResults/

**Comment by hangshao0** [comment]
Seems that OpenJDK is updated to support unicode 13.0: https://bugs.openjdk.java.net/browse/JDK-8239383. But the test material https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/functional/MBCS_Tests/unicode/data is still using the 12.0.1 version of NormalizationTest.txt. May need to update test material to use the 13.0 version https://www.unicode.org/Public/13.0.0/ucd/NormalizationTest.txt

**Comment by tajila** [comment]
Thanks for investigating this @hangshao0

**Comment by smlambert** [comment]
I have raised https://github.com/AdoptOpenJDK/openjdk-tests/issues/1957 to address this issue.
