### ISSUE TITLE
Unable to use --add-modules via options.default or IBM_JAVA_OPTIONS

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#1062]
OpenJ9 accepts --add-modules on the command line and appears to be processing it (I get an appropriate message if I give a non-existent module). But attempting to set --add-modules via options.default or the IBM_JAVA_OPTIONS env var causes the JVM to fail to start up

```
$ bin/java  -version
JVMJ9VM007E Command-line option unrecognised: --add-modules java.xml.bind
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```

**Comment by pshipton** [comment]
Only the java launcher understands the options with space as a separator. The VM understands the options using `=` instead of the space. i.e. use `--add-modules=java.xml.bind` (which is also valid on the command line).

**Comment by JamesKingdon** [comment]
Ah, thanks Peter, no wonder I was confused. Open Liberty is also passing options via IBM_JAVA_OPTIONS, so we'll need to be aware of this oddity.
