### ISSUE TITLE
Pls check win2012r2-x86-4

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10639]
Pls take a look at win2012r2-x86-4 to see if it needs any cleanup, if there are processes left running. Or just reboot it.

There are a number of failures related to creating processes, some of which look like the machine doesn't have the resources to create all the necessary sub-processes.

https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly/51/

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Rebooted and back in service in jenkins.
