### ISSUE TITLE
AdoptOpenJDK 8 OpenJ9 crash when Oracle Java 15 is in the PATH on Windows

### ISSUE THREAD

**Issue by megazone23** [eclipse/openj9#10696]
Java -version output
--------------------

openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)

Summary of problem
------------------

If Oracle Java 15 is in the Windows PATH the AdoptOpenJDK will crash and hand the session.  To reproduce...

1. Set the PATH to point to Oracle Java 15

```set PATH=C:/Program Files/Java/jdk-15/bin/server;C:/Program Files/Java/jdk-15/bin```

2. Run AdoptOpenJDK openj9

```"c:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-openj9"\bin\java -version```

You get  crash dump and it hangs trying to write the dump.  You cannot control-c out you have to kill the process from Task Manager.

This problem prevents developing Java 8 code with the latest version of eclipse, 2020-09.  Eclipse 2020-09 requires Java 11 or higher and it will configure the PATH with the version of java used to run the IDE.  The problem does not occur with the AdoptOpenJDK 8 hotspot version.  This failure only happens with the OpenJ9 version.

Diagnostic files
----------------

```
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFB2AD7BF18 ContextFlags=0010000f
Handler1=00007FFAF389FD20 Handler2=00007FFB0CAB8900
RDI=00000000112D3168 RSI=00007FFB2AD984C0 RAX=0000143400360034 RBX=00000000C0000139
RCX=00007FFB2AD9D7B8 RDX=00007FFB2ACD3550 R8=0000000000000000 R9=0000000000000000
R10=0000000000001112 R11=0000000000001000 R12=0000000000000003 R13=0000000000000003
R14=00007FFB0CE08401 R15=0000000000000003
RIP=00007FFB2AD7BF18 RSP=000000000301C640 RBP=000000000301CCE0 GS=002B
FS=0053 ES=002B DS=002B
XMM0 00007ffb2ad9d588 (f: 718919040.000000, d: 6.952330e-310)
XMM1 00007ffb2ad9d550 (f: 718918976.000000, d: 6.952330e-310)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM3 0000000000120003 (f: 1179651.000000, d: 5.828250e-318)
XMM4 000000000127a600 (f: 19375616.000000, d: 9.572826e-317)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\WINDOWS\SYSTEM32\ntdll.dll
Module_base_address=00007FFB2AC80000 Offset_in_DLL=00000000000fbf18
Target=2_90_20200728_776 (Windows 10 10.0 build 18362)
CPU=amd64 (12 logical CPUs) (0x7edda6000 RAM)
----------- Stack Backtrace -----------
RtlRaiseStatus+0x18 (0x00007FFB2AD7BF18 [ntdll+0xfbf18])
RtlCharToInteger+0x35c (0x00007FFB2ACEEEBC [ntdll+0x6eebc])
memset+0x941b (0x00007FFB2AD2C39B [ntdll+0xac39b])
LdrGetDllHandleByMapping+0x578 (0x00007FFB2ACAE2A8 [ntdll+0x2e2a8])
LdrGetDllHandleByMapping+0xb8f (0x00007FFB2ACAE8BF [ntdll+0x2e8bf])
RtlMultiByteToUnicodeSize+0x410 (0x00007FFB2ACA24C0 [ntdll+0x224c0])
RtlMultiByteToUnicodeSize+0x178 (0x00007FFB2ACA2228 [ntdll+0x22228])
LdrLoadDll+0xe4 (0x00007FFB2ACA16E4 [ntdll+0x216e4])
LoadLibraryExW+0x170 (0x00007FFB2805E9C0 [KERNELBASE+0x2e9c0])
j9port_init_library+0x2eebf (0x00007FFB0CAC188F [j9prt29+0x3188f])
J9_CreateJavaVM+0x26f04 (0x00007FFAF38D2014 [j9vm29+0xb2014])
J9_CreateJavaVM+0x2665b (0x00007FFAF38D176B [j9vm29+0xb176b])
J9_CreateJavaVM+0x272d9 (0x00007FFAF38D23E9 [j9vm29+0xb23e9])
JVM_OnLoad+0x28f (0x00007FFB0BF18D2F [jclse29+0x38d2f])
J9VMDllMain+0x131 (0x00007FFB0BF195A1 [jclse29+0x395a1])
J9_CreateJavaVM+0x7c59 (0x00007FFAF38B2D69 [j9vm29+0x92d69])
J9_CreateJavaVM+0x94550 (0x00007FFAF393F660 [j9vm29+0x11f660])
J9_CreateJavaVM+0xda90 (0x00007FFAF38B8BA0 [j9vm29+0x98ba0])
J9_CreateJavaVM+0xf4cd (0x00007FFAF38BA5DD [j9vm29+0x9a5dd])
j9port_init_library+0x2733f (0x00007FFB0CAB9D0F [j9prt29+0x29d0f])
J9_CreateJavaVM+0xf89a (0x00007FFAF38BA9AA [j9vm29+0x9a9aa])
J9_CreateJavaVM+0x89 (0x00007FFAF38AB199 [j9vm29+0x8b199])
JVM_BeforeHalt+0x1099 (0x00007FFB12441599 [jvm+0x11599])
JNI_CreateJavaVM+0x351 (0x00007FFB22B68431 [jvm+0x8431])
(0x00007FF7DAD92386 [java+0x2386])
(0x00007FF7DAD9D007 [java+0xd007])
(0x00007FF7DAD9D09B [java+0xd09b])
BaseThreadInitThunk+0x14 (0x00007FFB2AB27BD4 [KERNEL32+0x17bd4])
RtlUserThreadStart+0x21 (0x00007FFB2ACECE51 [ntdll+0x6ce51])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/09/24 16:37:00 - please wait.
JVMDUMP032I JVM requested System dump using 'C:\Development\Workspaces\eclipse-ide-for-java-ee-developers\Test\core.20200924.163700.35856.0001.dmp' in response to an event
```

**Comment by ChengJin01** [comment]
1) Tried with the nightly build AdoptOpenJDK8/OpenJ9 (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-10-01-16-17/OpenJDK8U-jdk_x64_windows_openj9_2020-10-01-16-17.zip) and the nightly build AdoptOpenJDK15/Hotspot (https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk15u-2020-10-01-04-18/OpenJDK15U-jdk_x64_windows_hotspot_2020-10-01-04-18.zip) as follows:
```
c:\JCHAU>set PATH=C:/JCHAU/jdk_15_hotspot_adopt/bin/server;C:/JCHAU/jdk_15_hotspot_adopt/bin
c:\JCHAU>java -version
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment Hotspot (build 15+36-202009282032)
OpenJDK 64-Bit Server VM Hotspot (build 15+36-202009282032, mixed mode, sharing)

c:\JCHAU>"c:\JCHAU\jdk8u272-b09_openj9"\bin\java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-202009301835-b09)
Eclipse OpenJ9 VM (build master-01c213f22, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200930_835 (JIT enabled, AOT enabled)
OpenJ9   - 01c213f22
OMR      - 64617ba64
JCL      - 52122fb6 based on jdk8u272-b09)
```

2) And tried with Oracle JDK15 binary (https://download.oracle.com/otn-pub/java/jdk/15+36/779bf45e88a44cbd9ea6621d33e33db1/jdk-15_windows-x64_bin.zip) as follows:
```
c:\JCHAU>set PATH=C:/JCHAU/jdk_15_hotspot_oracle/bin/server;C:/JCHAU/jdk_15_hotspot_oracle/bin
c:\JCHAU>java  -version
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

c:\JCHAU>"c:\JCHAU\jdk8u272-b09_openj9"\bin\java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-202009301835-b09)
Eclipse OpenJ9 VM (build master-01c213f22, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200930_835 (JIT enabled, AOT enabled)
OpenJ9   - 01c213f22
OMR      - 64617ba64
JCL      - 52122fb6 based on jdk8u272-b09)
```
3) Also tried with Oracle JDK15 installer (https://download.oracle.com/otn-pub/java/jdk/15+36/779bf45e88a44cbd9ea6621d33e33db1/jdk-15_windows-x64_bin.exe) as follows:
```
c:\JCHAU>java -version
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

c:\JCHAU>set PATH=C:/Program Files/Java/jdk-15/bin/server;C:/Program Files/Java/jdk-15/bin

c:\JCHAU>"c:\JCHAU\jdk8u272-b09_openj9"\bin\java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-202009301835-b09)
Eclipse OpenJ9 VM (build master-01c213f22, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200930_835 (JIT enabled, AOT enabled)
OpenJ9   - 01c213f22
OMR      - 64617ba64
JCL      - 52122fb6 based on jdk8u272-b09)
```
None of them ended up with crash or hang with the specified environment setting (ran for many times but nothing wrong occurred)
I suspect whether there is anything specific in the originator's environment that triggered the crash.

**Comment by ChengJin01** [comment]
Hi @megazone23, could you please try the latest release or nightly build to see whether the problem still occurs?

**Comment by megazone23** [comment]
I tried to use the version you used 272 but that caused a problem and eclipse is having problems recognizing it.  I uninstalled 272 and reinstalled 265 but now I cannot run programs it is failing with an error.  

An internal error occurred during: "Launching HelloWorld".
null argument:

Does eclipse 2020-09 work correctly with AdoptOpenJDK 8 openJ9?  Both Oracle Java 8 and AdoptOpenJDK 8 hotspot works properly.  It is just the openJ9 version which is having issues.

However, after installing the 272 version which ended up uninstalling the 265 version, the -version seems to work now.  So I uninstalled the 272 version and reinstalled the 265 version and now the -version from the command prompt also works with with 265.  Not sure what is happening.

**Comment by ChengJin01** [comment]
@megazone23,  if eclipse 2020-09 is a installing package that includes Java8/hotspot (JRE), then it's no wonder that it works fine with Oracle or OpenJDK/hotspot as it should be OK when Hotspot looks for to the Java path from either of them to locate the required libraries (both of them are pretty much identical in terms of the directory of libraries)

So the question is whether Openj9 correctly picks up the Java path of OpenJ9 instead of Hotspot. I suspect OpenJ9 totally went wrong due the mixed setting/environment on your side.

To rule out any other possibility,  please remove all Java versions (including all installed version & manually unzipped versions) and reinstall v265 or v272 to see how it goes.

**Comment by megazone23** [comment]
I created a new VM and only installed Oracle Java 15, Oracle Java 8, AdoptOpenJDK 8 Hotspot, and AdoptOpenJDK 8 OpenJ9.  It seems to work so your theory about mixed setting is probably correct.  I have several versions of Java installed on my laptop this is due to multiple upgrades of Java over the years.  How does OpenJ9 determine the Java path?

**Comment by ChengJin01** [comment]
@megazone23,  normally there are two ways to determine the Java path from VM perspective: one from the environment variable (e.g. `export JAVA_HOME= ....`  on Linux or set `JAVA_HOME=...` or the environment variable setting in path on Windows); another one from the path of the JDK itself by obtaining the current directory of the JDK.

If the Hotspot happens to be in front of the OpenJ9 in the Java path, unexpected failure will occurs when loading native libraries in the wrong path.

**Comment by megazone23** [comment]
@ChengJin01, I was able to get it working correctly.  I deleted a global JAVA_HOME which was pointing to an Oracle JDK 8 directory.  I also think there is a problem with the way eclipse adds the OpenJ9 JDK as a Java runtime this does not happen with the hotspot version.  It seems I have to point it the the JRE directory (JDK directory/jre) vs the JDK directory.  If I point it to the JDK directory some jar files are missing and it does not work correctly.

Thank you for the help.

**Comment by ChengJin01** [comment]
@megazone23,  

>  It seems I have to point it the the JRE directory (JDK directory/jre) vs the JDK directory. If I point it to the JDK directory some jar files are missing and it does not work correctly.

Could you show me the steps of how to reproduce the issue with missing jar file & what jar files were missing with your setting? We'd like to learn what really happened in such case.

**Comment by megazone23** [comment]
@ChengJin01 , 

I tried it on a clean box and I am not able to reproduce the problem.  The jar files which were missing were missing was adding the JRE to eclipse was resource.jar, jsse.jar, charset.jar, and jce.jar.  The rest of the jar files were found.  But it must be some eclipse corruption in my other environment.  That environment has been upgraded over time with multiple versions of eclipse.

**Comment by ChengJin01** [comment]
@megazone23,

Given the problem is unreproducible on your side, I suggest to close the issue for now till the problem reoccurs.

**Comment by megazone23** [comment]
Thanks for the help.
