### ISSUE TITLE
JEP 193 Variable Handles

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1070]
https://bugs.openjdk.java.net/browse/JDK-8046183

This is an "Epic" to contain requirements for supporting this JEP on OpenJ9.

**Comment by DanHeidinga** [comment]
https://github.com/eclipse/openj9/blob/86885ce89654fc08f80d36f760b84c1202d00e93/jcl/src/java.base/share/classes/java/lang/invoke/VarHandle.java

Implemented
