### ISSUE TITLE
jdk15 reflect cache NoSuchFieldException: root

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10708]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/57
cmdLineTester_reflectCache_0
The failure is occurring across all platforms.
```
Testing: No reflect.cache cmdLine option. Reflect Cache test classes are in classpath.
Test start time: 2020/09/25 05:17:50 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/openjdkbinary/j2sdk-image/bin/java"   -Xdump -cp "/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64_aix_Nightly_testList_0/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/reflectCache/reflectCache.jar" test.reflectCache.Test_ReflectCache
Time spent starting: 205 milliseconds
Time spent executing: 217 milliseconds
Test result: FAILED
Output from test:
 [OUT] TEST FAILED
 [ERR] java.lang.NoSuchFieldException: root
 [ERR] 	at java.base/java.lang.Class.getDeclaredField(Class.java:909)
 [ERR] 	at test.reflectCache.Test_ReflectCache.main(Test_ReflectCache.java:39)
>> Success condition was not found: [Output match: testField is cached]
>> Required condition was not found: [Output match: testMethod is cached]
>> Failure condition was found: [Output match: TEST FAILED]
>> Failure condition was not found: [Output match: JVMJ9VM085]
```

**Comment by pshipton** [comment]
Changes from the previous build which didn't have this failure.

https://github.com/eclipse/openj9/compare/7591bf3...d638000
https://github.com/eclipse/openj9-omr/compare/b5e3f10...79c250b

**Comment by pshipton** [comment]
@tajila the problem shows up because the test was added to OpenJ9, but it indicates the reflection cache isn't working for jdk15.

@llxia can you pls help exclude this test for jdk15 until the problem can be resolved.

**Comment by pshipton** [comment]
Sorry, actually I think it just means the test needs to be fixed for jdk15.

**Comment by pshipton** [comment]
The field still exists, but the module access rules are preventing access.

**Comment by pshipton** [comment]
The problem is that Reflection is filtering out the fields for the reflection classes, so they are not accessible even with command line options. Either we have to accept this test can't be run on jdk15+ (permanent exclude) or, I'm tempted to add a system property to work around the reflection filters, which can be used for test purposes. @tajila thoughts?

https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/openj9/src/java.base/share/classes/jdk/internal/reflect/Reflection.java#L58

**Comment by pshipton** [comment]
Either way, I'm deferring this to the next milestone.

**Comment by tajila** [comment]
> I'm tempted to add a system property to work around the reflection filters, which can be used for test purposes. @tajila thoughts?

That could work, however I would like to explore other approaches before adding new properties. My preferred solution would be to use a native or unsafe. Something like:

```
			Field testField1 = testClass.getField("testField");
			Unsafe unsafe = DefineAnonClass2.getUnsafe();
			long rootOffset = unsafe.objectFieldOffset(Field.class, "root");
			
			Object rootObject1 = unsafe.getObject(testField1, rootOffset);
			
			Field testField2 = testClass.getField("testField");
			Object rootObject2 = unsafe.getObject(testField2, rootOffset);
```

This should minimize the maintenance required to support the test.
