### ISSUE TITLE
Boot jdk for jdknext must be jdk15 or 16

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10737]
With the latest jdknext build, the boot jdk must be jdk15 or 16. Pls update to jdk15.

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Linux x86
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0/OpenJDK15U-jdk_x64_linux_openj9_15_36_openj9-0.22.0.tar.gz
- [ ] cent7-x64-1 -> cent7-x64-6

Linux PPCLE
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0/OpenJDK15U-jdk_ppc64le_linux_openj9_15_36_openj9-0.22.0.tar.gz
- [ ] cent7-ppcle-1 -> cent7-ppcle-6

Linux 390
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0/OpenJDK15U-jdk_s390x_linux_openj9_15_36_openj9-0.22.0.tar.gz
- [ ] rhel7-390-1 -> rhel7-390-4

Linux Aarch64

AIX
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0/OpenJDK15U-jdk_ppc64_aix_openj9_15_36_openj9-0.22.0.tar.gz
- [ ] aix71-p8-1 -> aix71-p8-10

MacOS
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0/OpenJDK15U-jdk_x64_mac_openj9_15_36_openj9-0.22.0.tar.gz
- [ ] osx1014-x86-1 -> osx1014-x86-3

Windows
https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15%2B36_openj9-0.22.0/OpenJDK15U-jdk_x64_windows_openj9_15_36_openj9-0.22.0.zip
- [ ] win2012-x86-1 -> win2012-x86-6

**Comment by jdekonin** [comment]
I missed cent7-x64-4 as its offline.  I also didn't update Linux Aarch64 as there is nothing listed for 0.22.

**Comment by jdekonin** [comment]
This can be closed.
