### ISSUE TITLE
jcmd doesn't request system dumps with exclusive access

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10747]
jcmd requests system dumps without options, which means it defaults to without exclusive access. This can make the dumps unusable. The `Dump.system` option already takes a filename parameter. The command can be extended to take other parameters as well so the user can set any options. It may be worth making the default parameters `request=exclusive+prepwalk` if nothing is specified.

**Comment by kgibm** [comment]
Looking at this again, I'm not sure why I put `compact` in there. There are times when we might want to see trash in the tenured region, so perhaps `request=exclusive+prepwalk` might be a better default (I've also never fully understood whether `prepwalk` is important or not). I'm curious what you all decide if this is delivered and then I'll match Java Surgery, Liberty, and tWAS to that.

**Comment by pshipton** [comment]
You didn't put compact, you mentioned serial instead, which I don't think is needed with exclusive. I copied those options from the defaults for OOM. @dmitripivkine any comments?

**Comment by paulcheeseman** [comment]
I would vote for no `compact` option. As @kgibm says, sometimes it's very useful to be able to look at the garbage on the heap in system dumps, and it can easily be disregarded if you're not interested in it. The forced global GC associated with `compact` can also significantly increase the length of the pause after triggering the dump.

**Comment by dmitripivkine** [comment]
I also vote for no `compact` option. This operation might ruin heap in cases of it's corruption. Also as mentioned already it takes extra time. `prepwalk` is essential and should be sufficient enough.

**Comment by pshipton** [comment]
I'll work on this.

**Comment by keithc-ca** [comment]
> I'll work on this.

I think I'm just about done. ;-) I think the essential change is to add `":request=exclusive+prepwalk"` to the request in `DiagnosticUtils::doDump`.

**Comment by JasonFengJ9** [comment]
> The command can be extended to take other parameters as well so the user can set any options. 

This is the trick part which made me thinking.

**Comment by pshipton** [comment]
I haven't updated the help, and it's not tested yet, but this is what I'm thinking. https://github.com/eclipse/openj9/pull/10774

**Comment by pshipton** [comment]
@dmitripivkine @kgibm what about heap dumps? The default is `exclusive+compact+prepwalk`, should I set jcmd differently?

**Comment by pshipton** [comment]
Note a user can change the default settings via `-Xdump:<type>:defaults:...`, although only when starting the JVM.

**Comment by kgibm** [comment]
In my opinion, I think heapdumps should have a default without `compact` for the same reasons as core dumps. It might be related to some of the original tooling for heapdump analysis (e.g. HeapAnalyzer) not performing a virtual global GC upon loading a dump and therefore making it a bit more difficult to analyze heaps not under GC pressure, but this point seems to be moot now with Eclipse MAT.

**Comment by kgibm** [comment]
Thank you very much!
