### ISSUE TITLE
New hotFieldMarking code is incompatible with JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#10749]
PR https://github.com/eclipse/openj9/pull/10124 has introduced new frontend routines:
`TR_J9VMBase::reportHotField(int32_t reducedCpuUtil, J9Class* clazz, uint8_t fieldOffset,  uint32_t reducedFrequency)`
`TR_J9VMBase::isHotReferenceFieldRequired()`
`J9::ObjectModel::isHotReferenceFieldRequired()`
that need to be overridden for JITServer to extract the desired information from the client JVM

Moreover, the optimizer code has new code like
`if (!jitConfig->javaVM->memoryManagerFunctions->j9gc_hot_reference_field_required(jitConfig->javaVM))`
which should always go through a frontend routine.

**Comment by dmitry-ten** [comment]
I will work on this.
