### ISSUE TITLE
jdk16 Support supplementary characters in String case insensitive operations

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10758]
From JDK16 release notes:

Support supplementary characters in String case insensitive operations (JDK-8248655)

Case insensitive operations in java.lang.String class now correctly do case insensitive comparisons for supplementary characters (characters which have code point values over U+FFFF). For details, see the updates to the methods:

   - compareToIgnoreCase(String other)
   - equalsIgnoreCase(String other)
   - regionMatches(boolean ignoreCase, ...)

For example,

`"ud801udc00".equalsIgnoreCase("ud801udc28")`
returns true, because '𐐀' ("ud801udc00") and '𐐨' ("ud801udc28") are equal to each other character in case insensitive comparison.

**Comment by pshipton** [comment]
@tajila  fyi

**Comment by tajila** [comment]
@mikezhang1234567890 can you take a look at this

**Comment by mikezhang1234567890** [comment]
Looking into this.
