### ISSUE TITLE
ub16x64j96 takes long time to do checkout scm

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#10768]
It took [ub16x64j96](https://ci.eclipse.org/openj9/computer/ub16x64j96/) ~19 mins to do `checkout scm` ([Grinder link](https://ci.eclipse.org/openj9/view/Test/job/Grinder/1090/)).The process usually takes <15secs (see [the example on s390](https://ci.eclipse.org/openj9/view/Test/job/Grinder/1091/)). 

Below is the Jenkins console output. Unfortunately, Jenkins does not provide timestamp at this stage. We can see the time in Queue.

```
[Pipeline] checkout
The recommended git tool is: git
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/AdoptOpenJDK/openjdk-tests.git
Avoid second fetch
Checking out Revision 695be9d3db83957ed2d0e519998ba959c0680425 (origin/master)
 > git init /home/jenkins/workspace/Grinder@2/openjdk-tests # timeout=10
Using reference repository: /home/jenkins//openjdk_cache
Fetching upstream changes from https://github.com/AdoptOpenJDK/openjdk-tests.git
 > git --version # timeout=10
 > git --version # 'git version 2.15.0'
 > git fetch --tags --progress -- https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/AdoptOpenJDK/openjdk-tests.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 695be9d3db83957ed2d0e519998ba959c0680425 # timeout=10
Commit message: "Remove the logic of using master node to get user email (#1988)"
[Pipeline] load
[Pipeline] { (/home/jenkins/workspace/Grinder@2/openjdk-tests/buildenv/jenkins/JenkinsfileBase)
[Pipeline] }
[Pipeline] // load
```

`cent6-x64-6` also has this problem. https://ci.eclipse.org/openj9/view/Test/job/Grinder/1093/
 Internal xlinux machines are fine.

**Comment by pshipton** [comment]
Many UNB machines seem to be having problems connecting with jenkins this morning, not sure if this is related.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau fyi

**Comment by jdekonin** [comment]
If its more than 1 system that would imply its not likely a machine specific problem.  I'll see what information I can get from our UNB friends.

**Comment by llxia** [comment]
The machine ub16x64j96 seems back to normal now. https://ci.eclipse.org/openj9/view/Test/job/Grinder/1100/ (checkout scm took 56 secs)

**Comment by jdekonin** [comment]
Can this be closed?
