### ISSUE TITLE
DirectByteBufferTest fails with NullPointerException on openjdk8_openj9 SDK 

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#1077]
DirectByteBufferTest fails with NullPointerException on openjdk8_openj9 SDKs on, at least, x64 and ppc64le linux platforms. It works fine on hotspot, as well as openjdk9_openj9 SDKs.

**Testcase**
The test creates a array of ByteBuffer of length = 90, and allocates a new bytebuffer of ALLOC_SIZE=10 MBytes in each index of that array (by calling ByteBuffer.allocateDirect(..)) and de-refences immediately to allow GC to happen.

` public static void testDirectMemory() {
		try {
			int ITERATIONS = 90;
			int ALLOC_SIZE = 10000000; // 10Mbytes

			ByteBuffer[] bbStore = new ByteBuffer[ITERATIONS];
			Runtime r = Runtime.getRuntime();

			System.out.println("Total memory is: " + r.totalMemory());
			System.out.println("Initial free memory: " + r.freeMemory());
			int i;
			for (i = 0; i < ITERATIONS; i++) {

				System.out.println("Iteration: " + i + " Total memory is: "
						+ r.totalMemory() + "Initial free memory: "
						+ r.freeMemory());
				bbStore[i] = ByteBuffer.allocateDirect(ALLOC_SIZE);
				// *** dereference to allow GC
				bbStore[i] = null;
			}
			
			assertTrue(i==ITERATIONS);
			
		} catch (Exception e) {
			System.out.println("Caught Exception: \n" + e);
			fail("Exception::"+e);
		}
	} `

**Error stacktrace**
> 14:32:27 DBLT Caught Exception: 
> 14:32:27 DBLT java.lang.NullPointerException
> 14:32:27 DBLT testFailure: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest): Exception::java.lang.NullPointerException
> 14:32:27 DBLT junit.framework.AssertionFailedError: Exception::java.lang.NullPointerException
> 14:32:27 DBLT 	at junit.framework.Assert.fail(Assert.java:57)
> 14:32:27 DBLT 	at junit.framework.TestCase.fail(TestCase.java:227)
> 14:32:27 DBLT 	at net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest.testDirectMemory(DirectMemoryTest.java:49)
> 14:32:27 DBLT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 14:32:27 DBLT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 14:32:27 DBLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 14:32:27 DBLT 	at java.lang.reflect.Method.invoke(Method.java:498)
> 14:32:27 DBLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
> 14:32:27 DBLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
> 14:32:27 DBLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
> 14:32:27 DBLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
> 14:32:27 DBLT 	at junit.framework.TestResult.run(TestResult.java:125)
> 14:32:27 DBLT 	at junit.framework.TestCase.run(TestCase.java:129)
> 14:32:27 DBLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
> 14:32:27 DBLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
> 14:32:27 DBLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
> 14:32:27 DBLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
> 14:32:27 DBLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 14:32:27 DBLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 14:32:27 DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 14:32:27 DBLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
> 14:32:27 DBLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
> 14:32:27 DBLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
> 14:32:27 DBLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 14:32:27 DBLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 14:32:27 DBLT 	at java.lang.Thread.run(Thread.java:811)
> 14:32:27 DBLT testFinished: testDirectMemory(net.adoptopenjdk.test.gc.directbytebuffer.DirectMemoryTest)

**Build Links**
openjdk8_j9_systemtest_x86-64_linux : https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_x86-64_linux/5/
openjdk8_j9_systemtest_ppc64le_linux: https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk8_j9_systemtest_ppc64le_linux/3/

**Comment by Mesbah-Alam** [comment]
This is related to the following issue that was originally opened under openjdk-systemtest repo: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/67

**Comment by pshipton** [comment]
Please fix the test to determine from where the NullPointerException is coming from. The stack trace isn't helpful because its from the fail() line. I don't see how this test can throw NPE.

**Comment by pshipton** [comment]
nm, I tried this simple test case

```
Exception in thread "main" java.lang.NullPointerException
        at java.nio.Bits.reserveMemory(Bits.java:669)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:126)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
```

**Comment by pshipton** [comment]
Its throwing NPE because SharedSecrets.getJavaLangRefAccess() returns null. OpenJ9 doesn't setJavaLangRefAccess() for Java 8, only for Java 9.

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
@Mesbah-Alam Is it correct this test works in internal build?

**Comment by dmitripivkine** [comment]
@DanHeidinga We looked to this problem another day - I believe the reason for failure is differences in Class Library.

**Comment by pshipton** [comment]
@dmitripivkine It is correct the test works on IBM builds. OpenJ9 needs to be fixed to implement JavaLangRefAccess.tryHandlePendingReference() to resolve this problem.

**Comment by pshipton** [comment]
and we think JavaLangRefAccess.tryHandlePendingReference() is something that needs to be provided by gc.

**Comment by dmitripivkine** [comment]
@LinHu2016 Would you please take a look? We need an implementation similar then Java 9 for Java 8
