### ISSUE TITLE
OpenJ9 -Xlog is a different option than Hotspot -Xlog

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10799]
Hotspot introduced JEP 158 (see https://github.com/eclipse/openj9/issues/8195) which adds the -Xlog option. OpenJ9 already implements a -Xlog option for a different purpose https://www.eclipse.org/openj9/docs/xlog/.

When the Hotspot -Xlog is used with OpenJ9 it causes a `JVMJ9VM085W Malformed option:` error.

OpenJ9 now parses the JAVA_OPTIONS environment variable for compatibility, which may contain Hotspot options. This may cause problems when JAVA_OPTIONS contains options which are not compatible with OpenJ9.

What I suggest is 
- add an alternative form of the OpenJ9 `-Xlog:` option, such as `-XOSLog:`, and deprecate the existing `-Xlog:` option.
- introduce another option like `-XX:-LegacyXlogOption`, which could become default for OpenJ9 builds. It would stop processing of the OpenJ9 `-Xlog:` option. 
- when `-XX:-LegacyXlogOption` is enabled, add processing for the Hotspot `-Xlog` option. The simplest form of this is to ignore the option, or print a warning that `-Xlog` isn't a valid OpenJ9 option. More complicated processing could map forms of `-Xlog` to options that OpenJ9 understands, such as `-Xlog:gc` to `-verbose:gc`, and understanding the `file=` suboption as well in order to set ` -Xverbosegclog`.

**Comment by keithc-ca** [comment]
What's the motivation for `-XOSLog` or `-XOSlog`? What's `OS` in this context? Why uppercase?

**Comment by pshipton** [comment]
It is my suggestion for a better name, OpenJ9 shouldn't use `-Xlog` as it conflicts with the Hotspot `-Xlog` option. The OpenJ9 legacy -Xlog option controls which messages of various severity are logged to the Operation System (OS) log.

**Comment by keithc-ca** [comment]
`OS` doesn't seem so inappropriate now that I'm aware that it controls system logging (e.g. use of `syslog(3)` on Linux).
I'm not a fan of using upper-case here; my preference would be for `-Xsyslog`, or `-Xoslog`.

**Comment by pshipton** [comment]
Both seem fine to me. If you have a preference I can wait a day in case anybody else has an opinion, and then update the PR.

**Comment by keithc-ca** [comment]
My preference is `-Xsyslog`. Even on Windows, it makes sense to me, given that the environment variable `IBM_JAVA_SYSLOG_NAME` can influence the event source name.

**Comment by pshipton** [comment]
I went ahead and updated the PR.

**Comment by keithc-ca** [comment]
@pshipton Please also create a docs issue.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9-docs/issues/658

**Comment by pshipton** [comment]
This is resolved via https://github.com/eclipse/openj9/pull/10873 and https://github.com/eclipse/openj9/pull/11082
