### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com/ibm/jvm/Dump.JavaDumpImpl()I

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#108]
An java.lang.UnsatisfiedLinkError: com/ibm/jvm/Dump.JavaDumpImpl()I occurs in Java 9 when calling com.ibm.jvm.Dump.JavaDump(Dump.java:115).

I expect this is caused by #58 @JasonFengJ9

**Comment by pshipton** [comment]
By default the new module is loaded by the application loader. It can be changed to a bootstrap module, which will fix the UnsatisfiedLinkError. Otherwise the security checks in some of the classes won't work.

**Comment by pshipton** [comment]
See openj9-openjdk-jdk9/closed/make/common/Modules.gmk

**Comment by ben-walsh** [comment]
Class file is part of the openj9.jvm module. Determining if there is any significance to what position this additional module is placed in the BOOT_MODULES.

**Comment by pshipton** [comment]
Not sure if there is an order, but just in case openj9.sharedclasses should remain first since this one is related to class loading. Otherwise openj9.jvm can go 2nd or 3rd it shouldn't matter.

**Comment by JasonFengJ9** [comment]
Thanks @ben-walsh for the fix.
Just like to add a note about the module order within `Modules.gmk`. The generated `ModuleLoaderMap.java` organizes modules to be loaded by the bootstaploader in alphabet order within an array as following:
   private static final String[] BOOT_MODULES
        = new String[] { "com.ibm.management",
            "java.base",
             ...........
            "jdk.httpserver",
            "jdk.management",
            "openj9.sharedclasses"};
So the order of J9 modules in `openj9-openjdk-jdk9/closed/make/common/Modules.gmk` shouldn't matter.

**Comment by pshipton** [comment]
This is fixed now, closing the Issue.
