### ISSUE TITLE
Assertion failure at cphelp.c:96: ((((void *)0) != clazz->module)

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9#1081]
Reproduce:
1. Create a shared cache using
`java -Xshareclasses:name=Cache1 -version`
2. Running an application using -verbose and module path.
```
java -Xshareclasses:name=Cache1 -verbose --module-path /path_to_util_/utils.jar -m utils/org.openj9.test.ivj.Hanoi 2
class load: java/lang/Object from: jrt:/java.base
class load: java/lang/J9VMInternals from: jrt:/java.base
class load: com/ibm/oti/vm/VM from: jrt:/java.base
class load: java/lang/J9VMInternals$ClassInitializationLock from: jrt:/java.base
...
...
19:41:07.515 0x96b700j9vmutil(j9vrb).15     *   ** ASSERTION FAILED ** at cphelp.c:96: ((((void *)0) != clazz->module))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/01/31 14:41:07 - please wait.
```

**Comment by hangshao0** [comment]
The class being loaded is com/ibm/jvm/Trace. This class is found in the shared cache. It belongs to module openj9.jvm.


But I found targetPtr is NULL for package com.ibm.jvm in the following code (ModularityHashTables.c), it is not in the packageHashTable.

```
findModuleForPackageUTF8(J9VMThread *currentThread, J9ClassLoader *classLoader, J9UTF8 *packageName)
{
	...
	J9Module * foundModule = NULL;

	package.packageName = packageName;
	package.classLoader = classLoader;

	targetPtr = hashTableFind(classLoader->packageHashTable, &packagePtr);
	if (NULL != targetPtr) {
		foundModule = (*targetPtr)->module;
	}

	/* TODO add asserts here once the package definitions have been fixed */

	return foundModule;
}
```

**Comment by hangshao0** [comment]
I have added -Xtrace:print={module.2-3}. 
```
java -Xtrace:print={module.2-3} --module-path /path_to_util_/utils.jar/utils.jar -m utils/org.openj9.test.ivj.Hanoi 2
...
20:20:41.714 0xd2b700  module(j9scar).2        - add package com/sun/org/apache/xerces/internal/impl/dtd for module java.xml
20:20:41.714 0xd2b700  module(j9scar).3        - JVM_DefineModule() define module java.xml
...
```
I don't see module openj9.jvm is defined or package com/ibm/jvm is added. It is the same with or without "-Xshareclasses" option. I guess module openj9.jvm is not resolved in this case.

**Comment by JasonFengJ9** [comment]
`openj9.jvm` is loaded as a boot module. It is loaded when running -version:
````
21:36:03.680 0x2137e00  module(j9scar).2        - add package com/ibm/jvm for module openj9.jvm
21:36:03.680 0x2137e00  module(j9scar).3        - JVM_DefineModule() define module openj9.jvm
````

**Comment by JasonFengJ9** [comment]
@hangshao0 can you find out what class was being loaded and where it comes from (share cache?) when the ASSERTION occurred?

**Comment by hangshao0** [comment]
Looking at the code here:
https://github.ibm.com/runtimes/openj9-openjdk-jdk9/blob/e27ea6d6dea45cd20c9e655801ee87ce508b250b/jdk/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java#L226-L264

If running with -version, all system modules will be resolved. If running with -m where there is a main module, not all system modules will be necessarily resolved. 

I have added some printf inside ModuleBootstrap.java, module openj9.jvm is not resolved when running with -m. 

The assertion goes away if I add "--add-modules ALL-SYSTEM" or "--add-modules openj9.jvm" in the CML.

So I believe shared cache should not return the class if it is from an unresolved module.

**Comment by DanHeidinga** [comment]
@hangshao0 Has a pull request been opened for this issue or is more investigation required?

**Comment by hangshao0** [comment]
A pull request will be opened shortly. I am still testing the fix.
