### ISSUE TITLE
jdk14+: jdk_foreign testcases intermittent failures with openj9

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#10828]
Testcases:

java/foreign/TestByteBuffer.java
java/foreign/TestLayoutConstants.java

JDK14+:
09:19:17 System.getProperty('java.fullversion')=14+36-202003272052
09:19:17 JRE 14 Linux amd64-64-Bit Compressed References 20200327_17 (JIT enabled, AOT enabled)
09:19:17 OpenJ9 - 76a961cb3
09:19:17 OMR - 2016086da
09:19:17 JCL - 77c5e421a5 based on jdk-14+36

Details: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1702

**Comment by pshipton** [comment]
@sophia-guo What suite do these run in? Do these tests still exist in Java 15 (Java 14 is obsolete)? I don't see them in sanity.openjdk.

**Comment by sophia-guo** [comment]
Yes, it's for jdk14+. Test should be run by target jdk_foreign under sanity. Though tests have been excluded.

https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk15-openj9.txt#L308

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk15_j9_sanity.openjdk_x86-64_linux/

**Comment by pshipton** [comment]
TestByteBuffer is an OOM, which is likely a machine problem. TestLayoutConstants doesn't have enough data.

Running these in a grinder.
https://ci.eclipse.org/openj9/job/Grinder/1104
https://ci.eclipse.org/openj9/job/Grinder/1105

**Comment by pshipton** [comment]
The grinders didn't work as the tests were not found, not sure what I'm doing wrong. Trying again with the exclude removed.

https://ci.eclipse.org/openj9/job/Grinder/1107

**Comment by sophia-guo** [comment]
TARGET is jdk_custom instead of jck_custom.

**Comment by smlambert** [comment]
Grinder reruns with updated jdk_custom target:
test/jdk/java/foreign/TestByteBuffer.java -> https://ci.eclipse.org/openj9/job/Grinder/1109
test/jdk/java/foreign/TestLayoutConstants.java -> https://ci.eclipse.org/openj9/job/Grinder/1110

**Comment by pshipton** [comment]
Thanks. Both grinders passed. I'm not sure how intermittent the failures were. It's possible they were machine issues that only occur on certain machines at Adopt. Or there may have been problems which are now fixed. I suggest we include them and see how it goes.

https://github.com/AdoptOpenJDK/openjdk-tests/pull/2001

**Comment by pshipton** [comment]
Tests are running again, closing this until we see a problem.
