### ISSUE TITLE
Windows build failed to delete workspace

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10834]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/878
```
20:57:42  Waiting for next available executor on ‘ci.role.build&&hw.arch.x86&&sw.os.windows’
21:50:41  Running on win2012-x86-5 in F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Personal
[Pipeline] {
[Pipeline] timeout
21:50:41  Timeout set to expire in 5 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
21:50:41  [WS-CLEANUP] Deleting project workspace...
21:50:41  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
21:50:55  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Personal\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] cleanWs
21:50:55  [WS-CLEANUP] Deleting project workspace...
21:50:55  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
21:50:58  Cannot delete workspace: null
21:50:58  Option not to fail the build is turned on, so let's continue
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
ERROR: Cannot delete workspace: Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_Personal\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
More, same machine https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/737

This one built the JVM but then `AccessDeniedException: F:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_OMR`
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_OMR/742

Disabled win2012-x86-5

**Comment by jdekonin** [comment]
I went on the system but no such directory exists.  Nothing for OMR either.  I rebooted and removed everything in workspace directory manually.

These 2 failures are quite far apart with many passing jobs in between, so its not like the machine isn't working.  DeleteWs has always been questionable for windows, I wonder if we just need to adjust the timeout between retries?  What do you think @AdamBrousseau @vsebe ?

**Comment by jdekonin** [comment]
Here is another oddity.  We have a job that finds all the job a specific node was used in.  Neither of those failures show up in the listing.  I know it finds passing and unstable jobs, I had thought it listed machine failure type jobs as well.  @vsebe thoughts there??

https://ci.eclipse.org/openj9/job/Node-Build-History/11/console

**Comment by jdekonin** [comment]
I brought the machine back online btw.

**Comment by pshipton** [comment]
Closing until it's seen again.

**Comment by vsebe** [comment]
>We have a job that finds all the job a specific node was used in. Neither of those failures show up in the listing.

@jdekonin Node-Build-History relies on job description. The jobs fail before adding node to description, thus they do are not listed.

**Comment by pshipton** [comment]
Another problem with win2012-x86-5 last night.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_Nightly/533
`22:12:21  Cannot contact win2012-x86-5: java.lang.InterruptedException`

**Comment by pshipton** [comment]
I don't think win2012-x86-5 is health, I've disabled it.

**Comment by pshipton** [comment]
See https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/883/console, it's just hanging on this machine.

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/883/
```
00:00:20.743  Timeout set to expire in 5 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] cleanWs
01:58:15.545  win2012-x86-5 was marked offline: Disconnected by peter_shipton@ca.ibm.com
```
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_Nightly/533/console
```
00:33:02.759  Cannot contact win2012-x86-5: java.lang.InterruptedException
05:24:24.631  Cancelling nested steps due to timeout
05:24:24.695  Sending interrupt signal to process
05:24:44.696  After 20s process did not stop
[Pipeline] sh
05:25:24.631  Body did not finish within grace period; terminating with extreme prejudice
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
05:29:54.834  [WS-CLEANUP] Deleting project workspace...
05:29:54.835  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
10:00:14.605  Cancelling nested steps due to timeout
[Pipeline] }
10:00:14.610  Cannot delete workspace: null
10:00:14.610  Option not to fail the build is turned on, so let's continue
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
Timeout has been exceeded
Finished: ABORTED
```
Since Joe already rebooted, not sure that would help. Although I see at the moment it is trying to reconnect to Jenkins and it is taking a very long time.
Looking at the cleanWs() steps. Currently we do
```
// disableDeferredWipeout also requires deleteDirs. See https://issues.jenkins-ci.org/browse/JENKINS-54225
cleanWs notFailBuild: true, disableDeferredWipeout: true, deleteDirs: true
```
We should see how often it fails. Perhaps also try going back to simple `cleanWs()`.
I have removed build & test labels for now so we can bring it online to allow debug builds to run.

**Comment by AdamBrousseau** [comment]
Discussed on our infra call. Since this has only happened in compile, for the time being we'll remove the build label and leave it as a test machine and see if it reproduces.

**Comment by pshipton** [comment]
Hanging on win2012-x86-5, disabled it again. 
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_Personal/555/console

**Comment by AdamBrousseau** [comment]
Unfortunately no timestamps on that test build. But build overall took just under 4 hours. Hang appears to be on the checkout step as soon as it grabs the node. So we either have multiple issues, a one off, or a larger problem with this machine. I would lean towards the larger machine problem. 

I will follow up with @jdekonin about having the machine rebuilt.

**Comment by pshipton** [comment]
We'd seen this before https://github.com/eclipse/openj9/issues/10834#issuecomment-706279082

+1 to rebuilding the machine.

**Comment by pshipton** [comment]
Although no timestamps on the job, there is a timestamp when it was started.
`12:45:36  Starting building: Test_openjdk11_j9_sanity.functional_x86-64_windows_Personal #555`
and I stopped it at ~4:40pm.

**Comment by jdekonin** [comment]
I don't see how cloning the machine is going to make a difference.  This system was recently recreated based on an image of a previous system. win2012-x86-1 -> win2012-x86-4 and win2012-x86-6 were created with this same image and they don't have this same problem.  There were 6 cl.exe and 14 bash.exe processes running on the system, I had to forcibly reboot the machine.

**Comment by pshipton** [comment]
Just seems strange we are consistently seeing problems on this machine. Perhaps something got messed up, making it different from the others.

**Comment by pshipton** [comment]
It seems the `Cannot delete workspace` and hangs migrated to win2012-x86-4. This implies it's not a machine problem but perhaps some job is leaving the machine in a bad state. 

The latest, which occurred last night (Oct 20), `Cannot delete workspace`:
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/909

Through the weekend, these are all hangs. The machine was taken down on Monday which has fixed this.
Oct 16:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_1/139/console
Oct 17:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly_testList_0/140/console
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_Nightly/541/console
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Release/44/console
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_extended.functional_x86-64_windows_Release_testList_1/9/console
Oct 18:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-32_windows_Personal_mauveLoadTest/22/console

**Comment by AdamBrousseau** [comment]
>The machine was taken down on Monday which has fixed this.

So not a problem on number 4 anymore? I was going to point out that this was the machine we used to take an image for number 5 replacement. Perhaps there was something about that process that fooeys the J drive?

**Comment by pshipton** [comment]
Rebooting 4 on Monday fixed the hang problems we were seeing earlier. We still got a `Cannot delete workspace` failure last night, and today I've seen `Cannot delete workspace` on 3.

**Comment by pshipton** [comment]
Actually I took 3 offline because it seems to need a reboot, there were a couple of `Cannot delete workspace` jobs in a row and I wanted the PR build to go through.

**Comment by jdekonin** [comment]
I rebooted and re-enabled 3

**Comment by jdekonin** [comment]
Has this been seen lately?

**Comment by pshipton** [comment]
I'm not sure, builds from Friday, Sat, Sun contain numerous failures due to bad OpenJ9/OMR code, I didn't search them for other problems. Mon night the builds were disabled. Remains to be seen if we'll have builds enabled for tonight.

**Comment by gacholio** [comment]
Seen repeatedly today in the linked PR build.

**Comment by AdamBrousseau** [comment]
The one in the PR above is on machine#5.
Not sure what else to do here. We should remove the dup cleanWs command that happens on Win/zOS
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/build.groovy#L62
We already do it on all platforms [here](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/build.groovy#L578)

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/783
```
05:12:19  [WS-CLEANUP] Deleting project workspace...
05:12:19  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
05:12:19  [WS-CLEANUP] done
[Pipeline] }
[Pipeline] // node
[Pipeline] stage
[Pipeline] { (Queue)
[Pipeline] timeout
05:12:19  Timeout set to expire in 10 hr
[Pipeline] {
[Pipeline] node
05:12:19  Running on win2012-x86-3 in F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR
[Pipeline] {
[Pipeline] timeout
05:12:19  Timeout set to expire in 5 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
05:12:19  [WS-CLEANUP] Deleting project workspace...
05:12:19  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
05:12:27  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
[Pipeline] cleanWs
05:12:27  [WS-CLEANUP] Deleting project workspace...
05:12:27  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
05:12:30  Cannot delete workspace: null
05:12:30  Option not to fail the build is turned on, so let's continue
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
ERROR: Cannot delete workspace: Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Finished: FAILURE
```

**Comment by AdamBrousseau** [comment]
That build is already cleaned up. I'm wondering if we could build a retry around the cleanWs(s) or some kind of try catch with a different kind of cleanup (like an `rm`). If you're posting here each time this happens, it seems like it doesn't happen too often. Just wondering what priority to assign to making a change here.

**Comment by AdamBrousseau** [comment]
Also, last build on that machine
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/782/console
```
00:42:40.968  [WS-CLEANUP] Deleting project workspace...
00:42:40.969  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
00:43:24.705  Cannot delete workspace: null
00:43:24.705  Option not to fail the build is turned on, so let's continue
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by pshipton** [comment]
It was happening more often earlier, but not lately. I'll be sure to document any more I find.

**Comment by pshipton** [comment]
This one caused OMR acceptance to fail.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/786
```
05:13:01  Still waiting to schedule task
05:13:01  Waiting for next available executor on ‘ci.role.build&&hw.arch.x86&&sw.os.windows’
06:41:55  Running on win2012-x86-3 in F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR
[Pipeline] {
[Pipeline] timeout
06:41:55  Timeout set to expire in 5 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
06:41:55  [WS-CLEANUP] Deleting project workspace...
06:41:55  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
06:42:00  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-32_windows_OMR\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by pshipton** [comment]
Another OMR acceptance blocker.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_OMR/786
```
05:51:18  [WS-CLEANUP] Deleting project workspace...
05:51:18  [WS-CLEANUP] Deferred wipeout is disabled by the job configuration...
05:51:25  ERROR: Cannot delete workspace :Unable to delete 'F:\Users\jenkins\workspace\Build_JDK8_x86-64_windows_OMR\build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_OMR/804/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/1026/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/1047/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_OMR/819/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/1087/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_OMR/827/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/1102/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_Personal/756/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_OMR/842/console

**Comment by jdekonin** [comment]
https://github.com/eclipse/openj9/pull/11881 is ready for your review and should address this problem.

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/pull/11881 is merged, I'll tentatively close this.
