### ISSUE TITLE
aarch64 pltest j9vmem_test_reserveExecutableMemory crash 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10843]
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.functional_aarch64_linux/8/
cmdLineTester_pltest_j9sig_ext_0 
test-aws-rhel76-armv8-2

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.functional_aarch64_linux/8 (0.23.0 M2 build)
cmdLineTester_pltest_0
test-aws-rhel76-armv8-6
```
 [ERR] Starting test j9vmem_test_reserveExecutableMemory
 [ERR]   function length = 8
 [ERR]   *memPtr: 0x52800020
 [ERR]   About to call dynamically created function, pageSize=0x10000...
 [ERR] 
 [ERR] An unhandled error (72) has occurred.
 [ERR] J9Generic_Signal_Number=00000048
 [ERR] Signal_Number=00000004
 [ERR] Error_Value=00000000
 [ERR] Signal_Code=00000001
 [ERR] Handler1=000000000043DC60
 [ERR] Handler2=0000FFFF8AA49288
 [ERR] R0=0000000000000000
 [ERR] R1=FABF6C945AF27400
 [ERR] R2=0000000000000000
 [ERR] R3=0000FFFFD88C8DE0
 [ERR] R4=0000000000000002
 [ERR] R5=0000000000000000
 [ERR] R6=00000000FFFFFFBB
 [ERR] R7=0000000000000000
 [ERR] R8=0000000000000040
 [ERR] R9=0000000000000001
 [ERR] R10=0000FFFFD88C8D70
 [ERR] R11=0000000000000001
 [ERR] R12=0000FFFFD88C8BF1
 [ERR] R13=FFFFFFFFFFFFFFFF
 [ERR] R14=0000000000000005
 [ERR] R15=0000000000000030
 [ERR] R16=0000000000000000
 [ERR] R17=0000FFFF8A76F300
 [ERR] R18=0000000000000002
 [ERR] R19=0000FFFFD88C9730
 [ERR] R20=0000FFFF83BC0000
 [ERR] R21=0000FFFFD88C9228
 [ERR] R22=000000000042D1F0
 [ERR] R23=0000FFFFD88C91E0
 [ERR] R24=0000000000000008
 [ERR] R25=000000001C085978
 [ERR] R26=000000001C085950
 [ERR] R27=0000000000450490
 [ERR] R28=0000000000000000
 [ERR] R29=0000FFFFD88C9170
 [ERR] R30=000000000042FF48
 [ERR] R31=0000FFFFD88C9170
 [ERR] PC=0000FFFF83BC0000
 [ERR] SP=0000FFFFD88C9170
 [ERR] PSTATE=0000000060000000
 [ERR] V0=0000000000000000
 [ERR] V1=1c08c610b71bac91
 [ERR] V2=000000001c08c610
 [ERR] V3=0000000000000008
 [ERR] V4=ffffffffffffffff
 [ERR] V5=0000000000000001
 [ERR] V6=0000000100000001
 [ERR] V7=ffffffffffffffff
 [ERR] V8=0000000000000000
 [ERR] V9=0000000000000000
 [ERR] V10=0000000000000000
 [ERR] V11=0000000000000000
 [ERR] V12=0000000000000000
 [ERR] V13=0000000000000000
 [ERR] V14=0000000000000000
 [ERR] V15=0000000000000000
 [ERR] V16=fffffffcfffffffc
 [ERR] V17=0000010000000100
 [ERR] V18=0101010101010101
 [ERR] V19=0000000c0000000c
 [ERR] V20=0000000800000008
 [ERR] V21=0000000400000004
 [ERR] V22=0000001000000010
 [ERR] V23=0000010000000100
 [ERR] V24=0000010000000100
 [ERR] V25=0000010000000100
 [ERR] V26=0000004d0000004c
 [ERR] V27=0000006500000064
 [ERR] V28=0000006d0000006c
 [ERR] V29=0000004100000040
 [ERR] V30=0000003d0000003c
 [ERR] V31=0000003900000038
```

**Comment by pshipton** [comment]
@knn-k

**Comment by knn-k** [comment]
Reproduced the crash with `j9vmem_test_reserveExecutableMemory` locally.

**Comment by knn-k** [comment]
I believe this is a test case error.

The test case calls `function()` after calling `memcpy(memPtr, ...)` without flushing the CPU cache.
https://github.com/eclipse/openj9/blob/971cc381889b44651f9cf9f1949281f1a7023acc/runtime/tests/port/j9vmemTest.c#L1705-L1711

There is no function available for flushing the CPU cache in the port library, as far as I know.

**Comment by andrew-m-leonard** [comment]
This re-occurred on GA jdk-11.0.9+11_openj9-0.23.0 : https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.functional_aarch64_linux/19/consoleFull

**Comment by knn-k** [comment]
As I wrote above, I believe this is a test case error.
I wonder why it used to pass before.

**Comment by LongyuZhang** [comment]
Tested cmdLineTester_pltest_0 on the same machine test-aws-rhel76-armv8-6 five times: 
- 1/5 passed, https://ci.adoptopenjdk.net/job/Grinder/4289/
- 4/5 failed with the same error as this issue: https://ci.adoptopenjdk.net/job/Grinder/4290/ - 4293

so it looks like an intermittent failure.

In addition, @llxia noticed cmdLineTester_pltest_0 is also running on other platforms, when checking the nightly on x86-64_linux and s390x_linux, it all passed, e.g.:
- Internal_Jenkins/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/490 - 500
- Internal_Jenkins/Test_openjdk11_j9_sanity.functional_s390x_linux_Nightly/546 - 556

@knn-k, is it because some special setting for AArch that requires CPU Cache flusing maybe? In addition, do we need to temporarily disable these two tests? I have a draft PR for it. Thanks.

**Comment by knn-k** [comment]
If I understand it correctly, Power architecture requires flushing the instruction cache in this case.  I wonder why the test works on p.

I found an OMR API for flushing the instruction cache, `omrcpu_flush_icache()`.  It needs to be implemented for AArch64.

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/5655 and #11098.
