### ISSUE TITLE
JEP 285 Spin-Wait Hints

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1085]
https://bugs.openjdk.java.net/browse/JDK-8147832

This is an "Epic" to contain requirements for supporting this JEP on OpenJ9.

**Comment by DanHeidinga** [comment]
Method added to Thread: https://github.com/eclipse/openj9/blob/4ecf784684dad533a04192647c5fb3ca7e8864da/jcl/src/java.base/share/classes/java/lang/Thread.java#L1056

FastJNI implementation:
https://github.com/eclipse/openj9/blob/26f8c7edb1fe37253d001243c0ce14473334d07f/runtime/vm/FastJNI_java_lang_Thread.cpp#L87

Interpreter INL:
https://github.com/eclipse/openj9/blob/11c1a878d7034ef62b6be560acda2683f9720754/runtime/vm/BytecodeInterpreter.hpp#L2480

Closing as this is implemented
