### ISSUE TITLE
Incomplete dumps since openj9-0.21.0

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#10878]
Hello,

We found that OpenJ9 is generating incomplete dumps since openj9-0.21.0 release.

To reproduce this issue, here is a sample code:

```
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class IBMDump {
      
      static Sample[] samples;

      public static void main(String[] args) throws ReflectiveOperationException {
            samples = new Sample[10000];
            for (int i = 0; i < samples.length; i++) {
                  samples[i] = new Sample();
            }
            System.out.println(dumpJavaHeap());
      }
      public static final File dumpJavaHeap() throws ReflectiveOperationException {
            return new File((String) Class.forName("com.ibm.jvm.Dump").getMethod("systemDumpToFile").invoke(null));
      }
      
      static class Sample {
            final List<String> stringList = new ArrayList<>(1000);
      }
}
```

This sample allocates some objects and then it generates a dump, which we then analyze using Eclipse MAT (with the IBM plug-in needed to read OpenJ9 dumps).

With openj9-0.20.0, we get the expected results, for example we have a count of 10,000 IBMDump$Sample items:

```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200416_544 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)
JVMDUMP034I User requested System dump using 'e:\tmp\core.20201012.104041.7596.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
JVMDUMP010I System dump written to e:\tmp\core.20201012.104041.7596.0001.dmp
```
![image](https://user-images.githubusercontent.com/17863217/95921338-66342d00-0db1-11eb-96ed-f78a3ae441e4.png)

But with openj9-0.21.0, we have only 2,178 IBMDump$Sample items:

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200715_679 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
JVMDUMP034I User requested System dump using 'e:\tmp\core.20201012.104058.19664.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
JVMDUMP010I System dump written to e:\tmp\core.20201012.104058.19664.0001.dmp
e:\tmp\core.20201012.104058.19664.0001.dmp
```
![image](https://user-images.githubusercontent.com/17863217/95921452-9c71ac80-0db1-11eb-89e3-2f21c0ef7f11.png)

And same issue with OpenJ9 from AdoptOpenJDK 11 built dated 12th of October 2020:

```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment Openj9 (build 11.0.9+10-202010112342)
Eclipse OpenJ9 VM Openj9 (build master-ad71f4fa5, JRE 11 Windows 10 amd64-64-Bit 20201011_517 (JIT enabled, AOT enabled)
OpenJ9   - ad71f4fa5
OMR      - cfd55882d
JCL      - cf49ddabb9 based on jdk-11.0.9+10)
JVMDUMP034I User requested System dump using 'e:\tmp\core.20201013.102345.10756.0001.dmp' through com.ibm.jvm.Dump.systemDumpToFile
JVMDUMP010I System dump written to e:\tmp\core.20201013.102345.10756.0001.dmp
```
![image](https://user-images.githubusercontent.com/17863217/95921861-5e28bd00-0db2-11eb-98fa-eb5e62a2fa7d.png)

 We are still missing about 3/4 of items in the dump.

Once maybe worthy detail is this line found in Eclipse MAT's log:

`!MESSAGE Corrupt data reading objects at null : J9DDRCorruptData [as=minidump : 0 Message: DDR structures in the core file are out of sync with the code base] from heaps from Java runtime at 0x1fa27ee9a00 `

Would it be possible to restore consistent dumps? Have we missed a change for which some special JVM parameters would be needed to have full dump ?

Kind regards,
Alexandre

**Comment by pshipton** [comment]
Pls try setting the option `-Xdump:system:defaults:request=exclusive+prepwalk` to see if this fixes the problem. If this is the solution this can be done programmatically as well. The default is `request=serial` which does not guarantee the heap is in a walkable state, you may just have been getting lucky.

@dmitripivkine fyi

**Comment by pshipton** [comment]
The other possibility is the IBM plugin is out of date. I don't expect it to get updated, but there is a way to update it manually, see https://github.com/eclipse/openj9/issues/7091#issuecomment-532323843. Someone is looking at updating Eclipse MAT to use the running JVM instead of depending on an out of date IBM plugin. Not sure when MAT would get this update however.

**Comment by avermeer** [comment]
Hello @pshipton,

Thank you very much for your answers: the use of `-Xdump:system:defaults:request=exclusive+prepwalk` option indeed solves the issue for us !

Kind regards,
Alexandre

**Comment by pshipton** [comment]
In order to do it programmatically without changing the defaults, the API is com.ibm.jvm.Dump.triggerDump(). Changing the defaults to include exclusive for `events=gpf+abort+traceassert+corruptcache` according to the docs: "acquiring locks during a crash can be problematic".

Also note that dumps requested via jcmd are modified in the next release to default to `request=exclusive+prepwalk`, and you can set different options on the `jcmd` command line.
