### ISSUE TITLE
different error message (IBM and OpenJ9) when loading library j9unresolved with flag -XX:-LazySymbolResolution

### ISSUE THREAD

**Issue by OscarQQ** [eclipse/openj9#10896]
test case:
```
public class Load {
public static void main(String[] args) throws Throwable {
System.loadLibrary("j9unresolved");
}
}
```
**OpenJ9 Version** console output
```
Output from test:
21:09:13   [OUT] Setup complete
21:09:13   [OUT] j9unresolved (Not found in java.library.path)
```
**IBM Version** gives `j9unresolved (path/amd64/compressedrefs/libj9unresolved.so: undefined symbol: dontResolveThis)`

This has been an issue when porting tests into OpenJ9
related: backlog/issues/399

**Comment by tajila** [comment]
@JasonFengJ9 Can you please take a look at this

**Comment by JasonFengJ9** [comment]
Sure, will look into it.

**Comment by JasonFengJ9** [comment]
IBM and OpenJ9 `Java 8` have same error message against the testcase supplied (https://github.com/eclipse/openj9/issues/10896#issue-722038645) with the command line option `-XX:-LazySymbolResolution` specified.

**OpenJ9 Java 8**
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200728_727 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)

Exception in thread "main" java.lang.UnsatisfiedLinkError: j9unresolved (Not found in java.library.path)
	at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1471)
	at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1423)
	at java.lang.System.loadLibrary(System.java:559)
```

**IBM Java 8**
```
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20201014_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201013_457371 (JIT enabled, AOT enabled)
OpenJ9   - e3ae38e
OMR      - c62c8ad
IBM      - 7d532c8)
JCL - 20200930_02 based on Oracle jdk8u271-b09

Exception in thread "main" java.lang.UnsatisfiedLinkError: j9unresolved (Not found in java.library.path)
	at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1460)
	at java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1411)
	at java.lang.System.loadLibrary(System.java:589)
```

@OscarQQ what's the IBM Java along with the command line option that produced `j9unresolved (path/amd64/compressedrefs/libj9unresolved.so: undefined symbol: dontResolveThis)`?

**Comment by pshipton** [comment]
You have to run with `-XX:-LazySymbolResolution`, and the j9unresolved library needs to be on the library path.

libj9unresolved.so or the platform specific variant is part of the test image download you can get from OpenJ9 or Adopt builds. I wrote a simple test as follows and ran it.

`java -Djava.library.path=/home/peter/Downloads/test-images/openj9 -XX:-LazySymbolResolution Load`

```
public class Load {
public static void main(String[] args) throws Throwable {
System.loadLibrary("j9unresolved");
}
}
```
IBM Java result:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: j9unresolved (/home/peter/pxa6480sr7-0624/jre/lib/amd64/compressedrefs/libj9unresolved.so: undefined symbol: dontResolveThis)`

OpenJ9 result:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: j9unresolved (Not found in java.library.path)`

If you run without `-XX:-LazySymbolResolution` or with `-XX:+LazySymbolResolution` when there is no exception.

**Comment by pshipton** [comment]
The concern here is that OpenJ9 builds aren't providing the detail for why a library can't be loaded, instead giving a misleading error `Not found in java.library.path`.

**Comment by JasonFengJ9** [comment]
After some offline investigation with @pshipton , it was determine the message difference was due to the package issue, IBM internal builds has `libj9unresolved.so` at `jre/lib/amd64/compressedrefs`.
Will look into how to get `better` error message without the native library presence in such path.

**Comment by pshipton** [comment]
To put it another way, you get a better message when the library is loaded from the `com.ibm.oti.vm.bootstrap.library.path` instead of the `java.library.path`.

**Comment by JasonFengJ9** [comment]
**Update:**
The `better` message was generated in first loading then overwritten by later also failed attempt as following code snippet:
https://github.com/eclipse/openj9/blob/e9d73ae0f63d036ab839dfdd204b45320bf24ee0/jcl/src/java.base/share/classes/java/lang/ClassLoader.java#L1929-L1937
The first `UnsatisfiedLinkError` when loading via `java.library.path` has `better` error message:
```
java.lang.UnsatisfiedLinkError: j9unresolved (/team/tbd/libj9unresolved.so: undefined symbol: dontResolveThis)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1748)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1694)
	at java.base/java.lang.System.loadLibrary(System.java:603)
```
Next loading attempt via `com.ibm.oti.vm.bootstrap.library.path` has the error message in question:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: j9unresolved (Not found in java.library.path)
	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1748)
	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1697)
	at java.base/java.lang.System.loadLibrary(System.java:603)
```
I think JVM should attempt loading native libraries coming with itself first, then try the path specified via `java.library.path` for non-bootstrap classloaders.
