### ISSUE TITLE
Not able to create SCC using OPENJ9_JAVA_OPTIONS 

### ISSUE THREAD

**Issue by anjanitsip** [eclipse/openj9#10895]
I am using docker image 

adoptopenjdk/openjdk11-openj9:jdk-11.0.8_10_openj9-0.21.0-debian

and passing JVM arguments using ENV variable OPENJ9_JAVA_OPTIONS '

 OPENJ9_JAVA_OPTIONS: "-XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport -Xshareclasses:cacheDir=/cache,verbose,checkURLTimestamps,persistent -Xscmx300M"

But it is not creating SCC

 java -Xshareclasses:listAllCaches
JVMSHRC005I No shared class caches available

I also need help to create multi layer SSC for docker container on K8s

**Comment by pshipton** [comment]
You need to run `java -Xshareclasses:cacheDir=/cache,listAllCaches`

**Comment by pshipton** [comment]
@hangshao0

**Comment by pshipton** [comment]
For a multi layer SCC, create each layer with the `createLayer` -Xshareclasses option.  Alternatively, you can create each layer by specifying `layer=<number>`  starting from 0, and incrementing each time.
https://www.eclipse.org/openj9/docs/xshareclasses/#layer

**Comment by anjanitsip** [comment]
Thank you.
One more doubt , I have - docker image also create shared cache. How it is useful for microservices?
And we can add class path resource (jars) into the cache. It is it right thing do ?
 
[INFO] Container entrypoint set to [java, -XX:MaxRAMPercentage=75.0, -XX:InitialRAMPercentage=20.0, -Xquickstart, -Xtune:virtualized, -Xscmx512M, -Xshareclasses:cacheDir=/cache,name=conductor,verbose,checkURLTimestamps,persistent,restrictClasspaths,createLayer, -cp, /app/resources:/app/classes:/app/libs/*, *.ConductorApplication]


I am using jib to build the docker image, so how can enable multilayer SCC with jib.

**Comment by pshipton** [comment]
> Base openj9 docker image also create shared cache. How it is useful for microservices?

Any shared cache created with default options is a layer zero cache. Additional layered caches can be built on top, one by one, using higher layer numbers. The shared cache improves startup time, due to the AOT (JIT precompiled code), and other precomputed data and hints stored in the cache. It also reduces overall memory usage if more than one JVM is running at the same time, since some of the class data is shared between processes.

> can add class path resource (jars) into the cache. It is it right thing do ?

There isn't any support for storing/reading resources for the shared cache. The JVM will continue to read from the resource jars on disk. Storing resources in the cache wouldn't result in any savings.

> how can enable multilayer SCC with jib

I'm not familiar with jib.

**Comment by anjanitsip** [comment]
While running docker container with (non root user) nobody/nogroup (user/group). I am getting below error - 

JVMSHRC226E Error opening shared class cache file
JVMSHRC336E Port layer error code = -102
JVMSHRC337E Platform error message: Permission denied
JVMSHRC840E Failed to start up the shared cache.
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified

**Comment by pshipton** [comment]
I'm guessing you are using default options. By default the shared cache is put into the user's home directory. Either this directory has to be setup correctly and be writable, or you can specify another location for the shared cache. To do this equivalent to the default options use `-Xshareclasses:cacheDir=<some dir>,bootClassesOnly`. If you want to attempt to share more classes, leave off the `bootClassesOnly` part.

**Comment by anjanitsip** [comment]
I am using below configuration to create the container - 

Using non root user (nobody) and jvm flags - 

<container>
  <user>nobody:nogroup</user>
  <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
  <jvmFlags> 
	<jvmFlag>-XX:MaxRAMPercentage=75.0</jvmFlag>
	<jvmFlag>-XX:InitialRAMPercentage=20.0</jvmFlag>
	<jvmFlag>-Xquickstart</jvmFlag>
	<jvmFlag>-Xtune:virtualized</jvmFlag>
	<jvmFlag>-Xscmx512M</jvmFlag>
	<jvmFlag>-Xshareclasses:cacheDir=/cache,name=conductor,verbose,checkURLTimestamps,persistent</jvmFlag>
  </jvmFlags>
  <mainClass>jp.co.toshibatec.ngp.conductor.ConductorApplication</mainClass>
  <format>OCI</format>
</container> 


Error - 

[-Xshareclasses persistent cache enabled]
[-Xshareclasses verbose output enabled]
JVMSHRC226E Error opening shared class cache file
JVMSHRC336E Port layer error code = -102
JVMSHRC337E Platform error message: Permission denied
JVMSHRC840E Failed to start up the shared cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

With root user it is working fine

**Comment by anjanitsip** [comment]
can we change permission of newly created cache directory using "cacheDirPerm
"-Xshareclasses:cacheDir=/cache,**cacheDirPerm=0777**,name=conductor,verbose,checkURLTimestamps,persistent

**Comment by anjanitsip** [comment]
I have observe one more issue. I have create SSC for my application and I am able to get it with List command but while printStats it is giving below error 

**JVMSHRC023E Cache does not exist**



root@terminal-7d489784d8-ng7lq:/# java -Xshareclasses:cacheDir=/cache,listAllCaches

Listing all caches in cacheDir /cache/

Cache name              level         cache-type      feature         layer       OS shmid       OS semid       last detach time

Compatible shared caches
terminal                Java11 64-bit  persistent      cr              0                                         In use

root@terminal-7d489784d8-ng7lq:/# java -Xshareclasses:cacheDir=/cache,printStats=classpath
JVMSHRC023E Cache does not exist
root@terminal-7d489784d8-ng7lq:/# java -Xshareclasses:cacheDir=/cache,printStats=help
Available options for -Xshareclasses:printStats=<options>. Use '+' to specify multiple options. i.e. printStats=aot+url

         all            Prints all the following types in the shared cache.
         classpath      Prints only classpath types in the shared cache.
         url            Prints only url types in the shared cache.
         token          Prints only token types in the shared cache.
         romclass       Prints only romclass types in the shared cache.
         rommethod      Prints only rommethod types in the shared cache.
         aot            Prints only aot types in the shared cache.
         invalidatedaot Prints only invalidated aot types in the shared cache.
         jitprofile     Prints only jitprofile types in the shared cache.
         jithint        Prints only jithint types in the shared cache.
         zipcache       Prints only zipcache types in the shared cache.
         stale          Prints all the stale entries in the shared cache.
         startuphint    Prints only startup hint types in the shared cache.

root@terminal-7d489784d8-ng7lq:/# java -Xshareclasses:cacheDir=/cache,printAllStats
JVMSHRC023E Cache does not exist
root@terminal-7d489784d8-ng7lq:/# java -Xshareclasses:cacheDir=/cache,printAllStats
**JVMSHRC023E Cache does not exist**
root@terminal-7d489784d8-ng7lq:/# java -Xshareclasses:cacheDir=/cache,printStats=all
**JVMSHRC023E Cache does not exist**

**Comment by anjanitsip** [comment]
root@barcode-67dc786f4c-rp6ct:/# java -Xshareclasses:cacheDir=/cache,printStats=all,verbose
[-Xshareclasses persistent cache enabled]
[-Xshareclasses verbose output enabled]
JVMSHRC764W Unable to create shared memory of size 314572800 bytes as requested
        Adjusted to maximum shared memory permitted (67108864 bytes)
        (To increase available shared memory, modify system SHMMAX value)
         If -Xscdmx is used, the debug attribute area is adjusted in proportion
         according to its original ratio to the -Xscmx value.
JVMSHRC023E Cache does not exist

**Comment by pshipton** [comment]
As the cache is named `terminal`, try `java -Xshareclasses:cacheDir=/cache,name=terminal,printStats`.

`terminal` is not the default cache name. I'm not sure how you created the cache, but without specifying a name, it defaults to `sharedcc_%u`, where `%u` inserts the current user name.

**Comment by hangshao0** [comment]
I see cache `terminal` is `In use`. If you didn't create it, it must be created by another user with `-Xshareclasses:name=terminal`, and that Java process is still running.

**Comment by pshipton** [comment]
I'm going to go ahead and close this, but if there are additional questions they can still be added.
