### ISSUE TITLE
win2012-x86-6 configure: Could not find /cygdrive/c/openjdk/freetype-2.5.3/lib64/freetype.dll

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10899]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_OMR/741
```
06:01:38  configure: Found freetype include files at /cygdrive/c/openjdk/freetype-2.5.3/include using --with-freetype
06:01:38  configure: Could not find /cygdrive/c/openjdk/freetype-2.5.3/lib64/freetype.dll. Ignoring location.
06:01:38  configure: error: Can not find or use freetype at location given by --with-freetype
```

Restarted the build and it's working fine on win2012-x86-4

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
I think this issue was because of this PR build (mine) which attempts to compile freetype
https://github.com/eclipse/openj9/pull/10892.

I have reinstalled freetype-2.5.3 content so it should be fine again.

**Comment by pshipton** [comment]
It's not fixed
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/895/
Disabled it again.

**Comment by jdekonin** [comment]
I mirrored the directory contents from win2012-x64-4 and did a successful manual test compile of JDK8.  Machine re-enabled.
