### ISSUE TITLE
Math.pow results are expected to be the same in Hotspot

### ISSUE THREAD

**Issue by darongmean** [eclipse/openj9#10918]
Java -version output
--------------------
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200715_677 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
```
Summary of problem
------------------

`Math.pow(3, 2.4)` doesn't return the same result in Hotspot.

In OpenJ9,
```
jshell> Math.pow(3,2.4)
$1 ==> 13.966610165238237
```
In Hotspot,
```
jshell> Math.pow(3,2.4)
$1 ==> 13.966610165238235
```
More discussion at https://openj9.slack.com/archives/C862YFGL9/p1602903053006700

**Comment by fjeremic** [comment]
I think @pshipton's comment in the Slack thread is key here, which I will quote:

> Actually, it's Hotspot that has the "incorrect" answer, although this is allowed by the spec. Using StrictMath, the answer is 13.966610165238237 on both OpenJ9 and Hotspot.
> "Unlike some of the numeric methods of class `StrictMath`, all implementations of the equivalent functions of class `Math` are not defined to return the bit-for-bit same results. This relaxation permits better-performing implementations where strict reproducibility is not required."

This does not look like a bug, but rather a difference allowed by the Java spec.
