### ISSUE TITLE
JITServer: AOT header validation failed: Heap Base for Barrier Range feature mismatch

### ISSUE THREAD

**Issue by EmanElsaban** [eclipse/openj9#10927]
I'm getting this error:  ```AOT header validation failed: Heap Base for Barrier Range feature mismatch.``` in the client verbose when running acmeair and jitserver locally. If I run acmeair alone and check the client verbose AOT is loaded and I dont get an error but when it's connected to jitserver AOT is not loaded and I get the above error.
The nightly image I'm using is ```adoptopenjdk/openjdk11-openj9:nightly```  and java version:
```openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment Openj9 (build 11.0.9+10-202010162349)
Eclipse OpenJ9 VM Openj9 (build master-e5e0324a0, JRE 11 Linux amd64-64-Bit Compressed References 20201016_802 (JIT enabled, AOT enabled)
OpenJ9   - e5e0324a0
OMR      - d2cc022b7
JCL      - 5e617ab0c8 based on jdk-11.0.9+10
```

The options I used for running JITServer locally: ``` docker run --env IBM_JAVA_OPTIONS="-Xjit:verbose" --entrypoint jitserver --network jitserver --name jitserver adoptopenjdk/openjdk11-openj9:nightly ```

The options I used for running the client locally: ``` docker run --env JVM_ARGS="-Xjit:verbose={compilePerformance},vlog=/tmp/vlog.txt,enableJITServerHeuristics" --network jitserver emanelsabban/acmeair:nightlyj920201016oldliberty ```

FYI: @harryyu1994

**Comment by harryyu1994** [comment]
```cpp
#if defined(J9VM_OPT_JITSERVER)
void
J9::Options::setupJITServerOptions()
   {
   TR::CompilationInfo * compInfo = getCompilationInfo(jitConfig);

   if (compInfo->getPersistentInfo()->getRemoteCompilationMode() == JITServer::SERVER ||
       compInfo->getPersistentInfo()->getRemoteCompilationMode() == JITServer::CLIENT)
      {
      self()->setOption(TR_DisableSamplingJProfiling);
      self()->setIsVariableHeapBaseForBarrierRange0(true);
      self()->setOption(TR_DisableProfiling); // JITServer limitation, JIT profiling data is not available to remote compiles yet
      self()->setOption(TR_DisableEDO); // JITServer limitation, EDO counters are not relocatable yet
      self()->setOption(TR_DisableMethodIsCold); // Shady heuristic; better to disable to reduce client/server traffic
      self()->setOption(TR_DisableJProfilerThread);
      self()->setOption(TR_EnableJProfiling, false);

      if (compInfo->getPersistentInfo()->getRemoteCompilationMode() == JITServer::SERVER)
         {
         // The server can compile with VM access in hand because GC is not a factor here
         // For the same reason we don't have to use TR_EnableYieldVMAccess
         self()->setOption(TR_DisableNoVMAccess);

         // IProfiler thread is not needed at JITServer because
         // no IProfiler info is collected at the server itself
         self()->setOption(TR_DisableIProfilerThread);
         J9::Compilation::setOutOfProcessCompilation();
         }
```
- it looks like this is due to JITServer setting `self()->setIsVariableHeapBaseForBarrierRange0(true);`.

**Comment by harryyu1994** [comment]
Two questions:
- Is there a need to set `self()->setIsVariableHeapBaseForBarrierRange0(true);`
- If we have both client and server set to true why are we getting a mismatch

**Comment by mpirvu** [comment]
> it looks like this is due to JITServer setting self()->setIsVariableHeapBaseForBarrierRange0(true);.

There should not be a problem if the client is running with a variable heap, because this option would be set to true anyway.

**Comment by mpirvu** [comment]
Oh, it's `heapBase`, not `heapSize`. I thought that was always variable.

**Comment by harryyu1994** [comment]
-  Only when `extensions->isVLHGC()` or `extensions->isStandardGC()` is on we set it to False
```cpp
	case j9gc_modron_configuration_heapBaseForBarrierRange0_isVariable:
		if (extensions->isVLHGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else if (extensions->isStandardGC()) {
			*((UDATA *)value) = FALSE;
			keyFound = TRUE;
		} else {
			keyFound = FALSE;
		}
		break;
```
- I will try to reproduce it on my end

**Comment by mpirvu** [comment]
Oh, so it's the opposite, it's always FALSE, but JITClient forces it to TRUE. I wonder why we forced it to TRUE. I comment would have helped.

**Comment by harryyu1994** [comment]
From the look of it, it will always be set to FALSE no matter which case we enter for non-jitserver. And I'm guessing this happens after `setupJITServerOptions()` on either client or server and thus the mismatch.

**Comment by mpirvu** [comment]
From the investigation that I did, things should work if we obtain the correct information from the client for:
```
getOptions()->getHeapBaseForBarrierRange0()
getOptions()->getHeapSizeForBarrierRange0()
getOptions()->getActiveCardTableBase()
getOptions()->getHeapAddressToCardAddressShift()
getOptions()->getHeapBase()
getOptions()->getHeapTop()
fe->getNurserySpaceBounds()
fe->getLowTenureAddress()
fe->getHighTenureAddress()
```
These should be stored per client in VMInfo because they cannot change.
For values that are extracted from options, we need to change the location to either fe or compiler object. I personally prefer fe because it can be overridden.

**Comment by mpirvu** [comment]
These fields in the Options class
```
   uintptr_t                   _gcCardSize;
   uintptr_t                   _heapBase;
   uintptr_t                   _heapTop;

   uintptr_t                   _heapAddressToCardAddressShift;
   uintptr_t                   _heapBaseForBarrierRange0;
   uintptr_t                   _heapSizeForBarrierRange0;
   uintptr_t                   _activeCardTableBase;
   bool                        _isVariableHeapBaseForBarrierRange0;
   bool                        _isVariableHeapSizeForBarrierRange0;
   bool                        _isVariableActiveCardTableBase;
```
are not static. I assume that they would be sent by the client and the server will use the correct values (please correct me if I am wrong on this one).
If so, only the three frontend queries need to be overridden:
```
fe->getNurserySpaceBounds()
fe->getLowTenureAddress()
fe->getHighTenureAddress()
```
