### ISSUE TITLE
Format of the version for Eclipse OpenJ9

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1096]
Eclipse OpenJ9 is soon to create a 0.8 release. It makes sense to expose this version from Java at runtime. The appropriate place is the java.vm.version system property (which is currently 2.9 as inherited from IBM). 

The current proposal is to set java.vm.version to the tag used for the build, which for the next OpenJ9 release will be openj9-0.8 or openj9-0.8.0. This Issue is for discussion.

The java.vm.version affects the java -version output, as seen below on the "Eclipse OpenJ9 VM" line where
the following example shows "build openj9-0.8.0". 

```
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (build 1.8.0_152-b16)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180130_000000 (JIT enabled, AOT enabled)
OpenJ9   - 296975c3
OMR      - f410d656
JCL      - 687ce89fd9 based on jdk8u152-b16)
```

For un-tagged (non-release) builds, the java.vm.version would be `<branch>-<sha>`, i.e. `master-a3814e1`.

Note OpenJ9 is still an incubation project. The Eclipse Project Handbook contains the following guidance. Perhaps the java.vm.version should indicate the incubation status of the project.

"In order to alert potential consumers of the incubating nature, projects in the incubation phase must include incubation branding. The project team must:
- Display the incubation logo on their project web page (if they have one);
- Display the incubation logo on their project’s primary download page;
- Include the word "incubation" in the filename of all downloadable files (when technically feasible) for builds and milestones; and
- When technically feasible, include the word "incubation" in features (e.g. about dialogs, feature lists, and installers)."

@mstoodle @DanHeidinga

**Comment by AdamBrousseau** [comment]
+1 for replacing `2.9` with `0.8.0`.
What about the `BUILDDATE_BUILDID`? I suggest we at least drop the build id or somehow incorporate the git tag name.

**Comment by pshipton** [comment]
The current proposal as found in https://github.com/eclipse/openj9/pull/1095 :

When not a release:
java.vm.version = $(OPENJ9_BRANCH)-$(OPENJ9_SHA) // i.e. master-1234567

For a release:
java.vm.version = $(OPENJ9_TAG) // i.e. openj9-0.8.0

**Comment by pshipton** [comment]
Changes have been merged
