### ISSUE TITLE
Broken docu links in IBM Knowledge Center

### ISSUE THREAD

**Issue by stmaute** [eclipse/openj9#1097]
Following link is broken: [Running Java applications](https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.90.doc/user/running_applications.html)
Also the other links won't work.

Hopefully you can fix this!

**Comment by DanHeidinga** [comment]
@SueChaplain Can you take a look at this?

**Comment by SueChaplain** [comment]
@stmaute Hi Stefan. Thanks for reporting this issue. 

The user guide links on that welcome page are now fixed. 

There are a couple of links under "More information" that still don't resolve. I think those pages might have been moved, so I'm investigating. However, hopefully you were after the user guide links.

**Comment by stmaute** [comment]
@SueChaplain Thx!

**Comment by SueChaplain** [comment]
The remaining external links that weren't working properly to some ibm.com sites are now working. Closing this issue.
