### ISSUE TITLE
Crash running gradle reported on StackOverflow

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#110]
https://stackoverflow.com/questions/46352408/cant-build-openjfx-with-eclipse-openj9181

"The new Eclipse J9 jvm does not come bundled with JavaFX, so I have tried to build OpenJFX but have failed. I believe I have followed all the build instructions on the OpenJFX website. I have Gradle 3.1, Ant, and the required libraries installed. I'm running Fedora 26. J9 appears to be failing with some kind of segmentation fault. Here is the error message I'm getting after I run gradle in the OpenJFX mercurial repository."

```
[_@localhost rt]$ gradle
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/usr/local/share/gradle-3.1/lib/gradle-base-services-3.1.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Unhandled exception
Type=Segmentation error vmState=0x00040000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F822A5BF730 Handler2=00007F82297A4D30 InaccessibleAddress=0000000000000008
RDI=00000000013AFA00 RSI=0000000000000000 RAX=0000000000000004 RBX=00007F822400FDA0
RCX=0000000000000011 RDX=0000000000000000 R8=00007F822400FDA0 R9=0000000000000000
R10=00007F822493EDD0 R11=00007F822BCC1610 R12=00000000013AFA00 R13=00007F822400FDA0
R14=00000000013AFA00 R15=00007F822B4E8190
RIP=00007F822A5EBA20 GS=0000 FS=0000 RSP=00007F822B4E8150
EFlags=0000000000010246 CS=0033 RBP=0000000000000000 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000008
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 726f6674616c502f (f: 1634488320.000000, d: 1.675017e+243)
xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm3 0000ff0000000000 (f: 0.000000, d: 1.385239e-309)
xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm5 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
xmm6 402bd9b2780ad4ad (f: 2013975680.000000, d: 1.392519e+01)
xmm7 402bd9b2780ad4ad (f: 2013975680.000000, d: 1.392519e+01)
xmm8 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
xmm9 402bd9b1c3a0f13b (f: 3282104576.000000, d: 1.392518e+01)
xmm10 3fee11aacd651245 (f: 3445953024.000000, d: 9.396566e-01)
xmm11 3cc7800000000000 (f: 0.000000, d: 6.522560e-16)
xmm12 bc40000000000000 (f: 0.000000, d: -1.734723e-18)
xmm13 402bb9d3beb8c600 (f: 3199780352.000000, d: 1.386294e+01)
xmm14 3bfc4721da1f8579 (f: 3659498752.000000, d: 9.580912e-20)
xmm15 402bb9d3beb8c600 (f: 3199780352.000000, d: 1.386294e+01)
Module=/usr/java/jdk-9+181/lib/compressedrefs/libj9vm29.so
Module_base_address=00007F822A52F000
Target=2_90_20170915_6 (Linux 4.12.12-300.fc26.x86_64)
CPU=amd64 (8 logical CPUs) (0x3dfa5d000 RAM)
----------- Stack Backtrace -----------
(0x00007F822A5EBA20 [libj9vm29.so+0xbca20])
(0x00007F821BF2D7C4 [libjclse9_29.so+0x457c4])
(0x00007F821BF2DA5B [libjclse9_29.so+0x45a5b])
(0x00007F821BF347C0 [libjclse9_29.so+0x4c7c0])
(0x00007F8229F0B7B4 [libffi29.so+0x67b4])
ffi_call+0x1b8 (0x00007F8229F09EB8 [libffi29.so+0x4eb8])
(0x00007F822A554A9B [libj9vm29.so+0x25a9b])
(0x00007F822A541B3B [libj9vm29.so+0x12b3b])
(0x00007F822A5F82C2 [libj9vm29.so+0xc92c2])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2017/09/21 15:46:12 - please wait.
JVMDUMP032I JVM requested System dump using '/path/to/openjfx/rt/core.20170921.154612.4490.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.4526.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 4526 was not found. Expected to find core file with name "/path/to/openjfx/rt/core.4526"
JVMDUMP032I JVM requested Java dump using '/path/to/openjfx/rt/javacore.20170921.154612.4490.0002.txt' in response to an event
```

**Comment by tajila** [comment]
I installed Gradle on ubuntu14 and able to run '--version' successfully. 

gradle -g /tmp --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/team/tobi/ISSUE110/gradle-4.2-bin/gradle-4.2/lib/groovy-all-2.4.11.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-internal (Eclipse OpenJ9 2.9)
OS:           Linux 3.13.0-129-generic amd64


I added the '-g /tmp' so it would run on the local drive instead of teh NFS mount.

**Comment by tajila** [comment]
I also tried it on RedHat:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/team/tobi/ISSUE110/gradle-4.2-bin/gradle-4.2/lib/groovy-all-2.4.11.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-internal (Eclipse OpenJ9 2.9)
OS:           Linux 3.10.0-693.1.1.el7.x86_64 amd64

**Comment by tajila** [comment]
Just noticed that the problem states Gradle 3.1.

**Comment by tajila** [comment]
I tried it with Gradle 3.1 and it works:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/team/tobi/ISSUE110/gradle-3.1-all/gradle-3.1/lib/groovy-all-2.4.7.jar) to method java.lang.Object.clone()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-internal (Eclipse OpenJ9 2.9)
OS:           Linux 3.10.0-693.1.1.el7.x86_64 amd64

**Comment by tajila** [comment]
Perhaps this failure only occurs on Fedora, will try it on there next.

**Comment by mgaudet** [comment]
Perhaps the failure also only occurs when gradle is building OpenJFX? (I could totally see gradle version being an insufficient workload to force the error)

**Comment by mgaudet** [comment]
You can make your text show up preformatted by either fencing it with three backticks, or spacing with four spaces: 

    ```
    fenced code shows up pre
    ```

```
    four spaces also 
    leads to pre
```

See more in the GitHub [Guide to Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by tajila** [comment]
thanks @mgaudet

**Comment by tajila** [comment]
It fails when calling `JVM_GetSystemPackage_Impl` with "com/ibm/lang/management/internal/"

It ends up calling `getModuleJRTURL ()` with a NULL moduleName. I'm investigating why this is happening

**Comment by tajila** [comment]
When searching for the package details of "com/ibm/lang/management/internal/" it looks up the first class it can find in the package to determine the module. In this case the class is "com/ibm/lang/management/internal/PlatformMBeanProvider". 

The class has been assigned to the bootloader unnamed module (which is incorrect) so when the moduleName is queried it returns NULL.

The reason for this is the locationType is set to `LOAD_LOCATION_UNKNOWN` instead of `LOAD_LOCATION_MODULE`. I am investigating why this is happening.

**Comment by sabkrish** [comment]
I'm also facing the crash issue when i run a gradle build with Gradle 3.5 + Eclipse J9 combination on Ubuntu 16.04.2. The issue goes away with Gradle 4.2 + Eclipse J9 combination.
