### ISSUE TITLE
Cannot delete workspace win2012-x86-6

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11005]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/928/console

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
System rebooted, manually cleaned rather large Build_JDK8_x86-64_windows_Personal work directory that was present on the machine.  Guessing a failed PR build??  Either way should be good again. Machine re-enabled on jenkins.
