### ISSUE TITLE
cent7-aarch64-1 has been offline

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#11007]
cent7-aarch64-1 has been offline for a couple of days.
https://ci.eclipse.org/openj9/computer/cent7-aarch64-1/

I cannot run jenkins jobs for AArch64.

**Comment by pshipton** [comment]
@jdekonin fyi. I know you are already aware of this and made a comment about it (somewhere). As I recall, there is no outlook for getting the system running again.

**Comment by jdekonin** [comment]
That correct, I am aware of this system being offline.  I should've opened an issue earlier sorry.  I took ~30 mins Oct 22nd to try get this online on but didn't get very far.  I am not sure when we can fit this rebuild into the schedule.  Atm looking like early next week.

https://openj9.slack.com/archives/C8PQL5N65/p1603385973014700

**Comment by jdekonin** [comment]
The original cause of the system unavailability was the installation of docker.  This was requested to be able to test Adopt build scripts on this system.  One of the dependencies installed with docker was SELinux, which disabled remote access.

I booted the system into rescue mode and made the needed changes to SELinux configuration to permit remote access for the build user.  It is online and available for use once again.

fyi I have also shown @rajdeepsingh1 and @AdamBrousseau how to access this system as well.

**Comment by AdamBrousseau** [comment]
Thanks Joe
