### ISSUE TITLE
JEP 395: Records

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11026]
See https://openjdk.java.net/jeps/395

Records moves out of preview status.

**Comment by pshipton** [comment]
@tajila

**Comment by tajila** [comment]
Monitoring this, I expect either none or very few JVM changes

**Comment by tajila** [comment]
Specs:
http://cr.openjdk.java.net/~gbierman/jep395/jep395-20201019/specs/records-jls.html
http://cr.openjdk.java.net/~gbierman/jep395/jep395-20201019/specs/records-jvms.html

@ChengJin01 Can you take a look at these to see if there are any VM changes required

**Comment by ChengJin01** [comment]
Given that JEP 359: Records (Preview) at https://openjdk.java.net/jeps/359 and JEP 384: Records (Second Preview) https://openjdk.java.net/jeps/384 were already implemented via https://github.com/eclipse/openj9/issues/7945 and https://github.com/eclipse/openj9/issues/9529,   I double-checked the content of JEP384 as compared to JEP395 in the following Specs:
https://openjdk.java.net/jeps/384
http://cr.openjdk.java.net/~gbierman/jep384/jep384-20200506/specs/records-jls.html
http://cr.openjdk.java.net/~gbierman/jep384/jep384-20200506/specs/records-jvms.html

https://openjdk.java.net/jeps/395
http://cr.openjdk.java.net/~gbierman/jep395/jep395-20201019/specs/records-jls.html
http://cr.openjdk.java.net/~gbierman/jep395/jep395-20201019/specs/records-jvms.html

It seems there is a few updated description in JEP395 at https://openjdk.java.net/jeps/395
```
This JEP proposes to finalize the feature in JDK 16, with the following refinement:

Relax the longstanding restriction whereby an inner class cannot declare a member that is explicitly or implicitly static. 
This will become legal and, in particular, will allow an inner class to declare a member that is a record class.
```
which only requires change for the java compiler at JLS Spec at http://cr.openjdk.java.net/~gbierman/jep395/jep395-20201019/specs/records-jls.html
```
The changes are the same as those in the second preview of Records in Java SE 15, 
except for minor editorial changes and the following:

To relax the current restriction on an inner class from declaring a member that is explicitly or implicitly static. 
This will now be permitted and, in particular, will allow an inner class to declare a record class member...
```
But there is no updated description in JVM Spec from http://cr.openjdk.java.net/~gbierman/jep384/jep384-20200506/specs/records-jvms.html & https://docs.oracle.com/javase/specs/jvms/se15/preview/specs/records-jvms.html to http://cr.openjdk.java.net/~gbierman/jep395/jep395-20201019/specs/records-jvms.html.  Meanwhile, the class version (`59.65535`)remains the same as JEP384 as follows:
```
Table 4.7-A. Predefined class file attributes  (by section)
Attribute    | Section          | class file           | Java SE
Record      |    4.7.30           | 59.65535         | 15
```
So there should be no change in JEP395 from the VM perspective. Will wait for the updated jtreg test suite to confirm this.

**Comment by tajila** [comment]
Okay, thanks for the analysis @ChengJin01

**Comment by pshipton** [comment]
fyi https://github.com/eclipse/openj9/issues/11403

**Comment by ChengJin01** [comment]
I've updated the code with `J9ROMCLASS_IS_RECORD` https://github.com/ChengJin01/openj9/commit/f45d67dfd51d58985753ad557e780a37c5a12317 to deal with the check in ` Class::isRecord` given `J9ROMCLASS_IS_RECORD` is only called by `isRecord()` but also at multiple places (already verified in personal builds).

**Comment by tajila** [comment]
All JVM changes are in.
