### ISSUE TITLE
Combine isAbstractClass() and isInterfaceClass() into one query

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#11029]
There are quite a few places in the code where we ask whether a class is a 'concrete' class, i.e. whether it is not abstract and not an interface:
```
 if (!TR::Compiler->cls.isAbstractClass(comp(), classId) && !TR::Compiler->cls.isInterfaceClass(comp(), classId))
```
For JITServer, each of these queries performs a locking operation. In order to reduce overhead we could create another query (say isConcreteClass()) that performs the two tests mentioned above in one critical section, rather than two.

**Comment by mpirvu** [comment]
Attn: @EmanElsaban

**Comment by EmanElsaban** [comment]
I'm currently looking at the following files:

- CHTable.cpp
- J9ClassEnv.cpp
- VMJ9.cpp
- j9javaaccessflags.h
