### ISSUE TITLE
Tomcat webapp jars/classes are not cached

### ISSUE THREAD

**Issue by verve111** [eclipse/openj9#11023]
We've enabled a shared class caching option on our OpenJ9 used by a Tomcat. There are a few webapps deployed onto it, but after the Tomcat is started, the shared cache doesn't include Classpaths of the webapp (i.e. /webapps/app1/WEB-INF/lib/*.jar are missing), it includes only default Tomcat jars (1: 0x00007FD32AE1BDB0 CLASSPATH
        /var/resultflow/openJ9-15/jdk-15.0.1+9-jre/lib/modules
1: 0x00007FD32AE13D2C CLASSPATH
        /usr/share/tomcat7
        /usr/share/tomcat/bin/bootstrap.jar
1: 0x00007FD32AE13B70 CLASSPATH
        /usr/share/tomcat7
        /usr/share/tomcat/bin/bootstrap.jar
        /usr/share/tomcat/bin/tomcat-juli.jar
1: 0x00007FD32AE10B94 CLASSPATH
        /usr/share/java/tomcat
        /usr/share/java/tomcat/tomcat-util.jar
        /usr/share/java/tomcat/catalina.jar
)

Is it possible to make OpenJ9 see the classpaths of the webapps? Thanks
Environment:
-Tomcat 9
-OpenJDK15U-jre_x64_linux (0.23)

**Comment by pshipton** [comment]
See https://github.com/eclipse/openj9/issues/10427

@hangshao0 fyi

**Comment by verve111** [comment]
Thanks for your hint, but we use an extracted webapp (not a war-packed app) with a set of jars (no fat jars) at webapps/app1/WEB-INF/lib/*.jar. In the provided link there're war-apps discussed. Please tell if it should work in our case. Thanks

**Comment by hangshao0** [comment]
In your case, if the classes in `webapps/app1/WEB-INF/lib/*.jar` are loaded by WebappClassLoaderBase, it is the same issue as #10427. The OpenJ9's shared class patch to `URLClassLoader.findClass()` is overridden by `org.apache.catalina.loader.WebappClassLoaderBase.findClass()`. The classes on the search path (no matter in jar or war) of `WebappClassLoaderBase` won't work properly with shared class cache.

**Comment by verve111** [comment]
Thanks for your comprehensive reply
