### ISSUE TITLE
JEP 392: Packaging Tool

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11028]
See https://openjdk.java.net/jeps/392

Evaluation of the incubator was done in https://github.com/eclipse/openj9/issues/8276

Other than updating the doc (https://github.com/eclipse/openj9-docs/pull/519) to refer to the new JEP, I don't expect there is anything further required.

**Comment by pshipton** [comment]
@tajila @SueChaplain

**Comment by pshipton** [comment]
> this just needs a mention in the 0.24 docs "What's New" topic to explain, and still doesn't need to be fully documented

agreed.

**Comment by pshipton** [comment]
@pmhayward actually since jpackage is out of incubation I think `jpackage is supported on only the following OpenJ9 platforms` needs a mention which is more permanent than a release note.

**Comment by pmhayward** [comment]
@pshipton  Will also add something more permanent in the 'Getting started' topic. 
(Can you say what platforms, please!)

**Comment by pshipton** [comment]
It's the same as https://github.com/eclipse/openj9-docs/pull/519/files with the updated JEP number. The unsupported platforms are AIX and zOS.

**Comment by pshipton** [comment]
Also note the target for this the OpenJ9 0.25.0 release, which is the Java 16 GA.

**Comment by pmhayward** [comment]
Thanks - yes, will make sure it doesn't go in 0.24!

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9-docs/issues/664 is open so I'll close this.
