### ISSUE TITLE
JEP 380 Unix-Domain Socket Channels

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11030]
See https://openjdk.java.net/jeps/380

Likely no OpenJ9 changes required for this.

**Comment by pshipton** [comment]
@tajila

**Comment by pshipton** [comment]
@smlambert @llxia are there any openjdk tests for this that are already run or can be run?

**Comment by llxia** [comment]
It looks like there are several tests added. For example:
https://github.com/AdoptOpenJDK/openjdk-jdk16/tree/master/test/jdk/java/net/UnixDomainSocketAddress
https://github.com/AdoptOpenJDK/openjdk-jdk16/tree/master/test/jdk/java/nio/channels/unixdomain
https://github.com/AdoptOpenJDK/openjdk-jdk16/blob/master/test/jdk/java/nio/channels/spi/SelectorProvider/inheritedChannel/UnixDomainChannelTest.java
...

**Comment by pshipton** [comment]
We should run these tests to validate the feature works with OpenJ9 and doesn't need VM support.

**Comment by llxia** [comment]
According to [this commit](https://github.com/AdoptOpenJDK/openjdk-jdk16/commit/6bb7e45e8e1a8f5a3b2f9c92b610fa4236f2eb90#diff-14c4fbe9aa8de106b276c93f5442491314c097e0630ea7bc9ca4f87c9b7bb557), the unix domain socket channels tests are mostly in `jdk_net` and `jdk_nio`.

Ran `jdk_net` and `jdk_nio` using the latest JDK16 x86-64_linux:
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1497/testReport/

jdk_nio passed. jdk_net sub tests (SocketAcceptInterruptTest and SocketReadInterruptTest) failed. The failures are not related to unix domain socket channels. In summary, the unix domain socket channels tests in jdk_net and jdk_nio are passed.

**Comment by pshipton** [comment]
Thanks Lan. Confirming other platforms as well.
AIX - https://ci.eclipse.org/openj9/view/Test/job/Grinder/1498
Mac - https://ci.eclipse.org/openj9/view/Test/job/Grinder/1499
Win - https://ci.eclipse.org/openj9/view/Test/job/Grinder/1500

**Comment by pshipton** [comment]
As this appears to be implemented completely in OpenJDK and not require any OpenJ9 support, closing this.
