### ISSUE TITLE
jps doesn't handle multiple flags in one argument

### ISSUE THREAD

**Issue by ajohnson1** [eclipse/openj9#11036]
Java -version output
--------------------

>openjdk version "11.0.9" 2020-10-20
>OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
>Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Windows 10 amd64-64-Bit Compressed References >20201022_795 (JIT enabled, AOT enabled)
>OpenJ9   - 0394ef754
>OMR      - 582366ae5
>JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)

Summary of problem
------------------

The command
`jps -ml`
gives
>jps: Print a list of Java processes and information about them
>    -J: supply arguments to the Java VM running jps
>   -l: print the application package name
>    -q: print only the virtual machine identifiers
>    -m: print the application arguments
>    -v: print the Java VM arguments, including those produced automatically

whereas a HotSpot JVM gives:
>bin\jps -ml
>1408 sun.tools.jps.Jps -ml

It doesn't make much difference as `jps -m -l` works but might give a problem with scripts etc. E.g. Eclipse Memory Analyzer used `jps -ml` to list running processes to trigger heap dumps. I can fix that by using `jps -m -l`

Other commands might have a similar problem, depending on how arguments are parsed.

**Comment by pshipton** [comment]
@JasonFengJ9 fyi, but I'm going to put this into the backlog.

**Comment by JasonFengJ9** [comment]
Agreed, we can pick it up from `Backlog` later.

**Comment by alexey-anufriev** [comment]
@pshipton, I can work on this one.
