### ISSUE TITLE
Fix tests failing due to injecting interfaces

### ISSUE THREAD

**Issue by OussamaSaoudi** [eclipse/openj9#11031]
New interface injection functionality causing test failures in c,p, and i test levels. Tests must be patched in order for the new additions to pass all the tests.

80 Load_Level_2.(Mauve, Harmony).5mins.*
80 VM_Sanity.(Mauve, Harmony).5mins.Mode607
- Hard coded expected serialUID must be changed since injecting interfaces changes auto-generated serialUID's

JVM_Regression.jck.runtime.*
- Throws assertion due to presence of different number of interfaces than expected

Test failures: http://vmfarm.ottawa.ibm.com/old/build_info.php?build_id=457884
Related Issue: https://github.com/eclipse/openj9/issues/10078
Related PR: https://github.com/eclipse/openj9/pull/10282

**Comment by pshipton** [comment]
This is an IBM problem, not an OpenJ9 problem. Pls open an issue internal to IBM.

**Comment by pshipton** [comment]
Likely the changes shouldn't be affecting Java 8.
