### ISSUE TITLE
Why are some of the string APIs `J9UTF8*` based and others `U_8*` and `UDATA` based?

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#1104]
As part of the following review comment https://github.com/eclipse/openj9/pull/1047#discussion_r165158418 it appears some of the APIs related to strings in the VM are designed around `J9UTF8*` and others around `U_8*` and `UDATA` pairs to represent string characters and length. 

Why is there such a difference? It seems having both of these APIs makes things harder as you are foced to copy or allocate memory at times. Would settling one one set of APIs improve compatibility and consistency of these APIs? Are both warranted in some scenarios?

**Comment by pshipton** [comment]
J9UTFs originate from string data stored in the constant pool. They have a limitation of U_16 for the length, since that is the maximum allowed by the java spec, and it keeps the footprint down. I suppose both sets of APIs grew organically over time as they were needed. U_8* and UDATA is more generic so it makes sense to use this for APIs, although it needs an extra parameter for each string.

**Comment by pshipton** [comment]
In cases like findModuleForPackageUTF8, the J9UTF8 is stored into a J9HashTable, which would point to the J9UTF8 in the constant pool.

**Comment by fjeremic** [comment]
> In cases like findModuleForPackageUTF8, the J9UTF8 is stored into a J9HashTable, which would point to the J9UTF8 in the constant pool. Which keeps the footprint down.

Thanks for the explanation. What purpose does `findModuleForPackage` serve then?

**Comment by pshipton** [comment]
Its a helper for when you have string data that doesn't originate (directly) from the constant pool and there isn't a UTF8 available. A UTF8 needs to be temporarily created to do a lookup in the J9HashTable.

**Comment by pshipton** [comment]
For example, the following starts with a J9UTF8 containing a class name, but it needs a J9UTF8 containing only the package part of the name.

```
					packageUTF = J9UTF8_DATA(J9ROMCLASS_CLASSNAME(packageRomClass));
					pkgNameLength = (U_32) packageNameLength(packageRomClass);

					omrthread_monitor_enter(javaVM->classLoaderModuleAndLocationMutex);
					module = findModuleForPackage(vmThread, classLoader, packageUTF, pkgNameLength);
```

**Comment by fjeremic** [comment]
Thanks for answers @pshipton! Closing this issue as my questions have been addressed.
