### ISSUE TITLE
Cannot run StringJoinerTest.java in jdknext grinder

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11048]
jdk15 grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/1133 is working.
jdknext grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/1132 shows `no tests selected`.
I did notice the test requirements are different in jdknext `@requires vm.bits == "64" & os.maxMemory > 4G` vs `@requires os.maxMemory > 4G` for jdk15.

```
14:46:00  mkdir -p "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16039971591783/jdk_custom_0"; \
14:46:00  cd "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16039971591783/jdk_custom_0"; \
14:46:00  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xmx512m -jar "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
14:46:00  -agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:3  -vmoptions:"-Xmx512m  " \
14:46:00  -w ""/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16039971591783/jdk_custom_0"/work" \
14:46:00  -r "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/report" \
14:46:00  -jdk:"/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image" \
14:46:00  "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner/StringJoinerTest.java"; \
14:46:00  if [ $? -eq 0 ] ; then echo ""; echo "jdk_custom_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Grinder/openjdk-tests/TKG/..;  else echo ""; echo "jdk_custom_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16039971591783/TestTargetResult";
14:46:01  Directory "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16039971591783/jdk_custom_0/work" not found: creating
14:46:01  Directory "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/report" not found: creating
14:46:13  XML output with verification to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16039971591783/jdk_custom_0/work
14:46:13  Test results: no tests selected
```

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
Just for the record, I rerun 1133 (jdk16) with machine cent7-ppcle-5 (previously passed machine with jdk15). The Grinder also failed: https://ci.eclipse.org/openj9/view/Test/job/Grinder/1135/

**Comment by llxia** [comment]
Used Grinder/11672 and ran the test on rhel7lert4 (internally). The test failed with `no tests selected` (as expected).
On rhel7lert4, use the same JDK16 and test material, and removed `vm.bits == "64"` from [StringJoinerTest.java ](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/4234d7565d34e4d9c313f5c044908e8a043460ca/test/jdk/java/util/StringJoiner/StringJoinerTest.java#L34
), manually run the test and it passed.

```
{ itercnt=1; \
mkdir -p "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16040082697277/jdk_custom_0"; \
cd "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16040082697277/jdk_custom_0"; \
"/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xmx512m -jar "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
-agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:4  -vmoptions:"-Xmx512m  " \
-w ""/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16040082697277/jdk_custom_0"/work" \
-r "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/openjdk/report" \
-jdk:"/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image" \
"/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner/StringJoinerTest.java"; \
if [ $? -eq 0 ] ; then echo ""; echo "jdk_custom_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Grinder/openjdk-tests/TKG/..;  else echo ""; echo "jdk_custom_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16040082697277/TestTargetResult";
Directory "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16040082697277/jdk_custom_0/work" not found: creating
XML output with verification to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16040082697277/jdk_custom_0/work
Test results: passed: 1
Report written to /home/jenkins/workspace/Grinder/jvmtest/openjdk/report/html/report.html
Results written to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_16040082697277/jdk_custom_0/work

jdk_custom_0_PASSED
```

Currently, we are using  https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz. I also tried https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-5.1-b01.tar.gz. It does not seem to make any difference. 

@sophia-guo Any idea of how jtreg checks `vm.bits`?

**Comment by sophia-guo** [comment]
I think it's due to vm.bits is not added as the requires properties in jdk components. Will check if it's correct.

**Comment by sophia-guo** [comment]
openjdk use [VMProps.java](https://github.com/AdoptOpenJDK/openjdk-jdk/blob/master/test/jtreg-ext/requires/VMProps.java) set up Properties used by @requires expressions, which setup vm.bits. 

openj9 use [OpenJ9PropsExt.java](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java) setup Properties , which hasn't added vm.bits property.

**Comment by sophia-guo** [comment]
Take 15 for example 
1. update https://github.com/sophia-guo/openj9-openjdk-jdk15/blob/vmbit/test/jdk/java/util/StringJoiner/StringJoinerTest.java with vm.bits == "64" test can't be found. 
https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/127/
2. Update https://github.com/sophia-guo/openj9-openjdk-jdk15/blob/vmbit/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java , test is found:
 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox/133/

https://github.com/sophia-guo/openj9-openjdk-jdk/blob/openj9/closed/test/jtreg-ext/requires/OpenJ9PropsExt.java need to be updated and back port to 11.

**Comment by llxia** [comment]
The fix is delivered in https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/246
