### ISSUE TITLE
JVMCFRE090 new bytecode cannot create arrays; class=sun/reflect/GeneratedSerializationConstructorAccessor91

### ISSUE THREAD

**Issue by DanySK** [eclipse/openj9#11067]
I found a different behaviour between Hotspot and OpenJ9, with the latter also showing a regression (it was working in previous OpenJ9 releases). The bug affects both OpenJ9 0.23.0 on JDK 8 and 11, on amd64 OS.

To reproduce:
* `git clone git@github.com:Protelis/Protelis.git`
* `git checkout a7898b4ab5b4650b2433047cfbcea6def71be973`
* `./gradlew test`

```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
```

Relevant stacktrace:
```
java.lang.VerifyError: JVMCFRE090 new bytecode cannot create arrays; class=jdk/internal/reflect/GeneratedSerializationConstructorAccessor91, method=newInstance([Ljava/lang/Object;)Ljava/lang/Object;, pc=0
    Exception Details:
      Location:
        jdk/internal/reflect/GeneratedSerializationConstructorAccessor91.newInstance([Ljava/lang/Object;)Ljava/lang/Object; @0: JBnew
      Reason:
        Error exists in the bytecode.
      Exception Handler Table:
        bci [0, 24] => handler: 28
        bci [0, 24] => handler: 28
        bci [24, 27] => handler: 40
        at java.base/jdk.internal.misc.Unsafe.defineClass0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.defineClass(Unsafe.java:1510)
        at java.base/jdk.internal.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:400)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
        at java.base/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:112)
        at java.base/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:514)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:427)
        at jdk.unsupported/sun.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:103)
        at org.nustaq.serialization.FSTDefaultClassInstantiator.findConstructorForSerializable(FSTDefaultClassInstantiator.java:107)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:137)
```

**Comment by gacholio** [comment]
I was under the impression we don't verify classes created via Unsafe, but the rules there may have been updated recently. Irrespective of that, the error indicates that the code is attempting a `new` bytecode on an array class identifier `[something`, which is certainly not allowed.

**Comment by paulcheeseman** [comment]
It seems that verification [was enabled for Unsafe classes](https://github.com/eclipse/openj9/pull/10060) recently, which appears to have exposed this issue. The bytecode for the GeneratedSerializationConstructorAccessor has been generated in the same way for many years.

Hotspot seems to allow this bytecode though.  [This testcase](https://github.com/eclipse/openj9/files/5482069/testcase.zip) simply tries to define a GeneratedSerializationConstructorAccessor class that contains the problematic bytecode, and this triggers a VerifyError on OpenJ9 but not on Hotspot. The test uses `ClassLoader.defineClass()` as opposed to `Unsafe.defineClass()` and it fails on any version of OpenJ9.

This seems to be the problematic bytecode for the class in the testcase:

```
public java.lang.Object newInstance(java.lang.Object[]) throws java.lang.reflect.InvocationTargetException;
    descriptor: ([Ljava/lang/Object;)Ljava/lang/Object;
    flags: ACC_PUBLIC
    Code:
      stack=6, locals=2, args_size=2
         0: new           #6                  // class "[Ljava/lang/Object;"    <----------
         3: dup
         4: aload_1
         5: ifnull        24
         ...
```
```
Constant pool:
    #1 = Utf8               sun/reflect/GeneratedSerializationConstructorAccessor61
    #2 = Class              #1            // sun/reflect/GeneratedSerializationConstructorAccessor61
    #3 = Utf8               sun/reflect/SerializationConstructorAccessorImpl
    #4 = Class              #3            // sun/reflect/SerializationConstructorAccessorImpl
    #5 = Utf8               [Ljava/lang/Object;
    #6 = Class              #5            // "[Ljava/lang/Object;"
    ...
```

**Comment by DanHeidinga** [comment]
We may need to disable verification for more of these classes - see comment in:
https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/2e947ea2025890e846beb37130ecd63960120c09/src/java.base/share/classes/jdk/internal/reflect/MagicAccessorImpl.java#L37-L44

**Comment by gacholio** [comment]
From what I can tell from perusing the code, `new` on an array descriptor will throw `InstantiationException`, so I'm not sure how this code could ever have worked.

**Comment by gacholio** [comment]
@keithc-ca Did the recent work for the new validation code - should generated reflect accessors be exempt from validation?

**Comment by keithc-ca** [comment]
> @keithc-ca did the recent work for the new validation code - should generated reflect accessors be exempt from validation?

Yes, I think so, because the generated classes extend `MagicAccessorImpl`; note also the comments https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/src/share/classes/sun/reflect/package.html#L75-L90.

**Comment by gacholio** [comment]
@paulcheeseman Has provided a test case. If I modify it to call the accessor method and run without verification, I get the expected result:
```
Exception in thread "main" java.lang.InstantiationError: [Ljava.lang.Object;
	at sun.reflect.GeneratedSerializationConstructorAccessor61.newInstance(Unknown Source)
	at Test.nat(Native Method)
	at Test.main(Test.java:18)
```

**Comment by gacholio** [comment]
An admittedly stale Hotspot java8 throws the same error. The test will not run with Java 11 due to internal accessor hierarchy changes.

**Comment by gacholio** [comment]
Also illegal on latest Adopt JDK11:
```
Caused by: java.lang.VerifyError: Illegal new instruction
Exception Details:
  Location:
    GAC.main([Ljava/lang/String;)V @0: new
  Reason:
    Invalid type: '[Ljava/lang/Object;' (constant pool 3)
  Bytecode:
    0000000: bb00 0359 b700 014c 2bc0 0003 c000 0303
    0000010: 0153 b1                                
```
Bytecodes are:
```
  Name: main
  Signature: ([Ljava/lang/String;)V
  Access Flags (1040009): (has debug info) 
  access: public static unknown_flags = 0x1000000
  Extended modfiers (0): 
  Max Stack: 3
  Argument Count: 1
  Temp Count: 1

    0 JBnewdup 3 [Ljava/lang/Object;
    3 JBdup 
    4 JBinvokespecial 1 java/lang/Object.<init>()V
    7 JBastore1 
    8 JBaload1 
    9 JBcheckcast 3 [Ljava/lang/Object;
   12 JBcheckcast 3 [Ljava/lang/Object;
   15 JBiconst0 
   16 JBaconstnull 
   17 JBaastore 
   18 JBgenericReturn 
```

**Comment by gacholio** [comment]
In java8, the class hierarchy is:
```
Class name: java/lang/Object
Class name: sun/reflect/MagicAccessorImpl
Class name: sun/reflect/ConstructorAccessorImpl
Class name: sun/reflect/SerializationConstructorAccessorImpl
```
so this should have been excluded from verification.

**Comment by gacholio** [comment]
@keithc-ca Can you determine why this class is being verified? Core is in `/team/gac/ver/z`. The class of the generated accessor is `0x701600`.

**Comment by gacholio** [comment]
Latest Adopt JDK11 also throws the `InstantiationException` when verification is disabled.

**Comment by gacholio** [comment]
To summarize - OpenJ9 and OpenJDK behave the same way, except for the recently-lost verification exemption. We'll have to wait and see once the verification is fixed to see if the submitted problem still exists (it's entirely possible that the calling code is catching the `InstantiationException`)

**Comment by gacholio** [comment]
The verify error is thrown from the static verifier, which is not affected by the exemption code. That code has been in place forever. The accessor generator code must have changed recently (or this app is doing something we've never seen before).

To fix this, we may need to move the array check into the runtime verifier.

**Comment by gacholio** [comment]
@ChengJin01 You've done something similar recently - can you take a look at moving the check? This is apparently affecting multiple customers, so it should be considered high priority.

**Comment by ChengJin01** [comment]
@gacholio,  Let me see what happened in there & what we can do with this issue.

**Comment by gacholio** [comment]
Nothing happened - the code has been there for many years.

**Comment by ChengJin01** [comment]
As for the comment at https://github.com/eclipse/openj9/issues/11067#issuecomment-721320429,  I don't think the check should be moved to the runtime verification. From the VM Spec perspective, the static verifier checks the class format to ensure it is structurally valid to move forward to the stage of runtime verification where the type-check rather then the class format is carried out.

**Comment by ChengJin01** [comment]
After double-checking the code around at https://github.com/eclipse/openj9/pull/10060, I think the idea is to skip the static verification for `sun.reflect.MagicAccessorImpl` and all its subclasses in `internalLoadROMClass()` (/runtime/bcutil/defineclass.c)
```
UDATA
internalLoadROMClass(J9VMThread * vmThread, J9LoadROMClassData *loadData, J9TranslationLocalBuffer *localBuffer)
{
...
	if (the romclass is MagicAccessorImpl or its subclasses) {
			translationFlags &= ~BCT_StaticVerification;
		}
	}
```
I will check tomorrow to see whether the idea works to fix the issue.

**Comment by ChengJin01** [comment]
I went through the code in `internalCreateRAMClassFromROMClass()` at `/runtime/vm/createramclass.cpp` as follows:
```
/*
 * A class which extends (perhaps indirectly) the 'magic'
 * accessor class is exempt from the normal access rules.
 */
#if JAVA_SPEC_VERSION == 8
#define MAGIC_ACCESSOR_IMPL "sun/reflect/MagicAccessorImpl"
#else /* JAVA_SPEC_VERSION == 8 */
#define MAGIC_ACCESSOR_IMPL "jdk/internal/reflect/MagicAccessorImpl"
#endif /* JAVA_SPEC_VERSION == 8 */

J9Class *
internalCreateRAMClassFromROMClass(...)
{
...
		if (J9_ARE_NO_BITS_SET(classFlags, J9ClassIsExemptFromValidation)) {
			J9UTF8 *className = J9ROMCLASS_CLASSNAME(romClass);

			if (J9UTF8_LITERAL_EQUALS(J9UTF8_DATA(className), 
                          J9UTF8_LENGTH(className), MAGIC_ACCESSOR_IMPL)) { <-------
				classFlags |= J9ClassIsExemptFromValidation;
			}
		}
...
```
It seems we do have code there handling the case for `MagicAccessorImpl` but it is too late for static verification and is only used to skip the later runtime verification.  So my understanding is that the existing code didn't fully implement the requirements on Java 8 & 11 in the case of  `MagicAccessorImpl` and its subclasses (both static verification and runtime verification should be skipped at this point)

To totally handling this case, we might need to leverage the flag `J9ClassIsExemptFromValidation` set up in  `MagicAccessorImpl` in internalLoadROMClass() to skip the static verification for the subclaseses by checking the flag in the superclasses.

**Comment by paulcheeseman** [comment]
>The accessor generator code must have changed recently (or this app is doing something we've never seen before).

The relevant part of the accessor generator code in the class library hasn't changed since the code (sun.reflect.MethodAccessorGenerator) was first added in 1.4.0, and the application in my IBM support case was working fine with earlier IBM Java 8 releases. The OP says the same about their app.

FYI, this is the code in OpenJDK:
https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/e5b1823a897e/src/share/classes/sun/reflect/MethodAccessorGenerator.java#l436

**Comment by ChengJin01** [comment]
I don't think there was any change with `MethodAccessorGenerator` or `MagicAccessorImpl` (including its subclasses) at this point in Java 8 & 11. 

Originally the static verification for `Unsafe` classses (including `MagicAccessorImpl` & its subclasses) was disabled and `J9ClassIsExemptFromValidation`  was set in `MagicAccessorImpl` and its subclasses in `internalCreateRAMClassFromROMClass` to skip the runtime verification, in which case the verification of `MagicAccessorImpl` and its subclasses was totally ignored in terms of the static & runtime verification.

Now the static verification for `Unsafe`  classes must be enabled in `https://github.com/eclipse/openj9/pull/10060` to support the implementation of valueTypes (for Project Valhalla), which inevitably triggered the issue with static verification on the subclasses of `MagicAccessorImpl`.

So the new fix for this problem must keep the static verification on `Unsafe` classses except the subclasses of `MagicAccessorImpl`.

**Comment by gacholio** [comment]
You can't really do this without modifying the ROM class creation code, and maybe not even then. You don't know the superclass until the class bytes have been parsed and even then you must not load the superclass in the ROM class creation code.

You need to mirror the behaviour of the existing macro:
```
(J9ROMCLASS_IS_UNSAFE((clazz)->romClass) && !J9ROMCLASS_IS_HIDDEN((clazz)->romClass)) || (J9_ARE_ANY_BITS_SET((clazz)->classFlags, J9ClassIsExemptFromValidation))
```
I think the unsafe and hidden checks can be done by looking at flags that are already passed in, but the RAM class check is the superclass check, which I don't think can be achieved here.

Note that the static (structural) verification is just to make sure we get something which doesn't contain junk data/offsets/etc. There's nothing preventing us from moving the array check into the runtime pass - the descriptor has been validated as well-formed.

The only danger is if there are tests out there which are pedantic about when we detect the error (and have been many over the years).

**Comment by ChengJin01** [comment]
As discussed with @gacholio offline, it seems there is no other or easy way to get rid of the problem without moving the check to the runtime verifier. So I will try to move the check to the runtime verifier to see how it goes and we need have all internal tests passed to ensure there is no issue introduced with the changes.

**Comment by ChengJin01** [comment]
I've created a fix at https://github.com/ChengJin01/openj9/commit/88e50fa75d97a6707d5d8df26e10d94bc3a90c15 which works good with the gradlew test (all test cases passed)
[gradlew_test_with_fix_passed.TXT](https://github.com/eclipse/openj9/files/5490296/gradlew_test_with_fix_passed.TXT)

Will launch personal builds on Java 8, 11 & 15 & check the internal tests to see how it goes.
