### ISSUE TITLE
[Doubt] which is better for Modded Minecraft 1.12? JDK or JRE?

### ISSUE THREAD

**Issue by gatoborrachon** [eclipse/openj9#11066]
more than an issue, its a doubt.

i used the **OpenJDK 8 - JDK OpenJ9** from this page:
https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9

but then i noticed that there is another page to download only the **OpenJDK 8 - JRE OpenJ9** (windows and x64):
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9

Using these arguments and **OpenJDK 8 - JDK OpenJ9** i get better results than using HotSpot (as intended):

_-XX:+UseG1GC -Xmx4G -Xms256m -XX:+UseStringDeduplication -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=50 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=2 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1HeapRegionSize=32M -Dsun.rmi.dgc.server.gcInterval=2147483646_
![2020-10-29_23 39 13](https://user-images.githubusercontent.com/61126174/97758944-95db7880-1ac5-11eb-87f3-88391bce64e6.png)
(the lower the graphs, the better the performance)

but then i noticed that using **OpenJDK 8 - JRE OpenJ9** with the following arguments i get a bit better performance:

_-Xms256M -Xmx4G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1_
![2020-10-30_10 35 27](https://user-images.githubusercontent.com/61126174/97759056-d76c2380-1ac5-11eb-830f-e1f56afc1e1a.png)

maybe its dumb but i only had the doubt if this is an expected behavior, and if maybe someone know about better arguments for OpenJDK 8 - JRE OpenJ9 or can give me an advice with the ones i use.

if someone need the custom modpack i'm using i can give it

also, using the last arguments i provided with **OpenJDK 8 - JDK OpenJ9** i get a worst performance than HotSpot, if someone had the doubt

**Comment by pshipton** [comment]
The JRE and JDK runtimes are exactly the same. The JDK comes with extra tools like the javac compiler, so it's a bigger install. For Java 8, the JRE is actually separated in the directory structure. From the JDK download, if you take only the jre directory and throw away the rest, you have the JRE.

You can check if the JDK and JRE you download are exactly the same version, by running `-version`.

Many of the arguments you are using are just  ignored by OpenJ9.
`-XX:+UseG1GC`
`-XX:MaxGCPauseMillis=50`
`-XX:SoftRefLRUPolicyMSPerMB=10000`
`-XX:+UnlockExperimentalVMOptions`
`-XX:G1NewSizePercent=20`
`-XX:G1HeapRegionSize=32M`

-XX:+ParallelRefProcEnabled 
-XX:MaxGCPauseMillis=200
`-XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1`

If you want to weed out the ignored options, you can run with `-XX:-IgnoreUnrecognizedXXColonOptions`

**Comment by pshipton** [comment]
I believe this makes the comparison between
`-Xmx4G -Xms256m -XX:+DisableExplicitGC -XX:ParallelGCThreads=2 -Dsun.rmi.dgc.server.gcInterval=2147483646`
and
`-Xms256M -Xmx4G -XX:+DisableExplicitGC -XX:+AlwaysPreTouch`

**Comment by pshipton** [comment]
Since sun.rmi.dgc.server.gcInterval controls when System.gc() is called, and `-XX:+DisableExplicitGC` is enabled, I think this parameter doesn't matter. Also 2147483646 is quite a long time, ~596 hours, I don't expect the timer is expiring. The default is 1 hour.

**Comment by pshipton** [comment]
If `-Xms256M -Xmx4G -XX:+DisableExplicitGC -XX:+AlwaysPreTouch` gives better performance with the JRE and worse performance with the JDK, and these are exactly the same version, I expect there is run to run variation.

Note `-XX:+AlwaysPreTouch` was just introduced in the 0.23 release, if using an older version the option is just ignored (unless `-XX:-IgnoreUnrecognizedXXColonOptions` is used).

**Comment by gatoborrachon** [comment]
thanks for answer and sorry for late reply

you were right, i saved the .msi file of the JDK version i was using and it is the 0.21.0 release, and the JRE release i tested is the 0.23.0

so, i just would need to use these arguments?
-Xms256M -Xmx4G -XX:+DisableExplicitGC -XX:+AlwaysPreTouch

or maybe -XX:ParallelGCThreads=2 would help too?

**Comment by gatoborrachon** [comment]
i need to explain this:
in the first pic i uploaded the game took ~30 minutes
the second pic (the faster one) took ~29 minutes

now, doing a test with these arguments the game took ~33 minutes to load
-Xms256M -Xmx4G -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:ParallelGCThreads=2

i will try again without -XX:ParallelGCThreads=2 and -XX:+DisableExplicitGC, but i'm going to add 
-Dsun.rmi.dgc.server.gcInterval=2147483646 to see how it goes, also this is the pic of the lagometer:
![2020-10-30_20 12 52](https://user-images.githubusercontent.com/61126174/97769002-f3cf8680-1aec-11eb-984c-fc03dae0334a.png)

**Comment by pshipton** [comment]
> which is better, DisableExplicitGC or sun.rmi.dgc.server.gcInterval

DisableExplicitGC ignores all calls to System.gc(), while sun.rmi.dgc.server.gcInterval only affects the System.gc() for the rmi.dgc.server.

I don't know which combination of options is going to provide the best performance, perhaps the GC folks will have some advice next week (since it is the weekend now). They typically want to look at a gc log for a run in order to make a recommendation. https://www.eclipse.org/openj9/docs/xverbosegclog/.

**Comment by gatoborrachon** [comment]
oh ok, many thanks for all
