### ISSUE TITLE
Remove redundant null and bound checks in NIO methods

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/openj9#11063]
The following methods can skip performing null checks and bound checks:
```
java/nio/HeapByteBuffer._get(I)B
java/nio/Bits.getCharB(Ljava/nio/ByteBuffer;I)C
java/nio/Bits.getCharL(Ljava/nio/ByteBuffer;I)C
java/nio/Bits.getShortB(Ljava/nio/ByteBuffer;I)S
java/nio/Bits.getShortL(Ljava/nio/ByteBuffer;I)S
java/nio/Bits.getIntB(Ljava/nio/ByteBuffer;I)I
java/nio/Bits.getIntL(Ljava/nio/ByteBuffer;I)I
java/nio/Bits.getLongB(Ljava/nio/ByteBuffer;I)J
java/nio/Bits.getLongL(Ljava/nio/ByteBuffer;I)J
```
Null checks and bound checks for these methods are redundant. Prior calls to `nextGetIndex` or `checkIndex` would have already thrown an exception if the access was out of bounds. All calls to the listed methods that use a `ByteBuffer` always pass in a non-NULL `ByteBuffer`.

Preliminary testing shows that skipping the checks produces an improvement in an internal benchmark.

**Comment by gita-omr** [comment]
Jenkins test sanity all jdk8,jdk11

**Comment by IBMJimmyk** [comment]
PR was merged in. I forgot to tag the PR with "closes" so I'm closing this manually.
