### ISSUE TITLE
Test the release process

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1111]
Create a new branch `test-openj9-0.8` and tag the content with the `test-openj9-0.8RC1` tag.  Use this to test the release process from https://github.com/eclipse/openj9/blob/master/doc/processes/release_process.md

**Comment by DanHeidinga** [comment]
Will attempt create a release branch from nightly build that's a few days old:

https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-linux_390-64_cmprssptrs/83/
OpenJ9: 453326f
OMR: 1f7d88e
OpenJDK: dde0d86

**Comment by DanHeidinga** [comment]
Created and tagged the repos as follows:

```
$ cd openj9
$ git branch openj9-0.0 453326f
$ git checkout openj9-0.0
$ git tag -a openj9-0.0M1
$ git push origin openj9-0.0 --follow-tags

$ cd ../openj9-omr/
$ git branch openj9-0.0  1f7d88e
$ git checkout openj9-0.0
$ git tag -a openj9-0.0M1
$ git push origin openj9-0.0 --follow-tags
```

Next step to checkout the code at those tags

**Comment by pshipton** [comment]
@AdamBrousseau is there a way to run the ci testing on this tag?

**Comment by AdamBrousseau** [comment]
I can kick a build manually, followed by sanity & extended.

https://ci.eclipse.org/openj9/job/Build-JDK8-linux_ppc-64_cmprssptrs_le/83/parameters/
https://ci.eclipse.org/openj9/job/Build-JDK8-linux_390-64_cmprssptrs/86/parameters/

We can easily add a "Release" build that will do this all for us by simply supplying a tag.

**Comment by AdamBrousseau** [comment]
zLinux
 - [Build](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_390-64_cmprssptrs/86/)
 - [Sanity](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-linux_390-64_cmprssptrs/74/)
 - [Extended](https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_390-64_cmprssptrs/70/)

pLinux
 - [Build](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_ppc-64_cmprssptrs_le/83/)
 - [Sanity](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/81/)
 - [Extended](https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le/72/)

**Comment by DanHeidinga** [comment]
Checked out and running the build:
```
$ bash get_source.sh -openj9-branch=openj9-0.0 -openj9-sha=openj9-0.0M1 -omr-branch=openj9-0.0 -omr-sha=openj9-0.0M1
```

which results in a 'detached head' state.

TODO: java version output
TODO: refresh branch based off more recent build, retag and test the checkout & java version again

**Comment by DanHeidinga** [comment]
The branch and tag names will show up in:
* `java -version` output
** `tag` if tagged
**  `branch-sha` if not tagged
* `tag` will show up in the javacore as well

Will open a pull request to adapt the release naming conventions to:

Branch: `openj9-0.0`
Tags: `v0.0RC1`, v0.0`

**Comment by DanHeidinga** [comment]
PR to change the tag and branch format: https://github.com/eclipse/openj9/pull/1199

**Comment by DanHeidinga** [comment]
Closing as #1199 has been merged.

**Comment by pshipton** [comment]
Seems Dan meant to close this Issue. https://github.com/eclipse/openj9/issues/1265 is opened to create the branch and tag for the 0.8 release.
