### ISSUE TITLE
cloud you help me ? file.listFiles() is 0

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#11120]
cloud you help me ? file.listFiles() is 0

when i use java ,  use File.ListFiles()   , when file dir have more than one file,    file.ListFiles() then return 0;

please java.io.io.File.listFiles()

**Comment by pshipton** [comment]
What is the `-version` output from the JVM where the problem is seen?
Does the problem occur when using a Hotspot JVM, or only with an OpenJ9 JVM?

**Comment by 15838028035** [comment]
Oracle Jvm ,not openj9
发自我的iPhone

**Comment by pshipton** [comment]
Not much we can do from an OpenJ9 perspective then.

**Comment by 15838028035** [comment]
Okay, thanks!


发自我的iPhone
