### ISSUE TITLE
enableSessionTicketExtension

### ISSUE THREAD

**Issue by agdolla** [eclipse/openj9#11133]
Hi

openjdk 13+ has an option jdk.tls.client.enableSessionTicketExtension to enable tls session tickets.
Does openj9 also support this tls feature ?

Thanks

Gabor

**Comment by pshipton** [comment]
The same OpenJDK code for TLS is used for OpenJ9, so the option should be supported. Have you encountered a problem using this option with OpenJ9?

**Comment by agdolla** [comment]
Thanks for taking time to answer to my question!
I could start OpenJ9 with the same options I used with HotSpot and it did not complain and it works but I can not really debug the TLS communication to check if session tickets are used or not.
So thanks for the info, I assume this should be OK.
