### ISSUE TITLE
Archive test step fails intermittently when run in parallel with testing

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1114]
During the PR builds, once the compile is complete, we archive the SDK in parallel with the testing. Sometimes, the SDK fails to archive ([eg](https://ci.eclipse.org/openj9/blue/organizations/jenkins/PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le-OpenJ9/detail/PullRequest-Sanity-JDK9-linux_ppc-64_cmprssptrs_le-OpenJ9/22/pipeline)). We shouldn't fail a PR build if this step fails (currently), however, this step needs to pass for a nightly build or an OMR Acceptance build. We could try/catch the archive and make failing optional, but I think its probably safe enough, and cleaner, to retry an archive rather than make optional whether it is critical it passes or not.

We could add a retry(3) block around the [archive step](https://github.com/eclipse/openj9/blob/20aeaf1fffb3bb330600afe484959717276b5bfa/buildenv/jenkins/build#L220).

**Comment by pshipton** [comment]
Ideally we should fix the underlying cause so the archive doesn't fail. Do you know why the archive fails? Disk space, job timeout, machine overloaded? If its out of disk space then would retrying help?

**Comment by AdamBrousseau** [comment]
Failed during tar of the test directory. Probably shouldn't be taring a directory while test stuff is being written to it. Before the pipelines were committed, we only archived the sdk in a PR. Now that the code is shared, we archive the test material in a PR unnecessarily. I can think of three options off the top of my head
1. Break this out into 2 separate archive steps
1. Wrap the test archive in some kind of if block
1. Put an exclude in the tar to ignore certain dir(s) where we write test results.

**Comment by AdamBrousseau** [comment]
More options to add to my previous list

4. Don't archive in PR builds at all
   - I don't know who how often these are used

5. Stop archiving in parallel with testing
   - Typical times to archive:
      - JDK8/zLinux: 4.5 Min
      - JDK9/zLinux: 9 min
      - JDK8/pLinux: <1 min
      - JDK9/pLinux: 2 min

**Comment by pshipton** [comment]
I've been downloading a few PR builds lately. 

6. It doesn't seem to fail very often. Archive in parallel with testing, but if it fails print a message to explain that it failed in case somebody ever looks, and don't fail the testing.

**Comment by AdamBrousseau** [comment]
(Implemented # 2)
