### ISSUE TITLE
Assign-to-project workflow runs too many times

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#11142]
Notice that in https://github.com/eclipse/openj9/pull/11140, 'Assign to MH Project' and 'Assign to Snapshot Project' ran twice each: I would expect them to run once each.

**Comment by DanHeidinga** [comment]
Where the labels added to the project one at a time?  Or both at once?  I can't tell now as it groups them into having been added over an hour ago.  Adding them individually would explain the double trigger of the workflow

**Comment by keithc-ca** [comment]
It appears as if they were added together in one step (there's only one 'added labels' event), but maybe it runs for each label regardless of the timing?

**Comment by pshipton** [comment]
It's possible I added them separately, I can't remember.

**Comment by keithc-ca** [comment]
I couldn't find anything that would confirm this in github documentation, but it makes sense that the action runs for each label added - our action does different things depending on which label is added.
