### ISSUE TITLE
Purge JITServer caches sooner under memory pressure

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#11161]
To reduce network communication, JITServer keeps a set of caches, one for each client JVM it serves. If a client hasn't issued a compilation request in more than 1000 seconds, its cache is purged from the JITServer memory because it is likely that the client has ended without communicating this to the server. 1000 seconds is a large time though and, if JITServer is running low on memory, it should be more aggressive in purging these, possible stale, caches.
Also, we should have an option to control that 1000 second value.

**Comment by mpirvu** [comment]
This issue proposes a mitigating solution for the problems raise by #11154

**Comment by mpirvu** [comment]
Attn: @EmanElsaban

**Comment by EmanElsaban** [comment]
Currently looking in file ```JITClientSession.cpp```. I think ```OLD_AGE``` is used to define when an entry is old.
```
ClientSessionHT::ClientSessionHT() : _clientSessionMap(decltype(_clientSessionMap)::allocator_type(TR::Compiler->persistentAllocator())),
                                     TIME_BETWEEN_PURGES(1000*60*30), // JITServer TODO: this must come from options
                                     OLD_AGE(1000*60*1000) // 1000 minutes
```

Here, I think is where the server will purge the client data.
```
void
ClientSessionHT::purgeOldDataIfNeeded()
   {
   PORT_ACCESS_FROM_PORT(TR::Compiler->portLib);
   int64_t crtTime = j9time_current_time_millis();
   if (crtTime - _timeOfLastPurge > TIME_BETWEEN_PURGES)
      {
      // Time for a purge operation.
      // Scan the entire table and delete old elements that are not in use
      for (auto iter = _clientSessionMap.begin(); iter != _clientSessionMap.end(); ++iter)
         {
         TR_ASSERT(iter->second->getInUse() >= 0, "_inUse=%d must be positive\n", iter->second->getInUse());
         if (iter->second->getInUse() == 0 &&
             crtTime - iter->second->getTimeOflastAccess() > OLD_AGE)
            {
            if (TR::Options::getVerboseOption(TR_VerboseJITServer))
               TR_VerboseLog::writeLineLocked(TR_Vlog_JITServer, "Server will purge session data for clientUID %llu", (unsigned long long)iter->first);
            ClientSessionData::destroy(iter->second); // delete the client data
            _clientSessionMap.erase(iter); // delete the mapping from the hashtable
            }
         }
      _timeOfLastPurge = crtTime;

      // JITServer TODO: keep stats on how many elements were purged
      }
   }
```

**Comment by mpirvu** [comment]
Indeed, OLD_AGE is what defines an entry that is eligible for purging. 
I would like both OLD_AGE and TIME_BETWEEN_PURGES to come from options rather than baked-in values.
Also,that the default value for TIME_BETWEEN_PURGES is too large, 30 minutes. Maybe 1 minute is large enough that it won't create too much overhead.
We may need to define another constant OLD_AGE_UNDER_LOW_MEMORY, that is much lower than OLD_AGE. If the available memory is low at the server, then we look at OLD_AGE_UNDER_LOW_MEMORY instead of OLD_AGE. OLD_AGE_UNDER_LOW_MEMORY could be something like 5 or 10 minutes.
