### ISSUE TITLE
Use different persistent allocators for JITServer per-client caches

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#11162]
All the caches that are allocated at the JITServer use the same persistent memory allocator. When a client goes away, its corresponding cache at JITServer is purged, but the deallocated memory is not completely freed; instead it is placed into a pool of freed memory for future consumption. This mechanism can create problems when many clients are served concurrently because a large amount of persistent memory is going to be allocated and never fully freed, even though the JITServer may be completely idle.
If we use a dedicated memory persistent allocator for each cache, then, once the cache is purged, we can free the corresponding memory back to the OS.

**Comment by dmitry-ten** [comment]
I'm working on a PR to address this issue.

**Comment by dmitry-ten** [comment]
@mpirvu #11686 closes this issue.
