### ISSUE TITLE
Remove J9_PROJECT_SPECIFIC guards from compiler

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#1117]
Remove the `J9_PROJECT_SPECIFIC` guards around code in OpenJ9 as they are not necessary.

14 uses found:

```
compiler/trj9/optimizer/InlinerTempForJ9.cpp:#ifdef J9_PROJECT_SPECIFIC
```

**Comment by tmcdermo** [comment]
I'd like to tackle this as a means for getting my feet wet in this project (and open source as a whole).  

Quick question though: When you say these guards are not necessary, does that mean it always evaluates to true?  I see the 14 uses mentioned but most are in #ifdef statements combined with #else.  Is it safe to assume the #else statements never execute and can be removed with the all of these?

**Comment by fjeremic** [comment]
> Quick question though: When you say these guards are not necessary, does that mean it always evaluates to true?

That's right. This is because the macro is defined directly in the makefiles for the entire project:

https://github.com/eclipse/openj9/blob/26f8c7edb1fe37253d001243c0ce14473334d07f/runtime/compiler/trj9/build/toolcfg/common.mk#L51
