### ISSUE TITLE
jdk15 NullPointerException.constructor Cannot invoke "java.lang.Throwable.fillInStackTrace()

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11206]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_ppc64le_linux_Nightly/106/
MauveMultiThreadLoadTest_0
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_x86-64_linux_Nightly/103/
MauveSingleThreadLoadTest_OpenJ9_0
```
LT  03:29:27.451 - Test failed
LT    Failure num.  = 1
LT    Test number   = 2208
LT    Test details  = 'Mauve[gnu.testlet.java.lang.NullPointerException.constructor]'
LT    Suite number  = 0
LT    Thread number = 13
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.lang.NullPointerException.constructor (number 0)
LT  FAIL: gnu.testlet.java.lang.NullPointerException.constructor (number 1)
LT  got java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.fillInStackTrace()" because "this" is null but expected java.lang.NullPointerException
LT  PASS: gnu.testlet.java.lang.NullPointerException.constructor (number 2)
LT  PASS: gnu.testlet.java.lang.NullPointerException.constructor (number 3)
LT  PASS: gnu.testlet.java.lang.NullPointerException.constructor (number 4)
LT  FAIL: gnu.testlet.java.lang.NullPointerException.constructor (number 5)
LT  got java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.fillInStackTrace()" because "this" is null but expected java.lang.NullPointerException
```

**Comment by pshipton** [comment]
Related to #11183

@JasonFengJ9 pls take a look.

**Comment by JasonFengJ9** [comment]
Sure, will look into it.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_x86-64_windows_Nightly/110

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_ppc64_aix_Nightly/109
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_x86-64_linux_Nightly/105

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_ppc64le_linux_Nightly/110
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_s390x_linux_Nightly/112

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_ppc64_aix_Nightly/111
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_ppc64le_linux_Nightly/111
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_s390x_linux_Nightly/113
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_x86-64_linux_Nightly/107
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.system_x86-64_windows_Nightly/114

This needs to be fixed or excluded.

**Comment by JasonFengJ9** [comment]
@pshipton I am actively working on this, the NPE was due to Throwable object invokes `NullPointerException.fillInStackTrace` while the `NullPointerException` object hasn't been initialized. The test can be excluded before a fix is merged.

**Comment by JasonFengJ9** [comment]
Opened https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/380 to exclude `Mauve[gnu.testlet.java.lang.NullPointerException.constructor]`.
