### ISSUE TITLE
JDK8/x64/Linux - Illegal Start of Expression in building

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#11229]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/854/console
```
12:22:38  Compiling tools to generate DDR pointer classes and structure stubs
12:22:38  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java:219: error: illegal start of expression
12:22:38  		Map<String, String> aliasMap = loadAliasMap(() -> getAliasVersion());
12:22:38  		                                             ^
12:22:38  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java:219: error: illegal start of expression
12:22:38  		Map<String, String> aliasMap = loadAliasMap(() -> getAliasVersion());
12:22:38  		                                                ^
12:22:38  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java:229: error: illegal start of expression
12:22:38  		return loadAliasMap(() -> Long.toString(version));
12:22:38  		                     ^
12:22:38  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/StructureReader.java:229: error: illegal start of expression
12:22:38  		return loadAliasMap(() -> Long.toString(version));
12:22:38  		                        ^
12:22:39  4 errors
```
First instance of this occurring at Adopt.

**Comment by pshipton** [comment]
Related to https://github.com/eclipse/openj9/pull/11210
@keithc-ca 

There weren't any problems in the OpenJ9 builds last night, which include this change.

**Comment by M-Davies** [comment]
> There weren't any problems in the OpenJ9 builds last night, which include this change.

Neither at Adopt's

**Comment by pshipton** [comment]
> Neither at Adopt's

I'm confused. If there isn't a problem in Adopt's builds what is being reported in this Issue?

**Comment by pshipton** [comment]
I'm saying that linux-x64 built fine in the OpenJ9 nightly build last night.

https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/1096/

**Comment by pshipton** [comment]
I expect Adopt is failing to build because it's using a Java 7 boot JDK. Although we should fix the code so Java 7 can still be used.
`BOOT JDK: java version "1.7.0_261"`

**Comment by sxa** [comment]
> I'm confused. If there isn't a problem in Adopt's builds what is being reported in this Issue?

Last night's regular build was ok, but [a subsequent one](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/) kicked off by @M-Davies about five hours ago did not.

**Comment by pshipton** [comment]
That's because the regular build pre-dated the change which broke it. It contains OpenJ9 SHA 280eaae30

**Comment by pshipton** [comment]
Also time zone confusion, because "last night" for AdoptOpenJDK runs at a different time from "last night" for OpenJ9.

**Comment by sxa** [comment]
Indeed - hence the reason I figured saying "5 hours ago" so it was relative to my comment would clarify and it seems to have done so :-)

**Comment by andrew-m-leonard** [comment]
Adopt builds failed last night with this: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/855/console
@pshipton @sxa

**Comment by andrew-m-leonard** [comment]
BootJDK being used:
```
17:16:52  Boot jdk directory: /usr/lib/jvm/java-1.7.0-openjdk.x86_64:
17:16:52  BOOT JDK: java version "1.7.0_261"
17:16:52  BOOT JDK: OpenJDK Runtime Environment (rhel-2.6.22.1.el6_10-x86_64 u261-b02)
17:16:52  BOOT JDK: OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)
17:16:52  JDK IN PATH: openjdk version "1.8.0_272"
17:16:52  JDK IN PATH: OpenJDK Runtime Environment (build 1.8.0_272-b10)
17:16:52  JDK IN PATH: OpenJDK 64-Bit Server VM (build 25.272-b10, mixed mode)
```

**Comment by keithc-ca** [comment]
That build used:
```
12:20:38    Source version info:
12:20:38      openjdk - eedf1763
12:20:38      openj9  - 2981dcb4c
12:20:38      omr     - 70484c499
```
`2981dcb4c` is one merge commit before the fix.
