### ISSUE TITLE
Should MethodHandles be always enabled in OpenJ9?

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#11225]
### Should MethodHandles be always enabled in OpenJ9?

**Or are there instances where we need to completely disable MethodHandle related code?**

Recently, we have also added new flags, `J9VM_OPT_OPENJDK_METHODHANDLE` and `J9VM_OPT_METHOD_HANDLE_COMMON`, in order to support OpenJDK's implementation of MethodHandles.

Recent changes, such as https://github.com/eclipse/openj9/pull/10893, won't allow MethodHandles to be completed disabled.

Currently, `J9VM_INTERP_MINIMAL_JCL` precludes `J9VM_OPT_METHOD_HANDLE`. In other words, `J9VM_INTERP_MINIMAL_JCL` expects `J9VM_OPT_METHOD_HANDLE` to be disabled.

**Do we still need to support `J9VM_INTERP_MINIMAL_JCL`?**
**Should the new flags also be precluded for `J9VM_INTERP_MINIMAL_JCL`?**

### Ref: J9VM_INTERP_MINIMAL_JCL
https://github.com/eclipse/openj9/blob/d939a539fc6416ea4ee89e3be60d2d489e234e9f/buildspecs/j9.flags#L934-L940

### Ref: J9VM_OPT_METHOD_HANDLE_COMMON
https://github.com/eclipse/openj9/blob/d939a539fc6416ea4ee89e3be60d2d489e234e9f/buildspecs/j9.flags#L1776-L1779

### Ref: J9VM_OPT_METHOD_HANDLE
https://github.com/eclipse/openj9/blob/d939a539fc6416ea4ee89e3be60d2d489e234e9f/buildspecs/j9.flags#L1772-L1775

### Ref: J9VM_OPT_OPENJDK_METHODHANDLE
https://github.com/eclipse/openj9/blob/d939a539fc6416ea4ee89e3be60d2d489e234e9f/buildspecs/j9.flags#L1812-L1815

**Comment by babsingh** [comment]
fyi @DanHeidinga @fengxue-IS @tajila

**Comment by DanHeidinga** [comment]
@pshipton you're the last person I remember who had a reason to disable methodhandles.  Do you recall why?  And if the reasons are still relevant?

**Comment by DanHeidinga** [comment]
> Do we still need to support J9VM_INTERP_MINIMAL_JCL?

Sounds like we don't need this anymore.

The code should expect that MHs are always present.  Don't worry about allowing MHs to be disabled

**Comment by babsingh** [comment]
Closing this issue: **MHs should always be enabled**.
