### ISSUE TITLE
jacoco_test failing with openj9 jdk11 and 14 

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11243]
Java -version output
--------------------

10:53:19  =JAVA VERSION OUTPUT BEGIN=
10:53:20  openjdk version "11.0.10" 2021-01-19
10:53:20  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+3-202011192348)
10:53:20  Eclipse OpenJ9 VM AdoptOpenJDK (build master-722c4437c, JRE 11 Linux amd64-64-Bit Compressed References 20201119_841 (JIT enabled, AOT enabled)
10:53:20  OpenJ9   - 722c4437c
10:53:20  OMR      - 70484c499
10:53:20  JCL      - 250afc0850 based on jdk-11.0.10+3)

Summary of problem
------------------

While adding the jacoco test suite to the openj9 external group, I noticed that there was one test consistently failing with openj9 jdk11 and 14 on all platforms (note the test passes with hotspot).

Here is the error message produced by https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4940/
Failed tests: startup_should_not_create_duplicate_class_definition(org.jacoco.core.runtime.InjectedClassRuntimeTest)
and
10:56:10 [[1;34mINFO[m] JaCoCo :: Test :: Core ............................. [1;31mFAILURE[m [ 3.992 s]

The failing test can be found at https://github.com/jacoco/jacoco/blob/master/org.jacoco.core.test/src/org/jacoco/core/runtime/InjectedClassRuntimeTest.java#L50-L61

based on: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2065

**Comment by tajila** [comment]
@hangshao0 ^^^

**Comment by hangshao0** [comment]
I will look into this.

**Comment by hangshao0** [comment]
Reproduced this failure:

```
java.lang.reflect.InvocationTargetException
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ...
  ...
  Caused by:
  java.lang.LinkageError: org.jacoco.core.runtime.startup_should_not_create_duplicate_class_definition
  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:481)
  	at java.base/java.lang.Access.defineClass(Access.java:234)
  	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:1686)
```

OpenJ9 does throw a InvocationTargetException which LinkageError as the cause, which is expected by the test. However, the test goes on to check for "duplicate class definition" in the error message:
https://github.com/jacoco/jacoco/blob/master/org.jacoco.core.test/src/org/jacoco/core/runtime/InjectedClassRuntimeTest.java#L59.

I don't see "duplicate class definition" in OpenJ9's error message, so the test failed. It is an issue of error reporting in OpenJ9, which is different from RI.

**Comment by hangshao0** [comment]
There seems to be more than one issue here. I tried adding the error message using `setCurrentExceptionNLSWithArgs()`, but the error message still does not show up. Looks like something is wrong with `setCurrentExceptionNLSWithArgs()`.
