### ISSUE TITLE
JEP 396 Strongly Encapsulate JDK Internals by Default

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11240]
See https://openjdk.java.net/jeps/396

**Comment by pshipton** [comment]
@llxia fyi, this may require some testing to add `--illegal-access=permit`

**Comment by pshipton** [comment]
Tentatively added it to jdk16, although atm it's only proposed with the review ending 2020/11/26.

**Comment by pshipton** [comment]
This applies to Java 11+. Tests that need to run with `--illegal-access=permit` print a warning like the following:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.openj9.test.com.ibm.jit.Test_JITHelpers (file:/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.openj9.test.com.ibm.jit.Test_JITHelpers
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by pshipton** [comment]
With the resolution of https://github.com/eclipse/openj9/issues/11419 I believe this can be closed. Although, @SueChaplain is there an appropriate place in the doc to mention this change? It seems new versions of Java should refer to the OpenJDK project, such as http://openjdk.java.net/projects/jdk/16/, with an interpretation of what does and doesn't apply to OpenJ9.

**Comment by SueChaplain** [comment]
@pshipton - seems appropriate to put something in the release topic of the user guide. Perhaps we can list the features that would apply to an OpenJDK that is built with OpenJ9, and point to http://openjdk.java.net/projects/jdk/16/ for more information. We can make a special note of JEP396. Can you list the ones that apply please? I can see that some are definitely HotSpot specific, but not sure about others. Created https://github.com/eclipse/openj9-docs/issues/726 Thanks.
