### ISSUE TITLE
jdk8 & 15: J9ILOps compile errors

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11246]
jdk8 all platforms:
See: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/769/console
```
17:19:39  make[4]: *** [E:/jenkins/tmp/workspace/build/src/build/windows-x86-normal-server-release/vm/compiler/build/rules/win-msvc/common.mk:83: E:/jenkins/tmp/workspace/build/src/build/windows-x86-normal-server-release/vm/objs/compiler/codegen/J9GCStackAtlas.obj] Error 2
17:19:39  E:\jenkins\tmp\workspace\build\src\build\windows-x86-normal-server-release\vm\compiler\il/ILOpCodesEnum.hpp(29) : error C2065: 'BCDCHK' : undeclared identifier
17:19:39  E:\jenkins\tmp\workspace\build\src\build\windows-x86-normal-server-release\vm\compiler\il/J9ILOps.hpp(84) : error C2039: 'zd2dfAbs' : is not a member of 'TR'
17:19:39  E:\jenkins\tmp\workspace\build\src\build\windows-x86-normal-server-release\vm\compiler\il/J9ILOps.hpp(84) : error C2065: 'zd2dfAbs' : undeclared identifier
...
```

jdk15 also:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-x64-openj9/114/console

**Comment by sxa** [comment]
Looks like https://ci.eclipse.org/openj9/job/Build_JDK15_x86-64_linux_Nightly/115 had a couple of nights of failures and then started working again last night. Possibly related?

**Comment by pshipton** [comment]
A change was delivered (https://github.com/eclipse/openj9/pull/11169) which was dependent on OMR promotion (https://github.com/eclipse/omr/pull/5670), but OMR promotion was failing because of a bad change (https://github.com/eclipse/openj9/pull/11114) which was reverted (https://github.com/eclipse/openj9/pull/11245).

All good now.
