### ISSUE TITLE
Mac fails to build with java.dSYM: is a directory

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11244]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_mac_OMR/760
```
16:52:58  rm: /Users/jenkins/workspace/Build_JDK8_x86-64_mac_OMR/build/macosx-x86_64-normal-server-release/jdk/bin/java.dSYM: is a directory
16:52:58  make[2]: *** [/Users/jenkins/workspace/Build_JDK8_x86-64_mac_OMR/build/macosx-x86_64-normal-server-release/jdk/bin/java.dSYM] Error 1
```

I'm thinking it's an intermittent problem.
First seen before in testing for https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/463

**Comment by pshipton** [comment]
@keithc-ca @JasonFengJ9 fyi

**Comment by keithc-ca** [comment]
It's not clear how to me how it could succeed (unless configured with `--disable-debug-info`).
I think this problem was introduced by:
* 8252395: [8u] --with-native-debug-symbols=external doesn't include debuginfo files for binaries

**Comment by keithc-ca** [comment]
Actually, I do have a theory. When make considers the rule to produce `java.dSYM`, if either of the rules to produce `java.dSYM/Contents/Info.plist` or `java.dSYM/Contents/Resources/DWARF/java` has already been executed, it's almost guaranteed that the `java.dSYM` directory will be newer than the prerequisites and so make will avoid the troublesome commands.
