### ISSUE TITLE
JPMS IllegalAccessError

### ISSUE THREAD

**Issue by Thihup** [eclipse/openj9#11274]
Java -version output
--------------------
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)

openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

Summary of problem
------------------
Running a JPMS application with OpenJ9 throws IllegalAccessError while with Hotspot it does not.

Diagnostic files
----------------
[bug-jpms.zip](https://github.com/eclipse/openj9/files/5598071/bug-jpms.zip)

```
$ mvn clean package
$ java --module-path target/bug-jpms-1.0-SNAPSHOT.jar:target/dependency -m jpms.example/jpms.example.Main
```

Output OpenJ9
```
Exception in thread "DefaultHttpServer-ProcessingThread-0" java.lang.IllegalAccessError: Class cloud/piranha/http/nano/NanoHttpServerProcessor(module cloud.piranha.http.nano) can not access class cloud/piranha/http/webapp/HttpWebApplicationResponse(module cloud.piranha.http.webapp) because module module cloud.piranha.http.nano does not read module module cloud.piranha.http.webapp 
        at cloud.piranha.http.nano/cloud.piranha.http.nano.NanoHttpServerProcessor.process(NanoHttpServerProcessor.java:66)
        at cloud.piranha.http.impl/cloud.piranha.http.impl.DefaultHttpServerProcessingThread.run(DefaultHttpServerProcessingThread.java:85)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:845)
```

**Comment by Thihup** [comment]
It says that the cloud.piranha.http.nano modules doesn't read the cloud.piranha.http.webapp, however this dependency is explicit here: https://github.com/piranhacloud/piranha/blob/master/http/nano/src/main/java/module-info.java#L37

**Comment by pshipton** [comment]
@tajila fyi

**Comment by tajila** [comment]
@JasonFengJ9 can you please take a look at this

**Comment by JasonFengJ9** [comment]
Sure, will pick up this.

**Comment by JasonFengJ9** [comment]
The actual cause of `IllegalAccessError` was `checkVisibility()` failed for `cloud/piranha/http/nano/NanoHttpServerProcessor` reading `cloud/piranha/webapp/impl/DefaultWebApplicationResponse`. 

A workaround is to add `--add-reads cloud.piranha.httpano=cloud.piranha.webapp.impl`.

Next action is to fix the misleading error message, and understand why `hotspot` doesn't fail (probably due to different code path and not invoke `DefaultWebApplicationResponse`).

**Comment by JasonFengJ9** [comment]
**Update:**

`IllegalAccessError` occurred when checking the target super classes.
Here is a simplified testcase. There are three modules involved, `module.a`, `module.b` and `module.c`.

```
module.a
     requires module.b;

     invoke `module.b/com.openj9.moduleB.B.name()`
```

```
module.b
     exports com.openj9.moduleB;
     requires module.c;

     public class B extends C {
     }
```

```
module.c
     exports com.openj9.moduleC;

     public class C {
	public static String name() {
        }
     }
```

`OpenJ9` output:
```
Exception in thread "main" java.lang.IllegalAccessError: Class com/openj9/moduleA/A(module module.a) can not access class com/openj9/moduleB/B(module module.b) because module module module.a does not read module module module.b 
	at module.a/com.openj9.moduleA.A.main(A.java:7)
```
This can be workaround via adding `--add-reads module.a=module.c` or changing `module.b` requires clause to `requires transitive module.c;`.
However `RI` works out-of-box.
It is not clear from modularity specification if the target super class should be checked for module access.

**Comment by tajila** [comment]
According to the spec

```
5.4.4. Access Control

Access control is applied during resolution (§5.4.3) to ensure that a reference to a class, interface, field, or method is permitted. Access control succeeds if a specified class, interface, field, or method is accessible to the referring class or interface.

A class or interface C is accessible to a class or interface D if and only if one of the following is true:

    C is public, and a member of the same run-time module as D (§5.3.6).

    C is public, and a member of a different run-time module than D, and C's run-time module is read by D's run-time module, and C's run-time module exports C's run-time package to D's run-time module.

    C is not public, and C and D are members of the same run-time package.

```

@JasonFengJ9 Do you know where we are doing the `superClass` access check?

**Comment by JasonFengJ9** [comment]
Thanks @tajila 
The `lookupClass` is being checked here which is updated via `lookupClass = SUPERCLASS(lookupClass)` at end of the loop.
https://github.com/eclipse/openj9/blob/c144b7cf44c4615323776676762b7cb3b662de35/runtime/vm/lookupmethod.c#L700
https://github.com/eclipse/openj9/blob/c144b7cf44c4615323776676762b7cb3b662de35/runtime/vm/lookupmethod.c#L204

> C is public, and a member of a different run-time module than D, and C's run-time module is read by D's run-time module, and C's run-time module exports C's run-time package to D's run-time module.

This issue is the case that the module of `D` reads the module of `C`, but the method being invoked is a method of `C` inherited from `B` which is from another module only read by the module of `C` but not module of `D`.

**Comment by tajila** [comment]
Perhaps the visibility check should be performed with the `targetClass` rather than the `methodClass`

**Comment by JasonFengJ9** [comment]
> Perhaps the visibility check should be performed with the targetClass rather than the methodClass

Agreed, `checkModuleAccess` just need check against `targetClass` instead of `methodClass`, other visibility check can stay intact.

**Comment by tajila** [comment]
The module check may not be needed at all in methodlookup since the class/interface resolve is always done first. The module check would have already been performed on the correct class.

**Comment by JasonFengJ9** [comment]
This seems the module access check when resolving the `class/interface`
https://github.com/eclipse/openj9/blob/c60b68ad083fb64d7936759202ce48deb52c6ed2/runtime/vm/resolvesupport.cpp#L403
