### ISSUE TITLE
JEP 397 Sealed Classes (Second Preview)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11273]
See https://openjdk.java.net/jeps/397

**Comment by pshipton** [comment]
@tajila

**Comment by tajila** [comment]
https://mail.openjdk.java.net/pipermail/amber-spec-experts/2020-May/002161.html

**Comment by tajila** [comment]
Latest specs:
http://cr.openjdk.java.net/~gbierman/jep397/jep397-20201104/specs/sealed-classes-jls.html
http://cr.openjdk.java.net/~gbierman/jep397/jep397-20201104/specs/sealed-classes-jvms.html

**Comment by tajila** [comment]
I think these changes will be merged sometime next week.

**Comment by tajila** [comment]
@ChengJin01 Can you please take a look at this

**Comment by ChengJin01** [comment]
I went through all these Specs mentioned above against the JEP360 related Specs at 
https://openjdk.java.net/jeps/360: JEP 360: Sealed Classes (Preview)
http://cr.openjdk.java.net/~dlsmith/jep360/jep360-20200421/specs/sealed-types-jls.html
http://cr.openjdk.java.net/~dlsmith/jep360/jep360-20200421/specs/sealed-types-jvms.html

It seems the only updated descriptions related to Sealed Classes to be addressed in terms of VM is the check of sealed superclass/superinterface in http://cr.openjdk.java.net/~gbierman/jep397/jep397-20201104/specs/sealed-classes-jvms.html as follows: 
```
Table 4.7-A. Predefined class file attributes (by section)
Attribute           | Section | class file | Java SE
PermittedSubclasses | 4.7.30 | 60.65535 | 16

5.3.5 Deriving a Class from a class File Representation
...
3. If C has a direct superclass, the symbolic reference from C to its direct superclass is resolved ...
...
    Otherwise, if the class named as the direct superclass of C has a PermittedSubclasses attribute (4.7.30)
    and any of the following are true, derivation fails with a IncompatibleClassChangeError:
---> (1)The superclass belongs to a different run-time module than C.
---> (2)C does not have its ACC_PUBLIC flag set (4.1) and the superclass belongs to a different run-time package than C.
...
4. If C has any direct superinterfaces, the symbolic references from C to its direct superinterfaces are resolved
...
  Otherwise, for each direct superinterface, if the superinterface has a PermittedSubclasses attribute (4.7.30) 
   and any of the following are true, derivation fails with a IncompatibleClassChangeError:
---> (1) The superinterface belongs to a different run-time module than C.
---> (2) C does not have its ACC_PUBLIC flag set (4.1) and the superinterface belongs to a different run-time package than C.
...
```
Actually these check were already mentioned in JEP 360 https://openjdk.java.net/jeps/360 but not yet emphasized in the corresponding `sealed-types-jvms.html`
```
Description
...
The classes specified by permits must be located near the superclass: 
either in the same module (if the superclass is in a named module)
or in the same package (if the superclass is in the unnamed module).
...
```
I will get started to prepare the code involved and hopefully they should capture all expected errors in these latest test suites in OpenJDK16.

**Comment by ChengJin01** [comment]
The code is pretty much ready at https://github.com/ChengJin01/openj9/commit/b49212ba422a16192aafaaccf07aeb395751f5e1.
Will wait for the update of jtreg & JCK test suite specific to sealed class in JDK16.

**Comment by pshipton** [comment]
fyi https://github.com/eclipse/openj9/issues/11405

**Comment by ChengJin01** [comment]
As for https://github.com/eclipse/openj9/issues/11405,  there is probably no change from VM perspective given it only mentioned about the compiler (javac).  Will wait & see how it goes in the latest jtreg test suites.

**Comment by pshipton** [comment]
Note that Class.permittedSubclasses() was renamed to getPermittedSubclasses().

http://cr.openjdk.java.net/~iris/se/16/build/latest/diffsFrom15%2b36/java.base/java/lang/Class.html

**Comment by tajila** [comment]
> Note that Class.permittedSubclasses() was renamed to getPermittedSubclasses().

This is tracked in https://github.com/eclipse/openj9/issues/10977. @mikezhang1234567890 will be looking at it.

**Comment by tajila** [comment]
We have delivered all items for this feature.
