### ISSUE TITLE
cmdLineTester_classesdbgddrext_aix needs to be tagged as impl=openj9

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#11286]
Currently, the test target 'cmdLineTester_classesdbgddrext_aix' is being included in the set that are run against a hotspot implementation.  This is an error in the [playlist](https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/classesdbgddrext/playlist.xml#L80-L103) file which needs to be updated to add and [impls block](https://github.com/eclipse/openj9/blob/master/test/functional/cmdLineTests/classesdbgddrext/playlist.xml#L74-L77):

```
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
```

Example of failure at https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk11_hs_extended.functional_ppc64_aix/19/tapResults/
(or [rerun link](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?TARGET=extended.functional&SDK_RESOURCE=upstream&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&EXTRA_DOCKER_ARGS=&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&PLATFORM=ppc64_aix&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&JDK_VERSION=11&USER_CREDENTIALS_ID=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptopenjdk%2Fopenjdk-jdk11u&RELEASE_TAG=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-aix-ppc64-hotspot&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&TKG_SHA=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&NUM_MACHINES=&OPENJDK_SHA=&BUILD_LIST=functional&UPSTREAM_JOB_NUMBER=774&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None))

**Comment by AhwiniMirajkar** [comment]
Can I work on this

**Comment by smlambert** [comment]
Oh, looks like someone beat you to it @AhwiniMirajkar !  

This issue can be closed via https://github.com/AdoptOpenJDK/openjdk-tests/issues/2144.  

I will scan through the other comp:test issues to see if there are other similar ones that can be worked on.
