### ISSUE TITLE
Trademark symbol for Eclipse OpenJ9

### ISSUE THREAD

**Issue by xliang6** [eclipse/openj9#113]
At the top of [Eclipse OpenJ9's landing page](https://github.com/eclipse/openj9), it says "Eclipse OpenJ9". There is a no trademark symbol next to it as it is on [Eclipse OMR's landing page](https://github.com/eclipse/omr/).

Is this intentional? Either way, we should add an explanation for the difference between OpenJ9 and OMR.

**Comment by mstoodle** [comment]
I believe that text is set by Eclipse, not us (only the org admins can change the text on the repository, I think). If Eclipse has a trademark on "Eclipse OpenJ9" then it could have the (tm). I don't actually know if they do. @waynebeaton do you know?

We should probably provide a little more detail than the name of the project there, too :) .

**Comment by xliang6** [comment]
+1 on us providing more information on Eclipse OpenJ9.

**Comment by pshipton** [comment]
This appears done, closing. Please re-open if there is still a problem.
