### ISSUE TITLE
JDK16 changes for Hidden Classes

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11321]
See https://bugs.openjdk.java.net/browse/JDK-8256214

Some changes to Lookup

**Comment by tajila** [comment]
@hangshao0

**Comment by hangshao0** [comment]
I will look at this.

**Comment by babsingh** [comment]
In https://bugs.openjdk.java.net/browse/JDK-8256214, the new specification introduces the following new methods:

```
    In java.lang.invoke.MethodHandles.Lookup class:
        New Lookup::defineHiddenClassWithClassData method
        New Lookup::ORIGINAL mode and the following methods are updated to reflect this new mode
            Lookup::lookupModes
            Lookup::in
            Lookup::dropLookupIn
    java.lang.invoke.MethodHandles class
        New MethodHandles::classData(Lookup lookup, String name, Class<?> type) static method
        New MethodHandles::classDataAt(Lookup lookup, String name, Class<?> type, int index) static method
        MethodHandles::lookup and MethodHandles::privateLookupIn are updated to reflect the new ORIGINAL mode
```

Since we plan to move to OpenJDK MH (#7352) in JDK16, the above Java changes to J9 classes can be avoided.

**Comment by hangshao0** [comment]
> Since we plan to move to OpenJDK MH (#7352) in JDK16, the above Java changes to J9 classes can be avoided.

I agree. I was planning to just add the missing bit ORIGINAL and the public API to resolve the compilation issue. But from https://github.com/eclipse/openj9/issues/11312#issuecomment-736691412 I see you are already doing that.

**Comment by hangshao0** [comment]
Since https://github.com/eclipse/openj9/pull/11322 is merged, I think this can be closed. All the new changes here are in OpenJDK MH, which will be consumed by OpenJ9 in Java 16.

**Comment by babsingh** [comment]
**Updated refs:**
1. https://bugs.openjdk.java.net/browse/JDK-8256214
2. https://bugs.openjdk.java.net/browse/JDK-8230501

**Related commit:** https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/1e8bd60220e0d038d45f4421a5f8654dc9ac7bb5

All is Java code. No native dependencies found. 
`+1` to close this issue. 
But, we should relate it `project:MH` to verify functionality once OpenJDK MH is enabled in OpenJ9.
