### ISSUE TITLE
NPEs running OpenJDK tests on zlinux

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11333]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_Nightly/253/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl_Nightly/232/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/250
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_xl_Nightly/228
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_s390x_linux_Nightly/121/

**Comment by pshipton** [comment]
I suspect https://github.com/eclipse/openj9/pull/11088, which is the only OpenJ9 change since the last nightly build, where the failures didn't occur.
There were OMR changes as well https://github.com/eclipse/openj9-omr/compare/1f46e75...c041fba

**Comment by pshipton** [comment]
I'm testing with #11088 reverted, https://ci.eclipse.org/openj9/job/Pipeline-Personal-Build/239/

**Comment by dchopra001** [comment]
I've opened https://github.com/eclipse/openj9/pull/11338 to disable the change for now.
