### ISSUE TITLE
jdk8 sanity.functional cmdLineTest_sigabrtHandlingTest_0 consumes excessive heap/disk space?

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11335]
Testcase: sanity.functional cmdLineTest_sigabrtHandlingTest_0 consumes Gb's of disk space with core dumps, typically causing AdoptOpenJDK AIX machines to run out of disk space, see: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2075

This runs test https://github.com/eclipse/openj9/blob/master/test/functional/cmdline_options_testresources/src/VMBench/GPTests/GPTest.java
and on some AIX machines the dumps are between 6-9Gb each, and this testcase produces 5 of them, so that's roughly 40Gb of space required.

It is puzzling why this simple test is producing such a large core dump, is there a memory leak? is the heap pre-allocating to a % of the physical memory?
Either way, is it possible to alter the test behaviour to not produce such a large dump?

**Comment by pshipton** [comment]
The core dumps are not expected. The test is running with `-Xdump:system+heap+snap+jit:none` and should only be producing the javacore txt files.  When I run it on Linux no core files are produced. I'll try it on an AIX machine just in case.

Looking at https://github.com/AdoptOpenJDK/openjdk-tests/issues/2075#issuecomment-735703926 I see `Type=Bus error` in the crash output. 
- these tests shouldn't be crashing with Bus error or anything else
- Bus error is perhaps side affect of trying to write to the shared cache memory mapped file when the system is already out of space

The expected output from that particular test is as follows.
```
10:12:32   [ERR] JVMJ9VM197E -XX:+HandleSIGABRT is not supported with -Xrs.
10:12:32   [ERR] Error: Could not create the Java Virtual Machine.
10:12:32   [ERR] Error: A fatal exception has occurred. Program will exit.
```

**Comment by pshipton** [comment]
I can see on AIX there are core files being produced by the `-XX:-HandleSIGABRT` testing.  I guess this is the default OS behavior when abort isn't being handled by the VM. I'll see if there is some way to disable it, otherwise we can at least delete the files after they are created so only room for one at a time is required.

**Comment by pshipton** [comment]
As for the size of the core files, the default object heap size is 25% of the available RAM up to 57G. We can limit these tests with `-Xmx20m` to reduce the core file size as much as possible.
