### ISSUE TITLE
Remove J9VM_JIT_NEW_INSTANCE_PROTOTYPE macro

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#11334]
Remove uses of the `J9VM_JIT_NEW_INSTANCE_PROTOTYPE` macro and fold associated code guarded with it assuming it is always **defined**.

Original question:

> If memory serves, `J9VM_JIT_NEW_INSTANCE_PROTOTYPE` guards the newInstanceImpl work that was completed literally 20 years ago.  Is there any reason to keep guarding it, or should we assume it is always on by default?  Have we ever disabled it for some reason?
>
>My understanding is that there are several places in the JIT where this is assumed enabled (and hence unguarded), so disabling `J9VM_JIT_NEW_INSTANCE_PROTOTYPE` will likely cause problems.
>
>Opinions?  @gacholio

**Comment by gacholio** [comment]
This is one of the many flags that can never be changed.

**Comment by 0xdaryl** [comment]
So we can assume it is always defined, and hence remove it assuming as such.  Correct?

**Comment by gacholio** [comment]
Yes.

**Comment by JCodyA** [comment]
Hello!  This might be a good one for me but I'm having one issue, I'm not really sure where to look for the mentioned macro.  Do you know the specific source file or should I find it?  I think I understand macros and the problem but this is all pretty new for me.

**Comment by abhijeetshuklaoist** [comment]
Hi, 
I would like to work on this. Is this still open for assignment? If yes, could you please assign it to me.

**Comment by abhijeetshuklaoist** [comment]
I went ahead and spent some time on it and I have a PR ready for this : https://github.com/eclipse/openj9/pull/11719

**Comment by gacholio** [comment]
Note the attached PR does not remove the flag itself, just the uses.
