### ISSUE TITLE
Improve cmdline_options_tester

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#11351]
The [command tokenizer](https://github.com/eclipse/openj9/blob/master/test/functional/cmdline_options_tester/src/Tokenizer.java) should be improved to also handle single-quotes so they could be used to deal with arguments that should contain double-quotes.

This was noticed in #11340 where, instead of:
```
<command>bash -c $Q$ulimit -c 0 ; $EXE$ $LIMT_HEAPSIZE$ $DUMP$ -Xrs $CP$ abort$Q$</command>
```
we would like to say:
```
<command>bash -c 'ulimit -c 0 ; $EXE$ $LIMT_HEAPSIZE$ $DUMP$ -Xrs $CP$ abort'</command>
```
so the double-quotes between the single-quotes (e.g. in `$EXE$`) are not given their usual special treatment.

For the time-being, we are lucky that, on platforms where this is needed, `$EXE$` contains no embedded spaces, so in
```
bash -c "ulimit -c 0 ; ".../java" -Xmx20 ..."
```
the quotes pair like this:
```
bash -c {ulimit -c 0 ; }.../java{ -Xmx20 ...}
```
This should be fixed so we don't need to rely on luck.

**Comment by TromboneMoose** [comment]
Hello!  I'm looking for a good first issue and this looks promising.  I think I would like to take a shot at it.

**Comment by TromboneMoose** [comment]
Hello!  I'm looking for a good first issue and this looks promising.  I'd like to take a shot at fixing it.

**Comment by keithc-ca** [comment]
@TromboneMoose Thanks for the offer of help. I've assigned this to you.

**Comment by TromboneMoose** [comment]
I will likely need to ask for guidance along the way.  I want to make sure to follow all your guidelines and do my part as professionally as possible.  This is all new territory for me!  I'm currently reading the contributing guide and will create a WIP pull request asap.
