### ISSUE TITLE
Merging Panama & Valhalla test projects

### ISSUE THREAD

**Issue by taliamccormick** [eclipse/openj9#1135]
Project Panama and Project Valhalla are both ongoing projects to develop future Java features. Project Panama's goal is to develop a bridge between Java and non-Java libraries (eg. C, C++). Project Valhalla proposes new language features for Java 10 onward. 

Both projects are for future features. As their contents become relevant to the current Java version, tests will likely need to be moved from from the Panama/Valhalla test project to another test project. Given that both test projects are similar, it makes sense to merge the Panama tests and Valhalla tests into a joint 'FutureJEP' test project.

**Comment by taliamccormick** [comment]
I plan to merge the Panama test project and the Valhalla test project into a single joint 'FutureJEP' project. Doing so will create a new 'FutureJEP' test subset.

Tagging @smlambert & @llxia  for any necessary design discussion. In particular, I would like to keep 'FutureJEP', 'Valhalla', and 'Panama' subsets so that they can easily be run separately. However, I am aware that it is better to avoid having unnecessary subsets defined.

**Comment by llxia** [comment]
Yes, we would like to maintain minimal subsets.
If we still need to run Panama and Valhalla test separately, does it make sense to keep them separate? In this way, we can run the test based on directory.

`cd path/to/directory; make -f autoGen.mk _sanity`

**Comment by smlambert** [comment]
Is there a reason why futureJEP tests are not simply going into Java10 / Java11  etc subsets, since it is known which Java version they are targeted to?  

I know we initially split them as there was a need to build Panama and Valhalla with different compiler options, but is that still the case?

**Comment by pshipton** [comment]
> Is there a reason why futureJEP tests are not simply going into Java10 / Java11 etc subsets, since it is known which Java version they are targeted to?

I don't think this is true. Changes go into OpenJDK when they are working and ready. Upcoming features may not have a target, or could be expected to go in but miss the 6 month window.

**Comment by taliamccormick** [comment]
Projects Panama and Valhalla are working on features that are 6 months to 2 years away. Due to their timeline:
- Tests may change frequently
- Different compiler options may be needed for the VM
- Different tools may require different or more flexible versions that the other tests (eg. ASM7 for nestmates attributes, groveller for native method handles)

The future JEPs tests are also only run on the future jeps spec - a JVM which is compiled with different spec flags. Merging the future JEPs tests with the regular tests means that we need to ensure the future jeps tests are only run on the correct VM.

The different timeline/requirements for the future jeps tests will make the test project brittle; adding them to the existing Java10/11 tests would make those tests brittle, too

**Comment by smlambert** [comment]
Ok, so I 'get' the need for FutureJEP based on the answers above, and I agree it is undesirable to keep Panama and Valhalla once they are merged into it.  So it is a very good goal to plan to get rid of Panama and Valhalla separate subsets once FutureJEP is working as expected (let's set a target date for it to avoid unintended creep/bloat).

**Comment by smlambert** [comment]
Changing tests frequently should not in theory make them brittle, it likely makes them more robust as they are being more closely monitored/curated/updated.  Features that are 6 months away are imminent, and the test suite that accompanies them should be well-planned and working as well as the feature.  

There are also tests going into Java10, is it simply because the Panama and Valhalla projects are less well-defined?  Based on Pete's note, am I to assume these 2 projects not targeted to Java10 because they are of unknown readiness?

FutureJEP features live in the same code base as the main stream code.  Are they built at the same time as the rest of the code?  Or is there a separate build.

Related discussion: https://github.com/eclipse/openj9/issues/170

**Comment by pshipton** [comment]
Java 10 is locked down already. There aren't any new features that affect OpenJ9 in any significant way, but there are a few new APIs (not covered by any feature) that need tests. The new APIs are unrelated to Panama and Valhalla.

Java 11 is still open for any new features that are ready in time.

**Comment by tajila** [comment]
> Based on Pete's note, am I to assume these 2 projects not targeted to Java10 because they are of unknown readiness?

Panama and Valhalla are fairly large projects and will be released in small increments starting with Java11 (Valhalla - nestmates). What is coming in future (Java12+) releases is not well known but as we get closer to the date we'll have a better idea.

> FutureJEP features live in the same code base as the main stream code. Are they built at the same time as the rest of the code? Or is there a separate build.

They are built separately. Currently, we have a separate spec for Panama, this will become the FutureJEPs spec and we'll turn on flags for nestmates, valuetype's, etc. They have to be built differently because some of the projects require classes that are not on the main OpenJDK branch. Currently, we pull in classes from OpenJDK experimental builds, similar to what is done with the rawbuilds.

**Comment by smlambert** [comment]
Yep, I am trying to determine how to best manage the test material as it is being stretched across multiple versions Java8+ and multiple implementations/projects (which hopefully mostly can be contained within FutureJEP project).  

A similar example of a component that spans this would be the JCLs, which are split out into different repos per version and per special project. 

As discussed in #170 we have decided to try to avoid separate repos, but we then bear the burden in the test framework (that we are actively trying to keep simple).  Thus my line of query on whether we can just use the Java10AndUp, Java11AndUp approach.  The answer is clearly no, which is fine, we need what we need.  Next best is to keep to a single FutureJEP project as a place for these larger special projects to incubate.

**Comment by DanHeidinga** [comment]
> They have to be built differently because some of the projects require classes that are not on the main OpenJDK branch.

Can both the Valhalla and Panama -related tests be compiled in the same test project if "the tests require classes" that aren't in the main OpenJDK branch?  Won't the Valhalla-related tests require classes that are only in the valhalla builds and panama tests required panama-specific classes?

My understanding is that all tests in the same test project have to compile from source with the same JDK.  While there is the ability to selectively run a subset of the tests, all of the tests in the same project have to be compiled at the same time.  There isn't (currently) the ability to compile a subset.

Does the merge into a single project still make sense in light of that restriction?

**Comment by taliamccormick** [comment]
I'm not sure what the requirements for the Panama tests are.
The current Valhalla tests do not need to be compiled on a Valhalla-specific jdk - they generate and load compiled .class content using the asm tool. Once there are tests for the nestmates java.lang.Class API, the tests may need to be compiled with a Valhalla JDK. For the initial manual testing of the java.lang.Class API changes, we had generated a jar and ran manual tests as
```
javac --patch-module java.base=nestmates-patch.jar *.java
java --patch-module java.base=nestmates-patch.jar <java test file>
```
Would it be possible and reasonable to generate the nestmates patch jar and apply it to the shared Panama JDK for the nestmates java.lang.Class API tests?

**Comment by DanHeidinga** [comment]
That's a neat approach @taliamccormick!  Will it scale when there are multiple subsets of tests for different SDKs?  ie: Valhalla LWorld vs NestMates, Panama VectorAPI vs LDL/FFI, Loom Fibers, etc?

I'm 100% on board with finding a way to test these changes in the project before the Valhalla / Panama / Loom etc projects are merged into the mainline.  We just need to think though the best way to make this work.

For NestMates, as we expect it to be targeted to JDK11, can we put the tests in the Java11andUp folder?  It's not as clear where to land tests for other subsets of the projects.

**Comment by taliamccormick** [comment]
I don't think it will scale well.

We would need a jar for each class/package that is having API content tested which is different from the SDK being tested and if it's a static jar which is kept in the test project then it would need to regenerated each time there's a change in the API. Generating the jar itself with the test/TestConfig code doesn't make sense - since it's part of VM/SDK content, rather than test content - and I think we're actively trying to avoid keeping jars within the test project - they are loaded from central.maven.org in test/TestConfig/scripts/tools/getDependencies.pl. 

Also, I just realized that using a jar which makes use of corresponding private native methods in our VM, such as:
```
private native Class<?>[] getNestMembersImpl();
public Class<?> getNestHost() { return getNestHostImpl(); }
```
in java.lang.Class would not let the tests be run against a different JVM.

Scratch that idea.
