### ISSUE TITLE
PatchModuleImgTest, UpgradeModPathTest failing on Windows, jvm.dll failed to load: j9vm29

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11365]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly/557
PatchModuleImgTest_Advanced_0
UpgradeModPathTest_ExpDirImg_0
UpgradeModPathTest_JarredImg_0
PatchModuleImgTest_PlatformMod_0
PatchModuleImgTest_UnexportedType_0

They are all like the followining.
PatchModuleImgTest_Advanced_0
```
STF 03:13:11.587 - +------ Step 9 - Run application class override test where we specify two exploded module paths in a single --patch-module option
STF 03:13:11.587 - | Run foreground process
STF 03:13:11.587 - |   Program:     F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/openjdk-tests/TKG/test_output_16070712767195/PatchModuleImgTest_Advanced_0/20201204-031258-PatchModuleImageTest/tmp/6.XpJVM/bin/java
STF 03:13:11.587 - |   Mnemonic:    OT1
STF 03:13:11.587 - |   Echo:        ECHO_ON
STF 03:13:11.587 - |   Expectation: CLEAN_RUN within 5m
STF 03:13:11.587 - |
STF 03:13:11.588 - Running command: F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/openjdk-tests/TKG/test_output_16070712767195/PatchModuleImgTest_Advanced_0/20201204-031258-PatchModuleImageTest/tmp/6.XpJVM/bin/java --add-reads com.test=ALL-UNNAMED --add-exports com.hello/adoptopenjdk.test.modularity.newpkg=com.test --patch-module com.hello=F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1\jvmtest\system\openjdk-systemtest\openjdk.test.modularity\bin\common-override\com.hello;F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1\jvmtest\system\openjdk-systemtest\openjdk.test.modularity\bin\common-override-new\com.hello -classpath F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/jvmtest/system/systemtest_prereqs/junit-4.12/junit-4.12.jar;F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/jvmtest/system/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar org.junit.runner.JUnitCore net.adoptopenjdk.test.modularity.junit.TestOverrideUsingMultipleFilePaths
STF 03:13:11.588 - Redirecting stderr to F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/openjdk-tests/TKG/test_output_16070712767195/PatchModuleImgTest_Advanced_0/20201204-031258-PatchModuleImageTest/results/9.OT1.stderr
STF 03:13:11.588 - Redirecting stdout to F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/openjdk-tests/TKG/test_output_16070712767195/PatchModuleImgTest_Advanced_0/20201204-031258-PatchModuleImageTest/results/9.OT1.stdout
STF 03:13:11.596 - Monitoring processes: OT1
OT1 stderr jvm.dll preloadLibrary: LoadLibrary(F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1\openjdk-tests\TKG\test_output_16070712767195\PatchModuleImgTest_Advanced_0\20201204-031258-PatchModuleImageTest\tmp\6.XpJVM\bin\compressedrefs\j9vm29.dll) error: ce
OT1 stderr jvm.dll preloadLibrary: LoadLibrary(F:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1\openjdk-tests\TKG\test_output_16070712767195\PatchModuleImgTest_Advanced_0\20201204-031258-PatchModuleImageTest\tmp\6.XpJVM\bin\compressedrefs\j9hookable29.dll) error: ce
OT1 stderr jvm.dll failed to load: j9vm29
STF 03:13:11.649 - **FAILED** Process OT1 ended with exit code (3221225477) and not the expected exit code/s (0)
STF 03:13:11.650 - Monitoring Report Summary:
STF 03:13:11.650 -   o Process OT1 ended with exit code (3221225477) and not the expected exit code/s (0)
STF 03:13:11.650 - Killing processes: OT1
STF 03:13:11.650 -   o Process OT1 is not running
```

**Comment by pshipton** [comment]
@llxia @Mesbah-Alam  I believe this is due to having longer directory paths because of the parallelism. We need to do something to shorten the paths.

**Comment by llxia** [comment]
@Mesbah-Alam we can shorten the test name in the playlist to fix this for now. 
However, I would like to understand why the above system test uses JVM under test_output dir. Do you happen to know?

java used in the test:
`F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/openjdk-tests/TKG/test_output_16070712767195/PatchModuleImgTest_Advanced_0/20201204-031258-PatchModuleImageTest/tmp/6.XpJVM/bin/java`

java should be used:
`F:/Users/jenkins/workspace/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java`

**Comment by Mesbah-Alam** [comment]
> I would like to understand why the above system test uses JVM under test_output dir

HI @llxia , The tests that have "Img" in their names are supposed to test the runtime image, not the main SDK. This is why they are using `~/6.XpJVM/bin/java`. 

For example, PatchModuleImageTest.java [creates a runtime image](https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.modularity/src/com.stf/net/adoptopenjdk/test/modularity/PatchModuleImageTest.java#L96) first and then runs tests on it. 

> We need to do something to shorten the paths.

@pshipton , Most likely this is the case. I will shorten these names and retry.

**Comment by llxia** [comment]
Just be aware, once mixedref build is enabled, the path will be longer. In addition to shorten the test names, maybe shorten the image path in system tests as well.

**Comment by llxia** [comment]
Close this issue as the latest windows nightly is green: https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_windows_Nightly/561/
