### ISSUE TITLE
Support "jenkins test all" as a synonym for "jenkins test sanity" and "jenkins test extended"

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#1138]
Looking at [1] we seem to support launching:

> Current supported PR builds are "Compile", "Compile & Sanity", or "Compile & Extended"

It would be wonderful if we could also support "Compile & Sanity & Extended" via "jenkins test all", or any other flavor of testing such as "functional" which I'm told exists. Our guideline at the moment is to launch both sanity and extended testing for every PR pending ample machine resources. This would simplify launching such builds via a single command.

[1] https://github.com/eclipse/openj9/blob/6fa061ffc2730e3d0b3de1c247581b93b478feae/buildenv/jenkins/README.md

**Comment by fjeremic** [comment]
@AdamBrousseau FYI, is this something within the realm of possibilities?

**Comment by fjeremic** [comment]
It also seems you cannot post:

> Jenkins test sanity
> Jenkins test extended

in the same comment to trigger both builds. They have to be posted in separate comments which creates unnecessary spam. It would definitely be wonderful if we could implement this.

**Comment by AdamBrousseau** [comment]
`Jenkins test all` should work now.
Ex regex
`.*\bjenkins\s+test\s+(all|sanity)\b\s*($|\n|depends\s+.*|(all|([a-z]+,)*zlinux(,[a-z]+)*)\s*($|\n|depends\s+.*|all|(jdk[0-9]+,)*jdk8(,jdk[0-9]+)*)(\s+depends.*)?)`

Have yet to figure out how to fix the multiline problem though. I think if I simply add `.*` to the end it starts to get too hungry. Will have to spend a few minutes to figure it out.

**Comment by fjeremic** [comment]
> Jenkins test all should work now.

Awesome! Thank you very much!

> Have yet to figure out how to fix the multiline problem though. I think if I simply add .* to the end it starts to get too hungry. Will have to spend a few minutes to figure it out.

Sounds like we need some tests here? Perhaps write a few "sample comments" with various combinations and have passing / failing criteria?

**Comment by fjeremic** [comment]
Just tried "Jenkins test all" in https://github.com/eclipse/openj9/pull/875 and it works as envisioned! @AdamBrousseau could I ask you to update https://github.com/eclipse/openj9/buildenv/jenkins/README.md with the new option documentation and behavior? In the PR you can link against closing out this issue.

**Comment by AdamBrousseau** [comment]
I think this was resolved in #1208
