### ISSUE TITLE
Improve gccheck for ownablesynchronizer in DDR

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/openj9#11384]
Currently `GCOwnableSynchronizerObjectListIterator` is taking head the list from `_head` slot of `mm_ownablesynchronizerobjectlist`.  However if this list is under scan the `_head` slot is NULL and actual head is saved in `_priorHead`. So `gccheck` does not check list for consistency.
For example:
```
> !mm_ownablesynchronizerobjectlist 0x00003FFF880A51F0
MM_OwnableSynchronizerObjectList at 0x3fff880a51f0 {
  Fields for MM_Base:
  Fields for MM_BaseNonVirtual:
	0x0: const U8* _typeId = !j9x 0x00003FFF8DEF3218 // "MM_OwnableSynchronizerObjectList"
  Fields for MM_OwnableSynchronizerObjectList:
	0x8: volatile struct J9Object* _head = !j9object 0x0000000000000000
	0x10: struct J9Object* _priorHead = !j9object 0x0000000088CE3710 // java/util/concurrent/locks/ReentrantLock$NonfairSync
	0x18: class MM_OwnableSynchronizerObjectList* _nextList = !mm_ownablesynchronizerobjectlist 0x00003FFF880A4D70
	0x20: class MM_OwnableSynchronizerObjectList* _previousList = !mm_ownablesynchronizerobjectlist 0x00003FFF880A5220
	0x28: UDATA _objectCount = 0x0000000000000000 (0)
}
```
So would be useful if `GCOwnableSynchronizerObjectListIterator` tries `_priorHead` as a head if `_head` slot is NULL

**Comment by dmitripivkine** [comment]
FYI @amicic @LinHu2016

**Comment by LinHu2016** [comment]
Thanks @dmitripivkine point the case, but _priorHead might only work during concurrent gc, for stop the world gc, we try to rebuild the ownablesynchronizerobjectlist list piggyback the objects scan, so during scanning, might be not able to retrieve whole list(gc-start and gc-end are fine). also there is a plan to remove whole OwnableSynchronizerObjectList in near future, so we'd better holding it as low priority except it cause the immediate issue.

**Comment by dmitripivkine** [comment]
Thanks Lin. There is a failure https://github.com/eclipse/openj9/issues/10489 (and dup https://github.com/eclipse/openj9/issues/11379) where GC crashes in `MM_MarkingSchemeRootClearer::scanOwnableSynchronizerObjects()` because of list corruption (assigned to JIT). There is no gccheck support to find corrupted object pointer, it should be done manually and it is inconvenient. I agree with you that way how we are handling Ownable Synchronizers is going to be changed in the future.
So let see to progress with this problem. Maybe it is ok for now

**Comment by AhwiniMirajkar** [comment]
Can I work on this

**Comment by dmitripivkine** [comment]
> Can I work on this

Thank you very much for offering help.
Unfortunately we reviewed this idea again and decided not go ahead with this improvement as far as we are planning to implement new way of handling of Ownable Synchronizers
