### ISSUE TITLE
JITServer should know when client is in a startup phase for hint support

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#11386]
`testSCCMLSoftmx_1`  [fails](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_extended.functional_x86-64_linux_jit_Nightly/249/tapResults/) due to JIT hints not being added.
The test requires for memory and cpu expensive compilations to add hints to the SCC, however
the hints are only added during startup, to reduce the total number of them.
But since JITServer is never in a startup phase and doesn't know the phase client is in, hints never get added.

Relevant code:
https://github.com/eclipse/openj9/blob/2aeffa1dfecbb10786d89c223d931753fe90141e/runtime/compiler/control/CompilationThread.cpp#L8811-L8844

**Comment by dmitry-ten** [comment]
@mpirvu what do you think is the best way to handle this?
I propose we store whether client is in a startup phase in server's client session and add a front-end query that would replace `jitConfig->javaVM->phase != J9VM_PHASE_NOT_STARTUP` in the above example.
I'm not sure if there are other places where client's phase would matter but if such cases exist we could use the same query there as well.

**Comment by mpirvu** [comment]
Yes, that's the right approach: store the phase in the ClientSession, update with each compilation request and use a frontend query to retrieve it.
