### ISSUE TITLE
ValueTypes: Gencon support for flattened arrays

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11382]
When running the ValueType tests with `-Xgcpolicy:gencon -Xnocompactgc -XX:ValueTypeFlatteningThreshold=99999 -XX:+EnableArrayFlattening` it fails with: 

```
15:41:54.783 0x150c00    j9mm.142    *   ** ASSERTION FAILED ** at ../../gc_glue_java/ScavengerDelegate.cpp:384: ((false))
```

The code in question is in `MM_ScavengerDelegate::getObjectScanner`

```
		case GC_ObjectModel::SCAN_FLATTENED_ARRAY_OBJECT:
		{
			Assert_MM_true(J9_IS_J9CLASS_FLATTENED(clazzPtr));
			Assert_MM_unimplemented();
		}
		break;
```

**Comment by tajila** [comment]
@dmitripivkine

**Comment by dmitripivkine** [comment]
ok, thank you. This is missed implementation too... I guess it was not obvious how to disable Split Arrays scan for Flattened Arrays so it was not added at all

**Comment by dmitripivkine** [comment]
This issue has been fixed. I believe the only piece of work left there is an implementation for https://github.com/eclipse/openj9/issues/11771 new functionality
