### ISSUE TITLE
String.equalsIgnoreCase() behaves differently to OpenJDK for Turkish 'i' characters

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9#11399]
In Turkish there are four 'i' characters:

- Dotted lowercase  - `U+0069 (i)`
- Dotless uppercase - `U+0049 (I)`
- Dotted uppercase  -  `U+0130 (İ)`
- Dotless lowercase  -  `U+0131 (ı)`

With OpenJDK, `String.equalsIgnoreCase()` returns `true` when comparing all of these characters to one another:

```
"İ".equalsIgnoreCase("İ") = true
"İ".equalsIgnoreCase("ı") = true
"İ".equalsIgnoreCase("I") = true
"İ".equalsIgnoreCase("i") = true

"ı".equalsIgnoreCase("İ") = true
"ı".equalsIgnoreCase("ı") = true
"ı".equalsIgnoreCase("I") = true
"ı".equalsIgnoreCase("i") = true

"I".equalsIgnoreCase("İ") = true
"I".equalsIgnoreCase("ı") = true
"I".equalsIgnoreCase("I") = true
"I".equalsIgnoreCase("i") = true

"i".equalsIgnoreCase("İ") = true
"i".equalsIgnoreCase("ı") = true
"i".equalsIgnoreCase("I") = true
"i".equalsIgnoreCase("i") = true
```

However, with OpenJ9, `String.equalsIgnoreCase()` returns `false` when comparing `U+0130 (İ)` and `U+0131 (ı)`:

```
"İ".equalsIgnoreCase("İ") = true
"İ".equalsIgnoreCase("ı") = false  <---
"İ".equalsIgnoreCase("I") = true
"İ".equalsIgnoreCase("i") = true

"ı".equalsIgnoreCase("İ") = false  <---
"ı".equalsIgnoreCase("ı") = true
"ı".equalsIgnoreCase("I") = true
"ı".equalsIgnoreCase("i") = true

"I".equalsIgnoreCase("İ") = true
"I".equalsIgnoreCase("ı") = true
"I".equalsIgnoreCase("I") = true
"I".equalsIgnoreCase("i") = true

"i".equalsIgnoreCase("İ") = true
"i".equalsIgnoreCase("ı") = true
"i".equalsIgnoreCase("I") = true
"i".equalsIgnoreCase("i") = true
```

The specification for `String.equalsIgnoreCase()` says:

> Two strings are considered equal ignoring case if they are of the same length and corresponding characters in the two strings are equal ignoring case.
>
> Two characters c1 and c2 are considered the same ignoring case if at least one of the following is true:
>
> - The two characters are the same (as compared by the == operator)
> - Applying the method Character.toUpperCase(char) to each character produces the same result
> - Applying the method Character.toLowerCase(char) to each character produces the same result

So it seems that OpenJ9 is behaving correctly, because none of the conditions above are satisfied for `İ` and `ı`. Both OpenJDK and OpenJ9 produce these results from `Character.toUpperCase()` and `Character.toLowerCase()`:

```
Character.toUpperCase("İ") = İ
Character.toUpperCase("ı") = I

Character.toLowerCase("ı") = ı
Character.toLowerCase("İ") = i
```

i.e. "applying the method `Character.toUpperCase(char)` to each character" does not produce the same result, and "applying the method `Character.toUpperCase(char)` to each character" does not produce the same result either. And the two characters are certainly not the same.

However, I also found [an OpenJDK bug report](https://bugs.openjdk.java.net/browse/JDK-8049038) which includes the same `String.equalsIgnoreCase()` comparison in its testcase, but the evaluation states that the result should be `true`:

> String.equalsIgnoreCase() is a locale insensitve method. It compares two strings based on the logic in the javadoc, which checks the length and compares each character which is locale insensitive. Thus all those test cases should return true.

The net of all this is that I'm not entirely sure which implementation is behaving correctly (perhaps I'm misinterpreting the specification somehow?), but it is certainly true that there is a difference between OpenJ9 and the reference OpenJDK implementation.

Testcase source:

```
public class TurkishITest {
	public static void main(String[] args) {
		String[] turkishIStrings = { "\u0130", "\u0131", "\u0049", "\u0069" };
		char[] turkishIChars = { '\u0130', '\u0131', '\u0049', '\u0069' };
		
		for (String s1 : turkishIStrings) {
			for (String s2 : turkishIStrings) {
				System.out.println("\"" + s1 + "\".equalsIgnoreCase(\"" + s2 + "\") = " + s1.equalsIgnoreCase(s2));
			}
			System.out.println();
		}
		
		for (char c : turkishIChars) {
			System.out.println("Character.toUpperCase(\"" + c + "\") = " + Character.toUpperCase(c));
			System.out.println("Character.toLowerCase(\"" + c + "\") = " + Character.toLowerCase(c));
		}
	}
}
```

**Comment by pshipton** [comment]
@paulcheeseman what version(s) of OpenJ9 have you testing?

**Comment by paulcheeseman** [comment]
OpenJ9 0.23 in both Java 8 and Java 11. Specifically these two AdoptOpenJDK builds:

- OpenJDK8U-jdk_x86-32_windows_openj9_8u275b01_openj9-0.23.0
- OpenJDK11U-jdk_x64_windows_openj9_11.0.9_11_openj9-0.23.0

I also see the same behaviour with IBM Java 8.0.6.20. This isn't a regression though - I see the same behaviour going all the way back through older 7.x and 6.x releases.

**Comment by tajila** [comment]
@sharon-wang Can you please take a look at this?

**Comment by sharon-wang** [comment]
Sure, taking a look

**Comment by paulcheeseman** [comment]
The OpenJDK code does something which isn't described in the spec. It compares the characters after converting them to uppercase, then, crucially, it converts those uppercase characters back to lowercase and compares them again.

This means that `"İ".equalsIgnoreCase("ı")` and `"ı".equalsIgnoreCase("İ")` will return true because:

```
Character.toUpperCase("İ") = İ  ---> Character.toLowerCase("İ") = i
Character.toUpperCase("ı") = I  ---> Character.toLowerCase("I") = i
```

The code is here:

https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/25cd39ef5b98/src/share/classes/java/lang/String.java#l1376

This extra comparison step seems to have always been present in Oracle Java / OpenJDK.

**Comment by pshipton** [comment]
Seems like an error in the spec. compareToIgnoreCase() describes "calling Character.toLowerCase(Character.toUpperCase(character)) on each character"

**Comment by sharon-wang** [comment]
Thanks for the details! Made it really easy to reproduce and verify that my fix works (opened https://github.com/eclipse/openj9/pull/11423).

I tested it with the original test program (single character strings) as well as with multi-character strings (e.g 
and got true for all cases:

```
"İİİ".equalsIgnoreCase("İİİ") = true
"İİİ".equalsIgnoreCase("ııı") = true
"İİİ".equalsIgnoreCase("Iıı") = true
"İİİ".equalsIgnoreCase("iıİ") = true

"ııı".equalsIgnoreCase("İİİ") = true
"ııı".equalsIgnoreCase("ııı") = true
"ııı".equalsIgnoreCase("Iıı") = true
"ııı".equalsIgnoreCase("iıİ") = true

"Iıı".equalsIgnoreCase("İİİ") = true
"Iıı".equalsIgnoreCase("ııı") = true
"Iıı".equalsIgnoreCase("Iıı") = true
"Iıı".equalsIgnoreCase("iıİ") = true

"iıİ".equalsIgnoreCase("İİİ") = true
"iıİ".equalsIgnoreCase("ııı") = true
"iıİ".equalsIgnoreCase("Iıı") = true
"iıİ".equalsIgnoreCase("iıİ") = true
```
