### ISSUE TITLE
OPENJ9_TAG doesn't match SHA being built

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1140]
ibmruntimes/openj9-openjdk-jdk8#36 and ibmruntimes/openj9-openjdk-jdk9#121 added OPENJ9_TAG, which is intended to be the TAG associated with the OpenJ9 SHA being built. However OPENJ9_TAG is the last tag available.

**Comment by JasonFengJ9** [comment]
Looking at getting the `tag` associated with the code `SHA` currently checked out.
Was thinking about the closest tag as per comment
https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/openj9/closed/OpenJ9.gmk#L31
