### ISSUE TITLE
jdknext failing to build, Java Preprocessor No configuration or non-existant configuration specified

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11446]
I suspect this is occurring because JDK16 was split and jdknext is building jdk17 now. We need to add the jdk17 preprocessor configuration, and I think a few other changes to support jdk17 build.

```
23:21:32  Building OpenJ9 Java Preprocessor
23:21:32  Building /home/jenkins/workspace/Build_JDKnext_ppc64le_linux_xl_OpenJDK/build/linux-ppc64le-server-release/support/j9tools/jpp.jar
23:21:40  Generating J9JCL sources
23:21:40  Reading preprocess instructions from xml...
23:21:40  No configuration or non-existant configuration specified (Configurations are case sensitive)
23:21:40  PREPROCESS WAS NOT SUCCESSFUL
```

**Comment by pshipton** [comment]
@JasonFengJ9 @tajila fyi

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/73fc9d848...dd80268
[8257450: Start of release updates for JDK 17](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/e45c45c462e1b169a54cb2838490da862a827407)
[Update OPENJDK_TAG to merged level jdk-17+0](https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/dd80268427517fd4a88c2d00757de5218ecb7d63)

**Comment by JasonFengJ9** [comment]
Will have a look.
