### ISSUE TITLE
Something is (or was) wrong with osx1011-x86-2

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11472]
I've disabled the machine. Otherwise all the testing tries to run on this machine and fails.
Example https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_mac_Release/47

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
Not sure if we can do anything about this type of problem? We need some kind of sanity check the machine is working, so it can be automatically disabled. Any time we have a bad machine much of the testing fails for that platform, and it's not easy to recover from that because (a) with the parallel test jobs one child might find a good machine and the other not, the failures don't show up until much later once testing on the good machine is done (b) the number of jobs that need to be manually restarted.

**Comment by jdekonin** [comment]
We could add a sanity check to jenkins but unless the test jobs are also running that job at the beginning of every job there is still going to be the possibility for failure between that scheduled sanity check job.

As for osx1011-x86-2, it appears to be fine now my guess is there was some sort of network blip that caused a temporary connection issue.  I've rebooted the system anyways, then enabled for use on jenkins.
