### ISSUE TITLE
Update Java 8 Windows build instructions for VS2013

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11477]
When switching to VS2013 for Windows Java 8 builds, the build instructions were never updated.
https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md

Building with VS2010 no longer works as the code isn't compatible, the instructions need to be updated.

**Comment by pshipton** [comment]
@jdekonin can you take a look at this please. I think the following parts need updating.
- update the list of requirements, modify to 2013, remove 2010 service pack 1 link, update freetype version?
- update to msdia100.dll section
- building freetype mentions VS2010, I see `--with-freetype-src` is used in the builds now. Probably the minimum freetype version needs to be updated, the builds are using 2.5.3
- update configure instructions wrt freetype

**Comment by harpreetbamrah** [comment]
Some input points from my side, I "build" win32 OpenJ9 on 64-bit Windows 10 recently:

- freetype-2.5.3 required and hence no need for "win32" folder in freetype\builds
- check for binary paths of clang and nasm and add in front of the PATH environment variable to override the older versions integrated in Cygwin
- regsvr32 commands for registering msdiaxxx.dll libraries to be run as administrator
- works with VS2013 and VS2010 as well, just a compiler error need to be rectified for VS2010 build as in #11519 

Hence, the configure script be like:
bash configure --disable-ccache \
               --with-boot-jdk=/cygdrive/c/<path_to_jdk8> \
               --with-freemarker-jar=/cygdrive/c/temp/freemarker.jar \
               --with-freetype-src=/cygdrive/c/temp/freetype  \
               --with-target-bits=32

**Comment by pshipton** [comment]
Note as per https://github.com/eclipse/openj9/issues/11519, using VS2010 is no longer supported.
