### ISSUE TITLE
OPENJ9_BRANCH is not as expected

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1149]
ibmruntimes/openj9-openjdk-jdk8#36 and ibmruntimes/openj9-openjdk-jdk9#121 added OPENJ9_BRANCH, which is intended to be the branch associated with the OpenJ9 SHA being built. The branch name is resolved to `HEAD` although this is not the branch used for the build.

@JasonFengJ9

**Comment by pshipton** [comment]
It occurs when get_source.sh is used with a -openj9-branch parameter, which probably has something to do with it.

**Comment by JasonFengJ9** [comment]
It appears `adoptopenjdk` latest nightly build (Feb. 12, 2018) hasn't picked up PRs ibmruntimes/openj9-openjdk-jdk8#36 and ibmruntimes/openj9-openjdk-jdk9#121.
