### ISSUE TITLE
Migrate Linter job from TravisCI

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#11505]
The only remaining job on TravisCI is the JIT linter job to detect incorrect uses of extensible classes.  Since OpenJ9 agreed to deprecate TravisCI, this job either needs to move to Azure (as OMR has done eclipse/omr#5659) or we need to find another home for it.  OMR has had success running it on Azure so it would seem to be the preferred choice for symmetry.

**Comment by pshipton** [comment]
@smlambert fyi

I believe github actions are preferred, which allows users to run the job from code in their forks.
