### ISSUE TITLE
JVM crashes using AdoptOpenJDK 15 OpenJ9 and Gradle 6.7.1

### ISSUE THREAD

**Issue by Jeeppler** [eclipse/openj9#11508]
I tested it in a Debian 10 container with Gradle 6.7.1 and AdoptOpenJDK 15 OpenJ9. It crashed immediately with a JVM dump.

~~~
./gradlew tasks
Unhandled exception
Type=Segmentation error vmState=0x00000000
…
~~~

Java Version:

~~~
java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Linux amd64-64-Bit Compressed References 20201022_81 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)
~~~

I did the same test with AdoptOpenJDK 15 Hotspot and everything worked out of the box in the same environment.

**Comment by JasonFengJ9** [comment]
There was a know issue for 0.23 release, could you try a nightly build [1]? (0.24 release is coming very soon)

[1] https://adoptopenjdk.net/nightly.html?variant=openjdk15&jvmVariant=openj9

**Comment by pshipton** [comment]
The milestone 1 builds for the next release are also available.

https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/tag/jdk-15.0.1+9_openj9-0.24.0-m1

**Comment by Jeeppler** [comment]
I tested it again with the Nightly build:

~~~
./java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9-202012162035)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-533459ac8, JRE 15 Linux amd64-64-Bit Compressed References 20201216_139 (JIT enabled, AOT enabled)
OpenJ9   - 533459ac8
OMR      - d255f376f
JCL      - 0e6bc58a45 based on jdk-15.0.1+9)
~~~

Gradle 6.7.1 works with the above mentioned OpenJ9 version.

**Comment by Jeeppler** [comment]
My build of and running the [SecHub](https://github.com/Daimler/sechub) application worked as well without problems.

**Comment by JasonFengJ9** [comment]
Good to hear that, thanks for verifying @Jeeppler
