### ISSUE TITLE
Solve  OMR issue 5717  for 0.25 release

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#11511]
This is just a placeholder to make sure [1] is addressed before openj9 0.25 release

[1] https://github.com/eclipse/omr/issues/5717

@aviansie-ben @rmnattas

**Comment by vij-singh** [comment]
@gita-omr How is this one going?

**Comment by gita-omr** [comment]
Hi @vij-singh. We are currently confirming that [1] and [2] will fix that problem. In any case, they are prerequisites so we are trying to finish the reviews and merge those two.

[1] https://github.com/eclipse/omr/pull/5652
[2] https://github.com/eclipse/openj9/pull/11305

**Comment by 0xdaryl** [comment]
@gita-omr : those two PRs you mentioned are now merged.  Is this still an issue, and if so should it move out to 0.26 ?

**Comment by gita-omr** [comment]
I would need to confirm with @zl-wang

**Comment by rmnattas** [comment]
There was a failure during acceptance testing introduced by the two merges above. Issue got fixed with eclipse/omr#5821, and no failures appeared in the latest acceptance test with this fix. This issue should be good to close.

**Comment by pshipton** [comment]
Note that none of these changes are delivered to the 0.25 branches.

**Comment by pshipton** [comment]
Considering this is related to 32-bit, and the 0.25 release is for Java 16 and doesn't contain any 32-bit platforms, I expect not delivering the changes to the 0.25 branches is fine.

**Comment by pshipton** [comment]
Closing as per https://github.com/eclipse/openj9/issues/11511#issuecomment-784233154
