### ISSUE TITLE
jdk17 sanity.functional testing cannot start, UnsatisfiedLinkError: com/ibm/oti/shared/Shared.isNonBootSharingEnabledImpl()Z

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11512]
All jdk17 sanity.functional (perhaps other suites, but didn't try them).
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/404/
```
06:07:37  + make genParallelList TEST=sanity.functional NUM_MACHINES=2 TEST_TIME=
06:07:37  JAVA_HOME is set to /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdkbinary/j2sdk-image
06:07:37  rm -f -r /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/../TKG/test_output_compilation; \
06:07:37  mkdir -p /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/../TKG/test_output_compilation; \
06:07:37  (ant -f ./scripts/build_tools.xml -DTEST_JDK_HOME=/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdkbinary/j2sdk-image -DTEST_ROOT=/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/.. 2>&1; echo $? ) | tee /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/../TKG/test_output_compilation/compilation.log; \
06:07:37  if [ -z $(tail -1 /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/../TKG/test_output_compilation/compilation.log | grep 0) ]; then perl scripts/moveDmp.pl --compileLogPath=/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/../TKG/test_output_compilation/compilation.log --testRoot=/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/..; false; else rm -f -r /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdk-tests/TKG/../TKG/test_output_compilation; fi
06:07:37  java.lang.UnsatisfiedLinkError: com/ibm/oti/shared/Shared.isNonBootSharingEnabledImpl()Z
06:07:37  	at openj9.sharedclasses/com.ibm.oti.shared.Shared.<clinit>(Shared.java:46)
06:07:37  	at openj9.sharedclasses/com.ibm.oti.shared.provider.SharedClassProviderImpl.isSharedClassEnabled(SharedClassProviderImpl.java:55)
06:07:37  	at openj9.sharedclasses/com.ibm.oti.shared.provider.SharedClassProviderImpl.initializeProvider(SharedClassProviderImpl.java:63)
06:07:37  	at java.base/java.net.URLClassLoader.initializeSharedClassesSupport(URLClassLoader.java:194)
06:07:37  	at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:232)
06:07:37  	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:279)
06:07:37  	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
06:07:37  2
06:07:37  /bin/sh[4]: test: 0403-004 Specify a parameter with this command.
06:07:37  AUTO_DETECT is set to true
06:07:37  /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_ppc64_aix_xl_OpenJDK/openjdkbinary/j2sdk-image/bin/java -cp ./bin/TestKitGen.jar org.openj9.envInfo.EnvDetector
06:07:37  Error: Could not find or load main class org.openj9.envInfo.EnvDetector
06:07:37  Caused by: java.lang.ClassNotFoundException: org.openj9.envInfo.EnvDetector
```

**Comment by pshipton** [comment]
@tajila fyi
Perhaps something has changed in jdk17 related to loading natives?

**Comment by pshipton** [comment]
JCL changes from previous build where this didn't occur.
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/4bdc9ef...e21ee05

**Comment by tajila** [comment]
@JasonFengJ9 can you please take a look at this

**Comment by JasonFengJ9** [comment]
@tajila sure, will look into this.

**Comment by pshipton** [comment]
@JasonFengJ9 fyi https://github.com/eclipse/openj9/issues/11515, if you are building you need to use an older JCL level than the latest until this is fixed.

**Comment by JasonFengJ9** [comment]
Recent OpenJDK update has caused `openj9.sharedclasses/com.ibm.oti.shared.Shared` classloader changed from `systemClassLoader` to `jdk.internal.loader.ClassLoaders$AppClassLoader`, however `com/ibm/oti/shared/Shared.isNonBootSharingEnabledImpl()Z` is implemented by `runtime/jcl/common/shared.c` (`libjclse29`) and is available as the native library associated with `systemClassLoader`, hence following native method binding missed it https://github.com/eclipse/openj9/blob/96ff2fb85b391bcdb041c1b7306ac4cfccd8e0a5/runtime/vm/bindnatv.cpp#L998-L1004
It appears the native libraries of `systemClassLoader` should be attempted for native method binding first.

**Comment by pshipton** [comment]
openj9.sharedclasses is supposed to be a BOOT_MODULE and loaded by the boot class loader.
https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/closed/custom/common/Modules.gmk#L23

**Comment by JasonFengJ9** [comment]
```
06:07:37  	at openj9.sharedclasses/com.ibm.oti.shared.Shared.<clinit>(Shared.java:46)
06:07:37  	at openj9.sharedclasses/com.ibm.oti.shared.provider.SharedClassProviderImpl.isSharedClassEnabled(SharedClassProviderImpl.java:55)
06:07:37  	at openj9.sharedclasses/com.ibm.oti.shared.provider.SharedClassProviderImpl.initializeProvider(SharedClassProviderImpl.java:63)
06:07:37  	at java.base/java.net.URLClassLoader.initializeSharedClassesSupport(URLClassLoader.java:194)
```
The class in question was loaded via `ServiceLoader` which seems using different classloader after this OpenJDK update.

**Comment by pshipton** [comment]
The change was `8258411: Move module set configuration from Modules.gmk to conf dir`.
The OpenJ9 boot and platform modules need to be added to the lists in `make/conf/module-loader-map.conf `

**Comment by pshipton** [comment]
Seems the hook `$(eval $(call IncludeCustomExtension, common/Modules.gmk))` is now called too early, before the lists are defined. Changing the order should fix it.

https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9-staging/make/common/Modules.gmk#L30-L35

**Comment by JasonFengJ9** [comment]
> The OpenJ9 boot and platform modules need to be added to the lists in make/conf/module-loader-map.conf

Yeah, adding `openj9.sharedclasses` to `make/conf/module-loader-map.conf` manually fixed the issue.

**Comment by JasonFengJ9** [comment]
> Seems the hook $(eval $(call IncludeCustomExtension, common/Modules.gmk)) is now called too early, before the lists are defined. Changing the order should fix it.

Does this sound an OpenJDK bug?

**Comment by pshipton** [comment]
> Does this sound an OpenJDK bug?

Yes. Possibly the hook was originally added at our request. We should confirm changing the order fixes evertyhing, make the change, and then request the change be contributed to OpenJDK.
