### ISSUE TITLE
Tests hanging on win2012-x86-4, pls reboot

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11525]
We just had this problem with 5, which was rebooted. It's time to reboot the rest of them.

@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
The sanitize job should reboot the windows machines.

**Comment by pshipton** [comment]
It was running something like that, and couldn't seem to re-launch. I tried to disconnect it, but now it's in relaunching state.

**Comment by pshipton** [comment]
Maybe it's because I tried to take it offline. I brought it back online and it's running cleanup. Perhaps it will run sanitize afterwards.

**Comment by pshipton** [comment]
I guess sanitize doesn't run until later. Perhaps https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.functional_x86-64_windows_Release/12/console is hanging on it now, time will tell.

**Comment by pshipton** [comment]
Looks hung to me. Disabled the machine until the scheduled sanitize job can run on it.

**Comment by pshipton** [comment]
Brought it back online after the sanitize started, but sanitize didn't run on the machine. Seems this is intentional. I can't leave it enabled other jobs hang on it.
`20:50:03  Offline slaves: [ub18-x86-1:Disconnected by joe_dekoning@ca.ibm.com : On loan to OMR project., win2012-x86-4:Disconnected by peter_shipton@ca.ibm.com`

**Comment by AdamBrousseau** [comment]
I've issues the shutdown command that the sanitize job does. The CI isn't loading for me to verify it reconnected. Give it a try.

**Comment by AdamBrousseau** [comment]
Rebooted it from the cloud UI. Connected again running jobs.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Personal_testList_1/3/
