### ISSUE TITLE
AIX extended.functional tests producing large j9core.dmp

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11537]
The following test seemingly Passed, but produced a 18Gb j9core.dmp
https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_sanity.functional_ppc64_aix/85/consoleFull
```
Test_openjdk11_j9_extended.functional_ppc64_aix/openjdk-tests/TKG/test_output_16086997302346/cmdLineTester_classesdbgddrext_1
-rw-r--r-- 1 jenkins staff 18566445080 Dec 23 00:48 j9core.dmp
```

Also, not just this test, several producing large j9core.dmp, see: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1772#issuecomment-750040757

**Comment by andrew-m-leonard** [comment]
@pshipton the common theme from the tests with large cores seems to be DDR ?

**Comment by pshipton** [comment]
Correct, DDR testing produces a core file in order to run the DDR tests, as these need a core file to process. The tests should delete the core files afterwards. We can modify the tests to specify a smaller -Xmx value than the default (25% of available RAM), which will produce smaller core files.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by andrew-m-leonard** [comment]
@pshipton reducing core size would be good please, the AIX boxes are trying to produce 10-18Gb core files per test, and some of the Adopt AIX machines only have about 20Gb partitions
