### ISSUE TITLE
14.0.2.12-openj9 fails with module not found: jdk.internal.vm.compiler

### ISSUE THREAD

**Issue by koppor** [eclipse/openj9#11555]
I am trying to use 14.0.2.12-openj9 within IntelliJ Ultimate. I get

```
C:\git-repositories\jabref\jabref\src\main\java\module-info.java:68: error: module not found: jdk.internal.vm.compiler
    requires jdk.internal.vm.compiler;
                            ^
```

I think, this is https://github.com/AdoptOpenJDK/openjdk-build/issues/2047, isn't it?

https://github.com/AdoptOpenJDK/openjdk-build/issues/2047#issuecomment-688309375:

>  Results are in. A server-only build of 15 includes jdk.internal.vm.compiler, a mixed client/server build does not.

**Comment by pshipton** [comment]
`jdk.internal.vm.compiler` is specific to Hotspot and this module is not included in OpenJ9 builds.

**Comment by koppor** [comment]
Thank you for the information. We need that module, because of [citeproc-java](https://michel-kraemer.github.io/citeproc-java/), which [depends on the GraalVM compiler](https://github.com/michel-kraemer/citeproc-java/blob/5d119ecde0e21b53e217be33730fa3dd8901c99c/citeproc-java/build.gradle#L54), because the Java implementation is "just" a wrapper around the existing JavaScript implementation of that library. As a result, this blocks our tool [JabRef](https://www.jabref.org/) to be compiled using OpenJ9.
