### ISSUE TITLE
ValueTypes: Add jit runtime helper to resolve field refs for flatteneable fields

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11570]
The current jithelpers for flattenable fields require that the fieldrefs for those fields are already resolved. This makes it difficult for the JIT to compile unresolved paths, see https://github.com/eclipse/openj9/pull/11022/#issuecomment-742760048. 

To solve this we need to introduce a runtime JIT helper that can be compiled in to unresolved paths which will resolve the flattenable field refs.

This helper will first check if the fieldref is resolved, if not it will attempt to resolve it. Initially this can be implemented using the SLOW_PATH_ONLY_HELPER_NO_RETURN_VALUE template.

Params:
J9VMThread currentThread: implicit param
J9Method method: method in which the resolution must take place
U_32 cpIndex: ram constant pool index for the field ref
U_32 resolveType: one of J9TR_FLAT_RESOLVE_WITHFIELD / J9TR_FLAT_RESOLVE_GETFIELD / J9TR_FLAT_RESOLVE_PUTFIELD

For U_32 parameters on 64-bit platforms, the high-order 32 bits are unused.

jitResolveFlattenableField(...)

To start we should first add the stubs to unblock the JIT progress (see https://github.com/eclipse/openj9/pull/9786 and https://github.com/eclipse/omr/pull/5278 for an example). In the second phase the actual implementation can be added.

**Comment by gacholio** [comment]
Not sure what the type flags are for - are you planning a generic single helper? That's not what's been stubbed so far.

**Comment by gacholio** [comment]
I was confusing the stubbed access helpers with resolve helpers. Since the resolve helpers will not be called from compiled code (they will presumably only be called from the picbuilder), it makes sense to have a single parameterized helper.

**Comment by gacholio** [comment]
This is a resolve helper, so I will make it slow only, there's no real benefit to making it dual.
