### ISSUE TITLE
Anon class name shows up with zeroes when SCC is enabled

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11583]
When creating an anonClass, the name shows up with this format `AnonClass/0x0000000000000000` when SCC is enabled, but without it it shows up as `AnonClass/0x0000000038479300`

```
/xa64150/jdk/bin/java -Xshareclasses:none  --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -cp ../issue.jar:../asm-6.2.jar Scratch3
Class name AnonClass/0x00000000804770d0
```

```
./xa64150/jdk/bin/java --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -cp ../issue.jar:../asm-6.2.jar Scratch3
Class name AnonClass/0x0000000000000000
```

**Comment by tajila** [comment]
@hangshao0 is this expected?

**Comment by tajila** [comment]
[issue.jar.zip](https://github.com/eclipse/openj9/files/5776939/issue.jar.zip)

The jar is attached here

**Comment by hangshao0** [comment]
>  is this expected?

Yes.

**Comment by tajila** [comment]
Thanks for confirming
