### ISSUE TITLE
Travis PR builds broken

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#116]
Travis pull request builds are broken. They time out cloning `openj9-openjdk-jdk9`

```Cloning into 'openj9-openjdk-jdk9'...
remote: Counting objects: 565618, done.
remote: Compressing objects: 100% (13/13), done.
Receiving objects:  98% (558063/565618), 776.86 MiB | 160.00 KiB/s   
The job exceeded the maximum time limit for jobs, and has been terminated.
```
https://travis-ci.org/eclipse/openj9/builds/278682619

~~Builds on branches still seem ok~~ I have seen the issue strike on branch builds but much less often than on PR builds

**Comment by AdamBrousseau** [comment]
Can this be closed?

**Comment by DanHeidinga** [comment]
I think so.  There has been other travis build flakiness but that's been related to source forge downloads of free marker.
