### ISSUE TITLE
Value type operations implemented in LowerTrees need to be moved somewhere else

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/openj9#11609]
A few value type operations are implemented by recognizing certain Trees as high-level operations and breaking them down into a more specific sequence of trees in LowerTrees. Unfortunately, LowerTrees does a bunch of other things that don't interact well with how trees get generated for value type operations. One example is that trees sometimes have to be inserted before the current point in the LowerTrees walk, so any trees that need lowering but get inserted before the current point don't actually get lowered (because LowerTrees only does a single linear pass).

The most straight forward solution is to move value type operation lowering to a separate pass (e.g. as part of a new optimization) so that no interference can happen.

The following list describes what work is currently done in LowerTrees:

- ACMP Lowering
  - correctness: non-helper symbol is replaced with helper symbol
  - optimization: fast-paths added around call
    - if both operands are equal then true
    - else if either operand is reference type then false
    - else do helper call
  - optimization: propagate fast-path result if possible
    - i.e. result of acmp feeds into an ifcmp, so fast-paths can jump directly to branches of ifcmp
- ArrayStoreCHK
  - correctness: create "augmented" ArrayStoreCHK that also does a NULLCHK

A few considerations:

- Originally, part of the reason for doing this in LowerTrees is to hide from GRA some of the complex control flow that gets generated
- Although these operations could be implemented differently (e.g. directly in the code gens), implementing them in IL saves from having to reproduce the same functionality in each code gen (which should hopefully save on implementation time)

**Comment by Leonardo2718** [comment]
FYI @vijaysun-omr @0xdaryl @hzongaro @a7ehuo

**Comment by a7ehuo** [comment]
Will moving the acmp lowering to optimization also address the performance regression related to the acmp fast path?

**Comment by Leonardo2718** [comment]
> Will moving the acmp lowering to optimization also address the performance regression related to the acmp fast path?

Unfortunately, no. Further work is going to be needed in order to eliminate the performance regression.

**Comment by fjeremic** [comment]
I suggest we move such a pass into its own file. There are similar passes like this, for example the Recognized Call Transformer which is a lowering operation but is isolated and concentrated in its own file for clarity since all the operations it performs are similar. This avoids lower trees from becoming a kitchen sink per say.
