### ISSUE TITLE
JDK16: isRecord test failures

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11603]
09:51:01  --- testDirectSubClass isFinal=false, isAbstract=false, extendsJLR=false, withRecordAttr=true, expectIsRecord=false ---
09:51:01  test IsRecordTest.testDirectSubClass(false, false, false, true, false): failure
09:51:01  java.lang.ClassFormatError: JVMCFRE172 Record is implicitly final; class=C, offset=70
09:51:01  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
09:51:01  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489)
veMethodAccessorImpl.invoke0(Native Method)
09:51:01  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
...
09:51:01  --- testDirectSubClass isFinal=false, isAbstract=false, extendsJLR=true, withRecordAttr=true, expectIsRecord=false ---
09:51:01  test IsRecordTest.testDirectSubClass(false, false, true, true, false): failure
09:51:01  java.lang.ClassFormatError: JVMCFRE172 Record is implicitly final; class=C, offset=70
09:51:01  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
09:51:01  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489)
09:51:01  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:450)
09:51:01  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:402)
09:51:01  	at jdk.test.lib.ByteCodeLoader.findClass(ByteCodeLoader.java:103)
09:51:01  	at jdk.test.lib.ByteCodeLoader.loadClass(ByteCodeLoader.java:90)
09:51:01  	at jdk.test.lib.ByteCodeLoader.load(ByteCodeLoader.java:116)

09:51:01  
09:51:01  --- testDirectSubClass isFinal=false, isAbstract=true, extendsJLR=false, withRecordAttr=true, expectIsRecord=false ---
09:51:01  test IsRecordTest.testDirectSubClass(false, true, false, true, false): failure
09:51:01  java.lang.ClassFormatError: JVMCFRE168 Record classes cannot be abstract; class=C, offset=70
09:51:01  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
09:51:01  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489)
09:51:01  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:450)
09:51:01  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:402)
09:51:01  	at jdk.test.lib.ByteCodeLoader.findClass(ByteCodeLoader.java:103)
09:51:01  	at jdk.test.lib.ByteCodeLoader.loadClass(ByteCodeLoader.java:90)
09:51:01  	at jdk.test.lib.ByteCodeLoader.load(ByteCodeLoader.java:116)

09:51:01  
09:51:01  --- testDirectSubClass isFinal=false, isAbstract=true, extendsJLR=true, withRecordAttr=true, expectIsRecord=false ---
09:51:01  test IsRecordTest.testDirectSubClass(false, true, true, true, false): failure
09:51:01  java.lang.ClassFormatError: JVMCFRE168 Record classes cannot be abstract; class=C, offset=70
09:51:01  	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
09:51:01  	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:489)
09:51:01  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:450)
09:51:01  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:402)
09:51:01  	at jdk.test.lib.ByteCodeLoader.findClass(ByteCodeLoader.java:103)

09:51:01  
09:51:01  --- testDirectSubClass isFinal=true, isAbstract=false, extendsJLR=false, withRecordAttr=true, expectIsRecord=false ---
09:51:01  cls=class C, Record::isAssignable=false, isRecord=true
09:51:01  test IsRecordTest.testDirectSubClass(true, false, false, true, false): failure
09:51:01  java.lang.AssertionError: expected [false] but found [true]
09:51:01  	at org.testng.Assert.fail(Assert.java:94)
09:51:01  	at org.testng.Assert.failNotEquals(Assert.java:496)
09:51:01  	at org.testng.Assert.assertEquals(Assert.java:125)
09:51:01  	at org.testng.Assert.assertEquals(Assert.java:288)
09:51:01  	at org.testng.Assert.assertEquals(Assert.java:298)
09:51:01  	at IsRecordTest.testDirectSubClass(IsRecordTest.java:93)

and more...

See https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_s390x_linux_Nightly/1/

**Comment by tajila** [comment]
@ChengJin01 can you please take a look at this

**Comment by tajila** [comment]
The SealedClassesReflectionTest failures are caused by https://github.com/eclipse/openj9/issues/10977

**Comment by ChengJin01** [comment]
Will check to see what happened to the failing tests.

**Comment by JasonFengJ9** [comment]
This is also observed at internal tests.
```
03:14:21  --- testDirectSubClass isFinal=false, isAbstract=false, extendsJLR=false, withRecordAttr=true, expectIsRecord=false ---
03:14:21  test IsRecordTest.testDirectSubClass(false, false, false, true, false): failure
03:14:21  java.lang.ClassFormatError: JVMCFRE172 Record is implicitly final; class=C, offset=70
03:14:21  	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:402)
03:14:21  	at jdk.test.lib.ByteCodeLoader.findClass(ByteCodeLoader.java:103)
03:14:21  	at jdk.test.lib.ByteCodeLoader.loadClass(ByteCodeLoader.java:90)
03:14:21  	at jdk.test.lib.ByteCodeLoader.load(ByteCodeLoader.java:116)
03:14:21  	at IsRecordTest.testDirectSubClass(IsRecordTest.java:90)
03:14:21  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:14:21  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:14:21  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:14:21  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:14:21  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
03:14:21  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
03:14:21  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
03:14:21  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
03:14:21  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
03:14:21  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
03:14:21  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
03:14:21  	at org.testng.TestRunner.run(TestRunner.java:623)
03:14:21  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
03:14:21  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
03:14:21  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
03:14:21  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
03:14:21  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
03:14:21  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
03:14:21  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
03:14:21  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
03:14:21  	at org.testng.TestNG.run(TestNG.java:1018)
03:14:21  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
03:14:21  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
03:14:21  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03:14:21  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03:14:21  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03:14:21  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
03:14:21  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
03:14:21  	at java.base/java.lang.Thread.run(Thread.java:853)
```

**Comment by ChengJin01** [comment]
The issue is under investigation but it seems like the `ClassFormatError` exception shouldn't be captured during the static verification. Need to double-check the failing test case against our code to confirm this.

**Comment by ChengJin01** [comment]
(1) Looking at the test case at `https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/openj9/test/jdk/java/lang/reflect/records/IsRecordTest.java`
```
    @Test(dataProvider = "scenarios")
    public void testDirectSubClass(boolean isFinal,
                                   boolean isAbstract,
                                   boolean extendsJLR,
                                   boolean withRecordAttr,
                                   boolean expectIsRecord) throws Exception {
        out.println("\n--- testDirectSubClass isFinal=%s, isAbstract=%s, extendsJLR=%s, withRecordAttr=%s, expectIsRecord=%s ---"
                .formatted(isFinal, isAbstract, extendsJLR, withRecordAttr, expectIsRecord));

        List<RecordComponentEntry> rc = null;
        if (withRecordAttr)
            rc = List.of(new RecordComponentEntry("x", "I"));
        String superName = extendsJLR ? "java/lang/Record" : "java/lang/Object";
        var classBytes = generateClassBytes("C", isFinal, isAbstract, superName, rc);
        Class<?> cls = ByteCodeLoader.load("C", classBytes);  <----- the ClassFormatError was thrown out when loading classes
        out.println("cls=%s, Record::isAssignable=%s, isRecord=%s"
                .formatted(cls, Record.class.isAssignableFrom(cls), cls.isRecord()));
        assertEquals(cls.isRecord(), expectIsRecord); <---- this test case is supposed to check the value of isRecord() against the expectIsRecord
```
which means the `ClassFormatError` exception should be ignored during the static verification and the check on record classes to isRecord() should be delayed to the java level. So the following code in checkAttributes() needs to be removed at /runtime/bcutil/cfreader.c
```
		case CFR_ATTRIBUTE_Record:
			/* record classes cannot be abstract */
			if (J9_ARE_ANY_BITS_SET(classfile->accessFlags, CFR_ACC_ABSTRACT)) {
				errorCode = J9NLS_CFR_RECORD_CLASS_CANNOT_BE_ABSTRACT__ID;
				goto _errorFound;
			}
			/* record classes must be final */
			if (J9_ARE_NO_BITS_SET(classfile->accessFlags, CFR_ACC_FINAL)) {
				errorCode = J9NLS_CFR_RECORD_CLASS_MUST_BE_FINAL__ID;
				goto _errorFound;
			}
```

2) Looking at the data source in the test case:
```
    @DataProvider(name = "scenarios")
    public Object[][] scenarios() {
        return new Object[][] {
             // isFinal, isAbstract, extendJLR, withRecAttr, expectIsRecord
             ...
             {     true,     false,     true,     true,      true     },
             ...
```
against the Spec at https://openjdk.java.net/jeps/395
```
Rules for record classes
There are numerous restrictions on the declaration of a record class in comparison to a normal class:

 A record class declaration does not have an extends clause. 
The superclass of a record class is always java.lang.Record,  <----------
similar to how the superclass of an enum class is always java.lang.Enum. 
Even though a normal class can explicitly extend its implicit superclass Object, 
a record cannot explicitly extend any class, even its implicit superclass Record.
```
which means a record class must be a subclass of `java.lang.Record` in addition to be final, abstract and the record attribute in the class file.

The Spec at https://openjdk.java.net/jeps/395  says  isRecord() is called to determine whether a class is a record class or not
```
Reflection API
    boolean isRecord() — Returns true if the given class was declared as a record.
```
which means it need to check the superclass of the specified class.

It seems isRecord() in our code at `/jcl/src/java.base/share/classes/java/lang/Class.java`is entirely implemented in the native code
```
	/**
	 * Returns true if the class instance is a record.
	 * 
	 * @return true for a record class, false otherwise
	 */
	public native boolean isRecord();

/runtime/vm/BytecodeInterpreter.hpp
	/* java.lang.Class: public native boolean isRecord(); */
	VMINLINE VM_BytecodeAction
	inlClassIsRecord(REGISTER_ARGS_LIST)
	{
		J9Class *receiverClazz = J9VM_J9CLASS_FROM_HEAPCLASS(_currentThread, *(j9object_t*)_sp);
--> returnSingleFromINL(REGISTER_ARGS, (J9ROMCLASS_IS_RECORD(receiverClazz->romClass) ? 1 : 0), 1);
		return EXECUTE_BYTECODE;
	}

/runtime/vm/FastJNI_java_lang_Class.cpp
/* java.lang.Class public native boolean isRecord(); */
jboolean JNICALL
Fast_java_lang_Class_isRecord(J9VMThread *currentThread, j9object_t receiverObject)
{
	J9Class *receiverClazz = J9VM_J9CLASS_FROM_HEAPCLASS(currentThread, receiverObject);
	return J9ROMCLASS_IS_RECORD(receiverClazz->romClass) ? JNI_TRUE : JNI_FALSE;
}
```
which calls a macro J9ROMCLASS_IS_RECORD at `/runtime/oti/j9modifiers_api.h`
```
#define J9ROMCLASS_IS_RECORD(romClass)			_J9ROMCLASS_J9MODIFIER_IS_SET((romClass), J9AccRecord)
```
the macro needs to be updated to check the final & abstract bit in the ROM class.

Given that `J9ROMCLASS_IS_RECORD` is also called in multiple places in the native code e.g.
```
/runtime/jcl/common/reflecthelp.c
createField(struct J9VMThread *vmThread, jfieldID fieldID)
{
...
	if (J9_ARE_ALL_BITS_SET(j9FieldID->field->modifiers, J9AccFinal)) {
		if (J9_ARE_ALL_BITS_SET(j9FieldID->field->modifiers, J9AccStatic)
			|| J9ROMCLASS_IS_RECORD(j9FieldID->declaringClass->romClass) <-----
			|| J9ROMCLASS_IS_HIDDEN(j9FieldID->declaringClass->romClass)
		) {
			J9VMJAVALANGREFLECTFIELD_SET_TRUSTEDFINAL(vmThread, fieldObject, JNI_TRUE);
		}
	}
```
all these code with J9ROMCLASS_IS_RECORD() needs to be modified to ensure the superclass of the specified class is `java.lang.Record`.    Need to figure out how to get all these changes working in this way.

**Comment by ChengJin01** [comment]
With the fixed I created to add more checks to `J9ROMCLASS_IS_RECORD` at https://github.com/ChengJin01/openj9/commit/6f782ca56c0f0c461d8fd50ce550950564d30a9e,  the failing test case above passed as expected [jtreg_test_isRecordTest_log_passed.txt](https://github.com/eclipse/openj9/files/5821776/jtreg_test_isRecordTest_log_passed.txt)
```
$ export JDK_CUSTOM_TARGET=test/jdk/java/lang/reflect/records/IsRecordTest.java
$ make _jdk_custom
...
===============================================
Running test jdk_custom_0 ...
===============================================
...
jdk_custom_0_PASSED
...
TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
PASSED test targets:
	jdk_custom_0

TOTAL: 2   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 1
ALL TESTS PASSED
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```
Will launch personal builds to ensure no break is introduced in the existing tests.
