### ISSUE TITLE
TR_J9VMBase::getClassSignature returns NULL terminated string ?

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#11608]
While reviewing a PR I happened to discover that the `TR_J9VMBase::getClassSignature` function produces a `\0`-terminated string rather than passing back the length when converted from UTF-16.

https://github.com/eclipse/openj9/blob/644d86edb54c8f83e5331203a962e96788449c8e/runtime/compiler/env/VMJ9.cpp#L2528

This doesn't seem correct, as at least theoretically the class name converted from UTF-16 could have a zero-byte in it which means that a function like `strlen()` shouldn't be called on it and expect a reliable answer.

Curiously, there is a deprecated version of that function which does what I expect it to do (passes back the length).  It was deprecated prior to open sourcing:

https://github.com/eclipse/openj9/blob/644d86edb54c8f83e5331203a962e96788449c8e/runtime/compiler/env/VMJ9.cpp#L2501

Am I wrong?  If not, we should probably sweep through the code and make sure this function is used correctly.  And check that other signature-generating functions are doing the right thing too.

**Comment by fjeremic** [comment]
An alternative to the proposal is to just do what the rest of the JVM (VM + GC) does and use `J9UTF8` to pass along UTF-16 strings. The structure already encodes both the length and data which can be accessed by the macros used throughout the VM:
https://github.com/eclipse/openj9/blob/644d86edb54c8f83e5331203a962e96788449c8e/runtime/oti/j9.h#L165-L173

**Comment by DanHeidinga** [comment]
`getClassSignature` gets the UTF8 class name from the J9ROMClass.  The UTF8 encoding ensures that the only way to get a null byte is to have `\0` in the name, which isn't a valid Java class name.

**Comment by fjeremic** [comment]
There is also a JVMTI function `jvmtiGetClassSignature`:
https://github.com/eclipse/openj9/blob/644d86edb54c8f83e5331203a962e96788449c8e/runtime/jvmti/jvmtiClass.c#L299-L420

But it seems it can throw JVMTI specific error codes. Wonder if there is anything else in the VM somewhere which we could just call rather than rolling out a JIT specific one.

**Comment by 0xdaryl** [comment]
@DanHeidinga : ah, ok.  Thanks for clarifying that.

@fjeremic : That's a possibility if it can be done efficiently (and nice for consistency with the rest of the VM).  Some of these APIs extend into OMR, however, which could theoretically be used by other language environments that don't encode names as UTF-16.
