### ISSUE TITLE
win2012-x86-5 hang, pls reboot

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11615]
Causing havoc in the weekend builds. 

For example, see https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly_testList_1/38/console

Other examples in the builds over the weekend.

Until I disconnected the machine, the output was hung at:
```
Running on win2012-x86-5 in F:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly_testList_1
[Pipeline] {
[Pipeline] checkout
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Rebooted and connected to jenkins.
