### ISSUE TITLE
DDR overrides don't match VM

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11639]
On a number of platforms, BOOLEAN is defined as 32-bits.
https://github.com/eclipse/omr/blob/master/include_core/omrcomp.h#L68

The following fields are overridden as UDATA, which is not a match on those platforms.
https://github.com/eclipse/openj9/blob/master/runtime/ddr/overrides-vm#L87-L88

On Windows jdk16, cmdLineTester_modularityddrtests is failing. However it should be failing on all platforms. The test expects java.base packages to be exported to ALL-UNNAMED, but this test is currently invalid for jdk16+ due to JEP 396 "Strongly Encapsulate JDK Internals by Default" changing the defaults. It's not failing on other platforms due to reading a UDATA value as the BOOLEAN, which overlaps the next field in the structure and reads a non-zero value.

From xlinux:
```
J9Package at 0x7f9934098b10 {
  Fields for J9Package:
	0x0: struct J9UTF8* packageName = !j9utf8 0x00007F9934176550
	0x8: UDATA exportToAll = 0x0000000000000000 (0)
	0xc: UDATA exportToAllUnnamed = 0x340987F800000000 (3749677663984287744)
	0x10: struct J9Module* module = !j9module 0x00007F99340987F8
	0x18: struct J9HashTable* exportsHashTable = !j9hashtable 0x00007F99341765B0
	0x20: struct J9ClassLoader* classLoader = !j9classloader 0x00007F99340976B8
}
```

Note the field offsets, which show 4 bytes for exportToAll and exportToAllUnnamed. The value of exportToAllUnnamed includes the lower 4 bytes of the next field.

https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_extended.functional_x86-64_windows_Nightly_testList_0/1/

I'm thinking to resolve this particular problem by declaring the fields as U_32 instead of BOOLEAN, and removing the DDR overrides. Also fixing the test for jdk16.

**Comment by pshipton** [comment]
@keithc-ca thoughts?

**Comment by keithc-ca** [comment]
I have always thought `typedef UDATA BOOLEAN;` was a waste of space.
Perhaps it should be `typedef U_32 BOOLEAN;`, or even narrower.

Ideally, we wouldn't need overrides for DDR, but not all compilers are created equal.

I'll give some thought about whether we can validate all overrides to make sure there aren't more problems like this.

**Comment by keithc-ca** [comment]
Note that the new overrides were derived from https://github.com/eclipse/openj9/blob/master/runtime/ddr/vmddrstructs.properties#L165-L166 (which are also wrong).

**Comment by gacholio** [comment]
We should eliminate BOOLEAN entirely. This would be made even simpler if we moved everything to C++...

**Comment by keithc-ca** [comment]
Is there more work to be done here, or can this be closed?

**Comment by pshipton** [comment]
The immediate problem was resolved. We could look to see if there are any other overrides of BOOLEAN values which may cause problems.

**Comment by keithc-ca** [comment]
I had a look at the remaining DDR type overrides. The only one that ought to have been different is
```
typeoverride.CacheletWrapper.dataStart=I_32
```
which should have been
```
typeoverride.CacheletWrapper.dataStart=J9SRP(U_8)
```
Unfortunately, this cannot be fixed without breaking `CacheletWrapperHelper` with respect to reading older core files.

There's nothing further to do for this issue: closing.
