### ISSUE TITLE
Default shared cache size is too small

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1164]
The default shared cache size is 16MB. I believe this dates back to a Linux default maximum setting for creating shared memory using sysV (/proc/sys/kernel/shmmax), requiring a Linux configuration change before using a bigger cache size (although it seems 32MB is the default today). As the shared cache uses mmap by default, the sysV restrictions do not apply (unless the nonpersistent option is used).

The 16MB size is typically not big enough for most applications. It is a common user error not to increase the default shared cache size, leading to smaller benefits from the shared cache than could be expected, due to the reduced amount of shared classes and AOT.

The open question is what the default shared cache size should be. Likely 50-100MB. It is also possible to set a large size such as 300MB, but set a lower limit on the amount of cache which can be used. This restricts the disk space the shared cache can consume, and stops it from growing slowly over time for no benefit, which can happen with some applications. The user then has the option to increase the amount of shared cache which can be used without having to destroy and recreate the cache.

@mpirvu fyi

**Comment by mpirvu** [comment]
I totally agree that we need a larger default.
Since on zOS the cache is implemented using shared memory, does the 32MB restriction apply? If so should we limit the default size on zOS to 32MB and have a larger size on other platforms?

We may also want to set different sizes for 32-bit and 64-bit platforms because on 32-bit the JVM may run into address space issues. 
Maybe a 32MB cache size on 32-bit and 64MB soft size on 64-bit (the default in Liberty 60MB) with a max size of 256MB.

**Comment by hangshao0** [comment]
Here are some statistics from the coreAnalytics tool: 54.1% users are using -Xscmx to set the shared cache size.
Among all the users using -Xscmx:
26.9% use 50m
33.9% use 60m
25.8% use 90m

**Comment by mpirvu** [comment]
Interesting stats. I wonder though if the stats are biased towards WAS/liberty because 50MB is the old SCC size in WebSphere, 60MB is the size in Liberty and 90MB is the size in WebSphere managed profile.
Nevertheless with the proposed change we would be helping the other 46% users that don't set a size.

**Comment by DanHeidinga** [comment]
We should look at making this change for JDK9+.  

The default SCC should use a different name from when a user explicitly enables it so that the default size won't conflict with any user specified sizes.

@hangshao0 Can you take a look at this?

**Comment by pshipton** [comment]
> The default SCC should use a different name from when a user explicitly enables it so that the default size won't conflict with any user specified sizes.

I think this is related to enabling a shared cache by default, for which we haven't created an issue yet but will shortly, and doesn't really apply to this Issue for changing the default size.

**Comment by DanHeidinga** [comment]
Thanks Peter.  In my eagerness, I mixed the two up :)

**Comment by hangshao0** [comment]
I plan to set default size to 32MB for non-persistent cache and 64MB for persistent cache.

**Comment by pshipton** [comment]
> I plan to set default size to 32MB for non-persistent cache and 64MB for persistent cache.

For the record, please explain the reasoning for using these values.

**Comment by mpirvu** [comment]
Are the new limits (32/64MB) going to be soft-limits or hard ones?

**Comment by hangshao0** [comment]
> Are the new limits (32/64MB) going to be soft-limits or hard ones?

Hard ones.

**Comment by pshipton** [comment]
- can we check the default shmmax and use a bigger cache size if its supported? Or just try a bigger limit and fall back to the smaller limit if the bigger limit fails.

- is it feasible to set a larger hard limit such as 300MB and set the soft limit to 64MB?

**Comment by pshipton** [comment]
I don't think there is any drawback to creating a cache which has a large hard limit. It doesn't actually take up the full amount on disk, only the amount which is used. Similarly for the non-persistent cache, it uses virtual address space but not physical memory.

**Comment by pshipton** [comment]
> But I guess we need to remove J9NLS_SHRC_SHRINIT_SHARED_MEMORY_SIZE_CHANGED

I'd expect the fallback to occur in lower level code rather than using adjustCacheSizes()

**Comment by hangshao0** [comment]
I am fine with creating a large cache and set a soft limit by default. How about this:
Set the default size to 300MB and set default soft limit to 64MB. In the case of shmmax < 200MB, set the cache size to shmmax and do not set soft limit.

**Comment by mpirvu** [comment]
In case we use a hard limit of 300MB (and a soft limit of 64MB) does that reserve some address space? I would like to avoid reducing the address space on 32-bit for no good reason.

**Comment by pshipton** [comment]
Thanks, good point. Perhaps we should limit the change in the default shared cache size to 64-bit JVMs.
