### ISSUE TITLE
-XX:+CompactStrings and a Trademark symbol in filenames

### ISSUE THREAD

**Issue by TX256** [eclipse/openj9#11650]
There appears to be a strange issue with -XX:+CompactStrings and filenames with trademark symbols in them. Instead of copying the content from a StackOverflow post, here's the link:

https://stackoverflow.com/questions/65496100/eclipse-openj9-xxcompactstrings-and-trademark-symbol-in-path-name

**Comment by gacholio** [comment]
@fjeremic

**Comment by fjeremic** [comment]
I'm unable to reproduce the issue on Linux. I don't have access to a Windows machine to try:

```
root@thy1:/tmp/fjeremic# jdk-11.0.9+11/bin/java TrademarkSymbol
/tmp/fjeremic/Test™.txt exists? true
/tmp/fjeremic/TrademarkSymbol.java exists? true
/tmp/fjeremic/OpenJDK11U-jdk_x64_linux_openj9_11.0.9_11_openj9-0.23.0.tar.gz exists? true
/tmp/fjeremic/jdk-11.0.9+11 exists? true
/tmp/fjeremic/TrademarkSymbol.class exists? true
/tmp/fjeremic/Test™.txt exists? true

root@thy1:/tmp/fjeremic# jdk-11.0.9+11/bin/java -XX:+CompactStrings TrademarkSymbol
/tmp/fjeremic/Test™.txt exists? true
/tmp/fjeremic/TrademarkSymbol.java exists? true
/tmp/fjeremic/OpenJDK11U-jdk_x64_linux_openj9_11.0.9_11_openj9-0.23.0.tar.gz exists? true
/tmp/fjeremic/jdk-11.0.9+11 exists? true
/tmp/fjeremic/TrademarkSymbol.class exists? true
/tmp/fjeremic/Test™.txt exists? true

root@thy1:/tmp/fjeremic# jdk-11.0.9+11/bin/java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
```

**Comment by pshipton** [comment]
It's recreatable on Windows using `-Xint`. The code creating the String is https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/src/windows/native/sun/nio/fs/WindowsNativeDispatcher.c#L358
So it seems NewString() isn't handling CompactString correctly.

**Comment by pshipton** [comment]
NewString() just calls j9gc_createJavaLangString()

Looks like this code is bogus
https://github.com/eclipse/openj9/blob/master/runtime/gc_base/StringTable.cpp#L537
length is the number of unicode (2 byte) characters, but `isUTF8ASCII()` expects the length in bytes.

**Comment by pshipton** [comment]
@dmitripivkine

**Comment by pshipton** [comment]
Sorry, ignore that, j9gc_createJavaLangString() is called with `((UDATA)len) * 2`

**Comment by pshipton** [comment]
Note I still believe there is a problem in j9gc_createJavaLangString(), although not sure where.

**Comment by pshipton** [comment]
Actually, I still think the call to `VM_VMHelpers::isUTF8ASCII()` is bogus. These are unicode character, a character like 0x1234 doesn't have any bytes > 0x7f, but it's not ascii.

**Comment by pshipton** [comment]
Note the trademark character is 0x2122

**Comment by gacholio** [comment]
isUTF8ASCII cannot be called with unicode characters.

**Comment by gacholio** [comment]
The call should not be made if STR_UNICODE is passed in the flags.

**Comment by pshipton** [comment]
Yes agree, there needs to be something similar, but different, done for unicode.

**Comment by pshipton** [comment]
i.e., assuming length is the unicode length
```

	static VMINLINE bool
	isUnicodeASCII(const unsigned short *data, UDATA length)
	{
		bool isASCII = true;

		for (UDATA i = 0; i < length; ++i) {
			if (data[i] > 0x7F) {
				isASCII = false;
				break;
			}
		}

		return isASCII;
	}
```

**Comment by pshipton** [comment]
I'll create a PR.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/pull/11668
