### ISSUE TITLE
[Nest mates] jvmti spec update to disallow nest mate attribute modification

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1165]
From the jvmti spec update:
```
11.0.0 7 February2018 
Minor update for new class file NestHost and NestMembers attributes: 
- Specify that RedefineClasses and RetransformClasses are notallowed to change the class file NestHost and NestMembers attributes. 
- Add new errorJVMTI_ERROR_UNSUPPORTED_REDEFINITION_CLASS_ATTRIBUTE_CHANGED that can be returned by RedefineClasses andRetransformClasses.
```

The new error constant is:
```
JVMTI_ERROR_UNSUPPORTED_REDEFINITION_CLASS_ATTRIBUTE_CHANGED (72)
A new class version has unsupported differences in class attributes.
```

And OpenJ9 will need to ensure that the NestHost and NestMembers attributes aren't modified by jvmti.

**Comment by DanHeidinga** [comment]
http://mail.openjdk.java.net/pipermail/valhalla-spec-experts/2018-February/000541.html

**Comment by DanHeidinga** [comment]
FYI @tajila @taliamccormick

**Comment by taliamccormick** [comment]
Disallow nestmates attribute changes during redefinition: https://github.com/eclipse/openj9/pull/1412
Update nestmates during redefinition: https://github.com/eclipse/openj9/pull/1411/
Tests for nestmate attributes during redefinition: https://github.com/eclipse/openj9/pull/1262

**Comment by DanHeidinga** [comment]
All 3 PRs have been merged.  Closing.
