### ISSUE TITLE
MathLoadTest_all_special_20 timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11666]
There is a core and javacore, but nothing obviously wrong other than the test is running for longer than the timeout allows.

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64_aix_Nightly_testList_1/43/
MathLoadTest_all_special_20
variation: Mode614
JVM_OPTIONS:  -Xcompressedrefs -Xgcpolicy:gencon -Xjit:counts=- - - - - - 1 1 1 1000 250 250 - - - 10000 100000 10000,gcOnResolve,rtResolve,sampleInterval=2,scorchingSampleThreshold=10000,quickProfile -Xmn512k -Xcheck:gc:vmthreads:all:quiet 
```
MLT 00:06:18.489 - Completed 1.5%. Number of tests started=81
MLT 00:06:38.435 - Completed 2.8%. Number of tests started=146 (+65)
MLT 00:06:58.428 - Completed 4.4%. Number of tests started=232 (+86)
...
MLT 02:04:58.575 - Completed 90.7%. Number of tests started=4764 (+8)
MLT 02:05:18.487 - Completed 90.8%. Number of tests started=4767 (+3)
MLT 02:05:38.694 - Completed 90.9%. Number of tests started=4772 (+5)
STF 02:05:55.410 - Heartbeat: Process MLT is still running
STF 02:05:56.413 - **FAILED** Process MLT has timed out
STF 02:05:56.413 - Collecting dumps for: MLT
...
MLT 02:05:58.404 - Completed 91.1%. Number of tests started=4785 (+13)
MLT 02:06:18.417 - Completed 91.3%. Number of tests started=4791 (+6)
MLT 02:06:38.548 - Completed 91.4%. Number of tests started=4799 (+8)
MLT 02:06:58.424 - Completed 91.5%. Number of tests started=4803 (+4)
MLT 02:07:18.481 - Completed 91.7%. Number of tests started=4813 (+10)
MLT 02:07:38.892 - Completed 91.7%. Number of tests started=4815 (+2)
MLT stderr JVMDUMP039I Processing dump event "user", detail "" at 2021/01/15 02:05:56 - please wait.
```

These timed out as well:

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly_testList_2/39/
MathLoadTest_all_special_20
```
MLT 02:49:46.433 - Completed 1.5%. Number of tests started=81
...
MLT 04:51:06.411 - Completed 73.5%. Number of tests started=3861 (+6)
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64_aix_Nightly_testList_1/41/
MathLoadTest_all_special_20
```
MLT 02:02:33.759 - Completed 1.6%. Number of tests started=86
...
MLT 04:03:54.105 - Completed 71.3%. Number of tests started=3741 (+0)
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly_testList_3/39/
MathLoadTest_all_special_20
```
MLT 01:18:19.684 - Completed 1.1%. Number of tests started=56
...
MLT 03:19:39.701 - Completed 81.1%. Number of tests started=4259 (+5)
```

Seems similar/dup of https://github.com/eclipse/openj9/issues/11190

**Comment by pshipton** [comment]
@Mesbah-Alam is this related to the timeout changes made yesterday? I think we need to reduce the number of iterations for Mode614. These tests don't need to be running for 2+ hours.

**Comment by Mesbah-Alam** [comment]
> is this related to the timeout changes made yesterday?

It should be. 

Some workloads defined in the test are likely taking longer than the timeout value set (2h) to finish when these special JIT modes were used on some platforms. 

It is a hard one to test in a Grinder as the time taken to complete same workload varies from machine to machine. 

I will reduce both the workload and the timeout of this test further. It should not cause us any testing gap since we are planning to enable the time-based equivalent for this test in near future.

**Comment by pshipton** [comment]
@Mesbah-Alam Note #11190 as well which has been going on for a while. Also Mode614. I'd like to see that one fixed as well so we aren't getting these sporadic failures in the builds.

**Comment by Mesbah-Alam** [comment]
https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/393 - this PR should ensure that the test runs a reduced workload for Mode614
