### ISSUE TITLE
J9 executed a different program path compared to OpenJDK.

### ISSUE THREAD

**Issue by fuzzy000** [eclipse/openj9#11665]
Java -version output
------------------
The issue happened in the following versions of J9:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201110_845 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)
```
```
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+12)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 9 Linux amd64-64-Bit Compressed References 20180814_248 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - feec4d2ae based on jdk-9.0.4+12)
```
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 11 Linux amd64-64-Bit Compressed References 20201022_810 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11)
```

The used OpenJDK versions:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```
```
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

Summary of problem
------------------

We made some changes to a class file in the Apache Ant project, and let several JVMs execute the corresponding JUnit test. We found that a test case, J9 (8u275, 9.0.4, 11.0.9) threw an org.junit.ComparisonFailure while OpenJDK (8u275, 9.0.4) threw a java.lang.AssertionError. After inspecting into the source code of JUnit, we found the JVM just executed the different path in the method `assertEquals` of `org.junit.Assert`(junit-4.12.jar):
```java
    static public void assertEquals(String message, Object expected,
            Object actual) {
        if (equalsRegardingNull(expected, actual)) {
            return;
        } else if (expected instanceof String && actual instanceof String) {
            String cleanMessage = message == null ? "" : message;
            throw new ComparisonFailure(cleanMessage, (String) expected, (String) actual);  // J9 executed this line
        } else {
            failNotEquals(message, expected, actual);  // OpenJDK executed this line
        }
    }
```

Take OpenJDK (8u275) and J9 (8u275) as an example:
OpenJDK (8u275):
```
3) testParse(org.apache.tools.zip.ExtraFieldUtilsTest)
java.lang.AssertionError: message expected:<bad extra field starting at 18.  Block length of 1 bytes exceeds remaining data of 0 bytes.> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.apache.tools.zip.ExtraFieldUtilsTest.testParse(ExtraFieldUtilsTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
```
J9 (8u275):
```
3) testParse(org.apache.tools.zip.ExtraFieldUtilsTest)
org.junit.ComparisonFailure: message expected:<[bad extra field starting at 18.  Block length of 1 bytes exceeds remaining data of 0 bytes.]> but was:<[Array index out of range: 22]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.apache.tools.zip.ExtraFieldUtilsTest.testParse(ExtraFieldUtilsTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
```

Diagnostic files
----------------

[DifferentExecutionPath.zip](https://github.com/eclipse/openj9/files/5821001/DifferentExecutionPath.zip)

1. extract the DifferentExecutionPath.zip
2. In directory `DifferentExecutionPath`, run command `java -cp sootOutput/junit-ant/:hamcrest-core-1.3.jar:junit-4.12.jar org.junit.runner.JUnitCore org.apache.tools.zip.ExtraFieldUtilsTest`

Sample Outputs
---------------------------------
Here is the sample output of OpenJDK and J9: [openjdk8_output.log](https://github.com/eclipse/openj9/files/5820912/openjdk8_output.log) and [j9-8_output.log](https://github.com/eclipse/openj9/files/5820917/j9-8_output.log)

Execution environment
---------------------------------
- OS and version: Ubuntu 16.04.6 LTS
- CPU model: Intel(R) Xeon(R) CPU E5-4610 v4 @ 1.80GHz
- Number of CPU cores: 4CPUs, each has 10 cores
- Size of physical memory: 16384 MB * 20

**Comment by pshipton** [comment]
This may be a difference in how the JVMs detect error conditions, or just something that works differently between Hotspot and OpenJ9. It's not necessary a problem that would be fixed, more information is required. There doesn't seem to be anything wrong in the execution of assertEquals() itself. The difference is related to the arguments passed in. Can you track back where `Object expected` comes from? Seems for Hotspot it's null, but for OpenJ9 it's a String "Array index out of range: 22".

I note the OpenJ9 versions are quite old, being 0.17. Maybe try with the latest release 0.23, or the 0.24 Milestone 2 driver, in case something changes.
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u282-b07_openj9-0.24.0-m2
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.10+8_openj9-0.24.0-m2

**Comment by fuzzy000** [comment]
Thanks for your response!
I have tried this class with the following version (latest I think), the result remains the same:
j9_8u275:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201110_845 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - b52d2ff7ee based on jdk8u275-b01)
```
openjdk_8u275:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
```
I'll update the versions in the issue description.

**Comment by fuzzy000** [comment]
I add several print statement in the ExtraFieldUtilsTest.java to debug:
```java
    @Test
    public void testParse() throws Exception {
        ZipExtraField[] ze = ExtraFieldUtils.parse(data);
        assertEquals("number of fields", 2, ze.length);
        assertTrue("type field 1", ze[0] instanceof AsiExtraField);
        assertEquals("mode field 1", 040755,
                     ((AsiExtraField) ze[0]).getMode());
        assertTrue("type field 2", ze[1] instanceof UnrecognizedExtraField);
        assertEquals("data length field 2", 1,
                     ze[1].getLocalFileDataLength().getValue());

        byte[] data2 = new byte[data.length - 1];
        System.arraycopy(data, 0, data2, 0, data2.length);
        try {
            ExtraFieldUtils.parse(data2);
            fail("data should be invalid");
        } catch (Exception e) {
            System.out.println(data2);
            System.out.println(e);
            System.out.println(e==null);
            System.out.println(e.getMessage());
            e.printStackTrace();
            assertEquals("message",
                         "bad extra field starting at " + (4 + aLocal.length)
                         + ".  Block length of 1 bytes exceeds remaining data of 0 bytes.",
                         e.getMessage());
        }
    }
```
I found that for openjdk8u275, e.getMessage() returns null, while e.getMessage() of J9 returns `Array index out of range: 22`. It seems that J9 is correct. I think it might be a bug in OpenJDK? What do you think? Does this violate the JVM specification? @pshipton

**Comment by pshipton** [comment]
I expect this behavior is outside of the spec. The spec dictates what exception to throw, but not the content of the exception message. The OpenJ9 message is more helpful, but I don't expect this behavior is a bug in OpenJDK/Hotspot.

What does the output of your debugging show? The `e.printStackTrace()` might show where the exception is thrown from.

**Comment by fuzzy000** [comment]
Here are what the print statements show:
[j9-8-OutputSample.log](https://github.com/eclipse/openj9/files/5834462/j9-8-OutputSample.log)
[openjdk8-OutputSample.log](https://github.com/eclipse/openj9/files/5834463/openjdk8-OutputSample.log)

**Comment by pshipton** [comment]
The exception is thrown from System.arraycopy(). There is no OpenJ9 problem here.
