### ISSUE TITLE
Merge jrvTest fix into v0.24.0-release branch

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9#11673]
PR https://github.com/eclipse/openj9/pull/11483 fixed the jrvTest failure seen in the v0.24.0 milestone builds at AdoptOpenJDK but was only merged into the master branch - it needs also to be included in the v0.24.0-release branch for the test to pass on that release.

**Comment by pshipton** [comment]
It shouldn't fail on the actual release when release versions are used, but anyway created https://github.com/eclipse/openj9/pull/11675
