### ISSUE TITLE
openjdk Cipher/ChaCha20/ChaCha20Poly1305ParamTest.java NullPointerException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11689]
com/sun/crypto/provider/Cipher/ChaCha20/ChaCha20Poly1305ParamTest.java 
```
11:15:04  java.lang.NullPointerException: Cannot read the array length because "this.nonce" is null
11:15:04  	at java.base/com.sun.crypto.provider.NativeChaCha20Cipher.engineGetParameters(NativeChaCha20Cipher.java:217)
11:15:04  	at java.base/javax.crypto.Cipher.getParameters(Cipher.java:1060)
11:15:04  	at ChaCha20Poly1305ParamTest.main(ChaCha20Poly1305ParamTest.java:240)
```

The test passes with `-Djdk.nativeCrypto=false`

**Comment by pshipton** [comment]
This also fails for jdk16, on Windows and Mac.
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_mac_Nightly/9
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/9

@ashbm5 we need an assessment of the severity, if this is a must fix for the jdk16 release or not.

**Comment by ashbm5** [comment]
This is an error in chacha20 block cipher. My assessment is that this is not a must fix for jdk16 release as the ChaCha20 algorithm intended user, the TLS v1.3 protocol, doesn't support its use (yet).

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Nightly/12
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_mac_Nightly/13
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/12

**Comment by pshipton** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-tests/pull/2221 to exclude the tests, moving to the next milestone.

**Comment by ashbm5** [comment]
@pshipton i'm having chao look at this issue

**Comment by pshipton** [comment]
Thanks. I'll tentatively move it back to the 0.25 milestone.

**Comment by shanchao95** [comment]
@pshipton PR is open for the fix of ChaCha20Poly1305ParamTest failure.

**Comment by pshipton** [comment]
I'll keep this open until the other versions are fixed as well.

**Comment by pshipton** [comment]
Opened https://github.com/AdoptOpenJDK/openjdk-tests/pull/2236 to un-exclude the test.
