### ISSUE TITLE
Create smaller code/data caches for JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#11687]
The default size of a code/data cache is 2MB. JITServer uses one such code/data cache per compilation thread (up to 63 threads by default). After compilation is done, the cache is reset to its original blank state. Thus, only the code and metadata for a single method is stored in a code/data cache and 2MB seems wasteful.
If we half the size, then we could save ~128M at the server during high load times.

**Comment by mpirvu** [comment]
FYI @dmitry-ten 
For JITServer, each compilation thread reserves a data cache and at the end of the compilation that data cache is reset (allocation pointer moved back to original position) and unreserved:
```
      if (((jitConfig->runtimeFlags & J9JIT_TOSS_CODE) || isJITServerMode) && comp)
         {
         if (jitConfig->runtimeFlags & J9JIT_TOSS_CODE)
            jitConfig->codeCache->heapAlloc = jitConfig->codeCache->heapBase;

         dataCache = (TR_DataCache*)comp->getReservedDataCache();
         if (dataCache)
            {
            dataCache->resetAllocationToMark();
            // TODO: make sure we didn't allocate a new dataCache (the mark was set in the old cache)
            TR_DataCacheManager::getManager()->makeDataCacheAvailable(dataCache);
            comp->setReservedDataCache(NULL);
            }
         }
```
To read the amount of data cache space used you check the available space in the reserved data cache `comp->getReservedDataCache()`
The memory segment backing the data cache grows from `_segment->heapBase` to `_segment->heapTop` and current allocation pointer is given by `uint8_t *getCurrentHeapAlloc() { return _segment->heapAlloc; }`
There is no accessor to read `heapBase` but you can get your hands on the segment with `dataCache->getSegment()` so the occupied space is  `dataCache->getCurrentHeapAlloc() - dataCache->getSegment()->heapBase`

**Comment by dmitry-ten** [comment]
Code and data cache size measurements for AcmeAir (1 client, 4CPUs per client, 2 runs):
```
Code Cache Max size: 114.8 KB
Code Cache Average size: 1.8 KB
Data Cache Max size: 144.5 KB
Data Cache Average size: 1.5 KB
n=12129
```
So most compilations are orders of magnitude smaller than 2MB and even the largest ones do not come close to approaching 2MB. Thus, reducing the size to 1MB or even to 512KB should be pretty safe.

**Comment by mpirvu** [comment]
Great! Let's reduce it to 1MB just in case other applications have larger methods.

**Comment by mpirvu** [comment]
Sizes are written in `onLoadInternal()` in `jitConfig->codeCacheKB` and `jitConfig->dataCacheKB`.
The tricky part is that we need to process options first to know that we are in server mode.

**Comment by mpirvu** [comment]
I am proposing to change `fePreProcess()` to add a test for `if (vm->internalVMFunctions->isJITServerEnabled(vm))` and change the default size of the code cache and data cache. This test needs to be placed before the logic that read the code cache size and data cache size from the command line options, to allow the user to change the default value. Hence, the new code needs to stay towards the beginning of `fePreProcess()`
