### ISSUE TITLE
DDR should use pointer classes generated at runtime

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11692]
DDR uses pre-compiled pointer classes generated at build time when using a 64-bit VM to look at a 64-bit core, or 32-bit VM to look at a 32-bit core. It uses pointer classes generated at runtime when there is a mismatch (e.g. 64-bit looking at 32-bit).

The runtime solution can be used always, instead of using the classes generated at build time. We were waiting for all the remaining DDR tests to  be ported to open source, and this action has been completed.

**Comment by keithc-ca** [comment]
Those classes still need to be generated at build time, in order to compile Java source files within `debugtools/DDR_VM/src`.

**Comment by pshipton** [comment]
> Those classes still need to be generated at build time

Edited to fix my wording.
