### ISSUE TITLE
libhyprtshim29.so is unnecessarily loaded

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#117]
libhyprtshim29.so is always loaded, but is only needed for IBM's Java 8 builds.

**Comment by pdbain-ibm** [comment]
I'll take this.

**Comment by pshipton** [comment]
Closing as a dup of #529. Current status: libhyprtshim29.so is no longer loaded by OpenJ9 builds, this obsoletes some OpenJ9 port library socket APIs which are still to be removed.
