### ISSUE TITLE
Update testng.xml files with parallel="none"

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#1170]
We are using a newer version of testng, and should check the testng.xml files in each of the test subdirs, and update those still using parallel to get rid of this warning:
[Test] [XmlSuite] [WARN] 'parallel' value 'false' is deprecated, default value will be used instead: 'none'.

**Comment by hmainismael** [comment]
Hello @smlambert , I'm a beginner and I would like to contribute for my first time.

Can I claim this issue ?

**Comment by llxia** [comment]
What version of testng are you using?

**Comment by hmainismael** [comment]
In fact I just would like to contribute and begin with an easy issue.


De : Lan Xia
Envoyé : jeudi 15 février à 17:31
Objet : Re: [eclipse/openj9] Update testng.xml files with parallel="none" (#1170)
À : eclipse/openj9
Cc : hmainismael, Comment


What version of testng are you using?

**Comment by pshipton** [comment]
If this issue isn't appropriately easy, #433 is simply adding some comments to the code.

**Comment by hmainismael** [comment]
Ok I'll check the testng.xml files in each of the test subdirs and update those still using parallel = "false" instead of parallel = "none"

**Comment by smlambert** [comment]
Thanks for picking this one up @hmainismael and welcome to the project!

**Comment by hmainismael** [comment]
The PR linked to this issue is #1187 . Thank you all !
