### ISSUE TITLE
Wrong MessageType::compilationCode comparison that always evaluates to false

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#11711]
In the code here https://github.com/eclipse/openj9/blob/master/runtime/compiler/control/JITClientCompilationThread.cpp#L3388-L3398
the `if` statement compares two different constants which will always evaluate to `false`
Note that at that point we know we have a message of type `compilationFailure` according to the `TR_ASSERT` above. What the code intended was to compare the `statusCode` sent by the server to `compilationLowPhysicalMemory` constant.
This bug was discovered by @AlexeyKhrabrov

**Comment by mpirvu** [comment]
Attn: @dmitry-ten

**Comment by dmitry-ten** [comment]
Good finding, I forgot that `statusCode` is not the same as message type.
In that case, we probably need a separate message to send the memory state.
