### ISSUE TITLE
SetGetSendBufferSize.testInitialSendBufferSize AssertionError: DatagramSocketAdaptor expected [true] but found [false]

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#11722]
A new test introduced in jdk-11.0.10+9 by https://bugs.openjdk.java.net/browse/JDK-8243488
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.openjdk_x86-64_mac_xl/10/consoleFull
```
15:59:03  test SetGetSendBufferSize.testInitialSendBufferSize("DatagramSocketAdaptor", SetGetSendBufferSize$$Lambda$69/0x0000000000000000@c72d44da): failure
15:59:03  java.lang.AssertionError: DatagramSocketAdaptor expected [true] but found [false]
15:59:03  	at org.testng.Assert.fail(Assert.java:94)
15:59:03  	at org.testng.Assert.failNotEquals(Assert.java:496)
15:59:03  	at org.testng.Assert.assertTrue(Assert.java:42)
15:59:03  	at SetGetSendBufferSize.testInitialSendBufferSize(SetGetSendBufferSize.java:95)
```

Is this an OpenSSL difference?

**Comment by pshipton** [comment]
Is it repeatable in a grinder (is it intermittent)? Does it only fail on specific machines?

> Is this an OpenSSL difference?
If it's repeatable, pls try running the test with `-Djdk.nativeCrypto=false`

**Comment by andrew-m-leonard** [comment]
Fails with -Djdk.nativeCrypto=false as well.
Also, fails with Hotspot so looks like upstream issue:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/13/testReport/junit/java_net_DatagramSocket_SetGetSendBufferSize/java/SetGetSendBufferSize/
