### ISSUE TITLE
openjdk jdk16 java/foreign/TestNative.java ClassCastException: java.lang.invoke.DirectHandle incompatible with java.lang.invoke.BoundMethodHandle

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11724]
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_windows_Nightly/1/
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_mac_Nightly/1/
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.openjdk_x86-64_linux_Nightly/1/
java/foreign/TestNative.java
```
00:21:10  Caused by: java.lang.ClassCastException: java.lang.invoke.DirectHandle incompatible with java.lang.invoke.BoundMethodHandle
00:21:10  	at java.base/java.lang.invoke.VarHandles.noCheckedExceptions(VarHandles.java:636)
00:21:10  	at java.base/java.lang.invoke.VarHandles.filterCoordinates(VarHandles.java:476)
00:21:10  	at java.base/java.lang.invoke.MethodHandleImpl$1.filterCoordinates(MethodHandleImpl.java:1781)
00:21:10  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryHandles.filterCoordinates(MemoryHandles.java:374)
00:21:10  	at jdk.incubator.foreign/jdk.internal.foreign.Utils.fixUpVarHandle(Utils.java:102)
00:21:10  	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:166)
00:21:10  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:488)
00:21:10  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout$$Lambda$36/0x0000000000000000.apply(Unknown Source)
00:21:10  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:534)
00:21:10  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:488)
00:21:10  	at TestNative.<clinit>(TestNative.java:90)
```

**Comment by babsingh** [comment]
Identical to https://github.com/eclipse/openj9/issues/10455. The `ClassCastException` should be resolved by https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/9. But, `TestNative.java` falls under the Foreign Function Support API (JEP389; incubator), which won't be supported in the 0.25 release. So, I will exclude this test.

**Comment by pshipton** [comment]
Strangely it's already excluded. Maybe the tests aren't using the jdk16 exclude list? @smlambert @llxia 
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk16-openj9.txt#L340

**Comment by smlambert** [comment]
A case where we have been 'tricky' with some native tests...  we excluded them in the Problemlists, and then run them via a different TKG target called [jdk_foreign_native](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/playlist.xml#L1122-L1147).  

This was so it can be tagged as 'native' type and not included when run in docker container runs or environments where we do not have the native test libraries and need to run only sanity.openjdk.regular (versus sanity.openjdk.native), related: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1921.

**Comment by pshipton** [comment]
The ClassCastException is resolved, https://github.com/eclipse/openj9/issues/11760 occurs instead now.
