### ISSUE TITLE
Same conditions in else if in CacheMap.cpp

### ISSUE THREAD

**Issue by qarmin** [eclipse/openj9#11743]
https://github.com/eclipse/openj9/blob/a1cfdc2866fe91f5eb5d775ff58a47bd7687a723/runtime/shared_common/CacheMap.cpp#L4785-L4789

**Comment by pshipton** [comment]
@hangshao0 looks like an easy fix

**Comment by hangshao0** [comment]
PR: https://github.com/eclipse/openj9/pull/11750
