### ISSUE TITLE
TR_ASSERT_FATAL uses abort() to terminate the program but SIGABRT cannot be caught via j9sig_protect

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#11765]
The fatal assert API within the JIT compiler, after printing a message uses `abort()` to send the `SIGABRT` signal and terminate the process eventually [1]. This is problematic for scenarios such as the JitDump generation mechanism because it appears we can only register one global `SIGABRT` handler:

https://github.com/eclipse/openj9/blob/6485d7550c994521c5ba78744d5530b78986d9a9/runtime/rasdump/dmpsup.c#L293-L306

What happens is that the first time a normal compilation triggers a failed assert, we will call `abort()` and the "one-shot dump trigger" in `abortHandler` (see above) will get executed. This will trigger the OpenJ9 dump processes. Eventually we will get to generating a JitDump at which point we will queue a recompilation of the problematic method with a trace log. During the compilation we will hit the assert again, and `abort()` will be called again. However the `abortHandler` has re-installed the applications default signal handler for `SIGABRT`:
https://github.com/eclipse/openj9/blob/6485d7550c994521c5ba78744d5530b78986d9a9/runtime/rasdump/dmpsup.c#L198-L199

And of course the second time we hit the `abort()` call while generating the JitDump trace log, we will execute the application default handler which just terminates the process. This means the JitDump generation does not fully complete, and any dump handlers following the JitDump will not execute. This is not what we want!

[1] https://github.com/eclipse/omr/blob/b38b0b77c9972bc0b8d01ed66665270a0f108845/compiler/infra/Assert.cpp#L69

**Comment by fjeremic** [comment]
@gacholio could you confirm that there is no way for us to catch `SIGABRT` via a custom handler function when calling `j9sig_protect`? I tried to add `J9PORT_SIG_FLAG_SIGABRT` to the flags here:
https://github.com/eclipse/openj9/blob/6485d7550c994521c5ba78744d5530b78986d9a9/runtime/compiler/control/CompilationThread.cpp#L7834-L7862

So that I could try to catch the signal during JitDump and handle it properly but it does not end up catching the signal.

If there is no way to catch this signal and execute custom logic, I think we will have to resort to not using `abort()` within the `TR_ASSERT_FATAL` API if we are a JitDump compile. This can easily be done via an option which we activate when starting the compilation for the JitDump.

**Comment by gacholio** [comment]
This would be a better question for @babsingh or @keithc-ca.

I would replace the abort with a crash.

**Comment by babsingh** [comment]
> catch SIGABRT via a custom handler function?

Yes, this is possible. Two requirements: 
1. The handler would need to be reset to JVM's default `abortHandler` after the JIT work is done.
2. A customer should not be impacted by the override of JVM's default `abortHandler`.

### Option 1
The behaviour is similar to https://man7.org/linux/man-pages/man2/signal.2.html. The handler is reset after the first invocation.
```
/* Install a customHandler */
void *oldHandler = OMRSIG_SIGNAL(SIGABRT, customHandler);
abort();
```
**Example:** https://github.com/eclipse/openj9/blob/adde9ef085c537ce7896bc67c3f31c7e315a347c/runtime/rasdump/dmpsup.c#L303-L304

### Option 2
The behaviour is similar to https://man7.org/linux/man-pages/man2/sigaction.2.html. The handler is persistent, and it will not reset after the first invocation.
```
/* Install a customHandler */
void **oldHandler;
IDATA rc = j9sig_set_single_async_signal_handler(customHandler, vm, J9PORT_SIG_FLAG_SIGABRT, oldHandler);
abort();
```
**Example:** https://github.com/eclipse/openj9/blob/4d4333997693ffd42793300b0ac13761569eb066/runtime/vm/jvminit.c#L7444

**Comment by fjeremic** [comment]
Thanks for the explanation. In #11825 we went with the simplest solution which GAC suggested, to just force a crash if we are doing a JitDump compilation, rather than an `abort`. This will avoid the whole issue of fiddling with handler entries.
