### ISSUE TITLE
ValueTypes: GC class slot iterator doesnt scan flattenable field classes

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11771]
The existing GC_ClassIteratorClassSlots doesn't scan the J9Classes in the flattened field cache (FCC). A class in the FCC may not necessarily belong to the same classloader (this will be possible with specialized generics) as the container classes. However the class in the FCC cannot be unloaded until the container class is unloaded as the existence of the container class implies that the FCC class is reachable since flattened fields are non-nullable even though an instance of the FCC class may not exist in the heap.

**Comment by tajila** [comment]
@dmitripivkine

**Comment by dmitripivkine** [comment]
May I have more precise details what exactly should be scanned? Where is reference to FCC? What is a way to iterate FCC? etc

**Comment by tajila** [comment]
In J9Class (https://github.com/eclipse/openj9/blob/master/runtime/oti/j9nonbuilder.h#L3074) there is a field called `flattenedClassCache` https://github.com/eclipse/openj9/blob/master/runtime/oti/j9nonbuilder.h#L1744. Each entry contains a J9Class pointer. 

We have macros to iterate items in the FCC (ie. `J9_VM_FCC_CLASS_FROM_ENTRY(..), etc.`. All classes that may contain fields (ie. not arrays or interfaces) need to be checked.

**Comment by dmitripivkine** [comment]
Unfortunately update of `GC_ClassIteratorClassSlots` is not enough. There is number of places where discovering class pointers from class is implemented manually, for example `MM_MarkingDelegate::scanClass()`

**Comment by dmitripivkine** [comment]
> Unfortunately update of `GC_ClassIteratorClassSlots` is not enough. There is number of places where discovering class pointers from class is implemented manually, for example `MM_MarkingDelegate::scanClass()`

Actually `MM_MarkingDelegate::scanClass()` is an only place does not use `MM_MarkingDelegate::scanClass()`... May be it is time to update this code to use iterator as well

**Comment by dmitripivkine** [comment]
implemented in https://github.com/eclipse/openj9/pull/12106

**Comment by dmitripivkine** [comment]
postponed due undefined specs https://github.com/eclipse/openj9/issues/12156

**Comment by dmitripivkine** [comment]
@tajila This is implemented. The only leftover is jvmtiHeap part but there is no specifications yet.
I think this item can be closed
