### ISSUE TITLE
4 zlinux machines offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11781]
ub16-390-1, 2
ub18-390-1, 2 are all offline

https://ci.eclipse.org/openj9/computer/ub16-390-1/log
https://ci.eclipse.org/openj9/computer/ub16-390-2/log
https://ci.eclipse.org/openj9/computer/ub18-390-1/log
https://ci.eclipse.org/openj9/computer/ub18-390-2/log
`Error: Invalid or corrupt jarfile slave.jar`

@AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
DNS is  failing on these systems.  There is an entry in the resolv.conf file on the RH7 systems that isn't on the UB systems.  I've added it and all 4 have come back online.

But I have not made this change permanent, as its supplied/updated from dhcpd.  I'll have to follow up with Marist.

**Comment by jdekonin** [comment]
IBM Z Open Source Ecosystem admins will be investigating the matter.  Until then the solution we have in place will work until the machine(s) are rebooted.

**Comment by jdekonin** [comment]
This also impacts ub16-s390x-01 and ub16-s390x-02 OMR nodes. ( https://ci.eclipse.org/omr )

**Comment by jdekonin** [comment]
Systems are online and functional again.
