### ISSUE TITLE
Suboptimal JITted code from String.equals()

### ISSUE THREAD

**Issue by 0dvictor** [eclipse/openj9#1179]
String.equals() checks a couple of shortcuts before calling String.regionMatches() to decide whether two strings are equal. String.regionMatches() always does sanity checks before element-by-element content comparison.
From their implementations, it is easy to tell that when calling from String.equals(), all sanity checks inside String.regionMatches() always hold and hence execution always reaches to element-by-element content comparison. 
However, the optimizer is unable to eliminate these sanity checks even though String.regionMatches() is very-likely being inlined into String.equals(). The reason behind is that sanity checks inside String.regionMatches() rely on field values of the String. OpenJ9's optimizer normally does not propagate value information of a field of a class. As a result, the optimizer does not have enough information to conclude that sanity checks inside String.regionMatches() are unnecessary. 
One solution is to separate element-by-element comparison logic into a new function, named String.regionMatchesInternal(), so that String.equals() can call String.regionMatchesInternal() directly, avoiding those unnecessary sanity checks.

```
public boolean equals(Object object) {
	if (object == this) {
		return true;
	}
	if (object instanceof String) {
		String s1 = this;
		String s2 = (String) object;
		int s1len = s1.lengthInternal();
		int s2len = s2.lengthInternal();
		if (s1len != s2len) {
			return false;
		}
		if (s1.value == s2.value) {
			return true;
		}
		// There was a time hole between first read of s.hashCode and second read if another thread does hashcode
		// computing for incoming string object
		int s1hash = s1.hashCode;
		int s2hash = s2.hashCode;
		if (s1hash != 0 && s2hash != 0 && s1hash != s2hash) {
			return false;
		}
		boolean matches = regionMatches(0, s2, 0, s1len);
		if (!matches) {
			return false;
		}
		if (com.ibm.oti.vm.VM.J9_JIT_STRING_DEDUP_POLICY != com.ibm.oti.vm.VM.J9_JIT_STRING_DEDUP_POLICY_DISABLED) {
			deduplicateStrings(s1, s2);
		}
		
		return true;
	}
	return false;
}
public boolean regionMatches(int thisStart, String string, int start, int length) {
	string.getClass(); // Implicit null check
	String s1 = this;
	String s2 = string;
	int s1len = s1.lengthInternal();
	int s2len = s2.lengthInternal();

	if (start < 0 || s2len - start < length) {
		return false;
	}
	if (thisStart < 0 || s1len - thisStart < length) {
		return false;
	}
	if (length <= 0) {
		return true;
	}
	int o1 = thisStart;
	int o2 = start;
	// Index of the last char to compare
	int end = length - 1;
	/*[IF Sidecar19-SE]*/
	byte[] s1Value = s1.value;
	byte[] s2Value = s2.value;
	/*[ELSE]*/
	char[] s1Value = s1.value;
	char[] s2Value = s2.value;
	/*[ENDIF]*/
	s1Value.getClass(); // Implicit null check
	s2Value.getClass(); // Implicit null check
	if (enableCompression && ((compressionFlag == null) || ((s1.count | s2.count) >= 0))) {
		if (helpers.getByteFromArrayByIndex(s1Value, o1 + end) != helpers.getByteFromArrayByIndex(s2Value, o2 + end)) {
			return false;
		} else {
			for (int i = 0; i < end; ++i) {
				if (helpers.getByteFromArrayByIndex(s1Value, o1 + i) != helpers.getByteFromArrayByIndex(s2Value, o2 + i)) {
					return false;
				}
			}
		}
	} else {
		if (s1.charAtInternal(o1 + end, s1Value) != s2.charAtInternal(o2 + end, s2Value)) {
			return false;
		} else {
			for (int i = 0; i < end; ++i) {
				if (s1.charAtInternal(o1 + i, s1Value) != s2.charAtInternal(o2 + i, s2Value)) {
					return false;
				}
			}
		}
	}
	return true;
}
```

**Comment by fjeremic** [comment]
Thanks for the explanation @0dvictor! This makes the change in #875 much clearer. I've merged the PR just now, thus closing out this issue as well. Please feel free to reopen should there be a need for further discussion on this topic.
