### ISSUE TITLE
Jep397Tests_0 failing on some platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11856]
Test introduced by https://github.com/eclipse/openj9/pull/11606

https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.functional_ppc64_aix_Nightly_testList_0/13/
Jep397Tests_0
```
===============================================
Running test Jep397Tests_0 ...
===============================================
Jep397Tests_0 Start Time: Tue Feb  2 06:38:20 2021 Epoch Time (ms): 1612265900114
variation: --enable-preview
JVM_OPTIONS:  --enable-preview 
java.io.FileNotFoundException: /home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_ppc64_aix_Nightly_testList_0/jvmtest/functional/Java16andUp/testng.xml (A file or directory in the path name does not exist.)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
	at org.testng.xml.Parser.parse(Parser.java:148)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.TestNG.initializeEverything(TestNG.java:995)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
[TestNG] [ERROR] No test suite found. Nothing to run
```

https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.functional_x86-64_linux_Nightly_testList_0/14
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.functional_s390x_linux_Nightly_testList_1/14/
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.functional_ppc64le_linux_Nightly_testList_0/14

**Comment by pshipton** [comment]
@mikezhang1234567890 pls take a look

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
The test passed on wins and mac, but failed on aix, s390 and ppcle

From `<internal TRSS>/testPerPlatform?testId=601915a8d39ffe5b180f2c99`

![image](https://user-images.githubusercontent.com/19273206/106613820-9c501500-6538-11eb-944e-85182805a06d.png)

**Comment by pshipton** [comment]
I thought it did pass on plinux 5 days earlier when PR testing ran https://github.com/eclipse/openj9/pull/11606#issuecomment-769435494

**Comment by pshipton** [comment]
I see in that earlier PR testing the test didn't run at all.

**Comment by mikezhang1234567890** [comment]
Taking a look.
