### ISSUE TITLE
ensureOSRBufferSize() is not working correctly for JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#11893]
`ensureOSRBufferSize()` is a frontend call that makes sure the OSR buffer kept by the VM is large enough.
This method defers to a VM implementation:
```
UDATA
ensureOSRBufferSize(J9JavaVM *vm, UDATA osrFramesByteSize, UDATA osrScratchBufferByteSize, UDATA osrStackFrameByteSize)
{
	UDATA result = TRUE;
	UDATA osrGlobalBufferSize = sizeof(J9JITDecompilationInfo);
	osrGlobalBufferSize += ROUND_TO(sizeof(UDATA), osrFramesByteSize);
	osrGlobalBufferSize += ROUND_TO(sizeof(UDATA), osrScratchBufferByteSize);
	osrGlobalBufferSize += ROUND_TO(sizeof(UDATA), osrStackFrameByteSize);
	if (osrGlobalBufferSize > vm->osrGlobalBufferSize) {
		omrthread_monitor_enter(vm->osrGlobalBufferLock);
		if (osrGlobalBufferSize > vm->osrGlobalBufferSize) {
			PORT_ACCESS_FROM_JAVAVM(vm);
			void *newBuffer = j9mem_reallocate_memory(vm->osrGlobalBuffer, osrGlobalBufferSize, OMRMEM_CATEGORY_JIT);
			if (NULL == newBuffer) {
				result = FALSE;
			} else {
				vm->osrGlobalBufferSize = osrGlobalBufferSize;
				vm->osrGlobalBuffer = newBuffer;
			}
		}
		omrthread_monitor_exit(vm->osrGlobalBufferLock);
	}
	return result;
}
```
The OSR buffer is needed in the client JVM, so increasing the buffer in the server JVM accomplishes nothing.
A fix could be to cache the current size of OSR buffer in the per client caches (vm struct). When we determine that current size is not large enough, a message needs to be sent to the client JVM to increase the OSR buffer size.

**Comment by mpirvu** [comment]
FYI @dmitry-ten

**Comment by dmitry-ten** [comment]
Is this triggered by a specific test?

**Comment by mpirvu** [comment]
No, I was reviewing a PR, found this code and realized we don't do the correct thing. It may happen that the initial size of the buffer is large enough that we don't have to grow it, in which case there will be no error showing.
