### ISSUE TITLE
ub16-390-1 and 2 are offline - Operation timed out

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11896]
https://ci.eclipse.org/openj9/computer/ub16-390-1/log
https://ci.eclipse.org/openj9/computer/ub16-390-2/log
`Operation timed out`

@jdekonin

**Comment by AdamBrousseau** [comment]
Also the 2 ub18s. rh7 seem fine.

Sent an email to z-cloud contact

**Comment by pshipton** [comment]
They are back now.
