### ISSUE TITLE
Upgrade website to improve compilation instructions.

### ISSUE THREAD

**Issue by jabrena** [eclipse/openj9#119]
Hi,

This morning I was testing the whole process to compile #openj9 with the first Docker image and I had a minor problem with the previous step to `make all`.
https://www.eclipse.org/openj9/oj9_build.html

**Evidence:**

```
root@ef8bdb6be04e:~/openj9-openjdk-jdk9# bash ./configure --with-freemarker-jar=~/freemarker.jar
Running custom generated-configure.sh
configure: Configuration created at Sat Sep 23 11:47:20 UTC 2017.
configure: configure script generated at timestamp 1506103370.
checking for basename... /usr/bin/basename
checking for bash... /bin/bash
checking for cat... /bin/cat
checking for chmod... /bin/chmod
checking for cmp... /usr/bin/cmp
checking for comm... /usr/bin/comm
checking for cp... /bin/cp
checking for cut... /usr/bin/cut
checking for date... /bin/date
checking for gdiff... no
checking for diff... /usr/bin/diff
checking for dirname... /usr/bin/dirname
checking for echo... /bin/echo
checking for expr... /usr/bin/expr
checking for file... /usr/bin/file
checking for find... /usr/bin/find
checking for head... /usr/bin/head
checking for gunzip... /bin/gunzip
checking for pigz... no
checking for gzip... /bin/gzip
checking for ln... /bin/ln
checking for ls... /bin/ls
checking for mkdir... /bin/mkdir
checking for mktemp... /bin/mktemp
checking for mv... /bin/mv
checking for nawk... /usr/bin/nawk
checking for printf... /usr/bin/printf
checking for rm... /bin/rm
checking for rmdir... /bin/rmdir
checking for sh... /bin/sh
checking for sort... /usr/bin/sort
checking for tail... /usr/bin/tail
checking for gtar... no
checking for tar... /bin/tar
checking for tee... /usr/bin/tee
checking for touch... /usr/bin/touch
checking for tr... /usr/bin/tr
checking for uname... /bin/uname
checking for uniq... /usr/bin/uniq
checking for wc... /usr/bin/wc
checking for which... /usr/bin/which
checking for xargs... /usr/bin/xargs
checking for gawk... no
checking for mawk... mawk
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for a sed that does not truncate output... /bin/sed
checking for cygpath... no
checking for greadlink... no
checking for readlink... /bin/readlink
checking for df... /bin/df
checking for cpio... /bin/cpio
checking for nice... /usr/bin/nice
checking for pandoc... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking openjdk-build os-cpu... linux-x86_64
checking openjdk-target os-cpu... linux-x86_64
checking compilation type... native
checking for top-level directory... /root/openj9-openjdk-jdk9
checking if custom source is suppressed (openjdk-only)... no
checking which variant of the JDK to build... normal
checking which debug level to use... release
checking which variants of the JVM to build... server
checking that freemarker location is set... yes
checking for ~/freemarker.jar... no
configure: error: freemarker.jar not found in directory indicated
configure exiting with result code 1
root@ef8bdb6be04e:~/openj9-openjdk-jdk9# make all
Error: No configurations found for /root/openj9-openjdk-jdk9.
Please run 'bash configure' to create a configuration.

/root/openj9-openjdk-jdk9/make/Init.gmk:124: *** Cannot continue.  Stop.
```

To finish the process, I had to set the absolute path in the step:

```
root@ef8bdb6be04e:~/openj9-openjdk-jdk9# bash ./configure --with-freemarker-jar=/root/freemarker.jar
```

If you indicate the repo for the microsite, I could do a PR.

Many thanks in advance.

Cheers

Juan Antonio

**Comment by DanHeidinga** [comment]
Thanks for checking out OpenJ9 and reporting this issue, @jabrena.

The website is currently hosted directly on the Eclipse git repo at: https://git.eclipse.org/c/gerrit/www.eclipse.org/openj9.git/ and will eventually be mirrored to https://github.com/eclipse/openj9-website

I haven't updated the website directly yet so I'm not sure how to open a pull request against that repo.  @SueChaplain Can you provide details on how to provide PRs to the site?

**Comment by jabrena** [comment]
Hi @DanHeidinga, you are welcome.

Later, I will test the rest of the images, the process is pretty easy.
I am creating some Docker files for `armel` and `armhf` compilation.

Juan Antonio

**Comment by AdamBrousseau** [comment]
related ibmruntimes/openj9-openjdk-jdk9#29

**Comment by jabrena** [comment]
Oki, I have pènding the second and third docker images if exist the same issue.

**Comment by SueChaplain** [comment]
@DanHeidinga We should have the prime site at github.com/eclipse/openj9-website within a couple of days. The admins at Eclipse have been setting up the credentials for us to pull from that site via the Eclipse JIPP and publish to https://git.eclipse.org/c/gerrit/www.eclipse.org/openj9.git/ .  It will be much easier for people to submit PRs in github. Watch this space :-) And @jabrena - thanks for testing and finding that. We've had mixed input on whether the absolute path was required or not ... I've got some other changes to make for the page, so we can apply that one on your behalf. BTW, if you come across anything else that needs updating on the website, or have any suggestions for improvement, we are hosting issues for the website here: github.com/eclipse/openj9-website/issues.

**Comment by jabrena** [comment]
Hi @SueChaplain, you are welcome. I try to collaborate with the `openj9` ecosystem. :)

Next week, I will continue working in a version of this `Dockerfile`:
https://github.com/ev3dev-lang-java/docker-cross/blob/master/ev3dev-jessie/debian-jessie-armel.dockerfile

To compile `openj9` on `armel`
https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile

Maybe it is better to test with the PR about CMake support:
https://github.com/eclipse/openj9/pull/52

Juan Antonio

**Comment by SueChaplain** [comment]
@jabrena The instructions for setting the path to the freemarker.jar are now updated on the website. Thanks for reporting it!
