### ISSUE TITLE
All AIX are offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11918]
@AdamBrousseau @jdekonin fyi

**Comment by jdekonin** [comment]
The VPN connection isn't resolving to a hostname.  I can connect with the IP address but there is still clearly something wrong as we cannot even ping the systems.

I've sent an email to our contacts looking for information.

**Comment by jdekonin** [comment]
Systems are all back online.

**Comment by pshipton** [comment]
The machines are offline again.
