### ISSUE TITLE
OJDK MH: java.lang.NoClassDefFoundError: InjectedInvoker/...

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#11926]
### Errors
Unexpected `NoClassDefFoundError` thrown when OJDK MHs are enabled in OpenJ9.
```
FAILED: test_RevealDirect_CrackCallerSensitive
java.lang.NoClassDefFoundError: InjectedInvoker/0x0000000000000000 (wrong name: org/openj9/test/java/lang/invoke/Test_MethodHandleInfo$$InjectedInvoker)
        at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:525) from jrt:/java.base
        at java.base/java.lang.Access.defineClass(Access.java:336) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2446) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2423) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.makeInjectedInvoker(MethodHandleImpl.java:1168) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1178) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandleImpl$BindCaller$1.computeValue(MethodHandleImpl.java:1176) from jrt:/java.base
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228) from jrt:/java.base
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210) from jrt:/java.base
        at java.base/java.lang.ClassValue.get(ClassValue.java:116) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandleImpl$BindCaller.bindCaller(MethodHandleImpl.java:1148) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandleImpl.bindCaller(MethodHandleImpl.java:1126) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandles$Lookup.maybeBindCaller(MethodHandles.java:4011) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3995) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:3932) from jrt:/java.base
        at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2596) from jrt:/java.base
        at org.openj9.test.java.lang.invoke.Test_MethodHandleInfo.test_RevealDirect_CrackCallerSensitive(Test_MethodHandleInfo.java:794) from jdk.internal.loader.ClassLoaders$AppClassLoader@36ed38dc(file:/home/jenkins/workspace/Test_openjdk16_j9_sanity.functional_x86-64_linux_ojdk292_Personal_testList_1/jvmtest/functional/Java8andUp/GeneralTest.jar)
```

### Failing Test Targets

1. `JCL_Test_*`  (multiple variants with different JVM arguments) [sanity.functional]
    - `test_RevealDirect_CrackCallerSensitive`
2. `jsr292BootstrapTest_0`, `jsr292BootstrapTests_special_0` [extended.functional]
    - `test_BootstrapLookup_NonBootstrapInvoke`
    - `test_NonBootstrapLookup_BootstrapInvoke`
    - `test_NonBootstrapLookup_NonBootstrapInvoke`
3. `cmdLineTester_getCallerClassTests_0` [extended.functional]
    - `call APIs with/without @CallerSensitive annotation from the bootstrap classloader`

### How-to Run Tests?

https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
Needs to be investigate.

This should be tagged with the `project:MH` label.

**Comment by babsingh** [comment]
**Error**:
```
java.lang.NoClassDefFoundError: 
    InjectedInvoker/0x0000000000000000 
        (
             wrong name: 
                 org/openj9/test/java/lang/invoke/Test_MethodHandleInfo$$InjectedInvoker
        )
```

**Trace output:**
```
01:55:33.372 0x1aa00     j9bcu(j9vm).198      - BCU Trc_BCU_internalDefineClass_FullData: data=<CA><FE><BA><BE>, classLoader=00007FF030085E78
01:55:33.372 0x1aa00     j9bcu(j9vm).18       > BCU createROMClassFromClassFile: entering with loadData=00007FF0382DAB50
01:55:33.372 0x1aa00     j9bcu(j9vm).11       > BCU internalLoadROMClass: loadData=00007FF0382DAB50 classDataLength=291
01:55:33.372 0x1aa00     j9bcu(j9vm).174      > BCU build ROMClass start [classname=javasoft/sqe/tests/api/java/lang/reflect/Proxy/ProxyModuleTest$ProxyClassSupplierMethod$$InjectedInvoker] (note - this value does not always get set)
01:55:33.372 0x1aa00     j9bcu(j9vm).177      - BCU Start Translation javasoft/sqe/tests/api/java/lang/reflect/Proxy/ProxyModuleTest$ProxyClassSupplierMethod$$InjectedInvoker Classloader 00007FF030085E78

01:55:33.372 0x1aa00     j9bcu(j9vm).179      < BCU build ROMClass end result=-11       // ClassNameMismatch
01:55:33.372 0x1aa00     j9bcu(j9vm).14       < BCU internalLoadROMClass: result=-11    // ClassNameMismatch

01:55:33.372 0x1aa00     j9bcu(j9vm).25     * - BCU createROMClassFromClassFile: !! ROMCLASS LOAD FAILED !! Throwing exception number 21
```

**During ROMClass creation**, `ClassNameMismatch` happens for `Test_MethodHandleInfo$$InjectedInvoker` (Lambda class):
https://github.com/eclipse/openj9/blob/13936a4d3a86c1330b7c34cb82106a72c205a3bd/runtime/bcutil/ROMClassCreationContext.hpp#L430

**OpenJ9 assumes** ... `Lambda class has class name: HostClassName$$Lambda$<IndexNumber>/0x0000000000000000`:
https://github.com/eclipse/openj9/blob/13936a4d3a86c1330b7c34cb82106a72c205a3bd/runtime/bcutil/ROMClassCreationContext.hpp#L412-L415

As per [MethodHandleImpl.makeInjectedInvoker](https://github.com/openjdk/jdk16/blob/37043b05576c8b81b43ac41a8f06de0d0bbb3f5b/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java#L1161), `%TARGET_CLASS%$$InjectedInvoker` will not have `$<IndexNumber>/0x0000000000000000`. This violates our `Lambda class` assumption.

@tajila @DanHeidinga @gacholio How should we handle `InjectedInvoker`? Should we remove `/0x0000000000000000` and then perform a class name match similar to the below code where `$<IndexNumber>/0x0000000000000000` is removed?
https://github.com/eclipse/openj9/blob/13936a4d3a86c1330b7c34cb82106a72c205a3bd/runtime/bcutil/ROMClassCreationContext.hpp#L407-L417

**Comment by DanHeidinga** [comment]
Is this problem specific to the OJDK MH's implementation or is it a general problem with our assumptions around names that may no longer hold given the introduction of MHs.Lookup.defineClass?

**Comment by babsingh** [comment]
> Is this problem specific to the OJDK MH's implementation ...?

Yes, this is OJDK MH specific: https://github.com/openjdk/jdk16/blob/37043b05576c8b81b43ac41a8f06de0d0bbb3f5b/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java#L1161.

`$$InjectedInvoker/0x0000000000000000` has been introduced. It shares similar traits to `$$Lambda$<IndexNumber>/0x0000000000000000`.

As per https://mail.openjdk.java.net/pipermail/core-libs-dev/2021-January/073184.html,
> A MethodHandle on the other hand should not be caller sensitive. To archive this, a MethodHandle will "bind" the lookup class as caller for caller sensitive methods. This is currently done by injecting a hidden class (**InjectedInvoker**) 
that acts as a trampoline for calling caller sensitive methods.

For `$$Lambda$`, we match the class name till the last `$`. For `$$InjectedInvoker/`, we will have to match the class name till the last `/`.

**Comment by DanHeidinga** [comment]
The reason I ask if its a general problem - rather than a MH specific one - is the line of code just a little further in that file that uses `Lookup().....defineClass()` to define the class:
https://github.com/openjdk/jdk16/blob/37043b05576c8b81b43ac41a8f06de0d0bbb3f5b/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java#L1167

So I'll ask again, will this affect other users of the Lookup definClass apis?

**Comment by babsingh** [comment]
> will this affect other users of the Lookup definClass apis?

The two public `Lookup` methods for creating hidden classes do not allow class names to be specified: [Lookup.defineHiddenClass](https://download.java.net/java/early_access/jdk16/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#defineHiddenClass(byte%5B%5D,boolean,java.lang.invoke.MethodHandles.Lookup.ClassOption...)) and [Lookup.defineHiddenClassWithClassData](https://download.java.net/java/early_access/jdk16/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#defineHiddenClassWithClassData(byte%5B%5D,java.lang.Object,boolean,java.lang.invoke.MethodHandles.Lookup.ClassOption...)). The Java doc specifies the naming convention for hidden classes. For the public API, our assumption around names should stay true.

In your reference, `Lookup.makeHiddenClassDefiner(String, byte[])` is package protected, and it allows the name for the hidden class to be specified. Only the `invoke` package has access to this API. `$$InjectedInvoker` seems to be a special case where the `ROMClass` name differs from the supplied class name. Not completely sure; may be `ClassNameMisMatch` can be avoided if the `InjectedInvoker` is created using the public API for creating a hidden class; but, this will require extension repo changes.

**Comment by DanHeidinga** [comment]
Thanks for confirming that.  It makes the suggested approach in https://github.com/eclipse/openj9/issues/11926#issuecomment-797009887 sound like the right way to go.
