### ISSUE TITLE
Enable valhalla as default in VT build

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#11920]
Currently the `-XX:+EnableValhalla` option needs to be turned on to enable value types in the VT build. Given that there has been more progress the JIT and the interpreter this can be enabled by default.

We can keep the option so it can be used for debugging purposes but we can make `-XX:+EnableValhalla` true by default so it doesn't need to be added in test cases.

We will need to update the option parsing code in jvminit.c to make it default. Also we will need to update the test code in `/openj9/test/functional/Valhalla/playlist.xml` to remove the option.

**Comment by tajila** [comment]
@hangshao0 can you please take a look at this.

**Comment by hangshao0** [comment]
> can you please take a look at this.

Yes.
