### ISSUE TITLE
Increase nightly build timeout

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11945]
Now that we are switching to mixed builds, testing is taking longer and can need more time to complete on the available machines. I'd like to add 2 hours to the nightly build timeouts to ensure we complete rather than timing out.

This one timed out last night.
https://ci.eclipse.org/openj9/job/Test_openjdk16_j9_sanity.system_x86-64_mac_mixed_Nightly_testList_0/1

@AdamBrousseau

**Comment by gacholio** [comment]
Would it make sense to split the compressed and full testing into different lists and run them separately?

**Comment by pshipton** [comment]
Probably not. We already have parallel testing enabled which splits the tests into multiple parts. I did ask @llxia about splitting system tests into 3 parts instead of the 2 we have now, which should help a little at the end when machines start to become free. I'm also disabling special.system tests for Mac and Win to reduce the test load. https://github.com/eclipse/openj9/pull/11947. I still think we should increase the build timeout because the number of builds happening overnight may still overrun the timeout.

The only way splitting compressed and full testing into separate suites would additionally help is by excluding part of it.

**Comment by AdamBrousseau** [comment]
Increased 3 nightly (8,11,16) from 14 hours to 16 hours in the Jenkins config at the top level since this is the timeout that was hit.
