### ISSUE TITLE
Question: can VM-Proxy support be removed?

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#1194]
Some `JVM_` methods are implemented within `j9vm/j[7|8|9]vmi.c`, and some are in `sunvmi/sunvmi.c` which are invoked via `g_VMI->JVM_xxx` in `j9vm/vmi.c`.

It appears those `JVM_` metheds implemented in `sunvmi/sunvmi.c` are for `VM-Proxy` service support, and `sunvmi` has its own `module.xml` file.

If `VM-Proxy` support is not required, `sunvmi` can be merged into `j9vm` to remove `sunvmi` module, in addition also avoid building extra `sunvmi` library to support incompatible API changes such as those introduced by `Java 11`. 
Note: `j9vm` for `Java 11` will be built instead similar with `j9vm` for `b148/b150/b156`.

@DanHeidinga @pshipton please provide guidance.

**Comment by DanHeidinga** [comment]
Most of the `VM-Proxy` support has already been removed from the code base.  I'm OK with merging sunvmi and j9vm if the only reason they were separated was `VM-Proxy`.

**Comment by DanHeidinga** [comment]
I'm going to close this as the answer has been provided.  Please reopen if further discussion is required.

**Comment by JasonFengJ9** [comment]
Thanks Dan.
