### ISSUE TITLE
StringPeepholes optimization is disabled on Java 11 in a trivial test

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#11960]
While working on @dchopra001 with a test case for #11832 we discovered that the following simple test case will employ the use of StringPeepholes in Java 8 but no in Java 11, even though the trees look identical:

```
class Test {
	public static void main(String[] args) {
		System.out.println(foo("abcd"));
		System.out.println(foo("abcd"));
	}

	public static String foo(String s) {
		return new StringBuilder().append(s).append('\u205e').toString();
	}
}
```

```
java '-Xjit:{Test.foo*}(count=1,traceFull,log=log.trace,traceStringPeepholes),disableAsyncCompilation' Test
```

Taking a look at the code the issue seems to be here:
https://github.com/eclipse/openj9/blob/9530f964a5f4a1a95a0e5147a462af8e9b987a29/runtime/compiler/optimizer/StringPeepholes.cpp#L2036-L2038

It seems to be the case that on Java 11 the StringBuffer class is not loaded at all for this simple program (where as on Java 8 it is), i.e. it probably never got used in the JCL at any point in Java 11. My bet is that OpenJDK removed such uses. This can be verified via `java -verbose:class -version`. As such because this class is never loaded we think someone has redefined it and we give up on any StringBuilder/StringBuffer peepholes. This is likely a source of performance loss between Java 8 vs Java 11.

I'm not sure why this code returns `true` if the class is `NULL`. Surely if this class is `NULL` it is not redefined?
https://github.com/eclipse/openj9/blob/9530f964a5f4a1a95a0e5147a462af8e9b987a29/runtime/compiler/optimizer/StringPeepholes.cpp#L2051-L2057

**Comment by fjeremic** [comment]
@0xdaryl @vijaysun-omr a source of regression between Java 11 and Java 8. Thoughts on changing the above to `return false`?

**Comment by vijaysun-omr** [comment]
I agree with returning false in this case; probably the original thinking around that case was that it could never happen but I agree that there is no point worrying about redefinition if the class is not loaded.

**Comment by pwagland** [comment]
Thanks for this fix, this might well explain why I was not able to create a simple test case for #11832, even though I could do so easily enough in the product. I know that we still have references to `StringBuffer` in our code, whereas my test would not have had this.
