### ISSUE TITLE
AArch64: Support mixed refs

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#11977]
Need to support mixed refs.

**Comment by knn-k** [comment]
Related changes for Power:  #8944

**Comment by pshipton** [comment]
We were hoping to enable mixedrefs by default across all versions and platforms, today in fact. Finding this is a surprise and blocks the change. If it can be addressed quickly it would be appreciated so the move to mixedrefs can proceed. Otherwise, getting some estimate of when it could be completed would be useful. For now I've set it as a blocker against the 0.25 release, as we had intended to move to mixedrefs for this release.

@gacholio tagging you since you authored at least one related PR https://github.com/eclipse/openj9/pull/8944

**Comment by 0xdaryl** [comment]
Many parts of the AArch64 runtime were derived from Power, so any changes required won't be too far from it.  I'd say it is still possible to get this done for 0.25.  We'll work on it over the next day or so, targeting EOW.  We have to be thorough though and sweep through the code to be sure we catch all the right places.

**Comment by knn-k** [comment]
@pshipton
I only see #11963 and #11965 with AArch64 mixed refs in the issue list.
Are there any other tests you run for `-Xnocompressedrefs` with mixedrefs builds?

**Comment by knn-k** [comment]
Related issue: #10266
You cannot build mixed refs binary in cross-build environments because CMake is disabled.

**Comment by Akira1Saitoh** [comment]
Opened https://github.com/eclipse/openj9/pull/11987

**Comment by pshipton** [comment]
You can see the whole tes at hyc-runtimes job/Test_openjdk11_j9_sanity.functional_aarch64_linux_mixed/7. I don't see anything else running besides the openjdk tests, but these are passing. I think once the sanity.functional tests are in good shape we can see about running additional test suites. @AdamBrousseau

**Comment by pshipton** [comment]
Note you can run an internal personal build using `aarch64_linux_mixed` as the platform, and include any test suites you want from the list: sanity.functional,extended.functional,sanity.system,extended.system,special.system (and sanity.openjdk but this passes).

**Comment by pshipton** [comment]
You can also specify those tests in a PR build. Seems we still only have the one aarch64 machine internally, so the ability to run testing is limited. At some point more machines will be available, but not sure when.

**Comment by knn-k** [comment]
I am running "jenkins test extended alinux64mxd jdk11" in #11987 now.

**Comment by gacholio** [comment]
While you're at it, the following dead code can be removed:

https://github.com/eclipse/openj9/blob/8d60d1d114d82a672c10607d05a0dce1768ff4e1/runtime/compiler/arm/codegen/J9ARMEvaluator.cpp#L122-L126

**Comment by knn-k** [comment]
@gacholio I opened PR #12007 for removing the `OMR_GC_COMPRESSED_POINTERS` code in ARM32 JIT.
