### ISSUE TITLE
functional tests failing to compile jdk11+

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12027]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_mixed_Nightly_testList_0/27
```
23:37:15      [javac] /home/****/****-agent/workspace/Test_openjdk11_j9_sanity.functional_ppc64le_linux_mixed_Nightly_testList_0/openjdk-tests/functional/Java8andUp/src_110_up/org/openj9/test/java/lang/Test_Class.java:449: error: cannot find symbol
23:37:15      [javac] 			if (IdentityInterface.class != anInterface) {
23:37:15      [javac] 			    ^
23:37:15      [javac]   symbol:   class IdentityInterface
23:37:15      [javac]   location: class Test_Class
```
Due to https://github.com/eclipse/openj9/pull/10282

@tajila @OussamaSaoudi

**Comment by tajila** [comment]
@OussamaSaoudi Can you change that check to something like `if (anInterface.getName().equals(...IdentityInterfact) {`. The `IdentityInterface.class` is only going to exist on valhalla builds.
