### ISSUE TITLE
Jenkins job to delete obsolete jenkins jobs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12057]
To keep a handle on the number of jenkins jobs, and reduce disk space usage on master (i.e. https://bugs.eclipse.org/bugs/show_bug.cgi?id=571470), we need to create a jenkins job that can delete obsolete jenkins jobs based on a pattern. There are hundreds of jobs per version, and we also introduce special jobs for OMH, mixed, cm, uma, xl, etc, which become obsolete. Trying to delete all the jobs manually is very painful. The delete job needs to take a pattern to control what is deleted so we can customize it as needed. It would be useful to have two modes, 1) list all the jobs that match the pattern, for confirmation the pattern will delete the correct things 2) delete them.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin fyi

**Comment by AdamBrousseau** [comment]
We have a similar job for Artifactory as you know.
https://ci.eclipse.org/openj9/view/Infrastructure/job/Cleanup_Artifactory_JDK_Version/
I think this should be a separate job but we could maybe look at improving that one while we're at it. 

Although, this will probably be easy to do with some pipeline groovy so maybe won't help with the Art cleanup.

**Comment by pshipton** [comment]
The artifactory cleaning job needs to be reworked. As it stands it takes to long, days or weeks, and can fail before finishing.

**Comment by AdamBrousseau** [comment]
I have a job for this (internally) but it runs on master and does a simple find and rm (Cleanup-JDK-Version-Master). This won't work for the OpenJ9 instance as we don't have a master executor.

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/view/Infrastructure/job/Cleanup-JDK-Version
Has "print only" and "print & rm" options but at the moment it only pretends to clean. Need script approvals to run.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=553778

**Comment by AdamBrousseau** [comment]
Complete. Pete already did 15 by hand so nothing to cleanup at this point.
