### ISSUE TITLE
[linux_ppc-64] SE80_GIT testDDRExtJunit_FindExtThread_0 - tck_ddrext.xml:115: Timeout: killed the sub-process

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12076]
Failure link
------------

From an internal build `461685`:
```
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxp6480sr7-20201201_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64-64-Bit Compressed References 20201212_461685 (JIT enabled, AOT enabled)
OpenJ9   - fb88b42
OMR      - dac2f6b
IBM      - 2edc62a)
JCL - 20201126_01 based on Oracle jdk8u281-b05
```
The test name is ` [linux_ppc-64] SE80_GIT testDDRExtJunit_FindExtThread_0` (or `job_output.php?id=664964831`).
Note: this failure was marked by another PT.

Optional info
-------------

- intermittent failure (yes): 19/50 failure rate as per the test history.

Failure output (captured from console output)
---------------------------------------------
```
     [java] [AutoRun] [INFO] Finished testFindvm(j9vm.test.ddrext.junit.TestFindExt)
     [java] 
     [java] [AutoRun] [INFO] Starting testFindpattern(j9vm.test.ddrext.junit.TestFindExt)

BUILD FAILED
/bluebird/builds/bld_461685/jvmtest/test/SE80/functional/DDR_Test/tck_ddrext.xml:115: Timeout: killed the sub-process

Total time: 20 minutes 16 seconds
Running compression command: jar cvf /tmp/results-6649648310.jar .
Compression was successful.Attempting to upload compressed file.Upload appears to have been successful.
testDDRExtJunit_FindExtThread_0_FAILED
```

**Comment by pshipton** [comment]
Guessing a test issue @llxia @keithc-ca fyi

**Comment by keithc-ca** [comment]
Looking at the test, I note this [comment](url):
```
	// searching pattern on AIX core dump is very slow
```
The first part of the test looks for 0x000000b1 while the second part looks for "b1"; finding first doesn't guarantee the second will be found, so it may involve a very lengthy search that could potentially time out.
