### ISSUE TITLE
MBCS_Tests_StAX_ja_JP_linux_0_FAILED - Can't locate Test/Simple.pm in @INC (@INC

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12084]
Failure link
------------

From an internal build `Test_openjdk16_j9_special.functional_s390x_linux/1`
```
02:07:06  openjdk version "16" 2021-03-16
02:07:06  OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
02:07:06  Eclipse OpenJ9 VM AdoptOpenJDK (build master-f021812fb, JRE 16 Linux s390x-64-Bit Compressed References 20210226_40 (JIT enabled, AOT enabled)
02:07:06  OpenJ9   - f021812fb
02:07:06  OMR      - eb4f5a875
02:07:06  JCL      - 503f3ea1b9 based on jdk-16+36)
```
rebuild the failed tests in one link:
02:56:28  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=functional&PLATFORM=s390x_linux_mixed&TARGET=testList%20TESTLIST=MBCS_Tests_StAX_ja_JP_linux_0,MBCS_Tests_StAX_ko_KR_linux_0,MBCS_Tests_StAX_zh_CN_linux_0,MBCS_Tests_StAX_zh_TW_linux_0,MBCS_Tests_coin_ja_JP_linux_0,MBCS_Tests_coin_ko_KR_linux_0,MBCS_Tests_coin_zh_CN_linux_0,MBCS_Tests_coin_zh_TW_linux_0,MBCS_Tests_i18n_ja_JP_linux_0,MBCS_Tests_i18n_ko_KR_linux_0,MBCS_Tests_i18n_zh_CN_linux_0,MBCS_Tests_i18n_zh_TW_linux_0,MBCS_Tests_locale_matching_ja_JP_linux_0,MBCS_Tests_locale_matching_ko_KR_linux_0,MBCS_Tests_locale_matching_zh_CN_linux_0,MBCS_Tests_locale_matching_zh_TW_linux_0,MBCS_Tests_pref_ja_JP_linux_0,MBCS_Tests_pref_ko_KR_linux_0,MBCS_Tests_pref_zh_CN_linux_0,MBCS_Tests_pref_zh_TW_linux_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test MBCS_Tests_StAX_ja_JP_linux_0 ...
===============================================
MBCS_Tests_StAX_ja_JP_linux_0 Start Time: Fri Feb 26 23:51:30 2021 Epoch Time (ms): 1614412290519
variation: NoOptions
JVM_OPTIONS:  
Can't locate Test/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/jenkins/workspace/Test_openjdk16_j9_special.functional_s390x_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/StAX/resultCheck.pl line 16.
BEGIN failed--compilation aborted at /home/jenkins/workspace/Test_openjdk16_j9_special.functional_s390x_linux/openjdk-tests/TKG/../../jvmtest/functional/MBCS_Tests/StAX/resultCheck.pl line 16.

MBCS_Tests_StAX_ja_JP_linux_0_FAILED
```

This appears a test setup issue.

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
The test passed at Adopt: https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_special.functional_s390x_linux/9/tapResults/

**Comment by smlambert** [comment]
Am presuming its a machine setup issue, check what version of perl is installed on the machine where the test fails.  On external machines, I believe the Perl module (https://metacpan.org/pod/Test::Simple) is automatically present (based on machines being configured using Ansible playbooks), seems not to be the case on the machine where this test failed.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau fyi

**Comment by JasonFengJ9** [comment]
Created an internal issue - `infrastructure/issues/5115`.
