### ISSUE TITLE
Parallel machine limits

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12088]
Can we add a way to override the parallel machine limits in specific jenkins jobs?

The parallel machine limit is currently 3/4 of the available machine. What happens on Windows externally is there are 6 machines but quite often 1 of the machines goes offline at the start of a weekend, only leaving 5 machines available for testing. The 3/4 math compute 3.75 machines which is rounded down to 3. Although there may be free machines, the special.system testing often times out since only 3 machines are being used.

The special.system testing runs on the weekend can be the only testing running.
@llxia

**Comment by llxia** [comment]
Instead of introducing a parameter to override the default parallel machine limit and maintaining the parameter, should we just set the limit to the total number of machines `nodesByLabel(LABEL).size()`?
FYI @smlambert

**Comment by smlambert** [comment]
re: https://github.com/eclipse/openj9/issues/12088#issuecomment-789013315 - yes that was my thought and preference.  It does mean that someone running a grinder could pooch the farm, but we can't protect that from that happening in other ways fully anyway.
