### ISSUE TITLE
xlc link error: unresolved OMR::SymbolReferenceTable::UNKNOWN

### ISSUE THREAD

**Issue by liqunl** [eclipse/openj9#12138]
This issue is to track a c++ compiler issue I have encountered and that I have to workaround it due to other work I have. We'd like to create a minimum reproducible test and forward it to xlc team to look at.

In #11634, the original change caused a xlc link error
```
ld: 0711-317 ERROR: Undefined symbol: OMR::KnownObjectTable::UNKNOWN
ld: 0711-344 See the loadmap file lmap for more information.
```
[lmap.txt](https://github.com/eclipse/openj9/files/6093109/lmap.txt)

With some experiment, the following code will cause the same xlc link error
```
uint32_t num = 10;
std::vector<TR::KnownObjectTable::Index> object(num, TR::KnownObjectTable::UNKNOWN);
```

If I change `uint32_t` to `int32_t`, the link error disappears. Another way to workaround the error is not pass the default value in constructor, but initialize the vector to `TR::KnownObjectTable::UNKNOWN` separately in a loop right after the object construction.

The code looks fine and it works fine on other platforms (linux, windows, mac), but doesn't work on aix and zos where xlc is used.

**Comment by 0xdaryl** [comment]
I'm not sure this issue is relevant anymore.  Should it be closed?

**Comment by liqunl** [comment]
Yes, the failure is due to c++ one-definition-rule. The static field UNKNOWN doesn't have a definition outside of the class, the link error doesn't happen with some compiler flags, and it can be worked around by statically casting the value to int.

Closing the issue.
