### ISSUE TITLE
AArch64: Enable idle GC tuning

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#12143]
Investigate and enable idle GC tuning on AArch64.

https://github.com/eclipse/openj9/blob/b227feba29b0b191867789756a14b1f1ab061b71/runtime/vm/jvminit.c#L2230

**Comment by 0xdaryl** [comment]
@amicic : I would appreciate your opinion on enabling this for AArch64 please.

**Comment by amicic** [comment]
I see no reason to restrict any h/w arch. 

Maybe some o/s, that does not support eager memory de-commit, but h/w is rather transparent. 

@mpirvu ?

**Comment by mpirvu** [comment]
If the OS is able to release the memory I see no reason to exclude AArch64.
Under Linux we use `madvise(void *addr, size_t length, MADV_DONTNEED);` to tell OS to take the given region out of the RSS. What OS is used for AArch64? If madvise is not available, we need to investigate similar OS calls.

**Comment by 0xdaryl** [comment]
Thanks.  AArch64 uses Linux at the moment and we'll have to verify the behaviour of `madvise` before enabling.  macOS is also in the cards for AArch64 later this year likely.

**Comment by knn-k** [comment]
I opened #12215 for this.
