### ISSUE TITLE
Enable requesting PR builds with dependent changes (Jenkins)

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#122]
Related #91 #11 #24
#### Background
By default, a PR build will pull the openj9 branches of the openj9-openjdk-jdk9 and the openj9-omr repos. Sometimes developers have changes in openj9 that depend on changes they are working on in one or both of the other repos. We therefore need a process to request PR builds which can checkout the PR(s) of the other repo(s).

- A dependent change must be at eclipse/omr, eclipse/openj9-omr or ibmruntimes/openj9-openjdk-jdk9
- A PR with the dependent change must be open at the appropriate repo
- A committer must be able to request an openj9 PR build with dependent changes by supplying the namespace, repo and PR number in the trigger phrase.

##### Default
`Jenkins test sanity`
##### Dependent change at OMR
`Jenkins test sanity depends eclipse/omr#<PR#>`
##### Dependent change at OpenJDK
`Jenkins test sanity depends ibmruntimes/openj9-openjdk-jdk9#<PR#>`
##### Dependent change at OMR and OpenJDK
`Jenkins test sanity depends eclipse/omr#<PR#> ibmruntimes/openj9-openjdk-jdk9#<PR#>`

The reason/benefit of supplying the org/repo#PR is that Github will automatically generate a link to the dependent PR in the comment.

**Comment by AdamBrousseau** [comment]
Logic added to PR builds. Please report any issues here, otherwise I will close this issue once a few builds have proven the changes.

**Comment by mstoodle** [comment]
Just want to verify (since there isn't an explicit example) that you can also specify eclipse/openj9-omr ?

**Comment by AdamBrousseau** [comment]
@mstoodle yes you can specify openj9-omr. Hopefully we never need to though :)
Ex. `Jenkins test sanity depends eclipse/openj9-omr#123`
