### ISSUE TITLE
JDK11 promote job failing, ERROR: Must supply COMMIT param

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#12201]
https://ci.eclipse.org/openj9/job/Promote_OpenJDK/317/console
https://ci.eclipse.org/openj9/job/Promote_OpenJDK/317/rebuild/parameterized
```
ERROR: Must supply COMMIT param
```

The last one worked https://ci.eclipse.org/openj9/job/Promote_OpenJDK/311/console
and jdknext worked this morning https://ci.eclipse.org/openj9/job/Promote_OpenJDK/314/console

@jdekonin @AdamBrousseau 
I'll promote this one manually.

**Comment by AdamBrousseau** [comment]
From the upstream job
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK11-Acceptance/108/console
```
05:49:12.996  SDK_VERSION:11
[Pipeline] echo
05:49:13.000  REPO:https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
[Pipeline] echo
05:49:13.003  COMMIT:
```
https://github.com/eclipse/openj9/blob/13936a4d3a86c1330b7c34cb82106a72c205a3bd/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All.groovy#L482

Further up
```
00:00:37.038  + git ls-remote https://github.com/ibmruntimes/openj9-openjdk-jdk11.git refs/heads/openj9-staging
00:00:37.039  + cut -c1-40
00:01:04.561  fatal: unable to access 'https://github.com/ibmruntimes/openj9-openjdk-jdk11.git/': Could not resolve host: github.com
[Pipeline] echo
00:01:04.910  OPENJDK11_SHA: - openj9-openjdk-jdk11
```
vs previous buld
```
00:00:11.516  + git ls-remote https://github.com/ibmruntimes/openj9-openjdk-jdk11.git refs/heads/openj9-staging
00:00:11.517  + cut -c1-40
[Pipeline] echo
00:00:12.122  OPENJDK11_SHA:83787478bbce6e6c08657ba266610123557914c4 - openj9-openjdk-jdk11
```
Looks like the SHA sniff failed. Likely a 1-off. We should probably retry on the sniff and fail if it fails.

**Comment by pshipton** [comment]
Closing since it didn't reoccur.
