### ISSUE TITLE
jdk16+36: java/lang/ProcessBuilder/Basic.java fails due to no OOM condition

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#12216]
Issue https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2024 highlights a failure for jdk-16+36 on certain machines that have large memory, where the testcase java/lang/ProcessBuilder/Basic.java fails to OOM. The scenario is specific to a Hotspot issue (https://bugs.openjdk.java.net/browse/JDK-6850957). So maybe not relevant to j9? the code is already patched, maybe it needs disabling for j9?
See: https://github.com/ibmruntimes/openj9-openjdk-jdk16/blob/3ca051dd4467c4b024565e3c71d00b854c1e75d7/test/jdk/java/lang/ProcessBuilder/Basic.java#L1822

**Comment by pshipton** [comment]
Maybe we can modify the test to set -Xmx or -XX:MaxRAMPercentage. The default -Xmx is 25% of the physical memory. How much memory do the failing machines have? How much memory does a passing machine have?

**Comment by andrew-m-leonard** [comment]
Failing machine has 65Gb of RAM
Passing machine has 32Gb of RAM.

**Comment by pshipton** [comment]
The fixes will also go into the 0.26.0 branches before Milestone 2. I'll go ahead and close this now.
