### ISSUE TITLE
sanity.system ExplMod fails due to unexpected java.lang.IllegalAccessError message text

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9#12315]
openj9's `java.lang.IllegalAccessError`  message text differs from hotpot's, and that causes the ExplMod system test (currently excluded) to fail.

The test was presumably calibrated against hotspot, and while the text which accompanies an exception is up to the implementor to specify I assume openj9 would like to consider whether to make changes to its message before requesting that the test case be changed.

This is the openj9 exception message thrown when running the test:
```
java.lang.IllegalAccessError: Class net/adoptopenjdk/test/modularity/junit/TestImpliedReadability(module com.test) can not access class org/hamcrest/CoreMatchers(module hamcrest.core) because module module com.test does not read module module hamcrest.core
```

It is the duplication of the word `module` (as in `module module hamcrest.core`) which causes the test to fail,

I notice the openj9 message also includes slashes rather than dots in the referenced class name.

See https://github.com/adoptium/aqa-systemtest/issues/200 for more details.

**Comment by pshipton** [comment]
@tajila fyi
