### ISSUE TITLE
FILIPINO LOCALIZATION

### ISSUE THREAD

**Issue by cordeta** [eclipse/openj9#1236]
To help you reach my fellow Filipino Comrades , i would like to offer Translation of your files in Filipino . A staging Repo of Translation/tl_PH would be fine :) 

Cheers !

**Comment by pshipton** [comment]
Thanks for the offer @cordeta. I'm not sure what you are suggesting by "A staging Repo of Translation/tl_PH".

All the translated files are found in https://github.com/eclipse/openj9/tree/master/runtime/nls. You can open Pull Requests with Filipino translations of these files.

**Comment by cordeta** [comment]
Thank you sir , i'll carefully read all the guidelines and intructions later .

**Comment by smlambert** [comment]
I believe AdoptOpenJDK uses a translation tool and then has volunteers/contributors verify the translations to ensure they sound/read correctly.  https://github.com/AdoptOpenJDK/openjdk-website/issues?utf8=%E2%9C%93&q=is%3Aissue+translation+

issue 79 talks about them using Google translate

**Comment by pshipton** [comment]
So basically, committers can pass any translations through Google translate and see what comes out in their native language before committing.

**Comment by smlambert** [comment]
Seems like a reasonable way forward, that way we benefit from the generous offers of translations, but have some approach to verifying the changes.

**Comment by DanHeidinga** [comment]
Closing as this has gone stale
