### ISSUE TITLE
JITServer crashes in signal handler due to uninitialized JIT helpers

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#12374]
When JITServer crashes or user sends it a `SIGQUIT` signal, it's supposed to print a diagnostic info and create a core file, javacore, snap and jitdump. Currently though, while trying to produce the diagnostics, we crash in the signal handler.

The point of the crash on x86-64:
https://github.com/eclipse/openj9/blob/25c1f42ca732d0e23f5fc1b5292275e9bde291d8/runtime/compiler/runtime/SignalHandler.c#L1763
This happens because `jitGetExceptionTableFromPC` is NULL, since we disabled JIT helpers and hooks on JITServer in #9233.

**Comment by dmitry-ten** [comment]
The easiest fix would be to remove the guard that prevents helpers and hooks from being initialized on JITServer:
https://github.com/eclipse/openj9/blob/25c1f42ca732d0e23f5fc1b5292275e9bde291d8/runtime/compiler/runtime/codertinit.cpp#L464-L489

A more complicated one would be to identify which functions are actually used and initialize just them, but that presents risks of not identifying all of them and ending up in a situation that led to this bug in the first place.

@mpirvu what are your thoughts on this?

**Comment by mpirvu** [comment]
The hooks were disabled at the server to avoid potential mistakes: Java code should not run at the server. If there is a use case for them we can re-instantiate them. Let's put back just the helpers and see if this addresses our issue.
