### ISSUE TITLE
OJDK MH: IllegalStateException: uninitialized call site

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#12404]
### Error

`IllegalStateException` is thrown for `MutableCallSite` when OJDK MHs are enabled in OpenJ9.

**Java16 doc** for `MutableCallSite`: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/invoke/MutableCallSite.html

```
Exception in thread "main" java.lang.IllegalStateException: uninitialized call site
	at java.base/java.lang.invoke.CallSite.uninitializedCallSite(CallSite.java:261)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000000000000.invokeStatic(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000000000000.invokeExact_MT(LambdaForm$MH)
	at MethodHandleTest.main(MethodHandleTest.java:)
```

### Micro-test

```
import static java.lang.invoke.MethodHandles.*;
import static java.lang.invoke.MethodType.*;
import java.lang.invoke.*;

public class MethodHandleTest {
        public static void main(String[] args) throws Throwable {
                MethodType methodType = MethodType.methodType(String.class);
                MutableCallSite mutableCallSite = new MutableCallSite(methodType);

                MethodHandle methodHandle = mutableCallSite.dynamicInvoker();
                Lookup lkup = MethodHandles.publicLookup();
                MethodHandle mhLowerCase = lkup.findVirtual(String.class, "toLowerCase", methodType);

                MethodHandle convertToLowerCase = MethodHandles.filterReturnValue(methodHandle, mhLowerCase);

                mutableCallSite.setTarget(MethodHandles.constant(String.class, "TestString"));
                String lowerCaseStr = (String)convertToLowerCase.invokeExact(); // IllegalStateException thrown from here
                if (lowerCaseStr.equals("teststring")) {
                        System.out.println("pass: " + lowerCaseStr);
                } else {
                        System.out.println("fail: " + lowerCaseStr);
                }
        }
}
```

### Steps to build an OpenJ9 JDK with OJDK MHs enabled

Refer to #11458.

**Comment by babsingh** [comment]
fyi @fengxue-IS @tajila

**Comment by DanHeidinga** [comment]
Does this fail even with https://github.com/eclipse/openj9/pull/12199 merged?

Also, does it fail if there's an `MCS.syncAll(new MCS[] {mutableCallSite})` call after the `setTarget`?

**Comment by babsingh** [comment]
> Does this fail even with #12199 merged?

Yes, it fails.

> Also, does it fail if there's an MCS.syncAll(new MCS[] {mutableCallSite}) call after the setTarget?

Yes, it fails.

When the `MutableCallSite` is created, the MCS constructor initializes `MCS.setTarget` to a MH which throws the `IllegalStateException: uninitialized call site`.

`MCS.setTarget` invokes `CS.setTargetNormal -> MHN.setCallSiteTargetNormal -> setCallSiteTargetImpl`, which doesn't update `MCS.target`. `MCS.target` still points to the MH which throws the `IllegalStateException`.

https://github.com/eclipse/openj9/blob/9a9df50b9ed26605e5d4583a7fbf2290ebd69eb9/runtime/jcl/common/java_lang_invoke_MethodHandleNatives.cpp#L470-L494

**Comment by DanHeidinga** [comment]
It's missing the addition of the header size to the offset.  Try something like:
```
	UDATA const objectHeaderSize = J9VMTHREAD_OBJECT_HEADER_SIZE(_currentThread);
	offset += objectHeaderSize;
```

**Comment by babsingh** [comment]
The suggestion in https://github.com/eclipse/openj9/issues/12404#issuecomment-817049735 fixes the problem. Thus, created https://github.com/eclipse/openj9/pull/12407 to merge the suggested fix.
