### ISSUE TITLE
AttachAPI does not initialize on Windows #194

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#1255]
"C:/temp/bld_379365/jdk/bin\java" -Xcompressedrefs 
--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED 
-cp "C:/temp/bld_379365/openj9/test///..//jvmtest\TestConfig\resources;C:/temp/bld_379365/openj9/test///..//jvmtest\TestConfig\lib\testng.jar;C:/temp/bld_379365/openj9/test///..//jvmtest\TestConfig\lib\jcommander.jar;C:/temp/bld_379365/openj9/test///..//jvmtest\Java8andUp\GeneralTest.jar" 
-Djava.sidecar="--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED" 
-Dcom.ibm.tools.attach.enable=yes 
-Dcom.ibm.tools.attach.timeout=15000 
org.testng.TestNG -d "C:/temp/bld_379365/openj9/test/\TestConfig\test_output_15193636742546\TestAttachAPI_SE90_0" "C:/temp/bld_379365/openj9/test///..//jvmtest\Java8andUp\testng.xml" -testnames TestAttachAPI 
-groups level.extended 
-excludegroups d..win_x86-64_cmprssptrs,d..arch.x86,d..os.win,d..bits.64,d.*.generic-all; 
if [ $? -eq 0 ] ; then echo "TestAttachAPI_SE90_0""_PASSED"; else echo "TestAttachAPI_SE90_0""_FAILED"; fi; } 2>&1 | tee -a "C:/temp/bld_379365/openj9/test/\TestConfig\test_output_15193636742546\TestTargetResult"
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is C:/temp/bld_379365/openj9/test///..//jvmtest\TestConfig\resources\excludes\latest_exclude_SE90.txt
...
... TestNG 6.10 by C�dric Beust (cedric@beust.com)
...

[IncludeExcludeTestAnnotationTransformer] [INFO] disable method is test_agntld01diabled annotation [level.extended, disabled.generic-all]
[IncludeExcludeTestAnnotationTransformer] [INFO] disable method is test_agntld02diabled annotation [level.extended, disabled.generic-all]
[IncludeExcludeTestAnnotationTransformer] [INFO] disable method is test_agntld03diabled annotation [level.extended, disabled.generic-all]
[TestNG] Running:
C:\temp\bld_379365\openj9\jvmtest\Java8andUp\testng.xml

FAILED CONFIGURATION: @beforemethod setUp(public void org.openj9.test.attachAPI.TestAttachAPI.testDeleteTargetDirectory())
java.lang.AssertionError: main process did not initialize attach API, PID = 13504
at org.testng.Assert.fail(Assert.java:94)
at org.openj9.test.attachAPI.TestAttachAPI.setUp(TestAttachAPI.java:88)

**Comment by llxia** [comment]
Test passed on windows without cygwin, but failed on windows with cygwin.
It looks like the test need to be updated to support cygwin env.

**Comment by pdbain-ibm** [comment]
This was probably a machine issue.  Please open a new issue if the problem recurs.
