### ISSUE TITLE
DTFJ error handling

### ISSUE THREAD

**Issue by georgejxu** [eclipse/openj9#12562]
I might have a corrupted core. and run into the following exception

java.lang.IndexOutOfBoundsException: Index: -91793, Size: 26819820
	at org.eclipse.mat.parser.index.IndexWriter$Identifier.get(IndexWriter.java:124)
	at org.eclipse.mat.dtfj.DTFJIndexBuilder.addThreadRefs(DTFJIndexBuilder.java:6211

MAT just blows up.   I made the following change, and I was able to open the core and get the information I needed.  Suggest to include the following change in future DTFJ release.

        try { //GXU
	        addThreadRefs(objId, aa);
	        addRefs(refd, objId, aa);
	        outRefs.log(indexToAddress, objId, aa);
        } catch (Exception e) {
            listener.sendUserMessage(Severity.WARNING, MessageFormat.format(
                    Messages.DTFJIndexBuilder_ProblemCheckingOutboundReferences, format(objId)), e);        	
        }

in processHeapObject of DTFJIndexBuilder.java

**Comment by pshipton** [comment]
@georgejxu this is the wrong project. The org.eclipse.mat classes are not part of OpenJ9. See https://projects.eclipse.org/projects/tools.mat
