### ISSUE TITLE
[Minor] Incorrect comment on exitCriticalRegion()

### ISSUE THREAD

**Issue by rednaxelafx** [eclipse/openj9#1257]
Minor comment nitpick: on https://github.com/eclipse/openj9/blob/d351c880874f614b582cfbf9e81f8a26a08e586f/runtime/gc_glue_java/JNICriticalRegion.hpp#L114, it currently reads:
```
Exit a JNI critical region (i.e. GetPrimitiveArrayCritical or GetStringCritical).
```
but it should be `ReleasePrimitiveArrayCritical` and `ReleaseStringCritical` instead.

**Comment by dmitripivkine** [comment]
Yes, thank you. This is typical copy/paste problem
