### ISSUE TITLE
[Adopt] Incorrect VM classes in src.zip for OpenJDK+OpenJ9 builds

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1264]
Mirroring Adopt issue )https://github.com/AdoptOpenJDK/openjdk-build/issues/227) here:

------

I was just playing around with this build:
```
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-jenkins_2018_02_22_15_07-b00)
Eclipse OpenJ9 VM (build openj9-0.0M1, JRE 1.8.0 Linux amd64-64 Compressed References 20180222_85 (JIT enabled, AOT enabled)
OpenJ9   - 453326f7
OMR      - 1f7d88e0
JCL      - ce606dfd1f based on jdk8u162-b12)
```
and I noticed the source code provided in src.zip for classes such as `java/lang/System` and `java/lang/Object` doesn't match the binaries.

It looks like src.zip contains the OpenJDK versions of these classes instead of the OpenJ9 versions.

I verified with Xtrace that the binary is definitely using OpenJ9's version of `java/lang/System`:
```
> java "-Xtrace:print=mt,methods=java/lang/System.completeInitialization" -version
16:19:20.221*0x1809200              mt.3        > java/lang/System.completeInitialization()V bytecode static method
16:19:20.224 0x1809200              mt.9        < java/lang/System.completeInitialization()V bytecode static method
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-jenkins_2018_02_22_15_07-b00)
Eclipse OpenJ9 VM (build openj9-0.0M1, JRE 1.8.0 Linux amd64-64 Compressed References 20180222_85 (JIT enabled, AOT enabled)
OpenJ9   - 453326f7
OMR      - 1f7d88e0
JCL      - ce606dfd1f based on jdk8u162-b12)
```
(The OpenJDK System class doesn't contain the completeInitialization() method.)

**Comment by DanHeidinga** [comment]
@JasonFengJ9 @jdekonin Can you help out with this?  We should aim to fix this ASAP for the 0.8 release.

**Comment by JasonFengJ9** [comment]
Sure, looking at it.

**Comment by JasonFengJ9** [comment]
This is a problem with `OpenJ9 Java 8` builds but not `OpenJ9 Java 9`.
Probably something in `Java 9` extension repo wasn't ported to `Java 8` extension properly.

**Comment by JasonFengJ9** [comment]
`OpenJ9 Java 8` seems have different approach than `OpenJ9 Java9` for compilation and `src.zip` creation. 
@andrew-m-leonard do you have any insights?

**Comment by andrew-m-leonard** [comment]
JDK8 is a very different built beast to JDK9! so not entirely surprises... i'll investigate

**Comment by andrew-m-leonard** [comment]
Fixed in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/50

**Comment by pshipton** [comment]
Thanks for the fast action @andrew-m-leonard
