### ISSUE TITLE
Changes to Unsafe.java have regressed JDK10 & JDK11 builds

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#1266]
It seems the J9 jcl now has a new version of jdk/internal/misc/Unsafe.java which is unfortunately not compatible on JDK10, with the following build errors:
=== Output from failing command(s) repeated here ===
* For target jdk_modules_java.base__the.java.base_batch:
/home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java:3310: error: method objectFieldOffset in class Unsafe cannot be applied to given types;
                = U.objectFieldOffset(TreeBin.class, "lockState");
                   ^
  required: Field
  found: Class<TreeBin>,String
  reason: actual and formal argument lists differ in length
/home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java:6376: error: method objectFieldOffset in class Unsafe cannot be applied to given types;
        SIZECTL = U.objectFieldOffset
                   ^
  required: Field
  found: Class<ConcurrentHashMap>,String
  reason: actual and formal argument lists differ in length
   ... (rest of output omitted)

* All command lines available in /home/admin/mydocker/ccm/openj9-openjdk/openj9-openjdk/build/linux-x86_64-normal-server-release/make-support/failure-logs.
=== End of repeated output ===

See build log: https://hyc-rt-openjdk-jenkins.swg-devops.com/job/build_ibmsdk/266/console

**Comment by andrew-m-leonard** [comment]
@DanHeidinga Same problem in JDK11 as well:
https://hyc-rt-openjdk-jenkins.swg-devops.com/job/build_ibmsdk/267/console

**Comment by DanHeidinga** [comment]
@theresa-m Can you look at this?

**Comment by DanHeidinga** [comment]
I suspect we're missing the `objectFieldOffset(Class, String)` implementation

**Comment by theresa-m** [comment]
Yes. Looking into this.
