### ISSUE TITLE
ConstantDynamic: Classfile parsing

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1270]
Detecting Condy CP entries will be almost identical to what is done with Indy CP entries. Changes will be required in cfreader.c (look at CFR_CONSTANT_InvokeDynamic for guidance).

**Comment by DanHeidinga** [comment]
@fengxue-IS Can you take a look at this?  Its the first stage in supporting JDK 11's ConstantDynamic.

**Comment by fengxue-IS** [comment]
sure, I ll look into how this can be implemented
