### ISSUE TITLE
ConstantDynamic: Add support for balanced GC policy

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1273]
Update the `GC_ConstantPoolObjectSlotIterator::nextSlot()` method to recognize Constant dynamic CP entries

**Comment by dmitripivkine** [comment]
I guess this item would be empty as far as Balanced does CP scan already. So probably changes (if any) will be required on level of CP Iterator

**Comment by tajila** [comment]
@dmitripivkine Does balanced scan in all cases?

If we added a bit to the Class object or J9Class saying there were no non-tenured objects in the constantpool would it still have to scan?

> will be required on level of CP Iterator
Is the CP Iterator common for all policies?

We are introducing two new CP types, the iterator(s) will have to know about them

**Comment by dmitripivkine** [comment]
Yes, Balanced does scan CP in all cases. I believe keep this item for now. We will double check after implementation.
I believe CP Iterator is common for all GC policies

**Comment by dmitripivkine** [comment]
Actually there are two iterators related to CP walk:
- GC_ConstantPoolObjectSlotIterator iterates heap objects in CP
- GC_ConstantPoolClassSlotIterator iterates classes in CP
