### ISSUE TITLE
ConstantDynamic: Adding sun_relfect_ConstantPool native

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1276]
A new native will have to be added to `sun_reflec_ConstantPool`. This native will be implemented similar to `getCPMethodHandleAt`. It will search the ramConstantPool first to see if there is a cached copy, if not it will call the resolve helper to resolve the cp entry.

**Comment by DanHeidinga** [comment]
Depends on https://github.com/eclipse/openj9/issues/1272
