### ISSUE TITLE
ConstantDynamic: Adding jithelper to resolve Constant dynamic entries

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1277]
A new helper will have to be added to `cnathelp.cpp` to resolve condy cp entires

**Comment by tajila** [comment]
@gacholio will we have to add a helper to `cnathelp.cpp` similar to `old_slow_jitResolveInvokeDynamic` in order to resolve ConstantDynamic constants ?

**Comment by DanHeidinga** [comment]
Depends on https://github.com/eclipse/openj9/issues/1272

**Comment by gacholio** [comment]
@tajila Yes, you'll need to add a new C helper and update *nathelp.m4 to provide the JIT-callable version.  These should be picbuilder helpers, asuming they will not be called directly from the compiled code.
