### ISSUE TITLE
ConstantDynamic: Verifier checks for Constant dynamic

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1278]
Condy entries are valid for classifies with major version 55 (or greater)
Static constraints: runtime/bcverify/staticverify.c
Runtime verification: runtime/bcverify/rtverify.c

Name and type must match bytecode (ie. 'D' and 'J' must be used with ldc2_w and not ldc)

http://mail.openjdk.java.net/pipermail/valhalla-spec-experts/2018-March/000586.html

**Comment by DanHeidinga** [comment]
Static constaints: `runtime/bcverify/staticverify.c`
Runtime verification: `runtime/bcverify/rtverify.c`

**Comment by DanHeidinga** [comment]
`ldc2w` will need to validate the Condy returns a long (`J`) or double (`D`)

**Comment by fengxue-IS** [comment]
tested with openjdk11-condy build and modified ASM jar (it doesn't generate `ldc2_w` bytecode),
```
public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=2, locals=1, args_size=1
         0: aload_0
         1: ldc2_w        #22                 // Dynamic #0:m:F
         4: return
```
```
Error: Unable to initialize main class A
Caused by: java.lang.VerifyError: Illegal type at constant pool entry 22 in class A
Exception Details:
  Location:
    A.main([Ljava/lang/String;)V @1: ldc2_w
  Reason:
    Constant pool index 22 is invalid
```

**Comment by tajila** [comment]
This work depends on https://github.com/eclipse/openj9/pull/1426

**Comment by tajila** [comment]
@taliamccormick can you take a look at this

**Comment by taliamccormick** [comment]
WIP PR here: https://github.com/eclipse/openj9/pull/1631
