### ISSUE TITLE
SharedClassCacheInfo is missing constants for Java 10 & 11

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1288]
SharedClassCacheInfo is missing constants for Java 10 & 11, as is runtime/include/ibmjvmti.h

These constants are present in runtime/oti/shchelp.h

Before adding the constants we should consider if we really need to have new levels for each Java version, as there will be a new Java version every 6 months. Perhaps only the LTS levels should change the mod level.

@hangshao0 fyi

**Comment by hangshao0** [comment]
We are already changing the mod level for Java 9 which is not a LTS.

**Comment by pshipton** [comment]
There is still time to change it. There isn't any released version of OpenJ9 for Java 9 yet.

**Comment by hangshao0** [comment]
If Java 8 and Java 9 share the same mod level and the same cache name is used, the cache file name (_cacheNameWithVGen) will be the same for Java 8 and 9. So a Java 9 cache could be started up by Java 8 when option "noAutoPunt" is used.

**Comment by pshipton** [comment]
I'm not suggesting that Java 8 & 9 share the same mod level. I'm suggesting that Java 9, 10. & 11 share the same level, since 9 & 10 are short term releases that will be obsolete when Java 11 is released.

**Comment by hangshao0** [comment]
> I'm suggesting that Java 9, 10. & 11 share the same level
OK, this should be fine.

**Comment by hangshao0** [comment]
We might want to mention this change in what's new for Java 10 ?

**Comment by SueChaplain** [comment]
What exactly needs documenting in the What's new? What is a constant? Is this to do with the cache generation number?

**Comment by hangshao0** [comment]
> Is this to do with the cache generation number?


No. It is not related to cache generation.

**Comment by pshipton** [comment]
The JVMLEVEL constants are visible here https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.api.80.doc/com.ibm.oti.shared/com/ibm/oti/shared/SharedClassCacheInfo.html
