### ISSUE TITLE
Add manually triggered 'Release' build to Jenkins

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1297]
Similar to [Pipeline-Build-Test-All](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/)
- Only builds one SDK version
- Takes parameters:
  - OPENJDK/OPENJ9/OMR x BRANCH/SHA
  - SDK_VERSION (choice)
- Build all platforms
- Launches appropriate downstream pipelines

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/
Based on Pipeline-Build-Test-All, can be configured to build any combination of releases/specs. Currently builds 8,9,10 all platforms. We can adjust the input params in the future as needed.

**Comment by pshipton** [comment]
This is awesome, and just in time for testing the 0.9.0 release. 

I'd like to run a jdk9 only build (once https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/172 is merged), since jdk9 all failed when testing the 0.9.0 release.

**Comment by AdamBrousseau** [comment]
Added 8,9,10 bools so you can launch specific versions

**Comment by pshipton** [comment]
Thanks. Instant service. I feel like I should be asking for more stuff. :)

**Comment by pshipton** [comment]
I tried to launch a jdk9 only build, but got 8 and 10 as well.
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Release-Build/detail/Pipeline-Release-Build/4/pipeline/

**Comment by pshipton** [comment]
@jdekonin fyi the last couple of comments. Is this something Violeta can fix quickly so we can run a jdk9 only build? Adam mentioned "Missing build-user plugin".

**Comment by AdamBrousseau** [comment]
fixed, had wrong case in the JavaX booleans
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/10
