### ISSUE TITLE
Cleanup class scanning in Balanced

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/openj9#1301]
J9 Class scanning in Balanced is initiated as soon as correspondent Class Object is discovered in the object heap. It calls a number of iterators to scan J9 scan class related parts:

 - GC_ClassStaticsIterator for RAM Statics
 - GC_CallSitesIterator for Call Sites
 - GC_ConstantPoolObjectSlotIterator for Constant Pool
 - GC_MethodTypesIterator twice for Method Types and Var Handle Method Types

This pattern is the same for all Balanced components (Copy Forward, Global Mark, Partial Mark, Card Scrabber, Write Once Compactor)

There is a general Class Slots Iterator available: GC_ClassIterator
It calls all iterators listed above one by one, so potentially it can be used in Balanced instead.

It should be possible because the handling of slots for all iterators is the same and scanning order is not important. 
However GC_ClassIterator requires slight modification: it returns slots from J9 Class structure itself so Class Object might be scanned twice. It might create problems. So we should add logic to GC_ClassIterator to prevent Class Object to be returned back.
By the way there is a potential problem with J9 Class scanning in Balanced: we never scan J9 Class structure itself so rely on fact that there is only one object reference in it and this is Class Object has been scanned before. Using of improved  GC_ClassIterator should solve this potential problem automatically.

**Comment by dmitripivkine** [comment]
@jonoommen Would you please take a look?

**Comment by jonoommen** [comment]
Yes 👍

**Comment by dmitripivkine** [comment]
Jenkins test sanity pLinux jdk8
