### ISSUE TITLE
Make freemarker.jar downloads robust to sourceforge outages

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1341]
While we cache freemarker.jar on the CI machines, we should also update the makefiles to pull from https://ci.adoptopenjdk.net/userContent/freemarker-2.3.8.tar.gz if sourceforge returns an error.

This will make builds more robust and prevent outages like the recent ones due to sourceforge being down.

**Comment by DanHeidinga** [comment]
See https://github.com/AdoptOpenJDK/openjdk-build/blob/ee35cfa2535d06a3b7250beada4678744db11b37/sbin/common-functions.sh#L65

Adopt has already handled this in their scripts and we've handled it by ensuring freemarker is available in the machine config.

**Comment by jdekonin** [comment]
OpenJ9s travis build pulls directly from sourceforge still.  Is this worth the simple change of pulling from https://ci.eclipse.org/openj9/userContent/freemarker.jar?
