### ISSUE TITLE
Stubs for generated files prevent out of tree compilation. 

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#135]
Currently we have stubs checked into the repo to stand in for files generated by tracegen / ~~hookgen~~. Eg. 
https://github.com/eclipse/openj9/blob/master/runtime/simplepool/ut_simplepool.h

The problem occurs when trying to perform an out of tree build. In such a scenario we would want to generate the generated files in the build tree rather than the source tree.  However may of the headers are included like so:
```#include  "ut_simplepool.h"```
The issue is in the use of the quotation syntax rather than angle bracket, since the preprocessor first looks for the file relative the source file before looking in the include path.  This means its impossible to have the files generated anywhere other than in the source tree

EDIT: we dont actually have stubs for the headers generated by hookgen

**Comment by DanHeidinga** [comment]
@dnakamura Is this still relevant?

**Comment by dnakamura** [comment]
closed via #754
