### ISSUE TITLE
A potential miss in format checking

### ISSUE THREAD

**Issue by myspringchen** [eclipse/openj9#1352]
It seems that J9 has a miss in checking an interface. The specification requires that "If the ACC_INTERFACE flag is set, the ACC_ABSTRACT flag must also be set". (https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-4.html#jvms-4.1). J9 fails in report formaterror.

How to reproduce: run Context.class (https://jbox.sjtu.edu.cn/l/fJ6wui) on OpenJ9 (jdk-9+181, nightly build 20180302_128) and HotSpot. (openjdk [1.8.0_151.) HotSpot states that the class has a format error (0x201). OpenJ9 does not.

OpenJ9:
Error: Main method not found in class avrora.syntax.Context, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

HotSpot:
java MicrocontrollerFactory Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ClassFormatError: Illegal class modifiers in class MicrocontrollerFactory1: 0x201
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

class format:
javap -verbose Context.class 
Classfile /home/yuting/Desktop/avrora/syntax/Context.class
  Last modified Dec 29, 2017; size 215 bytes
  MD5 checksum d12044d198af6e12c38d546d037e54aa
public interface avrora.syntax.Context
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_INTERFACE
Constant pool:
  #1 = Utf8               avrora/syntax/Context
  #2 = Class              #1              // avrora/syntax/Context
  #3 = Utf8               java/lang/Object
  #4 = Class              #3              // java/lang/Object
  #5 = Utf8               getRegister
  #6 = Utf8               (Lcck/parser/AbstractToken;)Lavrora/arch/legacy/LegacyRegister;
  #7 = Utf8               getVariable
  #8 = Utf8               (Lcck/parser/AbstractToken;)I
{
  public abstract avrora.arch.legacy.LegacyRegister getRegister(cck.parser.AbstractToken);
    descriptor: (Lcck/parser/AbstractToken;)Lavrora/arch/legacy/LegacyRegister;
    flags: ACC_PUBLIC, ACC_ABSTRACT

  public abstract int getVariable(cck.parser.AbstractToken);
    descriptor: (Lcck/parser/AbstractToken;)I
    flags: ACC_PUBLIC, ACC_ABSTRACT
}

**Comment by myspringchen** [comment]
A simplified test is given here:
[https://jbox.sjtu.edu.cn/l/NHfFp1](url)

**Comment by DanHeidinga** [comment]
Thanks @myspringchen for opening this.  I'll take look.

**Comment by DanHeidinga** [comment]
OpenJ9 detects this case when run with `-Xfuture`:
```
# java -Xfuture ATest
Error: LinkageError occurred while loading main class ATest
	java.lang.ClassFormatError: JVMCFRE077 interfaces must be abstract; class=ATest, offset=92
```

Looking in `cfreader.c`, I see that OpenJ9 fixes the missing `abstract` bit on interfaces.  This likely dates back a long way to when there were classfiles generated by javac or other tools (?) that did this incorrectly.

```
	/* Certain versions of the Java compiler forget to tag interfaces as abstract. Fix it. */
	/* See 1GCC5T2: J9VM:ALL - JDK accepts non-abstract interfaces */
	if( (classfile->accessFlags & (CFR_ACC_INTERFACE | CFR_ACC_ABSTRACT)) == CFR_ACC_INTERFACE ) {

		/* Only enforce the check if -Xfuture is specified */
		if (flags & CFR_Xfuture) { 
			errorCode = J9NLS_CFR_ERR_INTERFACE_NOT_ABSTRACT__ID;
			offset = index - data - 2;
			goto _errorFound;
		}

		classfile->accessFlags |= CFR_ACC_ABSTRACT;
	}
```
