### ISSUE TITLE
[Nestmates] Support invokevirtual of private methods in other classes

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1357]
Prior to nestmates, `invokevirtual` of private methods only occurred in the same class and could be rewritten to `invokespecial` at ROMClass creation time.

With nestmates, other classes in the nest can `invokevirtual` private methods of their mates.  This info isn't known until resolution when we can't modify the bytecode.  Additionally, the ROMClass could be in sharedclasses and this might not be a valid change from one run to the next due to separate compilation.

OpenJ9 needs to find a way to adapt to this in RAM & ROM constantpools.

**Comment by pshipton** [comment]
@DanHeidinga @fengxue-IS can this be closed now?

**Comment by fengxue-IS** [comment]
I think so, https://github.com/eclipse/openj9/pull/2434 should be the replacement for #1960
