### ISSUE TITLE
OpenJ9 in Alpine/musl Docker containers?

### ISSUE THREAD

**Issue by hrstoyanov** [eclipse/openj9#1363]
Any plans to support OpenJ9 to work with Alpine/musl (without needing to install  glibc)? OpenJDK 9 already support Alpine/musl directly. Thanks.

**Comment by DanHeidinga** [comment]
@ashu-mehra FYI (and can you share with Dinakar? I can't find his github id)

**Comment by stevewallin** [comment]
@dinogun

**Comment by dinogun** [comment]
@hrstoyanov The short answer is yes. I am still doing some background work to enable this and eventually you should see a PR at the AdoptOpenJDK [build github](https://github.com/AdoptOpenJDK/openjdk-build) for the builds to become available. Will update this issue with the PR details once I submit. Thanks

**Comment by hrstoyanov** [comment]
Thank you!

**Comment by avermeer** [comment]
Hello,

AdoptOpenJDK 16 HotSpot for Alpine has been released, but still no AdoptOpenJDK OpenJ9 supporting Alpine : any reason why ?

Kind regards,
Alexandre

**Comment by pshipton** [comment]
See https://github.com/eclipse/openj9/issues/5658#issuecomment-805312154

**Comment by pshipton** [comment]
As this is not active I will close it.
