### ISSUE TITLE
Upgrade TestNG to latest release (v6.14)

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#1367]
We are using TestNG 6.10, which has a known issue - TestNG exits with a zero when there are configuration failures. When this happens, TKG cannot catch the failure. Therefore, the TAP results that is generated will not have the failure.

Link to TestNG issue:
https://github.com/cbeust/testng/issues/1517 
https://groups.google.com/forum/#!msg/testng-users/WlX5H5B8fwo/m_GR0svPAQAJ

This issue is fixed in TestNG 6.13. We should upgrade TestNG to latest release (v6.14).
http://central.maven.org/maven2/org/testng/testng/

**Comment by llxia** [comment]
@TianyuZuo , could you take care of this? Thanks.

**Comment by TianyuZuo** [comment]
will update

**Comment by smlambert** [comment]
This upgrade will address/fix #1112
