### ISSUE TITLE
FAILED: testAllocateMemoryInCategory value for Unknown did not change

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#1377]
Regression in this build:https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_390-64_cmprssptrs/91/ 
Failed Tests: 2 (+2)
j9vm.test.memory.MemoryAllocator.testAllocateMemoryInAnUnknownCategory
j9vm.test.memory.MemoryAllocator.testAllocateMemoryInCategory

Exception java.lang.AssertionError

Message: value for Unknown did not change from 6,528 bytes / 32 allocations

Stacktrace:

at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
at org.testng.AssertJUnit.assertFalse(AssertJUnit.java:41)
at j9vm.test.memory.MemoryAllocator.verifyCategoryValueChanged(MemoryAllocator.java:174)
at j9vm.test.memory.MemoryAllocator.testAllocateMemoryInCategory(MemoryAllocator.java:130)

No obvious changes in OpenJ9.

**Comment by llxia** [comment]
#1365 is not fix for this issue. #1365 is fix for #1355 to fix LIBPATH on AIX.

The above failure is not test issue and it was introduced on Mar 6th. The test failed on all platforms.
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_390-64_cmprssptrs/91/console
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le/90/console
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK9-linux_390-64_cmprssptrs/88/console
https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le/84/console

**Comment by pdbain-ibm** [comment]
Will investigate.

**Comment by pdbain-ibm** [comment]
The 1000 new allocations are being ascribed to trace:
Old javacore:
2MEMUSER       +--VM: 2,365,679,968 bytes / 2546 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Classes: 9,832,096 bytes / 336 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Memory Manager (GC): 2,137,525,856 bytes / 465 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Java Heap: 2,095,054,848 bytes / 1 allocation
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Other: 42,471,008 bytes / 464 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Threads: 11,542,632 bytes / 179 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Java Stack: 240,448 bytes / 18 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Native Stack: 11,141,120 bytes / 19 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Other: 161,064 bytes / 142 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--**Trace: 189,096 bytes / 268 allocations**
2MEMUSER       |  | 
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--JNI: 60,616 bytes / 123 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Port Library: 206,166,184 bytes / 73 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Unused <32bit allocation regions: 206,155,072 bytes / 1 allocation
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Other: 11,112 bytes / 72 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Other: 345,712 bytes / 1089 allocations

New javacore:
2MEMUSER       +--VM: 2,365,986,280 bytes / 4802 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Classes: 9,838,992 bytes / 340 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Memory Manager (GC): 2,137,525,856 bytes / 465 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Java Heap: 2,095,054,848 bytes / 1 allocation
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Other: 42,471,008 bytes / 464 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Threads: 11,542,632 bytes / 179 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Java Stack: 240,448 bytes / 18 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Native Stack: 11,141,120 bytes / 19 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Other: 161,064 bytes / 142 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--**Trace: 487,960 bytes / 2515 allocations**
2MEMUSER       |  | 
3MEMUSER       |  +--JVMTI: 17,776 bytes / 13 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--JNI: 60,744 bytes / 124 allocations
2MEMUSER       |  | 
3MEMUSER       |  +--Port Library: 206,165,520 bytes / 76 allocations
3MEMUSER       |  |  | 
4MEMUSER       |  |  +--Unused <32bit allocation regions: 206,153,800 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 11,720 bytes / 75 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 346,800 bytes / 1090 allocations

**Comment by pdbain-ibm** [comment]
The "unknown" category is 32-bit negative:
[DEBUG] Allocate memory in unknown category 8000000e.
OMR category codes are negative.

**Comment by pdbain-ibm** [comment]
The issue is that the JNI native calls "malloc()", which it expected to be overridden via jvm.h.
However, the override isn't happening:
```
(gdb) disassemble Java_j9vm_test_memory_MemoryAllocator_allocateMemory
Dump of assembler code for function Java_j9vm_test_memory_MemoryAllocator_allocateMemory:
   0x00007fffe698db60 <+0>:	push   %rbp
   ...
   0x00007fffe698dbc7 <+103>:	mov    %rbp,%rdi
   0x00007fffe698dbca <+106>:	callq  0x7fffe697f3f0 <malloc@plt>
   0x00007fffe698dbcf <+111>:	test   %rax,%rax

```

**Comment by pdbain-ibm** [comment]
Probably due to this change:
https://github.ibm.com/runtimes/openj9/commit/1142acdb32f5846155839989780febf2c8c1b2f9
which removes the "include" of jvm.h.
