### ISSUE TITLE
Enable arm compilation on native platform

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#138]
Currently makefiles are written assuming cross compilation with specific tooling.  eg qemu.

**Comment by JamesKingdon** [comment]
This has a (partial?) dependency on https://github.com/eclipse/openj9/issues/509 as currently composition is not working correctly for 32 bit builds.

**Comment by pshipton** [comment]
I assume this can be closed since #686 is merged and a build for ARM can be completed with the other pending changes. Please re-open if still needed.
