### ISSUE TITLE
Valhalla LWVT: Flatten value type arrays

### ISSUE THREAD

**Issue by eric98zhang** [eclipse/openj9#1389]
The initial implementation should flatten all arrays whose element type is a value type. Later, flattening only arrays of smaller value types should be considered.

Note also that instance fields with the `ACC_FLATTENABLE` field modifier that are value class arrays can be flattened. See #1387.

**Comment by acrowthe** [comment]
The `internalFindArrayClass` method in `classsupport.c` will need to be revisted while flattenable arrays are being implemented.
https://github.com/eclipse/openj9/blob/master/runtime/vm/classsupport.c
