### ISSUE TITLE
Getting Hash Sum mismatch while building openj9 image

### ISSUE THREAD

**Issue by sabkrish** [eclipse/openj9#14]
I was running "docker build -t openj9 -f Dockerfile ." to build the dockerfile on linux x86-64. I ended up with the below error.

E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/universe/source/by-hash/SHA256/e201ab73d77c0208d5dcd4844b6215bc5e18b49d9f9b58d0fb627c47c0438ecd  Hash Sum mismatch
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/by-hash/SHA256/8d6ab57abf517d7712e4e4d23d762485af49f8140a83b221ea7282f82a51c795
E: Some index files failed to download. They have been ignored, or old ones used instead.

I already had a ubuntu image installed. Not sure if this was causing any issues. So, i did docker pull of ubuntu image and updated it. But no luck.

I'm not able to understand why is this happening.

Workaround:
Added "rm -rf /var/lib/apt/lists/* && apt-get clean" before apt-get update (based on google search) in the dockerfile and it helped.

**Comment by mstoodle** [comment]
@sabkrish can you provide a few more details about your host environment to see if we can figure out the origin of this issue?

**Comment by sabkrish** [comment]
OS: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-31-generic x86_64)
It already had a ubuntu 16.04 docker image pulled in 3 months ago.

**Comment by DanHeidinga** [comment]
@sabkrish Is there a proxy between you the apt server?  Or some form of caching in place for the packages?

Reading https://bugs.launchpad.net/ubuntu/+source/apt/+bug/972077 and related links indicates there was a bug in older version of apt (now fixed) but caching / proxies may be responsible for similar appearing issues.

**Comment by sabkrish** [comment]
@DanHeidinga - Dinakar also faced the same issue but the solution which worked for me didn't work for him. For him, when he switched from Wireless network to Wired network, it worked. So, it appears to be some problem with the network cache. I think the solution that worked for me mayn't work for everyone. So, i'm planning to close the PR i had raised with this change.

**Comment by pshipton** [comment]
Closing, please re-open if there is still a problem.
