### ISSUE TITLE
OpenJ9 compilation fails with -O0

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#1405]
Download as usual, then edit openj9/buildspecs/linux_x86-64_cmprssptrs.spec: add these lines
 ```
        <property name="uma_optimization_cflags" value="-O0 -g"/>
         <property name="uma_optimization_cxxflags" value="-O0 -g"/>
```
around line 103.
Run normal "configure" and "make all" steps.
The build fails with the following error:

gcc -DJAVA_SPEC_VERSION=9 -DOPENJ9_BUILD -O0 -g -fno-exceptions -fno-rtti -fno-threadsafe-statics -g -MMD -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64  -fPIC -DIPv6_FUNCTION_SUPPORT -DJ9HAMMER -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -I. -I../include -I../oti -I../util -I../gc_include -I../omr/gc/include -I../shared_common/include -I../gc_glue_java -I../nls -I../omr/include_core    -DUT_DIRECT_TRACE_REGISTRATION -DTR_HOST_X86 -c DebugBytecodeInterpreter.cpp
In file included from ../oti/j9.h:84:0,
                 from AsyncMessageHandler.cpp:24:
../oti/j9accessbarrierhelpers.h:42:1: error: ‘J9Object* j9javaArrayOfObject_load_VM(J9JavaVM*, J9IndexableObject*, I_32)’ defined but not used [-Werror=unused-function]
 j9javaArrayOfObject_load_VM(J9JavaVM *vm, J9IndexableObject *array, I_32 index)
 ^

Same issue with setting UMA_DO_NOT_OPTIMIZE_CCODE=1 on the make command line.

The issue is that runtime/oti/j9accessbarrierhelpers.h defines (rather than declares) two methods which are used via macros such as J9JAVAARRAYOFOBJECT_LOAD.

Any file which includes (directly or indirectly) this header will get definitions of the functions.  If they don't actually use them (or the macros) the compiler throws an error due to the unused functions.

This file was introduced by @amicic via this commit:
$ git log runtime/oti/j9accessbarrierhelpers.h 
commit bdce1b675c22b905f2fc169e735156ac24cb6fc4
Author: Aleksandar Micic <amicic@ca.ibm.com>
Date:   Tue Feb 20 09:43:06 2018 -0500

    Static read barrier
    
    Introduce API (external MemoryManagament and VM access barrier macros)
    for read barrier in class static slots. Implementation is just slightly
    different from the heap slot access, due to slot being always
    non-compressed reference.
    
    Also unifying the macros for reference slots reads (both static and
    non-static), to resemble more to store macros (to use separate a step
    for pre/post barriers and load/store).
    
    Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

**Comment by amicic** [comment]
@gacholio came across this too, and found that specifying -Wno-unused-function (whenever you need -O0) helps.

**Comment by pdbain-ibm** [comment]
It sounds like a bad idea to put function definitions in a header file. 
Could you move the functions to a .c file and put the declarations in the header?

**Comment by pdbain-ibm** [comment]
Why does this work with -O3?

**Comment by amicic** [comment]
We have a plenty of function definitions in GC header files, but they are always used, so we don't have problems. This head file however has high visibility and gets indirectly included where it's not necessary.

Putting it into .c would prevent inlining. These macros should be as fast as possible.

GAC's speculation is that high compiler optimization levels remove the definition of these functions selectively where it's not used.

I wish I have a better solution, but I don't. Suggestions are welcome, but non inlining it, I suspect is not a good compromise.

FYI @charliegracie

**Comment by pdbain-ibm** [comment]
I suggest "#include"ing it not in j9.h but instead in the files which need the functions, of which I count approximately 15.  You might also be able to include it in another header that is less universally used.
FYI @DanHeidinga

**Comment by amicic** [comment]
I had something like that at one point (having some similar problems with mutual dependencies, but not knowing about this problem), and I was eventually happy to find a solution so not do modify all those files :) 

But, yes, I can go back to it, if others agree.

**Comment by pdbain-ibm** [comment]
I submit that updating the header files makes OpenJ9 more usable by the general population.
That will allow users to set UMA_DO_NOT_OPTIMIZE_CCODE=1 on the command line and not need to set other options.

**Comment by pdbain-ibm** [comment]
Adding   __attribute__ ((unused)) to the functions should fix the problem.  Testing that now.
