### ISSUE TITLE
Add Jenkins Help message "bot" for PullRequest build syntax

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1408]
The [GithubPullRequestBuilder Plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin) has the option to post comments to a PR. We could use this option to add a help/usage comment to a PR.

Trigger: `Jenkins help`
Output comment:
<<<
[Jenkins README](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md)
Syntax: `Jenkins <build type> <level> [<platform(s)> [<java version(s)> [depends <org>/<repo>#<PR_ID>]]]`
- Build Types: `compile,test`
- Levels: `sanity,extended` (only if Build Type is test)
- Platforms: `zlinux,plinux,aix`
- Java Versions: `jdk8,jdk9`
- Orgs: `eclipse,ibmruntimes`
- Repos: `omr,openj9-omr,openj9,openj9-openjdk-jdk[8,9]`
- PR_ID: Pull Request ID containing the dependent change
##### Note: You can use keyword all for level, platform or version
<<<
See [example comment](https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/58#issuecomment-371930546)

##### TODO
- [ ] PR for README update

**Comment by keithc-ca** [comment]
This information is already available at [1]. I'd rather not clutter the discussion in a pull request with additional copies of that.

[1] https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md

**Comment by pshipton** [comment]
It may be useful to post a message any time an invalid jenkins command is entered, in the case of a typo or forgotten syntax. I think we could limit it to a simple message like "Invalid jenkins command, see [1]", which would avoid having to keep help output up to date. Afterwards the comment could be deleted by any committer to avoid cluttering the discussion.

**Comment by keithc-ca** [comment]
That works for me as long as mentions of jenkins in this comment and the previous one don't trigger the 'invalid command' response.

**Comment by AdamBrousseau** [comment]
Builds are launched based on a regex. I don't see how we could create such a regex that would recognize only bad syntax.

**Comment by keithc-ca** [comment]
Maybe restrict the responses to those (bad) comments that start with 'jenkins ...' and ignore those where jenkins isn't the first word?

**Comment by AdamBrousseau** [comment]
>via an "else"

Not that I am aware or can see upon initial searches

**Comment by pshipton** [comment]
It doesn't actually need to be an "else". Can we keep track if a build was launched, and if no build was launched after doing the regular expression processing, and there is a command starting with "jenkins ..." then post?

**Comment by AdamBrousseau** [comment]
not easily, if at all

**Comment by DanHeidinga** [comment]
Can we add this as a Slack "slash command"?  Committers should (hopefully) be connected to the slack instance already.

**Comment by AdamBrousseau** [comment]
I would argue that if the user is already at the repo on Github, it should be easier to find the Jenkins Readme than to go to Slack and request help.

**Comment by pshipton** [comment]
I vote to close this issue and not bother providing any help output. We could create a document for commiters in the doc directory which would point to https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md

**Comment by AdamBrousseau** [comment]
>close this issue

Agree
