### ISSUE TITLE
omrvmem.c asserts with hugepages in Docker

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#1419]
I noticed that when I had 1G hugepages configured in the host OS, running the JVM in Docker (in this case as part of the build) failed with an assert:

01:51:38.216 0x23c8a00 omrport.0      *   ** ASSERTION FAILED ** at ../../omr/port/linux/omrvmem.c:694: ((params->startAddress <= params->endAddress))

This is likely being caused by some sort of configuration problem with Docker (the Docker container was created before the hugepages were configured in the host OS), but it would be nice if we could handle the situation more gracefully.

**Comment by JamesKingdon** [comment]
I started hitting this outside of Docker with a prototype build that can use multiple hugepage sizes. It's possible there is a failure path that isn't being handled correctly when shmget calls fail to return memory (or possibly my very hacky prototype has just broken something and it's a complete coincidence that it falls over at the same assert)

**Comment by andrewcraik** [comment]
@mpirvu this looks familiar?

**Comment by mpirvu** [comment]
Yes, Harry Yu is looking at a similar issue.
@haryyu1994
