### ISSUE TITLE
Add support for specifying heap limit in terms of percentage of total memory

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#1428]
OpenJDK has added options to control heap memory allocations based on percentage of total memory. Details can be found in this [bug report](https://bugs.openjdk.java.net/browse/JDK-8186315). 
The newly added options (`-XX:MaxRAMPercentage -XX:MinRAMPercentage and -XX:InitialRAMPercentage`) are pretty useful for Java applications running in container. Specifying these limits as percentage of total memory, instead of statically setting using -Xmx/-Xms, makes it easy to auto configure the heap settings if container memory is changed.
It would be good for OpenJ9 to support these options as well.

fyi - @charliegracie @dmitripivkine @DanHeidinga @dinogun

**Comment by ashu-mehra** [comment]
I can understand `-XX:MaxRAMPercentage` would specify maximum percentage of RAM that java heap can occupy. Similarly, `-XX:InitialRAMPercentage` would be percentage of RAM that java heap starts with.
But I can't make out what `-XX:MinRAMPercentage` option is for? Does it mean minimum percentage of RAM memory that java heap should occupy? I can't understand why would someone want to specify that. I don't think OpenJ9 has anything like that.
@dmitripivkine your thoughts?

**Comment by dmitripivkine** [comment]
Sounds like -XX:MinRAMPercentage is alias of -XX:InitialRAMPercentage

**Comment by ashu-mehra** [comment]
> Sounds like -XX:MinRAMPercentage is alias of -XX:InitialRAMPercentage

Doesn't look like they are same.
If I just specify `-XX:MinRAMPercentage`, I don't see any change in initial heap size.
With `-XX:InitialRAMPercentage`, initial heap size gets updated as per the value given.
In the examples below, I am running jdk10 in a container with 2G memory limit.

```
# ./bin/java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version | grep InitialHeapSize
   size_t InitialHeapSize                          = 33554432                                 {product} {ergonomic}
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment 18.3 (build 10+46)
OpenJDK 64-Bit Server VM 18.3 (build 10+46, mixed mode)

# ./bin/java -XX:MinRAMPercentage=10 -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version | grep InitialHeapSize
   size_t InitialHeapSize                          = 33554432                                 {product} {ergonomic}
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment 18.3 (build 10+46)
OpenJDK 64-Bit Server VM 18.3 (build 10+46, mixed mode)

# ./bin/java -XX:InitialRAMPercentage=10 -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version | grep InitialHeapSize
   size_t InitialHeapSize                          = 216006656                                {product} {ergonomic}
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment 18.3 (build 10+46)
OpenJDK 64-Bit Server VM 18.3 (build 10+46, mixed mode)

**Comment by dmitripivkine** [comment]
InitialRAMPercentage and MaxRAMPercentage seems are settings in %% from total RAM size for -Xms and -Xmx - range(0.0, 100.0) 
However:
MinRAMPercentage (default value 50.0, range(1, max_uintx)) : Minimum percentage of real memory used for maximum heap (size on systems with small physical memory size)

**Comment by ashu-mehra** [comment]
I found reference to MinRAMFraction (which gets deprecated by MinRAMPercentage) in this book excerpt: https://books.google.co.in/books?id=aIhUAwAAQBAJ&pg=PA174&lpg=PA174&dq=XX:MinRAMFraction&source=bl&ots=E6Xs7m05gE&sig=4fOy_TApETJ4iSEpLhxKiw-j8Fo&hl=en&sa=X&ved=2ahUKEwiN_6n5jbfaAhWJQI8KHZieCGMQ6AEwA3oECAAQRg#v=onepage&q=XX%3AMinRAMFraction&f=false

From that text, it appears `MinRAMFraction's` default value is 2 and it is used to set max heap to half of physical memory when the physical memory is < 192 MB (i.e. systems with small physical memory size). In general, if `MinRAMFraction` is set to X, then for physical memory (P) < 92*X, the max heap size would be P/X.
I am not sure in which use-cases this kind of setting be useful. AFAIU I don't see any reason for supporting this type of parameter.
@dmitripivkine @DanHeidinga what are your thoughts on this?

**Comment by dmitripivkine** [comment]
We should not support obsolete options. However if MinRAMPercentage is supported currently by OpenJDK we should implement it as well. The meaning of it see my comment above

**Comment by ashu-mehra** [comment]
> MinRAMPercentage is a percentage of -Xmx provided value if it exceeds physical memory size. 
> For example run -Xmx256m on 200m physical memory size (if MinRAMPercentage is set to 50%) uses 128m for heap instead

I tried this but I still see max heap size as 256M. I started a docker container with 200M memory and ran java 10 as:
```
# ./jdk-10+46/bin/java -Xmx256m -XX:MinRAMPercentage=50 -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version | grep HeapSize
   size_t ErgoHeapSizeLimit                        = 0                                        {product} {default}
   size_t HeapSizePerGCThread                      = 87241520                                 {product} {default}
   size_t InitialHeapSize                          = 8388608                                  {product} {ergonomic}
   size_t LargePageHeapSizeThreshold               = 134217728                                {product} {default}
   size_t MaxHeapSize                              = 268435456                                {product} {command line}
    uintx NonNMethodCodeHeapSize                   = 7591728                               {pd product} {ergonomic}
    uintx NonProfiledCodeHeapSize                  = 122033256                             {pd product} {ergonomic}
    uintx ProfiledCodeHeapSize                     = 122033256                             {pd product} {ergonomic}
openjdk version "10" 2018-03-20
OpenJDK Runtime Environment 18.3 (build 10+46)
OpenJDK 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

> We should not support obsolete options. 

I agree. As the above observation is different from Dmitri's comment, I searched and referenced now obsolete option `MinRAMFraction` in my previous [comment](https://github.com/eclipse/openj9/issues/1428#issuecomment-381136686) only to understand what `MinRAMPercentage` means as the two options are suppose to do the same thing, as per my understanding. No intention to add support for any obsolete option at all.

**Comment by dmitripivkine** [comment]
ok. I apologize. So that description I found is not accurate

**Comment by SueChaplain** [comment]
This issue has a whatsnew label, but it is not clear from the comments what was actually implemented. Are the 3 -XX options introduced in OpenJDK in the first comment now supported by OpenJ9 (for compatibility)?
