### ISSUE TITLE
Adjust default max heap size when running in container

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#1429]
In non-container scenarios physical memory is shared between multiple applications, therefore it makes sense for JVM to use only a reasonable amount of physical memory for heap, so as to not strangle other applications.
However in container environments, the scenario is different. Prominent use case of containers is to run a single application (along with some agents). If its a JVM based application, then JVM is going to be the single largest consumer of memory in the container. This means JVM can take leeway and allocate large fraction of container memory as heap.

Current setting for max heap size for Java 9 are as follows:

Physical memory (P) | Default max heap size (H)
--- | ---
< 1G | P/2
1G - 2G | 512 MB 
| > 2G | P/4 

For Java 8, it is as follows:

Physical memory (P) | Default max heap size (H)
--- | ---
< 1G | P/2
| > 1G | 512 MB 

With 1/4th (in Java 9) or 512 MB (in Java 8) limit, JVM is clearly not utilizing memory that it as at its disposal.
I believe we should change the default settings when we are running in container. We can discuss out what the default should be, but I guess we can set it as high as 75%.

fyi - @charliegracie @dmitripivkine @dinogun @DanHeidinga 

Edit 1: updated heap settings for java 8 which is different from java 9.

**Comment by mpirvu** [comment]
If containers are not limited in the memory they can use then having 10 containers each with a single JVM in them is no different than running 10 JVMs natively.
For a memory limited container I can see the value of increasing the default Xmx value though we have to take into the account the fact that the native JVM footprint could easily be over 100MB (classes, code cache, data cache, JIT persistent memory, JIT scratch memory for compilations, memory for GC data structures, etc).

**Comment by ashu-mehra** [comment]
I agree. We should increase the default Xmx value only if the container is started with some memory limit. If no memory limit is specified, default Xmx need not be changed.

**Comment by ashu-mehra** [comment]
I have got two implementations for the changes required for fixing this and #1428.
The changes are currently present in my repo for review.

In both cases, I need to update sysinfo_cgroup_get_memlimit() to return -1 if the cgroup memory limit is not specified. This will allow us to check if cgroup imposes any memory limit or not.

Plan1:
https://github.com/ashu-mehra/omr/commit/ef6d7c8cf10adb03e18574e82a7378cae25b6d9e
https://github.com/ashu-mehra/openj9/commit/c01b532c50dc82c389e82b8f4d307fa4229bb495

Plan2:
https://github.com/ashu-mehra/omr/commit/323298d64e21693fb511e6bbf937643a5aa6bca5
https://github.com/ashu-mehra/openj9/commit/0b57b12740593418b8596709f25d81e11096de01

These are not final implementations, but good enough to compare the two approaches.
@DanHeidinga @charliegracie @dmitripivkine can you please review these commits and provide inputs on which way to go.

**Comment by dmitripivkine** [comment]
Plan 1 looks slightly better for me. Code in OpenJ9 needs to be better.

**Comment by ashu-mehra** [comment]
> BTW I can not understand why you are trying to handle (cgroupMemory == -1) explicitly?
(rc != 0) check is enough for caller

Idea is to increase default max heap only if there is a memory limit imposed by container. If container is not imposing any limit, we don't want to do anything.
For that I have updated `sysinfo_cgroup_get_memlimit()` to set limit to -1 if memory limit is not specified. That's the reason for the check `cgroupMemory == -1`.

**Comment by dmitripivkine** [comment]
My point is from user perspective I can not see difference (or no special handling) between cases: 
- sysinfo_cgroup_get_memlimit() returns 0 (may I say "enabled"?) but limit is not set and
- sysinfo_cgroup_get_memlimit() returns non-zero ("disabled")

**Comment by ashu-mehra** [comment]
Got your point. I can update sysinfo_cgroup_get_memlimit() to return negative error code when limit is not set.

**Comment by mpirvu** [comment]
To be conservative I would leave 512M for VM/JIT (one compilation thread can use up to 256M). 
Thus, for Java9 the logic when using container limits could become

Physical memory (P) | Default max heap size (H)
---|---
< 1G |  P/2 (as before)
1G - 2G | P-512M
2G | 3/4P
