### ISSUE TITLE
openjdk9-openj9 jdk_net  test failures

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#1432]
Test results from the openjdk regression test group run against the nightly openjdk9-openj9 build at AdoptOpenJDK:  Test results: passed: 511; failed: 7

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/consoleFull

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/java/net/
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/sun/net/
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/jdk/net/

sun/net/www/http/HttpClient/IsKeepingAlive.java
sun/net/www/http/HttpClient/OpenServer.java
sun/net/www/http/HttpURLConnection/NTLMAuthWithSM.java
sun/net/www/protocol/jrt/WithSecurityManager.java
jdk/net/Sockets/Test.java
java/net/SetFactoryPermission/SetFactoryPermission.java
java/net/HttpURLConnection/SetAuthenticator/HTTPSetAuthenticatorTest.java
java/net/InetAddress/BadDottedIPAddress.java
java/net/InetAddress/CachedUnknownHostName.java
java/net/InetAddress/IPv4Formats.java
java/net/SocketPermission/SocketPermissionCollection.java
java/net/SocketPermission/Wildcard.java
java/net/Socks/SocksV4Test.java
java/net/httpclient/websocket/WSDriver.java

**Comment by sophia-guo** [comment]
390 specific:
java/net/MulticastSocket/Promiscuous.java
java/net/MulticastSocket/SetLoopbackMode.java
java/net/MulticastSocket/Test.java

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_s390x_linux/3/artifact/jvmtest/openjdk_regression/work/java/net/MulticastSocket/

[SetLoopbackMode.jtr.txt](https://github.com/eclipse/openj9/files/1819694/SetLoopbackMode.jtr.txt)
[Test.jtr.txt](https://github.com/eclipse/openj9/files/1819695/Test.jtr.txt)
[Promiscuous.jtr.txt](https://github.com/eclipse/openj9/files/1819696/Promiscuous.jtr.txt)

**Comment by smlambert** [comment]
Also attached x64 jtr files, as we do not keep test job artifacts at AdoptOpenJDK forever, so links to builds above will eventually go stale:

[x64_testResults_jtr.zip](https://github.com/eclipse/openj9/files/1819747/x64_testResults_jtr.zip)

**Comment by sophia-guo** [comment]
Close this issue as its jdk9, and as individual issues are being opened against jdk11.
