### ISSUE TITLE
openjdk9-openj9 jdk_nio test failures

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#1433]
Test results from the openjdk regression test group run against the nightly openjdk9-openj9 build at AdoptOpenJDK:  Test results: passed: 337; failed: 7; error: 12

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/consoleFull
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/java(jdk/sun)/nio

java/nio/channels/DatagramChannel/SendToUnresolved.java
java/nio/channels/SocketChannel/ExceptionTranslation.java
java/nio/charset/coders/StreamTimeout.java
java/nio/Buffer/Basic.java
java/nio/Buffer/Chars.java
java/nio/Buffer/CopyDirectMemory.java
java/nio/Buffer/LimitDirectMemory.sh
java/nio/channels/AsyncCloseAndInterrupt.java
java/nio/channels/SocketChannel/Connect.java
java/nio/file/attribute/BasicFileAttributeView/UnixSocketFile.java
jdk/nio/zipfs/Basic.java
jdk/nio/zipfs/PathOps.java
jdk/nio/zipfs/ZFSTests.java
jdk/nio/zipfs/ZipFSTester.java
sun/nio/ch/TestMaxCachedBufferSize.java
sun/nio/cs/FindDecoderBugs.java
sun/nio/cs/FindEncoderBugs.java
sun/nio/cs/OLD/TestIBMDB.java
sun/nio/cs/TestEUC_TW.java
sun/nio/cs/TestIBM1364.java
sun/nio/cs/TestUTF8.java

**Comment by sophia-guo** [comment]
390 specific:
java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java
java/nio/channels/DatagramChannel/Promiscuous.java

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_s390x_linux/3/artifact/jvmtest/openjdk_regression/work/java/nio/channels/DatagramChannel/

[Promiscuous.jtr.txt](https://github.com/eclipse/openj9/files/1819704/Promiscuous.jtr.txt)
[MulticastSendReceiveTests.jtr.txt](https://github.com/eclipse/openj9/files/1819705/MulticastSendReceiveTests.jtr.txt)

**Comment by smlambert** [comment]
I will close this issue as its jdk9, and as individual issues are being opened against jdk11.
