### ISSUE TITLE
openjdk9-openj9 jdk_util test failures

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#1434]
Test results from the openjdk regression test group run against the nightly openjdk9-openj9 build at AdoptOpenJDK: Test results: Test results: passed: 771; failed: 13
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/consoleFull

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/java/util/

java/util/logging/CheckZombieLockTest.java.CheckZombieLockTest
java/util/Spliterator/SpliteratorCollisions.java.SpliteratorCollisions
java/util/concurrent/LinkedTransferQueue/WhiteBox.java
java/util/Arrays/TimSortStackSize2.java
java/util/Spliterator/SpliteratorCharacteristics.java
java/util/concurrent/atomic/VMSupportsCS8.java
java/util/concurrent/locks/Lock/TimedAcquireLeak.java
java/util/concurrent/tck/JSR166TestCase.java#id1
java/util/logging/TestLoggerWeakRefLeak.java
java/util/logging/modules/GetResourceBundleTest.java
java/util/prefs/PrefsSpi.sh
java/util/regex/RegExTest.java
java/util/stream/test/org/openjdk/tests/java/util/stream/ToArrayOpTest.java

**Comment by pshipton** [comment]
I don't think this issue is serving any purpose, closing it. sanity.openjdk (tier1) is running and passing, there should be individual issues for any test failures.
