### ISSUE TITLE
Will there be a build for a JRE only?

### ISSUE THREAD

**Issue by mlehmannm** [eclipse/openj9#1438]
Are there any plans to provide builds for a JRE, like Oracle does?

**Comment by DanHeidinga** [comment]
That's a really good question @mlehmannm!  OpenJ9 is a source-only project.  Binaries are provided by the AdoptOpenJDK community.

I think this is a great idea and will raise an issue at Adopt to address it.

**Comment by DanHeidinga** [comment]
This continue this discussion at the Adopt project in https://github.com/AdoptOpenJDK/openjdk-build/issues/262
