### ISSUE TITLE
Pull request copyright check should not assume IBM Corporation!

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9#1440]
The current pull request copyright check in  openj9/buildenv/jenkins/jobs/infrastructure/copyrightCheck currently assumes files should have a copyright statement from IBM, which is not appropriate (even though all the existing files were written by IBM so it's been working silently for us).

I think it's this code that should be removed: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/jobs/infrastructure/copyrightCheck#L50-L51

**Comment by DanHeidinga** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
removed or made more generic?

change from
`REGEX = "\'Copyright \\(c\\) ([0-9]{4}), ${DATE_YEAR} IBM Corp. and others\'"`
to
`REGEX = "\'Copyright \\(c\\) ([0-9]{4}), ${DATE_YEAR}\'"`
?

**Comment by DanHeidinga** [comment]
The second one.  We shouldn't be enforcing an IBM Corp. copyright.

**Comment by AdamBrousseau** [comment]
Sorry I didn't use the `Fixes` keyword in my PR, can this be closed now?
