### ISSUE TITLE
jextract failures

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#1448]
jextract fails to collect native libraries when the VM was started from a custom launcher. On a number of occasions we've been unable to collect the native libraries on a remote system following a crash. Sometimes this relates to running out of heap and can be worked around with -J-Xmx4g (can we raise the default size for the tool?). The common factor with cases where increasing the heap doesn't resolve the problem seems to be that the JVM was launched from a C application instead of using the default 'java' launcher.

**Comment by DanHeidinga** [comment]
This has gone stale.  Closing
