### ISSUE TITLE
Change Archived SDK tars to start at folder 'jdk' instead of 'build'

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1451]
Blocks #1450 #1409 

Adopt test pipeline expects this structure.
The only reason we had this was for consistent JAVA_BIN location between PR and Test builds. Also since the OpenJDK repo has a `jdk` folder at the root.

Will need to add an if around JAVA_BIN var to set differently for PR builds until 1450 is resolved.

**Comment by AdamBrousseau** [comment]
@sophia-guo or @llxia Does the root folder always need to be `jdk` or is it `j2sdk-image` for Java 8?

**Comment by sophia-guo** [comment]
Both works. It doesn't matter what the folder name is.
