### ISSUE TITLE
[NestMates] Java API spec changes

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#1457]
http://cr.openjdk.java.net/~dholmes/8010319/specs/java.lang/java/lang/Class.html

`getNestMembers` and `getNestHost` can now throw security exceptions

**Comment by tajila** [comment]
@taliamccormick

**Comment by taliamccormick** [comment]
I'm noticing a possible issue with the API method `isNestmateOf`. Earlier spec drafts load the nest host during class resolution. The nest host would therefore be loaded/verified prior to calling `isNestmateOf`. However, more recent spec drafts put off nest host loading until necessary for the access-check. It is therefore possible to have the situation where we attempt to call `isNestmateOf` and compare nest hosts before the nest host(s) have been loaded.

This java.lang.API spec gives:
```
isNestmateOf
public boolean isNestmateOf​(Class<?> c)
Determines if the given Class is a nestmate of the object represented by this Class. Two classes are
 nestmates if they have the same nest host .
Parameters:
    c - the class to check 
Returns:
    true if this class and c are valid members of the same nest; and false otherwise. 
Since:
    11 
```
(http://cr.openjdk.java.net/%7Edholmes/8010319/specs/java.lang/java/lang/Class.html)

The JVM spec, section 5.4.4 Access Control gives:
```
Access checking is performed during resolution to ensure that a reference is permitted to a class, 
interface, field, or method.
...
To determine whether a class or interface C belongs to the same nest as D (that is, whether C and D
 are nestmates), the following steps are performed:
    1. If C and D are the same class or interface, they belong to the same nest.
    2. Otherwise, the nest host of D, H, is determined. If an exception is thrown, the nest membership
test fails for the same reason.
    3. Otherwise, the nest host of C, H', is determined. If an exception is thrown, the nest
membership test fails for the same reason.
    4. Otherwise, C and D belong to the same nest if H and H' are the same class or interface.
```
(http://cr.openjdk.java.net/%7Edlsmith/nestmates.html)

However, this process describes the nest loading during an access check - not the java.lang.Class `isNestmateOf` - and can throw exceptions - which this spec draft of the java.lang.Class `isNestmateOf` does not.

@tajila @DanHeidinga Thoughts?

**Comment by taliamccormick** [comment]
Similarly to above - the case where a verification error occurs when loading a class's nest host (eg. a class claims a nest host but the nest host does not verify it). I assume "the nest host of this class, or this if we cannot obtain a valid nest host" implies these cases would simply return `this` but will test against an openjdk build to confirm.

**Comment by taliamccormick** [comment]
Will be resolved by https://github.com/eclipse/openj9/pull/1501 and https://github.com/eclipse/openj9/pull/1531.
