### ISSUE TITLE
JVM_BeforeHalt() requires implementation for Java 11

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#1459]
Currently an empty implementation is added to allow raw builds proceed.

**Comment by babsingh** [comment]
**Update**: Implementation spec not received from the JCL team. Need to consult the JCL team before implementing `JVM_BeforeHalt`.

**Comment by JasonFengJ9** [comment]
@babsingh you might create an issue at https://github.ibm.com/runtimes/openjdk-contribution/issues.

**Comment by pshipton** [comment]
Seems JVM_BeforeHalt() is used for flight recorder, which isn't supported by OpenJ9 at this time. Having a stub is sufficient.
