### ISSUE TITLE
[build test failure] testDisclaimMemoryEffects_GC_Test can't shrink heap within 5 minutes

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1470]
Test is failing in JDK9 builds on linux ppcle 64:
https://ci.eclipse.org/openj9/job/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le/94/console

```
02:46:57         [SoftmxAdvanceTest_GC_Only] [WARN] 	Generate Java core dump after forcing GC.
02:46:57         JVMJ9VM079W triggerOneOffDump(java) requires j9dmp29
02:46:57         JVMJ9VM079W triggerOneOffDump(heap) requires j9dmp29
02:46:57         JVMJ9VM079W triggerOneOffDump(system) requires j9dmp29
02:46:57         FAILED: testDisclaimMemoryEffects_GC_Test
02:46:57         java.lang.AssertionError: 	FAIL: Heap can't shrink to the reset max heap size within 5 minutes!
02:46:57         	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
02:46:57         	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
02:46:57         	at j9vm.test.softmx.SoftmxAdvanceTest_GC_Only.testDisclaimMemoryEffects_GC_Test(SoftmxAdvanceTest_GC_Only.java:150)
02:46:57         	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
02:46:57         	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
02:46:57         	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
02:46:57         	at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:564)
02:46:57         	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
02:46:57         	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
02:46:57         	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
02:46:57         	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
02:46:57         	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:46:57         	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
02:46:57         	at org.testng.TestRunner.privateRun(TestRunner.java:648)
02:46:57         	at org.testng.TestRunner.run(TestRunner.java:505)
02:46:57         	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
02:46:57         	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
02:46:57         	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
02:46:57         	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
02:46:57         	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
02:46:57         	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
02:46:57         	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
02:46:57         	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
02:46:57         	at org.testng.TestNG.runSuites(TestNG.java:1049)
02:46:57         	at org.testng.TestNG.run(TestNG.java:1017)
02:46:57         	at org.testng.TestNG.privateMain(TestNG.java:1354)
02:46:57         	at org.testng.TestNG.main(TestNG.java:1323)
02:46:57         
02:46:57         
02:46:57         ===============================================
02:46:57             testSoftMxDisclaimMemory_GC
02:46:57             Tests run: 1, Failures: 1, Skips: 0
02:46:57         ===============================================
```

**Comment by DanHeidinga** [comment]
Marking this as high priority as it failed in the build

**Comment by DanHeidinga** [comment]
FYI @dmitripivkine Any thoughts on this?

**Comment by dmitripivkine** [comment]
Can we add generation of GC verbose log to the job? As I remember this test does not look to fact that object heap shrinks but memory returns back to OS. This might be a problematic for Hypervizer environment

**Comment by smlambert** [comment]
Fails on [ub16-ppcle-4](https://ci.eclipse.org/openj9/computer/ub16-ppcle-4/), 
passes on [ub16-ppcle-2](https://ci.eclipse.org/openj9/computer/ub16-ppcle-2/), [ub16-ppcle-1](https://ci.eclipse.org/openj9/computer/ub16-ppcle-1/)

Have not seen it run on ppcle-3.  

If its isolated to failing on ub16-ppcle-4, then this failure could have been introduced as early as March 15 (https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le/92/changes#detail1).

**Comment by smlambert** [comment]
Interestingly, it is not observed in extended PR testing, only in the extended nightly testing.

**Comment by smlambert** [comment]
This doesn't reproduce often, as it only fails on 1 of the 4 machines, and only in the nightly job (not in PR testing).  As such, I am removing the "prio:high" label.  We have added verbose gc logging and will look at that on next failure.  

We should also determine in what ways machine 4 is different from the other 3.

**Comment by DanHeidinga** [comment]
This occurred on the xLinux build last night and continues to hit the builds intermittently.

Is there any progress on this or should we disable the test?

**Comment by pshipton** [comment]
@smlambert is the verbose gc log available from the failure? https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_x86-64_cmprssptrs/10/

**Comment by smlambert** [comment]
Verbose gc log is now being created for those tests (as of #1504):

02:01:25 -Xdump:none -Xmx1024m -Xsoftmx512m -Xmn1m -XX:+DisclaimVirtualMemory -verbose:gc -Xverbosegclog:"/home/jenkins/workspace/Test-Extended-JDK8-linux_x86-64_cmprssptrs/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15258447208753/testSoftMxDisclaimMemory_GC_2"/vgc.log 

But you have to log on to machine at present to get it.  Our Adopt test scripts archive the results folder on failure, but openj9 scripts currently do not, and is possibly delayed the archiving test results folder in openj9 builds (which should include core files #969), due to concerns over available space on Jenkins.

I will set up a grinder at openj9, so we can run this test case and grab results... (need to fix machine labels), then will attempt to reproduce this failure in grinder job: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/1/rebuild/parameterized

**Comment by pshipton** [comment]
Another one on JDK10-linux_x86-64
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_x86-64/94/testReport/junit/j9vm.test.softmx/SoftmxAdvanceTest_GC_Only/testDisclaimMemoryEffects_GC_Test/

looks like gc log is available https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_x86-64/94/artifact/functional_test_output.tar.gz

@dmitripivkine

**Comment by dmitripivkine** [comment]
Object heap should shrink from 512m to 256m in 5 minutes (300 seconds). GC verbose log shows heap size was reduced to 256m at 132 second of the test. So GC handles -Xsoftmx properly. However test rely on two conditions (both should be true for success): 
- (ibmMemoryMBean.getHeapMemoryUsage().getCommitted() <= new_softmx_value)
- (ibmOSMBean.getFreePhysicalMemorySize() > preMemSize)
First condition should be true for now according GC verbose log. So we don't see return of free memory to OS.

**Comment by dmitripivkine** [comment]
![screen shot 2018-10-15 at 3 47 48 pm](https://user-images.githubusercontent.com/18148831/46974352-cfcdb380-d091-11e8-85ee-0b3bb0cf64fd.png)

**Comment by dmitripivkine** [comment]
My suggestion is to remove check for return of free memory to OS. This is test for -Xsoftmx functionality and I would trust getHeapMemoryUsage().getCommitted() report. It does not lie.

**Comment by pshipton** [comment]
@smlambert ^
