### ISSUE TITLE
Should we archive the openj9 slack?

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1473]
The Adopt community is using http://slackarchive.io to archive their slack channels and make them available on the web.  Is this something we want to be doing as well?

**Comment by DanHeidinga** [comment]
Free slacks only have so much history - this looks like a way to preserve the history.

**Comment by DanHeidinga** [comment]
@SueChaplain pointed out we've had this discussion before and it stopped when we couldn't confirm who owns the archived data.

**Comment by AdamBrousseau** [comment]
Do we know how reliable this free service is?
Seems to be some complaints on Twitter
https://twitter.com/search?q=slackarchive

**Comment by DanHeidinga** [comment]
Are there other archive tools that don't run into the data ownership issue or the reliability concerns?

**Comment by AdamBrousseau** [comment]
[Slark](https://slarck.com/) seems to be similar to SlackArchive
https://github.com/mihaip/slack-archive appears to be a tool which exports it into a Google account

**Comment by DanHeidinga** [comment]
I'm going to read the limited response as archiving slack isn't a pressing need.  Closing this as we can always revisit it later.
