### ISSUE TITLE
Do we really need a new class loader for every JMX call?

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#1483]
We've been working on reducing class unloading times caused by unloading massive numbers of class loaders that contain no loaded classes. Despite a 15 to 20 fold improvement we still can't meet the target pause times, and I want to make sure that we have fully explored the question of why so many empty class loaders are created in the first place. 

I wasn't involved in the early part of the investigation, but from the notes it seems that we create a new class loader for every JMX call for "security reasons". Is this really the only available solution to that problem? This level of profligacy seems untenable, with the system attempting to unload upwards of 700k class loaders in a single event.

**Comment by DanHeidinga** [comment]
@JamesKingdon Can you provide some pointers to the code in question?

**Comment by JamesKingdon** [comment]
Sorry, there are no specifics in the notes left by the previous developer. The closest I get is

> many classloaders are being generated by RMI proxy.Issue has been caused by a recent JCL security fix

I foolishly assumed the problem was well known.

**Comment by JamesKingdon** [comment]
Ok, it looks like I've been a doofus. The problem appears to be specific to the IBM JDK and doesn't manifest when running OpenJ9. Closing, sorry for the noise.
