### ISSUE TITLE
Remove `.*\[skip\W+ci\].*` Skip build phrase from all Jenkins PR jobs

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1488]
TravisCI will look for `[skip ci]` and `[ci skip]`, by default the Jenkins PR Builder plugin uses `[skip ci]`.
If you have this in you PR, you will not get a PR build when you ask for one. Because we trigger PR builds based on PR comments, it is not necessary to have a "Skip build phrase" for Jenkins. We need to remove this from all the PR builds.

**Comment by DanHeidinga** [comment]
Note: the Jenkins PR build looks at the PR text, not the commit.  We demonstrated that with https://github.com/eclipse/openj9/pull/1424

**Comment by AdamBrousseau** [comment]
I think it may check the PR descriptions as well as the commit(s), but I'm not 100% sure. Either wayu, won't matter going forward.

**Comment by AdamBrousseau** [comment]
Done
