### ISSUE TITLE
Test failure on Power9

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#1532]
SDK binary build on a ub16.04 machine with gcc 4.8.5.

Using openj9 test StringPeepholeTest_0, I get a failure in the subtest testBigDecimal0ToString.
Options that the test uses are ```-XX:-EnableHCR -Xjit:count=0,optLevel=hot```

Fails with 
```
java.lang.AssertionError: expected [0] but found [--0]
```

The same test passes on a Power8 ub16.04 machine with gcc 4.8.5.

**Comment by DanHeidinga** [comment]
FYI @zl-wang

**Comment by zl-wang** [comment]
@DanHeidinga @jdekonin  likely fixed here:  https://github.com/eclipse/omr/pull/2334

**Comment by jdekonin** [comment]
The OMR change was merged 25 days ago; this error was reproduced on shas from 3 days ago.
OpenJ9 - 073ad04
OMR - b623c98
openj9-openjdk-jdk8 - 8599c6f

**Comment by alenbadel** [comment]
The fix to this issue is in this pull request: 

https://github.com/eclipse/omr/pull/2499

**Comment by pshipton** [comment]
eclipse/omr#2499 is merged, assuming this can be closed .Please reopen if there is still a problem.
