### ISSUE TITLE
JDK10 sanity tests don't compile

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1543]
See the problem by running `jenkins test sanity <plat> jdk10`. We don't think the problem is platform specific.

https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK10-aix_ppc-64_cmprssptrs/1/console

**Comment by AdamBrousseau** [comment]
Also
zlinux https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Sanity-JDK10-linux_390-64_cmprssptrs-OpenJ9/1/console
plinux https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Sanity-JDK10-linux_ppc-64_cmprssptrs_le-OpenJ9/1/console

**Comment by pdbain-ibm** [comment]
[javac] /home/u0020236/workspace/Test-Sanity-JDK10-aix_ppc-64_cmprssptrs/openj9/test/JLM_Tests/src/org/openj9/test/java/lang/management/TestLoggingMXBean.java:56: error: package com.ibm.java.lang.management.internal is not visible
15:53:37     [javac] import com.ibm.java.lang.management.internal.LoggingMXBeanImpl;

**Comment by renfeiw** [comment]
Looks like the logic in the build.xml causes this issue. Instead of doing `<equals arg1="${JAVA_VERSION}" arg2="SE90"/> ...addExports...`, we need to change it to if SE80 do not addExports, else addExport. We will have a PR to fix this.

**Comment by AdamBrousseau** [comment]
Doesn't appear to be resolved.
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK10-aix_ppc-64_cmprssptrs/3/console
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK10-linux_ppc-64_cmprssptrs_le/2/console
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK10-linux_390-64_cmprssptrs/2/console
```
00:03:45.232 compile:
00:03:45.232      [echo] Ant version is Apache Ant(TM) version 1.9.6 compiled on July 8 2015
00:03:45.232      [echo] ============COMPILER SETTINGS============
00:03:45.232      [echo] ===fork:				yes
00:03:45.232      [echo] ===executable:			/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK10-linux_390-64_cmprssptrs/jdk/bin/javac
00:03:45.232      [echo] ===debug:				on
00:03:45.232      [echo] ===destdir:				/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK10-linux_390-64_cmprssptrs/openj9/test/TestConfig/../../jvmtest/Java10andUp
00:03:45.232     [javac] Compiling 5 source files to /home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK10-linux_390-64_cmprssptrs/openj9/test/Java10andUp/bin
00:03:49.492     [javac] /home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK10-linux_390-64_cmprssptrs/openj9/test/Java10andUp/src/org/openj9/test/java/lang/management/ThreadMXBean/ThreadMXBeanTestCase.java:26: error: cannot find symbol
00:03:49.492     [javac] public abstract class ThreadMXBeanTestCase extends ThreadMXBeanTestCaseCommon {
```

**Comment by DanHeidinga** [comment]
Reopening based on @AdamBrousseau comments.

**Comment by DanHeidinga** [comment]
@renfeiw Can you take another look at this?

**Comment by smlambert** [comment]
That was on me, the PR test trigger did not work for jdk10 (which I believe is now working, thanks Adam), and I proceeded to merge.  This is a new failure from the previous, so seems we need to work through a few more issues.

**Comment by renfeiw** [comment]
It's not caused by the framework issue, it's a specific test compilation issue. Looks like Java10andUp doesn't have a working compilation process. I will look further.

**Comment by renfeiw** [comment]
Created a PR to fix the Java10andUp issue: https://github.com/eclipse/openj9/pull/1578 Tested compilation with Java10 locally.

**Comment by pshipton** [comment]
This Issue was resolved and the tests are compiling.
