### ISSUE TITLE
OpenJ9 PR#1554 Set InterfaceHandle correctly for methods inherited from Object 

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#1555]
Personal build:
http://vmfarm.ottawa.ibm.com/build_info.php?build_id=382472
https://urv-jenkins.canlab.ibm.com:9095/view/J9/job/jvm.29.personal/19225/

**Comment by DanHeidinga** [comment]
@pdbain-ibm Closing this as I think those internal build links weren't intended for here =)
