### ISSUE TITLE
Update Jenkins node labels to match AdoptOpenJDK label schema

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1562]
Ref AdoptOpenJDK/openjdk-infrastructure#93

Since we will be reusing Adopt test JenkinsFiles (#1450), it would be a good idea to have the same node labelling schema. We should only add the labels we need.

We could also use [NodeHelper API](https://github.com/AdoptOpenJDK/openjdk-jenkins-helper) and [NodeLabel job](https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/pull/14)
- [x] Add new labels to nodes
- [x] Pull Request to update the labels for our existing build & test pipelines #2204
- [x] Remove old labels from nodes

#### zLinux
- hw.arch.s390x
- sw.os.linux
- sw.os.ubuntu
- sw.os.ubuntu.16
#### pLinux
- hw.arch.ppc64le
- sw.os.linux
- sw.os.ubuntu
- sw.os.ubuntu.16
#### aix
- hw.arch.ppc64
- sw.os.aix
- sw.os.aix.7_2

**Comment by AdamBrousseau** [comment]
@llxia can you confirm which `os` label you want/prefer for test.
i.e. `sw.os.linux` or `sw.os.ubuntu` or `sw.os.ubuntu.16`

**Comment by llxia** [comment]
Talked with Adam, we should use the same labeling across sites and we can use Shubham's tool to label machine automatically.

**Comment by llxia** [comment]
As we use Jenkins files from AdoptOpenJDK for test and both sites have different labeling schema, we pass in `LABEL` as parameter for now.
For example:
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-Functional-JDK8-linux_390-64_cmprssptrs/

**Comment by AdamBrousseau** [comment]
@llxia I have updated the machines with the new labels

**Comment by llxia** [comment]
Please note that test jobs are using the passed in `LABEL` parameter. If the label is changed, please update the default value in the test jobs.

For example:
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK8-linux_x86-64/configure

Once the labels are in sync between OpenJ9 and AdoptOpenJDK, we should not need `LABEL` parameter any more.

**Comment by AdamBrousseau** [comment]
Waiting on AdoptOpenJDK/openjdk-tests#481 before I remove the old labels

**Comment by smlambert** [comment]
AdoptOpenJDK/openjdk-tests#481 has been merged

**Comment by AdamBrousseau** [comment]
This is now complete. Thanks @smlambert and @llxia for helping drive this at Adopt

**Comment by llxia** [comment]
Updated all test jobs to set default value for `LABEL` to be empty ( `LABEL` option is kept just in case we need it for debugging). All test jobs will use the LABEL value from the AdoptOpenJDK test script.
