### ISSUE TITLE
Use environment variables for compilers in DockerFile(s)

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#1575]
Currently, symbolic links are used to set compilers in `buildenv/docker/jdk*/.../DockerFile`.

```
# Create links for c++,g++,cc,gcc
RUN ln -s g++ /usr/bin/c++ \
  && ln -s g++-4.8 /usr/bin/g++ \
  && ln -s gcc /usr/bin/cc \
  && ln -s gcc-4.8 /usr/bin/gcc
```

@keithc-ca recommended usage of environment variables instead of symbolic links.

```
ENV CC gcc-4.8
ENV CXX g++-4.8
```

**Comment by babsingh** [comment]
@keithc-ca can you verify the details in the above description? did you test only on `x86`?

**Comment by keithc-ca** [comment]
According to [1], we need to use `=` to separate the names and values, like this:
```
# Capture our compiler selection in the environment.
ENV CC=gcc-4.8 \
    CXX=g++-4.8
```
I tested using environment variables this way, in a virtual machine rather than a docker container, but the results should be the same.

[1] https://docs.docker.com/engine/reference/builder/#environment-replacement

**Comment by keithc-ca** [comment]
Apparently we're not ready to simply remove the links for gcc and g++ as configuring OMR fails without them:
```
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/space/jdk09/build/linux-x86_64-normal-server-release/vm/omr':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
run_configure.mk:164: recipe for target 'CONFIGURE_SENTINEL_FILE' failed
```

**Comment by ymanton** [comment]
I came across that earlier; there's some quirks in OMR's `configure` that make it do that. I put together a fix but I wasn't sure if it was worth fixing so I let it be, but maybe this is a sign. :church:

**Comment by babsingh** [comment]
According to **[1]**, both formats are accepted.
- Format 1
```
ENV cc gcc-4.8
ENV cxx g++-4.8
```
- Format 2
```
# Capture our compiler selection in the environment.
ENV CC=gcc-4.8 \
    CXX=g++-4.8
```
**[1]** https://docs.docker.com/engine/reference/builder/#env

**Comment by babsingh** [comment]
@ymanton will you be opening a pull request for the OMR fix?
