### ISSUE TITLE
Redundant methods in ConstantPoolMap.hpp

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#1596]
```
	U_16 getROMClassCPIndexForReference(U_16 cfrCPIndex)  const { return getROMClassCPIndex(cfrCPIndex); }
	U_16 getROMClassCPIndexForAnnotation(U_16 cfrCPIndex) const { return getROMClassCPIndex(cfrCPIndex); }
```
These are used interchangeably.  Pull request #1594 adds getROMClassCPIndexForAnnotationWithCheck() to handle malformed annotations. 

getROMClassCPIndexForAnnotation() can be deprecated and removed.

FYI @fengxue-IS

**Comment by DanHeidinga** [comment]
Is there a reason #1594 doesn't reuse getROMClassCPIndexForAnnotation()?

**Comment by fengxue-IS** [comment]
@DanHeidinga `getROMClassCPIndexForReference / getROMClassCPIndexForAnnotation` are used interchangeably at different locations without any relation to the name, new one is added to make the purpose clear. I've opened #1598 to clean up all the redundant/duplicate code
