### ISSUE TITLE
There should be a warning if sharedclasses module presents but dll failed to be loaded

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9#162]
In the cases when the j9shr29 dll failed to be loaded,

1) if -Xshareclasses is used in the command line, there will be a fatal error message saying that libj9shr29.so is not loaded:
```
java -Xshareclasses -version
JVMJ9VM011W Unable to load j9shr29: /openj9/xa6490_openj9/jdk/lib/compressedrefs/libj9shr29.so: cannot open shared object file: No such file or directory
JVMJ9VM004E Cannot load library required by: -Xshareclasses
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

2) if -Xshareclasse is not used in the command line, we will proceed, silently ignoring that j9shr29 dll is not loaded.
```
java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170927_365380 (JIT enabled, AOT enabled)
OpenJ9   - 178f1e9
OMR      - 2d351f7
OpenJDK  - a3670d2 based on jdk-9+181)
```

In case 2, we should only silently ignore the dll loading failure if module openj9.sharedclasses is not in the Jimage. A warning message should be printed out if module openj9.sharedclasses presents in the Jimage.

**Comment by pshipton** [comment]
The design accommodates jlink'ed images, which may be missing both the openj9.sharedclasses module and the j9shr native library. Case 2 covers that the j9shr library is loaded to enable the utility APIs in com.ibm.oti.shared.SharedClassUtilities even when -Xshareclasses is not specified (except in the case of -Xshareclasses:none which doesn't load the j9shr library anyway).

**Comment by hangshao0** [comment]
I will have a fix for this one.
