### ISSUE TITLE
Tools like jstack not working with OpenJDK 8-OpenJ9

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1621]
Issue was raised at Adopt: https://github.com/AdoptOpenJDK/openjdk-build/issues/292

Should we support the OpenJDK J* diagnostic tools?

**Comment by DanHeidinga** [comment]
FYI @Param-S - I've raised the question here at OpenJ9 for further discussion.

**Comment by Param-S** [comment]
https://github.com/apache/incubator-openwhisk/pull/3504  Project is interested to use AdoptOpenJDK OpenJ9. But, there is some resistance due to the community is familiar with J* diagnostics tools.

**Comment by DanHeidinga** [comment]
@Param-S which J* tools are they using?  Are some essential for their workflows?

**Comment by DanHeidinga** [comment]
Two pieces of data we need:
* The top used / most important j* tools - allowing us to prioritize the implementation plan
* Any data on tool lifecycles - are the any of the tools deprecated / removed in later OpenJDK releases?

We don't want to implement tools that will be removed shortly.

**Comment by DanHeidinga** [comment]
https://docs.oracle.com/javase/9/docs/api/jdk.jcmd-summary.html

Describes the jdk.jcmd module which includes:
jcmd, jinfo, jmap, jps, jstack, jstat

All of the tools are listed as experimental and unsupported... but they've been listed that way for years so I don't think that tells us anything yet.

**Comment by pdbain-ibm** [comment]
I am under the impression that jcmd uses late attach (i.e. attach API), while the other tools do not.  Is that correct?

**Comment by ashu-mehra** [comment]
Another tool in this space is JDK Mission Control which will likely be open-sourced soon as per http://mail.openjdk.java.net/pipermail/discuss/2018-March/004715.html.

**Comment by DanHeidinga** [comment]
@ashu-mehra Mission Control is really cool.  The historical alternative has been HealthCenter.  

I'd like to keep this particular issue focused on which commandline tools to support with OpenJ9 so we don't try to boil the ocean in one go.

**Comment by sxa555** [comment]
Tagging in @cwsolee as she raised https://github.com/AdoptOpenJDK/openjdk-build/issues/345 which I've now closed

**Comment by pshipton** [comment]
#2112 asked about jstat and jinfo.

**Comment by Ali-Ni** [comment]
I briefly looked into each of these commands and how they are implemented in the openjdk extensions:

jps:
jps reads files in `hsperf_${username}` folder (temp files generated by hotspot, folder is found in `/tmp` on linux) to get lvmid and other general VM information. This is strictly specific to HotSpot’s implementation. I wasn't sure of the copyright/legal concerns regarding this so I didn't dig too deep in looking into these files' format and contents. 

jstack:
jstack uses implementation specific `HotSpotVirtualMachine.remoteDataDump`. The VM is cast as a `HotSpotVirtualMachine` before this is called, so even if an equivalent/similar stack dump method by this name is implemented in OpenJ9, some minimal changes would have to be made to the openjdk extensions. 

jcmd:
Similar to jstack - vm is cast as `HotSpotVirtualMachine` before calling implementation specific method `HotSpotVirtualMachine.executeJCmd` with a parameter that depends on the command option passed to jcmd.

jinfo:
Shortcut for a subset of jcmd commands through an implementation specific `VirtualMachine.executeCommand` method.

jmap:
Half of the options are shortcuts for jcmd (almost identical to jinfo). Other half are other data dumps that are internally implemented in HotSpot.

jstat
Same as jps (reads from HotSpot temp files)

**Comment by Ali-Ni** [comment]
Sorry, I should have been more clear - what I trying to get across was that since the temp files are read in the extensions, it is the extensions that must be changed, and simply implementing an API in OpenJ9 isn't enough (unless we want to implement the hsperf files).

**Comment by pshipton** [comment]
Understood. My point was that in order to provide a jps implementation for OpenJ9 we don't need to run the existing extensions code. We can create a jps implementation that runs different code and has a OpenJ9 specific implementation.

**Comment by pdbain-ibm** [comment]
You don't even need OpenJ9 specific code. This code (which I threw together ~10 years ago :-) ) does what you want, I believe (modulo the class name and the verbosity):
`
import java.util.List;

import com.sun.tools.attach.VirtualMachineDescriptor;
import com.sun.tools.attach.spi.AttachProvider;

public class listvms {

	public static final String LIST_VMS_EXIT = "listVms:exit";


	public static void main(String[] args) {
			listVms();
	}

	
	private static void listVms() {
		List<AttachProvider> providers = AttachProvider.providers();
		AttachProvider ap = providers.get(0);
		if (null == ap) {
			System.err.println("no attach providers available");
		}
		List <VirtualMachineDescriptor> vmds = ap.listVirtualMachines();
		System.out.println("looking for attach targets");
		for (VirtualMachineDescriptor vmd: vmds) {
			System.out.println("id: "+vmd.id()+" name: "+vmd.displayName());
		}
		System.out.println(LIST_VMS_EXIT);
	}

}
`

**Comment by DanHeidinga** [comment]
Closing this as a dup of https://github.com/eclipse/openj9/issues/4655 Note, several of the tools have already been implemented
