### ISSUE TITLE
Slackin appears to be broken

### ISSUE THREAD

**Issue by adleong** [eclipse/openj9#1629]
The [join slack](https://www.eclipse.org/openj9/oj9_joinslack.html) webpage displays a blank box instead of an area where an email can be entered.

[logs](https://zeit.co/XeTDEytpeuiDVRRChqWrCGQs/slackin/ozuyyvpmac/logs) suggest an issue starting slackin:

```
> slackin@0.14.0 start /home/nowuser/src
> chmod +x bin/slackin && ./bin/slackin

03/29 02:38 PM (8d)

chmod: bin/slackin: No such file or directory
```

**Comment by fjeremic** [comment]
Seems like an https://github.com/eclipse/openj9-website/ issue. @SueChaplain can you please take a look at this?

**Comment by DanHeidinga** [comment]
FYI @doveye Are you able to help with getting slackin working again?

**Comment by DanHeidinga** [comment]
I have access to the `now` deployment tool but can't restart the app from an error state.

https://github.com/rauchg/slackin/issues/319 seems to be related.  Trying to figure out how to update our slackin instance now (really should doc this somewhere....)

**Comment by DanHeidinga** [comment]
I've opened a PR against the website to update the page.  While waiting for that to land, please use this URL to join slack: slackin-eqftwddakt.now.sh

**Comment by adleong** [comment]
thanks!
