### ISSUE TITLE
Bad syncObject in OSR decompilation

### ISSUE THREAD

**Issue by gacholio** [eclipse/openj9#1637]
Regarding the crash reported in #1572, the cause of the crash is a NULL syncObject when executing a syncReturn bytecode.  The frame was recently decompiled using OSR, which filled in the bad syncObject.

The core can be found in /team/danh/openj9/pr1572/server1/dumps.

There would seem to be two possibilities:

1) The OSR code is not copying the syncObject correctly
2) The JIT is not maintaining the syncObject slot in its stack frame

Someone needs to examine the generated OSR code relevant to PC 0x00007F4A10DCC56D (see below).

Analysis:

<27d1b00> Bytecode frame: bp = 0x0000000003BE8A98, sp = 0x0000000003BE8A80, pc = 0x00007F4A2C41C463, cp = 0x000000000071D100, arg0EA = 0x0000000003BE8AA8, flags = 0x0000000000000000
<27d1b00>     Method: java/io/BufferedInputStream.read()I !j9method 0x000000000071D778
<27d1b00>     Bytecode index = 27
<27d1b00>     Sync object for synchronized method
<27d1b00>         Sync O-Slot[0x0000000003BE8AA0] = 0x0000000000000000
<27d1b00>     Using local mapper
<27d1b00>     Locals starting at 0x0000000003BE8AA8 for 0x0000000000000001 slots
<27d1b00>         I-Slot: a0[0x0000000003BE8AA8] = 0x00000007FEA9D6F8
<27d1b00>     Pending stack starting at 0x0000000003BE8A80 for UDATA(0x0000000000000001) slots
<27d1b00>         I-Slot: p0[0x0000000003BE8A80] = 0x00000007FFFFFFFF
> !bytecodes 0x000000000071D778
  Name: read
  Signature: ()I
  Access Flags (10070021): public synchronized
  Max Stack: 5
  Thrown Exceptions (1):
java/io/IOException  Argument Count: 1
  Temp Count: 0
    0 aload0getfield
    1 getfield 21 java/io/BufferedInputStream.pos I
    4 aload0getfield
    5 getfield 29 java/io/BufferedInputStream.count I
    8 ificmplt 28
   11 aload0
   12 invokespecial 32 java/io/BufferedInputStream.fill()V
   15 aload0getfield
   16 getfield 21 java/io/BufferedInputStream.pos I
   19 aload0getfield
   20 getfield 29 java/io/BufferedInputStream.count I
   23 ificmplt 28
   26 iconstm1
   27 syncReturn1
   28 aload0
   29 invokespecial 20 java/io/BufferedInputStream.getBufIfOpen()[B
   32 aload0
   33 dup
   34 getfield 21 java/io/BufferedInputStream.pos I
   37 dupx1
   38 iconst1
   39 iadd
   40 putfield 21 java/io/BufferedInputStream.pos I
   43 baload
   44 sipush 255
   47 iand
   48 syncReturn1
> !j9vmthread 0x27d1b00 | grep last
    0x948: struct J9JITDecompilationInfo * lastDecompilation = !j9jitdecompilationinfo 0x00007F49A419A460
> !j9jitdecompilationinfo 0x00007F49A419A460
J9JITDecompilationInfo at 0x7f49a419a460 {
  Fields for J9JITDecompilationInfo:
    0x0: struct J9JITDecompilationInfo * next = !j9jitdecompilationinfo 0x0000000000000000
    0x8: UDATA * bp = !j9x 0x0000000003BE8A98
    0x10: U8 * pc = !j9x 0x00007F4A10DCC56D
    0x18: U8 ** pcAddress = !j9x 0x0000000003BE8A38
    0x20: struct J9Method * method = !j9method 0x000000000071D778 // java/io/BufferedInputStream.read()I
    0x28: UDATA reason = 0x0000000000000088 (136)
    0x30: UDATA usesOSR = 0x0000000000000001 (1)
    0x38: struct J9OSRBuffer osrBuffer = !j9osrbuffer 0x00007F49A419A498
}
> !j9osrbuffer 0x00007F49A419A498
J9OSRBuffer at 0x7f49a419a498 {
  Fields for J9OSRBuffer:
    0x0: UDATA numberOfFrames = 0x0000000000000001 (1)
    0x8: void * jitPC = !j9x 0x00007F4A10DCC56D
}
> !j9osrframe 0x7f49a419a4A8
J9OSRFrame at 0x7f49a419a4a8 {
  Fields for J9OSRFrame:
    0x0: UDATA flags = 0x0000000000000000 (0)
    0x8: struct J9Method * method = !j9method 0x000000000071D778 // java/io/BufferedInputStream.read()I
    0x10: UDATA bytecodePCOffset = 0x000000000000000C (12)
    0x18: UDATA numberOfLocals = 0x0000000000000002 (2)
    0x20: UDATA maxStack = 0x0000000000000005 (5)
    0x28: UDATA pendingStackHeight = 0x0000000000000000 (0)
    0x30: struct J9MonitorEnterRecord * monitorEnterRecords = !j9monitorenterrecord 0x00007F49C80574B0
}
> !j9vmthread 0x27d1b00 | grep monitorEnterRecords
    0x2f8: struct J9MonitorEnterRecord * monitorEnterRecords = !j9monitorenterrecord 0x00007F49C80574B0
> !j9monitorenterrecord 0x00007F49C80574B0
J9MonitorEnterRecord at 0x7f49c80574b0 {
  Fields for J9MonitorEnterRecord:
    0x0: j9object_t object = !j9object 0x00000007FEA9D6F8 // java/io/BufferedInputStream
    0x8: UDATA * arg0EA = !j9x 0x00000000000002F8
    0x10: UDATA dropEnterCount = 0x0000000000000001 (1)
    0x18: struct J9MonitorEnterRecord * next = !j9monitorenterrecord 0x0000000000000000
}
> !j9x 0x7f49a419a4E0,40,8
0x7F49A419A4E0 :  0000000000000000 0000000000000000 [ ................ ]
0x7F49A419A4F0 :  0000000000000000 0000000000000000 [ ................ ]
0x7F49A419A500 :  0000000000000000 0000000000000000 [ ................ ]
0x7F49A419A510 :  00000007fea9d6f8 10e7ad16b7654321 [ ........!Ce..... ]
 
First 5 slots are for the maxStack, which are unused at this point.  Next two are the locals (syncObject then receiver).  Everything else looks OK, it's just the 0 in the syncObject that's the problem.

**Comment by andrewcraik** [comment]
@cathyzhyi this would seem close to your areas of expertise - any ideas which of 1 or 2 is going wrong?

**Comment by gacholio** [comment]
A trivial testcase to reproduce this worked correctly, but I didn't play around with opt levels, so it's worth checking that for the affected method as well.

**Comment by DanHeidinga** [comment]
@cathyzhyi Any update on this?

**Comment by cathyzhyi** [comment]
From the coredump, osrCatch block loaded "this" from an uninitialized slot and stored the unitialized value into the syn object slot. Weird thing is that the same register is stored into the receiver slot but the receiver slot got the correct value. My guess is that VM can figure out receiver and fix that slot?
```
0x7f4a10dcc59a +202 mov       rax, qword ptr [rsp+0x40] <<< *Unreachable*  osrCatchblock <----load rax from an uninitialized slot
......
0x7f4a10dcc5bd +237 lea       ecx, dword ptr [r12+0x68]
0x7f4a10dcc5c2 +242 movsxd    rcx, ecx
0x7f4a10dcc5c5 +245 mov       qword ptr [rcx+rdx], rax #store receiver into buffer
0x7f4a10dcc5ca +250 lea       ecx, dword ptr [r12+0x60]
0x7f4a10dcc5cf +255 movsxd    rcx, ecx
0x7f4a10dcc5d2 +258 mov       qword ptr [rcx+rdx], rax #store sync obj into buffer

!j9x 0x7f49a419a4E0,40,8
0x7F49A419A4E0 : 0000000000000000 0000000000000000 [ ................ ]
0x7F49A419A4F0 : 0000000000000000 0000000000000000 [ ................ ]
0x7F49A419A500 : 0000000000000000 0000000000000000 [ ................ ] (0x60 syn object slot)
0x7F49A419A510 : 00000007fea9d6f8 (0x68 receiver object slot) 10e7ad16b7654321 [ ........!Ce..... ]
```

Not sure how reproduceable this problem is. We need to get a jit tracing log of this failing method for further investigation. The java options is -Xjit:{java/io/BufferedInputStream.read()I}(log=PATHTOLOG/log,tracefull)

**Comment by urisimchoni** [comment]
I'll try to reproduce with -Xjit:{java/io/BufferedInputStream.read()I}(log=/path/to/log,tracefull)
Hopefully will get to it early  next week.
Thanks,
Uri

**Comment by urisimchoni** [comment]
For some reason it stopped reproducing :( will try some more in following days.

**Comment by cathyzhyi** [comment]
@urisimchoni Is it the tracing options that stops the failure? Does it fail when you remove the -Xjit options?

**Comment by vijaysun-omr** [comment]
@urisimchoni any further update on recreating this failure ?

**Comment by urisimchoni** [comment]
@vijaysun-omr No, sorry, haven't gotten to it yet. I'll give it another shot before Monday.
Thanks,
Uri.

**Comment by urisimchoni** [comment]
It reproduces reliably without the extra -Xjit tracing parameters, and does not reproduce with the parameters. If there's no other tracing combination to try, I can set up a VM in aws (it's a WebSphere traditional with PBW app, and some added Java and native agents that trigger the issue). Alternatively / additionally, given access to a Linux machine with WebSphere and PBW installed, I can add the "missing" components.

**Comment by cathyzhyi** [comment]
@urisimchoni could you point me to the logs from a passing run with tracing parameters? Let's see if we can find some clues there. You should be able to find the logs with name in the following format `log.xxxxx.xxxxx.YYYYMMDD.xxxxxx.$PID` and `blog.YYYYMMDD.xxxxxx.$PID`. 

Also, could you try to use `-Xjit:{java/io/BufferedInputStream.read()I}(log=/path/to/log,tracefull,traceOSR),vlog=/path/to/vlog,verbose={osr*}` which removes `prepareForOSREvenIfThatDoesNothing ` from the previous option and should add less overhead than the previous one as well. Hopefully the failure can be reproduced with this tracing option. Thanks!

**Comment by urisimchoni** [comment]
The logs are here:
https://drive.google.com/drive/folders/1vEO64-s93sGAQiVsbubbCKcGm4gEjBSj?usp=sharing

Removing prepareForOSREvenIfThatDoesNothing didn't change things - it doesn't crash

A bit more background - the scenario is to open a JMX RMI connection and send a command to a Java agent, which, in turn, calls a native method in a native JVMTI agent. The JVMTI agent scans all loaded classes and installs some field watches, and when it's done it returns, and the MBean returns. At this point the JMX client closes the connection, and *after* that I see the JVM process is gone. So probably the relation to BufferedInputStream is the RMI server doing IO, but after some field watches were installed.

**Comment by andrewcraik** [comment]
@cathyzhyi any update on this?

**Comment by cathyzhyi** [comment]
In mimicInterpreterFrame shape the method monitor slot is treated as an extra auto slot and there is no real used in the java bytecode of this auto slot and therefore OSRLiveRangeAnalysis conclude this auto slot is dead and zeroed that slot out. Disable OSRLiveRangeAnalysis for interpreter frame shape since it's not really needed. The fix is in https://github.com/eclipse/omr/pull/2881.

**Comment by gacholio** [comment]
OMR change has been merged,
