### ISSUE TITLE
-Xshareclasses unique id unsupported by OpenJ9 builds

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1645]
The -Xshareclasses unique build id generation is specific to the IBM internal build process and needs to be fixed to support the OpenJ9 build process.

-Xshareclasses uses a unique build id to identify which JVM created the shared cache. If a JVM with a different build id attempts to attach to the cache, the cache is destroyed (when possible) and recreated. This mechanism helps avoid stale entries in the cache, and incompatibilities that can occur in the rom class representation as the implementation is changed.

**Comment by hangshao0** [comment]
I will use the OpenJ9 SHA (J9VM_VERSION_STRING)  to distinguish between different builds.
