### ISSUE TITLE
cmdLineTester_getCallerClassTests_SE90_0 failed in Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#1659]
cmdLineTester_getCallerClassTests_SE90_0 failed in Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le

https://ci.eclipse.org/openj9/job/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/7/

getCallerClassTests_SE100.xml is missing.

```
cmdLineTester_getCallerClassTests_SE90_0 Start Time: Wed Apr 11 07:00:51 2018 Epoch Time (ms): 1523430051232
test with NoOptions
{ "/home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/jdk/bin/java"  -Xcompressedrefs  -Xdump -DRESJAR="/home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/cmdline_options_testresources/cmdlinetestresources.jar" -DEXE='"/home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/jdk/bin/java"  -Xcompressedrefs  -Xdump --add-exports=java.base/com.ibm.oti.vm=ALL-UNNAMED --add-exports java.base/jdk.internal.reflect=ALL-UNNAMED' -jar "/home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/cmdline_options_tester/cmdlinetester.jar" -config "/home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/cmdLineTests/getCallerClassTests/getCallerClassTests_SE100.xml" -explainExcludes -nonZeroExitWhenError; \
	if [ $? -eq 0 ] ; then echo ""; echo "cmdLineTester_getCallerClassTests_SE90_0""_PASSED"; echo ""; else echo ""; echo "cmdLineTester_getCallerClassTests_SE90_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15234275352030/TestTargetResult";
java.io.FileNotFoundException: /home/jenkins/jenkins-agent/workspace/Test-Extended-JDK10-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/cmdLineTests/getCallerClassTests/getCallerClassTests_SE100.xml (No such file or directory)
	at java.io.FileInputStream.open0(java.base@10-internal/Native Method)
	at java.io.FileInputStream.open(java.base@10-internal/FileInputStream.java:220)
	at java.io.FileInputStream.<init>(java.base@10-internal/FileInputStream.java:158)
	at java.io.FileInputStream.<init>(java.base@10-internal/FileInputStream.java:113)
	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:455)
	at TestConfigParser.runTests(TestConfigParser.java:75)
	at MainTester.main(MainTester.java:106)
java.lang.NullPointerException
	at java.io.Reader.<init>(java.base@10-internal/Reader.java:82)
	at java.io.InputStreamReader.<init>(java.base@10-internal/InputStreamReader.java:72)
	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:468)
	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)
	at TestConfigParser.runTests(TestConfigParser.java:75)
	at MainTester.main(MainTester.java:106)
Exception in thread "main" java.lang.NullPointerException
	at MainTester.main(MainTester.java:107)
```

**Comment by llxia** [comment]
jsr292_InDynTest_0 and jsr292_InDynTest_1 have same missing file issue.

**Comment by llxia** [comment]
Please also take a look at the rest failure in jdk10. Thanks.
TestAttachAPI_SE90_0
testSCCMLTests2_1
TestSunAttachClasses_SE90_0
VmArgumentTests_0

**Comment by DanHeidinga** [comment]
@llxia @renfeiw Any update on this?

**Comment by llxia** [comment]
PR #1672
I think this can be close.. @renfeiw , can you confirm?

**Comment by renfeiw** [comment]
The extended build should run green now. All failures are fixed. @pdbain-ibm Could you please take a look at the VmArgumentTests_0 testExecutableJarArguments and testJarArguments test? Looks like the test code needs to be updated to support SE100. I have excluded them right now in the latest_exclude_SE100.xml.

**Comment by pdbain-ibm** [comment]
This line in VmArgumentTests needs updating:
```
		vmargsJarFilename = isJava8? "vmargs_SE80.jar": "vmargs_SE90.jar";
```
Currently I have an ad-hoc test for Java version:

> 		isJava8 = JAVA_VERSION.startsWith("1.8.0");
That needs updating.

**Comment by pshipton** [comment]
Why does it need updating? Checking if the java.version system property starts with "1.8.0" is still valid.

**Comment by pshipton** [comment]
If you mean to check for Java 9, 10, etc. then if its not Java 8, it will start with 9, 10, 11, etc.

**Comment by DanHeidinga** [comment]
If you want a better version check, look at something like: https://github.com/eclipse/openj9/pull/1696

**Comment by pdbain-ibm** [comment]
This code doesn't handle Java 10 or later.

**Comment by DanHeidinga** [comment]
> This code doesn't handle Java 10 or later.

Does `this code` refer to #1696 or the `startsWith(...` code?

**Comment by pdbain-ibm** [comment]
https://github.com/eclipse/openj9/pull/1696 will come in handy here.

**Comment by pdbain-ibm** [comment]
@DanHeidinga 

> Does this code refer to #1696 or the startsWith(... code?

I was referring to the startsWith code which was written pre-Java 9.  I hacked in a variant of your algorithm to verify it.

**Comment by pdbain-ibm** [comment]
@smlambert I have regression tested my change with #1696 on Java 8 & 9.  Would you kindly run a Java 10 build on https://github.com/eclipse/openj9/pull/1706.  
Many thanks 
-p

**Comment by llxia** [comment]
Close this issue as the problem is fixed.
