### ISSUE TITLE
Rename 'java.lang.string.substring.share' to 'java.lang.string.substring.nocopy'

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#166]
Keeping the original option provides backwards compatibility to anyone who has been running with the old option.

See https://github.com/eclipse/openj9/pull/147 for change to create the new option

**Comment by fjeremic** [comment]
This issue can now be closed. Fixed in #167.

**Comment by pshipton** [comment]
FYI https://help.github.com/articles/closing-issues-using-keywords/

**Comment by fjeremic** [comment]
> FYI https://help.github.com/articles/closing-issues-using-keywords/

@pshipton I wanted to do this in the commit description but it was against the commit guidelines:
https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md#commit-guidelines

Which say to use the:

> Issue: #166

format. I would have much rather specified "Fixes #166" instead but I wanted to conform to the commit guidelines. Should we modify the guidelines to accept the keywords recognized by GitHub? I would love to use this feature but I don't think I understand the best way given our current guidelines.

**Comment by pshipton** [comment]
Thanks for pointing it out. I'm not sure if we intentionally intended to disallow using keywords to close the issue. I'll check with others and if necessary update the guidelines.
