### ISSUE TITLE
Assertion failed while launching a liberty app using -Xdump:dynamic 

### ISSUE THREAD

**Issue by chandrams** [eclipse/openj9#1694]
Launching a liberty application using -Xdump:dynamic failed with assertion failed as below.

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build master-4ecf7846, JRE 1.8.0 Linux amd64-64 Compressed References 20180411_144 (JIT enabled, AOT enabled)
OpenJ9   - 4ecf7846
OMR      - cb9e24de
JCL      - 580e5327 based on jdk8u162-b12)

```
chandrams@j9x3650m4:~$ ./wlp/bin/server run
Launching defaultServer (Open Liberty 17.0.0.3/wlp-1.0.18.cl170320170927-1854) on Eclipse OpenJ9 VM, version 1.8.0_162-b12 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://9.109.121.179:9080/ROOT/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://9.109.121.179:9080/ibm/api/
[AUDIT   ] CWWKZ0001I: Application ROOT started in 0.274 seconds.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://9.109.121.179:9080/IBMJMXConnectorREST/
[AUDIT   ] CWWKF0012I: The server installed the following features: [jsp-2.3, servlet-3.1, restConnector-2.0, ssl-1.0, monitor-1.0, jndi-1.0, json-1.0, distributedMap-1.0, el-3.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
10:11:42.452 0x1d09600    j9vm.249    *   ** ASSERTION FAILED ** at BytecodeInterpreter.hpp:8544: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/04/16 15:41:42 - please wait.
JVMDUMP032I JVM requested System dump using '/home/chandrams/wlp/usr/servers/defaultServer/core.20180416.154142.20620.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.20709.

JVMDUMP010I System dump written to /home/chandrams/wlp/usr/servers/defaultServer/core.20180416.154142.20620.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/chandrams/wlp/usr/servers/defaultServer/javacore.20180416.154142.20620.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/chandrams/wlp/usr/servers/defaultServer/javacore.20180416.154142.20620.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/chandrams/wlp/usr/servers/defaultServer/Snap.20180416.154142.20620.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/chandrams/wlp/usr/servers/defaultServer/Snap.20180416.154142.20620.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```

**Comment by DanHeidinga** [comment]
@chandrams Does a simple `java -Xdump:dynamic -version` assert as well?

**Comment by chandrams** [comment]
No, java -Xdump:dynamic -version this works fine. No other dump options are present. 
I have only exported JVM_ARGS="-Xdump:dynamic"

**Comment by JasonFengJ9** [comment]
@chandrams can you provide the steps to reproduce the assertion failure?

I just tried `Open Liberty sample-getting-started.git ` within a docker container against `Eclipse OpenJ9 VM (build master-40bbbfc9, JRE 1.8.0 Linux amd64-64 Compressed References 20180425_153` along with `export IBM_JAVA_OPTIONS=-Xdump:dynamic`. I don't observe such assertion, and navigating the same app web seems successful.

**Comment by chandrams** [comment]
@JasonFengJ9 Issue seems to be intermittent. I tried recreating it but didn't succeed. I had encountered this issue initially while running in a docker container. Tried with the docker container I can see it happen again.

**Comment by chandrams** [comment]
Please try your app with this export JVM_ARGS="-Xdump:dynamic"

**Comment by JasonFengJ9** [comment]
**Update**:
Tried the `JVM_ARGS`, wasn't able to reproduce the issue reported.
@chandrams, can you re-run the test with latest JVM from https://adoptopenjdk.net/nightly.html?

**Comment by chandrams** [comment]
It still fails  with the latest nightly build too, but the issue is intermittent.

Launching defaultServer (Open Liberty 17.0.0.4/wlp-1.0.19.201712061531) on Eclipse OpenJ9 VM, version 1.8.0_181-b13 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKS4104A: LTPA keys created in 0.850 seconds. LTPA key file: /opt/ol/wlp/output/defaultServer/resources/security/ltpa.keys
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://23ecea0f76a8:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://23ecea0f76a8:9080/ROOT/
[AUDIT   ] CWWKZ0001I: Application ROOT started in 0.344 seconds.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://23ecea0f76a8:9080/IBMJMXConnectorREST/
[AUDIT   ] CWWKF0012I: The server installed the following features: [jsp-2.3, servlet-3.1, restConnector-2.0, ssl-1.0, monitor-1.0, jndi-1.0, json-1.0, distributedMap-1.0, el-3.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
14:40:59.789 0x1ca3a00    j9vm.249    *   ** ASSERTION FAILED ** at BytecodeInterpreter.hpp:8622: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/08/24 14:40:59 - please wait.
JVMDUMP032I JVM requested System dump using '/opt/ol/wlp/output/defaultServer/core.20180824.144059.1.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.119.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 119 was not found. Expected to find core file with name "/opt/ol/wlp/output/defaultServer/core"
JVMDUMP032I JVM requested Java dump using '/opt/ol/wlp/output/defaultServer/javacore.20180824.144059.1.0002.txt' in response to an event
JVMDUMP010I Java dump written to /opt/ol/wlp/output/defaultServer/javacore.20180824.144059.1.0002.txt
JVMDUMP032I JVM requested Snap dump using '/opt/ol/wlp/output/defaultServer/Snap.20180824.144059.1.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /opt/ol/wlp/output/defaultServer/Snap.20180824.144059.1.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".


openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
Eclipse OpenJ9 VM (build master-b8498479, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180821_296 (JIT enabled, AOT enabled)
OpenJ9   - b8498479
OMR      - 2a08e96a
JCL      - 2b004fdb based on jdk8u181-b13)

Follow the below steps:

1) git clone -b helloworldapp git@github.ibm.com:chandra-ms/cloud-squad-tools.git
2) cd cloud-squad-tools/HelloWorldApp/libertyimage
3) ./build.sh
4) cd ..
5) ./build.sh
6) ./run.sh

**Comment by chandrams** [comment]
Able to recreate the issue outside docker container too, but as mentioned issue is intermittent

java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
Eclipse OpenJ9 VM (build master-6bed9018, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180823_298 (JIT enabled, AOT enabled)
OpenJ9   - 6bed9018
OMR      - 5d1ca9d4
JCL      - 2b004fdb based on jdk8u181-b13)


 ./wlp/bin/server run
Launching defaultServer (Open Liberty 17.0.0.4/wlp-1.0.19.201712061531) on Eclipse OpenJ9 VM, version 1.8.0_181-b13 (en_IN)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
14:57:54.345 0x1ea4600    j9vm.249    *   ** ASSERTION FAILED ** at BytecodeInterpreter.hpp:8627: ((0 ))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/08/24 20:27:54 - please wait.
JVMDUMP032I JVM requested System dump using '/home/chandrams/AdoptOpenJDK/git/Xdynamic-crash/wlp/usr/servers/defaultServer/core.20180824.202754.25978.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.26060.

JVMDUMP010I System dump written to /home/chandrams/AdoptOpenJDK/git/Xdynamic-crash/wlp/usr/servers/defaultServer/core.20180824.202754.25978.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/chandrams/AdoptOpenJDK/git/Xdynamic-crash/wlp/usr/servers/defaultServer/javacore.20180824.202754.25978.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/chandrams/AdoptOpenJDK/git/Xdynamic-crash/wlp/usr/servers/defaultServer/javacore.20180824.202754.25978.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/chandrams/AdoptOpenJDK/git/Xdynamic-crash/wlp/usr/servers/defaultServer/Snap.20180824.202754.25978.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/chandrams/AdoptOpenJDK/git/Xdynamic-crash/wlp/usr/servers/defaultServer/Snap.20180824.202754.25978.0003.trc


Follow the below steps:

1) Download and extract open liberty zip in current dir, where the cloud-squad-tools is cloned
2) cp ./cloud-squad-tools/HelloWorldApp/server.xml ./wlp/usr/servers/defaultServer
3) cp ./cloud-squad-tools/HelloWorldApp/HelloWorld.war ./wlp/usr/servers/defaultServer/dropins/ROOT.war
4) cp ./cloud-squad-tools/HelloWorldApp/keystore.jks  ./wlp/usr/servers/defaultServer/resources/security/keystore.jks
5) export JVM_ARGS="-Xdump:dynamic"
6) ./wlp/bin/server run

**Comment by ChengJin01** [comment]
I will double-check to see whether it can be reproduced with the latest nightly build.

**Comment by ChengJin01** [comment]
I already tried with Open Liberty 18.0.0.4 with the latest nightly build and Open Liberty 17.0.0.4 with latest build at https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12_openj9-0.11.0/OpenJDK8U-jdk_x64_linux_openj9_8u192b12_openj9-0.11.0.tar.gz but nothing wrong happened after restarting many times.

```
/tmp $ echo $JVM_ARGS
-Xdump:dynamic

/tmp $ ./wlp/bin/server run

Launching defaultServer (Open Liberty 18.0.0.4/wlp-1.0.23.20181210-1300) on Eclipse OpenJ9 VM, version 1.8.0_192-201812100430-b12 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ROOT/
[AUDIT   ] CWWKZ0001I: Application ROOT started in 0.614 seconds.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/IBMJMXConnectorREST/
[AUDIT   ] CWWKF0012I: The server installed the following features: [jsp-2.3, servlet-3.1, restConnector-2.0, ssl-1.0, monitor-1.0, jndi-1.0, json-1.0, distributedMap-1.0, el-3.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
^C[AUDIT   ] CWWKE0085I: The server defaultServer is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ROOT/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ibm/api/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/IBMJMXConnectorREST/
[AUDIT   ] CWWKZ0009I: The application ROOT has stopped successfully.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 3 minutes, 26.366 seconds.


./wlp/bin/server run
Launching defaultServer (Open Liberty 17.0.0.4/wlp-1.0.19.201712061531) on Eclipse OpenJ9 VM, version 1.8.0_192-b12_openj9 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ROOT/
[AUDIT   ] CWWKZ0001I: Application ROOT started in 0.725 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [jsp-2.3, servlet-3.1, restConnector-2.0, ssl-1.0, monitor-1.0, jndi-1.0, json-1.0, distributedMap-1.0, el-3.0].
[AUDIT   ] CWWKF0011I: The server defaultServer is ready to run a smarter planet.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/IBMJMXConnectorREST/
^C[AUDIT   ] CWWKE0085I: The server defaultServer is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ROOT/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/ibm/api/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://rhel6x64vm6.ottawa.ibm.com:9080/IBMJMXConnectorREST/
[AUDIT   ] CWWKZ0009I: The application ROOT has stopped successfully.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 4 minutes, 20.959 seconds.

```

**Comment by pshipton** [comment]
Closing, as the problem could not be reproduced and no diagnostic files were provided. If it still occurs on the latest, please provide more details, or the diagnostic files which are output from the crash.
