### ISSUE TITLE
wget dependent *.jar in getDependencies.pl  get "ERROR: sha1 sum check error." on Windows

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#1736]
Using getDependencies.pl to get dependent jars all jars got "ERROR: sha1 sum check error." on Windows. Following is asm-all.jar error:

20:40:59 downloading dependent third party jars to C:/Users/jenkins/workspace/openjdk_test_x86-64_windows/openjdk-tests/\\TestConfig\\lib 
20:40:59 downloading http://central.maven.org/maven2/org/ow2/asm/asm-all/6.0_BETA/asm-all-6.0_BETA.jar 
20:40:59 ERROR: sha1 sum check error. 
20:40:59 --> file downloaded to C:/Users/jenkins/workspace/openjdk_test_x86-64_windows/openjdk-tests/\\TestConfig\\lib\asm-all.jar 
20:40:59 Expected sha1 is: 535f141f6c8fc65986a3469839a852a3266d1025, 
20:40:59 Actual sha1 is  : f2f8bdd51f1a5280c7874af519fdf6425431cecd.

**Comment by smlambert** [comment]
I believe that we disabled this check of the sha1 for non-Windows for the asm-all.jar file (see #285), as we take a newly built one often, and therefore do not have lock on one particular jar file to check against.  Likely we should do the same for the Windows build?

**Comment by keithc-ca** [comment]
I think this is fixed by https://github.com/eclipse/openj9/pull/2454. @sophia-guo please close if you agree.

**Comment by sophia-guo** [comment]
This is still issue on windows without cygwin as default cmd. https://github.com/AdoptOpenJDK/openjdk-tests/issues/499. We do have a correctly configured windows machine test-azure-win2012r2-x64-1 now in AdoptOpenJDK and temporarily disabled problematic machine test-packet-x64-windows-2012r2-1. 

As Windows with cygwin is a prerequisite for openj9 and AdopetOpenJDK test project this should not be an issue. Close it.
