### ISSUE TITLE
[Jenkins] Git checkout failing because file name too long

### ISSUE THREAD

**Issue by taliamccormick** [eclipse/openj9#1737]
`git checkout` within a PR build fails with:
```
hudson.plugins.git.GitException: Command "git checkout -f dbc8b623365f7464fb5fbefe6a35f3616bfc4f18" returned status code 1:
stdout: 
stderr: error: unable to create file test/functional/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/PartitioningURLClassPathHelperURLHelperStaleEntryCompatabilityTest.java: Filename too long
error: unable to create file test/functional/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/PartitioningURLHelperURLClassPathHelperStaleEntryCompatabilityTest.java: Filename too long
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  0857b81d Merge 9e08d57a86732562c81520ac31efe0e97900ee15 into aae933eb81c36de7f82c533ca0114034575db9ba
```
(https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDKValhalla-linux_ppc-64_cmprssptrs_le_valhalla_nestmates-OpenJ9/14/)

This particular example is triggered by my WIP Valhalla nestmates build, which has a slightly longer job name. However, if future PR builds have longer names or internal file paths change then they can face the same failure. 

It can theoretically be resolved by changing the git config with `git config --system core.longpaths true` or updating to a different version of git.

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
The issue with the PR was actually something wrong with the pipeline code that was being added in the PR mentioned above. The PR was running on a Windows node (that is currently being configured via #1662). I think this can be closed as a dup of that.

I have opened #1746 to address the issue of not picking up the right node.

**Comment by taliamccormick** [comment]
Closing as duplicate of https://github.com/eclipse/openj9/issues/1662
