### ISSUE TITLE
java -version does not contain "64-Bit" keyword

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#1774]
OpenJDK GNU make build process from JDK10 onwards determines the bootjdk 32/64 bit'ness by grep'ing the java -version output for "64-Bit".
When using an OpenJ9 boot JDK to build JDK10/11 it incorrectly thinks it is building using 32bit bootjdk and sets small heap and stacksizes to build which sometimes causes OOM...

The suggestion is for the current output line:
Eclipse OpenJ9 VM (build master-c2a0f28a, JRE 11 Linux amd64-64 Compressed References 20180426_000000 (JIT enabled, AOT enabled)

to change to:
.... amd64-64-Bit .....
Eclipse OpenJ9 VM (build master-c2a0f28a, JRE 11 Linux amd64-64-Bit Compressed References 20180426_000000 (JIT enabled, AOT enabled)

**Comment by DanHeidinga** [comment]
+1 
This seems like a reasonable change and makes OpenJ9 fit better with the OpenJDK makefiles.
