### ISSUE TITLE
Enable parallel functional testing

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#1775]
We have functional builds added in OpenJ9 Jenkins. These builds are using Jenkins files from AdoptOpenJDK https://github.com/AdoptOpenJDK/openjdk-tests

We should enable the parallel testing to utilize machine resources.

**Comment by llxia** [comment]
Did a preliminary testing using sanity functional test build. Parallel based on folders under openj9/test/functional.
https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-Functional-JDK8-linux_390-64_cmprssptrs/12/
Blue Ocean view: https://ci.eclipse.org/openj9/blue/organizations/jenkins/Test-Sanity-Functional-JDK8-linux_390-64_cmprssptrs/detail/Test-Sanity-Functional-JDK8-linux_390-64_cmprssptrs/12/pipeline

Regular sanity functional takes about 35 mins to complete. The parallel was killed after 1hr15mins. We need to address the following issues:

- machines! we only have 4 s390 machines
- we need to do special handling, not all folders can be tested. For example, `J9 Exclude File Support`, `cmdline_options_testresources`, etc.
- handle folder name contains space
- with the SDK and test material downloading time in mind, we need to group tests.

**Comment by smlambert** [comment]
For folder name spaces, I think we have an older issue about renaming/reorganizing test directories.  It may happen in several iterations, standardizing folder names, moving consolidating certain types of tests together (either by component, or java package/module), distributing tests across dirs to optimize the workload in a parallel story (after some preliminary metrics gathering).

**Comment by llxia** [comment]
close this issue as we are working on [smart parallelization](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1563)
