### ISSUE TITLE
Add new Linux x86 machines for pull requests and build pipelines

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1785]
Four new Linux x86 (Ubuntu 16.04) machines have been created and need configuring with the Ansible scripts from AdoptOpenJDK.

openj9-ub16-x86-1; 169.55.150.154
openj9-ub16-x86-2; 169.55.150.150
openj9-ub16-x86-3; 169.55.170.78
openj9-ub16-x86-4; 169.55.150.153
root login passwords available under private communication.

Each one is 4 CPU, 8GB RAM, Ubuntu 16.04.3, 25Gb boot disk, 25 Gb data disk

- [x] PR for JenkinsFiles #1819 
- [x] Ansible machines
- [x] Connect to Jenkins
- [x] Setup Build jobs
- [x] Setup test jobs
- [x] Setup Pipeline jobs
- [x] Setup PR jobs
- [x] README
- [x] OMR Acceptance build #1828

**Comment by AdamBrousseau** [comment]
Builds & Test jobs created. Still need to do PR jobs.
First node created in Jenkins. Waiting for the Ansible script to finish running (thanks @jdekonin) to turn it on and test it out.

**Comment by jdekonin** [comment]
openj9-ub16-x86-4; 169.55.150.153 is ready for adding to jenkins.  Requires verification for compiling and testing all releases.

**Comment by jdekonin** [comment]
openj9-ub16-x86-1,2 & 3 are ready as well.  You should only need to test one of them as they are all identical.
SDK version and location detail for quick reference
```
# /usr/lib/jvm/java-7-openjdk-amd64/bin/java -version
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-3)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

# /usr/lib/jvm/adoptojdk-java-80/bin/java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build master-687c3129, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180501_157 (JIT enabled, AOT enabled)
OpenJ9   - 687c3129
OMR      - c1b89601
JCL      - ccbb2b3b based on jdk8u162-b12)

# /usr/lib/jvm/adoptojdk-java-90/bin/java -version
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build master-71d04615, JRE 9 Linux amd64-64-Bit Compressed References 20180430_171 (JIT enabled, AOT enabled)
OpenJ9   - 71d04615
OMR      - fec9db8a
JCL      - 13f6c542f based on jdk-9.0.4+12)
```

**Comment by AdamBrousseau** [comment]
All machines connected and tested. Seem to be working fine
