### ISSUE TITLE
-Xtrace:what output shows default trace configuration even when trace is switched off using -Xtrace:none

### ISSUE THREAD

**Issue by chandrams** [eclipse/openj9#179]
-Xtrace:what displays the default trace options even when we switch off the trace using -Xtrace:none, unlike -Xdump:what that doesn't display any dump agents when we turn them off using -Xdump:none

Is this expected?

```
C:\Users\IBM_ADMIN>java -Xtrace:none -Xtrace:what -version
Trace engine configuration
--------------------------
-Xtrace:FORMAT=c:\sdk8sr5\jre\lib;.
-Xtrace:MAXIMAL=all{level1}
-Xtrace:EXCEPTION=j9mm{gclogger}
-Xtrace:MAXIMAL=all{level2}
-Xtrace:none
-Xtrace:what
--------------------------
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 8.0.5.0 - pwa6480sr5-20170828_02(SR5))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 7 amd64-64 Compressed References 2017082
5_362543 (JIT enabled, AOT enabled)
J9VM - 70acfcf
JIT  - tr.open_20170825_110306_70acfcf
OMR  - 92fc14b)
JCL - 20170823_01 based on Oracle jdk8u144-b01

C:\Users\IBM_ADMIN>java -Xdump:none -Xdump:what -version

Registered dump agents
----------------------

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 8.0.5.0 - pwa6480sr5-20170828_02(SR5))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 7 amd64-64 Compressed References 2017082
5_362543 (JIT enabled, AOT enabled)
J9VM - 70acfcf
JIT  - tr.open_20170825_110306_70acfcf
OMR  - 92fc14b)
JCL - 20170823_01 based on Oracle jdk8u144-b01
```

**Comment by chandrams** [comment]
>> java -Xtrace:none -Xtrace:what -version

Trace engine configuration
--------------------------
-Xtrace:FORMAT=/home/chandrams/jdk-9+181/lib;.
-Xtrace:MAXIMAL=all{level1}
-Xtrace:EXCEPTION=j9mm{gclogger}
-Xtrace:MAXIMAL=all{level2}
-Xtrace:none
-Xtrace:what
--------------------------
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170925_14 (JIT enabled, AOT enabled)
J9VM - 291a949
JIT  - 291a949
OMR  - 3271be8
OpenJDK  - a3670d2 based on jdk-9+181)

**Comment by hangshao0** [comment]
```
java -Xtrace:help

Usage:

  java -Xtrace[:option,...]

  Valid options are:

     help                                Print general trace help
     what                                Print current trace configuration
     none[=tp_spec[,...]]                Ignore all previous/default trace options
```

It says -Xtrace:none overwrites previous -Xtrace option, not subsequent -Xtrace option.

**Comment by ashu-mehra** [comment]
It looks like the problem is unlike `-Xdump:what`, `-Xtrace:what` does not show the "effective" trace options; it just displays all the trace options specified, including the defaults.
Output of `-Xtrace:what` is not really useful if it is not showing the trace options which will be effective during runtime.
