### ISSUE TITLE
Uses of EXTRA_OPTIONS should include a space

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#1795]
After declaring a value of EXTRA_OPTIONS without a trailing space a subset of the openj9 functional tests failed because the arguments were run together. e.g. using
`export EXTRA_OPTIONS="-Xrs"`

Gave failures such as
`JVMJ9VM007E Command-line option unrecognised: -Xrs-cp`

This included
```
jit_jitt_*
jit_jar_0
jit_vich_0
```

**Comment by smlambert** [comment]
If this still exists as an issue, I think we should transfer it to the TKG repo (where the fix will need to occur). 
FYI @renfeiw @llxia

**Comment by renfeiw** [comment]
I think this issue not longer exists after we move to java version of TKG. Just ran a grinder to verify: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_TKG/171/

**Comment by smlambert** [comment]
Thanks for confirming @renfeiw !  I will close this issue.
