### ISSUE TITLE
Cleanup line in VM_Test build.xml not working as expected

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#1800]
https://github.com/eclipse/openj9/blob/f66506e7a528340d176260c3af47c63cf66979ec/test/functional/VM_Test/build.xml#L134
```
	<target name="clean" depends="dist" description="clean up">
		<!-- Delete the ${build} directory trees -->
		<delete dir="${build}" />
		<delete dir="${data}/*.class" />
		<delete dir="${databin}" />
	</target>
```
Specifically:
`<delete dir="${data}/*.class" />`

I believe the intention of this line is to delete all the class files within the `data` directory. I think the syntax currently reads "Delete all directories named `*.class` in the `data` directory" (where *.class is the actual name of a directory).
Ant doc: https://ant.apache.org/manual/Tasks/delete.html
I created a simple test case by hand and tried it on Windows and xLinux and it doesn't delete any *.class **files** in my directory.
Changing the syntax to the following removes the class files in my dir.
```
<delete>
   <fileset dir="${data}" includes="**/*.class"/>
</delete>
```

fyi @llxia @renfeiw @TianyuZuo

**Comment by AdamBrousseau** [comment]
I have the change above made in a pushed branch I am using to test https://github.com/eclipse/openj9/issues/1662#issuecomment-385009317 .
Let me know if you want me to open a PR.

**Comment by renfeiw** [comment]
Thanks for the fix, it would be appreciated if you can open a PR.

**Comment by AdamBrousseau** [comment]
see #1803

**Comment by AdamBrousseau** [comment]
Good news is this fixes my issue noted above too
