### ISSUE TITLE
Class.getDeclaredMethods throws exception after invoking Class.newInstance

### ISSUE THREAD

**Issue by felipepontes-research** [eclipse/openj9#1843]
Accordingly to Javadoc of Class.getDeclaredMethods (https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredMethods--), "...an array containing Method objects reflecting all the declared methods of the class or interface represented by this Class object" must be returned. But using the following program declared methods of class B can not be retrieved:

public class A {
   static {
      String x = null;
      x.getClass();
   }
}

public class B extends A {
   public void m() {}
}

public class C {
   public static void main(String[] args) throws NoSuchMethodException, NoSuchFieldException {
      try {
         B.class.newInstance();
      } catch (ExceptionInInitializerError e) {
      } catch (Exception e) {
      } finally {
         for (Method m : B.class.getDeclaredMethods()) {
            System.out.println(m);
         }
      }
   }
}

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9 - e24e8aa
OMR - 3e8296b4
JCL - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

1. Compile above program
2. Run it using openj9 java

**Current result:**

Exception in thread "main" java.lang.NoClassDefFoundError: B (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:96)
	at java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:300)
	at java.lang.Class.getDeclaredMethods(Class.java:940)
	at C.main(C.java:8)
Caused by: java.lang.NullPointerException
	at A.<clinit>(A.java:4)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1773)
	at C.main(C.java:2)

**Expected result:**

public void B.m()

**Comment by DanHeidinga** [comment]
This looks similar to #1627

Have you tried with a build that includes #1717 fix?

**Comment by JasonFengJ9** [comment]
#1717 fixed this issue as well.
```
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build master-40bbbfc9, JRE 9 Linux amd64-64 Compressed References 20180425_168 (JIT enabled, AOT enabled)
OpenJ9   - 40bbbfc9
OMR      - 7d6c6629
JCL      - 0fe102d61 based on jdk-9.0.4+12)
B.class = class atestse.java_lang.B
public int atestse.java_lang.B.x
public void atestse.java_lang.B.m() .  ---> Expected result
```
