### ISSUE TITLE
Different results presented by Class.getResource method

### ISSUE THREAD

**Issue by felipepontes-research** [eclipse/openj9#1848]
Class.getResource method presents different results as presented by Oracle HotSpot JVM when executing the following program:

```
package p;
public enum A {
    X, Y
}

package p;
public class B {
    public static void main(String[] args) {
        System.out.println(A[].class.getResource(""));
    }
}
```

**Affected versions:**

Eclipse OpenJ9

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9 - e24e8aa
OMR - 3e8296b4
JCL - ee1e77df1d based on jdk8u162-b12)

Oracle HotSpot

Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java
	3. Run it using Oracle HotSpot java

**Current result:**

Eclipse OpenJ9: null
Oracle HotSpot: file:/.../target/classes/

**Expected result:**

Eclipse OpenJ9 presenting same resources as Oracle JVM.

**Comment by DanHeidinga** [comment]
We'll need to check the spec on this one.  Its not immediately clear what the right behaviour is

**Comment by felipepontes-research** [comment]
Sorry. It happens just when considering a package. I updated the sample code.

**Comment by theresa-m** [comment]
Update: I don't think this is a spec issue. It looks like the hotspot behaviour is correct. The javadocs define:  

`The rules for searching resources associated with a given class are implemented by the defining class loader of the class.`

(https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getResource-java.lang.String-)

Using getClassloader() on the A class it looks like hotspot and openj9 are using the same `sun.misc.Launcher$AppClassLoader`

**Comment by theresa-m** [comment]
Just opened a fix for this. #1909 . The method needs find the resource with the arrays component type or the resource name will not be properly generated.
