### ISSUE TITLE
Parameter.getAnnotatedType throws exception when trying to get parameter type in an inner class

### ISSUE THREAD

**Issue by felipepontes-research** [eclipse/openj9#1850]
An exception is thrown when executing the following program:

```
import java.util.Iterator;
public class A {
    class Inner {
        Inner (Iterator<String> delegate) {
        }
    }
    public static void main(String[] args) {
        Class<?>[] classes = A.class.getDeclaredClasses();
        System.out.println(classes[0].getDeclaredConstructors()[0].getParameters()[0].getAnnotatedType().getType());
    }
}
```

**affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9 - e24e8aa9
OMR - 3e8296b4
JCL - ee1e77df1d based on jdk8u162-b12)

**steps to reproduce:**

	1. compile above program
	2. run it using openj9 java

**current result:**

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
	at java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:318)
	at java.lang.reflect.Executable.getAnnotatedParameterTypes(Executable.java:693)
	at java.lang.reflect.Parameter.getAnnotatedType(Parameter.java:237)
	at A.main(A.java:8)

**expected result:**

class A

**Comment by JasonFengJ9** [comment]
Not able to reproduce the exception reported.

@felipepontes-research could you provide the actual `java` file and command line options? thanks.

**Comment by felipepontes-research** [comment]
Please, use the following files:
[A.zip](https://github.com/eclipse/openj9/files/1981130/A.zip)

I'm not using any command line options (i.e.  ```jdk8u162-b12_openj9-0.8.0/bin/java A```).

**Comment by JasonFengJ9** [comment]
Yup, now the exception can be reproduced as updated issue description. Thanks.
