### ISSUE TITLE
JEP 327 Unicode 10

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1875]
https://bugs.openjdk.java.net/browse/JDK-8182490

This is an "Epic" to contain requirements for supporting this JEP on OpenJ9.

**Comment by pshipton** [comment]
Since #1786 OpenJ9 no longer has any Unicode dependencies in String.toUppercase() or String.toLowercase(), the implementations are in OpenJDK.

Closing since there shouldn't be any OpenJ9 changes required.

**Comment by pshipton** [comment]
@andrewcraik is there anything further from JIT required for this change?

I note there was a test failure still outstanding related to the change to Unicode 10. 
It should be visible in https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_390-64_cmprssptrs/17/ although jenkins isn't responding atm so I can't double check. Will open an Issue for this failure when jenkins returns.

**Comment by pshipton** [comment]
Opened #2890

**Comment by fjeremic** [comment]
> @andrewcraik mentioned, the JIT still has to upper and to lower implementations of the upper and lower case functions so those need to be checked. See toUpperHWOptimized as well as any recognized methods added for the StringLatin1 and StringUTF16 helpers.

I don't think so. We only accelerate "en" locale which is effectively the ASCII subset of UTF16:

https://github.com/eclipse/openj9/blob/298cfabf56acfce0cf1ba14e3f8f98debb6e601e/jcl/src/java.base/share/classes/java/lang/String.java#L2807-L2826

Any changes to Unicode standard will not affect the JIT intrinsics.

**Comment by pshipton** [comment]
Closing since nothing is required other than fixing the test #2890
