### ISSUE TITLE
Unclear use of  OMRSIG_SIGNAL / OMRSIG_SIGACTION

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#1889]
A number of places in the jvm ( eg [1](https://github.com/eclipse/openj9/blob/bd106f77686ddc3b2e5de6d533fcfef4506a24d9/runtime/j9vm/jvm.c#L4522) [2](https://github.com/eclipse/openj9/blob/bd106f77686ddc3b2e5de6d533fcfef4506a24d9/runtime/vm/jvminit.c#L828) [3](https://github.com/eclipse/openj9/blob/bd106f77686ddc3b2e5de6d533fcfef4506a24d9/runtime/vm/jvminit.c#L6452) among others ), we use the macros `OMRSIG_SIGNAL` / `OMRSIG_SIGACTION` These macros are conditionally defined in [`omrport.h`](https://github.com/eclipse/omr/blob/996c8e1ec72e7215f58216cb94806ef75ccb04c6/include_core/omrport.h#L167)   to expand to `omrsig_primary_signal` / `omr_primary_sigaction` if `OMRPORT_OMRSIG_SUPPORT` is defined, or  `signal` / `sigaction` otherwise. 

The issue is that we only define `OMRPORT_OMRSIG_SUPPORT` [when compiling the port library](https://github.com/eclipse/openj9/blob/bd106f77686ddc3b2e5de6d533fcfef4506a24d9/runtime/port/module.xml#L168). Thus these other reference are actually just calling `signal`/`sigaction`. Is this the intended behaviour? If so, shouldn't we make it more clear by avoiding the use of the macros? If not, we should be defining `OMRPORT_OMRSIG_SUPPORT` globally, or [merging it with `OMR_OMRPORT`](https://github.com/eclipse/omr/issues/2537).

**Comment by babsingh** [comment]
@dnakamura OMRPORT_OMRSIG_SUPPORT should be defined globally. OpenJ9 and OMR should consistently use either `omrsig_primary_signal/omr_primary_sigaction` or `signal/sigaction`.

How should we enable `OMRPORT_OMRSIG_SUPPORT` globally? Can you provide details about merging with `OMR_OMRPORT`?

**Comment by dnakamura** [comment]
I would maybe add something to the bottom of `omrcfg.h` like:
```
#if defined(OMR_PORT) && defined(OMR_OMRSIG)
#define OMRPORT_OMRSIG_SUPPORT
#endif
```

**Comment by babsingh** [comment]
@dnakamura In OpenJ9, the `J9VM_PORT_OMRSIG_SUPPORT` flag is used to enable the   `OMRPORT_OMRSIG_SUPPORT` flag when building the port library. 

If we use the above approach to enable `OMRPORT_OMRSIG_SUPPORT` globally, then `OMRPORT_OMRSIG_SUPPORT` won't be disabled when `J9VM_PORT_OMRSIG_SUPPORT` is disabled.

**Will the below changes work?**

1) Enable `OMRPORT_OMRSIG_SUPPORT` in `runtime/gc_glue_java/configure_includes/configure_common.mk.ftl`:
```
<#if uma.spec.flags.port_omrsigSupport.enabled>
  --enable-OMRPORT_OMRSIG_SUPPORT \
</#if>
```

2) Add `OMRPORT_OMRSIG_SUPPORT` in
  i) `omr/omrmakefiles/configure..mk.in`
  ii) `omr/configure.ac`
  iii) `omr/omrcfg.CMakeTemplate.h`
  iv) `omr/include_core/omrcfg.h.in`
  v) `omr/cmake/config.cmake`
