### ISSUE TITLE
Enable Sanity tests on Travis

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#190]
Taking a stab at this in my [fork](https://github.com/AdamBrousseau/openj9/blob/travis_test/.travis.yml)
https://travis-ci.org/AdamBrousseau/openj9/branches (travis_test)

related #24

**Comment by AdamBrousseau** [comment]
Seems to be functional now however we exceed to maximum allowed output of 4MB
https://travis-ci.org/AdamBrousseau/openj9/builds/281469003
>The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
>
>The job has been terminated

Comparing output from Jenkins PR builds, we seem to be only ~1/3 way through the console output when we max out on Travis.

**Comment by smlambert** [comment]
Could experiment with changing the logging level of some of the tests (default setting is log4testng.rootLogger=INFO, could change to WARN and see how far you get, in https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/log4testng.properties).

**Comment by AdamBrousseau** [comment]
Changing to WARN or ERROR didn't seem to do anything
https://travis-ci.org/AdamBrousseau/openj9/builds/281648982
Although, we only get ~350 lines into make sanity before we overflow. I guess we would need to change the compile to be less verbose? Don't know if that's an option.
There are people that have talked about workarounds for this
https://stackoverflow.com/questions/26082444/how-to-work-around-travis-cis-4mb-output-limit
Also there is the TRAVIS_WAIT command I might try out.

**Comment by AdamBrousseau** [comment]
ok so `travis_wait` is used to provide output when none is produced by the running command(s). This is not what we want. Once the `make all` command was complete, all the compile output was printed at once.
https://travis-ci.org/AdamBrousseau/openj9/builds/286241308

**Comment by AdamBrousseau** [comment]
Closing this as I have no plans to get Travis testing working and we will hopefully be getting x86 machines shortly
