### ISSUE TITLE
Increase default shared cache size for Java 8 64-bit

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1938]
#1930 #1164 increased the default shared cache size for Java 9 and later. We should consider doing the same for Java 8. Since Java 8 may be the more often used JVM, increasing the default in Java 8 should be beneficial, especially for those enabling -Xshareclasses without understanding that typically the default size needs to be increased. 

We can wait a little bit and see if any problems are discovered by the change to Java 9 and later.

@hangshao0 fyi

**Comment by pshipton** [comment]
@hangshao0 this is targeted for the 0.10.0 milestone, which is scheduled for the end of the month. Have you tried changing the default for OpenJ9 Java 8 yet? Not sure if making the change will need any test updates.

**Comment by hangshao0** [comment]
I will work on this.

**Comment by pshipton** [comment]
Since the 0.10.0 release will only create builds for Java 11, moving this to the 0.11.0 milestone. Please have the changes merged before Oct 8.

**Comment by hangshao0** [comment]
Doc change request created here: https://github.com/eclipse/openj9-docs/issues/80

**Comment by pshipton** [comment]
@SueChaplain I was hoping to coordinate and time the changes so they went into the 0.11.0 release but unfortunately the code was merged already. You can add it for 0.10.0, I'll fix the tagged milestone.
