### ISSUE TITLE
Only support allowed JNI versions

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#1944]
The VM should only allow JNI versions up to the version of the VM being used.

See the comments in #1942.

**Comment by gacholio** [comment]
Is there any real reason for this?  The table will support the new calls regardless of version (it's been crafted so that later versions only add to or use unused entries).  There's no enforcement on using calls from later JNI versions regardless of the version requested.

**Comment by pshipton** [comment]
I guess we'll wait until there is an actual problem.
