### ISSUE TITLE
JDWP "onuncaught=y" debugger initialization hangs

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#1951]
The fix for JDWP race condition:
https://github.com/ibmruntimes/openj9-openjdk-jdk10/commit/01d19a4376b08836b57bb3a4eeb221f2ad22c4ad
unfortunately regressed the use of "onuncaught=y" option, whereby the monitor added is never cleared.
I suspect the fix needs some re-think...
Applies to jdk8u, jdk10, jdk11.

**Comment by pshipton** [comment]
@andrew-m-leonard have you considered reverting the changes?

**Comment by andrew-m-leonard** [comment]
@pshipton yes,... but I was waiting Peter's comments first, maybe we ought to revert them for the moment

**Comment by pdbain-ibm** [comment]
I think it is safe to revert the change, since the test case's behaviour doesn't represent user behaviour.
Could you provide a test case for the "onuncaught=y" mentioned above?

**Comment by andrew-m-leonard** [comment]
@pdbain-ibm The openjdk JITDebug.sh always hangs with this failure:
make run-test TEST='jtreg:test/jdk/com/sun/jdi/JITDebug.sh'

**Comment by pshipton** [comment]
The changes have been reverted from Java 8, 9, 10, 11 streams.

**Comment by andrew-m-leonard** [comment]
Thanks Peter's

**Comment by pdbain-ibm** [comment]
@andrew-m-leonard did my JDWP fix break anything in OpenJ9 or were all the problems with HotSpot?

**Comment by pdbain-ibm** [comment]
For the record, further to https://github.com/eclipse/openj9/issues/1951#issuecomment-391719650, running the test on OpenJ9m with this change works fine:
```
$ cd openj9-openjdk-jdk8/jdk/test/com/sun/jdi
$ bash JITDebug.sh 
trigger onuncaught launch
trivial debugger started
attached to: 42389
we are happy - terminated VM with no error
JIT Debugging test PASSED
The test passed!!!
```

**Comment by andrew-m-leonard** [comment]
I must admit I can't remember exactly, but I suspect you might be right, as I think I found it when trying to contribute it to OpenJDK... Although, I;m not sure why J9 doesn't hit the problem then...?
