### ISSUE TITLE
Test Dependencies not complete

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9#196]
I've been playing with the Tests, and it seems there's some dependencies in the Makefiles that aren't specified. 

For example, if you follow the [instructions](https://github.com/eclipse/openj9/blob/master/test/README.md), but instead of starting with the `test` target you start with the `sanity` target, the dependencies will not get downloaded.

**Comment by llxia** [comment]
In the current implementation, ```getdependency``` target will get called when running make ```compile``` or ```test``` target. We assume that people will have to compile before they run any test.

However, I think we should make the instruction more clear - To get the dependencies, users can run ```make getdependency``` directly

**Comment by mgaudet** [comment]
Yeah, as I play with this I am keeping notes of things that can be improved, but, the failure if you don't run `make test` first is pretty uninformative, which makes me wonder if there instead be a stamp-file to allow `make` to make sure things work out fine.

**Comment by llxia** [comment]
Thanks for pointing out. We will update the readme. :)
