### ISSUE TITLE
MM_BasePointer.java not generated by PointerGenerator

### ISSUE THREAD

**Issue by Ailloviee** [eclipse/openj9#1973]
MM_BasePointer.java cannot be generated by PointerGenerator due to change made on line 278:
`structure.getConstants().size() > 1` was changed to `structure.getConstants().size() != 0` in by commit 70c18d5a81bb53b12276bf8716aec31843aaaddd

**Comment by pshipton** [comment]
@keithc-ca fyi

**Comment by keithc-ca** [comment]
I recognized that condition as incorrect, but it worked at the time for all existing classes, so I didn't think it worth the trouble to fix then. If `MM_Base` had two or more constants (now one or more) it would be omitted even though it is the base of other types. I will remedy the situation.

**Comment by keithc-ca** [comment]
Did that occur in the context of changes to `omr/gc/base/Base.hpp`?

**Comment by Ailloviee** [comment]
No I don't think `Base.hpp` was changed.
