### ISSUE TITLE
List of commits for the release notes

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/openj9#1979]
Release notes for 0.9.0 are underway and should be in a PR later today. Currently, those release notes include the following sections:

1. Binaries and supported environments: E.g. New builds available, new platforms supported
2. Notable changes: New features / changes in behavior 
3. Issues / Limitations: Problems and workarounds
4. Other changes: Everything else that's changed since 0.8.0

For (4) we need some way of extracting/formatting the information from the
 `git log openj9-0.8.0..openj9-0.9.0` command to provide a list that shows:

[commit] [Title] [Author] [#PR]

At node.js they have a tool to do this (github.com/nodejs/changelog-maker), which we could optionally use (it's licensed so we need to do the due diligence) or perhaps someone can quickly write a few lines of code to do it?

**Comment by dnakamura** [comment]
I have a simple script which has a few limitations.
- It is fragile with respect to the ordering of children on merge commits.  Currently its tuned for the way github formats merge commits. ie. the old master is the first child, the head that you are merging in is the second child (I believe `git merge` does it the other way arround)
- "title" is assumed to be the first line of the merge commit body (which will be the title of the pull request if using github)
- Whomever authored the last commit in the pull request is considered to have authored the pr
- "commit" shows the sha of the merge commit, I'm not crazy about this idea but Its the only thing that makes sense for PRs which have multiple commits

https://gist.github.com/dnakamura/517128aaee7cc05a57a290b97d073d7e

**Comment by SueChaplain** [comment]
@dnakamura  That's great Devin. I just had a play looking at a small set of changes between tags (openj9-0.8.0-rc1..openj9-0.8.0-rc2) and the list looks nice and neat. I can't comment on the limitations you mention .... sounds fair to me, but maybe some others can weigh in their thoughts.

@pshipton @DanHeidinga @mstoodle ?? Are you good with us using Devin's script to generate the "Other changes" section of the release notes? Any IP issues? 

One improvement I can think of (for future maybe) is to make the commit a link into GitHub. Don't think you can get it directly from `git log` so would need more lines of code. But this is really good right now - thank you!

**Comment by pshipton** [comment]
> Are you good with us using Devin's script to generate the "Other changes" section of the release notes?

+1

> Any IP issues?

Not if Devin wrote the script.

**Comment by DanHeidinga** [comment]
@dnakamura Can you contribute the script to the project so we can use it in future releases?  Maybe somewhere in either the `sourcetools` or `doc/processes` folder?

**Comment by SueChaplain** [comment]
@pshipton - Can we close this issue - I believe you are now using something similar to create the list for the release.
