### ISSUE TITLE
Checksum downloads of test dependencies

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9#198]
in `test/TestConfig/scripts/tools/getDependencies.pl` we download a number of dependencies

https://github.com/eclipse/openj9/blob/ae3d15f0bf9a586af1456d6a8d07a18400b84757/test/TestConfig/scripts/tools/getDependencies.pl#L57-L70

However, we do not checksum these to ensure the download was successful, or that we got the `jar` we thought we were after (what happens if download is interrupted or interposed)

**Comment by llxia** [comment]
@TianyuZuo  could you take care of this? Thanks!

**Comment by TianyuZuo** [comment]
will update the script to add the checking process.

**Comment by mgaudet** [comment]
Potentially stupid question: Was there a need that made it best to write this as a perl script, as opposed to just creating makefile dependencies on the jars? 

(_i.e._ a Makefile rule like 

```makefile
asmtools.jar: 
    $(WGET) --quiet --output-document=$@ https://adopt-openjdk.ci.cloudbees.com/view/OpenJDK/job/asmtools/ws/asmtools-6.0-build/release/lib/asmtools.jar
```

)

**Comment by TianyuZuo** [comment]
Yes, we can also integrate the jar downloading into makefiles. In the begin, Perl script was used for its fast development and reliability. We can also try to use makefile if we can also use for good reliability and fast development
