### ISSUE TITLE
Signals not working properly for Apache Kafka

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#1984]
How to reproduce the issue?

**Instructions:** https://kafka.apache.org/quickstart

- Step 1: Download the code
`tar -xzf kafka_2.11-1.1.0.tgz; cd kafka_2.11-1.1.0`

- Step 2: Start the server in a new shell or in background (`&`)
`bin/zookeeper-server-start.sh config/zookeeper.properties`

- Step 3: Start the Kafka server in a new shell or in background (`&`)
`bin/kafka-server-start.sh config/server.properties`

**Observations:** Kafka overwrites the default signal handlers for `SIGTERM`, `SIGHUP` and `SIGINT`: [related Kafka source code](https://github.com/apache/kafka/blob/ed8b0315a6c3705b2a163ce3ab4723234779264f/core/src/main/scala/kafka/Kafka.scala#L58).

Kafka also adds a [shutdown hook](https://github.com/apache/kafka/blob/ed8b0315a6c3705b2a163ce3ab4723234779264f/core/src/main/scala/kafka/Kafka.scala#L58).

**Issue:** When a signal is raised (`SIGTERM`, `SIGHUP` and `SIGINT`), the newly assigned signal handler is invoked in an infinite loop. Need to investigate this behavior further.

**Comment by babsingh** [comment]
fyi - @pshipton

**Comment by dnwe** [comment]
@babsingh FYI https://github.com/apache/kafka/pull/5047 (and https://issues.apache.org/jira/browse/KAFKA-6918)

**Comment by pshipton** [comment]
FYI Kafka just merged a PR that disables the custom signal handler code when it detects an IBM JRE now
https://github.com/apache/kafka/pull/5047. It seems that someone had raised an issue that it wasn't working on a recent IBM Java 8.

**Comment by babsingh** [comment]
### Fix
OpenJ9 changes: https://github.com/eclipse/openj9/pull/2004
OMR changes: https://github.com/eclipse/omr/pull/2598

**Comment by babsingh** [comment]
OpenJ9 SDK with the above fix: https://ibm.box.com/s/tymtaix6wql03c5a8b40i8rowzwvl53g

Using the above OpenJ9 SDK, I have verified that Apache Kafka terminates properly when the following signals are raised: `SIGINT`, `SIGTERM`, `SIGHUP` and `Ctrl + C`.

@dnwe would you like to confirm if Apache Kafka terminates properly with the above OpenJ9 SDK?
