### ISSUE TITLE
Jenkins: Discuss adding a restart job function for use in the OMR Acceptance build

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#2017]
The OMR Acceptance build currently consists of a compile job followed by a sanity job on jdk8 and jdk10 across aix, win, p/z/x linux and xlinux large heap. This equates to 24 downstream jobs, which is 24 points of failure. This number will only grow as we add more platforms.
We often will have one of them fail in the OMR acceptance build for an intermittent infra issue. Ideally we would fix these issues which is why I'm reluctant to suggest adding a feature which allows infra issues to be ignored.

Here is a list to track what has been failing in the recent builds. I will add to this list as I have time and see new failures.

- `#490` - Failed in:
   - AIX 10 compile failure - tracked in #1550
   - Build terminated

- `#489` - Failed in:
   - [Test-Sanity-JDK8-linux_x86-64_cmprssptrs #64](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_x86-64_cmprssptrs/64/console)
      - Problem: Initial JenkinsFile clone `Failed to connect to github.com port 443: Connection refused`
      - Solution: unknown
   - [Test-Sanity-JDK8-linux_x86-64 #21](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_x86-64/21/console)
      - Problem: full scm checkout on master, which is wrapped in retry(5), failed 5 times. 443 connection refused.
      - Solution: Could try switching to SSH protocol but we would need eclipse to add a key to our bot account
   - Timeout after 8 hours
      - JDK10-linux_x86-64, JDK10-linux_x86-64_cmprssptrs, JDK10-linux_390-64_cmprssptrs didn't complete in time (busy farm)

- `#488` - Failed in:
   - Timeout after 8 hours
      - JDK8-linux_x86-64, JDK10-aix_ppc-64_cmprssptrs, JDK10-linux_x86-64_cmprssptrs, JDK10-linux_x86-64, JDK8-linux_x86-64_cmprssptrs

- `#487` - Failed in:
   - Compile failure JDK10 AIX - tracked in #1550
      - [Build-JDK10-aix_ppc-64_cmprssptrs #117](https://ci.eclipse.org/openj9/job/Build-JDK10-aix_ppc-64_cmprssptrs/117/console)
   - Build terminated

- `#486` - Passed
- `#485` - Passed
- `#484` - Failed in:
   - Windows - No space left on nodes

**Comment by DanHeidinga** [comment]
@AdamBrousseau This is an interesting idea and would allow the OMR acceptance build to succeed more regularly.  

- Is there an existing Jenkins plugin that would allow restarting downstream stages of a pipeline?

- How is that reflected in the Jenkins UI?  Would it be possible to tell that a build needs regular manual intervention to succeed without having to do a lot of digging?

And the larger question is how many of these failures would be resolved by a restart?  I see a number of timeouts and git checkout issues, some of which failed despite the retry(5).

**Comment by fjeremic** [comment]
Having been wrestling with OMR-Acceptance for the last several days trying to get a dependent change promoted I'm very much in favor of this as the intermittent and seemingly random machine/infrastructure issues have been a pain to deal with.

**Comment by DanHeidinga** [comment]
@AdamBrousseau Any update on the questions asked in https://github.com/eclipse/openj9/issues/2017#issuecomment-393154695 ?  Answers to those questions would help determine the benefit of this and where to prioritize it, especially seeing as it's being mentioned in other items.

**Comment by AdamBrousseau** [comment]
>existing Jenkins plugin that would allow restarting downstream stages of a pipeline

There are at least 2 open issues I can see with a quick search, both are unresolved. I think the Cloudbees enterprise Jenkins offering has this feature.
- [Restarting stages
](https://issues.jenkins-ci.org/browse/JENKINS-45455)
- [Restart pipeline from specific stage, after failure
](https://issues.jenkins-ci.org/browse/JENKINS-33846)

>How is that reflected in the Jenkins UI?

Your best friend for the restarts will be 
- Slack notifications

You can also find out if a restart is pending on the UI for a build but its not necessarily that obvious.
- The console output will have a link [Input requested]().
This can get buried by other console output.
- From the OMR-Acceptance build number page (the specific build number you are running), there will be a link on the left for [? Paused for input]()
- From the Top level OMR_Acceptance build page, you can see on the "build grid" that a stage is paused. Hovering over will show the restart details.

For the first 2 cases, the link will take you to a page where you can take the restart action. The third option you can action directly from the hover-tip.

>how many of these failures would be resolved by a restart?

Obviously this depends on the failure type. Flaky infra would be the best use case for this.
- Git failures
```
 > git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/eclipse/openj9.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/eclipse/openj9.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: remote: Counting objects: 4657, done.        
remote: Compressing objects:   0% (1/161)       
...
...
Resolving deltas: 100% (3402/3402), completed with 1658 local objects.
fatal: unable to look up current user in the passwd file: Bad address
Unexpected end of command stream

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:860)
	... 13 more
```
- Space issues
```
java.io.IOException: remote file operation failed: /home/jenkins/workspace/Build-JDK8-linux_x86-64 at hudson.remoting.Channel@582479b6:ub16-x86-3: java.nio.file.FileSystemException: /home/jenkins/workspace/Build-JDK8-linux_x86-64: No space left on device
```
- Random java crashes
```
an exception which occurred:
	in field org.codehaus.groovy.control.MultipleCompilationErrorsException.collector
	in object org.codehaus.groovy.control.MultipleCompilationErrorsException@3b27b666
	in field com.cloudbees.groovy.cps.Outcome.abnormal
	in object com.cloudbees.groovy.cps.Outcome@77d5bc95
	in field org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.outcome
	in object org.jenkinsci.plugins.workflow.cps.CpsBodyExecution@377dec3b
	in field org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.body
	in object org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution@11e631f1
	in field org.jenkinsci.plugins.workflow.cps.CpsThread.step
	in object org.jenkinsci.plugins.workflow.cps.CpsThread@56ce7ca4
	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@250febcb
	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@250febcb
Caused: java.io.NotSerializableException: org.codehaus.groovy.control.ErrorCollector
```
The restarts to watch out for are legitimate intermittent compile or test failures. Restarting blindly can allow bad code to promote and failures to go undocumented.

**Comment by AdamBrousseau** [comment]
To summarize:
- Promoting OMR code "into" OpenJ9 requires a fully passed (green) build
- A build currently consists of Compile and Functional-Sanity across multiple platforms and multiple releases/versions
- Any one of these individual pieces can fail which will render the entire build failed
- Having the ability to restart an individual piece (compile for example) will prevent us from having to rerun everything.
- The nightly build currently doesn't have a promote step so it is unnecessary to have a restart in the nightly.
- Individual jobs or a pipeline of a jobs for a specific spec/version can be rebuilt currently. The limitation is that rebuilding is done out of context of a parent job (i.e. The status of the rebuild is not reflected in the parent job that launched initially).

Based on the feedback I've received, it seems like this would be a useful feature. I will go ahead and put together a Pull Request once I have something operational.
