### ISSUE TITLE
Turn off all OpenJ9 JDK9 builds

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2020]
JDK9 is a short term release which has been out of support since April. JDK10 is available and supported by OpenJ9. The 0.9.0 release plan [1] doesn't include support for JDK9, and JDK9 is not included in the OpenJ9 support statement [2].  OpenJ9 doesn't have the machine capacity to keep testing JDK9 in addition to JDK8 and JDK10.

I suggest OpenJ9 turn off all JDK9 builds.

[1] https://projects.eclipse.org/projects/technology.openj9/releases/0.9.0
[2] https://github.com/eclipse/openj9-docs/blob/master/docs/openj9_support.md

**Comment by AdamBrousseau** [comment]
Removing from the `all` would still allow PRs to run 9 if it's explicitly requested. We will continue to run 9 in the nightly for now. Also note that OMR Acceptance is only testing 8,10.

**Comment by AdamBrousseau** [comment]
Jenkins configs are updated. I did a quick test on the triggers for compile and extended jobs (sanity should be the same). Please let me know if you see any anomalies.

**Comment by fjeremic** [comment]
> The consensus on the OpenJ9 Community Call was to remove JDK9 from "all" when doing Pull Request builds.

I was unable to attend the call. What was the consensus of when to fully remove these builds? How long do we keep them around for?

**Comment by DanHeidinga** [comment]
> I was unable to attend the call. What was the consensus of when to fully remove these builds? How long do we keep them around for?

We only discussed removing them from the PR builds during the call to reduce the machine load and ensure that builds are able to complete in a reasonable timeframe.

**Comment by llxia** [comment]
How long will we continue running JDK9 in nightly build? I am working on Add AdoptOpenJDK test pipelines into nightly build #2037 and I am wondering if I need add new JDK9 test jobs into nightly?

**Comment by pshipton** [comment]
+1 for only running 8 and 10 (plus 11 shortly).

**Comment by AdamBrousseau** [comment]
I think this can be closed
