### ISSUE TITLE
The wrong logic for the disclaim work in the shared classes

### ISSUE THREAD

**Issue by ChengJin01** [eclipse/openj9#2024]
The current implementation of disclaiming the meta data in the shared cache is incorrect in that it only disclaims the area section(min/max value) set up by the "used" meta data (only when the meta data entry is retrieved) rather than the stored meta data. 

The problem was detected in cold/warm runs of LibertyStartup in which case only a few stored meta data entries got retrieved in the cold runs while a huge amount of stored meta data (e.g. for AOT methods) got retrieved in subsequent warm runs before exiting the startup stage.  So the VM ended up with much higher footprint in cold runs than in the warm runs.

The intent of the disclaim work is to release all stored meta data after exiting the startup stage, whether it is in the cold run or in the warm run (we assume the meta data is used as long as it is stored there). 
Note: the disclaimed memory can be loaded back after that if needed.

To achieve this, the min/max value of the disclaimed meta data section (initially updated by the stored meta data) should be modified to ensure these values are shared in both cold runs and warm runs.

From the footprint perspective, the score of cold runs should be pretty much equal to that of warm runs after fixing this issue.

**Comment by ChengJin01** [comment]
FYI: @pshipton , @DanHeidinga , @hangshao0, @pdbain-ibm

**Comment by ChengJin01** [comment]
@pshipton,    I talked to Hang. Basically there are two solutions to disclaim the meta data as follows:

1) call updateAccessedShrCacheMetadataBounds() whenever storing the meta data (AOT method, attachData, ROM class, etc) , in which case it triggers to disclaim the meta data in cold run ( the existing code already called updateAccessedShrCacheMetadataBounds when finding the meta data in warm runs). 
2) no need to call updateAccessedShrCacheMetadataBounds() at all and directly disclaim all stored meta data in both cold and warm runs as the left boundary/min value (UPDATEPTR(_theca)) and  the right boundary/max value (CADEBUGSTART(_theca)) of the stored meta data area are already stored in the header of the shared cache.

There is no fundamental difference for both solutions.  I am wondering which one you prefer to fix the issue. Correct me if anything I overlooked.

**Comment by vijaysun-omr** [comment]
FYI @mpirvu

**Comment by pshipton** [comment]
I think option 2 would work, but only for the cold run. The logic for the warm run should not be changed. We shouldn't disclaim from UPDATEPTR(_theca) in a warm run because this would AOT which hasn't yet been used.

**Comment by pshipton** [comment]
Although, its that simple because there can be multiple JVMs building the cache at the same time. Just because one JVM creates the cache doesn't mean it will write all the data, or be in sync with other JVMs writing to the cache. Option 2 will only work when there is only one JVM creating the cache contents. To play it safe we'd better stick with option 1.

**Comment by ChengJin01** [comment]
I already implemented the option 2 and compared the results with the existing build on LibertyStartup.
[liberty-xa6490_openj9_disclaim.txt](https://github.com/eclipse/openj9/files/2064637/liberty-xa6490_openj9_disclaim.txt)
[liberty-xa6490_openj9_ibuild.txt](https://github.com/eclipse/openj9/files/2064638/liberty-xa6490_openj9_ibuild.txt)

Only in terms of the footprint scores above, it works good as expected (reduced approx 4MB in the cold run and remains the same score (average) as the existing build in the warm run. But it is hard to tell whether the current status is in the cold run or in the warm run (can it be in cold run if the shared cache doesn't exist ? ). Otherwise, option 2 should be more preferable in cold run.

The option 1 always works in the cold run but the disclaimed memory might be smaller than that of the option 2 (not restricted to the application of LibertyStartup) because:
In the case of multiple VMs, _minimumAccessedShrCacheMetadata & _maximumAccessedShrCacheMetadata only reflect the min & max value (stored meta data) in the current VM while (UPDATEPTR(_theca)) & CADEBUGSTART(_theca) reflect the latest min & max value updated by multiple VMs (Theoretically UPDATEPTR(_theca)) <= _minimumAccessedShrCacheMetadata and CADEBUGSTART(_theca) >= _maximumAccessedShrCacheMetadata).

Will need to implement the option 1 to see what really happens as compared to the results of the option 2.
