### ISSUE TITLE
Cannot load agent jar in Java 10 modular app

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2030]
Trying to load an agent jar into OpenJ9 Java 10 using the attach API, where Java 10 is running a module, results in a AgentLoadException error 102. It works with OpenJDK.
```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message find class on InstrumentationImpl failed at JPLISAgent.c line: 493
*** java.lang.instrument ASSERTION FAILED ***: "success" at InvocationAdapter.c line: 395
Agent failed to start!
JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
```

openjdk version "10.0.1-adoptopenjdk" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-adoptopenjdk+0-adhoc..openjdk)
Eclipse OpenJ9 VM (build master-6f5a858a, JRE 10 Windows 8.1 amd64-64-Bit Compressed References 20180523_54 (JIT enabled, AOT enabled)
OpenJ9   - 6f5a858a
OMR      - 15290506
JCL      - 228f0625d8 based on jdk-10.0.1+10)

You need to start a Java 10 modular app to connect to, such as jconsole. While running jconsole exhibits the problem you don't get a console. To get a console run "java -m jdk.jconsole/sun.tools.jconsole.JConsole" instead.

Sample loader code.
```
		String vmid = com.ibm.tools.attach.target.AttachHandler.getVmId();
		VirtualMachineDescriptor target = null;
		List<VirtualMachineDescriptor> machines = VirtualMachine.list();
		for (VirtualMachineDescriptor vmd : machines) {
			if (vmd.id().equals(vmid)) continue;
			System.out.println(vmd);
			if (vmd.displayName().contains(args[0])) {
				if (target != null) {
					System.out.println("Duplicates!");
					System.exit(1);
				}
				target = vmd;
			}
		}
		if (target == null) {
			System.out.println("No target found");
			System.exit(1);
		}
		VirtualMachine vm = VirtualMachine.attach(target);
		vm.loadAgent("t:\\peter\\premain.jar");
```

**Comment by pshipton** [comment]
It doesn't work with Java 8 either. I was trying to recreate an error 102 with Java 10 but hit this instead. I feel like I'm doing something wrong but so far haven't been able to figure out what.

**Comment by pshipton** [comment]
One use case for having this working is MAT (the Eclipse memory analyzer toolkit). It allows you to attach to a running java process and create a system dump for analysis. However it doesn't work with Java 10 when running a modular app, as described above.

**Comment by pdbain-ibm** [comment]
Will investigate.

**Comment by pdbain-ibm** [comment]
jconsole is tricky to run (need X11), so I made an ad-hoc test case.

[testjar.zip](https://github.com/eclipse/openj9/files/2081287/testjar.zip)

Unzip and launch:
```
java -p pdb.modularity.jar -m pdb.modularity/pdb.looper
java loadagent 22890 /home/pdbain/macprojects/modularity/simpleagent.jar
```

Result is:
```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message find class on InstrumentationImpl failed at JPLISAgent.c line: 493
*** java.lang.instrument ASSERTION FAILED ***: "success" at InvocationAdapter.c line: 395
Agent failed to start!
JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
```

**Comment by pdbain-ibm** [comment]
Can't load InstrumentationImpl:
` <BCU j9bcutil_findLocallyDefinedClass: <dynamic search for sun/instrument/InstrumentationImpl failed>`
`sun/instrument/InstrumentationImpl from: jrt:/java.instrument `
```
$ java -d java.instrument
java.instrument@10.0.1-internal
exports java.lang.instrument
requires java.base mandated
qualified exports sun.instrument to java.base
```
This works fine with non-modular applications.

**Comment by pdbain-ibm** [comment]
Adding `--add-modules java.instrument` makes the test pass.

**Comment by pdbain-ibm** [comment]
```
		ModuleLayer b = ModuleLayer.boot();
		Optional<Module> ji = b.findModule("java.instrument");
		o.println("java.instrument isPresent="+ji.isPresent());
```
Normally this prints "false", but when running openjdk with -javaagent it prints "true", so the javaagent code is adding the module to the boot layer.

**Comment by pdbain-ibm** [comment]
Candidate fix in https://github.com/pdbain-ibm/openj9/tree/agent, running personal build now.

**Comment by pdbain-ibm** [comment]
@irinarada pull request builds are running now.  One failure due to known machine issue.

**Comment by pdbain-ibm** [comment]
Discussed with GAC.  We are refactoring this some more for performance and maintainability.

**Comment by pdbain-ibm** [comment]
Updated per GAC's comments.  Pull request build running, waiting for Keith's approval.
