### ISSUE TITLE
gdb unsupported in Docker

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#2041]
OpenJ9 DockerFile(s) used to build OpenJ9 don't support gdb out of the box.

We need to add documentation so that a user can setup Docker for debugging with gdb.

### Few known issues:

1) Docker containers don't support gdb by default. Docker containers need to be run in privileged mode to enable gdb.
   - Running Docker containers in privileged mode: 
            `docker run --privileged -it <docker image name>`
<br>

2) The following warning/error may be seen - **"warning: Error disabling address space randomization: Operation not permitted"**.
   - To resolve the above error, Docker containers need to be run using the following options:
           `docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined`
<br>

3) gdb doesn't find debug symbols automatically.
   - A possible solution is to tell gdb the location of debug symbols via: 
            `set debug-file-directory <directory>`

**Comment by babsingh** [comment]
fyi - @pshipton

**Comment by DanHeidinga** [comment]
@babsingh This would be a great blog post on the OpenJ9 blog or as a reference on how to debug in the in the /openj9/docs directory

**Comment by smlambert** [comment]
A blog post referencing new doc in the repo!  Yes!  Sent you an invite @babsingh for contributing to openj9/wordpress blog... :)

**Comment by babsingh** [comment]
Yes, I have access to openj9/wordpress blog. I will draft a blog post on this topic.

**Comment by babsingh** [comment]
I have published a blog post - [Debugging OpenJ9 in Docker with GDB](https://wordpress.com/post/blog.openj9.org/61). So ... closing this issue
