### ISSUE TITLE
Unnecessary synchronization in com.ibm.tools.attach.target.IPC.printLogMessage

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2048]
printLogMessage() (both versions) are synchronized and call synchronized getLogStream().
These methods are called in critical code paths to determine if logging is enabled.
The synchronization is usually unnecessary and adds overhead.  

Suggestion:
- static (non volatile) state variable for logging with 3 values: unknown, enabled, disabled.
- state initialized to unknown by IPC clinit
- Attach API initialization sets the state to enabled or disabled and creates the log stream if necessary, all in a synchronized block.
- Users of the logging API check the state: 
  - if unknown, enter a synchronized block and check again.  If state is unknown or disabled, quit. If enabled, get the log stream and proceed with logging.
  - if disabled, quit
  - if enabled, get the log stream object. Because of memory ordering, the log stream may be null. If it is null, enter a synchronized block to force memory updating and re-fetch the log stream.  Proceed with logging.

**Comment by pdbain-ibm** [comment]
@pshipton Could you review this idea?  Thanks.

**Comment by pshipton** [comment]
You can make it work by using Unsafe to write the log stream object. There is another potential problem other than the log stream being null, it could be non-null but not properly initialized due to out of order writes. See the code using Unsafe in java.lang.Class for examples.

**Comment by pdbain-ibm** [comment]
I think I'm over-engineering it.  I care about performance only when logging is disabled.
Amend above protocol:
- Users of the logging API check the state:
    - if unknown, enter a synchronized block and check again. If state is unknown or disabled, quit. If it is now enabled, get the log stream and proceed with logging. Exit synchronized block.
   - if disabled, quit
   - if enabled, enter a synchronized block and get the log stream object. Proceed with logging. Exit synchronized block.

**Comment by pshipton** [comment]
Seems fine.

**Comment by pdbain-ibm** [comment]
Hacking this up while waiting for compilations...

https://github.com/pdbain-ibm/openj9/tree/attach_logging
