### ISSUE TITLE
Eclipse equinox launcher does not recognise OpenJ9 java 10 as modular VM

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#2051]
Mirrored from: https://bugs.eclipse.org/bugs/show_bug.cgi?id=535414

I notice that the Eclipse Photon launcher has a test isModularVM() function here:

https://github.com/eclipse/rt.equinox.framework/blob/master/features/org.eclipse.equinox.executable.feature/library/win32/eclipseWin.c

which tests jvm.dll for PRODUCT_VERSION_KEY to check the product version >= 9

Using Windows Explorer to find jvm.dll, then properties > details shows 

Oracle Java 10 has product version = 10.0.1.0 and file version 10.0.1.0

OpenJ9 has product version R2.9, file version 2.9.0.54

I don't know whether the launcher looks in the compressrefs, j9vm or server directories.

I think the result is that the Eclipse launcher thinks OpenJ9 is not a modular VM and strips off vmargs such as --add-modules=ALL-SYSTEM
To test, change in eclipse.ini --add-modules=ALL-SYSTEM to --add-modules=BADALL-SYSTEM and try to start Eclipse Photon under Oracle Java 10, and under OpenJ9 Java 10.
The Oracle version won't start, the OpenJ9 will.

Who should change - the Eclipse launcher or the OpenJ9 product version? Is there a standard way to test a VM version without starting it? The release file in the JDK root directory has a MODULES= line and
JAVA_VERSION="10.0.1"

OpenJ9, Oracle and IBM JVMs and JREs seem to all have this file. Perhaps it would be better than checking jvm.dll, but does involving finding the root of the jdk/jre.

Also consider Linux.

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this?

**Comment by keithc-ca** [comment]
I think would be better to fix eclipse as I've described in the bugzilla.

**Comment by DanHeidinga** [comment]
> I think would be better to fix eclipse as I've described in the bugzilla.

I don't see your comment in the bugzilla.  Can you mirror it here?

**Comment by keithc-ca** [comment]
From https://bugs.eclipse.org/bugs/show_bug.cgi?id=535414#c3:

I think the eclipse launcher should be improved. Relying on the output of 'java -version' or the version in jvm.dll is at best fragile. Instead I suggest that on all platforms a small Java application should be used that consults the system property 'java.specification.version'.

**Comment by pshipton** [comment]
> The release file in the JDK root directory

Keith mentioned the JRE doesn't have the release file.

**Comment by pshipton** [comment]
I think I misunderstood. If you point at the jre/bin directory, instead of the bin directory, as the location of the JVM (or set JAVA_HOME=jre), it may not be obvious that the release file would be one level higher up.

**Comment by theresa-m** [comment]
should I still be looking at fixing this in OpenJ9 until there are changes in the Eclipse launcher?

**Comment by theresa-m** [comment]
> OpenJ9 has product version R2.9, file version 2.9.0.54

out of curiosity what do these numbers actually mean?

**Comment by pshipton** [comment]
The 2.9 corresponds to the J9 version 2.9 (jvm.29, R2.9)) which originates from IBM's contribution of the code. For the 0.54, looking at [1] it seems to be the build id.

[1] https://github.com/eclipse/openj9/blob/4e26fc285d48a87ee5f56ab8cea5541491514cca/sourcetools/com.ibm.uma/com/ibm/j9/uma/platform/PlatformWindows.java#L201
