### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [eclipse/openj9#2059]
Hi @eclipse

My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (open source) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by pshipton** [comment]
We are willing to look, but no guarantee we will accept what is proposed. We did get some logo proposals around the time the project was created, but didn't like any of them enough to use them.

**Comment by tjulises** [comment]
Yes, I understand! before proceeding, I'd also like to ask some questions (towards the logo-making) @pshipton 

What's the name that should be displayed on the logo, If there should be any.

How would you describe this project,
what is it intended to do?

What would you like this logo to transmit?

this little details are going to help me transmit what it's supposed to.

I'll look forward for your reply, cheers!

**Comment by DanHeidinga** [comment]
There's a regular community call on Wednesday's at 11 AM EST run using zoom.  If you're able to attend we could discuss on the call in a high bandwidth format and hopefully get some broader community feedback.

**Comment by tjulises** [comment]
Hello @pshipton @DanHeidinga ,
I've made my first proposal, this is what I came up with, 
This is a mock up of how it would look on your site
![1](https://user-images.githubusercontent.com/39039587/41019063-0825a342-692b-11e8-8409-f0acdf5aeaed.png)
![2](https://user-images.githubusercontent.com/39039587/41019070-0e8ca7bc-692b-11e8-8003-2725c86970ef.png)

**Comment by tjulises** [comment]
@pshipton  @DanHeidinga  Hiii

**Comment by pshipton** [comment]
Others, including all the committers on the project are free to comment as well. In my opinion, it doesn't seem like enough of a difference over the existing logo to consider making a change. We could just change the colors of the existing logo if we wanted to match the website colors.

**Comment by pdbain-ibm** [comment]
Disclaimer - this is my own personal opinion

Thank you for the suggested logo.  However, I find it misleading - when I saw it, it read like "J9 Open", rather than "OpenJ9".

**Comment by ymanton** [comment]
Personally I like it, the colors are pleasing together, and the typeface is nicer than the current one. I read it as OpenJ9, but maybe that's because that's what I was looking for. I don't know how someone without prior exposure would tend to read it.

Nitpicks: the "e" doesn't line up with itself and the curve of the "n" is a bit off where it meets the vertical line.

**Comment by dsouzai** [comment]
Closing as the current logo has been in place for quite a while now.
