### ISSUE TITLE
Clarify the license / legal status (relative to Oracle).

### ISSUE THREAD

**Issue by pbannister** [eclipse/openj9#2060]
This is an ask for the documentation. Should be easy (I hope).

What is the legal status of OpenJ9 relative to Oracle? Is it in any way encumbered?

Yes, the fact that this is an Eclipse project _seems_ to implicitly answer the question. However Oracle has a history that raises questions. A simple positive statement as to any (or no) restrictions on use would clarify.

Fodder for the README. :)

(Nothing came up in a search. Perhaps I asked the wrong question.)

**Comment by mstoodle** [comment]
OpenJ9 is an independent implementation of a Java Virtual Machine built originally by IBM and open sourced under AL2+EPL2 (with secondary license matching OpenJDK's license) in September 2017.

Is that the kind of statement you were looking for? Or are you looking for something even more explicit?

**Comment by pbannister** [comment]
After Oracle bought Sun, one of my (very large) DoD customers reported a
visit from an Oracle representative, who claimed the DoD was several
million licenses out of compliance. The DoD folk were able to face down the
Oracle guy, but this behavior raises questions.

Oracle is at present (still) suing Google, over Java.

As a developer, I am unsure whether basing future projects on the JVM is a
good long-term strategic bet. Oracle's desire to extract revenue might
weigh against.

I recall (somewhat vaguely) that IBM might have some special license
status. Not sure if that is still relevant, or how that reflects on OpenJ9.

Near their end, Sun made some moves to make Java more open. This seemed of
benefit to OpenJDK. Not sure where that lands us, in present.


If I as a developer base a future project on the JVM, am I in jeopardy of
legal blackmail from Oracle, or not?

**Comment by mstoodle** [comment]
Hi @pbannister,

The FAQ here may be helpful: https://www.eclipse.org/legal/epl-2.0/

For legal advice, you would have to consult your own attorney to see if these licences are appropriate for your use.  For prebuild OpenJDK binaries, including ones with OpenJ9, we recommend going to AdoptOpenJDK.net  https://adoptopenjdk.net/?variant=openjdk8-openj9

Incidentally, I submitted a PR (#2064) with additional text for the README, as you suggested an update would be warranted. What do you think of the text I have added?

**Comment by mstoodle** [comment]
In case anyone read my comment before I updated the link, I just updated it so that the "FAQ" link actually points at Eclipse's Legal FAQ page rather than the much less "FAQ-ey" EPLv2 license page. Sorry for any confusion.

**Comment by pbannister** [comment]
Curious, that Sun is explicit in the opening page of 1996 JVM specification:

Sun Microsystems, Inc. (SUN) hereby grants to you a fully-paid,
> nonexclusive, nontransferable, perpetual, worldwide limited license
> (without the right to sublicense) under SUN's intellectual property rights
> that are essential to practice this specification. This license allows and
> is limited to the creation and distribution of clean room implementations
> of this specification that (i) include a complete implementation of the
> current version of this specification without subsetting or supersetting,
> (ii) implement all the interfaces and functionality of the standard java.*
> packages as defined by SUN, without subsetting or supersetting, (iii) do
> not add any additional packages, classes or methods to the java.* packages
> (iv) pass all test suites relating to the most recent published version of
> this specification that are available from SUN six (6) months prior to any
> beta release of the clean room implementation or upgrade thereto, (v) do
> not derive from SUN source code or binary materials, and (vi) do not
> include any SUN binary materials without an appropriate and separate
> license from SUN.



Where the more recent JVM specifications seem to entirely omit similar
text. (Or perhaps I just missed?) We are assuming the same status applies
to the current JVM specifications.

In any case, long ago IBM did a clean-room implementation of the JVM, as
allowed in the JVM specification, so IBM is free to choose the license for
their implementation, and IBM has since chosen to open-source their JVM.
This is the basis for OpenJ9.

**Comment by mstoodle** [comment]
@pbannister Whenever I've looked for it, that approximate text has been in an appendix of the JVM specification.

**Comment by pbannister** [comment]
Thanks. Did not make it down to the end of the document. (Wanted to reply,
but had limited time, earlier.) Seems paragraph 2 of the "Limited License
Grant" says substantially the same, though in less clear language. Also no
mention of "clean-room" implementations.

https://docs.oracle.com/javase/specs/jvms/se10/html/spec-license.html

So...

OpenJ9 is a "clean-room" implementation (originally by IBM) in exact
compliance with the license of the Java Virtual Machine Specification. As
an independent implementation OpenJ9 can be offered under a permissive,
open-source license.

**Comment by mstoodle** [comment]
@pbannister I'm going to close this issue because I believe your question has been resolved. Please reopen if you don't agree :) .

Note the term "clean room implementation" has been updated to "independent implementation" :) .

**Comment by pbannister** [comment]
Personally, I prefer mentioning "clean room" as that ties back to the
original license for the JVM spec. But I am entirely fine with what you
have done. My main concern was to clarify the legal status of OpenJ9
up-front for new visitors.

Thanks.

**Comment by mstoodle** [comment]
Your attention to detail is laudable :) . Hopefully the use of the currently matching "independent implementation" language + the details in this issue will be sufficient.

Thank you for helping us to clarify this aspect of the OpenJ9 project !
