### ISSUE TITLE
--illegal-access problem accessing com.ibm.tools.attach.attacher

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2062]
Andrew Johnson reported the following on Slack.
com.ibm.tools.attach.attcher is in the java8 packages list
https://github.com/eclipse/openj9/blob/b1f429438c2f3200b3ba0374d682213312b4117a/runtime/oti/j9java8packages.h#L1688

"
I was writing a test case to understand what was happening with Eclipse MAT bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=535353. The problem was that I was reflectively calling com.ibm.tools.attach.attacher.OpenJ9AttachProvider.name() instead of com.sun.tools.attach.api.AttachProvider.name() on the same object when searching the list of methods on a class of an object.

This always gives an error with OpenJ9 - the corresponding sun.tools.attach.AttachProviderImpl.name() on Oracle JDK 10 had different behaviour with --illegal-access=permit (default, generates 1 warning + message for maintainers), --illegal-access=warn (generates 1 warning) or --illegal-access=deny (throws IllegalAccessException). OpenJ9 parses the option carefully, but seems not to act on it.

I fixed the original problem by calling searching through superclasses until I found one which was not "sun.*" or "ibm.*" or "org.*" or "com.ibm.tools.attach.attacher", so this is just a comment about OpenJ9.

It's tricky to write reflection code which handles inaccessible packages because of modules, but still works on Java 8.
"

**Comment by ajohnson1** [comment]
This was the test code.
```
import com.sun.tools.attach.*;
import com.sun.tools.attach.spi.*;
import java.util.List;
import java.lang.reflect.*;
public class Attach
{
    public static void main(String args[]) throws Exception
    {
        List<AttachProvider> provs = AttachProvider.providers();
        int provcount = provs.size();
        for (AttachProvider prov : provs)
        {
            System.out.println("provider "+prov.name()+" "+prov.getClass());
            Class ifs[] = prov.getClass().getInterfaces();
            for (Class cls : ifs) {
              Method ms[] = cls.getMethods();
              for (Method m : ms) {
                if (m.getParameterTypes().length == 0 && m.getName().equals("name")) {
                     System.out.println(Modifier.toString(cls.getModifiers())+" "+cls.getName()+" "+Modifier.toString(m.getModifiers())+" "+m.getName());
                     //if (cls.getPackage().getName().equals("com.ibm.tools.attach.attacher"))
                     //    continue;
                     Object z = m.invoke(prov);
                     System.out.println(z);
                }
              } 
            }
            for (Class cls = prov.getClass(); cls != null; cls = cls.getSuperclass()) {
            Method ms[] = cls.getMethods();
            for (Method m : ms) {
                if (m.getParameterTypes().length == 0 && m.getName().equals("name")) {
                     System.out.println(Modifier.toString(cls.getModifiers())+" "+cls.getName()+" "+Modifier.toString(m.getModifiers())+" "+m.getName());
                     //if (cls.getPackage().getName().equals("com.ibm.tools.attach.attacher"))
                     //    continue;
                     Object z = m.invoke(prov);
                     System.out.println(z);
                }
            }
            }
        }
    }
}
```
I ran it using:
```
java Attach
```
```
java --illegal-access=pemrit Attach
```
```
java --illegal-access=warn Attach
```
```
java --illegal-access=deny Attach
```

I don't think that com.ibm.tools.attach.attacher needs to be accessible - calling the method on the class from com.sun.tools.attach.spi package works.

**Comment by pshipton** [comment]
@pdbain-ibm can you please take a look when you have time.

**Comment by pdbain-ibm** [comment]
Working on it now.

**Comment by pdbain-ibm** [comment]
modularityHelper.isPackageExportedToModuleHelper() is a native which lists the legacy Java 8 packages to be exported to unnamed modules.

**Comment by pdbain-ibm** [comment]
The list of packages to open is stored in `jdk/modules/java.base/jdk/internal/module/jdk8_packages.dat`
 and is processed by `jdk.internal.module.IllegalAccessMaps.generate()`

**Comment by pdbain-ibm** [comment]
OpenJ9 uses a file `runtime/oti/j9java8packages.gperf` to generate a list of packages for use by native code.  `j9unique.txt` contains a list of packages in `j9java8packages.gperf` only and	 `jdk8unique.txt` contains packages in `jdk8_packages.dat`.
[j9unique.txt](https://github.com/eclipse/openj9/files/2233040/j9unique.txt)
[jdk8unique.txt](https://github.com/eclipse/openj9/files/2233041/jdk8unique.txt)
