### ISSUE TITLE
get test compilation ready for JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2071]
http://cr.openjdk.java.net/~iris/se/11/latestSpec/

Some links for detail in JDK11:
- Avoid use of the java.se.ee code in testing
Due to https://github.com/eclipse/openj9/issues/992, tests need to be updated to avoid use of the java.se.ee code, as it won't exist in JDK11. https://bugs.openjdk.java.net/browse/JDK-8189188
- java.lang.System#runFinalizersOnExit(boolean)is removed in JDK11 based on https://bugs.openjdk.java.net/browse/JDK-8198250
- remove terminally deprecated sun.misc.Unsafe.defineClass https://bugs.openjdk.java.net/browse/JDK-8199699
- Remove terminally deprecated SecurityManager APIs
https://bugs.openjdk.java.net/browse/JDK-8200185

Following projects have compilation error:

- [x] Java8andUp #2404
- [x] Java9andUp  #2198
- [x] Jsr335  #2136
- [x] VM_Test  #2186
- [x] cmdLineTests/jvmtitests #2326
- [x] SharedCPEntryInvokerTests
- [x] JIT_Test #2439

**Comment by babsingh** [comment]
@llxia using JDK11, i got other compile errors after ignoring tests that rely upon java.se.ee code. (Rename `build.xml` - a hack to ignore `functional/UnsafeTest` and `functional/Java8andUp`.)

```
    [javac] /openj9-openjdk/openj9/test/functional/Java9andUp/src/org/openj9/test/constantPoolTags/ConstantPoolTagTests.java:94: error: cannot find symbol
    [javac] 			Class<?> test = unsafe.defineClass(className, classBytes, 0,
    [javac] 			                      ^
    [javac]   symbol:   method defineClass(String,byte[],int,int,ClassLoader,ProtectionDomain)
```

may be this issue can aim at successfully compiling openj9/tests with JDK11.

**Comment by llxia** [comment]
With JDK11, `module name in --add-exports option not found: java.xml.bind`. And tests that uses this package failed in compilation. Is this expected?

```
[javac] warning: [options] module name in --add-exports option not found: java.xml.bind
...
/test/functional/Java8andUp/src/org/openj9/test/annotationPackage/Test_PackageAnnotation.java:34: error: package javax.xml.bind.annotation does not exist
    [javac] import javax.xml.bind.annotation.XmlSchema;
    [javac]                                 ^
    [javac] /test/functional/Java8andUp/src/org/openj9/test/annotationPackage/Test_PackageAnnotation2.java:31: error: package javax.xml.bind.annotation does not exist
```

**Comment by llxia** [comment]
`java.lang.System#runFinalizersOnExit(boolean)`is removed in JDK11 based on https://bugs.openjdk.java.net/browse/JDK-8198250

**Comment by llxia** [comment]
Close this issue as all PRs are delivered. Tests can compile successfully with JDK11.

**Comment by jluehe** [comment]
@pshipton, do you know of any artifact that exports javax.activity, which used to be made available by java.corba module?

**Comment by pshipton** [comment]
javax.activity is removed from Java 11. The tests need to stop using it.

**Comment by Talk2Harish** [comment]
use openjdk-orb in maven dependency 
<dependency>
	<groupId>org.jboss.openjdk-orb</groupId>
	<artifactId>openjdk-orb</artifactId>
	<version>8.1.1.Final</version>
</dependency>
