### ISSUE TITLE
Building tests added untracked file to git repo

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2111]
I compiled the Java 8 test material according to the quick start quide, and afterward the following untracked file was present in the git repo.

test/functional/Java8andUp/src/org/openj9/test/NoSuchMethod/AppLoaderCallee.java

**Comment by fjeremic** [comment]
This seems to be the offender:

https://github.com/eclipse/openj9/blob/8d42939fe55cacf5b956e47afbcddb8cb0e959fe/test/functional/Java8andUp/build.xml#L67

**Comment by smlambert** [comment]
I believe the untracked files are now checked in via https://github.com/eclipse/openj9/pull/2404 so will close this issue.
