### ISSUE TITLE
OOM native memory exhausted

### ISSUE THREAD

**Issue by ysstech** [eclipse/openj9#2115]
version：java_1.7_64
cause：Dump Event "systhrow" (00040000) Detail "java/lang/OutOfMemoryError" "native memory exhausted" receive
---
What config is decided by native memory？How is it calculated？
PS：Server physical memory is 32G，JVM heap 4G，no alarm。

![image](https://user-images.githubusercontent.com/23044050/41101352-7f238f42-6a96-11e8-967a-e16d84ac1e12.png)

**Comment by smithwil** [comment]
The table pasted here shows the java object heap "Object(reserved)" is full. The java heap maximum size is set by the Xmx option. Could you share the output from "java -version" so we can tell what java you're running?

**Comment by dmitripivkine** [comment]
You can refer to Native Memory Usage (NATIVEMEMINFO) section in javacore. There is a detailed description of Native memory usage by JVM

**Comment by smithwil** [comment]
The javacore text dump format is produced by default by the OpenJ9 Java VM when there is an OOME, though if you are running a Java 7 that has a different Java VM, there will probably not be a javacore. The java -version output would help to show the VM in use.

**Comment by ysstech** [comment]
Tanks.
Heap config is  -Xms4096m -Xmx4096m, But NATIVEMEMINFO list about JRE has 5G, why?
----
JAVAVERSION JRE 1.7.0 Linux amd64-64 build 20130421_145945 (pxa6470sr4fp1ifix-20130423_02(SR4 FP1+IV38579+IV38399+IV40208) )

----
NATIVEMEMINFO
JRE: 5,918,381,174 bytes / 114441 allocations
1MEMUSER       |
2MEMUSER       +--VM: 5,629,125,830 bytes / 100238 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 494,574,608 bytes / 40888 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Shared Class Cache: 94,371,936 bytes / 2 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 400,202,672 bytes / 40886 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 4,408,520,104 bytes / 10579 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 4,294,967,296 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 113,552,808 bytes / 10578 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Threads: 676,706,958 bytes / 11515 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Stack: 56,528,264 bytes / 2229 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Native Stack: 587,366,400 bytes / 2230 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 32,812,294 bytes / 7056 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Trace: 19,018,968 bytes / 6579 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JVMTI: 116,568 bytes / 119 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--JVMTI Allocate(): 10,128 bytes / 75 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 106,440 bytes / 44 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JNI: 14,122,888 bytes / 23217 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Port Library: 4,699,144 bytes / 151 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Unused <32bit allocation regions: 4,675,128 bytes / 4 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 24,016 bytes / 147 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 11,366,592 bytes / 7190 allocations
1MEMUSER       |
2MEMUSER       +--JIT: 203,327,328 bytes / 5033 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 77,594,624 bytes / 37 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 46,138,752 bytes / 22 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 79,593,952 bytes / 4974 allocations
1MEMUSER       |
2MEMUSER       +--Class Libraries: 85,928,016 bytes / 9170 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Harmony Class Libraries: 2,000 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--VM Class Libraries: 85,926,016 bytes / 9169 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--sun.misc.Unsafe: 85,780,744 bytes / 8982 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Direct Byte Buffers: 41,090,952 bytes / 8542 allocations
4MEMUSER       |  |  |  |
5MEMUSER       |  |  |  +--Other: 44,689,792 bytes / 440 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 145,272 bytes / 187 allocations

**Comment by smithwil** [comment]
The java object heap size is reported in the subsection "Java Heap: 4,294,967,296 bytes". This is the 4GB space to store java objects. All the other memory categories are for other data that the Java VM uses to maintain the runtime environment such as loading class data, JIT compilation, garbage collection record keeping, and also for storing some application data allocated for JNI methods.

**Comment by imkabir** [comment]
@ysstech Note that the memory allocations you see in NATIVEMEMINFO section, and the virtual memory size from "top" will almost always be different. NATIVEMEMINFO shows the direct allocations by Java, but there will be memory used by OS and JNI calls for the process which are not accounted for here, but is captured in top output.

If the OOM is your primary concern, for 64-bit JVM this happens because of process memory exhaustion under the 4GB memory mark.  There can be many different reasons why this happens. Here is a document on one of the most common ones:

http://www-01.ibm.com/support/docview.wss?uid=swg21660890

**Comment by ysstech** [comment]
@smithwil 
About 『All the other memory categories』，How allocate it? How to configure in J9？

**Comment by ysstech** [comment]
Thank you for everyone.
