### ISSUE TITLE
support exclude folder in TKG

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2123]
Currently, users can provide a Build_List for the projects that they want to compile and run. It may be convenient for users if we can support exclude folders in TKG. So that users can exclude the projects that they do not want to compile and run.

**Comment by llxia** [comment]
fyi @renfeiw

**Comment by smlambert** [comment]
I think this is partially addressed now, and perhaps any further enhancement could be captured as an enhancement feature in https://github.com/AdoptOpenJDK/TKG now that it is moved to a standalone repository.

Shall we close this issue ?

**Comment by llxia** [comment]
Yes, I think this is partially addressed by test list. I will close this issue.
