### ISSUE TITLE
Windows JDK8 jvmti tests failed with "NPT ERROR: Cannot open library"

### ISSUE THREAD

**Issue by liqunl** [eclipse/openj9#2129]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/36/tapResults/
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/48/tapResults/

Error message:
```
===============================================
Running test cmdLineTester_jvmtitests_extended_3 ...
===============================================
cmdLineTester_jvmtitests_extended_3 Start Time: Wed Jun  6 12:08:27 2018 Epoch Time (ms): 1528304907512
test with Mode154
NPT ERROR: Cannot open library

cmdLineTester_jvmtitests_extended_3_FAILED
```

Failing tests are
```
cmdLineTester_jvmtitests_extended_3
cmdLineTester_jvmtitests_extended_7
cmdLineTester_jvmtitests_extended_8
cmdLineTester_jvmtitests_extended_9
cmdLineTester_jvmtitests_extended_11
decompileAtMethodResolve_0
```

**Comment by liqunl** [comment]
Close this issue as a duplicate of https://github.com/eclipse/openj9/issues/2009

**Comment by liqunl** [comment]
Notice that there are nightly builds whose commits are more advanced than the PRs that failed the tests. I downloaded one nightly build and tried the same tests on my laptop and can't reproduce the error. Since we don't archive builds for PRs, I have no chance to test the failing builds.

I tried running the test on my laptop with `npt.dll` removed, the same error occurred. Thus, I believe the error is not caused by jit/vm/gc changes. If the same tests passed in nightly build but failed in PR builds, I suspect there is a problem in the packaging process for windows builds triggered by PR's jenkins sanity test. @smlambert @llxia

**Comment by pshipton** [comment]
A few PR builds are keep as attachments to the build jobs. You'll need to grab it quickly after a failures occurs.

I couldn't find a failed job that was still available, but as an example see the "Build Artifacts" of  https://ci.eclipse.org/openj9/job/Build-JDK8-win_x86-64_cmprssptrs/84/

**Comment by liqunl** [comment]
According to @AdamBrousseau, we don't keep the builds for PR's jenkins test. I didn't find any link to the failing build in the failing PRs. The "Build Artifacts" of this failing build contains only the result of the tests. https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-win_x86-64_cmprssptrs-OpenJ9/3/

The latest nightly build is more advanced than the failing PRs, however, the failure is not reproducible on the nightly builds. Thus the failure is not caused by any jit/gc/vm commits. I think the problem is either in machine, testing or packaging process, with the last one being the most likely.

If anyone can provide me a failing build, I'd love to test it on my laptop.

**Comment by pshipton** [comment]
You need to look at the "Build" job which created the JVM used by the Extended test job.

**Comment by pshipton** [comment]
Maybe I was looking at the wrong type of builds.

**Comment by smlambert** [comment]
To be clear, the [jvmti_extended tests should be renamed](https://github.com/eclipse/openj9/issues/2147) (no tests should contain the level they belong to), especially since they are tagged as sanity tests, so you'd look to see what JVM is used by the nightly sanity test job.

I believe the some tests are failing because they are running with compressedrefs commandline parameters against a nocompressedrefs build.

**Comment by pshipton** [comment]
> I believe the some tests are failing because they are running with compressedrefs commandline parameters against a nocompressedrefs build.

This should result in an error from the VM from which the problem should be obvious https://github.com/eclipse/openj9/pull/1777#issuecomment-384674994

**Comment by AdamBrousseau** [comment]
I think @liqunl was having troubles getting an sdk that could produce the error since the nightly is the only ones we archive and the error was never seen in the nightly. If your PR is still seeing this error we could hack the Jenkins files in your PR in order to archive the sdk for your build. PM me if you want to discuss going this route.

**Comment by liqunl** [comment]
My PR has been merged.

I want to clarify that, this is not caused by any PR that has failed the test. The reason being:
1. This failure has been seen on PRs with completely difference changes.
2. Two of the PRs that have failed the tests have been merged, the nightly build and continuous build containing the changes of the two PRs have passed.

Correct me if I'm wrong, it looks like the failing tests have never passed in a PR build since they were added.

I think we need to understand why this error only occurs in PR builds but not nightly/continuous builds or internal personal builds, i.e. what's different in the PR builds. It can be the machine, the testing environment, or the resulting jdk. 

All in all, I think we need someone from the test or infra team to take a look at this issue based on it's nature. I tried my best last Friday, but I can't help if it is not a jit issue.

**Comment by babsingh** [comment]
**Possible solution** - [Create a link to libnpt.so in $JAVA_HOME/jre/lib from /usr/local/lib](https://blog.art-of-coding.eu/java-and-npt-library-not-found-error/)
`ln -s <JAVA_HOME>/jre/lib/amd64/libnpt.so /usr/local/lib/libnpt.so`

The above solution works on FreeBSD. For Windows, Adam said that the nightly builds work fine. But, `NPT ERROR: Cannot open library` is encountered for the PR builds. 

`NPT ERROR: Cannot open library` is related to `-Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo` and absence of `libnpt.so`. We need to figure why the required dependencies are missing in the PR builds.

**Comment by llxia** [comment]
Not related to the failure, but the test level is wrong. It should be in `extended` not `sanity`. Issue 
 https://github.com/eclipse/openj9/issues/2165 is opened to address this.

**Comment by llxia** [comment]
Also seen `TestRefreshGCSpecialClassesCache` failed with `NPT ERROR: Cannot open library` error in PR build. https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-win_x86-OpenJ9/1/tapResults/

**Comment by andrewcraik** [comment]
@llxia @DanHeidinga @pshipton and @AdamBrousseau what is the next action on this - we are getting in the habit of ignoring the failures in the sanity builds (referenced above) and that is a dangerous precedent. Either the test is important enough to fix or we should exclude the affected tests. I'm hoping we just need to add the libnpt.dll on the windows machines or something?

**Comment by llxia** [comment]
As mentioned above, the issue only happens on wins PR build. The wins nightly build is fine.
Link to wins JDK8 nightly build: https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-win_x86-64_cmprssptrs/

I do not think this is machine issue as I saw PR build failed and night build passed on same machine `win2012r2-x86-3`:
failed: https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/119/
passed: https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-win_x86-64_cmprssptrs/133/

Is the SDK built the same for wins PR build and wins nightly build?

**Comment by AdamBrousseau** [comment]
Yes the SDK is built the same way in pr builds as nightly (uses the same code). The only difference I can think of would be in a PR we use the same machine and workspace to test where we just compiled. Compared to a nightly where we zip up the SDK and move to a different machine. I did a PR build a few weeks back and saved the SDK (which had the same test failure). I haven't had a chance to test the zip to see if I can reproduce.

**Comment by theresa-m** [comment]
I manually ran the tests with Adam's saved pr build sdk and the tests are passing.

I then ran a build and these tests on the same machine to replicate the pr build and the tests fail with `NPT ERROR: Cannot open library`.

**Comment by fjeremic** [comment]
Judging from the giant list of references above it seems we are hitting this issue every single time we launch a build. This seems like a high priority issue to me. @pshipton @AdamBrousseau any leads as to what is causing it or potential workarounds? If not we should disable the tests until we get this fixed IMO.

**Comment by pshipton** [comment]
The fix is https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/106 but its not ready to merge yet and won't be until next week unless somebody else wants to address the review comments.

**Comment by pshipton** [comment]
The immediate problem is fixed (for Windows) by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/107. Opened #2547 to handle remaining platforms and other jdk versions.
