### ISSUE TITLE
Top level OpenJ9 test makefile usage is incorrect 

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9#213]
Now, `test/README.md` indicates the makefile to use is actually `test/TestConfig/Makefile`, but there is a `test/Makefile`, and inside the makefile it suggests usage info: 

https://github.com/eclipse/openj9/blob/3b34d58942a9c34271fe7d9fdcda46201c5f7631/test/Makefile#L23-L41

However, trying that out it seems to ignore the very SPEC it requests: 

```
magaudet@ubuntu1604VM:~/open/openj9-openjdk-jdk9/openj9/test (master)*$ make JAVA_BIN=/home/magaudet/open/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/bin/ SPEC=linux_x86-64_cmprssptrs
Running sanity tests
(cd /home/magaudet/open/openj9-openjdk-jdk9/openj9/test/TestConfig && \
	make JAVA_BIN=/home/magaudet/open/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/bin/ SPEC= JAVA_VERSION=SE90 sanity)
make[1]: Entering directory '/home/magaudet/open/openj9-openjdk-jdk9/openj9/test/TestConfig'
Running make 4.1
set JAVA_BIN to /home/magaudet/open/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/bin/
makefile:59: *** Please provide SPEC that matches the current platform (e.g. SPEC=linux_x86-64).  Stop.
make[1]: Leaving directory '/home/magaudet/open/openj9-openjdk-jdk9/openj9/test/TestConfig'
Makefile:100: recipe for target 'test_sanity' failed
make: *** [test_sanity] Error 2
```

I think this is related to an attempt to auto-detect SPEC using a 'SPEC file'? 

https://github.com/eclipse/openj9/blob/3b34d58942a9c34271fe7d9fdcda46201c5f7631/test/Makefile#L48-58 

Note that `ADD_CMD_ARGS` will overwrite SPEC with whatever is in J9_SPEC. 

Passing `J9_SPEC=linux_x86-64_cmprssptrs` does work, but isn't what is documented, nor is it clear if this is the intended behaviour.

**Comment by llxia** [comment]
As far as I know, this file was created for internal builds. I think it can be removed for openJ9.
@vsebe and @renfeiw please correct me if I am wrong. Thanks.

**Comment by vsebe** [comment]
If removed, please fix the openj9 sanity and extended tests in the internal builds.
