### ISSUE TITLE
test.getDependency job failing

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#2144]
https://ci.eclipse.org/openj9/view/Infrastructure/job/test.getDependency/
```
00:07:09.519 + perl ./getDependencies.pl -path . -task default
00:07:09.519 ERROR: os not defined! 
```

Last good build was June 1st.

I believe it is this change that has caused the failure. @renfeiw 
https://github.com/eclipse/openj9/commit/0da64dcc97264a55a620fee45b7730a973853ceb#diff-b8aeab3b6cb4bcc650c6e3080d1d580a

**Comment by renfeiw** [comment]
I have fixed it by providing the required option os in Jenkins job command.
