### ISSUE TITLE
Dockerfile(s) not working

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#2152]
Dockerfile(s) that rely on AdoptOpenJDK API to get the bootjdk are not working because AdoptOpenJDK API service is down or doesn't have the required builds.

AdoptOpenJDK API service doesn't work for **openjdk9**. AdoptOpenJDK API service works fine for **openjdk8**.

- Download [openjdk9-openj9-x64-linux](https://api.adoptopenjdk.net/openjdk9-openj9/releases/x64_linux/latest/binary) [This link won't work]
- Download [openjdk8-openj9-x64-linux](https://api.adoptopenjdk.net/openjdk8-openj9/releases/x64_linux/latest/binary) [This link works]

The following Dockerfile(s), that use openjdk9 as the bootjdk, are impacted:
- `buildenv/docker/jdk10/aarch64_CC/arm-linux-aarch64/Dockerfile`
- `buildenv/docker/jdk10/armhf_CC/arm-linux-gnueabihf/Dockerfile`
- `buildenv/docker/jdk10/ppc64le/ubuntu16/Dockerfile`
- `buildenv/docker/jdk10/ppc64le/ubuntu18/Dockerfile`
- `buildenv/docker/jdk10/s390x/ubuntu16/Dockerfile`
- `buildenv/docker/jdk10/s390x/ubuntu18/Dockerfile`
- `buildenv/docker/jdk10/x86_64/ubuntu16/Dockerfile`
- `buildenv/docker/jdk10/x86_64/ubuntu18/Dockerfile`

**Workaround** is to replace the bootjdk link in the Dockerfile with an active AdoptOpenJDK nightly build link - https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9.

**Comment by babsingh** [comment]
fyi - @pshipton

**Comment by pshipton** [comment]
We can replace the "latest" builds with a release build. There is a release build for Java 8 OpenJ9 0.8, or we can wait until there is a release build for 0.9 if the known limitations in the 0.8 release cause any issues. 

For Java 9, perhaps we can convince Adopt to create a release from OpenJ9 0.9, which can serve as the final Java 9 build of OpenJ9, following which OpenJ9 will not make any efforts to keep Java 9 working.

**Comment by babsingh** [comment]
@pshipton for convincing Adopt to create a release from OpenJ9 0.9, do we need to open an issue somewhere?

**Comment by pshipton** [comment]
I expect so, we'll have to figure out which repo to create it in. I'll add it to the agenda of the OpenJ9 community call today.

**Comment by pshipton** [comment]
The issue should be created at https://github.com/AdoptOpenJDK/openjdk-build/issues

**Comment by babsingh** [comment]
AdoptOpenJDK Issue - https://github.com/AdoptOpenJDK/openjdk-build/issues/370

**Comment by babsingh** [comment]
Releases for **openjdk9-openj9** are available at AdoptOpenJDK: https://adoptopenjdk.net/archive.html?variant=openjdk9&jvmVariant=openj9.

Now, the following bootJDK links in JDK10 Dockerfiles work:
1) **openjdk9-openj9 x64_linux**: https://api.adoptopenjdk.net/openjdk9-openj9/releases/x64_linux/latest/binary
2) **openjdk9-openj9 ppc64le_linux**: https://api.adoptopenjdk.net/openjdk9-openj9/releases/ppc64le_linux/latest/binary
3) **openjdk9-openj9 s390x_linux**: https://api.adoptopenjdk.net/openjdk9-openj9/releases/s390x_linux/latest/binary

Thus, closing this issue.

**Comment by smlambert** [comment]
FYI, you may wish to update those bootJDK links to use the v2 version of the API at AdoptOpenJDK 
(described here: https://api.adoptopenjdk.net/README).  While those v1 links still work, I assume the use of the v1 api is deprecated now.
