### ISSUE TITLE
GC/Metronome crashed the JVM  j9mm.107 (ASSERTION FAILURE)

### ISSUE THREAD

**Issue by sinus0** [eclipse/openj9#2159]
A JVM running an active network application have crashed with dumpfiles after ~30 minutes of work. messages are: 

17:16:47.008 0x10d3c00    j9mm.107    *   ** ASSERTION FAILED ** at RealtimeMarkingScheme.cpp:1162: ((false && (gcEnv->_referenceObjectBuffer->isEmpty())))
17:16:47.008 0x1103900    j9mm.107    *   ** ASSERTION FAILED ** at RealtimeMarkingScheme.cpp:1162: ((false && (gcEnv->_referenceObjectBuffer->isEmpty())))

Observed on JDK 9 and JDK 10 builds by OpenJ9
[javacore.20180606.174121.211190.0003.txt](https://github.com/eclipse/openj9/files/2095262/javacore.20180606.174121.211190.0003.txt)

**Comment by pshipton** [comment]
1CIJAVAVERSION JRE 1.8.0 Linux amd64-64 (build 1.8.0_162-b12)
1CIVMVERSION   20180315_120
1CIJ9VMTAG     openj9-0.8.0
1CIJ9VMVERSION e24e8aa9
1CIJITVERSION  e24e8aa9
1CIOMRVERSION  3e8296b4_CMPRSS
1CIJCLVERSION  ee1e77df1d based on jdk8u162-b12

@amicic @dmitripivkine fyi

**Comment by pshipton** [comment]
@sinus0 you might try the latest nightly build instead of the 0.8 build, there have been many fixes since then. We expect OpenJ9 0.9 to be released shortly.

**Comment by amicic** [comment]
I wonder if this assert is valid. 

In the equivalent non-RT marking code (MM_MarkingSchemeRootClearer::scanPhantomReferenceObjects), there is no assert but actually a buffer flush. It's expected for buffer to be non empty, if the previous step in clearable roots scanning (unfinalized object processing), which can discover new live objects, happened to discover a phantom (or even soft/weak) reference.
