### ISSUE TITLE
Need an easier way to exclude tests

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse/openj9#216]
Currently, to exclude a test directory, we need to edit the `mkgen.pl` in the `test/TestConfig/scripts`. There should be a file (possibly in `test/TestConfig/resources/excludes`) that contains a list of tests or test directories to exclude from compilation and generation so people don't need to dig through a script.

**Comment by llxia** [comment]
Hi Mike, could you please describe your scenario where this feature is needed? So I can better understand this. In the current implementation, we do support:

- exclude test(s) if they are using TestNG framework

- run test in a directory

Also, for your personal test, you can rename playlist.xml in your test project directory to exclude all tests in this test project from make generation and execution.

**Comment by mikezhang1234567890** [comment]
This feature would be needed if we add tests for future versions of Java. I did not realize we could move or rename the playlist.xml to exclude from testing.

**Comment by andrew-m-leonard** [comment]
The current test/TestConfig/resources/excludes also only allows testcase "classes" to be excluded, if I need to exclude a "commandLineTester" type playlist entry, I cannot. the only way is to actually delete the test from the playlist.xml, not evening commenting it out removes it...!

**Comment by llxia** [comment]
I agree. We need a generic solution to support different tests exclude.
@renfeiw , I think we can have tag in playlist.xml to exclude any test (i.e., <defect>) and we should support it be commented out.

**Comment by smlambert** [comment]
This issue is addressed by #976 which adds support for <disabled> tag in playlist.xml file, a common and preferred way to exclude all types of tests.
