### ISSUE TITLE
xlinux machines are out of disk space, failing PR builds

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2161]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK10-linux_x86-64-OpenJ9/57/
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs-OpenJ9/86/
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_x86-64-OpenJ9/53/

1, 3, 4 failed here.

@jdekonin fyi

**Comment by keithc-ca** [comment]
It wasn't just xlinux; I believe when I checked, the Windows job failed similarly. 
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/66/

**Comment by pshipton** [comment]
The Windows issue is #2129

**Comment by AdamBrousseau** [comment]
I don't yet understand why these failed, there's plenty of space on the nodes and the master

**Comment by AdamBrousseau** [comment]
Restarted 3 & 4, waiting for 1 & 2 to finish jobs then will restart them too. Please close, we can reopen if the issue recurs.

**Comment by pshipton** [comment]
@hangshao0 
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs-OpenJ9/86/
failed trying to create a shared cache. It seems there is a problem with the logic to fall back to smaller sizes. Can you please create another issue for this and investigate.
```
 [ERR] JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 196653056, requested bytes = 314572800.
```

**Comment by hangshao0** [comment]
Issue created here: https://github.com/eclipse/openj9/issues/2174

**Comment by pshipton** [comment]
@AdamBrousseau I believe the machines have been fixed, and the cleaning job updated, I'll go ahead and close.
