### ISSUE TITLE
Class.getDeclaredMethod's behavior is not consistent with API documentation

### ISSUE THREAD

**Issue by unshorn** [eclipse/openj9#2162]
In the case a class has more than one method matching the signature supplied to either `getDeclaredMethod` or `getMethod`, the behavior specified by the [API documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getMethod-java.lang.String-java.lang.Class...-) is that it should return the method which has the more specific return type. Example.: for `Bar.class.getDeclaredMethod("foo")` where `Bar` is defined as :
```
class Bar {
  java.util.Collection foo() { return null; }
  java.util.List foo() { return null; }
}
```

it should return the method: ` List foo()`

The current implementation relies on `getClassDepth` to determine the most specific return type, and as `java.util.List` and `java.util.Collection` have the same depth (1) it does not make a distinction between the two methods and may return the method: `Collection foo()`, which violates the API specification..

**Comment by JasonFengJ9** [comment]
Will have a look this.
