### ISSUE TITLE
cmdLineTester_jvmtitests_extended test level is wrong

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2165]
`cmdLineTester_jvmtitests_extended` should be in `extended` level not `sanity`. 
https://github.com/eclipse/openj9/blob/ef9a7abd00e1b27888e79645ba1a8723707e5155/test/functional/cmdLineTests/jvmtitests/playlist.xml#L165

**Comment by smlambert** [comment]
related: #2147

**Comment by llxia** [comment]
@smlambert Sorry, I did not notice you open an issue for this already. I will close this one since it is duplicate.

**Comment by smlambert** [comment]
that's ok, mine was slightly different, involving a rename... but agree we do not need 2 issues for the action that should happen next :)
