### ISSUE TITLE
Please upgrade to Ant 1.9.7

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2171]
This version adds elements for compiling modules, such a <modulepath>, < modulesourcepath> et al.

<modulepath> adds path elements in a portable fashion without having to use `<compilerarg line="-p directory1:directory2:my.jar"/>`, with the complication of OS-dependent path separators.

**Comment by dsouzai** [comment]
Is this still relevant, or can this be closed?

**Comment by DanHeidinga** [comment]
Closing this as any update will be driven by work requiring it.
