### ISSUE TITLE
We should use a smaller shared cache size when there is not enough disk space

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9#2174]
We are seeing test failures like the following due to limited disk space 

> Running command: "/home/jenkins/workspace/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs-OpenJ9/build/linux-x86_64-normal-server-release/images/jdk/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI  -Xdump    -agentlib:jvmtitest=test:aln001 -cp "/home/jenkins/workspace/PullRequest-Sanity-JDK10-linux_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
> 19:05:48 Time spent starting: 38 milliseconds
> 19:05:48 Time spent executing: 98 milliseconds
> 19:05:48 Test result: FAILED
> 19:05:48 Output from test:
> 19:05:48  [ERR] JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 196653056, requested bytes = 314572800.
> 19:05:48  [ERR] JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
> 19:05:48  [ERR] Error: Could not create the Java Virtual Machine.
> 19:05:48  [ERR] Error: A fatal exception has occurred. Program will exit.
> 19:05:48 >> Success condition was not found: [Return code: 0]

**Comment by pshipton** [comment]
@mpirvu fyi

**Comment by mpirvu** [comment]
The proposed change make sense, though maybe we should generate some sort of a warning, otherwise we could transform a functional issue into a performance issue.

From the testing point of view it gets tricky: machines with little free disk space will silently use smaller caches and we may not be testing the real thing.

**Comment by hangshao0** [comment]
> The proposed change make sense, though maybe we should generate some sort of a warning, otherwise we could transform a functional issue into a performance issue.

> From the testing point of view it gets tricky: machines with little free disk space will silently use smaller caches and we may not be testing the real thing.

There are users that do not want to see messages printed to their console. I will add a trace point if we detect the free disk space is low. We can enable this trace point to know if the expected cache size is used or not.

**Comment by mpirvu** [comment]
We should update the documentation as well.

**Comment by pshipton** [comment]
I marked the PR with the label "doc:externals" so it will get picked up for the doc.

**Comment by pshipton** [comment]
Once we get past the OpenJ9 0.9.0 release, making the doc changes will be part of the work of making a change. I don't think we are quite set up for that yet @SueChaplain ?

**Comment by SueChaplain** [comment]
Not quite @pshipton. The intention is that every external change has a doc:externals label and the person owning the code change raises an issue at eclipse/openj9-docs. We have created templates to help people provide all the right information (of course they are free to contribute the actual changes if they want too). We should probably add something to CONTRIBUTING.md in the OpenJ9 repo? And we should find the best way to communicate to all the existing contributors. Any thoughts/recommendations welcome.

**Comment by ashu-mehra** [comment]
> we should find the best way to communicate to all the existing contributors.

One thing we can do is to send a note on openj9 mailing list.

**Comment by pshipton** [comment]
> We should probably add something to CONTRIBUTING.md in the OpenJ9 repo?

+1

We need to ensure all the committers are aware. I expect using Slack is fine, but can send to the mailing list if you like. As long as the committers are aware of the process, they will request the contributors to do the right things.

**Comment by SueChaplain** [comment]
@pshipton @hangshao0 Which OpenJ9 release did this target. Doc is not yet updated as it was not targeted for 0.9.0 but it looks like all the work is merged. Please confirm.

**Comment by hangshao0** [comment]
The code change is in v0.9.0.

**Comment by SueChaplain** [comment]
I've been basing 0.9.0 content on items that target the 0.9.0 milestone: https://github.com/eclipse/openj9/milestone/2?closed=1

This wasn't in it, so has missed the what's new and release notes. Please confirm where it landed and we'll have to retrospectively update the OpenJ9 user docs, OpenJ9 release notes and downstream documentation (IBM).

@pshipton - let's discuss how we can avoid this going forward.

**Comment by hangshao0** [comment]
> Please confirm where it landed and we'll have to retrospectively update the OpenJ9 user docs, OpenJ9 release notes and downstream documentation (IBM).

This change is in OpenJ9 v0.9.0. This change applies to Java 9 and up. But I think IBM SDK does not have a Java 9+ release yet.
