### ISSUE TITLE
YourKit testing bytecode instrumentation gpf compiling method

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2175]
1XHEXCPMODULE  Compiling method: com/ibm/jit/JITHelpers.isArray(Ljava/lang/Object;)Z

```
1CIJAVAVERSION JRE 1.8.0 Windows 10 x86-32 (build 1.8.0_172-adoptopenjdk-_2018_06_13_07_21-b00)
1CIVMVERSION   20180613_21
1CIJ9VMVERSION b8253882
1CIJITVERSION  b8253882
1CIOMRVERSION  e2f65411
1CIJCLVERSION  d587cde1 based on jdk8u172-b11
```

[javacore.20180613.203047.7396.0002.txt](https://github.com/eclipse/openj9/files/2099497/javacore.20180613.203047.7396.0002.txt)

```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "JIT Compilation Thread-0" J9VMThread:0x2316BB00, omrthread_t:0x009B79B4, java/lang/Thread:0x221EEB60, state:R, prio=10
3XMJAVALTHREAD            (java/lang/Thread getId:0x2, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x2BE8, native priority:0xB, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00002000)
3XMCPUTIME               CPU usage total: 0.296875000 secs, user: 0.125000000 secs, system: 0.171875000 secs, current category="JIT"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           No Java callstack available without taking locks
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               Java_java_lang_invoke_MutableCallSite_invalidate+0x1c8a86 (0x62BCEF46 [j9jit29+0x23ef46])
4XENATIVESTACK               Java_java_lang_invoke_MutableCallSite_invalidate+0x481c5f (0x62E8811F [j9jit29+0x4f811f])
4XENATIVESTACK               Java_java_lang_invoke_MutableCallSite_invalidate+0x49813f (0x62E9E5FF [j9jit29+0x50e5ff])
```

**Comment by gacholio** [comment]
JITHelpers should probably be in the list of non-instrumentable classes.

**Comment by gacholio** [comment]
jvmtiHook.c : canClassBeInstrumented to prevent load-time modification.

hshelp.c : classIsModifiable to prevent redefinition

**Comment by vijdotsingh** [comment]
Appears to be a crash during InstructionSelection...

**Comment by 0dvictor** [comment]
Investigation shows it is an OMR issue. I've created an OMR Issue: https://github.com/eclipse/omr/issues/2702.
I guess all discussions related to this crash should be redirected to the OMR one, and hence we can close this Issue.

**Comment by 0dvictor** [comment]
Besides the proposal from @gacholio that JITHelpers should not be instrumentable, JIT should also prevent recognizing/transforming helpers meant for 64-bit when the target is 32-bit or vice versa.

**Comment by 0dvictor** [comment]
The JIT part to fix this Issue has been merged.

**Comment by pshipton** [comment]
@gacholio are there still some changes you want to make for this? If so can they be completed in the next couple of weeks?

**Comment by gacholio** [comment]
This has nothing to do with me.

**Comment by pshipton** [comment]
@gacholio see https://github.com/eclipse/openj9/issues/2175#issuecomment-397068794 and https://github.com/eclipse/openj9/issues/2175#issuecomment-397069745 where you suggested some changes. Are these still changes that should be made? If so I think we should create a new issue and close this one.

**Comment by gacholio** [comment]
It seems sensible to prevent instrumentation (and we can probably come up with more classes that it would be disastrous to instrument).

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/2768, closing this one.
