### ISSUE TITLE
SharedClasses compile error on mac osx

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#2222]
Compiling on mac osx shows the following SCC error due to overloaded constructors with different parameters.  (One is missing the J9JavaVM* parameter)

```
In file included from OSCache.cpp:40:
./OSCachevmem.hpp:63:15: error: 'SH_OSCachevmem::startup' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
        virtual bool startup(const char* ctrlDirName, UDATA cacheDirPerm, const char* cacheName, J9SharedClassPreinitConfig* piconfig, IDATA numLocks,
                     ^
./OSCache.hpp:204:15: note: hidden overloaded virtual function 'SH_OSCache::startup' declared here: different number of parameters (14 vs 13)
        virtual bool startup(J9JavaVM* vm, const char* cacheDirName, UDATA cacheDirPerm, const char* cacheName, J9SharedClassPreinitConfig* piconfig_, IDATA numLocks,
                     ^
```

For the mac build, I'm probably going to hack around it but we should look at what the right answer is.

**Comment by DanHeidinga** [comment]
@hangshao0 Can you take a look at this?

**Comment by hangshao0** [comment]
OSCachevmem.hpp/OSCachevmem.cpp is not being used now. They are only active under J9SHR_CACHELET_SUPPORT, which is not defined. 
We could either remove all the code inside J9SHR_CACHELET_SUPPORT, 
or simply put #include "OSCachevmem.hpp" inside ifdef J9SHR_CACHELET_SUPPORT here.

**Comment by pshipton** [comment]
Lets go with the second option for now. Considering the work that went into cachelet support, I'd hate to throw it away without good reason.

**Comment by DanHeidinga** [comment]
Take a look at the changes in https://github.com/danheidinga/openj9/tree/djh/mac_june

I've worked around the issue with `using xxxx.startup` statement in the hpp file and made other cachelet changes as well.
