### ISSUE TITLE
Empty cacert file on jdk8u172-b11 Windows distribution

### ISSUE THREAD

**Issue by jefrajames** [eclipse/openj9#2243]
I've downloaded and installed jdk8u172-b11 for Windows from AdoptOpenJDK. When running Maven, I've observed errors related to https connection preventing artifact downloads. After some investigations, I've realized taht this is due to the jre/lib/security/cacert file which is empty. 
I have copied a non-null cacert file from an other OpenJDK distribution and now everything works fine.
Is it a bug or is it "normal" to have an empty cacert file in the distibution? In the second case, the workaround shoud be clearly documented.

**Comment by DanHeidinga** [comment]
This sounds like a bug.  We'll need to work with the AdoptOpenJDK project to get this addressed.

FYI @smlambert @sxa555 Is this a known Adopt issue?

**Comment by smlambert** [comment]
yes, https://github.com/AdoptOpenJDK/openjdk8-releases/issues/11

**Comment by DanHeidinga** [comment]
Closing this as resolution will be handled through Adopt
