### ISSUE TITLE
Windows platform PR build failures due to NPT ERROR: Cannot open library

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2256]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-win_x86-64_cmprssptrs-OpenJ9/92/consoleFull

09:46:46 FAILED test targets:
09:46:46 	cmdLineTester_jvmtitests_extended_3
09:46:46 	cmdLineTester_jvmtitests_extended_7
09:46:46 	cmdLineTester_jvmtitests_extended_8
09:46:46 	cmdLineTester_jvmtitests_extended_9
09:46:46 	cmdLineTester_jvmtitests_extended_11
09:46:46 	decompileAtMethodResolve_0
09:46:46 
09:46:46 TOTAL: 162   EXECUTED: 85   PASSED: 79   FAILED: 6   SKIPPED: 77

09:47:33         ===============================================
09:47:33         Running test cmdLineTester_jvmtitests_extended_11 ...
09:47:33         ===============================================
09:47:33         cmdLineTester_jvmtitests_extended_11 Start Time: Fri Jun 22 08:15:20 2018 Epoch Time (ms): 1529673320318
09:47:33         test with Mode607-OSR
09:47:33         NPT ERROR: Cannot open library
09:47:33         
09:47:33         cmdLineTester_jvmtitests_extended_11_FAILED

**Comment by keithc-ca** [comment]
@JasonFengJ9 is this not a duplicate of #2129?

**Comment by JasonFengJ9** [comment]
It appears so. 
Duplicate of #2129.
