### ISSUE TITLE
Signal Chaining not working

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#2257]
Signal chaining is not working in OpenJ9. Signal chaining allows the application handler to be invoked after the JVM handler finishes executing.

[IBM Java 8 Documentation](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_signals.html): 
_If an application handler for this signal is installed and you did not specify the -Xnosigchain command-line option, the application handler for this signal is called after the JVM has finished processing._

**Sample testcase:** [test_signal_micro.zip](https://github.com/eclipse/openj9/files/2128709/test_signal_micro.zip)

`signal_micro_test.c` - Registers an application handler, `sigint_temporary_handler`, for `SIGINT` using `sigaction`. Then, starts the JVM and invokes `SignalMicroTest.main`.

`SignalMicroTest.main` - Registers a shutdown hook. Then, it waits to receive `SIGINT` or `Ctrl-C`.

After receiving `SIGINT`, the JVM must execute the shutdown handler which should execute the shutdown hooks. After executing the shutdown handler, the application handler, `sigint_temporary_handler` should be invoked.

**How to run the test case?**

```
unzip -q test_signal_micro.zip

cd test_signal_micro

source run.sh <PATH_TO_JAVA_HOME>

# After the application starts, send SIGINT.
Ctrl-C 
```

 **Expected Output [Correct]:**

```
Launched JVM! :)
SignalMicroTest ...
ibm.signalhandling.sigchain: true
Send SIGINT or Ctrl+C signal
^COK... exiting
Terminating main thread correctly
sigint_temporary_handler_check = 100
sigint_temporary_handler was invoked.
```

**Current Output [Incorrect]:**

```
Launched JVM! :)
SignalMicroTest ...
ibm.signalhandling.sigchain: true
Send SIGINT or Ctrl+C signal
^COK... exiting
Terminating main thread correctly
sigint_temporary_handler_check = -1
sigint_temporary_handler was not invoked.
```

In the current output, application handler, `sigint_temporary_handler`, is not invoked. Signal chaining code fails to execute the application handler. We need to investigate the signal chaining code to identify the source of this issue.

**Signal chaining code resides in OMR:** [omr/omrsigcompat/omrsig.cpp](https://github.com/eclipse/omr/blob/master/omrsigcompat/omrsig.cpp)

**Related OMR signal chaining functions:**
- [omrsig_primary_sigaction](https://github.com/eclipse/omr/blob/master/omrsigcompat/omrsig.cpp#L223)
- [omrsig_primary_signal](https://github.com/eclipse/omr/blob/master/omrsigcompat/omrsig.cpp#L198)
- [omrsig_handler](https://github.com/eclipse/omr/blob/master/omrsigcompat/omrsig.cpp#L112)

**Comment by babsingh** [comment]
fyi - @DanHeidinga @pshipton @charliegracie

**Comment by babsingh** [comment]
**Update**: The attached testcase only covers Unix platforms (AIX, zOS, Linux). We also need to verify signal chaining functionality on Windows. To cover Windows, the testcase needs to be modified. sigaction(...) is unavailable on Windows. signal(...) can be used to register an application handler on Windows.

On Windows, `omrsig_primary_signal` (register signal handlers with OS) and `omrsig_handler` (invoke the application handler) are used.
On Unix platforms, `omrsig_primary_sigaction` (register signal handlers with OS) and `omrsig_handler` (invoke the application handler) are used.

**Comment by babsingh** [comment]
**Update:** To enable signal chaining, the `libjsig.so` library needs to be linked while compiling the application. `libjsig.so` can be found here: `<JAVA_HOME>/jre/lib/amd64/compressedrefs/libjsig.so`

Updated test with fix: [test_signal_micro_fix.zip](https://github.com/eclipse/openj9/files/2146346/test_signal_micro_fix.zip)

Updated compile command that links `libjsig.so`:
```
signal_micro_test: signal_micro_test.c
        gcc -o signal_micro_test \
        -I ${JAVA_HOME}/include/ \
        -I ${JAVA_HOME}/include/linux/ \
        -ldl \
        signal_micro_test.c \
        ${JAVA_HOME}/jre/lib/amd64/compressedrefs/libjvm.so \
        ${JAVA_HOME}/jre/lib/amd64/compressedrefs/libjsig.so
```

**IBM Documentation:** [Linking a native code driver to the signal-chaining library](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_native_signals.html)

**Comment by hangshao0** [comment]
@babsingh , Can this issue be closed ?

**Comment by babsingh** [comment]
@hangshao0 with the above fix, OpenJ9 allows signal chaining. so, this can be closed.
