### ISSUE TITLE
Elasticsearch v6.1.3 fails to build with OpenJ9 nightly build due to missing jps

### ISSUE THREAD

**Issue by suman-mitra** [eclipse/openj9#2259]
Building  elasticsearch v6.1.3 fails with OpenJ9 nightly build (OpenJDK8-OPENJ9_x64_Linux_201806201400) due to missing jps. However, it builds fine with older OpenJ9 build. It also works fine with latest OpenJDK build. Details provided below 

1. Passing OpenJ9 build - OpenJDK8-OPENJ9_x64_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz
2. Failing OpenJ9 build - Nightly build,   OpenJDK8-OPENJ9_x64_Linux_201806201400.tar.gz

Below Failure seen ->
---------------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':distribution'.
> jps executable not found; ensure that you're running Gradle with the JDK rather than the JRE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

---------------------------------------------------------------------------------------------------------------
STEPS TO REPRODUCE :-
---------------------------------------------------------------------------------------------------------------
 1. Download the nightly build from adopt
 2. set JAVA_HOME and PATH
 3. git clone https://github.com/elastic/elasticsearch.git
 4. cd elasticsearch
 5. git checkout v6.1.3
 6. ./gradlew assemble  --> this will fail with the above mentioned error

**Comment by Mesbah-Alam** [comment]
OpenJ9 does not support jps. So, any test dependent on this utility should be excluded from running on OpenJ9 JDKs.

**Comment by suman-mitra** [comment]
But in earlier OpenJ9 JDK we had the jps available. Did we decide it recently about OpenJ9 JDK not supporting jps ?

**Comment by pshipton** [comment]
The binary may have been available but it has never worked. It was removed since it didn't work.

**Comment by suman-mitra** [comment]
Then how do we build and run elasticsearch v6.1.3 , since it fails to build with OpenJ9 without jps.

**Comment by pshipton** [comment]
I suppose a workaround is to copy a jps executable from an OpenJDK build. It won't work, but will run and do nothing, which apparently is sufficient.

**Comment by DanHeidinga** [comment]
> I suppose a workaround is to

Or write an empty script `jps`, `chmod +x jps`, and give it a go

**Comment by suman-mitra** [comment]
@pshipton @DanHeidinga both the solutions work. Now, we are able to build elasticsearch 6.1.3 . However, we see some tests are failing ..I'll raise a separate defect for the new failures seen

**Comment by smlambert** [comment]
This issue can be closed as we can build and run Elasticsearch tests without the dummy jps workaround, which has now been removed under https://github.com/AdoptOpenJDK/openjdk-tests/pull/996
