### ISSUE TITLE
hsperfdata directory remains empty with OpenJ9 Windows jdk8u172-b11

### ISSUE THREAD

**Issue by jefrajames** [eclipse/openj9#2260]
VisualVM 1.4.1 cannot monitor local applications when running applications with OpenJ9 Windows jdk8u172-b11. 
The %tmp%\hsperfdata_<userid> directory remains empty. No monitoring data are created here. 
When I switch to a HostSpot OpenJDK distribution it works.
Is it a normal behaviour of OpenJ9 or a bug?

**Comment by pshipton** [comment]
OpenJ9 doesn't support hsperfdata at this time.

**Comment by jefrajames** [comment]
Ok thank you. Good to know. So this is not a bug.
