### ISSUE TITLE
[TVT:sk]Corrupted national characters found when executing NLS files

### ISSUE THREAD

**Issue by panlei080988** [eclipse/openj9#2264]
Locale: SK
Pre - Step: 

Install IBM SDK 80 Java platform.

Steps:
1. Open a Command Prompt: Start  >  All Programs  >  Accessories  >  Command Prompt , then run the follow command.

-  cd C:\Cases\J8_TVT_TEST

-  java -jar nlstest.jar -type nls -oldResources old.zip -newResources new.zip -module CFRE -language ca -output cfre_ca.txt

( * Please change the ca to your language which you want to verify)

2. Verify the strings in the cfre_lang.txt file.

@pshipton 
Expect Results:
The output txt should displayed normally in sk and sl machines.
![image](https://user-images.githubusercontent.com/18432988/41893949-f50321c4-794f-11e8-9ae0-83540518c76c.png)

**Comment by pshipton** [comment]
It seems likely the current code page doesn't support the SK characters. What is the output of "java -XshowSettings:properties"?

**Comment by panlei080988** [comment]
Property settings:
    awt.toolkit = sun.awt.windows.WToolkit
    com.ibm.cpu.endian = little
    com.ibm.jcl.checkClassPath =
    com.ibm.oti.configuration = scar
    com.ibm.oti.shared.enabled = false
    com.ibm.oti.vm.bootstrap.library.path = C:\Users\Administrator\Downloads\Jav
a80\sdk\jre\bin\compressedrefs
        C:\Users\Administrator\Downloads\Java80\sdk\jre\bin
    com.ibm.oti.vm.library.version = 29
    com.ibm.system.agent.path = C:\Users\Administrator\Downloads\Java80\sdk\jre\
bin
    com.ibm.util.extralibs.properties =
    com.ibm.vm.bitmode = 64
    com.ibm.zero.version = 2
    console.encoding = Cp437
    file.encoding = Cp1252
    file.encoding.pkg = sun.io
    file.separator = \
    ibm.signalhandling.rs = false
    ibm.signalhandling.sigchain = true
    ibm.signalhandling.sigint = true
    ibm.system.encoding = Cp1252
    java.awt.fonts =
    java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
    java.awt.printerjob = sun.awt.windows.WPrinterJob
    java.class.path = C:\STAF\samples\demo\STAFDemo.jar
        C:\STAF\bin\JSTAF.jar
    java.class.version = 52.0
    java.compiler = j9jit29
    java.endorsed.dirs = C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\end
orsed
    java.ext.dirs = C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ext
    java.fullversion = 8.0.6.0 - pwa6480sr6-20180606_02(SR6)
JRE 1.8.0 Windows 7 amd64-64-Bit Compressed References 20180605_388565 (JIT enab
led, AOT enabled)
OpenJ9   - a3a36a9
OMR      - 1700e8d
IBM      - 474a5f8
    java.home = C:\Users\Administrator\Downloads\Java80\sdk\jre
    java.io.tmpdir = C:\Users\ADMINI~1\AppData\Local\Temp\
    java.library.path = C:\Users\Administrator\Downloads\Java80\sdk\jre\bin\comp
ressedrefs
        C:\Users\Administrator\Downloads\Java80\sdk\jre\bin
        C:\Windows\system32
        C:\Windows
        C:\Users\Administrator\Downloads\Java80\sdk\bin
        C:\STAF\bin
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Program Files (x86)\Puppet Labs\Puppet\bin

        .
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 8.0.6.0 - pwa6480sr6-20180606_02(SR6)
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = IBM Corporation
    java.vendor.url = http://www.ibm.com
    java.version = 1.8.0_171
    java.vm.info = JRE 1.8.0 Windows 7 amd64-64-Bit Compressed References 201806
05_388565 (JIT enabled, AOT enabled)
OpenJ9   - a3a36a9
OMR      - 1700e8d
IBM      - 474a5f8
    java.vm.name = IBM J9 VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = IBM Corporation
    java.vm.version = 2.9
    line.separator = \r \n
    os.arch = amd64
    os.encoding = UTF8
    os.name = Windows 7
    os.version = 6.1
    path.separator = ;
    sun.arch.data.model = 64
    sun.boot.class.path = C:\Users\Administrator\Downloads\Java80\sdk\jre\bin\co
mpressedrefs\jclSC180\vm.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\se-service.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\cuda4j.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\math.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmorb.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmorbapi.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmcfw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmpkcs.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmcertpathfw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmjgssfw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmjssefw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmsaslfw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmjcefw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmjgssprovider.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmjsseprovider2.jar

        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\ibmcertpathprovider.
jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\xmldsigfw.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\xml.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\charsets.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\resources.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\rt.jar
        C:\Users\Administrator\Downloads\Java80\sdk\jre\lib\dataaccess.jar
    sun.boot.library.path = C:\Users\Administrator\Downloads\Java80\sdk\jre\bin\
compressedrefs
        C:\Users\Administrator\Downloads\Java80\sdk\jre\bin
    sun.cpu.endian = little
    sun.desktop = windows
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = Cp1252
    user.country = US
    user.dir = C:\Users\Administrator\Desktop\JVMTest
    user.home = C:\Users\Administrator
    user.language = es
    user.name = Administrator
    user.timezone =
    user.variant =

Uso: java [-opciones] class [args...]
           (para ejecutar una clase)
   o  java [-opciones] -jar archivojar [args...]
           (para ejecutar un archivo jar)
donde las opciones incluyen:
    -cp <vía de acceso de búsqueda de clases de directorios y archivos zip/jar>
    -classpath <vía de acceso de búsqueda de clases de directorios y archivos zi
p/jar>
                  Una lista separada por ; de directorios, archivos JAR
                  y archivos ZIP en los que buscar los archivos de clase.
    -D<name>=<valor>
                  definir una propiedad del sistema
    -verbose:[class|gc|jni]
                  habilitar la salida detallada
    -version      imprimir la salida detallada y salir
    -version:<value>
                  Aviso: esta función ha quedado obsoleta y se eliminará
                  en una versión futura.
                  solicitar la versión especificada para la ejecución
    -showversion  imprimir la versión del producto y continuar
    -jre-restrict-search | -no-jre-restrict-search
                  Aviso: esta función ha quedado obsoleta y se eliminará
                  en una versión futura.
                  incluir/excluir JRE privados de usuario en la búsqueda de vers
ión
    -? -help      imprimir este mensaje de ayuda
    -X            imprimir ayuda sobre opciones no estándar
    -ea[:<nombrepaquete>...|:<nombreclase>]
    -enableassertions[:<nombrepaquete>...|:<nombreclase>]
                  permitir aserciones con la granularidad especificada
    -da[:<nombrepaquete>...|:<nombreclase>]
    -disableassertions[:<nombrepaquete>...|:<nombreclase>]
                  inhabilitar aserciones con la granularidad especificada
    -esa | -enablesystemassertions
                  habilitar aserciones del sistema
    -dsa | -disablesystemassertions
                  inhabilitar aserciones del sistema
    -agentlib:<nombrebiblioteca>[=<opciones>]
                  cargar biblioteca de agente nativo <nombrebiblioteca>, p.e. -a
gentlib:hprof
                  ver también, -agentlib:jdwp=help y -agentlib:hprof=help
    -agentpath:<nombrevíaacceso>[=<opciones>]
                  cargar biblioteca de agente nativo por nombre completo de vía
de acceso
    -javaagent:<víaaccesojar>[=<opciones>]
                  cargar agente del lenguaje de programación Java, consultar jav
a.lang.instrument
    -splash:<víaaccesoimagen>
                  mostrar pantalla inicial con la imagen especificada

**Comment by panlei080988** [comment]
@pshipton any update about this issue?

**Comment by pshipton** [comment]
> console.encoding = Cp437
> file.encoding = Cp1252

You need to setup your machine to enable an encoding that supports the SK characters.
