### ISSUE TITLE
Remove APIs Thread.destroy(), stop(Throwable) from Java 11

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2267]
The deprecated APIs Thread.destroy() and Thread.stop(Throwable) are removed from Java 11.

Java 11 spec: http://cr.openjdk.java.net/~iris/se/11/latestSpec/
Javadoc: http://cr.openjdk.java.net/~iris/se/11/build/latest/api/

**Comment by pshipton** [comment]
@tajila is somebody available to work on this?

**Comment by tajila** [comment]
yes @Ailloviee can work on this
