### ISSUE TITLE
Largepages for object heap are not working

### ISSUE THREAD

**Issue by akrus** [eclipse/openj9#2289]
Hi,

I'm trying to configure large pages for object heap, but for some reason it always fails with message:
JVMJ9GC088I Requested objectheap page size 2M could not be satisfied; using 4K instead

sysctl:
vm.nr_hugepages=200000 (so ~400GB memory)

Java flags:
```
-server -Xmx25g -verbose:gc -verbose:sizes -Xshareclasses:name=myapp -Xgcpolicy:metronome -Xgc:targetPauseTime=1 -Xlp:codecache:pagesize=2M -Xlp:objectheap:pagesize=2M,warn
```

Startup messages:
```
-Xlp:objectheap:pagesize=2M         large page size
available large page sizes:
4K
2M
-Xlp:codecache:pagesize=2M         large page size for JIT code cache
available large page sizes for JIT code cache:
4K
2M
```

JIT code cache looks to be OK, only object heap doesn't work.

Tried rebooting the whole server as advised in J9 docs, but this didn't help.

OpenJ9 version:
```
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
Eclipse OpenJ9 VM (build master-6023611d, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180507_161 (JIT enabled, AOT enabled)
OpenJ9   - 6023611d
OMR      - 884959f4
JCL      - 7f27c537 based on jdk8u172-b11)
```

built with:
--with-freemarker-jar=/home/freemarker.jar --with-noncompressedrefs --disable-headful

**Comment by dmitripivkine** [comment]
Configuring Huge Pages in the Linux kernel is not enough. Huge Pages should be added to Shared Memory to be used by JVM. 
Did you set up shared memory for huge pages?

**Comment by akrus** [comment]
@dmitripivkine, well, no. Is it the one specified in kernel.shmmax sysctl?

**Comment by dmitripivkine** [comment]
SHMMAX and SHMALL

**Comment by dmitripivkine** [comment]
You can refer to article https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_configure_large_page.html

**Comment by akrus** [comment]
@dmitripivkine, thanks, now it's fine.
