### ISSUE TITLE
Elasticsearch v6.1.3 DisableGraphQueryTests fail with OpenJ9 (80) build

### ISSUE THREAD

**Issue by suman-mitra** [eclipse/openj9#2302]
Build :- latest openJ9 (80) build

Issues seen :- 

1.  While running the test, it fails with java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc") ;

```  > Throwable #1: junit.framework.AssertionFailedError: Clean up static fields (in @AfterClass?) and null them, your test still has references to classes of which the sizes cannot be measured due to security restrictions or Java 9 module encapsulation:
   >   - private static org.apache.lucene.search.Query org.elasticsearch.index.query.DisableGraphQueryTests.expectedQueryWithUnigram
   >    at __randomizedtesting.SeedInfo.seed([8B532B2CEC2545C8]:0)
   >    at java.lang.Thread.run(Thread.java:812)
   > Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
   >    at java.security.AccessController.throwACE(AccessController.java:176)
   >    at java.security.AccessController.checkPermissionHelper(AccessController.java:237)
   >    at java.security.AccessController.checkPermission(AccessController.java:373)
   >    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
   >    at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
   >    at java.lang.Class.checkMemberAccess(Class.java:245)
   >    at java.lang.Class.getDeclaredFields(Class.java:857)
   >    at java.security.AccessController.doPrivileged(AccessController.java:640)```

2. Adding   "java.lang.RuntimePermission" "accessClassInPackage.sun.misc"  in java.security file, helps to progress with the test execution. 
  
However, the tests again failed with similar exceptions such as :-

  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.net.www.protocol.jar")

  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.net.www.protocol.file")

  java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.provider.certpath")

3. Adding the above three in java.security file, helps to progress further with the test execution. And finally the test fails with below error :

  > Task :client:rest:test
==> Test Info: seed=E5265CF3655EB208; jvm=1; suites=12

```Suite: org.elasticsearch.client.RestClientSingleHostIntegTests
  2> Jun 26, 2018 3:03:58 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> WARNING: Will linger awaiting termination of 1 leaked thread(s).
  2> Jun 26, 2018 3:04:03 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> SEVERE: 1 thread leaked from SUITE scope at org.elasticsearch.client.RestClientSingleHostIntegTests:
  2>    1) Thread[id=26, name=ClassCache Reaper, state=WAITING, group=TGRP-RestClientSingleHostIntegTests]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:218)
  2>         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
  2>         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
  2>         at java.io.ClassCache$Reaper.run(ClassCache.java:232)
  2> Jun 26, 2018 3:04:03 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFO: Starting to interrupt leaked threads:
  2>    1) Thread[id=26, name=ClassCache Reaper, state=WAITING, group=TGRP-RestClientSingleHostIntegTests]
  2> Jun 26, 2018 3:04:06 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> SEVERE: There are still zombie threads that couldn't be terminated:
  2>    1) Thread[id=26, name=ClassCache Reaper, state=WAITING, group=TGRP-RestClientSingleHostIntegTests]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:218)
  2>         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
  2>         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
  2>         at java.io.ClassCache$Reaper.run(ClassCache.java:232)
ERROR   0.00s | RestClientSingleHostIntegTests (suite) <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.client.RestClientSingleHostIntegTests:
   >    1) Thread[id=26, name=ClassCache Reaper, state=WAITING, group=TGRP-RestClientSingleHostIntegTests]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:218)
   >         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
   >         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
   >         at java.io.ClassCache$Reaper.run(ClassCache.java:232)
   >    at __randomizedtesting.SeedInfo.seed([E5265CF3655EB208]:0)Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   >    1) Thread[id=26, name=ClassCache Reaper, state=WAITING, group=TGRP-RestClientSingleHostIntegTests]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:218)
   >         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
   >         at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
   >         at java.io.ClassCache$Reaper.run(ClassCache.java:232)
   >    at __randomizedtesting.SeedInfo.seed([E5265CF3655EB208]:0)```
Completed [1/12] in 8.90s, 5 tests, 2 errors <<< FAILURES!

**Comment by suman-mitra** [comment]
STEPS TO REPRODUCE 

1. export JAVA_HOME & PATH
2. PATH for gradle gradle-4.5 such as 
    export PATH=/home/testuser/Elastic/gradle-4.5/bin:$PATH

3.  git clone https://github.com/elastic/elasticsearch.git
4.  cd elasticsearch
5.  git checkout v6.1.3
6.  gradle assemble
7.  ./gradlew test

**Comment by pshipton** [comment]
I assume the same tests pass with OpenJDK?

**Comment by smlambert** [comment]
Same testsuite [passes on openjdk8](https://ci.adoptopenjdk.net/view/External%20tests/job/openjdk8_hs_externaltest_x86-64_linux/125/tapResults/)

**Comment by suman-mitra** [comment]
Yes, the test pass with OpenJDK8

**Comment by DanHeidinga** [comment]
@suman-mitra Are these tests part of the 3rd party tests at Adopt?  I'm wondering if we want a tag to identify these kinds of issues.

**Comment by smlambert** [comment]
They are part of the 3rd party app tests, https://ci.adoptopenjdk.net/view/External%20tests/ and we will (loosely) track upstream defects via this openjdk-tests issue, https://github.com/AdoptOpenJDK/openjdk-tests/issues/464.

**Comment by DanHeidinga** [comment]
Thanks @smlambert.  Created a new label svtRaised for these kinds of defects

**Comment by JasonFengJ9** [comment]
Attempted to reproduce the failure with latest `Eclipse OpenJ9 1.8.0_172 [Eclipse OpenJ9 VM master-3cbbe5f5]`, but got following error:
```
* What went wrong:
A problem occurred configuring project ':distribution'.
> jps executable not found; ensure that you're running Gradle with the JDK rather than the JRE
```
`OpenJ9` doesn't have `jps`.
@suman-mitra, any insights?

**Comment by pshipton** [comment]
@JasonFengJ9 see #2259

**Comment by JasonFengJ9** [comment]
Reproduced the issue reported. Will investigate.

**Comment by JasonFengJ9** [comment]
@suman-mitra sorry for getting back to this late (somehow fall off my radar).
Just tried again, it finished successfully. The JVM tested against was:
```
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-201811260519-b12)
Eclipse OpenJ9 VM (build master-617897dfa, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181126_122 (JIT enabled, AOT enabled)
OpenJ9   - 617897dfa
OMR      - 8001cf22
JCL      - ac4eeb4998 based on jdk8u192-b12)
```

Could you verify?

**Comment by suman-mitra** [comment]
I'll verify and update soon

**Comment by suman-mitra** [comment]
I'm unable to find the build mentioned by you. However, I tried with the below version

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-201811160518-b12)
Eclipse OpenJ9 VM (build master-4d8ad6b23, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181116_110 (JIT enabled, AOT enabled)
OpenJ9   - 4d8ad6b23
OMR      - ee38121f
JCL      - a98b32fb3b based on jdk8u192-b12)

And with this build I still see the same issue happening -

ERROR   0.00s J3 | DisableGraphQueryTests (suite) <<< FAILURES!
   > Throwable #1: junit.framework.AssertionFailedError: Clean up static fields (in @AfterClass?) and null them, your test still has references to classes of which the sizes cannot be measured due to security restrictions or Java 9 module encapsulation:
   >   - private static org.apache.lucene.search.Query org.elasticsearch.index.query.DisableGraphQueryTests.expectedQueryWithUnigram
   >    at __randomizedtesting.SeedInfo.seed([A85597ECD1FE79AB]:0)
   >    at java.lang.Thread.run(Thread.java:813)
   > Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
   >    at java.security.AccessController.throwACE(AccessController.java:176)
   >    at java.security.AccessController.checkPermissionHelper(AccessController.java:237)
   >    at java.security.AccessController.checkPermission(AccessController.java:373)
   >    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
   >    at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
   >    at java.lang.Class.checkMemberAccess(Class.java:245)
   >    at java.lang.Class.getDeclaredFields(Class.java:857)
   >    at java.security.AccessController.doPrivileged(AccessController.java:647)
   >    ... 10 more
Completed [174/1017] on J3 in 0.96s, 5 tests, 1 failure <<< FAILURES!

**Comment by JasonFengJ9** [comment]
Yeah, the test didn't pass with `OpenJ9`. (I misread the test result)

**Summary of investigation:**
1. Those `AccessControlException` are legitimate, i.e., the code within the call stack doesn't have the permission required and `OpenJ9` correctly rejected the resource access requests;
2. Adding required permissions to [test-framework.policy.txt](https://github.com/eclipse/openj9/files/2784867/test-framework.policy.txt) (decorated with _// needed for OpenJ9_, added `.txt` suffix to satisfy git attachment requirement) can make the `org.elasticsearch.index.query.DisableGraphQueryTests` in question pass. (There are other failures to run the whole test suite, so does `RI`);
3. Some of permissions required are due to the application specific `JVM` check for `Hotspots` such as https://github.com/randomizedtesting/randomizedtesting/blob/master/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/rules/RamUsageEstimator.java#L220-L254.

Ideally the `JVM` checking could include `OpenJ9`, othewise, permissions required have to be added to the test policy accordingly.

**Comment by suman-mitra** [comment]
@JasonFengJ9  Thanks !!
Do you  think we should raise a bug/issue there ?

**Comment by JasonFengJ9** [comment]
@suman-mitra it would be nice to let dev/user know that the `Elasticsearch` can run with `OpenJ9` with workaround mentioned https://github.com/eclipse/openj9/issues/2302#issuecomment-456593803, and adding check for `OpenJ9 JVM` are recommended.

**Comment by DanHeidinga** [comment]
> Do you think we should raise a bug/issue there ?

@suman-mitra Yes, that would be a big help.

Closing this here as no further openj9 work is required.
