### ISSUE TITLE
ConstantDynamic: JIT support for load constant dynamic

### ISSUE THREAD

**Issue by yanluo7** [eclipse/openj9#2307]
Implement JIT side support for loading Constant Dynamic constant pool entry. 
At compile time, check if the entry has already been resolved:
if so generate as if loading regular constant.
Otherwise generate the correct resolve check, which performs the one-time resolution by invoking the JIT helper that does the actual bootstrap method call and materializing the constant.

**Comment by yanluo7** [comment]
Depends on #1277

**Comment by yanluo7** [comment]
@DanHeidinga Could you add this to the ConstantDynamic project?

**Comment by yanluo7** [comment]
As I was discussing implementation details with @fengxue-IS, one issue that came up was that the JIT would need to know the type of the underlying data type of the ConstantDynamic CP entry. 
Currently, macro `J9_CP_TYPE(J9ROMCLASS_CPSHAPEDESCRIPTION(romClass), cpIndex)` would only return the newly created "Dynamic Constant" CP type. The JIT would need to know the actual type info of this constant in order to generate the right instruction.

If the VM has existing logic that can dig this information up it would be good to expose the API/macro to JIT; or we would need to write some parsing logic and expose that API/macro to the JIT.

**Comment by yanluo7** [comment]
For Constant Dynamic (condy for short), a new CP entry is defined as:
```
typedef struct J9RAMConstantDynamicRef {
        j9object_t value;
        j9object_t exception;
} J9RAMConstantDynamicRef;`
```
The value field stores the result of the resolution helper as such:
- For primitive condy type, a corresponding autobox'd object (e.g. `j/l/Integer` for `int` type) will be stored in value field.
- For object condy type, the actual object will be stored in value field.

If the condy is already resolved: 
- for primitive types: 
`TR::*contant <constant value>` is generated: e.g. `TR::iconst <41>`.
- for object type: 
`TR::aload <resolved static symbol>` 
We generated a direct address load, where the static address of the symbol is set to address of `J9RAMConstantDynamicRef.value` field.

So in the resolved case, existing codegen should be able to handle both primitive and object types -- no codegen change required.

If the condy is un-resolved: 
- for object type: 
`TR::aload <unresolved static symbol>` 
We generate aload with an unresolved static symbol, just like we do for unresolved constant Strings. The codegen creates a memory reference and an unresolved snippet that calls JIT helper `jitResolveConstantDynamic`, which resolves the object and put the j9object_t value in `J9RAMConstantDynamicRef.value`. Codegen patches the mainline code so we only execute the snippet and JIT helper once.
- for primitive type:
```
TR::iloadi java/lang/Integer.value [shadow]
    TR::aload <unresolved static symbol>
```
We generate a `aload` to load the autobox object and then an indirect load e.g. `iloadi` that loads the primitive value from the autobox object. The codegen creates a memory reference or an unresolved snippet that calls JIT helper `jitResolveConstantDynamic` and similarly patches the mainline code for the `aload` intruction.

Alternatively we could generate a `TR::iload <unresolved static symbol>` and have the snippet sequence load the primitive value after resolution helper, store the value somewhere and load it directly, so we can save an indirect load. On X86, because of the instruction encoding, the location within the instruction to patch would get quite complicated depending on the primitive type - we would have to write about 6 different PIC code for patching different types of primitive load instructions, which would be quite time consuming. And because this only concerns unresolved and primitive condy types, which we believe does not occur often and incur minimal performance impact, after discussing with Andrew Craik, we settled on having one patching sequence and an indirect load for unresolved primitive condy types.

**Comment by yanluo7** [comment]
OMR commit: https://github.com/yanluo7/omr/commit/222044b3f545ef8d52b6ae0f63edcb527535fefe
openj9 commit: https://github.com/yanluo7/openj9/commit/b68469ffff3aa1fe8738c662467af1e46281b318

Commit depend on VM helper APIs currently not yet merged.

**Comment by andrewcraik** [comment]
@yanluo7 two points:
- the unresolved aload will need to be under a ResolveCHK treetop to ensure the side-effects of resolution and potential exception are captured
- we need to consider what aliasing these constand dynamic symbols need - the unresolved ones will need to be conservative because the method handle run to resolve the constant dynamic could have arbitrary side-effects including modifying other fields read by the current method (at least that is my understanding at this time)

**Comment by yanluo7** [comment]
@andrewcraik 

- Looks like the ResolveCHK is already generated -- in `laodSymbol`, if the symbol is unresolved `genResolveCheck` is called to generate the ResolveCHK node.

- Made additional changes in `Aliases.cpp getUseDefAliasesBV` and `sharesSymbol` so that if the symbol is unresolved and condy type, we returned the conservative `defaultMethodDefAliases`.
