### ISSUE TITLE
PATH variable is missing the path to java 

### ISSUE THREAD

**Issue by stmaute** [eclipse/openj9#2311]
I recently pulled the new adoptopenjdk/openjdk8-openj9:jdk8u162-b12_openj9-0.8.0-alpine and wanted to start my java application at start-up but nothing happened.
It seems that the path to /opt/java/openjdk/jdk8u162-b12_openj9-0.8.0/bin is missing in the PATH env variable.

Can you please verify and then fix it?
Thx.

**Comment by dinogun** [comment]
This issue has been raised at adoptopenjdk repo (https://github.com/AdoptOpenJDK/openjdk-docker/issues/32) and will be fixed by https://github.com/AdoptOpenJDK/openjdk-docker/issues/33

**Comment by DanHeidinga** [comment]
Closing this issue as the fix will be handled at Adopt.
