### ISSUE TITLE
Compiling java.base failed on aix

### ISSUE THREAD

**Issue by bjxiangy** [eclipse/openj9#2331]
Compiling on aix. Use the source code version as https://ci.eclipse.org/openj9/job/Build-JDK10-aix_ppc-64_cmprssptrs/206/consoleFull
After issuing "make all", it reports following compiing errors.

gmake[1]: *** [stage-openj9-tools] Error 1
Error: Could not find or load main class com.ibm.jpp.commandline.CommandlineBuilder
Caused by: java.lang.ClassNotFoundException: com.ibm.jpp.commandline.CommandlineBuilder
gmake[1]: *** [/home/bjxiangy/openj9/openj9-openjdk-jdk10/build/aix-ppc64-normal-server-release/make-support/j9jcl_sources.done] Error 1
Building target 'all' in configuration 'aix-ppc64-normal-server-release'
Compiling 2873 files for java.base
/home/bjxiangy/openj9/openj9-openjdk-jdk10/src/java.base/share/classes/java/net/URLClassLoader.java:74: error: package com.ibm.sharedclasses.spi does not exist
import com.ibm.sharedclasses.spi.SharedClassProvider;
                                ^
/home/bjxiangy/openj9/openj9-openjdk-jdk10/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java:82: error: package com.ibm.sharedclasses.spi does not exist
import com.ibm.sharedclasses.spi.SharedClassProvider;
                                ^
/home/bjxiangy/openj9/openj9-openjdk-jdk10/src/java.base/share/classes/java/net/URLClassLoader.java:105: error: cannot find symbol
    private SharedClassProvider sharedClassServiceProvider;
            ^
  symbol:   class SharedClassProvider
  location: class URLClassLoader
/home/bjxiangy/openj9/openj9-openjdk-jdk10/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java:129: error: cannot find symbol
    private SharedClassProvider sharedClassServiceProvider = null;              //IBM-shared_classes_misc
            ^
  symbol:   class SharedClassProvider
  location: class URLClassPath
/home/bjxiangy/openj9/openj9-openjdk-jdk10/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java:183: error: cannot find symbol
                        AccessControlContext acc, SharedClassProvider helper) {                 //IBM-shared_classes_misc
......

**Comment by DanHeidinga** [comment]
```
gmake[1]: *** [stage-openj9-tools] Error 1
Error: Could not find or load main class com.ibm.jpp.commandline.CommandlineBuilder
Caused by: java.lang.ClassNotFoundException: com.ibm.jpp.commandline.CommandlineBuilder
```
is the critical error.  Can you look at the build log for more details on why it can't find the java source preprocessor?

**Comment by bjxiangy** [comment]
Thanks for reminder!  I have found two files in in my sandbox.  
_./build/aix-ppc64-normal-server-release/vm/sourcetools/com.ibm.jpp.preprocessor/com/ibm/jpp/commandline/CommandlineBuilder.java
./openj9/sourcetools/com.ibm.jpp.preprocessor/com/ibm/jpp/commandline/CommandlineBuilder.java_

Before the error occurs, there are some tar warnings. I am not sure whether it is caused by following warning. Should com/ibm/jpp/commandline/CommandlineBuilder.java be extracted from a tar file?
**/home/bjxiangy/bin/tar: ./com.ibm.jpp.preprocessor/com/ibm/jpp/commandline/CommandlineBuilder.java: file changed as we read it**
/home/bjxiangy/bin/tar: ./com.ibm.jpp.preprocessor/com/ibm/jpp/commandline/CommandlineLogger.java: file changed as we read it
/home/bjxiangy/bin/tar: ./com.ibm.jpp.preprocessor/com/ibm/jpp/commandline/CommandlineNowarnLogger.java: file changed as we read it

**Comment by DanHeidinga** [comment]
Where is `tar` used in the build?  I don't see that in my logs...  Might just be missing it.

**Comment by bjxiangy** [comment]
This issue is fixed by recompiling the tar file. The default tar on aix does not support gzip. I recompile the tar the install it in another path. After configuring the correct tar file, the compilation pass. Thanks!
