### ISSUE TITLE
Incomplete PR builds

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#2356]
For example, see [1], where a test starts then about 30 seconds later it appears Jenkins gets impatient:
```
08:39:53 wrapper script does not seem to be touching the log file in /home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/test/TestConfig@tmp/durable-9ae9c333
08:39:53 (JENKINS-48300: if on a laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300)
```
Perhaps we need to heed its advice?

[1] https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/105/

**Comment by DanHeidinga** [comment]
@AdamBrousseau thoughts?

**Comment by AdamBrousseau** [comment]
We've seen this problem before on other Jenkins instances. I believe adding the Java option to the startup resolves the issue. Do we want to wait and see if this occurs again or would you rather we open the Eclipse ticket right away @DanHeidinga?

**Comment by pshipton** [comment]
+1 to opening the ticket rather than waiting.

**Comment by AdamBrousseau** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536881

**Comment by AdamBrousseau** [comment]
Ticket is resolved. Please close this and reopen if you see it again

**Comment by keithc-ca** [comment]
Thanks, Adam,
