### ISSUE TITLE
Sjavac server failed to initialize Build-JDK9-linux_390-64_cmprssptrs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2364]
https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/290/console

```
00:40:08 Copying j9ddr.dat
00:40:08 make[4]: Entering directory '/home/jenkins/jenkins-agent/workspace/Build-JDK9-linux_390-64_cmprssptrs'
00:40:08 make[4]: Leaving directory '/home/jenkins/jenkins-agent/workspace/Build-JDK9-linux_390-64_cmprssptrs'
00:40:08 
00:40:08 ERROR: Build failed for target 'all' in configuration 'linux-s390x-normal-server-release' (exit code 2) 
00:40:08 
00:40:08 === Output from failing command(s) repeated here ===
00:40:08 * For target buildtools_idlj_classes__the.BUILD_IDLJ_batch:
00:40:08 Sjavac server failed to initialize: No port file values materialized. Giving up after 60438 ms
00:40:08 Process output:
00:40:08 <End of process output>
00:40:08 Process exit code: 1
00:40:08 IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60438 ms
00:40:08 * For target buildtools_jdk_tools_classes__the.BUILD_TOOLS_JDK_batch:
00:40:08 Sjavac server failed to initialize: No port file values materialized. Giving up after 60250 ms
00:40:08 Process output:
00:40:08 <End of process output>
00:40:08 Process exit code: 1
00:40:08 IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60250 ms
00:40:08 * For target buildtools_override_modules_jdk.rmic__the.BUILD_INTERIM_RMIC_batch:
00:40:08 Sjavac server failed to initialize: No port file values materialized. Giving up after 60321 ms
00:40:08 Process output:
00:40:08 <End of process output>
00:40:08 IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60321 ms
00:40:08 * For target support_jrtfs_classes__the.BUILD_JRTFS_batch:
00:40:08 Sjavac server failed to initialize: No port file values materialized. Giving up after 60472 ms
00:40:08 Process output:
00:40:08 <End of process output>
00:40:08 IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60472 ms
00:40:08 
00:40:08 * All command lines available in /home/jenkins/jenkins-agent/workspace/Build-JDK9-linux_390-64_cmprssptrs/build/linux-s390x-normal-server-release/make-support/failure-logs.
00:40:08 === End of repeated output ===
```

**Comment by pshipton** [comment]
Occurred again https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/291/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/294/console

**Comment by pdbain-ibm** [comment]
https://ci.eclipse.org/openj9/blue/organizations/jenkins/PullRequest-Sanity-JDK9-linux_390-64_cmprssptrs-OpenJ9/detail/PullRequest-Sanity-JDK9-linux_390-64_cmprssptrs-OpenJ9/162/pipeline

**Comment by pdbain-ibm** [comment]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK9-linux_390-64_cmprssptrs-OpenJ9/164/console

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/304/console

**Comment by DanHeidinga** [comment]
Can we disable it in the `configure` script to get the build running?

**Comment by keithc-ca** [comment]
Could this be just another consequence of slow startup on zLinux?
Perhaps if the boot JDK is updated to one that includes https://github.com/eclipse/omr/pull/2796 this problem will go away?
See also https://github.com/AdoptOpenJDK/openjdk-build/issues/429 and https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/416.

**Comment by babsingh** [comment]
Possible workaround: run configure with --disable-sjavac - bash ./configure --with-freemarker-jar=/root/freemarker.jar --disable-sjavac. Configure output should have **checking whether to use sjavac... no**.

**Comment by keithc-ca** [comment]
That is the default: the most recent build [1] confirms this.
```
checking whether to use sjavac... no
checking whether to use javac server... yes
```
I see the same configuration messages in my local builds which **don't** suffer from this, but I **do** use a boot JDK which includes the OMR fix.

[1] https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/315/

**Comment by babsingh** [comment]
with `--disable-sjavac`, `sjavac` server shouldn't be initialized.

if `sjavac` server is being initialized after the `configure` stage has disabled it, then there may be an issue in setup.

may be ... we also need to disable **javac server** to completely disable `sjavac`: `--disable-javac-server  disable javac server`.

**Comment by HusainYusufali** [comment]
The following machines have been updated with the newest adoptopenjdk 0.9.0

**Comment by HusainYusufali** [comment]
The following machines have been updated with the newest adoptopenjdk 0.9.0.

LXEOJ901
LXEOJ902
LXEOJ903
LXEOJ904

This is the java version information for `LXEOJ901`

`` linux1@LXEOJ901:/usr/lib/jvm$ adoptojdk-java-10/bin/java -version ``
`` openjdk version "10.0.2-adoptopenjdk" 2018-07-17 ``
`` OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)  ``
`` Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 10 Linux s390x-64-Bit Compressed References 20180813_120 (JIT enabled, AOT enabled) ``
`` OpenJ9 - 24e53631 `` 
`` OMR - fad6bf6e JCL - 7db90eda56 based on jdk-10.0.2+13) ``

`` linux1@LXEOJ901:/usr/lib/jvm$ adoptojdk-java-90/bin/java -version `` 
`` openjdk version "9.0.4-adoptopenjdk" `` 
`` OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+12) `` 
`` Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 9 Linux s390x-64-Bit Compressed References 20180814_261 (JIT enabled, AOT enabled) `` 
`` OpenJ9 - 24e53631 `` 
`` OMR - fad6bf6e JCL - feec4d2ae based on jdk-9.0.4+12) ``

`` linux1@LXEOJ901:/usr/lib/jvm$ adoptojdk-java-80/bin/java -version `` 
`` openjdk version "1.8.0_181" `` 
`` OpenJDK Runtime Environment (build 1.8.0_181-b13) `` 
`` Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20180813_261 (JIT enabled, AOT enabled) ``
`` OpenJ9 - 24e53631 ``
`` OMR - fad6bf6e JCL - a05586ac based on jdk8u181-b13) ``

The output is the same for the remaining machines.

**Comment by pshipton** [comment]
Another one
https://ci.eclipse.org/openj9/job/Build_JDKnext_s390x_linux_Nightly/213
```
01:41:07  IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60208 ms
01:41:07  CompileJavaModules.gmk:600: recipe for target '/home/jenkins/jenkins-agent/workspace/Build_JDKnext_s390x_linux_Nightly/build/linux-s390x-server-release/jdk/modules/java.desktop/_the.java.desktop_batch' failed
```

**Comment by keithc-ca** [comment]
Maybe updating the boot JDKs to versions that include [1] (or equivalent) will help?

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/232

**Comment by pshipton** [comment]
Not sure we should update the boot JDK to a nightly build, better to wait until the next release, unless this problem starts to occur often.

**Comment by keithc-ca** [comment]
I wasn't thinking of using nightlies: as you say, unless this occurs frequently, waiting for the next release should be fine. Perhaps we should re-open this as a reminder to update those boot JDKs?

**Comment by pshipton** [comment]
It doesn't seem appropriate to re-open this for updating boot JDKs. I've created https://github.com/eclipse/openj9/issues/7874 and assigned it to the next milestone.
