### ISSUE TITLE
Jenkins: Checkout 'Target branch" when dependent PR has already been merged

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#2366]
related #122 #827 
tag: enhancement, good first issue

We support PR builds with dependent changes in other open PRs. The issue is when a PR has already been merged, the merge ref we attempt to checkout no longer exists and the checkout will fail. The solution (for OMR as an example) would be to launch with "depends on a branch" (#827). Ideally, we would figure this out the first time automatically and not fail. A ~good assumption would be to fallback to checkout master, but this will not always be true (jdk extensions repo does not have a master branch for example). Not sure if it's possible to figure out the target branch of the merged PR. Maybe a simple API call?

**Comment by MichelleXiaoxiaoWang** [comment]
https://github.com/eclipse/openj9/pull/2415
