### ISSUE TITLE
JDK11 builds fail with coredump

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#2373]
Creating jdk image
Object 000000000086D900 not in heap range [00000000E0000000,0000000100000000)
08:44:36.125 0x847700    j9mm.141    *   ** ASSERTION FAILED ** at ./MarkingScheme.hpp:71: ((false))

**Comment by keithc-ca** [comment]
I have a fix in the works for this: it involves ensuring that `JAVA_SPEC_VERSION` is always defined so the condition in j9cfg.h (`JAVA_SPEC_VERSION >= 11`) is evaluated consistently.

**Comment by pshipton** [comment]
Fixed by #2374

**Comment by DanHeidinga** [comment]
A big thank you to everyone involved in tracking this down - @keithc-ca @tajila @charliegracie and any others I may have missed!
