### ISSUE TITLE
Attach API VirtualMachine.getSystemProperties() missing sun.jvm.args

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2377]
HotSpot's implementation of getSystemProperties() adds two system properties: `sun.jvm.flags` and `sun.jvm.args`. The latter is set to JVM arguments such as -Xint.  These properties are not available via System.getProperties() or -XshowSettings.  OpenJ9 does not include these properties.

Documentation issue: eclipse/openj9-docs#216

**Comment by DanHeidinga** [comment]
@pdbain-ibm Which JDK version?  Or all current versions up to / including JDK11?

**Comment by pdbain-ibm** [comment]
Tested with Oracle Java 8, same behaviour:

```
-- listing properties --
sun.jvm.args=-Xmx10m
sun.jvm.flags=
sun.java.command=looper -q
```
sun.jvm.flags seems always to be empty.

See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=491364: "Launcher should set sun.java.command at startup time for attach API".  That has been fixed (launcher adds sun.java.command),
but `sun.jvm.args` is generated by attach API.

**Comment by pdbain-ibm** [comment]
The arguments are available via com.ibm.oti.vm.VM.getVMArgs().

There are multiple possibilities as to what we include:

1. Just the launcher-provided arguments, e.g. for `java  -Xmx10m -Dfoo=bar HelloWorld`
```
-Xmx10m
-Dfoo=bar
-Dsun.java.command=HelloWorld
-Dsun.java.launcher=SUN_STANDARD
-Dsun.java.launcher.pid=13022
``` 
the last 3 arguments being set by the launcher.

2. The fully expanded set, including 
```
-Xoptionsfile=/team/pdbain/projects/modularity/jdk2/lib/options.default
-Xlockword:mode=...
-Xjcl:jclse10_29
-Dcom.ibm.oti.vm.bootstrap.library.path=...
-Dsun.boot.library.path=...
-Djava.library.path=...
-Djava.home=...
-Duser.dir=...
-Djava.class.path=...
```
The latter expands the environment variables IBM_JAVA_OPTIONS and JAVA_TOOL_OPTIONS, plus the contents of options files but includes JVM-generated options.

3. Use the J9CmdLineOption.flags field to indicate JVM-generated options and filter them out in a new method `getUserVMArgs()`.

**Comment by SueChaplain** [comment]
@pshipton This one is still in 0.13.0 but we have no issue for it in the docs repo. Not sure who is assigned to work on it, but please can you ask them to open an issue.

**Comment by pdbain-ibm** [comment]
It is included in https://github.com/eclipse/openj9/pull/4650

**Comment by pdbain-ibm** [comment]
Documentation issue: https://github.com/eclipse/openj9-docs/issues/216.
