### ISSUE TITLE
OpenJ9 does not work with IDEA (Ultimate)

### ISSUE THREAD

**Issue by cdxf** [eclipse/openj9#2391]
My current OpenJ9 version:

> 
> openjdk version "10.0.1" 2018-04-17
> OpenJDK Runtime Environment (build 10.0.1+10)
> Eclipse OpenJ9 VM (build openj9-0.9.0-rc1, JRE 10 Windows 8.1 amd64-64-Bit Compressed References 20180709_82 (JIT enabled, AOT enabled)
> OpenJ9   - da56ab5e
> OMR      - da0c7eeb
> JCL      - 73b1d6004c based on jdk-10.0.1+10)

I tried to run IDEA using this JDK but it only works partially.
Here is some problems:
- Can't open Settings (File -> Setting):

> 2018-07-16 16:24:15,285 [  45740]  ERROR - llij.ide.plugins.PluginManager - java/awt/IllegalComponentStateException 
> java.lang.NoClassDefFoundError: java/awt/IllegalComponentStateException
> 	at java.awt.Component.getLocationOnScreen_NoTreeLock(java.desktop@10.0.1/Component.java:2059)
> 	at java.awt.Component.getLocationOnScreen(java.desktop@10.0.1/Component.java:2033)
> 	at java.awt.event.MouseEvent.<init>(java.desktop@10.0.1/MouseEvent.java:578)
> 	at java.awt.event.MouseEvent.<init>(java.desktop@10.0.1/MouseEvent.java:640)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$$Lambda$2844.000000001E8572C0.run(Unknown Source)
> 	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:307)
> 	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:294)
> 	at javax.swing.AbstractButton.fireActionPerformed(java.desktop@10.0.1/AbstractButton.java:1967)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$$Lambda$2841.000000003210F850.run(Unknown Source)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> 	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
> 	at com.intellij.openapi.application.TransactionGuardImpl$$Lambda$626.000000001F815020.run(Unknown Source)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
> 	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:529)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
> 	at java.awt.Component.processMouseEvent(java.desktop@10.0.1/Component.java:6589)
> 	at javax.swing.JComponent.processMouseEvent(java.desktop@10.0.1/JComponent.java:3342)
> 	at java.awt.Component.processEvent(java.desktop@10.0.1/Component.java:6354)
> 	at java.awt.Container.processEvent(java.desktop@10.0.1/Container.java:2261)
> 	at java.awt.Component.dispatchEventImpl(java.desktop@10.0.1/Component.java:4966)
> 	at java.awt.Container.dispatchEventImpl(java.desktop@10.0.1/Container.java:2319)
> 	at java.awt.Component.dispatchEvent(java.desktop@10.0.1/Component.java:4798)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@10.0.1/Container.java:4914)
> 	at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@10.0.1/Container.java:4543)
> 	at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@10.0.1/Container.java:4484)
> 	at java.awt.Container.dispatchEventImpl(java.desktop@10.0.1/Container.java:2305)
> 	at java.awt.Window.dispatchEventImpl(java.desktop@10.0.1/Window.java:2772)
> 	at java.awt.Component.dispatchEvent(java.desktop@10.0.1/Component.java:4798)
> 	at java.awt.EventQueue.dispatchEventImpl(java.desktop@10.0.1/EventQueue.java:772)
> 	at java.awt.EventQueue.access$600(java.desktop@10.0.1/EventQueue.java:97)
> 	at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:721)
> 	at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:715)
> 	at java.security.AccessController.doPrivileged(java.base@10.0.1/AccessController.java:666)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:97)
> 	at java.awt.EventQueue$5.run(java.desktop@10.0.1/EventQueue.java:745)
> 	at java.awt.EventQueue$5.run(java.desktop@10.0.1/EventQueue.java:743)
> 	at java.security.AccessController.doPrivileged(java.base@10.0.1/AccessController.java:666)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
> 	at java.awt.EventQueue.dispatchEvent(java.desktop@10.0.1/EventQueue.java:742)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@10.0.1/EventDispatchThread.java:203)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@10.0.1/EventDispatchThread.java:124)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@10.0.1/EventDispatchThread.java:113)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:109)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.run(java.desktop@10.0.1/EventDispatchThread.java:90)
> 2018-07-16 16:24:15,287 [  45742]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2018.2 EAP  Build #IU-182.3684.2 
> 2018-07-16 16:24:15,287 [  45742]  ERROR - llij.ide.plugins.PluginManager - JDK: 10.0.1 
> 2018-07-16 16:24:15,287 [  45742]  ERROR - llij.ide.plugins.PluginManager - VM: Eclipse OpenJ9 VM 
> 2018-07-16 16:24:15,287 [  45742]  ERROR - llij.ide.plugins.PluginManager - Vendor: Eclipse OpenJ9 
> 2018-07-16 16:24:15,287 [  45742]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 8 
> 2018-07-16 16:24:15,287 [  45742]  ERROR - llij.ide.plugins.PluginManager - Last Action:  
> 2018-07-16 16:24:18,284 [  48739]  ERROR - ctionCallback.TimedOutCallback - Typeahead request blocked 
> com.intellij.openapi.wm.impl.FocusManagerImpl$2: Time: 3003; cause: Settings...; runnable waiting for the focus change: Focus event list (trying to execute runnable): 
> 	at com.intellij.openapi.wm.impl.FocusManagerImpl.typeAheadUntil(FocusManagerImpl.java:245)
> 	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.typeAheadUntil(IdeFocusManagerImpl.java:79)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:293)
> 	at javax.swing.AbstractButton.fireActionPerformed(java.desktop@10.0.1/AbstractButton.java:1967)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:114)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$$Lambda$2841.000000003210F850.run(Unknown Source)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> 	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
> 	at com.intellij.openapi.application.TransactionGuardImpl$$Lambda$626.000000001F815020.run(Unknown Source)
> 	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
> 	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
> 	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:114)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:529)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:49)
> 	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:549)
> 	at java.awt.Component.processMouseEvent(java.desktop@10.0.1/Component.java:6589)
> 	at javax.swing.JComponent.processMouseEvent(java.desktop@10.0.1/JComponent.java:3342)
> 	at java.awt.Component.processEvent(java.desktop@10.0.1/Component.java:6354)
> 	at java.awt.Container.processEvent(java.desktop@10.0.1/Container.java:2261)
> 	at java.awt.Component.dispatchEventImpl(java.desktop@10.0.1/Component.java:4966)
> 	at java.awt.Container.dispatchEventImpl(java.desktop@10.0.1/Container.java:2319)
> 	at java.awt.Component.dispatchEvent(java.desktop@10.0.1/Component.java:4798)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(java.desktop@10.0.1/Container.java:4914)
> 	at java.awt.LightweightDispatcher.processMouseEvent(java.desktop@10.0.1/Container.java:4543)
> 	at java.awt.LightweightDispatcher.dispatchEvent(java.desktop@10.0.1/Container.java:4484)
> 	at java.awt.Container.dispatchEventImpl(java.desktop@10.0.1/Container.java:2305)
> 	at java.awt.Window.dispatchEventImpl(java.desktop@10.0.1/Window.java:2772)
> 	at java.awt.Component.dispatchEvent(java.desktop@10.0.1/Component.java:4798)
> 	at java.awt.EventQueue.dispatchEventImpl(java.desktop@10.0.1/EventQueue.java:772)
> 	at java.awt.EventQueue.access$600(java.desktop@10.0.1/EventQueue.java:97)
> 	at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:721)
> 	at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:715)
> 	at java.security.AccessController.doPrivileged(java.base@10.0.1/AccessController.java:666)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:97)
> 	at java.awt.EventQueue$5.run(java.desktop@10.0.1/EventQueue.java:745)
> 	at java.awt.EventQueue$5.run(java.desktop@10.0.1/EventQueue.java:743)
> 	at java.security.AccessController.doPrivileged(java.base@10.0.1/AccessController.java:666)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
> 	at java.awt.EventQueue.dispatchEvent(java.desktop@10.0.1/EventQueue.java:742)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@10.0.1/EventDispatchThread.java:203)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@10.0.1/EventDispatchThread.java:124)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@10.0.1/EventDispatchThread.java:113)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:109)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.run(java.desktop@10.0.1/EventDispatchThread.java:90)

Can't Run Project, Build Project:

> java.lang.NoClassDefFoundError: java/text/CalendarBuilder
> 	at java.text.SimpleDateFormat.parse(java.base@10.0.1/SimpleDateFormat.java:1473)
> 	at java.text.DateFormat.parse(java.base@10.0.1/DateFormat.java:393)
> 	at com.intellij.compiler.server.BuildManager.c(BuildManager.java:1361)
> 	at com.intellij.compiler.server.BuildManager.k(BuildManager.java:200)
> 	at com.intellij.compiler.server.BuildManager$$Lambda$484.000000001C5B50F0.run(Unknown Source)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@10.0.1/Executors.java:514)
> 	at java.util.concurrent.FutureTask.run(java.base@10.0.1/FutureTask.java:264)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
> 	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@10.0.1/ThreadPoolExecutor.java:1135)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@10.0.1/ThreadPoolExecutor.java:635)
> 	at java.lang.Thread.run(java.base@10.0.1/Thread.java:835)

Autocomplete doesn't work:

> 
> java.lang.NoClassDefFoundError: java/awt/font/TextLayout
> 	at sun.font.FontDesignMetrics.stringWidth(java.desktop@10.0.1/FontDesignMetrics.java:471)
> 	at sun.swing.SwingUtilities2.getFontStringWidth(java.desktop@10.0.1/SwingUtilities2.java:914)
> 	at sun.swing.SwingUtilities2.stringWidth(java.desktop@10.0.1/SwingUtilities2.java:353)
> 	at sun.swing.SwingUtilities2.stringWidth(java.desktop@10.0.1/SwingUtilities2.java:323)
> 	at javax.swing.SwingUtilities.layoutCompoundLabelImpl(java.desktop@10.0.1/SwingUtilities.java:1133)
> 	at javax.swing.SwingUtilities.layoutCompoundLabel(java.desktop@10.0.1/SwingUtilities.java:1004)
> 	at javax.swing.plaf.basic.BasicLabelUI.layoutCL(java.desktop@10.0.1/BasicLabelUI.java:102)
> 	at javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(java.desktop@10.0.1/BasicLabelUI.java:256)
> 	at javax.swing.JComponent.getPreferredSize(java.desktop@10.0.1/JComponent.java:1680)
> 	at java.awt.GridBagLayout.GetLayoutInfo(java.desktop@10.0.1/GridBagLayout.java:1127)
> 	at java.awt.GridBagLayout.getLayoutInfo(java.desktop@10.0.1/GridBagLayout.java:922)
> 	at java.awt.GridBagLayout.preferredLayoutSize(java.desktop@10.0.1/GridBagLayout.java:742)
> 	at java.awt.Container.preferredSize(java.desktop@10.0.1/Container.java:1821)
> 	at java.awt.Container.getPreferredSize(java.desktop@10.0.1/Container.java:1805)
> 	at javax.swing.JComponent.getPreferredSize(java.desktop@10.0.1/JComponent.java:1682)
> 	at com.intellij.codeInsight.lookup.impl.Advertiser$1.calcPreferredSize(Advertiser.java:65)
> 	at com.intellij.codeInsight.lookup.impl.Advertiser$1.getPreferredSize(Advertiser.java:49)
> 	at com.intellij.codeInsight.lookup.impl.LookupUi$LookupLayeredPane$1.preferredLayoutSize(LookupUi.java:310)
> 	at java.awt.Container.preferredSize(java.desktop@10.0.1/Container.java:1821)
> 	at java.awt.Container.getPreferredSize(java.desktop@10.0.1/Container.java:1805)
> 	at javax.swing.JComponent.getPreferredSize(java.desktop@10.0.1/JComponent.java:1682)
> 	at java.awt.BorderLayout.preferredLayoutSize(java.desktop@10.0.1/BorderLayout.java:724)
> 	at java.awt.Container.preferredSize(java.desktop@10.0.1/Container.java:1821)
> 	at java.awt.Container.getPreferredSize(java.desktop@10.0.1/Container.java:1805)
> 	at javax.swing.JComponent.getPreferredSize(java.desktop@10.0.1/JComponent.java:1682)
> 	at com.intellij.codeInsight.lookup.impl.LookupUi.calculatePosition(LookupUi.java:245)
> 	at com.intellij.codeInsight.lookup.impl.LookupImpl.showLookup(LookupImpl.java:689)
> 	at com.intellij.codeInsight.completion.CompletionProgressIndicator.updateLookup(CompletionProgressIndicator.java:383)
> 	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$stop$2(CompletionProgressIndicator.java:583)
> 	at com.intellij.codeInsight.completion.CompletionProgressIndicator$$Lambda$3068.00000000320BAC50.run(Unknown Source)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
> 	at java.awt.event.InvocationEvent.dispatch(java.desktop@10.0.1/InvocationEvent.java:313)
> 	at java.awt.EventQueue.dispatchEventImpl(java.desktop@10.0.1/EventQueue.java:770)
> 	at java.awt.EventQueue.access$600(java.desktop@10.0.1/EventQueue.java:97)
> 	at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:721)
> 	at java.awt.EventQueue$4.run(java.desktop@10.0.1/EventQueue.java:715)
> 	at java.security.AccessController.doPrivileged(java.base@10.0.1/AccessController.java:666)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@10.0.1/ProtectionDomain.java:87)
> 	at java.awt.EventQueue.dispatchEvent(java.desktop@10.0.1/EventQueue.java:740)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@10.0.1/EventDispatchThread.java:203)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@10.0.1/EventDispatchThread.java:124)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@10.0.1/EventDispatchThread.java:113)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:109)
> 	at java.awt.EventDispatchThread.pumpEvents(java.desktop@10.0.1/EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.run(java.desktop@10.0.1/EventDispatchThread.java:90)
> 

Go to Declaration

> java.lang.NoClassDefFoundError: org/apache/batik/css/engine/value/URIValue

**Comment by pshipton** [comment]
Is it a Java 10 problem or an OpenJ9 problem? i.e. Does it work with OpenJDK v10?

**Comment by cdxf** [comment]
It works with both Oracle JDK and OpenJDK.

**Comment by cdxf** [comment]
The problem only happens in [ EAP version](https://www.jetbrains.com/idea/nextversion/) (both Ultimate and Community) but not in normal version.

**Comment by cdxf** [comment]
I tried with the Community Edition, using OpenJDK 10, I need to add `--add-modules=ALL-SYSTEM` to `idea64.exe.vmoptions`, without this, my project doesn't index.
But afterwards, everything works fine.
Then I try again with OpenJ9 with the same vmargs, but then it becomes so buggy:
![idea](https://user-images.githubusercontent.com/6419729/42800347-a5cabc3a-89c5-11e8-8ae3-919e78fe4ef7.gif)

**Comment by pshipton** [comment]
FYI we are still finding problems such as https://github.com/eclipse/openj9/pull/2402, and working on some remaining compliance failures.

**Comment by pdbain-ibm** [comment]
I'll take a look at this issue.

**Comment by pdbain-ibm** [comment]
I downloaded ideaIC-2018.2.tar.gz for Linux X86. It runs simple operations (create and run HelloWorld) fine with the JRE embedded in the package.  I used the `Switch JDK` feature to select a recent builds of OpenJDK Java 10, with HotSpot and OpenJ9.  It failed to launch in both cases:
```
Caused by: java.lang.NoClassDefFoundError: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
    at com.intellij.ide.ui.laf.IdeaLaf.initIdeaDefaults(IdeaLaf.java:81)
    at com.intellij.ide.ui.laf.IdeaLaf.initComponentDefaults(IdeaLaf.java:28)
    at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(java.desktop@10.0.2-adoptopenjdk/BasicLookAndFeel.java:150)
    at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(java.desktop@10.0.2-adoptopenjdk/MetalLookAndFeel.java:1560)
    at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:95)
    at javax.swing.UIManager.setLookAndFeel(java.desktop@10.0.2-adoptopenjdk/UIManager.java:587)
    at com.intellij.ide.ui.laf.LafManagerImpl.setCurrentLookAndFeel(LafManagerImpl.java:377)
    at com.intellij.ide.ui.laf.LafManagerImpl.loadState(LafManagerImpl.java:268)
    at com.intellij.ide.ui.laf.LafManagerImpl.loadState(LafManagerImpl.java:64)
    at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:356)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:312)
    at com.intellij.configurationStore.ComponentStoreImpl.initPersistenceStateComponent(ComponentStoreImpl.kt:115)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:90)
    at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:15)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
    ... 31 more
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:224)
    at java.lang.ClassLoader.loadClassHelper(java.base@10.0.2-adoptopenjdk/ClassLoader.java:1134)
    at java.lang.ClassLoader.loadClass(java.base@10.0.2-adoptopenjdk/ClassLoader.java:1049)
    at java.lang.ClassLoader.loadClass(java.base@10.0.2-adoptopenjdk/ClassLoader.java:1032)
```

I suspect this is an incompatibility with the Java 10 packaging.
Note that the IntelliJ documentation https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under  says: `Please note that using JetBrains Runtime is highly recommended for performance and stability reasons (it fixes many known OpenJDK and Oracle JDK bugs).`
Would you kindly try the OpenJ9 Java 10 with Hotspot? 
https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/201807101745/OpenJDK10_x64_Windows_201807101745.zip

**Comment by pdbain-ibm** [comment]
@cdxf 
I tested with the OpenJ9 and Hotspot Java 8 builds and both seem fine on Linux.  Would you kindly test with a Java 8 OpenJ9 build, such as https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u172-b11-201813080730/OpenJDK8-OPENJ9_x64_Windows_201813080730.zip.

Thank you
    -p

**Comment by cdxf** [comment]
It works fine both with OpenJ9/Hotspot Java8 and Hotspot Java 10 (which I am using without problems), 
I only have problems with OpenJ9 Java 10. The UI is very laggy, menubar sometimes unclickable, indexing is very buggy and I can't run the app or build it

**Comment by cdxf** [comment]
The latest time I tried with OpenJ9 Java 8 it fallback into the bundled JRE. 
For some reason, Intellij can't recogize the OpenJ9 Java 8 (but can recognize Hotspot Java 8 and works fine): 

`The enviroment variable JAVA_HOME (with the value of C:\Program Files\Java\jdk8u181-b13) does not point to a valid JVM installation.
`

I tried with different paths like jdk8u181-b13, jdk8u181-b13\bin, jdk8u181-b13\jre, jdk8u181-b13\jre\bin but none of them works

**Comment by pdbain-ibm** [comment]
I installed a fresh copy of IDEA community edition on a Windows 10 system and set the boot SDK to the latest Windows download of OpenJ9 Java 10: https://github.com/AdoptOpenJDK/openjdk10-openj9-nightly/releases/download/jdk-10.0.2%2B13-201808131307/OpenJDK10-OPENJ9_x64_Windows_201808131307.zip.  I'm not intimately familiar with the expected behaviour of IDEA, the performance was similar to the default embedded SDK.

**Comment by cdxf** [comment]
Update to OpenJ9 Java 11 fixed this problem
