### ISSUE TITLE
Enable a travis.ci-based PR build for linux x86-64

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#24]
Build a basic PR build based off the linux_x86-64 docker file.

**Comment by mgaudet** [comment]
This has been enabled, but we're seeing the occasional build failures that look like this

```[2017-09-21 04:25:59] OpenJ9 clone repositories finished in 4 seconds
Update openj9 to commit ID: d13eb4bbf02ddc6653524c236b5fd85c5c3264a5
fatal: reference is not a tree: d13eb4bbf02ddc6653524c236b5fd85c5c3264a5
The command "cd openj9-openjdk-jdk9 && bash ./get_source.sh -openj9-repo=$TRAVIS_BUILD_DIR -openj9-branch=$TRAVIS_BRANCH -openj9-sha=$TRAVIS_COMMIT" exited with 128.
```

https://travis-ci.org/eclipse/openj9/builds/277929812?utm_source=github_status&utm_medium=notification

**Comment by mgaudet** [comment]
Related to #11, one concern w/ travis builds is how to represent dependent changes.

**Comment by DanHeidinga** [comment]
Regarding the "fatal: reference is not a tree" issue, my understanding is that it is related to force pushes to the repo.  The PR build clones (with depth=50) the openj9 repo, merges the PR branch into the master branch, and then we run get_sources trying to checkout at a particular sha as supplied to travis.  

If a force push occurs, the sha may not be in the repo any more.  See https://github.com/travis-ci/travis-ci/issues/617 for more details.

**Comment by DanHeidinga** [comment]
> Related to #11, one concern w/ travis builds is how to represent dependent changes.

The travis.ci builds are a (hopefully) short term necessity.  @AdamBrousseau has recently enabled Jenkins-based PR builds on pLinux & zLinux.  Prior to open sourcing, our internal PR builds were able to handle cross repo dependencies so it should just be a matter of time until we've replicated the functionality here.

**Comment by AdamBrousseau** [comment]
>replicated the functionality here.

Done #122

**Comment by AdamBrousseau** [comment]
I think we should wrap the `script` commands in `set -e` & `set +e` so that we fail fast if any of the commands fail.
See travis-ci/travis-ci#1066

I am going to play around with the checkout (fatal: reference is not a tree) issue. I have a few suspicions.

**Comment by DanHeidinga** [comment]
Closing this as the compile only travis builds have been available for some time.  Thanks to everyone who helped to improve their stability!
