### ISSUE TITLE
New JDK12 JVM function 'JVM_InitializeFromArchive' missing from OpenJ9 

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#2419]
In the latest jdk code available from  https://github.com/ibmruntimes/openj9-openjdk-jdk (which is jdk next ie 12) Oracle seem to have added a new function to ./src/java.base/share/native/libjava/VM.c which calls `JVM_InitializeFromArchive(env, c);`. This doesnt seen to be available in the OpenJ9 code and therefore produced this error:
```
/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/build/linux-x86_64-normal-server-release/support/native/java.base/libjava/VM.o: In function `Java_jdk_internal_misc_VM_initializeFromArchive':
/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/src/java.base/share/native/libjava/VM.c:67: undefined reference to `JVM_InitializeFromArchive'
collect2: error: ld returned 1 exit status
CoreLibraries.gmk:128: recipe for target '/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/libjava.so' failed
make[3]: *** [/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/libjava.so] Error 1
```
This function `JVM_InitializeFromArchive` needs to be added somewhere in the OpenJ9 code to enable the JDK12 build to complete successfully.

**Comment by groeges** [comment]
Added slack comments from Michael Rasmussen:

This is for JDK-8202035, having it a no-op should be a valid implementation
The javadoc for `jdk.internal.misc.VM::initializeFromArchive` has more info: http://hg.openjdk.java.net/jdk/jdk/file/tip/src/java.base/share/classes/jdk/internal/misc/VM.java#l417

**Comment by JasonFengJ9** [comment]
Will look at this.
