### ISSUE TITLE
Rework getJimModules()

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2437]
getJimModules() loads and caches `java/lang/reflect/Module`.  This is currently used only by JVMTI.
Per 
https://github.com/eclipse/openj9/pull/2420#issuecomment-406409243, 
 suggest using 
`enterVMFromJNI
J9Class *clazz = J9VM_J9CLASS_FROM_JCLASS(vmThread, jclassForModule);
jimModule = &clazz->classObject;
exitVMToJNI
`

Also create a macro `JCLASS_FROM_J9CLASS ` to do `(jclass)&someJ9Class->classObject`

**Comment by pdbain-ibm** [comment]
Also, 
https://github.com/eclipse/openj9/pull/2420#pullrequestreview-138839583

**Comment by pdbain-ibm** [comment]
runtime/vm/classloadersearch.c
+loadModule(J9JavaVM *vm, const char *moduleName, jobject *modulePtr)
+{
+	UDATA rc = CLS_ERROR_NONE;
+	J9VMThread *currentThread = currentVMThread(vm);
  @keithc-ca
keithc-ca 8 minutes ago  Contributor
Where this function is used, we've already retrieved the current thread: it would make sense to avoid redoing that by passing currentThread or env instead of vm.

**Comment by pdbain-ibm** [comment]
runtime/vm/classloadersearch.c
+	vmModule = (*env)->CallStaticObjectMethod(env, jimModules, loadModule, moduleNameString);
+	if ((*env)->ExceptionOccurred(env)) {
+		rc = CLS_ERROR_INTERNAL;
+	} else if (NULL != modulePtr) {
  @keithc-ca
keithc-ca 9 minutes ago  Contributor
I like GAC's suggestion to move this after done and remove the *modulePtr = NULL; above.

**Comment by gacholio** [comment]
Not defining the macro I suggested, since the "ref" created doesn't keep the class alive, so the macro would be ripe for accidental misuse.

**Comment by gacholio** [comment]
Changes are here:

https://github.com/gacholio/openj9/tree/rework

I won't open a PR for them until @pdbain-ibm has tested them against the failure he was addressing.

**Comment by pdbain-ibm** [comment]
@gacholio do you have a Linux x86 build in hand?  If not, I will build from your repo.

**Comment by gacholio** [comment]
I'll run a test build to get the SDK.

**Comment by pdbain-ibm** [comment]
I pulled this one file into an exisiting build and did a quick test using -javaagent.  Tested and working.
