### ISSUE TITLE
Install MSVC2017 for OpenJ9 windows compile machines

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#2469]
As per #1697 Windows will support compiling with VS2017 shortly once the changes are merged. VS2017 needs to be installed on the build machines and then used to build JDK11.

**Comment by ChengJin01** [comment]
I already created a change for VS2017 at https://github.com/ChengJin01/openjdk-infrastructure/tree/update_install_vs2017.  @jdekonin is helping to verify whether it works via Ansible Tower.

**Comment by vsebe** [comment]
Installed MingWG-W64 8.1 and VS2017 on [windows machines](https://ci.eclipse.org/openj9/label/sw.os.windows/): 
 - win2012r2-x86-1
 - win2012r2-x86-2 
 - win2012r2-x86-3
 - win2012r2-x86-4

**Comment by vsebe** [comment]
[JDK11 build](https://ci.eclipse.org/openj9/view/Sandbox/job/wip_Build-Any_Platform/32/console)
Failure: ` make[5]: *** [run_omrddrgen.mk:73: ../j9ddr.dat] Segmentation fault` - know issue: #2885

**Comment by ChengJin01** [comment]
For the temporary solution, the crash can be avoided by specifying **--enable-ddr=no** to disable DDR-related code as DDR doesn't affect the operation of VM.
e.g.
bash configure --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-boot-jdk=/cygdrive/c/openjdk/jdk10 --with-toolchain-version=2017 **--enable-ddr=no**  --disable-ccache`

**Comment by pshipton** [comment]
Heads up that we are investigating using clang instead of mingw on Windows. If performance testing looks good we'll have to install clang on the builds machines as well.

**Comment by pshipton** [comment]
MSVC2017 is installed and in use for Java 11 builds.
