### ISSUE TITLE
Test failures with JDK11 on Windows

### ISSUE THREAD

**Issue by ChengJin01** [eclipse/openj9#2493]
With all script changes on Windows JDK11 at https://github.com/eclipse/openj9/issues/1697, the following test failures in sanity were detected:

FAILED test targets:
        cmdLineTester_callsitedbgddrext_openj9_0
        cmdLineTester_GCRegressionTests_3
        testSCCMLModularity_1
        JCL_Test_0
        JCL_Test_1
        JCL_Test_OutOfMemoryError_0
        JCL_Test_OutOfMemoryError_1
        JCL_TEST_Java-Security_0
        JCL_Test_Package_0
        JLM_Tests_interface_0
        JLM_Tests_interface_1
        J9vmTest_4
        J9vmTest_5

TOTAL: 166   EXECUTED: 85   PASSED: 72   FAILED: 13   SKIPPED: 81

[TestTargetResult.txt](https://github.com/eclipse/openj9/files/2233520/TestTargetResult.txt)

In addition, extended tests are also required to run after these failures get addressed.

FYI:  @DanHeidinga , @keithc-ca , @pshipton , @llxia

**Comment by hangshao0** [comment]
I see your JAVA_BIN is C:/temp/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release/jdk/bin. I guess some of the above tests will pass if you point JAVA_BIN under the "images" directory: C:/temp/openj9-openjdk-jdk11/build/windows-x86_64-normal-server-release/**images**/jdk/bin.

**Comment by ChengJin01** [comment]
There is no test will be compiled with /images/jdk/bin as no test libraries exist in there. This is new change since JDK11. The test libraries will be placed at images/test.

**Comment by llxia** [comment]
Thanks @ChengJin01 for sharing his JDK11. I ran the tests in internal Jenkins using jdk/bin and got slightly different results:

**sanity.functional**
FAILED test targets:
01:15:20.805 	cmdLineTester_callsitedbgddrext_openj9_0
01:15:20.805 	cmdLineTester_GCRegressionTests_3
01:15:20.805 	testSCCMLModularity_1
01:15:20.805 	cmdLineTester_SCURLClassLoaderNPTests_1
01:15:20.805 	JCL_Test_0
01:15:20.805 	JCL_Test_1
01:15:20.805 	JCL_Test_OutOfMemoryError_1
01:15:20.805 	J9vmTest_4
01:15:20.805 	J9vmTest_5
01:15:20.805 
01:15:20.805 TOTAL: 166   EXECUTED: 85   PASSED: 76   FAILED: 9   SKIPPED: 81

[sanity.functional_TestTargetResult.txt](https://github.com/eclipse/openj9/files/2241982/sanity.functional_TestTargetResult.txt)


**extended.functional**
01:48:08.130 FAILED test targets:
01:48:08.130 	cmdLineTester_classesdbgddrext_1
01:48:08.130 	cmdLineTester_shrcdbgddrext_1
01:48:08.130 	threadMXBeanTimersTest_3
01:48:08.130 	jsr292Test_1
01:48:08.130 
01:48:08.130 TOTAL: 294   EXECUTED: 106   PASSED: 102   FAILED: 4   SKIPPED: 188

[extended.functional_TestTargetResult.txt](https://github.com/eclipse/openj9/files/2241852/extended.functional_TestTargetResult.txt)

I will re-test the failed ones with JDK11 under images/jdk/bin

**Comment by pshipton** [comment]
I believe these failures are resolved now. For anything not resolved there are other Issues open.
