### ISSUE TITLE
Failure to attach com.sun.tools.attach.VirtualMachine agent on Windows AMD64

### ISSUE THREAD

**Issue by scottkurz** [eclipse/openj9#2505]
With [this nightly build](https://github.com/AdoptOpenJDK/openjdk8-openj9-nightly/releases/download/jdk8u172-b11-201827070700/OpenJDK8-OPENJ9_x64_Windows_201827070700.zip) I get this message:

> The Liberty Java agent could not be attached. This server will run, but it cannot perform functions that require the Java agent, such as monitoring or tracing. Exception: java.lang.IllegalAccessException: Class wlp.lib.extract.AgentAttach can not access a member of class com.ibm.tools.attach.attacher.OpenJ9VirtualMachine with modifiers "public synchronized"
La

To recreate:

1. package a Liberty server as a runnable JAR.    
    * One way is to take a Maven build such as the [BonusPayout sample](https://github.com/WASdev/sample.batch.bonuspayout) and do `mvn package`.

2. Then execute via:  `java -jar MyServer.jar`, e.g.:
>  java -jar target/batch-bonuspayout-application.jar

---

For reference, [here](https://github.com/OpenLiberty/open-liberty/blob/master/dev/wlp.lib.extract/src/wlp/lib/extract/AgentAttach.java) is the class in Open Liberty which invokes the **com.sun.tools.attach.VirtualMachine** agent attachment routine.   

I'm not sure there's any other consequence.  In truth, I don't really know what this code is doing.

**Comment by pshipton** [comment]
@pdbain-ibm

**Comment by pdbain-ibm** [comment]
@scottkurz Do you know why the code is using reflection to call the attach API methods? Straight calls to the static methods should do the trick.

**Comment by pdbain-ibm** [comment]
Looking at the `META-INF/services/com.sun.tools.attach.spi.AttachProvider` file in `tools.jar`, I see it has the wrong class for the service provider.  I am attaching an updated `tools.jar`, packaged in a zip file.  Would you kindly test it and see if that change anything?
[tools.jar.zip](https://github.com/eclipse/openj9/files/2242538/tools.jar.zip)

**Comment by scottkurz** [comment]
@pdbain-ibm  not sure why reflection.   If I had to guess, it was to make a build process easier, but not really sure.

**Comment by pdbain-ibm** [comment]
`com.ibm.tools.attach.attacher.OpenJ9VirtualMachine` is not a public class, nor is `com.ibm.tools.attach.attacher.OpenJ9AttachProvider`.  The equivalent Sun classes such as `sun.tools.attach.LinuxVirtualMachine`, `sun.tools.attach.HotSpotVirtualMachine`, and `sun.tools.attach.HotSpotAttachProvider` are public.
