### ISSUE TITLE
Must run jdmpview from a 32-bit JVM to look at a 32-bit core file

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2507]
Until it can be fixed, you must run jdmpview from a 32-bit JVM to look at a 32-bit core file. Similarly you must run jdmpview from a 64-bit JVM to look at a 64-bit core file.

**Comment by gacholio** [comment]
This should not be true. Should be fixed rather than documented.

**Comment by pshipton** [comment]
It will be fixed, but should be documented until the fix is ready.

I don't think the fix is going to be ready for the 0.10.0 release, deferring.

**Comment by pshipton** [comment]
I don't think this should have been closed yet since the changes in the extensions repo haven't been merged yet.

**Comment by pshipton** [comment]
The jdk11 part is merged https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/28

**Comment by pshipton** [comment]
The jdk11 part has to be reverted https://github.com/eclipse/openj9/issues/3227

Moving this to the 0.12.0 milestone as its becoming too late up make further updates to 0.11.0

**Comment by pshipton** [comment]
Deferring this until all the DDR testing is running.
