### ISSUE TITLE
Boot JDKs should be updated

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#2519]
Now that https://github.com/eclipse/omr/pull/2796 has been merged into OMR, we can gain some extra build performance by updating boot JDKs to include that fix. It's most significant on Linux 390, but it wouldn't hurt to update all build platforms.

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
Suggest updating zlinux immediately to take advantage of the faster jvm, and then updating everything once the 0.9.0 release builds are available.

**Comment by AdamBrousseau** [comment]
Will there be much value added if we update 390 now vs waiting once all 0.9 is available?

**Comment by pshipton** [comment]
It might build much faster. Keith mentioned getting a 7 min build, but not sure what it was before. Looking [here](https://ci.eclipse.org/openj9/blue/organizations/jenkins/Build-JDK10-linux_390-64_cmprssptrs/detail/Build-JDK10-linux_390-64_cmprssptrs/346/pipeline) I see 30 min.

**Comment by keithc-ca** [comment]
The time will depend (a little) on the number of cores available; the machine I used has 16.

**Comment by keithc-ca** [comment]
I think this has been done: closing.
