### ISSUE TITLE
libjvmtitest.so is missing

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#252]
This is causing issue https://github.com/eclipse/openj9/issues/238
libjvmtitest.so is an example JVMTI agent used for JVMTI and Attach API tests.
Source is in openj9/test/cmdLineTests/jvmtitests/.

**Comment by pdbain-ibm** [comment]
This is also causing https://github.com/eclipse/openj9/issues/241.

**Comment by smlambert** [comment]
To be clear, there are 2 parts to the jvmti tests: 

1) the java source alluded to above (in test/cmdLineTests/jvmtitests), which has been migrated and is ready to be included and run as part of sanity.
2) the native library, libjvmtitest.so, which used to be compiled during the compilation of the JVM, but is no longer being compiled.  Adding the comp:build label additionally to this issue, as if we want to include and run the tests, this native library needs to be compiled and available.  

Looking at the OpenJDK native tests, the native test libraries are compiled at the same time as the JVM.  The make target to compile the OpenJDK native test libraries is "make test-image".
