### ISSUE TITLE
Build failure OpenJDK9+OpenJ9 on AIX

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#2529]
```
m4 -DAIXPPC  -I. -I../include -I../oti -I../util -I../gc_include -I../omr/gc/include -I../shared_common/include -I../gc_glue_java -I../nls -I../omr/include_core  pcinterp.m4 > pcinterp.s

m4:pcinterp.m4:phelpers.m4:330 more than 4096 bytes of argument text
```

```
m4 -DAIXPPC  -I. -I../include -I../oti -I../util -I../gc_include -I../omr/gc/include -I../compiler/runtime -I../nls -I../omr/include_core  pnathelp.m4 > pnathelp.s

m4:pnathelp.m4:phelpers.m4:330 more than 4096 bytes of argument text
```

... attempting to build https://github.com/ibmruntimes/openj9-openjdk-jdk9 on/with ...

```
bash-4.3# uname -a
AIX aoaix2 2 7 00F6AB0E4C00
bash-4.3# make -v
GNU Make 4.1
Built for powerpc-ibm-aix6.1.0.0
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Build logs quoted text from ...

[build.1.log](https://github.com/eclipse/openj9/files/2249895/build.1.log)
[build.2.log](https://github.com/eclipse/openj9/files/2249896/build.2.log)

**Comment by jdekonin** [comment]
What is the version of m4?  xlc?

**Comment by ben-walsh** [comment]
Hmmmm. m4 isn't the GNU version. I've gone ahead and installed all the GNU versions of the tools from the packages in https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile.
It might be helpful for the configure script to fail if the GNU versions aren't available, if the OS provided ones cause build failures.
That or we need to document what yum packages are required for building on AIX.

**Comment by pshipton** [comment]
FYI examples of working builds:
0.9.0 release branch: https://ci.eclipse.org/openj9/job/Build-JDK9-aix_ppc-64_cmprssptrs/165/
head: https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK9-aix_ppc-64_cmprssptrs/149/

**Comment by pshipton** [comment]
There are instructions here https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V9.md#aix that include a list of yum packages.

**Comment by keithc-ca** [comment]
What part of those instructions specifies the version `m4` that should be installed?

**Comment by sxa555** [comment]
Not sure what caused this, but I was successfully able to build AO9/J9 using the 0.9.0 release branch on the adoptopenjdk CI and release it

**Comment by DanHeidinga** [comment]
Closing as this has gone stale
