### ISSUE TITLE
"jenkins test all" includes jdk11 but should not

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2539]
"jenkins test all" is not supposed to include jdk11 right now, since it doesn't compile and pass the tests. However it does seem to include jdk11, see https://github.com/eclipse/openj9/pull/2524 or https://github.com/eclipse/openj9/pull/2044

**Comment by pshipton** [comment]
@jdekonin

**Comment by DanHeidinga** [comment]
Any update on this @jdekonin ?

**Comment by jdekonin** [comment]
The JDK11 jobs were updated to stop doing this the morning after the ticket was opened.  But there were some modifications to triggers suggested and requested that @vsebe, @AdamBrousseau and I have been investigating with this as the reference issue.

I posted in the #committers-public channel last week with some details.

**Comment by pshipton** [comment]
I assume (and expect) `jenkins test sanity all` won't do anything, as the jdk levels will need to be specified?

**Comment by jdekonin** [comment]
Correct.
