### ISSUE TITLE
OpenJ9 Attach API Diagnostic extension

### ISSUE THREAD

**Issue by d0k1** [eclipse/openj9#2543]
I always ran jstack / jmap / jstat for OpenJDK in order get some diagnostic information. And I'd like to have similar useful utilities for OpenJ9.  I know I can configure -Xdump or use Diagnostic MBean to get a threaddump or heapdump, but it is not convenient for me.
jstack, jmap and other openjdk tools use Attach API to ask VM for a specific operation. So to make these  tools support OpenJ9 I want to extend Attach API implementation.
I want to add commands in jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Command.java.
After that, I will implement these commands in 
jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Attachment.java. 
To get java dump / heap dump I will call jcl/src/openj9.jvm/share/classes/com/ibm/jvm/Dump.java. 
May be there will be more commands

**Comment by pshipton** [comment]
Seems fine so far.
@pdbain-ibm fyi, and any concerns?

**Comment by d0k1** [comment]
To implement command line diagnostic utilities like jstack / jmap / etc I decided to use Attact API just as jstack does. Attach API extension contains 8 new commands. Among them, there are commands to get javadump/systemdump/heapdump/snapdump and to get Information about memory, about loaded/unloaded classes about JIT compilation time. There is one command to get a thread dump through com.ibm.lang.management.internal.ExtendedThreadMXBeanImpl. The communication between JVM and Attach API client is going through IPC mechanism. Some commands have to send back some data to a client so they use java serialization to serialize a response and send it. Besides there are some new methods in com.ibm.tools.attach.attacher.OpenJ9VirtualMachine that uses the extension.
