### ISSUE TITLE
openj9 build fails on ubuntu VM when compiling with debug enabled

### ISSUE THREAD

**Issue by atawre** [eclipse/openj9#2552]
I followed steps mentioned at - https://blog.openj9.org/2018/06/05/debugging-openj9-in-docker-with-gdb/ to compile debug build. 
I am using ubuntu VM and not the docker instance.

Machine details as follow - 
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

$ uname -a
Linux DataTemperature 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:48:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Without debug symbols, build does work for me.
The build fails with following messages.

Staging OpenJ9 runtime in /homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm
Compiling 61 files for BUILD_INTERIM_jdk.jdeps
Compiling 457 files for BUILD_INTERIM_jdk.javadoc
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Compiling 159 files for BUILD_TOOLS_JDK
Compiling 198 files for BUILD_INTERIM_RMIC
Compiling 141 files for BUILD_IDLJ
Compiling 6 files for BUILD_TOOLS_CORBA
Compiling 31 files for BUILD_JRTFS
Sjavac server failed to initialize: No port file values materialized. Giving up after 61796 ms
Sjavac server failed to initialize: No port file values materialized. Giving up after 61795 ms
Sjavac server failed to initialize: No port file values materialized. Giving up after 62056 ms
Process output:
Process output:
Sjavac server failed to initialize: No port file values materialized. Giving up after 62056 ms
Process output:
Process output:
Sjavac server failed to initialize: No port file values materialized. Giving up after 60388 ms
Process output:
<End of process output>
Process exit code: 1
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60388 ms
<End of process output>
<End of process output>
<End of process output>
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 61795 ms
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 61796 ms
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 62056 ms
make[3]: *** [/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/support/jrtfs_classes/_the.BUILD_JRTFS_batch] Error 1
make[2]: *** [jrtfs-jar] Error 1
make[2]: *** Waiting for unfinished jobs....
make[3]: *** [/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/buildtools/override_modules/jdk.rmic/_the.BUILD_INTERIM_RMIC_batch] Error 1
make[2]: *** [interim-rmic] Error 1
make[3]: *** [/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/buildtools/jdk_tools_classes/_the.BUILD_TOOLS_JDK_batch] Error 1
make[2]: *** [buildtools-jdk] Error 1
make[3]: *** [/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/buildtools/idlj_classes/_the.BUILD_IDLJ_batch] Error 1
make[3]: *** Waiting for unfinished jobs....
Staging OpenJ9 OMR in /homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm
Running OpenJ9 preprocessors with OPENJ9_BUILDSPEC: linux_x86-64_cmprssptrs
make[4]: Entering directory `/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm'
/usr/bin/make -C sourcetools -f buildj9tools.mk FREEMARKER_JAR=/homes/ataware/src/freemarker.jar
make[5]: Entering directory `/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm/sourcetools'
Building lib/j9nls.jar
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Building lib/j9vmcp.jar
Building lib/uma.jar
Note: j9constantpool/com/ibm/oti/VMCPTool/Main.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: com.ibm.uma/com/ibm/j9/uma/util/Tree.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
make[5]: Leaving directory `/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm/sourcetools'
/homes/ataware/src/large_pages/jdk/bin/java -cp sourcetools/lib/j9nls.jar com.ibm.oti.NLSTool.J9NLS
J9VM version: 6312ea1
/homes/ataware/src/large_pages/jdk/bin/java -cp "sourcetools/lib/om.jar:/homes/ataware/src/freemarker.jar:sourcetools/lib/uma.jar" com.ibm.j9.uma.Main -rootDir . -configDir buildspecs -buildSpecId linux_x86-64_cmprssptrs -buildId 000000 -buildTag 6312ea1 -jvf compiler/jit.version -buildDate 20180806 -ea tracegen,tracemerge
/homes/ataware/src/large_pages/jdk/bin/java -cp "sourcetools/lib/om.jar:sourcetools/lib/j9vmcp.jar" com.ibm.oti.VMCPTool.Main -rootDir . -buildSpecId linux_x86-64_cmprssptrs -configDir buildspecs -jcls se7_basic,se9_before_b165,se9
Universal Makefile Adapter - for J9, version 2.5.1

<End of process output>
Process exit code: 0
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 62056 ms
make[3]: *** [/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/buildtools/corba_tools_classes/_the.BUILD_TOOLS_CORBA_batch] Error 1
make[2]: *** [java.corba-gensrc-corba] Error 1
Reading constant pool from ./oti/vmconstantpool.xml
Found 7 flags used, declaring runtime constants.
        #define JCL_RTFLAG_DEFAULT  0x1 (useCount=212)
        #define JCL_RTFLAG_INTERP_HOT_CODE_REPLACEMENT  0x2 (useCount=1)
        #define JCL_RTFLAG_JIT_NEW_INSTANCE_PROTOTYPE  0x40 (useCount=1)
        #define JCL_RTFLAG_OPT_METHOD_HANDLE  0x8 (useCount=96)
        #define JCL_RTFLAG_OPT_MODULE  0x20 (useCount=12)
        #define JCL_RTFLAG_OPT_PANAMA  0x10 (useCount=2)
        #define JCL_RTFLAG_OPT_REFLECT  0x4 (useCount=16)
Generating header file ** Generating ./oti/j9vmconstantpool.h
Generating jcl constant pool definitions for se7_basic in ** Generating ./jcl/j9vmconstantpool_se7_basic.c
Generating jcl constant pool definitions for se9_before_b165 in ** Generating ./jcl/j9vmconstantpool_se9_before_b165.c
Generating jcl constant pool definitions for se9 in ** Generating ./jcl/j9vmconstantpool_se9.c

************************************************

        Total # of locales processed:           19
        Total # of NLS Files processed:         399
        Total # of messages processed:          34506

        Total # of header files generated:      21
        Total # of properties files generated:  19
        Total # of errors:                      0

************************************************

.
..
.
.
.
.

.

xt.o mgmtprocessor.o mgmtruntime.o mgmtthread.o orbvmhelpers.o proxy.o reflecthelp.o shared.o sigquit.o stdinit.o string.o sun_misc_Perf.o sun_misc_URLClassPath.o sun_misc_Unsafe.o sun_reflect_ConstantPool.o syshelp.o system.o thread.o unsafe_mem.o ut_j9jcl.o vm_scar.o vmfilesys.o vminternals.o \
     -Xlinker --start-group -lj9util -lj9utilcore -lj9vmi -lsunvmi -lj9avl -lj9hashtable -lj9pool -Xlinker --end-group -lomrsig -lj9hookable29 -lj9zlib29 -lj9thr29  -g -lm
objcopy --only-keep-debug ../../libjclse7b_29.so ../../libjclse7b_29.so.dbg
objcopy --add-gnu-debuglink=../../libjclse7b_29.so.dbg ../../libjclse7b_29.so
make[5]: Leaving directory `/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm/jcl/cl_se7_basic'
make[4]: Leaving directory `/homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/vm'
OpenJ9 compile complete
Creating support/modules_libs/java.base/server/libjvm.so from J9 sources

ERROR: Build failed for target 'all' in configuration 'linux-x86_64-normal-server-fastdebug' (exit code 2)

=== Output from failing command(s) repeated here ===
* For target buildtools_corba_tools_classes__the.BUILD_TOOLS_CORBA_batch:
Sjavac server failed to initialize: No port file values materialized. Giving up after 62056 ms
Process output:
<End of process output>
Process exit code: 0
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 62056 ms
* For target buildtools_idlj_classes__the.BUILD_IDLJ_batch:
Sjavac server failed to initialize: No port file values materialized. Giving up after 61795 ms
Process output:
<End of process output>
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 61795 ms
* For target buildtools_jdk_tools_classes__the.BUILD_TOOLS_JDK_batch:
Sjavac server failed to initialize: No port file values materialized. Giving up after 62056 ms
Process output:
<End of process output>
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 62056 ms
* For target buildtools_override_modules_jdk.rmic__the.BUILD_INTERIM_RMIC_batch:
Sjavac server failed to initialize: No port file values materialized. Giving up after 61796 ms
Process output:
<End of process output>
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 61796 ms
* For target support_jrtfs_classes__the.BUILD_JRTFS_batch:
Sjavac server failed to initialize: No port file values materialized. Giving up after 60388 ms
Process output:
<End of process output>
Process exit code: 1
IOException caught during compilation: Server failed to initialize: No port file values materialized. Giving up after 60388 ms

* All command lines available in /homes/ataware/src/debug/protect_pages/cold-memory-openjdk-j9/build/linux-x86_64-normal-server-fastdebug/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See common/doc/building.html#troubleshooting for assistance.

make[1]: *** [main] Error 1
make: *** [all] Error 2

**Comment by fjeremic** [comment]
@babsingh any pointers regarding this?

**Comment by babsingh** [comment]
This issue looks similar to https://github.com/eclipse/openj9/issues/2364 (`Sjavac server failed to initialize: No port file values materialized`).

In #2364, Keith suggests that the issue may be related to the boot JDK.

Possible workaround: run configure with `--disable-sjavac` - `bash ./configure --with-freemarker-jar=/root/freemarker.jar --disable-sjavac`. Configure output should have `checking whether to use sjavac... no`.

@atawre can you verify if the issue is resolved using the above option? can you provide the Java stack trace for the `IOException`? also, can you verify if the issue is resolved using an OpenJ9 Dockerfile (from https://www.eclipse.org/openj9/oj9_build.html)?

**Comment by atawre** [comment]
I got the debug build working for ubuntu 16 docker instance (host : ubuntu 14.04) . 
thanks for quick help from babneet.

**Comment by Holmistr** [comment]
Just in case it will help someone in the future - I ran into the same problem with vanilla OpenJDK build. This GH issue pointed me to the fact that I was using a previously built debug build as a boot JDK which made it super slow and thus giving up after a timeone. 
Switching to a "classic" OpenJDK build as a boot JDK solved the problem.
