### ISSUE TITLE
Java 11 interpreter sometimes skips type test for super invokespecial in interface method

### ISSUE THREAD

**Issue by jdmpapin** [eclipse/openj9#2577]
Super `invokespecial` requires that the receiver be an instance of the current class (i.e. the class containing the `invokespecial` bytecode instruction). When the current class is an interface, this is not guaranteed by bytecode verification. Instead, the `invokespecial` instruction dynamically checks that the receiver implements the current interface, and if not, it throws `IllegalAccessError`.

The attached [`BadSuperInInterface`](https://github.com/eclipse/openj9/files/2275859/BadSuperInInterface.zip) should print `true`, `false`, `true`, and then throw `IllegalAccessError`. I get the correct result from OpenJ9 if it is built as Java 8, or if it is built as Java 11 and JIT options force the `nosey` method to be compiled. But if `nosey` is interpreted in Java 11, I don't get an exception.

The problem appears to have been introduced by #2434. If I build with that commit reverted, I get the exception again.

I tried to reduce the test case further with [`InterfaceInvokeSpecialTest`](https://github.com/eclipse/openj9/files/2275862/InterfaceInvokeSpecialTest.class.zip), but this one correctly throws `IllegalAccessError`, so the type test is bypassed only sometimes.

**Comment by gacholio** [comment]
@fengxue-IS Can you please take a look at this?  Suggest removing bits and pieces of the change to see what's causing the issue.

**Comment by jdmpapin** [comment]
Yes, for a non-null receiver we need `(receiver instanceof CurrentClass)`, which includes instances of subclasses.

**Comment by fengxue-IS** [comment]
I ll take a look into this, @jdmpapin thanks for providing the test class

**Comment by fengxue-IS** [comment]
Iooking through the code changes made in #2434, this behavior should be due to we are now forcing shared ConstantPool entries between `invokeSpecial` and `invokeVirtual` to be split.

The patched bytecode `JBinvokespecialspilt` in interpreter is executing the method without the access check on the receiver class.

**Comment by gacholio** [comment]
Good catch - sounds like this was already a problem in some circumstances, and just made more frequent by your change.

**Comment by gacholio** [comment]
If possible, please try and common as much of the code as you can between invokespecial and invokespecialsplit. At a glance, once _sendMethod has been fetched, it should be very similar code.
