### ISSUE TITLE
Java 11: j.l.i.MethodHandle.internalMemberName need an implementation

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2597]
```
java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
        at java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(java.base@11-internal/OpenJDKCompileStub.java:38)
        at java.lang.invoke.MethodHandle.internalMemberName(java.base@11-internal/MethodHandle.java:1168)
        at java.lang.invoke.ConstantBootstraps.getStaticFinal(java.base@11-internal/ConstantBootstraps.java:167)
```

**Comment by JasonFengJ9** [comment]
Returning `null` for `j.l.i.MethodHandle.internalMemberName()` caused NPE within `java.lang.invoke.ConstantBootstraps.getStaticFinal(java.base@11-internal/ConstantBootstraps.java:168)`.
Returning a `MemberName` object requires its APIs to be implemented such as `isFinal()` which requires further implementation of class `MemberName`. Not sure if that's the direction to go.
Another option would be to implement this new class `j.l.i.ConstantBootstraps` which is new since `Java 11`.

**Comment by DanHeidinga** [comment]
Is `java.lang.invoke.ConstantBootstraps.getStaticFinal()` the only method that requires a MemberName?

Looking for some idea of how much of MemberName we'd need to implement and how many other places require it.

**Comment by JasonFengJ9** [comment]
@DanHeidinga so far `java.lang.invoke.ConstantBootstraps.getStaticFinal()` is the only method requiring `MemberName`. The tests expect either `true` (`Final`) or `false` (not `Final`) in different scenarios.
Will investigate how to set `MemberName` flag `Final` within a `MethodHandle`.
Agreed to avoid re-implementing `j.l.i.ConstantBootstraps`.
