### ISSUE TITLE
Eclipse OpenJ9 VM: Java OutOfMemoryError encountered when more than roughly 67M of Direct Byte Buffers are allocated.

### ISSUE THREAD

**Issue by dswierc** [eclipse/openj9#2604]
Per J9 documentation (https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/xxmaxdirectmemorysize.html), we were under the impression that the amount of memory reserved for Direct Byte Buffers is dynamically expanded from a "soft" limit of 64MB. We are not finding this in practice. When our application has allocated roughly 67M of direct memory we see the following exception:

java.lang.OutOfMemoryError: Direct buffer memory
at java.nio.Bits.reserveMemory(Bits.java:703) ~[?:1.8.0_181]
at java.nio.DirectByteBuffer.(DirectByteBuffer.java:126) ~[?:1.8.0_181]
at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_181]

We are using the option -XX:MaxDirectMemorySize=512m to work around the issue.

Note that we encountered this while migrating from a stable application that has been using a HotSpot VM. This issue does not occur when using a HotSpot VM. We have encountered this using recent builds for Windows (64 and 32 bit) as well as Linux x64.

I can also recreate this issue using a very simple test program which simply allocates direct byte buffers:

    byte[] byteData = new byte[1024];
    Arrays.fill(byteData,(byte)1);
    ByteBuffer[] bbuffs = new ByteBuffer[70000];
    for (int i=0;i<70000;i++)
    {
        System.out.println("direct mem allocation: " + i * 1024);
        bbuffs[i] = ByteBuffer.allocateDirect(1024);
        bbuffs[i].put(byteData);
    }

**Comment by fjeremic** [comment]
@pdbain-ibm FYI, not sure if you are the best person or not to take a look at this.

**Comment by pdbain-ibm** [comment]
I will take a look.

**Comment by pdbain-ibm** [comment]
Hmmm.  This works with IBM Java 7 Java 8, but not OpenJ9 Java 8.

**Comment by pdbain-ibm** [comment]
IBM (J9) uses a different implementation of `java.nio.Bits.reserveMemory()` from OpenJDK and OpenJ9. The J9 implementation will allocate arbitrarily large amounts of memory, per the documentation above. OpenJ9 and OpenJDK use the same implementation which has hard limits.  OpenJ9's limit is 3749183488 bytes, while OpenJ9's is 67108864.  I am looking to see where these are set...

**Comment by machonerddude** [comment]
That does not seem to be consistent with what I am seeing.  I am running with the option -Xmx1g which sets my max heap size to 1g.  I am seeing the OutOfMemory error at roughly 67M direct buffer memory utilization.

**Comment by pdbain-ibm** [comment]
Clarification: the **OpenJDK** VM is setting the maximum direct buffer memory, but **OpenJ9** doesn't (yet).  I'm working on it now...

**Comment by pdbain-ibm** [comment]
@SueChaplain FYI.  We will need to update the Knowledge Center documentation to draw attention to the distinction between classic J9 and OpenJ9.

**Comment by pdbain-ibm** [comment]
Pull request opened: https://github.com/eclipse/openj9/pull/2629

**Comment by DanHeidinga** [comment]
@pdbain-ibm Please open an issue for the doc update at the https://github.com/eclipse/openj9-docs repo

**Comment by pdbain-ibm** [comment]
Done: https://github.com/eclipse/openj9-docs/issues/67
