### ISSUE TITLE
[0.9.0] Release notes missing

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/openj9#2617]
I was expecting to see release notes in /doc/release-notes/0.9 as it was done for 0.8. 
This currently does not exist but some marketing materials do point to it e.g. https://blog.openj9.org/2018/08/15/release-0-9-0-is-now-available/

**Comment by smlambert** [comment]
The notes, https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.9/0.9.md, are mentioned in that blog post "You can check out the 0.9.0 release plan and [0.9.0 release notes](https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.9/0.9.md) for details"...

**Comment by smlambert** [comment]
Apologies @JervenBolleman I misread your issue.  Where are you asking to have the notes linked from?

**Comment by smlambert** [comment]
Aha, a PR #1996 is still to be merged...  thanks for the heads up.

**Comment by smlambert** [comment]
I have removed the reference from the blog post until it is merged.

**Comment by pmhayward** [comment]
PR #1996 is now merged, so release notes are available at https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.9/0.9.md

**Comment by JervenBolleman** [comment]
Thank you, I think this issue can be closed then. Maybe open a process improvement issue is so that release notes are merged before the release.
