### ISSUE TITLE
VarHandles - Cache generic handleTable in VarHandleOperations subclasses

### ISSUE THREAD

**Issue by bjornvar** [eclipse/openj9#263]
Currently, the MethodHandles for `VarHandle.handleTable` are generated for each VarHandle. We benefit from some caching in MethodHandle, but we can do better than that by caching the entire generic table per type. This will eliminate the MethodHandle lookups from the VarHandle construction.

**High-level design**
Split the handle table generation into two steps:
1) Generate generic table
Produces the cached table, and it's only called by the VarHandleOperations subclass's static initializer (e.g. `StaticFieldVarHandleOperations.OpInt.<clinit>`).
2) Specialize table
Clones the generic MethodHandles with new specialized MethodTypes. Called on every VarHandle generation.

**Comment by DanHeidinga** [comment]
@tajila Is this something you're tracking as part of the VarHandles work?

**Comment by tajila** [comment]
@DanHeidinga Taking a look at this

**Comment by DanHeidinga** [comment]
Closing as this is ancient and the code has evolved in different ways
