### ISSUE TITLE
Unexpected JVM behaviour (ASSERTION FAILED ** at MemorySubSpace)

### ISSUE THREAD

**Issue by stmaute** [eclipse/openj9#2641]
Hi OpenJ9 guys.
I currently encountered an unexpected behaviour of your JVM. I am using openjdk8-openj9 with the new released version [jdk8u181-b13_openj9-0.9.0](https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/tag/jdk8u181-b13_openj9-0.9.0) (from AdoptOpenJDK). 

The dockerized application running inside the JVM stopped working and the following lines were logged (Docker container is stopped afterwards):

> 08:35:36.117 0x10ec400    j9mm.141    *   ** ASSERTION FAILED ** at MemorySubSpace.cpp:1983: ((false))
> JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/08/17 08:35:36 - please wait.
> JVMDUMP032I JVM requested System dump using '//core.20180817.083536.8.0001.dmp' in response to an event
> JVMDUMP010I System dump written to //core.20180817.083536.8.0001.dmp
> JVMDUMP032I JVM requested Java dump using '//javacore.20180817.083536.8.0002.txt' in response to an event
> JVMDUMP010I Java dump written to //javacore.20180817.083536.8.0002.txt
> JVMDUMP032I JVM requested Snap dump using '//Snap.20180817.083536.8.0003.trc' in response to an event
> JVMDUMP010I Snap dump written to //Snap.20180817.083536.8.0003.trc
> JVMDUMP013I Processed dump event "traceassert", detail "".

[javacore.20180817.083536.8.0002.txt](https://github.com/eclipse/openj9/files/2296984/javacore.20180817.083536.8.0002.txt)

I am using the following Java Options for this application:
-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=80 -Xgcpolicy:balanced

I also have other applications which are using the same JVM but don't use the -Xgcpolicy:balanced. These applications are running without any problems.

Any ideas to solve this problem?

**Comment by pdbain-ibm** [comment]
@dmitripivkine or @amicic could you take a look?
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "VM Runtime State Listener" J9VMThread:0x00000000010EC400, omrthread_t:0x00007F7DB06F0FF0, java/lang/Thread:0x00000000CB5CEA40, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0xC, isDaemon:true)
3XMTHREADINFO1            (native thread ID:0x15, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMTHREADINFO2            (native stack address range from:0x00007F7DBCA9A000, to:0x00007F7DBCADA000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.341498817 secs, current category="Resource-Monitor"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           No Java callstack associated with this thread
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007F7DCE2A0002 [libj9prt29.so+0x3a002])
4XENATIVESTACK               (0x00007F7DCE28580D [libj9prt29.so+0x1f80d])
4XENATIVESTACK               (0x00007F7DCE2A007C [libj9prt29.so+0x3a07c])
4XENATIVESTACK               (0x00007F7DCE2A0186 [libj9prt29.so+0x3a186])
4XENATIVESTACK               (0x00007F7DCE28580D [libj9prt29.so+0x1f80d])
4XENATIVESTACK               (0x00007F7DCE29FED1 [libj9prt29.so+0x39ed1])
4XENATIVESTACK               (0x00007F7DCE29C07C [libj9prt29.so+0x3607c])
4XENATIVESTACK               (0x00007F7DCE29D234 [libj9prt29.so+0x37234])
4XENATIVESTACK               (0x00007F7DCE28580D [libj9prt29.so+0x1f80d])
4XENATIVESTACK               (0x00007F7DCDC245D7 [libj9dmp29.so+0x185d7])
4XENATIVESTACK               (0x00007F7DCDC249AD [libj9dmp29.so+0x189ad])
4XENATIVESTACK               (0x00007F7DCE28580D [libj9prt29.so+0x1f80d])
4XENATIVESTACK               (0x00007F7DCDC213AF [libj9dmp29.so+0x153af])
4XENATIVESTACK               (0x00007F7DCDC1CF3D [libj9dmp29.so+0x10f3d])
4XENATIVESTACK               (0x00007F7DCE28580D [libj9prt29.so+0x1f80d])
4XENATIVESTACK               (0x00007F7DCDC1DD17 [libj9dmp29.so+0x11d17])
4XENATIVESTACK               (0x00007F7DCDC26A19 [libj9dmp29.so+0x1aa19])
4XENATIVESTACK               (0x00007F7DCDC10A8D [libj9dmp29.so+0x4a8d])
4XENATIVESTACK               (0x00007F7DCDC100B5 [libj9dmp29.so+0x40b5])
4XENATIVESTACK               (0x00007F7DCE28580D [libj9prt29.so+0x1f80d])
4XENATIVESTACK               (0x00007F7DCDC138CA [libj9dmp29.so+0x78ca])
4XENATIVESTACK               (0x00007F7DCDC13A24 [libj9dmp29.so+0x7a24])
4XENATIVESTACK               (0x00007F7DCDC285B3 [libj9dmp29.so+0x1c5b3])
4XENATIVESTACK               (0x00007F7DCD9F9820 [libj9trc29.so+0x1d820])
4XENATIVESTACK               (0x00007F7DCD9EDAFD [libj9trc29.so+0x11afd])
4XENATIVESTACK               (0x00007F7DCD9E5333 [libj9trc29.so+0x9333])
4XENATIVESTACK               (0x00007F7DCC899662 [libj9gc29.so+0x12a662])
4XENATIVESTACK               (0x00007F7DCC8982A7 [libj9gc29.so+0x1292a7])
4XENATIVESTACK               (0x00007F7DCC89A667 [libj9gc29.so+0x12b667])
4XENATIVESTACK               (0x00007F7DCC921E08 [libj9gc29.so+0x1b2e08])
```

**Comment by ashu-mehra** [comment]
Crash in GC with current thread as `VM Runtime State Listener` indicates we are trying to do something (probably doing GC or de-committing free pages) during idle phase.
I believe we don't support this feature for `balanced` gc policy. It is only supported for `gencon`.
I guess we are missing check for gc policy when turning on idle tuning.

**Comment by ashu-mehra** [comment]
This should be a problem only if docker image is used since it enables idle tuning by default.

**Comment by stmaute** [comment]
I had a look in the logs and saw that these two parameters were set:
-XX:+IdleTuningCompactOnIdle, -XX:+IdleTuningGcOnIdle

Will disabling these parameter fix the problem?

**Comment by ashu-mehra** [comment]
@stmaute yes, those two options are for enabling idle tuning. So disabling them should also work.

**Comment by stmaute** [comment]
@ashu-mehra I will test it with both parameters disabled (-XX:-IdleTuningCompactOnIdle and -XX:-IdleTuningGcOnIdle).
Thx for the quick help!

**Comment by stmaute** [comment]
Disabling IdleTuning solved the problem for me.
