### ISSUE TITLE
FindStore.FindClassfile java.lang.ClassNotFoundException: jnurlcldr.shared.findstore.N_Dummy

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2653]
Test-sanity.functional-JDK10-win_x86-64_cmprssptrs

Testing: FindStore.FindClassfile
Test start time: 2018/08/17 14:58:53 Greenwich Mean Time
Running command: "C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK10-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin\\java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon    -Xshareclasses:nonpersistent,controlDir=.,name=FindStore,noTimestampChecks -cp .\FindStore\M_Classes;.\FindStore\N_Classes;.\FindStore\O_Classes;.\FindStore\P_Classes;.\FindStore\Nothing.jar jnurlcldr.shared.findstore.M_Main
Time spent starting: 4 milliseconds
Time spent executing: 209 milliseconds
Test result: FAILED
 [OUT] CACHED M
 [ERR] Exception in thread "main" java.lang.NoClassDefFoundError: jnurlcldr.shared.findstore.N_Dummy
 [ERR] 	at jnurlcldr.shared.findstore.M_Main$Data.getInt(M_Main.java:31)
 [ERR] 	at jnurlcldr.shared.findstore.M_Main.main(M_Main.java:36)
 [ERR] Caused by: java.lang.ClassNotFoundException: jnurlcldr.shared.findstore.N_Dummy
 [ERR] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@10.0.2-internal/BuiltinClassLoader.java:753)
 [ERR] 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@10.0.2-internal/ClassLoaders.java:190)
 [ERR] 	at java.lang.ClassLoader.loadClass(java.base@10.0.2-internal/ClassLoader.java:1032)
 [ERR] 	... 2 more
>> Success condition was not found: [Output match: Result=3]
>> Failure condition was not found: [Output match: LOCAL]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was found: [Output match: Exception:]
>> Failure condition was found: [Output match: Error:]

**Comment by JasonFengJ9** [comment]
Test-sanity.functional-JDK8-win_x86-64_cmprssptrs

Testing: FindStore.FindClassfile
Test start time: 2018/08/16 20:04:58 Greenwich Mean Time
Running command: C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK8-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin\\..\\..\jre\bin\java.exe  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon    -Xshareclasses:persistent,controlDir=.,name=FindStore,noTimestampChecks -cp .\FindStore\M_Classes;.\FindStore\N_Classes;.\FindStore\O_Classes;.\FindStore\P_Classes;.\FindStore\Nothing.jar jnurlcldr.shared.findstore.M_Main
Time spent starting: 5 milliseconds
Time spent executing: 159 milliseconds
Test result: FAILED
 [ERR] Error: Could not find or load main class jnurlcldr.shared.findstore.M_Main
>> Success condition was not found: [Output match: Result=3]
>> Failure condition was not found: [Output match: LOCAL]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]
>> Failure condition was found: [Output match: Error:]

**Comment by hangshao0** [comment]
I will investigate.

**Comment by hangshao0** [comment]
I re-ran these tests on Java 8 and Java 10, it passed. Might be a machine issue. I will try re-producing on the failed machines.

**Comment by hangshao0** [comment]
These tests passed on previously failed machines. I am closing this issue.

**Comment by JasonFengJ9** [comment]
See it again at `Test-sanity.functional-JDK10-win_x86-64_cmprssptrs/100`
Testing: FindStore.FindClassfile
Test start time: 2018/08/22 21:37:09 Greenwich Mean Time
Running command: "C:/Users/j9build/jenkins/workspace/Test-sanity.functional-JDK10-win_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin\\java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon    -Xshareclasses:nonpersistent,controlDir=.,name=FindStore,noTimestampChecks -cp .\FindStore\M_Classes;.\FindStore\N_Classes;.\FindStore\O_Classes;.\FindStore\P_Classes;.\FindStore\Nothing.jar jnurlcldr.shared.findstore.M_Main
Time spent starting: 4 milliseconds
Time spent executing: 223 milliseconds
Test result: FAILED
 [OUT] CACHED M
 [ERR] Exception in thread "main" java.lang.NoClassDefFoundError: jnurlcldr.shared.findstore.N_Dummy
 [ERR] 	at jnurlcldr.shared.findstore.M_Main$Data.getInt(M_Main.java:31)
 [ERR] 	at jnurlcldr.shared.findstore.M_Main.main(M_Main.java:36)
 [ERR] Caused by: java.lang.ClassNotFoundException: jnurlcldr.shared.findstore.N_Dummy
 [ERR] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@10.0.2-internal/BuiltinClassLoader.java:753)
 [ERR] 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@10.0.2-internal/ClassLoaders.java:190)
 [ERR] 	at java.lang.ClassLoader.loadClass(java.base@10.0.2-internal/ClassLoader.java:1032)
 [ERR] 	... 2 more

**Comment by hangshao0** [comment]
There is another failure on Java 8. Both the Java 8 failure and the failure in the above comment (Java 10) are running on the same machine. I will re-try on that machine.

**Comment by hangshao0** [comment]
It is a test/timing issue. I will fix this.
