### ISSUE TITLE
[Nestmates] Handle private invoke for jitted unresolved invokevirtual/interface

### ISSUE THREAD

**Issue by jdmpapin** [eclipse/openj9#2673]
With nestmates, when the JIT compiler encounters an `invokevirtual` or `invokeinterface` bytecode instruction with an unresolved constant pool entry, it's not possible to tell whether or not it's calling a private method. As such, the code generated for unresolved virtual and interface calls must deal with the possibility that after run-time resolution, the method turns out to be private.

These calls go through PicBuilder to resolve the first time they run, and on success, the vtable offset or itable offset (resp.) is known, and PicBuilder patches the call site to avoid further resolution. Private methods, however, have neither an itable offset nor a vtable offset, so the usual paths won't work.

The plan is for `jitResolveVirtualMethod` and `jitResolveInterfaceMethod` to return a `J9Method*` to be directly dispatched instead of a vtable/itable offset in this case. When PicBuilder gets a direct method from resolution (distinguished by a tag bit), it will remember the method, leave the originating call instruction in place, and carry out the direct dispatch itself.

-------------------------------

`invokevirtual` emitted code:
```
// Start of the emitted sequence for the unresolved call
call PicBuilderVResolve   <--- (*)

...

// VPIC Data
cpAddress
cpIndex
directMethod              <--- new! J9Method*, initially null
j2iVirtualThunk           <--- new! code address
```

`invokevirtual` PicBuilder resolve pseudocode:
```
    save registers
    find picData
    if (picData->directMethod != NULL) goto directDispatch
    vftOffset = jitResolveVirtualMethod(picData)
    if (vftOffset & J9_VTABLE_INDEX_DIRECT_METHOD_FLAG) {
        picData->directMethod = vftOffset & ~J9_VTABLE_INDEX_DIRECT_METHOD_FLAG
        goto directDispatch
    }

    non-direct case - patch (*) and continue as usual

directDispatch:
    // NOTE: (*) will not be patched
    adjust the return address
    if (picData->directMethod->extra & J9TR_MethodNotCompiledBit) {
        // interpreted
        privLinkageVftOffsReg = picData->directMethod | J9_VTABLE_INDEX_DIRECT_METHOD_FLAG
        jumpTarget = picData->j2iVirtualThunk
    } else {
        // compiled
        jumpTarget = picData->directMethod->extra        // interpreter entry point
        jumpTarget += *(uint32_t*)(jumpTarget - 4) >> 16 // add offset to JIT entry point
    }
    restore preserved and argument-passing registers
    jump to jumpTarget
```

----------------------

Unresolved interface calls are similar, but they have to do a type check.

`invokeinterface` emitted code:
```
// Start of the emitted sequence for the unresolved call
call PicBuilderIResolve    <--- (*)

...

// IPIC Data
cpAddress
cpIndex
interfaceClass
itableOffset              <--- can also now be a direct J9Method* | J9_ITABLE_OFFSET_DIRECT
j2iVirtualThunk           <--- new! code address
```

`invokeinterface` PicBuilder resolve pseudocode:
```
    save registers
    find picData

    // Checking both here defensively since another thread could be resolving,
    // and won't write these atomically. Alternately we could ensure that the
    // resolve helper writes in a consistent order, with the appropriate fence
    if (!(picData->itableOffset & J9_ITABLE_OFFSET_DIRECT)) goto callResolve
    if (picData->interfaceClass != NULL) goto typeCheckAndDirectDispatch

callResolve:
    jitResolveInterfaceMethod(picData)
    if (picData->itableOffset & J9_ITABLE_OFFSET_DIRECT) goto typeCheckAndDirectDispatch

    non-direct case - patch (*) and continue as usual

typeCheckAndDirectDispatch:
    // NOTE: (*) will not be patched
    if (!jitInstanceOf(receiver, picData->interfaceClass)) {
        // This will fail to find a matching itable and throw ICCE as required,
        // without looking at the supposed itable offset
        jitLookupInterfaceMethod(picData)
    }

    directMethod = picData->itableOffset & ~J9_ITABLE_OFFSET_DIRECT
    dispatch directly just as in invokevirtual above
    // NOTE: still use J9_VTABLE_INDEX_DIRECT_METHOD_FLAG for interpreted methods
```

-------------------------------

The VM is currently also making changes w.r.t. `invokeinterface` instructions that call methods of `Object`.

When such a method is non-final, the VM will populate `itableOffset` instead with a VFT offset tagged with `J9_ITABLE_OFFSET_VIRTUAL`. PicBuilder does not need any changes for this case. We will naturally pass the value into `jitLookupInterfaceMethod`, which will do the type check, and if it passes, produce the correct VFT offset.

Final methods of `Object`, however, are not in the VFT, so they also require direct dispatch. Currently, attempts to call final methods of `Object` through unresolved `invokeinterface` would break in PicBuilder, but the JIT compiler fails compilation if it sees an such an `invokeinterface`. With the coming changes, `jitResolveInterfaceMethod` will hand PicBuilder a direct method, same as it does for private methods. Once PicBuilder is modified to support direct (private) invoke, final methods of `Object` will work as well, and we should be able to stop failing compilation for them.

**Comment by DanHeidinga** [comment]
@gita-omr As a committer, you're able to add issues to projects.  I'll do this one but please add them yourself in the future.

**Comment by gita-omr** [comment]
@DanHeidinga that's what I thought too, but clicking on 'Projects' gave me empty menu. Probably some other way?

**Comment by zl-wang** [comment]
Maybe I am wrong (I only read this very briefly this morning), but the InvokeVirtual handling looks very sub-optimal.

It appeared, if it were resolved to with J9_VTABLE_INDEX_DIRECT_METHOD_FLAG,  that call site would not be polymorphic anymore (similar to a static method).  It can be patched into like a static call (for better performance).  CodeGen needs to prepare for a potential trampoline reservation though.  For GCMap reason, the final patch should be on the original call instruction instead of the branch to resolve.

It is unclear to me from the description, if InvokeInterface were resolved to be not iTableOffset (i.e.  J9Method * or VFT-offset), that call site could still be polymorphic (I guessed it could with different types of receivers).  It is reasonable to handle that way.

**Comment by zl-wang** [comment]
P.S.
For InvokeInterface, if it is resolved to be J9Method *,   it is single target?   i.e.  not polymorphic anymore? I guessed we could do better in this case.

**Comment by jdmpapin** [comment]
Yes, all of the `DIRECT` calls are monomorphic. However, any such calls that are important will generally be resolved by the time we compile, and for those we will generate a direct call without involving PicBuilder.

The unresolved case has intentionally suboptimal performance in order to reduce complexity. There is room for future improvement if/when this case becomes important.

**Comment by zl-wang** [comment]
Watch out for InvokeInterface then.  It is always unresolved from JIT perspective.

**Comment by zl-wang** [comment]
I guessed you meant ILGen can turn InvokeInterface into InvokeSpecial or InvokeStatic in the normal cases for this.

**Comment by jdmpapin** [comment]
Right, we detect when the constant pool entry is resolved to anything other than a "normal" interface method, and generate IL for either a direct call (as though for `invokespecial`) or a virtual call (as though for `invokevirtual`). The logic is in #2648

**Comment by irinarada** [comment]
@jdmpapin - do we have an ETA for this one?

**Comment by irinarada** [comment]
@jdmpapin - is this finished?

**Comment by jdmpapin** [comment]
This is now done! The following have all been merged.

General implementation on each platform, without handling for AOT:
- x86: #2851
- power: #2809
- z: #2665

Relocation to allow this to work in AOT-compiled callers:
- common: #2874
- x86: #2875
- power: #2882
- z: #2892
