### ISSUE TITLE
JDK10: LambdaForm Substitute Lacks the Kind Enum

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#268]
Several classes in JDK10, including java.lang.invoke.MethodHandleImpl, require an enum called "Kind" which is located in the LambdaForm class (same package). 

The OpenJ9 substitutes its own copy of the LambdaForm at build time. This substitute class does not have the Kind enum.

We need to solve this if we are to build JDK 18.3 with OpenJ9. 

Can we remove the need for this enum, or add this enum to the LambdaForm class in 18.3 ("[IF Java18.3]" ?) The latter sounds like a cleaner solution, and it also ensures our functionality stays consistent with the original LambdaForm.

**Comment by DanHeidinga** [comment]
```
or add this enum to the LambdaForm class in 18.3 ("[IF Java18.3]" ?) The latter sounds like a cleaner solution, and it also ensures our functionality stays consistent with the original LambdaForm.
```
+1 to this approach.

We want to introduce minimize changes to the OpenJDK code as that makes it easier to track the upstream OpenJDK project.

**Comment by Bluevisitor** [comment]
Hmm, it seems the LambdaForm class also lacks other bits and pieces, like the constructor LambdaForm(int,Name[],int,boolean,MethodHandle,Kind).

How badly do we need this override class for OpenJ9?

**Comment by Bluevisitor** [comment]
I'm told we do need this class, and we do need those methods replaced by stubs, mainly so that any use of them doesn't cause unintended consequences in the OpenJ9 (which supports lambdas, but doesn't use this class, and might not react well to its use).

I plan to update this issue with a list of the api elements we need to add to the j9jcl substitute.

**Comment by DanHeidinga** [comment]
When creating methods that are compile stubs for OpenJDK, there's an existing pattern to use - with a well named class.  @JasonFengJ9 do you have a pointer to an example of this?

**Comment by JasonFengJ9** [comment]
@DanHeidinga, following code snippet is the pattern to add a compile stub:
````
	LambdaForm(String str, int num1, Name[] names, int num2) {
		OpenJDKCompileStub.OpenJDKCompileStubThrowError();
	}
````

**Comment by JasonFengJ9** [comment]
In addition, `java.lang.invoke.LambdaForm$NamedFunction.<init>` requires an implementation as per following stacktrace discovered earlier (reported in an internal PR before going open) when running `Class.forName("java.lang.invoke.MethodHandleImpl");`
````
Exception in thread "main" java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
        at java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(java.base@9-internal/OpenJDKCompileStub.java:35)
        at java.lang.invoke.LambdaForm$NamedFunction.<init>(java.base@9-internal/LambdaForm.java:52)
        at java.lang.invoke.MethodHandleImpl.<clinit>(java.base@9-internal/MethodHandleImpl.java:1687)
        at java.lang.Class.forNameImpl(java.base@9-internal/Native Method)
        at java.lang.Class.forName(java.base@9-internal/Class.java:295)
````

**Comment by Bluevisitor** [comment]
Summary so far:

To compile OpenJDK with OpenJ9, with no errors from this class, the following additions should be made to the j9jcl LambdaForm stub class:

- [ ] The new LambdaForm constructors.
- [ ] The LambdaForm enum called "Kind".
- [ ] The new constructors in the LambdaForm inner-class called "NamedFunction".

Also, Jason recommends a "java.lang.invoke.LambdaForm$NamedFunction.<init>" implementation. See the above comment for details.

- [ ] "java.lang.invoke.LambdaForm$NamedFunction.<init>" implementation

**Comment by JasonFengJ9** [comment]
@Bluevisitor `java.lang.invoke.LambdaForm$NamedFunction` implementation might not be required because this is a runtime exception. The testcase was not valid for OpenJ9.
Pls work on those compilation errors instead.

**Comment by adamfarley** [comment]
Here's a pull request for everything except the contents of the Kind enum. 

https://github.com/eclipse/openj9/pull/294

**Comment by JasonFengJ9** [comment]
Chatted with Adam about this, I am going to implement `j.l.i.LambdaForm$Kind`. 
Attempting `Java 18.3` build against `openj9-openjdk-jdk18.3` such that I can verify the change to `j.l.i.LambdaForm$Kind` can fix the compilation error.

**Comment by adamfarley** [comment]
Any luck Jason?
