### ISSUE TITLE
Class.getMethods test is missing

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#2688]
Class.getMethods are not invoked by sanity tests. org.openj9.test.reflect.GetMethodsTests has been implemented. Looks like just a missing line ` <class name="org.openj9.test.reflect.GetMethodsTests" /> ` in file test/functional/Java8andUp/testng.xml

**Comment by sophia-guo** [comment]
@felipepontes-research could you confirm that?  Related with https://github.com/eclipse/openj9/pull/1792

**Comment by felipepontes-research** [comment]
@sophia-guo yes. It is missing.

**Comment by sophia-guo** [comment]
Test org.openj9.test.reflect.GetMethodsTests is actually in a different testcase 
```	<test name="reflect_getMethods">
		<classes>
			<class name="org.openj9.test.reflect.GetMethodsTests" />
		</classes>
	</test>
```

Will put all reflect tests together.
