### ISSUE TITLE
An issue with threads starting when native method `Thread#startImpl` is prefixed

### ISSUE THREAD

**Issue by vootelerotov** [eclipse/openj9#269]
New threads do not seem to start when `Thread#startImpl` is prefixed and JIT is enabled.

To reproduce the issue:

1. Patch `Thread#startImpl` to have a prefix `pre_` and add a method with the original name that delegates to the native method. Both the patched class file and the code used to create it are present in the attached archive.

2. Create a simple native agent that sets the native prefix to `pre_`. Again, the code for the agent is present in the attached archive.

3. Start a simple Java program that starts a new thread and waits for it. Start the program with the agent attached and  with patched `java.base` module to contain the modified `Thread.class`:
`java -agentpath:/path/to/simple/agent.so  --patch-module java.base=/path/to/the/wrapped-class -jar test-program.jar`. The reproducing app is also present in the attached archive.

4. Verify that the thread does not actually start. Verify that it does start with `-Xint` or with `-Xjit:exclude={java/lang/Thread.pre_*}`. 

Tested this with the latest nightly:

`Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170915_6 (JIT enabled, AOT enabled)`

Also reproduced on JVM built from source and on `IBM 1.8 Service Refresh 5`
(using `-Xbootclasspath/p`). 

Attachment: [native-method-prefix-repro.zip](https://github.com/eclipse/openj9/files/1371128/native-method-prefix-repro.zip)

**Comment by DanHeidinga** [comment]
@gacholio Can you take a look at this?  The jvmti native prefix functionality isn't working in 8sr5 and OpenJ9

**Comment by gacholio** [comment]
I have identified the source of the problem - working on a fix now.
