### ISSUE TITLE
Request for root Certification Authority (CA) certificates in the JDK

### ISSUE THREAD

**Issue by keithf22** [eclipse/openj9#2696]
The OpenJ9 jdk8u181-b13\jre\lib\security\cacerts file is empty. This is causing the below exception. (Setting javax.net.ssl.trustStore system property to a valid cacerts file works around the problem.)

_java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)_

Per http://openjdk.java.net/jeps/319, this problem is fixed in OpenJDK 10. Could a valid CA cert file be pulled into the OpenJ9 project?

**Comment by pshipton** [comment]
You can get a non-empty cacerts by downloading one of the builds at https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9

**Comment by vsabella** [comment]
I've noticed on later builds this is still a problem. The CACerts file is actually a github error message:

```
<h1>There was an unexpected problem serving your request</h1>
      <p>Please try again and contact us if the problem persists including C308:CAEC:600B060:92C23BF:5C59B184 in your message</p>
      <div id="suggestions">
        <a href="https://github.com/contact">Contact Support</a> &mdash;
        <a href="https://status.github.com">GitHub Status</a> &mdash;
        <a href="https://twitter.com/githubstatus">@githubstatus</a>
      </div>
    </div>
  </body>

```

**Comment by pshipton** [comment]
@vsabella this should be reported to the AdoptOpenJDK project at https://github.com/AdoptOpenJDK/openjdk-build/issues, although I see https://github.com/AdoptOpenJDK/openjdk-build/issues/895 already exists and there is a replacement build you can download. 

I'm going to close this issue.
