### ISSUE TITLE
Test-extended.functional-JDK11-linux_x86-64_cmprssptrs java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2705]
`===============================================`
Running test ContendedFieldsTests_90_0 ...
`=====================================================`

FAILED CONFIGURATION: @BeforeMethod setUp(public void org.openj9.test.contendedfields.ContendedFieldsTests.testBigContendedClass())
java.lang.UnsatisfiedLinkError: org/openj9/test/contendedfields/FieldUtilities.getObjectAlignmentInBytes()I

`===============================================`
GeneralTest suite
Total tests run: 21, Failures: 0, Skips: 21
Configuration Failures: 1, Skips: 41
`===============================================`

ContendedFieldsTests_90_0_FAILED

There are various test failures due to similar java.lang.UnsatisfiedLinkError.

**Comment by theresa-m** [comment]
looking at this.

**Comment by theresa-m** [comment]
failure related to https://github.com/eclipse/openj9/issues/2761

**Comment by theresa-m** [comment]
this test is passing now in the daily builds. this issue can be closed
