### ISSUE TITLE
Test-extended.functional-JDK11-linux_x86-64_cmprssptrs test natives not found

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#2706]
FAILED CONFIGURATION: @BeforeMethod setUp
java.lang.AssertionError: j9ben (Not found in java.library.path)
library path = /home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/lib/compressedrefs:/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/lib:/usr/lib64:/usr/lib

`===============================================`
GeneralTest suite
Total tests run: 3, Failures: 0, Skips: 3
Configuration Failures: 1, Skips: 5
`===============================================`

memoryCategories_0_FAILED

Various test failed with similar libraries `Not found in java.library.path`.

`===============================================`
Running test TestSoftMxCallBackOOM_1 ...
`===============================================`
TestSoftMxCallBackOOM_1 Start Time: Thu Aug 23 16:49:26 2018 Epoch Time (ms): 1535042966638
test with Mode601
JVMJ9TI001E Agent library softmxtest could not be opened (libsoftmxtest.so: cannot open shared object file: No such file or directory)
JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed

TestSoftMxCallBackOOM_1_FAILED 

FAILED: testSoftmxHasEffects
java.lang.AssertionError: No natives for j9vm.test.softmx.TestNatives

Output from test:
 [ERR] JVMJ9TI001E Agent library jvmtitest could not be opened (libjvmtitest.so: cannot open shared object file: No such file or directory)
 [ERR] JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed
>> Success condition was not found: [Return code: 0]

 [ERR] JVMJ9TI001E Agent library vmruntimestateagent29 could not be opened (libvmruntimestateagent29.so: cannot open shared object file: No such file or directory)

Output from test:
 [OUT] Begining testJvmtiCountLoadedClasses
 [ERR] java.lang.UnsatisfiedLinkError: j9lazyClassLoad (Not found in java.library.path)
 [ERR] 	at java.lang.ClassLoader.loadLibraryWithPath(java.base@11-internal/ClassLoader.java:1678)
 [ERR] 	at java.lang.ClassLoader.loadLibraryWithClassLoader(java.base@11-internal/ClassLoader.java:1648)
 [ERR] 	at java.lang.System.loadLibrary(java.base@11-internal/System.java:559)
 [ERR] 	at j9vm.test.classloader.LazyClassLoaderInitTest.<clinit>(LazyClassLoaderInitTest.java:40)
 [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: j9vm/test/classloader/LazyClassLoaderInitTest.jvmtiCountLoadedClasses(Ljava/lang/ClassLoader;)I
 [ERR] 	at j9vm.test.classloader.LazyClassLoaderInitTest.testJvmtiCountLoadedClasses(LazyClassLoaderInitTest.java:144)
 [ERR] 	at j9vm.test.classloader.LazyClassLoaderInitTest.main(LazyClassLoaderInitTest.java:87)
>> Success condition was not found: [Output match: .*Test PASSED*]
>> Failure condition was not found: [Output match: .*Test FAILED*]

It appears the test natives are not built properly in JDK11.

**Comment by pshipton** [comment]
This is resolved now.
