### ISSUE TITLE
Replace strcat with sprintf in runtime/jcl/common/jclcinit.c

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#272]

**Comment by andy5995** [comment]
I'll take this.

**Comment by andy5995** [comment]
I won't be working on this.

**Comment by fengxue-IS** [comment]
I'll take a look, @jdekonin is there a particular reason for the change?

**Comment by jdekonin** [comment]
I don't recall the details now, and I don't see any hints in #256.  @keithc-ca, do you recall the reason?

**Comment by andy5995** [comment]
Whoever works on this may want to review the changes I made in https://github.com/eclipse/openj9/pull/408/files

**Comment by keithc-ca** [comment]
Whoever works on this must be able to claim it is their own work (part of what you will agree to as part of the eclipse CLA) and so starting with the work offered in #408 will not qualify (unless @andy5995 is that person and changes his mind about agreeing to the CLA).
