### ISSUE TITLE
Integrating the code for out-of-process JIT compilation (aka JITaaS)

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#2726]
We have a prototype implementation for out-of-process JIT compilation in OpenJ9 (codename JITaaS).
Current code is stable enough to successfully run some enterprise workloads (e.g. AcmeAir, DayTrader) 
and to pass all sanity tests and most Java SVT tests; therefore, we think the code is ready
to be brought into the OpenJ9 project.
However, in order to avoid impacting the release quality it's better to avoid merging the JITaaS code into master for the time being. Instead, we propose to manage it as a separate project by delivering code to a separate branch. Possible names for the new branch include: JITaaS, OOPJIT, OOPJITComp. Additional suggestions are welcome.

We plan to periodically (maybe weekly) do a rebase operation to keep the code in the new branch up-to-date. Since there will be no separate branch for omr, someone trying to build JITaaS may encounter problems when the latest omr code is not compatible with openj9 code from the JITaaS branch. A simple interim solution could be to provide a text file specifying a blessed omr commit (this would change with every rebase operation), but this is not amenable to automated building triggered by pull requests. Maybe a tag in openj9-omr is a better approach. We are open to advice/suggestions in this area.

Automated builds: the machines on which the JITaaS build happens need to have protobuf 3.5.1 and openssl installed. We have Dockerfiles that create a suitable build environment, but I don't know how these can be used for PR builds.

Attn: @DanHeidinga @mstoodle @AdamBrousseau @smlambert   for comments/suggestions.

**Comment by mleipe** [comment]
@AdamBrousseau @jdekonin there may be build work here.

**Comment by smlambert** [comment]
From test perspective, a couple of mechanisms to test using Dockerfiles.  

Approach 1) 
One pattern we could follow is that used by the external tests that run at AdoptOpenJDK.  In this case, we would create a sub-directory in https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/thirdparty_containers called jitaas (or some such name), and follow the instructions: https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/thirdparty_containers#how-to-add-new-tests  These tests would be run as part of the "external" make target, but can be run directly with their test name (so as not to pick up all of the other application tests in the thirdparty_containers directory).  We can easily run these as nightly builds at openj9.  We need to have Docker installed on some openj9 machines, labeled sw.tool.docker.  

More work needed for PR builds, if you want them as part of PR builds, to incorporate in a PR build would require:
- do a similar step as we need to do with system tests to include them in openj9 PR builds (where we want to run sanity.system, instead we run either sanity.external, or the jitaas test target name directly).  

Approach 2) 
Another is the (not yet available) pre-built Docker image / swarm work that @AdamBrousseau is working on.  But I do not know how far out this is from being ready to deploy.  One would still need to create test cases (in playlist.xml files somewhere).

**Comment by mstoodle** [comment]
fyi @pshipton as well .

**Comment by harryyu1994** [comment]
@smlambert Thanks for the suggestions, I'm going to give Approach 1 a try.

**Comment by smlambert** [comment]
@harryyu1994 - sounds good, if you have questions, you can ask @Mesbah-Alam for assistance.

**Comment by AdamBrousseau** [comment]
> successfully run ... AcmeAir, DayTrader ... sanity tests and most Java SVT

Merge it!!! :)

I think I'm fine with having a separate branch in OpenJ9. It is preferable to merge into master and maybe use a configure option to enable it but I assume it isn't that simple from your side. Our builds are flexible enough we could setup a schedule to run with your branch. The PR builds should already work if the JITaaS PRs are pointed at the right branch.

> rebase operation to keep the code in the new branch up-to-date

Easy to automate on any schedule. Problems will arise when you have merge conflicts. I assume you mean "merge" instead of rebase as the latter would require rewriting the branch history on each update.

> text file specifying a blessed omr commit

Might be best to create a similarly named branch in the openj9-omr repo and point it at the last known "good" commit.

> protobuf 3.5.1 and openssl installed.

I believe many of the build machines already have openssl. We should add the other package to the Adopt playbooks and install it on the machines. I prefer this to docker containers as that process isn't quite ironed out yet. Similarly if you follow the docker path for test, we don't have docker installed on OpenJ9 machines (yet) so you would be limiting yourself to testing at Adopt. You are also limiting yourself to Docker supported platforms.

**Comment by harryyu1994** [comment]
For Approach 1 (adding jitaas to external tests that run at AdoptOpenJDK), I've created a PR for it ( https://github.com/AdoptOpenJDK/openjdk-tests/pull/534) and left a few questions there. @smlambert @Mesbah-Alam

**Comment by pshipton** [comment]
Eclipse CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17554

**Comment by smlambert** [comment]
@harryyu1994 - Perhaps you can take a look, I ran from your openjdk-tests/jitaas branch in an internal Grinder job (build number 300) and hit a build failure:
17:34:39      [exec] Step 18/31 : COPY ./dockerfile/key /root/.ssh/
17:34:39      [exec] COPY failed: stat /var/lib/docker/tmp/docker-builder001549607/dockerfile/key: no such file or directory

**Comment by harryyu1994** [comment]
Ah I will get the dockerfile fixed

**Comment by DanHeidinga** [comment]
I've created a "JIT as a Service" project to help track the jitaas work: https://github.com/eclipse/openj9/projects/5

**Comment by mstoodle** [comment]
Thanks @DanHeidinga . Good idea!

**Comment by mpirvu** [comment]
Closing this issue as the initial contribution was done.
