### ISSUE TITLE
Remove use of `aspp` executable in build processes for AIX

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#273]
In the build process for AIX an `aspp` executable is used.  This `aspp` executable does not seem to be a generally available executable. As such OpenJ9 will not be able to be built on AIX by people that do not been provided this `aspp` executable. In order to make OpenJ9 able to be built on AIX the `aspp` executable needs to be removed and alternative generally available build process included.

**Comment by pshipton** [comment]
It appears aspp is only used to on JIT code, including one omr file.

tr.source/trj9/p/runtime/J9PPCArrayCopy.spp
tr.source/trj9/p/runtime/J9PPCArrayCmp.spp
tr.source/trj9/p/runtime/J9PPCArrayTranslate.spp
tr.source/trj9/p/runtime/J9PPCEncodeUTF16.spp
tr.source/trj9/p/runtime/J9PPCCompressString.spp
tr.source/trj9/p/runtime/J9PPCCRC32.spp
tr.source/trj9/p/runtime/Math.spp
tr.source/trj9/p/runtime/PicBuilder.spp
tr.source/trj9/p/runtime/Recompilation.spp
tr.source/trj9/p/runtime/ebb.spp
tr.source/trj9/p/runtime/J9PPCSHA.spp (IBM internal)
tr.source/trj9/p/runtime/J9PPCCrypto.spp (IBM internal)
tr.source/trj9/p/runtime/J9PPCEC.spp (IBM internal)
tr.source/../omr/compiler/p/runtime/VirtualGuardRuntime.spp

**Comment by zl-wang** [comment]
aspp stood for Assembly Pre-Processor (as for cpp).  it was useful in the past that it inserted debugging pseudo ops e.g. line number etc. it is not that useful anymore nowadays.  we should/could get rid of it.

**Comment by groeges** [comment]
This is high priority as without removing `aspp` from the AIX build process we cannot make OpenJDK with OpenJ9 available on the AIX  platform (and it cannot be built on AdoptOpenJDK).
@pshipton @zl-wang Please can we get this looked into as soon as possible.

**Comment by groeges** [comment]
We have had to remove the availability of the binaries from AdoptOpenJDK due to this. 
We would like to get this resolved as soon as possible so we can get the binaries back onto AdoptOpenJDK.

**Comment by groeges** [comment]
@pshipton @zl-wang Doing a little bit of investigation, when running `aspp` I see this:
```
aspp  /home/groeges/openj9/openj9-openjdk-jdk9/build/aix-ppc64-normal-server-release/vm/tr.source/../tr.source/trj9/p/runtime/J9PPCArrayCmp.spp /home/groeges/openj9/openj9-openjdk-jdk9/build/aix-ppc64
-normal-server-release/vm/tr.source/../objs/tr.source/trj9/p/runtime/J9PPCArrayCmp.o.aspp
        AIX Assembly Preprocessor v1.1b (/home/groeges/openj9/openj9-openjdk-jdk9/build/aix-ppc64-normal-server-release/vm/tr.source/../tr.source/trj9/p/runtime/J9PPCArrayCopy.spp-->/home/groeges/open
j9/openj9-openjdk-jdk9/build/aix-ppc64-normal-server-release/vm/tr.source/../objs/tr.source/trj9/p/runtime/J9PPCArrayCopy.o.aspp) [copying]
```
which just seems to be copying the .spp file  to a .o.aspp file and when I diff the 2 files they are identical. 

I changed the `openj9/runtime/tr.source/trj9/build/toolcfg/aix-xlc/common.mk` file to set the 
```
ASPP_PATH?=aspp
```
to use
```
ASPP_PATH?=cp
```
and ran the build again. This all built successfully without the use of the aspp executable. 
Do you think we can make this change, as this is the simplest change without having the refactor all of the .mk files.

**Comment by zl-wang** [comment]
as a stop gap, it is fine.  in the mean time, i am looking for someone to change the makefile to fix.

**Comment by groeges** [comment]
Temporary fix: https://github.com/eclipse/openj9/pull/387

**Comment by DanHeidinga** [comment]
Complete fix: https://github.com/eclipse/openj9/pull/666

Closing.
