### ISSUE TITLE
testBasic and testPowersOf2 are in sanity and extended group

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#2734]
org.openj9.test.gpu.SortTest: testBasic and testPowersOf2 are setting as sanity and extended group. That is in jenkins they will run in sanity and extended test jobs, which is kind of unnecessary. 

@keithc-ca FYI, We're planning to remove these tests from extended group.

**Comment by keithc-ca** [comment]
That makes sense. Thanks.
