### ISSUE TITLE
Not able to get connector address for management-agent.jar

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#2742]
It looks like loading `management-agent.jar` (which is provided by OpenJDK and is present in the builds at `$JAVA_HOME/lib`) in OpenJ9 JVM using Attach API is not working as expected.

I tried it using following OpenJ9 level:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180813_291 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - a05586ac based on jdk8u181-b13)
```

Here is a client code that attaches to JVM using Attach API, loads `management-agent.jar`, gets connector address using property `com.sun.management.jmxremote.localConnectorAddress` and then gets list of thread names and their states.
This code is mentioned in https://blogs.oracle.com/corejavatechtips/the-attach-api.

```
import java.util.Set;
import java.io.File;

public class ThreadList {

	public static void displayThreadInfo(VirtualMachine vm) throws Exception {
		Properties props = vm.getAgentProperties();
		String connectorAddr = props.getProperty("com.sun.management.jmxremote.localConnectorAddress");
		if (connectorAddr == null) {
			String agent = vm.getSystemProperties().getProperty("java.home") + File.separator + "lib" + File.separator + "management-agent.jar";
			vm.loadAgent(agent);
			props = vm.getAgentProperties();
			connectorAddr = props.getProperty("com.sun.management.jmxremote.localConnectorAddress");
		}
		JMXServiceURL serviceURL = new JMXServiceURL(connectorAddr);
		JMXConnector connector = JMXConnectorFactory.connect(serviceURL); 
		MBeanServerConnection mbsc = connector.getMBeanServerConnection();
		ObjectName objName = new ObjectName(ManagementFactory.THREAD_MXBEAN_NAME);
		Set<ObjectName> mbeans = mbsc.queryNames(objName, null);
		for (ObjectName name : mbeans) {
			ThreadMXBean threadBean = ManagementFactory.newPlatformMXBeanProxy(mbsc, name.toString(), ThreadMXBean.class);
			long threadIds[] = threadBean.getAllThreadIds();
			for (long threadId: threadIds) {
				ThreadInfo threadInfo = threadBean.getThreadInfo(threadId);
				System.out.println (threadInfo.getThreadName() + " / " + threadInfo.getThreadState());
			}
		}
	}

	public static void main(String args[]) throws Exception {
		VirtualMachine vm = null;
		if (args.length != 0) {
			vm = VirtualMachine.attach(args[0]);
			displayThreadInfo(vm);
		} else {
			System.out.println("Usage: java ThreadList <pid>");
		}
	}
}
```

Command to compile above program:

`$JAVA_HOME/bin/javac -cp $JAVA_HOME/lib/tools.jar:. ThreadList.java`

**Steps to reproduce:**
1) Start a sample program that runs infinite loop. I used following program:

```
public class HelloWorld {
        public static void main(String args[]) throws Exception {
                int counter = 0;
                for (;;) {
                        System.out.println(counter);
                        counter += 1;
                        Thread.sleep(2000);
                }
        }
}
```
Run it as:
`$JAVA_HOME/bin/java HelloWorld`

2) Get its process id using `ps -ef|grep HelloWorld`

3) Run the client program that loads `management-agent.jar` mentioned above passing the process id as the argument:
$JAVA_HOME/bin/java -cp $JAVA_HOME/lib/tools.jar:. ThreadList <pid>

**Expected Output:**
List of threads running in the JVM started in step 1.
For example:
```
main / TIMED_WAITING
JIT Compilation Thread-0 / RUNNABLE
JIT Compilation Thread-1 Suspended / RUNNABLE
JIT Compilation Thread-2 Suspended / RUNNABLE
JIT Compilation Thread-3 Suspended / RUNNABLE
JIT Compilation Thread-4 Suspended / RUNNABLE
JIT Compilation Thread-5 Suspended / RUNNABLE
JIT Compilation Thread-6 Suspended / RUNNABLE
JIT Diagnostic Compilation Thread-7 Suspended / RUNNABLE
JIT-SamplerThread / TIMED_WAITING
IProfiler / RUNNABLE
Concurrent Mark Helper / RUNNABLE
GC Slave / RUNNABLE
GC Slave / RUNNABLE
GC Slave / RUNNABLE
Attach API wait loop / RUNNABLE
file lock watchdog / TIMED_WAITING
Finalizer thread / RUNNABLE
MemoryMXBean notification dispatcher / RUNNABLE
RMI TCP Accept-0 / RUNNABLE
RMI TCP Connection(1)-127.0.0.1 / RUNNABLE
ClassCache Reaper / WAITING
RMI Scheduler(0) / TIMED_WAITING
JMX server connection timeout 29 / TIMED_WAITING
```

**Actual Output:**
```
$JAVA_HOME/bin/java -cp "$JAVA_HOME"/lib/tools.jar:. ThreadList 5098
Exception in thread "main" java.lang.NullPointerException
	at javax.management.remote.JMXServiceURL.<init>(JMXServiceURL.java:142)
	at ThreadList.displayThreadInfo(ThreadList.java:21)
	at ThreadList.main(ThreadList.java:40)
```

Stack trace shows the `connectorAddr` at `JMXServiceURL serviceURL = new JMXServiceURL(connectorAddr);` is null.

With Openjdk build this works fine. Openjdk build I used is:

```
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_07_27_20_16-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
```

**Comment by ashu-mehra** [comment]
Note that in `ThreadList.java` if I replace `vm.loadAgent(agent);` with `vm.startLocalManagementAgent()`, then it is able to get the `connectorAddr`.

**Comment by ashu-mehra** [comment]
I looked at `sun.management.Agent` which is the agent class in `management-agent.jar`.
When the agent is loaded via `vm.loadAgent()` it sets property `com.sun.management.jmxremote.localConnectorAddress` at https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/2b004fdb6829f287eaa464a57a8680377886ca75/jdk/src/share/classes/sun/management/Agent.java#L140 but it never gets added to `java.lang.System.systemProperties`.
Later `ThreadList.java` calls `vm.getAgentProperties()` which basically returns `java.lang.System.systemProperties`.
However, when agent is loaded via `vm.startLocalManagementAgent()` this property gets added to `java.lang.System.systemProperties` in `Attachment.startJavaAgent()`(https://github.com/eclipse/openj9/blob/dd7d3f8e8796bed88feb66def6a876f673778d83/jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Attachment.java#L417)

I think that's the reason `ThreadList` is not able to get connector address when using `vm.loadAgent()`.

**Comment by aguibert** [comment]
I am also noticing this issue with the following OpenJ9 JDK 11 build:
```
$ java --version
openjdk 11-adoptopenjdk 2018-09-25
OpenJDK Runtime Environment (build 11-adoptopenjdk+28)
Eclipse OpenJ9 VM (build master-da9abedb, JRE 11 Linux amd64-64-Bit Compressed References 20180906_19 (JIT enabled, AOT enabled)
OpenJ9   - da9abedb
OMR      - 2bda1df3
JCL      - 2750e51dbe based on jdk-11+28)
```

This is effecting the Liberty Maven and Liberty Arquillian plugins:
https://github.com/OpenLiberty/liberty-arquillian/blob/master/liberty-managed/src/main/java/io/openliberty/arquillian/managed/WLPManagedContainer.java#L321
