### ISSUE TITLE
Native tests for JDK11 and forward

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2761]
Thanks for @keithc-ca 's help. In `openj9_test_image` target, native test libraries are built under `images/test/openj9`. To ensure JDK11 test running properly, we need:

- [x] archive(/upload to artifactory) `images/test/openj9` in Jenkins SDK build job (@jdekonin )

- [x] update test pipeline to take the native libs and unzip it (@llxia) https://github.com/AdoptOpenJDK/openjdk-tests/pull/542

- [x] update test lib path to look for native libs in new location (@llxia) https://github.com/eclipse/openj9/pull/2812

**Comment by llxia** [comment]
fyi @jdekonin @AdamBrousseau

**Comment by llxia** [comment]
Related: https://github.com/eclipse/openj9/issues/2100

**Comment by jdekonin** [comment]
@llxia, here is the content...
```
[j9build@cent69hdcrt9 openj9]$ pwd
/tmp/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/test/openj9
[j9build@cent69hdcrt9 openj9]$ ls
libballoon29.so  libj9ben.so               libj9vmtest.so     libmemorywatcher29.so           libtestjvmtiA.so
libbcuwhite.so   libj9lazyClassLoad.so     libjcoregen29.so   libmigration.so                 libtestjvmtiB.so
libbcvwhite.so   libj9thrnumanatives29.so  libjlmagent29.so   libosmemory29.so                libtestlibA.so
libgptest.so     libj9thrtestnatives29.so  libjniargtests.so  libSharedClassesNativeAgent.so  libtestlibB.so
libhooktests.so  libj9unresolved.so        libjvmtitest.so    libsoftmxtest.so                libvmruntimestateagent29.so
```

**Comment by llxia** [comment]
Thanks @jdekonin 

Could you archive the libs into a folder start with `native-test-libs` and tar it with the same name (similar as SDK)? In the script, we unzip in `.` 

https://github.com/AdoptOpenJDK/openjdk-tests/blob/22cf59223de7b602d48a93e0a2e916aa8f25422f/get.sh#L165

**Comment by jdekonin** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/541
https://github.com/eclipse/openj9/pull/2805

**Comment by llxia** [comment]
Tasks are completed. 
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-win_x86-64_cmprssptrs/10/console
