### ISSUE TITLE
Prevent instrumentation of com.ibm.jit.JITHelpers

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2768]
As per https://github.com/eclipse/openj9/issues/2175#issuecomment-397068794, https://github.com/eclipse/openj9/issues/2175#issuecomment-397069745 and https://github.com/eclipse/openj9/issues/2175#issuecomment-418807896 @gacholio wrote.

"JITHelpers should probably be in the list of non-instrumentable classes.

jvmtiHook.c : canClassBeInstrumented to prevent load-time modification.

hshelp.c : classIsModifiable to prevent redefinition

It seems sensible to prevent instrumentation (and we can probably come up with more classes that it would be disastrous to instrument).
"

**Comment by pshipton** [comment]
@gacholio would you like to volunteer to make the changes, or leave this for somebody else?

**Comment by gacholio** [comment]
This isn't critical, so let's gather the data before making any changes.

**Comment by gacholio** [comment]
@andrewcraik @vijaysun-omr Are there other classes that will be an issue if instrumented? Not concerned about loss of performance, just with incorrectness/crash. Bear in mind the granularity of the decision is at the class level, not method. I was wondering in particular about MethodHandle implementation classes - I suspect instrumenting the thunk implementation methods would lead to badness.

**Comment by gacholio** [comment]
@DanHeidinga - any classes you can think of that we should not instrument?

**Comment by DanHeidinga** [comment]
VarHandleInternal for one.

**Comment by vijaysun-omr** [comment]
@gacholio I think you are right about the thunk archetypes that they should not be modifiable since they are really "convenience" methods to make the job of ILgen of thunks easier. Arbitrary changes in those methods would break functionality.

I wonder if all the classes in com.ibm.jit package (such as com_ibm_jit_DecimalFormatHelper_formatAsDouble or the DAA/crypto classes) should not be allowed to instrument.

**Comment by vijaysun-omr** [comment]
@jdmpapin could you please give your opinion too ?

**Comment by vijaysun-omr** [comment]
com.ibm.Compiler.Internal.Quad might be another class that cannot be instrumented.

**Comment by gacholio** [comment]
Once #4876 is merged, any bootstrap class can be annotated with `com.ibm.oti.vm.J9INTERNAL_CLASS` to prevent it from being modified during load, or redefined later.

**Comment by gacholio** [comment]
Note the annotation is `NOT` inherited - every class that wants it must declare it.
