### ISSUE TITLE
Launching sanity jdk11 testing also run extended testing

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2769]
In https://github.com/eclipse/openj9/pull/2718 I ran "jenkins test sanity xlinux,plinux,zlinux,xlinuxlargeheap jdk11" which started both sanity and extended testing, although the plinux extended testing didn't run.

@jdekonin

**Comment by pshipton** [comment]
I ran "jenkins test extended zlinux jdk11" which also started sanity
https://github.com/eclipse/openj9/pull/2959

@AdamBrousseau fyi

**Comment by AdamBrousseau** [comment]
^ That one is now resolved. This should all go away once #2728 is resolved.

**Comment by AdamBrousseau** [comment]
This can likely be closed now?
