### ISSUE TITLE
Documentation references "github.ibm.com" which is not visible to the internet

### ISSUE THREAD

**Issue by sxa555** [eclipse/openj9#28]
See https://github.com/eclipse/openj9/blob/master/test/README.md where the git examples are referencing github.ibm.com - should be changed to the appropriate location on github.com

**Comment by DanHeidinga** [comment]
@smlambert Can someone on your team give this a once over and test out all the commands in the README.md?

I think the `git clone git@github.ibm.com:runtimes/test` reference likely needs to be changed to `git clone git@github.com:eclipse/openj9` but larger changes may be needed as the doc still refers to tests residing in another repo.

i.e.: `Currently, the tests reside in a separate repo, so you will first clone the test repo.`

**Comment by smlambert** [comment]
Lan is taking this one (though I don't find her git id to assign to her officially yet).

**Comment by llxia** [comment]
@llxia

**Comment by DanHeidinga** [comment]
@llxia's changes address this issue.  Closing now
