### ISSUE TITLE
PR testing from jdk11 extensions not working

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2802]
i.e. https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/19

https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK11-aix_ppc-64_cmprssptrs-OpenJDK11/3/console

```
Setting status of 2f69cc5a870b361ded201d0886e636bbffcdec6a to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK11-aix_ppc-64_cmprssptrs-OpenJDK11/3/ and message: 'Build finished. '
Using context: Compile - JDK11 - aix_ppc-64_cmprssptrs
ERROR: Must specify SDK_VERSION
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
@jdekonin please check https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK11-linux_390-64_cmprssptrs-OpenJDK11/5/ as well. Its a different error. I can't view it at the moment because of proxy errors.

**Comment by jdekonin** [comment]
The 390 failure isn't due to a trigger issue.  There were some zombie processes on the machine though.  I am not convinced those were related to the issue, but I have cleaned them up.  This was the actual failure on that pull request.

```
00:05:26.301 /bin/cp: not writing through dangling symlink '/home/jenkins/jenkins-agent/workspace/PullRequest-Compile-JDK11-linux_390-64_cmprssptrs-OpenJDK11/build/linux-s390x-normal-server-release/jdk/lib/jvm.cfg'
00:05:26.301 /home/jenkins/jenkins-agent/workspace/PullRequest-Compile-JDK11-linux_390-64_cmprssptrs-OpenJDK11/closed/make/copy/Copy-java.base.gmk:25: recipe for target 'override-jvm.cfg' failed
00:05:26.301 make[3]: *** [override-jvm.cfg] Error 1
```

**Comment by pshipton** [comment]
Assuming cleaning up the zombie processes will fix this, if not we'll find out later and open a new issue.
