### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by komolema** [eclipse/openj9#2810]
Is there a planned support for FreeBSD, in the future. Is it possible to compile the project for FreeBSD, and if possible, how would one go about it?

**Comment by pshipton** [comment]
@komolema There isn't any planned support for FreeBSD. Is it possible to compile, I'm not sure, somebody would have to try it. Is seems OpenJDK can run so there is some hope. 

I'd start by looking at the docker files [1] to see the prerequisites required on Linux, figure out the  equivalent prerequisites for FreeBSD and install them. Install the source code and try to build as per [2], and see what happens or where things go wrong.

[1] https://github.com/eclipse/openj9/tree/master/buildenv/docker
[2] https://www.eclipse.org/openj9/oj9_build.html
