### ISSUE TITLE
[FR] javaws / Web start

### ISSUE THREAD

**Issue by ildar** [eclipse/openj9#2825]
is currently missing but still demanded for some legacy apps. Please add.
see this issue discussed before: https://github.com/AdoptOpenJDK/openjdk9-openj9-releases/issues/2

**Comment by DanHeidinga** [comment]
@ildar Thanks for opening the request.  Historically, webstart was provided by Oracle and I'm not aware of any plans to land the code in OpenJDK.

Do you (or anyone) know of alternative implementations of webstart/javaws? 

Implementing this from scratch would be cool to do but also a large amount of work.  We'd be interested in investigating existing alternatives if anyone is aware of one.

**Comment by DanHeidinga** [comment]
My understanding is that webstart is deprecated and will be removed from Oracle JDK at some future point.  As a deprecated technology, it's not really an area of pursuit on our roadmap.

There are alternative webstart providers, such as https://icedtea.classpath.org/wiki/IcedTea-Web  

We'd be interested in helping to resolve JVM problems encountered with running IceTea-Web with OpenJ9 but are unlikely to undertake a webstart project here.

Hope that helps!

**Comment by DanHeidinga** [comment]
@ildar Webstart has been deprecated for a while now and based on this article[1], it is also removed from Oracle Java 11.

[1] https://dzone.com/articles/what-the-future-java-releases-will-mean-for-legacy

> But surely OpenJ9 may have its peculiarities I don't know about...

As far as I know, webstart has never been part of OpenJDK and was only available in commercial JDKs.  The peculiarity is with the parts of the JDK that have never been open sourced, and not with OpenJ9.  I'd suggest asking at OpenJDK to have webstart open-sourced if you want access to it but I wouldn't count on it happening.

As mentioned previously, there are other providers of webstart technology like IceTea-Web: 
https://icedtea.classpath.org/wiki/IcedTea-Web

This would be the path I'd pursue if you still require webstart.

**Comment by DanHeidinga** [comment]
@ildar The AdoptOpenJDK community has put together a video showing how to use IcedTea-Web with a JDK - https://youtu.be/wRRS0LejZuM  Hope that helps!

**Comment by ildar** [comment]
Seems that the issue was finally resolved, see
https://adoptopenjdk.net/icedtea-web.html
Thanks guys!

**Comment by ildar** [comment]
Thanks, @DanHeidinga !
