### ISSUE TITLE
Add jobs to archive nightly builds

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#2831]
Helps #2316 
Depends #2728 
- Per spec
- Per platform

In order to have test-only PR builds, we need to pull a "good" sdk. Since the Build* jobs which compile/archive the sdks are reusable across many build types, we need a way to identify which one is a nightly and which one is "good". The proposal is to add a job that would copy the sdk artifact from the build job to a new job. the test jobs would then look to the "archive job" to fetch the "good" sdk. This will have to work with both Jenkins archiving and Artifactory archiving. Since we only need to keep the last good level of sdks, this shouldn't put a huge strain on disk space as it only adds 1 build worth of SDKs to the archive.

**Comment by AdamBrousseau** [comment]
I'm not sure if this is needed anymore now that we have separated the builds by type. I know @R-Santhir is looking at working on #2316 but I think there is an ~easy way to pull the last build from Artifactory.
cc @llxia @smlambert I know we've had this conversation again recently too.

**Comment by AdamBrousseau** [comment]
Another option would be to look to the nightly jenkins build object and grab the SDK url from the env. We do a similar thing already here
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions#L364
and this will likely also be useful
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/pipeline-functions#L170

**Comment by pshipton** [comment]
> If we wanted to pursue test-only builds we can pull the last good nightly based on querying the Jenkins api.

Curious, do we have the ability to do this?

**Comment by smlambert** [comment]
Yes, you can use the [test pipeline script](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/JenkinsfileBase) directly to do this (setting SDK_RESOURCE=nightly to retrieve the latest published nightly build).  Its the same script that backends the Grinders and all testing at OpenJ9 and AdoptOpenJDK which use the Jenkins API to pull nightly or release builds (SDK_RESOURCE=releases). 

<img width="622" alt="Screen Shot 2020-06-10 at 9 55 38 PM" src="https://user-images.githubusercontent.com/2836948/84336411-2cce8500-ab65-11ea-935c-0940f9f1d340.png">

**Comment by AdamBrousseau** [comment]
Per platform, last successful would be simple pipeline code. Might need a few script approvals. If you wanted last fully green build or some other higher quality bar it could get a bit more tricky, maybe. If we wanted to move ahead with test-only builds (#

**Comment by pshipton** [comment]
> setting SDK_RESOURCE=nightly

I was asking about getting OpenJ9 builds, not Adopt builds.

**Comment by pshipton** [comment]
We have some OpenJ9 builds which should be test-only, although they are set up to re-build the JVMs since that seemed to be the only supported way.

**Comment by AdamBrousseau** [comment]
Which builds should be test only?

**Comment by pshipton** [comment]
The Pipeline-Special-System jobs that run on the weekend.

**Comment by pshipton** [comment]
I suppose there is nothing wrong with rebuilding the JVMs to run the special.system tests, it means we're testing the latest changes rather than the last nightly. I think we'd just keep it the way it is. I recall wanting to get the last nightly build in the past, so I was curious if it could be done now. I'm not sure what we'd use it for.

**Comment by pshipton** [comment]
It could be used to run grinders using the last nightly build from OpenJ9 (instead of Adopt), without having to look up the link manually. Although usually I run grinders from a failure, and there is a grinder link now (thanks!) that populates the build URL automatically.
