### ISSUE TITLE
Failure to dump system core in a docker environment by default

### ISSUE THREAD

**Issue by BrijeshNekkare** [eclipse/openj9#287]
Am unable to get system cores in a docker environment by default

**Recreate and related error:**
root@xxxxx:~/openj9-openjdk-jdk9# ./build/linux-x86_64-normal-server-release/jdk/bin/java -Xdump:system:events=vmstart -version
	JVMDUMP039I Processing dump event "vmstart", detail "" at 2017/10/11 00:29:17 - please wait.
	JVMDUMP032I JVM requested System dump using '/root/openj9-openjdk-jdk9/core.20171011.002917.20409.0001.dmp' in response to an event
	**JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.20427.**
	JVMDUMP012E Error in System dump: The core file created by child process with pid = 20427 was not found. Expected to find core file with name "/root/openj9-openjdk-jdk9/core.20427"
	JVMDUMP013I Processed dump event "vmstart", detail "".
	openjdk version "9-internal"
	OpenJDK Runtime Environment (build 9-internal+0-adhoc..openj9-openjdk-jdk9)
	Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171011_000000 (JIT enabled, AOT enabled)
	OpenJ9   - ebe9e7c
	OMR      - 5d625a3
	OpenJDK  - a4765a5 based on jdk-9+181)

**ulimit setting:**
	root@xxxxxx:~/openj9-openjdk-jdk9# ulimit -a
	**core file size          (blocks, -c) 0**
	data seg size           (kbytes, -d) unlimited
	scheduling priority             (-e) 0
	file size               (blocks, -f) unlimited
	pending signals                 (-i) 15217
	max locked memory       (kbytes, -l) 64
	max memory size         (kbytes, -m) unlimited
	open files                      (-n) 1024
	pipe size            (512 bytes, -p) 8
	POSIX message queues     (bytes, -q) 819200
	real-time priority              (-r) 0
	stack size              (kbytes, -s) 10240
	cpu time               (seconds, -t) unlimited
	max user processes              (-u) 15217
	virtual memory          (kbytes, -v) unlimited
	file locks                      (-x) unlimited

Looks like both /proc/sys/kernel/core_pattern and ulimit settings need change in docker environment. This would be a good feature to have by default.

**Comment by DanHeidinga** [comment]
@BrijeshNekkare Can you elaborate on what you're doing?

From my experience, generating core files in a docker image isn't particularly useful most of the time as the cores are lost when the image exits.  Unless the image has been configured to write cores to a mapped volume or upload them in some way, they aren't preserved.

The Dockerfiles in the buildenv/ directory of the project serve as an example of how to build OpenJ9.  Its never been the intent to turn them into a full fledged development environment.

**Comment by BrijeshNekkare** [comment]
@DanHeidinga

Yes i did map docker container filesystem into my native filesystem. My thought was to build and test in docker environment, debug outside of it (wherever applicable). 

For example
1. Crash analysis using DDR, KCA
2. hcd file analysis using Health Center
3. Memory leaks using MAT etc

Another thought (though not related to this issue) was build in docker and use outside of it.
1. map docker container filesystem into my native filesystem (exposing built OpenJ9)
2. Build OpenJ9 in docker environment 
3. Use OpenJ9 outside of docker environment. 
Have done a first pass of whether this works, notice that OpenJ9 has dependency on glibc 2.14

These are still early days for me and my colleagues hence we are still getting around to whats the best way forward. Am i totally off track that i should consider not going down this path.

**Comment by DanHeidinga** [comment]
The existing Dockerfiles in buildenv/ directory are a form of "executable documentation" that describe the minimum requirements to build OpenJ9.  

Your approach of creating a build, test, and debug env is cool and worth investigating further.  Starting from the existing Dockerfile and building on top of it - adding additional requirements, tools, mapped volumes, etc - would be a good way to go about this.

Aim for a separate Dockerfile for this work so that the existing buildenv/ ones can be kept to minimal executable doc.

**Comment by BrijeshNekkare** [comment]
Thanks @DanHeidinga for your inputs, took a while to get things working.

Tweaked my above stated procedure for build/test/debug/submit fixes courtesy ashu-mehra and it works like a charm.
1. git clone relevant "forked repos" outside of the docker container.
2. Now use docker volume feature and build/test within docker.
3. Submit repo changes outside of docker environment post fix verification. 
4. Debug crash files (if any) outside of the docker container.

Inability to edit /proc/sys/kernel/core_pattern within docker environment can be worked around by
1. Exit the docker container (where core-files was not generated due to default entry in core_pattern file)
2. Update the /proc/sys/kernel/core_pattern appropriately on host.
3. change ulimit settings if needed.
4. Restart and attach back to the docker container (updated core_pattern is visible)

I am happy to close this issue now.

**Comment by pshipton** [comment]
@BrijeshNekkare you opened the issue, so you can close it.
