### ISSUE TITLE
Writing to closed socket connection kills the JVM

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2871]
Recent regression.  Looks like a blocker.  FYI @gacholio .  I am investigating. 

```
$ java -version
openjdk version "10.0.2-internal" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-internal+0-adhoc.jenkins.Build-JDK10-linuxx86-64cmprssptrs)
Eclipse OpenJ9 VM (build master-e60de42, JRE 10 Linux amd64-64-Bit Compressed References 20180914_446 (JIT enabled, AOT enabled)
OpenJ9   - e60de42
OMR      - 28b6fbc
JCL      - a6243ec based on jdk-10.0.2+13)
28a57f78e63e-root:8$ "/java/bin/java"  -Xcompressedrefs  \
> --add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED \
> -cp "/openj9test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/openj9test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/openj9test/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/openj9test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/GeneralTest.jar" \
> -Dcom.ibm.tools.attach.enable=yes \
> -Dcom.ibm.tools.attach.timeout=15000 \
> -Djava.sidecar="--add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED" \
> org.testng.TestNG -d "/openj9test/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15369295991794/TestAttachErrorHandling_0" "/openj9test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java8andUp/testng.xml" -testnames TestAttachErrorHandling \
> -groups level.extended \
> -excludegroups d.*.linux_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.linux,d.*.bits.64,d.*.generic-all
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is null
...
... TestNG 6.14.2 by C?dric Beust (cedric@beust.com)
...

[AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/2351 not removed because -1 still alive
[AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/1234_5 not removed because -1 still alive
[AttachApiTest] [WARN] /tmp/.com_ibm_tools_attach/foo not removed because -1 still alive
28a57f78e63e-root:9$ echo $?
141
```

**Comment by pdbain-ibm** [comment]
None of the error handling tests are reporting failure.  AttachAPI sanity test passes.

**Comment by pdbain-ibm** [comment]
The TestNG harness is not printing the list of passing and failing tests.  the exit status of 141 is suspicious: a normal test failure causes an exit status of 1.

**Comment by pdbain-ibm** [comment]
Test is failing in `testVmShutdownWhileAttached`:
```
            info("terminated " + tgtId);
            tgtVm.getSystemProperties();
            info("completed getSystemProperties to " + tgtId);
```
Console log:
```
[TargetManager] [DEBUG] waitFor status = 0
[AttachApiTest] [DEBUG] TEST_INFO: terminated 16157
status=141
```
attach API log:
```
    1536935911319 16157: 18 [Attach API teardown]: AttachHandler tryObtainMasterLock failed
    1536935911322 16157: 18 [Attach API teardown]: deleting my directory 
    1536935911323 16157: 18 [Attach API teardown]: AttachHandler closed semaphore
1536935911335 16135: 1 [main]: streamSend ATTACH_GETSYSTEMPROPERTIES
```
at which point the attacher dies.

```
	public Properties getSystemProperties() throws IOException {
		if (!targetAttached) {
			/*[MSG "K0544", "Target not attached"]*/
			throw new IOException(getString("K0544")); //$NON-NLS-1$
		}
		Properties props = getTargetProperties(true);
		return props;
	}
```
I instrumented the test to catch Throwable: no exception or other throwable is thrown.

**Comment by pdbain-ibm** [comment]
The test connects to a target Java process, opening a socket in the process.  It then causes the target to stop (closing the socket) and tries to write to the socket. 

I wrote an ad-hoc test (attached):
```
			OutputStream commandStream = targetSocket.getOutputStream();
			Thread.sleep(10000);
			while (true) {
				System.out.println("Attacher:sending");
				commandStream.write(99);
				Thread.sleep(1000);
			}

```

This previously worked (i.e. threw an exception) on OpenJ9:
```
$ java -version
openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 10 Linux amd64-64-Bit Compressed References 20180813_102 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13)

$ (java attacher; echo Java exited with status $?) & (sleep 2; java target 12345)
[1] 5758
Attacher: Server port = 12345
Attacher:connected
Target attached
Target read
Attacher:sending
Target result=99
Target read
Target result=99
...
Attacher:sending
Target result=99
Target exit
$ Attacher:sending
Attacher:sending
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite(java.base@10.0.2-adoptopenjdk/SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(java.base@10.0.2-adoptopenjdk/SocketOutputStream.java:134)
	at attacher.main(attacher.java:21)
Attacher:exit
Java exited with status 0
```

... and OpenJDK:
```
$ java -version
openjdk version "10.0.1-adoptopenjdk" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-adoptopenjdk+10)
OpenJDK 64-Bit Server VM (build 10.0.1-adoptopenjdk+10, mixed mode)
...
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:134)
	at attacher.main(attacher.java:21)
```

But not with the latest OpenJ9:
```
Target read
Attacher:sending
Target result=99
Target read
Attacher:sending
Target result=99
Target exit
$ Attacher:sending
Attacher:sending
Java exited with status 141
```

The first call to `write()` returns silently and the second call kills the JVM instead of throwing an exception.

**Comment by pdbain-ibm** [comment]
[2871.zip](https://github.com/eclipse/openj9/files/2384850/2871.zip)

**Comment by pdbain-ibm** [comment]
This looks like a class library change. @andrew-m-leonard Has the socket code changed recently?
@pshipton would you please remove the "test failure" label?

**Comment by andrew-m-leonard** [comment]
Nothing has changed in jdk10u for 2 months... extensions haven't changed from about a month either

**Comment by pdbain-ibm** [comment]
Fails with Java 8:

> $ java -version
> openjdk version "1.8.0_192-internal"
> OpenJDK Runtime Environment (build 1.8.0_192-internal-pdbain_2018_09_14_14_16-b00)
> Eclipse OpenJ9 VM (build verifier-ab170ae, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180914_000000 (JIT enabled, AOT enabled)
> OpenJ9   - ab170ae
> OMR      - 28b6fbc
> JCL      - df909af based on jdk8u192-b03)

**Comment by andrew-m-leonard** [comment]
Java8 extensions were updated to jdk8u192-b03 recently

**Comment by pdbain-ibm** [comment]
Failing with 

> openjdk version "10.0.2-internal" 2018-07-17
> OpenJDK Runtime Environment (build 10.0.2-internal+0-adhoc.pdbain.openj9-openjdk-jdk10)
> Eclipse OpenJ9 VM (build master-03219bd, JRE 10 Linux amd64-64-Bit Compressed References 20180914_000000 (JIT enabled, AOT enabled)
> OpenJ9   - 03219bd
> OMR      - 28b6fbc
> JCL      - a6243ec based on jdk-10.0.2+13)

Passing with 

> openjdk version "10.0.2-adoptopenjdk" 2018-07-17
> OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
> Eclipse OpenJ9 VM (build master-669607af, JRE 10 Linux amd64-64-Bit Compressed References 20180912_8 (JIT enabled, AOT enabled)
> OpenJ9   - 669607af
> OMR      - f29d1585
> JCL      - a6243eca06 based on jdk-10.0.2+13)

**Comment by pdbain-ibm** [comment]
Passing with the latest nightly build from
https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/download/jdk10u-2018-09-17-09-19/OpenJDK10U-jre_x64_linux_openj9_2018-09-17-09-19.tar.gz

openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
Eclipse OpenJ9 VM (build master-669607af, JRE 10 Linux amd64-64-Bit Compressed References 20180916_12 (JIT enabled, AOT enabled)
OpenJ9   - 669607af
OMR      - f29d1585
JCL      - a6243eca06 based on jdk-10.0.2+13)

**Comment by pdbain-ibm** [comment]
Also passing with the latest ci.eclipse build:
OpenJDK10U_x64_linux_openj9_2018-09-16-14-04.tar.gz

> openjdk version "10.0.2-adoptopenjdk" 2018-07-17
> OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
> Eclipse OpenJ9 VM (build master-669607af, JRE 10 Linux amd64-64-Bit Compressed References 20180916_12 (JIT enabled, AOT enabled)
> OpenJ9   - 669607af
> OMR      - f29d1585
> JCL      - a6243eca06 based on jdk-10.0.2+13)

This is starting to look like a tool or environment issue.

**Comment by pdbain-ibm** [comment]
Bracketed it to the GCC-7.3 changes:
```
commit aeba9dec5b0b282c9868541892f144dc6954f7e1   ############## FAILED    #####################
Author: Violeta Sebe <vsebe@ca.ibm.com>
Date:   Fri Sep 14 12:22:24 2018 -0400 

    Enable GCC-7.3 toolchain for Linux PPC LE in Jenkins files 
    
    Add build environment variables for gcc-7.3 for JDK11 and Next. 
    
    [ci skip] 
    
    Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>

commit 9ef5381dc1e674d675c7929e10065220eda3b617   ############## PASSED    #####################
Author: Jack Lu <Jack.S.Lu@ibm.com>
Date:   Wed Sep 5 16:50:06 2018 -0400 

    Add support for Constant Dynamic entry in classfile writer
    
    - add constant dynamic case during constantpool analyze and writing
    
    Signed-off-by: Jack Lu <Jack.S.Lu@ibm.com>
```

Those changes should affect only PPCLE:

```
  build_env:
     vars:
       11: 'CC=gcc-7 CXX=g++-7'
       next: 'CC=gcc-7 CXX=g++-7'
```

**Comment by pshipton** [comment]
The gcc 7.3 changes only occurred for Java 11 builds, yet the test is failing on older versions.

**Comment by pshipton** [comment]
@pdbain-ibm Please exclude TestAttachErrorHandling_SE80_0 (Java 8 ) and TestAttachErrorHandling_0 (later versions) from the OpenJ9 extended testing so all the extended tests stop failing nightly.

**Comment by pdbain-ibm** [comment]
@pshipton Will do.  I am getting close to the root cause.

**Comment by pdbain-ibm** [comment]
Reverting these `omrsig` commits fixes the problem:

- 45135e8f9bd1e532ec20892d06ffef78801cacef https://github.com/eclipse/openj9/commit/45135e8
- 11c7267c52707a2cac55be38e04528651b1d4599 https://github.com/eclipse/openj9/commit/11c7267
- cfe191c045943a997d7cdf9ca39c9e015567e9ed  https://github.com/eclipse/openj9/commit/cfe191c

To test, unpack attached archive, add the Java under test, and runt the `runt` script.  If the script prints `Java exited with status 141` the test fails.  If it prints
```
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite(java.base@10.0.2-internal/SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(java.base@10.0.2-internal/SocketOutputStream.java:134)
	at attacher.main(attacher.java:21)
Attacher:exit
Java exited with status 0
``` it passed.
[2871_files.zip](https://github.com/eclipse/openj9/files/2401609/2871_files.zip)

@babsingh would you please investigate?

**Comment by pshipton** [comment]
Not sure Peter's ping worked, since its quoted.

@babsingh

**Comment by pshipton** [comment]
@babsingh See https://github.com/eclipse/openj9/issues/2871#issuecomment-421472432

**Comment by babsingh** [comment]
Fix - https://github.com/eclipse/openj9/pull/2965

**Comment by andrew-m-leonard** [comment]
@pshipton Interesting some of our TLS 1.3 SSL test failures fail with "Java exited with status 141", I will see if this PR has fixed that...
