### ISSUE TITLE
 Invoke JVM using JNI_CreateJavaVM with linkage path JAVA_HOME/lib/server failed

### ISSUE THREAD

**Issue by enasser** [eclipse/openj9#2888]
When we tried to invoke JVM using JNI_CreateJavaVM from a native code by providing the linkage path as JAVA_HOME/lib/j9vm or JAVA_HOME/lib/server, we are getting the following error where as it works fine when use the path JAVA_HOME/lib/compressedrefs.
 
`./invoke: error while loading shared libraries: libjvm_b156.so: cannot open shared object file: No such file or directory`
 
I could find an issue related to this at https://github.com/eclipse/openj9/issues/292 

The issue can be recreated with following test case on linux x64 system:
[test_case_2888.zip](https://github.com/eclipse/openj9/files/2388669/test_case_2888.zip)

**Recreate Steps:**
```
$ export JAVA_HOME=/home/enasser/openjdk/builds/j9/jdk-10.0.2+13/
$ export LD_LIBRARY_PATH=$JAVA_HOME/lib/j9vm
$ c++ -Wl,--no-as-needed -ldl -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -L$LD_LIBRARY_PATH -o invoke invoke.cpp -ljvm
invoke.cpp: In function ‘int main()’:
invoke.cpp:27:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     options[0].optionString = "-Djava.class.path=.";
                             ^
:~/testpgm/jni$ ./invoke
./invoke: error while loading shared libraries: libjvm_b156.so: cannot open shared object file: No such file or directory
```
```
$ export LD_LIBRARY_PATH=$JAVA_HOME/lib/server
$ c++ -Wl,--no-as-needed -ldl -I$JAVA_HOME/include -I$JAVA_HOME/include/linux -L$LD_LIBRARY_PATH -o invoke invoke.cpp -ljvm
invoke.cpp: In function ‘int main()’:
invoke.cpp:27:30: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     options[0].optionString = "-Djava.class.path=.";
                             ^
$ ./invoke
./invoke: error while loading shared libraries: libjvm_b156.so: cannot open shared object file: No such file or directory
```

**Comment by JasonFengJ9** [comment]
This appears due to the basename (`libjvm.so`) doesn't match soname (`libjvm_b156.so`) as per following:
```
readelf -d /home/jason/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-release/images/jdk/lib/j9vm/libjvm.so
Dynamic section at offset 0x13de0 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libjvm_b156.so]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN]
```
When the build script copies `redirector/libjvm_b156.so` to `j9vm/libjvm.so`, the soname need to be changed as well. 
Tried following command:
```
patchelf --set-soname libjvm.so /home/jason/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-release/images/jdk/lib/j9vm/libjvm.so
```
Now it finds correct library, and see Unhandled exception Floating point error as per #2887.

Note: all platform supported by `OpenJ9` have to be checked.

**Comment by keithc-ca** [comment]
My work in #2956 should take us a step closer to resolving this.
All variants of `libjvmXXX.so` will have the same content; then the extension repos can refer to the one with the right soname; and finally we can stop producing more than one jvm or more than one redirector.

**Comment by keithc-ca** [comment]
This should be fixed by https://github.com/eclipse/openj9/pull/3714 (and https://github.com/eclipse/openj9/pull/3638 which supersedes #2956).

**Comment by keithc-ca** [comment]
@enasser Closing (reopen if you find it isn't fixed).
