### ISSUE TITLE
Missing java.lang.ref.Reference.waitForReferenceProcessing() for openjdk regression tests for TLS 1.3

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2909]
< sun/security/provider/FileInputStreamPool/FileInputStreamPoolTest.java                                                  Failed. Execution failed: `main' threw exception: java.lang.Error: java.lang.NoSuchMethodException: java.lang.ref.Reference.waitForReferenceProcessing()

It appears a private method java.lang.ref.Reference.waitForReferenceProcessing() is required.

**Comment by JasonFengJ9** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/b44d19c4cbca42541aef5132f21870c1b924a68c/test/jdk/sun/security/provider/FileInputStreamPool/FileInputStreamPoolTest.java#L152-L154
```
                waitForReferenceProcessingMethod =
                    Reference.class.getDeclaredMethod("waitForReferenceProcessing");
                waitForReferenceProcessingMethod.setAccessible(true);
```
@LinHu2016 is on this.

**Comment by LinHu2016** [comment]
I can add new private static method waitForReferenceProcessing() in Reference.java to avoid the issue, but apparently test code (FileInputStreamPoolTest.java) uses unusual reflection way to access private method.

**Comment by LinHu2016** [comment]
currently plan to add private static method waitForReferenceProcessing() for Java 9 or above, but we can also add it in Java 8 openJ9

**Comment by JasonFengJ9** [comment]
It appears this test is against RI specific internal behaviour (a private static method). If there is no usage I would suggest to add it for `JDK11` and onwards.
