### ISSUE TITLE
Crashes in jitt and other testing on ppc le

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2917]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/19/tapResults/

example
```
===============================================
Running test jit_jitt_0 ...
===============================================
jit_jitt_0 Start Time: Tue Sep 18 05:01:41 2018 Epoch Time (ms): 1537246901364
test with -Xjit:noJitUntilMain,count=0,assumeStrictFP,optlevel=warm,gcOnResolve,rtResolve -verbose:stackwalk=0 -Xdump
Unhandled exception
Type=Segmentation error vmState=0x00110000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00003FFF7E53CA70 Handler2=00003FFF7E2CD2B0
R0=00003FFF7CBBBB78 R1=00003FFF7EF3CBB0 R2=00003FFF7CC77200 R3=0000000000000000
R4=00003FFF7EF3D490 R5=000000000000000B R6=00003FFF7CC48958 R7=00003FFF5CE80038
R8=0000000000000001 R9=00003FFF7EF3CFF8 R10=00003FFF7CC705B8 R11=00000000FFFFFFFF
R12=0000000000004400 R13=00003FFF7EF46900 R14=00000000000F02E0 R15=0000000000014F00
R16=00003FFF5CE80038 R17=FFFFFFFFFFFFFFFF R18=0000000000015958 R19=00003FFF7DF51A40
R20=00003FFF7DB421D0 R21=0000000000400000 R22=0000000000000000 R23=00003FFF7CC70298
R24=0000000000014F00 R25=00003FFF7DB68298 R26=00003FFF7EF3D0D8 R27=0000000000000000
R28=00003FFF7EF3D108 R29=0000000000000007 R30=0000000000000000 R31=00003FFF7EF3CFC8
NIP=00003FFF7CBBB814 MSR=800000000280F033 ORIG_GPR3=C0000000007C77EC CTR=00003FFF7F0DF080
LINK=00003FFF7CBBB7D8 XER=0000000020000000 CCR=0000000048224484 SOFTE=0000000000000001
TRAP=0000000000000300 DAR=0000000000000000 dsisr=0000000040000000 RESULT=0000000000000000
FPR0 000000000016c7c0 (f: 1492928.000000, d: 7.376044e-318)
FPR1 405557f9c2e6aa78 (f: 3269896704.000000, d: 8.537462e+01)
FPR2 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
FPR3 3c79c00000000000 (f: 0.000000, d: 2.233456e-17)
FPR4 402e7f9c1e980d00 (f: 513281280.000000, d: 1.524924e+01)
FPR5 3ff5f474c0000000 (f: 3221225472.000000, d: 1.372182e+00)
FPR6 6f632f676e747365 (f: 1853125504.000000, d: 3.635904e+228)
FPR7 7470737372706d63 (f: 1919970688.000000, d: 7.538209e+252)
FPR8 65542f747365746d (f: 1936028800.000000, d: 1.308742e+180)
FPR9 6372756f7365722f (f: 1936028160.000000, d: 1.114601e+171)
FPR10 2e737473694c2f73 (f: 1766600576.000000, d: 6.259072e-85)
FPR11 466c2d8c60000000 (f: 1610612736.000000, d: 1.785988e+31)
FPR12 0000000000000001 (f: 1.000000, d: 4.940656e-324)
FPR13 402f219b8d59a234 (f: 2371461632.000000, d: 1.556564e+01)
FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/home/jenkins/jenkins-agent/workspace/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vrb29.so
Module_base_address=00003FFF7CBA0000
Target=2_90_20180918_21 (Linux 4.4.0-134-generic)
CPU=ppc64le (4 logical CPUs) (0x1fe3a0000 RAM)
----------- Stack Backtrace -----------
(0x00003FFF7CBBB814 [libj9vrb29.so+0x1b814])
(0x00003FFF7CBBBB78 [libj9vrb29.so+0x1bb78])
(0x00003FFF7CBBD7B0 [libj9vrb29.so+0x1d7b0])
(0x00003FFF7CBC1CC4 [libj9vrb29.so+0x21cc4])
(0x00003FFF7DB4259C [libj9jit29.so+0x94259c])
(0x00003FFF7DB49108 [libj9jit29.so+0x949108])
(0x00003FFF7DB63B5C [libj9jit29.so+0x963b5c])
(0x00003FFF7E51EA8C [libj9vm29.so+0x8ea8c])
(0x00003FFF7E52BB28 [libj9vm29.so+0x9bb28])
(0x00003FFF7E52E43C [libj9vm29.so+0x9e43c])
(0x00003FFF7E576240 [libj9vm29.so+0xe6240])
(0x00003FFF7E576894 [libj9vm29.so+0xe6894])
(0x00003FFF7E576C34 [libj9vm29.so+0xe6c34])
(0x00003FFF7DB4900C [libj9jit29.so+0x94900c])
(0x00003FFF7DB63B5C [libj9jit29.so+0x963b5c])
(0x00003FFF7E5250C8 [libj9vm29.so+0x950c8])
(0x00003FFF7E541D60 [libj9vm29.so+0xb1d60])
(0x00003FFF7E59F7D8 [libj9vm29.so+0x10f7d8])
(0x00003FFF7E2CE89C [libj9prt29.so+0x2e89c])
(0x00003FFF7E59F8B8 [libj9vm29.so+0x10f8b8])
(0x00003FFF7E54496C [libj9vm29.so+0xb496c])
(0x00003FFF7E5412C4 [libj9vm29.so+0xb12c4])
(0x00003FFF7F21C43C [libjli.so+0xc43c])
(0x00003FFF7EF88070 [libpthread.so.0+0x8070])
clone+0x98 (0x00003FFF7F153A70 [libc.so.6+0x123a70])
```

**Comment by fjeremic** [comment]
I'm wondering if this failure is the same one as seen in https://github.com/eclipse/openj9/issues/2821#issuecomment-422138973. Looks sort of similar.

**Comment by irinarada** [comment]
@IBMJimmyk - would you please have a look, another possible Power nestamates issue? Thanks!

**Comment by pshipton** [comment]
Latest results for last night https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_ppc-64_cmprssptrs_le/20/tapResults/

Note one of the crashes is in the CondyPrimitive_1 testing.

**Comment by irinarada** [comment]
Condy issue @aviansie-ben would you please have a look?

**Comment by IBMJimmyk** [comment]
I was able to reproduce this crash on a local machine.

0x0000772ed802b814 {libj9vrb29.so}{jitWalkFrame} [0x772eda4bcb10]
0x0000772ed802d7b0 {libj9vrb29.so}{jitWalkStackFramesVerbose} [0x772eda4bcc20]
0x0000772ed8031cc4 {libj9vrb29.so}{walkStackFramesVerbose} [0x772eda4bcd20]
0x0000772ed8fc25dc {libj9jit29.so}{jitCheckScavengeOnResolve} [0x772eda4bcec0]
0x0000772ed8fc9148 {libj9jit29.so}{old_slow_jitResolveStaticMethod} [0x772eda4bd200]
0x0000772ed8fe3b9c {libj9jit29.so}{jitResolveStaticMethod} [0x772eda4bd250]
0x0000772ed9a9ea8c {libj9vm29.so}{sendLoadClass} [0x772eda4bd6d0]
0x0000772ed9aabb28 {libj9vm29.so}{internalFindClassInModule} [0x772eda4bd7d0]
0x0000772ed9aae43c {libj9vm29.so}{internalFindClassUTF8} [0x772eda4bd8c0]
0x0000772ed9af6240 {libj9vm29.so}{resolveClassRef} [0x772eda4bd8e0]
0x0000772ed9af6894 {libj9vm29.so}{resolveStaticMethodRefInto} [0x772eda4bd9e0]
0x0000772ed9af6c34 {libj9vm29.so}{resolveStaticMethodRef} [0x772eda4bdad0]
0x0000772ed8fc904c {libj9jit29.so}{old_slow_jitResolveStaticMethod} [0x772eda4bdb20]
0x0000772ed8fe3b9c {libj9jit29.so}{jitResolveStaticMethod} [0x772eda4bdb70]
0x0000772ed9aa50c8 {libj9vm29.so}{runCallInMethod} [0x772eda4bdff0]
0x0000772ed9ac1d60 {libj9vm29.so}{gpProtectedRunCallInMethod} [0x772eda4be100]
0x0000772ed9b1f7d8 {libj9vm29.so}{signalProtectAndRunGlue} [0x772eda4be130]
0x0000772ed97ee89c {libj9prt29.so}{omrsig_protect} [0x772eda4be150]
0x0000772ed9b1f8b8 {libj9vm29.so}{gpProtectAndRun} [0x772eda4be500]
0x0000772ed9ac496c {libj9vm29.so}{gpCheckCallin} [0x772eda4be5b0]
0x0000772ed9ac12c4 {libj9vm29.so}{callStaticVoidMethod} [0x772eda4be610]
0x0000772eda8187c0 {libjli.so}{JavaMain} [0x772eda4be640]
0x0000772eda50885c {libpthread.so.0}{start_thread} [0x772eda4be720]
0x0000772eda729028 {libc.so.6}{???} [0x772eda4bea30]

Somewhere in the middle of jitWalkFrame it tries to load from 0x0 and crashes.

**Comment by aviansie-ben** [comment]
Was finally able to reproduce this problem myself locally. Seems that this problematic behaviour was exposed by (but not caused by) ibmruntimes/openj9-openjdk-jdk11#21. I can't get any segfaults without that commit. As such, this is looking to be unrelated to constant dynamic at all, since javac does not yet use that feature AFAIK.

**Comment by pshipton** [comment]
although javac with target 11 does enable nestmates use in the class library code.

**Comment by IBMJimmyk** [comment]
Yes, I'm currently taking a look at it from the angle of a potential problem with the nestmates changes.

**Comment by IBMJimmyk** [comment]
I think I found the problem.

For the invokevirtual nestmate work on Power I did there was one part that I wasn't 100% confident in. It was a part related to GCmaps. Fortunately, it was part of an optimized later revision of the feature so I tried using an older version I had wrote. The older version seems to work. jit_jitt_0 had a near 100% failure rate before but now I got 5 passes in a row.

**Comment by IBMJimmyk** [comment]
I also tried out the CondyPrimitive_1. Similar to jit_jitt_0 it used to have a 100% failure rate but I was able to get 5 passes in a row using the older version of the invokevirtual nestmates change.

**Comment by IBMJimmyk** [comment]
I've hopefully fixed the problem with the GC map. I just made the PR with the fix ihere:
https://github.com/eclipse/openj9/pull/2972

**Comment by irinarada** [comment]
Is this fixed by Jimmy's 2972?
