### ISSUE TITLE
Separate binaries (libjvm.so, etc.) required for Java 18.3

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#293]
This issue was brought up during investigation of `Java 18.3` build against `openj9-openjdk-jdk18.3`.

Current `OpenJ9 Java 9` builds doesn't have `classlib.properties` file to specify vm shape value, and `J2SE_SHAPE_LATEST` is defined to latest VM shape `J2SE_SHAPE_B165`. However `Java 18.3` build requires a newer shape value `J2SE_SHAPE_B1803` for `J2SE_SHAPE_LATEST`.
Hence separated binaries are required to accommodate both `Java 9 & 18.3` builds. 

`JAVA_SPEC_VERSION` seems a good candidate flag to differentiate these Java builds.

fyi @DanHeidinga @pshipton @adamfarley

**Comment by DanHeidinga** [comment]
Two thoughts:

1. Can we add a classlib.properties file temporarily?  This could be generated by the build scripts in the 18.3 openjdk closed/ directory.

1. Can we pass in an environment variable or similar to pick the shape?

Just as we've continued to use runtime checks for java 8 vs 9 to enable easy testing / validation that the VM works with both releases, we should continue with that approach for 18.3 unless there's a compelling reason we can't.

When the binaries need to be different, that should be driven as much as possible by the OpenJDK repo OpenJ9 is being built with.  i.e.: the 18.3 openjdk mirror should indicate that it wants an 18.3 openj9 jvm.

Hope that's clear.

**Comment by pshipton** [comment]
Besides classlib.properties, which requires having a file with the correct contents put in the right place, the VM can peak at some file in the build structure to determine between Java 9 & 18.3 automatically. I checked libjava.so but I don't find any new symbols in Java 18.3 atm, likely later it coiuld be used. If nothing else, rt.jar can be used for now, as we can use the java preprocessor to include a file specific to Java 18.3.

**Comment by JasonFengJ9** [comment]
Adding a `classlib.properties` file seems a reasonable solution which is consistent with `Java 8 & 9`.

This issue can be resolved along with https://github.com/eclipse/openj9/issues/292 after confirming that `Java 18.3` works with a `classlib.properties`.

**Comment by pshipton** [comment]
classlib.properties works well for us, but I recall having problems in the past with missing or incorrectly configured classlib.properties files, which then requires us to debug the issue and figure out what is wrong. Automatic detection has the benefit of just working.

**Comment by JasonFengJ9** [comment]
@pshipton just suggested to use `release` file coming with OpenJDK instead which has following content:
````
IMPLEMENTOR="N/A"
JAVA_VERSION="10"
````
J9 can read the file, get the value for `JAVA_VERSION`, if it is not `9`, then it is `Java 18.3`.
