### ISSUE TITLE
Remove dependency on com.ibm.tools.attach.target.AttachHandler in TestUtilities

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2938]
TargetVM and TargetManager use internal attach API API such as `AttachHandler.getVmId()`. This makes life difficult for tests which don't have these classes.
Use reflection access these methods.

@llxia @pshipton FYI.

**Comment by llxia** [comment]
Thanks, Peter :)

**Comment by pdbain-ibm** [comment]
Completed via issue #2962.
