### ISSUE TITLE
cmdline_fetchRedirectorDllDir() is hard coding bin/j9vm, causing test failure

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#2946]
A couple of native tests have the code:

```	if (j9sl_open_shared_library(libjvmPath, &handle, J9PORT_SLOPEN_DECORATE)) {
		j9tty_printf(PORTLIB, "Failed to open JVM DLL: %s (%s)\n", J9_VM_DLL_NAME, j9error_last_error_message());
		rc = FAIL;
		goto cleanup;
	}
```
Using `J9_VM_DLL_NAME` create incorrect message.

**Comment by sophia-guo** [comment]
FYI @pshipton

**Comment by keithc-ca** [comment]
I see j9vm on Linux and Windows in my openj9 builds: I must misunderstand what you're saying.
Got a link to a failing test?

**Comment by keithc-ca** [comment]
Is it failing to find some test-specific shared library? If so, it shouldn't be expecting them to be in the same places as JVM shared libraries.

**Comment by pshipton** [comment]
@sophia-guo can provide more details about what is failing if necessary. Anything that calls cmdline_fetchRedirectorDllDir(), such as shrtest, thrstatetest, vmLifecyleTests.

Its looking for libj9vm.so in bin/j9vm (as hardcoded in cmdline_fetchRedirectorDllDir()) . When you see j9vm on Linux is it under bin?

and when it fails, the error message is wrong as it says it can't find libj9vm29.so when it was trying to load libjvm.so

**Comment by keithc-ca** [comment]
Ok, I think I understand now. On Windows, I see
```
jdk8/jre/bin/j9vm/jvm.dll
jdk10/bin/j9vm/jvm.dll
```
and on Linux I see
```
jdk8/jre/lib/amd64/j9vm/libjvm.so
jdk10/lib/j9vm/libjvm.so
```
so it might be as simple as swapping "lib" for "bin" on non-Windows platforms.

**Comment by pshipton** [comment]
swapping "lib" for "bin" on non-Windows platforms won't fix jdk8, but will for jdk9 and above
