### ISSUE TITLE
Nestmates visibility exception handling

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse/openj9#2948]
https://github.com/eclipse/openj9/blob/685530b8f8fe667e0651ed60c750b6c52921f827/runtime/vm/lookupmethod.c#L204-L209

`checkVisibility` could have set non `illegalAccessError` during validation of class nesthost, this exception might be overwritten by the caller of `processMethod` and result in a different exception type being thrown. 

We should reconsider how to handle the exception propagation of `checkVisibility(...)` call.

**Comment by gacholio** [comment]
This is a much larger issue - prior to nestmates, checkVisibility was not an HCR point, now it is. Also, it appears the flags being passed/used in this code are wildly incompatible (call assumes J9_LOOK_ flags, but is getting J9_RESOLVE_ flags in many cases - there is no compatibility between the two).

**Comment by gacholio** [comment]
I've found at least one other place not doing it. I'm working on a large fix.
