### ISSUE TITLE
Remove or hide unsupported tools.

### ISSUE THREAD

**Issue by whitingjr** [eclipse/openj9#295]
I tried using a couple of tools bundled in the download. These didn't work. Discussion on the [forums](http://dev.eclipse.org/mhonarc/lists/openj9-dev/msg00002.html) mentions these (amongst others) are unsupported.

 To avoid confusion can the tools be removed or hidden ?

**Comment by pshipton** [comment]
I think they have already been removed via ibmruntimes/openj9-openjdk-jdk9#54
I don't see the unsupported tools in a fresh OpenJ9 build. If the builds on AdoptOpenJDK.net still have them it needs to be refreshed, you might need to open an issue there. I'll have to download and look.

**Comment by pshipton** [comment]
Actually we can tell from the timestamp on the AdoptOpenJDK.net site - 16 September 2017. The latest build it quite old.

**Comment by pshipton** [comment]
@whitingjr I'll leave it to you if you want to open an Issue at https://github.com/AdoptOpenJDK/openjdk-build/issues to request a refresh of OpenJ9. I'm going to close this one since OpenJ9 itself is fine. Please go ahead if you want to open another Issue here to request support for the tools.
