### ISSUE TITLE
Options starting with -XX: should not be ignored

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2977]
OpenJ9 ignores any options starting with -XX: that it doesn't understand. While this may be useful if trying to use an OpenJDK command line containing options that don't apply to OpenJ9, it makes it hard to tell when an option starting with -XX: is valid for OpenJ9 or not. OpenJDK does not have this behavior.

https://github.com/eclipse/openj9/blob/a65785ba6a75ca53bdb15921808bb339479440c4/runtime/vm/jvminit.c#L184

I suggest changing the OpenJ9 default behavior so unrecognized options starting with -XX: cause an error. There is a option -XX:+IgnoreUnrecognizedVMOptions that can be used to ignore any unrecognized (top level) option, which includes those starting with -XX:.

Another option could be added if necessary to just ignore unrecognized options starting with -XX:

**Comment by DanHeidinga** [comment]
This has been requested previously: https://github.com/eclipse/openj9/issues/526

> Another option could be added if necessary to just ignore unrecognized options starting with -XX:

OpenJ9's current behaviour makes migration easier but is less explicit for users that want to be notified about the mismatch.

I think the new option is the right path forward as it allows existing users to maintain the behaviour they've come to know and love(?) without requiring them to modify their existing commandlines.

**Comment by pdbain-ibm** [comment]
I was palnning to do some argument hacking.  Would you like me to work on this?

**Comment by luchsh** [comment]
From a user's perspective, the current behavior is too confusing.
HotSpot has got an option '-XX:+IgnoreUnrecognizedVMOptions', can OpenJ9 work in the same way?
or maybe you can create a whitelist of valid '-XX' options for compatibility, and report errors when cannot find a match in the whitelist.

**Comment by AidanHa** [comment]
Hello, I will be working on this issue.

For now, I will implement the new option, where -XX:-IgnoreUnrecognizedVMOptions reports all unrecognized options, and -XX:+IgnoreUnrecognizedVMOptions ignores them.

I'm still a bit confused on how the current options work, but I will figure it out...

**Comment by pshipton** [comment]
Note https://github.com/eclipse/openj9/issues/2977#issuecomment-423578791, we want to introduce a new option here, rather than changing the behavior of IgnoreUnrecognizedVMOptions.

> I think the new option is the right path forward as it allows existing users to maintain the behaviour they've come to know and love(?) without requiring them to modify their existing commandlines.

**Comment by AidanHa** [comment]
Hello, if I were to remove line 184, I get the following error while building the jdk:

![image](https://user-images.githubusercontent.com/33072072/51499933-29810080-1d9a-11e9-9507-da0e4e7e3045.png)

where -XX:ThreadStackSize is not recognized (and it is now not ignored by default). What action should I take from here? Should I be modifying the make file and remove -XXThreadStackSize?

**Comment by pshipton** [comment]
Since ignoring -XX: options should be enabled by default, the build using -XX:ThreadStackSize shouldn't be a problem.
