### ISSUE TITLE
cpu entitlement when hypervisor is present 

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#30]
I believe there are two problems in JIT with respect to getting cpu entitlement information from hypervisor:

1) I noticed this code in `TR_CpuEntitlement::computeAndCacheCpuEntitlement`
```
   if (_numTargetCpu == 0)
      _numTargetCpu = 1; // some correction in case we get it wrong
   if (isHypervisorPresent())
      {
      _guestCpuEntitlement = computeGuestCpuEntitlement();
      // If the number of target CPUs is smaller (bind the JVM to a subset of CPUs), use that value
      if (_numTargetCpu < _guestCpuEntitlement || _guestCpuEntitlement <= 0)
```
It looks like _guestCpuEntitlement is in percentage, but _numTargetCpu is not. The condition `_numTargetCpu < _guestCpuEntitlement` is likely to be comparing incorrect values in that case.

2) Secondly, it appears `TR_CpuEntitlement::isHypervisorPresent` will always returns false, no matter what.
```
bool TR_CpuEntitlement::isHypervisorPresent()
   {
   if (_hypervisorPresent == TR_maybe)
      {
      // Caching works because we don't expect the information to change
      // However, we must call this after portlib is up and running
      PORT_ACCESS_FROM_JITCONFIG(_jitConfig);
      if (j9hypervisor_hypervisor_present() > 0) // J9HYPERVISOR_NOT_PRESENT/J9HYPERVISOR_PRESENT/J9PORT_ERROR_HYPERVISOR_UNSUPPORTED
         {
         _hypervisorPresent = TR_yes;
         }
      else
         {
         _hypervisorPresent = TR_no;
         }
      }
   return (_hypervisorPresent == TR_yes);
   }
```
`_hypervisorPresent` gets a default value of `TR_no`. I don't see it ever getting set to `TR_maybe` which means `isHypervisorPresent` will always return `false`.

I hope I have not missed anything here.
@mpirvu, any idea why is it like this? It appears this is just dead code right now.

**Comment by mpirvu** [comment]
Indeed, `_hypervisorPresent` is not initialized at all. It needs to get initialized to `TR_maybe` in `void init(J9JITConfig *jitConfig)` before calling `computeAndCacheCpuEntitlement()`

**Comment by mpirvu** [comment]
Regarding the first problem, yes the code needs to be changed to read
    `if (_numTargetCpu * 100 < _guestCpuEntitlement || _guestCpuEntitlement <= 0)`

**Comment by ashu-mehra** [comment]
@mpirvu thanks for confirming. I will open a PR to fix the two issues.
