### ISSUE TITLE
Update InvokeDynamic Error wrapping

### ISSUE THREAD

**Issue by fengxue-IS** [eclipse/openj9#3001]
JVMS JDK11 Section 5.4.3.6 'Dynamically-Computed Constant and Call Site Resolution' have updated the requirement of resolution exception/error should be handled.

`resolveInvokeDynamic(...)` method need to be updated to match the specification

**Comment by fengxue-IS** [comment]
> Invokedynamic resolution needs the same change in JDK11.
> This is a change in behaviour for indy pre-jdk11.
@DanHeidinga does this change also apply to JDK8 or is a runtime check need?

**Comment by DanHeidinga** [comment]
I think this can be handled with the java preprocessor so no runtime check is required, but yes to JPP ifdefs.
