### ISSUE TITLE
SIGPIPE received consistently with JDK11 Linux x64 sdk

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#3002]
For `TestJlmRemoteMemoryAuth` and `TestIBMJlmRemoteClassAuth` tests, the server process that runs a mini-mix load receives a `SIGPIPE` and ends unexpectedly (server process ends with `exit code 141` triggering failure of the test). 

**JDK11 version where the issue is seen:** 
```
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc.jenkins.Build-JDK11-linuxx86-64)
Eclipse OpenJ9 VM (build master-88b535a, JRE 11 Linux amd64-64-Bit 20180924_82 (JIT enabled, AOT enabled)
OpenJ9   - 88b535a
OMR      - fcbe08d
JCL      - afdb742 based on jdk-11+28)
```
**Build link:** 
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK11-linux_x86-64/18/tapResults/

**Reproduced in Grinder:** https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/156/console

**Note**
1) Running the server process and client (proxy) process locally shows that the server process ends unexpectedly causing 'broken pipe' for the client. 

2) Running the server process by itself (without running any client) does not cause any issue - the server process (mini-mix load) finishes normally. 

**How to reproduce**
1) Using Grinder : simply rebuild the Grinder build (https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/156/console) with your jdk11 sdk zip in the `CUSTOMIZED_SDK_URL` field. 
2) Locally (using a farm machine): The "server" and the "client" could be run on a local farm Linux machine using the following command lines: 

**Server**: 
```
$JAVA_HOME/bin/java -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.ssl.need.client.auth=true -Djavax.net.ssl.keyStore=/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.trustStore=/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.keyStoreType=JKS -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.keyStorePassword=passphrase -Djavax.net.ssl.trustStorePassword=passphrase -Dcom.sun.management.jmxremote.password.file=/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/jmxremote.password -classpath /team/mesbaha/jdk11jlmfailure/stf/stf.core/bin:/team/mesbaha/jdk11jlmfailure/stf/stf.load/bin:/team/mesbaha/systemtest_prereqs/log4j-2.3/log4j-api-2.3.jar:/team/mesbaha/systemtest_prereqs/log4j-2.3/log4j-core-2.3.jar:/team/mesbaha/systemtest_prereqs/junit-4.12/junit-4.12.jar:/team/mesbaha/systemtest_prereqs/junit-4.12/hamcrest-core-1.3.jar:/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.lang/bin:/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.util/bin:/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.math/bin net.adoptopenjdk.loadTest.LoadTest -resultsDir /team/mesbaha/jdk11jlmfailure/results -resultsPrefix 3.LT1. -timeLimit 30m -abortAtFailureLimit -1 -reportFailureLimit 1 -maxTotalLogFileSpace 200M -maxSingleLogSize 1/25 -suite.mini-mix.totalNumberTests 300000 -suite.mini-mix.inventoryFile /team/mesbaha/jdk11jlmfailure/results/3.LT1.inventory/openjdk.test.load/config/inventories/mix/mini-mix.xml -suite.mini-mix.inventoryExcludeFile /team/mesbaha/jdk11jlmfailure/results/3.LT1.inventory/openjdk.test.load/config/inventories/mix/mini-mix_exclude.xml -suite.mini-mix.threadCount 30 -suite.mini-mix.selection random -suite.mini-mix.seed -1 -suite.mini-mix.repeatCount 1 -suite.mini-mix.thinkingTime 0ms..0ms
```

**Client:** 
```
$JAVA_HOME/bin/../bin/java -Xdump:java:events=throw,file=/team/mesbaha/jdk11jlmfailure/results/javacore_smem_proxy.%Y%m%d.%H%M%S.%pid.%seq.txt,filter=java.lang.IllegalArgumentException -Djavax.net.ssl.keyStore=/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.trustStore=/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/testkeys -Djavax.net.ssl.keyStoreType=JKS -Djavax.net.ssl.trustStoreType=JKS -Djavax.net.ssl.keyStorePassword=passphrase -Djavax.net.ssl.trustStorePassword=passphrase -Dcom.sun.management.jmxremote.password.file=/team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/src/test.jlm/net/adoptopenjdk/test/jlm/jmxremote.password -classpath /team/mesbaha/jdk11jlmfailure/openjdk-systemtest/openjdk.test.jlm/bin:/team/mesbaha/systemtest_prereqs/junit-4.12/junit-4.12.jar net.adoptopenjdk.test.jlm.remote.MemoryProfiler proxy /team/mesbaha/jdk11jlmfailure/results/smem_proxy.log /team/mesbaha/jdk11jlmfailure/results/smem_proxy.csv auth controlRole control1 localhost 1234
```
* Please set JAVA_HOME to your JDK 11 SDK. 

Running the Server program in `gdb` will yield the following output: 

```
Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fff900b4700 (LWP 25322)]
0x00007ffff79002ab in send () from /lib64/libc.so.6
```

**Comment by fjeremic** [comment]
Very likely related to #2965 and the fix for #2871. @babsingh @pdbain-ibm @pshipton FYI.

**Comment by JasonFengJ9** [comment]
The PR fix has been merged, @Mesbah-Alam please re-run the test to check if the failure still presents.

**Comment by fjeremic** [comment]
> The PR fix has been merged, @Mesbah-Alam please re-run the test to check if the failure still presents.

Which PR fixed this issue? Can you reference it here?

**Comment by JasonFengJ9** [comment]
>Very likely related to #2965 and the fix for #2871.
The PR specified has been merged.

Just additional notes: 
1. The initial failure and grinder were around Sept. 18th;
2. There was no `SIGPIPE` in result file;
3. `SIGPIPE` was seen on originator local run;
4. @Mesbah-Alam is checking if same `SIGPIPE` occurs on `RI`.

**Comment by babsingh** [comment]
> Which PR fixed this issue? Can you reference it here?

PR which fixes this issue - https://github.com/eclipse/openj9/pull/2965.

**Comment by Mesbah-Alam** [comment]
Some points to note: 

1) `SIGPIPE` can only be seen when I ran the server process locally with`gdb`. 
2) Running locally without gdb will result in the server exiting with an exit code `exit code 141` ("Broken pipe: write to pipe with no readers"). 
3) "The initial failure and grinder were around Sept. 18th" - correct, but the local run where `SIGPIPE` is seen consistently is from a much later build (taken from https://ci.eclipse.org/openj9/view/Build/): 
```
openjdk version "11-internal" 2018-09-25
OpenJDK Runtime Environment (build 11-internal+0-adhoc.jenkins.Build-JDK11-linuxx86-64)
Eclipse OpenJ9 VM (build master-88b535a, JRE 11 Linux amd64-64-Bit 20180924_82 (JIT enabled, AOT enabled)
OpenJ9   - 88b535a
OMR      - fcbe08d
JCL      - afdb742 based on jdk-11+28)
```
- This VM should contain fix https://github.com/eclipse/openj9/pull/2965 - yet SIGPIPE continues to be seen. 

4) The failure is not reproducible with the following RI: 
```
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+27)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+27, mixed mode)
```

**Comment by Mesbah-Alam** [comment]
"I also tried running the above testcase locally. I couldn't reproduce the issue." - Could you please share how you tried to run it locally? Did you run the server and client command lines provided in the PR description? Which JDK11 version did you use?

**Comment by fjeremic** [comment]
@Mesbah-Alam FYI if you select some text in GitHub and press the `R` hotkey it will quote the selected text in the comment box. Alternatively you can copy and paste the text and prepend it with a `>` to insert a quote. It looks like this:

> I also tried running the above testcase locally. I couldn't reproduce the issue.

Could you please share how you tried to run it locally? Did you run t...

**Comment by babsingh** [comment]
I started the server and the client simultaneously on the same machine. I used the following JDK version:
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment (build 11-adhoc.j9build.Build-JDK11-linuxx86-64)
Eclipse OpenJ9 VM (build 96d25fe, JRE 11 Linux amd64-64-Bit 20180925_53 (JIT enabled, AOT enabled)
OpenJ9   - c96d25fe
OMR      - 7e32abc4
JCL      - cd859013 based on jdk-11+28)
```

**Comment by Mesbah-Alam** [comment]
@babsingh - I was unable to locally reproduce the defect using the latest SDK (https://ci.eclipse.org/openj9/view/Build/job/Build-JDK11-linux_x86-64/lastSuccessfulBuild/artifact/OpenJ9-JDK11-linux_x86-64-201825090023.tar.gz). 

Grinder is back, so I have launched a new test there as well - if that goes well, I'll close this PR and include back the failing tests. 
Grinder: 
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/182/console

**Comment by Mesbah-Alam** [comment]
The issue seems to have gone away with the latest SDK. I am cancelling this defect https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/184/console
