### ISSUE TITLE
Machines sitting idle, but job waiting to run

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3009]
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Build-Test-JDK8-win_x86/detail/Pipeline-Build-Test-JDK8-win_x86/252/pipeline/57/

waiting for Test-sanity.functional-JDK8-win_x86 to run

Part of https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Build-Test-All/detail/Pipeline-Build-Test-All/219/pipeline

@AdamBrousseau

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-win_x86/65/console
Hung on master for some reason

**Comment by AdamBrousseau** [comment]
Possibly something like this
[Pipelines hang on master before running anythin](https://issues.jenkins-ci.org/browse/JENKINS-45644)
This was from July '17 but the situation was similar and the response was `Without steps to reproduce from scratch this cannot be analyzed.`

Another one hanging here
https://ci.eclipse.org/openj9/job/Check_AIX_PDP_VPN/5288/console
```

Started by timer
Running in Durability level: PERFORMANCE_OPTIMIZED
[Pipeline] node
Running on proxy_worker in /home/jenkins/jenkins-agent/workspace/Check_AIX_PDP_VPN@3
```

**Comment by pshipton** [comment]
Obsolete.
