### ISSUE TITLE
Test-extended.functional-JDK10 JDK11 jsr292 failures across platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3037]
com.ibm.j9.jsr292.LookupAPITests_AccessClass.test_AccessNestedClass_ProtectedAccess_InterfaceLookup_DiffPackage
com.ibm.j9.jsr292.LookupAPITests_AccessClass.test_AccessNestedClass_ProtectedAccess_InterfaceLookup_DiffPackage
com.ibm.j9.jsr292.LookupAPITests_AccessClass.test_AccessNestedClass_ProtectedAccess_InterfaceLookup_DiffPackage

Error Message
The protected class shouldn't be accessible to the lookup interface from a different package

com.ibm.j9.jsr292.LookupAPITests_FindClass.test_FindNestClass_ProtectedAccess_InterfaceLookup_DiffPackage
com.ibm.j9.jsr292.LookupAPITests_FindClass.test_FindNestClass_ProtectedAccess_InterfaceLookup_DiffPackage
com.ibm.j9.jsr292.LookupAPITests_FindClass.test_FindNestClass_ProtectedAccess_InterfaceLookup_DiffPackage

Error Message
The class is not supposed to be found

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-win_x86-64_cmprssptrs/23/
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_390-64_cmprssptrs/26/
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_x86-64_cmprssptrs/77/
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-aix_ppc-64_cmprssptrs/22/
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-linux_ppc-64_cmprssptrs_le/74/
etc
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/220/

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by pdbain-ibm** [comment]
Will investigate.  @DanHeidinga FYI.

**Comment by DanHeidinga** [comment]
See previous investigations into this: https://github.com/eclipse/openj9/issues/636

**Comment by DanHeidinga** [comment]
And the recently merged change which broke this test: https://github.com/eclipse/openj9/pull/2964

**Comment by DanHeidinga** [comment]
Ok, let's check the spec on this again.  JVMS "5.4.4 Access Control" states:
>A class or interface C is accessible to a class or interface D if and only if one of the following is true:
• C is public, and a member of the same run-time module as D (§5.3.6).
• C is public, and a member of a different run-time module than D, and C's run- time module is read by D's run-time module, and C's run-time module exports C's run-time package to D's run-time module.
• C is not public, and C and D are members of the same run-time package.

http://cr.openjdk.java.net/~iris/se/11/latestSpec/java-se-11-jvms-draft-diffs.pdf

**Comment by DanHeidinga** [comment]
Based on that, our implementation is incorrect.  There should be two cases in that code:
1) When the targetClass is public, do the larger module related check
2) When targetClass is not public - check they are the same package and the lookup has package access

**Comment by pdbain-ibm** [comment]
Working on that now.

**Comment by pdbain-ibm** [comment]
Looks like a test bug: the same Jsr292 tests fail on OpenJDK Java 10:

> FAILED: test_FindNestClass_ProtectedAccess_InterfaceLookup_DiffPackage
> java.lang.AssertionError: The class is not supposed to be found
```
	 * Tell whether a class with package access is accessible to the lookup class
	 * from a different package.
```


> FAILED: test_AccessNestedClass_ProtectedAccess_InterfaceLookup_DiffPackage
> java.lang.AssertionError: The protected class shouldn't be accessible to the lookup interface from a different package
```
	 * Tell whether a class with protected access is accessible to the lookup
	 * which is actually an interface from a different package.
```
