### ISSUE TITLE
Test-extended.system-JDK8-aix_ppc-64_cmprssptrs SharedClassesWorkload_0 Package already defined

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3038]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-aix_ppc-64_cmprssptrs/45/

See also #3037

STF 04:11:31.613 - Monitoring processes: SCL2
STF 04:11:38.436 - **FAILED** Process SCL2 ended with exit code (1) and not the expected exit code/s (0)
```
>>> Captured test output >>>
Test failed:
java.lang.IllegalArgumentException: Package net.adoptopenjdk.test.lang.java7.ProjectCoin already defined.
	at java.lang.ClassLoader.definePackage(ClassLoader.java:1264)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:748)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:575)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:934)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:879)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:862)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:340)
	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:54)
	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:813)
<<<
```

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by DanHeidinga** [comment]
This is an odd one.  Documenting the changes in this build for when the jenkins build is gone from history:
```
Enable linkage creation on OSX in CodeGenerator (detail / githubweb)
Remove duplicate definition of VERBOSE_DYNLOAD (detail / githubweb)
Remove verbose.h (detail / githubweb)
Follow up for initial SATB barrier changes (detail / githubweb)
Use reflection to access attach API internal APIs (detail / githubweb)
update asm-7.0 to latest version (detail / githubweb)
Remove old OMR pipeline (detail / githubweb)
Handle 8-byte call in VPIC snippet for nestmates (detail / githubweb)
Mark VarHandle call sites with cannotAttemptOSR (detail / githubweb)
Fix package checking for array types (detail / githubweb)
Update resolveConstantDynamic Error wrapping (detail / githubweb)
Fix stack walker for new interface formats (detail / githubweb)
Save local connector address in Attach API code (detail / githubweb)
Fix access checking for protected classes (detail / githubweb)
```

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you test this as well when you have the fix in hand for 
https://github.com/eclipse/openj9/issues/3037 ?

**Comment by pdbain-ibm** [comment]
Tested and working with the current Java 11.  I'll test with Java 8 tomorrow.

**Comment by pdbain-ibm** [comment]
Note that the test for #3037 is on the test, not the VM.

**Comment by pshipton** [comment]
Another one https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_ppc-64_cmprssptrs_le/48

**Comment by pdbain-ibm** [comment]
Tested and working with the latest Eclipse CI build:
openjdk version "1.8.0_192-internal"
OpenJDK Runtime Environment (build 1.8.0_192-internal-jenkins_2018_09_27_04_24-b00)
Eclipse OpenJ9 VM (build master-a9a160d2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180927_481 (JIT enabled, AOT enabled)
OpenJ9   - a9a160d2
OMR      - 71c0c919
JCL      - 84cb836f680 based on jdk8u192-b03)

**Comment by pshipton** [comment]
> Tested and working with the latest Eclipse CI build

Not sure what this means. You've tested on Linux X. The test failed again in the overnight testing last night, using the same OpenJ9 sha. Likely the problem is intermittent or more likely to occur on AIX/PPC as this is where we've seen the failures.

```
03:54:27 [echoproperties] java8.Eclipse=OpenJ9 VM (build master-a9a160d, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20180927_668 (JIT enabled, AOT enabled)
03:54:27 [echoproperties] java8.JCL=- 84cb836 based on jdk8u192-b03)
03:54:27 [echoproperties] java8.JRE=1.8.0 Linux ppc64le-64-Bit Compressed References 20180927_668 (JIT enabled, AOT enabled)
03:54:27 [echoproperties] java8.OMR=- 71c0c91
03:54:27 [echoproperties] java8.OpenJ9=- a9a160d
03:54:27 [echoproperties] java8.OpenJDK=Runtime Environment (build 1.8.0_192-internal-jenkins_2018_09_27_04_33-b00)
```

**Comment by pdbain-ibm** [comment]
I am in the process of setting up testing on LinuxPPC.

**Comment by pdbain-ibm** [comment]
Tested with:
 openjdk version "1.8.0_192-internal"
OpenJDK Runtime Environment (build 1.8.0_192-internal-jenkins_2018_09_27_04_33-b00)
Eclipse OpenJ9 VM (build master-a9a160d, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20180927_668 (JIT enabled, AOT enabled)
OpenJ9   - a9a160d
OMR      - 71c0c91
JCL      - 84cb836 based on jdk8u192-b03)

2 successful runs so far, trying 10 runs.

@pshipton do you know the failure rate on this test?

**Comment by pshipton** [comment]
It failed the last 2 nights, first on aix and then on ppc le last night. Afaik we've never seen this failure before.

**Comment by pdbain-ibm** [comment]
I ran over a dozen times on PPC LE.  One failure.

**Comment by pshipton** [comment]
Fairly sure this is a a timing issue, the number of cpus and other things running on the machine likely affects it. Hopefully being able to repeat the failure is sufficient to determine what the problem is.

**Comment by pdbain-ibm** [comment]
Ran 50x on LinuxPPCLE Java 8, got one failure.  Ran 200x on Java 11, _no failures_.

Note that Java 8 and Java 11 have different implementatiobns of `definePackage()`:
```

		/*[IF Sidecar19-SE]*/
		if (packages.containsKey(name)) {
		/*[ELSE]		
		if (null != getPackage(name)) {
		/*[ENDIF]*/			
			/*[MSG "K0053", "Package {0} already defined."]*/
			throw new IllegalArgumentException(com.ibm.oti.util.Msg.getString("K0053", name)); //$NON-NLS-1$
		} else {
			Package newPackage = new Package(name, specTitle, specVersion, specVendor, implTitle, implVersion, implVendor, sealBase, this);
			packages.put(name, newPackage);
			return newPackage;
		}
```

**Comment by pshipton** [comment]
Thanks Peter, I'll re-target to the 0.11.0 release milestone.

**Comment by pdbain-ibm** [comment]
There is a bunch of unused code in the classloading classes which is confusing the issue. Opened 
https://github.com/eclipse/openj9/pull/3067 to remove same.

**Comment by pdbain-ibm** [comment]
Progress so far: I  instrumented the package methods in `ClassLoader`.  The exception is coming from `definePackage()`:
```
	synchronized(packages) {
		if (null != getPackage(name)) {
			// K0053 = Package {0} already defined.
			throw new IllegalArgumentException(com.ibm.oti.util.Msg.getString("K0053", name)); //$NON-NLS-1$
		} else {
			Package newPackage = new Package(name, specTitle, specVersion, specVendor, implTitle, implVersion, implVendor, sealBase, this);
			packages.put(name, newPackage);
			return newPackage;
		}
	}
```
This is the only method that adds entries to `packages`, a final private `Hashtable`.
In the failing case, `getPackage()` returns a value fro the local `packages`.
The instrumentation prints when `ProjectCoin` is added to `packages`.  This occurs only once, and `ProjectCoin` is _already in the Hashtable_.  Disabling compilation of `addPackage()` and of `Hashtbale` methods makes no difference.  I verified that the nominal entry in the Hashtable is in fact correct and there are no collisions.

Continuing to investigate...

**Comment by pdbain-ibm** [comment]
I was using `System.err.println()`, which wasn't active early enough and I lost ~50 calls to `definePackage()`.  Trying again with `VM.dumpString()`.

**Comment by pdbain-ibm** [comment]
Here is the problem: we are loading `net.adoptopenjdk.test.lang.java7.ProjectCoin.SwitchOnString` and `net.adoptopenjdk.test.lang.java7.ProjectCoin.TryWithResources` concurrently. The `AppClassLoader` is parallel capable and uses different lock objects for the two classes since they are different classes and can be loaded concurrently.  During the classloading, both threads try to update the package list, which causes an error.

**Comment by pdbain-ibm** [comment]
In both threads, `URLClassLoader.defineClass()` calls `getPackage(net.adoptopenjdk.test.lang.java7.ProjectCoin)`.  Both calls return null, which causes both threads to call `definePackage()`.

**Comment by pdbain-ibm** [comment]
Normally, the URLClassLoader catches and ignores the `IllegalArgumentException`.  However, the shared classes version of `defineClass()` is missing this try/catch block.

**Comment by pdbain-ibm** [comment]
Added the try/catch block and tested manually: 50/50 passed.  Running a personal build on linux ppcle and x86, sanity and extended tests.

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/120 fixes this problem for Java 8. Need to check if Java 9 and up need a similar change.

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you confirm whether this applies to JDK11?

**Comment by pshipton** [comment]
Yes it does apply, jdk11 also needs the fix.

**Comment by pshipton** [comment]
This doesn't need to be tracked against the 0.11.0 release as the release will not hold on this. Either the fix makes it in, or it doesn't and goes into the next release.

**Comment by pdbain-ibm** [comment]
IN RE 
https://github.com/eclipse/openj9/issues/3038#issuecomment-428297015, yes, but it's a narrow timing window and an unusual situation which is why we haven't seen it.

**Comment by pdbain-ibm** [comment]
Fixed in jdk8 by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/120
Fixed in jdk10 by https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/63
Fixed in jdk11 by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/38
Fixing in Java 12 and later by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/40 (in review now).
