### ISSUE TITLE
Test-extended.functional aix_ppc-64_cmprssptrs attachAPI staleDirectory failures

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3039]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/86/

org.openj9.test.attachAPI.TestAttachErrorHandling.testInitializationDeletesStaleDirectoryWithTextId

`stale target directory not removed /tmp/.com_ibm_tools_attach/foo`

org.openj9.test.attachAPI.TestAttachErrorHandling.testInitializationDeletesStaleDirectoryWithNumericId

`stale target directory not removed /tmp/.com_ibm_tools_attach/8192022`

**Comment by pshipton** [comment]
@pdbain-ibm

**Comment by pdbain-ibm** [comment]
Will investigate.

**Comment by pshipton** [comment]
Another one https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-aix_ppc-64_cmprssptrs/23

org.openj9.test.attachAPI.TestAttachErrorHandling.testInitializationDeletesStaleDirectoryWithTextId

`stale target directory not removed /tmp/.com_ibm_tools_attach/foo`

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK10-aix_ppc-64_cmprssptrs/73

org.openj9.test.attachAPI.TestAttachErrorHandling.testInitializationDeletesStaleDirectoryWithTextId

`stale target directory not removed /tmp/.com_ibm_tools_attach/foo`

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-aix_ppc-64_cmprssptrs/33

org.openj9.test.attachAPI.TestAttachErrorHandling.testInitializationDeletesStaleDirectoryWithTextId

`stale target directory not removed /tmp/.com_ibm_tools_attach/foo`

**Comment by pshipton** [comment]
Another one in PR testing
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/6/

**Comment by pshipton** [comment]
Another
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/103/

**Comment by pshipton** [comment]
The job shows:
`LIBPATH=/usr/java8_64/jre/lib/ppc64/j9vm:/usr/java8_64/jre/lib/ppc64:/usr/java8_64/jre/lib/ppc64/jli:/usr/java8_64/jre/../lib/ppc64:/usr/lib`

**Comment by pdbain-ibm** [comment]
The builds from 
https://github.com/eclipse/openj9/issues/3039#issuecomment-429286308 and 
https://github.com/eclipse/openj9/issues/3039#issuecomment-430193003
both ran on aix71-p8-1.  The logs for the older builds are missing.

**Comment by pshipton** [comment]
@pdbain-ibm you can check with @jdekonin and get access to the machine to take a look if needed.

**Comment by pshipton** [comment]
Another on aix71-p8-1
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/104

**Comment by pdbain-ibm** [comment]
@jdekonin would you please allow me to log in to aix71-p8-1, per @pshipton 's suggestion: 
https://github.com/eclipse/openj9/issues/3039#issuecomment-430277362.
Thank you

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/106
aix71-p8-1

**Comment by pdbain-ibm** [comment]
The problem is that attach API thinks that PID -1 is a valid process. IPC.java:
```
	public static boolean processExists(long pid) {
		int rc = processExistsImpl(pid);
		return (rc > 0);
	}
```
attach.c:
```
jint JNICALL
Java_com_ibm_tools_attach_target_IPC_processExistsImpl(JNIEnv *env, jclass clazz, jlong pid)
{
	jint rc;
	rc =  (jint) j9sysinfo_process_exists((UDATA) pid);
	return rc;
}
```
omrsysinfo.c:
```
intptr_t
omrsysinfo_process_exists(struct OMRPortLibrary *portLibrary, uintptr_t pid)
{
	intptr_t rc = 0;
	int result = 0;
	result = kill(pid, 0);
	if (0 == result) {
		rc = 1; 
	} else if (-1 == result) { /* note that kill() returns only 0 or -1 */
		if (errno == ESRCH) {
			rc = 0;
		} else if (errno == EPERM) {
			rc = 1;
		} else {
			rc = -1;
		}
	}
	return rc;
}
```

**Comment by pdbain-ibm** [comment]
from `man kill(2)`: 
```     If pid is -1:
             If the user has super-user privileges, the signal is sent to all processes excluding system processes and the process sending the
             signal.  If the user is not the super user, the signal is sent to all processes with the same uid as the user, excluding the
             process sending the signal.  No error is returned if any process could be signaled.

     For compatibility with System V, if the process number is negative but not -1, the signal is sent to all processes whose process group ID
     is equal to the absolute value of the process number.  This is a variant of killpg(2).
```
`IPC_processExistsImpl` should check for pid=-1.
