### ISSUE TITLE
JTReg test: java/lang/Class/forName/NonJavaNames.sh.NonJavaNames fails in openj9

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#3048]
JTReg Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/Class/forName/NonJavaNames.sh is failing in openj9

Error evaluating expression: invalid boolean value: `null' for expression `vm.graal.enabled'
java/lang/Class/GetPackageBootLoaderChildLayer.java: Exercise Class.getPackage on a class defined to the boot loader but in a module that is in a child layer rather than the boot layer

For failed test report with exception and log is attached here 
[JTreport_NonJavaNames.sh.NonJavaNames.tar.gz](https://github.com/eclipse/openj9/files/2423585/JTreport_NonJavaNames.sh.NonJavaNames.tar.gz)

This test passes against Hotspot. Build used ...
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by pshipton** [comment]
The failure seems related to the following in the test class. I'm not sure what is being tested for this. There is no system property vm.graal.enabled in an OpenJDK build.

` * @requires !vm.graal.enabled`

**Comment by pshipton** [comment]
I found https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/e4b4f667a1a863204b9531bdd3ab15d5155c8fe2/test/jtreg-ext/requires/VMProps.java#L94

@archanaNogriya can you please debug the test harness and see why the requires property isn't getting set.

**Comment by pshipton** [comment]
Also note https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/e4b4f667a1a863204b9531bdd3ab15d5155c8fe2/test/jdk/TEST.ROOT#L47

**Comment by archanaNogriya** [comment]
@pshipton I will get back to you once I get through debugging.

**Comment by pdbain-ibm** [comment]
@archanaNogriya Any progress on this?

**Comment by archanaNogriya** [comment]
I have not looked into this issue after my last update, I was pulled into other priority work since then.

**Comment by ben-walsh** [comment]
I think this issue can be closed out now. My PRs (https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/88, https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/145 and https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/31) have allowed us to get to the underlying problems (which I've raised an issue for https://github.com/eclipse/openj9/issues/5225). Also issue https://github.com/eclipse/openj9/issues/5274.
