### ISSUE TITLE
JTReg Test : jdk/java/lang/Class/forName/arrayClass/ExceedMaxDim.java.ExceedMaxDim fails against openj9 

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#3049]
Jtreg test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/Class/forName/arrayClass/ExceedMaxDim.java fails in openj9.

Exception is causing in here beause it is not able to create an array
 public class ExceedMaxDim {
                             //0123456789012345678901234567890123456789
    private String brackets = "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[" +
                              "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[" +
                              "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[" +
                              "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[" +
                              "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[" +
                              "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[" +
                              "[[[[[[[[[[[[[[";
    private String name254 = brackets + "Ljava.lang.String;";
    private String name255 = "[" + name254;
    private String name256 = "[" + name255;
    private String name1 = "[Ljava.lang.String;";

Exception is 
java.lang.String;
java.lang.RuntimeException: Test failed, was able to create array with dim > 255. See log for details.
	at ExceedMaxDim.main(ExceedMaxDim.java:71)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test failed, was able to create array with dim > 255. See log for details.
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Test failed, was able to create array with dim > 255. See log for details.
----------rerun:(21/1571)*----------
cd /home/archana/OpenJDK_JTRegTestsFramework/jtreg/bin/JTwork/scratch && \\
DISPLAY=:1 \\
GNOME_DESKTOP_SESSION_ID=this-is-deprecated \\
HOME=/home/archana \\
LANG=en_GB.UTF-8 \\
PATH=/bin:/usr/bin \\
XMODIFIERS=@im=ibus \\
CLASSPATH=/home/archana/OpenJDK_JTRegTestsFramework/jtreg/bin/JTwork/classes/java/lang/Class/forName/arrayClass/ExceedMaxDim.d:/home/archana/openj9-openjdk-jdk11/test/jdk/java/lang/Class/forName/arrayClass:/home/archana/OpenJDK_JTRegTestsFramework/jtreg/lib/javatest.jar:/home/archana/OpenJDK_JTRegTestsFramework/jtreg/lib/jtreg.jar \\
    /home/archana/openj9-openjdk11/jdk-11+28/bin/java \\
        -Dtest.src=/home/archana/openj9-openjdk-jdk11/test/jdk/java/lang/Class/forName/arrayClass \\
        -Dtest.src.path=/home/archana/openj9-openjdk-jdk11/test/jdk/java/lang/Class/forName/arrayClass \\
        -Dtest.classes=/home/archana/OpenJDK_JTRegTestsFramework/jtreg/bin/JTwork/classes/java/lang/Class/forName/arrayClass/ExceedMaxDim.d \\
        -Dtest.class.path=/home/archana/OpenJDK_JTRegTestsFramework/jtreg/bin/JTwork/classes/java/lang/Class/forName/arrayClass/ExceedMaxDim.d \\
        -Dtest.vm.opts= \\
        -Dtest.tool.vm.opts= \\
        -Dtest.compiler.opts= \\
        -Dtest.java.opts= \\
        -Dtest.jdk=/home/archana/openj9-openjdk11/jdk-11+28 \\
        -Dcompile.jdk=/home/archana/openj9-openjdk11/jdk-11+28 \\
        -Dtest.timeout.factor=1.0 \\
        com.sun.javatest.regtest.agent.MainWrapper /home/archana/OpenJDK_JTRegTestsFramework/jtreg/bin/JTwork/java/lang/Class/forName/arrayClass/ExceedMaxDim.d/main.0.jta
result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Test failed, was able to create array with dim > 255. See log for details.

test result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Test failed, was able to create array with dim > 255. See log for details.

Log is attached here :
[JTreport.tar.gz](https://github.com/eclipse/openj9/files/2423682/JTreport.tar.gz)

This test works fine on openjdk11 hotspot
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by pshipton** [comment]
This looks related to #802

**Comment by pdbain-ibm** [comment]
This failure is questionable.  See the discussion in https://github.com/eclipse/openj9/issues/802#issuecomment-444608015 _et seq._

The test creates an array _type_ with more than 255 dimensions, but there is no constraint on the dimensions of the type _per se_ in the specification; the only constraint is on new _instances_.

The validity to the Class is moot: the Class of an array type cannot be used directly to create array instances since the type has no constructor. The only way way to use the Class is to get the transitive closure of the component type and call `Array.newInstance()`, which will throw an exception if the number of dimensions exceeds 255.

This test should be excluded as invalid.

**Comment by DanHeidinga** [comment]
I think this is a case we've missed and we should update OpenJ9 to match the RI's behaviour here.  See more detailed comment in #802
