### ISSUE TITLE
Potential deadlock for calling GarbageCollectorMXBean.getLastGcInfo()

### ISSUE THREAD

**Issue by LinHu2016** [eclipse/openj9#3057]
native method getLastGcInfoImp() hold managementDataLock(for read) for retrieving GC Information,
during constructing memory pool name(Java String), it could trigger GC due to allocation failure.
GCStartEvent would require managementDataLock (for write) to update memory usage Data in vm structures. it would cause a deadlock.

**Comment by dmitripivkine** [comment]
FYI @DanHeidinga

**Comment by pshipton** [comment]
#3090 was also required as part of this fix.
