### ISSUE TITLE
Investigate limiting System.identityHashcode() to positive numbers

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#3062]
OpenJ9 allows both positive and negative identity hashcodes.  This is problematic for programs that incorrectly assume hashcodes can only be positive.

Investigate adding an option to limit hashcode to be positive and determine the performance overhead of this.

Note, any such option would limit the range of hashcodes and may lead to more collisions.

**Comment by charliegracie** [comment]
Are there open/closed issues where consumers of OpenJ9 were having this issue?

**Comment by DanHeidinga** [comment]
The likely place to hack for this is https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/runtime/oti/ObjectHash.hpp#L177

Changing it here will ensure the option + mask is only rechecked until the object is moved.  All the fast paths that read the hashcode from moved objects shouldn't require any modification.

Will attempt to add an -XX option and investigate the performance implications of this change.

**Comment by vijaysun-omr** [comment]
Maybe if the result of the -XX option is stored in a private static final boolean variable and if that variable is checked in the identityHashCode at the spot @DanHeidinga pointed out, then the JIT should be able to fold away the extra test at compile time via it's usual static final optimizations.

**Comment by vijaysun-omr** [comment]
I assume you were thinking of an -XX option to work around this particular migration issue in terms of different JCL behavior. One question is whether you prefer different -XX options for different JCL issues such as this one (assuming there are more of them we will find down the line) or have one option that changes all the JCL behaviours needed to make migration easier.

**Comment by DanHeidinga** [comment]
@vijaysun-omr I've looked for how to push the option as low in the code as possible - down to the native hash operation -  to ensure there is only 1 place that needs to be modified and that there's never a chance of an inconsistent hashcode being returned.

> One question is whether you prefer different -XX options for different JCL issues such as this one (assuming there are more of them we will find down the line) or have one option that changes all the JCL behaviours needed to make migration easier.

That's an interesting idea.  I think we should start with a single option. If we end up with multiple migration related options, they can be grouped later under a single -XX:EasyMigration (or similar) option.

**Comment by vijaysun-omr** [comment]
Thanks @DanHeidinga I am in agreement with your approach to wait for the "second" migration related option before considering grouping under one option. 

Is there a PR for the change to the native hash ?

**Comment by DanHeidinga** [comment]
Thanks @gacholio for coding this up.  For those following along, the next step is to check a microbench for any regressions and then we'll proceed with the merge provided the results are ok

**Comment by gacholio** [comment]
Doc issue: https://github.com/eclipse/openj9-docs/issues/109
