### ISSUE TITLE
All testing failed to start Pipeline-Build-Test-All

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3063]
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Build-Test-All/detail/Pipeline-Build-Test-All/222/pipeline

Example https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs/166/console

```
00:02:38 get jdk binary...
00:02:38 --sdkdir is set to null. Therefore, skip download jdk binary
00:02:38 ls: cannot access '*/': No such file or directory
00:02:38 chmod: cannot access 'j2sdk-image': No such file or directory
```

**Comment by pshipton** [comment]
Seems PR testing isn't affected.

@llxia @AdamBrousseau 

Is this caused by https://github.com/eclipse/openj9/pull/3042 ?

**Comment by smlambert** [comment]
This should be fixed by https://github.com/AdoptOpenJDK/openjdk-tests/pull/600
We merged our two Jenkinsfile test scripts last night (tested in 4 places, but managed to miss this case).

**Comment by pshipton** [comment]
Thanks. Will close this. @llxia thanks for starting a new build https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/223/
