### ISSUE TITLE
Default PR testing should test jdk11 and not jdk10

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3079]
"Jenkins test sanity" tests jdk8 and jdk10, but should test jdk11 now instead of jdk10. Or have no defaults at all.
fyi #3076

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Will be resolved in #2836

**Comment by pshipton** [comment]
I'm concerned about the timeframe of resolving #2836. Time is short to get all features into the 0.11.0 release, and it would be better to test jdk11 by default.

**Comment by jdekonin** [comment]
After #2836 there will be no default.  Release will need to be explicit.

**Comment by pshipton** [comment]
That isn't the point. When will #2836 be ready?

**Comment by AdamBrousseau** [comment]
last week :stuck_out_tongue: 
`Jenkins test sanity all jdk8,jdk11`
It depends on how the reviews and approvals go. Its "ready" as is but the requirements might change.

**Comment by AdamBrousseau** [comment]
JDK 10 no longer included in `all` or unspecified. You must explicitly request jdk10

**Comment by AdamBrousseau** [comment]
Well you still won't get 11 if you `Jenkins test sanity`. As per Joe's original email, we intended to drop support for `all` except when used for platforms

**Comment by pshipton** [comment]
Will `jenkins test sanity` test jdk8 only, or will it do nothing? If nothing then I think this work is completed.

**Comment by AdamBrousseau** [comment]
8

**Comment by pshipton** [comment]
Is it hard to remove 8 when nothing is specified?

**Comment by pshipton** [comment]
Obsolete.
