### ISSUE TITLE
Build-Test-All should use the same shas for both testing and JVM builds

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3080]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/224/

While it was the intention to use the same sha for both testing and JVM builds, its not working. I found the following in the output, which may indicate the problem.

`fatal: reference is not a tree: 2f4d3bf98b737e7741bf4ca2ebdff4b2edcec502`

**Comment by AdamBrousseau** [comment]
I think the test scripts need to fail if they cannot checkout the correct ref.
@llxia @renfeiw

**Comment by llxia** [comment]
The above link is not valid anymore. Do we still have the issue?

**Comment by AdamBrousseau** [comment]
The Sha was likely unavailable for whatever reason. I think the point is the test shouldn't continue if it can't fetch the correct version of source.

**Comment by llxia** [comment]
what was the behavior? The script continued even it had git clone failure?

**Comment by AdamBrousseau** [comment]
Yes I believe the get.sh always continues if any of the commands fail. I've noticed this before with other commands it runs.

**Comment by pshipton** [comment]
Obsolete.
