### ISSUE TITLE
OpenJDK8 Sanity test failures in suite J9vmTest_2, J9vmTest_4,  & J9vmTest_5

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#313]
Running the J9vmTest_2, J9vmTest_4 and J9vmTest_5 testsuites for OpenJ9 built on extensions for OpenJDK8 all fail with these errors:

**Failures:**
+++ j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest: +++
command: /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m  -Xtrace:print={j9bcu.192-194}  -Xbootclasspath:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/se-service.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/resources.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jsse.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/charsets.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jce.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/tools.jar -classpath /home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest

*** Test FAILED *** (j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest)

+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m  -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31}  -Xbootclasspath:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/se-service.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/resources.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jsse.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/charsets.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jce.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/tools.jar -classpath /home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest 

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)

+++ j9vm.test.intermediateclasscreate.IntermediateClassCreateTest: +++
command: /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m -Xtrace:print=tpnid{j9bcu.210} -javaagent:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/jvmtest/VM_Test/VM_Test.jar  -Xbootclasspath:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/se-service.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/resources.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jsse.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/charsets.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jce.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/tools.jar -classpath /home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.intermediateclasscreate.IntermediateClassCreateTest 0 enableRCT enableRIT

Class file SampleClass_Invalid_0.class is created in dir /tmp/intermediateClassCreateTest/0/j9vm/test/intermediateclasscreate
RITransformer.transform called for j9vm.test.intermediateclasscreate.SampleClass
Class file SampleClass_Invalid_1.class is created in dir /tmp/intermediateClassCreateTest/0/j9vm/test/intermediateclasscreate
RCTransformer.transform called for j9vm.test.intermediateclasscreate.SampleClass
Class file SampleClass_Valid_2.class is created in dir /tmp/intermediateClassCreateTest/0/j9vm/test/intermediateclasscreate
RCTransformer.transform called for j9vm.test.intermediateclasscreate.SampleClass
Class file SampleClass_Valid_3.class is created in dir /tmp/intermediateClassCreateTest/0/j9vm/test/intermediateclasscreate
Invoking j9vm.test.intermediateclasscreate.SampleClass.foo() returned 3
RCTransformer.transform called for j9vm.test.intermediateclasscreate.SampleClass
Class file SampleClass_Valid_4.class is created in dir /tmp/intermediateClassCreateTest/0/j9vm/test/intermediateclasscreate
Invoking j9vm.test.intermediateclasscreate.SampleClass.foo() returned 4

FAIL: Expected trace point j9bcu.210 was not generated
*** Test FAILED *** (j9vm.test.intermediateclasscreate.IntermediateClassCreateTest)

+++ j9vm.test.invalidclasspath.SetClasspathTest: +++
command: /home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m -Xshareclasses:name=setclasspathtest,reset,verboseHelper -Xtrace:print={j9jcl.423}   -Xbootclasspath:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/se-service.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/rt.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/resources.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jsse.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/charsets.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/jce.jar:/home/admin/mydocker/ccm/openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/tools.jar -classpath /home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/home/admin/mydocker/ccm/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.invalidclasspath.SetClasspathTest

[-Xshareclasses Helper API verbose output enabled]
JVMSHRC256I Persistent shared cache "setclasspathtest" has been destroyed
K0594
K0594
K0594
K0594
K0594
K0594
K0594
K0594
K0594
K0594
K0594
K0594
K0594
SetClasspathTest> Searching class TestA1 in shared class cache...
K0594
SetClasspathTest> Failed to find class TestA1 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestA1 at classpath index 0
K0594
SetClasspathTest> Successfully stored class TestA1 in shared cache

SetClasspathTest> URL Transformation 1
K0594
K0594
K0594
K0594
K0594
SetClasspathTest> Searching class TestA2 in shared class cache...
K0594
SetClasspathTest> Failed to find class TestA2 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestA2 at classpath index 0
K0594
SetClasspathTest> Failed to store class TestA2 in shared cache

SetClasspathTest> URL Transformation 2
K0594
K0594
K0594
K0594
SetClasspathTest> Searching class TestB1 in shared class cache...
K0594
SetClasspathTest> Failed to find class TestB1 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestB1 at classpath index 1
K0594
SetClasspathTest> Failed to store class TestB1 in shared cache

SetClasspathTest> URL Transformation 3
K0594
K0594
K0594
K0594
SetClasspathTest> Searching class TestB2 in shared class cache...
K0594
SetClasspathTest> Failed to find class TestB2 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestB2 at classpath index 1
K0594
SetClasspathTest> Failed to store class TestB2 in shared cache
K0594
SetClasspathTest> Searching class TestC1 in shared class cache...
K0594
SetClasspathTest> Failed to find class TestC1 in shared class cache, loading from disk
K0594
K0594
K0594
SetClasspathTest> Found classfile bytes for class TestC1 at classpath index 3
K0594
SetClasspathTest> Failed to store class TestC1 in shared cache

SetClasspathTest> URL Transformation 4
K0594
K0594
SetClasspathTest> Searching class TestB3 in shared class cache...
SetClasspathTest> Failed to find class TestB3 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestB3 at classpath index 1
K0594
SetClasspathTest> Successfully stored class TestB3 in shared cache

SetClasspathTest> URL Transformation 5
K0594
K0594
K0594
SetClasspathTest> Searching class TestA3 in shared class cache...
K0594
SetClasspathTest> Failed to find class TestA3 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestA3 at classpath index 0
K0594
SetClasspathTest> Failed to store class TestA3 in shared cache

SetClasspathTest> URL Transformation 6
K0594
K0594
SetClasspathTest> Searching class TestA4 in shared class cache...
SetClasspathTest> Failed to find class TestA4 in shared class cache, loading from disk
SetClasspathTest> Found classfile bytes for class TestA4 at classpath index 0
SetClasspathTest> Successfully stored class TestA4 in shared cache

Error:: Expected message "URL https://w3.ibm.com/ does not have required file or jar protocol." to appear 4 times but found 0 times
Error:: Expected message "Classpath contains an invalid URL. Returning null." to appear 5 times but found 0 times
Error:: Expected message "Classpath contains an invalid URL. Returning null." to appear 5 times but found 0 times
*** Test FAILED *** (j9vm.test.invalidclasspath.SetClasspathTest)

**Comment by andrew-m-leonard** [comment]
Internal repo available to build and reproduce this here : https://github.ibm.com/runtimes/openjdk-jdk8

**Comment by pshipton** [comment]
These tests are passing now.
