### ISSUE TITLE
JTReg test fail : java/lang/Class/getResource/ResourcesTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3136]
Following relevant error message from output ...

```
Exception in thread "main" java.lang.RuntimeException
	at Main.assertTrue(Main.java:284)
	at Main.assertEquals(Main.java:299)
	at Main.main(Main.java:96)
```

Looking at https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/Class/getResource/Main.java#L95
it seems that instead of returning the m2 resource, our ClassLoader impl wrongly returns the m1 resource.

At the completion of line 95 ...

url = file:/home/walshbp/jtreg_testing/JTwork/scratch/mods/m2/myresource with HotSpot, which looks correct
url = file:/home/walshbp/jtreg_testing/JTwork/scratch/mods/m1/myresource with OpenJ9, which seems incorrect

This is the only sub-test which fails, all other sub-tests pass.

This test passes when run against Hotspot.

Full logs archive : 
[resourceProblem.tar.gz](https://github.com/eclipse/openj9/files/2445813/resourceProblem.tar.gz)

**Comment by DanHeidinga** [comment]
FYI @pdbain-ibm

**Comment by pdbain-ibm** [comment]
The test calls a method in a class in p1 which calls a method in a class in p2 which calls `Class.getResource()`.  The implementation of same is:
```
	Module thisModule = getModule();
	
	if (thisModule.isNamed() && (thisModule == System.getCallerClass().getModule())) {
		try {
			return loader.findResource(thisModule.getName(), absoluteResName);
		} catch (IOException e) {
			return null;
		}
	} else
	{
		if (loader == ClassLoader.bootstrapClassLoader) {
			return ClassLoader.getSystemResource(absoluteResName);
		} else {
			return loader.getResource(absoluteResName);
		}
	}
```
`thisModule` is m1 and  `System.getCallerClass().getModule()` returns m2.  This causes us to drop to classical `getResource()` which picks up the first matching resource on the classpath.

The specification for `Class.getResource()` says: 

> If this class is in a named Module then this method will attempt to find the resource in the module. This is done by delegating to the module's class loader findResource(String,String) method, invoking it with the module name and the absolute name of the resource. 

The changeset from @ashu-mehra  which introduced this has the following comment:

> 114603: Update Class.getResource() and Class.getResourceAsStream() to load…
114603: Update Class.getResource() and Class.getResourceAsStream() to load resources from module - jazz103 114603 : Jason Feng + Peter Shpiton : CS1 - Update Class.getResource() and Class.getResourceAsStream() to search module before delegating to parent..- Add AbstractClassLoader.findResource(String, String) to allow bootloader to locate resource in modules defined by it.

**Comment by pshipton** [comment]
This doesn't need to be tracked against the 0.11.0 release as the release will not hold on this. Either the fix makes it in, or it doesn't and goes into the next release.

**Comment by pdbain-ibm** [comment]
I am working on a fix.  I hope to get it ready for review this week.

**Comment by pdbain-ibm** [comment]
Testing the fix now.  It passes this test case; I am testing it on the regression and compliance suites now.

The test in question exercises the visibility of resources at the root of a module, i.e. no package.  I can't find any documentation specifically for this case but I infer from the reference implementation that resources in the default package are implicitly open to other modules.  FYI @DanHeidinga @pshipton .
