### ISSUE TITLE
Field watch performance on x86

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3153]
Managed via ZenHub. Install the plugin to see the associated Issues and PRs.

As things stand currently under full speed debug, when an agent requests a field to be watched we cannot JIT compile the method because we cannot respect the hooks for reporting accesses of the respective field. This limitation will be lifted by using the rdbar / rdbari/ wrbar/ wrbari opcodes to represent reads/writes which have requested fields of certain types to be watched.

The JIT will generate read/write barriers for such fields of the correct type and the optimizer will treat them as normal loads/writes. At codegen time we will insert a C helper call to notify the VM via a hook that a field will be read/written and reduce the read/write barrier to the load/store.

**Comment by pshipton** [comment]
As per @andrewcraik this won't be ready in 0.11.0, deferring.

**Comment by DanHeidinga** [comment]
@andrewcraik @cathyzhyi Can you confirm the status of this item?  Is it still on target for the `0.12.0` release?

**Comment by DanHeidinga** [comment]
@andrewcraik Is this complete on x86 for 0.12?  Can it be closed?

**Comment by andrewcraik** [comment]
This is now merged. Closing.
