### ISSUE TITLE
JTReg tests fail : java/lang/invoke/VarHandles/VarHandleTestByteArrayAs...

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3161]
Further to issue https://github.com/eclipse/openj9/issues/3142 ...

Both java/lang/invoke/VarHandles/VarHandleTestByteArrayAs[Long|Int] have far more common sub-test failures resulting from NPEs in certain situations.

Log archive of runs of both, including also Char and the passing Float, Double and Short versions : 
[VarHandleTestByteArrayAsXProblems.tar.gz](https://github.com/eclipse/openj9/files/2450858/VarHandleTestByteArrayAsXProblems.tar.gz)

Hopefully these observations can also help in resolving issue https://github.com/eclipse/openj9/issues/3137.

**Comment by pshipton** [comment]
This doesn't need to be tracked against the 0.11.0 release as the release will not hold on this. Either the fix makes it in, or it doesn't and goes into the next release.

**Comment by ben-walsh** [comment]
Confirmed test pass using ...
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28-201810141809)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-fa48180f, JRE 11 Linux amd64-64-Bit Compressed References 20181014_61 (JIT enabled, AOT enabled)
OpenJ9   - fa48180f
OMR      - 6f35a3ce
JCL      - 4f9e2ba5c4 based on jdk-11+28)
```
