### ISSUE TITLE
OpenJ9 Sanity test suite not configured correctly for OpenJDK8

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#317]
- [ ] Test Cmvc194280.java should be excluded for OpenJ9 as it is for SE90.
- [ ] The test/TestConfig/scripts/build_test.xml JAVAC location is incorrect for the JDK8 image, it should be ..property name="JAVAC" value="${JAVA_BIN}/javac" /...
- [ ] The test/VM_Test/playlist.xml playlist should exclude tests reliant on cfdump (recreateClassTest, CFdumptest), which is not available currently in OpenJ9.

**Comment by andrew-m-leonard** [comment]
- [ ] Test Cmvc194280.java should be excluded for OpenJ9 as it is for SE90.
- [ ] The test/TestConfig/scripts/build_test.xml JAVAC location is incorrect for the JDK8 image, it should be <property name="JAVAC" value="${JAVA_BIN}/javac" />
- [ ] The test/VM_Test/playlist.xml playlist should exclude tests reliant on cfdump (recreateClassTest, CFdumptest), which is not available currently in OpenJ9.

**Comment by pshipton** [comment]
The tests are running and the only failures are due to #469 and #472. I think we can close this Issue. @smlambert ?

**Comment by smlambert** [comment]
Agree, closing this issue.
