### ISSUE TITLE
JTReg test fail : java/lang/ClassLoader/RecursiveSystemLoader.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3178]
Fails because no IllegalStateException is triggered when calling ClassLoader.getSystemClassLoader() before the VM is booted.
Unclear whether this is something that should happen with the OpenJ9 impl of ClassLoader and associated objects or only applicable to Hotspot impl.

Log archive : [RecursiveSLProb.tar.gz](https://github.com/eclipse/openj9/files/2456514/RecursiveSLProb.tar.gz)

This test passes against Hotspot.

**Comment by JasonFengJ9** [comment]
Will look at this.

**Comment by JasonFengJ9** [comment]
Looked at the testcase code, 
```
public class RecursiveSystemLoader extends ClassLoader {
   ...
   public RecursiveSystemLoader(ClassLoader classLoader) {
        super("RecursiveSystemLoader", classLoader);
        try {
            ClassLoader.getSystemClassLoader();
        } catch(IllegalStateException ise) {
            System.err.println("Caught expected exception:");
            return;
        }
        throw new RuntimeException("Expected IllegalStateException was not thrown.");
    }
    ....
}
```
This tests RI internal specific behaviour.
As per spec https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ClassLoader.html#getSystemClassLoader()
> If circular initialization of the system class loader is detected then an IllegalStateException is thrown.

`OpenJ9` doesn't suffer a circular initialization hence no need to throw `IllegalStateException`.
This issue can be closed.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/623
