### ISSUE TITLE
Relevance of CommandLineOptions.html

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#319]
I noticed [runtime/gc_doc/CommandLineOptions.html](https://github.com/eclipse/openj9/blob/master/runtime/gc_doc/CommandLineOptions.html) documents good number of GC options. But it appears to be outdated. Are we still maintaining this file or is it obsolete now?

**Comment by pshipton** [comment]
@dmitripivkine fyi

**Comment by dmitripivkine** [comment]
I believe we do support this list. All options mentioned there should be valid. However it was not updated for a while.

**Comment by dmitripivkine** [comment]
Our documentation is organized different way, so this file is not used any more. After discussion we decided to remove it. However we need to double check that it's contain duplicate information only.

**Comment by dmitripivkine** [comment]
@SueChaplain Would you please double check that gc_doc/CommandLineOptions.html is not used any more and can be deleted safely?

**Comment by SueChaplain** [comment]
Never seen this file before! Not really for me to comment on whether you should delete it, but I can tell you what we don't have ...... 

We have nothing in the user guide documentation for the following options. Maybe they are obsolete?
- -Xresman
- -Xmdx

For -Xgc, we only have the following documented:
concurrentScavenge | dnssExpectedTimeRatioMaximum | dnssExpectedTimeRatioMinimum | excessiveGCratio | minContractPercent | maxContractPercent | overrideHiresTimerCheck | preferredHeapBase | scvNoAdaptiveTenure | scvTenureAge |verboseFormat

We don't have -Xtgc:reference

Interesting that the options are listed by policy. This is something we might want to provide a view for in the OpenJ9 command reference (hope to be working this soon) as I'm aware that some policies like Balanced don't have the full set.

If you want, you can make your own assessment of what we have here:

https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.vm.9.0.doc/docs/x_jvm_commands.html

**Comment by dmitripivkine** [comment]
Thank you Sue.
-Xresman is obsolete, last usage in 2.4 (or even 2.3)
We still parse for -Xmdx, I don't know history of this. Will check.

**Comment by SueChaplain** [comment]
File removed, closing this issue.
