### ISSUE TITLE
JITaaS hangs when doing java -Xjit:count=0 -version

### ISSUE THREAD

**Issue by harryyu1994** [eclipse/openj9#3193]
Discovered during JITaaSClient AOT experiment.
The hang is there even if no jitaas options are specified.

@mpirvu @ymanton @dmitry-ten

**Comment by mpirvu** [comment]
Are you using a debug build or a prod?

**Comment by mpirvu** [comment]
Also, what exactly is in your build (which commits)?

**Comment by harryyu1994** [comment]
latest jitaas branches, debug build, and used sdk from 2018/10/03. Only jit dll was built.

**Comment by mpirvu** [comment]
I have an older SDK (20180921_397495) and it works for me. I also build only the JIT dll.
Does yours work with -Xint? How about -Xjit:initialOptLevel=noOpt,count=0 ?

**Comment by harryyu1994** [comment]
works with -Xint, does not work with -Xjit:initialOptLevel=noOpt,count=0. As long as there is -Xjit:count=0, it hangs with "#JITSTATE:  t=  2537 VM changed state to NOT_STARTUP" in the verbose log.

**Comment by harryyu1994** [comment]
I tried building the whole sdk and the problem seems to go away.

**Comment by mpirvu** [comment]
I had a couple of these weird behaviors a while back. Recompilation made them go away.
