### ISSUE TITLE
StackOverflow #OpenJ9 tag doesn't exist

### ISSUE THREAD

**Issue by kgibm** [eclipse/openj9#32]
The [OpenJ9 landing page](https://www.eclipse.org/openj9/index.html#get-started) points to a [StackOverflow search for the OpenJ9 tag](https://stackoverflow.com/search?q=%23OpenJ9); however, when I tried to submit a question with the OpenJ9 tag, StackOverflow said that I need to have at least 1,500 reputation to create a new tag.

**Comment by mstoodle** [comment]
Heh, yeah that part of the landing page is, I suppose you could say, aspirational. We should probably remove this reference until that tag can get created with some content. Sorry for the confusion!

**Comment by mstoodle** [comment]
Closing now that the issue has been moved to the eclipse/openj9-website repository.
