### ISSUE TITLE
Enable idle tuning options by default when running in container

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#3226]
OpenJ9 docker images produced at AdoptOpenJDK already enable `-XX:+IdleTuningGcOnIdle` and `-XX:+IdleTuningCompactOnIdle`. See https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/ubuntu/Dockerfile.openj9.releases.full.
It would be beneficial if we enable these options at runtime when OpenJ9 is running in container so that any product that uses OpenJ9 but does not use the docker images from Adopt, also gets the benefits of these options without the need to explicitly add these options in their Dockerfile.

@mpirvu @dinogun

**Comment by ashu-mehra** [comment]
Doc issue: https://github.com/eclipse/openj9-docs/issues/112

**Comment by DanHeidinga** [comment]
@ashu-mehra Can you expand on:
* the rationale for this, 
* the differences users might see, 
* whether these options are supported on all platforms or not, 
* any limitations
* any performance impacts to either startup or throughput when this is enabled

**Comment by ashu-mehra** [comment]
> the rationale for this,

I added my understanding of why we want to do this in the first comment i.e. `It would be beneficial if we enable these options at runtime when OpenJ9 is running in container so that any product that uses OpenJ9 but does not use the docker images from Adopt, also gets the benefits of these options without the need to explicitly add these options in their Dockerfile.`
Generally when someone includes OpenJ9 in their Dockerfile, they are unlikely to enable these options unless they are aware of them. So this PR would be useful in such scenarios.
@mpirvu do you want to add anything more to it?

 > the differences users might see,

I don't expect any differences observable by user other than during idle state when the physical memory footprint may drop down.

 > whether these options are supported on all platforms or not,

AFAIK these options are supported on all platforms except windows, but this PR only enables them when OpenJ9 in running in container which currently covers Linux platforms only.

> any limitations

Same limitations that apply to these options (eg only work with gencon policy), nothing new added by this PR.

> any performance impacts to either startup or throughput when this is enabled

I don't think any throughput impact was observed in earlier performance runs done when these options were added. That should hold true if we enable these options by default.
For startup, Marius has shared his script for gathering Liberty startup numbers (as in https://github.com/eclipse/openj9/issues/2263#issuecomment-427010152). I will use that and will post the startup numbers here.

**Comment by ashu-mehra** [comment]
I created two builds, one without https://github.com/eclipse/openj9/pull/3228 (baseline) and another with https://github.com/eclipse/openj9/pull/3228 which has idle tuning enabled by default if running in container.
I measured startup of liberty on bare metal and in container on my system.

**Results on bare metal:**

**Baseline**
```
Results for JDK=/home/ashu/data/builds/openj9/jdk8_baseline/linux-x86_64-normal-server-release/images/j2sdk-image jvmOpts=-Xquickstart -Xmx256m -Xshareclasses:enableBCI,name=liberty -Xscmx60M -Xscmaxaot8m
Stats for cold run:
StartupTime	avg=2807	min=2717	max=3029	stdDev=45.1	maxVar=11.5%	confInt=0.15%	samples=299
	Outlier values:  3057.33
Footprint	avg=55678	min=53964	max=59440	stdDev=939.3	maxVar=10.1%	confInt=0.16%	samples=300
CThreadTime	avg=2675	min=2606	max=2763	stdDev=28.8	maxVar=6.0%	confInt=0.10%	samples=299
	Outlier values:  2896
```

**IdleTuning enabled**
```
Results for JDK=/home/ashu/data/builds/openj9/jdk8_idletuning_enabled/linux-x86_64-normal-server-release/images/j2sdk-image jvmOpts=-Xquickstart -Xmx256m -Xshareclasses:enableBCI,name=liberty -Xscmx60M -Xscmaxaot8m
Stats for cold run:
StartupTime	avg=2846	min=2740	max=2984	stdDev=42.2	maxVar=8.9%	confInt=0.14%	samples=298
	Outlier values:  3053.364 3053.076
Footprint	avg=55730	min=53844	max=58856	stdDev=1000.0	maxVar=9.3%	confInt=0.17%	samples=300
CThreadTime	avg=2705	min=2640	max=2820	stdDev=31.3	maxVar=6.8%	confInt=0.11%	samples=299
	Outlier values:  2903
```
On bare metal startup difference is (2846-2807)/2807 ~ 1.4%

**Results on container with 256m:**

**Baseline**

```
Results for JDK=/root/builds/openj9/jdk8_baseline/linux-x86_64-normal-server-release/images/j2sdk-image jvmOpts=-Xquickstart -Xmx256m -Xshareclasses:enableBCI,name=liberty -Xscmx60M -Xscmaxaot8m
Stats for cold run:
StartupTime	avg=2915	min=2828	max=3084	stdDev=45.3	maxVar=9.1%	confInt=0.15%	samples=298
	Outlier values:  3160.856 3320.805
Footprint	avg=55002	min=53064	max=57756	stdDev=799.2	maxVar=8.8%	confInt=0.14%	samples=300
CThreadTime	avg=2741	min=2669	max=2845	stdDev=29.1	maxVar=6.6%	confInt=0.10%	samples=297
	Outlier values:  2951 3108 2876
ProcessTime	avg=5304	min=5130	max=5610	stdDev=73.5	maxVar=9.4%	confInt=0.13%	samples=298
	Outlier values:  5690 6070
```

**IdleTuning enabled**
```
Results for JDK=/root/builds/openj9/jdk8_idletuning_enabled/linux-x86_64-normal-server-release/images/j2sdk-image jvmOpts=-Xquickstart -Xmx256m -Xshareclasses:enableBCI,name=liberty -Xscmx60M -Xscmaxaot8m
Stats for cold run:
StartupTime	avg=2908	min=2835	max=3057	stdDev=40.0	maxVar=7.8%	confInt=0.13%	samples=299
	Outlier values:  3253.123
Footprint	avg=54991	min=53292	max=57892	stdDev=833.5	maxVar=8.6%	confInt=0.14%	samples=300
CThreadTime	avg=2737	min=2669	max=2862	stdDev=27.6	maxVar=7.2%	confInt=0.10%	samples=298
	Outlier values:  2871 2991
ProcessTime	avg=5291	min=5140	max=5500	stdDev=62.9	maxVar=7.0%	confInt=0.11%	samples=299
	Outlier values:  5870
```

In container startup difference is (2908-2915)/2915 ~ -0.25%

There is not much difference in startup. I think the impact of enabling idle tuning by default is negligible.

**Comment by mpirvu** [comment]
> There is not much difference in startup. I think the impact of enabling idle tuning by default is negligible.

@ashu-mehra This issue discusses the enabling of idle_tuning in containers only. Are you proposing to enable idle_tuning outside containers too?

**Comment by ashu-mehra** [comment]
>  Are you proposing to enable idle_tuning outside containers too?

No, the reason I measured on bare metal as well (in addition to containers) is because the [code](https://github.com/ashu-mehra/openj9/blob/432c0da668d909613e965fe143ff53e2ad306fb8/runtime/vm/jvminit.c#L1825) to check if the JVM is running in containers gets executed in either case. Basically that's the only piece that can impact startup, if at all. So I just wanted to measure its impact when not running in container. But we enable idle tuning only when running in container.
