### ISSUE TITLE
JTReg test fail : java/util/prefs/PrefsSpi.sh

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3232]
Following failure is presented ...

```
Exception in thread "main" java.lang.Exception: Preferences class name "java.util.prefs.FileSystemPreferences" does not match regular expression "StubPreferences".
	at PrefsSpi.main(PrefsSpi.java:40)
```

The sub-test ...

```
Sys "$java" ${TESTVMOPTS} "-cp" "$TESTCLASSES${CPS}extDir/PrefsSpi.jar" \
    -Djava.util.prefs.userRoot=. \
    PrefsSpi "StubPreferences"
```

... is the one which is failing.

Inside PrefsSpi.jar (which is added to the classpath in this sub-test) is a file 
META-INF/services/java.util.prefs.PreferencesFactory which has the content "StubPreferencesFactory".

This should result in the overriding of the default java.util.prefs.PreferencesFactory value of "java.util.prefs.FileSystemPreferences" with the provided value "StubPreferencesFactory" as per the "Implementation Note" given at 
https://docs.oracle.com/javase/9/docs/api/java/util/prefs/Preferences.html, but it does not, instead the default value class is wrongly loaded and instantiated.

Test passes against Hotspot.

Log archive : [PrefsSpiProb.tar.gz](https://github.com/eclipse/openj9/files/2469345/PrefsSpiProb.tar.gz)

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/634

**Comment by JasonFengJ9** [comment]
Looking at this.
