### ISSUE TITLE
linux x86-64 fails to build

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/openj9#3234]
Following https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V9.md with dependencies updated per https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk9/x86_64/ubuntu16/Dockerfile. 

Then 

`rm -fR ./build`
`bash configure --disable-ddr --with-freemarker-jar=/root/freemarker.jar`
`make clean`
`make all`

fails with 

```
Updating images/sec-bin.zip
Compiling 4 files for BUILD_JIGSAW_TOOLS
ExplodedImageOptimize.gmk:40: recipe for target '/root/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/_packages_attribute.done' failed
make[3]: *** [/root/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/_packages_attribute.done] Error 1
make[2]: *** [exploded-image-optimize] Error 1
make/Main.gmk:358: recipe for target 'exploded-image-optimize' failed

ERROR: Build failed for target 'images' in configuration 'linux-x86_64-normal-server-release' (exit code 2)
Stopping sjavac server
```

I am building clones of eclipse openj9/omr master branches

```
root@evacuator1:~/openj9-openjdk-jdk9# checkj9
openJDK:
328fcae Merge pull request #180 from keithc-ca/tar
b5ea6f8 Avoid using `--exclude-vcs` which isn't universally supported
402f993 Merge pull request #178 from mikezhang1234567890/aix-ddr
* openj9
omr:
cd1d1b6 Merge pull request #3010 from shingarov/bug_3009
6332e68 Restore building on gcc>=4.9
c5a3dc5 Merge pull request #3022 from rwy0717/fix-gctest
* master
openj9:
27aedbb Merge pull request #3184 from ashu-mehra/enable_container_support_default
4d0cc96 Merge pull request #3196 from dnakamura/compiler_exports
0ad5dd6 Merge pull request #3199 from hangshao0/work
* master
```

with 

```
root@evacuator1:~/openj9-openjdk-jdk9# echo $JAVA_HOME
/root/bootjdk8
root@evacuator1:~/openj9-openjdk-jdk9# echo $PATH
.:/root/bootjdk8:/root:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by DanHeidinga** [comment]
@ktbriggs Is there any other info in the build log?  Scrolling back through it may highlight more context as there's not enough info here to offer any suggestions.

**Comment by ktbriggs** [comment]
@DanHeidinga I agree that the build log does not provide enough info but I think that should be considered part of the issue. There is no other info relating to the failure before the posted snippet above and nothing after that is not redundant. I'm running the build again to be doubly sure and will post full build log here when it completes.

**Comment by ktbriggs** [comment]
With `export HAS_AUTOCONF=1` set the build failed again as before. Attached is the build log. I see many warnings but no way to tell which if any are relevant.

[build.log](https://github.com/eclipse/openj9/files/2469935/build.log)

**Comment by DanHeidinga** [comment]
I don't see anything there.  Try rebuilding with `make LOG=debug,cmdlines images`

**Comment by ktbriggs** [comment]
I think this is happening because I am building omr/openj9 master branches in a Java 9 build environment. I have been maintaining this environment for evacuator development (https://github.com/eclipse/omr/issues/2664) to stabilize performance metrics between builds. 

I'll try retooling for Java 11 and close this if evacuator (tracking omr/openj9 master) builds work out.

**Comment by ktbriggs** [comment]
Build works fine after upgrading environment to Java 11. Closing this.

**Comment by ktbriggs** [comment]
@DanHeidinga I didn't run `make LOG=debug,cmdlines images` in my V9 environment as you suggest but I would suggest that any `debug` log messages relating to events that will break make should be promoted to `error` log messages so that the root cause may be identified. 

I'll leave it to you to decide whether to raise this as an issue. If you do, the problem can be reproduced by setting up for V9 builds and checking out the omr/openj9 master branches pinned at the SHAs provided in original comment, in case you want to reference this issue.
