### ISSUE TITLE
Graal API Support

### ISSUE THREAD

**Issue by sirinath** [eclipse/openj9#3263]
Since Graal is an easy way to [embed other languages in Java](https://www.graalvm.org/docs/graalvm-as-a-platform/embed/) it will be great if you  can support Graal API. Otherwise portability to code between OpenJDK and OpenJ9 is hampered.

Also might be a good time to perhaps have Graal/Truffle APIs revised to support both platforms.

**Comment by DanHeidinga** [comment]
Graal's api is not a focus for the project at this time.  Closing.
