### ISSUE TITLE
Enable software CS testing on Z

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3283]
After we have support for software based CS on Z we need to investigate what is needed to enable testing on our build far against the feature.

**Comment by fjeremic** [comment]
@NigelYiboYu has the software testing been enabled? If not let's enable it so we can close this off.

**Comment by NigelYiboYu** [comment]
Not yet. Let me look into this now.

**Comment by pshipton** [comment]
@fjeremic @NigelYiboYu we're running out of time for the 0.15 release, has this been completed?

**Comment by NigelYiboYu** [comment]
In the open, openJ9 is tested in concurrent scavenge mode in abbs, and mauve tests. Harmony isn't open-sourced yet.

These are named differently in the open and the old-new name mapping is here: https://ibm.ent.box.com/file/279411185722

**mauve CS tests:** 
https://github.com/AdoptOpenJDK/openjdk-tests/blob/b360d8168d542054eb3faa6fd55b0afe2b8f71fd/systemtest/mauveLoadTest/playlist.xml#L164

**abbs CS tests**
abbs is broken into DAA, ClassLoading and other tests. They can be found at 
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/otherLoadTest/playlist.xml#L323 and 

https://github.com/AdoptOpenJDK/openjdk-tests/blob/b360d8168d542054eb3faa6fd55b0afe2b8f71fd/systemtest/daaLoadTest/playlist.xml#L194


I'm still looking at vmFarm tests. The vmFarm uses different infra scripts.

**Comment by fjeremic** [comment]
Thanks @NigelYiboYu. We already have coverage running from when x86 introduced the CS testing as per above. There is however an issue that we're not getting equivalent test coverage for Power. I've opened up an issue to track that work above. Closing this one as it's complete.
