### ISSUE TITLE
Documentation updates for software CS on Z

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3284]
Once software CS is available on Z we need to make sure documentation is update appropriately so as to inform users that we can run on z13- processors as well on any OS level. This issue is to ensure the appropriate people are pulled in to make sure the documentation is updated accordingly.

**Comment by SueChaplain** [comment]
@fjeremic - this sounds like a change for external documentation, which requires the label doc:externals and an issue needs opening at openj9-docs repo: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md

**Comment by fjeremic** [comment]
> @fjeremic - this sounds like a change for external documentation, which requires the label doc:externals and an issue needs opening at openj9-docs repo: [eclipse/openj9-docs/issues/new?template=new-documentation-change.md](https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md)

Thanks @SueChaplain this is more of a shell item for me to track the work needed. This is exactly the information I would have been looking for. Thanks for chiming in ahead of time! I'll be opening up the suggested issue closer to when I begin this work in the next week or so once I have some more details.

**Comment by fjeremic** [comment]
@NigelYiboYu can you take care of opening up the documentation issue so we can close off this item?

**Comment by NigelYiboYu** [comment]
Documentation issue here: https://github.com/eclipse/openj9-docs/issues/261

Closing this one.
