### ISSUE TITLE
JITaaS: reducing the size of Persistent CH table updates

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#3285]
Currently, CH table updates are the biggest messages, accounting for about a third of network traffic from client to the server. On average, updates are very big because for each dirty class, we serialize the class and pointers to all of its subclasses. But some classes have hundreds of subclasses, which results in a large message.
After looking at the code, I see that a list of subclasses is modified only in `TR_PersistentCHTable::classGotExtended`. This means that we don't need to send a list of subclasses to the server in other cases. 
I suggest that we keep track of when `classGotExtended` is called, and send subclasses only then.
This would also save some CPU, because computing the number of subclasses is expensive.

We could also keep track of classes that got added, and only send them, instead of all subclasses.

**Comment by mpirvu** [comment]
Fixed by #3527
