### ISSUE TITLE
MacOS: libjvmtitest.dylib not copied to images/jdk/bin/../../native-test-libs

### ISSUE THREAD

**Issue by pdbain** [eclipse/openj9#3292]
This is causing failures in tests which use the jvmti test agent.
cf. https://github.com/eclipse/openj9/issues/3266.

**Comment by keithc-ca** [comment]
The test libraries are copied to `build/macosx-x86_64-normal-server-release/images/test/openj9` following the pattern for other platforms.

**Comment by llxia** [comment]
Close this issue as this is obsolete.
