### ISSUE TITLE
Enable Concurrent Scavenge testing on X

### ISSUE THREAD

**Issue by 0dvictor** [eclipse/openj9#3294]
#3054 introduced Concurrent Scavenge support on X. Now we need to investigate what is needed to enable related testing as part of our CI process.

**Comment by pshipton** [comment]
@smlambert

**Comment by smlambert** [comment]
You can start with enabling the concurrentScavenge tests for xlinux, by updating the < platformRequirements > tag in the tests listed at the end of this [playlist.xml file](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/playlist.xml#L2648)

**Comment by pshipton** [comment]
@0dvictor any progress on this?

**Comment by 0dvictor** [comment]
Sorry, I'm still working on it. More testing and debugging is needed; however, none of the changes belong to OpenJ9.

**Comment by pshipton** [comment]
> none of the changes belong to OpenJ9.

Understood, this issue is for tracking against the milestone.

**Comment by pshipton** [comment]
@0dvictor Are there any other Issues/PRs that can be referenced here for the ongoing work?

**Comment by 0dvictor** [comment]
Just created an Issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/651

**Comment by pshipton** [comment]
Testing is manual for the 0.11 release. Automated testing will be enabled shortly after https://github.com/eclipse/openj9/issues/3338 is completed.

**Comment by 0dvictor** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/662 has been merged and hence CS tests on X86-64 have been enabled. Closing this Issue.

**Comment by pshipton** [comment]
Test build running https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/263/

**Comment by pshipton** [comment]
Failures are fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/177
Started a new build https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/264/

**Comment by pshipton** [comment]
fyi a crash in LambdaLoadTest_ConcurrentScavenge_0
https://github.com/eclipse/openj9/issues/3294
