### ISSUE TITLE
JTReg test fail : java/lang/invoke/ProtectedMemberDifferentPackage/Test.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3301]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/ProtectedMemberDifferentPackage/Test.java fails with ...

```
java.lang.Error: Unexpected error
	at p1.T2.assertSuccess(T2.java:76)
	at p1.T2.main(T2.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
Caused by: java.lang.IllegalAccessException: Class 'p2.T3' no access to: class 'p1.T1'
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:483)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:368)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:323)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:628)
	at p1.T2.lambda$main$2(T2.java:47)
	at p1.T2$$Lambda$7.000000001002E710.call(Unknown Source)
	at p1.T2.assertSuccess(T2.java:74)
	... 7 more
``` 

Test passes against Hotspot.

Same failure running with ```-Xint``` too.

Log archive : [ProMemDiffPackageProb.tar.gz](https://github.com/eclipse/openj9/files/2483701/ProMemDiffPackageProb.tar.gz)

**Comment by DanHeidinga** [comment]
Likely related to this issue: https://github.com/eclipse/openj9/issues/3047

**Comment by DanHeidinga** [comment]
Right now the system tests for mac osx are more important.  Please continue with that investigation

**Comment by pdbain-ibm** [comment]
I will pick this up.

**Comment by pdbain-ibm** [comment]
`p2.T3` is trying to access method `m1` in class `T2`. `T2` is public and inherits `m1` from its non-public superclass `T1`. `T3`'s package is different from `T1` and `T2` and cannot see the former. `findVirtual` creates a handle to `T2.m1` (which is actually `T1.m1`), then does the access check, but uses `m1`'s defining class (i.e. `T1`) instead of the nominal class (`T2`) and fails.

@DanHeidinga do you know why we check the defining class and not the actual target class?

**Comment by DanHeidinga** [comment]
This in `findVirtual` or one of the `checkAccess` methods?  A link to the relevant code would help =)

**Comment by pdbain-ibm** [comment]
```
		void checkAccess(MethodHandle handle, boolean skipAccessCheckPara) throws IllegalAccessException {
			if (INTERNAL_PRIVILEGED == accessMode) {
				// Full access for use by MH implementation.
				return;
			}

			if (NO_ACCESS == accessMode) {
				throw new IllegalAccessException(this.toString());
			}

			checkAccess(handle.getDefc(), handle.getMethodName(), handle.getModifiers(), handle, skipAccessCheckPara);
		}
```

**Comment by pdbain-ibm** [comment]
I changed `getDefC()` to `handle.getReferenceClass()` and the test passed.

**Comment by pdbain-ibm** [comment]
... but it broke jsr292Test test_GetterSetter_Protected_CrossPackage_SuperclassLookup. Investigating.

**Comment by DanHeidinga** [comment]
The rules for JSR292 are meant to closely approximate the behaviour of the bytecodes.  Check the code in resolvesupport.cpp & visible.c for how we handle the checks there.

**Comment by pdbain-ibm** [comment]
The test in question is:
Superclass CA declares protected field X.  Subclass CB in a different package inherits X.
CA tries to use a Lookup based in CA to access X in CB and fails because CA does not subclass CB and is in a different package.
This used to pass because the check formerly used the declaring class (CA) of X as the target class.

**Comment by pdbain-ibm** [comment]
For the record, from the JVM spec https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-5.html#jvms-5.4.4:

> A field or method R is accessible to a class or interface D if and only if any of the following is true:
> 
>  R is public.
> 
>  R is protected and is declared in a class C, and D is either a subclass of C or C itself.
> 
> Furthermore, if R is not static, then the symbolic reference to R must contain a symbolic reference to a class T, such that T is either a subclass of D, a superclass of D, or D itself.
> 
> During verification of D, it was required that, even if T is a superclass of D, the target reference of a protected field access or method invocation must be an instance of D or a subclass of D (§4.10.1.8).
> 
>  R is either protected or has default access (that is, neither public nor protected nor private), and is declared by a class in the same run-time package as D.
> 
>  R is private and is declared by a class or interface C that belongs to the same nest as D, according to the nestmate test below.

**Comment by pdbain-ibm** [comment]
Waiting for pull request https://github.com/eclipse/openj9/pull/3592 to be merged.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/646
