### ISSUE TITLE
Update testkitgen to support new osx_x86-64 and osx_x86-64_cmprssptrs specs

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#3307]
We have been using SPEC=macos_x86-64 for testing hotspot mac builds at Adopt.  I see that the specs at openj9 are named differently, we should update to recognize both, or shift to use osx_ naming.

This should also address the fact that we now have a cmpressedrefs osx build, and need to have testkitgen skip tests that are not applicable.

**Comment by pdbain-ibm** [comment]
There is also an issue with the native libraries:
```
build-natives-unix:
     [exec] Makefile:74: *** "The variable PLATFORM=osx_x86-64 is not one of aix_ppc-32,aix_ppc-64,linux_390-31,linux_390-64,linux_ppc-32,linux_ppc-64,linux_x86-32,linux_x86-64,win_x86-32,win_x86-64,zos_390-31,zos_390-64,linux_ppcle-64,linux_arm-32".  Stop.
```

See also https://github.com/eclipse/openj9/issues/3292

**Comment by renfeiw** [comment]
We need to an entry to ottawa.csv and mode service about the new macos spec, in this way, the tests will be filtered based on the corresponding modes and spec.

**Comment by renfeiw** [comment]
ottawa.csv is updated: #3312, mode service database is also updated. This should handle the issue that tests running on inapplicable platforms.

**Comment by JasonFengJ9** [comment]
Does this help https://github.com/eclipse/openj9-systemtest/issues/49?

**Comment by llxia** [comment]
Change is delivered. Close this issue.
