### ISSUE TITLE
Setup OSX Machines for JDK8

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3323]
## Setting up the machine

- Install Mac OS X 10.10 (Yosemite)

- The instructions below must be executed with `sudo` permissions.

- Install brew
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

- Download Xcode 4.6.3 from https://developer.apple.com/downloads.
```
sudo mkdir /Applications/Xcode4
```

- Drag Xcode.app for Xcode4 into /Applications/Xcode4. Alternate command line variant to mount and copy the Xcode dmg file. This will help in automating the setup process on OSX machines:
```
# Mount the Xcode dmg file
hdiutil attach /path/to/XCODE.dmg

# Copy Xcode.app to the desired location
cp -a /Volumes/Xcode/Xcode.app <PATH_TO_DESIRED_LOCATION>

# Unmout the Xcode dmg file
hdiutil detach /dev/disk...
```

- Download Xcode 7.2.1 from https://developer.apple.com/downloads.
```
sudo mkdir /Applications/Xcode7
```

- Drag Xcode.app for Xcode7 into /Applications/Xcode7. The above command line variant can be used to mount and copy Xcode7 to a desired location. brew won't allow gcc-4.9 to be installed with Xcode4. So, switch to Xcode7.
```
sudo xcode-select -switch /Applications/Xcode7/Xcode.app
```

- Accept Xcode license if needed.
```
sudo xcodebuild -license accept
```

- Install Bash version 4. Instructions: https://gist.github.com/samnang/1759336. `./get_source.sh` asks for Bash version 4. Bash version 4 will be located here: `/usr/local/bin/bash`. Extension repo scripts will try to use `/bin/bash`. `/bin/bash` will point to Bash version 3 after installing Bash version 4. Associate `/bin/bash` symlink to Bash version 4:
```
rm -f /bin/bash
ln -s /usr/local/bin/bash /bin/bash
```

- Install gnu-sed. Default `sed` on OSX won't process carriage returns (`\r`) and new-lines (`\n`). `gsed` will doesn't have this issue.
```
brew install gnu-sed
```

- Install gnu-tar. Default `tar` on OSX doesn't support `--exclude-vcs` option where `gtar` supports `--exclude-vcs`.
```
brew install gnu-tar
```

- Install other required tools.
```
brew install nasm autoconf git freetype
```

- Only required on OSX 10.10 (Yosemite). Edit **line 143** (`typedef void (^dispatch_block_t)(void);`) in **/usr/include/dispatch/object.h**:
```
#ifdef __clang__
typedef void (^dispatch_block_t)(void);
#else
typedef void* dispatch_block_t;
#endif
```

## Building OpenJ9 JDK8

- Download the boot JDK from AdoptOpenJDK. Technically, JDK7 should be used as the boot JDK but JDK7 isn't available at AdoptOpenJDK. So, I used OpenJDK8 with Hotspot as the boot JDK, and no issues were seen: https://adoptopenjdk.net/releases.html#x64_mac.

- Clone openj9-openjdk-jdk8 extensions repo:
```
git clone https://github.com/ibmruntimes/openj9-openjdk-jdk8.git
cd ./openj9-openjdk-jdk8
```

- Download and unzip `freemarker.jar`:
```
wget https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/freemarker-2.3.8.tar.gz/download -O freemarker.tgz
gtar -xzf freemarker.tgz freemarker-2.3.8/lib/freemarker.jar --strip-components=2
rm -f freemarker.tgz
```
The default BSD `tar` on Mac won't strip component. `gtar` should be used to `--strip-components`.

- Set the following environment variables:
```
export SED=gsed
export TAR=gtar

export MACOSX_DEPLOYMENT_TARGET=10.9.0
export SDKPATH=/Applications/Xcode4/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk

export JAVA_HOME=<PATH_TO_BOOT_JDK>
```
^^^ Make sure that the above file and executable paths are valid on the machine. ^^^

- Info about the above environment variables:
```
# SED=gsed overrides the default sed OSX since it doesn't process new lines \n and carriage returns \r.
# TAR=gtar overrides the default tar on OSX since it doesn't support --exclude-vcs option.

# Setting UMA_SUPPRESS_WARNINGS_AS_ERRORS and OMR_WARNINGS_AS_ERRORS: warnings won't be treated as errors.

# If MACOSX_DEPLOYMENT_TARGET is not set to 10.9.0, ./configure will fail.
# SDKPATH points to the Xcode4 SDK directory

# JAVA_HOME should point to the boot JDK.
```

- Run `./configure`:
```
# Compressedrefs
bash ./configure \
    --with-freemarker-jar=<PATH_TO_FREEMARKER_JAR> \
    --with-xcode-path=<PATH_TO_XCODE4_APP> \
    --with-openj9-cc=<PATH_TO_OPENJ9_CC> \
    --with-openj9-cxx=<PATH_TO_OPENJ9_CXX> \
    --with-openj9-developer-dir=<PATH_TO_OPENJ9_DEVELOPER_DIR>

# Non-compressedrefs
bash ./configure \
    --with-freemarker-jar=<PATH_TO_FREEMARKER_JAR> \
    --with-xcode-path=<PATH_TO_XCODE4_APP> \
    --with-openj9-cc=<PATH_TO_OPENJ9_CC> \
    --with-openj9-cxx=<PATH_TO_OPENJ9_CXX> \
    --with-openj9-developer-dir=<PATH_TO_OPENJ9_DEVELOPER_DIR> \
    --with-noncompressedrefs

PATH_TO_XCODE4_APP=/Applications/Xcode4/Xcode.app
PATH_TO_OPENJ9_CC=<POINT_TO_XCODE7_CLANG>
PATH_TO_OPENJ9_CXX=<POINT_TO_XCODE7_CLANG++>
PATH_TO_OPENJ9_DEVELOPER_DIR=/Applications/Xcode7/Xcode.app/Contents/Developer

# OPENJ9_DEVELOPER_DIR, OPENJ9_CC and OPENJ9_CXX are used to specify custom
# tools to build OpenJ9. The default tools Xcode4 + gcc-4.2 will fail to build OpenJ9.
```

- Run `make`:
```
# Variant 1
make all

# In JDK8, build.log isn't generated. Also, make's output may have insufficient info for debugging.
# For debugging, make can be run as follows:
make LOG=trace all 2>&1 | tee make_images.log

# Shorter and quicker variant if one doesn't want to run "make all".
make images
```

If `make` is successful, a `j2sdk-images` and a `j2re-image` should be generated in the `build` directory.

**Comment by babsingh** [comment]
fyi - @DanHeidinga @groeges @AdamBrousseau @jdekonin

**Comment by babsingh** [comment]
related to https://github.com/eclipse/openj9/issues/36

**Comment by jdekonin** [comment]
@cwillhelm can you please setup the remaining 3 macs using these instructions.  Please provide any questions or feedback here.  Thanks.

**Comment by cwillhelm** [comment]
For these statements `Drag Xcode.app for Xcode4 into /Applications/Xcode4`

is it as simple as doing `cp Xcode.app` into `/Applications/Xcode4` Or are there other files / steps that need to be done? I ask because this configuration is being done completely from the CLI.

**Comment by babsingh** [comment]
@cwillhelm Xcode comes as a `*.dmg` file. To access `Xcode.app`, mounting and unzipping is done by the OS when you double click the `*.dmg` file. If you can convert `*.dmg` -> `Xcode.app`, then `cp` should probably work. You will have to figure out the cmds.

**Comment by babsingh** [comment]
fyi @sxa555

**Comment by cwillhelm** [comment]
Do you specifically need MacOS 10.10, or can we use a newer version? (10.13)

**Comment by babsingh** [comment]
not sure. it will depend on whether Xcode4 and Xcode7 work with a newer OSX version.

**Comment by babsingh** [comment]
Added instructions to **Build OpenJ9 JDK8** in the first post.

**Comment by babsingh** [comment]
A good source for build platform requirements - https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms. 

### JDK 8 build platforms supported by Oracle
OS and CPU | OS Type/Vendor | OS Version | Compiler/Toolchain Type/Vendor | Compiler/Toolchain version | Notes
-- | -- | -- | -- | -- | -- |
Mac OSX x86_64 | Mac OS X | 10.7 (Lion) | Xcode / gcc | 4.6.2 | 

### Other JDK 8 build platforms
Platform | Status | OS Type/Vendor and Version | Compiler/Toolchain Type/Vendor and Version | Notes
-- | -- | -- | -- | --
Mac OS X x86_64 |  Works correctly | Mac OS X 10.8 (Mountain Lion) | XCode / gcc 4.2.1 | Maintained by SAP

**Comment by cwillhelm** [comment]
Some additional steps to do prior to starting install:

```
mkdir /Users/bruin

dscl . -create /Users/bruin
dscl . -create /Users/bruin UserShell /bin/bash
dscl . -create /Users/bruin RealName “new” 
dscl . -create /Users/bruin UniqueID "510"     # make sure no other user has this id 
dscl . -create /Users/bruin PrimaryGroupID 20
dscl . -create /Users/bruin NFSHomeDirectory /Users/bruin
dscl . -passwd /Users/bruin brewtest      # change me 

visudo        # add bruin to sudoers
sudo chown -R bruin:admin /Users/bruin

su - bruin
sudo xcode-select --reset
```

**Comment by babsingh** [comment]
Changes to the JDK8 build process. The following environment variables won't work anymore:
```
export OPENJ9_USE_CUSTOM_COMPILER=1
export OPENJ9_DEVELOPER_DIR="/Applications/Xcode7/Xcode.app/Contents/Developer"
export OPENJ9_CC="/usr/local/bin/gcc-4.9"
export OPENJ9_CXX="/usr/local/bin/g++-4.9"
```
Reference: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/147. Instead of using the above environment variables, `./configure` needs to be run differently:
```
bash ./configure \
    --with-freemarker-jar=<PATH_TO_FREEMARKER_JAR> \
    --with-xcode-path=<PATH_TO_XCODE4_APP> \
    --with-openj9-cc=<PATH_TO_OPENJ9_CC> \
    --with-openj9-cxx=<PATH_TO_OPENJ9_CXX> \
    --with-openj9-developer-dir=<PATH_TO_OPENJ9_DEVELOPER_DIR>
```
**Examples:**
- <PATH_TO_XCODE4_APP>: `/Applications/Xcode4/Xcode.app`
- <PATH_TO_OPENJ9_CC>: `/Applications/Xcode7/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`
- <PATH_TO_OPENJ9_CXX>: `/Applications/Xcode7/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++`
- <PATH_TO_OPENJ9_DEVELOPER_DIR>: `/Applications/Xcode7/Xcode.app/Contents/Developer`

**Comment by babsingh** [comment]
^^^ fyi: @sxa555 @groeges @AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
I also needed to install `pkg-config` and I didn't need to modify `/usr/include/dispatch/object.h` or `/bin/bash`.  The system I used was 10.11.6 (El Capitan), an update to 10.12 (Sierra) causes failures with xcode4.

**Comment by babsingh** [comment]
> undo the change to object.h on the machines that we needed previously?

The `object.h` change is needed to workaround an OSX 10.10 specific bug. @jdekonin setup the machines with OSX 10.11 where the `object.h` workaround is not needed.

**Note:** One won't be able to edit `object.h` on OSX >= 10.11 without [disabling System Integrity Protection (SIP)](https://www.imore.com/how-turn-system-integrity-protection-macos), which is a tedious step.

fyi - @sxa555

**Comment by babsingh** [comment]
The knowledge for setting up OSX machines for OpenJ9 JDK8 development has been transferred to the infra team. Machines have been setup, and the infra team has developed the required scripts for setting up OSX machines for OpenJ9 JDK8 development. Thus, closing this issue. 

fyi - @jdekonin @sxa555.
