### ISSUE TITLE
OpenJ9 JDK8 OSX g++4.9 -Werror=header-guard unrecognized

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3326]
When building OpenJ9 JDK8 on OSX, the following compiler option was unrecognized: `-Werror=header-guard`.

This compiler option is used by the JIT [runtime/compiler/build/toolcfg/gnu/common.mk](https://github.com/eclipse/openj9/blob/master/runtime/compiler/build/toolcfg/gnu/common.mk#L179):
```
ifeq ($(C_COMPILER),clang)
    CX_FLAGS+=-Wno-parentheses -Werror=header-guard
endif
```

When building JDK8 on OSX, `gcc-4.9` was used. The above `ifdefs` only add the compiler option if `C_COMPILER == clang`. Since `gcc-4.9` was used, `-Werror=header-guard` shouldn't be added. Perhaps, a setup issue.

After removing `-Werror=header-guard`, OpenJ9 JDK8 built without errors on OSX.

**Comment by DanHeidinga** [comment]
@nbhuiyan mentioned he'll pick this up
