### ISSUE TITLE
MacOS: shared classes cannot allocate memory

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#3346]
> $ java -Xshareclasses:nonpersistent,controlDir=.,name=Sanity,expire=0 -Xscmx5M  HelloWorld
JVMSHRC005I No shared class caches available
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC336E Port layer error code = -393970
JVMSHRC337E Platform error message: shmget : Cannot allocate memory
JVMSHRC029E Not enough memory left on the system
JVMSHRC663I Error recovery: destroyed semaphore set with id=12189697 associated with shared class cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed

There is plenty of shared memory:

> $ sysctl -a | grep shm
kern.sysv.shmmax: 33554432
kern.sysv.shmmin: 1
kern.sysv.shmmni: 32
kern.sysv.shmseg: 8
kern.sysv.shmall: 1024
$ ipcs -a
IPC status from <running system> as of Thu Oct 18 10:40:20 EDT 2018
T     ID     KEY        MODE       OWNER    GROUP  CREATOR   CGROUP CBYTES  QNUM QBYTES LSPID LRPID   STIME    RTIME    CTIME
Message Queues:
q  65536 0xf803ffff --rw-------   pdbain    staff   pdbain    staff     56      7   2048  62213  62213  1:05:49  1:05:49 13:04:53

> T     ID     KEY        MODE       OWNER    GROUP  CREATOR   CGROUP NATTCH  SEGSZ  CPID  LPID   ATIME    DTIME    CTIME
Shared Memory:
m  65536 0x00fedc64 --rw-rw-rw-     root    wheel     root    wheel      1      8     79     79 13:04:08 no-entry 13:04:08
m  65537 0x5205d34e --rw-------     root    wheel     root    wheel      2 159744     70    306 13:04:09 13:04:09 13:04:09
 
> T     ID     KEY        MODE       OWNER    GROUP  CREATOR   CGROUP NSEMS   OTIME    CTIME
Semaphores:
s 52166656 0xa105bf16 --ra-ra-ra-   pdbain    staff   pdbain    staff      2 10:25:36 10:24:55

**Comment by hangshao0** [comment]
From http://www.spy-hill.com/myers/help/apple/SharedMemory.html
```
shmall
    Maximum amount of shared memory (measured in pages). This is generally shmmax divided by 4096. 
```

> kern.sysv.shmall: 1024

It is only 4MB

**Comment by pdbain-ibm** [comment]
I'll fix that and retest.  Unfortunately that means a reboot.

**Comment by pdbain-ibm** [comment]
Thanks @hangshao0 . That did the trick:
>$ cat /etc/sysctl.conf 
kern.sysv.shmmax=33554432
kern.sysv.shmmin=1
kern.sysv.shmmni=32
kern.sysv.shmseg=8
kern.sysv.shmall=8192
$ java -Xshareclasses:nonpersistent,controlDir=.,name=Sanity,expire=0 -Xscmx5M -cp $HOME/lib HelloWorld
JVMSHRC005I No shared class caches available
Hello, world!

**Comment by DanHeidinga** [comment]
Is this something we should document for users?  I don't know what the common setting for `kern.sysv.shmall` is on mac

**Comment by pdbain-ibm** [comment]
On my machine `smmax` was 4 meg and `shmall` was 1024 pages.  @DanHeidinga if you want to check on your machine, the command is `sysctl -a`, though I pipe it through `grep shm` to limit the output.

**Comment by DanHeidinga** [comment]
```
$ sysctl -a | grep shm
kern.sysv.shmmax: 4194304
kern.sysv.shmmin: 1
kern.sysv.shmmni: 32
kern.sysv.shmseg: 8
kern.sysv.shmall: 1024
machdep.pmap.hashmax: 40
security.mac.posixshm_enforce: 1
security.mac.sysvshm_enforce: 1
```

**Comment by hangshao0** [comment]
> Is this something we should document for users?

Yes, I think this should be documented.

**Comment by hangshao0** [comment]
> what is the behaviour of shared classes when no size is specified? A small shared memory limit may silently cause sub-optimal cache performance.

We will try an default size. We will fall back to shmmax if shmmax is less than the default size with an NLS message.
