### ISSUE TITLE
JITaaS: Aggressively cache information for j9classes at the server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#3349]
Currently, when the JITaaS server inquires about some field of a j9class the following pattern is used:
```
if j9class is cached
   return desired field
else
    send a message to client to get the value of the desired field
```
The proposal is to fetch all the info about a j9class (not just the desired field) when it is not cached. This transfers a lot more data, but the assumption is that future queries about j9class fields will be avoided, thus saving CPU. 
We need to measure whether this technique actually saves CPU and network traffic.

**Comment by fjeremic** [comment]
Do we have data on which fields we usually request info about? Is it only specific classes (recognized fields for example or JCL classes) or is it arbitrary classes?

**Comment by mpirvu** [comment]
The classes are arbitrary.
Examples of fields the optimizer wants to know can be found in https://github.com/eclipse/openj9/issues/3201
