### ISSUE TITLE
JITaaS: Override isAnonymousClass(TR_OpaqueClassBlock *j9clazz)

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#3351]
This frontend method accesses j9class fields and needs to be overridden to work correctly at the JITaaS server. Probably it was missed because the definition is in the header file rather than the cpp file.

**Comment by mpirvu** [comment]
@satbir-ca Could you please implement this missing frontend query?

**Comment by satbir-ca** [comment]
@mpirvu I will do that. Thanks
