### ISSUE TITLE
DDR Tests do not compile with OpenJ9 OSX builds

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#3366]
From https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk11_j9_functionaltest_x86-64_macos/4/consoleFull

00:08:49     [javac] /Users/jenkins/workspace/openjdk11_j9_functionaltest_x86-64_macos/openjdk-tests/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java:60: error: package com.ibm.j9ddr.tools.ddrinteractive does not exist
00:08:49     [javac] import com.ibm.j9ddr.tools.ddrinteractive.Context;
00:08:49     [javac]         
...

For developer builds I have been deleting the directory, to workaround this, but we should address it properly as we proceed.

**Comment by llxia** [comment]
Compilation and execution for DDR tests in `DDR_Test` are disabled in #3494
DDR cmdLineTests are excluded in https://github.com/eclipse/openj9/pull/3505

**Comment by pshipton** [comment]
@llxia DDR is now partially enabled for osx so I think the tests should compile now. The tests still cannot run until #3483

**Comment by llxia** [comment]
Remove `test excluded` label as the DDR tests are re-enabled on osx.
