### ISSUE TITLE
Ensure stack maps are generated for exception catch blocks on x86

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3374]
Please see the parent Epic for further details. We need to ensure that under the new mode we generate stack maps at the start of every exception catch block and ensure that we don't enable throw to goto transformations when this mode is enabled.

**Comment by gacholio** [comment]
See #3373 for latest comments.

**Comment by 0dvictor** [comment]
On X86, the related code is part of OMR; so that an OMR pull request has been created.
https://github.com/eclipse/omr/pull/3104

**Comment by 0dvictor** [comment]
After rethinking the purpose of this Issue, I withdraw my proposal to implement this in OMR, and am proposing #3462 - a J9-only implementation.

**Comment by gacholio** [comment]
Seems this issue is no longer useful.

**Comment by fjeremic** [comment]
> Seems this issue is no longer useful.

@gacholio this issue was supposed to be closed by #3462 where support is actually added.

**Comment by gacholio** [comment]
Ah, got confused by the common change.
