### ISSUE TITLE
Using "../java" in system.c when looking for a shared library doesn't work on zOS

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#3392]
A change went in recently: https://github.com/eclipse/openj9/pull/3176 to fix an issue with MacOS but this fix has broken the zOS builds. See issue: https://github.ibm.com/runtimes/openjdk-contribution/issues/631 for details of issue.   This needs to be resolved in order to get the zOS builds working again.

**Comment by tajila** [comment]
Ill take a look at this

**Comment by groeges** [comment]
@tajila Any progress on this?

**Comment by tajila** [comment]
I have a PR https://github.com/eclipse/omr/pull/3148

**Comment by pshipton** [comment]
Does the original change to use `../` only work because it fails to find the library at that path and falls back to search the portlib directory?

**Comment by tajila** [comment]
@pshipton yes

**Comment by pshipton** [comment]
I think I'm still missing something. If "../java" always fails on Mac, and the fallback makes it work, wouldn't just using "java" have been sufficient on the Mac, as it could also fail and then use the fallback?

**Comment by tajila** [comment]
I'm not sure what happens on mac, I never tried it there. But on xa64 `../java` only works because of the fallback.

**Comment by pshipton** [comment]
Perhaps I misunderstood. Does the fallback still use the `../java` path, but from the portlib directory?

**Comment by DanHeidinga** [comment]
> Does the fallback still use the ../java path, but from the portlib directory?

Yes. it makes the path relative to the portlib directory as libjava.so is up one level from the compressed | default directories

**Comment by pshipton** [comment]
#3535 was reverted
#3542 fixes the problem.
