### ISSUE TITLE
openj9_8u192b12: Duplicate classes in the boot class path jars

### ISSUE THREAD

**Issue by TeaJayOrg** [eclipse/openj9#3393]
Some classes occur at least twice - in different jars -  on the `sun.boot.class.path`:

```
sun/awt/motif/X11GB2312$Decoder.class
	 ../OpenJ9/jre/lib/charsets.jar
	 ../OpenJ9/jre/lib/rt.jar
-------------------------------------------------------------

sun/awt/motif/X11KSC5601$Decoder.class
	 ../OpenJ9/jre/lib/charsets.jar
	 ../OpenJ9/jre/lib/rt.jar
-------------------------------------------------------------

sun/awt/motif/X11KSC5601$Encoder.class
	 ../OpenJ9/jre/lib/charsets.jar
	 ../OpenJ9/jre/lib/rt.jar
-------------------------------------------------------------

sun/awt/motif/X11GB2312$Encoder.class
	 ../OpenJ9/jre/lib/charsets.jar
	 ../OpenJ9/jre/lib/rt.jar
-------------------------------------------------------------

sun/awt/motif/X11GBK$Encoder.class
	 ../OpenJ9/jre/lib/charsets.jar
	 ../OpenJ9/jre/lib/rt.jar
-------------------------------------------------------------
```
I don't believe that this is intentional.

It makes my compiler unusable on openj9_8 as it doesn't accept duplicate class names when scanning the libraries. There are no problems with at least version 11.0.1_13  (using the jrt:/ file system). I did not have such problems with the HotSpot OpenJDK 8 (from Ubuntu repos).

Attached is the Program that produces the above output. 

[P.java.zip](https://github.com/eclipse/openj9/files/2501363/P.java.zip)

**Comment by pshipton** [comment]
@andrew-m-leonard can you please investigate.

**Comment by andrew-m-leonard** [comment]
@pshipton jtreg failure found this too, existing issue: https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/142
The problem is actually in the make file macro which we replaced with a better version of,  ListPathsSafely 
Not sure if @keithc-ca know anything about why we replaced this macro?

**Comment by keithc-ca** [comment]
The recent changes to `ListPathsSafely` were so it would properly handle _source_ files whose names include the `$` character.

https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/154 should fix this.
