### ISSUE TITLE
OMR acceptance trying to build Pipeline-Build-Test-JDK11-zos_390-64_cmprssptrs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3420]
OMR acceptance shouldn't be gated on a z/OS build (atm).

`No item named Pipeline-Build-Test-JDK11-zos_390-64_cmprssptrs found`

https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-OMR-Acceptance/detail/Pipeline-OMR-Acceptance/866/pipeline/70

**Comment by pshipton** [comment]
@vsebe

**Comment by vsebe** [comment]
Provided a list of platform to the jenkins build, zos excluded (should apply to the new builds). 
[Pipeline-OMR-Acceptance](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/868/)
