### ISSUE TITLE
Software based Concurrent Scavenge support on P

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#3421]
The software based read barrier solution for pauseless GC on P

Related issue for Z: https://github.com/eclipse/openj9/issues/3276

Doc issue https://github.com/eclipse/openj9-docs/issues/134

Pull requests:
https://github.com/eclipse/openj9/pull/4159
https://github.com/eclipse/openj9/pull/4712

Dependencies:
 https://github.com/eclipse/openj9/issues/3453

**Comment by SueChaplain** [comment]
Hi @gita-omr 

Assuming we will need some documentation to support this.  Please add doc:externals label to this and  open an issue at openj9-docs repo: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md so we can plan for this in the 0.12.0 list.

**Comment by gita-omr** [comment]
An update:
While working on non-compressed version, @jimmyk found a problem with the way read barriers are generated for NULLCHK trees. @0dvictor is working on a different solution right now. @andrewcraik @fjeremic. I imagine this might affect all read/write barrier opcodes @cathyzhyi ...

**Comment by 0dvictor** [comment]
The NULLCHK issue will be fixed with https://github.com/eclipse/openj9/pull/3798.

**Comment by gita-omr** [comment]
@pshipton : @IBMJimmyk made some cosmetic changes after another code review and we would like to run more tests. They will be done by Monday morning. Could the code split wait for that?

**Comment by pshipton** [comment]
Yes, since we got not much delivered today because of the Jenkins issues it seems we need to delay another day.

**Comment by pshipton** [comment]
Deferred to the next release.

**Comment by gita-omr** [comment]
@pshipton we are ready to deliver it to 0.13.

**Comment by pshipton** [comment]
@gita-omr when do you expect the merges to occur?

**Comment by gita-omr** [comment]
@pshipton @amicic I updated Dependencies in the description -- JVMTI fixes for CS.

**Comment by gita-omr** [comment]
Just merged #4159

**Comment by fjeremic** [comment]
> Just merged #4159

@gita-omr left some extra review comments on that PR. There are some changes required.

**Comment by vij-singh** [comment]
@gita-omr are we still ok for 0.13.0 ?

**Comment by SueChaplain** [comment]
@gita-omr is this now moved to 0.14.0 please?

**Comment by gita-omr** [comment]
No, it's in 0.13. We generally try to keep milestone field up to date.

**Comment by gita-omr** [comment]
Sorry, just noticed @vij-singh question. This is definitely in 0.13.

**Comment by SueChaplain** [comment]
@gita-omr - please can you revisit the docs issue you created a while back (https://github.com/eclipse/openj9-docs/issues/134) to see if you can provide any further information. It implies that the info will be similar to that for z, except that is definitely moved in to 0.14. Thanks!

**Comment by gita-omr** [comment]
Yeah,  I meant that the description of software-based CS is the same on Intel, Power, Z (if enabled). As of 0.13 it will be enabled on Intel and Power. Let me review the docs once again to make sure they are up to date in terms of which platform the feature is being enabled.

**Comment by pshipton** [comment]
@gita-omr can this Issue be closed now?

**Comment by gita-omr** [comment]
Yes, I just should not that we enabled this on Power Linux LE and AIX. We will open an issue for 0.14 for software-based CS on Linux BE. I will update documentation accordingly.
