### ISSUE TITLE
Improved performance for watched fields on P

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#3422]
Parent issue: https://github.com/eclipse/openj9/issues/2668
Includes design in this comment: https://github.com/eclipse/openj9/issues/2668#issuecomment-414756016

Apply  https://github.com/eclipse/openj9/issues/3153  on P

docs:
https://github.com/eclipse/openj9-docs/issues/305
test:
https://github.com/eclipse/openj9/pull/6257
PRs:
eclipse/omr#4068
#6234

**Comment by pshipton** [comment]
I'm told this won't be ready for the 0.12 release, moving to the next quarterly release 0.14. If it happens to get completed for the 0.13 (Java 12) release, we'll adjust the milestone.

**Comment by gita-omr** [comment]
@pshipton we really want to get it done in next couple weeks. Can we change the milestone to 0.13 just so that it's on the radar?

**Comment by pshipton** [comment]
@gita-omr The 0.14 release should be on your radar. This is the next quarterly release in April. The 0.13 release in March is focused on Java 12 and will only deliver Java 12 builds.

**Comment by gita-omr** [comment]
We need more time. Changing to 0.15.

**Comment by DanHeidinga** [comment]
We're coming up on the `0.15.0` "reality check" date of June 18 to determine what will make the release.  Is this going to be ready for the June 24 code split?

**Comment by gita-omr** [comment]
@DanHeidinga we are working on it but I will let @AlenBadel confirm.

**Comment by AlenBadel** [comment]
@DanHeidinga Yes, this will definitely be ready by then.

**Comment by pshipton** [comment]
Reminder the code split for 0.15 happens on Sunday.

**Comment by AlenBadel** [comment]
Watched Fields implementation has been requested here:
https://github.com/eclipse/omr/pull/4068
https://github.com/eclipse/openj9/pull/6234

**Comment by DanHeidinga** [comment]
Given how close we are to the `0.15.0` release date, moving this out to `0.16.0`.

**Comment by gita-omr** [comment]
@AlenBadel has a fix but unfortunately personal build takes very long time. He will try to merge the fix today in anyway (into master).

**Comment by pshipton** [comment]
@gita-omr can this be resolved now?
