### ISSUE TITLE
JVM_SocketShutdown() stubbed

### ISSUE THREAD

**Issue by planetf1** [eclipse/openj9#3442]
When attempting to build github.com/odpi/egeria under J9 192 b12 (from adoptopenjdk.net) on MacOPS Mojave under Intellij IDEA & using maven 3.5.4 I get an exception

Assertion failed: (!"JVM_SocketShutdown() stubbed!"), function JVM_SocketShutdown, file j7vmi.c, line 2375.
JVMDUMP039I Processing dump event "abort", detail "" at 2018/10/25 08:15:25 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jonesn/java/jdk8u192-b12/Contents/Home/bin/core.20181025.081525.44173.0001.dmp' in response to an event

See also #3441 where the same code/IDE fails on windows, but with a slightly different exception

**Comment by pdbain-ibm** [comment]
@planetf1 do you have a stack trace or javacore?

**Comment by planetf1** [comment]
Hi - I posted the javacore TXT file above. I have the full core too if it helps, but it is 2.6GB. I didn't even try attaching ;-) I could transfer it somewhere if it helps?

**Comment by babsingh** [comment]
Currently, `defined(J9UNIX) || defined(OSX)` is used at a lot of places. [inconsistencies] We have missed to add `defined(OSX)` at some `defined(J9UNIX)` locations. It will be cleaner to enable `J9UNIX` for OSX instead of using `defined(J9UNIX) || defined(OSX)`. @pshipton @pdbain-ibm thoughts?

**Comment by pdbain-ibm** [comment]
Since OSX is derived from BSD Unix I suggest we do so.

**Comment by babsingh** [comment]
At some places, `J9UNIX` code doesn't apply to `OSX`. With this revelation, it won't be straight forward to enable `J9UNIX` on `OSX`. Someone will have to look at all `J9UNIX` locations and evaluate if that piece of code is needed for `OSX`.

Example -`jvm.c::JVM_SetLength`
```
#elif defined(J9UNIX) && !defined(J9ZTPF)
	result = ftruncate64(fd, length);
#elif defined(J9ZOS390) || defined(J9ZTPF) || defined(OSX)
	result = ftruncate(fd, length);
```

Another case - in `jvm.c::JVM_Available`, `stat` is used on `OSX` whereas `stat64` is used on `J9UNIX`.
```
#if defined(J9UNIX) && !defined(J9ZTPF)
		struct stat64 tempStat;
#endif
#if defined(J9ZOS390) || defined(J9ZTPF) || defined(OSX)
		struct stat tempStat;
```

**Comment by pshipton** [comment]
Although there are only 34 places where J9UNIX is used, and fewer that don't already use OSX as well. I would be worth looking at the remaining places to see if OSX needs to be added.

**Comment by gacholio** [comment]
Should OSX just define J9UNIX?

**Comment by pdbain-ibm** [comment]
I concur with @gacholio . Personally, I would like OSX to imply J9UNIX. In cases where that is invalid, i.e. in which J9UNIX applies but need special treatment for OSX, we should handle that case explicitly.

**Comment by babsingh** [comment]
Moving discussion about `J9UNIX` usage to a new issue: https://github.com/eclipse/openj9/issues/3452.
