### ISSUE TITLE
MacOS: DDR: No Image sources found for dump file

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#3444]
To reproduce:
Create a dump file, e.g. `java -Xdump:system:events=vmstop HelloWorld`, then try to open it:
`jdmpview -core core.20181025.090255.99913.0001.dmp`.

```
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

Could not load dump file and/or could not load XML file: No Image sources were found for /some/random/directory/core.20181025.090255.99913.0001.dmp
```

**Comment by babsingh** [comment]
Currently, DDR is unavailable on OSX. Mike is working on getting DDR ready for OSX. Core files on OSX won't have DDR support and `jdmpview` won't work on OSX until DDR is ported to OSX.

fyi - @tajila @mikezhang1234567890 @keithc-ca

**Comment by mikezhang1234567890** [comment]
Currently working on core reader to support the OSX file format (Mach-O). Estimate to be done in January.
