### ISSUE TITLE
Enable J9UNIX locations on OSX

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3452]
Since OSX is derived from BSD Unix, it seems logical to enable `J9UNIX` on OSX.

Currently, `defined(J9UNIX) || defined(OSX)` is used at a lot of places. There are inconsistencies where we have missed to add `defined(OSX)` at some `defined(J9UNIX)` locations. It will be cleaner to enable `J9UNIX` on OSX instead of using `defined(J9UNIX) || defined(OSX)` everywhere.

At some places, `J9UNIX` code doesn't apply to `OSX`. With this revelation, it won't be straight forward to enable `J9UNIX` on `OSX`. Someone will have to look at all `J9UNIX` locations and evaluate if that piece of code is needed for `OSX`.

Example -`jvm.c::JVM_SetLength`
```
#elif defined(J9UNIX) && !defined(J9ZTPF)
	result = ftruncate64(fd, length);
#elif defined(J9ZOS390) || defined(J9ZTPF) || defined(OSX)
	result = ftruncate(fd, length);
```

Another case - in `jvm.c::JVM_Available`, `stat` is used on `OSX` whereas `stat64` is used on `J9UNIX`.
```
#if defined(J9UNIX) && !defined(J9ZTPF)
		struct stat64 tempStat;
#endif
#if defined(J9ZOS390) || defined(J9ZTPF) || defined(OSX)
		struct stat tempStat;
```

There may be more places where `J9UNIX` code doesn't apply to `OSX`. We need to be careful.

There is mixed opinion the possible approaches:

**Approach 1:** Some want `J9UNIX` enabled on `OSX` and special cases where `J9UNIX` doesn't apply to `OSX` handled separately.
**Approach 2:** Although there are only 34 places where `J9UNIX` is used, and fewer that don't already use `OSX` as well. It would be worth looking at the remaining places to see if `OSX` needs to be added.

Which approach should be taken?

### `J9UNIX` is used at 20 locations in OpenJ9:

1) `jvm.c::JVM_SocketShutdown` - J9UNIX and OSX execute the same code.
```
jint JNICALL
JVM_SocketShutdown(jint fd, jint howto)
{
	jint retVal = JNI_FALSE;

#if defined(J9UNIX) || defined(OSX)
	retVal = shutdown(fd, howto);
#elif defined(WIN32) /* defined(J9UNIX) || defined(OSX) */
	retVal = closesocket(fd);
#else /* defined(J9UNIX) || defined(OSX) */
	assert(!"JVM_SocketShutdown() stubbed!");
#endif /* defined(J9UNIX) || defined(OSX) */
```
2) `j9vm_internal.h` - J9UNIX and OSX execute the same code to include header files.
```
#if defined(J9UNIX) || defined(OSX)
#include <sys/socket.h>
#include <dlfcn.h>
#include <sys/ioctl.h>
#include <setjmp.h>
#include <sys/time.h>
#if defined(J9ZTPF) || defined(OSX)
#define J9FSTAT fstat
#else /* defined(J9ZTPF) */
#define J9FSTAT fstat64
#endif /* !defined(J9ZTPF) */
#endif /* J9UNIX */
```
3) `jvm.c::DestroyJavaVM` - The below code is not invoked on OSX. J9UNIX and OSX should both execute the below code.
```
#if defined(J9UNIX) || defined(J9ZOS390)
		j9vm_dllHandle = 0;
		java_dllHandle = 0;
#endif
```
4) `jvm.c::preloadLibraries` - J9UNIX and OSX both include definition of `preloadLibraries`. 
```
#if defined(J9UNIX) || defined(J9ZOS390) || defined(OSX)
static BOOLEAN 
preloadLibraries(void)
{
    ....
}
#endif  /* defined(J9UNIX) || defined(J9ZOS390) */
```
5) `jvm.c::JNI_CreateJavaVM` - Copy `DYLD_LIBRARY_PATH` onto `ldLibraryPathValue`. Same code used by J9UNIX and OSX.
```
#if defined(J9UNIX) || defined(OSX)
	ldLibraryPathValue = getenv(ENV_LD_LIB_PATH);
	if (NULL != ldLibraryPathValue) {
		size_t pathLength = strlen(ldLibraryPathValue) +1;
		char *envTemp = malloc(pathLength);
		if (NULL == envTemp) {
			result = JNI_ERR;
			goto exit;
		}
		strcpy(envTemp, ldLibraryPathValue);
		ldLibraryPathValue = envTemp;
	}
#endif
```
6) `vmargs_api.h` - On OSX, `LD_LIBRARY_PATH` equivalent is `DYLD_LIBRARY_PATH`. So, `ENV_LD_LIB_PATH` should be defined as follows:
```
#if defined(OSX)
#define ENV_LD_LIB_PATH "DYLD_LIBRARY_PATH"
#else /* defined(OSX) */
#define ENV_LD_LIB_PATH "LD_LIBRARY_PATH"
#endif /* defined(OSX) */
```
7) `jvm.c::JNI_CreateJavaVM` - Get `IBM_MALLOCTRACE_STR` environment variable. Same code used by J9UNIX and OSX.
```
#if defined(J9UNIX) || defined(J9ZOS390) || defined(OSX)
	if (getenv(IBM_MALLOCTRACE_STR)) {
		ibmMallocTraceSet = TRUE;
	}
#endif
```
8) `jvm.c::preloadLibrary` - Derive the path to a library using the path to `libjvm.dylib` as a reference. Same code is shared between J9UNIX and OSX.
```
#if defined(J9UNIX) || defined(OSX)
	buffer = jvmBufferCat(buffer, "/lib");
	buffer = jvmBufferCat(buffer, dllName);
	buffer = jvmBufferCat(buffer, J9PORT_LIBRARY_SUFFIX);
        ....
```
9) `jvm.c::JVM_LoadSystemLibrary` - Same code is shared between J9UNIX and OSX.
10) `jvm.c::JVM_LoadLibrary` - Code is only enabled for J9UNIX. This code should also be enabled for OSX. Code is similar to `JVM_LoadSystemLibrary`. Currently, `JVM_LoadLibrary` won't work properly on OSX.
11) `jvm.c::JVM_Available` - J9UNIX and OSX code slightly differs here.
```
#if defined(J9UNIX) && !defined(J9ZTPF)
		struct stat64 tempStat;
#endif
#if defined(J9ZOS390) || defined(J9ZTPF) || defined(OSX)
		struct stat tempStat;
#endif
```
12) `jvm.c::JVM_Available` - The below code should also be enabled on OSX. Currently, it is disabled. So, `JVM_Available` won't function properly on OSX.
```
#if (defined(LINUX) && !defined(J9ZTPF)) || defined(AIXPPC) || defined(J9ZOS390)
				else {
					struct pollfd pollOne;
					int  ret = 0;
					pollOne.fd = descriptor;
					pollOne.events = POLLRDNORM | POLLRDBAND | POLLPRI;
					pollOne.revents = 0;
					if (-1 != poll(&pollOne, 1, 0)) {
						/* poll succeeded (-1 is failure) */
						if(0 != (pollOne.events & pollOne.revents)) {
							/* if the one descriptor we were looking at returns a modified revents
									which matches a read operation, return at least one byte readable */
							*bytes = 1;
							Trc_SC_Available_Exit(1, *bytes);
							return 1;
						} else {
							/* none of the events are ready so this is 0 bytes readable */
							*bytes = 0;
							Trc_SC_Available_Exit(1, *bytes);
							return 1;
						}
					} else {
						/* poll failed so use a poll failure trace point and return failure */
						Trc_SC_Available_poll_failed(descriptor, errno);
						*bytes = 0;
						return 0;
					}
				}
#endif
```
13) `jvm.c::JVM_Open` - J9UNIX and OSX code slightly differs here.
```
#if defined(J9UNIX) && !defined(J9ZTPF)
	struct stat64 tempStat;
	int doUnlink;
#endif
#if defined(J9ZOS390) || defined(J9ZTPF) || defined(OSX)
	struct stat tempStat;
	int doUnlink;
#endif
```
14) `jvm.c::JVM_Open` - J9UNIX and OSX share the same code here.
```
#if defined(J9UNIX) || defined(J9ZOS390) || defined(OSX)
#if defined(OSX)
#define EXTRA_OPEN_FLAGS 0
#else
#define EXTRA_OPEN_FLAGS O_LARGEFILE
#endif /* defined(OSX) */

#ifndef O_DSYNC
#define O_DSYNC O_SYNC
#endif

	doUnlink = (flags & O_TEMPORARY);
#if !defined(J9ZTPF)
    flags &= (O_CREAT | O_APPEND | O_RDONLY | O_RDWR | O_TRUNC | O_WRONLY | O_EXCL | O_NOCTTY | O_NONBLOCK | O_NDELAY | O_SYNC | O_DSYNC);
#else /* !defined(J9ZTPF) */
    flags &= (O_CREAT | O_APPEND | O_RDONLY | O_RDWR | O_TRUNC | O_WRONLY | O_EXCL | O_NOCTTY | O_NONBLOCK | O_SYNC | O_DSYNC);
#endif /* defined(J9ZTPF) */
#endif /* defined(J9UNIX) || defined(J9ZOS390) || defined(OSX) */
```
15) `jvm.c::JVM_Open` - Currently, disabled. The below code should be enabled on OSX. Otherwise, `JVM_Open` won't work properly on OSX.
```
#if defined(J9UNIX) || defined(J9ZOS390)
	do {
		errorVal = 0;
#endif

#ifdef J9OS_I5
	returnVal = Xj9Open_JDK6((char *)filename, (flags | EXTRA_OPEN_FLAGS), mode);
#else
	returnVal = open(filename, (flags | EXTRA_OPEN_FLAGS), mode);
#endif
	if (-1 == returnVal) {
		errorVal = errno;
	}

#if defined(J9UNIX) || defined(J9ZOS390)
	/* Unix open() call does not reject directories, so extra checks required */
	if ((returnVal>=0) && (J9FSTAT(returnVal, &tempStat)==-1)) {
		Trc_SC_Open_fstat64(filename);
		close(returnVal);
		return -1;
	}
	if ((returnVal>=0) && S_ISDIR(tempStat.st_mode)) {
		char buf[1];

		Trc_SC_Open_isDirectory(filename);

		/* force errno to be EISDIR in case JVM_GetLastErrorString is called */
		errno = EISDIR;

		close(returnVal);
		return -1;
	}

	/* On unices, open() may return EAGAIN or EINTR, and should then be re-invoked */
	}
	while ((-1 == returnVal) && ((EAGAIN == errorVal) || (EINTR == errorVal)));

	/* Unix does not have an O_TEMPORARY flag. Unlink if Sovereign O_TEMPORARY flag passed in. */
	if ((returnVal>=0) && doUnlink)
		unlink(filename);
#endif
```
16) `jvm.c::JVM_SocketAvailable` - J9UNIX and OSX share the same code.
17) `jvm.c::JVM_Timeout` - J9UNIX and OSX share the same code.
18) `jvm.h` - Enable `__USE_LARGEFILE64` and add header files. Currently, disabled. The below code should be enabled on OSX.
```
#ifdef J9UNIX
#ifndef __USE_LARGEFILE64
#define __USE_LARGEFILE64
#endif
#include <unistd.h>
#include <sys/param.h>
#include <dirent.h>
#endif /* J9UNIX */
```
19) `jvm.h` - Currently, disabled. The below code should be enabled on OSX. OSX supports `sigjmp_buf`. [Reference](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/_setjmp.3.html). `sigjmp_buf` is related to functions such as `sigsetjmp()/siglongjmp()`, which save and restore the signal mask.
```
#ifdef J9UNIX
typedef sigjmp_buf* pre_block_t;
#else
typedef void* pre_block_t;
#endif
```
20) `vmargs.c::addJavaLibraryPath`: Unused variable `envVarSize`. Remove dead code.
```
#if defined(J9UNIX) || defined(J9ZOS390)
	IDATA envVarSize = 0;
#endif
```
21) `vmargs.c::addJavaLibraryPath`: Currently, disabled. The below code should be enabled on OSX. `/usr/lib64` doesn't exist on OSX. The code to append `/usr/lib64` should be disabled on OSX. Only the code to append `/usr/lib` should be enabled on OSX.
```
#ifdef J9UNIX
#if defined(J9VM_ENV_DATA64)
	/* JAZZ103 117105: 64-bit JDKs on Linux and AIX should add /usr/lib64 to java.library.path ahead of /usr/lib. */
#define USRLIB64 ":/usr/lib64"
	substringBuffer[substringIndex] = USRLIB64;
	substringIndex += 1;
	substringLength += (sizeof(USRLIB64) - 1) ;
#undef USRLIB64
#endif /* defined(J9VM_ENV_DATA64) */

	substringBuffer[substringIndex] = ":/usr/lib";
	substringIndex += 1;
	substringLength += strlen(":/usr/lib");
#endif
```

### Summary
- Current locations where code is shared between J9UNIX and OSX: 1, 2, 4, 5, 7, 8, 9, 14, 16, and 17. [10 locations]
- Locations where code differs between J9UNIX and OSX: 11 and 13. [2 locations]
- Locations where code should be shared between J9UNIX and OSX; these locations are currently disabled on OSX: 3, 10, 12, 15, 18, 19 and 21. [7 locations]
- Unrelated to J9UNIX: 6 (`LD_LIBRARY_PATH` -> `DYLD_LIBRARY_PATH` on OSX) and 20 (remove dead code).

In seventeen locations, J9UNIX and OSX share the same code. In two locations, J9UNIX and OSX code slightly differs. So, J9UNIX macro should be enabled on OSX. The two outliers should be separately handled with comments stating why J9UNIX and OSX code differs.

**Comment by babsingh** [comment]
fyi - @pshipton @pdbain-ibm @gacholio

**Comment by pdbain-ibm** [comment]
+1 on Approach 1.

**Comment by pshipton** [comment]
> Although there are only 34 places where J9UNIX is used, and fewer that don't already use OSX as well. It would be worth looking at the remaining places to see if OSX needs to be added.

This is not an opinion on how we should proceed re changing J9UNIX, but a suggestion for improving Mac support. Clearly we've already missed at least one place that needs to be included for OSX, there may be more.

**Comment by babsingh** [comment]
Updated the issue's description. Evaluated all J9UNIX code locations in the context of OSX. **Conclusion:** In seventeen locations, J9UNIX and OSX share the same code. In two locations, J9UNIX and OSX code slightly differs. So, J9UNIX macro should be enabled on OSX. The two outliers should be separately handled with comments stating why J9UNIX and OSX code differs.

**Comment by pdbain-ibm** [comment]
Could you provide the details of the outliers?

**Comment by babsingh** [comment]
> Could you provide the details of the outliers?

[2 locations] In `jvm.c::JVM_Available` and `jvm.c::JVM_Open`, `stat/fstat` is used on OSX whereas `stat64/fstat64` is used on J9UNIX. But, `stat64/fstat64` is supported on OSX. If we use `stat64/fstat64` on OSX, then there will be no outliers.

Creating a pull request to close this issue.

**Comment by pdbain-ibm** [comment]
Given that `man fstat64` redirects to `fsat`, could we use the non64 versions throughout?

**Comment by babsingh** [comment]
> could we use the non64 versions throughout?

non64 versions use `stat` data structure and 64bit versions use `stat64` data structure. The `stat64` structure is similar to the `stat` structure, **except that it is capable of returning information about files that are larger than 2 gigabytes**. Using non64 versions throughout will lead to change in behavior on platforms such as Linux. On Linux, our implementation of `JVM_*` functions won't be able to handle files > 2GB. So, we should use the non64 versions only where 64bit versions are unsupported.

**Comment by pdbain-ibm** [comment]
How does MacOS handle large files if `fstat64` is deprecated?

**Comment by babsingh** [comment]
> How does MacOS handle large files if fstat64 is deprecated?

MacOS doesn't have a 32-bit variant. So, my guess is that everything defaults to 64-bit.
