### ISSUE TITLE
Modify -Xmx rules for jdk8 to be the same as jdk11

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3475]
The OpenJ9 -Xmx default settings for jdk8 do not match with OpenJDK. This is due to historical reasons dating back before the code was contributed to OpenJ9. We should consider changing it.

https://www.eclipse.org/openj9/docs/openj9_defaults/

The smaller limit for jdk8 has already hit one user, #3467

**Comment by dmitripivkine** [comment]
This might change behaviour for customers never specified -Xmx explicitly (I surprised how many customers unaware about it). For platforms with limited virtual memory support (ex. ZOS) or shared Large Pages there might be a large impact for system capacity.

**Comment by pshipton** [comment]
@dmitripivkine I'm suggesting to make the change for OpenJ9. The rules do not need to change for IBM Java 8 builds.

**Comment by dmitripivkine** [comment]
> @dmitripivkine I'm suggesting to make the change for OpenJ9. The rules do not need to change for IBM Java 8 builds.

Yes, it is ok. Do we have a way to differentiate OpenJ9 from IBM J9 from code?

**Comment by charliegracie** [comment]
I tend to agree with @dmitripivkine. Users who may have already deployed OpenJ9 that they have downloaded from Adopt may have expectations about how the binary works. I would prefer to leave Java 8 without any changes.

As an aside how does IBM build and package OpenJ9? Would it be easy for a downstream consumer of OpenJ9 to change the default behaviour without having to apply hard to maintain patches?

**Comment by pshipton** [comment]
> Do we have a way to differentiate OpenJ9 from IBM J9 from code?

There is a #define OPENJ9_BUILD which is already used in a few places.

> Would it be easy for a downstream consumer of OpenJ9 to change the default behaviour without having to apply hard to maintain patches?

Not for this code atm, but there could be extension points added as we have done in other places already.

**Comment by pshipton** [comment]
> Users who may have already deployed OpenJ9 that they have downloaded from Adopt may have expectations about how the binary works.

I expect most users will expect it to work as OpenJDK does, there are likely few OpenJ9 users at this point.

**Comment by charliegracie** [comment]
Can you explain more about the OPENJ9_BUILD flag?  The expectation is that the OpenJ9 project should use this flag to differentiate code changes from the IBM JVM? The project IS OpenJ9 so this does not make sense to me. I think we should actively remove all uses of this flag immediately. If a down stream consumer wants go modify behaviour this is not the correct mechanism.

**Comment by pshipton** [comment]
Agreed, usage of the flag will be removed asap.

**Comment by DanHeidinga** [comment]
@pshipton @charliegracie @dmitripivkine Can you three continue this discussion and make a proposal for this?  It would also be good to highlight what this change would do our out of the box footprint numbers.

**Comment by dmitripivkine** [comment]
From code maintenance point of view I would appreciate this change. However there are a few problem we should maintain:
 - Should we add and support compatibility mode for non-OpenJ9 Java 8 builds need to keep old behaviour ?
 - Do clear notice for OpenJ9 Java 8 about possible side effects related to change if JVM is not configured properly -Xmx from 512m to 25% RAM size - possibly increased footprint and startup time, possible long GC times etc.
 - Possible significant growth of system core file size on ZOS if -Xmx is not specified explicitly. This is only platform would include all reserved memory pages to the system core (when other platforms include "touched only" pages). As a result customers might face multi GB system core files in case of failure.

**Comment by DanHeidinga** [comment]
@mstoodle had a great suggestion for this:
> Could we offer a "compatibility mode" option (a better named `-XX:+CompatibilityMode` / `-XX:-CompatibilityMode`) that would be + by default in OpenJ9 but [could be disabled for groups wanting the old behaviour]? ...We'd get an easy mitigation for OpenJ9 users negatively affected by the change in behaviour. Just a suggestion.

This sounds like the right approach to me though I'm in favour of something long and explicit like `-XX:[+-]OriginalJDK8HeapSizeCompatibilityMode` for the option name as it's clear what it does and is explicitly for one purpose.

**Comment by pshipton** [comment]
#8498 is merged and a docs PR https://github.com/eclipse/openj9-docs/pull/509 is open, I believe this is completed.

**Comment by non-conformances-research** [comment]
This change fixes issues #6449, #8221, #8223, and #8224. However, it is not working for issue #8222.
