### ISSUE TITLE
All overnight builds failed although they did succeed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3480]
All the overnight builds last night failed
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Build-Test-All/detail/Pipeline-Build-Test-All/262/pipeline

Looking at an individual build, it shows -version output and `Finished: SUCCESS`
https://ci.eclipse.org/openj9/job/Build-JDK11-aix_ppc-64_cmprssptrs/142

There were a couple of build changes merged yesterday, I suspect https://github.com/eclipse/openj9/pull/3427
although https://github.com/eclipse/openj9/pull/3309 was also merged.

**Comment by pshipton** [comment]
@jdekonin @vsebe

**Comment by pshipton** [comment]
On Slack @AdamBrousseau mentioned "DOWNSTREAM_JOB_TIME I think was the missing property exception I saw"

**Comment by vsebe** [comment]
@AdamBrousseau - fyi
`groovy.lang.MissingPropertyException: No such property: DOWNSTREAM_JOB_TIME for class: groovy.lang.Binding`

See pipeline-function.build_with_slack() method `DOWNSTREAM_JOB_TIME = JOB.getDurationString()`
