### ISSUE TITLE
OpenJDK diagnostic tools (jmap, jstack, jinfo etc.) do not work with OpenJ9

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9#350]
OpenJDK's diagnostic tools are present in the AdoptOpenJDK OpenJ9 builds, but they do not work due to differences in the Attach implementation. They fail with ClassCastExceptions like this:

`Exception in thread "main" java.lang.ClassCastException: com.ibm.tools.attach.attacher.OpenJ9VirtualMachine incompatible with sun.tools.attach.HotSpotVirtualMachine
	at sun.tools.jmap.JMap.executeCommandForPid(jdk.jcmd@9-internal/JMap.java:128)
	at sun.tools.jmap.JMap.dump(jdk.jcmd@9-internal/JMap.java:192)
	at sun.tools.jmap.JMap.main(jdk.jcmd@9-internal/JMap.java:110)`

`Exception in thread "main" java.lang.ClassCastException: com.ibm.tools.attach.attacher.OpenJ9VirtualMachine incompatible with sun.tools.attach.HotSpotVirtualMachine
	at sun.tools.jstack.JStack.runThreadDump(jdk.jcmd@9-internal/JStack.java:119)
	at sun.tools.jstack.JStack.main(jdk.jcmd@9-internal/JStack.java:98)`

**Comment by pshipton** [comment]
@paulcheeseman The original AdoptOpenJDK "release" build is quite old and isn't being refreshed because OpenJ9 hasn't done a release yet. These executables have been removed from the OpenJ9 build and are no longer present in the AdoptOpenJDK nightly builds.

Should we keep this Issue open as an enhancement request? Adding support to OpenJ9 for these executables isn't currently in IBM's plans.

**Comment by paulcheeseman** [comment]
Sorry Peter - I downloaded the "latest build" from AdoptOpenJDK and foolishly thought that it would be the latest build :o)

I don't think the OpenJDK tools are needed as long as we plan to get DDR/DTFJ working soon.

**Comment by pshipton** [comment]
We do plan to get DDR/DTFJ working "soon", although I can't yet say yet how many weeks it will take. Since this isn't a request for the OpenJDK diagnostic tools, I'm going to close it.

**Comment by pshipton** [comment]
and btw I expect it would take much longer to add support for the OpenJDK diagnostic tools than to get DDR working. Most of the pieces for DDR support are already in place.
