### ISSUE TITLE
Reduce the number of Recompilation_getExistingMethodInfo messages

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#3504]
The JITaaS server will issue `Recompilation_getExistingMethodInfo` messages in `J9::Recompilation::setupMethodInfo()` which is executed during the constructor of `TR_X86Recompilation` object. Since any compilation that can be followed by a re-compilation has a recompilation object, it may make sense for the client to send the existing method info together with the compilation request and save one message pair. We just need a place to stash the desired method info until is needed.

**Comment by dmitry-ten** [comment]
We are already sending `TR_PersistentMethodInfo` when creating a resolved method mirror.
Since at that point we already have a resolved method for method being compiled, we should be able to just access method info from there.

**Comment by dmitry-ten** [comment]
Then it makes sense to send resolved method info for method being compiled with compilation request, this would save us another message pair.

**Comment by mpirvu** [comment]
Note that for a TR_ResolvedJ9Method representing a method undergoing compilation
there could be two PersistentJittedBodyInfos at the server
(1) One that describes the previous compilation (uses heap memory) and it is cached in the resolvedMethod. This one is NULL for first time compilations (which are the vast majority of compilations).
  We should access this through compilee->getExistingJittedBodyInfo()

(2) Another one that describes current compilation (uses persistent memory)
  We should access this through the recompilation object
  compiler->getRecompilationInfo()->getJittedBodyInfo().  Recompilation_getExistingMethodInfo messages are sent for this one.

**Comment by dmitry-ten** [comment]
I see. Then we could store persistent method info in `TR_MethodToBeCompiled`.
