### ISSUE TITLE
Some IBM Diagnostic tooling missing from OpenJ9 builds

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9#351]
Some of IBM's diagnostic tools (e.g. jdmpview and jextract) are missing from the AdoptOpenJDK OpenJ9 builds.

The HealthCenter agent also seems to be missing:

`$ ./jdk-9+181/bin/java -Xhealthcenter:level=headless -version
JVMJ9TI001E Agent library healthcenter could not be opened (/xxxx/xxxx/openj9/jdk-9+181/lib/libhealthcenter.so: cannot open shared object file: No such file or directory)
JVMJ9VM015W Initialization error for library j9jvmti29(-3): JVMJ9VM009E J9VMDllMain failed`

**Comment by pshipton** [comment]
@paulcheeseman you need to look at the nightly build from AdoptOpenJDK. The original "release" build is quite old and isn't being refreshed because OpenJ9 hasn't done a release yet. The nightly builds contain jdmpview, however note that jdmpview (or MAT or anything depending on DDR) isn't going to work properly right now because OpenJ9 doesn't support DDR yet.

**Comment by pshipton** [comment]
As for jextract, @adamfarley are you able to add this executable?

**Comment by pshipton** [comment]
For the HealthCenter agent, this needs to be provided to AdoptOpenJDK and included into the build. I don't believe an OpenJ9 issue is appropriate for this because I don't expect the HealthCenter agent will be contributed to the OpenJ9 project. You might check with Toby on this.

**Comment by adamfarley** [comment]
@pshipton - Right now my focus needs to stay on the 18.3 extensions work. I advise raising a new Extensions issue, and it can be picked up by the next community developer with time (you, me, whoever).

I recommend referencing https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/22 in the issue you raise so people can see how it was done before.

**Comment by DanHeidinga** [comment]
@pshipton The extensions repo is for changes we'd like to see contributed back to OpenJDK.  I would be surprised if the HC agent fit that characterization.  Would it be better hosted here?

**Comment by pshipton** [comment]
I don't think anyone is suggesting contributing the HC agent to the extensions. Either to OpenJ9 or as a separate project.

**Comment by pshipton** [comment]
Created ibmruntimes/openj9-openjdk-jdk9#68

**Comment by pshipton** [comment]
This Issue is partially fixed. It is fixed for Java 9 (ibmruntimes/openj9-openjdk-jdk9#68), but pending for Java 8 (ibmruntimes/openj9-openjdk-jdk8#8). Also note #775

**Comment by pshipton** [comment]
As this is fixed for Java 8 now I'm going to close. The health center agent isn't included, but since this isn't open source, adding it isn't an OpenJ9 issue.
