### ISSUE TITLE
Native test shrtest failed on all platforms with jdk11

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#3516]
Sharedclass testGetAllCacheStatistics,  testCorruptCache failed on all platforms with jdk11.

13:29:14 testGetAllCacheStatistics begin
13:29:14 JVMSHRC808I Compressed references shared cache "abc" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:29:14 JVMSHRC808I Compressed references shared cache "def" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:29:14 JVMSHRC808I Compressed references shared cache "ghi" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:29:14 testGetAllCacheStatistics: failed: number of elements expected = 5, result =2
13:29:14 JVMSHRC808I Compressed references shared cache "abc" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:29:14 JVMSHRC808I Compressed references shared cache "def" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:29:14 JVMSHRC808I Compressed references shared cache "ghi" is destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:29:14 testGetAllCacheStatistics: FAIL

13:29:22 Corrupt cache with corruption type: 14(CACHE_SIZE_INVALID_TYPE)
13:29:22 openTestCache: Opening test cache
13:29:22 openTestCache: Done opening test cache
13:29:22 	ERROR: CorruptCacheTest.cpp(890) truncateCache Failed to open cache file
13:29:22 openCorruptCache: Opening test cache
13:29:22 	ERROR: CorruptCacheTest.cpp(473) openCorruptCache CacheMap.startup() passed when a fail was expected
13:29:22 openCorruptCache: Done opening test cache
13:29:22 	ERROR: CorruptCacheTest.cpp(740) verifyCorruptionContext incorrect corruption context. 
13:29:22 	Expected code: -11	 found: 0
13:29:22 testCorruptCache: corruption context verification failed
13:29:22 
13:29:22 Result of test CorruptCacheTest: FAILED

**Comment by hangshao0** [comment]
Do you have a link of the failures ?

**Comment by hangshao0** [comment]
The failures are caused by the wrong cache directory. The default cache directory has been changed to user's home from Java 11. The test needs to be updated.
