### ISSUE TITLE
Update tests to use OPENJ9_JAVA_OPTIONS

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3525]
Due to [Deprecate IBM_JAVA_OPTIONS and replace with OPENJ9_JAVA_OPTIONS](https://github.com/eclipse/openj9-docs/issues/131), tests need to be updated.

- https://github.com/eclipse/openj9/blob/master/test/functional/Java8andUp/src/org/openj9/test/vmArguments/VmArgumentTests.java needs to be updated.
- https://github.com/eclipse/openj9/blob/master/test/TestConfig/resources/modes.xml will not break, but also should be updated.

**Comment by pdbain-ibm** [comment]
@llxia While I have the modes file open, I will also delete some obsolete or unused modes.

**Comment by pdbain-ibm** [comment]
Please not that VmArgumentsTests was already updated by 
https://github.com/eclipse/openj9/pull/3495/files#diff-7f1510116e93ef7b021414c1fa329409.
