### ISSUE TITLE
Allow more than 8 compilation threads at the JITaaS server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#3526]
Currently the JIT only allows a maximum of 8 compilation threads mainly because `TR_PersistentClassInfo::_shouldNotBeNewlyExtended` keeps a bit mask of compilation thread IDs and the size of this mask is 8 bits (to conserve footprint). PR #3524 eliminated that restriction, but more changes are needed.

The following #defines need to be replaced with `uint32` variables that can be changed, such that the JITaaS server can use a different value after parsing the command line options.
```
#define MAX_USABLE_COMP_THREADS 7
#define MAX_DIAGNOSTIC_COMP_THREADS 1
#define MAX_TOTAL_COMP_THREADS (MAX_USABLE_COMP_THREADS + MAX_DIAGNOSTIC_COMP_THREADS)
```
There are a few static arrays whose sizes depend on `MAX_USABLE_COMP_THREADS` and `MAX_TOTAL_COMP_THREADS `. We may have to use some dynamic allocations for them. Examples:
In HookedByTheJIT.cpp: 
`int32_t cpuUtilizationValues[MAX_USABLE_COMP_THREADS];`
In CompilationRuntime.hpp:
`TR::CompilationInfoPerThread *_arrayOfCompilationInfoPerThread[MAX_TOTAL_COMP_THREADS];`
In CompilationThread.cpp:
```
int32_t compThreadActivationThresholds[MAX_TOTAL_COMP_THREADS+1] =       {-1, 100, 200, 300, 400, 500, 600, 700, 800};
int32_t compThreadSuspensionThresholds[MAX_TOTAL_COMP_THREADS+1] = {-1,  -1,  10,  110, 210, 310, 410, 510, 610};
int32_t compThreadActivationThresholdsonStarvation[MAX_TOTAL_COMP_THREADS + 1] = {-1, 800, 1600, 3200, 6400, 12800, 19200, 25600, 32000};
```
Also, we need to change the size of arrays that store compilation thread names. Currently the assumption is that the ID of a thread fits on one digit. We should allow two digits if we impose a cap of 100 threads at the server:
```
   static const char activeDiagnosticThreadName[]    = "JIT Diagnostic Compilation Thread-%d";
   static const char suspendedDiagnosticThreadName[] = "JIT Diagnostic Compilation Thread-%d Suspended";
   static const char activeThreadName[]              = "JIT Compilation Thread-%d";
   static const char suspendedThreadName[]           = "JIT Compilation Thread-%d Suspended";
```
One possibility is to use `%2d` instead of `%d` above. An alternative is to remove the `-1` from:
```
      activeThreadNameLength      = sizeof(activeDiagnosticThreadName) - 1;
      suspendedThreadNameLength   = sizeof(suspendedDiagnosticThreadName) - 1;
      activeThreadNameLength      = sizeof(activeThreadName) - 1;
      suspendedThreadNameLength   = sizeof(suspendedThreadName) - 1;
```

**Comment by mpirvu** [comment]
@a7ehuo as discussed, please work on this issue instead of the tracing one. Thanks

**Comment by a7ehuo** [comment]
@mpirvu Thank Marius. I'll start with this one this week.

**Comment by mpirvu** [comment]
Code notes:
A lot of the initialization happens in `onLoadInternal()`. 
1) The JIT persistent memory is created
` initializePersistentMemory(jitConfig);`
2) The compInfo singleton is created: 
`if (!TR::CompilationInfo::createCompilationInfo(jitConfig))`
3) Options are parsed and the global option objects are created:
`char *endJITOptions = TR::Options::processOptionsJIT(xjitCommandLine, jitConfig, feWithoutThread);`

4) The compilation threads are created
```
      for (; highestThreadID < TR::Options::_numUsableCompilationThreads; highestThreadID++)
         {
         if (compInfo->startCompilationThread(-1, highestThreadID, /* isDiagnosticThread */ false) != 0)
```

`compThreadActivationThresholds` array is only accessed from `TR::CompilationInfo::shouldActivateNewCompThread()` so the dynamically allocated array should stay inside `TR::CompilationInfo`
Same idea for `compThreadSuspensionThresholds` except that in this case `CompilationInfoPerThread::processEntry` also needs access to it, so you may need an accessor like `int32_t TR::CompilationInfo::getCompThreadSuspensionThreshold(int32_t queueWeight)`

The dynamic arrays could be allocated using JIT persistent memory and populated just before the compilation threads are created because nobody else can use them. They could be declared static.
