### ISSUE TITLE
Tests leave extra processes running

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#3548]
Symptoms include causing the cleanup job to fail, see https://ci.eclipse.org/openj9/job/Cleanup-Nodes/531/console.

This isn't limited to Windows hosts; I've seen abandoned processes on AIX as well.

**Comment by smlambert** [comment]
There were several issues, all of which have been addressed via: 
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2059
https://github.com/AdoptOpenJDK/openjdk-tests/pull/2121
https://github.com/AdoptOpenJDK/stf/pull/89
https://github.com/AdoptOpenJDK/stf/pull/94

Test jobs now also report on any processes that were left and not killed, so we may see and catch any other problems (especially helpful in the case of new tests being added and not cleaning up after themselves).
