### ISSUE TITLE
zlinux/plinux is not statically linking libstdc++.so

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3558]
Unlike the xlinux builds, zlinux/plinux builds are not statically linking libstdc++.so

I checked a zlinux jdk11 build (the 0.11.0 release) downloaded from Adopt
This build uses gcc 7.3.
Also looked at a jdk8 build using gcc 4.8.5 and it is the same.

`ldd libj9jit29.so` shows
`libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x000003fffc8e8000)`

`nm libj9jit29.so | grep GLIBCXX` shows
```
                 U _ZNSt8__detail15_List_node_base7_M_hookEPS0_@@GLIBCXX_3.4.15
                 U _ZNSt8__detail15_List_node_base9_M_unhookEv@@GLIBCXX_3.4.15
                 U _ZNSt9bad_allocD1Ev@@GLIBCXX_3.4
                 U _ZNSt9bad_allocD2Ev@@GLIBCXX_3.4
                 U _ZNSt9exceptionD2Ev@@GLIBCXX_3.4
                 U _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base@@GLIBCXX_3.4
                 U _ZSt18_Rb_tree_incrementPKSt18_Rb_tree_node_base@@GLIBCXX_3.4
                 U _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base@@GLIBCXX_3.4
                 U _ZSt20__throw_length_errorPKc@@GLIBCXX_3.4
                 U _ZSt24__throw_out_of_range_fmtPKcz@@GLIBCXX_3.4.20
                 U _ZSt28_Rb_tree_rebalance_for_erasePSt18_Rb_tree_node_baseRS_@@GLIBCXX_3.4
                 U _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_@@GLIBCXX_3.4
                 U _ZSt7nothrow@@GLIBCXX_3.4
                 U _ZTVSt9bad_alloc@@GLIBCXX_3.4
```

**Comment by pshipton** [comment]
Note the user encountered problem #3580 on plinux.

**Comment by 0dvictor** [comment]
I've investigated the issue on plinux. Removing `stdc++` from following line resolves the issue.

https://github.com/eclipse/openj9/blob/6a0d9ce716377ddc2e084950180868ba92210f5e/runtime/compiler/build/toolcfg/gnu/common.mk#L435

We explicitly links to `libstdc++` on both P and Z, but not on X. @fjeremic @gita-omr @ymanton do you know why we have to explicitly link to `libstdc++` on Z and P?

Quote from GCC's documentation: [1]
> When the g++ program is used to link a C++ program, it normally automatically links against libstdc++. If libstdc++ is available as a shared library, and the -static option is not used, then this links against the shared version of libstdc++. 

While we are using `g++` to link, explicitly linking to `libstdc++` is redundant. In addition, by default, `g++/gcc` prefers shared library unless `-static` is specified; therefore, JIT ends up dynamically linking to the shared version of `libstdc++`.

[1] https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#Link-Options

**Comment by gita-omr** [comment]
> We explicitly links to libstdc++ on both P and Z, but not on X. @fjeremic @gita-omr @ymanton do you know why we have to explicitly link to libstdc++ on Z and P?

I don't know why we do it specifically for P and Z. Maybe @ymanton or @zl-wang know...

@AlenBadel, just fyi.

**Comment by ymanton** [comment]
The explicit `-lstdc++` for the GCC makefile for Power has been there nearly forever  but I don't know why it was originally added. However, the GCC makefiles were hardly ever used in the past; the Power Linux builds used XLC. At the time we went to static linking of the C++ library the change was done for the XLC builds, not the GCC builds that were unused and unsupported.

**Comment by gita-omr** [comment]
That’s a good explanation. Thanks.
