### ISSUE TITLE
cmdLineTester_dumpromclasstests_0 failing on AIX

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3562]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-aix_ppc-64_cmprssptrs/65
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/124

```
Testing: Run !dumpallromclasslinear 2 - with BCI agent core
Test start time: 2018/11/06 01:26:12 Central Standard Time
Running command: /home/u0020236/workspace/Test-extended.functional-JDK11-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/../bin/jdmpview -core j9core.dmp
Time spent starting: 14 milliseconds
Time spent executing: 959 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Could not load dump file and/or could not load XML file: Could not create a valid ImageFactory
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: java/lang/Object]
>> Required condition was not found: [Output match: (.)*intermediateClassData(.)*0x[0-9a-fA-F]*]
>> Failure condition was not found: [Output match: DDRInteractiveCommandException]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: could not read]
>> Failure condition was not found: [Output match: dump event]
```

**Comment by pshipton** [comment]
@jdekonin are the machines out of space?

or perhaps related to #3550
@sophia-guo @llxia

**Comment by jdekonin** [comment]
The 4 AIX machines do not appear to be out of space at the moment.

**Comment by sophia-guo** [comment]
Test was re-enabled by #3550, which had been disabled ever since open source.

**Comment by pshipton** [comment]
Please disable it again until it can pass reliably.

**Comment by sophia-guo** [comment]
will do

**Comment by llxia** [comment]
Can you also disable this test on osx?
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/5/tapResults/

```
Testing: Run !dumpallromclasslinear 2 - with BCI agent core
Test start time: 2018/11/05 18:12:03 Eastern Standard Time
Running command: /Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/build/macosx-x86_64-normal-server-release/images/jdk/bin/../bin/jdmpview -core j9core.dmp
Time spent starting: 5 milliseconds
Time spent executing: 2378 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Could not load dump file and/or could not load XML file: Image file '/Users/jenkins/workspace/PullRequest-Extended-JDK11-osx_x86-64_cmprssptrs-OpenJ9/openj9/test/TestConfig/test_output_15414595104103/cmdLineTester_dumpromclasstests_0/j9core.dmp' not found.
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: java/lang/Object]
>> Required condition was not found: [Output match: (.)*intermediateClassData(.)*0x[0-9a-fA-F]*]
>> Failure condition was not found: [Output match: DDRInteractiveCommandException]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: could not read]
>> Failure condition was not found: [Output match: dump event]
```

**Comment by pshipton** [comment]
Removing prio:high since the test is now excluded and so not longer failing in the builds

**Comment by babsingh** [comment]
**Update:**
- [**cmdLineTester_dumpromclasstests_0**] `Run !dumpallromclasslinear` depends on `DDRInteractive`. It still fails since DDR support is currently missing on OSX.

**Comment by babsingh** [comment]
@mikezhang1234567890 Since DDR support has been enabled on OSX, can you verify if `cmdLineTester_dumpromclasstests_0` passes, and close this issue?

**Comment by babsingh** [comment]
@mikezhang1234567890 or @llxia or @sophia-guo Since DDR support has been enabled on OSX via https://github.com/eclipse/openj9/issues/3483, can you verify if `cmdLineTester_dumpromclasstests_0` passes, re-enable the test, and close this issue?

**Comment by pshipton** [comment]
AIX https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/247/tapTestReport/
OSX https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/116/tapTestReport/

lgtm

**Comment by pshipton** [comment]
Also for 11
AIX https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-osx_x86-64_cmprssptrs/116/tapTestReport/
OSX https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-osx_x86-64_cmprssptrs/127/tapTestReport/
