### ISSUE TITLE
ASSERTION FAILED ** at classsupport.c:1244 running Build-JDK11-win_x86-64_cmprssptrs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3565]
https://ci.eclipse.org/openj9/job/Build-JDK11-win_x86-64_cmprssptrs/159
```
00:54:12 JVMJ9VM019E Unrecoverable error: Unable to find and initialize required class java/lang/Byte
00:54:12 JVMJ9VM023I This may indicate that JAVA_HOME is incorrect, or that class libraries are not installed
00:54:12 05:55:10.107 0x19a00    j9vm.546    *   ** ASSERTION FAILED ** at classsupport.c:1244: ((0 ))
```

**Comment by pshipton** [comment]
1244:	Assert_VM_internalFindKnownClassFailure();

**Comment by gacholio** [comment]
Likely filesystem flakiness. None of the changes in the PR would have caused this. Java ran successfully before the error.

**Comment by pshipton** [comment]
Agreed, but I wanted to record it in case it occurs again.

**Comment by pshipton** [comment]
Occurred again, looking like a real issue
https://ci.eclipse.org/openj9/job/Build-JDK11-win_x86-64_cmprssptrs/160

**Comment by pshipton** [comment]
Blocking omr acceptance builds as well

**Comment by pshipton** [comment]
#3542 is the suspect change

**Comment by DanHeidinga** [comment]
I've opened PR #3609 as a way to test whether this change was the culprit as I'm running into issues building windows locally.
