### ISSUE TITLE
Move randomGen architecture disabling on Z into OMR

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3576]
The randomGen code in J9CodeGenerator [1] needs to be moved out into the OMRCodeGenerator constructor. The reason for this is that when constructing the J9CodeGenerator object the OMR constructor will be invoked first and when that happens we will have already made a bunch of decisions based on the architecture level we currently support.

When we finally get to the J9CodeGenerator constructor we execute the randomGen code and potentially disable an architecture. This is bad because we'll potentially be generating instructions for the wrong processor level. The following problems are the ones I encoutnered as an example:

```
        Processor detected does not support instruction LOCR

compiling java/nio/charset/CharsetEncoder.replaceWith([B)Ljava/nio/charset/CharsetEncoder; at level: warm
#0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x7bf76fc6 [(nil)]
#1: function TR_Debug::printStackBacktrace()+0x7bf89d3c [(nil)]
#2: /sandbox1/fjeremic/defects/000000/jre/lib/s390/default/libj9jit29.so(+0xb1cf1e) [0x7bbedf1e]
#3: function TR::assertion(char const*, int, char const*, char const*, ...)+0x7bbee048 [(nil)]
#4: function OMR::Z::Instruction::Instruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*)+0x7c011ab0 [(nil)]
#5: function J9::Instruction::Instruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*)+0x7b69db28 [(nil)]
#6: function J9::Z::Instruction::Instruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*)+0x7b8bf54c [(nil)]
#7: function TR::Instruction::Instruction(OMR::InstOpCode::Mnemonic, TR::Node*, TR::CodeGenerator*)+0x7b8bf5b0 [(nil)]
```

```
        cannot evaluate imin on z10 or below
        
compiling java/nio/charset/CharsetEncoder.replaceWith([B)Ljava/nio/charset/CharsetEncoder; at level: warm
#0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x7be28fc6 [(nil)]
#1: function TR_Debug::printStackBacktrace()+0x7be3bd3c [(nil)]
#2: /sandbox1/fjeremic/defects/000000/jre/lib/s390/default/libj9jit29.so(+0xb1cf1e) [0x7ba9ff1e]
#3: function TR::fatal_assertion(char const*, int, char const*, char const*, ...)+0x7baa00c0 [(nil)]
#4: /sandbox1/fjeremic/defects/000000/jre/lib/s390/default/libj9jit29.so(+0xf04a3a) [0x7be87a3a]
#5: function OMR::Z::TreeEvaluator::minEvaluator(TR::Node*, TR::CodeGenerator*)+0x7be880b0 [(nil)]
#6: function OMR::CodeGenerator::evaluate(TR::Node*)+0x7b9ba2b8 [(nil)]
```

[1] https://github.com/eclipse/openj9/blob/defe5656903bac8fa2ef139254b31f671944f04a/runtime/compiler/z/codegen/J9CodeGenerator.cpp#L65-L97

**Comment by pshipton** [comment]
@fjeremic if this is not going to be completed by Jan 14 can it be moved to the next release?

**Comment by fjeremic** [comment]
> @fjeremic if this is not going to be completed by Jan 14 can it be moved to the next release?

We can move to the next release, this is not mission critical at all.

**Comment by pshipton** [comment]
Moved to 0.14 release.

**Comment by fjeremic** [comment]
@pshipton actually we're just waiting on a committer to pick up #4730 and merge it for this issue to be closed. Do you want to be that committer?

**Comment by pshipton** [comment]
Sure
