### ISSUE TITLE
Enable minimum ALS asserts as fatal and add `-Xjit:disable<arch>` testing

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3577]
Since the introduction of the `minimumALS` property for each instruction we've introduced a nice assert in OMR which asserts [1] that the instruction we're about to generated is supported on the architecture we're running on. This prevents the common bugs of forgetting to guard a particular piece of evaluator with an architecture guard. These will result as SIGILL failures in production.

Unfortunately one shortcoming of the current implementation is that the assert is non-fatal, meaning it will not fire at the moment unless we're in a debug compilation, which is pretty much never. Another shortcoming is that there are instructions which have a `TR_UnknownArchitecture` ALS. These are typically pseudo-instructions. They will actually trigger those asserts always. We need to fix that as well.

What I propose here is the following:

1. Enable the asserts to be fatal
2. Take a look at which instructions have a `TR_UnknownArchitecture` ALS and see if we can modify them to use `TR_LatestArchitecture` instead. If we can eliminate `TR_UnknownArchitecture` from OMRInstOpCodeProperties then everything will work.
3. Add OpenJ9 tests on some simple workload, possibly even `java -version` with variants of every single `-Xjit:disable<arch>` that we support so we catch all these bugs right at the PR level before they're checked in

[1] https://github.com/eclipse/omr/blob/c7354fbf6a328349e8f55f559d994c381e297b4d/compiler/z/codegen/OMRInstruction.cpp#L83-L101

**Comment by dhong44** [comment]
Number 2. seems incorrect to me. The `supportsArch` function [1] returns true if the processor architecture is greater than or equal to the architecture we are checking support for, in this case the `minimumALS` of an instruction.

If we use `TR_UnknownArchitecture` as the `minimumALS` then we will always support since `TR_UnknownArchitecture` is mapped to 0 and every architecture will be greater than this. If instead we change it to `TR_LatestArchitecture` which is mapped to `TR_zNext` then the architecture will never be supported and we assert will be thrown. I think the minimumALS of pseudo instructions should remain as `TR_UnknownArchitecture`.

[1] https://github.com/eclipse/omr/blob/c7354fbf6a328349e8f55f559d994c381e297b4d/compiler/z/codegen/OMRInstOpCode.hpp#L49-L72

**Comment by fjeremic** [comment]
> Number 2. seems incorrect to me. The `supportsArch` function [1] returns true if the processor architecture is greater than or equal to the architecture we are checking support for, in this case the `minimumALS` of an instruction.

Ahhh! You're totally right. I must have confused myself with something. I do recally hitting the OMRInstruction assert though on some of these pseudo-instructions. I think it may have been `DCB` when I tried using debug counters. Perhaps they map to instructions we may not support on all architectures?

I'm not sure. However the goal is to enable the fatal asserts and introduce testing without us asserting all over the place for false positives. Thanks for tackling this @dhong44!

**Comment by pshipton** [comment]
@fjeremic if this is not going to be completed by Jan 14 can it be moved to the next release?

**Comment by fjeremic** [comment]
> @fjeremic if this is not going to be completed by Jan 14 can it be moved to the next release?

This is adding extra paranoid testing and does not affect functionality so it's safe to move to the next release.

**Comment by SueChaplain** [comment]
Do you want the `-Xjit:disable<arch>` option documented in the user docs, or are you keeping this out just for testing please?

**Comment by fjeremic** [comment]
> Do you want the `-Xjit:disable<arch>` option documented in the user docs, or are you keeping this out just for testing please?

This is just for testing. We would prefer to leave these undocumented as we use them for debugging mostly.

**Comment by gita-omr** [comment]
@fjeremic this is all Z specific work, right? Could you mark as comp:jit:z then? Thanks.

**Comment by fjeremic** [comment]
> @fjeremic this is all Z specific work, right? Could you mark as comp:jit:z then? Thanks.

Yes, feel free to add the tags yourself if it is obvious in the PR that i's x/z/p specific. Thanks!

**Comment by fjeremic** [comment]
@dhong44 will we get to this by the 0.13.0 milestone or should we push it to 0.14.0?

**Comment by vij-singh** [comment]
@dhong44 how are we looking for the 0.13.0 milestone?

**Comment by dhong44** [comment]
I tried adding these asserts and have a passing build but I've been having some failures when using the `-Xjit:disable<arch>` options. It seems these are issues with the options themselves and not that we are generating instructions unsupported by the architecture level. 

With `-Xjit:disable<arch>` testing on `java -version` I now have passing tests except 31 bit zOS where no output is printed to stdout. I am trying to look into this but even after this is resolved we should still run a full suite of tests with `-Xjit:disable<arch>` for each architecture level. `java -version` tests alone wouldn't be sufficient. Although I could possibly fix the issue of no stdout by 0.13.0 we would likely have other failures running more extensive testing. I think to properly test minimum ALS levels and the `-Xjit:disable<arch>` option, we should push this back to 0.14.0

**Comment by fjeremic** [comment]
Given the current state of this issue, the progress, and the fact that this is a non-functional improvement to the ecosystem I'm ok to move this to 0.14.0.
