### ISSUE TITLE
libj9jit29.so issue on RHEL 7.5 ppc64le

### ISSUE THREAD

**Issue by takiguc** [eclipse/openj9#3580]
Hello.
I started AdoptOpenJDK+OpenJ9 builds on Linux RHEL 7.5 ppc64le environment, following message was displayed on screen:
On JDK-11+28, Java was not started
$ ~/jdk-11+28/bin/java -jar SwingSet2.jar
JVMJ9VM011W Unable to load j9jit29: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /home/jdktest/jdk-11+28/lib/compressedrefs/libj9jit29.so)
JVMJ9VM013W Initialization error in function j9dyn29(7): failed to initialize JImage interface
JVMJ9VM013W Initialization error in function VMInitStages(7): cannot initialize modules path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

On JDK-11.0.1+13,
$ ~/jdk-11.0.1+13/bin/java -jar SwingSet2.jar
JVMJ9VM011W Unable to load j9jit29: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jdktest/jdk-11.0.1+13/lib/compressedrefs/libj9jit29.so)

When I tried to turn off JIT by using -Xint, java was started but it seemed Java was frozen by thread deadlock.
(Both build worked fine on Ubuntu 18.04 ppc64le.) 

Load issue may be related by #3558.

**Comment by pshipton** [comment]
It seems the jdk-11+28 build from AdoptOpenJDK was built on Ubuntu 16, while the later build was created on RHEL 7. I believe compilation with gcc 7.3 requires the newer GLIBCXX version. Agreed that #3588 is a factor, I'll update it to include plinux.

**Comment by pshipton** [comment]
> Will there be any negative impact on people who build JNI libraries with the GCC 4.8 which is standard on RHEL7?

@sxa555 not sure what you are asking about. **What** may cause a negative impact, static linking?

**Comment by DanHeidinga** [comment]
A PR was merged to statically link glibc & libstdc++ yesterday.  This should be fixed in recent nightly builds.

@takiguc  Are you able to retest with a nightly build from AdoptOpenJDK?

**Comment by cwesMills** [comment]
I got the following error with a nightly build on cent7.5 ppc64le

[root@880ae43750f9 adoptojdk-java-10]# ./bin/java -version
JVMJ9VM011W Unable to load j9jit29: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/jvm/adoptojdk-java-10/lib/compressedrefs/libj9jit29.so)
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201811081909)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-22e0009fd, JRE 11 Linux ppc64le-64-Bit Compressed References 20181108_107 (JIT disabled, AOT disabled)
OpenJ9   - 22e0009fd
OMR      - c7354fbf
JCL      - 358ac0fdee based on jdk-11.0.1+13)

**Comment by pshipton** [comment]
@cwesMills please try a newer nightly build, this problem should be fixed now.
https://github.com/eclipse/openj9/pull/3671

**Comment by pshipton** [comment]
@sxa555 would likely know ^

**Comment by pshipton** [comment]
Closing since the reported issue is fixed.

**Comment by takiguc** [comment]
Thanks.
I ran SwingSet2 testcase on RHEL7.5 ppc64le with following build.
It worked fine
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201811271910)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-d3f9e38ec, JRE 11 Linux ppc64le-64-Bit Compressed References 20181127_35 (JIT enabled, AOT enabled)
OpenJ9   - d3f9e38ec
OMR      - d92f2bdd
JCL      - d42cd0d94f based on jdk-11.0.1+13)
