### ISSUE TITLE
Add build version to native-test-libs

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#3584]
After a test libraries folder (native-test-libs) is unzipped it is impossible to tell which build / shas it belongs to. This gets confusing when making changes to those libraries and downloading them to test manually. Perhaps adding a txt file to native-test-libs with the corresponding `java -version` output would be a good solution.

- [x] openj9-openjdk-jdk8 https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/271
- [x] openj9-openjdk-jdk11 https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/66
- [x] openj9-openjdk-jdk https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/49

**Comment by pshipton** [comment]
@keithc-ca fyi

**Comment by keithc-ca** [comment]
Good idea, Theresa.

In the extensions repos, it should be as simple as adding a new prerequisite in OpenJ9.gmk for `openj9_test_image` that creates the file with that information.

**Comment by pshipton** [comment]
Fixed in all versions, closing.
