### ISSUE TITLE
Small reduction in data sent for method tracing

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#3585]
When the client sends information about a j9class to the JITaaS server it packs the method tracing information into a vector of a pair of boolean values. Because the number of methods may be large for some classes, it may worthwhile to do a better packing by using 2 bits (thus just one byte) per method. Relevant code:
```
JITaaSHelpers::ClassInfoTuple
JITaaSHelpers::packRemoteROMClassInfo(J9Class *clazz, TR_J9VM *fe, TR_Memory *trMemory)
{
...
  for(uint32_t i = 0; i < numMethods; ++i)
      {
      methodTracingInfo.push_back(std::make_tuple(
         fe->isMethodEnterTracingEnabled((TR_OpaqueMethodBlock *) &methodsOfClass[i]),
         fe->isMethodExitTracingEnabled((TR_OpaqueMethodBlock *) &methodsOfClass[i])
         ));
      }
...
}
```

**Comment by dmitry-ten** [comment]
Looking at the VM code, it is identical for both enter and exit tracing.
```
UDATA
jitMethodEnterTracingEnabled(J9VMThread *currentThread, J9Method *method)
{
	J9JavaVM *vm = currentThread->javaVM;

	if (vm->extendedRuntimeFlags & J9_EXTENDED_RUNTIME_METHOD_TRACE_ENABLED) {
		U_8 *pmethodflags = fetchMethodExtendedFlagsPointer(method);
		if (J9_RAS_IS_METHOD_TRACED(*pmethodflags)) {
			return TRUE;
		}
	}
	return FALSE;
}

/**
 * Check if method exit tracing is enabled
 * @param currentThread	The current J9VMThread
 * @param method		The method to be checked if exit tracing is required
 * @return 				non-zero if the method exit tracing is required, otherwise 0 is returned
 */
UDATA
jitMethodExitTracingEnabled(J9VMThread *currentThread, J9Method *method)
{
	J9JavaVM *vm = currentThread->javaVM;

	if (vm->extendedRuntimeFlags & J9_EXTENDED_RUNTIME_METHOD_TRACE_ENABLED) {
		U_8 *pmethodflags = fetchMethodExtendedFlagsPointer(method);
		if (J9_RAS_IS_METHOD_TRACED(*pmethodflags)) {
			return TRUE;
		}
	}
	return FALSE;
}
```
So we can just send one boolean per method, instead of 2.

**Comment by mpirvu** [comment]
I agree with your suggestion only if we make jitMethodExitTracingEnabled call jitMethodEnterTracingEnabled in the mainline. This minimizes (but does not eliminate) the possibility of someone changing the implementation to make them different.

**Comment by mpirvu** [comment]
Even better, we should only have one method called `jitMethodEnterExitTracingEnabled`

**Comment by mpirvu** [comment]
I looked at the code and the VM has 4 implementations that are identical:
```
	static VMINLINE bool
	methodBeingTraced(J9JavaVM *vm, J9Method *method)
	{
		bool rc = false;
		if (J9_ARE_ANY_BITS_SET(vm->extendedRuntimeFlags, J9_EXTENDED_RUNTIME_METHOD_TRACE_ENABLED)) {
			U_8 *pmethodflags = fetchMethodExtendedFlagsPointer(method);
			if (J9_RAS_IS_METHOD_TRACED(*pmethodflags)) {
				rc = true;
			}
		}
		return rc;
	}
    
 
UDATA
jitMethodEnterTracingEnabled(J9VMThread *currentThread, J9Method *method)
{
	J9JavaVM *vm = currentThread->javaVM;

	if (vm->extendedRuntimeFlags & J9_EXTENDED_RUNTIME_METHOD_TRACE_ENABLED) {
		U_8 *pmethodflags = fetchMethodExtendedFlagsPointer(method);
		if (J9_RAS_IS_METHOD_TRACED(*pmethodflags)) {
			return TRUE;
		}
	}
	return FALSE;
}

UDATA
jitMethodExitTracingEnabled(J9VMThread *currentThread, J9Method *method)
{
	J9JavaVM *vm = currentThread->javaVM;

	if (vm->extendedRuntimeFlags & J9_EXTENDED_RUNTIME_METHOD_TRACE_ENABLED) {
		U_8 *pmethodflags = fetchMethodExtendedFlagsPointer(method);
		if (J9_RAS_IS_METHOD_TRACED(*pmethodflags)) {
			return TRUE;
		}
	}
	return FALSE;
}

UDATA
methodBeingTraced(J9JavaVM *vm, J9Method *method)
{
	UDATA rc = FALSE;
	if (vm->extendedRuntimeFlags & J9_EXTENDED_RUNTIME_METHOD_TRACE_ENABLED) {
		U_8 *pmethodflags = fetchMethodExtendedFlagsPointer(method);
		if (J9_RAS_IS_METHOD_TRACED(*pmethodflags)) {
			rc = TRUE;
		}
	}
	return rc;
}
```
What I am proposing to replace our own code
`TR_J9VMBase::isMethodEnterTracingEnabled(TR_OpaqueMethodBlock *method)`
`TR_J9VMBase::isMethodExitTracingEnabled(TR_OpaqueMethodBlock *method)`

with something like:
```
bool
TR_J9VMBase::isMethodTracingEnabled(TR_OpaqueMethodBlock *method)
   {
   return VM_VMHelpers::methodBeingTraced(_jitConfig->javaVM,  (J9Method *)method);
   }
```
Of course, this means that we need to change all places that call `isMethodEnterTracingEnabled` and `isMethodExitTracingEnabled` to call the new method `isMethodTracingEnabled`.

**Comment by mpirvu** [comment]
What I proposed above needs changes even to the OMR level, so we should stage it like this:

Phase 1
1. Create new method
```
bool
TR_J9VMBase::isMethodTracingEnabled(TR_OpaqueMethodBlock *method)
   {
   return VM_VMHelpers::methodBeingTraced(_jitConfig->javaVM,  (J9Method *)method);
   }
```
2. Modify `TR_J9VMBase::isMethodEnterTracingEnabled(TR_OpaqueMethodBlock *method)` and `TR_J9VMBase::isMethodExitTracingEnabled(TR_OpaqueMethodBlock *method)` to call the newly created method
3. Change the two protobuf messages `J9ServerMessageType::VM_isMethodEnterTracingEnabled` and `J9ServerMessageType::VM_isMethodExitTracingEnabled` into one called `J9ServerMessageType::VM_isMethodTracingEnabled`
Create a handler for this type of message
```
      case J9ServerMessageType::VM_isMethodTracingEnabled:
         {
         auto method = std::get<0>(client->getRecvData<TR_OpaqueMethodBlock *>());
         client->write(fe->isMethodTracingEnabled(method));
         }
         break;
```
4. Change the code in `packRemoteROMClassInfo` to create a vector of bools instead of a vector to tuples and adjust the receiving part as well in `cacheRemoteROMClass`

Phase 2.
Create new frontend method `isMethodTracingEnabled` at OMR level (if others agree)

Phase 3.
Replace all uses of `isMethodEnterTracingEnabled` `isMethodExitTracingEnabled` with `isMethodTracingEnabled`

Phase4.
Detele `isMethodEnterTracingEnabled` `isMethodExitTracingEnabled` from frontend

**Comment by mpirvu** [comment]
Maybe this is a change Annabelle  @a7ehuo could implement.

**Comment by a7ehuo** [comment]
@mpirvu Looked at the code, the implementation of `isMethodEnterTracingEnabled()` and `isMethodExitTracingEnabled()` in TR_J9SharedCacheVM are different. If we combine them into one call as isMethodTracingEnabled() in packRemoteROMClassInfo(), what if `TR_J9VM *fe`, fe is pointing to an object of `TR_J9SharedCacheVM` and then we need to differentiate if it's `isMethodEnterTracingEnabled()` and `isMethodExitTracingEnabled()`?

**Comment by ymanton** [comment]
Fixed in master and has been merged back into the jitaas branch, this issue can be closed now.
