### ISSUE TITLE
Deprecate `getAccessStaticsIndirectly`

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3610]
@liqunl has been doing some work in the area of static final fields. She came to as with a question about `getAccessStaticsIndirectly` which is used in the Walker to determine which of the following tree sequences we generate for accessing static fields:

```
direct load <static field address symref>
```

or

```
indirect load <static field symref>
   loadaddr <class statics>
```

The code in question which controls this can be found in [1]. Currently the only setter of this is in the Z codegen on z9 or when compiling AOT [2]. I don't see a particular reason for this restriction however. @vijaysun-omr gave some historical context here:

>I asked Vijay if he recall any reason of the indirect load for static. He said it's not for functional purpose, it's an optimization. We use indirect load such that the `class statics` child can be commoned. He said materialization of a static address was expensive at the time this opt was implemented, but the perf gain wasn't much. If this opt is only used on Z9 and under non-AOT, he has no objection if Z team wants to clean it up.

We should clean this up and simplify the code. This can only be done after #3577 is addressed however.

[1] https://github.com/eclipse/openj9/blob/22e0009fda531be602d728ea128f4ad9b4d289fd/runtime/compiler/ilgen/Walker.cpp#L6199-L6206

[2] https://github.com/eclipse/openj9/blob/22e0009fda531be602d728ea128f4ad9b4d289fd/runtime/compiler/z/codegen/J9CodeGenerator.cpp#L199-L203

**Comment by fjeremic** [comment]
@dhong44 since you are completing #3577 we can tackle this one after.

**Comment by liqunl** [comment]
[`isLoadOfStaticFinalField`](https://github.com/eclipse/omr/blob/master/compiler/il/OMRNode.cpp#L8699) needs to have a check for direct load once this is done.
