### ISSUE TITLE
OSX JDK8 clang: error: unsupported option '-static-libgcc'

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3669]
https://github.com/eclipse/openj9/pull/3594 has broken OSX JDK8 builds. During JIT compilation, the following error is seen:
```
clang: error: unsupported option '-static-libgcc'
```

The above error prevents https://github.com/eclipse/openj9/pull/3646 to be tested.

fyi - @0dvictor @DanHeidinga @nbhuiyan @pshipton

**Comment by nbhuiyan** [comment]
This seems to also break JDK11 OSX builds. When linking, `-static-libgcc` is not ignored by Xcode Clang like `-static-libstdc++` does. I think we should not be relying on the linker to ignore options and instead guard them with proper checks. I will open a PR with a fix.
