### ISSUE TITLE
cmdLineTest: cmdLineTest/shareClassTests cannot find HelloWorld class

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#367]
During the test execution, test cannot find target class file to run, they are excluded in

 test/cmdLineTests/shareClassTests/SCCommandLineOptionTests/exclude.xml
`<exclude id="nameOption2" platform="all"><reason>cannot find HelloWorld class</reason></exclude>`
`<exclude id="nameOption4" platform="all"><reason>cannot find HelloWorld class</reason></exclude>`

java -version:
```
root@1c569afa5e3e:/test/TestConfig# /java/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171011_366953 (JIT enabled, AOT enabled)
OpenJ9   - 26f4ca3
OMR      - 5d625a3
OpenJDK  - a4765a5 based on jdk-9+181)
```

**Comment by TianyuZuo** [comment]
FYI @hangshao0

**Comment by hangshao0** [comment]
This might due to the incorrect setting of class path
