### ISSUE TITLE
cmdLineTest: core files have been generated unexpectedly during gcRegressionTests

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#368]
extra core.* files have been generated during the execution of 

this test was excluded in `test/cmdLineTests/gcRegressionTests/gcRegressionTests_excludes.xml`

`<exclude id="Ensure no core files have been produced by the preceding tests" platform="all" shouldFix="true"><reason>Extra core files were created which caused failure</reason></exclude>`

java -version:
```
root@1c569afa5e3e:/test/TestConfig# /java/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171011_366953 (JIT enabled, AOT enabled)
OpenJ9   - 26f4ca3
OMR      - 5d625a3
OpenJDK  - a4765a5 based on jdk-9+181)
```

**Comment by DanHeidinga** [comment]
@fengxue-IS Can you take a look at this?

**Comment by fengxue-IS** [comment]
Looking into this

**Comment by fengxue-IS** [comment]
Tested personal build with level.sanity on all platform, did not see failure with this test enabled
Opening PR to enable the test

**Comment by pshipton** [comment]
Please try ginding the gcRegressionTests testcase to see if you can get any failures. Since the problem is intermittent, and we don't know the frequency, a single run is probably not enough to expose the problem.

**Comment by fengxue-IS** [comment]
Run grinder 50 iterations for 
`linux_x86-64_cmprssptrs`
`linux_ppc-64_le`
`zos_390-64`
all passed, seems like the problem has been fixed
