### ISSUE TITLE
Test code/infrastruture should use DYLD_LIBRARY_PATH on OSX JDK11

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3686]
The following tests are failing in https://github.com/eclipse/openj9/pull/3603 ... [Sanity - JDK11 - osx_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-osx_x86-64_cmprssptrs-OpenJ9/33/consoleFull): 
```
16:49:38 ---SUMMARY OF FAILED TESTS---
16:49:38 abort  
16:49:38 softwareFloat  
16:49:38 hardwareFloat  
16:49:38 softwareRead  
16:49:38 hardwareRead  
16:49:38 abort thread
16:49:38 softwareFloat thread
16:49:38 hardwareFloat thread
16:49:38 softwareRead thread
16:49:38 hardwareRead thread
```
The reason for the above test failures is `UnsatisfiedLinkError`:
```
16:49:18  [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
16:49:18  [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1678)
16:49:18  [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1648)
16:49:18  [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:559)
16:49:18  [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:70)
```
To fix the above test failures, test infrastructure needs to set `DYLD_LIBRARY_PATH` on MacOSX instead of `LD_LIBRARY_PATH`.

fyi - @llxia @smlambert @gacholio

**Comment by smlambert** [comment]
fyi @renfeiw

**Comment by babsingh** [comment]
Before tests would hang at `Test: abort` stage. To reproduce the above failures locally, you will need the commits in https://github.com/eclipse/openj9/pull/3603.

**Comment by llxia** [comment]
@sophia-guo Could you update the lib path for osx? Could you also check if we can use `JDK_IMPL` instead of `JCL_VERSION ` in if statement. Thanks
https://github.com/eclipse/openj9/blob/80b8e6c420fff2b443b4bc3746c261d37c49a738/test/TestConfig/openj9Settings.mk#L74

**Comment by llxia** [comment]
Talked with Sophia, I will work on this issue

**Comment by babsingh** [comment]
`UnsatisfiedLinkError` failures are specific to OSX JDK11. With OSX JDK8, `gpTest` suite failures are different: [gpTest suite failures on OSX with JDK8](https://github.com/eclipse/openj9/issues/3789).

**Comment by babsingh** [comment]
#3765 is the fix for this issue. Closing this issue since the following exception is no longer seen while running the `gpTest` suite:
```
16:49:18  [ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: gptest (Not found in java.library.path)
16:49:18  [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1678)
16:49:18  [ERR] 	at java.base/java.lang.ClassLoader.loadLibraryWithClassLoader(ClassLoader.java:1648)
16:49:18  [ERR] 	at java.base/java.lang.System.loadLibrary(System.java:559)
16:49:18  [ERR] 	at VMBench.GPTests.GPTest.<clinit>(GPTest.java:70)
```
**make** target: `_cmdLineTest_gpTest_0`.
