### ISSUE TITLE
Add GitHub issue templates for Eclipse CI failures

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#3697]
## Background

As we ramp up our Eclipse CI testing I'm noticing more and more issues being raised such as the one in #3688 where a test failure occurs on some PR testing or a nightly test run and an issue is opened with a link to the test console output and a snapshot of what went wrong.

It is not immediately clear to developers how exactly to tackle these problems. Some common questions I see being asked around various issues, or on Slack:

1. Why is there no core file saved from the job?
2. How can I reproduce this problem?
3. How do I launch a grinder for this particular issue so I can reproduce it?
4. Will the grinder save the test output, and if so where do I download it from?
5. How can I reproduce this test locally?
6. How do I avoid running the entire test suite and only run the problematic test?
7. How do I upload custom SDKs to run against a particular test?

Aside from these questions, and others I may have missed, there is sometimes incomplete information in an issue describing the problem.

## Possible Solution

One possible way to eliminate these types of questions is to create an FAQ on the wiki detailing what should be done when an issue with a _test failure_ label is opened against a failing job on the Eclipse CI. This issue can have a prepopulated GitHub issue template [1] which prepopulates the issue description with links to FAQ answering common questions and asks the issue author to provide certain details about the problem, such as a link to the failing job, possible core files, a snippet of the output saying what the failure was, etc.

An example of this can be found on the [babel](https://github.com/babel/babel) project. If you go to the project and try to open up an issue you will get to the issue template page [2]. After choosing the template the issue will be prepopulated with a whole bunch of information, and the user will be responsible for filling in the blanks so that the developers have the necessary information to be able to solve the problem. The templates are simply markdown documents which you can see in [3].

We can have a template in Eclipse OpenJ9 for Eclipse CI test failures with a bunch of useful information front and center when the issue is opened. If the grinder process changes, or anything related to how we operate changes in the future we can simply change the issue templates and all new issues will have the updated information on how to debug Eclipse CI failures. I think this will save us lots of churn moving forward.

I wanted to tag a bunch of people to hear everyones thoughts and if we think this is a good idea we can open up a PR and start working on an issue template draft for Eclipse CI test failures.

@smlambert @llxia @sophia-guo @pshipton @DanHeidinga thoughts?

[1] https://blog.github.com/2016-02-17-issue-and-pull-request-templates/
[2] https://github.com/babel/babel/issues/new/choose
[3] https://github.com/babel/babel/tree/master/.github/ISSUE_TEMPLATE

**Comment by pshipton** [comment]
Fine with me. I think having a template with the must gather list is a good idea. Also the FAQ, and the link to it, would be very helpful.

Note there is a core attached to the failing job in #3688.

**Comment by pshipton** [comment]
Although, any open FAQ would have to describe the open grinder infrastructure, which is only available to committers.

**Comment by smlambert** [comment]
To answer some of your questions, we can augment the test/README files, particularly the https://github.com/eclipse/openj9/tree/master/test#faq

To immediately answer, 
1) core files for functional and system tests ARE captured (exception, not yet for z/OS platform).  If there cores are created, they are included in the archived test output file, named functional_test_output.tar.gz or system_test_output.tar.gz and attached to the test job in jenkins, recent examples : https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDK8-linux_x86-64/139/artifact/functional_test_output.tar.gz and https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/138/artifact/systemtest_test_output.tar.gz.  Download and unzip those files and find cores/dmp files enclosed.

2) and 3) 
A while back we had the idea that we/testkitgen should generate the following:
- creation of pre-populated template for git issue
- script to setup and reproduce same test locally (env vars, target names, etc), testkitgen already captures failed targets from last run, for convenience, so you can "[make _failed](https://github.com/eclipse/openj9/tree/master/test#9-how-to-rerun-failed-tests)" and we created this wiki to help also: https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally
- xml file to auto-run a Jenkins grinder to reproduce (this would autopopulate the fields in a grinder job from an existing nightly test run.  WE pushed to use the same test script to run nightlies as we do to run Grinders, to allow for this to be possible (eventually PR testing should also use our test Jenkinsfile/script).
This work has not been done yet, its been sitting on a wish list in our test plan, needing to find time to get to it.

4) Grinder also saves test output and core files (see question 1 above)

5) see https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally

6) [failed.mk](https://github.com/eclipse/openj9/tree/master/test#9-how-to-rerun-failed-tests) gets generated with only the targets that failed from last run (so you don't have to rerun all of sanity or extended targets), but also for some categories of test, you can extract the test class out of the test target to run it by itself (it is not AS easy to offer this for certain types of tests)

7) Grinders have 2 parameters of interest for this one: 
<img width="887" alt="screen shot 2018-11-15 at 2 15 20 pm" src="https://user-images.githubusercontent.com/2836948/48575827-f9703980-e8e0-11e8-8d2b-dfe56e27c2cf.png">
SDK_RESOURCE - tell us how to get the SDK you wish to test nightly/release goes and picks up from AdoptOpenJDK, upstream takes from a build job in Jenkins, customized lets you supply a CUSTOMIZED_SDK_URL, (somewhere accessible you have put your own SDK) - more details at https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins
If you wish to upload an SDK from your laptop, there is an UploadFile job that allows people with permissions to run Jenkins jobs to do so (at internal and Adopt Jenkins servers, I can add one at openj9 server too, but as Pete mentions, only committers can run jobs at that server).

**Comment by smlambert** [comment]
On the topic of defect templates, we have this doc to help those who need to raise issues upstream at the openjdk bug database:  https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-OpenJDK-Test-Defects  - It was actually this that got us thinking about having our tools generate as much of this info for us as possible.  Goal is to ease developer workload and friction experienced with tools and processes, (we're just suffering from not having too many extra hands).  

I did not create an open issue, as it would sit open for a long time before we could get to it, and its not a 'beginner issue' per se.

**Comment by llxia** [comment]
Another commonly asked question is - how do I get the SDK that is used in this particular test build?
- Open test build link, click to open upstream build console:
<img width="978" alt="screen shot 2018-11-15 at 2 29 07 pm" src="https://user-images.githubusercontent.com/19273206/48576687-2aea0480-e8e3-11e8-9b1c-f8307b0d2e43.png">

- In upstream build console, find the SDK build:

<img width="704" alt="screen shot 2018-11-15 at 2 29 40 pm" src="https://user-images.githubusercontent.com/19273206/48576758-5c62d000-e8e3-11e8-8f9d-acb5e99e794c.png">

- Open SDK build, SDK should be archived. (In case SDK is not archived, there should be link to artifactory download in job console output.)

<img width="714" alt="screen shot 2018-11-15 at 2 30 10 pm" src="https://user-images.githubusercontent.com/19273206/48576807-7c928f00-e8e3-11e8-8898-d3296a7ab6fa.png">


- Copy the SDK dowload link and paste it in `CUSTOMIZED_SDK_URL` in Grinder. For native tests (functional tests), `native-test-libs.tar.gz` needs to be copied into `CUSTOMIZED_SDK_URL`. 
If artifactory link is used, please also provide `CUSTOMIZED_SDK_URL_CREDENTIAL_ID`

Unfortunately, my answer for this is long. Anyone kowns a quick way?

**Comment by smlambert** [comment]
Shorter explanation?  yes a challenge:

Go to the artifact view of the build that produced it (example: https://ci.eclipse.org/openj9/view/Build/job/Build-JDK10-linux_x86-64/460/artifact/), and copy link addresses of the artifacts found there, enter them space-separated as inputs to the CUSTOMIZED_SDK_URL field in the Grinder.

But yes, I find that I also have to remind folks to avoid using "lastSuccessfulArtifacts" URLs, as those are changing often, and go stale quick.

**Comment by fjeremic** [comment]
This has mostly been handled by #4973.
