### ISSUE TITLE
would you please add an ubuntu ppa for openj9?

### ISSUE THREAD

**Issue by netroby** [eclipse/openj9#37]
would you please add an ubuntu ppa for openj9?

**Comment by mstoodle** [comment]
Great request, thanks for opening this issue.

In fact, this repository does not build OpenJDK with OpenJ9; it is the AdoptOpenJDK organization that takes care of this kind of thing.

Sorry to do the repo-hopping thing, but would you be so kind to open your request at https://github.com/adoptopenjdk/openjdk-build ?
