### ISSUE TITLE
Starting jdk11 extended PR testing starts sanity as well win,xlinux,xlinuxlargeheap

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3722]
I requested "jenkins test extended plinux,win,zlinux,xlinux,xlinuxlargeheap,aix jdk11" and also got sanity testing for xlinux, xlinuxlargeheap,win

https://github.com/eclipse/openj9/pull/3693

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
The trigger regex syntax included both extended and sanity for those 3 jobs.  I have updated them by removing the extended criteria.
