### ISSUE TITLE
A number of compiler sources assume that omr is a subdirectory of openj9

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#3725]
There are a number of places in the compiler sources which have includes of the form `#include "omr/compiler/foo/bar.hpp"` This assumes that omr exists as a sub-directory of openj9. This prevents us from performing out-of-tree builds. (see also eclipse/omr#3189).

Offenders I have found so far:
compiler/runtime/Runtime.hpp
compiler/il/ILProps.hpp
compiler/il/ILOpCodeProperties.hpp
compiler/x/amd64/codegen/TreeEvaluatorTable.hpp

**Comment by fjeremic** [comment]
I think we introduced the `omr/` include prefixes because of https://github.com/eclipse/openj9/pull/1992#issuecomment-392142667 by @mstoodle. The `omr/` include assumes the contents of the `runtime/` directory in OpenJ9 is a sibling to all of OMR, i.e. the directory looks like this:

```
/runtime$ tree -d -L 1
.
├── bcutil
├── bcverify
├── cassume
├── cfdumper
├── clear_vmi
├── cmake
├── codert_vm
├── compiler
├── cuda
...
├── omr // This is the entire OMR repository
```

**Comment by dnakamura** [comment]
Reworking the headers, so that the OMR version is named `OMR<some_header>.hpp` as is done with  many of the other headers appears to work fine.  Id be willing to open those PRs if people are alright with that solution

**Comment by fjeremic** [comment]
> Reworking the headers, so that the OMR version is named `OMR<some_header>.hpp` as is done with many of the other headers appears to work fine. Id be willing to open those PRs if people are alright with that solution

@0xdaryl thoughts?

**Comment by mstoodle** [comment]
Doesn't the OpenJ9 build system already need to know where the omr repository is located? Why can't the directory containing OMR just be a configurable setting and passed in on the IPATH which makes the compiler layering solution a more or less consistent mechanism?

(for the record and to make it clear, I hate the idea to smurf file names with the project name *in the project* even though we still do it in places).

**Comment by mstoodle** [comment]
and, by the way, I think this issue is misnamed :)

**Comment by DanHeidinga** [comment]
@dnakamura What's the next step for this issue?

**Comment by dnakamura** [comment]
just #4928

**Comment by dnakamura** [comment]
Closing as last PR merged
