### ISSUE TITLE
Bits.reserveMemory(long, int) throws NullPointerException

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#373]
When using direct memory in Java, we use a class called "Bits" to ensure we do not exceed the maximum allowed quantity of direct memory.

I understand that we are asked to call Bits.reserveMemory(long,int) before attempting to obtain some direct memory, to avoid problems that may arise from exceeding the maximum.

If we call Bits.reserveMemory(long,int) when we don't have enough memory, one of the things it does is it calls SharedSecrets.getJavaLangRefAccess() to obtain a SharedSecrets variable which is an instance of JavaLangRefAccess.

In OpenJDK on OpenJ9, this returns a null, and any method call on that object throws a NullPointerException.

In OpenJDK on Hotspot, we do still get that object, but another class (java.base/java/lang/ref/Reference) sets it beforehand, so it isn't null.

I think the j9cl classes replace Reference with a version that doesn't set the JavaLangRefAccess object inside SharedSecrets.

I advise changing Reference.java so it sets the JavaLangRefAccess object inside SharedSecrets (like the OpenJDK version of Reference.java that we're replacing).

**Comment by adamfarley** [comment]
Also, here's a test case to reproduce the failure:


    import java.nio.*;
    
    public class DirectMemoryTest{
        public static void main(String[] args) {
            testDirectMemory();
        }
    
        public static void testDirectMemory() {
            try {
                int ITERATIONS = 90;
                int ALLOC_SIZE = 10000000; // 10Mbytes
    
                ByteBuffer[] bbStore = new ByteBuffer[ITERATIONS];
                Runtime r = Runtime.getRuntime();
            
                int i;
                for (i = 0; i < ITERATIONS; i++) {
                    System.out.println("Iteration: " + i + " Total memory is: "
                            + r.totalMemory() + " Initial free memory: "
                            + r.freeMemory());
                    System.out.println("About to allocate.");
                    bbStore[i] = ByteBuffer.allocateDirect(ALLOC_SIZE);
                    // *** dereference to allow GC
                    System.out.println("Allocation complete.");
                    bbStore[i] = null;
                }
                if(i==ITERATIONS) System.out.println("Test Passed.");
            } catch (Exception e) {
                System.out.println("Caught Exception: \n" + e);
                System.out.println("Failed with Exception::"+e);
                throw new Error(e);
            }
        }
    }

**Comment by pshipton** [comment]
The original issue was fixed, SharedSecrets.getJavaLangRefAccess() no longer returns null. The remaining work is to implement waitForReferenceProcessing().
