### ISSUE TITLE
Assert running with -Xgcpolicy:balanced in docker.

### ISSUE THREAD

**Issue by bharathappali** [eclipse/openj9#3767]
I was running a memory consuming program for some of my tests and found out the openj9 asserts when I run inside a docker with cpu restriction in balanced gc policy.

**Java program :**
```
import java.util.ArrayList;
import java.util.List;

public final class JvmKill
{
    public static void main(String[] args)
            throws Exception
    {
        System.out.println("creating OOM...");
        List<Object> arr = new ArrayList<>();
        try {
            while (true) {
                byte[] bytes = new byte[1024 * 1024 * 1024];
                arr.add(bytes);
                System.out.println("list size: " + arr.size());
            }
        }
        catch (Throwable t) {
            System.out.println(t.toString());
        }
    }
}
```
**Crash :**
```  
creating OOM...
10:27:42.307 0x1b6df00    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:3377: ((false && (nodeOfThread <= _extensions->_numaManager.getMaximumNodeNumber())))
10:27:42.307 0x1b62b00    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:3377: ((false && (nodeOfThread <= _extensions->_numaManager.getMaximumNodeNumber())))
10:27:42.307 0x1b66700    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:3377: ((false && (nodeOfThread <= _extensions->_numaManager.getMaximumNodeNumber())))
10:27:42.307 0x1b6a300    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:3377: ((false && (nodeOfThread <= _extensions->_numaManager.getMaximumNodeNumber())))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/21 10:27:42 - please wait.
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/21 10:27:42 - please wait.
JVMDUMP032I JVM requested System dump using '/root/openj9-stuff/core.20181121.102742.34.0001.dmp' in response to an event
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/21 10:27:42 - please wait.
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/11/21 10:27:42 - please wait.
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.56.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 56 was not found. Expected to find core file with name "/root/openj9-stuff/core.56"
JVMDUMP032I JVM requested Java dump using '/root/openj9-stuff/javacore.20181121.102742.34.0005.txt' in response to an event
JVMDUMP012E Error in Java dump: /root/openj9-stuff/javacore.20181121.102742.34.0005.txt
JVMDUMP032I JVM requested Snap dump using '/root/openj9-stuff/Snap.20181121.102742.34.0006.trc' in response to an event
JVMDUMP010I Snap dump written to /root/openj9-stuff/Snap.20181121.102742.34.0006.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```
**NUMA Node config on host**
```
numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3 8 9 10 11
node 0 size: 9204 MB
node 0 free: 4440 MB
node 1 cpus: 4 5 6 7 12 13 14 15
node 1 size: 9216 MB
node 1 free: 4865 MB
node distances:
node   0   1 
  0:  10  21 
  1:  21  10 
```
**Command**
```
docker run --cpuset-cpus=4-7 -v $PWD:/root/openj9-stuff --workdir=/root/openj9-stuff adoptopenjdk/openjdk8-openj9 java -Xgcpolicy:balanced JvmKill
```

**Comment by bharathappali** [comment]
**Exploration**

I have observed that the assert which i hit was due to not passing a condition (`nodeOfThread <= _extensions->_numaManager.getMaximumNodeNumber()`) in `runtime/gc_vlhgc/CopyForwardScheme.cpp`.

I have debugged and checked those values `nodeOfThread` is 1 and `_extensions->_numaManager.getMaximumNodeNumber()` is 2, I haven't understood why it's failing and i was surprised that i worked fine when i was debugging it.

But it failed in some containers even if i'm running my program on a NUMA box which has two nodes. I added print statements in code to print `nodeOfThread` and `_extensions->_numaManager.getMaximumNodeNumber()` which were `1` and `0` respectively.

After going deeper into what `_extensions->_numaManager.getMaximumNodeNumber()` is returning and where it's getting `0`, I found `_extensions->_numaManager.getMaximumNodeNumber()` in `gc/base/NUMAManager.cpp` returns `_maximumNodeNumber` which is set in `MM_NUMAManager::recacheNUMASupport` in `gc/base/NUMAManager.cpp`.
 In failing case `_maximumNodeNumber` is set to 0, which indicates some problem in portlibrary APIs. So I checked the apis and found `omrvmem_numa_get_node_details` is failing.

This particular api is working in my debugging container but not in any other container. `omrvmem_numa_get_node_details` is returning error as the check in it `if(PPG_numa_platform_supports_numa)` is not met. Its due to failure in `initializeNumaGlobals` which sets `PPG_numa_platform_supports_numa`.

In `initializeNumaGlobals` there was a system call failure for `get_mempolicy` which is called in `do_get_mempolicy`. So that was the reason why `_extensions->_numaManager.getMaximumNodeNumber()` is returning `0` even if it has `2` nodes.

*But why its working on my debugging container ?*

[docker docs](https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile) states that default seccomp policy used by docker doesn't allow system calls like `get_mempolicy` and `set_mempolicy` etc. In my debugging container, I have overridden the seccomp setting using `--security-opt` `seccomp=unconfined`, due to which these system calls work fine.

**Note**
In kubernetes its working fine as the default pod security policy sets seccomp to unconfined, [info from doc](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp)

**Comment by bharathappali** [comment]
I have observed that [PortLibrary](https://github.com/eclipse/omr/blob/b21d26c497f0a49736bb39897cc8e012e45df2cf/port/linux/omrvmem.c#L174) and [Thread Library](https://github.com/eclipse/omr/blob/f8fc704032f95cbc0f337eb6be54f2b06e58a773/thread/linux/omrthreadnuma.c#L149) are not having a consistent view of NUMA. In the above case, PortLibrary is turning off the NUMA but Thread Library is showing NUMA characteristics. 

Please correct me if i'm wrong

**Comment by charliegracie** [comment]
@LinHu2016 can you take a look please?

**Comment by LinHu2016** [comment]
@charliegracie sure.

**Comment by LinHu2016** [comment]
As @bharathappali mentioned in previous comment, We do have similar methods, which try to check numa availability, in both PortLibrary and Thread. the code in Thread is used for balanced gc case only, the code in PortLibrary can affect both balance gc case and memory interleave case. I guess because during Thread initialization, the PortLibrary hasn't been initialized, thread can not reuse the result from PortLibrary, so we do have two similar methods in both Libraries.
Why are they slightly different? I am not sure, I will invite Peter Bain to here, he might know some details.
@pdbain-ibm Hi Peter, Could you please verify if we can make those two methods consistent? Thanks

**Comment by pdbain-ibm** [comment]
The port library is controlled by an option `-XX:[-+]InterleaveMemory`.  By default (cf. `jvminit.c:processMemoryInterleaveOptions()` it is disabled. The port library is configured via PortPlatformGlobals; it looks like `omrthread_lib_control()` could be used similarly. There may be an issue of timing: the JVM argument parsing may occur after the thread library has checked the NUMA state.

Ideally, we would parse the NUMA information once and share it with both libraries.

**Comment by bharathappali** [comment]
@LinHu2016 was right. Thread Library is getting initialized first.
```
root@f96cbdeffa6d:~# gdb --args ./openj9-openjdk-jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/bin/java JvmKill      
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./openj9-openjdk-jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/bin/java...(no debugging symbols found)...done.
(gdb) b omrport_init_library
Function "omrport_init_library" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (omrport_init_library) pending.
(gdb) b omrthread_init
Function "omrthread_init" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 2 (omrthread_init) pending.
(gdb) r
Starting program: /root/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/bin/java JvmKill
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6fa4700 (LWP 20037)]
[Switching to Thread 0x7ffff6fa4700 (LWP 20037)]

Thread 2 "java" hit Breakpoint 2, omrthread_init (lib=0x7ffff5ed2b80 <default_library>) at ../omr/thread/common/omrthread.c:240
240		lib->spinlock = 0;
(gdb) 
```
I have added 2 breakpoints one at **omrport_init_library** and other at **omrthread_init**  and found out that Thread Library is getting initialized before Port Library initialization

**Comment by bharathappali** [comment]
@LinHu2016 was right. The thread library is initialized before port library.
```
root@f96cbdeffa6d:~# gdb --args ./openj9-openjdk-jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/bin/java JvmKill
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./openj9-openjdk-jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/bin/java...(no debugging symbols found)...done.
(gdb) b j9port_init_library
Function "j9port_init_library" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (j9port_init_library) pending.
(gdb) b omrthread_init
Function "omrthread_init" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 2 (omrthread_init) pending.
(gdb) r
Starting program: /root/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-slowdebug/images/jdk/bin/java JvmKill
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6fa4700 (LWP 20171)]
[Switching to Thread 0x7ffff6fa4700 (LWP 20171)]

Thread 2 "java" hit Breakpoint 2, omrthread_init (lib=0x7ffff5ed2b80 <default_library>) at ../omr/thread/common/omrthread.c:240
240		lib->spinlock = 0;
(gdb) c
Continuing.

Thread 2 "java" hit Breakpoint 1, j9port_init_library (portLibrary=0x7ffff67a0d80 <j9portLibrary>, version=0x7ffff6fa2cc0, size=3432) at common/j9port.c:247
247		rc = j9port_create_library(portLibrary, version, size);
(gdb) 
```
I have added 2 breakpoints one at **j9port_init_library** and **omrthread_init**, found out that thread library is initialized first.

**Comment by prakaashkpk** [comment]
The issue has occurred for one of our users. @LinHu2016 Any update on the issue ?  

3XHCPUARCH       Architecture   : amd64
3XHNUMCPUS       How Many       : 56

3XEHSTTYPE     05:47:28:594708000 GMT j9mm.107 - * ** ASSERTION FAILED ** at CopyForwardScheme.cpp:3376: ((false && (nodeOfThread <= _extensions->_numaManager.getMaximumNodeNumber())))

**Comment by ashu-mehra** [comment]
@bharathappali I guess you have some kind of a fix for this. Can you please open a PR for that and get it reviewed.

**Comment by bharathappali** [comment]
@ashu-mehra Sure will be raising it today.

**Comment by dmitripivkine** [comment]
If I understand correctly the end point is `do_get_mempolicy()` failed:
```
static long
do_get_mempolicy(int *policy, unsigned long *nmask, unsigned long maxnode, unsigned long addr, unsigned long flags)
{
	return (long)syscall(SYS_get_mempolicy, policy, nmask, maxnode, addr, flags);
}
```
Making this system call work fir this docker image would be a work around

**Comment by bharathappali** [comment]
closing this issue as [#3474 PR](https://github.com/eclipse/omr/pull/3474) is merged
