### ISSUE TITLE
Recent Java12 changes have moved some classes causing builds to now fail

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#3768]
The recent merge of JDK12 code to the extensions repository has caused the JDK12 builds to fail.
This seems to be related to Oracle moving some files from `src/java.base/share/classes/jdk/internal/misc` to `src/java.base/share/classes/jdk/internal/access`. 

The files that seem to have caused the OpenJ9 jcl source build to fail are: 
```
JavaLangRefAccess.java
SharedSecrets.java
```
as the package locations have changed and hence the import statements in the OpenJ9 jcl code that references these classes is incorrect and causes issues:
```
/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/MethodHandle.java:41: error: cannot find symbol
import jdk.internal.misc.SharedSecrets;
                        ^
  symbol:   class SharedSecrets
  location: package jdk.internal.misc
/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/System.java:33: error: cannot find symbol
import jdk.internal.misc.SharedSecrets;
                        ^
  symbol:   class SharedSecrets
  location: package jdk.internal.misc
/home/groeges/source/openj9jdk12/openj9-openjdk-jdk/build/linux-x86_64-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/Access.java:49: error: cannot find symbol
import jdk.internal.misc.JavaLangAccess;
```

**Comment by groeges** [comment]
These need to be fixed in order for the builds to work correctly.

**Comment by groeges** [comment]
The following files needed to be updated to resolve the issues with the missing imports:
```
	modified:   jcl/src/java.base/share/classes/java/lang/Access.java
	modified:   jcl/src/java.base/share/classes/java/lang/ClassLoader.java
	modified:   jcl/src/java.base/share/classes/java/lang/System.java
	modified:   jcl/src/java.base/share/classes/java/lang/invoke/MethodHandle.java
	modified:   jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java
	modified:   jcl/src/java.base/share/classes/java/lang/ref/Reference.java
	modified:   jcl/src/java.management/share/classes/com/ibm/java/lang/management/internal/BufferPoolMXBeanImpl.java
```

**Comment by groeges** [comment]
Now these files have been updated the build fails with lots of other issues with missing methods etc.

**Comment by theresa-m** [comment]
looking at this

**Comment by theresa-m** [comment]
From what I can see the following needs to be changed / is missing:
- [ ] change package names of JavaLangRefAccess, SharedSecrets (https://github.com/eclipse/openj9/pull/3824)
- [ ]  argument added for java.lang.VersionProps.init() _(verification of change pending)_
- [ ] Methods missing from jdk.internal.misc.Unsafe _(working on these)_
- All put, get, compareAndX variations for Reference (putReferece, getReferece, compareAndSetReference etc)
- [ ] Methods missing from java.lang.invoke.MethodHandles
- filterArgumentsWithCombiner
- [ ] Methods missing from java.lang.invoke.MethodType
- makeImpl
- ptypes
- [ ] Methods missing from java.lang.invoke.LambdaFormEditor
- filterRepeatedArgumentForm

**Comment by theresa-m** [comment]
Update: Java 12 builds with extensions commit 0b941d8 with this pr: https://github.com/eclipse/openj9/pull/3980

since then there looks to be more jcl changes around varhandles

fyi @keithc-ca

**Comment by theresa-m** [comment]
Update: Java 12 builds with extensions commit 0b941d8 (point when this issue was created) and probably later: #3980 is the pr for this (fyi @keithc-ca)

at the head of openj9-openjdk-jdk there are more compilation errors due to JEP 334 classes missing fyi @DanHeidinga @tajila @gacholio
