### ISSUE TITLE
ConcurrentScavenge ASSERTION FAILED ** at StandardAccessBarrier.cpp:856

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3769]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/88
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64/85

MathLoadTest_all_ConcurrentScavenge_0
```
===============================================
Running test MathLoadTest_all_ConcurrentScavenge_0 ...
===============================================
MathLoadTest_all_ConcurrentScavenge_0 Start Time: Wed Nov 21 06:52:12 2018 Epoch Time (ms): 1542783132365
variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
JVM_OPTIONS: -Xcompressedrefs -Xgcpolicy:gencon -Xgc:concurrentScavenge 
STF 06:52:12.542 - =========================   S T F   =========================
systemtest-prereqs has been processed, and set to: /home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqsRetrieving amount of free space on drive containing /home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15427797033140/MathLoadTest_all_ConcurrentScavenge_0
...
MLT stderr readObject ffe88d48 in Evacuate
MLT stderr 06:52:15.326 0xf9e700    j9mm.141    *   ** ASSERTION FAILED ** at StandardAccessBarrier.cpp:856: ((false))
```

DaaLoadTest_all_ConcurrentScavenge_0
```
===============================================
Running test DaaLoadTest_all_ConcurrentScavenge_0 ...
===============================================
DaaLoadTest_all_ConcurrentScavenge_0 Start Time: Wed Nov 21 06:52:19 2018 Epoch Time (ms): 1542783139939
variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
JVM_OPTIONS: -Xcompressedrefs -Xgcpolicy:gencon -Xgc:concurrentScavenge 
STF 06:52:20.113 - =========================   S T F   =========================
systemtest-prereqs has been processed, and set to: /home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/jvmtest/systemtest/systemtest_prereqsRetrieving amount of free space on drive containing /home/jenkins/workspace/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15427797033140/DaaLoadTest_all_ConcurrentScavenge_0
...
DLT stderr readObject fffd37d0 in Evacuate
DLT stderr 06:52:22.063 0x118b700    j9mm.141    *   ** ASSERTION FAILED ** at StandardAccessBarrier.cpp:856: ((false))
```

**Comment by dmitripivkine** [comment]
@amicic FYI

**Comment by dmitripivkine** [comment]
I looked to these failures. Most of them looks like #3491
However there are failures look different (but might still be the by same reason) - the problematic values referred from "temporary" slots of j9vmthread (returnValue2 and floatTemp1). These slots are not GC roots so it might refer to missed Read Barrier somewhere... or mean nothing. I am going to run grinder with -Xint in attempt to verify that GC changes is unrelated. If it is a case we need to wait until #3491 is fixed

**Comment by pshipton** [comment]
First failing builds SHAs
00:56:41 [echoproperties] java8.OpenJ9=- 449dda8
00:56:41 [echoproperties] java8.OMR=- 6945416

Previous build SHAs:
01:56:20 [echoproperties] java8.OpenJ9=- f439efd
01:56:20 [echoproperties] java8.OMR=- 69b1b77

Changes:
f439efd...449dda8
https://github.com/eclipse/omr/compare/69b1b77...6945416

**Comment by pshipton** [comment]
Note bootstrap shared classes by default was enabled in the first failing build, in case the AOT code in the shared cache could contribute to the failure.

**Comment by pshipton** [comment]
@dsouzai ^
I also note the failures only occur on jdk11, and only jdk11 was affected by shared classes by default.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/87
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64/86
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/90
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/89
