### ISSUE TITLE
java.lang.invoke.MethodHandleProxies is missing in OpenJ9

### ISSUE THREAD

**Issue by TianyuZuo** [eclipse/openj9#379]
JSR292 and JSR335 tests cannot be enabled due to java.lang.invoke.MethodHandleProxies is missing in OpenJ9. 

These tests are currently excluded from compilation and testing.
To include them in compilation, delete lines 
```
<exclude name="Jsr292/build.xml" />
<exclude name="Jsr335/build.xml" />
``` 
in `/test/TestConfig/scripts/build_test.xml`.

To include them in testing, delete `Jsr292 Jsr335` in `/test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl`

java -version 
```
root@66970b9fd915:/test/TestConfig# /java/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171016_367471 (JIT enabled, AOT enabled)
OpenJ9   - 73fb55a
OMR      - e705c80
OpenJDK  - 275ed65 based on jdk-9+181)
```

compilation error message
```
compile:
     [echo] Ant version is Apache Ant(TM) version 1.9.6 compiled on July 8 2015
     [echo] ============COMPILER SETTINGS============
     [echo] ===fork:				yes
     [echo] ===executable:			/java/bin/javac
     [echo] ===debug:				on
     [echo] ===destdir:				/test/TestConfig/../../jvmtest/Jsr292
    [javac] Compiling 69 source files to /test/Jsr292/bin
    [javac] /test/Jsr292/src/com/ibm/j9/jsr292/MethodHandleProxiesTest.java:27: error: cannot find symbol
    [javac] import java.lang.invoke.MethodHandleProxies;
    [javac]                        ^
    [javac]   symbol:   class MethodHandleProxies
    [javac]   location: package java.lang.invoke
```

**Comment by theresa-m** [comment]
Looking into this.

**Comment by DanHeidinga** [comment]
The key issue here is we want to reuse the OpenJDK version of `MethodHandleProxies.java` by providing minimal compile / runtime methods to make it work with OpenJ9's JSR 292 implementation.

Currently, the OpenJ9 code overrides MHProxies with an empty file:
` ./openj9/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandleProxies.java `

This task to remove that empty file and fix any compilation issues.

**Comment by theresa-m** [comment]
Pull request: https://github.com/eclipse/openj9/pull/439

**Comment by pshipton** [comment]
@TianyuZuo note we had to back out of enabling the Jsr292 tests #465 since they were failing  https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-linux_390-64_cmprssptrs/35
