### ISSUE TITLE
JDK8 OSX unrecognised option -Xgcpolicy:metronome

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3792]
With JDK8 on OSX, the following tests are failing because of `JVMJ9VM007E Command-line option unrecognised: -Xgcpolicy:metronome`:

```
cmdLineTester_jvmtitests_5
cmdLineTester_jvmtitests_hcr_SE80_7
cmdLineTester_jvmtitests_debug_5
TestHashTablePerformance_2
TestHashTableCorrectness_2
J9vmTest_2
```

Based upon [Dmitri's comment](https://github.com/eclipse/openj9/issues/3321#issuecomment-435074705), 
`-Xgcpolicy:metronome  supported at Linux x86 and AIX only at the moment. It might be enabled  on other platforms if they can support high-resolution clock.`

Based upon [Lan's comment](https://github.com/eclipse/openj9/issues/3321#issuecomment-435086459) and https://github.com/eclipse/openj9/issues/3508, tests shouldn't use `-Xgcpolicy:metronome` on OSX. 

But, the above failing tests still use `-Xgcpolicy:metronome` on OSX. May be few cases related to `-Xgcpolicy:metronome` were missed.

Note: Not verified but the above errors may also be seen with JDK11 OSX. Currently, the test sanity/extended jobs can't run the above tests on OSX because of hangs and test infra failures documented in https://github.com/eclipse/openj9/issues/3787, https://github.com/eclipse/openj9/issues/3789 and https://github.com/eclipse/openj9/issues/3685. Disabling the following tests will allow the test sanity jobs to run the above failing tests: https://github.com/eclipse/openj9/pull/3751/files.

**Comment by babsingh** [comment]
fyi - @llxia, @DanHeidinga

**Comment by llxia** [comment]
Exclude running -Xgcpolicy:metronome mode on osx in ottawa.csv (#3552) is merged.
I ran a grinder in openj9 Jenkins and `cmdLineTester_jvmtitests` worked as expected - `cmdLineTester_jvmtitests_5` was excluded:
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/79/tapResults/

However, when I ran the same `cmdLineTester_jvmtitests` internally. I got the same result as above - `cmdLineTester_jvmtitests_5` was not excluded.

By looking at the console output, it looks like we are using `mode service` internally, whereas externally, we are using ottawa.csv. 

@renfeiw could you turn off mode services for now? If we need to use `mode service` in the future, then it has to be updated based on ottawa.csv

**Comment by renfeiw** [comment]
Created a PR to turn it off: #3801

**Comment by llxia** [comment]
#3801 is delivered. The fix is verified internally.
