### ISSUE TITLE
JDK8 OSX Test failures: Initialization error for library j9gc29(2)

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3795]
JDK8 OSX Failure:
`JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata; 200M requested`

The following native tests are failing because of the above error:
```
jsigjnitest_0
thrstatetest_0
```

The issue is similar to https://github.com/eclipse/openj9/issues/3371#issuecomment-432291933.

If JDK with compressedrefs is used on OSX, native test binaries such as `jsigjnitest` and `thrstatetest` need to be compiled with `-pagezero_size 0x1000`. This will allow the JVM to allocate memory below 4GB. Otherwise, the `j9gc29` initialization error will be encountered.

`-pagezero_size 0x1000` should be used when building the native test binaries. `-pagezero_size 0x1000` should work with compressedrefs and non-compressedrefs SDKs on OSX. So, `-pagezero_size 0x1000` can be applied all the time when building native test binaries on OSX.

Note: Not verified but the above errors may also be seen with JDK11 OSX. Currently, the test sanity/extended jobs can't run the above tests on OSX because of hangs and test infra failures documented in https://github.com/eclipse/openj9/issues/3787, https://github.com/eclipse/openj9/issues/3789 and https://github.com/eclipse/openj9/issues/3685. Disabling the following tests will allow the test sanity jobs to run the above failing tests: https://github.com/eclipse/openj9/pull/3751/files.

**Comment by babsingh** [comment]
fyi - @DanHeidinga

**Comment by llxia** [comment]
yes, jsigjnitest_0 and thrstatetest_0 also have the same failure on osx JDK11.
