### ISSUE TITLE
would you please publish docker image on hub.docker.com?

### ISSUE THREAD

**Issue by netroby** [eclipse/openj9#38]
would you please publish docker image on hub.docker.com?
We want to try openj9 with docker

**Comment by stevewallin** [comment]
@dinogun - one for the cloud team to cover

**Comment by dinogun** [comment]
Thanks for the request and the heads-up. This is being worked on and the dockerfiles for OpenJDK with OpenJ9 will reside at https://github.com/AdoptOpenJDK/openjdk-build/tree/master/installer/docker and the images at https://hub.docker.com/u/adoptopenjdk/

**Comment by mstoodle** [comment]
@dinogun is there an issue at adoptopenjdk where @netroby (and others) can register their interest?
