### ISSUE TITLE
Test-extended.functional-JDK11 hang creating test summary

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3816]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_x86-64/87

TestClassLoaderFindResource_0  is the last test, the next step is creating the test result summary.

Copied the raw console output because the regular console output isn't working due to `org.apache.commons.jelly.JellyTagException: jar:file:/home/hudson/genie.openj9/.jenkins/war/WEB-INF/lib/jenkins-core-2.138.3.jar!/hudson/model/Run/console.jelly:65:27: <j:whitespace> Java heap space` 

```
TestClassLoaderFindResource_0 Finish Time: Fri Nov 23 08:02:42 2018 Epoch Time (ms): 1542960162021
make[2]: Leaving directory '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/functional/Java9andUp'
make[1]: Leaving directory '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/functional'
Cancelling nested steps due to timeout
Sending interrupt signal to process
Terminated
/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/settings.mk:311: recipe for target 'resultsSummary' failed
make: *** [resultsSummary] Error 143
make: Leaving directory '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests'
script returned exit code 2
```

working build output
```
2:32:49 TestClassLoaderFindResource_0 Finish Time: Fri Nov 23 07:32:52 2018 Epoch Time (ms): 1542958372258
02:32:49 make[2]: Leaving directory '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/functional/Java9andUp'
02:32:49 make[1]: Leaving directory '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/functional'
02:32:49 
02:32:49 
02:32:49 TEST TARGETS SUMMARY
```

**Comment by pshipton** [comment]
@llxia fyi

**Comment by pshipton** [comment]
@AdamBrousseau fyi

**Comment by renfeiw** [comment]
Looks like the failure output size is too large which causes the results summary to OOM. We have a variable $tapString to keep all the test status and failure output and print out tap result in the end. I can change the logic to dump tap output every one or two thousand lines.

**Comment by llxia** [comment]
We narrowed down the problem. It should be fixed in https://github.com/eclipse/openj9/pull/3821

**Comment by llxia** [comment]
On the related note, why the console output has 358M?

It seems the output is mostly from `Testing: Run !dumpallromclasslinear 2`. We should check if we can set `-outputLimit` on this test.

```
01:16:46.163 Testing: Run !dumpallromclasslinear 2 - with BCI agent core
01:16:46.163 Test start time: 2018/11/23 07:00:56 Coordinated Universal Time
01:16:46.163 Running command: /home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/../bin/jdmpview -core j9core.dmp
01:16:46.163 Time spent starting: 2 milliseconds
01:17:56.233 Time spent executing: 67931 milliseconds
01:17:56.233 Test result: FAILED
...
```

**Comment by pshipton** [comment]
@llxia do we still need this open? The problem appears to be fixed. #3821 #3844

**Comment by llxia** [comment]
I will close this one. I left a comment in backlog issue - Revisit test output of cmdlinetester tests
