### ISSUE TITLE
jdmpview find command does not match help output

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3819]
Running jdmpview on a core file, I was trying to use the `find` command according to the help output, but it doesn't work.

`find                                           searches memory for a given string`

```
> find J9VMRAS
incorrect number of parameters
> find
"find" takes a set comma separated parameters with no spaces
> find a,b
incorrect number of parameters
```

A workaround is to use the !find command

```
> !find ascii J9VMRAS
Scanning memory for 4a 39 56 4d 52 41 53 aligned to 1 starting from 0x0
Match found at 0x30000048
```

**Comment by ChengJin01** [comment]
Will double-check this issue to see what happens

**Comment by ChengJin01** [comment]
Already checked OpenJDK11_OpenJ9, OpenJDK8_OpenJ9 and internal Java 8. It seems the functional problem has been there for a long while (never be detected and addressed before). 

Need to investigate the code at /jcl/src/openj9.dtfjview/share/classes/com/ibm/jvm/dtfjview/commands/FindCommand.java to figure out what we can do wit that.

**Comment by pshipton** [comment]
I expect the simplified help output should either include the required parameters, or suggest running `help find` to see them. The user guide should also be updated with the full help.

**Comment by pshipton** [comment]
I must have looked in the wrong place, because now I see the OpenJ9 user guide has the full help https://www.eclipse.org/openj9/docs/tool_jdmpview/
