### ISSUE TITLE
OSX extended functional test failures

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3832]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-osx_x86-64_cmprssptrs/1

org.openj9.test.contendedfields.ContendedFieldsTests.setUp
org.openj9.test.contendedfields.ContendedFieldsTests.setUp
org.openj9.test.contendedfields.ContendedFieldsTests.setUp
org.openj9.test.contendedfields.ContendedFieldsTests.setUp
org.openj9.test.attachAPI.TestAttachAPI.test_agntld03
org.openj9.test.attachAPI.TestSunAttachClasses.testAgentLoading
j9vm.test.jni.ExceptionTest.test_loadLibraryExceptions
j9vm.test.jni.ExceptionTest.test_loadLibraryExceptionAndFail
j9vm.test.jni.ExceptionTest.test_loadLibraryExceptions
j9vm.test.jni.ExceptionTest.test_loadLibraryExceptionAndFail
j9vm.test.memory.MemoryAllocator.setUp
j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects
j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects
j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects
j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects
j9vm.test.softmx.SoftmxAdvanceTest_GC_Only.testDisclaimMemoryEffects_GC_Test
j9vm.test.softmx.SoftmxLocalTest.testSoftmxHasEffects
j9vm.test.softmx.SoftmxLocalTest.testSoftmxHasEffects
org.openj9.test.java.lang.management.ThreadMXBean.MonitorTraceTest.testMonitorTraceTest
org.openj9.test.java.lang.management.ThreadMXBean.MonitorTraceTest.testMonitorTraceTest
org.openj9.test.java.lang.management.ThreadMXBean.APITest2.testAPITest2

**Comment by llxia** [comment]
native test libs missing issue should be fixed by https://github.com/eclipse/openj9/pull/3765

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-osx_x86-64_cmprssptrs/3

Updated list of failures:


testSCCMLTests4_1
testSCCMLTests5_1
testSCCMLTests6_1
TestSunAttachClasses_0
ContendedFieldsTests_90_1
threadMXBeanTestSuite2_3
testSoftMxDisclaimMemory_LP4k_2
testDefaultDisclaimMemory_2

org.openj9.test.contendedfields.ContendedFieldsTests.testMultipleFieldContClass
org.openj9.test.contendedfields.ContendedFieldsTests.testContentionGroupsAndClass
org.openj9.test.contendedfields.ContendedFieldsTests.testFinalizableMultipleFieldContClass
org.openj9.test.contendedfields.ContendedFieldsTests.testMultipleContFieldContClass
org.openj9.test.attachAPI.TestSunAttachClasses.testAgentLoading
j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects
j9vm.test.softmx.SoftmxAdvanceTest.testDisclaimMemoryEffects
org.openj9.test.java.lang.management.ThreadMXBean.APITest2.testAPITest2

**Comment by pdbain-ibm** [comment]
I plan to investigate the `ContendedFiledsTests` and `TestSunAttachClasses`.

**Comment by pshipton** [comment]
Looking at the latest build, all of these failures seem to be resolved except https://github.com/eclipse/openj9/issues/3778 so I will close this.
