### ISSUE TITLE
OSX shared classes extended system test failures

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3833]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-osx_x86-64_cmprssptrs/1

SharedClassesAPI_0
SharedClasses.SCM01.MultiThreadMultiCL_0
SharedClasses.SCM23.MultiCL_0
SharedClasses.SCM23.MultiThread_0

**Comment by hangshao0** [comment]
Code is here; 
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/d42cd0d94f7e017c1b3fbcb748cfecce81e15801/src/java.base/share/classes/jdk/internal/loader/BuiltinClassLoader.java#L245toL246

Might be related to recent Boolean change.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-osx_x86-64_cmprssptrs/3

List of failures has changed a little:
SharedClassesAPI_0
SharedClassesWorkload_0
SharedClasses.SCM23.MultiThread_0

**Comment by hangshao0** [comment]
SharedClassesAPI_0 failure is caused by:
```
JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC336E Port layer error code = -393970
JVMSHRC337E Platform error message: shmget : Cannot allocate memory
JVMSHRC029E Not enough memory left on the system
JVMSHRC663I Error recovery: destroyed semaphore set with id=65537 associated with shared class cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

SharedClassesWorkload_0 failure is caused by the same NPE in my previous comment. 

SharedClasses.SCM23.MultiThread_0 failure is caused by:
```
MT5 stderr Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NullPointerException
MT5 stderr 	at java.base/java.lang.ModuleLayer.getServicesCatalog(ModuleLayer.java:939)
MT5 stderr 	at java.base/java.lang.Access.getServicesCatalog(Access.java:281)
MT5 stderr 	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.providers(ServiceLoader.java:1002)
MT5 stderr 	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.iteratorFor(ServiceLoader.java:1048)
MT5 stderr 	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.<init>(ServiceLoader.java:994)
MT5 stderr 	at java.base/java.util.ServiceLoader.newLookupIterator(ServiceLoader.java:1294)
MT5 stderr 	at java.base/java.util.ServiceLoader.iterator(ServiceLoader.java:1359)
MT5 stderr 	at java.base/java.net.URLClassLoader.initializeSharedClassesSupport(URLClassLoader.java:193)
MT5 stderr 	at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:285)
MT5 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.run(LoaderSlaveMultiThread.java:70)
MT5 stderr 	at net.openj9.test.sc.LoaderSlaveMultiThread.main(LoaderSlaveMultiThread.java:54)
MT5 stderr Caused by: java.lang.NullPointerException
MT5 stderr 	at java.base/jdk.internal.org.objectweb.asm.MethodWriter.visitFieldInsn(MethodWriter.java:897)
MT5 stderr 	at java.base/jdk.internal.org.objectweb.asm.MethodVisitor.visitFieldInsn(MethodVisitor.java:452)
MT5 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory$ForwardingMethodGenerator.generate(InnerClassLambdaMetafactory.java:458)
MT5 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:283)
MT5 stderr 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:188)
MT5 stderr 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
MT5 stderr 	at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1105)
MT5 stderr 	... 11 more
```

**Comment by dsouzai** [comment]
The error seen in https://github.com/eclipse/openj9/issues/3833#issuecomment-441688790 might be related to https://github.com/eclipse/openj9/issues/3333#issuecomment-440327270 . When I last left off my investigation, I managed to get core files and some logging; I'm going to have to go through them to see what the problem is. As far as I can tell, the AOT problem isn't a new one (since it happens with "old" AOT). 

If that error is very reproducable, might be worth either running with `-Xnoaot` or perhaps `-Xjit:exclude={jdk/internal/org/objectweb/asm/Item.set(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V}`

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-osx_x86-64_cmprssptrs/8/tapResults/
`shmget : Cannot allocate memory` still occurs.

**Comment by pshipton** [comment]
I'm going to close this now as a dup of https://github.com/eclipse/openj9/issues/3947. The machine configuration issue causing `shmget : Cannot allocate memory` is the only remaining failure I see.
