### ISSUE TITLE
New methods in String for jdk12

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3850]
indent(int)
transform​(Function<? super String,? extends R> f)
http://cr.openjdk.java.net/~iris/se/12/build/latest/api/java.base/java/lang/String.html

**Comment by JasonFengJ9** [comment]
@theresa-m does your `Java 12` PR cover the methods specified here?

**Comment by JasonFengJ9** [comment]
There are couple of new additions:
```
public Optional<String> describeConstable()
public String resolveConstantDesc​(MethodHandles.Lookup lookup)
```

**Comment by theresa-m** [comment]
I have not covered the align/indent/transform methods. describeConstable and resolveConstantDesc are part of jep334. the pr for them is https://github.com/eclipse/openj9/pull/4105

**Comment by JasonFengJ9** [comment]
It appears `align()` & `align(int)` have been removed.

**Comment by theresa-m** [comment]
@sharon-wang

**Comment by pshipton** [comment]
@JasonFengJ9 @theresa-m is somebody looking at transform?

**Comment by fjeremic** [comment]
> @JasonFengJ9 @theresa-m is somebody looking at transform?

In addition I'd like to add to please take a look at the corresponding StringLatin1 and StringUTF16 classes to see if OpenJDK has already added helpers for these APIs which we can reuse. IIRC that was th ecase for some of the previous Java 12 methods.

**Comment by JasonFengJ9** [comment]
> is somebody looking at transform?

Not that I am aware of.

**Comment by pshipton** [comment]
@DanHeidinga we need an implementation for `String.transform​(Function<? super String,? extends R> f)`

@theresa-m @sharon-wang any outlook for indent(int)? The feature complete date is Feb 25.
There is no StringLatin1, StringUTF16 helper.

**Comment by JasonFengJ9** [comment]
Will take `String.transform​(Function<? super String,? extends R> f)`.

**Comment by theresa-m** [comment]
We're on it. @sharon-wang is working on some tests for the method.
