### ISSUE TITLE
Enable shared classes by default on jdk8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3854]
As enabling shared classes by default for jdk11 #1646 appears to be working now, we can look at enabling it by default on jdk8.

**Comment by pshipton** [comment]
@hangshao0

**Comment by hangshao0** [comment]
I will wait one more week to backport to Java 8 if there is no problem found for #1646

**Comment by pshipton** [comment]
@hangshao0 We can wait a week to merge the change, but I suggest making a PR now and we can run all the PR testing to see if it exposes any problems.
