### ISSUE TITLE
jconsole fails to attach to local openj9 JVM process

### ISSUE THREAD

**Issue by Param-S** [eclipse/openj9#386]
jconsole failing to attach to local openj9 JVM process with exception

**com.sun.tools.attach.AttachOperationFailedException: AttachOperationFailedException from target: ATTACH_ERR AttachOperationFailedException in startLocalManagementAgent:  
startLocalManagementAgent: com.sun.management.jmxremote.localConnectorAddress not defined at** 
com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(jdk.attach/OpenJ9VirtualMachine.java:336) at 
com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.startLocalManagementAgent(jdk.attach/OpenJ9VirtualMachine.java:522) at sun.tools.jconsole.LocalVirtualMachine.loadManagementAgent(jdk.jconsole/LocalVirtualMachine.java:237) at sun.tools.jconsole.LocalVirtualMachine.startManagementAgent(jdk.jconsole/LocalVirtualMachine.java:96) at 
sun.tools.jconsole.ProxyClient.tryConnect(jdk.jconsole/ProxyClient.java:333) at 
sun.tools.jconsole.ProxyClient.connect(jdk.jconsole/ProxyClient.java:313) at 
sun.tools.jconsole.VMPanel$2.run(jdk.jconsole/VMPanel.java:296)

**Comment by Param-S** [comment]
Issue is same as #238 

I tested with the proposed PR, jconsole able to connect to target JVM with the fix.

**Comment by pdbain-ibm** [comment]
Correction to @Param-S 's comment above: issue #238 is due to a different issue (missing JVMTI agent).

**Comment by pshipton** [comment]
And can we close #241 now?

**Comment by pshipton** [comment]
I see it was closed anyway because of the commit comment for #236
