### ISSUE TITLE
Build all java executables with -pagezero_size on MAC

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#3861]
-pagezero_size 0x1000 can be used for both compressedrefs and non-compressedrefs variants. This will allow executables to work with both compressedrefs and non-compressedrefs OpenJ9 librarires.

If I use compressedrefs shared libraries in a non-compressedrefs SDK, then the executables such as java, javap ... would fail with `JVMJ9VM015W Initialization error for library j9gc29(2): Failed to instantiate compressed references metadata; 200M requested.`

Second, this change will provide a generic front-end where executables such as java, javap ... can be used with both compressedrefs and non-compressedrefs shared libraries.

This change also is one less thing to do in the future when compressed / default jvm sidecars are merged.

- [x] jdk8 https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/217
- [x] jdk11 https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/71
- [x] jdk.next  ibmruntimes/openj9-openjdk-jdk#51

**Comment by DanHeidinga** [comment]
@babsingh Can you also create a PR against https://github.com/ibmruntimes/openj9-openjdk-jdk for this change?

**Comment by babsingh** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/51.

**Comment by DanHeidinga** [comment]
Closing as changes delivered to jdk8, 11, and next extensions repos
