### ISSUE TITLE
Failing to compile windows with VS2017

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#3872]
Compiling with the latest greatest, I'm getting a link failure.

```
link -DLL -subsystem:windows -nologo -nodefaultlib -incremental:no -debug -machine:AMD64   -libpath:"c:\temp\bld_403503\bld_win_x86-64\compiler\.." -libpath:"c:\temp\bld_403503\bld_win_x86-64\compiler\..\lib" -OUT:"c:\temp\bld_403503\bld_win_x86-64\compiler\..\j9j
it29.dll" -MAP:"c:\temp\bld_403503\bld_win_x86-64\compiler\..\j9jit29.dll.map" -BASE:0x12900000 -DEF:"c:\temp\bld_403503\bld_win_x86-64\compiler\..\compiler\build\scripts\j9jit.def" @"c:\temp\bld_403503\bld_win_x86-64\compiler\..\j9jit29.dll.objlist" "j9jit_vm.lib" "j9codert_vm.lib" "j9util.lib" "j9utilcore.lib" "j9pool.lib" "j9avl.lib" "j9stackmap.lib" "j9hashtable.lib" "j9jit_vm.lib" "j9codert_vm.lib" "j9util.lib" "j9utilcore.lib" "j9pool.lib" "j9avl.lib" "j9stackmap.lib" "j9hashtable.lib" "j9thr.lib" "j9hookable.lib" "kernel32.lib" "oldnames.lib" "msvcrt.lib" "msvcprt.lib" "ws2_32.lib"
   Creating library c:\temp\bld_403503\bld_win_x86-64\compiler\..\j9jit29.lib and object c:\temp\bld_403503\bld_win_x86-64\compiler\..\j9jit29.exp
j9codert_vm.lib(dlt.obj) : error LNK2001: unresolved external symbol memcpy
...
TRPersistentMemory.obj : error LNK2001: unresolved external symbol memset
...
OMRLabelSymbol.obj : error LNK2001: unresolved external symbol __imp___stdio_common_vsprintf
...
Tree.obj : error LNK2001: unresolved external symbol __CxxFrameHandler3
...
```

**Comment by pshipton** [comment]
I'm thinking the problem is related to the `-nodefaultlib` option. The location of memcpy has changed in VS2017, it is no longer in `msvcrt.lib`. I did find something in `vcruntime.lib` although it is called `memcpy` and not `_memcpy`

**Comment by pshipton** [comment]
Looking at a pre-OpenJ9 build it still uses `-nodefaultlib` so I don't think it is new. The change is in trying to compile with VS2017 instead of 2015 or earlier.

**Comment by jdekonin** [comment]
The nightly worked with 2017, so I'm guessing this is how the environment is setup??
https://ci.eclipse.org/openj9/job/Build-JDK11-win_x86-64_cmprssptrs/237/consoleFull

**Comment by jdekonin** [comment]
"ucrt.lib" "vcruntime.lib" is added to the JDK11 compile.  only one use in openj9, runtime/compiler/build/toolcfg/win-msvc/common.mk.  These appear to be added only if MSVC_VERSION is set to 2015 or 2017.  Guessing that openjdk sets this variable and I am trying to compile openj9 standalone.

**Comment by pshipton** [comment]
This is not an OpenJ9 problem. The fix is here https://github.com/eclipse/openj9/blob/8d61ec233297c565e4a186a2be5d0a3ea23b8fdb/runtime/compiler/build/toolcfg/win-msvc/common.mk#L241

**Comment by gacholio** [comment]
I find it odd that you say "not an openj9 problem" and provide an openj9 link to the fix...

**Comment by pshipton** [comment]
"not a OpenJ9 problem" because OpenJ9 already contains the necessary code. The reported problem is a user error when trying to build (IBM Java 8).

**Comment by jdekonin** [comment]
Works fine by setting MSVC_VERSION.
