### ISSUE TITLE
Default shared cache may cause -Xscmx to be ignored

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3885]
@DanHeidinga raised an interesting point in conversation. Recording it here so there is a record, and for discussion.

Apps which already use the shared cache may be setting a -Xscmx option. These apps should be setting a cache name as best practice, and not using the default name. If they set a cache name there is no issue. 

The -Xscmx option has no affect if the cache already exists. A cache with the default name could have always pre-existed, but once shared classes is enabled by default (#3858), it may occur more frequently or unexpectedly.

The default shared cache is created with a hard limit of 300MB, and a soft limit of 64MB (when possible). It would be possible to change the behavior of -Xscmx and have it adjust the soft limit of an existing cache. This would be an incompatible change and could cause other unexpected behavior. I think the best solution is to mention the problem in the release notes and tell users that best practice is for apps to set a cache name.

**Comment by pshipton** [comment]
@hangshao0

**Comment by pshipton** [comment]
@mpirvu

**Comment by hangshao0** [comment]
If the subsequent JVMs with different -Xscmx value can change the soft max limit of an existing shared cache, it basically invalidate the softmx setting of the first JVM, it is very likely to cause problems for the first JVM.  Also the soft max value could be changed back and forth more frequently.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9-docs/issues/162
