### ISSUE TITLE
JTreg test fail : java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessXXX.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3940]
The set of java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessXXX.java JTreg tests (e.g. https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/test/jdk/java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessByte.java) inconsistently fail by exiting unexpectedly with a return code 137.

For example, this job shows the failures of 6 of this group of tests due to this issue - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/158/.

However, these tests do pass without problems occasionally, for example this job shows just 1 of this group of tests failing due to this issue - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/149/.

Other other job instances under https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/ illustrate the inconsistent failures of this group of tests.

These inconsistent failures occur with the "default" JTreg concurrency value of 4.
When the concurrency value is set to 1, I have yet to see these failures - this set of job instances demonstrate this ...

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/506/ No such failures
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/507/ No such failures
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/508/ No such failures
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/509/ No such failures

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/510/ No such faliures
(14 iterations request - 8 completed before timeout reached)

There was discussion online that such a problem could be prevented by ensuring certain ulimit settings were increased (e.g. https://github.com/travis-ci/travis-ci/issues/4192#issuecomment-161800452) - I set all the ulimits on the test machine to "unlimited" or significantly increased them, with no impact - these tests continue to fail inconsistently.

I am not aware of any other test machine configuration that could cause these failures, so I am now assuming this is a problem with the OpenJ9 code.

Please could you provide details of what additional PD information you would like me to attempt to capture.

**Comment by pdbain-ibm** [comment]
For the record, exit code 139 indicates a `kill -9` from another process.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/727

**Comment by pdbain-ibm** [comment]
Cannot reproduce on MacOS or Linux X86. 100/100 runs passed on both platforms.
Given that this is an external `kill -9`, and reducing the concurrency fixes the problem, this is most likely a problem with hardware limits, e.g. real memory.

**Comment by pdbain-ibm** [comment]
@ben-walsh is this still occurring?

**Comment by adam-thorpe** [comment]
Can confirm this is still an issue. Managed to reproduce multiple times on multiple platforms, eg.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2013

I believe the problem lies in:
```
test VarHandleTestMethodHandleAccessFloat.testAccess("VarHandle -> MethodHandles.varHandleInvoker -> Array", VarHandleBaseTest$MethodHandleAccessTestCase@54281746)
```
Test does not print this line out in the stdout (above line is grabbed from a hotspot run), which means that the test exited in this sub-test.

StdErr:
```
11:33:12  Assertion failed at /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9/workspace/build/src/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/optimizer/InterpreterEmulator.cpp:208: 0
11:33:12  VMState: 0x000502ff
11:33:12  	unexpected bytecode in thunk archetype 0x7f49a00e0950 at bcIndex 8 JBastore3 (89)
11:33:12  
11:33:12  compiling java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(Ljava/lang/Object;)I at level: warm
11:33:12  #0: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8adfd5) [0x7f4a41a6cfd5]
11:33:12  #1: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x8ba150) [0x7f4a41a79150]
11:33:12  #2: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x57c07b) [0x7f4a4173b07b]
11:33:12  #3: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x57c26d) [0x7f4a4173b26d]
11:33:12  #4: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x26542c) [0x7f4a4142442c]
11:33:12  #5: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2690a2) [0x7f4a414280a2]
11:33:12  #6: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x257440) [0x7f4a41416440]
11:33:12  #7: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x2599a2) [0x7f4a414189a2]
11:33:12  #8: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x23b3c2) [0x7f4a413fa3c2]
11:33:12  #9: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x246ed9) [0x7f4a41405ed9]
11:33:12  #10: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x24ea2b) [0x7f4a4140da2b]
11:33:12  #11: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x66ab7e) [0x7f4a41829b7e]
11:33:12  #12: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x246366) [0x7f4a41405366]
11:33:12  #13: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x72c337) [0x7f4a418eb337]
11:33:12  #14: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x72c859) [0x7f4a418eb859]
11:33:12  #15: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x72dc9b) [0x7f4a418ecc9b]
11:33:12  #16: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x51e24d) [0x7f4a416dd24d]
11:33:12  #17: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x184466) [0x7f4a41343466]
11:33:12  #18: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x1852a1) [0x7f4a413442a1]
11:33:12  #19: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x20df3) [0x7f4a43813df3]
11:33:12  #20: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x186f75) [0x7f4a41345f75]
11:33:12  #21: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18750e) [0x7f4a4134650e]
11:33:12  #22: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183143) [0x7f4a41342143]
11:33:12  #23: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183592) [0x7f4a41342592]
11:33:12  #24: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x18363a) [0x7f4a4134263a]
11:33:12  #25: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9prt29.so(+0x20df3) [0x7f4a43813df3]
11:33:12  #26: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so(+0x183a94) [0x7f4a41342a94]
11:33:12  #27: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9thr29.so(+0xe1a6) [0x7f4a480331a6]
11:33:12  #28: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f4a49b8d6ba]
11:33:12  #29: function clone+0x6d [0x7f4a494ae41d]
11:33:12  
11:33:12  JVMDUMP039I Processing dump event "abort", detail "" at 2020/01/30 11:32:49 - please wait.
11:33:12  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15803839146056/jdk_custom_0/work/scratch/core.20200130.113249.9008.0001.dmp' in response to an event

11:33:12  TEST RESULT: Failed. Unexpected exit from test [exit code: 134]
```
