### ISSUE TITLE
Cannot load curl on aix71-p8-4

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#3961]
Running test on `aix71-p8-4` and it failed with `Cannot load program curl `

https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/115/console
https://ci.eclipse.org/openj9/computer/aix71-p8-4/

```
00:00:27.958 curl -OLJks  https://api.adoptopenjdk.net/v2/binary/nightly/openjdk8?openjdk_impl=openj9&os=aix&arch=ppc64&release=latest&type=jdk&heap_size=normal
00:00:27.958 exec(): 0509-036 Cannot load program curl because of the following errors:
00:00:27.958 	0509-150   Dependent module /usr/lib/libcurl.a(libcurl.so.4) could not be loaded.
00:00:27.958 	0509-103   The module has an invalid magic number.
[Pipeline] }
00:00:29.388 [ssh-agent] Stopped.
```

**Comment by llxia** [comment]
fyi @jdekonin

**Comment by llxia** [comment]
Same with PR build: https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/329/console

**Comment by jdekonin** [comment]
Seems to work fine when I perform a command manually, as the same user id as the PR would use.

I have updated and rebooted the machine.  It online for work again.

**Comment by pshipton** [comment]
Closing as per https://github.com/eclipse/openj9/issues/4245#issuecomment-454014383
