### ISSUE TITLE
System Property "os.version" shows unexpected version for macOS

### ISSUE THREAD

**Issue by pe-st** [eclipse/openj9#3969]
I'm using the macOS version of JDK 11.0.1 obtained form adoptopenjdk:

```
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181020_7 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - f62696f378 based on jdk-11.0.1+13)
```

The System Property `os.version` is set to `18.2.0`, though I would have expected `10.14.1` (this is shown both by "About my Mac" and the Hotspot VM)

    $ java -XshowSettings:properties --version 2>&1 | grep -E "(java|os).(version|vendor) "
    java.vendor = Eclipse OpenJ9
    java.version = 11.0.1
    os.version = 18.2.0

Here's the output of Java 11 with the Hotspot VM, showing the expected version `10.14.1`

    $ java -XshowSettings:properties --version 2>&1 | grep -E "(java|os).(version|vendor) "
    java.vendor = Oracle Corporation
    java.version = 11
    os.version = 10.14.1

**Comment by fjeremic** [comment]
@pdbain-ibm FYI.

**Comment by pdbain-ibm** [comment]
Looking at this.  The OS version comes from OMR via a call to `uname()`, which returns the kernel information:
version=`Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64`
release=`17.7.0`

**Comment by pdbain-ibm** [comment]
We should use `syscall` on `kern.osproductversion` in `omrsysinfo.c`.

**Comment by pdbain-ibm** [comment]
OMR pull request opened: https://github.com/eclipse/omr/pull/3327.

**Comment by pe-st** [comment]
Great, thx!

**Comment by DanHeidinga** [comment]
Closing as OMR fix has been merged.
