### ISSUE TITLE
Update buildj9tools.mk for OpenJDK 7

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#397]
Currently, buildj9tools.mk will only build if you're using an OpenJDK8 (or up) as the boot JDK.

To build OpenJDK8 on OpenJ9, we need to use an OpenJDK7 boot JDK (according to the OpenJDK8 build docs).

To verify this, I changed the numbers in buildj9tools.mk manually, and the OpenJDK8 on OpenJ9 build passed the error step without problems. In the long run we should probably put some logic in to set the java version number/s (there are two "8"s in that file) to be n-1, where "n" is the version of the Java we're compiling.

**Comment by jdekonin** [comment]
In jdk9 the instructions state, '...OpenJDK should be able to "build itself", so an up-to-date build of the current OpenJDK source is an acceptable alternative.'
http://hg.openjdk.java.net/jdk9/jdk9/file/a08cbfc0e4ec/common/doc/building.md

Would it be possible to test to see if this is the case for jdk8?

**Comment by adamfarley** [comment]
I'm using the OpenJDK8 build instructions, found here: 

hg.openjdk.java.net/build-infra/jdk8/raw-file/tip/README-builds.html

These instructions tell me:

"Building JDK 8 requires use of a version of JDK 7 that is at Update 7 or newer. JDK 8 developers should not use JDK 8 as the boot JDK, to ensure that JDK 8 dependencies are not introduced into the parts of the system that are built with JDK 7."

If you're asking me "Can OpenJDK8 on OpenJ9 be built using OpenJDK8 on Hotspot as a boot Java", then I imagine it would, either right away or with minor tweaking. 

If you're asking me if we *should* do this, I'd say the documentation says a clear "no". 

If you're asking me if it would cause additional test failures, I'd say "I don't know".

Right now, I'm going by the word of the documentation.

**Comment by pshipton** [comment]
Since we are building OpenJ9 and not OpenJDK, this restriction doesn't really apply "JDK 8 developers should not use JDK 8 as the boot JDK, to ensure that JDK 8 dependencies are not introduced into the parts of the system that are built with JDK 7.". As per this Issue, we already have built is dependencies on Java 8.

I suggest we use Java 8 for building, at least in the short term, as long as it appears to work. Meaning this Issue will not be a blocker for getting Java 8 builds running.

**Comment by adamfarley** [comment]
Apologies. I should have been more clear.

The Java 8 builds are already running (on pLinux, my assigned platform, at least). Using a private repository for the prototype Extensions, I can build OpenJDK8 on OpenJ9 on pLinux, while using OpenJDK7 on Hotspot as a boot JVM.

The only change I need to make to make the build work (beyond my special extensions and some changes I contributed to OpenJ9 already) is to change those two "8"s in buildj9tools.mk into "7"s.

Dan Heidinga suggested using an "n-1" system in the long run, and that's what this is about.

**Comment by pshipton** [comment]
Thanks Adam. I incorrectly assumed there would be more tooling problems like the change required to the java preprocessor.

**Comment by adamfarley** [comment]
I've made the changes in pull request 478

These changes have been tested for Javas 8 and 9 on x86, and we're testing on ppcle and zLinux now.

Note that we'll be able to verify java -version on x86 and ppcle only. zLinux still doesn't build to completion locally due to disk space issues on our assigned zLinux box.

**Comment by adamfarley** [comment]
Verified on x86 and pLinux. zLinux passed the trouble stage and produced the right debugging output, so we're fairly confident it would build to completion if it had enough disk space.

**Comment by adamfarley** [comment]
Here's a pull request with the bare minimum change to enable building OpenJDK8 with OpenJDK7, as the full suite of n-1 changes (PR 478) is proving contentious.

https://github.com/eclipse/openj9/pull/483

**Comment by DanHeidinga** [comment]
Explicitly linking to #478 to tie all the conversations together

**Comment by adamfarley** [comment]
The change in #483 has been merged, and #478 has been discarded. Closing issue.
