### ISSUE TITLE
UnixOperatingSystemMXBean#getOpenFileDescriptorCount returns -1 on macOS

### ISSUE THREAD

**Issue by pe-st** [eclipse/openj9#3970]
I'm not sure if this is a bug or just something not clearly specified, but it's a behaviour different from Hotspot. Here's a small example class:

```
import java.lang.management.ManagementFactory;
import java.lang.management.OperatingSystemMXBean;

import com.sun.management.UnixOperatingSystemMXBean;

public class OsMxBean {

    public static void main(String[] args) {
        OperatingSystemMXBean osMXBean = ManagementFactory.getOperatingSystemMXBean();
        if (osMXBean instanceof UnixOperatingSystemMXBean) {
            final UnixOperatingSystemMXBean unixOsMXBean = (UnixOperatingSystemMXBean) osMXBean;
            System.out.printf("ofdc : %d / Java Version %s %s / OS %s %s\n",
                    unixOsMXBean.getOpenFileDescriptorCount(),
                    System.getProperty("java.version"),
                    System.getProperty("java.vendor"),
                    System.getProperty("os.name"),
                    System.getProperty("os.version"));
        }
    }
}
```

Here is the output from the Hotspot VM...

    $ java OsMxBean.java
    ofdc : 5 / Java Version 11 Oracle Corporation / OS Mac OS X 10.14.1

... and OpenJ9 VMs:

    $ java OsMxBean.java
    ofdc : -1 / Java Version 11.0.1 Eclipse OpenJ9 / OS Mac OS X 18.2.0

OpenJ9 returns -1 as Open File Descriptor Count, which isn't what I would expect.

Notes:

- I've opened #3969 for the slightly unexpected OS version 18.2.0
- the method `getOpenFileDescriptorCount` is used by `com.codahale.metrics.jvm.FileDescriptorRatioGauge#getRatio`. The value -1 lets fail the corresponding unit test `com.codahale.metrics.jvm.FileDescriptorRatioGaugeTest#validateFileDescriptorRatioPresenceOnNixPlatforms`

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by JasonFengJ9** [comment]
This failure was due to missing `Mac OSC` implementation to get open file count. Submitted a PR https://github.com/eclipse/omr/pull/3363.

**Comment by pshipton** [comment]
@JasonFengJ9 do we have a test for getOpenFileDescriptorCount()? Either there isn't one and it should be added, or it isn't running for some reason and we should get it enabled.

**Comment by JasonFengJ9** [comment]
@pshipton It doesn't appear there is a test for `com.ibm.lang.management.internal.UnixExtendedOperatingSystem.getOpenFileDescriptorCount()`, will add one a bit later.

**Comment by JasonFengJ9** [comment]
@pe-st please be advised that a fix (https://github.com/eclipse/omr/pull/3363) has been merged, this issue will be closed when an automated test is added.

**Comment by pshipton** [comment]
The fix is in omr which is currently blocked in promotion. Until the omr promotion problem is fixed, the fix will not affect OpenJ9 builds.

**Comment by pshipton** [comment]
omr has promoted, the fix should be in the next set of builds. I'm going to go ahead and close this. If it turns out there is still a problem we can reopen.
