### ISSUE TITLE
Update buildj9tools.mk for OpenJDK 7

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#398]
Currently, buildj9tools.mk will only build if you're using an OpenJDK8 or up. 

To build OpenJDK8 on OpenJ9, we need to use an OpenJDK7 (according to the OpenJDK8 build docs).

To verify this, I changed the numbers manually, and the OpenJDK8 on OpenJ9 build passed the error step without problems. In the long run we should probably put some logic in to set the java version number/s (there are two "8"s in that file) to be n-1, where "n" is the version of the Java we're compiling.

**Comment by keithc-ca** [comment]
This looks like a duplicate of #397.

**Comment by adamfarley** [comment]
A fair comment. I recall the tab appeared to get "stuck" while raising the issue, so I copied the text over into a new issue.

Will close.
