### ISSUE TITLE
EclipseJ9 not implementing JEP 158

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#3999]
Hello,

  While migrating my applications from ORACLE Java 8 to AdoptOpenJDK11 with EclipseJ9, I have been surprised to see that options related to verbose garbage collection are not working.
  I read that for Java version >8, anything related to garbage collection logging should rely on command line options documented in [JEP 158](https://openjdk.java.net/jeps/158).
  However, AdoptOpenJDK 11 with OpenJ9 (0.11.0) fails to support JEP 158 options.
  See this sample test:

```
 ./j9/bin/java "-Xlog:gc*" -version
JVMJ9VM085W Malformed option: '-Xlog:gc*'
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux amd64-64-Bit Compressed References 20181115_18 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)
```

on the other hand, AdoptOpenJDK11 with HotSpot is correctly interpreting JEP 158 command-line options:

```
./hotspot/bin/java "-Xlog:gc*" -version
[0.004s][info][gc,heap] Heap region size: 1M
[0.006s][info][gc     ] Using G1
[0.006s][info][gc,heap,coops] Heap address: 0x000000008da00000, size: 1830 MB, Compressed Oops mode: 32-bit
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.1+13, mixed mode)
[0.106s][info][gc,heap,exit ] Heap
[0.106s][info][gc,heap,exit ]  garbage-first heap   total 118784K, used 0K [0x000000008da00000, 0x0000000100000000)
[0.106s][info][gc,heap,exit ]   region size 1024K, 1 young (1024K), 0 survivors (0K)
[0.106s][info][gc,heap,exit ]  Metaspace       used 3121K, capacity 4480K, committed 4480K, reserved 1056768K
[0.106s][info][gc,heap,exit ]   class space    used 269K, capacity 384K, committed 384K, reserved 1048576K
```

I am puzzled by this issue, as I thought that both AdoptOpenJDK VM types are going through TCKs, and I assumed that JEPs are part of TCKs. 
Isn't it the case?

Anyway, is there any target for OpenJ9 to support JEP 158 ?

Kind regards,
Alexandre

**Comment by DanHeidinga** [comment]
Expanding on @charliegracie's answer, some JEPs - in particular those that affect the Java language or VM specifications - are rolled up as part of JSRs that are submitted through the regular JCP processes.  Most commonly, JEPs are rolled up as part of the platform JSR - the JSR that defines a new Java release.

Command line options aren't covered by the specifications and as so JEPs that primarily add new options or refactor existing options aren't included in the platform JSR.

As Charlie says, implementation of them is optional.

**Comment by pshipton** [comment]
OpenJ9 has alternate options to enable gc logging, `-verbose:gc` https://www.eclipse.org/openj9/docs/cmdline_general/ and https://www.eclipse.org/openj9/docs/xverbosegclog/

There is also a tool (GCMV) that reads the GC logs and interprets them. https://publib.boulder.ibm.com/httpserv/cookbook/Major_Tools-Garbage_Collection_and_Memory_Visualizer_GCMV.html
https://www.ibm.com/developerworks/library/j-ibmtools2/index.html
https://marketplace.eclipse.org/category/free-tagging/gcmv

**Comment by avermeer** [comment]
Hello,

Thank you very much for these clear answers: I was not aware of the optional nature of JEPs.

Our project does not deeply depends on JEP 158 command-line options for verbose GC : we can by-pass the HotSpot vs OpenJ9 command line different by using scripts that will call `java -version` in order to produce different arguments.

It's a minor pain, so if eventually OpenJ9 adopts (pun intended) JEP 158 , then we'll be happy to remove our conditional arguments.

I leave you the decision to decide if this issue can be closed as an "answered question", or if you would like to use it for future JEP 158 support.

Kind regards,
Alexandre

**Comment by pdbain-ibm** [comment]
@charliegracie Can we map `-Xlog:gc*` to an equivalent OpenJ9 option in the VM argument processing code?
Even if it doesn't give exactly the same result, it avoids a launch error.

**Comment by fjeremic** [comment]
> @charliegracie Can we map `-Xlog:gc*` to an equivalent OpenJ9 option in the VM argument processing code?

Not a fan of that because JEP 158 explicitly defines a structure output format, and if we output anything with `-Xlog` it should be in the same format, otherwise existing tools which rely on this will break.

**Comment by DanHeidinga** [comment]
Closing this as the question has been answered.  OpenJ9 doesn't intend to implement JEP 158 at this time.
