### ISSUE TITLE
Investigate increase in ResolvedMethod_getClassFromConstantPool messages

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#4001]
After the latest marge of master into jitaas we saw that CPU consumption increased 2-3% and that ResolvedMethod_getClassFromConstantPool messages increased 4 times, becoming the most frequent type of message.
This issue will investigate the reason for such an increase.

**Comment by mpirvu** [comment]
@satbir-ca could you please investigate this issue? Thanks

**Comment by satbir-ca** [comment]
I am using the java -version for testing.
 
Total messages send  - >3635

1. TR_J9ByteCodeIlGenerator::walker-> TR_J9ByteCodeIlGenerator::genNew -> TR_J9ByteCodeIlGenerator::loadClassObject  -->  ResolvedMethod_getClassFromConstantPool --> 1094

2. J9::TransformUtil::foldReliableStaticFinalField -> J9::TransformUtil::canFoldStaticFinalField -> getClassFromFieldOrStatic --> ResolvedMethod_getClassFromConstantPool  -->> 2233

3. TR_J9ByteCodeIlGenerator::walker  --> TR_J9ByteCodeIlGenerator::genCheckCast --> TR_J9ByteCodeIlGenerator::loadClassObjectForTypeTest --> ResolvedMethod_getClassFromConstantPool -->> 254

4. TR_J9ByteCodeIlGenerator::walker --> TR_J9ByteCodeIlGenerator::loadFromCP --> TR_J9ByteCodeIlGenerator::loadClassObjectAndIndirect --> ResolvedMethod_getClassFromConstantPool -->> 48

5. TR_LoopVersioner::collectAllExpressionsToBeChecked --> ResolvedMethod_getClassFromConstantPool -->> 6

**Comment by mpirvu** [comment]
I hope that this very small test doesn't distort the information.
Since most of the messages come from J9::TransformUtil::foldReliableStaticFinalField which has been recently changed (refactored) can we generate the same stats with an older build and compare. In principle code refactoring should not increase the number of messages.

**Comment by dmitry-ten** [comment]
Isn't this because we enabled final static field folding?
If I remember correctly, we used to always return false at the beginning of `transformDirectLoad`, so `canFoldStaticFinalField` would never get called.

**Comment by mpirvu** [comment]
Good point. That settles the issue.

**Comment by mpirvu** [comment]
I reopened the issue because of the following piece of code
```
   if (J9::TransformUtil::canFoldStaticFinalField(comp, node) == TR_yes)
      {
      return J9::TransformUtil::foldStaticFinalFieldImpl(comp, node);
      }
```
Most messages come from `canFoldStaticFinalField` folding, but the code that was changed when we enabled static final field folding in #3220 was in `J9::TransformUtil::foldStaticFinalFieldImpl(comp, node);`

**Comment by dmitry-ten** [comment]
`foldStaticFinalFieldImpl` and `canFoldStaticFinalField` got added in #3159, the code they contain used to be inside `transformDirectLoad`.

**Comment by mpirvu** [comment]
I better understand the issue now, so closing it. Satbir will work on implement some caching.
