### ISSUE TITLE
OpenJ9 build fails to tar OpenJDK8 images output

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#401]
The OpenJDK8 images output JDK directory is a different name to JDK9, see job:
https://urv-jenkins.canlab.ibm.com:9095/view/OpenJ9/job/openj9.personal/158/console

The build tar script for OpenJKD8 needs to specify "j2sdk-image" instead of the "jdk" directory, error:
06:28:49 [pLinux] + date +%Y%d%m%H%M
06:28:49 [pLinux] + tar -zcvf OpenJ9-linux-ppc64le-normal-server-release-201718100609.tar.gz jdk
06:28:49 [pLinux] tar: jdk: Cannot stat: No such file or directory

**Comment by jdekonin** [comment]
This appears to be internal to IBM for how openj9 is being built.  I suggest opening against an internal process.

**Comment by pshipton** [comment]
Closing since this isn't an OpenJ9 problem.
