### ISSUE TITLE
JTReg test fail - Windows : java/net/httpclient/ssltest/CertificateTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4053]
The test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/net/httpclient/ssltest/CertificateTest.java fails on Windows with a coredump ...
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFAFBD4B96B ContextFlags=0010005f
Handler1=00007FFAFBDC60C0 Handler2=00007FFAFDC3ECA0 InaccessibleReadAddress=0000000099669976
RDI=000000269DCD1A06 RSI=0000000099669966 RAX=0000000099669966 RBX=0000000000390B20
RCX=04F26C0C13670000 RDX=0000000000000000 R8=000000269DCD0B78 R9=0000000002040002
R10=0000000000000013 R11=000000269E5CEF50 R12=000000000032A100 R13=0000000000390E00
R14=0000000000390B20 R15=000000269DCD15F7
RIP=00007FFAFBD4B96B RSP=000000269E5CF2E0 RBP=000000269E5CF6A0 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000390b80 (f: 3738496.000000, d: 1.847062e-317)
XMM1 000000269e5cf720 (f: 2656892672.000000, d: 8.194852e-313)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 00000000000001b0 (f: 432.000000, d: 2.134364e-321)
XMM6 000000269e5cf700 (f: 2656892672.000000, d: 8.194852e-313)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\Users\jenkins\workspace\Grinder\openjdkbinary\j2sdk-image\bin\compressedrefs\j9vm29.dll
Module_base_address=00007FFAFBD40000 Offset_in_DLL=000000000000b96b
Target=2_90_20181115_19 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (2 logical CPUs) (0xfff8d000 RAM)
----------- Stack Backtrace -----------
(0x00007FFAFBD4B96B [j9vm29+0xb96b])
(0x00000000003910F8)
(0x000000269E5CF6A0)
(0x0000000000390B30)
(0x0000000000000011)
---------------------------------------
```

This occurs very infrequently (2 in 100 runs in job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/581/consoleFull).

No such issue has been observed on Linux.

I've kicked off a repeat of the 100 iteration run requesting the workspace be kept (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/598) which should hopefully provide access to the coredump files once it has completed (assuming consistent failure rate).

**Comment by ben-walsh** [comment]
1 of the 100 run in the job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/600 produced a coredump. This should be present in the kept workspace.

**Comment by dmitripivkine** [comment]
There is `InaccessibleReadAddress=0000000099669976` and `RAX=0000000099669966`contain J9class eye catcher. So most likely j9class is treated as an object somewhere and this is an attempt to read slot `superclasses` from j9class

**Comment by ben-walsh** [comment]
Seems KEEP_WORKSPACE parameter doesn't work as I expected. Stewart created a modified grinder job to test with, which should hopefully keep the coredumps. Running same parameters with this - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/7

**Comment by pdbain-ibm** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/11 is no longer available. @ben-walsh did you have a chance to look at the results?

**Comment by ben-walsh** [comment]
Afraid not. I've kicked off an equivalent here - https://ci.adoptopenjdk.net/view/work in progress/job/SXA-BenWalsh-Grinder/15

**Comment by JasonFengJ9** [comment]
Re-enabled the test at https://github.com/AdoptOpenJDK/openjdk-tests/pull/1126.
