### ISSUE TITLE
JTReg test fail - Windows : java/net/httpclient/InvalidInputStreamSubscriptionRequest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4054]
The test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/net/httpclient/InvalidInputStreamSubscriptionRequest.java fails on Windows with a coredump ...
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFAFBD4B96B ContextFlags=0010005f
Handler1=00007FFAFBDC60C0 Handler2=00007FFAFDC3ECA0 InaccessibleReadAddress=0000000099669976
RDI=000000E499420672 RSI=0000000099669966 RAX=0000000099669966 RBX=0000000000402710
RCX=4B19E742A3340000 RDX=0000000000000000 R8=000000E49941FC40 R9=0000000000040022
R10=000000000000000C R11=000000E499E3EA60 R12=0000000000000001 R13=0000000000402A00
R14=0000000000402710 R15=0000000000000011
RIP=00007FFAFBD4B96B RSP=000000E499E3EDF0 RBP=000000E499E3F1B0 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000006 (f: 6.000000, d: 2.964394e-323)
XMM1 000000e499e3f230 (f: 2581852672.000000, d: 4.850906e-312)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6 000000e499e3f210 (f: 2581852672.000000, d: 4.850906e-312)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\Users\jenkins\workspace\Grinder\openjdkbinary\j2sdk-image\bin\compressedrefs\j9vm29.dll
Module_base_address=00007FFAFBD40000 Offset_in_DLL=000000000000b96b
Target=2_90_20181115_19 (Windows Server 2012 R2 6.3 build 9600)
CPU=amd64 (2 logical CPUs) (0xfff8d000 RAM)
----------- Stack Backtrace -----------
(0x00007FFAFBD4B96B [j9vm29+0xb96b])
(0x0000000000402CF8)
(0x000000E499E3F1B0)
(0x00000000004026C0)
(0x0000000000000011)
---------------------------------------
```

This occurs very infrequently (1 in 100 runs in job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/589/consoleFull).

No such issue has been observed on Linux.

I've kicked off a repeat of the 100 iteration run requesting the workspace be kept (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/599) which should hopefully provide access to the coredump files once it has completed (assuming consistent failure rate).

**Comment by ben-walsh** [comment]
KEEP_WORKSPACE doesn't work as expected. Rerunning using modified test grinder to hopefully obtain the coredumps - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/8

**Comment by smlambert** [comment]
test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/744

**Comment by ben-walsh** [comment]
3/100 failure rate observed with job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/8. Successfully obtained coredump files - available here - https://ibm.box.com/s/krord0wa2egbrxu30ww2du0b0z1zicxg

**Comment by pdbain-ibm** [comment]
@ben-walsh 
Would you  please retest this with `-Xint`?
Thank you
         -p

**Comment by ben-walsh** [comment]
@pdbain-ibm I've kicked off https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/790 to cover your request in https://github.com/eclipse/openj9/issues/4054#issuecomment-453143281. Given the low observed failure rate to date, I've made it a 400x rather than 100x.

**Comment by pdbain-ibm** [comment]
No failures so far.  @ben-walsh can you launch another large build?

**Comment by ben-walsh** [comment]
@pdbain-ibm 
Looks like there were 5 failures in before some infrastructure problem ended the job (search for "jdk_custom_0_FAILED" to find them).
I've kicked off a repeat of the job (this time archiving the core dump files etc ...) - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-BenWalsh-Grinder/16

**Comment by pdbain-ibm** [comment]
Fails with -Xint.

**Comment by JasonFengJ9** [comment]
Re-enabled the test at https://github.com/AdoptOpenJDK/openjdk-tests/pull/1126.
