### ISSUE TITLE
Discuss changing xlinux Jenkins machines to RHEL/CentOS 6 instead of Ubuntu 16

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#4063]
Currently, our Softlayer Linux x86-64 machines are Ubuntu 16.04. These have a glibc level of 2.23. Generally we try and compile on the lowest glibc level so our binaries will run across all supported OSs. While OpenJ9 does not ship it's own binaries, developers still occasionally pull builds from the CI server for further testing and investigation.

RHEL 6 or CentOS 6 has a glibc level of 2.12. This is the lowest level across our supported OSs. Switching our build machines to one of these OSs will align with the AdoptOpenJDK binaries as well as IBM Java.

We currently have an opportunity to change the OS for these machines because we are creating new VMs using the new UNB hardware. Depending on capacity, it is still worth having more than one flavour of OS for test purposes, but compiles would be limited to the lowest OS level we have in the farm.

Are there any objections, questions, or concerns?

cc @jdekonin @cwillhelm

**Comment by pshipton** [comment]
@DanHeidinga @andrewcraik 

Seems fine to me, as long as the compiler levels remain the same.

**Comment by DanHeidinga** [comment]
> it is still worth having more than one flavour of OS for test purposes, but compiles would be limited to the lowest OS level we have in the farm.

* Will this segregate our machines into two pools: build, & test?
* Will all the CentOS 6 build machines be located at UNB?  How does this effect the network traffic to / from UNB given we don't wan to monopolize their pipe.  Question may be moot unless we have other pools of machines as the intention is to give back the Softlayer linux machines once we're transitioned to the UNB machines.
* Is the intention to change the other linux platforms (p, z) to use CentOS 6 as well?

Overall, +1 to the idea of using consistent build environments across OpenJ9 and Adopt builds.

**Comment by andrewcraik** [comment]
A consistent environment seems like a very good idea to me. How are we picking the OSes for the test pool? Too much breadth may reduce reproducibility...

**Comment by AdamBrousseau** [comment]
>segregate our machines into two pools

Yes, Build & Test and Test only
> Will all the CentOS 6 build machines be located at UNB?

My understanding was once UNB machines are stable and at minimum capacity we would return the Softlayer (UB16) machines. Network traffic would be unaffected unless we were to have machines not at UNB, then the jobs that land outside UNB would reduce the UNB traffic.

>change the other linux platforms (p, z) to use CentOS 6 as well?

We sent a Power server to UNB, so we could move those compiles to Cent7 once we start creating those images. Cent is not supported on s390x. We would have to look at RHEL licensing if we wanted to move from UB16 to RHEL7. Adopt uses Cent 7.4 for ppcle and RHEL 7.4 for s390x.
>How are we picking the OSes for the test pool

Keep in mind, we would only create "test only" machines if the value of different OS testing outweighed the need for more compile machines. I think we can discuss OS coverage if/when we start down that road. (cc @smlambert )

**Comment by mleipe** [comment]
> these will be the same as the build env at Adopt

Yes, the goal is to use the Ansible playbooks from Adopt to configure machines at Eclipse OpenJ9, too.

**Comment by vsebe** [comment]
I've configured a centos6 node: https://ci.eclipse.org/openj9/computer/cent6-x86-1/
All builds passed:
https://ci.eclipse.org/openj9/job/Build-JDK8-linux_x86-64_cmprssptrs/1159/
https://ci.eclipse.org/openj9/job/Build-JDK11-linux_x86-64_cmprssptrs/746/
https://ci.eclipse.org/openj9/job/Build-JDK12-linux_x86-64_cmprssptrs/48/
Tests in progress:
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/226/

**Comment by pshipton** [comment]
Note we'll want to test all the suites
- sanity.functional
- extended.functional
- sanity.system - running above
- extended.system

**Comment by vsebe** [comment]
(waiting for next executor)
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/219/
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/219/
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/653/

**Comment by vsebe** [comment]
`cmdLineTester_CryptoTest_0`  failed - see https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/656/ (fails when using the default openssl package for CentOS 6 - OpenSSL 1.0.1e-fips 11 Feb 2013.
Installed openssl 1.1.1, test passed: https://ci.eclipse.org/openj9/view/Test_grinder/job/Test-Grinder/361/

**Comment by vsebe** [comment]
`SharedClasses.SCM01.MultiThread_0` passed in grinder - https://ci.eclipse.org/openj9/view/Test_grinder/job/Test-Grinder/362/
Relaunched [Test-extended.system-JDK11-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/229/console) - in progress

**Comment by vsebe** [comment]
All tests suites for JDK11 passed.

**Comment by vsebe** [comment]
Build and tests passed for JDK8 too: https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-linux_x86-64_cmprssptrs/895/console

**Comment by vsebe** [comment]
@pshipton  fyi
There are 7 CentOS 6 machines available: https://ci.eclipse.org/openj9/label/sw.os.cent.6%20&&%20ci.role.test/
For now they are configured to run tests.

**Comment by AdamBrousseau** [comment]
The SDKs won't run on these because they're still compiled on Ubuntu 16.

**Comment by pshipton** [comment]
> The SDKs won't run on these because they're still compiled on Ubuntu 16.

Right. @vsebe if we are ready to switch, we'll have to make these CentOS machines the only build machines, and the Ubuntu machines test machines. So we don't loose a night of testing, we should schedule this with enough time remaining in the day to go through some tests, and revert by EOD if there are problems.

**Comment by jdekonin** [comment]
This work was completed.  The issue can close.
