### ISSUE TITLE
The jdk12 extensions repo is created, add support for builds

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4065]
https://github.com/ibmruntimes/openj9-openjdk-jdk12 is created, support for builds is required.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
OpenJ9 pull requests for JDK12 created and verified functional.

**Comment by jdekonin** [comment]
OpenJDK12 extensions pull request job created and verified functional.  Triggers tested via https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/17

Copyright, LineEndingsCheck and SignedOffByCheck for JDK12 were created under a different issue.

I believe this can be closed.
