### ISSUE TITLE
No functionality PR builds for osx jdk8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4080]
It seems there are no funtionality PR builds for osx jdk8. i.e. https://github.com/eclipse/openj9/pull/4079#issuecomment-447992461

As osx jdk8 is a target for the 0.12.0 release, having PR builds is required to ensure that changes are good.

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
They were there, stopped triggering at one point for some reason. Re-save seemed to do the trick,

**Comment by pshipton** [comment]
The sanity tests are not running, just the compile. See https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-osx_x86-64_cmprssptrs-OpenJ9/37/console

**Comment by AdamBrousseau** [comment]
Fixed. TEST_TARGET was missed when the job was added.
