### ISSUE TITLE
"jenkins compile plinux jdk8" not working

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4117]
Tried to compile plinux jdk8 in https://github.com/eclipse/openj9/pull/4115 but no PR build is started.

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
See #4017 . I can temporarily fix the job shortly and relaunch.

**Comment by AdamBrousseau** [comment]
>temporarily fix the job and relaunch

Done
