### ISSUE TITLE
aix build machine compile issues

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4120]
https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/42/
aix71-p8-4
https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/44
aix71-p8-1
```
11:49:28 Creating images/lib/jconsole.jar
11:50:03 gmake[2]: *** virtual memory exhausted.  Stop.
11:50:03 gmake[2]: *** Waiting for unfinished jobs....
11:50:03 gmake[2]: *** virtual memory exhausted.  Stop.
11:50:03 gmake[1]: *** [BuildJdk.gmk:106: images] Error 2
11:50:03 gmake[1]: INTERNAL: Exiting with 6 jobserver tokens available; should be 8!
11:50:03 make: *** [/home/u0020236/workspace/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs-OpenJ9//make/Main.gmk:141: images-only] Error 2
```

https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/43
aix71-p8-2
```
13:23:14 Building lib/uma.jar
13:23:16 J9VM version: ad53cf012
13:23:16 #
13:23:16 # A fatal error has been detected by the Java Runtime Environment:
13:23:16 #
13:23:16 #  SIGBUS (0xa) at pc=0x000000000000e898, pid=9961620, tid=258
13:23:16 #
13:23:16 # JRE version:  (7.0) (build )
13:23:16 # Java VM: OpenJDK 64-Bit Server VM (24.95-b00 mixed mode aix-ppc64 compressed oops)
13:23:16 # Problematic frame:
13:23:16 # C  0x000000000000e898
13:23:16 #
13:23:16 # Core dump written. Default location: /home/u0020236/workspace/PullRequest-Compile-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/build/aix-ppc64-normal-server-release/vm/core or core.9961620
```

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Heppened again, disabled aix71-p8-2

**Comment by pshipton** [comment]
Not sure about the `virtual memory exhausted` problem. For a minute I was thinking it is related to the change in #4115 to use openssl 1.1.1a, but then remember that AIX doesn't enable openssl.

**Comment by pshipton** [comment]
Seems the `virtual memory exhausted` problem is due to the jdk8 extensions merging in jdk8u202-b1.

**Comment by pshipton** [comment]
@pdbain-ibm you can use this Issue for your investigation.

**Comment by AdamBrousseau** [comment]
What does configure report when `--with-jobs` isn't supplied. The answer may be different for different jdk versions too. Iirc we added it because the openjdk source couldn't figure out AIX smt correctly?

**Comment by pshipton** [comment]
@pdbain-ibm please confirm you are building jdk8 and using the latest jdk8 extensions.

**Comment by jdekonin** [comment]
@pdbain-ibm does this mean this issue is resolved with newer content?  Can the machine be made available to jenkins again?

**Comment by pdbain-ibm** [comment]
@jdekonin 
I suspect we need either to reduce the number of parallel jobs or increase the memory limit.

**Comment by jdekonin** [comment]
Machine configuration was fine for months, and there hasn't been any changes to the AIX configuration/setup that I am aware of.  Is there something in the content that changed that might have this impact?   Would the jvm default change have any impact on this?  Or the recent additions to the extensions repo?

**Comment by jdekonin** [comment]
All the machines are of the same configuration.  I think is just going to be a matter of time before the same type of failure(s) occur on the currently enabled machines.

**Comment by pshipton** [comment]
Julian told me the workaround for the `virtual memory exhausted.` problem is as follows:
`export LDR_CNTRL=MAXDATA=0x80000000`

@jdekonin can you please add this to the machine configurations so we can see if this resolves the build problem.

**Comment by pshipton** [comment]
and @jdekonin see https://github.com/eclipse/openj9/issues/4120#issuecomment-448993288

**Comment by jdekonin** [comment]
Testing with the option added still fails.
https://ci.eclipse.org/openj9/view/Build/job/Build-JDK8-aix_ppc-64_cmprssptrs/931/consoleFull

**Comment by sxa555** [comment]
FYI We already use that variable at adoptopenjdk https://github.com/AdoptOpenJDK/openjdk-build/blob/2032638c3e281cd0e13032e1b5c927b94aca86a0/build-farm/platform-specific-configurations/aix.sh#L57

**Comment by jdekonin** [comment]
I made it on the machine side, and I can see both the jenkins job and direct logon having the env var set.  I'll try add it to the job as part of the cmdln and see what happens.

**Comment by pshipton** [comment]
Fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/237
