### ISSUE TITLE
 JTreg test fail - MacOS : java/util/prefs/ExportSubtree.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4130]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/util/prefs/ExportSubtree.java fails consistently on MacOS with ...

```
04:50:29.580 0xce8a200    j9vm.228    *   ** ASSERTION FAILED ** at VMAccess.cpp:352: (0 == ((vmThread)->publicFlags & J9_PUBLIC_FLAGS_VM_ACCESS))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/12/19 20:50:29 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/core.20181219.205029.62853.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 62854 was not found. Expected to find core file with name "/cores/core.62854"
JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/javacore.20181219.205029.62853.0002.txt' in response to an event
JVMDUMP010I Java dump written to /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/javacore.20181219.205029.62853.0002.txt
JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/Snap.20181219.205029.62853.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/Snap.20181219.205029.62853.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```

Example job showing failure - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/608/consoleText

**Comment by ben-walsh** [comment]
I've kicked off job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/15/ to try to obtain the dump files.

**Comment by pdbain-ibm** [comment]
I'll take a look.

**Comment by smlambert** [comment]
test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/768

**Comment by pdbain-ibm** [comment]
From the javacore:

> 1XMCURTHDINFO  Current thread
> 3XMTHREADINFO      "main" J9VMThread:0x00000000049ACA00, omrthread_t:0x00007F8ACD813A50, java/lang/Thread:0x000000070004F5B0, state:R, prio=5
> 3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
> 3XMTHREADINFO1            (native thread ID:0x2D3FA2, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
> 3XMTHREADINFO2            (native stack address range from:0x00000000B0080000, to:0x00000000B0100000, size:0x80000)
> 3XMCPUTIME               CPU usage total: 1.260100000 secs, current category="Application"
> 3XMHEAPALLOC             Heap bytes allocated since last GC cycle=566344 (0x8A448)
> 3XMTHREADINFO3           Java callstack:
> 4XESTACKTRACE                at java/util/prefs/MacOSXPreferencesFile.getKeysForNode(Native Method)
> 4XESTACKTRACE                at java/util/prefs/MacOSXPreferencesFile.getKeysForNode(MacOSXPreferencesFile.java:433)
> 5XESTACKTRACE                   (entered lock: java/util/prefs/MacOSXPreferencesFile@0x00000007004217C8, entry count: 1)
> 4XESTACKTRACE                at java/util/prefs/MacOSXPreferences.keysSpi(MacOSXPreferences.java:206)
> 4XESTACKTRACE                at java/util/prefs/AbstractPreferences.keys(AbstractPreferences.java:731)
> 5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000007FFE37108, entry count: 2)
> 4XESTACKTRACE                at java/util/prefs/XmlSupport.putPreferencesInXml(XmlSupport.java:155)
> 

`** ASSERTION FAILED ** at VMAccess.cpp:352: (0 == ((vmThread)->publicFlags & J9_PUBLIC_FLAGS_VM_ACCESS))`

Line 352 is: 

> void   internalAcquireVMAccessNoMutexWithMask(J9VMThread * vmThread, UDATA haltMask)
> {
> ...
> 	if (vm->extendedRuntimeFlags & J9_EXTENDED_RUNTIME_DEBUG_VM_ACCESS) {
> 		Assert_VM_true(currentVMThread(vm) == vmThread);
> 	}
> 	Assert_VM_mustNotHaveVMAccess(vmThread);  <<<<< line 352
>

**Comment by pdbain-ibm** [comment]
Condensed to a minimal test case:

> import java.util.prefs.Preferences;
> public class exp {
> 	public static void main(String[] args) {
> 		System.err.println("PDB_DEBUG exportSubtree");
> 		try {
> 			Preferences.userRoot().exportSubtree(System.out);
> 		} catch (Exception e) {}
> 		System.err.println("PDB_DEBUG exit");
> 	} 
> }

**Comment by pdbain-ibm** [comment]
Exporting the `systemRoot` (which happens to be empty), causes no problems.

**Comment by pdbain-ibm** [comment]
I am fixing the assertion.

However, I ran the test with OpenJDK and it fails for a different reason:
```
$ ./jdk-11.0.1+13/bin/java ~/tfr/Expo*.java
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE preferences SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<preferences EXTERNAL_XML_VERSION="1.0">
  <root type="user">
    <map/>
    <node name="testExportSubtree">
      <map>
        <entry key="key2" value="value2"/>
      </map>
      <node name="test">
        <map>
          <entry key="key3" value="value3"/>
        </map>
      </node>
    </node>
  </root>
</preferences>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE preferences SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<preferences EXTERNAL_XML_VERSION="1.0">
  <root type="user">
    <map/>
    <node name="testExportSubtree">
      <map>
        <entry key="key2" value="value2"/>
      </map>
      <node name="test">
        <map>
          <entry key="key3" value="value3"/>
        </map>
      </node>
    </node>
  </root>
</preferences>
java.io.IOException: exportSubtree does not output expected result
	at ExportSubtree.main(ExportSubtree.java:48)
```
note `<?xml version="1.0" encoding="UTF-8" standalone="no"?>` vs `<?xml version="1.0" encoding="UTF-8"?>` (extra metadata).

**Comment by pdbain-ibm** [comment]
@sxa555 or @andrew-m-leonard could you raise the test issue mentioned in 
https://github.com/eclipse/openj9/issues/4130#issuecomment-450933059 in OpenJDK?

**Comment by andrew-m-leonard** [comment]
@pdbain-ibm could you raise an issue on our board following this template please: https://ibm.ent.box.com/notes/350032081728
thanks

**Comment by ben-walsh** [comment]
Delay re-enable of test until https://github.ibm.com/runtimes/openjdk-contribution/issues/717 resolved.

**Comment by pdbain-ibm** [comment]
@ben-walsh The test may pass if it is run via the makefile: I noticed the incorrect behaviour when I ran it from the command line.

**Comment by pdbain** [comment]
@smlambert or @llxia would you please re-enable this test when the OpenJDK fix mentioned in https://github.ibm.com/runtimes/openjdk-contribution/issues/717#issuecomment-9694458 is available.
Thank you.

**Comment by llxia** [comment]
@pdbain-ibm PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/840 is created to re-enable the test. 

We are using [ProblemList* ](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/openjdk_regression) to exclude openjdk regression tests. Please feel free to modify them as needed. Thanks :)
