### ISSUE TITLE
Some functional tests don't compile on non-openj9 JVMs

### ISSUE THREAD

**Issue by jerboaa** [eclipse/openj9#4131]
I've been directed here from AdoptOpenJDK which uses some openj9 tests. Not all of them seem to compile on non-openj9 JVMs. I'm on Fedora 28 with package `java-1.8.0-openjdk-devel` installed.

Steps to reproduce:

    $ git clone https://github.com/AdoptOpenJDK/openjdk-tests
    $ cd openjdk-tests
    $ TEST_DIR="do-tests"
    $ mkdir $TEST_DIR && ./get.sh -t $TEST_DIR -p x64_linux -j SE80 -i hotspot -R latest -T jdk
    $ export JAVA_BIN=/usr/lib/jvm/java-1.8.0-openjdk/jre/bin
    $ export SPEC=linux_x86-64
    $ export JDK_IMPL=hotspot
    $ ./maketest.sh $TEST_DIR

Fails with:

```
    [javac]   symbol:   variable J9BuildFlags
    [javac]   location: class DumpSegmentsVM29
    [javac] /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/openjdk-tests/do-tests/functional/DDR_Test/src/j9vm/test/ddrext/plugin/dumpsegments/DumpSegmentsVM29.java:242: error: cannot find symbol
    [javac] 					reportObjectRegion(region, start, end, subspace, type, size, addr, out, J9BuildFlags.env_data64);
    [javac] 					                                                                        ^
    [javac]   symbol:   variable J9BuildFlags
    [javac]   location: class DumpSegmentsVM29
    [javac] 100 errors

BUILD FAILED
/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/openjdk-tests/do-tests/TestConfig/scripts/build_test.xml:71: The following error occurred while executing this line:
/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/openjdk-tests/do-tests/functional/build.xml:52: The following error occurred while executing this line:
/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/openjdk-tests/do-tests/functional/DDR_Test/build.xml:113: The following error occurred while executing this line:
/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/openjdk-tests/do-tests/functional/DDR_Test/build.xml:59: Compile failed; see the compiler error output for details.
```

**Comment by DanHeidinga** [comment]
FYI @smlambert @llxia

**Comment by smlambert** [comment]
Thanks @jerboaa - I will paste some of my comments from the Adopt testing slack channel here:

Essentially, we have this scenario:
1) openjdk tests were initially created to test a hotspot impl (so some tests need to be excluded to be used against openj9, which we have almost finished doing, some work still needed for jdk11)

2) functional tests were initially created to test an openj9 impl (we have not done the work yet to make the entire suite useful for a hotspot impl, but it is in plan - as in we will attempt to address this issue in the near-term/early 2019)

These 2 test groups (openjdk and functional) have some overlap, tests that test the same functionality, but some pieces that are quite different.  We have an work item to get code coverage builds running, which should better show the overlap and gaps, and help us focus our efforts in the right places to fill any remaining gaps.

**Comment by llxia** [comment]
With PR https://github.com/eclipse/openj9/pull/6001, functional tests are tagged with proper impls and should be able to run against non-openj9 JVMs.

**Comment by jerboaa** [comment]
Thanks, @llxia.
