### ISSUE TITLE
Investigate possible native stack space optimizations

### ISSUE THREAD

**Issue by gacholio** [eclipse/openj9#4134]
The interpreter entrypoints (like sendClinit, etc) all take 5 arguments, which is a leftover from the builder days when those calls created the interpreter stack frame. This is certainly no longer necessary.

Also worth looking at is the 32-slot reserved outgoing argument area on various architectures. The interpreter no longer needs this (JNI calls are performed using libffi which builds its own stack frames as required).

**Comment by gacholio** [comment]
@gita-omr @fjeremic @JamesKingdon 

Does your plarform's direct JNI depend on any more than the mandatory argument slots in the native stack frame?

For reference, the interpreter stack frame is defined here:

https://github.com/eclipse/openj9/blob/1e7ab9b2abe374133f3f0d98c0160b9711eb3f30/runtime/oti/j9nonbuilder.h#L5547

**Comment by fjeremic** [comment]
> Does your plarform's direct JNI depend on any more than the mandatory argument slots in the native stack frame?

The work on Z happens in [1]. Not exactly sure what you mean by "depend on any more"? Could you clarify this exactly? JNI linkage is very similar to system linkage. We only need to perform a few extra things like stack switching. Subscribing @NigelYiboYu here as well since he did the Atomic-free JNI work on Z and did a ton of refactoring in this area.

[1] https://github.com/eclipse/openj9/blob/b5587e76d9709d8563375c320d46356773ee79bc/runtime/compiler/z/codegen/J9S390PrivateLinkage.cpp#L2862-L3116

**Comment by DanHeidinga** [comment]
@fjeremic Does Z always buy a stack frame and spill space for the JNI args or does it rely on the "extra" space in the primordial stack frame?

**Comment by fjeremic** [comment]
> @fjeremic Does Z always buy a stack frame and spill space for the JNI args or does it rely on the "extra" space in the primordial stack frame?

Just generated a short Linux JNI dispatch sequence with 8 arguments. Here is what I see in the trace:

```
------------------------------
 n23n     (  0)  treetop                                                                              [0x78a04098] bci=[-1,25,22] rc=0 vc=177 vn=- li=2 udi=- nc=1
 n22n     (  1)    acall  Sample1.stringMethod(Ljava/lang/String;IIIIIII)Ljava/lang/String;[#693  native virtual Method -28] [flags 0x500 0x0 ] (in &GPR_0174) (sharedMemory )  [0x78a04058]
 n259n    (  0)      loadaddr  <auto slot 0>[#625  Auto] [flags 0x4007 0x0 ] (in GPR_0170) (X!=0 nodePointsToNonNull sharedMemory )  [0x78a83080] bci=[-1,13,22] rc=0 vc=177 vn=- li=2 udi=30 n261n    (  0)      loadaddr  <temp slot 3>[#694  Auto] [flags 0x4007 0x0 ] (in GPR_0171) (X!=0 nodePointsToNonNull sharedMemory )  [0x78a83100] bci=[-1,14,22] rc=0 vc=177 vn=- li=2 udi=30 n14n     (  0)      iconst 1 (in GPR_0172) (X!=0 X>=0 )                                              [0x78a03e58] bci=[-1,16,22] rc=0 vc=177 vn=- li=2 udi=30902 nc=0 flg=0x104
 n15n     (  0)      iconst 2 (in GPR_0173) (X!=0 X>=0 )                                              [0x78a03e98] bci=[-1,17,22] rc=0 vc=177 vn=- li=2 udi=30902 nc=0 flg=0x104
 n16n     (  0)      iconst 3 (X!=0 X>=0 )                                                            [0x78a03ed8] bci=[-1,18,22] rc=0 vc=177 vn=- li=2 udi=- nc=0 flg=0x104
 n17n     (  0)      iconst 4 (X!=0 X>=0 )                                                            [0x78a03f18] bci=[-1,19,22] rc=0 vc=177 vn=- li=2 udi=- nc=0 flg=0x104
 n18n     (  0)      iconst 5 (X!=0 X>=0 )                                                            [0x78a03f58] bci=[-1,20,22] rc=0 vc=177 vn=- li=2 udi=- nc=0 flg=0x104
 n19n     (  0)      iconst 6 (X!=0 X>=0 )                                                            [0x78a03f98] bci=[-1,21,22] rc=0 vc=177 vn=- li=2 udi=- nc=0 flg=0x104
 n20n     (  0)      iconst 7 (X!=0 X>=0 )                                                            [0x78a03fd8] bci=[-1,23,22] rc=0 vc=177 vn=- li=2 udi=- nc=0 flg=0x104
------------------------------

 [0x78b6ea50]   LR      GPR_0166,GPR13
 [0x78b6eb80]   LARL    GPR_0168, &<LiteralPool Base Address>    ; LoadLitPool
 [0x78b6ed30]   LA      GPR_0170, Auto[<auto slot 0>] ?+0(GPR5)
 [0x78b6ee50]   LA      GPR_0171, Auto[<temp slot 3>] ?+0(GPR5)
 [0x78b6ef20]   LHI     GPR_0172,0x1
 [0x78b6f000]   LHI     GPR_0173,0x2
 [0x78b6f110]   MVHI    #703 96(GPR15),0x0003
 [0x78b6f220]   MVHI    #704 100(GPR15),0x0004
 [0x78b6f330]   MVHI    #705 104(GPR15),0x0005
 [0x78b6f440]   MVHI    #706 108(GPR15),0x0006
 [0x78b6f550]   MVHI    #707 112(GPR15),0x0007
 [0x78b002b0]   LARL    GPR_0181, 0x78B00140
 [0x78b003d0]   LAY     GPR5,#708 -20(GPR5)
 [0x78b00550]   MVC     #709 20(12,GPR13),#710 20(GPR_0181)
 [0x78b00660]   ST      GPR5,#711 16(GPR13)
 [0x78b007e0]   MVC     #712 0(20,GPR5),#713 0(GPR_0181)
 [0x78b008f0]   MVHI    #714 1376(GPR13),0x0001
 [0x78b00a00]   L       GPR_0164,#715 76(GPR13)
 [0x78b00b00]   CIJ     GPR_0164,Snippet Label L0089,32,BNH(mask=0x6),
 [0x78b00c40]   Label L0090:
 [0x78b00d70]   L       GPR_0169,#716 40(GPR_0181)
 [0x78b00df0]   LR      GPR_0167,GPR_0171
 [0x78b00e80]   LR      GPR5,GPR_0172
 [0x78b00f10]   LR      GPR_0165,GPR_0168
 [0x78b00fa0]   LR      GPR_0168,GPR_0173
 [0x78b01330]   ASSOCREGS
  PRE:
 {GPR2:GPR_0166:R} {GPR3:GPR_0170:R} {GPR8:GPR_0171:R} {GPR9:GPR_0172:R} {GPR10:GPR_0173:R}
 [0x78b01030]   BASR    GPR_0169,GPR_0169       # Call "Sample1.stringMethod(Ljava/lang/String;IIIIIII)Ljava/lang/String;"
```

First few arguments go into registers, the last 5 arguments get stored directly onto the native stack (`GPR15`). I don't see us buying any stack frame here.

**Comment by gacholio** [comment]
The outgoing argument area on Z is not at the top (lowest address) of the fixed stack frame, so creating a new frame for the JNI call would be non-trivial.

Does Z perhaps decline to compile JNI calls that have more than 32 slots of arguments?  A search for `J9_INLINE_JNI_MAX_ARG_COUNT` in the JIT codebase has no hits, so if there is a restriction, it's magic not based on the VM constant.

**Comment by NigelYiboYu** [comment]
> Does Z perhaps decline to compile JNI calls that have more than 32 slots of arguments? 

I haven't seen any argument count restrictions on Z. So the answer is no.

**Comment by gacholio** [comment]
Found it:

https://github.com/eclipse/openj9/blob/4abcaf783a339440178b5c5b5c611a35dadd9c46/runtime/compiler/ilgen/IlGenerator.cpp#L1301

If nothing else, I'll update that magic 32 to be the defined constant.

**Comment by gacholio** [comment]
ARM and X do not have any reserved space in the C interpreter stack frame, so there may not be any more work to do here. The ILGenerator limit is unnecessary for these platforms (or at least, doesn't have to be the constant count). I'm not sure optimizing for native calls with more than 32 arguments has any real-world value.

**Comment by gita-omr** [comment]
I recall we needed more than 32 arguments for GPU work (calling CUDA runtime functions from JIT) and we had to go out of our way to put them somewhere else...

**Comment by gacholio** [comment]
No more work to be done at the moment.
