### ISSUE TITLE
Out of space on Windows jenkins node

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4151]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-win_x86-64_cmprssptrs-OpenJDK11/8
Running on win2012r2-x86-3
Took node offline.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
There was an extensions pull request job that left a 31G directory behind.  Its been cleaned up and the machine has been added back into service.

**Comment by jdekonin** [comment]
This can be closed @pshipton
