### ISSUE TITLE
Ensure boolean JNI methods produce a result of zero or one on Z codegen

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#4162]
As part of #4086 we made a slight modification on the x86 codegen to comply with the Java spec on JNI methods which return boolean values. If we encounter such a method the only valid results should be 0 or 1 coming out of the method call and we must ensure this at the codegen level.

We need to port #4086 over to Z.

**Comment by fjeremic** [comment]
@NigelYiboYu since you are most familiar with the JNI implementation having done some work there recently could you please take a look at this one as well?

**Comment by fjeremic** [comment]
@NigelYiboYu this is slated for 0.13.0, could you prioritize it accordingly?

**Comment by NigelYiboYu** [comment]
OK. Making it my first priority now.

**Comment by NigelYiboYu** [comment]
Pull request: https://github.com/eclipse/openj9/pull/4724
I'm currently running tests.
