### ISSUE TITLE
JTreg test fail - MacOS : java/lang/System/OsVersionTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4188]
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/System/OsVersionTest.java is failing with the following ...

```
java.lang.Error: 14.5.0 != 10.10.5
	at OsVersionTest.main(OsVersionTest.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Running the latest 11 release levels of Hotspot and OpenJ9 on my local mac machine (running 10.13.6 according to "About This Mac") shows ...

```
bens-mbp:~ ben_walsh@uk.ibm.com$ cat Test.java
public class Test {

	public static void main(String[] args) {

		System.out.println(System.getProperty("os.version"));

	}

}
bens-mbp:~ ben_walsh@uk.ibm.com$ /Users/ben_walsh@uk.ibm.com/Downloads/openj9_11/jdk-11.0.1+13/Contents/Home/bin/javac Test.java
bens-mbp:~ ben_walsh@uk.ibm.com$ /Users/ben_walsh@uk.ibm.com/Downloads/hotspot_11/jdk-11.0.1+13/Contents/Home/bin/java Test
10.13.6
bens-mbp:~ ben_walsh@uk.ibm.com$ /Users/ben_walsh@uk.ibm.com/Downloads/openj9_11/jdk-11.0.1+13/Contents/Home/bin/java Test
17.7.0
bens-mbp:~ ben_walsh@uk.ibm.com$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

So it looks like Hotspot is using the Product Version value of the Mac OS installation it's executing on, while OpenJ9 is using the Darwin Version value of the Mac OS installation it's executing on.

**Comment by pdbain-ibm** [comment]
Looks related to https://github.com/eclipse/openj9/issues/3969.  I'll take a look.

**Comment by ben-walsh** [comment]
Agreed. Cancelling as duplicate of #3969. Should be fixed in nightlies going forwards.

**Comment by pdbain** [comment]
@ben-walsh issue 3969 is nominally closed as fixed.  Please re-open this while I investigate.

**Comment by ben-walsh** [comment]
@pdbain-ibm Okey dokey.
Reopening per Peter's request.

**Comment by pdbain-ibm** [comment]
@ben-walsh I can reproduce this issue with the "latest release".  Please retest with a recent nightly build.

**Comment by ben-walsh** [comment]
@pdbain-ibm
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/768 failed with ...
```
java.lang.Error: unknown != 10.10.5
	at OsVersionTest.main(OsVersionTest.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

From https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/System/OsVersionTest.java#L41 it looks like the behaviour is inconsistent between Mac OS X release levels. My local Mac laptop at 10.13.6 is fine but the Jenkins test machine at 10.10.5 is not.
What release level are you observing the failure on ?

**Comment by pdbain-ibm** [comment]
I am testing (using `java  -XshowSettings:properties HelloWorld 2>&1 | grep os.version`.
On my machine (High Sierra) I get `os.version = 10.13.6`  with both:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201901071909)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f8231edc8, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190107_82 (JIT enabled, AOT enabled)
OpenJ9   - f8231edc8
OMR      - 3c42fa79
JCL      - ab5eb2bc46 based on jdk-11.0.1+13)
```
and 
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)
```

**Comment by pdbain-ibm** [comment]
Reproduced on MacOS 10.10.5:
```
$ jdk-11.0.1+13/Contents/Home/bin/java -XshowSettings:properties -version 2>&1 | grep os.version
    os.version = unknown
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```

**Comment by pdbain-ibm** [comment]
MacOS 10.10.5 (Yosemite) does not have the `kern.osproductversion` key.

**Comment by smlambert** [comment]
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/813

**Comment by pdbain-ibm** [comment]
@smlambert I think this can be re-enabled.
