### ISSUE TITLE
Duplicate macros in j9const.h and j9nonbuilder.h

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#4198]
Beginner item

We have duplicate macros ie.

```
J9AccFinal
J9AccClassUnsafe
J9AccMethodFrameIteratorSkip
J9AccClassHotSwappedOut
```

and

```
J9_JAVA_FINAL
J9_JAVA_CLASS_UNSAFE
J9_JAVA_METHOD_FRAME_ITERATOR_SKIP
J9_JAVA_CLASS_HOT_SWAPPED_OUT
```

j9nonbuilder.h seems to more up to date so I suggest we keep that one and remove the j9consts.h equivalents.

**Comment by DanHeidinga** [comment]
Note, any change along these lines will also need to consider the DDR code as well.  The namespacing of constants may also be affected by this change.

**Comment by AidanHa** [comment]
I will be addressing this issue.

**Comment by AidanHa** [comment]
@tajila are these 4 the only duplicate macros, or is there a list of duplicate macros I can refer to?

**Comment by tajila** [comment]
There are more macros. I do not have a list but the duplicate ones will have the same name.

Take a look at j9consts.h line 260 - 308 and j9nonbuilder.h line 64 - 154

**Comment by AidanHa** [comment]
https://github.com/eclipse/openj9/pull/4283#issuecomment-454013744

@pdbain-ibm suggested to remove the j9nonbuilder.h equivalents. Thoughts? @tajila @DanHeidinga

**Comment by tajila** [comment]
I think thats fine, but it means that you'll have to change the `#includes` in a bunch of places as j9nonbuilder.h contains a lot of struct def'n, flags, contants, etc.  
  
I suggest doing this in phases, for this PR focus on removing the duplicate macros, just as you have done. In the next PR you can merge j9nonbuilder.h and j9conts.h into one file.

**Comment by AidanHa** [comment]
Hmm okay, for this PR, I will focus on removing the duplicates from j9consts.h. Eventually I will merge both files into 1 (in another PR).
