### ISSUE TITLE
Dockerfile for JDK11 installs gcc 7.4 by default

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#4208]
https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile

Default gcc7 on ubuntu16 is 7.4. Should we install gcc7.3 instead of default 7.4 from the package manager?

@pshipton

**Comment by AdamBrousseau** [comment]
@samuel-rubin as a good first issue, please update the Dockerfile(s) in the buildenv/docker/jdk11 directories to install gcc 7.3 instead of the default one from the package manager.
We should probably also check the ub16/390 Dockerfile used for the buildfarm containers
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/docker-slaves/s390x/ubuntu16/Dockerfile

**Comment by pshipton** [comment]
Using gcc 7.4 for s390/zlinux is fine. 7.4 is the desired level for zlinux, and it has already been verified for performance.

**Comment by AdamBrousseau** [comment]
Confirmed the Container for ub16/390 already has 7.4
https://hub.docker.com/r/eclipse/openj9-jenkins-agent-s390x-ubuntu16

**Comment by samuel-rubin** [comment]
The current repository for gcc-7 only holds onto the latest version which is currently 7.4.0. I also looked into Installing GCC 7.3 from the source but that took too long (over an hour). Something that we can do is copy the gcc binary from the AdoptOpenJDK jenkins like in #3864.

**Comment by samuel-rubin** [comment]
I am going to copy to copy the 7.3 binaries (and links so they work) to the ub16 machines on x86 and ppc64le. On ub18 for x86 and ppc64le, I am thinking of using the ubuntu repo and restricting the version to 7.3. On s390 containers and x86 centos7 container, I'm thinking of keeping the same method, but requiring the version the be 7.4. If the package updates, the docker build will fail.

**Comment by samuel-rubin** [comment]
Jenkins Docker files: 

|           | x86                   | s390x            | ppc64le               |
|-----------|-----------------------|------------------|-----------------------|
| Ubuntu16  | AdoptOpenJDK Binaries | Ubuntu toolchain | AdoptOpenJDK Binaries |
| Ubuntu18  | Ubuntu default        | Ubuntu toolchain | Ubuntu Default        |
| Centos6.9 | Centos devtoolset     | Not Available    | Not Available         |
| Centos7   | Not Available         | Not Available    | AdoptOpenJDK Binaries |

Developper Docker Files 

|          | x86                   | s390x            | ppc64le               |
|----------|-----------------------|------------------|-----------------------|
| Ubuntu16 | AdoptOpenJDK Binaries | Ubuntu toolchain | AdoptOpenJDK Binaries |

**Comment by samuel-rubin** [comment]
We have 2 types of Dockerfiles, Build & test and test only. For the build & test files, the default gcc is currently 4.8.5 and 7.3 is also available but it must be called explicitly. For the test only files we need to know what to install.
a) no gcc needed (all natives are compiled with the SDK)
b) exact same versions as the Build containers
c) something close is good enough (i.e. we can install 7.4 instead of 7.3 or vice versa)
d) something else

**Comment by samuel-rubin** [comment]
I can compile system tests in my test only docker image without gcc.

**Comment by samuel-rubin** [comment]
Here is my PR related to removing GCC from the test containers: #4474

**Comment by samuel-rubin** [comment]
I realized that my tests were flawed and that I did have gcc installed. The build-essentials package installs the default version of gcc on the system. Should I keep it like that or should we specify the version of GCC. I did not see any specification for the version of gcc in the testing repos.

**Comment by AdamBrousseau** [comment]
Depending on #5276, I think this can be closed?
