### ISSUE TITLE
Revert SharedClasses by default for both JDK8 & JDK11

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#4222]
@pshipton and @DanHeidinga I would like to propose reverting the "default shared classes" change for the 0.12 release. It does'nt seem like we would be able to fix the regression being investigated here and do the necessary performance testing on the fix in time for the 0.12 release.

_Originally posted by @vijaysun-omr in https://github.com/eclipse/openj9/issues/4205#issuecomment-452762613_

**Comment by DanHeidinga** [comment]
PR / issues to enable SCC by default:
https://github.com/eclipse/openj9/pull/4079
https://github.com/eclipse/openj9/issues/3854
https://github.com/eclipse/openj9/issues/1646

**Comment by pshipton** [comment]
#4227 has been merged.
