### ISSUE TITLE
Ensure boolean JNI methods on P produce a result of zero or one

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#4244]
Part of https://github.com/eclipse/openj9/issues/4241

@R-santhir

Pull request: https://github.com/eclipse/openj9/pull/4243

**Comment by gita-omr** [comment]
jenkins test extended plinux jdk11

**Comment by gita-omr** [comment]
jenkins test sanity plinux jdk11

**Comment by gita-omr** [comment]
@R-Santhir ran personal build sanity  and everything passed. So I think we can merge.

**Comment by pshipton** [comment]
@gita-omr can this be closed now that #4243 is merged?

**Comment by gita-omr** [comment]
Yes, closing.
