### ISSUE TITLE
Problem with curl installation on AIX machines libcurl.a could not be loaded

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#4245]
On aix71-p8-3, from https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/147/console:

18:50:25 curl -OLJks  https://api.adoptopenjdk.net/v2/binary/nightly/openjdk11?openjdk_impl=openj9&os=aix&arch=ppc64&release=latest&type=jdk&heap_size=normal
18:50:25 exec(): 0509-036 Cannot load program curl because of the following errors:
18:50:25 	0509-150   Dependent module /usr/lib/libcurl.a(libcurl.so.4) could not be loaded.
18:50:25 	0509-103   The module has an invalid magic number.

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
aix71-p8-4 was updated via #3961.  I thought I had done them all at the time, but I think I had just done the one and was waiting to determine if the update should be pushed out to them all.  They have all been updated now.

Package Updated:
`  curl.ppc 0:7.61.1-1`
Dependency Updated:
`  libssh2.ppc 0:1.8.0-3`

Noth #3961 and this one can be closed.
