### ISSUE TITLE
Install xvfb on OpenJ9 machines and Docker agent containers

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#4258]
related #4250 , https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/217

#### Machines

- [ ] aix
- [ ] osx
- [x] xlinux
- [x] plinux
- [x] zlinux
##### x
- [x] cent6
- [x] ub16
- [x] ub18
##### p
- [x] cent7
- [x] ub16
- [x] ub18
##### z
- [x] ub16
- [x] ub18

**Comment by AdamBrousseau** [comment]
@samuel-rubin Can you add this to the containers for your next task?

**Comment by AdamBrousseau** [comment]
xvfb added to Dockerfiles via #4329 
All containers have been rebuilt.

cc @jdekonin @smlambert 
Does this need to be added to AIX and Mac?

**Comment by smlambert** [comment]
Short answer is its a 'nice to have' on those platforms for the openj9 machines (we have no builds at openj9 that run the tests that require it).

Longer answer is yes, though not urgent, we need it on internal machines for those platforms as we will eventually need to run the tests that require it on those platforms (subset of jck & openjdk tests need it).  We have restricted the tests that require it to only run on Linux platforms for now, and have to run manually on mac/AIX after setting DISPLAY.  

We will need it on mac next as I've been asked to enable those tests in automation, but have not yet determined why the Jenkins plugin doesn't work to invoke it.  Connor has it installed on one mac internally and I have an open internal issue to try and figure out why Jenkins plugin isn't working as it does on Linux.  I have not had a chance to get back to that investigation.

**Comment by AdamBrousseau** [comment]
Will close this for now. Will open another issue for AIX once we are ready to test there and we can coordinate how to set it up. Will wait for the Mac issue to resolve before installing it on the rest of them.
