### ISSUE TITLE
Adding new labels for platform specific JIT work

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#4261]
I would like to add the following labels to openj9:

comp:jit:p, comp:jit:x, comp:jit:z, comp:jit:common

This will help us differentiate common and platform specific JIT work. Note that comp:jit can still be used when appropriate (e.g. implementation details are not known yet).

Please let me know what you think
@andrewcraik @fjeremic @pshipton @DanHeidinga

**Comment by pshipton** [comment]
This is fine with me.

**Comment by gita-omr** [comment]
@mstoodle

**Comment by andrewcraik** [comment]
I'm fine with it - making sure they have comp:jit as well might make sense to make searches and filtering easier, but I see the benefit of the more specific labels.

**Comment by gita-omr** [comment]
> 
> 
> I'm fine with it - making sure they have comp:jit as well might make sense to make searches and filtering easier, but I see the benefit of the more specific labels.

Yes, that's a good point. We will need to set both.

**Comment by 0xdaryl** [comment]
Don't forget about arm and soon-to-be aarch64.

**Comment by gita-omr** [comment]
Should we add comp:jit:opt or comp:jit:common ? Otherwise it's unclear if comp:jit belongs to common or simply was not identified yet.
