### ISSUE TITLE
Epic description template

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#4275]
I would like to suggest that whenever we open an epic it should have the following template at the bottom of the description:

- [ ] Design:
- [ ] VM:
- [ ] JIT:  
- [ ] Test cases: 
- [ ] Documentation:

Each of the checkboxes would point at a placeholder issues labeled accordingly. For example, JIT will point to an issue covering JIT work and labeled comp:jit. JIT developers will split it further into platform specific work.

The checkboxes will help: identify dependencies, find related issues and track status easier.

**Comment by pshipton** [comment]
+1

**Comment by gita-omr** [comment]
@andrewcraik @fjeremic @0xdaryl : fyi
