### ISSUE TITLE
Lost my Eclipse project when doing commit and push to my repository

### ISSUE THREAD

**Issue by ggvJava** [eclipse/openj9#4278]
I having an issue with Eclipse when I push and commit a project to GitHub.

![schermata del 2019-01-12 15-23-36](https://user-images.githubusercontent.com/46625948/51077991-be0aa500-16ae-11e9-8bd0-e03b38605d5a.png)

In the Package Explorer the code regarding that project disappears so as in the GitHub master repository!

Does that mean I lost my project?

In GitHub the project is there with just a bin folder and .project file

Eclipse STS 4.1.0 and openjdk version "10.0.2" 2018-07-17 OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4) OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode).

First in Eclipse I clone my github repository providing the url (ending with .git suffix). Then I select a project in the package explorer and do: Team->Share Project.., in the dialog box I select my .git repository and click finish. Then do Team->Commit and in the Git Staging tab I add all file, write a commit mesage and do Commit and push...I must say the moment I get in the Git Staging tab I see those Bib and .project file instead of the real project.

**Comment by gacholio** [comment]
This appears to be an issue with Eclipse, not OpenJ9. You'll need to open this elsewhere (sorry, not sure exactly where, might be bugzilla rather than a git issue).

**Comment by gacholio** [comment]
Sorry, I mean the issue is within the Eclipse IDE, possibly an issue with UI or the git plugin. You may want to start here:

https://bugs.eclipse.org/bugs/
