### ISSUE TITLE
Cannot start zlinux compile from jdk8 extensions, or win from jdk11

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4292]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/227

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
windows - https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/90

**Comment by pshipton** [comment]
plinux compile from https://github.com/eclipse/openj9/pull/4291 didn't work either

**Comment by AdamBrousseau** [comment]
fixed by #4017
