### ISSUE TITLE
Openssl for all build machines

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4293]
The following changes enable using the system installed openssl. Is a version of openssl 1.0 or later installed on all jenkins machines?

ibmruntimes/openj9-openjdk-jdk8#227
ibmruntimes/openj9-openjdk-jdk11#90

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
xlinux, plinux, zlinux all seem to be working anyway.

**Comment by pshipton** [comment]
Seems either we don't have openssl install everywhere, or there is a version problem. plinux testing in eclipse/openj9#4291 results in
`08:42:25 configure: error: Unable to find openssl 1.1.0(and above) installed on System. Please use other options for '--with-openssl'`

**Comment by jdekonin** [comment]
openssl 1.1.0g is installed on the new x86 machines only.  The Adopt playbooks only have it as a requirement for x86, and that requirement was raised via https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/493.

I don't see a requirement/issue for other platforms, is there one?  Can we just expand the existing playbook for p/z linux for the same version, 1.1.0g?

**Comment by pshipton** [comment]
@jdekonin Please consider this a formal requirement to have openssl on all build machines for all platforms. I will change the title. Instead of building/bundling openssl with the openj9 builds, we will use it from the machines.
1.1.0g is fine, it doesn't matter much since it is only used to compile against and perhaps run a few tests. Any version from 1.0 - 1.1 will be supported. Although 1.1.1 is the LTS version so you might consider using that instead.

**Comment by jdekonin** [comment]
All x86 ci machine have been updated already.  To be consistent I was planning on using the same version for p/z.  That change and machine update is in progress.

**Comment by pshipton** [comment]
Note we also want openssl on OSX, AIX, Windows.
For Window it is already installed, it needs to be on the path so Java can find the library
```
/cygdrive/c/OpenSSL-1.1.1-x86_64
/cygdrive/c/OpenSSL-1.1.1-x86_32
```

**Comment by jdekonin** [comment]
All zLinux (390) ci machine have been updated with 1.1.0g.

**Comment by pshipton** [comment]
@sxa555 do the Adopt test machines have openssl installed?

**Comment by pshipton** [comment]
@jdekonin a test compile on zlinux failed. Note the xlinux compile worked fine.
https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-linux_390-64_cmprssptrs-OpenJ9/64
```
13:21:21 checking for OPENSSL... checking for OPENSSL... no
13:21:21 configure: error: Unable to find openssl 1.1.0(and above) installed on System. Please use other options for '--with-openssl'
``

**Comment by jdekonin** [comment]
Can I have a pointer to a passing job please?

**Comment by pshipton** [comment]
I had a feeling you were going to ask for the link I didn't keep track of. :) But I tracked it down.
https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-linux_x86-64_cmprssptrs-OpenJ9/55/
Weirdly there is no console output. I've started a new one.
https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-linux_x86-64_cmprssptrs-OpenJ9/56/

**Comment by pshipton** [comment]
Try again https://ci.eclipse.org/openj9/job/PullRequest-Compile-JDK8-linux_x86-64_cmprssptrs-OpenJ9/57/

**Comment by jdekonin** [comment]
I got it.  The logs were compressed.  55 console output is readable now.

**Comment by jdekonin** [comment]
The Adopt playbook role OpenSSL does not cover the requirement for this request.  We need to install openssl via the package manager.

zLinux and plinux instances have 
```
/usr/bin/openssl version
OpenSSL 1.0.2g  1 Mar 2016
```
xlinux instance have
```
openssl version
OpenSSL 1.1.0g  2 Nov 2017
```

ub16-390-1, ub16-390-2, ub16-390-3, ub16-390-4
ub16-ppcle-1, ub16-ppcle-2, ub16-ppcle-3, ub16-ppcle-4
ub16-x86-1, ub16-x86-2, ub16-x86-3, ub16-x86-4, ub16-x86-5, ub16-x86-6

**Comment by pshipton** [comment]
@jdekonin are the following on the Windows path when running testing?

/cygdrive/c/OpenSSL-1.1.1-x86_64
/cygdrive/c/OpenSSL-1.1.1-x86_32

**Comment by jdekonin** [comment]
No, there is nothing added to the path for openssl, regardless of job.  I believe the actual location, at least according to the playbooks, is /cygdrive/c/openjdk/OpenSSL*.  Is windows smart enough to use the 32/64bit version needed for the test if both are on the path?

**Comment by pshipton** [comment]
> Is windows smart enough to use the 32/64bit version needed for the test if both are on the path?

I believe so.

**Comment by jdekonin** [comment]
I have added `;C:\OpenSSL-1.1.1-x86_32;C:\OpenSSL-1.1.1-x86_64` to the end of each of the system paths for win2012r2-x86-[1-4].  The jenkins agent will need to be restarted for the changes to be seen.  They are fairly busy atm, but will update once I have each of them reconnected.

**Comment by jdekonin** [comment]
win2012r2-x86-[1-4] each have been reconnected to jenkins.  PATH has been modified as per last comment.  Please advise if this setup works as expected and I can have the playbook modified to reflect the new changes.

**Comment by pshipton** [comment]
Started a test build to ensure nothing is broken by the change. Although, this won't confirm openssl on the path can be found.
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Pipeline-Build-Test-All/detail/Pipeline-Build-Test-All/418/pipeline

**Comment by pshipton** [comment]
The previous build worked, so the changes didn't break anything. Next I'll try using the library from the path. All I can try is 64-bit atm because the necessary Java 8 changes aren't delivered yet.

https://github.com/eclipse/openj9/pull/4914
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-win_x86-64_cmprssptrs-OpenJ9/341/

**Comment by pshipton** [comment]
Previous build passed. I won't be able to try 32-bit until we have the jdk8 support in place. Since 32-bit is first in the path, I think the work here is done.
