### ISSUE TITLE
zlinux sanity testing failed to start

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4297]
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs-OpenJDK8/21
```
17:01:35 TEST AUTO GEN SUCCESSFUL
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Get Test Dependencies)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] step
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // timeout
[Pipeline] End of Pipeline
Setting status of 448a532e88fef9c015e37b6fcacc428d8356479a to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_390-64_cmprssptrs-OpenJDK8/21/ and message: 'Build finished. '
Using context: Sanity - JDK8 - linux_390-64_cmprssptrs
ERROR: Unable to find a build for artifact copy from: test.getDependency
Finished: FAILURE
```

**Comment by pshipton** [comment]
@smlambert @llxia @jdekonin

**Comment by smlambert** [comment]
Would indicate there were no artifacts available from this build https://ci.eclipse.org/openj9/view/Infrastructure/job/test.getDependency/ at the time the zlinux test ran or that the test job could not access them.

**Comment by llxia** [comment]
Afaik, PR builds do not use test scripts from AdoptOpenJDK. PR builds run their own scripts.

In the AdoptOpenJDK test scripts, this case is handled. If any exception happens during calling test.getDependency job, the test scripts will ignore it. And the test script will try to download jars directly in the later process.

https://github.com/AdoptOpenJDK/openjdk-tests/blob/cd1a7fa3a6b69625e1d158000fdcd908c9540c93/buildenv/jenkins/JenkinsfileBase#L208-L213

**Comment by llxia** [comment]
I think we need try catch in PR builds as well:
https://github.com/eclipse/openj9/blob/4409caac7a850972790076b8a293fd7d1dc3a390/buildenv/jenkins/common/test#L62-L68

fyi @AdamBrousseau

**Comment by AdamBrousseau** [comment]
I would rather convert to the Adopt test pipes (#2836) than spend time fixing these ones. Since this is the first time I've seen this reported I wouldn't say it's a blocker.
