### ISSUE TITLE
Documentation - default OS stack size on z/OS

### ISSUE THREAD

**Issue by smithwil** [eclipse/openj9#4335]
The documentation at: https://www.eclipse.org/openj9/docs/openj9_defaults/

shows default OS thread stack size (Xmso) on z/OS as 256KB. But when I run java -verbose:sizes -version for the IBM Java 8.0.5.15 SDK on z/OS it shows: -Xmso384K. So, perhaps the documentation needs updating if 384K is the accurate default size.

**Comment by pshipton** [comment]
@SueChaplain

**Comment by smithwil** [comment]
According to j9cfg_builder.h,
The default is 384KB on z/OS 64-bit with compressed references, otherwise it is 256KB.

**Comment by SueChaplain** [comment]
Opened https://github.com/eclipse/openj9-docs/issues/194. Closing this issue here to clear it from the list.
