### ISSUE TITLE
Handle exception thrown by the constructor of J9::SystemSegmentProvider

### ISSUE THREAD

**Issue by dsouzai** [eclipse/openj9#434]
`J9::SystemSegmentProvider` takes in a `J9::J9SegmentProvider` as its segment allocator. `J9::J9SegmentProvider` is currently extended by two classes: `J9::J9SegmentCache` and `J9::SegmentAllocator`; the former is used for performance reasons - it caches a segment that can be used by future compilations that are likely to happen soon after the current compilation, preventing the churn of deallocation and reallocation.

When `J9::J9SegmentCache` is initialized, it first tries to allocate a segment of 16 MB; failing that it tries to allocate 2 MB, and failing that it tries to allocate 64 KB. The problem occurs when it allocates either 2 MB or 64 KB. When the `J9::SystemSegmentProvider` is initialized in `TR::CompilationInfoPerThreadBase::compile`, it tries to allocate a 16 MB segment. Because it takes in a `J9::J9SegmentCache` which has already preallocated 16 MB, it just receives this preallocated segment. However, if `J9::J9SegmentCache` allocated 2 MB or 64 KB, then when `J9::SystemSegmentProvider` requests a 16 MB segment, `J9::SegmentCache` will see that its preallocated segment is not big enough, and will try to allocate the requested size, which will most likely fail since it failed earlier. This will result in the constructor of `J9::SystemSegmentProvider` throwing, which gets caught in `TR::CompilationInfoPerThread::processEntries`. The problem is that a bunch of work done in `TR::CompilationInfoPerThread::processEntry` does not get cleaned up (including releasing VM Access).

The current plan is to change the hierarchy of `J9::J9SegmentCache` to make it a child of `J9::SegmentAllocator` (https://github.com/dsouzai/openj9/commit/6b819681d8d46280edfcfc87331cab2cef0e7a36) and then add a couple of virtual functions in `J9::J9SegmentProvider` to provide the cached segment size (https://github.com/dsouzai/openj9/commit/681bf5e6d5eece07a4a6581555d02e6ab8effc2d). 

This will solve the problem described in the previous paragraphs, but it does not solve the underlying problem, namely that the constructor of `J9::SystemSegmentProvider` could still throw for different reasons (some OOM in an STL container for example). I can't wrap just the code in the very beginning of  the `compile` method because then the `defaultSegmentProvider` and `debugSegmentProvider` variables only exist in the scope of the try block. Copy constructing does not work because that too could throw.

I don't know if wrapping `compile` is the right thing to do because only the code in the very beginning of the `compile` method throws. The `compile` method also contains code to handle what happens if a compilation failed, and so if we fail to allocate the allocator, we need to have a path to handle that situation (lower memory limits, reduce compilation threads, etc).

**Comment by dsouzai** [comment]
fyi @mpirvu @fjeremic

**Comment by lmaisons** [comment]
FWIW, I would solve the segment size problem by adding a `getPreferredSegmentSize` to the J9SegmentProvider interface class with the option of returning 0 to mean no preferred size.

Then add the appropriate implementations to J9SegmentAllocator and J9SegmentCache...

I *really* don't like inheritance, preferring instead composition and chaining, so factor that bias into the value of my opinion...

**Comment by lmaisons** [comment]
Also, thanks for writing this up.  I owe you a beer next time we meet.

**Comment by pshipton** [comment]
@mpirvu I suspect you didn't mean to close this issue from the commit.

**Comment by mpirvu** [comment]
@dsouzai please confirm, but I believe that https://github.com/dsouzai/openj9/commit/566f38054466adc9ab63d25ba41c09d2c2c0242d completely closes this issue.

**Comment by pshipton** [comment]
Sorry, I got confused and thought this Issue somehow got closed without the change being merged.

**Comment by dsouzai** [comment]
Yeah, https://github.com/eclipse/openj9/pull/1118 completely addresses this issue.
