### ISSUE TITLE
Liberty Startup Regressions ~2-8% All Platforms

### ISSUE THREAD

**Issue by piyush286** [eclipse/openj9#4377]
This issue was discovered internally at IBM and is currently being investigated. This issue is created so the problem can be exposed to the Release 0.12.0 milestone plan.

Comparing the weekend runs, startup regressions have been introduced between 20190111 and 20190118 builds.

**Comment by pshipton** [comment]
Set as a blocker for the 0.12 release

**Comment by dsouzai** [comment]
https://github.com/eclipse/openj9/pull/4383 should fix this.

**Comment by andrewcraik** [comment]
Fixed by #4383 we just missed the close marker in the commit/PR.

**Comment by pshipton** [comment]
Reopening as the comment in #4393 indicate #4393 is also required to fix this regression.

**Comment by pshipton** [comment]
#4393 and #4405 are merged.
