### ISSUE TITLE
Improve BNDCHK evaluator on Z

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#4384]
Using the following command line on Linux on Z:

```
bin/java -Xjit:count=0,'{java/lang/Long.getChars(JI[C)V}(tracefull,tracecg,tracera={*},log=log.trace)' -version
```

We can generate a trace file with the following trees:

```
------------------------------
 n983n    (  0)  BNDCHK [#1]                                                                          [     0x3ff987b1300] bci=[-1,82,459] rc=0 vc=976 vn=- li=62 udi=- nc=2
 n960n    (  0)    ==>iloadi (in GPR_0789) (X>=0 cannotOverflow )
 n975n    (  4)    iadd (in GPR_0799) (cannotOverflow )                                               [     0x3ff987b1080] bci=[-1,71,459] rc=4 vc=976 vn=- li=62 udi=- nc=2 flg=0x1000
 n1251n   (  1)      ==>iRegLoad (in GPR_0768) (cannotOverflow SeenRealReference )
 n976n    (  0)      iconst -2 (X!=0 X<=0 )                                                           [     0x3ff987b10d0] bci=[-1,58,458] rc=0 vc=976 vn=- li=62 udi=- nc=0 flg=0x204
------------------------------

 [     0x3ff989b43d0]   AHIK    GPR_0799,GPR_0768,-2,
 [     0x3ff989b44e0]   CLR     GPR_0789,GPR_0799
 [     0x3ff989b45d0]   BRC     BNL(0xc), Snippet Label L0187
```

This sequence is suboptimal. We can combine the compare and branch into a `CLRB` instruction. Taking a look at the `BNDCHKEvaluator` on Z it also seems to be a mess. We should take this time to clean it up a  bit. A lot of the code inside looks like duplicate code which is already handled in other APIs.

**Comment by VermaSh** [comment]
It looks like those instructions are generated as a result of [neither child being constant](https://github.com/VermaSh/openj9/blob/master/runtime/compiler/z/codegen/J9TreeEvaluator.cpp#L3390).

Next step will be to identify and implement peephole optimizations.

**Comment by VermaSh** [comment]
Was able to implement peephole optimizations. `CLR` and `BRC` instructions will now reduced to `CLRJ`. PR: https://github.com/eclipse/omr/pull/4529
