### ISSUE TITLE
Failures running Javac for DDR_Test

### ISSUE THREAD

**Issue by andrewcraik** [eclipse/openj9#4397]
PR builds are failing regularly trying to run the DDR_Tests. Failures report a compile step failed related to javac with cryptic messages similar to:
```10:48:33 /home/u0020236/workspace/PullRequest-Sanity-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/openj9/test/functional/DDR_Test/build.xml:59: Error running /home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/build/aix-ppc64-normal-server-release/images/jdk/bin/javac compiler
10:48:33 
10:48:33 Total time: 1 second
10:48:33 makefile:82: recipe for target 'compile' failed
10:48:33 make: *** [compile] Error 1
[Pipeline] }
```

see https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK11-aix_ppc-64_cmprssptrs-OpenJ9/85/console

**Comment by andrewcraik** [comment]
@DanHeidinga @pshipton FYI. @keithc-ca could this be related to any of the recent DDR changes? Not trying to place blame just trying to figure out if this is a problem with javac or a problem with DDR - any thoughts?

**Comment by andrewcraik** [comment]
FYI @0xdaryl and @liqunl due to interest on the OpenJ9 triage slack channel

**Comment by DanHeidinga** [comment]
I think I've seen it on non-DDR builds as well - looking for a link now.

**Comment by keithc-ca** [comment]
Yes, I think the test code is being compiled with the brand new JDK. I agree it's serious if javac in that JDK doesn't work.

**Comment by pshipton** [comment]
I think we found the culprit
https://github.com/eclipse/openj9/pull/4017

**Comment by DanHeidinga** [comment]
@pshipton Is this fixed now that #4017 has been merged?  If so we should close it out.

**Comment by AdamBrousseau** [comment]
No, 4017 is what caused this issue. I am still determining why though. I would like to figure it out so we can get in a fix rather than simply reverting the change.

**Comment by DanHeidinga** [comment]
@AdamBrousseau What's the downside of reverting now and re-introducing the change later?  Currently PR builds are broken which affects all PRs.
