### ISSUE TITLE
Remove unused or obsolete UMA flags

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#4398]
In https://github.com/eclipse/openj9/pull/4350, I questioned setting `module_codegen_ia32` to `true` in an ARM spec. It turns out that flag and many others are unused: those should simply be removed.

**Comment by DanHeidinga** [comment]
Given the plan to migrate to cmake, I don't think it's worth spending time cleaning up the UMA flags.  The unused ones will naturally die off in the migration.

**Comment by DanHeidinga** [comment]
Link to the cmake migration plan: https://github.com/eclipse/openj9/issues/90
