### ISSUE TITLE
Generate AOT code at JITaaS server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#4401]
This issue proposes to allow the JITaaS server to perform AOT compilations, but the AOT code is going to be stored at the client where the shared class cache resides.

A few infrastructure changes need to be implemented:
1) Extend `TR_J9ServerVM` with `TR_J9SharedCacheServerVM` and teach the new frontend how to find the relevant pieces of information remotely. This means that we have to reimplement all the methods in `TR_J9SharedCacheVM`
2) Extend `TR_ResolvedJ9JITaaSServerMethod` with `TR_ResolvedRelocatableJ9JITaaSServerMethod` and reimplement all the methods in `TR_ResolvedRelocatableJ9Method` teaching them how to fetch relevant information from the remote client
3) Extend `TR_RelocationRuntime` with `TR_SharedCacheJITaaSRelocationRuntime` and reimplement all the methods in `TR_SharedCacheRelocationRuntime`

To implement all this incrementally I propose to start by making a simple AOT compilation work (like a method that just return 3).

**Comment by mpirvu** [comment]
Will need to look into `classChain = fej9->sharedCache()->rememberClass(definingClass);`

**Comment by dsouzai** [comment]
It might almost be worth extending the shared cache object to make a network call.

**Comment by dsouzai** [comment]
It might be worth updating the jitaas branch before doing a bunch of work implementing the sharedvm queries. For example: 

```
   if (comp->getOption(TR_UseSymbolValidationManager))
      {
      if (comp->getSymbolValidationManager()->verifySymbolHasBeenValidated(static_cast<void *>(classPointer)))
         {
         validated = true;
         }
      else
         {
         TR_ASSERT(false, "Class 0x%p should already be validated\n", classPointer);
         }
      }
```
(https://github.com/eclipse/openj9/pull/4406/files#diff-770fc7473e17fd36db57f82532b90d82R1510)

has been changed to 
https://github.com/eclipse/openj9/blob/fc206904ce524f8575628a8d9a217bf6c1548066/runtime/compiler/env/VMJ9.cpp#L8597-L8601

**Comment by dsouzai** [comment]
Given the remaining PRs in https://github.com/eclipse/openj9/issues/3752 there might be additional changes to the frontend queries (though @jdmpapin can confirm that).

**Comment by harryyu1994** [comment]
After added some initial setup code for `TR_J9SharedCacheServerVM`, the first issue I hit is due to wrong `TR_RelocationRuntime` at the server side. Going to create a `TR_SharedCacheJITaaSRelocationRuntime` class next and add dummy definitions with assert.

**Comment by harryyu1994** [comment]
Do we want to have shared class cache stored at both client and server side or just the client side?

**Comment by harryyu1994** [comment]
Should there be a task for "storing the AOT to SCC"?
It happens in `compilationEnd` for non-jitaas, I'm proposing JITaaS to handle this task in `remoteCompile`.
