### ISSUE TITLE
Auto-detect SPEC during test config in testkitgen

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#442]
Rather than require users to set SPEC prior to running tests, we should auto-detect it (and only require it if unable to detect).  Building its value from a combination of the 2 system properties os.name and os.arch is likely sufficient.

**Comment by llxia** [comment]
I think we can check how compilation job detects spec and use the same logic in test.

**Comment by smlambert** [comment]
To build a spec name (see https://github.com/eclipse/openj9/tree/master/buildspecs for examples), we will likely do something similar to what is done in this file:
https://github.com/eclipse/openj9/blob/master/debugtools/DDR_Autoblob/src/com/ibm/j9ddr/autoblob/GetNativeDirectory.java

The missing piece (from using os.name and os.arch) may be knowing whether we are using a cmprssptrs spec.

**Comment by smlambert** [comment]
As we are iterating into v2 of the test tools, in addition to SPEC, we can also see about auto-detecting/setting some of the other environmental variables like JAVA_VERSION, so that the instructions for setting up and running tests becomes simpler/easier.

**Comment by mgaudet** [comment]
Silly Q: Is there a reason we can't bake the spec into either the `-version` output, or a queriable system property? 

Just seems odd to me that this identity seems deeply desirable by multiple areas of the code, but it's mandatory to provide externally, or we'll end up in situation where we have multiple computations  of it.

**Comment by smlambert** [comment]
Yes, I was implying that it would be a useful unit of information to be able to query from an SDK (in earlier conversation with @keithc-ca that lead to the creation of this issue).

**Comment by llxia** [comment]
We can get the SPEC value if the sdk is compiled on the same machine.
```
cat ./build/aix-ppc64-normal-server-release/custom-spec.gmk | grep SPEC
OPENJ9_BUILDSPEC        := aix_ppc-64_cmprssptrs
```

**Comment by llxia** [comment]
fyi @Yuehan-Lin

**Comment by llxia** [comment]
- Based on the provided `JAVA_BIN`, we should be able to auto-detect the following using java program:
JDK_VERSION
JDK_IMPL
SPEC

A makefile will be generated with the above value and it will be incorporated into the TKG framework.

From a user point of view, the above three variables are not required. If provided by user, our famework should honor it. TKG can display a warning message if needed. 
All steps for running TKG should remain the same.

- Additional requirement (can be in another PR if needed):
Do not set `SPEC` as the environment variable in test. Pass it in as a parameter in TKG if possible.
`SPEC` is also used in SDK compilation but with a different value. This can be confusing if a user is repeatedly doing SDK compilation and test locally.
