### ISSUE TITLE
Add Pipeline support to include ADOPTOPENJDK_REPO and ADOPTOPENJDK_BRANCH

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4433]
@llxia suggested it needs to be done here
https://github.com/eclipse/openj9/blob/0b5606dbd2c3a4119530e6182173d09b86d4d51c/buildenv/jenkins/jobs/pipelines/Pipeline-Build-Test-All#L188

I expect we might need this fairly soon, as the AdoptOpenJDK test material might change and become incompatible with the 0.12 release builds.

**Comment by pshipton** [comment]
@jdekonin something for your next iteration plan
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Is there some background here?
I'm wondering if we can simply add the params and generally always/usually pull master or if we need to "lock" to a version/branch (like we do for OMR).

**Comment by pshipton** [comment]
We may need to pull a specific version (branch, tag, sha) of the AdoptOpenJDK test material for an OpenJ9 release branch. This would occur when the test material changes in some way incompatible with the release. Apparently such a thing is going to occur soon, @llxia can provide more details, although hopefully not before the 0.12 release ships, or until we can accommodate specifying a particular test level to use.

**Comment by pshipton** [comment]
From from Lan told me, the short answer is we just need to add the params so they can be modified if needed.

**Comment by llxia** [comment]
Another option is we can delay the [incompatible PR](https://github.com/AdoptOpenJDK/openjdk-tests/pull/832) until we are done testing 0.12

Or we can port [this PR](https://github.com/eclipse/openj9/pull/4262) into 0.12.

I guess the question is which solution is more beneficial to us. If the incompatible change does not happen too often, maybe we can just delay the change in Adopt. As far as I know, we will not test 0.12 once it is shipped.

fyi @smlambert

**Comment by pshipton** [comment]
In the future, I suppose we may not always have control over changes at Adopt.

**Comment by smlambert** [comment]
That future would only be if absolutely none of us showed up to help at Adopt, which is not a future that I can currently envision.  

But if we were somehow pressed to the wall in the future, branching at Adopt, or forking are 2 ways to mitigate.

**Comment by smlambert** [comment]
For this issue, I vote for the solution that requires the least work to do the right thing.

**Comment by pshipton** [comment]
> For this issue, I vote for the solution that requires the least work to do the right thing.

Which is ... ?

**Comment by pshipton** [comment]
delay the incompatible PR until we are done testing 0.12, seems the least amount of work.

**Comment by smlambert** [comment]
Yes, I assumed it was obvious so did not say it.  :)  
I am assuming we are within days of delivering 0.12.

**Comment by llxia** [comment]
fyi @vsebe

**Comment by AdamBrousseau** [comment]
Is the passed values expected to be used in the SCM configuration section or will that always point to `master`?

**Comment by pshipton** [comment]
@llxia ^

**Comment by llxia** [comment]
> Is the passed values expected to be used in the SCM configuration section or will that always point to master?

The SCM configuration section in job configure points to master. If the repo and branch are provided, we will checkout again using provided repo and branch.

**Comment by smlambert** [comment]
I believe this can be closed as won't fix, since it is expected to be very rare occurrence that an incompatible test change would be introduced during the period of time that a release branch is alive and being tested in tandem with the main stream.  

Rare, as in we have only ever made 1 of these types of changes in the last 2 years and do not have an need for any other major changes in the foreseeable future.

If we were to hit that occurrence again, we can do as we did in the release 0.12 case and hold off on the change until the release completes.

**Comment by AdamBrousseau** [comment]
This was delivered on Feb 5 (2019) via #4523, although after reading this issue, I don't think it was implemented correctly to address the origin of this issue. It's seemingly implemented as a means to pass the test repo as a param during a personal build. Although, it could work if we were to fork the Adopt test repo and create release branches for ourselves and then change the values of the repo/branch in the defaults.yml on our release branches. If that was the intended use case then I guess it's implemented correctly.

I got back to here after trying to dig up why these params were added in the first place. We've been asked to make some modification to the change to support https://github.com/AdoptOpenJDK/openjdk-tests/pull/1758 but based on that ask, it seems we still may not be on the same page.

@llxia what is the use case for the change request? Is it simply that the internal build will break on zOS? Or do you have a use case for doing personal builds with different test repo values?

**Comment by llxia** [comment]
This is not related to smart parallelization or internal zos ssh issue. The original problem was some PRs that we deliver into Adopt may be incompatible with OpenJ9 release branch during its testing period. The fix was to set Adopt repo and branch so that we can avoid incompatible PRs in the release branch. But as mentioned above, incompatible PRs may be a very rare occurrence, so we did not really use it for the release build.
