### ISSUE TITLE
JITaaS stream failure when compiling at hot

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#4445]
I attempted to run AcmeAir with JITaaS and -Xjit:initialOptLevel=hot. The benchmarks fails to run and the vlogs show the following:
Client:
```
 (warm) Compiling java/lang/String.lengthInternal()I  OrdinaryMethod j9m=0000000001F26D00 t=101018 compThread=5 memLimit=2000000 KB freePhysicalMemory=15016 MB
#JITaaS: Client sending compReq seqNo=1193 to server for method java/lang/String.lengthInternal()I @ warm.
```
Server:
```
#JITaaS: Server received request for stream 00007F7C812C4EB0
#JITaaS: compThreadID=1 found clientSessionData=00007F7C91C8D570 for clientUID=18163716480807386620 seqNo=1193
#JITaaS: Server will process a list of 0 unloaded classes for clientUID 18163716480807386620
#JITaaS: Stream failed while compThreadID=1 was reading the compilation request: JITaaS I/O error: reading message size
#JITaaS: compThreadID=1 did an early abort for clientUID=18163716480807386620 seqNo=1193
#JITaaS: JITaaS StreamFailure: JITaaS I/O error: reading message size
```
After this the client stops sending and new compilation requests and the application throws exceptions. Ideally the server should have closed the socket so that the client can interrupt its waiting and retry

**Comment by dmitry-ten** [comment]
I'll look into it

**Comment by harryyu1994** [comment]
It seems like for the setup I have on my own vm don't see this problem. Going to try this on Lara.

**Comment by harryyu1994** [comment]
"initialOptLevel=warm" works fine while "initialOptLevel=hot" failed. I'll look into it.

**Comment by harryyu1994** [comment]
It may not be a JITServer issue. I have managed to reproduce the same crash with JIT Server turned off(made JIT Server unreachable so all compilations will be local).
Though there is still a difference between JIT Server turned off and pure non-JITServer. So I tried with non-JITServer. We still see the crash but it takes much longer to crash.

**Comment by mpirvu** [comment]
If I remember correctly, @dmitry-ten tracked this to be due to some bad code emmitted at hot in presence of GCR. Using `disableGuardedCountingRecompilation` circumvents the issue. I'll code this in, since GCR was originally meant to upgrade from cold to warm and not from hot to very-hot.
