### ISSUE TITLE
windows10&openj9-jdk8??JVM_EnqueueOperation() stubbed

### ISSUE THREAD

**Issue by iver3on** [eclipse/openj9#4465]
![image](https://user-images.githubusercontent.com/12184988/51782060-4da75d80-215d-11e9-9449-0e424c3c5d07.png)
what's wrong???!!!

**Comment by pshipton** [comment]
This error means that an OpenJDK+Hotspot / Oracle JVM is attempting to use Attach API to connect to an OpenJ9 VM. This is not supported.

**Comment by pshipton** [comment]
We could update the assertion error message with a description of the problem, rather than "JVM_EnqueueOperation() stubbed!".

**Comment by DanHeidinga** [comment]
@sharon-wang is looking at updating the message

**Comment by DanHeidinga** [comment]
This didn't make the `0.13.0` milestone.  Retargeting to `0.14.0`
