### ISSUE TITLE
Allow multiple hot compilations in parallel in JITaaS mode

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#4476]
The heuristics in the JIT don't allow multiple expensive compilation to be performed in parallel to avoid increasing the peak footprint too much. This is controlled by an option which defines what an expensive compilation is: `-Xjit:expensiveCompWeight=`
The default value is set such that hot, scorching and JSR292 compilations are considered expensive.
However, in JITaaS world such compilation are performed remotely and therefore there is no risk of blowing the footprint limit on the JVM. Therefore, for the JITaaS client we should set a large value for `expensiveCompWeight` to allow several memory expensive compilations to be performed in parallel.

**Comment by harryyu1994** [comment]
Looking into this one.
