### ISSUE TITLE
Incorrect handling of _residualWeight in IProfiler data structures

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#450]
For the purpose of profiling targets for interface invokes, checkcasts and interfaceofs the IProfiler maintains 3 slots in this data structure
```
#define NUM_CS_SLOTS 3
class CallSiteProfileInfo
   {
   uint16_t _weight[NUM_CS_SLOTS];
   uint16_t _residueWeight:15;
   uint16_t _tooBigToBeInlined:1;
  uint32_t _clazz[NUM_CS_SLOTS];
   }
```
Thus, IProfiler can track 3 different classes. For a highly polymorphic site, once the 3 slots have been populated with first 3 seen classes, the frequency of any other class gets accumulated into a spill field called _residueWeight. If the _residueWeight becomes greater than the maximum frequency among the 3 tracked classes, we start over by resetting the identity of those classes.
Because _residueWeight is kept on 15 bits we have to be careful for overflow. 
The code that is supposed to update the _residueWeight currently reads:
```
   if (!found && _csInfo._residueWeight >= 0x7FFF)
      {
      if (_csInfo._residueWeight > maxWeight)
         {
         if (lockEntry())
            {
            for (int32_t i = 1; i < NUM_CS_SLOTS; i++)
               {
               _csInfo.setClazz(i, 0);
               _csInfo._weight[i] = 0;
               }
            _csInfo._weight[0] = freq;
            _csInfo.setClazz(0, v);
            _csInfo._residueWeight = 0;
            returnCount = freq;
            releaseEntry();
            }
         }
      else
         {
         // Check for overflow
         uint16_t newWeight = _csInfo._residueWeight + freq;
         if (newWeight >= _csInfo._residueWeight)
            _csInfo._residueWeight = newWeight;
         else
            _csInfo._residueWeight = 0xFFFF;
         returnCount = _csInfo._residueWeight;
         }
      }
```
Because _residueWeight starts at 0, the condition in the IF above is not fulfilled and _residueWeight is not updated, perpetually remaining at 0.

**Comment by harryyu1994** [comment]
What's the reason behind having the `_csInfo._residueWeight >= 0x7FFF` condition in the above `if` statement? I think removing this condition will make the code work.

**Comment by mpirvu** [comment]
The condition at that point is bogus. It needs to be moved at the point where we are about to increment _residueWeight to avoid overflow.
