### ISSUE TITLE
Removing j9signalTest.c and j9signalExtendedTest.c

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#452]
[j9signalTest.c](https://github.com/eclipse/openj9/blob/05160934f57ada3fdf831d6a547715f1fc0055cc/runtime/tests/port/j9signalTest.c) and [j9signalExtendedTest.c](https://github.com/eclipse/openj9/blob/05160934f57ada3fdf831d6a547715f1fc0055cc/runtime/tests/port/j9signalExtendedTest.c) are essentially duplicates of corresponding tests in Eclipse OMR [omrsignalTest.cpp](https://github.com/ashu-mehra/omr/blob/470bcf78c72a72a2d71fef6f314ad28f3f338e13/fvtest/porttest/omrsignalTest.cpp) and [omrsignalExtendedTest.cpp](https://github.com/ashu-mehra/omr/blob/470bcf78c72a72a2d71fef6f314ad28f3f338e13/fvtest/porttest/omrsignalExtendedTest.cpp).

As I understand, there is no need for having these tests in both repositories.
It would be better to clean up `j9signalTest.c` and `j9signalExtendedTest.c` from OpenJ9 repo.

**Comment by smlambert** [comment]
IMO we want to push tests down to the lowest layer to which they apply.  If there is no Java specifics remaining in these tests and they are already in the OMR project, they should be removed from OpenJ9, yes.
