### ISSUE TITLE
Windows assembler error: error A2075:jump destination too far 

### ISSUE THREAD

**Issue by vsebe** [eclipse/openj9#454]
Openj9 build failure on windows 10: 

m4 -DWIN32  -I. -I../include -I../oti -I../util -I../gc_include -I../omr/gc/include -I../tr.source/runtime -I../tr.source/codegen -I../tr.source/base -I../tr.source/trj9/runtime -I../nls -I../omr/include_core xnathelp.m4 > xnathelp.asm
jswalk.c
thunkcrt.c
ut_j9codertvm.c
jsr292.c
ml64 /c /Cp /W3 /nologo /Zd /Zi  -DWIN32 -DWIN64 -DJ9HAMMER /I. /I../include /I../oti /I../util /I../gc_include /I../omr/gc/include /I../tr.source/runtime /I../tr.source/codegen /I../tr.source/base /I../tr.source/trj9/runtime /I../nls /I../omr/include_core  -DTR_HOST_X86 -DTR_64Bit -DTR_HOST_64BIT -DTR_TARGET_64BIT -DTR_TARGET_X86  xnathelp.asm
 Assembling: xnathelp.asm
xnathelp.asm(2458) : error A2075:jump destination too far : by 26 byte(s)
make[5]: *** [../makelib/targets.mk:400: xnathelp.obj] Error 1
make[5]: Leaving directory '/cygdrive/c/tmp/openj9-openjdk-jdk9_latest/build/windows-x86_64-normal-server-release/vm/codert_vm'
make[4]: *** [makefile:1138: j9codert_vm] Error 2

**Comment by vsebe** [comment]
Attn @DanHeidinga, @gacholio

**Comment by pshipton** [comment]
We merged a fix for this yesterday #445, I expect you just need to update.
