### ISSUE TITLE
RESOLVER dependency

### ISSUE THREAD

**Issue by BillOgden** [eclipse/openj9#4540]
(For z/OS) java apparently goes to the RESOLVER (if it is active) to obtain the local system name. I assume this is to allow the name to be included in diagnostic information. If the RESOLVER is active and has name server address(es) specified but cannot contact any of the name servers (for whatever reasons) then java startup hangs until the RESOLVER times out waiting for a name server. Using common default settings for the RESOLVER, the external effect is that the java program is hung for many seconds --- typically 60 seconds, with common time out defaults. On a production z/OS system this situation should be rare, but on a small development platform (such as zPDT) this is more likely, especially when LAN connection is via a DHCP address to the underlying Linux.  There should be a java option to skip this nameserver request.

**Comment by DanHeidinga** [comment]
@sharon-wang Can you take a look at this?

**Comment by BillOgden** [comment]
Sorry, but when I go to your shortURL I see nothing about RESOLVER.

Bill Ogden

**Comment by sharon-wang** [comment]
@DanHeidinga I'm looking at other options for guidance, such as: https://github.com/eclipse/openj9/blob/bd19d90b8ef80bfc7a96c837719a2b4b4ce6e568/runtime/oti/jvminit.h#L307

I noticed that there are a variety of prefixes, such as "-X", "-XX", "-XX:". Just wondering if there is a convention for selecting which one to use?

**Comment by DanHeidinga** [comment]
For new options, prefer the `-XX:[+-]Option` format.

**Comment by pdbain-ibm** [comment]
From Slack conversation:

A couple of comments:
1. Use a more descriptive name, e.g. `useResolverForHostname`
2. Add `+` and `-` versions of the option.  This is useful for overriding a default embedded in an environment variable.
