### ISSUE TITLE
Indy work for jep334

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#4542]
This is my current understanding of the problem and what needs to happen:

m is the original MethodHandle
mDesc is a nominal descriptor of MethodHandle of type MethodHandleDesc
m' is the MethodHandle resolved mDesc

m and m' are equivalent.

If indy is called on m and then m' the current expected behaviour is that the bsm will be called and MethodHandle will need to be resolved each time. This is unnecessary because the resulting call site entries will contain the same information.

**Steps:**
- [ ] Write a test case to verify that resolved invokedynamic call sites are propagated between retransformed classes (it is assumed that this should fail) https://github.com/eclipse/openj9/pull/5029

- [ ] Discuss next steps including the best way to determine callsite equivalence in `redefineClassesCommon` code 

fyi @DanHeidinga @gacholio

**Comment by DanHeidinga** [comment]
This isn't quite what I was thinking when we talked so apologies for the unclear presentation.

The background:
JVMTI allows classes to be redefined / retransformed - basically modifying method bodies to contain different bytecodes.  

Now, not every retransformation modifies every method.  Many methods are unchanged and are viewed as `equivalent` between the original and the redefined class.  Equivalent in this context means the methods have the same bytecodes that point to equivalent constant pool data (ie: the cp indexes may be different, but the data must be the same).

This task is to confirm whether OpenJ9 propagates the resolved state for invokedynamic bytecodes in equivalent methods from the original class to the new class.  Default assumption - it doesn't.

Step 1 is to write a test that uses invokedynamic in a method.  Run the method and observe the BSM being invoked.  Retransform the class in a way that the method with the invokedynamic is equivalent.  Invoke the method again and see if the BSM is invoked a second time.

If the BSM is invoked a second time, it means the resolution state for those invokedynamics isn't being propagated.  The resolution state is stored in the `J9Class->callsites[]` array and we'll need to find a way to map from the old index into that array to the new index.  Note, indexes are assigned linearly from the start of the class.

**Comment by theresa-m** [comment]
Okay that makes sense. So I'm assuming one of the ways retransformation can be simulated is when a MH's nominal descriptor is resolved? Does retransformation also happen when something like MethodHandles.lookup().findStatic() is called?
