### ISSUE TITLE
JIT returns to incorrect stack location in certain optimization / inlining active

### ISSUE THREAD

**Issue by DanGritter** [eclipse/openj9#455]
Running some tests with certain optimization results in a GPF dump - linux_390-64 test recreate invocation is as below:

[Dan: Edited to remove references to compliance tests]

**Comment by mstoodle** [comment]
@DanGritter sorry we (appear to have) let this one languish. @fjeremic have you been tracking this one?

**Comment by fjeremic** [comment]
> @fjeremic have you been tracking this one?

No, unfortunately I have let this one slip past my radar. It appears this is running on zTPF though? We certainly do run JCK tests on some flavor of this codebase and this problem was not observed. Could you tell us more about the environment this was running in?

Also if possible given that this is months old now, does it occur on the latest commits available?

**Comment by DanGritter** [comment]
This occurs both on z/TPF as well as linux, however is tied to the "invalid" jit options so not really a big concern for us.
Just recreated it with java 1.8.0.151, not sure if this is the "latest" but certainly recent, specific version is at the bottom.

LD_LIBRARY_PATH=/tmp:/ztpf/java/bld/jck/JCK8b/jtctest/apps/ascii/jck/jck8b/natives/linux_390-64:$LD_LIBRARY_PATH java -Xjit:counts="- - - - - - 0 0 0 0 0 0 - - - 0 0 0" -server -agentlib:jckjvmti=feri00101 -Xfuture -classpath runtest.jar javasoft.sqe.tests.vm.jvmti.feri001.feri00101.feri00101 -platform.jvmtiSupported true -platform.nativeLibsLinkage dynamic
Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000010 Signal_Number=00000004 Error_Value=00000000 Signal_Code=00000001
Handler1=000003FF9509F5F8 Handler2=000003FF94EA9928
gpr0=0000000000000016 gpr1=0000000000000003 gpr2=0000000000000000 gpr3=0000000000197CE0
gpr4=000003FF7E24FD68 gpr5=0000000000197D08 gpr6=000000002C75F970 gpr7=000003FF94D7E8C8
gpr8=000003FF951A0430 gpr9=000000002C75F970 gpr10=000003FF94D7E8C0 gpr11=000003FF94D7E8B8
gpr12=00000000001CC348 gpr13=000000000018D900 gpr14=000000002C75F970 gpr15=000003FF94D7E498
psw=000000002C75F972 mask=0705100180000000 fpc=0008000000000000 bea=000003FF7E24FD82
fpr0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr1 402f2d555d9429ab (f: 1569991040.000000, d: 1.558854e+01)
fpr2 000000002c75fa88 (f: 745929344.000000, d: 3.685381e-315)
fpr3 bee2800000000000 (f: 0.000000, d: -8.821487e-06)
fpr4 000003ff95a7e228 (f: 2510807552.000000, d: 2.172042e-311)
fpr5 402f2d548abf572a (f: 2327795456.000000, d: 1.558854e+01)
fpr6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr7 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
fpr8 00000001266d9490 (f: 644715648.000000, d: 2.440528e-314)
fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr10 00000000bfc54e50 (f: 3217378816.000000, d: 1.589596e-314)
fpr11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
fpr15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Target=2_90_20171102_369060 (Linux 4.4.92-6.30-default)
CPU=s390x (4 logical CPUs) (0xbc096000 RAM)
----------- Stack Backtrace -----------
(0x000000002C75F972 [<unknown>+0x0])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2018/01/24 11:15:56 - please wait.
JVMDUMP032I JVM requested System dump using '/home/dgritter/core.20180124.111556.42379.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.42399.

JVMDUMP012E Error in System dump: The core file created by child process with pid = 42399 was not found. Expected to find core file with name "/home/dgritter/core"
JVMDUMP032I JVM requested Java dump using '/home/dgritter/javacore.20180124.111556.42379.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/dgritter/javacore.20180124.111556.42379.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/dgritter/Snap.20180124.111556.42379.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/dgritter/Snap.20180124.111556.42379.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/home/dgritter/jitdump.20180124.111556.42379.0004.dmp'
JVMDUMP013I Processed dump event "gpf", detail "".

gritter@linuxtpf:~> java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 8.0.5.5 - pxz6480sr5fp5-20171114_01(SR5 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux s390x-64 Compressed References 20171102_369060 (JIT enabled, AOT enabled)
OpenJ9   - 7ade437
OMR      - 1b656cb
IBM      - 59c3d96)
JCL - 20171113_01 based on Oracle jdk8u151-b12

**Comment by mstoodle** [comment]
Ok, this issue reports a problem against an internal IBM build, which should not be reported at Eclipse OpenJ9.

@DanGritter I suggest you discuss this failure within IBM (IBM J9 VM) and open an issue to address the problem, once it has been diagnosed. On that basis, I'll close this issue. Sorry we took so long to reach this conclusion for you.
