### ISSUE TITLE
ub16x64j91 problems creating core files

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4559]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_x86-64/165/
```
JVMDUMP012E Error in System dump: The core file created by child process with pid = 12814 was not found. Expected to find core file with name "/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/core"
```

```
[ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.14780.
 [ERR] 
 [ERR] JVMDUMP012E Error in System dump: The core file created by child process with pid = 14780 was not found. Expected to find core file with name "/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests4_0/core"
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_x86-64/223/

**Comment by jdekonin** [comment]
There appears to be 2 issues here; corefile not present and error to generate.

I took last nights build (JDK8 and JDK11) and there doesn't seem to be a specific problem with the machine.  I can generate a corefile 10 times (with both releases) concurrently without issue, although I did notice that some of the times to generate a core on vmstart were taking between 8-10 seconds, 2 of the 20 as a sample size.

I discussed with @llxia, because I didn't know how testing waits or checks for core generation to be complete.  This might be worth adding as a enhancement to the test to check for an agreed upon time before giving up and failing the test.  That might help address the corefile not present issue.

For the specific failure in generating the cores I am not sure how to proceed.  There is nothing in /var/log/* indicating that there was a problem with the system.  A respin the the same failing test on that machine is now passing.
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_x86-64/224/consoleFull

**Comment by llxia** [comment]
When we talked this morning, I thought it was a Java DDR tests where we generate code, then run java test to validate DDR commands.

However, this is a command line test, which means we just run command and just valid the output from the command. In this case, we get error message `Error in System dump` when running the command. I do not think we need to add check to valid if core is completed.

```
Testing: Test 105: Design 40220: Corrupt the cache.
Test start time: 2019/02/02 23:40:32 Atlantic Standard Time
Running command: "/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdkbinary/j2sdk-image/bin/java" -Xnocompressedrefs -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xdump:system:file=shrcmltest.dmp -Xdump:java:file=shrcmltest.txt -Xdump:snap:file=shrcmltest.trc -Xshareclasses:name=ShareClassesCMLTests,printStats,testFakeCorruption -version
Time spent starting: 2 milliseconds
	Match (success): jvmshrc443e cache crc is incorrect indicating a corrupt cache. incorrect cache crc: 0x0.
	Match (required): JVMDUMP039I Processing dump event "corruptcache", detail "" at 2019/02/02 23:40:32 - please wait.
	Match (required): JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/shrcmltest.dmp' in response to an event
	Match (failure): JVMDUMP012E Error in System dump: The core file created by child process with pid = 12814 was not found. Expected to find core file with name "/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/core"
	Match (required): JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/shrcmltest.txt' in response to an event
	Match (required): JVMDUMP010I Java dump written to /home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/shrcmltest.txt
	Match (required): JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/shrcmltest.trc' in response to an event
	Match (required): JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test-extended.functional-JDK11-linux_x86-64/openjdk-tests/TestConfig/test_output_15491650588048/testSCCMLTests2_0/shrcmltest.trc
Time spent executing: 5503 milliseconds
Test result: FAILED
```

**Comment by pshipton** [comment]
Still core file related problems on this machine. 
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/507

```
Testing: Create core file
Test start time: 2019/02/08 00:49:21 Atlantic Standard Time
Running command: "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs  -Xaot:forceaot,count=0 -Xshareclasses:name=shareddbgext -cp /home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/utils/utils.jar -Xdump:system:file=j9core.dmp,events=vmstop org.openj9.test.ivj.Hanoi 2
Time spent starting: 8 milliseconds
Time spent executing: 10398 milliseconds
Test result: PASSED

Testing: Remove shared cache
Test start time: 2019/02/08 00:49:32 Atlantic Standard Time
Running command: "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs  -Xshareclasses:name=shareddbgext,destroy
Time spent starting: 4 milliseconds
Time spent executing: 172 milliseconds
Test result: PASSED

Testing: Run !printallcallsites
Test start time: 2019/02/08 00:49:32 Atlantic Standard Time
Running command: /home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/../bin/jdmpview -core j9core.dmp
Time spent starting: 6 milliseconds
Time spent executing: 976 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] Could not load dump file and/or could not load XML file: Image file '/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15496011472785/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp' not found.
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] > DDR is not enabled for this core file, '!' commands are disabled
 [OUT] > 
>> Success condition was not found: [Output match: jvminit.c]
>> Failure condition was not found: [Output match: DDRInteractiveCommandException]
>> Failure condition was not found: [Output match: no shared cache]
>> Failure condition was not found: [Output match: unable to read]
>> Failure condition was not found: [Output match: could not read]
>> Failure condition was not found: [Output match: dump event]
```

```
         [ERR] 1: j9dump_test_create_dump_with_name
         [ERR] 	j9dumpTest.c line  213: j9dump_create returned: 1, with filename: The core file created by child process with pid = 21840 was not found. Expected to find core file with name "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15496011472785/cmdLineTester_pltest_0/core"
         [ERR] 
         [ERR] 		LastErrorNumber: -108
         [ERR] 		LastErrorMessage: No such file or directory
         [ERR] 
         [ERR] 2: j9dump_test_create_dump_from_signal_handler
         [ERR] 	j9dumpTest.c line  311: j9dump_create returned: 1, with filename: The core file created by child process with pid = 21846 was not found. Expected to find core file with name "/home/jenkins/workspace/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/openjdk-tests/TestConfig/test_output_15496011472785/cmdLineTester_pltest_0/core"
         [ERR] 		LastErrorNumber: -108
         [ERR] 		LastErrorMessage: No such file or directory
         [ERR] 
         [ERR] 3: j9dump_test_create_dump_with_NO_name
         [ERR] 	j9dumpTest.c line  153: j9dump_create returned: 1, with filename: The core file created by child process with pid = 21853 was not found. Expected to find core file with name "core"
         [ERR] 		LastErrorNumber: -108
         [ERR] 		LastErrorMessage: No such file or directory
```

**Comment by jdekonin** [comment]
This would appear to be the `corefile not present` issue I highlighted in my previous comment.  The time between `Testing: Create core file` and `Testing: Run !printallcallsites` is only 1 second.  I'm not sure how reasonable it is to have the o/s generate a corefile in 1 second consistently.  The only error in the syslog is error to find.  There doesn't appear to be any error generated from trigger itself though.

@llxia this is where I mean there should be a check to verify that the `Testing: Create core file` actually generates a corefile.

**Comment by pshipton** [comment]
@jdekonin it is the VM/OMR that waits for the core file [1]. The test waits for the VM process to complete, and also checks the output for `System dump written`, which is a message output by the VM that should not be output until the renamed core is available. The core file is generated by the OS, which produces a file like core.123, and then the VM renames it to something else. 

[1] https://github.com/eclipse/omr/blob/f8fc704032f95cbc0f337eb6be54f2b06e58a773/port/linux/omrosdump_helpers.c#L543

@keithc-ca

**Comment by pshipton** [comment]
I've disabled ub16x64j91 for a while to see if these failures occur on another machine. I don't think they were occurring on the Softlayer machines.

**Comment by keithc-ca** [comment]
The OMR code waits at most 5 seconds (see [1] for example); apparently that's not sufficient.

[1] https://github.com/eclipse/omr/blob/f8fc704032f95cbc0f337eb6be54f2b06e58a773/port/linux/omrosdump_helpers.c#L560

**Comment by pshipton** [comment]
Apparently these machines are old and slow. Joe mentioned in https://github.com/eclipse/openj9/issues/4559#issuecomment-460333695 "I did notice that some of the times to generate a core on vmstart were taking between 8-10 seconds, 2 of the 20 as a sample size."

In https://github.com/eclipse/openj9/issues/4559#issuecomment-461843149 the output shows 11 seconds between "Create core file" and the next test.

Strange we haven't been seeing these types of failures internally or externally before now. I'm curious to see if the problem occurs on another machine now that ub16x64j91 is disabled.

**Comment by pshipton** [comment]
@jdekonin I haven't seen this problem occur since ub16x64j91 was disabled. Can this machine be replaced/retired?

**Comment by jdekonin** [comment]
@cwillhelm, I am pretty sure ub16x64j91 is likely the image 2-6 were generated from, correct?  Either way, can we get ub16x64j91 deleted and recreated please?

**Comment by pshipton** [comment]
@jdekonin @cwesMills do we have the resources at UNB to add more xlinux machines? xlinux is a backlogged platform, and we could use more machines if possible.

**Comment by jdekonin** [comment]
I think new machines should be a new issue.  We do have cpu for more, the current concern is tracking bandwidth wrt UNB hosted machines to make sure the recent increase hasn't made too big of an impact.

**Comment by pshipton** [comment]
@jdekonin I think we have had enough time with the new machines active to track the bandwidth. Are there any concerns so far? 

Created https://github.com/eclipse/openj9/issues/4710

**Comment by jdekonin** [comment]
Its been a 6-10 days and over 2 weekends so not the best sample size, but I haven't been looking at numbers/times at all.  @AdamBrousseau have you been monitoring?

**Comment by cwillhelm** [comment]
`ub16x64j91` has been re-created.

**Comment by jdekonin** [comment]
Machine has been added back into use on jenkins.  Please advise if there are problems with it.

**Comment by AdamBrousseau** [comment]
I had not been monitoring but a quick glance at the compile and test jobs show normal times for transferring to/from unb/jenkins master.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_x86-64_cmprssptrs/230/
```
Caused by: java.rmi.ConnectIOException: Exception creating connection to: 192.168.10.154; nested exception is: 
	java.net.NoRouteToHostException: No route to host (Host unreachable)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:631)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
	... 32 more
Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 37 more
```

**Comment by cwillhelm** [comment]
These machines are configured with DHCP, so whenever they are re-deployed they get a new IP. The new address for that host is  `192.168.10.182`

**Comment by pshipton** [comment]
The test doesn't have any IP address hard coded. It must have retrieved 192.168.10.154 from the machine somehow.

**Comment by cwillhelm** [comment]
@pshipton indeed, it appears `virt-sysprep` didn't modify `/etc/hosts` on startup. Updated the file to the proper IP.

**Comment by AdamBrousseau** [comment]
Can this be closed?

**Comment by adamfarley** [comment]
@pshipton @AdamBrousseau - We're seeing this symptom on sles12x64rt1-1. Could it be connected?

https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/78/consoleText

**Comment by pshipton** [comment]
It does look related, although we've never figured out why this problem occurs on some machines.
```
[2019-05-19T07:07:45.716Z]  [ERR] Starting test j9dump_test_create_dump_with_name
[2019-05-19T07:07:45.716Z]  [ERR]   calling j9dump_create with filename: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15582483558316/cmdLineTester_pltest_0/j9dump_test_create_dump_with_name
[2019-05-19T07:07:45.716Z]  [ERR] JVMPORT030W 
[2019-05-19T07:07:45.716Z]  [ERR] j9dumpTest.c line  213: j9dump_test_create_dump_with_name j9dump_create returned: 1, with filename: The core file created by child process with pid = 9671 was not found. Expected to find core file with name "/home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/TestConfig/test_output_15582483558316/cmdLineTester_pltest_0/core"
[2019-05-19T07:07:45.716Z]  [ERR] 
[2019-05-19T07:07:45.716Z]  [ERR] 		LastErrorNumber: -108
[2019-05-19T07:07:45.716Z]  [ERR] 		LastErrorMessage: No such file or directory
[2019-05-19T07:07:45.716Z]  [ERR] 
[2019-05-19T07:07:45.716Z]  [ERR] Ending test j9dump_test_create_dump_with_name
```
