### ISSUE TITLE
JTReg test fail - Windows & MacOS : java/net/httpclient/UnknownBodyLengthTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4593]
Intermittent failures ...

```
Stacktrace

Execution failed: `main' threw exception: java.io.IOException: http1_0 content, bytes received: 327490    

Standard Output

ServerSocket = class java.net.ServerSocket ServerSocket[addr=/127.0.0.1,localport=57437]
URL: http://localhost:57437/test
Accepted: /127.0.0.1:57438
Accepted: Socket[addr=/127.0.0.1,port=57438,localport=57437]
Content-Length: 327490

Received reply: 200
    

Standard Error

java.net.SocketException: Socket is closed
	at java.base/java.net.Socket.shutdownOutput(Socket.java:1551)
	at UnknownBodyLengthTest.server(UnknownBodyLengthTest.java:121)
	at UnknownBodyLengthTest.lambda$run$0(UnknownBodyLengthTest.java:161)
	at UnknownBodyLengthTest$$Lambda$40.00000000F0D9FBC0.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

... of test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/net/httpclient/UnknownBodyLengthTest.java observed on both Windows and Mac.

Latest failure on Windows and Mac ...

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows/122/testReport/java_net_httpclient_UnknownBodyLengthTest/java/UnknownBodyLengthTest/

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_macos/171/testReport/junit/java_net_httpclient_UnknownBodyLengthTest/java/UnknownBodyLengthTest/

A 100x run shows a 39% failure rate - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/969/consoleText

A 100x with -Xint run shows a 1% failure rate - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/972/consoleText

**Comment by ben-walsh** [comment]
I've kicked off a 400x with -Xint run - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/975

**Comment by adam-thorpe** [comment]
100x runs on both platforms have shown 100% pass rate so marking this as resolved and this can be closed

**Comment by pshipton** [comment]
@adam-thorpe I assume the test is being un-excluded?

**Comment by adam-thorpe** [comment]
@pshipton yep
