### ISSUE TITLE
Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs jsigjnitest_0 Cannot load module jre/lib/ppc64//libjvm.so

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4643]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs/536
```
===============================================
Running test jsigjnitest_0 ...
===============================================
jsigjnitest_0 Start Time: Thu Feb  7 03:01:51 2019 Epoch Time (ms): 1549530111836
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
Usage: jvmlibpath[-java options]

failed to open </usr/java8_64/jre/lib/ppc64//libjvm.so> - reason: <	0509-022 Cannot load module /usr/java8_64/jre/lib/ppc64//libjvm.so.
	0509-026 System error: A file or directory in the path name does not exist.>
Attempting to open /home/u0020236/workspace/Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/bin/../lib/ppc64/j9vm/libjvm.so
About to invoke JNI_CreateJavaVM with 2 option(s).
Starting test.
Primary handler set.
Secondary handler set.
Raising signal.
Test passed. Both signal handlers invoked.
Internal Error: Failed to initialize redirector - exiting

jsigjnitest_0_FAILED
```

**Comment by pshipton** [comment]
I expect this failing is intermittent. I saw it in an omr promotion build that didn't promote yesterday, but the subsequent build passed.

There seems to be a missing directory in the path, as the path should be `ppc64/compressedrefs/libjvm.so`. I'm going to guess this is a test problem.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs/586

**Comment by llxia** [comment]
Noticed the same failure in PR build: https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-aix_ppc-64_cmprssptrs-OpenJ9/428/tapResults/

**Comment by pshipton** [comment]
I haven't seen this failure in quite some time, I assume it is fixed.

**Comment by llxia** [comment]
Noticed this failure in PR build:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_Personal/39/tapResults/
