### ISSUE TITLE
RHEL7 nasm isn't new enough

### ISSUE THREAD

**Issue by FireBurn** [eclipse/openj9#4653]
The default nasm installed on RHEL7.6 is nasm-2.10.07-7.el7.x86_64 which fails with the following errors:

Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:784: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:785: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:786: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:787: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:788: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:789: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:790: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:791: error: mismatch in operand sizes
Compile_OpenJ9/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/x/runtime/X86Codert.nasm:792: error: mismatch in operand sizes

Manually compiling nasm 2.14.02 and adding it to the PATH works around the issue

Maybe a configure check can be added to test that the nasm version can deal with the above code

**Comment by 0xdaryl** [comment]
I believe @nbhuiyan is already working on the configure check as we speak.  Thanks for raising the issue.

**Comment by andrewcraik** [comment]
@nbhuiyan is this done?

**Comment by nbhuiyan** [comment]
@andrewcraik Yes it is. This issue can be closed.

**Comment by andrewcraik** [comment]
Closing as complete
