### ISSUE TITLE
Java 12 functional sanity failure cmdLineTester_jvmtitests_hcr

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4662]
I ran a Java 12 functional sanity test using the changes from #3980 and #4531.

https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK12-linux_ppc-64_cmprssptrs_le/2
cmdLineTester_jvmtitests_hcr_4
cmdLineTester_jvmtitests_hcr_8
cmdLineTester_jvmtitests_hcr_10
```
Testing: rtc001
Test start time: 2019/02/07 19:12:19 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test-sanity.functional-JDK12-linux_ppc-64_cmprssptrs_le/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xshareclasses:name=bcienabled,enableBCI  -Xdump    --add-opens=java.base/java.lang.reflect=ALL-UNNAMED -agentlib:jvmtitest=test:rtc001 -Dsun.reflect.noInflation=true  -cp "/home/jenkins/workspace/Test-sanity.functional-JDK12-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test-sanity.functional-JDK12-linux_ppc-64_cmprssptrs_le/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/asm-all.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 3 milliseconds
Time spent executing: 230 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/1]:	testUnsafeAccess
 [OUT] *** Test took 4 milliseconds
 [OUT] FAILED
 [OUT] 
 [ERR] java.lang.NoSuchFieldException: methodAccessor
 [ERR] 	at java.base/java.lang.Class.getDeclaredField(Class.java:901)
 [ERR] 	at com.ibm.jvmti.tests.retransformClasses.rtc001.testUnsafeAccess(rtc001.java:45)
 [ERR] 	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
 [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
 [ERR] 	at com.ibm.jvmti.tests.util.TestCase.run(TestCase.java:215)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:68)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:79)
 [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
>> Success condition was not found: [Return code: 0]
```

**Comment by pshipton** [comment]
@theresa-m @DanHeidinga @JasonFengJ9

**Comment by theresa-m** [comment]
It looks like this failure and https://github.com/eclipse/openj9/issues/4658 are related

**Comment by JasonFengJ9** [comment]
@theresa-m is right, this is due to same cause as per https://github.com/eclipse/openj9/issues/4658#issuecomment-461913909

**Comment by pshipton** [comment]
@JasonFengJ9 can we exclude this test, at least temporarily, to get green test results for jdk12.

**Comment by pshipton** [comment]
Similar failure in the following tests: rtc001
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-linux_390-64_cmprssptrs/2
cmdLineTester_jvmtitests_hcr_nongold_4
cmdLineTester_jvmtitests_hcr_nongold_8
cmdLineTester_jvmtitests_hcr_nongold_10
cmdLineTester_jvmtitests_hcr_OSRG_nongold_2
cmdLineTester_jvmtitests_hcr_OSRG_nongold_3
cmdLineTester_jvmtitests_hcr_OSRG_nongold_4

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-win_x86-64_cmprssptrs/1
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-osx_x86-64_cmprssptrs/1
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-linux_x86-64_cmprssptrs/2
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-aix_ppc-64_cmprssptrs/1
cmdLineTester_jvmtitests_hcr_OSRG_nongold_2
cmdLineTester_jvmtitests_hcr_OSRG_nongold_3
cmdLineTester_jvmtitests_hcr_OSRG_nongold_4

https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK12-linux_x86-64/1
cmdLineTester_jvmtitests_hcr_OSRG_nongold_0
cmdLineTester_jvmtitests_hcr_OSRG_nongold_1

```
 [ERR] java.lang.NoSuchFieldException: methodAccessor
 [ERR] 	at java.base/java.lang.Class.getDeclaredField(Class.java:905)
 [ERR] 	at com.ibm.jvmti.tests.retransformClasses.rtc001.testUnsafeAccess(rtc001.java:45)
 [ERR] 	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
 [ERR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
 [ERR] 	at com.ibm.jvmti.tests.util.TestCase.run(TestCase.java:215)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:68)
 [ERR] 	at com.ibm.jvmti.tests.util.TestSuite.run(TestSuite.java:79)
 [ERR] 	at com.ibm.jvmti.tests.util.TestRunner.main(TestRunner.java:60)
```

**Comment by JasonFengJ9** [comment]
This test might be able to use the package access method to get the restricted field `Method.methodAccessor`.

**Comment by pshipton** [comment]
@JasonFengJ9 please try that. We'll need to find better solutions than exclusion to get all these tests passing on jdk12.
