### ISSUE TITLE
Support for JVMTI 11.0 spec

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4667]
Java 11 and later should support the JVMTI 11.0 specification.

https://docs.oracle.com/en/java/javase/11/docs/specs/jvmti.html

jvmti.h contains JVMTI_VERSION_9_0 but not 11_0

**Comment by JasonFengJ9** [comment]
This will be addressed by https://github.com/eclipse/openj9/pull/3754 or https://github.com/eclipse/openj9/pull/4461.
