### ISSUE TITLE
Improved reporting in JMX MemoryPool MBean

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4674]
The JMX MemoryPool MBean should return the value of the max storage limits for the JIT Data Cache, Code Cache. These values default to 128 or 256M and can be set using -Xcodecachetotal.
 
Without this data users are not able to understand if they have sufficient (or too much) storage allocated for the JIT, and have to be aware of what the default maximum sizes are set as. In addition if the storage areas are exhausted then the data from the MBeans can not be used to determine this.

**Proposed Solution**

Return the max size of the JIT data cache and code cache areas using the max value for the following MBean attributes  (note currently this value returns -1)
a) java.lang->MemoryPool->JIT code cache->Attributes->Usage
b) java.lang->MemoryPool->JIT data cache->Attributes->Usage

**Comment by pshipton** [comment]
@joransiu @DanHeidinga

**Comment by PhilWakelin** [comment]
It would also be good to know if the storage reported from the MemoryPool MBean is in 31 or 64-bit as both the Class storage, and the JIT code cache can be above or below the bar, depending on compressedrefs or RMODE64.

**Comment by LinHu2016** [comment]
currently JMX MemoryPoolMXBean retrieves nonHeap Memory usage via memory segment (used and committed only), need a guideline for retrieving max size from JIT. Thanks

**Comment by joransiu** [comment]
@mpirvu

**Comment by mpirvu** [comment]
The limits are present in `jitConfig->codeCacheTotalKB` and `jitConfig->dataCacheTotalKB`

**Comment by LinHu2016** [comment]
Do ClassMemory and MiscMemory have limitation? currently the maxSize for both of them are -1.

**Comment by LinHu2016** [comment]
Hi @mpirvu, could you please confirm if seg->heapAlloc and seg->size has been updated in runtime(for both jitConfig->dataCacheList and jitConfig->codeCacheList), someone reports commit size and used size of JIT Data Cache and Code Cache have never been changed.

**Comment by fjeremic** [comment]
@mpirvu FYI the above if you missed it.
