### ISSUE TITLE
OpenJDK8 Sanity test failure pair in suite cmdLineTester_SCHelperCompatabilityTests_unix_1 on PPCLE

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#469]
When running the OpenJDK8 OpenJ9 sanity tests on PPCLE, we see a pair of HelperCompatabilityTest failures in the cmdLineTester_SCHelperCompatabilityTests_unix_1 suite. I've included the full error output in the first issue comment.

To build OpenJDK8 with OpenJ9, use the unreleased extensions here: https://github.ibm.com/runtimes/openjdk-jdk8

Note: To build, you will need to perform two manual changes, as the work to make the changes automated hasn't been finished yet

1. Use OpenJDK 7 as the boot jdk. Easiest way to do this is to run the commands below in the docker container and add the java executable directory to the start of the path. New dockerfiles will eventually be available with this logic.

apt-get update
apt-get install software-properties-common python-software-properties
apt-get update
add-apt-repository ppa:openjdk-r/ppa
apt-get install openjdk-7-jdk libfontconfig

2. Modify the openj9/sourcetools/buildj9tools.mk file so that the following lines say "7" instead of "8".

JAVA := java8
SPEC_LEVEL ?= 8

Note: the 1.8.0 bit shouldn't need to be modified, as we shouldn't be using that code path.

**Comment by adamfarley** [comment]
Testing: HelperCompatabilityTest 9
Running command: "/home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses -Xbootclasspath/a:./Utils:. URLClassPathHelperURLHelperStaleEntryCompatabilityTest -testfile "/home/cloudusr/builds/java8/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/props_unix/Test8.props" -javacdir /home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../../bin
Test result: FAILED
 [OUT] 
 [OUT] ** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../../bin
 [OUT] Here is the standard output of the command:
 [OUT] 
 [OUT] added manifest
 [OUT] adding: B.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: C.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: D.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: E.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: F.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: X.class(in = 298) (out= 234)(deflated 21%)
 [OUT] Here is the standard error of the command (if any):
 [OUT] 
 [OUT] 
 [OUT] ** urlsString: ./AlphabetJar/Alphabet.jar;
 [OUT] 
 [OUT] Failure finding class: D on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: E on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: F on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

Testing: HelperCompatabilityTest 11
Running command: "/home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses -Xbootclasspath/a:./Utils:. URLHelperURLClassPathHelperStaleEntryCompatabilityTest -testfile "/home/cloudusr/builds/java8/openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/props_unix/Test10.props" -javacdir /home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../../bin
Test result: FAILED
 [OUT] 
 [OUT]  Incorrect usage
 [OUT] 
 [OUT]  Please specifiy -testfile <filename> -javacdir <path to javac>
 [OUT] 
 [OUT] ** urlsString: ./AlphabetJar/Alphabet.jar;./Pets;:./Vowels;:
 [OUT] 
 [OUT] ** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../../bin
 [OUT] Here is the standard output of the command:
 [OUT] 
 [OUT] added manifest
 [OUT] adding: B.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: C.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: D.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: E.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: F.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: X.class(in = 298) (out= 234)(deflated 21%)
 [OUT] Here is the standard error of the command (if any):
 [OUT] 
 [OUT] 
 [OUT] Failure finding class: A result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: E result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: F result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

**Comment by hangshao0** [comment]
This is the same issue as #470

**Comment by pshipton** [comment]
The fix #568 for #470 is merged, but these tests are still failing on Java 8.

**Comment by hangshao0** [comment]
Same issue, but different sub-tests. I will fix the failing sub-tests here.
