### ISSUE TITLE
OpenJDK8 Sanity test failure in suite cmdLineTester_SCURLHelperTests_80_1 on PPCLE

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#470]
When running the OpenJDK8 OpenJ9 sanity tests on PPCLE, we see a single failuree in the cmdLineTester_SCURLHelperTests_80_1 suite. I've included the full error output in the first issue comment.

To build OpenJDK8 with OpenJ9, use the unreleased extensions here: https://github.ibm.com/runtimes/openjdk-jdk8

Note: To build, you will need to perform two manual changes, as the work to make the changes automated hasn't been finished yet

1. Use OpenJDK 7 as the boot jdk. Easiest way to do this is to run the commands below in the docker container and add the java executable directory to the start of the path. New dockerfiles will eventually be available with this logic.

apt-get update
apt-get install software-properties-common python-software-properties
apt-get update
add-apt-repository ppa:openjdk-r/ppa
apt-get install openjdk-7-jdk libfontconfig

2. Modify the openj9/sourcetools/buildj9tools.mk file so that the following lines say "7" instead of "8".

JAVA := java8
SPEC_LEVEL ?= 8

Note: the 1.8.0 bit shouldn't need to be modified, as we shouldn't be using that code path.

**Comment by adamfarley** [comment]
Testing: URLStaleClassPathEntryTest 4
Running command: "/home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses -Xbootclasspath/p:./Utils:.; StaleClassPathEntryTests.URLStaleClassPathEntryTest -testfile ./StaleClassPathEntryTests/props_unix/Test4.props -javacdir /home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../../bin
Test result: FAILED
 [OUT] 
 [OUT] ** urlsString: ./AlphabetJar/Alphabet.jar;
 [OUT] classToLoad = B
 [OUT] classToLoad = E
 [OUT] 
 [OUT] ** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /home/cloudusr/builds/java8/openjdk-jdk8/build/linux-ppc64-normal-server-release/images/j2sdk-image/jre/bin/../../bin
 [OUT] Here is the standard output of the command:
 [OUT] 
 [OUT] added manifest
 [OUT] adding: B.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: C.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: D.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: E.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: F.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: X.class(in = 298) (out= 234)(deflated 21%)
 [OUT] Here is the standard error of the command (if any):
 [OUT] 
 [OUT] testResult = "false"
 [OUT] urlIndex = "0"
 [OUT] classToFind = "B"
 [OUT] 
 [OUT] Failure finding class: B on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] testResult = "false"
 [OUT] urlIndex = "0"
 [OUT] classToFind = "E"
 [OUT] 
 [OUT] Failure finding class: E on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

**Comment by hangshao0** [comment]
We have the same issue in Java 9: (I believe the problem is the same in Java 8)

```
java  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses --add-modules openj9.sharedclasses --add-reads java.base=openj9.sharedclasses --patch-module java.base=./Utils:. StaleClassPathEntryTests.URLStaleClassPathEntryTest -testfile ./StaleClassPathEntryTests/props_unix/Test4.props -javacdir /bluebird/builds/bld_368596/sdk/xa6490/bin

** urlsString: ./AlphabetJar/Alphabet.jar;
classToLoad = B
classToLoad = E

** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /bluebird/builds/bld_368596/sdk/xa6490/bin
Here is the standard output of the command:

added manifest
adding: B.class(in = 298) (out= 233)(deflated 21%)
adding: C.class(in = 298) (out= 233)(deflated 21%)
adding: D.class(in = 298) (out= 233)(deflated 21%)
adding: E.class(in = 298) (out= 233)(deflated 21%)
adding: F.class(in = 298) (out= 233)(deflated 21%)
adding: X.class(in = 298) (out= 234)(deflated 21%)
Here is the standard error of the command (if any):

testResult = "false"
urlIndex = "0"
classToFind = "B"

Failure finding class: B on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
testResult = "false"
urlIndex = "0"
classToFind = "E"

Failure finding class: E on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true

TEST FAILED
```

But if I run with -Xshareclasses:noTimeStampChecks, I will pass the test:

```
java -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:noTimeStampChecks --add-modules openj9.sharedclasses --add-reads java.base=openj9.sharedclasses --patch-module java.base=./Utils:. StaleClassPathEntryTests.URLStaleClassPathEntryTest -testfile ./StaleClassPathEntryTests/props_unix/Test4.props -javacdir /bluebird/builds/bld_368596/sdk/xa6490/bin

** urlsString: ./AlphabetJar/Alphabet.jar;
classToLoad = B
classToLoad = E

** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /bluebird/builds/bld_368596/sdk/xa6490/bin
Here is the standard output of the command:

added manifest
adding: B.class(in = 298) (out= 233)(deflated 21%)
adding: C.class(in = 298) (out= 233)(deflated 21%)
adding: D.class(in = 298) (out= 233)(deflated 21%)
adding: E.class(in = 298) (out= 233)(deflated 21%)
adding: F.class(in = 298) (out= 233)(deflated 21%)
adding: X.class(in = 298) (out= 234)(deflated 21%)
Here is the standard error of the command (if any):


TEST PASSED
```

**Comment by hangshao0** [comment]
The reason for not finding classes "B" and "E" is that the timestamp of Alphabet.jar has changed. 
We hit the following condition in SH_TimestampManagerImpl::localCheckTimeStamp():
`if (current == -1) {
		if (test == -1) {
			return TIMESTAMP_DOES_NOT_EXIST;
		} else {
			return TIMESTAMP_DISAPPEARED;
		}
	} else {
		if (current == test) {
			return TIMESTAMP_UNCHANGED;
		} else {
			**return current;**
		}
	}`

Looking at the code in URLStaleClassPathEntryTest.executeTest(), it has:
		```
/*Sleep for 2 s ... otherwise time stamps may not match ...*/
		try {
			Thread.sleep(2000);
		} catch (Exception e) {
			e.printStackTrace();
		}
```

I guess 2s is not sufficient ?

**Comment by hangshao0** [comment]
Unfortunately increasing the 2s sleep time does not fix this issue. Something else is going on.

**Comment by hangshao0** [comment]
OK, I know what is happening. 

This is what the testing code is doing:
1. store classes B and E from Alphabet.jar to the shared cache.
2. modified the jar file after 2s.
3. try finding the classes B and E from the shared cache.  

We shouldn't return classes B and E from the shared cache as the jar (and its timestamp) has been updated. So our behaviour is correct in this case. 

I will fix the test code. The expected test result should be changed to "false".
