### ISSUE TITLE
Create more xlinux machines 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4710]
Please create more xlinux machines. As per https://github.com/eclipse/openj9/issues/4559#issuecomment-462832715 we have the CPUs at UNB to create more xlinux machines. I've often seen this platform backlogged due to the large heap builds and cmake builds that occur on xlinux.

**Comment by pshipton** [comment]
@jdekonin @cwillhelm

**Comment by jdekonin** [comment]
We can look into this at some point next week.  There was discussion on moving xlinux to cent6 as its the lowest supported glibc platform.  So this might be a good opportunity to do this cutover.

**Comment by AdamBrousseau** [comment]
Related #4063

**Comment by jdekonin** [comment]
DIscussed in more detail with @pshipton.  He would like to add 4 ub16 images right away as that can be done quickly.  Once we have a cent6 image setup and functional we can visit converting ub16 -> cent6.  We'll track that work under #4063.

**Comment by cwillhelm** [comment]
```
ub16x64j97 
ub16x64j98 
ub16x64j99 
ub16x64j910 
```

Have been created, IPs / login info is on GHE / Slack.

**Comment by AdamBrousseau** [comment]
Added to Jenkins
Builds running
https://ci.eclipse.org/openj9/view/Build/job/Build-JDK11-linux_x86-64/640/
https://ci.eclipse.org/openj9/view/Build/job/Build-JDK11-linux_x86-64/641/
https://ci.eclipse.org/openj9/view/Build/job/Build-JDK11-linux_x86-64/642/
https://ci.eclipse.org/openj9/view/Build/job/Build-JDK11-linux_x86-64/643/
Tests running
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64/511/
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64/512/
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64/513/
https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64/514/

**Comment by AdamBrousseau** [comment]
All passes. Machines enabled in farm.

**Comment by vsebe** [comment]
CentOS6 x86
Builds:
[Build-JDK8-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_x86-64_cmprssptrs/1159/)
[Build-JDK11-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Build-JDK11-linux_x86-64_cmprssptrs/746/)

Tests:
[Test-extended.functional-JDK8-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-linux_x86-64_cmprssptrs/269/)
[Test-extended.system-JDK8-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_x86-64_cmprssptrs/228/)
[Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-linux_x86-64_cmprssptrs/755/)
[Test-sanity.system-JDK8-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/271/)

[Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/652/)
[Test-extended.functional-JDK11-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK11-linux_x86-64_cmprssptrs/218/)
[Test-sanity.system-JDK11-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/224/)
[Test-extended.system-JDK11-linux_x86-64_cmprssptrs](https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_x86-64_cmprssptrs/218/)

**Comment by vsebe** [comment]
We'll add 6 more systems - CentOS 6 x86 - from UNB too - see #4063
