### ISSUE TITLE
Test target/group discussion

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#473]
We support sanity, extended, openjdk, external, perf group in test. And a systemtest group will be added in the near future. Currently these groups contain different tests and they are defined at the same level. A user can run one or more targets, but not combined.

This issue is an open discussion of how we should move forward to support our testing. Below are some options that we have:

1. we can make sanity and extended to be the top level group, and define everything else as subgroup. So we have 
   - sanity.systemtest 
   - sanity.openjdk
   - extended.perf
   ...

2. we can have openjdk, external, perf  and systemtest group to be the top level, and define sanity and extend as subgroups.
   - fvtest.sanity
   - systemtest.sanity
   - systemtest.extended
   ...

**Comment by smlambert** [comment]
Summary of some recent discussions, we pull tests from various locations:

- functional tests live in openj9
- system tests live at adoptopenjdk and openj9
- openjdk regression tests live at openjdk (and clones of that repo)
- external tests (currently 3rd party applications) live in their respective repos (i.e. community tests from scala, derby, etc)
- perf tests are benchmarks from various locations
- jck tests under special license 

Our testkitgen framework supports running of all of these various tests (from various repos) in a standardized way.  We will also support the categorization of those top-level targets/groups.  By tagging a test (from what ever repo it originates) with a "sanity" tag, we cause it to be included in PR builds. 

For the usage question posed by this issue, it seems natural to invoke the test group by your suggested:
make sanity => run all the tests tagged with the sanity tag
make sanity.function => run the functional tests tagged with sanity
make sanity.system => run the system tests tagged with sanity
etc.

**Comment by smlambert** [comment]
Closing as this is fulfilled by #976
