### ISSUE TITLE
java.security.manager=disallow in jdk12

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4734]
See setSecurityManager() in http://cr.openjdk.java.net/~iris/se/12/build/latest/api/java.base/java/lang/System.html

```
Implementation Note:
In the JDK implementation, if the Java virtual machine is started with the system property java.security.manager set to the special token "disallow" then the setSecurityManager method cannot be used to set a security manager
```

**Comment by pshipton** [comment]
@JasonFengJ9 @DanHeidinga

**Comment by JasonFengJ9** [comment]
Will take this.

**Comment by pshipton** [comment]
Also see the table in the description for http://cr.openjdk.java.net/~iris/se/12/build/latest/api/java.base/java/lang/SecurityManager.html

"allow" is also permitted.

**Comment by pshipton** [comment]
Might check with a test case to see if jdk8 should support "disallow" and "allow".
