### ISSUE TITLE
Improve handling of endianness in the VM and JIT

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#4741]
As part of #4688 we made a slight change in some test cases to make use of the `java.nio.ByteOrder` utilities provided in the standard library. Namely the `nativeOrder()` static function which returns endianness of the execution environment. This value is actually a compile time constant which should enable the JIT to fold away quite some code.

Grepping the codebase there are several uses of this API, and we're bound to get more. In fact a major one comes from the String API which we'll need to improve here. There are several tasks we can accomplish:

---

- [ ] Deprecate the `IS_PLATFORM_LITTLE_ENDIAN` in favor of `java.nio.ByteOrder`

We created a custom native function to determine the endianness at startup. This is duplicate code and we should just use the standard library instead.

[1] https://github.com/eclipse/openj9/blob/35c44ead49a53f8c0ad1ca3e63c18711d3a7b26f/jcl/src/java.base/share/classes/com/ibm/jit/JITHelpers.java#L82

---

- [ ] Make use of the `(get|put)ByteInArrayByIndex` JITHelper APIs in #4688 to extract and zero out bytes instead of using the `java.nio.ByteOrder`

In [2] instead of checking the `byteOrder` we should just use the JITHelper APIs to get and put a zero byte into the right index into the `char[]`, similarly to how we do it in String.java. There are many examples there.

[2] https://github.com/eclipse/openj9/pull/4688/files#diff-fe67427200feb55170a5f1cce53462a1R385

---

- [ ] Teach the JIT to fold away a call to `java.nio.ByteOrder.nativeOrder()` to a load of the respective static field at IL generation time

I think we can safely disregard HCR here and simply fold away the call because the native order of the execution environment cannot and should not change, no matter what the user says as critical parts of the JVM depend on it. This is similar to the compression check in String.java.

I'll reference #2381 for this one as we definitely have the power to skip HCR guards on intrinsically reduced methods.

**Comment by gacholio** [comment]
` Teach the JIT to fold away a call to java.nio.ByteOrder.nativeOrder() to a load of the respective static field at IL generation time`

This is a compile-time constant, there's no need to load anything.

**Comment by fjeremic** [comment]
> This is a compile-time constant, there's no need to load anything.

@gacholio unfortunately this is only the case for JDK11, not JDK8. I checked the source code for this anomaly [1] [2].

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/4d2b0d68a3fbb3c0fc3d0ab5821e0908e2b077bd/jdk/src/share/classes/java/nio/ByteOrder.java#L71-L73
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/455c2c304c24257edff886e543cf18f95c4bb785/src/java.base/share/classes/java/nio/ByteOrder.java#L78-L80

**Comment by fjeremic** [comment]
I'm also not sure if the JIT will even fold it away in JDK11, part of this work item should be to verify what exactly the JIT does in JDK11 and JDK8.

**Comment by gacholio** [comment]
Then let's get it fixed properly in the java code - it is clearly a constant for the entire run the of the VM.

Better yet, let's just ignore it - you already recognize all sorts of methods. Any change to this method to make it incorrect would clearly bring down the VM, so there's no danger.

**Comment by fjeremic** [comment]
> Then let's get it fixed properly in the java code - it is clearly a constant for the entire run the of the VM.

Can we even do this? We can easily fix it by just copying the JDK11 implementation into JDK8. Are we allowed to do this "backport" effectively? Not sure what the legalities are since it's OpenJDK code.

**Comment by gacholio** [comment]
Sorry, my point is you already recognize things that could be meaningfully modified (and presumably ignore the mods), so this is clear candidate for translation to compile-time constant.

**Comment by pshipton** [comment]
There doesn't seem to be anything happening for this so I'll move it to the next release.

**Comment by fjeremic** [comment]
Thanks for reminding me about this one Peter. We have someone lined up to do the work so only a matter of time.

**Comment by fjeremic** [comment]
I believe @simonameng is working on this at the moment, but it is a nice to have thing addressed. I don't think this should block the 0.18.0 release.
