### ISSUE TITLE
Why are monexit trees anchored to a treetop?

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#475]
Just grabbed a log of `java/lang/StringBuffer.length()I` and I see the following:

```
n13n      monent  jitMethodMonitorEntry[#178  helper Method]
n18n        ==>aRegLoad
...
n10n      treetop
n9n         monexit  jitMethodMonitorExit[#33  helper Method]
n18n          ==>aRegLoad
```

Is there a reason for this asymmetry between `monent` and `monexit`? Are there cases where `monexit` is not under a `treetop`?

**Comment by andrewcraik** [comment]
monexit is not required to be under a treetop - it can be at the top level and a moment can be under a treetop I believe.

**Comment by fjeremic** [comment]
Is there a reason why one may choose to anchor such nodes under a `treetop` as opposed to the nodes themselves being TreeTop nodes?

**Comment by ymanton** [comment]
Both `monent` and `monexit` can themselves be treetops as far as I know. Maybe your `monexit` used to be under a `nullchk` that was later removed and replaced with that `treetop` node?

**Comment by fjeremic** [comment]
> Maybe your monexit used to be under a nullchk that was later removed and replaced with that treetop node?

Bingo. This was the case exactly. Interesting that we have a `NULLCHK` on the `monexit` rather than the `monent` though.

**Comment by DanHeidinga** [comment]
There's some great information here which I've tried to capture in PR #512.  It's a very rough start at an FAQ for these kinds of questions.

As this question appears to have been answered, I'm closing this issue.
