### ISSUE TITLE
JVM_INTERFACE_VERSION changed to 6 in JDK11,12,13

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#4770]
OpenJDK have just incremented the JVM_INTERFACE_VERSION to 6 with bug:
  https://bugs.openjdk.java.net/browse/JDK-8216302
This has been pushed to JDK11,12,13 and has already auto-merged into our jdk11, 12&head to follow..

**Comment by pdbain-ibm** [comment]
It is breaking the builds: https://ci.eclipse.org/openj9/job/Build-JDK11-linux_x86-64/615/console
What's the plan to fix it?

**Comment by DanHeidinga** [comment]
@andrew-m-leonard What other changes are required from the VM to support the new interface level?  Where JVM_ functions added or removed?

**Comment by JasonFengJ9** [comment]
@andrew-m-leonard please push this `JVM_INTERFACE_VERSION` to `JDK12` & HEAD. Current `JDK12` PR build failed with `Fatal error: JVM interface version mismatch: expecting 5, got 6.`.

**Comment by pshipton** [comment]
This is the change which modified the version
`8216302: StackTraceElement::fill_in can use cached Class.name`
JVM_GetClassName was changed to JVM_InitClassName
OpenJ9 does have an implementation, but I suspect it was added for a project to use more OpenJDK classes as-is, and the OpenJ9 implementation is not used.

I don't see the same change in OpenJDK jdk12, but I do for jdk. The jdk12 project is in Release-Candidate Phase and may not get the change until the next release. I suggest OpenJ9 only make the version change for jdk11 and 13 at this time.

**Comment by andrew-m-leonard** [comment]
As Peter refers to it looks like jdk12 is on ramp-down at OpenJDK, so this change will probably be in 12.0.1.
I have kicked off a jdk13 merge-job again, it failed the last few times due to jenkins issues...

**Comment by DanHeidinga** [comment]
Java 12.1 will need the version update and then this should be complete

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/issues/5223 was opened for jdk12. I'll close this one.
