### ISSUE TITLE
JDK 8 build errors e.g. 'package com.ibm.oti.shared does not exist'

### ISSUE THREAD

**Issue by davehobbs** [eclipse/openj9#4780]
Trying to build DK 8 with Open J9 on a local ubuntu 16 04 machine. The builds are logging a number of error messages which are also present on the AdoptOpenJDK job output e.g:

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/227/consoleFull

`data/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/jdk/src/share/classes/java/io/ObjectInputStream.java:341: error: cannot find symbol
     private static final ClassCache classCache;
                          ^
  symbol:   class ClassCache
  location: class ObjectInputStream
/data/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/jdk/src/share/classes/sun/misc/URLClassPath.java:65: error: package com.ibm.oti.shared does not exist
import com.ibm.oti.shared.CannotSetClasspathException;`

Strangely the build does complete. However the error messages don't seem right.

**Comment by pshipton** [comment]
I expect it is a build problem on the extensions side of things, not with OpenJ9 itself. Something is missing from the path in order to find the OpenJ9 classes.

Seems something to do with awt. The following is what comes before.
```
Generating Nimbus source files
[Error] encoded value was less than 0: encode(-8.326673E-17, 5.0, 11.0, 16.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] encoded value was greater than 3: encode(15.029411, 1.0, 14.0, 15.0)
[Error] encoded value was less than 0: encode(-0.05882353, 1.0, 24.0, 25.0)
[Error] Encountered Infinity: encode(-0.00877193, 0.0, 7.0, 7.0)
Verifying /data/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/build/linux-x86_64-normal-server-release/jdk/gensrc_x11wrappers/sizes.64.verification.tmp to /data/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-x64-openj9/workspace/build/src/build/linux-x86_64-normal-server-release/jdk/gensrc_x11wrappers/sizes.64
```

**Comment by keithc-ca** [comment]
These messages can safely be ignored.

The first is triggered by line 7302 of `jdk/src/share/classes/javax/swing/plaf/nimbus/skin.laf`:
```
    <point x="11.304347826086955" y="-8.326672684688674E-17" cp1x="11.304347826086955" cp1y="-8.326672684688674E-17" cp2x="11.304347826086955" cp2y="-8.326672684688674E-17"/>
```
In Java 11 (and later versions) such messages are only emitted if the [`debug`](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/make/jdk/src/classes/build/tools/generatenimbus/PainterGenerator.java#L61) flag is true; e.g. see [PainterGenerator.java](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/make/jdk/src/classes/build/tools/generatenimbus/PainterGenerator.java#L400)
