### ISSUE TITLE
Save AOT Compilation Failure Information in Shared Class Cache

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#4786]
If an AOT compilation fails for reasons that we know it will fail again, such as the type of methods is not supported by AOT compilation, we can mark it in SCC after the first time we fail to AOT compile it. In the subsequent runs, this information in SCC will prevent us from trying to AOT compile the same method and fail again, instead we choose to JIT compile the method directly.

**Comment by mpirvu** [comment]
This could be done with an AOT hint, though we may need to enlarge the size of the 'word' for it. I remember that all bits are used at the moment.

**Comment by dsouzai** [comment]
`TR_HintInline` isn't used anywhere; it could be reused I think.

**Comment by a7ehuo** [comment]
@mpirvu @dsouzai I tested the change of adding hints when compilation fails due to `compilationAotHasInvokehandle` or `compilationAotHasInvokeVarHandle`. The change has to be enabled by `Xaot:enableSCHint=2` which is `TR_HintInline`. As Marius predicated, there is no performance gain.  

1. With this test result, should we still add this change?
2. If so, should `TR_HintInline` be changed into `TR_HintMethodHandle`? Or expand the size of `TR_SharedCacheHint` accommodate more hints in the future?

**Comment by mpirvu** [comment]
Note that using `Xaot:enableSCHint=2` will enable your new hint but disable all the other hints that are set by default.

Increasing the number of hints we support requires changes in the VM. It's better not to spend too much on an item that doesn't provide an advantage.

**Comment by a7ehuo** [comment]
@mpirvu Yes, setting `Xaot:enableSCHint=2` overrides the default hints. It's a quick way to test this theory. Agreed. Let's leave this item as it is now.

**Comment by dsouzai** [comment]
Let's close this issue then; it can be reopened when this is worth pursuing.
