### ISSUE TITLE
VirtualMachine.list() doesn't work across JVM variants

### ISSUE THREAD

**Issue by martinlippert** [eclipse/openj9#4799]
We are using VirtualMachine.list() to identify running Java processes in the local machine to connect to them via JMX later on.

But it looks like when running this on an OpenJ9 variant of the JDK the call can only identify running JVMs that are based on OpenJ9, not others - and vice versa.

You can reproduce this easily by starting `jconsole` from an Oracle JDK, it doesn't list any processes that are running on an OpenJ9 VM.

This turns out to be somewhat problematic for us, since we use this inside of an IDE (Spring Tools 4) and we cannot assume that people use the same JVM variant to run the IDE than they use to run their apps from within the IDE.

Any thoughts on this?

(originated from tests around this issue here: https://github.com/spring-projects/sts4/issues/138)

**Comment by pdbain-ibm** [comment]
@martinlippert 
Thank you for your comment.  The restriction to attaching to a JVM's own kind is a known limitation of both the HotSpot and OpenJ9 implementations of Attach API.  While the Attach API specifies the interface to application code, it does not specify the discovery or communication protocols.  As the HotSpot implementation is proprietary and undocumented, OpenJ9 does not claim or provide compatibility with it.

**Comment by martinlippert** [comment]
@pdbain-ibm Okay, I understand the reasons now, thanks for providing the details, much appreciated. Do you have any thoughts on maybe a different way to identify JVM processes on the local machine in an JVM-implementation-independent way? I somehow cannot stop thinking about a different/better solution for this JVM process discovery and JMX attaching... :-)

**Comment by pdbain-ibm** [comment]
There are a couple of options.  If your application has access to the launcher of both JVM types, it could launch child OpenJ9 and HotSpot JVMs with a small application which calls `VirtualMachine.list()` in both, and combines the results.  A HotSpot JVM could also discover the VMs the same way OpenJ9 does, by scanning the attach API common directory, though that is tricky.

Probably the best way is to run both variants' copies of `jps -q` (I am polishing up the pull request right now)) and scrape the list from stdout.

**Comment by martinlippert** [comment]
Hey @pdbain-ibm thanks a lot for the feedback and the input, much appreciated. Will be food for thought on our end.
