### ISSUE TITLE
Clean up JPP configurations

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#4800]
`jpp_configuration.xml` contains a number of configurations which are unused or now invalid.
To prevent spurious errors when regression testing, suggest deleting the following:

- `SIDECAR19-SE-B148` (Java 9 is dead)
- `SIDECAR19-SE-B136`
- `SIDECAR19-SE-OPENJ9`
- `SIDECAR19-SE_RAWPLUSJ9`
- `SIDECAR18-TOOLS-OPENJ9`  (won't build)

Do we still need these?

- `SIDECAR18-DAA`
- `SIDECAR18-DTFJ`
- `SIDECAR18-DTFJVIEW`
- `SIDECAR18-TRACEFORMAT`
- `SIDECAR18-TOOLS-OPENJ9`

`PANAMA` should be updated depend on JAVA11

attn: @pshipton @tajila @keithc-ca @fjeremic

**Comment by pshipton** [comment]
> Do we still need these?
    * `SIDECAR18-DAA` - yes
    * `SIDECAR18-DTFJ` - yes
    * `SIDECAR18-DTFJVIEW` - yes
    * `SIDECAR18-TRACEFORMAT` - yes
    * `SIDECAR18-TOOLS-OPENJ9` - no

**Comment by fjeremic** [comment]
@pshipton I thought we bundle DAA in rt.jar in OpenJ9? Is the `SIDECAR18-DAA` for generating dataaccess.jar for internal builds?

**Comment by pshipton** [comment]
> Is the `SIDECAR18-DAA` for generating dataaccess.jar for internal builds?

Correct. All of DAA, DTFJ, DTFJVIEW, TRACEFORMAT are for internal builds.

**Comment by pdbain-ibm** [comment]
Working on this in the background...
Pausing until 0.13 is released.

**Comment by keithc-ca** [comment]
Reopening: #4867 was reverted.

**Comment by keithc-ca** [comment]
Fixed via #4911.
