### ISSUE TITLE
xlinux build machines don't have the minimum cmake level

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4809]
What cmake version do the xlinux machines use?

Ubuntu 16 comes with cmake ~4.5.1~ 3.5.1, but apparently code was merged that doesn't work on this version, yet the problem was not found in the OpenJ9 builds.

**Comment by pshipton** [comment]
@jdekonin @keithc-ca

**Comment by pshipton** [comment]
The cmake builds shows `Starting with CMake version 3.11.4`

- @jdekonin do you know why we have this much newer version of cmake?

- If we are going to support the default cmake that comes with Ubuntu 16, and get included in the OpenJ9 docker images, we should downgrade the build machines.

@dnakamura fyi

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by jdekonin** [comment]
The playbooks explicitly install v3.11.4, which was newer than the initial v3.7.4 requirement set by @dnakamura on first being added to the playbooks.  

I can check why, but my guess is that v4.5.1 must have been installed via a package manager dependency and overwrote the playbooks install.

Either way, v3.11.4 is what is wanted correct?  Not v4.5.1.  Do I need to wait/coordinate that change?

**Comment by keithc-ca** [comment]
The top level cmake file says:
```
cmake_minimum_required(VERSION 3.4 FATAL_ERROR)
```
The version that you get via `apt install cmake` on Ubuntu 16.04 is 3.5.1.

**Comment by pshipton** [comment]
@jdekonin note I had a typo which is fixed now. I meant 3.5.1 and not 4.5.1

As Keith pointed out, 3.5.1 is what you get by default on Ubuntu 16 vai `apt install cmake`
As this is what the example docker files do, they also get 3.5.1 installed.

If we need a newer version as the minimum (3.7.4 or whatever), we'll have to update the docker files and the build instructions when switching to cmake. Otherwise, we should down grade the openj9 build machines to have the minimum level supported, otherwise we cannot guarantee it keeps working.

**Comment by jdekonin** [comment]
Can you please change the summary accordingly?

I didn't realize the cmake version had changed to v3.11.4.  It appears the playbooks were updated to accommodate a JFX build requirement.  If this isn't a good version for OpenJ9 I can make the addition/change.

fyi @AdamBrousseau, docker file changes to the version of cmake are required.
