### ISSUE TITLE
Jsr292 Extended Test Failures

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#481]
Extended tests failures need to be fixed before adding Jsr292 tests to run in OpenJ9.

See https://github.com/eclipse/openj9/pull/439 for enabling.

**Comment by DanHeidinga** [comment]
@theresa-m Thanks for opening the issue.  Can you provide a link to the failing tests or add the details here?  It makes it easier for who ever picks up the issue to know what they need to look at.

**Comment by theresa-m** [comment]
These were the failing tests: https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-linux_390-64_cmprssptrs/36/testReport/
