### ISSUE TITLE
extended.functional testing failed to run on ppcle - Can't locate XML/Parser.pm

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4830]
PR testing started from #4628
https://ci.eclipse.org/openj9/job/PullRequest-Extended-JDK11-linux_ppc-64_cmprssptrs_le-OpenJ9/26]
ub16-ppcle-3
```
23:48:59  + make -f run_configure.mk
23:48:59  perl configure.pl
23:48:59  cd /home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK11-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/test/TestConfig/scripts/testKitGen; \
23:48:59  perl testKitGen.pl --graphSpecs=linux_ppc-64_cmprssptrs_le --jdkVersion=11 --impl=openj9 --buildList= --iterations=1 --testFlag= ; \
23:48:59  cd /home/jenkins/jenkins-agent/workspace/PullRequest-Extended-JDK11-linux_ppc-64_cmprssptrs_le-OpenJ9/openj9/test/TestConfig;
23:48:59  Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: ./makeGenTool /etc/perl /usr/local/lib/powerpc64le-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/powerpc64le-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/powerpc64le-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/powerpc64le-linux-gnu/perl-base .) at makeGenTool/mkgen.pl line 28.
23:48:59  BEGIN failed--compilation aborted at makeGenTool/mkgen.pl line 28.
23:48:59  Compilation failed in require at testKitGen.pl line 31.
```

**Comment by pshipton** [comment]
@smlambert @jdekonin 

In case it is a machine issue, I've disabled the machine.

**Comment by smlambert** [comment]
Machine needs [test prereqs](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) installed.

**Comment by pshipton** [comment]
Re-run on ub16p8j92 worked.

Nightly builds failed on ub16-ppcle-2 - disabled it.
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK11-linux_ppc-64_cmprssptrs_le/182/
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK8-linux_ppc-64_cmprssptrs_le/198/

**Comment by pshipton** [comment]
Did the test prereqs change, or did the machines change?

**Comment by pshipton** [comment]
Seems zos testing has the same issue.
`Can't locate XML/Parser.pm in @INC`

**Comment by smlambert** [comment]
Related: 
internal infra issue (infrastructure/issues/1071) - this referenced updates on external openj9 machines, so perhaps should have an open / openj9 issue related to it
<img width="575" alt="screen shot 2019-02-22 at 9 26 34 am" src="https://user-images.githubusercontent.com/2836948/53248572-017c0a00-3684-11e9-95e1-75239173af77.png">

also: 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/622 and https://github.com/eclipse/openj9/pull/499

**Comment by jdekonin** [comment]
Same test passed on the 12th on ub16-ppcle-2 and 14th on ub16-ppcle-3.  I don't believe there have been machine changes, although when I try install XML:Parser because it wasn't installed for some reason it fails.  Trying to figure out why now. 

ub16-ppcle-4 also doesn't, but its a worker machine now, so irrelevant to this discussion.  ub16-ppcle-1 is fine though as it is installed.  I find this odd because 1-4 are all from the same base and setup at the same time.

| Machine needs [test prereqs](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) installed.

@smlambert I think the documentation needs to be updated because XML::Parser is not on this list as a requirement.

**Comment by smlambert** [comment]
Agree, the test doc update is in PR #499 I referenced, which is WIP / not yet been merged.

**Comment by jdekonin** [comment]
cpan wasn't allowing me to overwrite CC for some reason and its using the version perl sees.

```
ubuntu@eclipse-openj9-2:~$ perl -V:cc
cc='powerpc64le-linux-gnu-gcc'
```

After installing the default gcc package, which we didn't have installed as we had a specific version compiled from source (first 4.8 and then 7), XML::Parser installs fine on ub16-ppcle-[2-4].

```
$ perldoc -l XML::Parser
/usr/local/lib/powerpc64le-linux-gnu/perl/5.22.1/XML/Parser.pm
```
