### ISSUE TITLE
Grinder passes if no tests are run

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4834]
I think it would be a good idea to have a grinder fail (not be green) if no tests are run. A couple of times I have incorrectly configured a grinder, it ran no tests, but looks like it passed. Unless the results are checked to ensure a test was run, the green result may be interpreted incorrectly.

**Comment by smlambert** [comment]
As I mentioned in slack discussion, this could be considered a 'user error', but agree that its not optimal and we should likely 'foolproof' and protect users from themselves, so potentially create a final test that checks what ran, if the answer is 0 tests that final test should fail.
