### ISSUE TITLE
jdk12 osx test sanity PR build doesn't run sanity tests

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4838]
i.e. https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK12-osx_x86-64_cmprssptrs-OpenJ9/3

It built the JVM but didn't run any testing.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau 
I'd like to get this one fixed asap please.

**Comment by AdamBrousseau** [comment]
Try now. There may be others
