### ISSUE TITLE
Docker build failed on ub16x64j96

### ISSUE THREAD

**Issue by samuel-rubin** [eclipse/openj9#4845]
While I was building a docker container on ub16x64j96, I got this error (https://ci.eclipse.org/openj9/view/Build/job/Build-Jenkins-Agent-Container/45/console):
``` 
mkdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
The same build worked on a different machine. I removed the `sw.tool.docker` label from the machine.

**Comment by pshipton** [comment]
@jdekonin
