### ISSUE TITLE
jdk12 intermittent test build failure os.name property value ${java8.os.name} not recognised

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4853]
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK12-linux_390-64_cmprssptrs/3
```
06:01:45  /home/jenkins/jenkins-agent/workspace/Test-extended.system-JDK12-linux_390-64_cmprssptrs/openjdk-tests/systemtest/openj9-systemtest/openj9.build/include/top.xml:469: java os.name property value ${java8.os.name} not recognised.  Update the get-platform-prefix macrodef in openj9.build/include/top.xml
```

**Comment by DanHeidinga** [comment]
Failure occurred on ub16-390-2 and based on today's community call, only occurs when the system tests can't find the right boot jdk.

@pshipton @smlambert @jdekonin Is this applicable to the 0.13.0 release?

**Comment by AdamBrousseau** [comment]
Is there a simple command line we can run on each machine so we can see the result across each machine?

**Comment by pshipton** [comment]
I haven't seen the problem re-occur, but perhaps the tests are choosing a different machine that works. It is only a problem for the 0.13 release if it blocks testing. So far the testing has succeeded, not just for the 0.13 release, but for jdk8 and 11 head as well. I didn't know how often this problem would occur when I created the issue. I'm fine to remove it from 0.13 or even just close it until it is seen again.

**Comment by pshipton** [comment]
The testing has passed on ub16-390-2 since this was opened. I'm just going to close it.

**Comment by pshipton** [comment]
Although the "passed" testing actually ran no tests.
