### ISSUE TITLE
JDKhead: InvokerBytecodeGenerator.HIDDEN_SIG not defined

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#4857]
Latest "to be merged" openjdk"head" stream build fails:
https://hyc-runtimes-jenkins.swg-devops.com/job/Build-JDKnext-linux_x86-64_cmprssptrs/128/consoleFull

11:12:33 /home/jenkins/workspace/Build-JDKnext-linux_x86-64_cmprssptrs/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java:1269: error: cannot find symbol
11:12:33             AnnotationVisitor av0 = mv.visitAnnotation(InvokerBytecodeGenerator.HIDDEN_SIG, true);
11:12:33                                                                                ^
11:12:33   symbol:   variable HIDDEN_SIG
11:12:33   location: class InvokerBytecodeGenerator

**Comment by andrew-m-leonard** [comment]
Introduced by: 8213234: Move LambdaForm.Hidden to jdk.internal.vm.annotation

**Comment by andrew-m-leonard** [comment]
See git@github.com:andrew-m-leonard/openj9-openjdk-jdk.git openj9 branch

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you take a look at this?

**Comment by JasonFengJ9** [comment]
Looking at it.
