### ISSUE TITLE
Implement jstack: display runtime state of a Java process

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#4858]
Suggested command syntax:
`jstack <option>* <pid>*`
`<pid>*` is a list of target process IDs; if none are supplied, the PID(s) are read from `stdin`.  A user may then query all processes via `jps -q | jstack`.  IDs of dead processes are silently ignored.
By default, `jstack` prints the Java stacks and thread information of the specified processes: this essentially the information in `java.lang.management.ThreadInfo`.

Options:
- `-p`: also print the process's system and agent properties
- `l`: also print information about ownable synchronizers.
- The usual suspects: `-J`, `-h`.

`jstack`'s targets must be on the same host and owned by the same user. if `jsatck` connects to a JVM of a different Java version, the behaviour is undefined: if `jstack`cannot print well-formated stack traces due to VM incompatibilities, it will print the raw data in human-readable form.

This differs from the HotSpot version of `jstack`, which allows access to remote hosts and will display data from core dumps.  OpenJ9's `jstack` displays information about only local processes owned by the current user, due to security considerations.  A user may display remote processes using `ssh jstack ...`.  To view information from a core dump, `jdmpview` is preferred.  Other options , such as `-F` (force a dump of an unresponsive) may be accomplished using `kill -QUIT <pid>`.  Printing of native stack frames is not supported due to limitations of the VM.

**Comment by paulcheeseman** [comment]
The inability to show native stack frames is a significant limitation.

Will Java monitor information be printed? i.e. show which locks are held by each thread, and which frame took them (in the stack itself)? Here's what we get in javacores:

```
3XMTHREADBLOCK     Waiting on: java/util/TaskQueue@0x00000000E01737A8 Owned by: <unowned>
...
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Object.wait(Native Method)
4XESTACKTRACE                at java/lang/Object.wait(Object.java:218)
4XESTACKTRACE                at java/util/TimerThread.mainLoop(Timer.java:563)
5XESTACKTRACE                   (entered lock: java/util/TaskQueue@0x00000000E01737A8, entry count: 1)
4XESTACKTRACE                at java/util/TimerThread.run(Timer.java:516)
```

Also, will CPU usage and heap allocation since the last GC be included? These are very useful in javacores.

```
3XMCPUTIME               CPU usage total: 0.001207392 secs, current category="Application"
...
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
```

**Comment by pshipton** [comment]
@paulcheeseman why are you looking for monitor information and cpu usage in the jstack output? jstack is not a replacement for javacore, but something to be roughly equivalent to Hotspot jstack. 

Perhaps we should introduce a utility that generates a javacore.

**Comment by paulcheeseman** [comment]
I would expect monitor info because Hotspot's jstack includes it. Here's some Hotspot output as an example:

```
"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x050e7c00 nid=0x5f8 in Object.wait() [0x17b5f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0cb836b8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x0cb836b8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:212)
```

Regarding the CPU usage and heap allocation data, I thought that it would be nice to include that data if it can be added easily.

I'm just considering what sort of problems would prompt people to use jstack - high CPU and hangs are probably top of the list.

**Comment by pshipton** [comment]
Perhaps we should implement jstack differently. It could generate a partial javacore file to the console, and we could decide which parts of the javacore to generate, and perhaps control different parts via stack options. This could give the same monitor info available in a javacore, and also include the native stacks when supported by the platform.

**Comment by DanHeidinga** [comment]
+ 1 to @pshipton's proposal.  It reuses our code and allows jstack to benefit from future improvements to javacore thread / stack info

**Comment by smlambert** [comment]
Note: 
javax/net/ssl/finalize/SSLSessionFinalizeTest.java fails/timeouts 

Timeout information:
Running jstack on process 26196
Warning: Could not find jstack in: C:\\Users\\jenkins\\workspace\\openjdk11_j9_securitytest_x86-64_windows\\openjdkbinary\\j2sdk-image\\bin\\..
Will not dump jstack output.

[SSLSessionFinalizeTest.jtr.txt](https://github.com/eclipse/openj9/files/2921595/SSLSessionFinalizeTest.jtr.txt)

**Comment by smlambert** [comment]
BTW, I suspect this is part of the reason why the execution time of openjdk regression tests is very long for openj9 runs.  SSLSessionFinalizeTest (and likely other tests) hangs around for 16 min before time out kicks in.

**Comment by pdbain-ibm** [comment]
> I would expect monitor info because Hotspot's jstack includes it. 

OpenJ9's `jstack` does include monitor information:
```
[AttachApiTest] [DEBUG] "main" prio=5 Id=1 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:502)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:490)
	at openj9.tools.attach.diagnostics.internal.ThreadGroupInfo.getThreadInfoProperties(ThreadGroupInfo.java:88)
	at org.openj9.test.attachAPI.TestJStack.testMonitors(TestJStack.java:143)
	-  locked java.lang.Object@3551a94
	at org.openj9.test.attachAPI.TestJStack.main(TestJStack.java:191)

"Thread-1" prio=5 Id=13 BLOCKED on java.lang.Object@3551a94 owned by "main" Id=1
	at org.openj9.test.attachAPI.TestJStack.syncMethod(TestJStack.java:182)
	-  blocked on java.lang.Object@3551a94
	at org.openj9.test.attachAPI.TestJStack$2.run(TestJStack.java:132)
	at java.lang.Thread.run(Thread.java:834)
```

> Regarding the CPU usage and heap allocation data, I thought that it would be nice to include that data if it can be added easily.

I'll see what I can do.

**Comment by pdbain-ibm** [comment]
> +1 to @pshipton's proposal. It reuses our code and allows jstack to benefit from future improvements to javacore thread / stack info

Neat idea. For the orthodox data  `jstack` uses mxbeans for portability and to take advantage of the code for manipulation, but we should be able to use the dump agent code to get native stack traces.

**Comment by pdbain-ibm** [comment]
I have this basically working, though the formatting leaves something to be desired, see https://github.com/eclipse/openj9/issues/4965.

Per discussion with @pshipton , I suggest the following:
- Proceed with the basic mxbean-base `jstack` (sans native stack pro tem) in this release.  I am  adding some timeing information such as CPU user and system time.
- Add native stacks to `jstack` in another release
- Implement `jcmd` to create dumps, get CPU and heap information.  This will be a win on Windows, since it will allow us to create javacores on demand.

**Comment by pdbain-ibm** [comment]
https://github.com/eclipse/openj9/pull/4998 cleans up the output format.

**Comment by pdbain-ibm** [comment]
https://github.com/eclipse/openj9/issues/5012 relates to lock information.

**Comment by pshipton** [comment]
This seems unlikely to be delivered before the 0.14 code split Monday. However we will make an assessment of the change when it is ready to determine if it can go into 0.14 after the code split.
