### ISSUE TITLE
BUILD_LIST cannot set to empty in upstream build

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#4862]
`BUILD_LIST` is not a required value by test job. It has a default value set in test job. The upstream build can overwrite it, but the upstream build cannot set it to empty.

https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK11-osx_x86-64_cmprssptrs/233/console
```
[Pipeline] echo
00:41:44.942  Using VENDOR_TEST_REPOS = , VENDOR_TEST_BRANCHES = , VENDOR_TEST_SHAS = , VENDOR_TEST_DIRS = , BUILD_LIST = 
```

Set it to empty, it will cause test job to fail. Currently, we got false positive result.

https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK11-osx_x86-64_cmprssptrs/91/parameters/

```
02:01:00.822  TEST TARGETS SUMMARY
02:01:00.822  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
02:01:00.822  TOTAL: 0   EXECUTED: 0   PASSED: 0   FAILED: 0   SKIPPED: 0
02:01:00.822  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

This affects all system test builds.

**Comment by llxia** [comment]
fyi @AdamBrousseau @pshipton

**Comment by llxia** [comment]
To fix this, the upstream builds can simply not set BUILD_LIST.

**Comment by llxia** [comment]
After further investigation, this issue may due to recent TKG changes. fyi @renfeiw 
As we noticed the similar test build failure in AdoptOpenJDK  (openJDK regression test and system test builds). Functional test builds are fine.

The upstream builds should not pass in empty `BUILD_LIST` to overwrite the default value. However, the test script ia able to handle this case and tries to set it based on `TARGET` value:

https://github.com/AdoptOpenJDK/openjdk-tests/blob/04692d90e704b19433ab608cadf1751e10bda60a/buildenv/jenkins/JenkinsfileBase#L66

The upstream builds set BUILD_LIST to empty is not root cause of this issue.

**Comment by AdamBrousseau** [comment]
@llxia Should we remove the feature of the OpenJ9 pipelines passing BUILD_LIST then? @vsebe originally added it but I don't think it's heavily used. I think the originally use case of why it was added is no longer needed.

**Comment by renfeiw** [comment]
@llxia I have a PR to fix this issue: #4866

**Comment by llxia** [comment]
> Should we remove the feature of the OpenJ9 pipelines passing BUILD_LIST then?

As the test script can handle empty `BUILD_LIST` case well when `TARGET` is set to standard group (sanity.XXX/extended.XXX/special.XXX group), I think we can keep the feature for now. 

Just be aware, when rerun the test build with a non-standard group `TARGET` (i.e., specific test) and empty BUILD_LIST, test build will not work.

**Comment by pshipton** [comment]
I assume this is related to #4851?

**Comment by llxia** [comment]
yes, it is the same issue as #4851.

**Comment by llxia** [comment]
PR is merged. JDK8 and JDK11 system test builds are fixed.
https://ci.eclipse.org/openj9/view/Test/job/Test-extended.system-JDK11-aix_ppc-64_cmprssptrs/172/tapResults/
