### ISSUE TITLE
PR build failed for no reason

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4880]
I can't see why this PR build failed.

https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/837

**Comment by pshipton** [comment]
@AdamBrousseau @smlambert

**Comment by smlambert** [comment]
Does seem odd.  

I think this would still be driven by the original PR build scripts, as we have not switched over to use Adopt test pipelines yet in PR testing, so I am not so familiar with it, looking for where status of build is set (and prints "Setting status of").  Adam will be more familiar with how that status is determined.

**Comment by AdamBrousseau** [comment]
At the start of the build
```
Using variables file: buildenv/jenkins/variables/defaults.yml
[Pipeline] readYaml
Creating placeholder flownodes because failed loading originals.
[Pipeline] Start of Pipeline
[Pipeline] End of Pipeline
Setting status of d05944cfb525cdfce5208f067bd25e10b1e405cf to FAILURE with url https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_ppc-64_cmprssptrs_le-OpenJ9/837/ and message: 'Build finished. '
Using context: Sanity - JDK8 - linux_ppc-64_cmprssptrs_le
Finished: FAILURE
[Pipeline] echo
Using OPENJDK_REPO = https://github.com/ibmruntimes/openj9-openjdk-jdk8.git OPENJDK_BRANCH = openj9 OPENJDK_SHA = 
```
vs a passed run
```
Using variables file: buildenv/jenkins/variables/defaults.yml
[Pipeline] readYaml
[Pipeline] echo
Using OPENJDK_REPO = https://github.com/ibmruntimes/openj9-openjdk-jdk8.git OPENJDK_BRANCH = openj9 OPENJDK_SHA =
```
Appears to be coming from here:
https://github.com/jenkinsci/workflow-cps-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java#L640
Not sure what happened, likely a 1-off. Not sure what we can do other than keep an eye on it for now.

**Comment by pshipton** [comment]
I'll close this and we can re-open if it is seen again (although people may just ignore it).
