### ISSUE TITLE
Create a command separator macro in TestConfig/makefile

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#490]
We need to create a command separator macro which needs ot be ';' for unix and '&' for Windows. 

This results from the fact that we have '\' being used in playlist.xml for testkitgen which won't work for WIndows. 

Quoting Simon's comment in https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/24/files "\ is not valid in a Windows shell. Instead you could create a macro AND_THEN (or a similar name) with a value of '&' on windows, otherwise ';'. and then use cd $(OPENJDK_SYSTEMTEST_ROOT)/openjdk.build && make test.ClassloadingLoadTest JAVA_ARGS=$(Q)$(JVM_OPTIONS)$(Q) $(AND_THEN) $(TEST_STATUS)"

**Comment by llxia** [comment]
The command in playlist.xml will be used to generate make target and command. The tests runs ok on windows in the lab machines. What is your error message?

**Comment by smlambert** [comment]
Is there an update on this?  I am going through older issues to see which can be or have been resolved.

**Comment by Mesbah-Alam** [comment]
Thanks for reminding me, Shelley. 

This turns out to be a non-issue, as we have the functional tests running on Windows in the eclipse openj9 builds, where `;\` in the command line in playlists didn't create any problem. And also, as Lan had indicated, they are running in jobs in internal build as well. I am therefore closing this issue.
