### ISSUE TITLE
Windows ERROR: Cannot delete workspace

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4908]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-win_x86-64_cmprssptrs/512
win2012r2-x86-4
```
11:32:59  ERROR: Cannot delete workspace :C:\Users\jenkins\workspace\Test-sanity.functional-JDK11-win_x86-64_cmprssptrs\openjdk-tests\functional\JLM_Tests
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
I restarted the build

**Comment by jdekonin** [comment]
The directory isn't present now, so either it was a previous job that was slow to remove/delete, or the cleanup job took care of it.

**Comment by DanHeidinga** [comment]
Closing as this appears stale.
