### ISSUE TITLE
testKitGen sometimes creates stale reports

### ISSUE THREAD

**Issue by Mesbah-Alam** [eclipse/openj9#493]
I have a job that can run a full set of svt tests. And then it can also run a given smaller subset of the svt tests. In the latter case, I have observed that the report that gets generated points to previous results and not the result of the current run. 

Example: https://urv-jenkins.canlab.ibm.com:9095/view/SV_Tests/job/ibmjava8_openjdk-systemtest_x86-64_linux/247/tapResults/ 

If you check the parameters for this build, you will see that this build was run with only one test. But the report lists the full suite of tests that was run in a previous run. May be it's a bug in the report generation process, that can be fixed

**Comment by llxia** [comment]
This is not testKitGen issue. testKitGen does not store any previous results.
Please make sure your Jenkins job cleans its workspace.

**Comment by llxia** [comment]
Please choose "Wipe out repository and force clone" in your Jenkins job.

![image](https://user-images.githubusercontent.com/19273206/32290164-89898352-bf0f-11e7-8a0e-d83aaa8a4116.png)

**Comment by Mesbah-Alam** [comment]
Thanks, added that option to all the jobs.
