### ISSUE TITLE
Version string error with AdoptOpenJDK v11.0.2+9_openj9-0.12.1

### ISSUE THREAD

**Issue by AdamCarroll** [eclipse/openj9#4932]
The version information reported by OpenJ9 in AdoptOpenJDK v11.0.2+9_openj9-0.12.1 contains the string `based on )`.  It looks like it's missing information:
~~~
$ /opt/adoptopenjdk/jdk-11.0.2+9_openj9-0.12.1/Contents/Home/bin/java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190204_123 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - 289c70b684 based on )
~~~

This was tested on MacOS 10.12.6.

**Comment by DanHeidinga** [comment]
The format is very obtuse but the opening `(` from 
```
Eclipse OpenJ9 VM AdoptOpenJDK (
``` 
closes on the last line:
```
JCL      - 289c70b684 based on )
```

The idea was to format the text inside to be more readable compared to a single line

**Comment by DanHeidinga** [comment]
You're completely right - it does appear to be missing info

**Comment by pshipton** [comment]
What it should show is `based on jdk-11.0.2+9` or maybe `based on jdk-11.0.2-ga`. The sha is correct and there is nothing wrong with the build itself, but the Adopt build process didn't manage to find the correct git tag to include in the -version output.

**Comment by DanHeidinga** [comment]
There was suggestion on the community call this may be a mac specific issue - possibly infra related?

**Comment by DanHeidinga** [comment]
Here's the code that should find the tag:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/autoconf/custom-hook.m4#L313-L330

**Comment by pshipton** [comment]
We did find that `sort -V` doesn't work the older osx required to build jdk8. Among other things, this is fixed for jdk8 in https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/277

I believe Adopt is building jdk11 on an older osx version were `sort -V` also doesn't work.
```
sort: invalid option -- V
Try `sort --help' for more information.
```

I believe @keithc-ca has a fix for this.

**Comment by pshipton** [comment]
This is fixed now.
