### ISSUE TITLE
jvmti.h: JVMTI_VERSION_xxx constant name mismatch

### ISSUE THREAD

**Issue by AntonKatilin** [eclipse/openj9#4958]
OpenJ9 JDK 11 jvmti.h defines the constant JVMTI_VERSION_9_0, while Oracle Java/OpenJDK JDK 11 jvmti.h provides the constant JVMTI_VERSION_9 with the same value 0x30090000, as well as the constant JVMTI_VERSION_11 = 0x300B0000 whose counterpart is absent in OpenJ9. This creates a compile time incompatibility.

**Comment by pshipton** [comment]
@AntonKatilin I raised an issue earlier. This problem has been resolved #4667.
Note that although the version is changed #2679 is still outstanding.
