### ISSUE TITLE
AIX not enough space

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4972]
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK8-aix_ppc-64_cmprssptrs/610
aix71-p8-2 
`fatal: write error: There is not enough space in the file system.`

Lots more failures

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
Disabled the machine

**Comment by AdamBrousseau** [comment]
Workspace mount is gone.  Just like #4512 . Still investigating

**Comment by pshipton** [comment]
Machines are working now.
