### ISSUE TITLE
Some ROMclasses in Java 11 are not stored in the shared cache due to unaligned size 

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#4976]
Found some ROMclasses in Java 11 are not stored the shared cache due to `The size of the rom class requested is not a multiple of a double`. The size of those same ROMClasses are dword aligned in Java 8 and are able to be stored in Java 8 SCC. Running Liberty with both Java 11 and Java 8, during the startup, the same type error does not occur in Java 8. Could it be an issue in the component that aligns the ROMClassSize?  

Java 11
```
21:38:41.076 0x19ac700           j9shr.2259     > API j9shr_classStoreTransaction_createSharedClass : enter (classname=java/util/concurrent/ConcurrentLinkedQueue romClassSizeFullSize=14312 romClassMinimalSize=11388 lineNumberTableSize=782 localVariableTableSize=2136
...
21:38:41.076*0x19ac700           j9shr.1571   * - API j9shr_classStoreTransaction_createSharedClass : The size of the rom class requested is not a multiple of a double
...
21:38:41.076*0x19ac700           j9shr.1461     - API j9shr_classStoreTransaction_stop : Nothing to commit to the cache for class java/util/concurrent/ConcurrentLinkedQueue
```

Java 8
```
21:53:59.955 0x23b0700           j9shr.2259     > API j9shr_classStoreTransaction_createSharedClass : enter (classname=java/util/concurrent/ConcurrentLinkedQueue romClassSizeFullSize=7328 romClassMinimalSize=6760 lineNumberTableSize=562 localVariableTableSize=0
...

Stored class java/util/concurrent/ConcurrentLinkedQueue in shared cache for class-loader id 0 with URL /home/ahuo/sdk/jdk8u202-b08/jre/lib/rt.jar (index 2).
```

**Comment by pshipton** [comment]
@hangshao0 @DanHeidinga

**Comment by hangshao0** [comment]
We might have missed some alignment adjustment.

**Comment by gacholio** [comment]
I've been in the ROM class building code recently, and it clearly aligns to 8 at the end (with a comment saying it doesn't know why, so maybe you should update that to indicate the SC requires it).

**Comment by hangshao0** [comment]
> it clearly aligns to 8 at the end (with a comment saying it doesn't know why...

I see it is aligned to 8 here:
https://github.com/eclipse/openj9/blob/01be53f659a8190959c1641eac20b0488739e94c/runtime/bcutil/ROMClassBuilder.cpp#L592-L594

But I didn't find the comment you mentioned, can you point me to where the comment is ?

**Comment by gacholio** [comment]
https://github.com/eclipse/openj9/blob/01be53f659a8190959c1641eac20b0488739e94c/runtime/bcutil/ROMClassWriter.cpp#L431

Looks like some stuff is written after, so maybe the alignment is lost there.

**Comment by gacholio** [comment]
Maybe that align needs to move down (and be stringently commented). Really, each section should align at the start to what it needs, with the final alignment at the end (for reasons that I'm still not clear on).

**Comment by DanHeidinga** [comment]
@hangshao0 Can you update this with the current state?  Will it make the March 25th code split?

**Comment by hangshao0** [comment]
Hopefully I can fix this by the end of this week.

**Comment by hangshao0** [comment]
> Hopefully I can fix this by the end of this week.

It is unlikely to happen. You may need to move this to the next release. @DanHeidinga

**Comment by pshipton** [comment]
Since this is not a feature, but a bug fix, it can be delivered to the release after the code split. We'll look at the fix when it is ready and decide if it should go in.

**Comment by pshipton** [comment]
@hangshao0 is there any update on this?

**Comment by hangshao0** [comment]
PR: https://github.com/eclipse/openj9/pull/5301
