### ISSUE TITLE
openJ9 build Dockerfiles are inconsistent.

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#501]
The Dockerfiles utilise different Ubuntu images/versions and use different bootJVMs

Ideally same Ubuntu image and OpenJDK at the suitable N-1 level as the "boot JDK".

**Comment by AdamBrousseau** [comment]
Not sure if this is still a problem. Can more details be provided otherwise could this be closed?

**Comment by dsouzai** [comment]
Is this still needed given the dockerfile generator script?

**Comment by AdamBrousseau** [comment]
I vote close
