### ISSUE TITLE
Valhalla: Add support for flattened valueType arrays

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#5021]
When creating a non-primitive array, all fields are currently ref sized (32 or 64bits). Each slot in the array contains a reference to the element.

With valueTypes the lack of identity enables the JVM to create flattened arrays. These are arrays where the array elements are not stored as references, rather, they are stored directly (flattened) into the array.

Not flattened
```
----------------------
|       array header   |
----------------------                  ----------------------  
|       reference       |  -->          |        element         |
----------------------                  ----------------------  
|       reference       |  -->          |        element        |
----------------------                  ---------------------- 
```

Flattened
 ```
----------------------
|       array header  |
----------------------          
|      element        |  
----------------------          
|      element       |  
----------------------          
```

For now we will treat all valueType arrays as flattenable (later when we add the distinction between Q and L values in the constantPool we can change this). Note: flattenable does not mean flattened, it means it is allowed to be flattened.

1) Array Classes
------------------
A valueType is flattened if the `J9ClassIsFlattened` flag is set in the J9Class->classFlags. This is the same flag that will determine if the valueType array will be flattened or not. In order to do this for arrays we need to make sure that the classFlags of the elementType are copied over to the arrayRamClass (this may already be the case, but it is worth double checking).

Also, we need to add the `flattenedClassCache` to `J9ArrayClass`, this was an oversight in a previous PR.

2) Creating arrays
--------------------
Add a simple test to ValueTypeTests.java that creates a Value type array. ie.

`Array.newInstance(FlattenedLine2Dclass, ....)` 

Array creation is done with the anewarray bytecode. There are two functions used to create arrays in the interpreter `inlineAllocateIndexableObject` and `J9AllocateIndexableObject` (which uses `MM_IndexableObjectAllocationModel` for the actual allocation). In both cases the arrayClass is used to determine the elementType. And in both cases the size calculation must be changed if the element type is flattened. We can introduce a new macro for this (ie `J9_IS_J9CLASS_FLATTENED`) see j9.h for examples.

Classes may have padding bytes added before the first field in order to satisfy alignment constraints. The flattened layout may or may not include this padding. As a result, in order to determine the flattened size of a valuetype, one must take the `J9Class->totalInstanceSize` and subtract it by the `J9Class->backfillOffset`. A macro can also be added for this.

When calculating the size of the each element, one must ensure that the alignment constraints of the type are met (see `J9ClassLargestAlignmentConstraintDouble` and `J9ClassLargestAlignmentConstraintReference` in J9Class->classFlags). This might mean that extra space must be allocated for each element in order to make sure that all alignment constraints are met. This should also be taken into account when calculating the size of the array. 

Size calculation is done as follows:
```
if VT contains doubles //long, double
    elementSize = ROUND_UP_TO(instanceSize - offsetOfFirstField, sizeof(U_64))
else if VT contains ref
    elementSize = ROUND_UP_TO(instanceSize - offsetOfFirstField, sizeof(fj9object_t))
else  // VT only contains singles (int, short, etc) at this point
    elementSize = instanceSize - offsetOfFirstField
```
This ensures that we pad up the size of the elements so alignment constraints are met.

Note: J9 indexable object headers are guaranteed to end on a 8byte boundary, so the starting point of the array elements should always satisfy alignment constraints, we only need to worry about the sizing of the elements.

The `J9ARRAYCLASS_SET\GET_STRIDE` have been added to set/get the stride length on array objects. All array classes will need their stride lengths set upon creation. This can be done in `internalCreateRAMClassFromROMClass`. For all non-VT array classes the stride length will be `1 << elementClass->romClass->instanceShape`. For VT-arrays stride length will be calculated as demonstrated above.

The `dataSize` calculation in `inlineAllocateIndexableObject` will have to be updated to use `strideLength` from the arrayClass. Like wise with `GC_ArrayletObjectModel::getDataSizeInBytes(..)`.

3) Accessing array elements
-----------------------------
Accessing object array elements is done with the aaload and aastore bytecodes. Both of these use access barrier functions (ObjectAccessBarrierAPI.hpp) to read/store array elements. These functions need to detect if the array is flattened so that it read/stores the elements at the correct location.

Flattened array elements are variable length, so they must be read and written to with the `copyObjectFields` helper. 

It is possible that the size of a flattened type in an array will differ than the size of a flattened type in a field (or on its own). In order to keep track of the element size we can use the flattenedClassCache (currently unsued) field in the arrayRamClass to store that information.

4) Scanning flattened arrays
------------------------------
Finally, the GC object scanners need to be updated to take into account that array elements may contained mixed objects. Typically, arrays are either primitive, in which case the GC can ignore the elements when scanning for objects, or they are object arrays in which case the GC scans every slot. With flattened arrays, it is a combination of the two. The GC needs to use the instance description bits of the element type in order to determine which slots to scan.

5) Testing flattened arrays
---------------------------
We will need basic testing for flattened array support, this includes creating an array, then reading and writing fields out of it.  We will need further testing to ensure that the GC is able to scan array elements properly. We will need to test multiple GC policies (ie, gencon, balanced and metronome) for this.

------------------------------
Note: This work should be done in stages (1 - 5), at least 1 PR for each stage. Also, this is design is subject to change and will likely be modified in the future to accommodate the Q and L array distinction. I will also add more details on scanning array fields.

March 8: Updates made to section 1, 2 and 4
March 18: Udates made to section 2

**Comment by tajila** [comment]
FYI @dmitripivkine

**Comment by tajila** [comment]
More updates have been made regarding alignments

**Comment by dmitripivkine** [comment]
List of items should be look at from GC perspective (not in particular order and to be updated):
- Add recognition for new type of array. Scanning should be two level - use Indexable object Iterator to get start address of the element and use Mixed object Iterator to scan each element as a headless Mixed.
- Should each element to be aligned to (Minimum Heap Object size(16) - Mixed object header size(8)) ?
- Arraylet logic assumed that size of element is power of 2 - should be changed
- Split array logic might require tuning

**Comment by dmitripivkine** [comment]
@RSalman Would you please work on GC support for this feature?

**Comment by RSalman** [comment]
I'll start looking into the GC items!

**Comment by tajila** [comment]
@AidanHa will be working on the VM+Barrier changes

**Comment by dmitripivkine** [comment]
Would be helpful to add some kind of PRIMITIVE flag to this type if mixed object part does not have object  references to scan, so GC might go to primitive array path

**Comment by AidanHa** [comment]
> A valueType is flattened if the J9ClassIsFlattened flag is set in the J9Class->classFlags. This is the same flag that will determine if the valueType array will be flattened or not. In order to do this for arrays we need to make sure that the classFlags of the elementType are copied over to the arrayRamClass (this may already be the case, but it is worth double checking).

I've confirmed that the classFlags are copied over to the array RamClass Flags!

**Comment by tajila** [comment]
@dmitripivkine 

> Would be helpful to add some kind of PRIMITIVE flag to this type if mixed object element does not have object references to scan, so GC might go to primitive array path

I have some ideas to do that 

We can introduce a VM macro to do  the check. ie. `J9_DOES_VALUE_ARRAY_CONTAIN_REFERENCES` , just checks if the instance description bits of the element class is zero.

We can use the macro for now in the GC code. Then we can make it faster by adding a primitive flag later. I don't won't to commit to adding a primitive now, because there are a lot of flags we will potentially need, so we need to decide which ones are most important

**Comment by tajila** [comment]
I believe the size calculation for flattened array elements is something like the following:
```
if VT contains doubles (long, double)
    elementSize = ROUND_UP_TO(instanceSize - offsetOfFirstField, sizeof(U_64))
else if VT contains ref
    elementSize = ROUND_UP_TO(instanceSize - offsetOfFirstField, sizeof(fj9object_t))
else
    // VT only contains singles (int, short, etc) at this point
    elementSize = instanceSize - offsetOfFirstField
```
This ensures that we pad up the size of the elements so alignment constraints are met.

Once we have the element size, the total arraySize is simply `elementSize * numOfElements`

@AidanHa for part 1 (Array Classes) instead of adding the `flattenedClassCache` field to the array ramClass. Add a `UDATA flattenedElementSize` field instead. 

When the array class is being created you can perform the steps above to determine the flattened elementSize.

In part2, you can use the `elementSize` field to determine how large an array to create.

**Comment by dmitripivkine** [comment]
Can special (from GC point of view) mixed objects like Phantom/Weak/Soft References, Ownable Synchronizers etc. be flattened?

**Comment by tajila** [comment]
Also, For part2, you'll need to add a simple test to `ValueTypeTests.java` that creates a Value type array. ie. 
`Array.newInstance(FlattenedLine2Dclass, ...`. This will be sufficient to test your changes for now. The more extensive tests can be added later.

**Comment by tajila** [comment]
@dmitripivkine 

> Can special (from GC point of view) mixed objects like Phantom/Weak/Soft References, Ownable Synchronizers etc. be flattened?

There is currently no restriction on the type of references a value type is allowed to have. So yes, a value type could contain a  Phantom/Weak/... reference and that value type may be flattened in an array.

**Comment by dmitripivkine** [comment]
> @dmitripivkine
> 
> > Can special (from GC point of view) mixed objects like Phantom/Weak/Soft References, Ownable Synchronizers etc. be flattened?
> 
> There is currently no restriction on the type of references a value type is allowed to have. So yes, a value type could contain a Phantom/Weak/... reference and that value type may be flattened in an array.

This would cause extra complications in GC. The cases of building lists of References and other handling based on scan-only-once, Work Packet Overflow cases etc. This case can be avoided in first implementation by disabling of flattening for special types and be addressed later.
Is my understanding correct that for example stand alone Weak Reference object and Weak Reference element of array are equivalent in VM functionality?

**Comment by tajila** [comment]
> Is my understanding correct that for example stand alone Weak Reference object and Weak Reference element of array are equivalent in VM functionality?

Yes, I believe this is the case.

**Comment by tajila** [comment]
@AidanHa updates made to the description
