### ISSUE TITLE
Produce a summarized excludes list for a particular test run

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#5022]
We currently run several different types of tests (that use various underlying test frameworks).  There are several methods for excluding test targets and the individual tests within the test target.  

We would like a way to summarize all of the test exclusions of a particular test run.  There are a variety of ways to do this, one way, which would produce this info even on a manual/local test run would be to add a "getExcludes" target to testkitgen to tally test exclusions.

Different supported mechanisms to exclude tests:
- disable an entire test target in playlist.xml using `<disabled>` tag (preferred way)
- disable a target's subtest: openjdk regression test using openjdk exclude files 
- disable a target's subtest: testNG functional test using functional exclude files
- disable a target's subtest: cmdlinetester functional test

**Comment by pdbain-ibm** [comment]
Also excluding via a TestNG method annotation:  `@Test(groups = { "disable.generic-all" })`.

**Comment by smlambert** [comment]
We should/will absolutely stop using that mechanism (annotated test code) if its currently in use. 

We need to limit the number of places to check for excludes, in order to make it easier to automate re-inclusion, etc.

**Comment by llxia** [comment]
For the initial step, we will try to list the tests that use <disabled> in playlist.xml (FYI @LongyuZhang )

**Comment by smlambert** [comment]
Closing this issue, as its partly addressed through existing TKG features (which lists disabled playlist tests as part of the TKG and TAP summary).  

Since the reason for this issue was to ensure that we re-include disabled tests in a timely manner, further work will be accomplished under https://github.com/AdoptOpenJDK/openjdk-tests/issues/1853.
