### ISSUE TITLE
Enable Software Based Concurrent Scavenger on P Linux BE

### ISSUE THREAD

**Issue by gita-omr** [eclipse/openj9#5023]
In https://github.com/eclipse/openj9/issues/3421 we somehow missed enabling the feature on Linux BE. This is just a matter of turning on a switch, so we will do it for 0.14.

@IBMJimmyk @pshipton 

Documentation will need to be adjusted @SueChaplain as well.

**Comment by vij-singh** [comment]
@gita-omr @IBMJimmyk  Are we still ok for 0.14.0 ?

**Comment by gita-omr** [comment]
@vij-singh yes, it's already in.

**Comment by pshipton** [comment]
@gita-omr as the change is delivered, is there any reason to keep this open?

**Comment by gita-omr** [comment]
Just recalled why I kept it opened. I wanted to make sure docs are updated.

**Comment by SueChaplain** [comment]
I've got the work captured for 0.14.0 @gita-omr - thanks
