### ISSUE TITLE
Prepare functional tests for use on non-openj9 implementations

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#5066]
As part of AdoptOpenJDK QA, we would like to leverage some of the functional tests to verify non-openj9 implementations also.  We need to do a few things to prep these tests for that purpose:

- segregate/separate build targets so that test material that contain openj9 specific classes are excluded from compilation with non-openj9 implementations 
- update playlists to properly tag tests that are good for verifying any impl, or only openj9/ibm by adding appropriate `impl` tags

**Comment by llxia** [comment]
fyi @dutingda

**Comment by smlambert** [comment]
Latest [run-aqa](https://github.com/AdoptOpenJDK/run-aqa/actions) tests of functional material against hotspot is passing, so I will close this issue.
