### ISSUE TITLE
x86 32 Bit Builds

### ISSUE THREAD

**Issue by madduci** [eclipse/openj9#509]
Knowing the fact that Oracle isn't supporting Java 9 for 32 bit systems officially (changed strangely on 21st September, maybe as option for paying customers), it think it would still make sense provide 32 bit builds as long as a lot of PCs are still running 32 bit OSes (e.g Windows 8.1/10 Tablets are 32 bits, a lot of legacy systems, both Windows and Linux). Java 8 is now entering the End-of-Life cycle, so why not giving updates?

Some distributions are providing openjdk 32 builds, then why not openj9 as well?

In addition, it would be nice to have also OpenJFX.

**Comment by pshipton** [comment]
IBM Java 8, which uses OpenJ9, does support 32-bit platforms (except PPC LE), so OpenJ9 does contain this support. It should be a matter of getting a 32-bit build configured, as long as OpenJDK can support it. Getting pure OpenJ9 32-bit builds going, or building OpenJFX, is beyond the scope of what IBM is trying to accomplish atm.

**Comment by pshipton** [comment]
Note there is some active investigation going on to create an OpenJ9 32-bit build, at least for Windows.

**Comment by sxa555** [comment]
Will this change require a 32-bit host OS to build on or is the work being done on a 64-bit host OS?

**Comment by pshipton** [comment]
It works on a 64-bit host. I don't think anything changes in the machine configuration if you already have all the cygwin tooling.

**Comment by tellison** [comment]
Any update on support for win32?  Will it be targeted to the 0.10.0 milestone?

**Comment by DanHeidinga** [comment]
@tellison win32 support is included in the 0.9.0 release.  The release was targeted to June but has slipped.

The (as yet unmerged) 0.9 release notes are: https://github.com/pmhayward/openj9/blob/94d7f5140456814f4c3cfcb2c4fd9fecbe99df23/doc/release-notes/0.9/0.9.md

**Comment by DanHeidinga** [comment]
Looks like there's a problem publishing the nightly builds at adopt: https://github.com/AdoptOpenJDK/openjdk-build/issues/398

**Comment by sxa555** [comment]
Now sorted

**Comment by DanHeidinga** [comment]
AdoptOpenJDK is only building 32 bit for JDK8 as that has primarily been where the requests for 32 bit have been.  JDK8 will be supported until 2019 [1] and, assuming community support at OpenJDK, much longer.

It should be possible to build OpenJDK with OpenJ9 for newer releases but we haven't prioritized that work.

The added complication is that to provide 32 bit on newer JDK releases requires OpenJDK to continue to support building 32 bit platforms.  The focus there has been to 64 bit windows, linux, & mac which may result in issues building / running 32 bit.

[1] https://www.eclipse.org/openj9/docs/openj9_support/

**Comment by DanHeidinga** [comment]
Closing as our focus (and OpenJDK's) is on 64 bit systems in future releases.
