### ISSUE TITLE
testDDRExt_SharedClasses failed in OpenJ9 SDK

### ISSUE THREAD

**Issue by Yuehan-Lin** [eclipse/openj9#5095]
When importing the DDR tests, DDR sharedClasses test(testDDRExt_SharedClasses_openj9) passed on IBM SDK from vmfarm, but did not passed on OpenJ9 SDK.
The IBM SDK I used is
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pxa6480sr6-20181206_03(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190115_407521 (JIT enabled, AOT enabled)
OpenJ9   - a4fe0b0
OMR      - 327dfe0
IBM      - e2996d1)
JCL - 20181121_01 based on Oracle jdk8u201-b05
```
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1250/
If the link cannot be opened:
-  buildlist: functional/DDR_Test
- OS/architecture: linux_x86-64_cmprssptrs
- OpenJDK version: 
```
openjdk version "1.8.0_202-internal"
OpenJDK Runtime Environment (build 1.8.0_202-internal-201903130430-b08)
Eclipse OpenJ9 VM (build master-6259e9f2e, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190313_249 (JIT enabled, AOT enabled)
OpenJ9   - 6259e9f2e
OMR      - da32e2b9
JCL      - 9dc1c4d81c based on jdk8u202-b08)
```

Failure output
--------------
Output from Grinder:
 **test name: testDDRExt_SharedClasses_openj9**
```
[java] [DDRExtTesterBase] [ERROR] '!shrc  findaotp getSecurity' output does not contain success key : No entry found in the cache
[java] [DDRExtTesterBase] [ERROR] '!shrc  findaotp getSecurity' output :!j9sharedclassconfig 0x00007F70A00B92C0
.....
[java] [DDRExtTesterBase] [ERROR] '!shrc  findaot getSecurityManager' output does not contain success key : No entry found in the cache
[java] [DDRExtTesterBase] [ERROR] '!shrc  findaot getSecurityManager' output :!j9sharedclassconfig 0x00007F70A00B92C0
.....
[java] [DDRExtTesterBase] [ERROR] '!shrc  findjithp r' output does not contain success key : run\(\)Ljava/lang/.*
[java] [DDRExtTesterBase] [ERROR] '!shrc  findjithp r' output :!j9sharedclassconfig 0x00007F70A00B92C0
```

**Comment by hangshao0** [comment]
Looks like methods getSecurityManager() and getSecurity() are not AOT'ed.

**Comment by hangshao0** [comment]
Talked to @Yuehan-Lin, methods getSecurityManager() and getSecurity() are AOT'ed and in the system core. The messages are not real errors. We can stop printing such info messages in error log.

> [java] [DDRExtTesterBase] [ERROR] '!shrc  findaotp getSecurity' output does not contain success key : No entry found in the cache
> [java] [DDRExtTesterBase] [ERROR] '!shrc  findaot getSecurityManager' output does not contain success key : No entry found in the cache

The test failed due to:

> [java] [DDRExtTesterBase] [ERROR] '!shrc  findjithp r' output does not contain success key : run\(\)Ljava/lang/.*

Test can be updated to check for another method.
