### ISSUE TITLE
aix71-p8-1 There is not enough space in the file system

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5109]
Machine disabled

https://ci.eclipse.org/openj9/job/Build-JDK11-aix_ppc-64_cmprssptrs/669
https://ci.eclipse.org/openj9/job/Build-JDK8-aix_ppc-64_cmprssptrs/1198
https://ci.eclipse.org/openj9/job/Test-extended.system-JDK12-aix_ppc-64_cmprssptrs/21
https://ci.eclipse.org/openj9/job/Test-extended.functional-JDK8-aix_ppc-64_cmprssptrs/228
etc.
Been happening for a few days.

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Looks like the extra workspace mountpoint has become unmounted.  I have rebooted and manually cleaned up content, but this still leaves only 4G free and no obvious 50G mount. fyi @AdamBrousseau

**Comment by AdamBrousseau** [comment]
I will have to recreate. Not sure why it disappeared this time. I did not create any images of it since everything was resolved.

**Comment by pshipton** [comment]
Machine is active again so I assume this is resolved.
