### ISSUE TITLE
JDK-NEXT testing cannot run tests

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5123]
https://ci.eclipse.org/openj9/blue/organizations/jenkins/Test-sanity.functional-JDKnext-linux_ppc-64_cmprssptrs_le/detail/Test-sanity.functional-JDKnext-linux_ppc-64_cmprssptrs_le/2/pipeline
`No such property: JDK_VERSION for class: groovy.lang.Binding`

Build started from https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/

Did I set it up incorrectly, or are more changes required to support jdknext?

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
The test pipelines appear to be missing a large number of parameters.  I thought these were updated at the time of running.  @llxia, how do the test jobs get updated wrt parameters?

**Comment by llxia** [comment]
These JDKnext test pipelines are created by @vsebe. 
I am not sure the plan for it. Current test job template does not update these JDKnext test pipelines.

**Comment by AdamBrousseau** [comment]
Since the test framework now auto detects jdk version, I think if we regenerate these set of jobs using the test script, then we should be able to use them without having to specify version or change the version every 6 months. Does that sound reasonable @llxia?

**Comment by pshipton** [comment]
This was resolved.
