### ISSUE TITLE
Having a NFS home directory gives confusing shared cache error message

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5134]
If the user's home directory is set to a network (NFS) location, trying to use/create a shared cache results in the following error, which is cryptic. Better to have an error which is understandable, without having to look any further.

`JVMSHRC404E Failed to get a directory for the cache`

Further, this message code has the following explanation, which isn't appropriate for all the failure cases.

`J9NLS_SHRC_OSCACHE_GETCACHEDIR_FAILED.explanation=The directory path requested is bigger than the internal buffer space`

**Comment by pshipton** [comment]
@hangshao0

**Comment by fjeremic** [comment]
I got bit by this too when I tried to build OpenJ9 and run some tests while my home directory was mounted on an NFS. All of the SCC tests were giving the above message or even something weirder and it was definitely non-obvious that home directory on NFS was the issue.

**Comment by hangshao0** [comment]
I will fix the error reporting.
