### ISSUE TITLE
Use 1MB as native thread stack size minimum on 64-bit z/OS

### ISSUE THREAD

**Issue by smithwil** [eclipse/openj9#5156]
As the smallest possible native stack size on 64-bit z/OS is 1MB, could the handling of -Xmso and the default native stack size change to use 1MB as the minimum native stack size?

At the time of writing, the default native stack size value used is 256KB for non-compressed references JVM and 384KB for compressed refs. This leads to artificial native OOME's when the JVM predicts that the native stack is about to grow above these values. In truth, there is no OOM condition until the native stack grows to 1MB, because that is the smallest native thread stack possible on z/OS 64-bit.

**Comment by PhilWakelin** [comment]
[IARV64 GETSTOR](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.ieaa900/iea3a9_Description1.htm) allocates storage in segments, "A segment represents one megabyte of virtual storage on a one megabyte boundary".  

So 1MB is the smallest allocate unit of stack, and by default the LE runtime options for STACK64/THREADSTACK64 default to a max of 128M, so the stacks can grow upto 128M by default, providing there is enough space left in the MEMLIMIT. [LE Prog Ref](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3SA380683/$file/ceea300_v2r3.pdf)

**Comment by pshipton** [comment]
The internal build on this (412759) passed all the sanity tests, for both 31-bit and 64-bit z/OS builds.

**Comment by doveye** [comment]
This issue should have a doc:externals label and a corresponding issue created in openj9-docs - we need to document that a default has changed, and change the value in https://eclipse.github.io/openj9-docs/openj9_defaults.

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9-docs/issues/295
