### ISSUE TITLE
Valhalla: Add support for DDR

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#5178]
Background
----------------------------------------------------
Currently, DDR only knows about two kinds of instance fields, primitives (Z, B, S, I, J, C, F, D) and L-types (LFoo;). With the introduction of valueTypes there is an additional kind of instance field called a Q-type (QFooVal;). Q-types are unique in that they may be flattened in place inside of the container. This means that unlike L-types they are not always guaranteed to be reference  sized (32bit/64bit) they they can be any size. 

The common way to look at objects in DDR is with the `!j9object [objAddress]` command. 

Given a the types:

```
value Point2D {
    int x;
    int y;
}

value Line2D {
    Point2D st;
    Point2D en;
}

value FlattenedLine2D {
    flattened Point2D st;
    flattened Point2D en;
}
```

Inspecting a `Line2D` instance in today's DDR would look something like:

```
> !j9object 0x7055bbaf0
!J9Object 0x00000007055BBAF0 {
      struct J9Class* clazz = !j9class 0x9F2500   // Line2D
      Object flags = 0x00000000;
      LPoint2D; st = !fj9object 0x7ffef39f6 (offset=0) (Line2D)
      LPoint2D; en = !fj9object 0x7ffef39f6 (offset=4) (Line2D)
}
```

The `!fj9object` denotes that the field is stored as a compressed reference.  In the example above `st` and `en` contain the same value. Running `!fj9object 0x7ffef39f6` would output:

```
> !fj9object 0x7ffef39f6
!J9Object 0x00000007FFEF39F8 {
      struct J9Class* clazz = !j9class 0x9F0E00   // Point2D
      Object flags = 0x00000000;
      I x = 0xffeeffee (offset=0) (Point2D)
      I y = 0xaabbaabb (offset=4) (Point2D)
}
```

With Q-types the JVM is allowed to flatten the value in place, similar to a nested C struct. In DDR flattened q-types currently look like this:
```
> !j9object 0x7fff56a58
!J9Object 0x00000007FFF56A58 {
      struct J9Class* clazz = !j9class 0x9F1D00   // FlattenedLine2D
      Object flags = 0x00000000;
      QPoint2D; st = !fj9object 0xffeeffee (offset=0) (FlattenedLine2D)
      QPoint2D; en = !fj9object 0xaabbaabb (offset=4) (FlattenedLine2D)
}
```

Instead of showing the address of `st` and `en` it shows the contents of `st`. 

The examples above show what DDR currently outputs. The goal of this Issue is to add support for flattened objects.

---------------------------------------------------
1) Add DDR support of flattened value types
-----------------------------------------------------------

The first task is to create a command that can print q-types. Q-types may or may not be flattened. And whether a q-type is flattened or not will vary from type to type. In order to determine if a field is flattened, one has to check the `J9Class->classFlags` of that field for the `J9ClassIsFlattened` bit.

The following shows the memory layout of `FlattenedLine2D`:
```
0x7fff56a58: 009f1d00 // J9Class/flags
0x7fff56a5C: ffeeffee  // st.x
0x7fff56a60: aabbaabb // st.y
0x7fff56a64: ccddccdd // en.x
0x7fff56a68: aaffaaff  //en.y
```

One will notice that the flattened types do not have headers. This means that the command used to print the flattened type must have a reference to the container as well as a value to indicate which field is to be printed.

New command: `flattenedj9object`

Usage: !flattenedj9object [addressOfContainer],[[fieldNum] ... ]
addressOfContainer - Address of the class/value that contains the flattened valueType field. In the case of multi-level field flattening, `addressOfContainer` is the address of the top most container. In other words, `addressOfContainer` must always point at something with a header.

fieldNum - The index of the field that is to be printed. In the case of multi-level flattening, mutliple field numbers may have to be specified.

i.e
```
> !j9object 0x7fff56a58
!J9Object 0x00000007FFF56A58 {
      struct J9Class* clazz = !j9class 0x9F1D00   // FlattenedLine2D
      Object flags = 0x00000000;
      QPoint2D; st = !flattenedj9object 0x7fff56a58,0 (offset=0) (Point2D)
      QPoint2D; en = !flattenedj9object 0x7fff56a58,1 (offset=8) (Point2D)
}
```

If `FlattenedLine2D` where nested in another value type, then the command to print the `st` field would be ` !flattenedj9object 0xCONTAINERADDRESS,0,0`. Where `0xCONTAINERADDRESS` is the address of the object that contains the `FlattenedLine2D` instance, the first `0` is the field index for the `FlattenedLine2D`  instance and the last `0` is the index for the `st` field. 

---------------------------------------------------
2) Update !j9classshape command
-----------------------------------------------------------

The class shape command prints out the names and offsets of each field. This will have to be updated to work for flattened value types.

**Comment by tajila** [comment]
@MarkQingGuo

**Comment by tajila** [comment]
FYI @keithc-ca @gacholio

**Comment by keithc-ca** [comment]
I think some of the sample addresses need fixing (e.g. the example `Line2D` shows the same address for both `st` and `en` fields).

**Comment by keithc-ca** [comment]
I think we should modify the existing commands as much as possible rather than expect users to figure out which command to use for a given object. So the existing `!j9object` and `!fjobject` commands should show all inlined objects; the names should reflect the paths from the context to the field (e.g. `en.x` below). Perhaps we could also include the inlined containers as well:
```
> !j9object 0x7fff56a58
!J9Object 0x00000007FFF56A58 {
    struct J9Class* clazz = !j9class 0x9F1D00   // FlattenedLine2D
    Object flags = 0x00000000;
    Point2D st = !flattenedj9object 0x7fff56a58,0 (offset=0) (Point2D)
    I st.x = 0xffeeffee (offset=0) (Point2D)
    I st.y = 0xaabbaabb (offset=4) (Point2D)
    Point2D en = !flattenedj9object 0x7fff56a58,1 (offset=8) (Point2D)
    I en.x = 0xccddccdd (offset=8) (Point2D)
    I en.y = 0xaaffaaff (offset 12) (Point2D)
}
```
The name `!flattenedj9object` is rather long: how about `!flatobject`?
Can we support field names as well so a user could say: `!flatobject 0x7fff56a58,en`?

**Comment by MarkQingGuo** [comment]
> I think some of the sample addresses need fixing (e.g. the example `Line2D` shows the same address for both `st` and `en` fields).
The `st` and `en` fields point to the same object in the sample, so the addresses are the same here

**Comment by keithc-ca** [comment]
> The `st` and `en` fields point to the same object in the sample, so the addresses are the same here

How can that be? We're talking about `flattened` fields.
Also, the offset of `en` should be 8 in a `FlattenedLine2D` object.

**Comment by MarkQingGuo** [comment]
```
value Line2D {
    Point2D st;
    Point2D en;
}
```
I thought you were taking about `Line2D` : fields are not flattened in `Line2D`, so references `st` and `en` can refer to the same object. Offset of `en` is 4 in a `Line2D` object.
It's impossible in `FlattenedLine2D`. sorry for that. : )

**Comment by tajila** [comment]
>>The st and en fields point to the same object in the sample, so the addresses are the same here

> How can that be? We're talking about flattened fields.

Line2D does not contain flattened fields, only FlattenedLine2D. L-types are never flattened.

> Also, the offset of en should be 8 in a FlattenedLine2D object.

The purpose of the first 3 examples was to show that current DDR commands do not work for flattened fields. I simply pasted what DDR currently outputs. I have updated the description to make it more clear.

> I think we should modify the existing commands as much as possible rather than expect users to figure out which command to use for a given object. 

The intention is that users do not have learn any new commands. Currently, users do not need to think about when to use `!fjobject` or `!j9object` they always just use `!j9object`. 

If an object happens to have fields that are stored as compressed references, then the output of `!j9object` will contain `!fjobject`. The user simply copy/pastes the output to inspect the object fields. Similarly, if an object has flattenedfields, then the result will contain `!flattenedj9object`, and the users will continue to do what they normally did.  

>  Perhaps we could also include the inlined containers as well

This works for small objects, but for larger objects the output will be very large. I think this will be more suitable in a separate command.

> The name !flattenedj9object is rather long: how about !flatobject?

Yes, a shorter name would work

> Can we support field names as well so a user could say: !flatobject 0x7fff56a58,en?

yes this is a good addition

**Comment by MarkQingGuo** [comment]
Is there a simpler way to find a flattened class's flags?
I attempt to use a similar way as function `findJ9ClassInFlattenedClassCache`, but `flattenedCache` is a new thing to DDR, do we have access to it in DDR?
does `IsJ9ClassIsFlattened` exist in `fieldShapePointer.modifiers()`? If so, we can use it directly without considering flattenedCache.
Also I can't find definition of function `modifier()`, is it generated? If so, do you mind telling where I can find other generated functions? These functions might be useful in this issue.

**Comment by MarkQingGuo** [comment]
What’s your expectation of behaviour of `!flatobject`?
Here is what in my mind:
Let’s consider we have a `triangle2D` object:
```
value Triangle2D {
    flattened Line2D v1;
    flattened Line2D v2;
    flattened Line2D v3;
}
```
For simplification, we consider its located at 0x0
if we use !j9object 0x0, the correct output should be
```
!J9Object 0x000000000000000 {
      struct J9Class* clazz = !j9class 0x9F1D00  // triangle2D, the class address doesn't matter here
      Object flags = 0x00000000;
      QFlattenedLine2D; v1 = !flatobject 0x00000000,0 (offset=0) (FlattenedLine2D)
      QFlattenedLine2D; v2 = !flatobject 0x00000000,1 (offset=16) (FlattenedLine2D)
      QFlattenedLine2D; v3 = !flatobject 0x00000000,2 (offset=32) (FlattenedLine2D)
}
```
If we want to get the content of `v2` here:
The command should be `!flatobject 0x00000000,1`, and the output should be
```
!flatobject 0x000000000000000, 1 {
      struct J9Class* clazz = !j9class 0x9AAAAAA  // FlattenedLine2D, the class address doesn't matter here
      Object flags = 0x00000000;
      QPoint2D; st = !flatobject 0x00000000,1,0 (offset=0) (Point2D)
      QPoint2D; en =!flatobject 0x00000000,1,1 (offset=8) (Point2D)
}
```
Is this correct?

**Comment by tajila** [comment]
> Since we have to modify J9ObjectFieldOffsetIterator in DDR to find a flattenedfield's offset.
Is there a simpler way to find a flattened field's flags?

The only way to find a fields flags is to look up the  `J9Class` for the field type in the `FlattenedclassCache`. The function `findJ9ClassInFlattenedClassCache()` isnt implemented in DDR but you can add one. The `J9ClassIsFlattened` flag only exists in the `J9Class->classFlags`

**Comment by tajila** [comment]
> Is this correct? Or we don't need clazz or flags? I think these two might be necessary here.

That looks correct. An argument can be made that we dont need flags, since it will always be zero. But class is important.

**Comment by keithc-ca** [comment]
> Since we have to modify J9ObjectFieldOffsetIterator in DDR to find a flattenedfield's offset.

It's not clear to me that we *need* to modify `J9ObjectFieldOffsetIterator`; the iteration of flattened fields can take into account an offset adjustment with the existing iterator implementation.

**Comment by MarkQingGuo** [comment]
I use an example from above.
```
> !j9object 0x7fff56a58
!J9Object 0x00000007FFF56A58 {
      struct J9Class* clazz = !j9class 0x9F1D00   // FlattenedLine2D
      Object flags = 0x00000000;
      QPoint2D; st = !fj9object 0xffeeffee (offset=0) (FlattenedLine2D)
      QPoint2D; en = !fj9object 0xaabbaabb (offset=4) (FlattenedLine2D)
}
```
If we get this result in current DDR implementation, we might need to modify iterator: since the offset of field `en` should be 8 here.

**Comment by MarkQingGuo** [comment]
When I use DDR to investigate a valuetype in docker: command !j9object <address>
I keep getting an error: ``Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9Consts.J9_JAVA_CLASS_RAM_ARRAY``
Are there some configuration I missed?

**Comment by tajila** [comment]
> When I use DDR to investigate a valuetype in docker: command !j9object <address>
I keep getting an error: Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/J9Consts.J9_JAVA_CLASS_RAM_ARRAY
> Are there some configurations I missed?

`J9_JAVA_CLASS_RAM_ARRAY` no longer exists in the source code, so I think you may be using outdated source, or a version of DDR based on vm28

> Beside, how do we let J9classPointer have access to its J9flattenedClassCache field like fieldShapePointer has access to its modifier field?

the `J9classPointer.flattenedClassCache()` method should be generated if you are building the JDK with `J9VM_OPT_VALHALLA_NESTMATES`

**Comment by MarkQingGuo** [comment]
I think it's better to create a new class called `J9ValueTypeHelper` which contains a group of helpers used for valuetypes in ddr. What folder should I place this class? Is this directory `openj9/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive` good?

**Comment by keithc-ca** [comment]
I'd suggest we continue the pattern of putting helper classes
in `package com.ibm.j9ddr.vm29.pointer.helper;`.

**Comment by MarkQingGuo** [comment]
Would this field `J9FlattenedClassCache *_flattenedClassCache` in `ObjectFieldInfo.hpp` be generated as `J9FlattenedClassCachePointer[] _flattenedClassCache` in.ddr?

**Comment by keithc-ca** [comment]
You should expect this method in `ObjectFieldInfoPointer` to be derived from that field:
```
public J9FlattenedClassCachePointer _flattenedClassCache() throws CorruptDataException
```

**Comment by tajila** [comment]
@MarkQingGuo can you confirm that all new objects you introduced in the VT tests can be viewed with your DDR changes

**Comment by tajila** [comment]
this work is complete
