### ISSUE TITLE
Add StackWalker.StackFrame.getMethodType() / getDescriptor()

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#522]
StackWalker.StackFrame.getMethodType() / getDescriptor() need to be implemented for Java 18.3 / 10

**Comment by DanHeidinga** [comment]
@pdbain-ibm You've worked on the StackWalker.  Want to take this?

**Comment by pdbain-ibm** [comment]
@DanHeidinga I'm on it.

**Comment by pdbain-ibm** [comment]
@pshipton Could you send me the javadoc for the new API?

**Comment by pshipton** [comment]
http://cr.openjdk.java.net/~iris/se/18.3/build/latest/api/overview-summary.html

**Comment by pdbain-ibm** [comment]
Pull request https://github.com/eclipse/openj9/pull/758
