### ISSUE TITLE
JDK12u JVM_INTERFACE_VERSION is now 6

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#5223]
The jdk-updates/jdk12u stream has now updated the JVM_INTEFACE_VERSION to 6, we need to align openj9:
01:21:01  Fatal error: JVM interface version mismatch: expecting 6, got 5.
https://hyc-runtimes-jenkins.swg-devops.com/job/Build-JDK12-linux_x86-64_cmprssptrs/152/console

The following latest jdk12u extensions can be used to test with:
git@github.ibm.com:andrew-m-leonard/openj9-openjdk-jdk12test.git

We will need to coordinate the merge into jdk12 extensions with this change...

**Comment by pshipton** [comment]
@JasonFengJ9 can you please create the openj9 PR

**Comment by JasonFengJ9** [comment]
@pshipton sure, will do.

**Comment by JasonFengJ9** [comment]
@andrew-m-leonard there is no `get_source.sh` at `openj9-openjdk-jdk12test.git` provided, could you try my change instead (repo: `https://github.com/JasonFengJ9/openj9`, branch = `jdk12iv`)?

**Comment by andrew-m-leonard** [comment]
@JasonFengJ9 i've just kicked off a build with it here: https://hyc-runtimes-jenkins.swg-devops.com/job/Build-JDK12-linux_x86-64_cmprssptrs/156/

**Comment by andrew-m-leonard** [comment]
@JasonFengJ9 kicked off again as I had left the previous openj9_SHA in there!! 
https://hyc-runtimes-jenkins.swg-devops.com/job/Build-JDK12-linux_x86-64_cmprssptrs/157/

**Comment by JasonFengJ9** [comment]
```
[Pipeline] sh
14:09:17  + git checkout cb728f546925dea79e23540d55cd0d07e2f03c5c
14:09:17  fatal: reference is not a tree: cb728f546925dea79e23540d55cd0d07e2f03c5c
[Pipeline] }
14:09:17  [ssh-agent] Stopped.
```

**Comment by andrew-m-leonard** [comment]
Yes I made a 2nd misstake! 3rd time lucky! and it Succeeds :-)
https://hyc-runtimes-jenkins.swg-devops.com/job/Build-JDK12-linux_x86-64_cmprssptrs/159/

So looks good @JasonFengJ9 
Let me know if you're going to merge your fix, and I will kick off an auto-merge for the jdk12 extensions update.

**Comment by pshipton** [comment]
@andrew-m-leonard please contact me on Slack when you are ready to proceed and I will merge https://github.com/eclipse/openj9/pull/5235

**Comment by pshipton** [comment]
Changes are merged.
