### ISSUE TITLE
JTReg Test Failure - java/lang/Class/forName/NonJavaNames.sh

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#5225]
Consistent failure ...

```
Testing bad class name ``;''
STDERR:
Exception in thread "main" java.lang.ClassFormatError: JVMCFRE068 class name is invalid; class=;, offset=0
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:482)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:451)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:1115)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:903)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:809)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:767)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1055)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:345)
	at NonJavaNames.main(NonJavaNames.java:92)
```

... of test https://github.com/ibmruntimes/openj9-openjdk-jdk12/blob/openj9/test/jdk/java/lang/Class/forName/NonJavaNames.sh observed.

See [consoleText.txt](https://github.com/eclipse/openj9/files/3003021/consoleText.txt).

**Comment by smlambert** [comment]
Excluded via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1027

**Comment by JasonFengJ9** [comment]
This is a dup of https://github.com/eclipse/openj9/issues/3048.
It appears the test expects an `Exception` instead of `ClassFormatError`.
As per Java doc [java.lang.Class.forName()](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#forName-java.lang.String-), it throws:
```
LinkageError - if the linkage fails
ExceptionInInitializerError - if the initialization provoked by this method fails
ClassNotFoundExce
```

**Comment by ben-walsh** [comment]
This test passes against JDK12+Hotspot - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_linux/202/testReport/java_lang_Class_GetPackageBootLoaderChildLayer/java/GetPackageBootLoaderChildLayer

**Comment by ben-walsh** [comment]
This test passes against JDK12+Hotspot - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_linux/202/testReport/java_lang_Class_forName_NonJavaNames/sh/NonJavaNames

**Comment by ChengJin01** [comment]
The problem has nothing to with static verification (ClassFormatError). If the error needs to be captured in ClassforName() instead of later in verification,  verifyQualifiedName() at /runtime/vm/stringhelpers.cpp should be modified against the VM Spec to math Reference Implementation.

**Comment by ben-walsh** [comment]
Yep, this is the problem I believe, the RI is implemented to capture the "bad class name" of `;` earlier than OJ9 and this test checks for that earlier capture.

**Comment by DanHeidinga** [comment]
> verifyQualifiedName() at /runtime/vm/stringhelpers.cpp should be modified against the VM Spec to math Reference Implementation.

Let's give the vm spec a careful re-read and ensure that our behaviour is valid.  Having looked at similar issues in the past, I believe it is but worth validating.

This may just be a test that doesn't apply to OpenJ9

**Comment by ChengJin01** [comment]
The VM Spec at Chapter 4 The class File Format says:
```
4.2 Names
...
 In this internal form, the ASCII periods (.) that normally separate the identifiers
 which make up the binary name are replaced by ASCII forward slashes (/). 
The identifiers themselves must be unqualified names (§4.2.2).
4.2.2 Unqualified Names
... 
An unqualified name must contain at least one Unicode code point
and must not contain any of the ASCII characters . ; [ /   
<-------(that is, period or semicolon or left square bracket or forward slash).
```
This is specific to the check of identifiers (including class names) stored in the class file, which should be addressed by the static verification when loading classes (specifically in `j9bcv_verifyClassStructure `in our case).

In term of a class name string passed-in as argument, there is no rule as to where to check the class name itself. So 1) it can be firstly checked before loading the corresponding class or 2) postponed to the stage of the static verification on the class format.

According to the failing test cases with bad class name (`; [ .`) as follows:
```
forName/testclasses# ls -a -l  (the classes with bad class name were placed here for check)
...
-rw-r--r-- 1 root root  408 Mar 28 15:07 ;.class
-rw-r--r-- 1 root root  408 Mar 28 15:07 ..class
-rw-r--r-- 1 root root  408 Mar 28 15:07 [.class

bash NonJavaNames.sh
Testing bad class name:   ;
java.lang.ClassFormatError: JVMCFRE068 class name is invalid; class=;, offset=0
        at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:482)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:451)
...
Testing bad class name: [
java.lang.ClassNotFoundException: [
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:345)
        at NonJavaNames.main(NonJavaNames.java:92)
Testing bad class name:  .
java.lang.ClassNotFoundException: .
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:345)
        at NonJavaNames.main(NonJavaNames.java:92)
```
Technically, the existing implementation in OpenJ9 already captured these bad class names but treated them in different ways, which might seem kind of confusing to users if they are really concerned about what exception should be thrown out.

We can choose not to modify anything as the problem was already handled or unify the exception/error in our code. Personally I didn't see there is any strong motivation to do that way.

**Comment by smlambert** [comment]
Is the consensus that this test is not applicable to OpenJ9?  

For those trying to increase their OpenJDK contributions, is this test a candidate to fix?

**Comment by ChengJin01** [comment]
@smlambert,  yes this test is not applicable to OpenJ9.

We don't think there is no need to modify our code to throw out exactly the same exceptions because OpenJ9 already captured all errors in the test.

**Comment by DanHeidinga** [comment]
I looked through our code and the confusing thing here is the difference in behaviour between:

https://github.com/eclipse/openj9/blob/ad68fc5e4ef89bdea9f81df7ce2320c56988c38b/runtime/vm/stringhelpers.cpp#L416
and `bcvCheckClassName` which calls:
https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/runtime/verutil/chverify.c#L42

The verifier does the extra checks for `;`,`.`&`[`, etc.  If `verifyQualifiedName` did them as well, OpenJ9 would throw the same exception as the RI as we have code in place to throw CNFE at the start of each of the classloading entry points.

Given it would be fairly straightforward to match the RI here, I think it might be worth doing as `verifyQualifiedName` isn't doing entirely what it claims to be doing

**Comment by ChengJin01** [comment]
If all exceptions should be captured in` verifyQualifiedName()`, then this function doesn't work correctly to handle `; , . [` because the debugging indicates even `ClassNotFoundException `is thrown out due to failure to find the class via `internalFindClassString() `rather than being captured in `verifyQualifiedName()`.

I am trying to refactor the code in ` verifyQualifiedName()` to ensure it captures all error cases at this point.

**Comment by ChengJin01** [comment]
Already verify the failing test with the code changes:
```
bash NonJavaNames.sh
Testing bad class name ``;''
java.lang.ClassNotFoundException: ;
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:345)
        at NonJavaNames.main(NonJavaNames.java:93)
Testing bad class name ``[''
java.lang.ClassNotFoundException: [
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:345)
        at NonJavaNames.main(NonJavaNames.java:93)
Testing bad class name ``.''
java.lang.ClassNotFoundException: .
        at java.base/java.lang.Class.forNameImpl(Native Method)
        at java.base/java.lang.Class.forName(Class.java:345)
        at NonJavaNames.main(NonJavaNames.java:93)
```
And no issue was detected on personal builds on OpenJ9 & internal Java 8.
