### ISSUE TITLE
Docker images are installing gcc 4.8, but should be using gcc 7.3

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5238]
Looking at https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk8/x86_64/ubuntu18/Dockerfile but I expect others need to be fixed as well.

**Comment by pshipton** [comment]
Note https://github.com/eclipse/openj9/issues/5276 - Advertise the buildenv/jenkins/docker-slaves docker files

Perhaps we should retire the Dockerfile's in the  buildenv/docker directory.

**Comment by fjeremic** [comment]
> 
> 
> Perhaps we should retire the Dockerfile's in the buildenv/docker directory.

These are the ones I've been using all the time. I think they also may be references on the official website IIRC. If htis is the case then definitely we need some education/updates and I support removing the stale ones.

**Comment by keithc-ca** [comment]
I plan to address this in the script I'm writing for #5781.

**Comment by pshipton** [comment]
I don't expect the script is going to be ready for the 0.15 release.

**Comment by pshipton** [comment]
I don't see anybody working on this, or anybody complaining. I don't expect the scripts will be ready for 0.17, although they aren't really tied to the release schedule. Moving to the next release.

**Comment by pshipton** [comment]
Fixed by #7465
