### ISSUE TITLE
Rework the omr acceptance schedule

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5275]
OMR acceptance will start a new build every 15 minutes if there are changes. I've seen this result in 3-5 omr acceptance builds all running at the same time. I don't think the jenkins build farm can handle this load as we are light on machines for some platforms. When I see too many omr acceptance builds running, I cancel some of them. Having a large number of omr acceptance builds running can also block OpenJ9 PR testing.

I'm proposing a couple of possible changes
- don't start a new omr acceptance build for 2 hours if there is already one running
- bundle multiple changes into the same build. Wait for 15-20 min after a change is found before starting a build, to see if any additional changes are merged.

**Comment by pshipton** [comment]
@DanHeidinga @AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
> bundle multiple changes.

Ideally the 15 minute window on the mirror would already do that. We could change it to launch with a 20 minute quiet period (longer than the gap between mirrors) which would force back to back mirrors that have changes to be merged as 1 build.

Not starting a build until 2 hours after one is running is a bit trickier and more complicated.

**Comment by AdamBrousseau** [comment]
Talked to Pete.
We've set Quiet period in the job for now at `1200s` which is 20min.
Quiet period is ignored when launched manually.
Mirror job still runs every 15 minutes.
We've also set Throttle builds to 10/day which should limit how often they run.

**Comment by pshipton** [comment]
I'll close this for now, we can re-open later if necessary and the new settings aren't working as desired.
