### ISSUE TITLE
JCK Test in test.jck8b.runtime.lang.FP fail with FP issues on AIX

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#528]
Running the JCK tests against an OpenJ9 with OpenJDK8 give errors in the `test.jck8b.runtime.lang.FP` suite of tests. The actual tests that fail are:
```
javasoft.sqe.tests.lang.fpl036.fpl03602m1.fpl03602m1
javasoft.sqe.tests.lang.fpl036.fpl03602m11.fpl03602m11
javasoft.sqe.tests.lang.fpl036.fpl03602m12.fpl03602m12
javasoft.sqe.tests.lang.fpl036.fpl03602m13.fpl03602m13
javasoft.sqe.tests.lang.fpl036.fpl03602m3.fpl03602m3
javasoft.sqe.tests.lang.fpl036.fpl03602m31.fpl03602m31
javasoft.sqe.tests.lang.fpl036.fpl03602m32.fpl03602m32
javasoft.sqe.tests.lang.fpl036.fpl03602m33.fpl03602m33
```
Which can be executed using a command like (if the STF JCK test framework has been installed):
```
/home/groeges/openj9jdk8/openjdk-jdk8/build/aix-ppc64-normal-server-release/images/j2sdk-image/bin/java -classpath /home/groeges/systemtest_prereqs/jck/jck8b/JCK-runtime-8b/classes javasoft.sqe.tests.lang.fpl036.fpl03602m1.fpl03602m1
```
Theses tests give the following failures:
```
float test failed: format width=53
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=54
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=55
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=56
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=57
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=58
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=59
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=60
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=61
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)

float test failed: format width=62
test_value: 1.0
instead of: 1.0000001 == Float.intBitsToFloat(0x3f000001)
```

These tests also fail  when testing against OpenJ9 with OpenJDK9 (on AIX)
but pass OK when running against a plain OpenJDK8 or OpenJDK9 with hotspot.

**Comment by groeges** [comment]
Similar tests in the test.jck8b.runtime.xopts.vm.fp test suite give the same errors as above. 
Failing tests are:
```
javasoft.sqe.tests.vm.fp.fpm035.fpm03504m1.fpm03504m1
javasoft.sqe.tests.vm.fp.fpm035.fpm03504m5.fpm03504m5
```

**Comment by pshipton** [comment]
@groeges 
Please provide the -version output for the build being tested.
On which AIX OS version (oslevel -s) and xlc version (xlc -qversion) is the OpenJ9 build created? 

There was a FP issue (on Linux x) with a different test for a short time (around Nov 2) which is now resolved, although I suspect this is a different issue. I wasn't able to repeat these failures with the IBM Java 8 build (20171106_369421) which is created on AIX 6.1 TL9 (6100-09-09-1717) with xlc V12.1 (Version: 12.01.0000.0018).

**Comment by pshipton** [comment]
Also, can you please try with -Xint to determine if this issue is caused by the JIT.

**Comment by groeges** [comment]
@pshipton 
```
/home/groeges/openj9jdk8/openjdk-jdk8/build/aix-ppc64-normal-server-release/images/j2sdk-image/bin/java -version 
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-groeges_2017_11_02_10_11-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64 Compressed References 20171102_000000 (JIT enabled, AOT enabled)
OpenJ9   - 315256d
OMR      - 30c2196
OpenJDK  - 19873b0 based on jdk8u152-b03)
```
```
oslevel -s
7200-01-02-1717
```
```
xlc -qversion
IBM XL C/C++ for AIX, V13.1 (5725-C72, 5765-J07)
Version: 13.01.0000.0009
```

**Comment by groeges** [comment]
tried running with -Xint and it made no different to the tests

**Comment by pshipton** [comment]
alternate command line
```
java -classpath /bluebird/javatest/lib/jck/jck8b/JCK-runtime-8b/classes javasoft.sqe.tests.lang.fpl036.fpl03602m1.fpl03602m1
```

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at this?

**Comment by pdbain-ibm** [comment]
@DanHeidinga I'm on it.

**Comment by pdbain-ibm** [comment]
Got the VM, reproduced the problem even with -Xfuture.
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-groeges_2017_11_02_10_11-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64 Compressed References 20171102_000000 (JIT enabled, AOT enabled)
OpenJ9   - 315256d
OMR      - 30c2196
OpenJDK  - 19873b0 based on jdk8u152-b03)

Tested and passing with the IBM proprietary build:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pap6480sr6-20171023_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64 Compressed References 20171107_369540 (JIT enabled, AOT enabled)
OpenJ9   - b3a705b
OMR      - c788ba3
IBM      - b06f521)
JCL - 20170927_01 based on Oracle jdk8u151-b12

Swapping in the jre/lib/ppc64/compressedrefs/lib*.so files from the IBM build makes the test pass.
 
@jdekonin FYI.  Do you have the Java 9 flavour of AIX OpenJ9 available?

**Comment by groeges** [comment]
@pdbain-ibm I have a copy of the AIX OpenJ9 with OpenJDK9 SDK if you cant get it from Joe. 
It is one I built but should be Ok. Or you can get one from AdoptOpenJDK.

**Comment by pdbain-ibm** [comment]
Brewed a stripped-down test case: take a long value 0x20_0000_2000_0001 (2^53 + 2^31 + 1),
convert it to a float, and divide by 2^53.

**Comment by pdbain-ibm** [comment]
Tested with @jdekonin's Java 9 OpenJ9 for AIX. JCK passes fine. I suggest parking this until the official AIX builds are available.

**Comment by pdbain-ibm** [comment]
@groeges Do you see the same issue with your Java 9 OpenJ9 builds?

**Comment by groeges** [comment]
@pdbain-ibm Yes I do see this with my OpenJ9 AIX build but it is quite a old build. 
Rebuilding now just to see if that makes any difference.

If this works on Joe's build, what is the difference between his build and mine.
I also tested this on the OpenJ9 build from AdoptOpenJDK and that also fails with the same errors.
If we are going to get people using builds that are generated from AdoptOpenJDK we need to ensure that these builds are OK. So we need to find why this works on Joe's internal builds but not on any others. 

I listed my build info above, can @jdekonin provide his so we can compare. It may be that I am using a later OS level or xlc level but we will need to get this working with the latest levels of stuff, as that is what customer would potentially be using.

**Comment by groeges** [comment]
Rebuilt my Openj9 with JDK9 and also with JDK8 and still gives the same error.

There must be something different with my build setup if @jdekonin has a build that works.
Joe please can you send me your build environment config as well as the configure options you are using when building on AIX.

**Comment by jdekonin** [comment]
shas based on yesterday EST morning master.  I don't have them on disk anymore, but it was current source.

# oslevel -s
6100-09-09-1717

# /opt/IBM/xlC/13.1.3/bin/xlc -qversion
IBM XL C/C++ for AIX, V13.1.3 (5725-C72, 5765-J07)
Version: 13.01.0003.0000

**Comment by pshipton** [comment]
My guess is the compiler. V13.1 has the problem and V13.1.3 is ok.

**Comment by gaolibj** [comment]
@groeges  Found the similar issue as you.  We also used xlc 13.1.   Have you tried xlc 13.1.3?

**Comment by groeges** [comment]
I am in the process of upgrading to 13.1.3 and will then rebuild and retry the tests. Will update this issue with the results.

**Comment by DanHeidinga** [comment]
@groeges Have you had a chance to test with 13.1.3 yet?  I'd like to get all the java 8 JCK issues resolved asap

**Comment by groeges** [comment]
@DanHeidinga  Sorry I have been on vacation for the last week. I am requesting that 13.1.3 be installed on my AIX system and once that is installed I will rebuild and retest.

**Comment by groeges** [comment]
Having compiled the JDK using XLC 13.1.3 rather than 13.1.0 the FP tests seem to now work:

Started 24-11-17 08-29-15 test.jck8b.runtime.vm.fp Passed
Started 24-11-17 08-30-44 test.jck8b.runtime.xopts.vm.fp Passed
Started 24-11-17 09-30-28 test.jck8b.runtime.lang.FP Passed

I have also used the JDK that was build on AdoptOpenJDK and that also seems to work OK for these tests.

Closing this issue. Please reopen if anyone thinks more work needs to be done on this.
