### ISSUE TITLE
AArch64: Create configuration for native build

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#5285]
Build of AArch64 Linux runtime requires cross-compilation environment in Docker on x86-64 Linux.
There is a request for building the runtime natively on AArch64 Linux.

**Comment by jdekonin** [comment]
Trying looking at what @dsouzai and @JamesKingdon have done via #1159 and #712

**Comment by knn-k** [comment]
The file `runtime/jilgen/module.xml` uses `qemu-aarch64` for running `constgen` in the cross build.  I have found I can build the runtime natively on AArch64 Linux by changing that file.
Now my question is: **How can you detect the native/cross-building environment in `module.xml`?**  Is there any flag that can be used for that purpose?

The AArch64 build does not support DDR at the moment (#5221).  When we support it, `runtime/ddr/module.xml` also needs to be modified because it uses `qemu-aarch64`.

**Comment by hangshao0** [comment]
It seems that we do not have an existing flag for this purpose. You might need to add a new flag. Not sure if it is worth the effort, as uma is going to be replaced by cmake shortly. Adding a new spec might be an easier solution for now.

**Comment by knn-k** [comment]
@hangshao0 Thank you for your suggestion.  What is the plan for moving to cmake?

**Comment by hangshao0** [comment]
> What is the plan for moving to cmake?

@dnakamura

**Comment by pshipton** [comment]
Note there is a cmake plan of sorts in #90

**Comment by knn-k** [comment]
I opened #5321 and https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/149 adding a new flag to j9.flags as a short-term solution.
