### ISSUE TITLE
Missed trace points with maximal/minimal and none

### ISSUE THREAD

**Issue by amicic** [eclipse/openj9#5290]
Java -version output
------------------
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pxa6480sr6-20190325_02(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190326_413077 (JIT enabled, AOT enabled)
OpenJ9   - b990b1c
OMR      - 35ccc22
IBM      - 72459d3)
JCL - 20190311_01 based on Oracle jdk8u211-b78
```

Summary of problem
------------------

`-Xtrace` with maximal or minimal and none,  only enables the last trace point in a list of trace points

Exact option used: 

```
-Xtrace:none,minimal={j9mm.630,j9mm.190-191,j9mm.474-475,j9mm.467-468,j9mm.54},output="output%p.trc"
```

Trace point reported:

```
15:46:07.425608000 *0x0000000001804600 j9mm.54             Event       Mark start
15:46:39.016991000  0x0000000001804600 j9mm.54             Event       Mark start
15:46:48.150756000  0x0000000001804600 j9mm.54             Event       Mark start
15:46:54.697912000  0x0000000001804600 j9mm.54             Event       Mark start
```

When used iprint without none, all trace points were reported (this is just a short sample): 

```
15:55:38.293 0x159b600            j9mm.191       < MM_GlobalCollector_isTimeForClassUnloading result = true
15:55:38.294 0x159b600            j9mm.54        - Mark start
15:55:38.296 0x159b600            j9mm.475       - GlobalGC end: workstackoverflow=0 overflowcount=0 memory=5368097584/10737418240
```

When the list is broken down, everything works as expected, too:

```
-Xtrace:none,minimal=j9mm.630,minimal={j9mm.190-191},minimal={j9mm.474-475},minimal={j9mm.467-468},minimal=j9mm.54,"output=output%p.trc"
```

This was run with `-Xgcpolicy:metronome  -verbose:gc`, but probably not relevant to the root cause. Still mentioning, since default GC policy (gencon) may not issue some of these trace points, at all.

**Comment by keithc-ca** [comment]
@amicic This could be a simple misunderstanding of how your shell processes arguments. Bash (and other shells) attribute special meaning to `{` and `}`. For example, running
```
for arg in -Xtrace:none,minimal={j9mm.630,j9mm.190-191,j9mm.474-475,j9mm.467-468,j9mm.54},output="output%p.trc" ; do echo ARG : $arg ; done
```
yields
```
ARG : -Xtrace:none,minimal=j9mm.630,output=output%p.trc
ARG : -Xtrace:none,minimal=j9mm.190-191,output=output%p.trc
ARG : -Xtrace:none,minimal=j9mm.474-475,output=output%p.trc
ARG : -Xtrace:none,minimal=j9mm.467-468,output=output%p.trc
ARG : -Xtrace:none,minimal=j9mm.54,output=output%p.trc
```
while running
```
for arg in "-Xtrace:none,minimal={j9mm.630,j9mm.190-191,j9mm.474-475,j9mm.467-468,j9mm.54},output=output%p.trc" ; do echo ARG : $arg ; done
```
yields
```
ARG : -Xtrace:none,minimal={j9mm.630,j9mm.190-191,j9mm.474-475,j9mm.467-468,j9mm.54},output=output%p.trc
```
The only difference is the placement of the quote (`"`). In the first version, each `-Xtrace:none` erases any previous trace settings which is consistent with your experience.

Can you try again with the quotes around the whole option?

**Comment by amicic** [comment]
@keithc-ca Thanks for the elaborative answer. The quotes around it, indeed fixed it.

**Comment by amicic** [comment]
Btw, the quotes from just around the output file name came from https://www.eclipse.org/openj9/tools/xtrace_option_builder.html

![image](https://user-images.githubusercontent.com/18264984/55237890-88834b80-5209-11e9-9b9d-dda7862648a4.png)

**Comment by keithc-ca** [comment]
I create #5303 for that.
