### ISSUE TITLE
Include J9VMThread in `!info thread` output in jdmpview

### ISSUE THREAD

**Issue by sehirst** [eclipse/openj9#5295]
The `!stackslots` output is usually the most important output to begin investigating a dump on exception. It requires the `J9VMThread` of the thread throwing the exception.

The only way I know how to get this is to first do `!info thread` to get the thread that's executing, but this does not have the `J9VMThread`, instead it has the Thread object and posix thread id.

To get the `J9VMThread` we need to run `!threads` and then correlate the posix thread id with the appropriate thread to get the `J9VMThread`.

It would be more efficient to simply include the `J9VMThread` in the `info thread` output.

**Comment by fjeremic** [comment]
@keithc-ca FYI.

**Comment by keithc-ca** [comment]
I have worked out how to add the following to the output of `info thread`
```
Native info:   !j9vmthread 0x1e700  !stack 0x1e700
```
@sehirst Will that work for you, or do you think `!stackslots` needs to be there (as well or instead of `!stack`)?

**Comment by sehirst** [comment]
That's perfect. Thanks!!

**Comment by keithc-ca** [comment]
Fixed via #5382.
