### ISSUE TITLE
Bad advice from -Xtrace option builder tool

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#5303]
https://www.eclipse.org/openj9/tools/xtrace_option_builder.html suggests double-quotes only around the `output=...` portion of the string which doesn't work well with bash (or other shells that attach special meaning to `{` and `}`). See #5290.

**Comment by pshipton** [comment]
@SueChaplain @paulcheeseman

**Comment by pshipton** [comment]
This is probably better opened at https://github.com/eclipse/openj9-website since that is the repo which contains the problematic code.

**Comment by paulcheeseman** [comment]
Checking the "Wrap in quotes (for use in a shell)" option at the bottom of the tool should solve the problem.

**Comment by keithc-ca** [comment]
Superseded by eclipse/openj9-website#164.
