### ISSUE TITLE
Enable jck test "test.jck8b.runtime.api.signaturetest" to pass

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#531]
JCK test "test.jck8b.runtime.api.signaturetest" fails on OpenJDK8 on OpenJ9 because it does not expect the following methods in MethodHandle:

protected MethodHandle getTarget()
public MethodHandle asTypeUncached(MethodType)

These methods are present in J9JCL's MethodHandle.

**Comment by adamfarley** [comment]
Note: the affected methods are both stub methods, so in theory altering the scope of one and removing another should change precisely nothing, especially as the changes bring us closer to the OpenJDK reality, not further away.

**Comment by adamfarley** [comment]
Pull Request: https://github.com/eclipse/openj9/pull/530

**Comment by pshipton** [comment]
@adamfarley FYI a Pull Request is sufficient when a fix is available, you don't need to open an Issue to correspond to every Pull Request. An Issue would be appropriate when a fix isn't available or you want to have a discussion before making any code changes.

**Comment by adamfarley** [comment]
Ok. Will remember that for next time. Closing the issue.

**Comment by JasonFengJ9** [comment]
Chatted with Adam about his PR during early morning. Will take care this instead.

**Comment by pshipton** [comment]
command line example
```
java  -classpath /bluebird/javatest/lib/jck/JCK8b-b03/JCK-runtime-8b/classes javasoft.sqe.tests.api.signaturetest.JCKSigTest.basicTests -TestURL file:/bluebird/javatest/lib/jck/JCK8b-b03/JCK-runtime-8b/tests/api/signaturetest/sigtest.basic.html#basic -profile 4
```
