### ISSUE TITLE
ClassCastException thrown at Logger.getLogger()

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#5325]
Java -version output
--------------------

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+2-201903171911)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f2782748f, JRE 11 Linux amd64-64-Bit Compressed References 20190317_171 (JIT enabled, AOT enabled)
OpenJ9   - f2782748f
OMR      - 9b73e2bd
JCL      - 3cd1a589af based on jdk-11.0.3+2)
```

Summary of problem
------------------

Test case code snippet:
```
import java.util.logging.Handler;
import java.util.logging.LogManager;
import java.util.logging.Logger;

public class TestSimpleLoggerGC {
	private static final String LOGGER_FOO = "com.foo.bar.zzz";

	public static void main(String[] args) {
		new TestSimpleLoggerGC().testAll();
	}

	static final class TestLogger extends java.util.logging.Logger {
		public TestLogger(String name, String resourceBundleName) {
			super(name, resourceBundleName);
		}
		@Override
		public Handler[] getHandlers() {
			return super.getHandlers();
		}
	}

	void testAll() {
		TestLogger tl = new TestLogger(LOGGER_FOO, null);
		LogManager.getLogManager().addLogger(tl);
		for (int i = 0; i < 48; i++) {
			System.gc();
		}
		tl = (TestLogger)Logger.getLogger(LOGGER_FOO);
		System.out.println("TestLogger tl: " + tl);
	}
}
```

```
Exception in thread "main" java.lang.ClassCastException: java.util.logging.Logger incompatible with atestse.java_util_logging.TestSimpleLoggerGC$TestLogger
	at atestse.java_util_logging.TestSimpleLoggerGC.testAll(TestSimpleLoggerGC.java:33)
	at atestse.java_util_logging.TestSimpleLoggerGC.main(TestSimpleLoggerGC.java:11)
```

`RI` finished without `ClassCastException`.

Diagnostic files
----------------

n/a

**Comment by JasonFengJ9** [comment]
This occurs to `-Xint` and gc policies `optthruput`, `gencon` and `balanced`.

fyi @dmitripivkine

**Comment by JasonFengJ9** [comment]
**Update:**

First, if moving `TestLogger tl = new TestLogger(LOGGER_FOO, null);` out of instance method `testAll()` to class level just above `main`, i.e., just after `LOGGER_FOO` declaration, `OpenJ9` finishes without `ClassCastException`.

The reason for the `weak reference` to `tl` within `LogManager` is removed is that `TestLogger tl` declared within `testAll()` is not considered a `strong` reference hence GC swiped out the `weak reference` to `tl`.

This is a known issue and probably won't be addressed. A workaround is to create a `strong` reference  in class level mentioned earlier.

fyi: @gacholio @DanHeidinga

**Comment by DanHeidinga** [comment]
This is the standard keepAlive problem.  OpenJ9 aggressively allows objects to be GC'd when they are no longer referenced by further bytecodes in the method.  

If the test is relying on the TestLogger instance to be kept alive, it needs to do something to ensure it is alive.  See also [Reference#reachabilityFence](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/Reference.html#reachabilityFence(java.lang.Object))
