### ISSUE TITLE
OpenJ9 should ignore unknown JVM options when started from C++ instead of stopping with JVMJ9VM007E

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#5332]
Hello,

While trying to use AdoptOpenJDK8 with OpenJ9 on various legacy applications, I found a generic issue which doesn't hit the AdopOpenJDK8 with HotSpot flavor with applications launching the JVM from C++ code with some empty JVM options.

In this case, running those legacy apps with OpenJ9 breaks the application with the following error message:

> JVMJ9VM007E Command-line option unrecognised:

while using HotSpot at same Java 8 update level runs smoothly.

My understanding is that OpenJ9 community is willing to make replacement of HotSpot by OpenJ9 a smooth experience, but here this is failing and I guess that fixing this in OpenJ9 would be quite simple.

I have created a sample to reproduce the issue.
Please note that I have installed:

- AdoptOpenJDK8 update 202 with OpenJ9 in /home/data/Java/AdoptOpenJDK/j9-jdk8u202-b08
- AdoptOpenJDK8 update 202 with HotSpot in /home/data/Java/AdoptOpenJDK/hotspot-jdk8u202-b08

1. Create a file called sampleJNI.cpp with the following content (source also attached to the incident):

```
#include <jni.h>
#include <iostream>
#include <stdlib.h>

int main()
{
       JavaVM *jvm;                      // Pointer to the JVM (Java Virtual Machine)
       JNIEnv *env;                      // Pointer to native interface
           //================== prepare loading of Java VM ============================
       JavaVMInitArgs vm_args;                        // Initialization arguments
       JavaVMOption* options = new JavaVMOption[2];   // JVM invocation options
       options[0].optionString = "";
       options[1].optionString = "-Djava.class.path=.";   // where to find java .class
       vm_args.version = JNI_VERSION_1_6;             // minimum Java version
       vm_args.nOptions = 1;                          // number of options
       vm_args.options = options;
           //=============== load and initialize Java VM and JNI interface =============
       jint rc = JNI_CreateJavaVM(&jvm, (void**)&env, &vm_args);  // YES !!
       delete options;    // we then no longer need the initialisation options.
       if (rc != JNI_OK) {
              // TO DO: error processing...
             std::cin.get();
             exit(EXIT_FAILURE);
       }
          //=============== Display JVM version =======================================
       std::cout << "JVM load succeeded: Version ";
       jint ver = env->GetVersion();
       std::cout << ((ver>>16)&0x0f) << "."<<(ver&0x0f) << std::endl;

       jvm->DestroyJavaVM();
}
```

2. Compile it:
```
export JAVA_HOME=/home/data/Java/AdoptOpenJDK/j9-jdk8u202-b08
g++ -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/linux" -L"$JAVA_HOME/jre/lib/amd64/server" sampleJNI.cpp -ljvm -ldl
```

3. Run it with OpenJ9:
```
export JAVA_HOME=/home/data/Java/AdoptOpenJDK/j9-jdk8u202-b08
export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
./a.out
```
It prints:

> JVMJ9VM007E Command-line option unrecognised:

It fails without printing the requested Java version.

4. Run it with Hotspot:

```
export JAVA_HOME=/home/data/Java/AdoptOpenJDK/hotspot-jdk8u202-b08
export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
./a.out
```
It prints:
> JVM load succeeded: Version 1.8

It works and prints the requested Java version.

I would 100% agree that this sample sounds artificial and that a properly written application shouldn't add such empty JVM options. Unfortunately, couple of legacy applications I have tried have been written & tested with ORACLE Java, whose behavior is same here as AdoptOpenJDK with HotSpot, so this kind of issue was unseen, and it's too late to fix already released application to switch these to OpenJ9-based Java.

I have tested the same scenario with AdopOpenJDK11, and HotSpot behavior with such empty options remains to ignore them, while OpenJ9 fails with JVMJ9VM007E.

Would it be possible to make OpenJ9 consistent with HotSpot on this behavior?

If OpenJ9 developers fears to introduce a regression by changing this behavior, then could this "tolerant behavior" be activated using an environment variable that I could set before running the legacy application(s) impacted by this issue?

**Note:** this issue vaguely seems to be related to https://github.com/eclipse/openj9/issues/2977, but I'm unsure since my sample doesn't relies on -XX options.

Kind regards,
Alexandre Vermeerbergen

[sampleJNI.zip](https://github.com/eclipse/openj9/files/3035727/sampleJNI.zip)

**Comment by DanHeidinga** [comment]
This sounds like a bug.  I've tentatively assigned it to Milestone 15 (July refresh)

**Comment by avermeer** [comment]
Is it really too late for Milestone 14 (April refresh if I'm not mistaken)? My guess is that it's a quite small fix, but I can be wrong.

**Comment by DanHeidinga** [comment]
It'll depend on when we're able to investigate this and how risky the fix is.  If it's something straightforward found quickly, then we look at putting it in 0.14

**Comment by avermeer** [comment]
Alright, thanks!

**Comment by pshipton** [comment]
Moved it to the 0.14 milestone to ensure we don't forget. This is not a commitment to fix it in 0.14

**Comment by JasonFengJ9** [comment]
will have a look.

**Comment by JasonFengJ9** [comment]
@sharon-wang is working on it already

**Comment by sharon-wang** [comment]
Opened https://github.com/eclipse/openj9/pull/5353 to address this issue.

It ignores options that are empty ("") or that only contain white space characters to match the RI behaviour.

**Comment by avermeer** [comment]
Hello @sharon-wang,

I am glad to see that you extended the fix to ignore Java options only made of white spaces, as it can happen and it is also ignored by HotSpot-based Java Runtimes.

Please let me know when your fix will be available in AdoptOpenJDK nightly builds. I will test my legacy apps which currently fail to start with OpenJ9 using such nightly builds, and I will let you know if the issue is solved with those real-life cases.

Kind regards,
Alexandre

**Comment by pshipton** [comment]
Keep this open until the change is delivered in the 0.14 branch.

**Comment by pshipton** [comment]
#5392 is merged in the 0.14 branch.

**Comment by sharon-wang** [comment]
@avermeer The fix is now available in the AdoptOpenJDK nightly builds:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u212-b01_openj9-0.14.0-m1
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.3+2_openj9-0.14.0-m1

**Comment by pshipton** [comment]
Better to use the release builds please.
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u212-b03_openj9-0.14.0
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.3%2B7_openj9-0.14.0
