### ISSUE TITLE
Fix behaviour of XX:-IdleTuningGcOnIdle

### ISSUE THREAD

**Issue by ShishirH** [eclipse/openj9#5374]
In a container environment, both XX:+IdleTuningGcOnIdle and XX:+IdleTuningCompactOnIdle are enabled by default. Right now, XX:-IdleTuningGcOnIdle only does not release the pages back to the OS. Because CompactOnIdle is enabled in the container, GC still takes place. This can be easily verified by a simple program that sleeps for a few minutes, running the program in a container, and looking at the logs.

This behaviour would probably be unintuitive for the users, who would expect setting XX:-IdleTuningGcOnIdle would stop idle gc. The only two ways to currently stop GC on idle in a container are:
1. Use both XX:-IdleTuningGcOnIdle and XX:-IdleTuningCompactOnIdle or
2. Use -XX:IdleTuningMinIdleWaitTime=0, which prevents idle detection, and thus idle GC cycles.

Ideally, XX:+IdleTuningGcOnIdle should both perform GC and release pages. If disabled, it should do neither.

One way of designing could be to display a warning that idle gc needs to be enabled when XX:-IdleTuningGcOnIdle and XX:+IdleTuningCompactOnIdle are used. The behaviour then would be

| gcOnIdle | compactOnIdle | Behavior                                 |
|----------|---------------|------------------------------------------|
| Enabled  | Enabled       | gc on idle -> compaction + release pages |
| Enabled | Disabled       | gc on idle + release pages                          |
| Disabled | Enabled | Display warning                            |
| Disabled  | Disabled | No gc on idle               |

gcOnIdle is enabled when XX:+IdleTuningGcOnIdle is used and disabled when XX:-IdleTuningGcOnIdle is used. compactOnIdle similarly follows IdleTuningCompactOnIdle.

Code that governs this behaviour: 
https://github.com/eclipse/openj9/blob/2b707c264308cf5ba413b476c835b1bf6c98ec50/runtime/gc_modron_startup/mminit.cpp#L486

@DanHeidinga @dmitripivkine @dinogun

**Comment by ashu-mehra** [comment]
@gjdeval - fyi

**Comment by DanHeidinga** [comment]
Thanks for reporting this @ShishirH.

I agree that it's not intuitive to need to set both `XX:-IdleTuningGcOnIdle` and `XX:-IdleTuningCompactOnIdle` to actually disable GC on idle.

The way to approach this is to make CompactOnIdle a subset (tuning) of GCOnIdle.  

So the following would be legal:

gcOnIdle | compactOnIdle | Behavior
-- | -- | --
Enabled | Enabled | gc on idle -> compaction + release pages
Enabled | Disabled | gc on idle + release pages
Disabled | illegal | Illegal
Disabled | illegal | illegal

In that it only makes sense to tune the compaction if the gcOnIdle is already enabled.

Default behaviour would be to silently ignore compactOnIdle if gcOnIdle is disabled and otherwise fail to start the VM.

@dinogun Does that approach contradict any of the original design discussions on this feature?

**Comment by ashu-mehra** [comment]
We should also add some command-line tests to ensure the combination of these options is working as expected.

**Comment by ShishirH** [comment]
@DanHeidinga Can you please clarify if the default behaviour would be a fatal error, or just ignore the option and run?

**Comment by dinogun** [comment]
Going over the original design, the options and their meanings were as follows
```
if only compactOnIdle is set then invoke “global_GC*_with_forced compaction”
if only gcOnIdle is set then invoke “global_GC* + release free memory pages”
if both gcOnIdle + CompactOnIdle are set then invoke “global_GC*_with_forced compaction + release free memory pages”
```

So it looks like the name `gcOnIdle` was overloaded as `do GC + free pages`. Not sure if we can change the name now (?), assuming it cannot be, I would suggest that we just change the documentation to make it clear how to ensure no GC happens on Idle. 

I'd suggest adding the following statement for both [IdleTuningGcOnIdle](https://www.eclipse.org/openj9/docs/xxidletuninggconidle/) and [IdleTuningCompactOnIdle](https://www.eclipse.org/openj9/docs/xxidletuningcompactonidle/).
```
To ensure that no GC happens on Idle, set both  `-XX:-IdleTuningGcOnIdle` and `-XX:-IdleTuningCompactOnIdle`
```

**Comment by ShishirH** [comment]
@DanHeidinga FYI

**Comment by dmitripivkine** [comment]
IMO it is overcomplicated. GC should always try to do compact before idle. I believe time for compact operation is much less then expected idle time but allows to release memory significantly more effective.

**Comment by ashu-mehra** [comment]
> GC should always try to do compact 

@dmitripivkine If we always want to do compaction, then we won't need CompactOnIdle option. Are you suggesting that we should have only one option `IdleTuningGcOnIdle` that controls all the three operations - global gc + compaction + decommit?

**Comment by dmitripivkine** [comment]
> > GC should always try to do compact
> 
> @dmitripivkine If we always want to do compaction, then we won't need CompactOnIdle option. Are you suggesting that we should have only one option `IdleTuningGcOnIdle` that controls all the three operations - global gc + compaction + decommit?

yes

**Comment by ashu-mehra** [comment]
@dinogun @DanHeidinga @pshipton any concerns if we use only one option `IdleTuningGcOnIdle` as suggested above. If we want to remove `CompactOnIdle`, can we just remove it or do we need to first deprecate it?

**Comment by gjdeval** [comment]
From a user perspective, having a single option to turn on/off the "reduce
memory footprint when idle" function sounds like a good idea, mostly users
do not understand the underlying GC sub-operations (and do not want
to ... ;-)

If it seemed useful, we might keep finer-grained controls available for
diagnosis or triage, "unofficially" ... though of course everything will be
visible to those who care to read the code.


Cheers,
Gary DeVal
IBM WebSphere Performance Engineering
Email:  gjdeval@us.ibm.com

**Comment by DanHeidinga** [comment]
@dinogun @ashu-mehra Do you recall from the original designs for this feature why compact was split out separately?  Did users request the ability to treat the operations separately?

The single option is a clear story for users to understand though I'm loathe to remove the ability to differentiate if it was driven by real user requests.

**Comment by ashu-mehra** [comment]
@DanHeidinga digging up previous discussion, I figured that it was a conscious decision to keep `compact` and `free pages` independent so that `compact` can be set without requiring freeing the pages. This could be useful when running in a dedicated box (non-cloud) where freeing the pages wouldn't be beneficial.
I will mail you the link where we discussed this. As that link is internal to IBM, so won't be useful to put it over here.

**Comment by amicic** [comment]
The value of compact is to squeeze extra free memory (pages). 

Normally, compact triggers are rather passive (we don't wont to introduce long pauses for small gains in free memory with actively running applications). 

Doing always compact is another opposite extreme.

A compromise would be to introduce additional, more aggressive compact triggers, that would be (by default) used only for this scenario (idle detection). Then we could get rid of compact-on-idle option.

We have some metrics about fragmentation (this is relatively new thing) that we could based it off.

**Comment by ashu-mehra** [comment]
I agree with @amicic . If we can use some heuristics to decide on compaction, then we don't really need any option to control it, which also spares the users from understanding another technicality.
@amicic can you please provide more details about the fragmentation metrics that you mentioned in the previous comment?

However, this would only address one part of the problem. The other part is freeing of heap pages, and as I mentioned earlier there was a deliberate decision to keep `global_gc + free pages` independent of `global gc + compact`. Do we still want to maintain that? If yes, then we need two options.

**Comment by amicic** [comment]
Here is a proposal for compact trigger. I put it on OMR side, since most of the logic would be there, but we can move it on OpenJ9 side if it makes more sense.

https://github.com/eclipse/omr/issues/3797

**Comment by amicic** [comment]
Introduction of this compact trigger is relatively small work item. While someone from IBM Cloud team could work on this, IBM Core VM team will soon have a junior person that could work on it.

**Comment by ShishirH** [comment]
@DanHeidinga If the heuristics are implemented, that would ideally remove the need for a CompactOnGc option. Do we need another option for freeing pages? Or will bunding `glocal_gc + compact + free_pages` together in one IdleTuningGcOnIdle option be fine?

@amicic May I know if your team is working on the heuristics?

**Comment by amicic** [comment]
@ShishirH Yes, I believe we'll have someone start soon. We should be able to introduce the heuristic, and and you would then try to make use of it: test it, validate if it's useful, if necessary tune it...

**Comment by DanHeidinga** [comment]
Once we have the heuristics @amicic mentioned then it makes sense to bundle `glocal_gc + compact + free_pages` together in one IdleTuningGcOnIdle option.

The `XX:-IdleTuningCompactOnIdle` option should be deprecated now to indicate that it will be removed in the future.

The code can also be updated as suggested above so that ``XX:[+-]IdleTuningCompactOnIdle` without `XX:+IdleTuningGcOnIdle` is an error / ignored.  As these are XX options, the correct behaviour is to ignore them unless `-XX:-IgnoreUnrecognizedXXColonOptions` is set

**Comment by ShishirH** [comment]
@DanHeidinga For marking the option as deprecated, would a doc change suffice? Or is there anything else that needs to be done?

**Comment by DanHeidinga** [comment]
> For marking the option as deprecated, would a doc change suffice?

Yes, a doc change is sufficient

**Comment by ShishirH** [comment]
https://github.com/eclipse/openj9/pull/5894 fixes the issue.

**Comment by amicic** [comment]
Compact trigger is in:
https://github.com/eclipse/omr/pull/3939
https://github.com/eclipse/openj9/pull/5992

In short, when GC-on-idle is triggered, optional compact will be performed based on heuristic.

There is threshold parameter that can be controlled by -XXgc:gcOnIdleCompactThreshold= option. Default value is 25, meaning if there is a potentially 25% or more fragmented free memory (ot of existing free memory) that would be freed up (and decommited by GC-idle logic) .

If compact triggers, there will be a clear reason message in verbose GC.

One can try some other value, for example 40 (less likely to trigger compact) or 10 (more likely to trigger compact). Valid value are [0-100]. 

This is not an option I would document - it's unlikely this will be exposed to a customer. But we can use it now to tune the default threshold to a reasonable value.

**Comment by ShishirH** [comment]
@ashu-mehra @DanHeidinga While the heuristics added would allow more efficient memory release in a default use case, because we are not documenting the options to control the heuristics, there would be no way of always doing compact if the user wants to do so, once the option `XX:IdleTuningCompactOnIdle` is deprecated, and removed in the future.

For such a use case, it might make sense to keep `XX:IdleTuningCompactOnIdle` and not deprecate it.

**Comment by DanHeidinga** [comment]
>  it might make sense to keep XX:IdleTuningCompactOnIdle and not deprecate it.

Deprecating the option doesn't prevent users from using it and signals our intention that it's unnecessary given the heuristics that have been put in place.

If users find it's necessary to set it explicitly, then we can easily un-deprecate it.

**Comment by amicic** [comment]
I believe setting gcOnIdleCompactThreshold to 0 would effectively give you IdleTuningCompactOnIdle  behaviour.
