### ISSUE TITLE
The shared cache compatibility broken

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9#5380]
New bytecodes were introduced by #1831, which breaks the shared cache compatibility. The shared cache generation was not increased. 

A simple test case is:
```
class Test 
{ 
    public static boolean doPrint() {
		return true;
	}
	public static void main(String args[]) 
    { 
		if (doPrint()) {
			System.out.println("Hello, World"); 
		}
    } 
} 
```

I stored the class to the shared cache using an old JVM before #1831. 
```
java -Xshareclasses:name=Cache1 Test
Hello, World
```
Then startup the shared cache again using the newest JVM (with -Xshareclasses:readonly). 
`java -Xshareclasses:name=Cache1,readonly Test`

I get:
```
Exception in thread "main" java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=Test, method=doPrint()Z, pc=1
Exception Details:
  Location:
    Test.doPrint()Z @1: JBireturn
  Reason:
    Type integer (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @1
    flags: { }
    locals: { }
    stack: { integer }
        at java.lang.J9VMInternals.prepareClassImpl(Native Method)
        at java.lang.J9VMInternals.prepare(J9VMInternals.java:304)
        at java.lang.Class.getMethodHelper(Class.java:1243)
        at java.lang.Class.getMethod(Class.java:1187)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:556)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:538)
```

**Comment by fjeremic** [comment]
@hangshao0 can you ensure whoever fixes this that we add a unit test into our sanity builds so this doesn't happen in a future change?

**Comment by hangshao0** [comment]
FYI: @dnakamura

**Comment by DanHeidinga** [comment]
Discussed with @hangshao0:
* OpenJ9 stores the SHA into the cache header and will normally attempt to delete and recreate the cache if the SHAs are different
* Under some circumstances, the cache can't be deleted (group access + readonly) and the VM continues to use it despite the SHA difference
* There are a large number of ways that the compatibility can be broken (romclass changes, new bytecodes, cache structure changes) but they are rare.

Need to find out more of the history to determine why the cache is not ignored when there is a SHA mismatch.

**Comment by pshipton** [comment]
@DanHeidinga the cache generation changes are delivered. Did you want to keep this open or can it be closed?

**Comment by DanHeidinga** [comment]
I had been keeping it open to try to address
>ensure whoever fixes this that we add a unit test into our sanity builds so this doesn't happen in a future change?

but after discussing various options, I haven't been able to come up with a reliable way to test this as it would require validating a cache is always shareable between the current and previous builds and we don't typically have both on a filesystem to test with.  It would also require hitting the particular case that causes the problem.... and that case can change each time.

I think we need to continue to be diligent about catching changes to the cache structure, romclasses, and bytecodes but I don't see a good way to test this.

Closing.
