### ISSUE TITLE
cmake build problems

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5391]
jdk8
----
This is happening in OpenJ9 and OMR acceptance builds, likely since https://github.com/eclipse/openj9/pull/5386 was merged
https://ci.eclipse.org/openj9/job/Build-JDK8-linux_x86-64_cmprssptrs_cmake/185
https://ci.eclipse.org/openj9/job/Build-JDK8-linux_x86-64_cmprssptrs_cmake/186
```
04:00:01  CMake Error at CMakeLists.txt:269 (add_dependencies):
04:00:01    The dependency target "run_cptool" of target "omrutil_obj" does not exist.
```

jdk11
-----
OMR acceptance failure since https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/1295/
OpenJ9: 9ef06ee
OMR: 5f0f036
I promoted this OMR level hoping to fix the jdk8 problem, so I expect it occurs at openj9 now as well.
https://ci.eclipse.org/openj9/job/Build-JDK11-linux_x86-64_cmprssptrs_cmake/185
```
07:17:24  gmake[6]: Leaving directory '/home/jenkins/workspace/Build-JDK11-linux_x86-64_cmprssptrs_cmake/build/linux-x86_64-normal-server-release/vm'
07:17:25  [  8%] Building C object runtime/omr/omr/CMakeFiles/omrcore.dir/home/jenkins/workspace/Build-JDK11-linux_x86-64_cmprssptrs_cmake/openj9/runtime/gc_glue_java/LanguageVMGlue.c.o
07:17:25  [  8%] Built target j9vm_nlsgen
07:17:25  In file included from /home/jenkins/workspace/Build-JDK11-linux_x86-64_cmprssptrs_cmake/openj9/runtime/gc_glue_java/LanguageVMGlue.c:23:0:
07:17:25  /home/jenkins/workspace/Build-JDK11-linux_x86-64_cmprssptrs_cmake/openj9/runtime/oti/j9.h:52:10: fatal error: j9vmconstantpool.h: No such file or directory
07:17:25   #include "j9vmconstantpool.h"
07:17:25            ^~~~~~~~~~~~~~~~~~~~
07:17:25  compilation terminated.
07:17:25  runtime/omr/omr/CMakeFiles/omrcore.dir/build.make:214: recipe for target 'runtime/omr/omr/CMakeFiles/omrcore.dir/home/jenkins/workspace/Build-JDK11-linux_x86-64_cmprssptrs_cmake/openj9/runtime/gc_glue_java/LanguageVMGlue.c.o' failed
```

**Comment by pshipton** [comment]
@dnakamura

**Comment by keithc-ca** [comment]
Perhaps we're missing the equivalent of https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/153 for jdk8?

**Comment by keithc-ca** [comment]
I expect that #5398 will fix this - time will tell.
