### ISSUE TITLE
JMX MemoryPool MBean for JIT code cache reports 0 for "used"

### ISSUE THREAD

**Issue by PhilWakelin** [eclipse/openj9#5418]
Java -version output
--------------------

java.fullversion: JVM version: 8.0.5.35 - pmz6480sr5fp35-20190402_01(SR5 FP35) JRE 1.8.0 z/OS s390x-64-Bit 20190401_413512 (JIT enabled, AOT enabled) OpenJ9 - cd21265 OMR - 16b77d7 IBM - 72459d3

Summary of problem
------------------
Following testing of https://github.com/eclipse/openj9/issues/4674 here are some stats produced by my servlet MemoryPool MBean browser
```
JIT code cache: init=2048K max=262144K used=0K committed=208896K
JIT data cache: init=0K max=393216K used=10240K committed=12288K
```

Here is the JIT code cache data summary from the Java core that maps to the above
```
1STSEGTOTAL    Total memory:                   213909504 (0x000000000CC00000)
1STSEGINUSE    Total memory in use:             17853408 (0x0000000001106BE0)
1STSEGFREE     Total memory free:              196056096 (0x000000000BAF9420)
1STSEGLIMIT    Allocation limit:               268435456 (0x0000000010000000) 
```

You can see that committed= Total memory and max=Allocation limit
However, used is always 0K for the JIT code cache MBean data, whereas it reports the equivalent of "Total memory in use" for the other beans such as the data cache.

I have viewed the MBeans in JConsole and also see that  JIT code cache used is always 0 in the JConsole UI

Diagnostic files
----------------
[javacore.20190409.102315.67174515.0002.txt](https://github.com/eclipse/openj9/files
/3059222/javacore.20190409.102315.67174515.0002.txt)

**Comment by PhilWakelin** [comment]
I have tested on FP40 on V2R3 and my testcase still show the following with the used value of 0.

JIT code cache: init=262144K max=262144K used=0K committed=262144K

**Comment by pshipton** [comment]
A new issue #7171 is opened for the problem.
