### ISSUE TITLE
cmake testing failing

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5447]
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_linux_cm/3
`ERROR: No item named Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_OMR found`
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_linux_cm/4
`ERROR: No item named Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly found`

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Created the following "hello world" test jobs
[Test_openjdk11_j9_sanity.functional_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_cm_Nightly/)
[Test_openjdk11_j9_extended.functional_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_cm_Nightly/)
[Test_openjdk11_j9_sanity.system_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_cm_Nightly/)
[Test_openjdk11_j9_extended.system_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_cm_Nightly/)
[Test_openjdk11_j9_sanity.functional_x86-64_linux_cm_OMR](https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_cm_OMR/)

[Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_Nightly/)
[Test_openjdk8_j9_extended.functional_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_cm_Nightly/)
[Test_openjdk8_j9_sanity.system_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_cm_Nightly/)
[Test_openjdk8_j9_extended.system_x86-64_linux_cm_Nightly](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_cm_Nightly/)
[Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_OMR](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_OMR/)

I'll open a follow up issue to have a feature whereby we can specify test levels to include/exclude in the defaults.yml
