### ISSUE TITLE
Remove CONCURRENT_SCAVENGER_ACTIVE VM Thread flag

### ISSUE THREAD

**Issue by amicic** [eclipse/openj9#5458]
All code relying on J9_PRIVATE_FLAGS_CONCURRENT_SCAVENGER_ACTIVE flag if CS cycle is active could rely on  readBarrierRangeCheckBase/Top fields.

First step is to remove users (a couple of spots in JIT code), and then GC code that controls the flag would be cleaned up.

**Comment by fjeremic** [comment]
@NigelYiboYu can you please handle this as part of your open PRs?

**Comment by fjeremic** [comment]
@NigelYiboYu can you please handle this as part of your open PRs?

**Comment by fjeremic** [comment]
@NigelYiboYu can you please handle this as part of your open PRs?

**Comment by amicic** [comment]
I'll likely need a flag soon, and all are taken. Could this be completed - should be relatively easy?

**Comment by amicic** [comment]
https://github.com/eclipse/openj9/blob/master/runtime/compiler/env/VMJ9.cpp#L1911
