### ISSUE TITLE
Jenkins: Feature Request: Add ability to include/exclude test suites per spec

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#5459]
Add an option to include and or exclude running entire test suites per spec in the defaults.yml variable file.

Ex usage: The CMake builds do not currently support testing so we've had to temporarily create empty "hello world" test jobs so the pipeline call doesn't fail.
Ref #5447

**Comment by samuel-rubin** [comment]
I'll go and make a change to the variable file to exclude the tests from running. The only way for the test to run after the change will be if someone would change the variable file that is being used.
