### ISSUE TITLE
JDWP tests are hanging on OpenJ9-JDK8

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#547]
Currently, when we run the vm.jdwp test, it runs for over 7 hours and gets killed by our automation.

Though this degree of overrun strongly implies a hang somewhere (an infinite loop of some sort, perhaps), the javacores imply that it's not a hang, just veryveryveryvery slow progress. 

If I'm reading the javacores correctly, main thread appears to launch a DefaultTestRunner thread, which runs a thread starting at ProcessCommand$StreamCopier.waitUntilDone, to launch a ProcessCommand$StreamCopier.run thread. These seem to be reading data from files via FileInputStream.readBytes, and taking upwards of 2 mins per file. 

At the end of our most recent run (where the timeout was capped at 3 hours), we seem to be at StreamCopier 37.

Other Javas:

OpenJDK9 on OpenJ9 passes in under 5 minutes.
OpenJDK8 on Hotspot passes in under 5 minutes.
IBM Java 8 passes in under 5 minutes.

**Comment by DanHeidinga** [comment]
@pdbain-ibm Can you take a look at this?

**Comment by pdbain-ibm** [comment]
Will do

**Comment by pdbain-ibm** [comment]
@adamfarley would you please provide instructions on running the test manually?
Thanks

**Comment by adamfarley** [comment]
Sure thing. The easiest way in the long run is probably to go here and follow the quick start guide, followed by the guide inside openjdk.test.jck.

https://github.com/AdoptOpenJDK/openjdk-systemtest

In the short run, if you just want a straight-forward set of steps, here:

1) Get a built copy of jck8b (the java 8 jck tests).

1) export JAVA_HOME=<java_home>
export JCK_HOME=<jck8b_home>

2) Run these commands:
```
$JAVA_HOME/bin/java -Djavatest.security.allowPropertiesAccess=true -Djava.security.policy=$JCK_HOME/JCK-runtime-8b/lib/jck.policy -classpath $JCK_HOME/JCK-runtime-8b/lib/jtlite.jar:$JCK_HOME/JCK-runtime-8b/classes com.sun.javatest.agent.AgentMain -passive &

$JAVA_HOME/bin/rmiregistry &

$JAVA_HOME/bin/rmid -J-Dsun.rmi.activation.execPolicy=none -J-Djava.security.policy=$JCK_HOME/JCK-runtime-8b/lib/jck.policy &

$JAVA_HOME/bin/tnameserv -ORBInitialPort 9876 &
```
3) Edit the text below to replace everything inside chevrons, and save it on your test machine as  jtb_file.jtb
```
testsuite "<jck8b_home>/JCK-runtime-8b";
workDirectory -create -overwrite <a directory for the test to work in>;
tests vm/jdwp;
concurrency 1;
timeoutfactor 1;
keywords !interactive;
set jck.env.testPlatform.os "Current system";
set jck.env.runtime.testExecute.cmdAsFile "<java home>/bin/java";
set jck.env.runtime.testExecute.libPathEnv LD_LIBRARY_PATH;
set jck.env.runtime.testExecute.nativeLibPathFileValue "<jck8b_home>/natives/linux_ppcle-64";
set jck.env.runtime.remoteAgent.passiveHost localhost;
set jck.env.runtime.remoteAgent.passivePortDefault Yes;
set jck.env.runtime.testExecute.otherOpts "    -Xdump:system:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -Xdump:snap:none -Xdump:snap:events=gpf+abort+traceassert+corruptcache -Xdump:java:none -Xdump:java:events=gpf+abort+traceassert+corruptcache -Xdump:heap:none -Xdump:heap:events=gpf+abort+traceassert+corruptcache ";
set jck.excludeList.customFiles "<jck8b_home>/excludes/jck8b.jtx <jck8b_home>/excludes/jck8b.kfl";
runTests;
writeReport <a directory to put reports in>;
```
Note: you may need to replace the linux_ppcle-64 bit if you're not using that.
Also Note: You *need* to modify the "java home" bit in this file when running on different javas. Simply changing the java used to run stage 5 is not enough.

4) Copy this file to your computer: https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.jck/config/jck8b/runtime.jti

5) Edit and run this command:

$JAVA_HOME/bin/java -jar <jck8b_home>/JCK-runtime-8b/lib/jtlite.jar -config <runtime.jti location>/runtime.jti @<jtb_file location>/jtb_file.jtb

**Comment by pdbain-ibm** [comment]
Tested and passing with Linux-X86.
$ cat jdwp_run 
export JCK_HOME=/bluebird/javatest/lib/jck/jck8b
export TESTDIR=/team/pdbain/projects/jck
$JAVA_HOME/bin/java -jar $JCK_HOME/JCK-runtime-8b/lib/jtlite.jar -config $TESTDIR/runtime.jti @$TESTDIR/jtb_file.jtb

$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171108_369621 (JIT enabled, AOT enabled)
OpenJ9   - 124092b
OMR      - e1404d5
OpenJDK  - ae4d07b based on jdk-9+181)

$ bash jdwp_run 
Nov 16, 2017, 2:39:26 PM Harness starting test run with configuration "jck_runtime"...
Nov 16, 2017, 2:42:30 PM Finished executing all tests, wait for cleanup...
Nov 16, 2017, 2:42:30 PM Harness done with cleanup from test run.
Total time = 183s
Setup time = 0s
Cleanup time = 0s
Test results: passed: 141
Results written to /team/pdbain/projects/jck/results.
Report written to /team/pdbain/projects/jck/report

**Comment by adamfarley** [comment]
I've already mentioned this to Peter, but I should be clear here that this issue is specific to OpenJDK8 on OpenJ9. OpenJDK9 on OpenJ9 should pass fine, and so should OpenJDK8 on Hotspot.

**Comment by pdbain-ibm** [comment]
Tested with OpenJ9 Java 8 running com.sun.javatest.agent.AgentMain, plus rmid, rmiregistry;kill 9516 and tnameserv, and running the test with OpenJ9 Java 8 and Java 9, test hangs.

Tested with OpenJ9 Java 9 running com.sun.javatest.agent.AgentMain, plus rmid, rmiregistry; and tnameserv, and running the test with OpenJ9 Java 8, test passes.

**Comment by pdbain-ibm** [comment]
Copied libjdwp.so and libjdwp.diz from OpenJ9 Java 9 to OpenJ9 Java 8 and ran the test using the modified Java 8 throughout.  It hung.

**Comment by pdbain-ibm** [comment]
Swapped libjdwp.so from an IBM java 8 into the OpenJ9 Java 8.  No errors, still hangs.

**Comment by pshipton** [comment]
#714 has been merged, please check if this problem still occurs.

**Comment by pdbain-ibm** [comment]
Looks good.  It still hangs (likely a separate issue), but runs ~20 tests fairly readily.

**Comment by pdbain-ibm** [comment]
Tested with:
java version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2017_11_30_09_08-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171130_371963 (JIT enabled, AOT enabled)
OpenJ9   - fb423d1
OMR      - 380ed91)

**Comment by adamfarley** [comment]
Sure. Running now.

**Comment by adamfarley** [comment]
It completes and most of the tests pass, though we have a single failure. Since this isn't a hang or a significant overrun, I'll raise a separate issue.

Thanks Peter. :)

**Comment by adamfarley** [comment]
The single test failure was a timeout in the ClearAllBreakpoints (number 1) subtest, however this passes the second time I ran the jdwp tests. Another issue will not be raised.
