### ISSUE TITLE
cent6-x64-1 and 7 Error fetching remote repo error: index-pack died of signal 15

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5472]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_Nightly/3/console
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/3/console
```
Receiving objects:  28% (1593/5628), 45.18 MiB | 65.00 KiB/s   
error: index-pack died of signal 15
fatal: index-pack failed
```

Suspect a machine issue, disabling cent6-x64-1

**Comment by pshipton** [comment]
@jdekonin @vsebe

**Comment by pshipton** [comment]
Many more of these occurred last night as well, checked a number and they all occurred on cent6-x64-1

**Comment by vsebe** [comment]
```
Cloning into './openjdk-tests'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
Receiving objects:  28% (1591/5628), 43.25 MiB | 73.00 KiB/s
```
Rebooted and cleaned up jenkin's workspace:

```
Cloning into 'openjdk-tests'...
...
Receiving objects: 100% (5628/5628), 53.02 MiB | 1.67 MiB/s, done.
Resolving deltas: 100% (3213/3213), done.
```
Grinder: https://ci.eclipse.org/openj9/view/Test_grinder/job/Test-Grinder/392/

**Comment by vsebe** [comment]
Enabled machine.

**Comment by AdamBrousseau** [comment]
related #5630 
Still having issues cloning on this slave

**Comment by jdekonin** [comment]
Leave it disabled or delete.  Its easier to to recreate than troubleshoot what might be wrong with the setup.

**Comment by pshipton** [comment]
cent6-x64-7 developed the same problem and was also disabled.

**Comment by daneshforouhari** [comment]
Hello. I am  running into the same problem, i.e. git index-pack dying (via signal 15). This happens at random when running 'git clone ...' on the same repo (without repo's content getting any bigger).
Any idea what could be causing this behavior. BTW, we are using Ubuntu 18.04 (not CentOS).
Thanks

**Comment by pshipton** [comment]
@AdamBrousseau do you know why the `index-pack died of signal 15` occurs?

**Comment by AdamBrousseau** [comment]
I don't think we ever found root cause as it wasn't easy to reproduce. Could be a number of things. Try adding `GIT_TRACE=1` to your env to get more verbose output. Not sure what your setup is like but we also use [reference repositories](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---reference-if-ableltrepositorygt) to help with our clones.
