### ISSUE TITLE
Suggestion: A mechanism for interacting with the JIT from Java code

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#549]
It would be useful from a testing perspective to be able to influence the JIT compiler from Java code, for example to force a given method to be JIT compiled at a given optimisation level. Without wishing to imply too much about what such a mechanism would look like, the sort of capability I'm envisioning would allow tests such as

```
final class PseudoTest
{
   public static final void main(String[] args)
   {
   	String optlevels[] = {"cold","warm","scorching"};

   	// This invocation guaranteed to run in the interpreter (mechanism TBD)
   	int resI = someMethod();

   	for(String opt : optlevels) {
   		com.ibm.Compiler.compile(someMethod, opt); // made up api, actual form TBD

   		// this invocation to run in jit compiled code at the optlevel specified above
   		int resJit = someMethod();

   		if (resJit!=resI) System.out.println("Test failed at optlevel "+opt);
   	}
   }

   static int someMethod()
   {
   	// do interesting things that are hard to compile
   }
}
```

@mgaudet raised the possibility of using annotations to control the compiler, and I have wondered if it might be possible to return a method handle from the .compile method, where the method handle provides the only mechanism to invoke the newly generated code (avoiding issues around recompilation between compilation and invocation).
To be useful it is not necessary for the compilation to always succeed, but it must be possible to tell if the compilation was successful or not.
Once a basic mechanism is in place it is likely that we could rapidly come up with usage scenarios for extending the functionality, perhaps by being able to over-ride Xjit: options at each compile, or adding APIs for querying the compiler state.

**Comment by mstoodle** [comment]
I would like to see some scenarios fleshed out for what this kind of facility would be used for, to make sure that what gets implemented actually addresses those scenarios. Given how adaptive the JIT compiler is to prevailing circumstances, It would be very easy to implement such an API that does something but not the something everyone will assume it's doing.

If we're clear on the goals we want to accomplish, that will make it easier to bring implementation and expectations in line.

**Comment by DanHeidinga** [comment]
Archiving this issue as there hasn't been any recent discussions here
