### ISSUE TITLE
ub16-390-1 and ub16-390-3 need a reboot

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5499]
https://ci.eclipse.org/openj9/computer/ub16-390-1
https://ci.eclipse.org/openj9/computer/ub16-390-3
`This node is being launched.`

They didn't come back from one from one of the jenkins restarts.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
Machines are reconnected.  Neither one rebooted, so it looks like just a failure to launch the slave process.
