### ISSUE TITLE
Rename runtimes/tr.source

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#550]
I wanted to gauge peoples opinion on renaming runtimes/tr.source to something more sensible. Perhaps follow OMR's footsteps and use runtime/compiler as the directory name instead? Would this have any internal / external dependencies? Last thing I would want to do is to break a bunch of internal builds.

**Comment by DanHeidinga** [comment]
@AdamBrousseau / @jdekonin How deeply is the `tr.source` name backed into the build system?  Does this have an internal dependencies?

**Comment by AdamBrousseau** [comment]
Off the top of our heads

1. Makefiles (which I would assume would be all part of the OpenJ9 PR)
1. jit.version file is hardcoded to get dumped into `openj9/runtime/tr.source/jit.version` when we clone OpenJ9 (internal only)
1. Possible failures in Create Source.zip (internal only)

2,3 would be easy to test/fix

**Comment by jdekonin** [comment]
I agree with Adam, references within *.mk and *.xml files should be the only change required aside from the directory change.

I believe that the entries in buildspecs/* are obsolete.  There might be an internal build issue, but that shouldn't block doing this work.

**Comment by 0xdaryl** [comment]
To be more symmetric with OMR would require a little more reworking on the path names.  Namely,
```
runtimes/compiler/<stem path>
```
However, there are occasions when using extensible classes when the "project" needs to be referenced in the include directive.  In the above case the project would be `runtimes` which isn't particularly descriptive or unique, but could work.

This then might suggest the following:
```
runtimes/trj9/compiler/<stem path>
```
where `trj9` represents the project.  This would look better in the include directives, but is somewhat redundant in that "trj9" can only be a "compiler".  I'd be willing to live with that slight inconsistency.

**Comment by fjeremic** [comment]
> where `trj9` represents the project. This would look better in the include directives, but is somewhat redundant in that "trj9" can only ever be a "compiler". I'd be willing to live with that slight inconsistency though.

Thanks @0xdaryl. I hand't thought of this. My first step was to rename tr.source and as a next step I thought it would make sense to fold the trj9 directory as well as it currently serves exactly no purpose.

**Comment by 0xdaryl** [comment]
What I proposed might cause more things to break though without changes to OMR itself.  Right now in OMR it looks like `compiler` is used as the project in some cases.  For example:
```
#include "compiler/x/codegen/OMRCodeGenerator.hpp"
```
This would now find a version in trj9 (if you followed my second naming scheme above) rather than what was intended (a version in OMR).  I believe cases like this would need to be prefixed with 'omr/compiler/x/codegen/OMRCodeGenerator.hpp'.  Ugh.

I seem to recall there was a good reason why we didn't do it that way, but it escapes me right now.  Thinking...

I do like the idea of symmetry between the projects.
