### ISSUE TITLE
Rip out grpc code from codebase

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5512]
Raw sockets are significantly faster and cheaper than the grpc solution. The only downside of raw sockets was the absence of encryption, but currently we have that covered as well. Thus, it's better to remove this code and the dependency it creates.

**Comment by dmitry-ten** [comment]
I'll work on this, if no one else is already doing it.

**Comment by mpirvu** [comment]
Thanks. No one is yet working on it.
