### ISSUE TITLE
OpenJ9 attach from SSH session fails on Windows

### ISSUE THREAD

**Issue by AntonKatilin** [eclipse/openj9#5533]
A Windows 10 machine is running an OpenJ9 JVM process started under a regular user.

OpenSSH server is running on the machine:
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

We connect to the machine via ssh, under the same user as of the said JVM process. The Windows session is different: for ssh the session ID is 0 ("services"), the target JVM process session ID is 3 ("console").

The problem: attach to the JVM does not work from within the ssh session, because communication between the attacher and the process fails for some reason, presumably the process does not receive the notification. According to the attach logs, attach activity is performed in the proper .com_ibm_tools_attach directory.

**Comment by AntonKatilin** [comment]
The problem was initially reported as https://openj9.slack.com/messages/C8312LCV9/
The attach log files can be found there.

**Comment by pdbain-ibm** [comment]
Thanks Anton.  I will investigate.

**Comment by pdbain-ibm** [comment]
Connection between JVMs launched from SSH tested and working.  JVMs launched from SSH can see JVMs launched from the console and vice-versa, but cannot attach.  The working hypothesis is that the SSH and console JVMs are using different semaphores.

I dumped the handle information using sysinternals `handle63.exe -p <id> -a` for JVMs launched from SSH and the console:

3464 (SSH):
  5E0: Semaphore     \BaseNamedObjects\CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore              
  5E4: Semaphore     \BaseNamedObjects\CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore_set0         

7620:
  594: Semaphore     \Sessions\2\BaseNamedObjects\CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore         
  598: Semaphore     \Sessions\2\BaseNamedObjects\CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore_set0    

Note that they are using different file path roots: `\Sessions\2\BaseNamedObjects` vs. `\BaseNamedObjects` even though they are based on the same file path.

FYI @pshipton: Could this affect the semaphores used by shared classes?

**Comment by pshipton** [comment]
By default, shared classes doesn't use a semaphore, it uses omrfile_blockingasync_lock_bytes(). Only if a -Xshareclassese:nonpersistent cache is created would it use a semaphore.

**Comment by pdbain-ibm** [comment]
I grabbed the tracepoints from a console  and SSH JVM respectively:
Console:

>  j9prt.260           Event       j9shsem_open translated semaphore mutex name = CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore
 j9prt.62            Debug       j9shsem_open: baseFile=CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore
 j9prt.261           Event       j9shsem_open WaitForSingleObject for global mutex successful, rc = 0, windows last error = 0
 j9prt.63            Event       j9shsem_open sempahore file CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore exists, opening
 j9prt.670           Entry      >j9shsem:openSemaphore Entered, rootname = CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore
 j9prt.671           Event       j9shsem:openSemaphore opening set semaphore 0, name = CUsersADMINI1AppDataLocalTempcom_ibm_tools_attach__notifier_semaphore_set0
 j9prt.673           Exit       <j9shsem:openSemaphore successfully opened semaphores, exiting
 j9prt.68            Exit       <j9shsem_open returns success, rc=101, handle=0x18387d88e50

SSH:

>  j9prt.260           Event       j9shsem_open translated semaphore mutex name = CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore
 j9prt.62            Debug       j9shsem_open: baseFile=CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore
 j9prt.261           Event       j9shsem_open WaitForSingleObject for global mutex successful, rc = 0, windows last error = 0
 j9prt.64            Event       j9shsem_open semaphore file CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore does not exist, creating
 j9prt.665           Entry      >j9shsem:createSemaphore Entered, rootname = CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore
 j9prt.666           Event       j9shsem:createSemaphore created main semaphore, will now create set semaphores
 j9prt.667           Event       j9shsem:createSemaphore creating set semaphore 0, name = CUsersAdministratorAppDataLocalTempcom_ibm_tools_attach__notifier_semaphore_set0
 j9prt.669           Exit       <j9shsem:createSemaphore successfully created semaphores, exiting
 j9prt.68            Exit       <j9shsem_open returns success, rc=100, handle=0x2788b73f490

Note that they also have different IDs for the temp file path: console uses `CUsersADMINI1` while SSH uses `CUsersAdministrator`.

**Comment by pdbain-ibm** [comment]
The `TEMP` and `TMP` environment variables differ depending on whether I log on via SSH (in which case I get `Administrator`) or console (`ADMIN` respectively).  Resetting the TMP and TEMP for the console session doesn't fix the problem: we still get `\Sessions\2` with the console JVM.

**Comment by pdbain-ibm** [comment]
I am experimenting with setting the namespace directly.  See https://docs.microsoft.com/en-ca/windows/desktop/api/synchapi/nf-synchapi-createsemaphoreexw.

**Comment by pdbain-ibm** [comment]
Prepending `Global\` to the semaphore IDs causes SSH and console JVMs to use the same semaphore namespace.  SSH JVMs cannot attach to console JVMs, but console JVMs cannot initiate an attachment: it appears they cannot post to the semaphore.

**Comment by pdbain-ibm** [comment]
Did some more digging:
1. Windows treats the handles from different login sessions as separate namespaces and doesn't allow then to be shared.
2. OpenJDK with HotSpot does not allow Attach API attachment s between JVMs running in different sessions, e.g. console and SSH.
3.  OpenJDK's `jps` displays "process information unavailable" for foreign processes.

As OpenJ9's behaviour is consistent with OpenJDK's, could we close this? I will add a clarification to our online documentation.

**Comment by AntonKatilin** [comment]
I don't agree that OpenJ9 behavior matches HotSpot behavior: in fact, we successfully attach the agent from "services" session to a HotSpot JVM running in user session. That was the reason why we filed this request: we found that OpenJ9 missed a capability available with HotSpot.

> 3. OpenJDK's jps displays "process information unavailable" for foreign processes.
Yes. Interestingly, jstack and jmap seem to work just fine. Our attacher also works.

Nevertheless, if OpenJ9 attach mechanism is fundamentally unable to work cross Windows session, please close this. In this case, we would appreciate if you could share a direct link to the [about to be written] documentation describing this limitation.

**Comment by pdbain-ibm** [comment]
Anton
Thanks for the update.  Curiously, the HotSpot AttachProvider.listVirtualMachines() API running on SSH does not see the console JVM at all, and `jps` reports "information unavailable", but actual attachments work fine.  I will continue the investigation...

**Comment by pdbain-ibm** [comment]
Prepending `Global\` to the semaphore name allows attachment between sessions.
Working on a proper fix.

**Comment by pdbain-ibm** [comment]
@AntonKatilin
I have a prototype JDK which should help.  You can download it at https://ibm.box.com/s/wbxgee1a3g85j69kbzyeo4astwukv0bs

This can attach to legacy VMs if they are running in the same session. VMs running the above JDK can attach across sessions (but only to the same user). The attacher and target must have the same values for %TEMP% and %TMP%.

Could you test it and let me know the results?

Thank you
    -p

**Comment by AntonKatilin** [comment]
> I have a prototype JDK which should help. You can download it at https://ibm.box.com/s/wbxgee1a3g85j69kbzyeo4astwukv0bs

Unfortunately I have troubles with the download. I'm not part of IBM, so the only option for me to login is to use a google account.  For my address I get "Your Google account is not linked to a Box account..." On attempt to create a free Box Business trial account I am asked to provide credit card or bank account detail.
Is there a way to download the test JVM via a publicly available link?

**Comment by pdbain-ibm** [comment]
@AntonKatilin Sorry about that.  Please try https://drive.google.com/file/d/1UbT6BPkUBIkljLDWclv7a22_9rM2AugJ/view?usp=sharing

**Comment by AntonKatilin** [comment]
I confirm the prototype JDK solves the problem. Thank you very much for the fix.

The fix currently targets "Release 0.15 (Java 8, 11, 12) July refresh". Just curious, do you have any plans to backport it e.g. to 14.0.2? A backport is not critical for us at all, I just wanted to know.

**Comment by pshipton** [comment]
Unfortunately this fix missed the 0.14.2 release, which has been finalized and is building (for jdk8) at AdoptOpenJDK now.

**Comment by pshipton** [comment]
Although there are no plans, if for some reason there is another 0.14.x release, this fix would be considered.

**Comment by pdbain-ibm** [comment]
@AntonKatilin This change is now live and should be available on  AdoptOpenJDK.
FYI, we have seen an issue where a product was failing because it contained an older copy of `tools.jar`; if you have private copies of tools.jar, please ensure they match the JVM as some of the internal interfaces have changed.
Please contact me if you have any questions.

**Comment by raphw** [comment]
@pdbain-ibm Hey Peter, I just reimplemented the attach API of OpenJ9 for a library when no JDK is available. In the process, I realized that by adding the global namespace, it is no longer possible to attach to a JVM of an older version. That is really unfortunate since the attach API was always backwards compatible.

Was this breakage an oversight or is this an implicit behavior?

**Comment by pdbain-ibm** [comment]
@raphw The API should be backward compatible.  Note that there is a property the the target's advertisement file to indicate if it is using the local or global semaphore.  The attacher consults this property to determine if it should use the local or global semaphore.  I can point you at  the code if you want to update your implementation.

**Comment by raphw** [comment]
You are right, I missed this. This is where the advertisement file is queried: https://github.com/eclipse/openj9/blob/8c21754c14de8020281b01cb4ee7e7a0bd57a09e/jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Advertisement.java#L281
