### ISSUE TITLE
jtreg: java/nio/channels/Selector/LotsOfChannels.java fails on jdk8 / s390x

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#5542]
Failure link: https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_s390x_linux/270/

------------

To reproduce via Grinder:

BUILD_LIST=openjdk_regression
TARGET=jdk_custom
CUSTOM_TARGET=java/nio/channels/Selector/LotsOfChannels.java
Jenkinsfile=openjdk_s390x_linux
SDK_RESOURCE=nightly
JDK_VERSION=8
JDK_IMPL=openj9

Appears to be regression, passing on April 6th, **consistently** failing on April 10th and onward:

Pass (Apr 6th)
java -version
20:47:56  openjdk version "1.8.0_212"
20:47:56  OpenJDK Runtime Environment (build 1.8.0_212-201904060333-b01)
20:47:56  Eclipse OpenJ9 VM (build master-69c95fe61, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20190405_279 (JIT enabled, AOT enabled)
20:47:56  OpenJ9   - 69c95fe61
20:47:56  OMR      - a595091d
20:47:56  JCL      - 2b68f66d68 based on )

First Failure seen (Apr 10th)
java -version
07:18:19  openjdk version "1.8.0_212"
07:18:19  OpenJDK Runtime Environment (build 1.8.0_212-201904101300-b01)
07:18:19  Eclipse OpenJ9 VM (build v0.14.0-release-581f9de22, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20190410_284 (JIT enabled, AOT enabled)
07:18:19  OpenJ9   - 581f9de22
07:18:19  OMR      - 4a4278e6
07:18:19  JCL      - fe984ddb37 based on )

Changes between SHAs:
https://github.com/eclipse/openj9/compare/69c95fe...581f9de

Failure output
--------------
16:45:30  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 1 timed out with a timeout of 960 seconds; check console log for any additional details
16:45:30  REASON: User specified action: run main LotsOfChannels 
16:45:30  TIME:   961.585 seconds
16:45:30  messages:
16:45:30  command: main LotsOfChannels
16:45:30  reason: User specified action: run main LotsOfChannels 
16:45:30  Mode: agentvm
16:45:30  Agent id: 1
16:45:30  Timeout refired 960 times
16:45:30  Timeout information:
16:45:30  Running jstack on process 8713
16:45:30  2019-04-17T10:45:23.269
16:45:30  Virtual machine: 8713 JVM information JRE 1.8.0 Linux s390x-64-Bit Compressed References 20190417_289 (JIT enabled, AOT enabled)
16:45:30  OpenJ9   - bad1d4d06
16:45:30  OMR      - 4a4278e6
16:45:30  JCL      - 0ade4cc962 based on jdk8u212-b03
16:45:30  "main" Id=1 WAITING
16:45:30  	at java.lang.Object.wait(Native Method)
16:45:30  	at java.lang.Object.wait(Object.java:218)
16:45:30  	at java.lang.Thread.join(Thread.java:693)
16:45:30  	- locked java.lang.Thread@2f7b3281
16:45:30  	at com.sun.javatest.regtest.agent.MainActionHelper.runClass(MainActionHelper.java:184)
16:45:30  	at com.sun.javatest.regtest.agent.AgentServer.doMain(AgentServer.java:257)
16:45:30  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:193)
16:45:30  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:65)
16:45:30  	CPU time: 2877681419 ns
16:45:30  	User time: 2877681419 ns
16:45:30  
16:45:30  "JIT Compilation Thread-0" Id=2 RUNNABLE
16:45:30  	CPU time: 4012188247 ns
16:45:30  	User time: 4012201254 ns
16:45:30  
16:45:30  "JIT Compilation Thread-1 Suspended" Id=3 RUNNABLE
16:45:30  	CPU time: 3098982545 ns
16:45:30  	User time: 3098982545 ns
16:45:30  
16:45:30  "JIT Compilation Thread-2 Suspended" Id=4 RUNNABLE
16:45:30  	CPU time: 2322560471 ns
16:45:30  	User time: 2322560471 ns
16:45:30  
16:45:30  "JIT Compilation Thread-3 Suspended" Id=5 RUNNABLE
16:45:30  	CPU time: 65019 ns
16:45:30  	User time: 65019 ns
16:45:30  
16:45:30  "JIT Compilation Thread-4 Suspended" Id=6 RUNNABLE
16:45:30  	CPU time: 55135 ns
16:45:30  	User time: 55135 ns
16:45:30  
16:45:30  "JIT Compilation Thread-5 Suspended" Id=7 RUNNABLE
16:45:30  	CPU time: 64750 ns
16:45:30  	User time: 64750 ns
16:45:30  
16:45:30  "JIT Compilation Thread-6 Suspended" Id=8 RUNNABLE
16:45:30  	CPU time: 46705 ns
16:45:30  	User time: 46705 ns
16:45:30  
16:45:30  "JIT Diagnostic Compilation Thread-7 Suspended" Id=9 RUNNABLE
16:45:30  	CPU time: 50898 ns
16:45:30  	User time: 50898 ns
16:45:30  
16:45:30  "JIT-SamplerThread" Id=10 TIMED_WAITING
16:45:30  	CPU time: 279499743 ns
16:45:30  	User time: 279499743 ns
16:45:30  
16:45:30  "IProfiler" Id=11 RUNNABLE
16:45:30  	CPU time: 1705316807 ns
16:45:30  	User time: 1705316807 ns
16:45:30  
16:45:30  "Concurrent Mark Helper" Id=12 RUNNABLE
16:45:30  	CPU time: 23849198 ns
16:45:30  	User time: 23849198 ns
16:45:30  
16:45:30  "GC Slave" Id=13 RUNNABLE
16:45:30  	CPU time: 140001678 ns
16:45:30  	User time: 140001678 ns
16:45:30  
16:45:30  "GC Slave" Id=14 RUNNABLE
16:45:30  	CPU time: 170995411 ns
16:45:30  	User time: 170995411 ns
16:45:30  
16:45:30  "GC Slave" Id=15 RUNNABLE
16:45:30  	CPU time: 157858318 ns
16:45:30  	User time: 157858318 ns
16:45:30  
16:45:30  "Attach API wait loop" Id=18 RUNNABLE
16:45:30  	at com.ibm.tools.attach.target.IPC.waitSemaphore(Native Method)
16:45:30  	at com.ibm.tools.attach.target.CommonDirectory.waitSemaphore(CommonDirectory.java:254)
16:45:30  	at com.ibm.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:66)
16:45:30  	at com.ibm.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
16:45:30  	CPU time: 15759000 ns
16:45:30  	User time: 15759000 ns
16:45:30  
16:45:30  "pool-1-thread-1" Id=19 TIMED_WAITING
16:45:30  	at sun.misc.Unsafe.park(Native Method)
16:45:30  	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
16:45:30  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
16:45:30  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
16:45:30  	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	CPU time: 11336319 ns
16:45:30  	User time: 11336319 ns
16:45:30  
16:45:30  "Finalizer thread" Id=20 RUNNABLE
16:45:30  	CPU time: 31195813 ns
16:45:30  	User time: 31195813 ns
16:45:30  
16:45:30  "InnocuousThread-1" Id=22 WAITING
16:45:30  	at sun.misc.Unsafe.park(Native Method)
16:45:30  	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
16:45:30  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
16:45:30  	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
16:45:30  	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:262)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	at sun.misc.InnocuousThread.run(InnocuousThread.java:106)
16:45:30  	CPU time: 53104691 ns
16:45:30  	User time: 53104691 ns
16:45:30  
16:45:30  "InnocuousThread-2" Id=23 WAITING
16:45:30  	at sun.misc.Unsafe.park(Native Method)
16:45:30  	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
16:45:30  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
16:45:30  	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
16:45:30  	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:262)
16:45:30  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	at sun.misc.InnocuousThread.run(InnocuousThread.java:106)
16:45:30  	CPU time: 11569883 ns
16:45:30  	User time: 11569883 ns
16:45:30  
16:45:30  "InnocuousThread-3" Id=24 RUNNABLE
16:45:30  	at sun.nio.ch.EPoll.epollWait(Native Method)
16:45:30  	at sun.nio.ch.EPollPort$EventHandlerTask.poll(EPollPort.java:194)
16:45:30  	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:268)
16:45:30  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	at sun.misc.InnocuousThread.run(InnocuousThread.java:106)
16:45:30  	CPU time: 12693482 ns
16:45:30  	User time: 12693482 ns
16:45:30  
16:45:30  "InnocuousThread-4" Id=25 WAITING
16:45:30  	at sun.misc.Unsafe.park(Native Method)
16:45:30  	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
16:45:30  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
16:45:30  	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
16:45:30  	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:262)
16:45:30  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	at sun.misc.InnocuousThread.run(InnocuousThread.java:106)
16:45:30  	CPU time: 12624732 ns
16:45:30  	User time: 12624732 ns
16:45:30  
16:45:30  "InnocuousThread-5" Id=26 WAITING
16:45:30  	at sun.misc.Unsafe.park(Native Method)
16:45:30  	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
16:45:30  	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
16:45:30  	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
16:45:30  	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:262)
16:45:30  	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:45:30  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	at sun.misc.InnocuousThread.run(InnocuousThread.java:106)
16:45:30  	CPU time: 7721603 ns
16:45:30  	User time: 7721603 ns
16:45:30  
16:45:30  "AgentVMThread" Id=916 RUNNABLE
16:45:30  	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
16:45:30  	- locked java.lang.Object@5fd6f0c
16:45:30  	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
16:45:30  	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
16:45:30  	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
16:45:30  	at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:167)
16:45:30  	at LotsOfChannels.main(LotsOfChannels.java:63)
16:45:30  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:45:30  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:45:30  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:45:30  	at java.lang.reflect.Method.invoke(Method.java:498)
16:45:30  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
16:45:30  	at java.lang.Thread.run(Thread.java:813)
16:45:30  	CPU time: 4082576 ns
16:45:30  	User time: 4082576 ns
16:45:30  
16:45:30  "Attachment 39665" Id=917 RUNNABLE
16:45:30  	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
16:45:30  	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:643)
16:45:30  	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:626)
16:45:30  	at openj9.tools.attach.diagnostics.info.ThreadGroupInfo.getThreadInfoProperties(ThreadGroupInfo.java:107)
16:45:30  	at openj9.tools.attach.diagnostics.target.TargetDiagnosticsProviderImpl.getThreadGroupInfo(TargetDiagnosticsProviderImpl.java:41)
16:45:30  	at com.ibm.tools.attach.target.Attachment.doCommand(Attachment.java:195)
16:45:30  	at com.ibm.tools.attach.target.Attachment.run(Attachment.java:147)
16:45:30  	CPU time: 34110004 ns
16:45:30  	User time: 34119843 ns
16:45:30  
16:45:30  "file lock watchdog" Id=918 TIMED_WAITING
16:45:30  	at java.lang.Object.wait(Native Method)
16:45:30  	at java.lang.Object.wait(Object.java:218)
16:45:30  	at java.util.TimerThread.mainLoop(Timer.java:552)
16:45:30  	- locked java.util.TaskQueue@679f7bf3
16:45:30  	at java.util.TimerThread.run(Timer.java:505)
16:45:30  	CPU time: 46187 ns
16:45:30  	User time: 46187 ns
16:45:30  
16:45:30  
16:45:30  --- Timeout information end.
16:45:30  elapsed time (seconds): 961.585
16:45:30  configuration:
16:45:30  Boot Layer
16:45:30    class path: /data/jenkins/workspace/openjdk8_j9_openjdktest_s390x_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar
16:45:30                /data/jenkins/workspace/openjdk8_j9_openjdktest_s390x_linux/jvmtest/openjdk_regression/jtreg/lib/javatest.jar
16:45:30                /data/jenkins/workspace/openjdk8_j9_openjdktest_s390x_linux/jvmtest/openjdk_regression/jtreg/lib/jtreg.jar
16:45:30  

Also see attached jtr file for output details
[LotsOfChannels.jtr.txt](https://github.com/eclipse/openj9/files/3090733/LotsOfChannels.jtr.txt)

**Comment by pshipton** [comment]
@smlambert note the test has been failing since jstack was delivered. "Implement jstack" is one of the changes between the two SHAs 69c95fe...581f9de 

@pdbain-ibm

**Comment by pdbain-ibm** [comment]
... and someone is apparently using `jstack`, since the target portion thereof is running:

> "Attachment 39665" Id=917 RUNNABLE
> 	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
> 	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:643)
> 	at com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:626)
> 	at openj9.tools.attach.diagnostics.info.ThreadGroupInfo.getThreadInfoProperties(ThreadGroupInfo.java:107)
> 	at openj9.tools.attach.diagnostics.target.TargetDiagnosticsProviderImpl.getThreadGroupInfo(TargetDiagnosticsProviderImpl.java:41)
> 	at com.ibm.tools.attach.target.Attachment.doCommand(Attachment.java:195)
> 	at com.ibm.tools.attach.target.Attachment.run(Attachment.java:147)

**Comment by pdbain-ibm** [comment]
The same test passes on Linux x86: https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_linux/515/tapTestReport/

Possibly `dumpAllThreadsImpl` is deadlocking.

**Comment by pdbain-ibm** [comment]
I will investigate.

**Comment by pdbain-ibm** [comment]
I ran this on another Linux 390 system with Java 11:

> $ java -version
> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+2-201904131220)
> Eclipse OpenJ9 VM AdoptOpenJDK (build master-9da13cbf0, JRE 11 Linux s390x-64-Bit Compressed References 20190413_217 (JIT enabled, AOT enabled)
> OpenJ9   - 9da13cbf0
> OMR      - f4de44cc
> JCL      - 5c13382d6b based on jdk-11.0.3+2)
> 

and Java 8:

> $ java -version
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment (build 1.8.0_212-201904131246-b01)
> Eclipse OpenJ9 VM (build master-9da13cbf0, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20190413_288 (JIT enabled, AOT enabled)
> OpenJ9   - 9da13cbf0
> OMR      - f4de44cc
> JCL      - c113451d based on jdk8u212-b01)
> 

and it passed fine: 
`java/nio/channels/Selector/LotsOfChannels.java                                                                     Passed. Execution successful`

This appears to be a machine issue.

For the record, the system limits on my test machine are:

> $ ulimit -a
> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> scheduling priority             (-e) 0
> file size               (blocks, -f) unlimited
> pending signals                 (-i) 31379
> max locked memory       (kbytes, -l) 64
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 1024
> pipe size            (512 bytes, -p) 8
> POSIX message queues     (bytes, -q) 819200
> real-time priority              (-r) 0
> stack size              (kbytes, -s) 8192
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 31379
> virtual memory          (kbytes, -v) unlimited
> file locks                      (-x) unlimited
>

**Comment by pdbain-ibm** [comment]
Could you please re-test with JVM option `-Dcom.ibm.tools.attach.enable=no`? That should take `jstack` out of the equation (sort of).  Note that Attach API uses a number of file channels during initialization and during the connection process, though not while _waiting_ for a connection.

**Comment by smlambert** [comment]
Hmm, I thought I updated this issue already (so perhaps I have mistakenly updated the wrong one).

Here is the update:
Rerunning with that JVM option makes no difference to the result on test-marist-sles12-s390x-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1561/rebuild/parameterized (still failing).

The test does pass on other machines, like build-marist-s390x-sles-12 (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1558/).

ulimit info for test-marist-sles12-s390x-1, difference in open files setting:
00:00:07  ulimit: core file size          (blocks, -c) 0
00:00:07  data seg size           (kbytes, -d) unlimited
00:00:07  scheduling priority             (-e) 0
00:00:07  file size               (blocks, -f) unlimited
00:00:07  pending signals                 (-i) 31287
00:00:07  max locked memory       (kbytes, -l) 64
00:00:07  max memory size         (kbytes, -m) unlimited
00:00:07  open files                      (-n) 1048576
00:00:07  pipe size            (512 bytes, -p) 8
00:00:07  POSIX message queues     (bytes, -q) 819200
00:00:07  real-time priority              (-r) 0
00:00:07  stack size              (kbytes, -s) 8192
00:00:07  cpu time               (seconds, -t) unlimited
00:00:07  max user processes              (-u) 31287
00:00:07  virtual memory          (kbytes, -v) unlimited
00:00:07  file locks                      (-x) unlimited

where as on build-marist-s390x-sles-12   
open files                      (-n) 4096

**Comment by sophia-guo** [comment]
The test consistently failed on Adopt https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_s390x_linux/336/. Test machine is [test-marist-ubuntu1604-s390x-1](https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-1/).

The system limit is same as https://github.com/eclipse/openj9/issues/5542#issuecomment-484538794

```
Last login: Wed Jul  3 15:15:07 2019 from 32.97.110.56
jenkins@test-marist-ubuntu1604-s390x-1:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31287
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 31287
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
jenkins@test-marist-ubuntu1604-s390x-1:~$ 
```

**Comment by sophia-guo** [comment]
Test also failed with hotspot though with different error msg.

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_s390x_linux/93/consoleFull

Same with jdk11. Test failed with both hotspot and openj9 with not same error message.

**Comment by sophia-guo** [comment]
There is not issue reported in JBS yet.

**Comment by JasonFengJ9** [comment]
Any chance to reproduce this failure at an internal jenkins machine? otherwise we have to request machine access for investigation.

**Comment by sophia-guo** [comment]
Right now there is only one s390 test machine available 'jrxzrt01' and test passed on that machine. All other s390 test machines with ubuntu are offline. Not sure the test status on ubuntu ones.

Looks like the main difference between https://ci.adoptopenjdk.net/computer/test-marist-ubuntu1604-s390x-1/ and 'jrxzrt01' t machine is the OS. Failed on ubuntu and passed on rhel.

**Comment by JasonFengJ9** [comment]
100x grinder passed at `ub16s390xrt1-1` yesterday.

**Comment by JasonFengJ9** [comment]
The failure reported in this issue was `jtreg: java/nio/channels/Selector/LotsOfChannels.java fails on jdk8` on couple of `s390x` machines. 
Launched 3x grinder on each `s390x` machine available at AdoptOpenJDK [1]:
```
build-marist-rhel74-s390x-1 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2072/
build-marist-rhel74-s390x-2 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2073/
build-marist-s390x-zOS-1 -- offline
build-marist-s390x-zOS-2 -- offline
build-marist-ubuntu1604-s390x-2 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2074/
build-marist-ubuntu1604-s390x-3 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2075 (still awaiting for machine)
test-marist-sles12-s390x-1 -- offline
test-marist-ubuntu1604-s390x-1 : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2071/
test-marist-ubuntu1604-s390x-2-XJ : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/2069/
```
There was no failure observed. I think this issue can be closed. It can be re-opened if the problem shows up again.
@smlambert do you concur this assessment?


[1] https://ci.adoptopenjdk.net/label/s390x/

**Comment by smlambert** [comment]
Yes, it is no longer seen or reproducible, perhaps it was a transient machine config issue, closing this.
