### ISSUE TITLE
JDK12.0.1 should be JVM_INTERFACE_VERSION = 5

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#5553]
The jdk-12.0.1+12 GA build pushed to openjdk by Oracle is based off of jdk-12+33, and does not include the change for:
    https://bugs.openjdk.java.net/browse/JDK-8216302
which updated it to 6, but only for releases: 11.0.3, 12.0.2 and 13,
so not 12.0.1
We unfortunately did change:
   https://github.com/eclipse/openj9/pull/5235/files
based on building jdk12 from the latest jdk12u head code. We need to revert this until 12.0.2.

jdk-12.0.1+12 has been pushed to the repo and new branch openj9-0.14.0:
https://github.com/ibmruntimes/openj9-openjdk-jdk12/tree/openj9-0.14.0

**Comment by pshipton** [comment]
@JasonFengJ9 can you make the change in the 0.14 branch please.
