### ISSUE TITLE
x86 operating system coverage for OpenJ9 jenkins

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#5563]
Currently we have : 
- 7 cent6 instances for build/test
- 9 ubuntu16 instances for test (or build for 0.14 and older releases)

In shifting to cent6 for build, the initial plan was to add another 3 cent6 and keep 6 ub16.  But there are other options; cent7, ub18, debian9..

What os coverage would be desired moving forward?

**Comment by pshipton** [comment]
There are very rarely JVM problems related to OSes. The most interesting would be the very latest, i.e. cent8 if/when it exists, ub18, etc.

**Comment by DanHeidinga** [comment]
I'd like the OpenJ9 build farm to optimize for getting the maximum number of PR builds through at the same time.  That suggests we should target more cent6 and worry less about having broad linux version coverage.

**Comment by AdamBrousseau** [comment]
When the PR builds change to pipeline of jobs (hopefully this week). You will no longer be limited to cent6 for the PR builds. I think we need to consider build times for compile vs test and also amount of CPU needed for test-only machines. If we only need 2cpu test machines we could create 4 test machines for the cost of a 8cpu compile machine.

**Comment by pshipton** [comment]
The functional tests should be ok, but some of the system tests benefit from having 8 cpus.
