### ISSUE TITLE
Unintialized variable use inside SPMDParallelizer optimization

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/openj9#557]
Inside insertGPUTemporariesLivenessCode in SPMDParallelizer.cpp the variable currentNode will sometimes be used before being initialized. This can lead to issue like a segfault.

currentNode is typically initialized inside the inner for loop in insertGPUTemporariesLivenessCode. The for loop iterates over the gpuSymbolMap and skips entries where either the hostSymRef is null or the parmSlot value is -1. It is possible that none of the entries in the gpuSymbolMap pass both conditions. In this case, currentNode is never initialized with a value. At the end of the outer for loop, currentNode is used to create a Treetop. If currentNode has not been initialized, segfaults or other unexpected behavior can occur.

A fix is required such that currentNode is always initialized to a usable value before being used.

**Comment by mstoodle** [comment]
@IBMJimmyk Seems like this issue has been resolved, please reopen if I've misunderstood.
