### ISSUE TITLE
Confusing VerifyError when trying to load class that inherits from final class

### ISSUE THREAD

**Issue by Barteks2x** [eclipse/openj9#5573]
When trying to load a class that extends a final class, for example with `X extends Y`, the VerifyError points to Y (the final class) being wrong instead of to X, and there is no information as to what is wrong.

OpenJDK and oracle JVM point to the class that attempts to inherit from final class, with message "Cannot inherit from final class".

**Comment by DanHeidinga** [comment]
@ChengJin01 Can you take a look at this?

**Comment by ChengJin01** [comment]
Will check to see what happened to this issue.

**Comment by ChengJin01** [comment]
I managed to reproduce the problem via ASM code (as such problem will be captured as error during compilation) as follows:

the test case:
```
public class X extends Y
{
    public static void main(String args[]) 
    { 
       X x = new X();
    }
}

public final class Y {
}
```
The output on Hotspot  & OpenJ9
```
jdk_11.0.3_7_hotspot/bin/java  -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

jdk_11.0.3_7_hotspot/bin/java  -cp . X
Error: LinkageError occurred while loading main class X
        java.lang.VerifyError: Cannot inherit from final class  <-------------- 

 jdk_11.0.3_7_openj9/bin/java  -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.0, JRE 11 Linux amd64-64-Bit Compressed References 20190417_202 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5cc996a803 based on jdk-11.0.3+7)

jdk_11.0.3_7_openj9/bin/java  -cp .  X
Error: LinkageError occurred while loading main class X
        java.lang.VerifyError: Y  <------- point to the final class with misleading message
```
As compared to the Hotspot, the verification check for this error on OpenJ9 is correct but the error message offered in such case is pretty simple which leads to confusion.  I will double-check the code related to the message to see how to make it more descriptive.

**Comment by ChengJin01** [comment]
The error message came from loadSuperClassAndInterfaces() at /runtime/vm/createramclass.cpp as follows:
```
loadSuperClassAndInterfaces(...)
...
				/* ensure that the superclass isn't an interface or final */
			if ((superclass->romClass->modifiers & J9AccFinal) != 0) {
				Trc_VM_CreateRAMClassFromROMClass_superclassIsFinal(vmThread, superclass);
				setCurrentExceptionForBadClass(vmThread, superclassName, J9VMCONSTANTPOOL_JAVALANGVERIFYERROR);
				return FALSE;
			}

static void
setCurrentExceptionForBadClass(J9VMThread *vmThread, J9UTF8 *badClassName, UDATA exceptionIndex)
{
	J9MemoryManagerFunctions *gcFuncs = vmThread->javaVM->memoryManagerFunctions;
	j9object_t detailMessage = gcFuncs->j9gc_createJavaLangString(vmThread, J9UTF8_DATA(badClassName), J9UTF8_LENGTH(badClassName), J9_STR_XLAT);

	setCurrentException(vmThread, exceptionIndex, (UDATA *)detailMessage); <------
}
```
It seems the existing implementation in our code only includes the class name in the error message when checking the loaded classes. Given setCurrentExceptionForBadClass is shared among various types of errors, it means only a bad class name shows up in the error message when any one of these errors is thrown out. So we need to modify the code here in some way to introduce more detailed message (e.g. by calling setCurrentExceptionUTF() ) to these errors (not specific to the verification error in this issue).

**Comment by ChengJin01** [comment]
I already modified the code to cover all errors with detailed messages when calling setCurrentExceptionForBadClass in loading classes, including the verification error as follows, which should satisfy our needs.
```
jdk_openj9/bin/java -cp . X
Error: LinkageError occurred while loading main class X
        java.lang.VerifyError: Y: The final superclass can't be inherited  <--------------
```
