### ISSUE TITLE
Cache RAM class flags on the server

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#5584]
**Problem**
`J9::ClassEnv::classFlagsValue` returns flags of a RAM class.
Class flags contain some metadata about its RAM class.
Since RAM classes are loaded on the client, when JITaaS server calls this method, it
needs to make a remote call to the client, and fetch flags from there.
We could reduce message count by a few percent by caching the return values of this method on the server.

**Relevant Files**
```
env/J9ClassEnv.cpp
control/JITaaSCompilationThread.hpp
control/JITaaSCompilationThread.cpp
```

**Proposed solution:**
Cache `classFlags` in `ClientSessionData::ClassInfo` struct.
`ClassInfo` stores cached values of a client RAM class, such as: whether class is an array, pointer to its superclass, pointer to methods of the class and so on.
Use cache implementation in `J9::ClassEnv::classDepthOf` (or any other method with cached values from that class) as a reference.

**Potential problems:**
- RAM class can be modified during runtime. This means that cached values might become invalid. Usually, this does not pose a problem, because whenever any major change to a RAM class occurs, it is marked as unloaded, and server will clear the cache.
Are we guaranteed, that `classFlags` will not change while the class is loaded?
We already cache most things from `J9::ClassEnv`, so I would assume caching one more flag should be fine, but we still need to be careful.
- There is a similarly named attribute, called `classDepthAndFlags` which is already cached.
Could they actually refer to the same thing? From what I can tell, they are different, and are used for different purposes, so there should be no overlap.

**Comment by dmitry-ten** [comment]
@mpirvu this could be another beginner issue.

**Comment by chrisc66** [comment]
I am working on this issue

**Comment by mpirvu** [comment]
`classFlags` are different than `classDepthAndFlags`. See the following definitions

```
#define J9CLASS_FLAGS(clazz) ((UDATA)(clazz)->classDepthAndFlags)
#define J9CLASS_DEPTH(clazz) (((UDATA)(clazz)->classDepthAndFlags) & J9AccClassDepthMask)
#define J9CLASS_EXTENDED_FLAGS(clazz) ((clazz)->classFlags)
```

Individual flags
```
/* Constants from J9JavaClassFlags */
#define J9ClassDoNotAttemptToSetInitCache 0x1
#define J9ClassHasIllegalFinalFieldModifications 0x2
#define J9ClassReusedStatics 0x4
#define J9ClassContainsJittedMethods 0x8
#define J9ClassContainsMethodsPresentInMCCHash 0x10
#define J9ClassGCScanned 0x20
#define J9ClassIsAnonymous 0x40
#define J9ClassIsFlattened 0x80
#define J9ClassHasWatchedFields 0x100
#define J9ClassReservableLockWordInit 0x200
#define J9ClassIsValueType 0x400
#define J9ClassLargestAlignmentConstraintReference 0x800
#define J9ClassLargestAlignmentConstraintDouble 0x1000
```

Some of these fields can be changed at runtime while others (like `J9ClassIsAnonymous`) cannot.
The JIT uses classFlags for `J9ClassReservableLockWordInit` (in two places) and more generic in `simplifyJ9ClassFlags()`. In the latter case the value of the flags is baked into the jitted code so it could be argued that even the non-jitaas optimizer can introduce some staleness as the flags could change after the jitted body has been produced.
`J9ClassReservableLockWordInit` is set when the class is loaded and doesn't seem to change afterwards.

I would like to understand where do most JIT queries for classFlags come from.

**Comment by chrisc66** [comment]
Hey @mpirvu, from the tests and stack trace results that @dmitry-ten and I ran:
* function `TreeEvaluator::VMnewEvaluator` calls `ClassEnv::classFlagsValue` 715 times
* function `J9VMBase::initializeClazzFlagsMonitorFields` calls `ClassEnv::classFlagsValue` 3 times

All functions are only reading `J9ClassReservableLockWordInit` flag inside `classFlagsValue`, and we believe that this flag is not changed. 

It seems that `J9ClassReservableLockWordInit` is the only one that is queried from other functions, and no other flag inside `classFlagsValue` is queried. So it seems to be safe it we cache `classFlags` on the server for now. This could be verified by running more benchmarks and look into the stack traces.

**Comment by mpirvu** [comment]
I agree that `J9ClassReservableLockWordInit` flag does not change. However, to avoid cases where in the future the optimizer could test other flags that could change I am in favor of creating a query just for this flag.

**Comment by chrisc66** [comment]
Thanks, I am working on this right now.

**Comment by chrisc66** [comment]
Added the function that query only `J9ClassReservableLockWordInit` flag, but some other problem pops up. 

At some point during runtime, remote call shows that the entire struct `classFlagsValue = 0` , while the cached version `classFlagsValue` is valid. GDB output shows below:

```
(gdb) p/t classFlagsCache
$1 = 11111111111111111011010010111110101011100100000
(gdb) p/t classFlagsRemote
$2 = 0
```

This happens quite frequent, likely more than once every five compilation. From my understanding, this function is only called during compilations. When compilation is finished, the entire class along with flags are destroyed without calling this function. Not sure why entire `classFlagsValue` becomes zero. Does it imply that we should not cache `RAM class flags`?

**Comment by mpirvu** [comment]
I don't understand the scenario you described. 
Does this behavior happen for the RAMClass of the method being compiled?
Does it always happen for some classes, but not for others?

**Comment by chrisc66** [comment]
Just a bit update, @dmitry-ten and I investigated into this `J9ClassReservableLockWordInit` flag. 

To answer your previous question
* this behaviour happens when a method is being compiled
* it seems to be happening on many classes, not sure for every class

From observation, the cached flag values are always 0, and some of the remote call flag values are 1. I am suspecting that this flag is unset at the beginning, but it might change during compilation process. 

I am going to look into the client's code and find out if there is anything that I missed.
