### ISSUE TITLE
Metronome GC - long pause in sweep phase

### ISSUE THREAD

**Issue by akrus** [eclipse/openj9#5615]
As discussed in #4769, creating a new issue for too long pauses (~5 ms) when the targetPauseTime is set to 1 ms.

**Comment by amicic** [comment]
copy-pasting a sample cycle from the 'parent' issue:

```
<cycle-start id="8115" type="global" contextid="0" timestamp="2019-04-25T06:32:05.475" intervalms="204486.425" />
  <quanta quantumCount="170" quantumType="mark" minTimeMs="1.006" meanTimeMs="1.100" maxTimeMs="1.609" maxTimestampMs="0.000" />
  <quanta quantumCount="155" quantumType="mark" minTimeMs="1.022" meanTimeMs="1.085" maxTimeMs="1.211" maxTimestampMs="175.328" />
  <quanta quantumCount="193" quantumType="mark" minTimeMs="0.603" meanTimeMs="1.067" maxTimeMs="1.219" maxTimestampMs="1006.300" />
  <quanta quantumCount="179" quantumType="mark" minTimeMs="0.245" meanTimeMs="1.088" maxTimeMs="1.210" maxTimestampMs="164.778" />
  <quanta quantumCount="188" quantumType="sweep" minTimeMs="0.771" meanTimeMs="1.051" maxTimeMs="5.272" maxTimestampMs="0.000" />
  <quanta quantumCount="199" quantumType="sweep" minTimeMs="0.800" meanTimeMs="1.025" maxTimeMs="1.067" maxTimestampMs="461.437" />
  <quanta quantumCount="72" quantumType="sweep" minTimeMs="0.753" meanTimeMs="1.009" maxTimeMs="3.154" maxTimestampMs="331.711" />
  <quanta quantumCount="5" quantumType="postcollect" minTimeMs="0.394" meanTimeMs="0.898" maxTimeMs="1.029" maxTimestampMs="0.000" />
<cycle-end id="8124" type="global" contextid="8115" timestamp="2019-04-25T06:32:11.846" />
```

We appear to have two longish pauses, one (about 5ms) at the very beginning of sweep phase (max timestamp is always 0, which indicates it's the first increment in the quanta, and it's always the first sweep quanta in the cycle) and another one (about 3ms) toward the end of (quite possibly the very end) of sweep phase.

**Comment by amicic** [comment]
hi @akrus, do you still see these types of delays after https://github.com/eclipse/openj9/issues/4769#issuecomment-497743809? If you are not sure how to identify them, you can just send me logs.

**Comment by akrus** [comment]
@amicic, I think it's still here:
```
<quanta quantumCount="192" quantumType="sweep" minTimeMs="0.609" meanTimeMs="1.035" maxTimeMs="5.596" maxTimestampMs="0.000" />
```

Sent the logs.

**Comment by amicic** [comment]
Ok, not surprised. Felt like a different problem from the first look. I'm yet to think how to tackle this - probably introduce some new trace logs to narrow down the scope....

**Comment by akrus** [comment]
Just noticed on another server:
```
  <quanta quantumCount="194" quantumType="sweep" minTimeMs="0.994" meanTimeMs="1.219" maxTimeMs="8.592" maxTimestampMs="592.714" />
...
  <quanta quantumCount="202" quantumType="sweep" minTimeMs="1.046" meanTimeMs="1.215" maxTimeMs="9.055" maxTimestampMs="536.484" />
...
  <quanta quantumCount="190" quantumType="sweep" minTimeMs="0.976" meanTimeMs="1.290" maxTimeMs="10.444" maxTimestampMs="62.498" />
...
  <quanta quantumCount="203" quantumType="sweep" minTimeMs="0.937" meanTimeMs="1.225" maxTimeMs="10.251" maxTimestampMs="46.934" />
```
Average was ~3-5 ms before and it spiked for some reason after 1 day of uptime.

**Comment by amicic** [comment]
@akrus is this still an outstanding issue? could we close this?

**Comment by dmitripivkine** [comment]
Closing this issue due inactivity. If problem still exist please reopen or create new one

**Comment by akrus** [comment]
I believe the problem is still there, just we stopped using OpenJ9 there.

**Comment by pshipton** [comment]
@akrus was the switch due to any failings of OpenJ9? Anything we can do to improve?

**Comment by akrus** [comment]
@pshipton,
we still use OpenJ9 with Metronome GC for another project where latency requirements are not that strict, the load and heaps are much smaller, it works well there so far.
Regarding main app, as it's described here, the pause times were unpredictable and depending on load they could easily reach 10+ ms (which is our target that we can never exceed), although that was just part of the issue.
I had an email conversation with @amicic directly regarding another issue. OpenJ9 under some conditions didn't clean the garbage properly, so we had a couple of OOMs with 1s+ sync GC pauses after (and restarting the app was the only possible fix). Unfortunately, we haven't found why this could happen, the only thing we found that directly affects this was the option -Xgc:regionSize (increasing it was shortening the time needed to reach the OOM condition).
Probably worth noticing that the app is generating up to ~300 GB of garbage per minute with many millions of small objects.
