### ISSUE TITLE
Please update test instructions for Windows

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#5619]
The [Reproducing Test Failures Locally](https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally) page indicates that JAVA_BIN must be set to ```/someLocation/jre/bin``` (same without ```jre``` for post Java 8).  On Windows,
it seems that the scripts require the JAVA_BIN path to be in Windows format, e.g.
```JAVA_BIN=C:\Users\foobar\Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/openjdkbinary/j2sdk-image/jre/bin```.

Please update the instructions to reflect this.

Please also update the usage() in ```get.sh```:
```--platform|-p x64_linux | x64_mac | s390x_linux | ppc64le_linux | aarch64_linux | ppc64_aix```

Note that Windows is missing.

Thank you

**Comment by llxia** [comment]
[Reproducing Test Failures Locally](https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally) is updated:
-  set `TEST_JDK_HOME` (instead of `JAVA_BIN`)
- remove unnecessary `-p` instruction for running `get.sh` (`-p` is needed if we use `get.sh` to download nightly SDK)

**Comment by llxia** [comment]
Close the issue as the doc is updated.
