### ISSUE TITLE
testXXXGetAndOpLong failures on x86-64 Linux JDK11

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#5626]
There appear to be 3 failures in PR builds on x86 Linux JDK11.  JDK8 seems fine.   I don't see these failures on any other architecture or OS.

These were seen in two different PRs based on a rebase of OpenJ9 from last night and OMR master.  The PRs being tested are independent, one of which contained code that could not execute on this platform.

Latest OpenJ9 SHA:  0e1dbb160be298b72e9b6c13b35ddc944ac41112

```
00:07:41          FAILED: testArrayGetAndOpLong (Regular)
00:07:41          java.lang.NullPointerException
00:07:41          	at org.openj9.test.unsafe.TestUnsafeGetAndOp.testArrayGetAndOpLong(TestUnsafeGetAndOp.java:141)
...

00:07:41          FAILED: testInstanceGetAndOpLong (Regular)
00:07:41          java.lang.NullPointerException
00:07:41          	at org.openj9.test.unsafe.TestUnsafeGetAndOp.testInstanceGetAndOpLong(TestUnsafeGetAndOp.java:86)
...

00:07:41          FAILED: testStaticGetAndOpLong (Regular)
00:07:41          java.lang.NullPointerException
00:07:41          	at org.openj9.test.unsafe.TestUnsafeGetAndOp.testStaticGetAndOpLong(TestUnsafeGetAndOp.java:196)
...
```

**Comment by DanHeidinga** [comment]
This appears to be a dup of a known problem: https://github.com/eclipse/openj9/issues/4657 which has been difficult to track down as it hasn't been sufficiently reproducible in grinders.

Conversation can continue in #4657 so I'll close this now
