### ISSUE TITLE
Remove asserts that prevent testing with a JITaaS debug build

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5631]
A bunch of asserts that try to asertain the quality of the cached IProfiler data are firing, which prevents us from doing testing with debug builds.
We should comment out those asserts to allow proper testing and re-visit them later on (they *might* have performance implications).

**Comment by a7ehuo** [comment]
One of the asserts is 
https://github.com/eclipse/openj9/blob/67de68a8802efc98132772914b6d2853e65dd235/runtime/compiler/runtime/JITaaSIProfiler.cpp#L665

**Comment by dmitry-ten** [comment]
That's actually the only assert I've ever seen happening in IProfiler.

**Comment by caohaley** [comment]
I will work on this one with the help of Annabelle.

**Comment by a7ehuo** [comment]
Remember seeing `"static attributes from client and cache do not match"` assert while running sanity test. It'd be good to use this issue to identify as many JITaaS related asserts in debug build while running sanity test as possible.

**Comment by caohaley** [comment]
I ran the following tests independently and have not seen any failed asserts:
_jit_jitt_0
_jit_jitt_1
_jit_jitt_2
_jit_jitt_3
_jit_jar_0
_jit_ra_0
_jit_vich_0
I am going to run _sanity now.

**Comment by caohaley** [comment]
Ran the make_sanity test as a whole and came across to the following assert on server side. The asserts occurred one by one as I commented them out in the following order and reran the debug test. @ymanton should we investigate into the asserts and which asserts shall we comment out?

```
Assertion failed at ../compiler/env/j9methodServer.cpp:144: validateMethodFieldAttributes(attributes, isStatic, cpIndex, isStore, needAOTValidation)
VMState: 0x00050080
	static attributes from client and cache do not match
```
```
Assertion failed at ../compiler/env/j9methodServer.cpp:523: validated
VMState: 0x000501ff
        field attributes from client and cache do not match
```
```
Assertion failed at ../compiler/runtime/JITaaSIProfiler.cpp:666: domClazzClient == domClazzServer
VMState: 0x0005ff04
	Missmatch dominant class client=0x2397400 server=0x231b400
```
```
Assertion failed at ../compiler/runtime/ClassUnloadAssumption.cpp:1544: prev.getEnd() < cur.getStart()
	UAR: ERROR: range 56 [0x321dead - 0x321dead] overlaps previous range ending at 0x321dead
```
Still in the process of running the test after the last assert mentioned.

**Comment by mpirvu** [comment]
I think that the first two asserts (and possibly the last one) are indicative of existing bugs. Thus the asserts should not be eliminated.

**Comment by caohaley** [comment]
Okay! I will make 2 issues, one for investigating into the j9methodServer.cpp file and one for ClassUnloadAssumption.cpp file.

**Comment by caohaley** [comment]
I am currently looking into why and where the dominant class does not match for client and server for the assert:
```
Assertion failed at ../compiler/runtime/JITaaSIProfiler.cpp:666: domClazzClient == domClazzServer
VMState: 0x0005ff04
	Missmatch dominant class client=0x2397400 server=0x231b400
```
