### ISSUE TITLE
Acceptance builds for OpenJDK extensions

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5637]
OpenJDK extensions are going to have OpenJDK changes merged into a openj9-staging branch. We want to run an acceptance build (similar to OMR) on the openj9-staging branch, and merge openj9-staging into the openj9 banch when the acceptance testing passes.

jdknext is ready to go now, the older versions will follow.
Note the test builds for jdknext aren't working yet, so until they do the acceptance build for jdknext can just be compile only.

**Comment by pshipton** [comment]
@AdamBrousseau @andrew-m-leonard

**Comment by AdamBrousseau** [comment]
All platforms? xlinux, xlinux_xl, xlinux_cm?

**Comment by pshipton** [comment]
The same platforms as OMR acceptance. i.e. all

**Comment by andrew-m-leonard** [comment]
Note: jdk12 MUST not be included in auto-accepting openj9-staging into openj9, as it is Oracle managed and currently openj9-staging is based on jdk12u "head" which may or may not have the correct commits for jdk-12.0.2...

jdk: Auto-merges HEAD into openj9-staging. Good for auto-acceptance.
jdk12: Auto-merges HEAD into openj9-staging. NOT good for auto-acceptance.
jdk11 : Auto-merges latest tagged build into openj9-staging. Good for auto-acceptance.

**Comment by andrew-m-leonard** [comment]
Also added jdk8u auto-merge of latest tagged builds:
jdk8 : Auto-merges latest tagged build into openj9-staging. Good for auto-acceptance.

**Comment by AdamBrousseau** [comment]
PR is ready to be merged. Just need to determine how to trigger the builds. I can look at setting up a hook on the repos that will fire the job when content is pushed to the staging branch.

**Comment by pshipton** [comment]
@AdamBrousseau please confirm that JDK12 will not promote to openj9. We can run the acceptance build to see if anything is failing, but the build should not promote anything.

**Comment by AdamBrousseau** [comment]
correct. The `PROMOTE` param in the jenkins job is not set
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK12-Acceptance/build?delay=0sec
vs jdk11
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK11-Acceptance/build?delay=0sec

**Comment by pshipton** [comment]
Thanks @AdamBrousseau. I notice the jdk11 build has TESTS_TARGETS `none`. We shouldn't be promoting anything that hasn't passed the testing.

**Comment by AdamBrousseau** [comment]
fixed (and jdk8)

**Comment by AdamBrousseau** [comment]
Until I sort out the trigger, feel free to launch on demand.

**Comment by pshipton** [comment]
Started a jdk11 acceptance. Which should promote, considering the material being staged is the 11.0.3+7 level we already shipped with OpenJ9 0.14

**Comment by pshipton** [comment]
The builds are available and working, but not yet automatically triggered, so I won't close this issue yet.

**Comment by pshipton** [comment]
The builds are available and working when manually launched, but since they aren't automatically triggered yet I won't close this.

**Comment by pshipton** [comment]
The builds are available, working, and can be started manually. Since they aren't automatically triggered yet, I won't close this issue.

**Comment by pshipton** [comment]
The builds are available, working, and can be started manually. Since they aren't automatically triggered yet, I won't close this issue.

**Comment by AdamBrousseau** [comment]
I have setup the repo triggers on all repos (8,11,12,next). The builds should launch when content is pushed to the `openj9-staging` branch. @andrew-m-leonard if you could confirm the next time the merge jobs run and content is pushed that the corresponding Acceptance build fires that would be great.

**Comment by pshipton** [comment]
Two builds for each version (8, 11, 12, next) were started at 10:13 and 10:24pm. Jenkins could not handle this load. I've disabled all the acceptance builds.

**Comment by andrew-m-leonard** [comment]
@AdamBrousseau jdk11 openj9-staging is now at jdk-11.0.4+2
jdkNext is quite busy and is merging new changes every night

**Comment by pshipton** [comment]
@andrew-m-leonard the linux compile problems are blocking merging new levels, not automated kickoff of acceptance builds. If you've seen a fix get merged, we can try a new build.

https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_OpenJDK11/3/console
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_OpenJDK11/5/console

**Comment by AdamBrousseau** [comment]
Made a change to the job trigger configs to hopefully resolve the issue of them all launching. Kicked off a merge job now to test.

**Comment by AdamBrousseau** [comment]
No go yet, they all just launched at the same time

**Comment by AdamBrousseau** [comment]
Added another filter on the triggers. Hopefully solved now. Will keep an eye on it.

**Comment by pshipton** [comment]
@AdamBrousseau Suggest we launch a merge job during the day today, for one jdk version, in order to test.

**Comment by andrew-m-leonard** [comment]
@AdamBrousseau jdk8 openj9-staging has just updated to jdk8u222-b02

**Comment by AdamBrousseau** [comment]
Looks like we got a build triggered
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK8-Acceptance/7/
And no other builds triggered. I think this is resolved.
