### ISSUE TITLE
Issues with generated coredump when using MAT and gdb

### ISSUE THREAD

**Issue by BrijeshNekkare** [eclipse/openj9#564]
Notice couple of issues with the coredumps generated (using command "java -Xdump:system:events=vmstart -version") on OpenJ9 .

1. Memory analyzer tool(MAT) is unable to parse the coredump generated. It fails with below error

		Error opening heap dump 'adopt_openjdk_core.20171110.155110.13247.0001.dmp'. Check the error log for further details.
		Error opening heap dump 'adopt_openjdk_core.20171110.155110.13247.0001.dmp'. Check the error log for further details.
		Unable to find Java runtime in DTFJ image after searching 1 address spaces (last space: '0x0') 1 processes (last process ID: '13278') 0 Java runtimes (last runtime address: '') (java.io.IOException)
		Unable to find Java runtime in DTFJ image after searching 1 address spaces (last space: '0x0') 1 processes (last process ID: '13278') 0 Java runtimes (last runtime address: '')

	    Failed with both the below versions
		    a. AdoptOpenJDK version
				openjdk version "9-internal"
				OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
				Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171027_36 (JIT enabled, AOT enabled)
				OpenJ9   - 292f272
				OMR      - 9ea665d
				OpenJDK  - 640ef65 based on )
			b. Built OpenJ9-OpenJDK-JDK9
				openjdk version "9-internal"
				OpenJDK Runtime Environment (build 9-internal+0-adhoc..openj9-openjdk-jdk9)
				Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171110_000000 (JIT enabled, AOT enabled)
				OpenJ9   - d9ad7aa
				OMR      - e1404d5
				OpenJDK  - ae4d07b based on jdk-9+181)

2. gdb is unable to get backtrace when the coredump is generated inside the Docker container

			gdb ./openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/bin/java within_docker_core.20171110.064025.10.0001.dmp
			...............................
			Reading symbols from ./openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/bin/java...(no debugging symbols found)...done.

			warning: core file may not match specified executable file.
			[New LWP 42]

			warning: .dynamic section for "/lib/x86_64-linux-gnu/libgcc_s.so.1" is not at the expected address (wrong library or version mismatch?)

			warning: Could not load shared library symbols for 25 libraries, e.g. /root/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/jdk/bin/../lib/jli/libjli.so.
			Use the "info sharedlibrary" command to see the complete listing.
			Do you need "set solib-search-path" or "set sysroot"?

			warning: File "/lib/x86_64-linux-gnu/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
			To enable execution of this file add
					add-auto-load-safe-path /lib/x86_64-linux-gnu/libthread_db-1.0.so
			line to your configuration file "/root/.gdbinit".
			To completely disable this security protection add
					set auto-load safe-path /
			line to your configuration file "/root/.gdbinit".
			For more information about this security protection see the
			"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
					info "(gdb)Auto-loading safe path"

			warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

			warning: File "/lib/x86_64-linux-gnu/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".

			warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
			Core was generated by `./build/linux-x86_64-normal-server-release/jdk/bin/java -Xdump:system:events=vm'.
			Program terminated with signal SIGSEGV, Segmentation fault.
			#0  sem_open (name=0x7fcef612a2e0 "/root/openj9-openjdk-jdk9/", oflag=<error reading variable: Cannot access memory at address 0xffffffffffffff58>)
				at sem_open.c:233
			233     sem_open.c: No such file or directory.
			(gdb) thread apply all bt

			Thread 1 (LWP 42):
			#0  sem_open (name=0x7fcef612a2e0 "/root/openj9-openjdk-jdk9/", oflag=<error reading variable: Cannot access memory at address 0xffffffffffffff58>)
				at sem_open.c:233
			Backtrace stopped: Cannot access memory at address 0x8
			(gdb)

Am i missing something very basic here.

**Comment by pshipton** [comment]
Scenario 1 doesn't work because of #378

**Comment by pshipton** [comment]
For scenario 2, perhaps the core file has been truncated?

**Comment by BrijeshNekkare** [comment]
1. Ulimit for corefiles is set to unlimited.

2. On the same system if i generate the coredumps outside the docker (have used docker mapped volume feature) container it works.

**Comment by pshipton** [comment]
Does it work if you run gdb inside docker?

**Comment by pshipton** [comment]
Note the core file is created by the OS, not by OpenJ9.

**Comment by BrijeshNekkare** [comment]
Had issues running gdb inside the docker, will get back to this by end of this week.

**Comment by pshipton** [comment]
@BrijeshNekkare any update on this?

**Comment by BrijeshNekkare** [comment]
@pshipton,
Sorry about the delay, i wasn't able to reproduce this issue on ubuntu 16.04, so closing this issue.
