### ISSUE TITLE
Increase scratchSpaceLimit for JITaaS server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5644]
Remote compilations should be allowed to use more memory for compilation.
This way, in theory, we could improve the performance of applications over what a non-jitaas solution can provide.
Note that the scratchSpaceLimit comes from TR::Options and it's going to be passed from client to server. Maybe we could double the value at the server making sure we don't exceed 2GB, maximum an int could hold.

**Comment by harryyu1994** [comment]
Taking this one on the side.

**Comment by harryyu1994** [comment]
```
 // Cap the limit for JIT to 4GB
            size_t proposedCapped = proposedScratchMemoryLimit > UINT_MAX ? UINT_MAX : (size_t)proposedScratchMemoryLimit;
```
- Looks like it's an unsigned int and can be capped to 4GB

**Comment by harryyu1994** [comment]
The default value is already 2GB when we don't specify anything

**Comment by mpirvu** [comment]
Some strangeness seen when the client is running in docker and is limited to a small amount of memory:
```
The following messages at the client show that we fail a compilation due to heap limit
#JITaaS: Client sending compReq seqNo=18325 to server for method com/ibm/ws/webcontainer/webapp/WebApp$AnnotatedMethods.lookupMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method; @ warm.
#JITaaS: Client failed to load method com/ibm/ws/webcontainer/webapp/WebApp$AnnotatedMethods.lookupMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method; @ warm following compilation request.
! com/ibm/ws/webcontainer/webapp/WebApp$AnnotatedMethods.lookupMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method; time=49946us compilationHeapLimitExceeded memLimit=262144 KB freePhysicalMemory=0 MB mem=[region=128 system=128]KB
```
According to the diagnostic output the memory limit at the client is 256M, yet the compilation failed with `compilationHeapLimitExceeded` after using only 128KB. Note that we operate in a region where there is very little free physical memory (`freePhysicalMemory=0`). Typically the segment allocated for scratch memory would be 16MB and if that's too large to allocate it is reduced to 2MB and then to 64KB. Here `system memory` is 128KB which means we were forced to go down to 64KB segments.

From the server point of view the compilation finishes normally:
```
#JITaaS: compThreadID=2 found clientSessionData=00007FEDE1D1A620 for clientUID=9703904877905968535 seqNo=18325
#JITaaS: Server will process a list of 0 unloaded classes for clientUID 9703904877905968535
 (warm) Compiling com/ibm/ws/webcontainer/webapp/WebApp$AnnotatedMethods.lookupMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method;  RemoteOrdinaryMethod j9m=000000000206B3E8 t=235199 compThread=2 memLimit=262144 KB freePhysicalMemory=13324 MB
+ (warm) com/ibm/ws/webcontainer/webapp/WebApp$AnnotatedMethods.lookupMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method; @ 00007FEDCF800060-00007FEDCF802682 RemoteOrdinaryMethod - Q_SZ=0 Q_SZI=0 QW=0 j9m=000000000206B3E8 bcsz=451 OSR time=43421us mem=[region=5696 system=16384]KB compThread=2 CpuLoad=14%(1%avg) JvmCpu=0%
#JITaaS: compThreadID=2 has successfully compiled com/ibm/ws/webcontainer/webapp/WebApp$AnnotatedMethods.lookupMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method;
```

**Comment by mpirvu** [comment]
I used some instrumentation and it appears that we run out of memory while doing the CHTable commit after the compiled body was received from the server:
```
 (warm) Compiling com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I  OrdinaryMethod j9m=00000000040A9020 t=265528 compThread=0 memLimit=262144 KB freePhysicalMemory=1 MB
#JITaaS: Client sending compReq seqNo=18772 to server for method com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I @ warm.
#FAILURE:  Finishing compilation; after remoteCompilationEnd
#FAILURE:  Finishing compilation; entering CHTable mutex
#FAILURE:  Finishing compilation; about to execute JITaaSCHTableCommit
#JITaaS: Client failed to load method com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I @ warm following compilation request.
! com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I time=25244us compilationHeapLimitExceeded memLimit=262144 KB freePhysicalMemory=0 MB mem=[region=128 system=128]KB
 (cold) Compiling com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I  OrdinaryMethod j9m=00000000040A9020 t=265548 compThread=0 memLimit=262144 KB freePhysicalMemory=0 MB
! com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I time=74us compilationHeapLimitExceeded memLimit=262144 KB freePhysicalMemory=0 MB mem=[region=64 system=64]KB
 (no-opt) Compiling com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I  OrdinaryMethod j9m=00000000040A9020 t=265548 compThread=0 memLimit=262144 KB freePhysicalMemory=0 MB
! com/ibm/ws/sib/api/jms/impl/JmsMsgProducerImpl.getDeliveryMode()I time=52us compilationHeapLimitExceeded memLimit=262144 KB freePhysicalMemory=0 MB mem=[region=64 system=64]KB
 (warm) Compiling com/ibm/ws/sib/api/jms/impl/ProducerProperties.setInDeliveryModeOverride(Ljava/lang/String;)V  OrdinaryMethod j9m=00000000040AAC38 t=265548 compThread=0 memLimit=262144 KB freePhysicalMemory=0 MB
#JITaaS: Client sending compReq seqNo=18773 to server for method com/ibm/ws/sib/api/jms/impl/ProducerProperties.setInDeliveryModeOverride(Ljava/lang/String;)V @ warm.
```
It's not clear to me why the retrials are not sent to the server as well.
Interestingly, the next compilation is sent remotely and it succeeds.

I am thinking that the client should hold on to a segment of 128K and never release that.

**Comment by mpirvu** [comment]
@harryyu1994 Could you please look again at this one?
From time to time I am seeing compilations failing at the server with scratchMemoryLimit failures. I was proposing to double the limit when in client mode. This increased limit will be passed to the server which may have a better chance of succeeding.

**Comment by harryyu1994** [comment]
Correct me if I'm wrong, I think "static size_t _scratchSpaceLimit;" is static and static options aren't passed from client to the server. So i think we just need to handle the limit change on the server side. Is there a need to have it passed from client to server?

**Comment by harryyu1994** [comment]
I think the limit that each compilation used is a non-static variable stored in the TR::Compilation object and that one is set depending on 1. the static _scratchSpaceLimit 2. current available memory and other factors like whether it's a JSR292 method. I think we just need to "2x" it if it's a JITServer compilation there.

**Comment by mpirvu** [comment]
`Is there a need to have it passed from client to server?`
Not necessarily. I thought that this option is passed like any other option.
