### ISSUE TITLE
Reduce number of ResolvedMethod_isUnresolvedString messages

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#5649]
Most of the `ResolvedMethod_isUnresolvedString` messages come from the following piece of code
```
J9::SymbolReferenceTable::findOrCreateStringSymbol(TR::ResolvedMethodSymbol * owningMethodSymbol, int32_t cpIndex)
   {
   TR_ResolvedMethod * owningMethod = owningMethodSymbol->getResolvedMethod();
   void * stringConst = owningMethod->stringConstant(cpIndex);
   TR::SymbolReference * symRef;
   if (owningMethod->isUnresolvedString(cpIndex))
```
As seen above, before calling `isUnresolvedString` we call `stringConstant` which requires another message. We could create a combined frontend function that returns the answer to both queries, so that we need one message instead of two.

**Comment by a7ehuo** [comment]
I'll work on this one next.
