### ISSUE TITLE
Support AsyncGetCallTrace in OpenJ9

### ISSUE THREAD

**Issue by gacholio** [eclipse/openj9#5654]
Structures we need to mirror from OpenJDK:

```
typedef struct {
  jint lineno;         // BCI in the source file
  jmethodID method_id; // method executed in this frame
} ASGCT_CallFrame;

typedef struct {
  JNIEnv *env_id   //Env where trace was recorded
  jint num_frames; // number of frames in this trace
  ASGCT_CallFrame *frames;
} ASGCT_CallTrace; 
```

Error codes (presumable returned in `num_frames` above):

```
enum {
ticks_no_Java_frame         =  0, // new thread
ticks_no_class_load         = -1, // jmethodIds are not available
ticks_GC_active             = -2, // GC action
ticks_unknown_not_Java      = -3, // ¯\_(ツ)_/¯
ticks_not_walkable_not_Java = -4, // ¯\_(ツ)_/¯
ticks_unknown_Java          = -5, // ¯\_(ツ)_/¯
ticks_not_walkable_Java     = -6, // ¯\_(ツ)_/¯
ticks_unknown_state         = -7, // ¯\_(ツ)_/¯
ticks_thread_exit           = -8, // dying thread
ticks_deopt                 = -9, // mid-deopting code
ticks_safepoint             = -10 // ¯\_(ツ)_/¯
}; 
```

And the API function:

```
void AsyncGetCallTrace(
                       jASGCT_CallTrace *trace, // pre-allocated trace to fill
                       jint depth,             // max number of frames to walk up the stack
                       jvoid* ucontext) // signal context
```

**Comment by gacholio** [comment]
Several things need to be sorted out:

- Where to find the VM? AGCT does not accept any java-related parameters

I suspect we'll have to maintain a global for the VM (horrible, but we already restrict to one VM per process).

- How to find the current thread

Given the VM, currentVMThread(vm) will return the current thread or NULL.

- How to walk the stack

For now, consider only stack which have a jitted method running on top. To determine this, get the PC value from the signal context and get the jit metadata. If non-NULL, the frame is jitted.

At this point, to make the stack walkable, use jitPushResolveFrame (see https://github.com/eclipse/openj9/blob/master/runtime/compiler/runtime/SignalHandler.c).

- How to handle errors

It's not clear to me that we can reliably signal-protect the stack walk in the signal handler.

- Where is the function exported

Seem likely from the jvm library, but need to confirm.

**Comment by DanHeidinga** [comment]
From a recent slack discussion, this api is required to support Intellij's built-in profiler.

**Comment by planetf1** [comment]
It was almost a remark in passing on slack .. 
On our open source project we were looking at what java profiling tool to use. Whilst a proprietary tool had been mentioned, it was async-profiler that matched the open requirement. We found this was the tool used within intellij, but that it was dependent on hotspot APIs. All our devs currently AFAIK are using hotspot, but it would be good to support OpenJ9 too.

**Comment by DanHeidinga** [comment]
To make jit stack frames walkable, ie as we do in the current signalhandler, we call `jitPushResolveFrame` - https://github.com/eclipse/openj9/blob/master/runtime/compiler/runtime/SignalHandler.c#L398
- which is implemented  in https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/runtime/util/jitresolveframe.c#L39

This is a generic resolve frame so we can use the stackwalker to walk the stack.

**Comment by ninja-** [comment]
I would love to have this supported

**Comment by bmarwell** [comment]
This renders JetBrains IntelliJ methods unusuable: https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-245020

**Comment by gacholio** [comment]
A few issues we'll need to think about:

- variable frame platforms

x86-32 platforms are not "fixed frame", i.e. they push outgoing arguments one at a time. If we hit the interrupt during the pushes, there's currently no way to determine what has been pushed. We can either not support this feature on these platforms, or we'll need to somehow record the push count in the metadata for every PC range.

- JIT metadata updates

The outer metadata table is locked by VM access (only updated with exclusive). There's no guarantee that the table won't be mid-update when the interrupt occurs, so we'll need to handle this.

**Comment by ninja-** [comment]
> variable frame platforms

Does that include x64 as well?

> The outer metadata table is locked by VM access (only updated with exclusive). There's no guarantee that the table won't be mid-update when the interrupt occurs, so we'll need to handle this.

I think using mutexes could kill the whole point of async call trace fetch, would it? I may be wrong.
Maybe what we could do is make sure the whole metadata change gets memory visibility at once so no garbage could be read mid-update...

**Comment by gacholio** [comment]
// This function must only be called when JVM/TI
// CLASS_LOAD events have been enabled since agent startup. The enabled
// event will cause the jmethodIDs to be allocated at class load time.
// The jmethodIDs cannot be allocated in a signal handler because locks
// cannot be grabbed in a signal handler safely.

We don't currently do this (as it appears nowhere in any specification), but easily can. The code for getting jmethodIDs is currently using a lock, which will need to be removed for the pre-populated case.

**Comment by 0xdaryl** [comment]
> x86-32 platforms are not "fixed frame", i.e. they push outgoing arguments one at a time. If we hit the interrupt during the pushes, there's currently no way to determine what has been pushed. We can either not support this feature on these platforms, or we'll need to somehow record the push count in the metadata for every PC range.

We used to implement some form of this on IA32 where we would keep track of the "extra" pushes on the stack in some contexts.  We encoded the number of extra pushes in 8 bits of the GC map at that point.  I don't know if the VM relies on this mechanism any more.  However, I think some support for this still lives in the JIT and if it needs to be re-purposed/resurrected I think it can be.  The one difference would be that each PUSH would require a map reflecting the stack adjustment at that point.

**Comment by gacholio** [comment]
At the start (and possibly forever), we will only be supporting Linux AMD64.

I'm also signal protecting the stack walk, so if we were to hit the push case, we would just lose that sample.

**Comment by gacholio** [comment]
Is there a trivial profiler somewhere I can run to test the implementation (preferably for Java 8)?

**Comment by ninja-** [comment]
https://github.com/jvm-profiling-tools/async-profiler

**Comment by gacholio** [comment]
Initial implementation is here: https://github.com/gacholio/openj9/tree/agct

Note this implements only AsyncGetCallTrace, not any of the other HotSpot internals that the above profiler requires.

@tajila Can you get one of the interested parties to try a build from this branch?

**Comment by tajila** [comment]
@gacholio Ill give it a try

**Comment by gacholio** [comment]
Closing this as ASGCT has been verified as working. The async profiler requires many more hotspot internals, so we will probably never support it as-is.
