### ISSUE TITLE
which jdk should i used 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5695]
Hi,
i use docker , there are openjkd8,  oraclejdk8, oepnj9 
which jdk should i use ?

**Comment by pshipton** [comment]
Oracle java, and OpenJDK + Hotspot or OpenJDK + OpenJ9 have different licenses.

Oracle: https://www.java.com/en/download/faq/distribution.xml
For OpenJDK, see https://adoptopenjdk.net/about.html

OpenJDK + Hotspot is most compatible with Oracle, but OpenJ9 has some performance advantages. There is some migration information https://adoptopenjdk.net/migration.html

OpenJ9 advantages: https://www.eclipse.org/openj9/oj9_performance.html

**Comment by 15838028035** [comment]
Okay! Thanks for replay!   I use docker, I want to  know which jdk use memory lower and speed is good , how to test my idea?

发自我的 iPhone

**Comment by DanHeidinga** [comment]
Start by pulling the OpenJ9 docker images using a command like:
```
docker pull adoptopenjdk/openjdk8-openj9
```
or basing your docker file off it:
```
FROM adoptopenjdk/openjdk8-openj9:latest
```
and then testing your application to determine the footprint / performance meets your needs.

The easiest way to test the footprint is to use a command like monitor the containers memory usage

**Comment by 15838028035** [comment]
Okay! Thanks! 

发自我的 iPhone

**Comment by 15838028035** [comment]
Okay! Thanks, I find alpine-slim  image, is it can used for production

发自我的 iPhone

**Comment by pshipton** [comment]
> I find alpine-slim  image, is it can used for production

yes
