### ISSUE TITLE
Test master build for build breaks on all platforms before jitaas merge

### ISSUE THREAD

**Issue by raguks** [eclipse/openj9#5701]
We have to validate mac support for jitaas if we decide not to support as yet we need to make sure our master build on all platform build properly when jitaas goes in. @mpirvu @ymanton

**Comment by mpirvu** [comment]
I am closing this issue since JITServer code is already merged into master branch.
We are not supporting JITServer for mac at the moment and mac builds will not include any of the JITServer code.
