### ISSUE TITLE
Locale.getDefault differs between hotspot and openj9, suspect openj9's output is malformed, *breaks ojdbc*

### ISSUE THREAD

**Issue by rubin55** [eclipse/openj9#5705]
I am running OpenJ9 faithfully and the other day I "randomly" ran into issues when in relation to Locale settings on macOS. I didn't have these issues with Hotspot. To illustrate:
```
import java.util.Locale;
public class Hello {
    public static void main(String[] args){
        System.out.println(Locale.getDefault());
    }
}
```

Compiled the above and ran with both hotspot and openj9:
```
[rubin@kuro Desktop]$ jdk8u212-b03-hotspot/Contents/Home/bin/java Hello
en_NL
[rubin@kuro Desktop]$ jdk8u212-b03-openj9/Contents/Home/bin/java Hello
utf_US
```

It seems to me that utf_US is not a valid Locale setting. Things like the Oracle JDBC driver cry foul and refuse to operate at least. I'm not sure what hotspot is doing, but en_NL is a valid Locale setting so I don't notice any weirdness when using that.

**Comment by rubin55** [comment]
I have two example outputs from  Locale.getDefault that might be helpful.

When started from app icon:
```
{
  "a": {
    "script": "",
    "displayCountry": "United States",
    "displayVariant": "",
    "unicodeLocaleKeys": [
    ],
    "displayName": "English (United States)",
    "country": "US",
    "unicodeLocaleAttributes": [
    ],
    "displayLanguage": "English",
    "ISO3Language": "eng",
    "variant": "",
    "ISO3Country": "USA",
    "extensionKeys": [
    ],
    "displayScript": "",
    "language": "en"
  }
}
```

When started from command line:
```
{
  "a": {
    "script": "",
    "displayCountry": "United States",
    "displayVariant": "",
    "unicodeLocaleKeys": [
    ],
    "displayName": "utf (United States)",
    "country": "US",
    "unicodeLocaleAttributes": [
    ],
    "displayLanguage": "utf",
    "ISO3Language": "utf",
    "variant": "",
    "ISO3Country": "USA",
    "extensionKeys": [
    ],
    "displayScript": "",
    "language": "utf"
  }
}
```

**Comment by rubin55** [comment]
More notes: I notice that on macOS, the `env` of a command started from the dock contains:
```
LANG=en_US
LC_ALL=
LC_MESSAGES=
```

When I start Apple Terminal, my env only contains:
```
LC_CTYPE=UTF-8
```

That LC_CTYPE variable only gets set when you turn on `Preferences -> Advanced Tab -> Set locale environment variables on startup`. It's also the only one that gets set, no other LC_* or LANG. When you turn that option off, LC_CTYPE is not set, as are none of the other LC_* or LANG variables. 

Although this issue is also definitely an issue in OpenJ9 as compared to hotspot's handling of the case, it seems to me to be a bug in Apple Terminal.app also (i.e, when enabling `Set locale environment variables on startup`, not only LC_CTYPE should be set, but also at least LANG).

**Comment by mikezhang1234567890** [comment]
OpenJ9 sets the default locale based on the current environment, using LC_ALL, then LC_CTYPE, then LANG. We assume that LC_TYPE begins with a language code, and handle the special cases of `C` and `POSIX`. We forgot to handle the case when LC_CTYPE is `UTF-8` since that seems to be unique to OSX.  I will make a PR to handle the `UTF-8` case, though I don't know if there are other valid values for LC_CTYPE that don't start with a language code.

**Comment by pshipton** [comment]
@mikezhang1234567890 can this be close now that https://github.com/eclipse/omr/pull/3856 is merged?

**Comment by mikezhang1234567890** [comment]
Yes, that PR should fix the issue causing `utf-US` to be emitted as a locale.
