### ISSUE TITLE
which linxu do you used ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5724]
HI, which linxu do you used ?

there are centos, debian  linux system.

**Comment by pshipton** [comment]
> there are centos, debian linux system.

Both should work. Adopt runs tests on a number of systems. The platform support is https://adoptopenjdk.net/supported_platforms.html
Debian isn't mentioned, but I believe it works. `Any other Linux distributions that have a minimum glibc version 2.12 on x86 or version glibc version 2.17 on other architectures are expected to function without problems.`

**Comment by 15838028035** [comment]
Okay! Thanks!

发自我的 iPhone

**Comment by DanHeidinga** [comment]
Closing as an answer has been provided
