### ISSUE TITLE
docker use openj9 problem

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5725]
Hi, there'are some old docker images containers use openjkd , not openj9 ,

how should i replace it ?

i want to use docker  not like docker file way , is there othere way ?

**Comment by ashu-mehra** [comment]
I am not sure if I understood your question correctly.
If you are asking about replacing openjdk with openj9 in an existing docker image, I don't think it is possible to do. But you can always [bind mount](https://docs.docker.com/storage/bind-mounts/) openj9 from the host into docker container, and probably update entry point of the image to use openj9.

**Comment by 15838028035** [comment]
okay! Which docker command  should I used? Is there a demo ?

发自我的 iPhone

**Comment by DanHeidinga** [comment]
The AdoptOpenJDK project makes OpenJ9 docker images available: https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9  In addition to the ones for Java 8, there are also docker files for Java 11 & 12.  These come various sizes (jdk, jre, alpine, etc)

For example, the Java 8 image can be pulled using this command:
```
docker pull adoptopenjdk/openjdk8-openj9
```

You can also base your docker file on the on the OpenJ9 version by setting the FROM line in your docker file:
```
FROM adoptopenjdk/openjdk8-openj9:latest
```

**Comment by 15838028035** [comment]
hi, i  have use docker bind command ,but docker status memory not lower
