### ISSUE TITLE
docker openjdk8-openj9:apline-slim  bind mount memory problem 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5738]
Hi,  i have a docker image named sonartype/nexus3, i want to use openjdk8-openj9 replace docker container openjdk, i use commnad like this:

docker run --name nexus3  \
                  --mount bype ="bind" source=$PWD/oepndjk8-openj8 target="/usr/lib/jvm/openjdk8" \
-p 8081:8081 \

sonatype/nexus \

nexus i run    docker ps -a  -s 

i see nexus3 memory use about 500M,  not lower, this is the same with openjdk8

what should i do ?
i want to use openjdk8-openj9 to use lowere memory

**Comment by DanHeidinga** [comment]
fyi @ashu-mehra

**Comment by ashu-mehra** [comment]
@15838028035  Did you use `docker ps -a -s` to monitor memory usage? I am afraid that is not the right way.
You can use `docker stats <container id>` and monitor `MEM USAGE` to determine physical memory usage of the container.

I ran `sonatype/nexus3` image from https://hub.docker.com/r/sonatype/nexus3/.
With OpenJDK8 (with Hotspot JVM), I see `docker stats` reports around 1.6G usage.
With OpenJDK8-OpenJ9, `docker stats` reports around 1.3G usage.
So there is atleast 300M less memory footprint with OpenJ9.

Hope this helps!

**Comment by 15838028035** [comment]
Okay! Thanks! If I only use java, how can I see the memory on Linux ? Top ?

发自我的 iPhone

**Comment by ashu-mehra** [comment]
Yes, on Linux you can monitor using `top` or `ps`. In the `top` output `RES` field indicates physical memory size.

**Comment by 15838028035** [comment]
Okay ! Thanks 

发自我的 iPhone
