### ISSUE TITLE
have you used sonar checked your code ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5749]
Hi, have you use sonare checked your code ?

i use docker , run docker jenkins containers,  sonaqube containers

i want do use sonarqube memory more lower

have you use used it  ?

**Comment by ashu-mehra** [comment]
> Hi, have you use sonare checked your code ?

I don't think we have analyzed OpenJ9 code base with sonarqube if that is what you are asking, nor we have run sonarqube using OpenJ9 (as per my knowledge).

**Comment by 15838028035** [comment]
Yes! Run sonarqube with openj9

发自我的 iPhone

**Comment by 15838028035** [comment]
Yes! Use sonarqube !

发自我的 iPhone

**Comment by DanHeidinga** [comment]
I haven't tried running sonarqube on OpenJ9 and I don't expect there to be any issues doing so.  If that's something you're going to be doing, we'd love to hear some feedback on how well it works for you.

**Comment by 15838028035** [comment]
okay ！ thanks
