### ISSUE TITLE
is there a eclipse.ini file used openjkd8-openj9 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5750]
HI,
is there a eclipse.ini file used openjkd8-openj9   ?

on windows10, i config openjkd8-openj9 as JAVA_HOME,

config eclipse.ini file add vm args 

but start failure ,
is there a eclipse.ini file used openjkd8-openj9   ?

**Comment by ashu-mehra** [comment]
As to my knowledge, Eclipse works fine with OpenJ9.
Which version of Eclipse did you try with?
Can you tell us more about the error message? Is it an exception or core dump or something else?

**Comment by 15838028035** [comment]
Only a alert msg box , I don’t remember it !
 

Thanks 

发自我的 iPhone

**Comment by pshipton** [comment]
I can confirm the eclipse.ini file is used when running with OpenJ9. This is a feature of Eclipse and unrelated to which JVM is used. Likely there is something wrong with the arguments specified in the eclipse.ini file. Please provide the arguments specified to get feedback about their compatibility with OpenJ9.

**Comment by 15838028035** [comment]
hi, i have config openjdk8-openj9 as java_home 
this eclipse.ini config file:

-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.300.v20150602-1417
-product
org.eclipse.epp.package.jee.product
--launcher.defaultAction
openFile
--launcher.XXMaxPermSize
256M
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
256m
--launcher.defaultAction
openFile
--launcher.appendVmargs


-vmargs
-Dosgi.requiredJavaVersion=1.8
-server
-Xms2048m
-Xmx2048m
-Xmn768m
-XX:MataspaceSize=2014M
-XX:SurvivorRatio=8 
-XX:+UseParNewGC
-XX:+UseConcMarkSweepGC
-XX:ParallelGCThreads=8
-XX:CompileThreshold=100
-XX:CMSInitiatingOccupancyFraction=80
-XX:+DisableExplicitGC
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-Xverify:none
-verbose:gc
-Xloggc:gc.log
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails

i install a eclipse start showtime plugin ,
![图片](https://user-images.githubusercontent.com/12193885/57740692-ae967980-76eb-11e9-9740-01d8d283e112.png)

start time is long than openjk8

**Comment by DanHeidinga** [comment]
Can you add `-Xshareclasses -Xtune:virtualized -Xscmx60m` to the eclipse ini file?  These options enable OpenJ9's sharedclasses cache which enables AOT code to help improve startup speed,

**Comment by 15838028035** [comment]
thanks !
