### ISSUE TITLE
OpenJ9 - "Could not create the Java Virtual Machine" when some special characters are on the command line

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#5751]
Reported at Adopt: https://github.com/AdoptOpenJDK/openjdk-build/issues/1080

**Comment by DanHeidinga** [comment]
@pdbain-ibm can you take a look at this?

**Comment by DanHeidinga** [comment]
FYI @bobswift

**Comment by pdbain-ibm** [comment]
> @pdbain-ibm can you take a look at this?

Will do.

**Comment by DanHeidinga** [comment]
AdoptOpenJDK/openjdk-build#1080 was closed as we're unable to reproduce the issue.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/issues/1080#issuecomment-542875476

**Comment by JasonFengJ9** [comment]
> Try running jar with unicode in path on Windows and you'll get that error.
I use jdk8u222-b10_openj9-0.15.1.

I think it probably is same issue as https://github.com/eclipse/openj9/issues/6722, will pick it up.

**Comment by pshipton** [comment]
Assuming this is fixed.
