### ISSUE TITLE
win2012r2-x86-5 not a git repository

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5752]
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_Release/5
win2012r2-x86-5 disabled
```
Running on win2012r2-x86-5 in C:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Release
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 6 hr 0 min
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Get Source)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] fileExists
[Pipeline] sh
09:54:18  + git clean -ffxd
09:54:18  fatal: not a git repository (or any parent up to mount point /cygdrive)
09:54:18  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
Issue is the previous [build](https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_Release/4/console) left the WS in a bad state. We don't use the `git clean` logic anymore so we should change it to something like `if workspace is not empty { cleanWs() }`

The workspace was cleaned up properly by the build you linked so I will re-enable the machine. I also don't see any issue with the workspace@tmp dir as the failed build#4 points to.
