### ISSUE TITLE
about jenkins problem

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5763]
hi ,i see the proeject use jenkins  as ci build.

is  the jenkins use docker run ?

**Comment by pshipton** [comment]
No it doesn't. However there are some docker files for the build and test environment here https://github.com/eclipse/openj9/tree/master/buildenv/jenkins/docker-slaves

**Comment by AdamBrousseau** [comment]
It doesn't currently. We are prototyping using the containers Pete linked above on a private Jenkins server in the hopes that we will use them for production soon.

**Comment by 15838028035** [comment]
Okay! Thanks!

发自我的 iPhone
