### ISSUE TITLE
Add ThreadMXBean.dumpAllThreads(..., int maxDepth) and getThreadInfo(..., int maxDepth) APIs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#577]
ThreadMXBean.dumpAllThreads(..., int maxDepth) and getThreadInfo(..., int maxDepth) need to be implemented for Java 18.3 / 10. Added in +31.

**Comment by pdbain-ibm** [comment]
Per discussion with pshipton, will investigate

**Comment by pdbain-ibm** [comment]
The code is implemented and manually tested.

Working on the testcase, but the test repository will likely need some rework.  Discussing this
with @llxia and @smlambert.

**Comment by pdbain-ibm** [comment]
I have a testcase written.  Blocked waiting for https://github.com/eclipse/openj9/pull/1247.

**Comment by pshipton** [comment]
Fixed by #1471
