### ISSUE TITLE
Add Ubuntu18 Dockerfiles for JDK11+

### ISSUE THREAD

**Issue by ShishirH** [eclipse/openj9#5781]
Currently there are no Ubuntu18 Dockerfiles for JDK11 and 12 at `openj9/buildenv/docker/`.

Earlier, there was an OpenJDK issue that was preventing the Dockerfiles from building, but that has been [resolved for JDK12](https://bugs.openjdk.java.net/browse/JDK-8202794) and [backported for JDK11](https://bugs.openjdk.java.net/browse/JDK-8221919).

**Comment by ShishirH** [comment]
Due to the large number of Dockerfiles present, I was thinking that there could be a script that could take in the OS, the platform and the JDK version, and generate the Dockerfile based on that. Then you could probably replace all the Dockerfiles with the script.

Any thoughts about this @keithc-ca ?

**Comment by keithc-ca** [comment]
There are a number of Dockerfiles for Ubuntu18, for jdk8 (e.g [1]), jdk9 and jdk10, but variants have not been created for jdk11 or newer. These are not to be confused by the ones used with Jenkins (e.g. [2]) which don't appear to include all the tools necessary to build a jdk.

I like your idea to replace the (incomplete) collection of Dockerfiles with some scripting that should make it easier to support new jdk versions and to remove much of the redundancy among those files. I suggest you have a look at [3] for some ideas.

[1] https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk8/x86_64/ubuntu18/Dockerfile
[2] https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/docker-slaves/x86/ubuntu18/Dockerfile
[3] https://github.com/ibmruntimes/ci.docker

**Comment by fjeremic** [comment]
@keithc-ca I thought we were going to deprecate [1] in favor of [2] since the latter has both build and test dependencies setup? I do recall us talking about that in another issue.

**Comment by keithc-ca** [comment]
I don't see freemarker in [2], for example, and so it can't be used (directly) to build.
We did have a discussion about _adding_ test dependencies to [1] a while back, but nothing has been done in that direction.

**Comment by pshipton** [comment]
Re [2], some platforms are designated as build and test, and some are test only. For example, on x86 the build platform is centos6. In order to deprecate [1], we'd have to update build capabilities for [2].

@AdamBrousseau @jdekonin fyi

**Comment by fjeremic** [comment]
If there are dependencies missing then that is likely a bug. According to #5276:

> The Dockerfile's advertised in the OpenJ9 documentation are only available for Ubuntu. They also only handle building OpenJ9 and not testing. There is another set of Dockerfiles's in /buildenv/jenkins/docker-slaves@master which are not well known. These files add support for additional OSes and provide images suitable for running tests as well as building OpenJ9. They are also regularly maintained. This issue is opened to discuss documenting these Dockerfile's.

Looking at the README:
https://github.com/eclipse/openj9/tree/master/buildenv/jenkins/docker-slaves

It seems only S390 is configured for build and test currently. I suspect we just haven't gotten to the other platforms yet. Looking at the history it seems @AdamBrousseau @samuel-rubin and @cwesMills were the people working on that.

**Comment by AdamBrousseau** [comment]
The Docker Files in [2] (docker-slaves) are setup for build (& test) only on the OS we build on (lowest glibc). The others are setup for test-only. There is no plan or intention to add build dependencies to OSs we don't build on in the farm.

**Comment by keithc-ca** [comment]
I've started writing a shell script that will generate a Dockerfile for a specified distribution (on the host architecture). Then it should be simpler to add new distribution versions or deal with additional requirements.

**Comment by ashu-mehra** [comment]
@keithc-ca last time I checked with @ShishirH, he has written some stuff for automating Dockerfile generation. @ShishirH, do you mind sharing the status of your work here and probably opening a PR if it is something Keith can start reviewing?

**Comment by ShishirH** [comment]
@ashu-mehra Nothing concrete to show as of now. I was waiting for the discussions on https://github.com/eclipse/openj9/issues/5276 to conclude, to know whats the plan for the Dockerfiles, before I could start working on them.

**Comment by pshipton** [comment]
> I've started writing a shell script that will generate a Dockerfile for a specified distribution

@keithc-ca is there any outlook (which Milestone) for when this work might be completed?
