### ISSUE TITLE
is should be a email notice for jenkins ci build 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5782]
hi, i see the project use jenkins,  use jenkins pipline,
when build failure,  has no email notice,  

is there a demo ?

**Comment by pshipton** [comment]
jenkins failures are posted to the OpenJ9 Slack in the #jenkins channel (https://openj9.slack.com/messages/C8QU16TDW). You might be able to get email from Slack.

To join the OpenJ9 Slack, see https://github.com/eclipse/openj9/blob/master/README.md or https://www.eclipse.org/openj9/

**Comment by DanHeidinga** [comment]
The OpenJ9 jenkins is to support our build and test infrastructure such as pull request builds, nightly builds, etc.  

The place to get OpenJ9 binaries is from AdoptOpenJDK.  
For Java 8, this would be a https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9
