### ISSUE TITLE
how the openj9.svg do you generte it ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5807]
hi , from readme.md  , i see openj9.svg 

how the openj9.svg do you generate it ?

**Comment by pshipton** [comment]
I don't recall what program was used, maybe Dan will. Googling, Inkscape can create .svg files.

**Comment by DanHeidinga** [comment]
Those are the original OpenJ9 logos Ron created or had someone create.

Sorry, not sure what program was used to do it.

**Comment by 15838028035** [comment]
close
