### ISSUE TITLE
jdk1.8 run gcc4.92 problem 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5851]
Hi, i use centos 7
 have install gcc 4.9.2

config java_HOME jdk1.8

run ./java -version 

no  message print out ,  jdk1.8 can run gcc4.9.2 ?

**Comment by pshipton** [comment]
Did you build OpenJ9 yourself? gcc isn't required at runtime if you download a binary from AdoptOpenJDK.net

If you are building yourself, the minimum gcc required is 7.3 https://www.eclipse.org/openj9/docs/openj9_support/

**Comment by 15838028035** [comment]
no,     i only want to run java on centons7 ,  i install gcc4.9.2 

about 14 days , i find  run ./java --version   no message print

**Comment by 15838028035** [comment]
![图片](https://user-images.githubusercontent.com/12193885/58248853-d642ad00-7d8f-11e9-99df-3235a59130a2.png)


no message print , what should i do next ?

**Comment by pshipton** [comment]
Try
`java -verbose:init`
or
`java -Xtrace:iprint=j9vm`

**Comment by pshipton** [comment]
What exactly did you download? I can try it on CentOS 7 myself.

**Comment by 15838028035** [comment]
okay ! thanks !

**Comment by 15838028035** [comment]
on my one host ,  i install a gcc 4.9.2 ,  
run java --version  no message print

**Comment by 15838028035** [comment]
![图片](https://user-images.githubusercontent.com/12193885/58249734-3cc8ca80-7d92-11e9-9fca-2c4dd34899ce.png)

**Comment by pshipton** [comment]
What is the result of the following?
`uname -a`
`ldd bin/java`

**Comment by 15838028035** [comment]
libjli.so => not found
  is this ?

**Comment by 15838028035** [comment]
![图片](https://user-images.githubusercontent.com/12193885/58250692-97632600-7d94-11e9-8eef-bbdf5359de89.png)

**Comment by pshipton** [comment]
it should be found in `lib/amd64/jli/libjli.so` when java is in `bin`

**Comment by pshipton** [comment]
I don't think the java you are running is the OpenJ9 version.

**Comment by 15838028035** [comment]
i run openjkd8 , not openj9

**Comment by 15838028035** [comment]
root user run okey 

a simple user user1 run java no message print

**Comment by DanHeidinga** [comment]
If there are issues running OpenJ9 we can help resolve them.  We can't help resolve issues with Hotspot based builds.

**Comment by 15838028035** [comment]
okat! Thanks


发自我的 iPhone

**Comment by DanHeidinga** [comment]
Thanks.  Closing for now but please comment / reopen if this occurs on openj9
