### ISSUE TITLE
java object question ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5870]
Hi , i want to use lower memory ,  in a java object for class maybe like this:

public class TestA {

private String attrA;

private Double attrB;

private Long attrC;

//get set method ....
}

should i use wrapper type or origin type ?

public class TestA {
private String attrA;

private double attrB;

private long attrC;
//get set method ....
}

which should i use ?
how can i test the class use memory ?

**Comment by pshipton** [comment]
You can determine how much memory is used by the instance of a class via java.lang.instrument.Instrumentation.getObjectSize(). You need to write a java agent to use this, but the details of how to do this are in the java.lang.instrument package documentation. See https://github.com/eclipse/openj9/issues/5739#issuecomment-495409169 for a simple java agent example.

**Comment by 15838028035** [comment]
Okay! Thanks

发自我的 iPhone

**Comment by pdbain-ibm** [comment]
You can also force a core dump and check the object size using jdmpview's `objectsizeinfo` command:

 `objectsizeinfo            [-a] [class name]    Print information about object fields and size of the objects, including unused space`

 on the class of interest, e.g.:
```
$ java  -Xdump:system:events=vmstop HelloWorld
$ jdmpview -core core.blahblahblah.dmp
> !objectsizeinfo toe/foo/Bar
```

!j9help will give a list of commands.
