### ISSUE TITLE
Failed to connect to local process using jconsole 

### ISSUE THREAD

**Issue by HirokiYoshinaga** [eclipse/openj9#5872]
Java -version output
--------------------
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux amd64-64-Bit Compressed References 20181115_18 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dcd
OMR      - ea548a66
JCL      - d4455071ce based on jdk-11.0.1+13)

Summary of problem
------------------
JConsole fails to connect to local process using jconsole.
I created target runtime with following commands.

`
$jlink -p jmods --compress=2 --add-modules jdk.management.agent --output NameOfDir
`

When I execute an application using the runtime and tried to monitor it, JConsole fails to connect.
So I execute JConsole with "-debug" option, and following exception was displayed.

```
com.sun.tools.attach.AttachOperationFailedException: AttachOperationFailedException from target: ATTACH_ERR AttachOperationFailedException in startLocalManagementAgent:  startLocalManagementAgent error starting agent:class com.ibm.tools.attach.target.IbmAttachOperationFailedException startLocalManagementAgent cannot access startLocalManagementAgent
	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:335)
	at jdk.attach/com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.startLocalManagementAgent(OpenJ9VirtualMachine.java:525)
	at jdk.jconsole/sun.tools.jconsole.LocalVirtualMachine.loadManagementAgent(LocalVirtualMachine.java:237)
	at jdk.jconsole/sun.tools.jconsole.LocalVirtualMachine.startManagementAgent(LocalVirtualMachine.java:96)
	at jdk.jconsole/sun.tools.jconsole.ProxyClient.tryConnect(ProxyClient.java:333)
	at jdk.jconsole/sun.tools.jconsole.ProxyClient.connect(ProxyClient.java:313)
	at jdk.jconsole/sun.tools.jconsole.VMPanel$2.run(VMPanel.java:296)
```

Although I also tried with OpenJDK, this issue did not occurred.
Then this problem is specific to OpenJ9.

**Comment by pshipton** [comment]
@pdbain-ibm can you please take a look.

**Comment by pdbain-ibm** [comment]
Attachment.java uses reflection to get the `jdk.internal.agent.Agent.start*ManagementAgent()` methods. These are in the `jdk.management.agent` module, but the `jlink`ed JDK cannot load it.
Running the following:
```
import java.security.AccessController;
import java.security.PrivilegedAction;

public class testconnector {
	public static void main(String[] args) {
		AccessController.doPrivileged((PrivilegedAction<Object>) () -> {
			Class<?> agentClass;
			try {
				agentClass = Class.forName("jdk.internal.agent.Agent"); //$NON-NLS-1$
				System.err.println("Loaded " + agentClass);
			} catch (ClassNotFoundException | SecurityException e) {
				System.err.println("Exception: "+e);
			}
			return null;
		});
	}
}
```
on a full JDK produces:
`Loaded class jdk.internal.agent.Agent`

On the `jlink`ed JVM we get:
`Exception: java.lang.ClassNotFoundException: jdk.internal.agent.Agent`

This is a modularity/classloading issue.

**Comment by pshipton** [comment]
@pdbain-ibm Run your test on the jlinked image with `--add-modules jdk.management.agent` and then it works. Although the jdk.management.agent is available, it doesn't get loaded by default. 
This behavior is the same between Hotspot and OpenJ9 builds. More investigation required.

**Comment by pshipton** [comment]
You can run `java --show-module-resolution -version` to see what gets resolved by default. I expect Attach needs to explicitly cause jdk.management.agent to be loaded when necessary.

**Comment by pdbain-ibm** [comment]
@HirokiYoshinaga  I believe I have fixed the issue you report.
Please test this JDK:
 https://drive.google.com/open?id=1VP2m2EqoaUauAK-9B2Sm606U7xRLJiRV
and tell me if it solves your problem.

If you have questions, please contact me on Slack at openj9.slack.com; you can join the channel via the `Request an invite` link on "https://www.eclipse.org/openj9/index.html".

**Comment by HirokiYoshinaga** [comment]
@pdbain-ibm Thank you for your fix!
I confirmed JConsole succeeded to connect to local process with the provided JDK.
