### ISSUE TITLE
docker question 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5886]
Hi, my docker file like this:
FROM adoptopenjdk/openjdk8-openj9:alpine-slim
VOLUME /tmp
ADD upm-0.0.1-SNAPSHOT.jar upm-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","upm-0.0.1-SNAPSHOT.jar"]

docker exec -ti upm bash

bash colud not find ,how can i into the upm container , i have start the container upm 

could you help me ?

**Comment by ShishirH** [comment]
Run `docker ps` and check the container ID. Should be a mix of alphabets and numbers, like `df084e8ff94a`.

Then run `docker exec -it <container_id> bash`

**Comment by 15838028035** [comment]
My container id is openjkd8-openj9, I have fixed it! 

发自我的 iPhone
