### ISSUE TITLE
possible??? java gpu rendering

### ISSUE THREAD

**Issue by annopnod** [eclipse/openj9#5889]
possible??? java gpu rendering
-BufferedImage
-paintComponent

**Comment by pshipton** [comment]
We'll need more details about the problem in order to respond to this.

**Comment by annopnod** [comment]
i view JOGL is large size file.
pure java 3d engine Platform Independent.

**Comment by pshipton** [comment]
I still don't understand what the problem is.

**Comment by 0xdaryl** [comment]
Are you simply asking whether the `BufferedImage` class and `paintComponent` method could leverage a GPU if one were available on the system running your Java application?

**Comment by annopnod** [comment]
> Are you simply asking whether the `BufferedImage` class and `paintComponent` method could leverage a GPU if one were available on the system running your Java application?

yes.

**Comment by pshipton** [comment]
I don't think OpenJ9 is the correct place to discuss this. OpenJ9 is a replacement virtual machine to Hotspot, and unrelated the awt implementation. A Google search turned up https://openjdk.java.net/projects/sumatra/

**Comment by pshipton** [comment]
https://openjfx.io/ might be of interest.
