### ISSUE TITLE
j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest fails on openj9 openjdk-jdk8

### ISSUE THREAD

**Issue by vsebe** [eclipse/openj9#590]
J9vmTest_2, J9vmTest_4,	J9vmTest_5 j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest failures:

J9vmTest_2:
+++ j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump -Xms64m -Xmx64m  -Xtrace:print={j9bcu.192-194}  -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest 

*** Test FAILED *** (j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest)

J9vmTest_4:
+++ j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m  -Xtrace:print={j9bcu.192-194}  -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest 

*** Test FAILED *** (j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest)

J9vmTest_5:
+++ j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump -Xms64m -Xmx64m  -Xtrace:print={j9bcu.192-194}  -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest 

*** Test FAILED *** (j9vm.test.romclasscreation.OrphanROMHashTableDeletionTest)

**Comment by vsebe** [comment]
attn @llxia

**Comment by vsebe** [comment]
Tested openj9 openjdk-jdk8 on linux_x86-64_cmprssptrs.
j2sdk-image/jre/bin/java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2017_11_15_12_33-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171115_370249 (JIT enabled, AOT enabled)
OpenJ9 - 10706ea
OMR - 99498e1
OpenJDK - e9942fd based on jdk8u152-b03)

**Comment by pshipton** [comment]
Suspect same issue as #595, J9TraceFormat.dat is in the wrong place.

**Comment by pshipton** [comment]
Test is passing now.
