### ISSUE TITLE
Replace uses of FrontEnd::getObjectAlignmentInBytes with ObjectModel::objectAlignmentInBytes

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#5904]
The `FrontEnd::getObjectAlignmentInBytes()` API is deprecated.  Replace all references with `TR::Compiler->om.objectAlignmentInBytes()` instead.  Delete the FrontEnd implementation when done.

The OpenJ9 implementation in the ObjectModel class is identical to the FrontEnd implementation.

Simply grep through the compiler source for `getObjectAlignmentInBytes` to find the references to change.

Create a PR in the OMR project to remove the FrontEnd::getObjectAlignmentInBytes() when done.

**Comment by Eoghan-K** [comment]
Hey can I take a look at this?
