### ISSUE TITLE
jenkins pipline file problem 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#5907]
HI ,
 i use jenkins pipline,  there two files ,
one file named jenkins_pipline.groovy  maybe like this:

// 生命全局工具变量
def GLOBAL_TOOL_JDK_ID   = 'JAVA_HOME'
def GLOBAL_TOOL_MAVEN_ID = 'MAVEN_HOME'
properties([parameters([string(name: 'GIT_URL', defaultValue: ' git_URL_1', description: 'git仓库地址'),
                        string(name: 'GIT_BRANCH', defaultValue: 'master', description: 'git分支名称'),
                        string(name: 'GIT_CREDIT', defaultValue: '47e7e050-aa0c-42cd-a1af-500a3f07d5c1', description: 'git用户凭证')

            ])])

node {
    
    try{
    // 全局获取最新代码
    stage("获取最新代码") {
        // 限制15分钟内完成。
        timeout(time: 15, unit: 'MINUTES') {
             coCode()
        }
    }

    // 组件编译测试
    stage("SCA编译&&测试") {
        execMavenCommand(GLOBAL_TOOL_MAVEN_ID, "", "clean compile -Dmaven.test.skip=true")
    }
    
    // sonar
   stage("sonar代码扫描") {
         timeout(time: 15, unit: 'MINUTES') {
            execMavenCommand(GLOBAL_TOOL_MAVEN_ID, "", "sonar:sonar -Dsonar.host.url=http://192.168.96.89:9000 -X")
         }
    }

    stage("清理工程") {
        // 暂时不删除目录
        deleteDir()
        // 查看当前目录
        // sh 'ls -lah'
    }
    }  finally {
             
        }

}

def execMavenCommand(mvnTools, path, params) {
      init(mvnTools);
     def curPath = pwd();
      timeout(time: 15, unit: 'MINUTES') {
        sh "cd ${curPath}${path} && mvn ${params} -V -B -Duser.timezone=GMT+08"
    }
}
def init(mvnTools) {
       // coCode();
       addMvnEnv(mvnTools);
}

def addMvnEnv(t) {
    // 定义maven组件
    def mvnHome = tool t
    env.PATH = "${mvnHome}/bin:${env.PATH}"
}

def coCode() {

            
   checkout([
       $class: 'GitSCM', 
       branches: [[name: 'refs/heads/'+params.GIT_BRANCH]],
       doGenerateSubmoduleConfigurations: false, 
       extensions: [], 
       submoduleCfg: [], 
       userRemoteConfigs: [[credentialsId: params.GIT_CREDIT, 
       url: params.GIT_URL
       ]
       ]]
       )
}

def versionOfProject(path) {
    def matcher = readFile(path + '/pom.xml') =~ '<version>(.+)</version>'
    matcher ? matcher[0][1] : null
}

def artifactIdProject(path) {
    def matcher = readFile(path + '/pom.xml') =~ '<artifactId>(.+)</artifactId>'
    matcher ? matcher[0][1] : null
}

the second files may like this:

node {
    
    // 全局获取最新代码
    stage("获取最新代码") {
        // 限制15分钟内完成。
        timeout(time: 15, unit: 'MINUTES') {
            
             parameters([string(name: 'GIT_URL', defaultValue: 'http://192.168.96.89:3000/Model_Training/Audio_ModelDD.git', description: 'git仓库地址CC'),
                        string(name: 'GIT_BRANCH', defaultValue: 'masterCC', description: 'git分支名称A'),
                        string(name: 'GIT_CREDIT', defaultValue: '47e7e050-aa0c-42cd-a1af-500a3f07d5c1', description: 'git用户凭证DD')
            ])
            
                                    // i want to load this file with params , what sholud i do ?            
                load 'jenkins_pipline.groovy'

            
        }
    }

    }

**Comment by DanHeidinga** [comment]
I'm not clear on what your trying to do here.  Sorry, the OpenJ9 project can't provide support for Jenkins build pipelines.

**Comment by 15838028035** [comment]
okay ! thanks ! i have fixed it ,    used jenkins pipline params 

run jenknins jobs
