### ISSUE TITLE
j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest failure on openj9 open

### ISSUE THREAD

**Issue by vsebe** [eclipse/openj9#591]
**Running test J9vmTest_2 ...**

test with Mode351
{ export LIBPATH="/tmp/bld_370249/j2sdk-image/jre/bin/../lib/amd64/compressedrefs:/tmp/bld_370249/j2sdk-image/jre/bin/j9vm:"; 
"/tmp/bld_370249/j2sdk-image/jre/bin/java" -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs -Xdump -Xint 
-cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" 
j9vm.runner.Menu A -exe="/tmp/bld_370249/j2sdk-image/jre/bin/java -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs -Xdump" -version=SE80 -jar="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar" -xlist="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/j9vm.xml" 
-xids=all,linux_x86-64_cr; 
if [ $? -eq 0 ] ; then echo "J9vmTest_2""_PASSED"; else echo "J9vmTest_2""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
add excludes for [all]
add excludes for [linux_x86-64_cr]
DONE in 0 ms.
...
+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs -Xdump -Xms64m -Xmx64m -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31} -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)

**Running test J9vmTest_4 ...**

test with Mode551
{ export LIBPATH="/tmp/bld_370249/j2sdk-image/jre/bin/../lib/amd64/compressedrefs:/tmp/bld_370249/j2sdk-image/jre/bin/j9vm:"; 
"/tmp/bld_370249/j2sdk-image/jre/bin/java" -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced -Xdump -Xint 
-cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" 
j9vm.runner.Menu A -exe="/tmp/bld_370249/j2sdk-image/jre/bin/java -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced -Xdump" -version=SE80 -jar="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar" -xlist="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/j9vm.xml" 
-xids=all,linux_x86-64_cr; 
if [ $? -eq 0 ] ; then echo "J9vmTest_4""_PASSED"; else echo "J9vmTest_4""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
add excludes for [all]
add excludes for [linux_x86-64_cr]
DONE in 0 ms.

...

+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced -Xdump -Xms64m -Xmx64m -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31} -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)

**Running test J9vmTest_5 ...**

test with Mode610
{ export LIBPATH="/tmp/bld_370249/j2sdk-image/jre/bin/../lib/amd64/compressedrefs:/tmp/bld_370249/j2sdk-image/jre/bin/j9vm:"; 
"/tmp/bld_370249/j2sdk-image/jre/bin/java" -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xdump -Xint 
-cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" 
j9vm.runner.Menu A -exe="/tmp/bld_370249/j2sdk-image/jre/bin/java -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xdump" -version=SE80 -jar="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar" -xlist="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/j9vm.xml" 
-xids=all,linux_x86-64_cr; 
if [ $? -eq 0 ] ; then echo "J9vmTest_5""_PASSED"; else echo "J9vmTest_5""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
add excludes for [all]
add excludes for [linux_x86-64_cr]
DONE in 0 ms.
...
+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon -Xdump -Xms64m -Xmx64m -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31} -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)

Tested openj9 openjdk-jdk8 on linux_x86-64_cmprssptrs.
j2sdk-image/jre/bin/java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2017_11_15_12_33-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171115_370249 (JIT enabled, AOT enabled)
OpenJ9 - 10706ea
OMR - 99498e1
OpenJDK - e9942fd based on jdk8u152-b03)

**Comment by vsebe** [comment]
===============================================
Running test J9vmTest_2 ...
===============================================
test with Mode351
{ export LIBPATH="/tmp/bld_370249/j2sdk-image/jre/bin/../lib/amd64/compressedrefs:/tmp/bld_370249/j2sdk-image/jre/bin/j9vm:"; \
	"/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xint \
	-cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" \
	j9vm.runner.Menu A -exe="/tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump" -version=SE80 -jar="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar" -xlist="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/j9vm.xml" \
	-xids=all,linux_x86-64_cr; \
	if [ $? -eq 0 ] ; then echo "J9vmTest_2""_PASSED"; else echo "J9vmTest_2""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
  add excludes for [all]
  add excludes for [linux_x86-64_cr]
DONE in 0 ms.
 ...
+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs  -Xdump -Xms64m -Xmx64m  -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31}  -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest 

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)

===============================================
Running test J9vmTest_4 ...
===============================================
test with Mode551
{ export LIBPATH="/tmp/bld_370249/j2sdk-image/jre/bin/../lib/amd64/compressedrefs:/tmp/bld_370249/j2sdk-image/jre/bin/j9vm:"; \
	"/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xint \
	-cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" \
	j9vm.runner.Menu A -exe="/tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump" -version=SE80 -jar="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar" -xlist="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/j9vm.xml" \
	-xids=all,linux_x86-64_cr; \
	if [ $? -eq 0 ] ; then echo "J9vmTest_4""_PASSED"; else echo "J9vmTest_4""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
  add excludes for [all]
  add excludes for [linux_x86-64_cr]
DONE in 0 ms.

...

+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump -Xms64m -Xmx64m  -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31}  -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest 

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)

===============================================
Running test J9vmTest_5 ...
===============================================
test with Mode610
{ export LIBPATH="/tmp/bld_370249/j2sdk-image/jre/bin/../lib/amd64/compressedrefs:/tmp/bld_370249/j2sdk-image/jre/bin/j9vm:"; \
	"/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump -Xint \
	-cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" \
	j9vm.runner.Menu A -exe="/tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump" -version=SE80 -jar="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar" -xlist="/tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/j9vm.xml" \
	-xids=all,linux_x86-64_cr; \
	if [ $? -eq 0 ] ; then echo "J9vmTest_5""_PASSED"; else echo "J9vmTest_5""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
  add excludes for [all]
  add excludes for [linux_x86-64_cr]
DONE in 0 ms.
...
+++ j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest: +++
command: /tmp/bld_370249/j2sdk-image/jre/bin/java  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump -Xms64m -Xmx64m  -Xtrace:print=tpnid{j9bcu.205} -Xtrace:print=tpnid{j9bcu.31}  -Xbootclasspath:/tmp/bld_370249/j2sdk-image/jre/lib/amd64/compressedrefs/jclSC180/vm.jar:/tmp/bld_370249/j2sdk-image/jre/lib/se-service.jar:/tmp/bld_370249/j2sdk-image/jre/lib/cuda4j.jar:/tmp/bld_370249/j2sdk-image/jre/lib/rt.jar:/tmp/bld_370249/j2sdk-image/jre/lib/resources.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jsse.jar:/tmp/bld_370249/j2sdk-image/jre/lib/charsets.jar:/tmp/bld_370249/j2sdk-image/jre/lib/jce.jar:/tmp/bld_370249/j2sdk-image/jre/lib/tools.jar -classpath /tmp/bld_370249/test/TestConfig/../../jvmtest/VM_Test/VM_Test.jar:/tmp/bld_370249/test/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar  j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest 

ERROR: Unexpected number of matched lines (got 0, expected 10)!
*** Test FAILED *** (j9vm.test.romclasscreation.ROMRetentionAfterRAMFailureTest)


Tested openj9 openjdk-jdk8 on linux_x86-64_cmprssptrs.
j2sdk-image/jre/bin/java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2017_11_15_12_33-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171115_370249 (JIT enabled, AOT enabled)
OpenJ9   - 10706ea
OMR      - 99498e1
OpenJDK  - e9942fd based on jdk8u152-b03)

**Comment by vsebe** [comment]
attn @llxia

**Comment by pshipton** [comment]
Suspect same issue as #595, J9TraceFormat.dat is in the wrong place.

**Comment by pshipton** [comment]
Test is passing now.
