### ISSUE TITLE
CryptoTest failed with $TEST_JDK_HOME/bin/java as $(JAVA_COMMAND) for jdk8 on windows

### ISSUE THREAD

**Issue by LongyuZhang** [eclipse/openj9#5931]
cmdLineTester_CryptoTest works with $TEST_JDK_HOME/jre/bin/java as $(JAVA_COMMAND), but failed with $TEST_JDK_HOME/bin/java, for jdk8 on windows

Failure link: https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/2452/console

------------

Public link to the failing test.
If the link is not public, instead include 
- test category : functional
- test suite name: openssl
- OS/architecture : windows x64
- OpenJDK version : jdk8
- public build SHAs (i.e. -version output): 
OpenJ9 8ecd118
OMR 3172276
JCL 7b46afb

Optional info
-------------

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output
--------------
```
11:45:11  *** Starting test suite: OpenSSL Tests ***
11:45:11  Testing: CryptoTest
11:45:11  Test start time: 2019/05/24 08:45:10 Pacific Standard Time
11:45:11  Running command: C:/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image\\bin\\java -Xcompressedrefs  -Djdk.nativeCryptoTrace=true -cp "C:/Users/jenkins/workspace/Grinder/openjdk-tests///..//jvmtest\functional\cmdLineTests\openssl\"openssltest.jar org.openj9.test.openssl.CryptoTest
11:45:11  Time spent starting: 32 milliseconds
11:45:13  Time spent executing: 1384 milliseconds
11:45:13  Test result: FAILED
11:45:13  Output from test:
11:45:13   [OUT] Crypto test COMPLETED
11:45:13   [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
11:45:13   [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
11:45:13  >> Success condition was not found: [Output match: using native crypto library]
11:45:13  >> Required condition was found: [Output match: Crypto test COMPLETED]
11:45:13  >> Failure condition was found: [Output match: Native crypto library load failed]
11:45:13  >> Failure condition was not found: [Output match: Crypto test FAILED]
```
Include the test name:
cmdLineTester_CryptoTest

**Comment by pshipton** [comment]
Using the 0.14.2 build from Adopt, I wasn't able to reproduce this on a 64-bit JVM, but I can reproduce it using a 32-bit JVM.

**Comment by pshipton** [comment]
@groeges can you please take a look at this.

**Comment by groeges** [comment]
The issue seems to be that the relevant libcrypto dll file is not in the ./bin directory.
It is available in the ./jre/bin directory which is why the test passes when run using ./jre/bin/java.
If the dll is copied into ./bin then running using ./bin/java also works.
Investigating how to get the dll into the correct directories.

**Comment by pshipton** [comment]
@groeges The file should be found in the jre/bin directory, I don't think other similar libraries have multiple copies.

**Comment by groeges** [comment]
Should be resolved by this PR: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/312

**Comment by DanHeidinga** [comment]
@LongyuZhang Can you retest this now that the Extensions PR has been merged?

**Comment by LongyuZhang** [comment]
Both win64 and win32 have passed this test on Jenkins. I think this issue has been fixed. Thanks.
[https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/2624/](url)
[https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/2625/](url)
