### ISSUE TITLE
Determine if `systemClassLoader` property is still relevant to Java 9+

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#5940]
https://github.com/eclipse/openj9/blob/097492a09bfc0767aeea69141794c39063e080db/jcl/src/java.base/share/classes/java/lang/ClassLoader.java#L213-L233

This code looks up the property and takes action it it's set but the resulting ClassLoader object is never assigned to anything.  

Either this code is bogus in 9+ (likely) or we're missing something to support it.

**Comment by DanHeidinga** [comment]
Looking at the javadoc for ClassLoader#getSystemClassLoader():
> If the system property "java.system.class.loader" is defined when this method is first invoked then the value of that property is taken to be the name of a class that will be returned as the system class loader. The class is loaded using the default system class loader and must define a public constructor that takes a single parameter of type ClassLoader which is used as the delegation parent. An instance is then created using this constructor with the default system class loader as the parameter. The resulting class loader is defined to be the system class loader. During construction, the class loader should take great care to avoid calling getSystemClassLoader(). If circular initialization of the system class loader is detected then an IllegalStateException is thrown.

http://cr.openjdk.java.net/~iris/se/12/latestSpec/api/java.base/java/lang/ClassLoader.html#getSystemClassLoader()

**Comment by JasonFengJ9** [comment]
`sysTemp = com.ibm.oti.vm.BootstrapClassLoader.singleton();` referred was in `/*[ELSE]*/` block of `/*[IF Sidecar19-SE]*/`, so it is for `Java 8` just like `sysTemp = (ClassLoader)Class.forName(systemLoaderString,true,null).newInstance();` three lines after it.
Later it is assigned to `bootstrapClassLoader` as following: https://github.com/eclipse/openj9/blob/e01d70f115f1a9b2cdd34aa4d44af10f042a901b/jcl/src/java.base/share/classes/java/lang/ClassLoader.java#L239-L240

I guess too much JPP flags caused confusion.

**Comment by pshipton** [comment]
The "java.system.class.loader" behavior is implemented here
https://github.com/eclipse/openj9/blob/388014125ba7278f4f3721d7f51bcd06ffa8c976/jcl/src/java.base/share/classes/java/lang/ClassLoader.java#L1068

The "systemClassLoader" properly is a J9 extension which is obsolete for Java 11+. The code can be cleaned up to remove the unused bits.
