### ISSUE TITLE
Constructor.getAnnotatedParameterTypes returns wrong type to annotated parameter related to an inner class

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#5995]
**Sample program:**

```
import java.lang.reflect.AnnotatedType;

public class A<T> {

    A(B<T> b) {
    }

    class B<T> {
    }

    public static void main(String[] args) {
        AnnotatedType[] annotatedParameterTypes = A.class.getDeclaredConstructors()[0].getAnnotatedParameterTypes();
        System.out.println(annotatedParameterTypes[0].getType());
    }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java

**Current result:**

A<T>.B<T>

**Expected result:**

A<T>$B<T>

**Comment by pshipton** [comment]
Please try a newer release, it seems this problem has already been fixed.
```
OpenJDK Runtime Environment (build 1.8.0_212-b04)
Eclipse OpenJ9 VM (build openj9-0.14.2, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20190521_368 (JIT enabled, AOT enabled)
OpenJ9   - 4b1df46fe
OMR      - b56045d2
JCL      - a8c217d402 based on jdk8u212-b04)
```
result: `A<T>$B<T>`
