### ISSUE TITLE
Documentation for JEP 331

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#6003]
`JEP 331` [1] has been implemented via #4461, #4618, #5869, https://github.com/eclipse/openj9/pull/5968. 

@SueChaplain please update documentation and release notes.

Note: there are still couple of `JTreg` test issues being investigated. Also will test this functionality against `YourKit Java Profiler` as well.

[1] http://openjdk.java.net/jeps/331

**Comment by SueChaplain** [comment]
@JasonFengJ9 - please create an issue at the openj9-docs repo and include anything that is specific to OpenJ9 for this JEP. 

https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md

**Comment by JasonFengJ9** [comment]
Created https://github.com/eclipse/openj9-docs/issues/284.
