### ISSUE TITLE
SharedClasses: Improve timestamping story - no assumption that Jar files are kept open

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6022]
Making available here the IBM design that resulted in the JVM_ZipHook implementation (https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/311).

Introduction
--------------
One of the main features of the Shared Classes component is its "dynamic update" capability. If a class changes on the filesystem, we detect this and ensure that the correct class is always returned from the cache or loaded from disc. This is an absolutely essential feature as it guarantees transparency when running with shared classes.

The main problem with keeping track of class and jar file version is the performance impact of having to check every element on the classpath before a class is loaded. We optimize this as much as possible by stating the assumption (in the Helper API documentation) that once a Jar file has been opened for reading by a ClassLoader, it should be kept open for the life of the ClassLoader. By forcing the first class-load from each jar to come from disk, regardless of whether it is in the cache or not, we get the classloader to lock jar files for us. We keep track of which jars on a given classpath are locked and once they are locked, we assume that they cannot change and stop checking them.

Without this optimization, stat'ing each entry on the classpath when we load every class is prohibitively expensive.

It's actually more complicated than this, because for directory entries on a classpath, there is nothing to lock. We have to mock up expected sub-directories and class name for a class file to see if one has "appeared". This too is expensive and having many directories on a classpath has an inevitable impact on performance.

There is also a second problem. The current optimizations don't account for class GC and ClassLoader unloading. If a ClassLoader is unloaded and it lets go of the read lock on its jar files, the "isLocked" property that we've stored is not updated, so there is potential for a jar to be updated and for these updates to not be picked up. This is a bug - pure and simple - and needs to be fixed.

The customer drive for this feature comes from Eclipse 3.2. It has a feature where it can close plugin jar files at any time to help with resource constraints, so this breaks our assumption that a ClassLoader will keep its jars open. This, combined with the "hole" described in the previous paragraph, means that we need to get smarter about how we do this without sacrificing performance.

It should also be noted that RAD (Eclipse-based IDE) and WAS do not expect OSGi plugins to be updated during runtime and therefore only require a mechanism for checking that these have not changed on startup. We therefore don't need to continually check them if they are not opened. They also don't want to have to open plugin jars at all if the classes they need are already cached.

High Level Design
---------------------
Since this only applies to jars and zips, this design proposes to move the logic from <an assumption that a ClassLoader will "do the right thing">, to <hooks that are triggered when a zip/jar file is opened or closed which the class sharing code can listen to>.

All Java ClassLoaders must use the java.util.JarFile and java.util.ZipFile to open and examine jars and zips. These classes call into JNI natives when a jar file needs to be opened or closed. Since these calls always end up in native code, it should therefore be possible to add a couple of JVM hooks that are triggered when a zip/jar is opened and closed. If the shared classes code is able to listen to these hooks, it would be able to update the "isLocked" field of all the jars/zips it knows about based on the information it gets from the hooks.

To support the OSGi requirement described above, there needs to be some external mechanism for a ClassLoader to say "don't bother to check my jar files more than once". This mechanism will be useful if a particular ClassLoader knows that its jars won't change during the lifetime of the JVM - or if it doesn't care if they do. In the OSGi plugin case, they don't care if the plugin jar changes once the plugin has been initialized. They don't expect these updated classes to be picked up.
The only problem with this approach is the following: Imagine that a plugin ClassLoader loads a bunch of classes into the cache from jar A1.jar. During the lifetime of the same JVM, A1.jar is updated. Some more cached classes are loaded from the cache after the update - the classes from the old A1.jar are returned from the cache (the update is not noticed). Then a class is loaded which doesn't exist in the cache. It is loaded from the updated A1.jar and stored in the cache - since it was not built against the original classes, the verifier rejects the class. However, this problem is not unique to class sharing. This would happen even without class sharing if a plugin jar is updated during the lifetime of a ClassLoader. I think the only way they get around this in OSGi is just by saying that replacing plugin jars while Eclipse is running is "not supported".

Description
-------------
A summary of these changes would be:
1) Change how the shared classes code represents locked Jar files, to allow this to be manipulated externally
2) Trigger a hook in the places where zips and jars are opened and closed.
3) Link the hooks to the shared classes code
4) Add the function to SharedClassURLHelper to allow minimized checking

(1)
Previously, each classpath entry is stored in a local hashtable of known classpath entries in the ClasspathManager and each representation of a classpath entry has an "isLocked" field. This field is set if a timestamp check is done of a jar/zip when a class is being stored in the cache - the jar/zip must have been opened if the class is being stored. We therefore check the timestamp of the container once and then set isLocked, which prevents further checks of that container for the lifetime of the JVM. Each container in the hashtable has one or more entries in the cache.

The main changes required to this design is 
a) the ability to store information about containers that are not yet in the cache and 
b) be able to store more states than just isLocked
c) change the way the information is obtained... currently it is driven by the cache code... it will need to be driven by the zip APIs via a hook mechanism.

(a)
Storing information about containers that don't exist in the cache is easy. We simply break the assumption that if a hashtable entry exists, it must point to an entry in the cache. Checks will need to be added to support this assumption when the hashtable is queried.

(b)
Change the "isLocked" field to be "flags". This field is already a U_8 which is sufficient to store the flags required. Flags would be:

CPM_ZIP_OPEN				Indicates zip/jar is currently open
CPM_ZIP_CHECK_TIMESTAMP			Indicates that the timestamp of this container should be checked for each class load
CPM_ZIP_ONLY_TIMESTAMP_ON_INIT		Indicates that the timestamp of this container should only be checked once during initialization to support OSGi requirements described above
CPM_ZIP_CHECKED_INIT_TIMESTAMP		Indicates that the initialization timestamp has been done

(c)
Changing the way the information is driven should also be straightforward. When shared classes initializes, it registers to listen to the hooks that are installed in the Zip APIs. These hooks can update the ClasspathManager hashtable at any time. See (3) below for more details of the hook mechanism.

(2)
The J9HOOK_VM_ZIP_LOAD hook already exists and just needs to be extended with the new states.

The constants which can be passed through the hook are defined in vmzipcachehook.h and are the following:

J9ZIP_STATE_OPEN
J9ZIP_STATE_CLOSED
J9ZIP_STATE_RESET
J9ZIP_STATE_IGNORE_STATE_CHANGES (results in CPM_ZIP_ONLY_TIMESTAMP_ON_INIT)

The hook ideally needs to be triggered in a single place where the bootstrap loader and all other classloaders will go when they open and close zip files. 

A new JVM_ function will be added to jvm.c:

JVM_ZipHook(JNIEnv *env, const char* filename, jint newState)

The constants for the JVM_ZipHook function are defined in jvm.h as:

JVM_ZIP_HOOK_STATE_OPEN
JVM_ZIP_HOOK_STATE_CLOSED
JVM_ZIP_HOOK_STATE_RESET

(3)
The classpath entry state changes are driven by the following function in ClasspathManager:

void notifyClasspathEntryStateChange(J9VMThread* currentThread, const char* path, UDATA newState)

This function is propogated right through CacheMap and out to the SharedCache interface. Shrinit.cpp registers a listener function with the J9HOOK_VM_ZIP_LOAD and this function calls notifyClasspathEntryStateChange.

The notifyClasspathEntryStateChange function performs the following tasks for the various states:

J9ZIP_STATE_OPEN

There may or may not be an entry for this jar/zip in the hashtable. If no entry exists, create one. Set CPM_ZIP_OPEN. Set CPM_ZIP_CHECK_TIMESTAMP, if CPM_ZIP_CHECKED_INIT_TIMESTAMP is not set.
If CPM_ZIP_CHECK_TIMESTAMP and CPM_ZIP_OPEN are set, the first time the timestamp is checked, CPM_ZIP_CHECK_TIMESTAMP is removed.

J9ZIP_STATE_CLOSED

We will definitely already have an entry for this jar/zip in the hashtable. Remove the CPM_ZIP_OPEN flag. Set CPM_ZIP_CHECK_TIMESTAMP if CPM_ZIP_CHECKED_INIT_TIMESTAMP is not set.

J9ZIP_STATE_RESET

Driven by the bootstrap natives, but not currently driven by the class-libraries. This is a no-op for the shared classes code as it does not change the state of the zip file.

J9ZIP_STATE_IGNORE_STATE_CHANGES

This hook causes the CPM_ZIP_CHECKED_INIT_TIMESTAMP to be added to the classpath entry. This will ensure that the timestamp of the container is checked on initialization and then not checked again.

(4)
To support the OSGi requirements above, I propose adding the following function to com.ibm.oti.shared.SharedClassURLHelper:
```
	/**
	 * Minimize update checking on jar files for optimal performance<p>
	 * By default, when a class is loaded from the shared class cache, the timestamp of the container it was originally loaded from is
	 * compared with the timestamp of the actual container on the filesystem. If the two do not match, the original class is marked stale
	 * and is not returned by findSharedClass(). These checks are not performed if the container is held open by the ClassLoader.<br>
	 * If the ClassLoader does not want to open the container, but doesn't want the timestamp to be constantly checked when 
	 * classes are loaded, it should call this function immediately after the SharedClassURLHelper object has been created.
	 * Once this function has been called, each container timestamp is checked once and then is not checked again for the lifetime 
	 * of the SharedClassURLHelper.<br>
	 * This feature cannot be unset.
	 * <p>
	 * @author		OTI
	 * @version		initial
	 *
	 * @return		boolean
	 * 					True if the feature has been successfully set, false otherwise.
	 */
	public boolean setMinimizeUpdateChecks();
```
This will cause an extra flag to be passed through to the natives for every findSharedClass() and storeSharedClass() call to indicate that minimal checking should be performed. Internally, this results in a call to the hook every time a new classpath entry is created to inform the ClasspathManager that only an initial check should be performed on the container.

**Comment by pshipton** [comment]
@hangshao0 @DanHeidinga fyi

**Comment by pshipton** [comment]
The current problems (#5918) are with ClassLoader's using class paths, i.e. the URLClassLoader. Loaders which use single URLs (OSGi/Eclipse) can/do already use the setMinimizeUpdateChecks() API to do minimum timestamp checking.

- the zip state is registered by file name, and is not associated with a ClassLoader. This may cause problems when the file name is opened/closed by more than one ClassLoader, or opened/closed outside of any ClassLoaders.

- an optimization for storing the zip state causes zip file names to be stored in the shared cache, which can grow the shared cache size every time a unique zip file is opened. 

- the JVM_ZIPHook extensions patch (ibmruntimes/openj9-openjdk-jdk8#311) is specific to Java 8 and not easily portable to Java 11 and later.

To address these problems, we can introduce a similar api setMinimizeUpdateChecks() for class paths. For minimized update checks there is no zip open/closed state required, the zip files are assumed to be kept open and not modified during use. Only the single initial timestamp check is required. This matches the behavior of URLClassLoader, which keeps zip (jar) files open. A command line option can be added to force timestamp checking in case there is a problem.

When not using setMinimizeUpdateChecks(), if we still want to have a zip state optimization, the zip state can be stored separately for each ClassLoader class path entry. Rather than hooking into the zip file implementation to record zip open/close, hook into the ClassLoader implementation and make calls to the com.ibm.oti.shared APIs, as we already have done to support class sharing. The first class load already occurs from the jar file, and not the shared cache, and the ClassLoader reports this class load to the shared cache. We should be able to take advantage of this to record the initial zip open state. Finalization is problematic because if zip files are closed this way they can't be associated with a ClassLoader. If not explicitly closed, WeakReferences must be used to track file close. Again a force timestamp check option can provide a work around for any problems.

**Comment by ChengJin01** [comment]
> I think what we should do first is add some -Xshareclasses options `checkClasspathTimestamps` and
>  `noCheckClasspathTimestamps` .
> with `noCheckClasspathTimestamps` as the default, giving the same behavior as J9ZIP_STATE_OPEN. 
> If `checkClasspathTimestamp` is specified,  the behavior is the same as today in OpenJ9 builds.
>
> In SH_ClasspathManagerImpl2::CpLinkedListHdr::CpLinkedListHdr() it initializes the _flags. 
> If the CpLinkedListHdr is being created for a URLClasspath, then the flags can be initialized to 
> `CPM_ZIP_OPEN | CPM_ZIP_FORCE_CHECK_TIMESTAMP`, which is the same as J9ZIP_STATE_OPEN.
>
> The two tricky parts I can think of are:
>  1) determining if the CpLinkedListHdr is for a URLClasspath
> `j9shr_classStoreTransaction_start()` calls `cachemap->updateClasspathInfo()` which calls
> `addClasspathToCache()`  which calls `localCPM->storeNew()`. 
> For a classpath, the cpi->getType() will be CP_TYPE_CLASSPATH

Given that the calling path is  as follows:
`localCPM->storeNew() --> cpeTableUpdate() --> cpeTableAdd() --> cpeTableAddHeader() (which create a new CpLinkedListHdr) `
The code there can be something like:
```
SH_ClasspathManagerImpl2::storeNew(J9VMThread* currentThread, const ShcItem* itemInCache, SH_CompositeCache* cachelet)
{
...
U_8 isURLClasspath = (cpi->getType()==CP_TYPE_CLASSPATH); <------
if (!cpeTableUpdate(currentThread, path, pathLen, i, itemInCache, isToken, isURLClasspath, isLastItem, cachelet)) {
...

SH_ClasspathManagerImpl2::CpLinkedListHdr::CpLinkedListHdr(const char* key_, U_16 keySize_, U_8 isToken_, U_8 flags_, <----- introduce a new argument `flags_`
 CpLinkedListImpl* listItem)
 : _isToken(isToken_),
   _flags(flags_),  <-------------
   _keySize(keySize_),
   _key(key_),
   _list(listItem)
{
}

SH_ClasspathManagerImpl2::cpeTableAddHeader(J9VMThread* currentThread, const char* name, U_16 nameLen, CpLinkedListImpl* newItem, U_8 isToken, U_8 isURLClasspath)
{
J9JavaVM* vm = currentThread->javaVM;
U_8 flags =  (J9_ARE_ANY_BITS_SET(vm->sharedCacheAPI->runtimeFlags, checkClasspathTimestamp) &&  isURLClasspath) ? (CPM_ZIP_OPEN | CPM_ZIP_FORCE_CHECK_TIMESTAMP) : 0;
}
CpLinkedListHdr header(name, nameLen, isToken, flags, newItem);
```

**Comment by hangshao0** [comment]
To get the Jar/Zip File open state, there might be 2 possible ways: 

1. From the code that classloader calls to open the Jar/Zip file on the URL class path, somewhere around:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/jdk/internal/loader/URLClassPath.java#L860

2. Take advantage of the confirmedCount. The Jar/Zip files on the class path that has index < confirmedCount should already be open by this class loader. 
https://github.com/eclipse/openj9/blob/master/jcl/src/openj9.sharedclasses/share/classes/com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.java#L201

**Comment by ChengJin01** [comment]
I already finished coding on OpenJDK8 & OpenJ9
https://github.com/ChengJin01/openj9-openjdk-jdk8/tree/sc_notify_close_state_jdk8
https://github.com/ChengJin01/openj9/tree/sc_no_classpath_timestamp_check
to cover the following requested parts:
1. initialize to flags of CpLinkedListHdr to `CPM_ZIP_OPEN | CPM_ZIP_FORCE_CHECK_TIMESTAMP` if the CpLinkedListHdr is being created for a URLClasspath.
2. resetting the flags to J9ZIP_STATE_OPEN every time a new URLclassloader is created (which will definitely use CpLinkedListHdr)
3. notify the J9ZIP_STATE_CLOSED state from OpenJDK8 to set the flags when the URLclassloader is closed.

According to the code in OpenJDK8 & OpenJDK11 at jdk/src/share/classes/java/net/URLClassLoader.java,
```
    /* A map (used as a set) to keep track of closeable local resources
     * (either JarFiles or FileInputStreams). We don't care about
     * Http resources since they don't need to be closed.
     *
     * If the resource is coming from a jar file
     * we keep a (weak) reference to the JarFile object which can
     * be closed if URLClassLoader.close() called. Due to jar file
     * caching there will typically be only one JarFile object
     * per underlying jar file.
     *
     * For file resources, which is probably a less common situation
     * we have to keep a weak reference to each stream.
     */

    private WeakHashMap<Closeable,Void>
        closeables = new WeakHashMap<>();
...
    public void close() throws IOException {
        SecurityManager security = System.getSecurityManager();
        if (security != null) {
            security.checkPermission(new RuntimePermission("closeClassLoader"));
        }
        List<IOException> errors = ucp.closeLoaders();

        // now close any remaining streams.
        sharedClassURLClasspathHelper.notifyCloseState();
        
        synchronized (closeables) {
            Set<Closeable> keys = closeables.keySet();
            for (Closeable c : keys) {
                try {
                    c.close();
                } catch (IOException ioex) {
                    errors.add(ioex);
                }
            }
            closeables.clear();
        }
...
```
I believe `WeakReferences `are already used to deal with file close on OpenJDK 8 & OpenJDK11.

The changes above need to be compiled to clean up all errors to see whether it works with the test application at https://drive.google.com/file/d/1dvNNXXmYQZqvlQRzkST4DRGMrm5nsfhh/view

**Comment by ChengJin01** [comment]
Test with spring.boot.openj9-0.0.1-SNAPSHOT.jar shows there were some errors with these command options specified.  Need to double-check the code to see what happened in there.

**Comment by ChengJin01** [comment]
@hangshao0 and I already checked the test results as follows with the latest changes:
```
(without SCC)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
09:21:14.506 [main] INFO  com.example.application.Application  - Started Application in 20.324 seconds (JVM running for 22.27)

------------

(cold SCC / with checkClasspathTimestamp specified)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java   -Xshareclasses:name=spring,checkClasspathTimestamp  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
10:43:55.183 [main] INFO  com.example.application.Application  - Started Application in 30.707 seconds (JVM running for 34.216)

(warm SCC / with checkClasspathTimestamp specified)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java   -Xshareclasses:name=spring,checkClasspathTimestamp  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
10:44:35.821 [main] INFO  com.example.application.Application  - Started Application in 16.451 seconds (JVM running for 17.603)

(warm SCC / with checkClasspathTimestamp & noTimestampChecks  specified)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java   -Xshareclasses:name=spring,checkClasspathTimestamp,noTimestampChecks  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
10:46:18.218 [main] INFO  com.example.application.Application  - Started Application in 10.421 seconds (JVM running for 11.166)
--------------

(cold SCC / with nocheckClasspathTimestamp by default)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java  -Xshareclasses:name=spring2   -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
09:29:12.453 [main] INFO  com.example.application.Application  - Started Application in 25.58 seconds (JVM running for 28.679)

(warm SCC / with nocheckClasspathTimestamp by default)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java  -Xshareclasses:name=spring2   -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
09:31:57.696 [main] INFO  com.example.application.Application  - Started Application in 10.151 seconds (JVM running for 10.962)

--------------

(cold SCC / with nocheckClasspathTimestamp explicitly specified)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java  -Xshareclasses:name=spring4,nocheckClasspathTimestamp  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
09:44:08.710 [main] INFO  com.example.application.Application  - Started Application in 26.135 seconds (JVM running for 29.159)

(warm SCC / with nocheckClasspathTimestamp by default)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java  -Xshareclasses:name=spring4,nocheckClasspathTimestamp  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
09:44:48.466 [main] INFO  com.example.application.Application  - Started Application in 10.584 seconds (JVM running for 11.456)
```
The results shows the time spent with `checkClasspathTimestamp & noTimestampChecks `specified (pretty much the existing implementation) was almost the same as the time spent with `nocheckClasspathTimestamp `specified)
```
(warm SCC / with checkClasspathTimestamp & noTimestampChecks  specified)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java   -Xshareclasses:name=spring,checkClasspathTimestamp,noTimestampChecks  -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
10:46:18.218 [main] INFO  com.example.application.Application  - Started Application in 10.421 seconds (JVM running for 11.166)

(warm SCC / with nocheckClasspathTimestamp by default)
C:\...>j2sdk_image_jdk8_openj9_v2\bin\java  -Xshareclasses:name=spring2   -jar spring.boot.openj9-0.0.1-SNAPSHOT.jar
09:31:57.696 [main] INFO  com.example.application.Application  - Started Application in 10.151 seconds (JVM running for 10.962)
```
which means the solution works good as expected.

**Comment by ChengJin01** [comment]
The solution above is specific to Java 8.  For Java 11, extra java code need to be added to the sharedclasses related places.

**Comment by hangshao0** [comment]
I believe documentation change is required.

**Comment by ChengJin01** [comment]
> To address these problems, we can introduce a similar api setMinimizeUpdateChecks() for class paths. For minimized update checks there is no zip open/closed state required ...

Given that the new option `checkClasspathTimestamp` can be specified on the command line to enable the minimal check in the native code (to be implemented with `checkClasspathTimestamp` specified), there should be no need to create a public API to set up `minimizeUpdateChecks` at Java level (in OpenJDK or in user application) unless it is required by users.

**Comment by pshipton** [comment]
The setMinimizeUpdateChecks() is more specific as it can be specified per classloader, while `checkClasspathTimestamps ` affects all URL loaders.  However I agree we should wait and see if setMinimizeUpdateChecks() is needed before implementing it.

**Comment by pshipton** [comment]
I'll go ahead and close this since the checkURLTimestamps/noCheckURLTimestamps options are added, with the default behavior as noCheckURLTimestamps. We can reopen or create a new issue later if a Java API like setMinimizeUpdateChecks() is needed.
