### ISSUE TITLE
Failed to connect to local process via remote connection mode using jconsole

### ISSUE THREAD

**Issue by hi5san** [eclipse/openj9#6034]
Java -version output
--------------------
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.3, JRE 11 Linux amd64-64-Bit Compressed References 20190531_239 (JIT enabled, AOT enabled)
OpenJ9   - b8ab01656
OMR      - b56045d2
JCL      - dcdc97f9dc based on jdk-11.0.3+7)

Summary of problem
------------------
JConsole fails to connect to runtime process using JConsole's **remote connection mode** (local process attach works, since fixed in issue #5872).

I created the target runtime with the following command.

```
$ jlink -p jmods --add-modules jdk.management.agent --output NameOfDir
```

When I execute an application using the jlinked image and tried to monitor it using JConsole's **remote connection mode** as below, JConsole fails to connect with "Connection refused" error.

```
$ ./java -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.rmi.port=9996 -Dcom.sun.management.jmxremote.port=9996 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -cp /path/to/HW11.jar HelloWorld
```

```
$ jconsole localhost:9996
```

Executing JConsole with `-debug` option gives the following stack trace.

```
java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: connect (Connection refused)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:209)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
	at java.rmi/sun.rmi.server.UnicastRef.newCall(UnicastRef.java:338)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:112)
	at jdk.jconsole/sun.tools.jconsole.ProxyClient.checkSslConfig(ProxyClient.java:234)
	at jdk.jconsole/sun.tools.jconsole.ProxyClient.<init>(ProxyClient.java:127)
	at jdk.jconsole/sun.tools.jconsole.ProxyClient.getProxyClient(ProxyClient.java:475)
	at jdk.jconsole/sun.tools.jconsole.JConsole$3.run(JConsole.java:524)
Caused by: java.net.ConnectException: connect (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at java.rmi/sun.rmi.transport.tcp.TCPDirectSocketFactory.createSocket(TCPDirectSocketFactory.java:40)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 8 more
```

I checked using `netstat` and it seems the runtime agent is not listening for remote connections on the specified port.

It works using non-jlinked image.
I've also tried the same on OpenJDK HotSpot VM, and this issue does not occur.
So it seems this problem is OpenJ9 specific when using a jlinked image.

**Comment by pdbain-ibm** [comment]
This usage bypasses the Attach API completely: launching the target process with `-Dcom.ibm.tools.attach.enable=no` on a full OpenJ9 JVM works correctly.

**Comment by pdbain-ibm** [comment]
jlinking with `jdk.management.agent,jdk.jconsole` makes the test pass. 
Adding only the modules on which `jdk.jconsole` depends: `java.management,java.rmi,jdk.management,jdk.internal.jvmstat,java.management.rmi,jdk.attach,jdk.management.agent,java.desktop` does not.

**Comment by pshipton** [comment]
I think the difference is that jdk.jconsole is a root and requires jdk.management.agent, causing it to get loaded.

**Comment by pshipton** [comment]
@hi5san btw, there is a workaround for this problem, until it can be resolved. Which is to add `--add-modules jdk.management.agent` to the application.

**Comment by hi5san** [comment]
@pshipton @pdbain-ibm Thanks for your prompt actions.

> @hi5san btw, there is a workaround for this problem, until it can be resolved.
> Which is to add `--add-modules jdk.management.agent` to the application.

Thanks, that worked.  I could successfully connect to application using JConsole's remote connection mode locally (localhost:port) and also from remote host (hostname:port) as expected.

**Comment by pdbain-ibm** [comment]
As an experiment, I loaded and invoked `jdk.internal.agent.Agent.startLocalManagementAgent()` unconditionally during startup. jconsole was unable to connect.

**Comment by pdbain-ibm** [comment]
Another interesting problem: adding the VM option `--show-module-resolution` causes the loading of Module `jdk.management.agent` to fail.

**Comment by DanHeidinga** [comment]
@pdbain-ibm We're coming up on the `0.15.0` "reality check" date of June 18 to determine what will make the release.  Is this going to be ready for the June 24 code split?

**Comment by pdbain-ibm** [comment]
> Is this going to be ready for the June 24 code split?

Probably.  I will know better later today.

**Comment by pdbain-ibm** [comment]
So far so good.  Adding the following (as an experiment, still needs work) to the end of `jclcinit.c::initializeRequiredClasses()`:

```
	if (NULL != vm->modulesPathEntry->extraInfo) {
		const char *module = vm->jimageIntf->jimagePackageToModule(
				vm->jimageIntf, (UDATA) vm->modulesPathEntry->extraInfo,
				"jdk/internal/agent");
		if (NULL != module) {
			vmFuncs->addSystemProperty(vm, "jdk.module.addmods.0", "jdk.management.agent", 0);
		}
	}
```
causes `jdk.management.agent` to be loaded as a root module and jconsole is able to connect via `localhost:9996`. No error is thrown if `jdk.management.agent` is missing.

**Comment by pdbain-ibm** [comment]
I have a candidate fix (https://github.com/pdbain-ibm/openj9/commit/6a253e3499167844a3cffb3ee2b225697fa7a889) which I have designer tested but is not ready for detailed review. I will create a Linux image and upload it for @hi5san to test.

**Comment by pdbain-ibm** [comment]
@hi5san Please test https://drive.google.com/open?id=1GrB7ozSFMpAYDRbmMCbRummS-RoIluW9
(Java 11) and inform me if this fixes your issue. Please contact me on Slack or this issue if you have any questions.
Thank you.
     -p

**Comment by hi5san** [comment]
@pdbain-ibm Thanks Peter.  I've confirmed fix using your test build, successfully connected via remote connection for (1) localhost:port and (2) remoteIp:port from different host, as expected.  Thank you.
