### ISSUE TITLE
Suboptimal GC parallelism resulting from deep structures

### ISSUE THREAD

**Issue by RSalman** [eclipse/openj9#6060]
### Problem
Deep structures, such as long lists, are known to cause issues with GC parallelism. Given the object graph of deep structures and limitations of traversing/scanning them, these structures are left un-sharable and thus hogged by a single thread during scanning. Traversing through a deep structure is “slow” as the sub-structure (e.g., Item pointer) of each node is visited before progressing through the deep structure (progressing through next pointer, from head to tail). Unlike arrays, lists cannot be easily split, because to reach to an arbitrary node of the list (as a point of sharing with other threads) all previous nodes of the list have to be visited first. Overall, deep structure traversal isn’t effective in producing work to maintain parallelism. GC threads are left idle thus causing suboptimal parallelism.

The effects of this issue are illustrated by the graph of GC times below, large fluctuations in GC cycle times can be seen as collection times periodically peak up ~2x-3x optimal cycle times. These increases in time are directly correlated to a decrease in parallelism resulting from scanning deep structures.

![image](https://user-images.githubusercontent.com/9648788/59115919-4d437e00-8918-11e9-824a-e4a241aea9e4.png)

### Solution
Priority based scanning solves issues related to GC parallelism and deep structures. With priority based scanning, nodes and links of deep structures are special treated with scan priority. An object is given scan priority if it contains a self-referencing field (e.g., next or previous pointer). Specifically, the positions of self-referencing fields are marked and remembered. These special fields are identified very early during class loading time, just based on the type of the field. Later, when a priority object is recognized during scanning (during GC time), the regular scan routine is impeded and a “special treatment” routine is started. The special treatment routine essentially begins a full structure traversal by only following the self-referencing pointer of its nodes and ignoring other scan fields of that object (i.e., traversal from head to tail – ignoring node sub-structures). As a result, node items/sub-structures are discovered but not scanned, hence they can be shared with other threads for scanning. Overall, parallelism is maintained as work is produced by proactively traversing through the nodes of a deep structure with priority.

### Results

With priority based scanning, a lot more work is produced and available for idle threads. Thus, parallelism is maintained and large fluctuations in GC times are dealt with as the high GC times resulting from suboptimal parallelism are addressed. Overall, average GC times are reduced as shown below (priority based scanning GC times outlined in blue).

![image](https://user-images.githubusercontent.com/9648788/59115523-74e61680-8917-11e9-9ace-a9ef1784a549.png)

**Comment by RSalman** [comment]
### Testing for regression/overhead

For each object being scanned, an extra check is introduced to determine if it contains a self referencing fields for deep scanning. Hence, we may have overhead and we must ensure that we don't have regression for workloads that don't make use of deep structures.

From the benchmark results below, we can conclude that there is no regression.

Workloads without Deep structures:

![image (2)](https://user-images.githubusercontent.com/9648788/59223487-0bc20580-8b9a-11e9-82c2-83c68b240438.png)

![image](https://user-images.githubusercontent.com/9648788/59223972-39f41500-8b9b-11e9-9117-f27d9bddff7c.png)

**Comment by RSalman** [comment]
### Startup and Footprint Performance (Liberty Benchmark)
<table>
    <thead>
        <tr>
            <th colspan='3'>Setup</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>Platform</b></td>
            <td>xa</td>
        </tr>
        <tr>
        </tr>
        <tr>
            <td><b>JDK Options</b></td>
             <td>-Xmx256m -Xcompressedrefs</td>
        </tr>
        <tr>
            <td><b>Benchmark Options</b></td>
<td>2 cold, 3 warmup and 25 warm runs </td>
        </tr>
    </tbody>
</table>

**_Each set of results is an average of 25 iterations of WARM runs_**

#### 48 Core Machine
![image](https://user-images.githubusercontent.com/9648788/59802918-03fc1280-92b8-11e9-82ff-b2eb31f17c05.png)


#### 4 Core Machine
![image](https://user-images.githubusercontent.com/9648788/59802649-6c96bf80-92b7-11e9-80d8-762091ae42e4.png)

**Comment by avermeer** [comment]
Hello @RSalman,

I have the feeling that we had an application having inefficient CG and indeed having big structure as you decribe.

In a PCS test we experienced very long GC pauses (up to 9s) with OpenJ9 vs. HotSpot.
We tried Metronome, which avoided the long GC pauses, but still we got worse performance with OpenJ9 vs. HotSpot.

Is there a way we could test your improvement for deep structures with a recent nightly build of OpenJ9 on AdoptOpenJDK site? 

Any specific option that we should use to activate your optimizations?

Kind regards,
Alexandre Vermeerbergen

**Comment by amicic** [comment]
@avermeer The changes are not yet it, and probably will not be in the coming (0.15) release, but should be in nightly builds in a week or so. We can let you know when it's available.

Meanwhile, feel free to send us verbose GC logs, ideally with -Xtgc:parallel,file=tgc.log logs to examine. There could be various sources of long delays, unrelated to deep structure tracing.

**Comment by avermeer** [comment]
@amicic thank you very much for the suggested GC log option. I checked, and this Xtgc:parallel,file=tgc.log is not supported by HotSpot, which is too bad because I won't be able to do comparisons. 
  Is there an HotSpot option which could provide similar output so that a meaningful comparison of my PCS scenario between OpenJ9 vs HotSpot could be done?

Kind regards,
Alexandre Vermeerbergen

**Comment by amicic** [comment]
Correct, -Xtgc options are J9 specific. They are just additional logs that may help with debugging various pause related problem. I'm not aware of similar HotSpot option, but we don't really need them. I'm looking just for J9 verbose GC and TGC logs . If you accompany them with HotSpot verbose GC logs it could be also useful.

I suggest you create a separate Issue for this to not pollute this design discussion. You can also try to contact us on Slack, Eclipse OpenJ9 workspace.

**Comment by DanHeidinga** [comment]
@mpirvu Can you comment on the footprint / startup #s in https://github.com/eclipse/openj9/issues/6060#issuecomment-503754773 ?

**Comment by mpirvu** [comment]
Regarding the footprint/startup numbers in https://github.com/eclipse/openj9/issues/6060#issuecomment-503754773
- There is a 0.6% footprint regression on the big machine, but on those machines scalability is much more important than a small increase in footprint after startup.
- There is a 0.1-0.4% footprint increase for the 4-core machine, which is noise in my opinion.
- There are mixed start-up time results for the big machine (+1.4% : -1.9%) which are likely due to fluctuations
- There is virtually no change in start-up time for the 4-core machine.

One observation though: the absolute start-up numbers look large (I am used to ~3-5 seconds). 
@RSalman Was that a very slow machine? What was installed on top of Liberty? What is the confidence interval for the experiments?

**Comment by RSalman** [comment]
> Was that a very slow machine?
```Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Stepping:              4
CPU MHz:               1200.000
BogoMIPS:              5386.28
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47```

**Comment by RSalman** [comment]
>Was that a very slow machine?

It seems like a pretty fast machine
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
Stepping:              4
CPU MHz:               1200.000
BogoMIPS:              5386.28
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47
```
> What was installed on top of Liberty?

Nothing that I am aware of, I believe using the "default package", and I'm not making any modifications to it. Here are some parameters that I'm setting for the benchmark:

```
export JDK_OPTIONS=" -Xmx256m -Xcompressedrefs "
export COLD=2
export WARMUP=3
export NO_SETUP=false
export SETUP_ONLY=false
export WARM=25
export INSTALL_DIR=
export LIB_PATH=
export HEALTH_CENTRE=
export COGNOS_WAIT=
export REQUEST_CORE=
export SCENARIO=DayTrader
export SERVER_NAME=LibertySUDTServer-DEEPSCAN
export PETERFP=
export APP_VERSION=daytrader3.0.10.1-ee6-src
export AFFINITY="taskset -c 0-47 "
export RESULTS_DIR=libertyResults
export LAUNCH_SCRIPT=server
export LIBERTY_VERSION=liberty18003
```

> What is the confidence interval for the experiments?

I'll look into this and get back to you - will need to go back to the results for this.

**Comment by RSalman** [comment]
> The absolute start-up numbers look large (I am used to ~3-5 seconds)

I didn't use shared class cache for these runs, perhaps that may explains the slow start ups.

**Comment by mpirvu** [comment]
Without shareclasses my startup numbers for liberty+sufpdt3 are around 7 sec on a 4-core machine @3.5Ghz, so maybe 9.4 sec on a machine @2.7Ghz is not that far off. Note that on liberty shareclasses are enabled by default and one has to specify -Xshareclasses:none to disable the feature. Was that the case in the experiments above?

**Comment by RSalman** [comment]
I didn't specify that option, however from the logs it seems like there was an issue running with share classes. For each run, I'm seeing

```JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified```

```
.--------------------------
| Printing shared class cache stats:

/perf/sdks/deepscan/bin/../bin/java -Xshareclasses:name=liberty-dt-sufp-deepscan,printStats
JVMSHRC023E Cache does not exist
```

I also did a quick run with verbose logs and it does seem like share classes get enabled:

```<vmarg name="-Xquickstart" />
    <vmarg name="-Xnoaot" />
    <vmarg name="-Xshareclasses:name=liberty-%u,nonfatal,cacheDir=/perf/libertyBinaries/liberty18003/usr/servers/.cl..." />
    <vmarg name="-XX:ShareClassesEnableBCI" />
    <vmarg name="-Xscmx60m" />
    <vmarg name="-Xscmaxaot8m" />
```

**Comment by mpirvu** [comment]
Then the perf results may be ok, though it would be interesting to know what prevents SCC from being used.

**Comment by RSalman** [comment]
Perhaps not enough privileges to create SC cache at default dir

**Comment by amicic** [comment]
File/dir access privileges might be a problem with creating SC. I see: cacheDir=/perf/....        @RSalman was running under its own account.

While he can try to investigate (for benefits of future experiments), I don't think it's relevant for the original concern.

**Comment by mpirvu** [comment]
> While he can try to investigate (for benefits of future experiments), I don't think it's relevant to the original concern.

Agreed
