### ISSUE TITLE
String compression check NOP involving static StringCompressionFlag field

### ISSUE THREAD

**Issue by yanluo7** [eclipse/openj9#608]
Parent issue encompassing child Pull Reqs that contribute to string compression check NOP involving static StringCompressionFlag field.

Optimization
--------------
Currently, we check if a String is compressed by checking its count field is non-negative. We can optimize by checking if the static compressionFlag field is null instead. Because StringCompressionFlag class is only initialized if an uncompressed String is constructed, we can tell there's no uncompressed String objects in the JVM as long as the field is null.
On the JIT side, we can tell the optimizer to generate guarded NOP for these null checks, effectively skipping (compressionFlag == null || count >= 0). When an uncompressed String is constructed, 'StringCompressionFlag' class is initialized and this triggers the JIT to patch all the NOP sites, restoring the (compressionFlag == null || count >= 0) check.

Approach
----------
Writing and testing BumbleBench testcases for each API can take some time, so Andrew and I decided to break all the APIs into batches to commit, so we don't build too much of a change set.

There are another ~27 of the enableCompression && count >= 0 checks in String to be addressed under this issue.

**Comment by yanluo7** [comment]
JIT PR: https://github.com/eclipse/omr/pull/2013
JCL PR: https://github.com/eclipse/openj9/pull/603

**Comment by DanHeidinga** [comment]
Edited the description to include some of the context from #603

**Comment by yanluo7** [comment]
JCL PR for remaining String API/helper:https://github.com/eclipse/openj9/pull/700

**Comment by andrewcraik** [comment]
@yanluo7 is this done now that #700 is merged? If so we should close the issue.

**Comment by yanluo7** [comment]
This should be done. I'm currently tracking down cases where certain uncompressed string(s) are being created in the JVM/JCL and trying to suppress their generation. I will open new issue for additional work.
