### ISSUE TITLE
Remove references to UT_DIRECT_TRACE_REGISTRATION

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6080]
https://github.com/eclipse/omr/pull/3263 removed the UT_DIRECT_TRACE_REGISTRATION feature, which is now always enabled by default. There are a number of references in OpenJ9 that should be removed.

https://github.com/eclipse/openj9/search?q=UT_DIRECT_TRACE_REGISTRATION&unscoped_q=UT_DIRECT_TRACE_REGISTRATION

https://github.com/eclipse/openj9/search?q=-DUT_DIRECT_TRACE_REGISTRATION&unscoped_q=-DUT_DIRECT_TRACE_REGISTRATION

**Comment by jkjsjsjsjy** [comment]
good
