### ISSUE TITLE
Send processor features from JITaaS client to server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6081]
The JITaaS server must generate code that can be run on the client, therefore the client must communicate its processor features.
In general, we have to look at any AOT compatibility flags and make sure the appropriate information is passed from client to server.
This information could be stored in the `VMinfo` struct which holds information global to the VM that does not change throughout the life of the VM.

**Comment by mpirvu** [comment]
@harryyu1994 For your attention.

**Comment by harryyu1994** [comment]
Each compilation object creates a `CodeGenerator` object (using `allocateCodeGenerator`), the CodeGenerator object initializes its `TR_X86ProcessorInfo` flag from the global `TR::Compiler->target.cpu.getX86ProcessorFeatureFlags()` routine. We need to change this routine to per-client for JITaaS so that each CodeGenerator object takes information from its own client when doing initialization.

**Comment by harryyu1994** [comment]
```
void TR_X86ProcessorInfo::initialize()
   {
   // For now, we only convert the feature bits into a flags32_t, for easier querying.
   // To retrieve other information, the VM functions can be called directly.
   //
   _featureFlags.set(TR::Compiler->target.cpu.getX86ProcessorFeatureFlags());
   _featureFlags2.set(TR::Compiler->target.cpu.getX86ProcessorFeatureFlags2());
   _featureFlags8.set(TR::Compiler->target.cpu.getX86ProcessorFeatureFlags8());

   // Determine the processor vendor.
   //
   const char *vendor = TR::Compiler->target.cpu.getX86ProcessorVendorId();
   if (!strncmp(vendor, "GenuineIntel", 12))
      _vendorFlags.set(TR_GenuineIntel);
   else if (!strncmp(vendor, "AuthenticAMD", 12))
      _vendorFlags.set(TR_AuthenticAMD);
   else
      _vendorFlags.set(TR_UnknownVendor);

   // Finally set this bit so we don't attempt to re-initialize.
   //
   _featureFlags.set(TR_X86ProcessorInfoInitialized);
```
`TR_X86ProcessorInfo` is initialized in OMR.
