### ISSUE TITLE
Reduce number of VM_classHasBeenExtended messages

### ISSUE THREAD

**Issue by caohaley** [eclipse/openj9#6084]
This issue is similar to issue #5650. `VM_classHasBeenExtended` messages are generated by TR_J9ServerVM::classHasBeenExtended(TR_OpaqueClassBlock *clazz) which asks the client for the value of the flag. The implementation of 'TR_J9VM::classHasBeenExtended' is 
```bool
TR_J9VM::classHasBeenExtended(TR_OpaqueClassBlock * clazzPointer)
   {
   return (J9CLASS_FLAGS(TR::Compiler->cls.convertClassOffsetToClassPtr(clazzPointer)) & J9AccClassHasBeenOverridden) != 0;
   }
```
However, we cache the value of the flag in `clazz->classDepthAndFlags` so we have the value of  `J9AccClassHasBeenOverridden`.

**Comment by caohaley** [comment]
I will work on this one.

**Comment by mpirvu** [comment]
Caching for this flag has a catch: while for class redefinition the caches are invalidated, this is not happening when classes are extended. Thus, it is possible to cache a value of "not extended", then the class gets extended and then serve "not extended" from the cache.

A simple but possibly not efficient workaround is to return an answer from the cache only when the desired flag is set because once set, the flag cannot be reset. This solution is worthwhile only if the cache hit is high enough.

**Comment by caohaley** [comment]
Using the spec performance test, it seems like with the simple solution of only returning from cache if desired flag is set, there are around 1950 messages. In comparison to around 2700 messages the way it is right now.

**Comment by caohaley** [comment]
So it means that for this test, cache hit rate is around 28%. Should I run make Sanity and see how many messages are avoided by using values from the cache (when the flag is set)?

**Comment by mpirvu** [comment]
Instead of the Sanity bucket you should run the AcmeAir benchmark.
Dmitry has it for sure. Annabelle could have it. Harry should have it.

**Comment by caohaley** [comment]
Okay sounds good, I ran AcmeAir benchmark. Using the simple solution, there is around 5500 classHasBeenExtended messages whereas before there were around 11000 messages. So the number of messages reduced by around half for this message.

The implementation being:
```
bool
TR_J9ServerVM::classHasBeenExtended(TR_OpaqueClassBlock *clazz)
   {
   uintptrj_t classDepthAndFlags = 0;
   JITaaS::J9ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
   JITaaSHelpers::getAndCacheRAMClassInfo((J9Class *)clazz, _compInfoPT->getClientData(), stream, JITaaSHelpers::CLASSINFO_CLASS_DEPTH_AND_FLAGS, (void *)&classDepthAndFlags);
   if((classDepthAndFlags & J9AccClassHasBeenOverridden) != 0)
      return true;
   else
      {
      stream->write(JITaaS::J9ServerMessageType::VM_classHasBeenExtended, clazz);
      return std::get<0>(stream->read<bool>());
      }
   }
```

**Comment by mpirvu** [comment]
If this code obtains a 50% hit rate then there is a chance we could do better.
`getAndCacheRAMClassInfo` may send a message to fetch the class from which the flags are cached. If the flags are 0 we send another message just to discover that the flags are still 0. It's true that in the vast majority of the cases the class could be there so this code does not end up in duplicate messages, but it's worth checking this aspect.

**Comment by mpirvu** [comment]
`getAndCacheRAMClassInfo()` could return whether the value came from the cache and if not, then we don't have to send another message.

**Comment by caohaley** [comment]
Yes I also checked `getRemoteROMClassAndMethods` messages which are the messages that the `getAndCacheRAMClassInfo()` sends to cache the class. It seems like the number of those messages are the same, at around 2900 messages. 

Currently `getAndCacheRAMClassInfo()` returns false when the class doesn't exist, so I was wondering if it is okay to return whether or not that value came from the cache.

**Comment by mpirvu** [comment]
> Currently getAndCacheRAMClassInfo() returns false when the class doesn't exist, so I was wondering if it is okay to return whether or not that value came from the cache.

Since the return value of `getAndCacheRAMClassInfo()` is currently not used anywhere we could easily make that modification.

**Comment by caohaley** [comment]
Okay sounds good, I will make that change.
