### ISSUE TITLE
lock reservation on Z?

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#6085]
There is a comment in #2344 (https://github.com/eclipse/openj9/pull/2344#issuecomment-403550883) where @jdmpapin makes the claim:

> I believe lock reservation is not currently enabled on z, so z should be immune to the problem addressed here for the time being.

Just curious, why is lock reservation not enabled on Z?  Was this a point-in-time statement, or a permanent limitation?  @fjeremic

**Comment by fjeremic** [comment]
@NigelYiboYu has the details. IIRC we have a functional problem in ODM in the form of a deadlock with lock reservation enabled. It's been disabled for many months now. We have an item on the queue to get back to enabling it in priority order.
