### ISSUE TITLE
jenkins openj9 test problem 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6093]
Hi  , i use jenkins ,  i want to test openj9  use memory ,
in my jenkins pipline like this,
i run the jenkins job,
docker containers always exit, what shoul i do ?

node {
    
   
  stage('deploy images'){    
   
    
    sh "docker run -i  -v /app:/app -p 10001:8086 adoptopenjdk/openjdk8-openj9 sh"
    
   
   sh "nohup  java -jar /app/openj9dockertest-0.0.1-SNAPSHOT.jar >log.file 2>&1 &"
   sh "exit " 

      }
}
  

This docker ps -a like this:
ONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS                      PORTS                                              NAMES
0c121ebd6ba8        adoptopenjdk/openjdk8-openj9                    "sh"                     57 seconds ago      Exited (0) 57 seconds ago                                                      clever_kalam
0a4f8991b603        adoptopenjdk/openjdk8-openj9                    "sh"                     2 minutes ago       Exited (0) 2 minutes ago                                                       modest_meninsky
a8d7f0f79e71        adoptopenjdk/openjdk8-openj9                    "sh"                     3 minutes ago       Created                                                                        elastic_brattain
b334eab4d6f1        adoptopenjdk/openjdk8-openj9                    "sh"                     9 minutes ago       Exited (0) 8 minutes ago                                                       angry_poitras
2e82d1dcd2bf        adoptopenjdk/openjdk8-openj9                    "sh"                     9 minutes ago       Exited (0) 9 minutes ago                                                       goofy_bhabha
235ec37de029        adoptopenjdk/openjdk8-openj9                    "/bin/bash"              10 minutes ago      Exited (0) 10 minutes ago                                                      quirky_archimedes
ef5656ab4139        adoptopenjdk/openjdk8-openj9                    "sh"                     12 minutes ago      Exited (0) 11 minutes ago                                                      gallant_yalow
db5b0f310e3c        adoptopenjdk/openjdk8-openj9                    "sh"                     12 minutes ago      Exited (2) 12 minutes ago                                                      vibrant_poitras
13f30396f126        adoptopenjdk/openjdk8-openj9                    "/bin/sh"                12 minutes ago      Exited (0) 12 minutes ago                                                      quizzical_mclean

**Comment by DanHeidinga** [comment]
Do you want the Java in the docker image to run the jar?  Maybe try something like:
```
sh "docker run -i  -v /app:/app -p 10001:8086 adoptopenjdk/openjdk8-openj9 java -jar /app/openj9dockertest-0.0.1-SNAPSHOT.jar >log.file 2>&1 &"
```
though you'll need to either mount the jar file into the image (look at docker's `-v` option) or create your own image based on the adopt one that includes the jar.

**Comment by 15838028035** [comment]
Yes! Thanks! 

发自我的 iPhone
