### ISSUE TITLE
jenkins pipline jobDSL 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6101]
Hi , i use jenkins , i want to create jobs use jobDSL, i want to config all the config info in a yml files,

jenkins jobs pipeline load it , maybe the code like this:

/*
*  通用jenkins自动构建pipline文件
* 参数说明:
* GIT_URL:  仓库地址
* GIT_BRANCH: 分支名称
* GIT_CREDIT： jenkins凭据参数
* IS_RUN_SONNAR: 是否执行ssonar扫描
* IS_GEN_DOCKER_IMG： 是否执行docker镜像
* MODEL_NAMES 镜像模块名称
* IS_SEND_EMAIL: 是否发送邮件
*/

node {
    
   
    // 全局获取最新代码
    stage("获取最新代码") {
        // 限制15分钟内完成。
        timeout(time: 15, unit: 'MINUTES') {
             def VARIABLES = readYaml file: '/home/user1/wrapper_variables.yml'
          
          echo "run aaaaaa"
          
           def general = VARIABLES.get('Audio_Model')
             
             params.each { param ->
                // If the boolean parameter is true, it will create the specified wrapper job
                
                    echo "=========="+param.value
                    
                if (param.value == true){
                    def name
                    def version
                  
                  name = param.key
                  
                  echo "name=============" + name
                   
                    def specifications = VARIABLES.get(name)
                   
                   
                        createWrapper(general, specifications)
                    
                }
        }

        }
    }
}

def createWrapper(GENERAL_SPECIFICATIONS, SPECIFICATIONS){
    stage("Build ${SPECIFICATIONS.job_name}"){
      //  def parameters = [:]

      //  parameters = GENERAL_SPECIFICATIONS + SPECIFICATIONS

    //  echo "=======================" + parameters
    //    jobDsl targets: '/home/liaokunpeng/wrapper_template_test', ignoreExisting: false, additionalParameters: parameters
    echo "=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
         jobDsl targets: '/home/user1/wrapper_template_test'
    }
}

when i run the jenkins job, console log 

  
java.io.IOException: Expecting Ant GLOB pattern, but saw '/home/user1/wrapper_template_test'. See http://ant.apache.org/manual/Types/fileset.html for syntax
	at hudson.FilePath.glob(FilePath.java:1955)
	at hudson.FilePath.access$3400(FilePath.java:213)
	at hudson.FilePath$ListGlob.invoke(FilePath.java:1936)

i am every sure /home/user1/wrapper_template_test exists ,

i have install the jenkins job dsl plugin

what sould i do  next ?

**Comment by DanHeidinga** [comment]
Sorry, we can't provide support for general Jenkins queries.  If there's an issue related to OpenJ9, we're able to help with that.
