### ISSUE TITLE
sonarqube use memory too up !

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6103]
hi, i use jenkins , use sonarqube to scanner java code ,
user docker run jenkins , sonarqube ,

run docker stats sonarqube , print the message out:

CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
4c51eb745700        sonarqube           1.31%               2.339GiB / 23.37GiB   10.01%              94.1MB / 11.8MB     3.77MB / 2.51GB     161

sonarqube use memory too up ! about 2.4G , 
how can i make sonarqube  memory lower ?
i run sonarqube not with database mysql, with memory

**Comment by DanHeidinga** [comment]
Sorry, we can't provide support for sonarqube.  We can help with issues with the JVM but can't provide support for other applications.
