### ISSUE TITLE
jdk_x64_linux_openj9_8u212b04_openj9-0.14.2.tar.gz   tar failure 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6104]
tar -zxvf OpenJDK8U-jdk_x64_linux_openj9_8u212b04_openj9-0.14.2.tar.gz 
jdk8u212-b04/
jdk8u212-b04/ASSEMBLY_EXCEPTION
jdk8u212-b04/jre/
jdk8u212-b04/jre/ASSEMBLY_EXCEPTION
jdk8u212-b04/jre/bin/
jdk8u212-b04/jre/bin/tnameserv
jdk8u212-b04/jre/bin/jextract
jdk8u212-b04/jre/bin/unpack200
jdk8u212-b04/jre/bin/policytool
jdk8u212-b04/jre/bin/java
jdk8u212-b04/jre/bin/orbd
jdk8u212-b04/jre/bin/servertool
jdk8u212-b04/jre/bin/pack200
jdk8u212-b04/jre/bin/rmid
jdk8u212-b04/jre/bin/keytool
jdk8u212-b04/jre/bin/rmiregistry
jdk8u212-b04/jre/bin/jjs
jdk8u212-b04/jre/LICENSE
jdk8u212-b04/jre/lib/
jdk8u212-b04/jre/lib/jexec
jdk8u212-b04/jre/lib/psfontj2d.properties
jdk8u212-b04/jre/lib/ddr/
jdk8u212-b04/jre/lib/ddr/_the.j9ddr.jar_manifest
jdk8u212-b04/jre/lib/ddr/j9ddr.jar

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by DanHeidinga** [comment]
Does the checksum for the `tar.gz` file match the one you've downloaded?  The checksum for the Adopt builds can be downloaded from this page: https://adoptopenjdk.net/archive.html

It might be simpler to download the file again and try untaring the new file.

**Comment by 15838028035** [comment]
Thanks! I am in China, often down failure, is there other way to get it !

发自我的 iPhone

**Comment by DanHeidinga** [comment]
This would be a good question to ask at AdoptOpenJDK.  They provide the binaries and downloads infrastructure.  

I'm not aware of anything other than the website and API and I believe both are served by the same backend. 

Try asking on the https://adoptopenjdk.net/slack.html or create an issue in the https://github.com/AdoptOpenJDK/TSC repo and they'll route it appropriately
