### ISSUE TITLE
how can i download a apline openj9 jdk neightly build ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6105]
how can i download a apline openj9 jdk neightly build ?

**Comment by DanHeidinga** [comment]
There are alpine-based docker images available for OpenJ9 from Adopt's dockerhub page: https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9

See the `alpine-nightly`, `alpine-jre-nightly`, `alpine-nightly-slim` tags.

The alpine images are using the regular OpenJ9 nightly builds in an alpine package.  

@dinogun Can you confirm that's the case?

**Comment by 15838028035** [comment]
No! I am not use docker on my one Linux host , I only want to download a memory lower openj9 

发自我的 iPhone

**Comment by DanHeidinga** [comment]
It's the same OpenJ9 build used in the alpine image as in the regular image.  The size benefit of the alpine package is the smaller OS.

**Comment by 15838028035** [comment]
Okay! Thanks ! 

发自我的 iPhone
