### ISSUE TITLE
jenkins pipline clearWs

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6106]
HI, from this project ,
jenkins pipline 

cleanWs()

i see call  ,what the plugin jenkins install ?

**Comment by pshipton** [comment]
@adam

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
Workspace Cleanup Plugin
https://jenkins.io/doc/pipeline/steps/ws-cleanup/
