### ISSUE TITLE
jps should add file path info

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6124]
Hi, when i use jps, 
message print like this 
123456  aa

jps not show file path info 

jps should add file path info ？

**Comment by pdbain-ibm** [comment]
@15838028035 
The OpenJ9 implementation of `jps` matches that of HotSpot.  The specified behaviour, per the man page, is to print the application's main class or the jar file name, omitting the package information or jar file path.  `jps -l` will print the file path for the jar file.

**Comment by 15838028035** [comment]
There are two tomcat run, Jps -l can not not filepath 

发自我的 iPhone

**Comment by pdbain-ibm** [comment]
1. Which operating system are you running? Linux?
2. Assuming Linux, would you please sent me the output of `ps -f -p <pid>` where `<pid>` is the process ID of your Tomcat instance
3. Please also send the output of `jps -v`
4. `jstack -p <pid>` will print the system properties for the process.  Could you send that too? 

As the above may be lengthy, I suggest adding the information as `.txt` files.

Thank you

**Comment by 15838028035** [comment]
Thanks

发自我的 iPhone

**Comment by pdbain-ibm** [comment]
Your query did expose a bug in `jps`: `jps` without arguments displays processes launched via `-jar foo/bar.jar` as `jar` rather than `bar.jar`.  I am testing a fix now.

**Comment by keithc-ca** [comment]
Fixed via #6134.
