### ISSUE TITLE
jps problem

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6126]
`java -version
`

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
Eclipse OpenJ9 VM (build openj9-0.14.2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190521_315 (JIT enabled, AOT enabled)
OpenJ9   - 4b1df46fe
OMR      - b56045d2
JCL      - a8c217d402 based on jdk8u212-b04)

` free -lh
`

Mem:           125G        113G        1.5G        570M         10G         10G
Low:           125G        124G        1.5G
High:            0B          0B          0B
Swap:          4.0G        4.0G          0B

when i run the command 
` jps 
`

This long time to print message, sometime dided ?

what should i do ?

change large jdk?

**Comment by DanHeidinga** [comment]
fyi @pdbain-ibm

**Comment by pdbain-ibm** [comment]
More likely one of the target processes is having trouble communicating with the `jps` process.

Please run `jps` with `-J-Dcom.ibm.tools.attach.logging=yes`.  That will produce a file `<pid>.log`, where `pid` is the ID of the `jps` process, and attach the file.

You can also communicate with me directly via Slack at https://openj9.slack.com.  You can join the channel by requesting an invitation: https://join.slack.com/t/openj9/shared_invite/enQtNDU4MDI4Mjk0MTk2LWM2MjliMTQ4NWM5YjMwNTViOTgzMzM2ZDhlOWJmZTc1MjhmYmRjMDg2NDljNGM0YTAwOWRiZDE0YzI0NjgyOWI

**Comment by pdbain-ibm** [comment]
1. Does `jps` produce any output on the console?  If so, please send it to me.
2. Please also test with `jps -q` and inform me if that works reliably.

**Comment by 15838028035** [comment]
Yes! There are not message print, maybe sided! 

发自我的 iPhone

**Comment by 15838028035** [comment]
jps -q  print output pid info

**Comment by 15838028035** [comment]
free -lh 

    total        used        free      shared  buff/cache   available
Mem:           125G        119G        1.9G        626M        4.6G        4.9G
Low:           125G        123G        1.9G
High:            0B          0B          0B
Swap:          4.0G        4.0G        1.7M

top -u user1 message output 

40609 user1+  20   0  158388   2812   1504 R   5.9  0.0   0:00.02 top                                                                                                                                                       
 58680 user1+  20   0 44.257g 2.867g   7988 S   5.9  2.3  92:12.88 java                                                                                                                                                      
149529 user1+  20   0 42.376g 3.508g   8020 S   5.9  2.8  10:56.90 java                                                                                                                                                                      
  1890 user1+  20   0 2991240 553884   6608 S   0.0  0.4  10:09.49 java                                                                                                                                                                
  2720 user1+  20   0 2965848 542664   6544 S   0.0  0.4   9:49.81 java                                                                                                                                                      
  3505 user1+  20   0 2937056 356212   6360 S   0.0  0.3   5:33.47 java                                                                                                                                                      
  4109 user1+  20   0 3116880 381820   6188 S   0.0  0.3  41:22.46 java                                                                                                                                                      
  5069 user1+  20   0 3059204 423276   6508 S   0.0  0.3  43:07.25 java                                                                                                                                                      
  9168 user1+  20   0 37.453g 1.304g  13208 S   0.0  1.0   1:59.14 java                                                                                                                                                      
 12618 user1+  20   0 22.795g 687600   5896 S   0.0  0.5 157:47.03 java                                                                                                                                                      
 13537 user1+  20   0 53.049g 4.913g   5960 S   0.0  3.9 152:25.10 java                                                                                                                                                      
 22281 user1+  20   0  113124    292     12 S   0.0  0.0   0:00.00 bash                                                                                                                                                      
 22295 user1+  20   0 32.357g 770616   6456 S   0.0  0.6  15:41.49 java                                                                                                                                                      
 22426 user1+  20   0  113128    304      8 S   0.0  0.0   0:00.00 bash                                                                                                                                                      
 22441 user1+  20   0 32.546g 1.279g   6884 S   0.0  1.0  18:39.49 java                                                                                                                                                      
 26648 user1+  20   0  150516   1712    216 S   0.0  0.0   0:00.93 sshd                                                                                                                                                      
 26655 user1+  20   0  116700   2648    864 S   0.0  0.0   0:00.31 bash                                                                                                                                                      
 27211 user1+  20   0  150364   2328   1004 S   0.0  0.0   0:00.00 sshd                                                                                                                                                      
 27220 user1+  20   0  116692   3356   1700 S   0.0  0.0   0:00.08 bash                                                                                                                                                      
 27617 user1+  20   0 41.739g 3.436g   6044 S   0.0  2.7  17:06.88 java                                                                                                                                                      
 27935 user1+  20   0 11.184g 285296  11072 S   0.0  0.2  12:56.80 java                                                                                                                                                      
 38327 user1+  20   0 42.122g 3.511g   6084 S   0.0  2.8  19:56.96 java                                                                                                                                                      
 44996 user1+  20   0 16.944g 1.412g   6924 S   0.0  1.1  52:48.83 java                                                                                                                                                      
 45947 user1+  20   0 43.755g 6.241g   7100 S   0.0  5.0  18:26.95 java                                                                                                                                                      
 49888 user1+  20   0  150364   1712    304 S   0.0  0.0   0:10.23 sshd                                                                                                                                                      
 49889 user1+  20   0  116792   2800   1000 S   0.0  0.0   0:01.19 bash                                                                                                                                                      
 53859 user1+  20   0 39.609g 954368   7940 S   0.0  0.7   8:05.60 java                                                                                                                                                      
 55398 user1+  20   0 41.355g 3.211g   5800 S   0.0  2.6  18:09.43 java                                                                                                                                                      
 56343 user1+  20   0 43.437g 2.795g   7992 S   0.0  2.2  36:58.74 java                                                                                                                                                      
 60250 user1+  20   0 41.478g 4.013g   8024 S   0.0  3.2  12:11.04 java                                                                                                                                                      
 65718 user1+  20   0 12.521g 515316  13052 S   0.0  0.4  22:53.00 java                                                                                                                                                      
 80200 user1+  20   0  150364   1656    292 S   0.0  0.0   0:10.38 sshd                                                                                                                                                      
 80209 user1+  20   0  116696   2816   1052 S   0.0  0.0   0:00.17 bash                                                                                                                                                      
 80329 user1+  20   0  150364   1648    272 S   0.0  0.0   0:01.62 sshd                                                                                                                                                      
 80348 user1+  20   0  116696   2656    880 S   0.0  0.0   0:00.22 bash                                                                                                                                                      
109953 user1+  20   0 42.437g 3.880g   6068 S   0.0  3.1  18:22.17 java                                                                                                                                                      
112656 user1+  20   0 11.938g 285564  11096 S   0.0  0.2  14:11.26 java                                                                                                                                                      
125111 user1+  20   0  150364   1684    272 S   0.0  0.0   0:01.21 sshd                                                                                                                                                      
125120 user1+  20   0  116696   2704    936 S   0.0  0.0   0:00.17 bash                                                                                                                                                      
145979 user1+  20   0 41.794g 4.221g   5392 S   0.0  3.4  35:12.13 java                                                                                                                                                                  
172777 user1+  20   0 42.058g 3.025g   5744 S   0.0  2.4  17:59.11 java                             


jps not put message out memory lower caused ?

**Comment by pdbain-ibm** [comment]
It unlikely to be a memory problem.  More probable is that `jps` cannot attach to one or more of the target processes.  Would you kindly run `jps  -J-Dcom.ibm.tools.attach.logging=yes` and send me the resulting log file (it will be something like `1234.log`).

Thank you.

**Comment by 15838028035** [comment]
I change openjdk8 to openj9 ,some java application not restart , is this reason?

发自我的 iPhone

**Comment by pdbain-ibm** [comment]
OpenJDK (with HotSpot) and OpenJ9 use different implementations of Attach API, upon which `jps` is based (at least in the case of OpenJ9; I cannot speak for HotSpot).  OpenJ9's `jps` will not show or attach to HotSpot Java processes.

If you are using a mixture of HotSpot and OpenJ9 JDKs, ca you confirm that you are running the OpenJ9 copy of `jps`?

**Comment by 15838028035** [comment]
I only want to use openj9 

发自我的 iPhone

**Comment by JasonFengJ9** [comment]
@15838028035 are you still experiencing the problem reported initially? If so, are you running any `HotSpot` JVM?

**Comment by pdbain-ibm** [comment]
@15838028035 do you have a reply to https://github.com/eclipse/openj9/issues/6126#issuecomment-508307250?

**Comment by pdbain-ibm** [comment]
@DanHeidinga or @pshipton I suggest closing this issue.
