### ISSUE TITLE
Enable a connection timeout in JITaaS

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6130]
Networks can be flaky and connections can be broken or take a very long time. JITaaS needs to be able to cope with such situations and we already have the ability of setting a timeout at the socket level with suboption `timeout=`:

```
   if (setsockopt(sockfd, SOL_SOCKET, SO_RCVTIMEO, (void *)&t, sizeof(t)) < 0)
      {
      perror("Can't set option SO_RCVTIMEO on socket");
      exit(-1);
      }
   if (setsockopt(sockfd, SOL_SOCKET, SO_SNDTIMEO, (void *)&t, sizeof(t)) < 0)
      {
      perror("Can't set option SO_SNDTIMEO on socket");
      exit(-1);
      }
```

Currently the timeout value is set to 0 which means " wait forever".
We need to set a sensible timeout value and then test thoroughly the behavior, simulating faulty situations.
The question becomes: "what is a sensible timeout value"? Sometimes temporary network hiccups can last for a few seconds, but I don't think we can afford that. Since we have the ability to perform the compilations locally we should do so if a response takes a large amount of time, say more than 1 second. In that second we have to include the time the server does useful work. For that matter I propose we gather statistics about the elapsed time between the moment the server receives a message and the moment it sends the next message. Using a slow machine for the server and finding the maximum inter-query time for the server should be good enough.

If a timeout situation is encountered, the client should drop the connection and perform a compilation locally. If free physical memory is low we may have to resort to a cheap local compilation to avoid native OOM situations.

The JITaaS server should have timeouts too, because we don't want to block a compilation thread forever. However, timeout values at the server could be larger (say 4 seconds)

**Comment by mpirvu** [comment]
We should collect by default statistics on how often the timeout situation was encountered.

**Comment by a7ehuo** [comment]
I'll take a look at this one.

**Comment by a7ehuo** [comment]
With the following server-client setup, the timeout values are:
- Max write on the server ~50ms 
- Max read on the client ~316ms 

```
=== Setup Details ===
Server <=> Client (local VM machine <=> Fyre) 
1. 1 CPU: cpulimit -e java -c 1 -l 100
2. -Xjit:compilationThreads=1
3. OpenSSL connection 
4. Instrumented code available at https://github.com/a7ehuo/openj9/commit/13130ca1c432bcf4eb8eb24a0824d9370f08f00f
5. Run sanity _jit_jit_* (four tests) at optLevel=cold, optLevel=warm, optLevel=hot
6. On server: find the max elapsed time between the current write and the last read, only when read/write message types are matched and TR::comp() exists 
7. On client: find the max elapsed time between the current read and the last write, only when read/write message types are matched and TR::comp() exists
======================
```
```
======================================================== 
Server: Max write elapsed time from last read 47998 us
#JITaaS: stream 00007FF9C1254CD0 server write msgType 217: currentTS 1457782535 us, elapsedTime 47998 us, (hot) java/util/regex/Pattern$StartS.match(Ljava/util/regex/Matcher;ILjava/lang/CharSequence;)Z

========================================================
Client: Max read elapsed time from last write 315459 us
#JITaaS: stream 00007F4CAE2992C0 client read msgType 127: currentTS 1970841851 us, elapsedTime 315459 us, (hot) java/lang/ClassLoader.loadClassHelper(Ljava/lang/String;ZZ)Ljava/lang/Class;

========================================================
Message type:
   VM_getClassFromSignature = 217;
   ResolvedMethod_getRemoteROMClassAndMethods = 127;
```
