### ISSUE TITLE
OpenJ9 Java 12 does not support enable-preview

### ISSUE THREAD

**Issue by lostiniceland** [eclipse/openj9#6140]
Running Openliberty 19.0.0.5 with a OpenJ9 12 JRE while using preview-features (switch expressions) it is necessary to pass --enable-preview to the JVM.

However running this option on OpenJ9 results in the following error:
```
JVMJ9VM007E Nicht erkannte Befehlszeilenoption: --enable-preview
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Running the same setup on a OpenJDK (Hotspot) 12 JRE works as expected.

**Comment by DanHeidinga** [comment]
@lostiniceland what's the `java -version` from the build you're using?

**Comment by DanHeidinga** [comment]
I've confirmed this works in the latest release:
```
$ docker run --rm -it adoptopenjdk/openjdk12-openj9 java --enable-preview -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.1, JRE 12 Linux amd64-64-Bit Compressed References 20190418_66 (JIT enabled, AOT enabled)
OpenJ9   - 412258978
OMR      - 4a4278e6
JCL      - 9fad1c64af based on jdk-12.0.1+12)
```

If you're still seeing issues with the latest release, we'll need to investigate further why it would be different.

**Comment by lostiniceland** [comment]
`marc@tux:~/Development/environment/jdk-12.0.1+12-jre/bin> ./java -version --enable-preview
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.1, JRE 12 Linux amd64-64-Bit Compressed References 20190418_66 (JIT enabled, AOT enabled)
OpenJ9   - 412258978
OMR      - 4a4278e6
JCL      - 9fad1c64af based on jdk-12.0.1+12)
marc@tux:~/Development/environment/jdk-12.0.1+12-jre/bin> ./java --enable-preview -version
JVMJ9VM007E Nicht erkannte Befehlszeilenoption: --enable-preview
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
`

I've just downloaded the latest release and unzipped it.

**Comment by pdbain-ibm** [comment]
Please test with one of the nightly builds.

**Comment by lostiniceland** [comment]
Yes, the nightly build from 17. June 2019 works

```
marc@tux:~/Development/environment/jdk-12.0.2+0+preview/bin> ./java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+0-201906160904)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-506df00a3, JRE 12 Linux amd64-64-Bit Compressed References 20190616_120 (JIT enabled, AOT enabled)
OpenJ9   - 506df00a3
OMR      - a6e5f83d
JCL      - 35a9302515 based on jdk-12.0.2+0+preview)
```

```
marc@tux:~/Development/environment/jdk-12.0.2+0+preview/bin> ./java --enable-preview
...usage....
```

Interesting, the "openjdk version" in the preview has the same version as the release version, but thats probably just not updated yet.

**Comment by DanHeidinga** [comment]
> (so from this point of view it looks like the docker-images are ignoring the option)

I had forgotten that the docker images set `-XX:+IgnoreUnrecognizedVMOptions` by default :
 https://github.com/AdoptOpenJDK/openjdk-docker/blob/ce8b120411b131e283106ab89ea5921ebb1d1759/12/jdk/ubuntu/Dockerfile.openj9.releases.full#L60

Disabling that reproduces your results:
```
$ docker run --rm -it adoptopenjdk/openjdk12-openj9 java -XX:-IgnoreUnrecognizedVMOptions --enable-preview -version
JVMJ9VM007E Command-line option unrecognised: --enable-preview
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Thanks for confirming that the nightlies are good.  The next release will ship in mid-July and will include this fix.

Sorry for the confusion on this.

**Comment by lostiniceland** [comment]
/reopen

Unfortunately the issue is not resolved by the latest release. Still getting the same error when using preview-features

```
> docker pull adoptopenjdk/openjdk12-openj9
> docker run --rm -it adoptopenjdk/openjdk12-openj9 java -XX:-IgnoreUnrecognizedVMOptions --enable-preview -version
JVMJ9VM007E Command-line option unrecognised: --enable-preview
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by DanHeidinga** [comment]
Interesting. I just pulled the latest docker file and got:
```
$ docker run --rm -it adoptopenjdk/openjdk12-openj9 java -XX:-IgnoreUnrecognizedVMOptions --enable-preview -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 12 Linux amd64-64-Bit Compressed References 20190719_151 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - 06c2cc3322 based on jdk-12.0.2+10)
```

Can you confirm that `docker run --rm -it adoptopenjdk/openjdk12-openj9 java -XX:-IgnoreUnrecognizedVMOptions -version` shows `build openj9-0.15.1` in the version output?

**Comment by lostiniceland** [comment]
The version from yesterday still showed 0.14.1 so I did another pull and to suprise there was a new image. The new image 0.15.1 works.

Bad timing.

**Comment by DanHeidinga** [comment]
I'm glad it works for you now.  Thanks for trying again.
