### ISSUE TITLE
sanity.system_Nightly MauveSingleThreadLoadTest_OpenJ9_0 NPE

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#6145]
Failure link
------------
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_xl_Nightly/64/tapResults/

Optional info
-------------

Failure output
--------------

```
===============================================
Running test MauveSingleThreadLoadTest_OpenJ9_0 ...
===============================================
LT  PASS: gnu.testlet.java.beans.PropertyDescriptor.constructorTest2: new PropertyDescriptor() (should fail) (number 0)
LT  Test failed:
LT  java.lang.NullPointerException
LT  	at java.desktop/java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:109)
LT  	at java.desktop/java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:74)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest2.constructor1Tests(constructorTest2.java:600)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest2.test(constructorTest2.java:700)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:831)
LT  <<<
```

**Comment by JasonFengJ9** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly/63/tapResults/
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_sanity.system_x86-64_linux_Nightly/66/tapResults/

**Comment by pshipton** [comment]
First failure:
OpenJ9: b9829d7
OMR: 9f5d885
OpenJDK8: 0843c3e - openj9-openjdk-jdk8
OpenJDK11: ad988f0 - openj9-openjdk-jdk11
OpenJDK12: 35a9302 - openj9-openjdk-jdk12

Last passing:
OpenJ9: 3d9ad73
OMR: 6eea707
OpenJDK8: 3f30074 - openj9-openjdk-jdk8
OpenJDK11: 2a60f1f - openj9-openjdk-jdk11
OpenJDK12: e941d38 - openj9-openjdk-jdk12

3d9ad73...b9829d7
eclipse/omr@6eea707...9f5d885
ibmruntimes/openj9-openjdk-jdk8@3f30074...0843c3e
ibmruntimes/openj9-openjdk-jdk11@2a60f1f...ad988f0

**Comment by pshipton** [comment]
See also #6146

**Comment by pshipton** [comment]
@andrewcraik fyi this blocker

**Comment by andrewcraik** [comment]
see #6146 that we believe there is a fix for the NPE already merged in OMR

**Comment by andrewcraik** [comment]
@liqunl can you verify this one is fixed with the OMR fix for the CFGSimplifier from last week?

**Comment by liqunl** [comment]
No, it doesn't have the fix for CFGSimplifier.

**Comment by pshipton** [comment]
Seems to be resolved now.
