### ISSUE TITLE
64-bit z/OS Java SDK allows Xmso values less than the smallest possible native stack of 1M

### ISSUE THREAD

**Issue by PhilWakelin** [eclipse/openj9#6150]
As the smallest possible native stack size on 64-bit z/OS is 1MB, the default Xmso value was increased from 256/384K to 1M in issue [5156](https://github.com/eclipse/openj9/issues/5156)

However,  applications that have historically set Xmso values <1M  are still exposed to future failures as the JRE validates native stack frames used using whatever the Xmso value is set to.

As an example if Xmso128K is set, then the JVM will fail if too many stack frames are used such as if starting a debug session, when in-fact on the 64bit z/OS JVM the LE stack is a min of 1M in size and allocated in a min of 1M segments, so plenty of native storage is actually available See [LE Programming Ref](https://www.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3SA380683/$file/ceea300_v2r3.pdf)

**Comment by pshipton** [comment]
@PhilWakelin should the stack size always be rounded up to the next 1MB increment?

**Comment by PhilWakelin** [comment]
@pshipton yes I think this is the best behavior, as z/OS will allocate 64-bit storage in megabyte increments. It could be possible to have the LE THREADSTACK64 set to a larger minimum size or increment size than 1M but the default is THREADSTACK64(OFF,1M,1M,128M) meaning 1M initial and 1M increments, so rounding Xmso to the next 1MB increment would match this.

**Comment by DanHeidinga** [comment]
Is there an (inexpensive) zOS call to get the THREADSTACK64 size from LE?  We'd rather use the correct min value than hardcode 1M as the usual case.

**Comment by joransiu** [comment]
From LE team regarding how to query the THREADSTACK64 values:

> We keep the values in our runtime option control blocks (CEEOCB).
> https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.ceev100/ocbappen.htm
>            4      (4) SIGNED           8   CEEOCB_THREADSTACK64_INIT_SIZE
>           12      (C) SIGNED           8   CEEOCB_THREADSTACK64_INCR_SIZE
>  
> And it can be located by CEEEDBOPTCB
> https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.ceev100/celedb.htm
>  
> It is a very complex control block containing many variable length fields.
>  
> Note that those control blocks should never be changed by user, or there will be unexpected program behaviors.

**Comment by SueChaplain** [comment]
If this requires a doc change we need an issue opening in the docs repo: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md

**Comment by pshipton** [comment]
I made an attempt to read the values from CEEOCB, but got zeros. The code is in https://github.com/pshipton/omr/tree/threadstack and was based on https://github.com/eclipse/omr/blob/65ef0ad6a46409ff2fc2c39276a300a1cf65a27d/port/zos390/omrsignal_context.c#L64. My next step is to double check I didn't miss something, and validate the ceeocb_options enum in omr/port/zos390/omrceeocb.h
At this point I don't expect it to make the 0.17 release, moving forward.

**Comment by pshipton** [comment]
As far as I can tell the code is correct. Reading THREADSTACK64 I get the following. Given that init_size and incr_size are zero, we can't use these values to control the behavior of the VM.
on = false
init_size = 0
incr_size = 0
max_size = 0xe0000000

**Comment by pshipton** [comment]
@PhilWakelin yes CEEOCB_STACK64_INIT_SIZE and INCR are also 0, although this one has ON true. The MAX is the same value 0xe0000000.

**Comment by pshipton** [comment]
Ror comparison, these are the CEEOCB_STACK values. For the record, I'm running on on V2R3 machine.
CEEOCB_STACK_INIT_SIZE 0x20000
CEEOCB_STACK_INCR_SIZE 0x20000
CEEOCB_STACK_DSINIT_SIZE 0x80000
CEEOCB_STACK_DSINCR_SIZE 0x20000

**Comment by pshipton** [comment]
The original request to make 1MB the minimum -Xmso on z/OS, which is the most important aspect, was fixed via #7304. Rounding values bigger than 1MB should use OS support to ensure the rounding is being done correctly to the values used by the OS. As the OS support doesn't seem to be present, closing this Issue as completed.
