### ISSUE TITLE
TravisCI Pass Condition is not sufficiently robust

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9#618]
Because our Travis builds simply check for `java -version` 

https://github.com/eclipse/openj9/blob/9428bb89877946185791a8852dcbd3fd4c079c1c/.travis.yml#L87-L88

There is a possibility for dynamic linking errors to go un-noticed: 

    The command "make images" exited with 0.
    0.13s$ ./build/linux-x86_64-normal-server-release/images/jdk/bin/java -version
    JVMJ9VM011W Unable to load j9jit29: /home/travis/build/eclipse/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/images/jdk/lib/compressedrefs/libj9jit29.so: undefined symbol: _ZN3OMR3X8628RegisterDependencyConditions12useRegistersEPN2TR11InstructionEPNS2_13CodeGeneratorE
    openjdk version "9-internal"
    OpenJDK Runtime Environment (build 9-internal+0-adhoc.travis.openj9-openjdk-jdk9)
    Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171117_000000 (JIT disabled, AOT disabled)
    OpenJ9   - 5fa86c1
    OMR      - 2d0112b4
    OpenJDK  - e180b84d based on )
    

The above clearly should be failing to pass the test, and yet gets a green checkmark on Travis.

**Comment by DanHeidinga** [comment]
Travis builds are a sniff test for "does this compile on x86".
Testing happens through the Jenkins pull request builder plugin.  The project is looking at ways to get x86 hardware in Jenkins. 

Closing this as travis builds aren't the focus right now.
