### ISSUE TITLE
how much max memory used tomcat default config ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6181]
Hi , i use java openjk8,  tomat 8,
use ps monitor  memory ,
tomcat8 memory up to 7GB

my server memory is 128GB

i don't config any jvm params
how much max memory used tomcat default config ?

**Comment by pshipton** [comment]
Is this a question about Hotspot, or OpenJ9? 
OpenJ9 jdk8 uses a default -Xmx512m, see https://www.eclipse.org/openj9/docs/openj9_defaults/
