### ISSUE TITLE
Deciding on a replacing name for JITaaS

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6203]
@mstoodle  brought to my attention that `JITaaS` can be easily mispronounced and therefore we need to find a better name. This issue serves as a discussion forum for coming up with a replacement.

Currently, `JITaaS` is used in:
1) Filenames. E.g.: JITaaSCompilationThread.cpp, JITaaSPersistentCHTable.cpp
2) Namespaces
3) Data structures. E.g.: JITaaSHelpers, JITaaSPersistentClassInfo, JITaaSIProfiler
4) vlog and error messages
5) Name of options: -XX:JITaaSClient
6) Soon to come, #ifdefs

A grep over the code base shows ~1500 hits.

Alternate names being proposed:
- JITservice
- JITsrvc
- JITserv
- OopJIT (from out-of-process JIT)
- RemoteJIT

The list is still open!

**Comment by fjeremic** [comment]
- :+1: for JITService (with proper camel-casing of "Service") as it's simple and understandable
- :-1: for JITsrvc, JITserv as the abbreviations do not add any value to me
- :-1: for OopJIT as "OOP" conflicts with Object Oriented Programming

**Comment by dsouzai** [comment]
Could we just do CaaS (Compiler as a Service)?

**Comment by smlambert** [comment]
JITAAS also used as a possible TEST_FLAG value (to create a server, to enable testing of this service/feature).
<img width="390" alt="Screen Shot 2019-06-20 at 8 26 42 PM" src="https://user-images.githubusercontent.com/2836948/59872380-e43d1b00-9399-11e9-90cf-d993767d0b5c.png">

**Comment by andrewcraik** [comment]
- 👍 JITService (with proper camel-casing)
- 👎 OopJIT (OOP was too overloaded and not intuitive)
- 👎 JITsrvc and JITserv - abbreviations are not helpful
Could also go for JITServer

**Comment by charliegracie** [comment]
I like `JITServer` for the server part... A client that wants to connect to a JIT Service could issue a command line `-XX:+UseJitServer` or `-XX:+UseJitCompiliationServer` but the second one is quite long.

**Comment by mpirvu** [comment]
For what is worth I prefer abbreviations because long names make long lines which are harder to read. This is probably the reason ClassHierarchyTable is just `CHTable` and Testarossa is just `TR` (Testarossa_PersistentClassHierarchyTable is quite a name).
For that reason I second the `CaaS` proposal.

**Comment by charliegracie** [comment]
That is what code assist or completion or whatever you IDE calls it is for. Abbreviations make typing things simpler but make reading and understanding the code much more difficult, especially for new people to the code base. It is similar to using `aa` for a local variable name. Does that stand for archiveAnalyzer or just the 27th local?

I am fine with using the word Compiler instead of JIT (although every time I talk external to the team it is a point of confusion) but doesn't CaaS have exactly the same issue is JITaaS? Why change anything if the same issue exists with mis typed characters?

**Comment by mpirvu** [comment]
With JITaaS, it's not about spelling, but about pronunciation. People tend to pronounce it as two syllables JIT-aas, the second syllable being the offending one. With CaaS it's just one syllable. It's the same as with PaaS, IaaS, SaaS, etc.

Heh, I just received an email saying: 'This is to inform you that your on-premises server has been activated in Security as a Service (SECaaS).'

**Comment by xasx** [comment]
Quickly check for CaaS already being in use for Container as a Service

https://duckduckgo.com/?q=container+as+a+service

Although it is not that widespread, a handful of people might get confused.

**Comment by mpirvu** [comment]
> CaaS already being in use for Container as a Service

That's unfortunate, but not entirely surprising as by now almost every letter of the alphabet is taken. Even Anything-as-a-service exists: `XaaS`

**Comment by DanHeidinga** [comment]
> I like JITServer for the server part... 

I second @charliegracie's comment.  A term like `JITServer` or `OffLoadCompile` would be my preference as they describe the functionality and avoid having to decode acronyms.

**Comment by fjeremic** [comment]
I think `JITServer` is also good given all the information here.

**Comment by mpirvu** [comment]
I am not opposed to JITServer, though I have a hard time coming up with an option to switch the JDK to the 'client' persona. It used to be `-XX:JITaaSClient`, but now `-XX:JITServerClient` doesn't work.
Even variations like `XX:JITServer:client`, `XX:JITServer:clientmode` etc don't look good in my opinion.

**Comment by dsouzai** [comment]
Another suggestion, given the previous comment:

`-XX:RemoteCompiler:server` and `-XX:RemoteCompiler:client`

"RemoteCompiler` is perhaps not necessarily the best name, but something along those lines..

**Comment by ashu-mehra** [comment]
why not just `JITServer` and `JITClient`?

**Comment by charliegracie** [comment]
`-XX:+UseJitServer` is the option the client would use in my suggestion above. I would hope / assume that eventually the actual server is not a full JavaVM per se but rather simple server that accepts connections and hands them off to the Compiler. In the meantime if that is not true then the sever could use an option like `-XX:EnableJitServer` or something similar until it isn't launched via a java command line.

Simple options like -XJITServer or -XJITClient do not say enough in my opinion. Something that explains what is happening is easier to understand. The `+` and `-` for enabling / disabled a feature is the common standard now for JVMs.

**Comment by DanHeidinga** [comment]
Is there an option to tell the client where the server is located?  Looking at the minimum set of options / config files to set up that connection may help with choosing reasonable option names

**Comment by pshipton** [comment]
+1 for `+` and `-` options like `-XX:+UseJitServer` and `-XX:-UseJitServer` or some variable of that.

**Comment by mpirvu** [comment]
> Is there an option to tell the client where the server is located

It used to be `-XX:JITaaSClient:server=...,port=...,timeout=...`

**Comment by mpirvu** [comment]
>  I would hope / assume that eventually the actual server is not a full JavaVM per se but rather simple server that accepts connections and hands them off to the Compiler

The JDK can be configured to run as a regular JDK, as a JITaaS client or as a server. So, it is a full JavaVM that is `frozen` right after init (no Java application needs to be specified).

**Comment by mstoodle** [comment]
Anyone else notice the duality with Hotspot's `-server` and `-client` options? :(

Nonetheless, I personally prefer something like:
* `-XX:+StartAsJitServer` to activate the JVM as a JIT server (open to different verbs than `StartAs`)
* `-XX:+UseJitServer` to configure the JIT as a client JIT

The client can then also specify options like:
* `-XX:JitServerPort=<N>`
* `-XX:JitServerHost=<hostname/ip>`
* `-XX:JitServerTimeout=<n>`
* ...

As verbose as at is, this scheme follows the common naming conventions in the Java ecosystem and the options are meaningful and hopefully relatively easy to understand even without reading the documentation.

**Comment by mstoodle** [comment]
I guess that roughly translates to "JIT Server" is the name to replace JITaaS with :) (i.e. the point of this issue).

**Comment by mstoodle** [comment]
@mpirvu did you want to set a deadline by which to decide the new name, just to ensure this discussion comes to a definite conclusion? And by "decide" do we mean a committer vote or something else?

**Comment by mpirvu** [comment]
All of the people commenting here agree with (or have no objections for) JITServer, so I think that a vote is not necessary.
I'll let the issue open for another day and if nobody comes up with some valid objections, JITServer it is.

**Comment by mpirvu** [comment]
Since no other opinions were expressed we will proceed with changing `JITaaS` into `JITServer` throughout the code.

Public options will be
`-XX:+StartAsJitServer` to activate the JVM as a JIT server
`-XX:+UseJitServer` to allow the JVM to send remote compilation requests

@smlambert when we change the options and deliver them to master we need to address the testing infrastructure.

Thank you all for your input on this matter!
