### ISSUE TITLE
Update release notes related to "Signal Handling"

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#6207]
[0.14 Release Notes](https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.14/0.14.md)

In the above release notes, the following issue is reported:

Issue number | Description | Platform | Impact | Workaround
-- | -- | -- | -- | --
#54 | Signal handling | All platforms | Currently, shutdown signals (SIGINT, SIGHUP and SIGTERM) and SIGCONT are fully supported on Unix platforms (pLinux, zLinux, xLinux, AIX, and z/OS). Support for other POSIX signals is pending. See SunMiscSignalTest.java for the list of signals that need to be supported. | None

The last set of code changes (eclipse/omr#3921 and eclipse/openj9#5923) to close eclipse/openj9#54 have been delivered. All POSIX signals listed in [SunMiscSignalTest.java](https://github.ibm.com/runtimes/openj9-openjdk-jdk/blob/openj9/test/jdk/sun/misc/SunMiscSignalTest.java) are supported by OpenJ9. In the next release notes, the **Signal Handling** issue should be removed from the **Known Issues** section. In the **Notable changes** section, it should be noted that OpenJ9 supports all POSIX signals.

Links to issue eclipse/openj9#54 and eclipse/openj9#2507 were incorrectly reported in the release notes. https://github.com/eclipse/openj9/pull/6206 has been created to fix the incorrect links.

SunMiscSignalTest.java: https://github.ibm.com/runtimes/openj9-openjdk-jdk/blob/openj9/test/jdk/sun/misc/SunMiscSignalTest.java

**Comment by babsingh** [comment]
fyi @SueChaplain @pshipton

**Comment by pshipton** [comment]
Please create this at https://github.com/eclipse/openj9-docs

**Comment by babsingh** [comment]
Created issue in https://github.com/eclipse/openj9-docs: https://github.com/eclipse/openj9-docs/issues/296. Closing this issue.
