### ISSUE TITLE
how do you delete unused docker images from docker nexus3 repo

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#6235]
HI, i use jenkins , run nexus3 as docker images pro, there are many unused docker images,
how do you delete unused docker images from docker nexus3 repo?
cloud you help me ?
have you used nexus3 as docker images repo ?

**Comment by DanHeidinga** [comment]
Sorry, that isn't something we can help with.  Try StackOverflow or the Nexus community support
