### ISSUE TITLE
j9_extended.functional_x86-64_mac DDR No JRE

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6239]
https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.functional_x86-64_mac_Nightly/68
osx1011-x86-1
cmdLineTester_shrcdbgddrext_1 
```
Testing: Run !shrc
Test start time: 2019/06/22 04:22:32 Eastern Standard Time
Running command: /Users/jenkins/workspace/Test_openjdk12_j9_extended.functional_x86-64_mac_Nightly/openjdkbinary/j2sdk-image/bin/jdmpview -core j9core1.dmp
Time spent starting: 4 milliseconds
Time spent executing: 18726 milliseconds
Test result: FAILED
Output from test:
 [OUT] DTFJView version 4.29.5, using DTFJ version 1.12.29003
 [OUT] Loading image from DTFJ...
 [OUT] 
 [OUT] For a list of commands, type "help"; for how to use "help", type "help help"
 [OUT] Available contexts (* = currently selected context) : 
 [OUT] 
 [OUT] Source : file:///Users/jenkins/workspace/Test_openjdk12_j9_extended.functional_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15611891649391/cmdLineTester_shrcdbgddrext_1/j9core1.dmp
 [OUT] 	*0 : PID: 0 : No JRE
 [OUT] 
 [OUT] > Unrecognised command: !shrc
 [OUT] > 
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/70

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Personal/12
osx1013-x86-4
testDDRExt_Callsites_openj9_0
`[java] [DDRExtTesterBase] [ERROR] '!findallcallsites ' is not recognized`

**Comment by pshipton** [comment]
@AdamBrousseau can you please check the space on the macos machines to see if there is less free space than there should be. This intermittent problem has been occurring since the Saturday nightly run. One theory is the core file is being truncated by lack of disk space. 
@keithc-ca fyi

**Comment by AdamBrousseau** [comment]
All 4 machines have loads of space. I was able to wget a 200M sdk to each of them without issue.  I can try rebooting them?

**Comment by pshipton** [comment]
>  I can try rebooting them?

Sure, as long is nothing is running.

**Comment by keithc-ca** [comment]
On MacOS, core files are quite large:
```
java -Xdump:system:events=vmstart -version
```
creates a 6.2GB file. Do we have room for several files that size?

**Comment by AdamBrousseau** [comment]
Rebooted them all
They each have over 600G free so should be tons.

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 As the resident mac DDR expert, any ideas on what to try next?

**Comment by pshipton** [comment]
Haven't seen the problem since the machines were rebooted. Keith looked at one core, and it appeared truncated. I don't expect this was a DDR problem but a machine issue.

**Comment by pshipton** [comment]
Another one https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Personal/20

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_OpenJDK13/19
osx1011-x86-1

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/99
osx1011-x86-1

@AdamBrousseau seems osx1011-x86-1 could use a reboot.

**Comment by AdamBrousseau** [comment]
>osx1011-x86-1 could use a reboot

Done

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin is there any way to automatically reboot the machines every weekend?

**Comment by AdamBrousseau** [comment]
The cleanup/sanitize script already reboots Windows machines. So I assume it could be extended relatively easily. Although I don't like the idea as this script is already a band-aid solution.

**Comment by pshipton** [comment]
Not sure what else to do if the machines need to be rebooted periodically in order for non-truncated core files to get created. We can continue to monitor and see how often the problem occurs.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/136
osx1011-x86-1
@AdamBrousseau @jdekonin pls reboot the machine.

**Comment by jdekonin** [comment]
Rebooted and its reconnected to jenkins again.

/cores contained 300gb of corefiles (523 artifacts) dating back to Feb.  There was still ~600G free on the device so I don't think that was the problem.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_mac_Nightly/36/
@jdekonin @AdamBrousseau pls reboot osx1013-x86-4

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_OMR/310
cmdLineTester_callsitedbgddrext_openj9_0
Run !printallcallsites
osx1014-x86-3

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/171
testDDRExt_General
`'!vmcheck ' is not recognized`_openj9_0
osx1011-x86-1

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_Nightly/167
cmdLineTester_callsitedbgddrext_openj9_0
`Run !printallcallsites`
osx1013-x86-3

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/178
testDDRExt_JITExt_openj9_0
`junit.framework.AssertionFailedError: TestJITExt failed. Unable to find a threads contained a JIT frame  and using the TestJITExtHelperThread class. Cannot proceed with JIT extension tests`
