### ISSUE TITLE
-Xdump documentation is incorrect

### ISSUE THREAD

**Issue by IvanHargreaves** [eclipse/openj9#6252]
The documentation in the IBM Java Knowledge Center for -Xdump is incorrect:

1) https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/openj9/xdump/index.html#parameters
Scroll down to the File location table, and it says both System dumps and JIT dumps are controlled by the JAVA_DUMP_TDUMP_PATTERN. 

The JIT dump output (like Java, Heap, Snap) is controlled by _CEE_DMPTARG and not JAVA_DUMP_TDUMP_PATTERN.

2) At this location https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/openj9/xdump/index.html#syntax
Under the heading of "Dump agent tokens" the list is incomplete. For example if you issue -Xdump:tokens on a z/OS platform it shows dump agent tokens, such as %asid and %jobid are missing from the docs.

**Comment by pshipton** [comment]
Opened https://github.com/eclipse/openj9-docs/issues/299

**Comment by SueChaplain** [comment]
@IvanHargreaves 

For (1), the latest documentation at OpenJ9 is accurate. See https://www.eclipse.org/openj9/docs/xdump/#file-location. The IBM doc will be fixed the next time the OpenJ9 is consumed for their current release program (end July).

For (2), if you can tell me what %asid and %jobid should have as a description I will add them to the table.
