### ISSUE TITLE
JTReg Test Failure - java/net/NetworkInterface/IPv4Only.java fails with jdk8 on AIX

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#6266]
Failure link
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_ppc64_aix/69/testReport/junit/java_net_NetworkInterface_IPv4Only/java/IPv4Only/

Optional info
-------------

- intermittent failure (yes|no): no

Failure output
--------------

```
Stacktrace

Execution failed: `main' threw exception: java.lang.RuntimeException: NetworkInterfaceV6List failed - found v6 address 0:0:0:0:0:0:0:1%lo0    

Standard Output

    

Standard Error

java.lang.RuntimeException: NetworkInterfaceV6List failed - found v6 address 0:0:0:0:0:0:0:1%lo0
	at IPv4Only.main(IPv4Only.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:819)

JavaTest Message: Test threw exception: java.lang.RuntimeException: NetworkInterfaceV6List failed - found v6 address 0:0:0:0:0:0:0:1%lo0

```

**Comment by DanHeidinga** [comment]
@sophia-guo This looks like a setup / config issue as the main method is `IPv4Only.main(IPv4Only.java:46)` and it's reporting it found an IPv6 address.

**Comment by sophia-guo** [comment]
@DanHeidinga agree. However hotspot doesn't have this issue. Neither openj9 jdk12 aix.  

Test code

```
public class IPv4Only {
    public static void main(String[] args) throws Exception {
        System.setProperty("java.net.preferIPv4Stack","true");

        Enumeration<NetworkInterface> nifs = NetworkInterface.getNetworkInterfaces();
        while (nifs.hasMoreElements()) {
            NetworkInterface nif = nifs.nextElement();
            Enumeration<InetAddress> addrs = nif.getInetAddresses();
            while (addrs.hasMoreElements()) {
               InetAddress hostAddr = addrs.nextElement();
               if ( hostAddr instanceof Inet6Address ){
                    throw new RuntimeException( "NetworkInterfaceV6List failed - found v6 address " + hostAddr.getHostAddress() );
               }
            }
        }
    }
}
```

openjdk does have a patch for IPv6 only environment
http://hg.openjdk.java.net/jdk/jdk/file/751a19168b11/test/jdk/java/net/NetworkInterface/IPv4Only.java

**Comment by DanHeidinga** [comment]
Interesting.  I didn't think OpenJ9 had any patches in the OpenJDK class library code for things like `nif.getInetAddresses()` so I'd expect this to work the same for both Hotspot and OpenJ9

**Comment by DanHeidinga** [comment]
` * @run main/othervm -Djava.net.preferIPv4Stack=true IPv4Only`
Looking at the test code, it should set a -D to tell the VM to prefer the IPv4 stack.  I don't see that in the test output though.  @sophia-guo Can you confirm it's being set on the commandline?

**Comment by sophia-guo** [comment]
No, we didn't set test with -D option as we are using https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/jdk/test/java/net/NetworkInterface/IPv4Only.java.  Test code use system property 'System.setProperty("java.net.preferIPv4Stack","true");'

http://hg.openjdk.java.net/jdk/jdk/file/751a19168b11/test/jdk/java/net/NetworkInterface/IPv4Only.java also works with IPv6 only environment, which is different. And I'm not sure why that patch hasn't been merged to adopt or ibmruntimes openjdk repo.

**Comment by DanHeidinga** [comment]
The System property is checked in the JNI_OnLoad call for the net library:
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/9637dcdbc7aa80442aafbd4fb6822aeeedb122d7/jdk/src/share/native/java/net/net_util.c#L69

Setting the property at runtime won't have any affect if the net native libraries have already been loaded.

It seems like a brittle test

**Comment by sophia-guo** [comment]
I tried with -D option and test passed.

**Comment by sophia-guo** [comment]
Issue opened https://github.com/AdoptOpenJDK/openjdk-tests/issues/1197. Close this one. Thanks @DanHeidinga
