### ISSUE TITLE
Create an IRC / Slack / other? chat group

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#627]
This was mentioned on the mailing list:
```
Btw, is there any IRC chat or something similar available for general questions?
```
and is a great idea.  

What platform should be used:

- Slack
- IRC
- Gitter
- Others

Please respond to this issue with pros / cons and preferences so we can get this started.

**Comment by mgaudet** [comment]
I think there's a path dependent preference to Slack.

**Comment by akrus** [comment]
I'd personally prefer IRC or Jabber conference.

**Comment by smlambert** [comment]
Somehow, I thought a Slack channel was already being set up.  It would be my preference since its already a tool used by two other projects I work on, it works reasonably well, and I don't want to grow the list of tools I am using.

**Comment by mgaudet** [comment]
There is also [Gateway support for IRC and XMPP in slack](https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP)

**Comment by jonathanwoodford** [comment]
I have created a slack channel for the Eclipse OpenJ9 project:  https://openj9.slack.com/

I would like to add a reference to this slack channel from the Eclipse OpenJ9 landing page.  

The aim of the slack channel is to encourage discussion, questions and collaboration within the whole OpenJ9 community.  Does anyone have any objections, thoughts, etc. in doing so?

**Comment by pshipton** [comment]
@smlambert mentioned https://github.com/rauchg/slackin is setup for AdoptOpenJDK at https://slackin-jmnmplfpdu.now.sh/, which allows anyone to automatically request access to the Slack channel.

**Comment by DanHeidinga** [comment]
@SueChaplain FYI - this is the issue tracking the adoption of Slack and (now) the configuration of the slackin tool.

**Comment by jonathanwoodford** [comment]
Wayne (Eclipse Foundation) highlighted that there is an Eclipse tool used by a lot of the Eclipse projects called Mattermost:   https://mattermost.eclipse.org

It is very simple to use and channels (by default) are available for anyone to join (without invite).

Is it too late to change direction / tool?

**Comment by jonathanwoodford** [comment]
The user experience for new users when using mattermost looks pretty good too.

You can specify the URL of the channel (in our case via a button on the OpenJ9 landing page), then when you login, it'll take you directly to the channel (after logging in / creating an ID).  If you have not previously joined the channel, you will join automatically.

You can send invites to the channel, etc.

P.S.
All users don't seem to be able to archive channels either.

**Comment by jonathanwoodford** [comment]
I have not created an OpenJ9 channel on https://mattermost.eclipse.org 
This could cause confusion if we chose not to use this tool.

Any votes for moving this this tool.  What do you think?

**Comment by SueChaplain** [comment]
I've never heard of Mattermost, so have no real feel for whether it is as good as Slack / better than Slack. I thought Slack was chosen to align with AdoptOpenJDK and perhaps that is an important point. The work to automate the Slack invitations has already been done and there is a PR open to merge the changes for the website. Of course we can change direction if there is a strong preference to doing so. Be good to come to some sort of decision asap so we can move on.
@mstoodle @DanHeidinga @pshipton ... others?

**Comment by smlambert** [comment]
Not sure why this issue is still open, as I too thought Slack was the choice.

Safe to say that few have heard of Mattermost, which may be an argument against it (even if it proves to be better tool), and may be a point of aggravation for people joining the project, "grrr, another tool, ever so similar, but different from the de facto standard used in many other elsewhere projects".

There are plugins for Mattermost notifications (https://jenkins.io/doc/pipeline/steps/mattermost/), so we don't lose that piece, if we are seriously considering shifting from Slack to it.  It means not directly reusing entire Jenkins scripts from AdoptOpenJDK that use Slack notification, but we can make that notification step "plugin-able".

**Comment by DanHeidinga** [comment]
The commonly stated preference here is Slack with one IRC vote and one Mattermost vote.  Given the stated preference for Slack and the goal of aligning tools across related communities (OMR, AdoptOpenJDK, OpenJDK), I vote for staying with Slack.

**Comment by DanHeidinga** [comment]
I'll leave this open until the end of the day for any other strong preferences to appear and if there is no ground swell behind an alternative tool, I'll close this.

**Comment by SueChaplain** [comment]
I had a quick look around. Posting some points that might spark discussions.......

**Pros for slack:**
- widely used and adopted (even has IRC integration)
- aligned with AdoptOpenJDK, with whom we share a user base.
- easy re-use of Adopts notification process (Shelley's point above)
- we're ready to go with it (in the absence of there being any info about using Mattermost for Eclipse projects)

**Cons for slack:**
- requires slackin to automate invitations (which in turn requires us to put the slack private key out there)
- our kind of use not openly encouraged by Slack.com (according to https://thenextweb.com/insider/2015/03/24/slack-is-quietly-unintentionally-killing-irc/) 

**Pros for Mattermost:**
- Eclipse project
- developed for community discussion (not commercial)
- no equivalent slackin integration required

**Cons for Mattermost:**
- yet another tool for users (no wide adoption o/s Eclipse) *Inhibitor to contribution?*
- not maintained by Eclipse Foundation, maintained on a best efforts basis by contributors.

**Questions:**
- can you use code snippets in  Mattermost?
- how about file transfers?

**Comment by SueChaplain** [comment]
In the absence of further discussion and direction, slackin added and merged. We can change the approach should there be a compelling reason.
