### ISSUE TITLE
Create Dockerfile for JITaaS in RHEL7 based container

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6277]
Currently, for JITaaS we support only Ubuntu 16.04 and Ubuntu 18.04 based containers and would like to support RHEL7 (and 8) too.

**Comment by mpirvu** [comment]
Attn: @ymanton

**Comment by chrisc66** [comment]
I looked into this issue. In order to get a RHEL based container, we need some subscription to red hat. Is there any enterprise red hat docker base image that is available to us?

**Comment by mpirvu** [comment]
Does `docker pull registry.access.redhat.com/ubi7/ubi-minimal` work?

**Comment by chrisc66** [comment]
Thanks, I can pull UBI image without any subscription. Does UBI works fine for us or do we have to use RHEL7/8?

**Comment by mpirvu** [comment]
Red Hat Universal Base Image (UBI) is what we want to use in the end.

**Comment by chrisc66** [comment]
Sounds good, I will work on this.

**Comment by mpirvu** [comment]
Some instructions on how to install gcc7 on rhel7:
https://developers.redhat.com/blog/2018/07/07/yum-install-gcc7-clang/

**Comment by mpirvu** [comment]
Some instructions on how to build protobuf on rhel7 on  Linux on IBM Z. They should work for x86 as well.

**Comment by harryyu1994** [comment]
This issue can be closed now. Fixed by #7019
