### ISSUE TITLE
Enable software CS testing on Power

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#6284]
I just noticed from [1] we have `^arch.ppc` specified, meaning we're not getting the same coverage testing for concurrent scavenge on Power as we are on x86 and Z. @gita-omr @zl-wang FYI. 

We may want to go through all the tests and enable them on Power to ensure we get full coverage testing and no regressions in OpenJ9. Example in [2], there are tons of others. We likely need to search for `-Xgc:concurrentScavenge` and check all the `playlist.xml` files in which we get hits to see if the tests which run under CS are disabled on `arch.ppc`.

[1] https://github.com/eclipse/openj9/issues/3283#issuecomment-505997448
[2] https://github.com/AdoptOpenJDK/openjdk-tests/blob/b360d8168d542054eb3faa6fd55b0afe2b8f71fd/systemtest/mauveLoadTest/playlist.xml#L184

**Comment by gita-omr** [comment]
@IBMJimmyk fyi.

**Comment by AlenBadel** [comment]
@fjeremic 
CS Tests have all been enabled, and are passing on Power.

See 
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1324
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1302

**Comment by fjeremic** [comment]
Excellent. We can conclude this issue as fixed. Thanks for the work here!
