### ISSUE TITLE
JMX not listening on a port

### ISSUE THREAD

**Issue by akrus** [eclipse/openj9#629]
Hi,

I'm testing AdoptOpenJDK build of OpenJ9 (latest one for Linux x64), but for some reason JMX doesn't work. I've tried running both OpenJ9 and Oracle JRE (where it works).

Here are the options used:
```
-Dcom.sun.management.jmxremote.port=19000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.password.file=/etc/jmx.passwd
```

I've also tried adding these:
```
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=9000 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=<ip> -Dcom.sun.management.jmxremote.local.only=false
```

but nothing changed, JVM is not listening on a port, VisualVM shows the app is running, but says JMX is unavailable (if running locally).

**Comment by samkamer** [comment]
You need to use the following - 
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.port=19000
-Dcom.sun.management.jmxremote.rmi.port=19000
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false

The rmi.port is what usually gets missed, but is required. It works best when both the rmi registry and rmi server are set to the same port.

**Comment by pshipton** [comment]
I'm not 100% sure, you might need #572, and also #488 would be a good idea. @akrus is the OpenJ9 build you are trying up to date? To get the latest from AdoptOpenJDK you need to take from the nightly builds.

**Comment by samkamer** [comment]
You are right @pshipton, both those PRs would be needed, in addition to the rmi.port property.

**Comment by akrus** [comment]
Didn't know there are also nightlies available, thanks for pointing out!
It works well with latest nightly, even without rmi.port, i.e. with this:
```
-Dcom.sun.management.jmxremote.port=19000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
```

Thanks everyone for such a quick response!
