### ISSUE TITLE
Send optimization plan to the server

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6291]
Currently, the client does not send the entire optimization plan to the server, but just the opt level. However, the compiler may look at other pieces of information from the optimization plan. For instance, one bit in the optimization plan indicates whether to generate a sampling body or not. The default is to use a sampling body. Missing this information could lead to the following problem seen in AcmeAir runs performed in containers limited to 150M:
- client sends hot compilation request which fails due to not enough free physical memory
- client retries the compilation at warm and sets the bit indicating that sampling of this method should be disabled
- server completes the compilation, but leaves sampling enabled
- sampling at the client indicates that the method is hot which triggers another hot compilation
- client sends hot compilation request which fails again and the cycle continues

Interestingly, some of the bits in the optimization plan are set by the compiler and used by the runtime, so we may have to send the optimization plan back from the server to the client:
```
self()->comp()->getOptimizationPlan()->setGPUResult(result)
self()->comp()->getOptimizationPlan()->setGPUIR(programSource)
comp()->getOptimizationPlan()->setDowngradedDueToSamplingJProfiling(false)
comp()->getOptimizationPlan()->setOptLevelDowngraded(false)
```
comp()->getOptimizationPlan()->resetAddToUpgradeQueue()

**Comment by harryyu1994** [comment]
Looking into this one.

**Comment by harryyu1994** [comment]
Currently server only has client's
```
TR_Hotness _optLevel;
```
Other fields in optimization plan includes:
```
flag32_t _flags; // client definitely needs to send this to server
int32_t _preceivedCPUUtil; // not sure if we need this one
bool _hwpDoReducedWarm; // not sure why this isn't included in the _flags
int32_t _gpuBlockDimX; // don't see it being used anywhere except in setters and getters
void *  _gpuParms; // don't see it being used anywhere except in setters and getters
char *  _gpuIR; // set by codegen, need to be sent back to client
int32_t _gpuResult; // set by codegen, need to be sent back to client
```
