### ISSUE TITLE
Pull request format check

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#63]
We will have a mix of people using hosts where LF is the default line-end and Windows where CR/LF is common.

I suggest that we ought to strive for consistency in the repository. After agreeing on the appropriate line-ends for various file types, perhaps we could add a pull-request check that verifies that proposed changes use the expected line-ends?

I haven't found a way in the web UI to tell what line-ends are used by a given file, so an automatic check would be helpful.

**Comment by keithc-ca** [comment]
It has been a week and the only feedback has been positive. @AdamBrousseau can you help make this happen? Thanks.

**Comment by DanHeidinga** [comment]
Would a `.gitattribute` file be a better solution?  See https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings for examples of how to use the .gitattribute file to control line endings.

**Comment by keithc-ca** [comment]
I never did get the result I was hoping for with `.gitattributes`, and I believe it depends on users configuring their local clones properly.

**Comment by AdamBrousseau** [comment]
I can provide an automatic build that will get the list of files modified/added in a PR

```
FILES=($(git diff --diff-filter=ACM --name-only origin/$ghprbTargetBranch HEAD))

for filename in ${FILES[@]};
do
    # Check line endings
done
```

@keithc-ca can you provide the check inside the loop. I will add some bits that will collect all the bad files and print them to the console at the end of the job

**Comment by keithc-ca** [comment]
I ran this over the entire openj9 repository; the files flagged are corrected by https://github.com/eclipse/openj9/pull/146.

```
#!/bin/bash -

debug() {
  : # echo "$*"
}

error() {
  echo "$*"
}

for filename in "$@" ; do
  type=$(file -b "$filename")

  case "$type" in
    empty)
      debug "Empty file: '$filename'"
      ;;
    *text*)
      # map filename to lowercase with ',,'
      case "${filename,,}" in
        *.bat | *.cmd)
          case "$type" in
            *CRLF\ line\ terminators*)
              debug "Good windows script: '$filename' type: '$type'"
              ;;
            *)
              error "*** ERROR: should have CRLF line terminators: '$filename' type: '$type'"
              ;;
          esac
          ;;
        *)
          case "$type" in
            *CR*line\ terminators*)
              error "*** ERROR: should have LF line terminators: '$filename' type: '$type'"
              ;;
            *)
              debug "Good text file: '$filename' type: '$type'"
              ;;
          esac
          ;;
      esac
      ;;
    *)
      debug "Non-text file:'$filename' type: '$type'"
      ;;
  esac
done
```

**Comment by AdamBrousseau** [comment]
@keithc-ca I have been testing this in my fork and I think its working as expected.
The temp PR for the script is [here](https://github.com/AdamBrousseau/openj9/pull/4)
The PR I have been testing with is [here](https://github.com/AdamBrousseau/openj9/pull/5)
The job is [here](https://ci.eclipse.org/openj9/job/PullRequest-LineEndingsCheck)
It launches automatically on every PR, can launch manually via `Jenkins line endings check`
Feel free to open a PR at my fork to test.
Please take a look. If you are satisfied, I will fix the repo variable and open a PR here.
