### ISSUE TITLE
Limiting OpenJ9 memory usage from a Jenkins build

### ISSUE THREAD

**Issue by cwesMills** [eclipse/openj9#6313]
I am using the docker-plugin for Jenkins to allow the provisioning for Docker containers. A Jenkins job I am running on a Docker container involves building OpenJ9. Using the config for the docker-plugin I have set a limit on how much memory each container can use, but the OpenJ9 configure stage thinks it has access to all the memory on the docker host machine. This causes the compile stage to use memory unchecked until it hits the cap set in the plugin config, causing the container to shut down and the Jenkins job to fail.
Is there any way to limit how much memory is used in the building of OpenJ9 from within Jenkins?

**Comment by DanHeidinga** [comment]
> the OpenJ9 configure stage thinks it has access to all the memory on the docker host machine.

Which version of OpenJ9 is being used as the bootjdk?  Which version are you building?

**Comment by cwesMills** [comment]
I've seen this issue occur while building jdk12 and jdk11 (both using jdk11 as the bootjdk)

**Comment by DanHeidinga** [comment]
How have you limited the memory to the docker container?

Is there an example / jenkins job / reproducible test case that we can look at?

**Comment by cwesMills** [comment]
It turns out that the configure script was the problem, it was reading the memory from `/proc/meminfo` which contained the wrong value. I was able to limit the usage with `--with-memory-size=4096` as an extra config option.
