### ISSUE TITLE
Make J9ServerStream::finishCompilation() a variadic function

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6314]
As suggested by @dmitry-ten this change would make adding new arguments easier, and would also remove the need for a CHTableCommitData import, which is not in OMR (thus we can easily port the communication layer top omr should we want to).

**Comment by harryyu1994** [comment]
In issue #6291 we are adding a new field in`finishCompilation()`. I might fix this one first.

**Comment by dmitry-ten** [comment]
I already opened #6322. Just waiting for sanity tests to pass.

**Comment by harryyu1994** [comment]
Great! Thanks for letting me know.
