### ISSUE TITLE
Capture diagnostic files created during build job

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6331]
In https://github.com/eclipse/openj9/issues/6330 we got a crash during the build process. Ideally the build job should capture the core file and archive it for diagnostics.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
Is there a specific location where these files will be? And will they have a specific naming/file format?

**Comment by pshipton** [comment]
Below is what was created in this instance, which is a good start. The files are `core.*.dmp`, `javacore.*.txt`, `Snap.*.trc`, and `jitdump.*.dmp`.

```
23:31:29  JVMDUMP010I System dump written to C:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Nightly\make\core.20190703.223114.3136.0001.dmp
23:31:29  JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Nightly\make\javacore.20190703.223114.3136.0002.txt
23:31:29  JVMDUMP010I Snap dump written to C:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Nightly\make\Snap.20190703.223114.3136.0003.trc
23:31:29  JVMDUMP010I JIT dump written to C:\Users\jenkins\workspace\Build_JDK11_x86-64_windows_Nightly\make\jitdump.20190703.223114.3136.0004.dmp
