### ISSUE TITLE
Rename files related to JITaaS communication

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6333]
We would like to eliminate the "J9" particle from the name to make them more generic.
Proposal:
J9Client.cpp/hpp  --> ClientStream.cpp/hpp
J9Server.cpp/hpp  --> ServerStream.cpp/hpp
J9Stream.cpp/hpp  --> CommunicationStream.cpp/hpp

Also, to be consistent, the `#ifndef` in the hpp files need to change.
E.g.:
```
#ifndef J9_CLIENT_H
#define J9_CLIENT_H
```
needs to become
```
#ifndef CLIENT_STREAM_H
#define CLIENT_STREAM_H
```

Moreover, all these files are under a directory called `rpc`. This made sense when we were using `gRPC`, but now we are directly using network sockets, no rpc style of communication. Thus we need to change the name of this directory to something else and I am proposing the name `networking`.

**Comment by a7ehuo** [comment]
I'll make the change.

**Comment by mpirvu** [comment]
@0xdaryl  proposed to change `rpc` into `net` instead of `networking`. It does sound better and therefore I fully agree.
