### ISSUE TITLE
With -Xjit:enableJITaaSHeuristics all AOT compilations are local

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#6364]
Under `-Xjit:enableJITaaSHeuristics` all cold compilations are performed locally because they are deemed inexpensive. AOT compilations are typically performed at 'cold' optimization level, but in a recent change meant to improve rampup time, they are later transformed into warm compilations. The net effect is that AOT compilations are performed locally, because they are perceived as cold, but they are essentially warm compilations.
We should change the code to perform all AOT compilations remotely.

**Comment by a7ehuo** [comment]
I'll make the change
