### ISSUE TITLE
cent6-x64-1 index-pack died of signal 15 - disabled

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6380]
```
Receiving objects:  28% (1858/6439), 48.05 MiB | 87.00 KiB/s   
Receiving objects:  28% (1858/6439), 48.14 MiB | 91.00 KiB/s   
error: index-pack died of signal 15
fatal: index-pack failed
```
Disabled the machine

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by AdamBrousseau** [comment]
When was this? I saw 5 in the Slack channel overnight, all the same machine. Just wondering if it has happened since.
I removed the build/test labels off the machine temporarily and am running a build on that machine to see if it was a temp network blip.
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-Personal/2/

**Comment by pshipton** [comment]
I created this because of the 5 overnight failures, haven't seen it since. As I recall, in the past when a machine started doing this, it didn't fix itself.

**Comment by AdamBrousseau** [comment]
It clones in the build job fine but we use a ref repo for the OpenJDK repo which is where there is a timeout used. When we clone OpenJ9 and OMR there is no timeout but it takes 6 minutes for OMR and 11 minutes for OpenJ9 (which is slow). In the test job there is a 10 minute timeout on the Adopt openjdk-tests repo which is where it's failing. Should also note that the machine clock is 2.5 hours behind which throws off the timestamper.  Going to try a restart and run another build.

**Comment by AdamBrousseau** [comment]
@HusainYusufali Do you know anything about the time server at UNB or how this machine could be out of sync?

**Comment by HusainYusufali** [comment]
The machines were probably setup with the default time servers when installed. You can check which servers are being used in `/etc/ntp.conf`

**Comment by AdamBrousseau** [comment]
Last test build cloned in under a minute (after restart)
```
Running on cent6-x64-1 in /home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal
[Pipeline] {
[Pipeline] checkout
No credentials specified
Fetching changes from the remote Git repository
 > git rev-parse --is-inside-work-tree # timeout=10
 > git config remote.AdoptOpenJDK.url https://github.com/AdoptOpenJDK/openjdk-tests.git # timeout=10
Fetching upstream changes from https://github.com/AdoptOpenJDK/openjdk-tests.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/AdoptOpenJDK/*
Checking out Revision 11cfa8171de4fe22fca41e3289968cfd35addce7 (AdoptOpenJDK/master)
 > git rev-parse AdoptOpenJDK/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 11cfa8171de4fe22fca41e3289968cfd35addce7
Commit message: "Add more renaissance perf test targets (#1185)"
 > git rev-list --no-walk 11cfa8171de4fe22fca41e3289968cfd35addce7 # timeout=10
[Pipeline] load
[Pipeline] { (/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_Personal/openjdk-tests/buildenv/jenkins/JenkinsfileBase)
[Pipeline] }
[Pipeline] // load
[Pipeline] timeout
Timeout set to expire in 10 hr
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Setup)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] sh
00:00:56.768  + printenv
```
Will look at the clock issue now but I think we can add it back to the pool once I get that sorted.

**Comment by AdamBrousseau** [comment]
ran `ntpdate` which has corrected the time. Not sure why it was skewed or if there is an underlying issue that will come back.
```
[root@cent6-x64-1 ]# ntpdate  192.168.10.1
 9 Jul 08:55:47 ntpdate[9527]: 192.168.10.1 rate limit response from server.
 9 Jul 11:23:31 ntpdate[9527]: step time server 192.168.10.1 offset 8863.519474 sec
[root@cent6-x64-1 ]# date
Tue Jul  9 11:23:36 EDT 2019
```
