### ISSUE TITLE
How to exit on OutOfMemoryError?

### ISSUE THREAD

**Issue by PascalSchumacher** [eclipse/openj9#6382]
We are using `adoptopenjdk/openjdk11-openj9:jre-11.0.3_7_openj9-0.14.3-alpine`.

After a container encontered a `java.lang.OutOfMemoryError: Java heap space` a heap dump was generated:

>at java.base/java.lang.OutOfMemoryError.<init>	at (OutOfMemoryError.java:58)
JVMDUMP010I Heap dump written to //heapdump.20190704.162223.1.0012.phd
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVMDUMP010I Snap dump written to {nothing to snap}
JVM requested Heap dump using '//heapdump.20190704.162223.1.0012.phd' in response to an event
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVM requested Snap dump using '//Snap.20190704.162223.1.0013.trc' in response to an event
JVMDUMP010I Java dump written to //javacore.20190704.162223.1.0011.txt
JVM requested Java dump using '//javacore.20190704.162223.1.0011.txt' in response to an event
JVMDUMP010I Snap dump written to //Snap.20190704.162217.1.0010.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVM requested Snap dump using '//Snap.20190704.162217.1.0010.trc' in response to an event
JVMDUMP010I Java dump written to //javacore.20190704.162217.1.0009.txt
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/07/04 16:22:23 - please wait.
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/07/04 16:22:23 - please wait.
JVM requested Java dump using '//javacore.20190704.162217.1.0009.txt' in response to an event
JVMDUMP010I Heap dump written to //heapdump.20190704.162217.1.0008.phd
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/07/04 16:22:17 - please wait.
JVM requested Heap dump using '//heapdump.20190704.162217.1.0008.phd' in response to an event
JVM requested Snap dump using '//Snap.20190704.162207.1.0007.trc' in response to an event
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVMDUMP010I Snap dump written to //Snap.20190704.162207.1.0007.trc
JVMDUMP010I Java dump written to //javacore.20190704.162207.1.0005.txt
JVM requested Java dump using '//javacore.20190704.162207.1.0005.txt' in response to an event
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVM requested Snap dump using '//Snap.20190704.162151.1.0006.trc' in response to an event
JVMDUMP010I Snap dump written to //Snap.20190704.162151.1.0006.trc
JVMDUMP010I Java dump written to //javacore.20190704.162151.1.0004.txt
JVM requested Java dump using '//javacore.20190704.162151.1.0004.txt' in response to an event
JVMDUMP010I Heap dump written to //heapdump.20190704.162207.1.0003.phd
JVM requested Heap dump using '//heapdump.20190704.162207.1.0003.phd' in response to an event
JVMDUMP010I Heap dump written to //heapdump.20190704.162151.1.0002.phd
JVM requested Heap dump using '//heapdump.20190704.162151.1.0002.phd' in response to an event
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/07/04 16:22:07 - please wait.
JVMDUMP010I System dump written to //core.20190704.162151.1.0001.dmp
JVM requested System dump using '//core.20190704.162151.1.0001.dmp' in response to an event
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/07/04 16:21:51 - please wait.

But the JVM kept running (I guess because Apache Camel caught and swallowed the error).

Now I am locking for a way to relieable exit the JVM if an `OutOfMemoryError` occurs.

I found this document https://docs.oracle.com/middleware/1212/coherence/COHAG/deploy_plat_consid.htm#COHAG502 which suggest using 

`-Xdump:tool:events=throw,filter=java/lang/OutOfMemoryError,exec="kill -9 %pid"`

This seem to be the only option because `-XX:+ExitOnOutOfMemoryError` isn't supported by OpenJ9 (according to https://www.eclipse.org/openj9/docs).

Sadly I could not get it to work. Should it work? Is there a better way?

By the way: Thank you very much for providing OpenJ9.

**Comment by DanHeidinga** [comment]
`throw` covers exceptions thrown by java code.  An OOM is typically thrown by the vm and would require `systhrow`.

Try `-Xdump:tool:events=throw+systhrow,filter=java/lang/OutOfMemoryError,exec="kill -9 %pid"`

**Comment by DanHeidinga** [comment]
`-XX:+ExitOnOutOfMemoryError` seems like a reasonable thing to implement.

@PascalSchumacher would you still expect to get the diagnostic files (core, javacore, heapdump, etc)?

**Comment by PascalSchumacher** [comment]
>throw covers exceptions thrown by java code. An OOM is typically thrown by the vm and would require systhrow.

Thank you very much! I will try it tomorrow.

`-XX:+ExitOnOutOfMemoryError` on Hotspot just terminates without creating any diagnostic files. If you add options to create diagnostic files like `-XX:+HeapDumpOnOutOfMemoryError` the files are created before terminating.

**Comment by PascalSchumacher** [comment]
I tried `-Xdump:tool:events=throw+systhrow,filter=java/lang/OutOfMemoryError,exec="kill -9 %pid"` but it failed with 

>...
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/07/09 06:49:42 - please wait.
...
JVMDUMP007I JVM Requesting Tool dump using '"kill -9 1"'
JVMDUMP011I Tool dump created process 94
/bin/sh: kill -9 1: not found
...

**Comment by DanHeidinga** [comment]
There's something interesting going on here as it works fine outside docker:
```
$ ~/projects/jdk12/openj9-openjdk-jdk12/build/macosx-x86_64-server-release/jdk/bin/java -Xdump:none -Xdump:tool:events=throw+systhrow,filter=java/lang/OutOfMemoryError,exec="kill -9 %pid" ThrowOOM
JVMDUMP039I Processing dump event "throw", detail "java/lang/OutOfMemoryError" at 2019/07/09 08:53:08 - please wait.
JVMDUMP007I JVM Requesting Tool dump using 'kill -9 78858'
JVMDUMP011I Tool dump created process 78859
Killed: 9
```

We'll need to look at the code(port library?) that maps `%pid` to the actual pid and why it might be different in a container.

**Comment by DanHeidinga** [comment]
Opened https://github.com/eclipse/openj9/issues/6412 to track adding the `-XX:+ExitOnOutOfMemoryError` option

**Comment by PascalSchumacher** [comment]
Thank you very much.

I guess this is not a OpenJ9 Problem. We do not use an entry-point script for our containers. Therefore OpenJ9 has PID `1`:

```
/ # ps -ef
PID   USER     TIME  COMMAND
    1 xxx      0:43 java -Xtune:virtualized -Xgcpolicy:optthruput -Xdump:tool:events=throw+systhrow,filter=java/lang/OutOfMemoryError,exec="k
  407 xxx      0:00 /bin/sh
  413 xxx      0:00 ps -ef
```

My knowledge of linux is very limited, but from googling it seems like PID 1 can not be killed.

I guess we either have add an entry-point script (so that OpenJ9 has another PID) or wait for #6412 to be implemented.

Thanks again for your help and sorry for wasting your time.
