### ISSUE TITLE
RMI LocateRegistry#createRegistry() not handling useCodebaseOnly=false correctly

### ISSUE THREAD

**Issue by hi5san** [eclipse/openj9#6391]
Java -version output
--------------------
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.3, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190531_242 (JIT enabled, AOT enabled)
OpenJ9   - b8ab01656
OMR      - b56045d2
JCL      - dcdc97f9dc based on jdk-11.0.3+7)

Summary of problem
------------------
Setting the RMI system property `-Djava.rmi.server.useCodebaseOnly=false` seem to have no effect when RMI Registry server is launched programmatically via `LocateRegistry#createRegistry(1099)`.

Whereas, using this with the `rmiregistry` command works as expected.
```
$ rmiregistry -J-showversion -J-Djava.rmi.server.useCodebaseOnly=false
```

This option (explicitly set to false) is required since `Java7u21` to make RMI Registry retain  compatibility of class loading with that of prior versions (ref: https://docs.oracle.com/javase/7/docs/technotes/guides/rmi/enhancements-7.html).

Diagnostic files
----------------
[rmitest.zip](https://github.com/eclipse/openj9/files/3371834/rmitest.zip)

The attached zip contains simple test jars and scripts to demonstrate the issue.  Source included in jars.

#### Expected
Here are the steps showing the expected behavior, demonstrated using `rmiregistry` command.

__(Terminal-1) Run rmiregistry__
```
$ ./01_runregistry.sh
rmiregistry -J-showversion -J-Djava.rmi.server.useCodebaseOnly=false
```

__(Terminal-2) Run RMI server application__
```
$./02_runserver.sh
java -Djava.rmi.server.hostname=localhost -showversion -classpath /path/to/rmitest/MsgServer.jar -Djava.rmi.server.codebase=file:/path/to/rmitest/MsgServer.jar -Djava.rmi.server.useCodebaseOnly=false example.rmi.MsgServer
...
codebase=file:/path/to/rmitest/MsgServer.jar
Binding.
Ctrl-C to quit.
```

__(Optional: Terminal-3) Run RMI client application__
```
$ ./03_runclient.sh 
java -showversion -classpath /path/to/rmitest/MsgClient.jar example.rmi.MsgClient
...
Listing services..
//:1099/Message
got Message: RMI message
```

#### Actual
Before running these tests, the RMI Server application and  rmiregistry need to be terminated by sending Ctrl-C to their terminals-1 and -2.

This time we launch RMI Registry programmatically, instead of using the `rmiregistry` command as in above.

__(Terminal-1) Launch RMI Registry programmatically__
```
$ ./01_runregistry-programatically.sh 
java -Djava.rmi.server.hostname=localhost -showversion -classpath /path/to/rmitest/rmireg.jar -Djava.rmi.server.useCodebaseOnly=false TestRMIRegistry
...
Ctrl-C to quit.
```

__(Terminal-2) Run RMI server application__
This time, we get the following error.
```
Binding.
java.rmi.ServerException: RemoteException occurred in server thread; nested exception is: 
	java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
	java.lang.ClassNotFoundException: example.rmi.Message (no security manager: RMI class loader disabled)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:391)
<snip>
Caused by: java.lang.ClassNotFoundException: example.rmi.Message (no security manager: RMI class loader disabled)
	at java.rmi/sun.rmi.server.LoaderHandler.loadProxyClass(LoaderHandler.java:565)
	at java.rmi/java.rmi.server.RMIClassLoader$2.loadProxyClass(RMIClassLoader.java:646)
	at java.rmi/java.rmi.server.RMIClassLoader.loadProxyClass(RMIClassLoader.java:311)
	at java.rmi/sun.rmi.server.MarshalInputStream.resolveProxyClass(MarshalInputStream.java:254)
	at java.base/java.io.ObjectInputStream.readProxyDesc(ObjectInputStream.java:1924)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1875)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2166)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
	at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:517)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:455)
	at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:92)

```

I'm not completely sure but am suspecting that this difference (rmiregistry vs programmatically launch) is due to the `useCodebaseOnly=false` not being handled in the latter case, as described in https://docs.oracle.com/javase/7/docs/technotes/guides/rmi/enhancements-7.html.

Wondering if this is by spec., and/or if there's a *correct* way of achieving this.

**Comment by pshipton** [comment]
@andrew-m-leonard can you please take a look.

**Comment by andrew-m-leonard** [comment]
The key here is the exception cause:
    no security manager: RMI class loader disabled
which indicates no security manager is setup. Having looked at your TestRMIRegistry it does not set one.
See doc reference: https://docs.oracle.com/javase/tutorial/rmi/implementing.html
essentially quote:
"If an RMI program does not install a security manager, RMI will not download classes (other than from the local class path) for objects received as arguments or return values of remote method invocations. This restriction ensures that the operations performed by downloaded code are subject to a security policy."
The above doc shows what you need to add to your test program:
```
if (System.getSecurityManager() == null) {
    System.setSecurityManager(new SecurityManager());
}
```
You may need some security policy settings too.

**Comment by hi5san** [comment]
@andrew-m-leonard Yes I noticed the error.  However, the intended setup is local class path only, and as noted, using the rmiregistry command works.  Could you please help me understand the difference?

**Comment by hi5san** [comment]
@andrew-m-leonard Thanks - by setting SecurityManager with AllPermission policy (as it required "*", "access" SocketPermission and "read" FilePermission to RMI server app's CWD for some reason), it worked as expected.  I can image `rmiregistry` command does something similar.

The reason I was running w/o SecurityManager was because I have a long running implementation on a Java ME based VM, which is working w/o SecurityManager in using LocateRegistry#createRegistry() (which is strange now that I think about it, perhaps due to RMI spec. changes, rmic usage difference, or itself an issue, but is not scope of this issue).

I might run into additional questions in upgrading my implementation to run under these conditions, but for now, its OK to close this Issue if you are fine as well.  Thank you for your expertise and support.
