### ISSUE TITLE
Pull Request Automatic Copyright Check

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#64]
Setup a Jenkins build at the [Eclipse OpenJ9 JIPP](https://ci.eclipse.org/openj9) instance to automatically run copyright checks against PRs.
The check should ensure the following about modified or added files:
- The file contains a copyright header if it is needed (based on file extension?).
- The Copyright header matches the template in [CONTRIBUTING.md](https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md).
- The second date in the copyright matches the current year.

Other Requirements:
- The job should run automatically when a PR is opened since no PR code is being built/executed.
- The job should detail all the files that cause the check to fail.
- The job should have a trigger phrase to rerun the check manually.
- The pipeline code should be checked into the openj9 rpeo.
- There should be doc available at/in the repo about the job.

**Comment by pshipton** [comment]
There aren't many files without copyrights. I suggest we start by checking all files and let the committers decide when to ignore a failed check.
