### ISSUE TITLE
Implement `TR_ResolvedJ9Method::varHandleMethodTypeTableEntryAddress` for JITaaS

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#6437]
This method needs to access attributes of a RAM class and other client-side info.
It's called in Java 11 but not Java 8 (I think because Java 8 doesn't have var handles).
Need to override this method for `TR_ResolvedJ9JITaaSServerMethod` and create a new remote call to fetch all of the client-side info.

**Comment by harryyu1994** [comment]
Looking into this.
