### ISSUE TITLE
Support and enable Quad optimizations for AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#6444]
Support and enable opcodes needed for Quad recognized method support (e.g., `TR::computeCC`) on AArch64.

**Comment by 0xdaryl** [comment]
@knn-k

**Comment by fjeremic** [comment]
Is this related to BigDecimal Quad uses? Are these relevant to OpenJ9?

**Comment by 0xdaryl** [comment]
Yeah, it's the BigInteger division quads acceleration.  You're right, not relevant for OpenJ9.
