### ISSUE TITLE
How to use -Xshareclasses with JLink?

### ISSUE THREAD

**Issue by Ealrann** [eclipse/openj9#6446]
Hello,

I'd like to test the `-Xshareclasses` capability of OpenJ9 with my JLink build. Unfortunately, when I use this option, I got this error message: 
```
JVMJ9VM011W Unable to load j9shr29: /home/XXXX/build/image/lib/compressedrefs/libj9shr29.so: cannot open shared object file: No such file or directory
JVMJ9VM004E Cannot load library required by: -Xshareclasses
Error: Could not create the Java Virtual Machine.
```

Is there something specific to enable Xshareclasses with JLink?

I use this jlink options:
```
--strip-debug
--compress 2
--no-header-files
--no-man-pages
--exclude-files **java_*.properties
```

**Comment by pshipton** [comment]
@Ealrann please include the openj9.sharedclasses module when jlink'ing.

**Comment by Ealrann** [comment]
Thank you very much 👍 !
