### ISSUE TITLE
ArrayList.ensureCapacity crashes the JVM

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#6449]
ArrayList.ensureCapacity throws OutOfMemoryError when executing the following program:

```
public class A {
   public static void main(String args[]) {
      ArrayList al = new ArrayList();
      al.ensureCapacity(Integer.MAX_VALUE/10);
   }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java

**Current result:**

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3210)
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacity(ArrayList.java:219)
	at A.main(A.java:6)

**Expected result:**

The same result as Oracle JVM (ArrayList capacity increased by Integer.MAX_VALUE/10).

**Comment by fjeremic** [comment]
This does not seem surprising given the default heap size (`-Xmx` value) for Java 8 is 512 MB [1]. The problem should go away if you explicitly give the JVM more heap memory. Curious do you know what the default is for Oracle? 

[1] https://www.eclipse.org/openj9/docs/openj9_defaults/

**Comment by non-conformances-research** [comment]
It is dynamically allocated: _"The default value is chosen at runtime based on system configuration"_ (https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html).

**Comment by DanHeidinga** [comment]
For Java 11+, OpenJ9 behaves more like Hotspot in how it picks default heap sizes.  The Java 8 size is due to history

**Comment by pshipton** [comment]
See also https://github.com/eclipse/openj9/issues/3475

**Comment by pshipton** [comment]
I don't think this needs to remain open. The problem has been identified and #3475 remains open to consider changing the defaults in the future.
