### ISSUE TITLE
AttachAPI backwards compatibility broken?

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#6455]
@pdbain-ibm Hey Peter, I just reimplemented the attach API of OpenJ9 for a library when no JDK is available. In the process, I realized that by adding the global namespace, it is no longer possible to attach to a JVM of an older version. That is really unfortunate since the attach API was always backwards compatible.

Was this breakage an oversight or is this an implicit behavior?

_Originally posted by @raphw in https://github.com/eclipse/openj9/issues/5533#issuecomment-511034601_

**Comment by DanHeidinga** [comment]
FYI @pshipton @pdbain-ibm @JasonFengJ9 

Can someone point me at the fallback code for this?  I can't find it now but remember discussing that there should either be an option to fallback to local semaphore or the VM should check the advertisement file to figure out which version of semaphore to use so that new VMs could still talk to old.

Hopefully, I've overlooked the code for that.  Any help would be appreciated.

**Comment by DanHeidinga** [comment]
Here's a link to the PR that made the change and the comment that indicates:

> I have reworked it so:
> 
> * new VMs can talk to old or new VMs _in the same session_ (as before)
> * new VMs can talk to new VMs in different sessions (OpenJ9 only).


https://github.com/eclipse/openj9/pull/5613#issuecomment-493475328

**Comment by raphw** [comment]
False alarm, here is the relevant line: https://github.com/eclipse/openj9/blob/8c21754c14de8020281b01cb4ee7e7a0bd57a09e/jcl/src/java.base/share/classes/com/ibm/tools/attach/target/Advertisement.java#L281

**Comment by pshipton** [comment]
I assume this can be closed, now the relevant code has been found.
