### ISSUE TITLE
VarHandle isAccessModeSupported tests are broken

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#646]
After merging https://github.com/eclipse/openj9/pull/631, which includes:

```
Added final for methods j.l.i.VarHandle.coordinateTypes/isAccessModeSupported, also removed the override method j.l.i.ViewVarHandle.isAccessModeSupported.
```

There are new extended test failures:

https://ci.eclipse.org/openj9/job/PullRequest-Extended-linux_ppc-64_cmprssptrs_le/6/testReport/

org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedShortByteArrayViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedFloatByteArrayViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedCharByteArrayViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedShortByteArrayViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedCharByteBufferViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedFloatByteArrayViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedDoubleByteBufferViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedFloatByteBufferViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedFloatByteBufferViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedDoubleByteArrayViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedDoubleByteBufferViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedCharByteBufferViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedDoubleByteArrayViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedCharByteArrayViewLE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedShortByteBufferViewBE    
org.openj9.test.varhandle.VarHandleUtilTests.testIsAccessModeSupportedShortByteBufferViewLE

**Comment by DanHeidinga** [comment]
FYI @JasonFengJ9

**Comment by DanHeidinga** [comment]
Note the different conditions under the cases like `GET_AND_SET_RELEASE` between the two implementations.

**Comment by JasonFengJ9** [comment]
I see, will look at this. Thanks @DanHeidinga
