### ISSUE TITLE
OpenJ9 uses modified jvm.cfg files from extensions to build correctly 

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#647]
When trying to build OpenJ9 it uses modified OpenJDK jvm.cfg files (which are delivered as part of the extensions repository: https://github.com/ibmruntimes/openj9-openjdk-jdk9). In order to reduce the amount to changes needed in the extensions repository we need to be able to use the jvm.cfg files that are provided as part of OpenJDK.

In the extensions there are several jvm.cfg files for separate platforms, such as jdk/src/java.base/unix/conf/amd64/jvm.cfg, and they have their content as: 
```
    -j9vm KNOWN
    -hotspot IGNORE
    -classic IGNORE 
    -native IGNORE 
    -green IGNORE 
```
rather than the original from OpenJDK
```
    -server KNOWN  
    -client IGNORE  
```
We need to be able to use the jvm.cfg files that are provided as part of OpenJDK rather than modified versions.

**Comment by groeges** [comment]
Peter Shipton has said: 
"these are related to the j9vm sub-directory of lib. If you rename the j9vm directory to server then the original file works. Although the JVM starts, there are OpenJ9 code changes required to accommodate this change properly."

and also

"I do note there are number of different jvm.cfg files for different platforms. Perhaps J9 could define a new set of conf/openj9-XXX platforms to pick up a different set of jvm.cfg files"

Both these are think that we need to discuss as part of this OpenJ9 Issue.

**Comment by archanaNogriya** [comment]
@Peter-Shipton , Is this issue somewhere connected to this https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/20? or this is very different.

 Is there any discussion going on regarding this issue where I can be part of it? 

or if we need to start one then @pshipton who else we need to involve?  what is the priority for this issue to get into progress or in any discussion?

**Comment by pshipton** [comment]
This is not related to ibmruntimes/openj9-openjdk-jdk9#20. There is no discussion on this outside of this issue. 

@DanHeidinga any thoughts on this?

@archanaNogriya this can be pursued by finding or introducing a way to replace the jvm.cfg files with OpenJ9 versions that specify `-j9vm KNOWN`.

**Comment by DanHeidinga** [comment]
In `Copy-java.base.gmk`, I see there is a mechanism to specify an alternative jvm.cfg:
```
# Allow override by ALT_JVMCFG_SRC if it exists
  JVMCFG_SRC := $(if $(wildcard $(ALT_JVMCFG_SRC)),$(ALT_JVMCFG_SRC),$(JVMCFG_SRC))
```

Can we use this to specify the OpenJ9 version of the jvm.cfg files?

**Comment by archanaNogriya** [comment]
@DanHeidinga What you are suggesting the changes is using OpenJ9 version of the jvm.cfg files, where do we have way that we can use the jvm.cfg files that are provided as part of OpenJDK rather than modified versions ?

**Comment by archanaNogriya** [comment]
Ignore my previous comment @DanHeidinga , Looking at code and now I can see what you are suggesting .

**Comment by archanaNogriya** [comment]
Build has been worked fine by changes as follows,
Move j9 jvm config files to closed dir  example /openj9-openjdk/closed/src/java.base/unix/conf/amd64/jvm.cfg

and replace back the openjdk jvm.cfg files to openJDK version

Modify /openj9-openjdk/closed/make/copy/Copy-java.base.gmk
# JVMCFG_ARCH needs to set while this make file has been initiated to set the closed jvm.cfg path
ifeq ($(call check-jvm-variant, zero), true)
  JVMCFG_ARCH := zero
else
  JVMCFG_ARCH := $(OPENJDK_TARGET_CPU_LEGACY)
endif

ALT_JVMCFG_SRC := $(TOPDIR)/closed/src/java.base/$(OPENJDK_TARGET_OS_TYPE)/conf/$(JVMCFG_ARCH)/jvm.cfg

And it all works fine.

Code has been merged into openj9-openjdk and openj9-openjdk10.

@DanHeidinga We can closed this issue.

**Comment by archanaNogriya** [comment]
As @pshipton has suggested, all j9 jvm.cfg files(Identical) are replaced with one single file.
and single file resides /openj9-openjdk/closed/src/java.base/conf/jvm.cfg

**Comment by pshipton** [comment]
Does putting the file in src/java.base/conf/jvm.cfg have any side affects? i.e. does it put the file in the conf directory of a build?

**Comment by archanaNogriya** [comment]
@Param-S Yes looking at the build log, It seems it is doing right thing and keeping config in right place .

/bin/cp -fP '/home/archana/openj9-openjdk/closed/src/java.base/conf/**jvm.cfg**' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base**/jvm.cfg**'
/bin/mkdir -p /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security
/bin/rm -f /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security/java.policy /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security/java.policy.tmp
/bin/cat /home/archana/openj9-openjdk/src/java.base/share/conf/security/java.policy >> /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security/java.policy.tmp;
/bin/mv /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security/java.policy.tmp /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security/java.policy
/bin/mkdir -p /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security
Copying support/modules_libs/java.base/security/cacerts
/bin/rm -f /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security/default.policy /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security/default.policy.tmp
/bin/cat /home/archana/openj9-openjdk/src/java.base/share/lib/security/default.policy >> /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security/default.policy.tmp;
/bin/mv /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security/default.policy.tmp /home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security/default.policy
/bin/cp -fP '/home/archana/openj9-openjdk/src/java.base/share/lib/security/cacerts' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/security/cacerts'
Copying support/modules_conf/java.base/net.properties
/bin/cp -fP '/home/archana/openj9-openjdk/src/java.base/share/conf/net.properties' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/net.properties'
Copying support/modules_legal/java.base/LICENSE
/bin/cp -fP '/home/archana/openj9-openjdk/LICENSE' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_legal/java.base/LICENSE'
Copying support/modules_legal/java.base/ASSEMBLY_EXCEPTION
/bin/cp -fP '/home/archana/openj9-openjdk/ASSEMBLY_EXCEPTION' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_legal/java.base/ASSEMBLY_EXCEPTION'
Copying support/modules_legal/java.base/ADDITIONAL_LICENSE_INFO
/bin/cp -fP '/home/archana/openj9-openjdk/ADDITIONAL_LICENSE_INFO' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_legal/java.base/ADDITIONAL_LICENSE_INFO'
Copying jdk/include/jni.h
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_include/java.base/jni.h' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/include/jni.h'
Copying jdk/include/jvmticmlr.h
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_include/java.base/jvmticmlr.h' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/include/jvmticmlr.h'
Copying jdk/include/classfile_constants.h
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_include/java.base/classfile_constants.h' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/include/classfile_constants.h'
Copying jdk/include/linux/jni_md.h
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_include/java.base/linux/jni_md.h' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/include/linux/jni_md.h'
Copying jdk/include/jvmti.h
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_include/java.base/jvmti.h' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/include/jvmti.h'
Copying jdk/include/ibmjvmti.h
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_include/java.base/ibmjvmti.h' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/include/ibmjvmti.h'
Copying jdk/conf/security/java.policy
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/security/java.policy' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/conf/security/java.policy'
Copying jdk/conf/net.properties
/bin/cp -fP '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/support/modules_conf/java.base/net.properties' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/conf/net.properties'
Creating symlink jdk/lib/**jvm.cfg**
/bin/rm -f '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/lib/**jvm.cfg**'
Creating symlink jdk/lib/security/default.policy
/bin/ln -s '../../support/modules_libs/java.base/**jvm.cfg**' '/home/archana/openj9-openjdk/build/linux-x86_64-normal-server-release/jdk/lib/**jvm.cfg**'
