### ISSUE TITLE
getDependencies.pl has hard-coded build number for asmtools.jar

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#6482]
TestConfig/scripts/tools/getDependencies.pl:
```
my %asmtools = (
	url => 'https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/107/artifact/asmtools.jar',
	fname => 'asmtools.jar',
	sha1 => '04cf07c584121c2e5a3d1dad2839fc8ab4828b6d'
);
```
Build 107 no longer exists.

Note that this affects designer testing.

Please update to a newer version and adjust the SHA accordingly.
As this issue is likely to recur, can we use a more durable reference to `asmtools.jar`?

**Comment by pshipton** [comment]
See also https://github.com/eclipse/openj9/pull/6469

**Comment by llxia** [comment]
Please see #6567 for the immediate fix.
Close this issue. We are going to keep https://github.com/eclipse/openj9/issues/6537 open until we deliver the proper solution.
