### ISSUE TITLE
Port testkitgen to Java

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#6488]
Previous discussions and a [draft PR from @fjeremic](https://github.com/eclipse/openj9/pull/6065) have prompted this issue to be expedited.
  
We will port the features and functionality of testkitgen (currently written in Perl) to Java.  This work will be delivered in phases, the first phase focussing on the following:
- remove dependency on 2 non-core Perl modules used by testkitgen to simplify prereqs story
- remove workaround that is in place to support testing on z/OS platform (where the non-core Perl modules are not easily installed)

Caveats:
- this work will not remove dependency on Perl itself, as STF and the system tests make heavy use of Perl.
- in this rewrite, we will also remove any references, compromises and features that were added to support internal mechanisms (Axxon graphgen, etc).  The implication of this is that for the period of continuing to need to support internal mechanisms, the Perl version of testkitgen will be used (housed in an internal repo), for internal testing.  This will allow us a clean break, with no references to old/internal testing in the open project.

**Comment by smlambert** [comment]
FYI @renfeiw

**Comment by renfeiw** [comment]
I will work on it.

**Comment by smlambert** [comment]
This work is now complete (see https://github.com/eclipse/openj9/pull/6703)
