### ISSUE TITLE
Metronome gc policy does not start up on AIX

### ISSUE THREAD

**Issue by smithwil** [eclipse/openj9#6499]
Metronome gc policy does not start up on AIX.

```
$ uname -a
AIX itcaix15 2 7 00C1C95E4C00

java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 8.0.5.31 - pap6480sr5fp31-20190311_03(SR5 FP31))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20190306_411656 (JIT enabled, AOT enabled)
OpenJ9   - d97ae0f
OMR      - a975735
IBM      - ad515e8)
JCL - 20190307_01 based on Oracle jdk8u201-b09

$ java -Xgcpolicy:metronome -version
Unable to initialize alarm thread for time-based GC scheduling
Most likely cause is non-supported version of OS
JVMJ9GC070E Failed to startup the Garbage Collector
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by amicic** [comment]
@LinHu2016 Please, investigate

**Comment by pshipton** [comment]
There is information below about changing "the user account to allow access to high-resolution timers", and "Set the AIXTHREAD_HRT environment variable to true". @smithwil have these instructions been followed?

https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/mm_gc_mgc_config_aix.html

**Comment by smithwil** [comment]
Thanks, @pshipton that explains it. The user account setup will not have been done on the system where I was testing.

**Comment by LinHu2016** [comment]
I have tried to test it on a few of AIX machines locally (2 AIX 7.2s, 1 AIX 7.1 and 2 AIX 6.1s), I can not reproduce the issue, also I did try to unset AIXTHREAD_HRT or set AIXTHREAD_HRT to false, it did not affect the results.

**Comment by gaoyn-cn** [comment]
i have got the same issue.
my os is AIX

jdk version is 1.8.0_301
SR6 FP36  OpenJ9 7bb9176 20210824_12036

**Comment by gaoyn-cn** [comment]
> 

it there any work around?

**Comment by gaoyn-cn** [comment]
> There is information below about changing "the user account to allow access to high-resolution timers", and "Set the AIXTHREAD_HRT environment variable to true". @smithwil have these instructions been followed?
> 
> https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/mm_gc_mgc_config_aix.html

page of the link is missing.

**Comment by doveye** [comment]
@pshipton looks like that info was removed from v8 docs when most of the GC content was ported to OpenJ9 early last year. We believed the info related to hard real time and shouldn't have been in the docs anyway. I also found that the info was copied from WebSphere Real Time docs to Java 7.1 docs in 2014. If these config steps do make a difference then I guess the info *is* still valid for v8.

**Comment by AdamBrousseau** [comment]
We set AIXTHREAD_HRT in the Jenkins node config, for some reason. I see it in the OpenJ9 AIX nodes. The internal AIX nodes seem to be hit and miss whether or not it's set. I'll open an issue to follow up on all of them.

**Comment by pshipton** [comment]
@Sreekala-Gopakumar See https://github.ibm.com/runtimes/infrastructure/issues/6944
