### ISSUE TITLE
JDK10 mono-repo compilation errors due to multiple classes in single .java file

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#650]
The new make file changes in OpenJDK10 for the Oracle change to a single src "repo" have resulted in several of the following types of errors. This is due to a J9 class java file declaring multiple "classes". This is fine in a single compilation unit, however with the repo changes the "nashorn" build is a special separate compilation unit, and the compiler cannot find these hidden classes as a result.
```
* For target support_special_classes_jdk.scripting.nashorn__the.jdk.scripting.nashorn_batch:
/home/admin/mydocker/ccm/jdk18.3/build/linux-x86_64-normal-server-release/support/j9jcl_sources/java.base/share/classes/java/lang/invoke/MethodHandle.java:224: error: cannot find symbol
	CacheKey cacheKey;			/* Strong reference to a CacheKey to ensure the WeakHashMap doesn't immediately collect the item */
	^
  symbol:   class CacheKey
  location: class MethodHandle
```

I have moved the problem classes into their own Java file, and this solves the problem.
Classes affected are:
- Class java.lang.invoke.CacheKey declared in HandleCache.java. => Create CacheKey.java
- Class java.lang.invoke.BruteArgumentMoverHandle declared in ArgumentMoverHandle.java. => Create BruteArgumentMoverHandle.java
- Class java.lang.invoke.VarHandleInvokeExactHandle declared in VarHandleInvokeHandle.java. => Create VarHandleInvokeExactHandle.java

**Comment by andrew-m-leonard** [comment]
@DanHeidinga The new make file changes in OpenJDK10 for the Oracle change to a single src "repo" have resulted in several of the following types of errors. This is due to a J9 class java file declaring multiple "classes". This is fine in a single compilation unit, however with the repo changes the "nashorn" build is a special separate compilation unit, and the compiler cannot find these hidden classes as a result.

**Comment by andrew-m-leonard** [comment]
PR: https://github.com/eclipse/openj9/pull/1247#issuecomment-368056306

**Comment by andrew-m-leonard** [comment]
This is now breaking JDK10 builds...
The problem shows itself because of the way OpenJDK10 has restructured the single-repo build. Nashorn is built as a separate compilation unit to the other components, and references some java.base classes. When this Nashorn compilation tries to find directly/indirectly some classes eg.java.lang.invoke.CacheKey it has no way to find it since there is no CacheKey.java file and CacheKey.class was built as a separate java.base compilation unit.
(This is my interpretation anyway!)
Here is a build log: https://hyc-rt-openjdk-jenkins.swg-devops.com/job/build_ibmsdk/272/console

**Comment by andrew-m-leonard** [comment]
@DanHeidinga Can someone take a look at this one please? i've tried my best fiddling with nashorn compile options... but to no avail...
thanks

**Comment by andrew-m-leonard** [comment]
@pshipton fyi, splitting out the hidden classes as per my PR (https://github.com/eclipse/openj9/pull/1247#issuecomment-368056306) will fix this

**Comment by pshipton** [comment]
Thanks Andrew, we are aware.

**Comment by DanHeidinga** [comment]
I've started looking at the build output and see that there are two make targets that are failing:
* docs-jdk-api-javadoc
* jdk.scripting.nashorn-java

@andrew-m-leonard Can you check the JDK 8 / 9 extensions repos as I believe we've previously disabled the javadoc generation in those builds.  This will help clarify which failures are related to `jdk.scripting.nashorn-java`

**Comment by andrew-m-leonard** [comment]
@danheidinga We do currently build the docs-image as part of "all", however, i've tried taking that out, and has no affect on the issue. I think the docs issue is simply hitting the same problem as the nashorn compilation...

**Comment by DanHeidinga** [comment]
Now that #1425 is merged, java version on 10 should work.
