### ISSUE TITLE
New Java 13 String methods

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6509]
The following new Java 13 String methods need implementations.

String formatted(java.lang.Object...)
String stripIndent()
String translateEscapes()

http://cr.openjdk.java.net/~iris/se/13/build/latest/api/java.base/java/lang/String.html

**Comment by DanHeidinga** [comment]
Note, these methods need to be marked as `@Deprecated` for removal as they relate to a preview feature.

**Comment by fjeremic** [comment]
Also a note to whoever picks this issue up to take a look at StringUTF16 and StringLatin1 to see if there are helpers already implemented there which we can make use of.

**Comment by tajila** [comment]
@fengxue-IS Can you please take a look at this.

**Comment by tajila** [comment]
Both `StringUTF16` and `StringLatin1` implement `stripIndent()`.

**Comment by tajila** [comment]
For `String::formatted(java.lang.Object...)` you can use `String::format` as a helper

**Comment by fengxue-IS** [comment]
looking into this
