### ISSUE TITLE
J9 VM JCL classes missing some new JDK10 method implementations

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#651]
JDK10 has added some new methods to some of the J9 JCL classes that openj9 implements. The following are missing:
- java.lang.invoke.MemberName:
    public MethodType getMethodType()
    public String getMethodDescriptor()
- java.lang.invoke.MethodType:
    int parameterSlotCount()

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you take a look at this?

Assuming the javadoc says what I think it will, MethodType already has the info to return in parameterSlotCount().  See:
```
	@VMCONSTANTPOOL_FIELD
	int argSlots;	// Number of stack slots used by the described args in the MethodType
```

Hopefully compile stubs will satisfy other two methods.

**Comment by JasonFengJ9** [comment]
Agreed, will do.

**Comment by JasonFengJ9** [comment]
From `OpenJDK Java 10 b32`, one of new methods added into `java.lang.invoke.MemberName` was `java.lang.String getMethodDescriptor();`, not `public String getMethodDescriptor()`, i.e., it is `package` access instead of `public`.
@andrew-m-leonard  which build level were you referring?

**Comment by JasonFengJ9** [comment]
As per http://jdk.java.net/10/, latest `Java 10` build level is `jdk-10-ea+32`. Making a PR to match this build API instead.

**Comment by andrew-m-leonard** [comment]
I was using b30 at the time
