### ISSUE TITLE
`make test` getdependency target fails

### ISSUE THREAD

**Issue by oneturkmen** [eclipse/openj9#6537]
Trying to compile and run all the tests via `make test`, the process fails:

> ERROR: downloading https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/107/artifact/asmtools.jar failed, return code: 2048
makefile:76: recipe for target 'getdependency' failed
make: *** [getdependency] Error 8

The file does not seem to exist anymore on the URL link above. Any way to resolve this?

OS: Ubuntu 18.04
JDK version: 8

Thanks!

**Comment by DanHeidinga** [comment]
fyi @llxia  @smlambert

**Comment by smlambert** [comment]
https://github.com/eclipse/openj9/pull/6469

**Comment by smlambert** [comment]
To work around this problem, you can apply the 2 line change proposed in #6469 PR to getdependencies.pl, while that will not be the final solution, it will work for your immediate needs (until asmtools is built again).

**Comment by oneturkmen** [comment]
Resolved (as suggested in the comments). Thanks!

**Comment by smlambert** [comment]
Thanks @oneturkmen, glad to hear the work around helps you - I will reopen this issue until we deliver the proper solution to the master branch.

**Comment by llxia** [comment]
PR https://github.com/eclipse/openj9/pull/6574 is delivered. Close this issue
