### ISSUE TITLE
Making isAssignableFrom fast-JNI

### ISSUE THREAD

**Issue by zl-wang** [eclipse/openj9#6586]
isAssignableFrom is a significant performance factor in Hadoop/Spark/PySpark, and it is typically the case that the Class argument is check-cast before it is called. As such, the potential NPE is typically not present.  It should be made into a fast-JNI.

**Comment by gacholio** [comment]
I doubt this will be much of a win, since the native can throw NPE, so there's very little optimization to be had.

Doing this inline in the JIT as a mildly special case of checkcast would make a lot more sense.

**Comment by gacholio** [comment]
I'd be tempted to float the null check out into a new method so that the native never needs a stack frame. This may slow down the interpreter a bit, though from inside Class itself, we could just call the native that does not NULL check.

**Comment by zl-wang** [comment]
That is a reasonable plan forward ...

**Comment by gacholio** [comment]
This is already a recognized method, so this work item is seeming less and less useful...

**Comment by gacholio** [comment]
This is already a fast JNI native. Closing as a complete waste of time.

**Comment by zl-wang** [comment]
Are we talking across each other, when referring to fast JNI?  At least, I saw we still built JNI call-out frame, releaseVMAccess/reacquireVMAccess, and checking pending exception etc, when calling this helper.  That is not fast JNI.  It could be due to incorrect properties returned on native method query.

**Comment by gacholio** [comment]
It very much is fast JNI, just not optimal, since it has the NULL check.

**Comment by zl-wang** [comment]
can we make it optimal and how?  that is the original ask anyway.  plus, the observation that the class arg is typically check-cast already.

**Comment by gacholio** [comment]
We can move the NULL check out, with possible startup performance issues in the interpreter. I can prototype the work, but I'm not going to benchmark it.

**Comment by zl-wang** [comment]
no worry about benchmarking.  i already hack it by -XjniAcc and measure it (worth of 12% for PySpark SQL#1).

**Comment by gacholio** [comment]
You miss the point - I'm interested in regressions caused by the wrapper method. Everything we care about needs to be measured.

**Comment by zl-wang** [comment]
fair enough.  PMA can do this.

**Comment by gacholio** [comment]
So, why is it not being recognized? Maybe fix instead.

**Comment by zl-wang** [comment]
That method is recognized already for some simple fast-pathing (as far as I can see ... likely only class equal comparison), but obviously not for fast JNI.  Once you make it qualified as fast JNI, you can return its proper properties through javaVM->internalVMFunctions->jniNativeMethodProperties  compile-time call.

**Comment by gacholio** [comment]
For the record, the old flags were

J9_FAST_JNI_RETAIN_VM_ACCESS | J9_FAST_JNI_DO_NOT_WRAP_OBJECTS)

so you should never have been dropping VM access.

The new one is fully-optimized.

**Comment by gacholio** [comment]
The change above causes crashes in JIT compilation all over the place - probably loads of assumptions about isAssignableFrom which are now being broken by having the wrapper.

I will not be looking into this.

**Comment by gacholio** [comment]
In the one core I looked at:
```
#0  0x00007fffef88627b in TR_InlinerBase::findAndUpdateCallSiteInGraph(TR_CallStack*, TR_ByteCodeInfo&, TR::TreeTop*, TR::Node*, TR::Node*, TR_CallTarget*) () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#1  0x00007fffef887369 in TR_InlinerBase::inlineFromGraph(TR_CallStack*, TR_CallTarget*, TR_InnerPreexistenceInfo*) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#2  0x00007fffef88c36b in TR_InlinerBase::inlineCallTarget2(TR_CallStack*, TR_CallTarget*, TR::TreeTop**, bool, int) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#3  0x00007fffef5332a2 in TR_InlinerBase::inlineCallTarget(TR_CallStack*, TR_CallTarget*, bool, TR_PrexArgInfo*, TR::TreeTop**) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#4  0x00007fffef8871a6 in TR_InlinerBase::inlineFromGraph(TR_CallStack*, TR_CallTarget*, TR_InnerPreexistenceInfo*) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#5  0x00007fffef88c36b in TR_InlinerBase::inlineCallTarget2(TR_CallStack*, TR_CallTarget*, TR::TreeTop**, bool, int) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#6  0x00007fffef5332a2 in TR_InlinerBase::inlineCallTarget(TR_CallStack*, TR_CallTarget*, bool, TR_PrexArgInfo*, TR::TreeTop**) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#7  0x00007fffef520b37 in TR_MultipleCallTargetInliner::inlineCallTargets(TR::ResolvedMethodSymbol*, TR_CallStack*, TR_InnerPreexistenceInfo*) () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#8  0x00007fffef88cf3f in TR_InlinerBase::performInlining(TR::ResolvedMethodSymbol*) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#9  0x00007fffef519646 in TR_Inliner::perform() () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#10 0x00007fffef94dba7 in OMR::Optimizer::performOptimization(OptimizationStrategy const*, int, int, int) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#11 0x00007fffef94f4cb in OMR::Optimizer::optimize() () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#12 0x00007fffef744441 in OMR::Compilation::compile() () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
---Type <return> to continue, or q <return> to quit---
#13 0x00007fffef47a6e0 in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR::Compilation*, TR_ResolvedMethod*, TR_J9VMBase&, TR_OptimizationPlan*, TR::SegmentAllocator const&) () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#14 0x00007fffef47b57d in TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#15 0x00007ffff564ed93 in omrsig_protect () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9prt29.so
#16 0x00007fffef47cefd in TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR_MethodToBeCompiled*, J9::J9SegmentProvider&) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#17 0x00007fffef47d422 in TR::CompilationInfoPerThread::processEntry(TR_MethodToBeCompiled&, J9::J9SegmentProvider&) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#18 0x00007fffef47dd1a in TR::CompilationInfoPerThread::processEntries() ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#19 0x00007fffef47e03a in TR::CompilationInfoPerThread::run() ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#20 0x00007fffef47e0fa in protectedCompilationThreadProc(J9PortLibrary*, TR::CompilationInfoPerThread*) ()
   from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#21 0x00007ffff564ed93 in omrsig_protect () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9prt29.so
#22 0x00007fffef47e554 in compilationThreadProc(void*) () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9jit29.so
#23 0x00007ffff5abc2c6 in thread_wrapper () from /bluebird/builds/bld_423644/sdk/xa6480/jre/lib/amd64/default/libj9thr29.so
#24 0x00007ffff7bc6e25 in start_thread () from /lib64/libpthread.so.0
#25 0x00007ffff74d734d in clone () from /lib64/libc.so.6
```

**Comment by zl-wang** [comment]
That is bizarre ... indicating compiler calling this helper with NULL Class arg(?).  I presumed that is all you changed.

**Comment by gacholio** [comment]
Assigning to you while the JIT issue is resolved.

**Comment by DanHeidinga** [comment]
@zl-wang Are you still pursing this? If not, please close the item

**Comment by zl-wang** [comment]
Not pursuing anymore.
