### ISSUE TITLE
Add JDK8 PR builds to repos OpenJ9, OpenJ9-OMR and OpenJ9-OpenJDK-JDK8 and nightly builds

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#660]
OpenJ9 with [openjdk-jdk8](https://github.com/ibmruntimes/openj9-openjdk-jdk8) is now available.

Builds we need to add to [Jenkins](https://ci.eclipse.org/openj9) for jdk8 (as per the jdk9 list we currently have)
#### Nightlies
- [x] Build zLinux [8](https://ci.eclipse.org/openj9/view/Build/job/Build-JDK8-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_390-64_cmprssptrs) & [9](https://ci.eclipse.org/openj9/view/Build/job/Build-JDK9-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Build-JDK9-linux_390-64_cmprssptrs)
- [x] Build pLinux [8](https://ci.eclipse.org/openj9/view/Build/job/Build-JDK8-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Build-JDK8-linux_ppc-64_cmprssptrs_le) & [9](https://ci.eclipse.org/openj9/view/Build/job/Build-JDK9-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Build-JDK9-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Build-JDK9-linux_ppc-64_cmprssptrs_le)
- [x] Test Sanity zlinux [8](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_390-64_cmprssptrs) & [9](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK9-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK9-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK9-linux_390-64_cmprssptrs)
- [x] Test Sanity plinux [8](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le) & [9](https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le)
   - ~#469 cmdLineTester_SCHelperCompatabilityTests_unix_1~
   - ~#472 testSCCMLTests1_1~
- [x] Test Extended zlinux [8](https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_390-64_cmprssptrs) & [9](https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK9-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Extended-JDK9-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Extended-JDK9-linux_390-64_cmprssptrs)
- [x] Test Extended plinux [8](https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Extended-JDK8-linux_ppc-64_cmprssptrs_le) & [9](https://ci.eclipse.org/openj9/view/Test/job/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Test-Extended-JDK9-linux_ppc-64_cmprssptrs_le)
   - ~#730 TestManagementAgent_SE80_0~
   - ~#731 VmArgumentTests_0~
   - ~#732 testvmcheck~
- [x] Pipeline Build & Test zLinux [8](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-JDK8-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-linux_390-64_cmprssptrs) & [9](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-JDK9-linux_390-64_cmprssptrs/) [![Build Status](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK9-linux_390-64_cmprssptrs/badge/icon)](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK9-linux_390-64_cmprssptrs)
- [x] Pipeline Build & Test pLinux [8](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-JDK8-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK8-linux_ppc-64_cmprssptrs_le) & [9](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-JDK9-linux_ppc-64_cmprssptrs_le/) [![Build Status](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK9-linux_ppc-64_cmprssptrs_le/badge/icon)](https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK9-linux_ppc-64_cmprssptrs_le)
#### PRs (to be committed in JenkinsFiles)
- #851 
   - [x] PR Compile only zLinux JDK8 (OpenJ9)
   - [x] PR Compile only zLinux JDK9 (OpenJ9)
   - [x] PR Compile only pLinux JDK8 (OpenJ9)
   - [x] PR Compile only pLinux JDK9 (OpenJ9)
   - [x] PR Sanity zLinux JDK8 (OpenJ9)
   - [x] PR Sanity zLinux JDK9 (OpenJ9)
   - [x] PR Sanity pLinux JDK8 (OpenJ9)
   - [x] PR Sanity pLinux JDK9 (OpenJ9)
   - [x] PR Extended zLinux JDK8 (OpenJ9)
   - [x] PR Extended zLinux JDK9 (OpenJ9)
   - [x] PR Extended pLinux JDK8 (OpenJ9)
   - [x] PR Extended pLinux JDK9 (OpenJ9)
- #1354 will support the ability to have the following builds. The jenkins files can be reused.
   - [ ] PR Sanity zLinux (OpenJ9-Openjdk-jdk8)
   - [ ] PR Sanity pLinux (OpenJ9-Openjdk-jdk8)
   - [ ] PR Sanity zLinux (OpenJ9-Openjdk-jdk9)
   - [ ] PR Sanity pLinux (OpenJ9-Openjdk-jdk9)
   - [ ] PR Compile only zLinux (OpenJ9-Openjdk-jdk8)
   - [ ] PR Compile only pLinux (OpenJ9-Openjdk-jdk8)
   - [ ] PR Compile only zLinux (OpenJ9-Openjdk-jdk9)
   - [ ] PR Compile only pLinux (OpenJ9-Openjdk-jdk9)
   - [ ] PR Sanity zLinux JDK8 (OpenJ9-OMR)
   - [ ] PR Sanity zLinux JDK9 (OpenJ9-OMR)
   - [ ] PR Sanity pLinux JDK8 (OpenJ9-OMR)
   - [ ] PR Sanity pLinux JDK9 (OpenJ9-OMR)

Will need to update the [Jenkins README](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md)
I believe the only machine config update is a boot-jdk 7 is required. I will confirm with @vsebe.

Note to self: This would be a really great time to commit our Jenkins pipeline configs to the repo.

**Comment by AdamBrousseau** [comment]
Confirmed with Violeta the only machine change is to get a boot jdk7.

**Comment by AdamBrousseau** [comment]
Downloading boot_jdk7/8 (z/p) 7.1.4.15 and 8.0.5.5 from
https://developer.ibm.com/javasdk/downloads/
The current boot jdk8 on P is openjdk8 default on the machine. Switching it to IBM 7.1.4.15.
Current boot jdk8 on Z is 8.0.4.11, switching to 8.0.5.5

**Comment by AdamBrousseau** [comment]
boot jdk 7/8 installed on all 8 machines at $HOME/openj9

**Comment by AdamBrousseau** [comment]
Apparently we need openjdk7 for the boot jdk not IBM java, installed openjdk7 on all 8 machines.

**Comment by AdamBrousseau** [comment]
JDK8/9 z/p build/test added. Puling Jenkins files from my fork for now. (see links in description).
Please note @DanHeidinga that there are still JDK8 failures in the sanity bucket that will need to be addressed before we can add these to default PRs.

**Comment by DanHeidinga** [comment]
>  there are still JDK8 failures in the sanity bucket

Is there a list of the existing failures or a set of issues open for them?  If you can identify them we can get them fixed asap.

**Comment by pshipton** [comment]
> Is there a list of the existing failures ...

In general https://github.com/eclipse/openj9/issues?q=is%3Aissue+is%3Aopen+label%3Ajdk8
more specifically for the sanity tests #469, #472

**Comment by DanHeidinga** [comment]
@AdamBrousseau The items Peter mentioned have been resolved.  Are there any other JDK8 sanity tests that are blocking PR builds from being enabled?

**Comment by AdamBrousseau** [comment]
No, according to my build badges in the description all sanity/extended 8/9 are green now.
We do need to resolve #662 before they can be enabled.

**Comment by DanHeidinga** [comment]
What's the outlook for #662?

**Comment by AdamBrousseau** [comment]
1354 has been merged
