### ISSUE TITLE
Enable recompilation for AArch64

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#6607]
Enable recompilation and patching support for AArch64.  For now, recompilation is disabled by returning `NULL` from `CodeGenerator::allocateRecompilationInfo()`.

**Comment by 0xdaryl** [comment]
@knn-k fyi

**Comment by knn-k** [comment]
Related PR:  #6165

**Comment by knn-k** [comment]
Additional related PR: #6937

**Comment by knn-k** [comment]
Enable the following tests when recompilation is implemented:

- SC_Softmx_JitAot_Linux (#8966)
- testDDRExt_SharedClasses_openj9 (#9003)

These tests are disabled for now because the AOT behavior assumes on heuristics depending on recompilation.

**Comment by knn-k** [comment]
Related PRs:
- eclipse/omr#5126, eclipse/omr#5132, eclipse/omr#5159

**Comment by knn-k** [comment]
Related PRs:
- #9756, #9765

**Comment by knn-k** [comment]
Recompilation is enabled.  Closing this issue now.
Issue #9881 tracks the support for profiling.
