### ISSUE TITLE
Sanity checks failing on Vagrant VM

### ISSUE THREAD

**Issue by Scott-Young-6746** [eclipse/openj9#665]
When testing a fresh clone of OpenJ9 on a 64bit Vagrant VM the tests are not runnable due to an error in the `openj9/test/TestConfig/makefile`. 

`BUILD_ROOT := $(SRC_ROOT)$(D)..$(D)jvmtest`
should be
`BUILD_ROOT := $(SRC_ROOT)$(D)..$(D)test`

Fixing this causes 83 out of 84 tests to fail during sanity check.

Common errors:
`Selected VM [default] by option -Xnocompressedrefs does not exist.`
```
Error: Unable to access jarfile /home/ubuntu/openj9-openjdk-jdk9/openj9/test/TestConfig/../../test/cmdline_options_tester/cmdlinetester.jar
```
Vagrant File: 
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus=2
    vb.memory = "2048"
  end
  config.vm.synced_folder "/mnt/NVStorage/", "/cold"
end
```
OS: Ubuntu 16.04
GCC: 4.8.5-4ubuntu2

output of `make sanity` attached
[sanity.log](https://github.com/eclipse/openj9/files/1499764/sanity.log)

**Comment by jdekonin** [comment]
The SPEC should be defined as linux_x86-64_cmprssptrs, as OpenJ9 built with the openj9-openjdk-jdk9(or 8) extensions isn't possible with non-compressedrefs atm.  I think this will resolve a lot of the failures I see in your sanity.log.

**Comment by Scott-Young-6746** [comment]
I did another rebuild and exported the cmprssptrs spec and still have 71/72 tests failing.

Seems it cannot create the JVM for the tests for those that it can find the test jar/class for.

[cmprssptrs.log](https://github.com/eclipse/openj9/files/1500082/cmprssptrs.log)

**Comment by jdekonin** [comment]
This time you did a jdk8 compile but used test options for 90. Failure "VMJ9VM007E Command-line option unrecognised: --add-exports=java.base/com.ibm.tools.attach.target=ALL-UNNAMED", java8 wouldn't recognize that cmdln option.  You need to set JAVA_VERSION to SE80 for compiling the test material.

**Comment by Scott-Young-6746** [comment]
Accidentally downloaded jdk8 source on a clean rebuild. Retried with jdk9.

Also found and the read-me for the openj9 tests and made sure to grab the dependencies.

However, I'm still seeing 71/72 tests failing.
[jdk9_cmprssptrs_sanity.log](https://github.com/eclipse/openj9/files/1500160/jdk9_cmprssptrs_sanity.log)
I noticed some classes are missing according to the errors in the log, but I ran `make getdependency` before running the tests.

**Comment by smlambert** [comment]
You do seem to have some strange errors for your tests, not finding the jar files that should have been compiled if you did actually compile the tests.

Example:
/home/ubuntu/openj9-openjdk-jdk9/openj9/test/TestConfig/../../test/cmdLineTests/shareClassTests/ListAllCachesTests/ShareClassesCMLTests.jar': No such file or directory  <- confirming, if you look there there are no jar files?

1) you set your ENV VARs needed for test (according to the log, this is what you set):
export SPEC=linux_x86-64_cmprssptrs
export JAVA_VERSION=SE90   <- change this to SE80 if you want to run tests against Java8 JVM
export JAVA_BIN=/home/ubuntu/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/images/jdk/bin      <- this changes to jre/bin location for Java8

2) cd TestConfig -> make -f run_configure.mk
3) make compile  (which now triggers the getdependencies target, so should go and get the dependencies it needs)
4) make sanity

**Comment by Scott-Young-6746** [comment]
I seem to have everything working now, however, on initial clone it's still required that the programmer change the makefile in /openj9-openjdk-jdk9/openj9/test/TestConfig/ to set the build root as test instead of jvmtest. I'll try to get a PR made for it before end of day to fix this issue.

**Comment by Scott-Young-6746** [comment]
After fixing a problem with the remaining space on the VMDK, I still have 2 failing tests. They both fail with the same error of failing to find a module.
`Exception in thread "main" java/lang/module/FindException: Module mods.modulec not found`
The complete log file is attached here.
Failing tests are:
* `openj9_jsr292Test_JitCount0_SE90_0`
* `openj9_jsr292Test_SE90_0`

**Comment by Scott-Young-6746** [comment]
After re-cloning and running the full list of instructions from the README.md in the test folder again it seems that the error I assumed was related to an incorrect folder name was in fact related to the problem of not calling `make compile` before calling make sanity.

I'll close this issue.

I might create a new issue and PR to make the subsets of make test (which does depend on make compile) to depend on make compile to simplify the test process.
