### ISSUE TITLE
Extended system test failure: SharedClassesAPI_0

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#6670]
Failure link
------------
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_mac/7

Failing thread reference can be found in the results tar.gz, here:
openjdk-tests\TestConfig\test_output_15648593132736\SharedClassesAPI_0\20190803-205835-SharedClassesAPI\execute\execute.stdout

and the error message itself can be found in the output for that thread, here:
C:\Users\ADAMFarley\Downloads\systemtest_test_output(1).tar\systemtest_test_output(1)\openjdk-tests\TestConfig\test_output_15648593132736\SharedClassesAPI_0\20190803-205835-SharedClassesAPI\results\8.WL3.stderr

Optional info
-------------

- intermittent failure: no
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
Unknown.

Failure output
--------------

JVMSHRC659E An error has occurred while opening shared memory
JVMSHRC336E Port layer error code = -174
JVMSHRC337E Platform error message: Invalid argument
JVMSHRC026E Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings
JVMSHRC663I Error recovery: destroyed semaphore set with id=54067200 associated with shared class cache.
JVMJ9VM015W Initialization error for library j9shr29(11): JVMJ9VM009E J9VMDllMain failed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by DanHeidinga** [comment]
> JVMSHRC659E An error has occurred while opening shared memory
> JVMSHRC026E Cannot create cache of requested size: Please check your SHMMAX and SHMMIN settings

@adamfarley have you checked the SHMMAX / SHMMIN settings for the machine?  I recall we had to modify the default osx settings for shared memory - @jdekonin or @babsingh may remember the details.

**Comment by jdekonin** [comment]
Looks like a dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/840

Details as to the fix are documented in that issue.

**Comment by adamfarley** [comment]
Thanks Dan and Joe. Will implement the fix as detailed, and re-run the test.

**Comment by adamfarley** [comment]
Confirmed that this is a dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/840

Closing because dup.
