### ISSUE TITLE
Add option to allow JNI function getArrayElements to return isCopy = FALSE

### ISSUE THREAD

**Issue by pquiring** [eclipse/openj9#6711]
Add some sort of -XX: flag so that the JNI function getArrayElements() always returns a non-copy of the array.  I've tried to use -XX:+AlwaysUseJNICritical but then the app crashes quickly.
The new option should force the GC to avoid moving memory (compacting) or fragmenting arrays.
Of course there would be memory inflation issues but that is a reasonable trade off for needed performance.
I have several video editor/processing apps that are starting to slow down due to excess copying of buffers when calling JNI functions.
I could use java.nio.ByteBuffer but that just complicates the source code too much.
Overall I've noticed much better performance in J9 compared to stock OpenJDK.
Thanks,

**Comment by gacholio** [comment]
`-XX:+AlwaysUseJNICritical` does exactly this.

**Comment by gacholio** [comment]
There are only two options - copy so the GC is not affected, or don't copy and impact the GC. We've minimized the impact to the GC for critical regions, but this is affected by which GC policy is chosen.

Holding critical regions for an unbounded amount of time will certainly degrade the VM/GC performance over time, likely leading to OOM eventually.
