### ISSUE TITLE
JDK13 JTReg Failure: java/util/stream/test/org/openjdk/tests/java/util/SplittableRandomTest.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6735]
Failure link
------------
- Test: https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/openj9/test/jdk/java/util/stream/test/org/openjdk/tests/java/util/SplittableRandomTest.java
- Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/96/
- Test Category: openjdk
- Test Suite Name: jdk_util
- OS/Architecture: x64_windows and x64_linux
- OpenJDK Version: 13+30
- Public Build SHAs:
- OpenJ9 - `5dd23af84`
- OMR - `6e99760b`
- JCL - `2337332cb3`

Optional info
-------------
- Intermittent failure: Yes
- Regression or new test: Regression
- Fails roughly 50% of the time in the nightly testing on just linux and windows as far as i can tell. I couldn't manage to replicate the problem just targetting the test itself but could've just been bad luck.

Failure output (captured from console output)
---------------------------------------------
Too long, but has problems with testDoubles and testLong. Rougly 28/39 of the tests fail when the test itself fails. 
Example error:
```
java.lang.AssertionError: 5 failure(s) for test data: DoubleTestData[new SplittableRandom().doubles(16.000000, 256.000000).limit(65536)]
14:53:47  1: java.lang.Error: PAR_STREAM_SPLITERATOR: java.lang.NullPointerException
14:53:47  java.lang.NullPointerException
14:53:47  	at org.testng.Assert.assertEquals(Assert.java:118)
14:53:47  	at org.testng.Assert.assertEquals(Assert.java:372)
14:53:47  	at org.testng.Assert.assertEquals(Assert.java:382)
14:53:47  	at org.openjdk.tests.java.util.SplittableRandomTest.lambda$randomAsserter$0(SplittableRandomTest.java:108)
14:53:47  	at org.openjdk.tests.java.util.SplittableRandomTest$$Lambda$52.00000000AC0783F0.assertResult(Unknown Source)
14:53:47  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.lambda$exercise$2(OpTestCase.java:406)
14:53:47  	at java.util.stream.OpTestCase$ExerciseDataStreamBuilder$$Lambda$117.00000000AC08F1E0.run(Unknown Source)
14:53:47  	at java.base/java.util.stream.LambdaTestHelpers.launderAssertion(LambdaTestHelpers.java:453)
14:53:47  	at java.base/java.util.stream.OpTestCase$ExerciseDataStreamBuilder.exercise(OpTestCase.java:409)
14:53:47  	at org.openjdk.tests.java.util.SplittableRandomTest.testDoubles(SplittableRandomTest.java:365)
```

**Comment by pdbain-ibm** [comment]
Ran this ~6 times on my Mac without failure. 3 runs were with `JVM_OPTIONS=-Xjit:count=0`.
```
openjdk version "13-internal" 2019-09-17
OpenJDK Runtime Environment (build 13-internal+0-adhoc.jenkins.BuildJDK13x86-64macNightly)
Eclipse OpenJ9 VM (build master-b87b38cf6, JRE 13 Mac OS X amd64-64-Bit Compressed References 20190820_37 (JIT enabled, AOT enabled)
OpenJ9   - b87b38cf6
OMR      - c46dfdbf
JCL      - 9beb413b360 based on jdk-13+33)
```

**Comment by adam-thorpe** [comment]
This test only seems to be failing on windows and linux, as stated above.

**Comment by adam-thorpe** [comment]
Ignore above, found an old issue: https://github.com/eclipse/openj9/issues/4613
Test seems to fail across multiple systems but intermittently. Not sure why your mac passed perfectly though.

**Comment by smlambert** [comment]
If this is a dup of #4613, we should close this and add any additional detail in the first reporting of the problem

**Comment by adam-thorpe** [comment]
Done.
