### ISSUE TITLE
MauveSingleInvocationLoadTest_OpenJ9_0: ub16x64j97: Name or service not known

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#6742]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_Nightly/110/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  >>> Captured test output >>>
LT  Test failed:
LT  java.net.UnknownHostException: ub16x64j97: ub16x64j97: Name or service not known
LT  	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)
LT  	at gnu.testlet.java.net.DatagramPacket.DatagramPacketTest2.<init>(DatagramPacketTest2.java:70)
LT  	at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
LT  	at java.base/java.lang.Class.newInstance(Class.java:2082)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:52)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
LT  	at java.base/java.lang.Thread.run(Thread.java:831)
LT  Caused by: java.net.UnknownHostException: ub16x64j97: Name or service not known
LT  	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
LT  	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
LT  	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
LT  	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
LT  	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
LT  	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1637)
LT  	... 8 more
LT  <<<
```

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
WIthout rights I cannot actual respin this failure on this machine to confirm the problem/resolution, so this will have to sit open until the test lands on this machine again, or we get access rights restored.

I updated the `/etc/hosts/` file which was not the same as the hostname.  I know that has caused issues in the past.

**Comment by smlambert** [comment]
or committer runs a Grinder:
https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/474

@AdamBrousseau - is the ticket still open to work out the kinks of the migration?  I see we hit some other UnsupportedOperationException when running the Grinder job

java.lang.UnsupportedOperationException: no known implementation of class jenkins.tasks.SimpleBuildWrapper is named BuildUser

**Comment by AdamBrousseau** [comment]
We've been opening issues or pull requests (eclipse-cbi/jiro) as we find them. I think we're missing the BuildUser plugin in this case. I can open a PR shortly unless someone beats me to it.

**Comment by AdamBrousseau** [comment]
https://github.com/eclipse-cbi/jiro/pull/37
