### ISSUE TITLE
get_sources.sh add ability to clone using reference repository

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#6744]
This will be work in extensions but opening here to track overall.

For build purposes it would be more efficient if the get_sources.sh script had the option to pass a reference repository (repo cache) in order to make the clones of OpenJ9, OMR etc faster.

More info about git clone using a reference repo
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---reference-if-ableltrepositorygt

**Comment by AdamBrousseau** [comment]
I'm seeing UNB get_sources clones take 4+ minutes. We should look into adding this sometime this year.

**Comment by pshipton** [comment]
@jdekonin please add this onto the todo list.
