### ISSUE TITLE
jdk-11.0.5+3 failure: undefined reference to `JVM_InitializeFromArchive'

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#6748]
04:51:32  /home/jenkins/workspace/Build_JDK11_x86-64_linux_Personal/build/linux-x86_64-normal-server-release/support/native/java.base/libjava/VM.o: In function `Java_jdk_internal_misc_VM_initializeFromArchive':
04:51:32  /home/jenkins/workspace/Build_JDK11_x86-64_linux_Personal/src/java.base/share/native/libjava/VM.c:67: undefined reference to `JVM_InitializeFromArchive'
04:51:32  collect2: error: ld returned 1 exit status
04:51:32  gmake[3]: *** [/home/jenkins/workspace/Build_JDK11_x86-64_linux_Personal/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/libjava.so] Error 1
04:51:32  gmake[3]: *** Waiting for unfinished jobs....
04:51:32  CoreLibraries.gmk:99: recipe for target '/home/jenkins/workspace/Build_JDK11_x86-64_linux_Personal/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/libjava.so' failed
04:51:32  Updating support/src.zip
04:51:32  gmake[2]: *** [java.base-libs] Error 1
04:51:32  gmake[2]: *** Waiting for unfinished jobs....
04:51:32  make/Main.gmk:215: recipe for target 'java.base-libs' failed

**Comment by JasonFengJ9** [comment]
It was defined for `JDK12` only.
https://github.com/eclipse/openj9/blob/41360de87a5edfb83d478e8bc27f246fd1a73521/runtime/j9vm/javanextvmi.c#L26-L32
