### ISSUE TITLE
Incremental JVM builds do not process changes affecting libj9gc29.so

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/openj9#676]
This relates to support for developers who are modifying source and testing locally. As far as I can tell, the recipe for a full (clean) build is something like: 

```
Exporting:
   EXTRA_CONFIGURE_ARGS=--enable-optimized
   enable_optimized=yes
   enable_debug=no
   OMRGLUE=/<sdk>/lib/amd64/compressedrefs/gc_glue_java
   JAVA_HOME=/<sdk> or whatever
Compiling linux_x86-64_cmprssptrs in /<sdk>/lib/amd64/compressedrefs (Nov 24 06:44:18 AM) ...
SPEC=linux_x86-64_cmprssptrs make clean >> make.clean.out
SPEC=linux_x86-64_cmprssptrs make -j16 >> make.jvm.out
```

An incremental build, after changing source in, say, omr/gc/base, would be as above without the `make clean` step. This should compile source changed since last build and link all .so dependent on changed source. However, only libj9vm29.so is linked in incremental builds in this case. Nothing is done to link changes into lib29gc29.so.

Also, complete recipes for building clean/optimized, clean/debug, incremental/optimized and incremental/debug builds should be documented in openj9 README.md. Completeness includes identification of configuration/environment settings and range of appropriate values for each setting.

IMO this issue should be given some priority, as developers internal and external will lose patience as long as we confront them with an hour-long build/test cycle.

**Comment by DanHeidinga** [comment]
Closing as this has been dormant for a long time and it may be addressed by the cmake story.
