### ISSUE TITLE
Github pull request view loses CI build information when commit pushed

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#6763]
For example: https://github.com/eclipse/openj9/pull/6702 had a failing CI build started by https://github.com/eclipse/openj9/pull/6702#issuecomment-522360298.  The link to that and other builds disappeared when I rebased and re-pushed the branch.

**Comment by keithc-ca** [comment]
This is expected: the previous builds relate to different commits and aren't necessarily relevant to the current change.
