### ISSUE TITLE
Failing JDK13 Extended System Test: SharedClasses.SCM23.MultiThread

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6765]
Failure link
------------
- https://ci.adoptopenjdk.net/view/Test_system/job/Test_openjdk13_j9_extended.system_x86-64_mac_xl/21/tapResults/
- Test Category: extended system
- OS/Architecture: x64_macosx_xl
- OpenJDK Version: 13+30
- Public Build SHAs:
- OpenJ9 - `81195db9c`
- OMR - `6e99760b `
- JCL - `2337332cb3`

Optional info
-------------
- Intermittent failure: No
- Regression or new test: Regression 

Failure output (captured from console output)
---------------------------------------------
```
MT2 09:53:59 >> --> Threads 4200 to 4500 <--
MT5 09:53:59 >> --> Threads 3600 to 3900 <--
MT4 09:54:02 >> Loaded 4000 classes...
MT5 09:54:09 >> --> Threads 3900 to 4200 <--
MT5 09:54:09 >> Loaded 4000 classes...
MT3 09:54:16 >> --> Threads 4200 to 4500 <--
STF 09:54:18.168 - Heartbeat: Process MT2 is still running
MT2 09:54:28 >> --> Threads 4500 to 4800 <--
MT1 09:54:32 >> --> Threads 4200 to 4500 <--
MT3 09:54:42 >> --> Threads 4500 to 4800 <--
...
STF 10:49:18.327 - Heartbeat: Process MT2 is still running
STF 10:49:21.076 - **FAILED** Process MT2 has timed out
...
**FAILED** at step 5 (Start java processes using LoaderSlaveMultiThread). Expected return value=0 Actual=1 at /Users/jenkins/workspace/Test_openjdk13_j9_extended.system_x86-64_mac_xl/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15657634683051/SharedClasses.SCM23.MultiThread_0/20190814-094910-SharedClasses/execute.pl line 122.
```

**Comment by adam-thorpe** [comment]
JTReg Test: java/lang/System/LoggerFinder/modules/JDKLoggerForImageTest.java produces a very similar output on mac, JDK13.
Link: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk13_j9_sanity.openjdk_x86-64_mac/13/consoleFull

**Comment by pshipton** [comment]
In the artifacts, the 5.MT2.stdout file shows
```
10:43:55 >> Loaded 19000 classes...
10:44:42 >> --> Threads 18900 to 19200 <--
10:46:44 >> --> Threads 19200 to 19500 <--
10:48:25 >> --> Threads 19500 to 19800 <--
10:49:09 >> Loaded 20000 classes...
```
I don't see any useful diagnostics. There are a number of 5.MT2.kill* files, but they are all zero size.

**Comment by pshipton** [comment]
@Mesbah-Alam

**Comment by Mesbah-Alam** [comment]
Those output are coming from: https://github.com/Mesbah-Alam/openj9-systemtest/blob/728736451a116cec202ce4ae08757e0db5dbccf4/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/test/sc/LoaderSlaveMultiThread.java#L92

I agree that they are not very useful as in they don't provide any clue as to why the test was taking "longer" than usual - which triggered the eventual failure due to timeout. 

I have a PR to increase this timeout value https://github.com/eclipse/openj9-systemtest/pull/91

**Comment by pshipton** [comment]
eclipse/openj9-systemtest#91 is merged so I'll close this. @adam-thorpe Let us know if there is still any problem.
