### ISSUE TITLE
aix71-p8-1 is out of disk space

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6774]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_Nightly/110/
`JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 0, requested bytes = 16777216.`

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_OMR/212/
`JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 1220608, requested bytes = 16777216.`

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by jdekonin** [comment]
Cleanup has it looking fine.

```
/dev/fslv00      50G   85M   50G   1% /home/u0020236/workspace
/dev/hd1        6.8G  764M  6.1G  12% /home
```

**Comment by pshipton** [comment]
Didn't see this failure last night, will close for now and see how it goes.
