### ISSUE TITLE
Enable HCR for AArch64

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#6775]
Implement HCR support for AArch64.

**Comment by Akira1Saitoh** [comment]
- [ ] Add `VirtualGuardNOPInstruction`.
- [ ] Add `virtualGuardHelper` function and use it from `ifcmpne` evaluator.
- [ ] Add compensation code for aarch64 to `TR_RuntimeAssumptionTable::notifyClassRedefinitionEvent` and `TR_RedefinedClassPicSite::compensate`.

**Comment by knn-k** [comment]
This can be closed now.
