### ISSUE TITLE
JTReg Test Failure: java/lang/StringBuffer/CompactStringBuffer.java and CompactStringBuilder.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6778]
Failure link
------------
- Build: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk13_j9_sanity.openjdk_s390x_linux/18/
- Test Category: openjdk
- Test Suite: jdk_lang
- OS/Architecture: s390x_linux
- OpenJDK Version: 13+30
- Public Build SHAs:
- OpenJ9 - `1625c27d4`
- OMR - `6e99760b`
- JCL - `2337332cb3`

Optional info
-------------
- Intermittent failure: No
- Regression or new test: Regression

Failure output (captured from console output)
---------------------------------------------
```
test CompactStringBuffer.testCompactStringBufferForLatinA(): failure
14:56:12  java.lang.AssertionError: expected [0] but found [-1]
14:56:12  	at org.testng.Assert.fail(Assert.java:94)
14:56:12  	at org.testng.Assert.failNotEquals(Assert.java:496)
14:56:12  	at org.testng.Assert.assertEquals(Assert.java:125)
14:56:12  	at org.testng.Assert.assertEquals(Assert.java:372)
14:56:12  	at org.testng.Assert.assertEquals(Assert.java:382)
14:56:12  	at CompactStringBuffer.testCompactStringBufferForLatinA(CompactStringBuffer.java:62)
```
Both classes have the exact same error, ending with the same line number:
`CompactStringBuilder.testCompactStringBuilderForLatinA(CompactStringBuilder.java:62)`

**Comment by adam-thorpe** [comment]
Same issue with stringbuffer on jdk11: https://github.com/eclipse/openj9/issues/6671

**Comment by pshipton** [comment]
@DanHeidinga @fjeremic fyi, regression indicated

**Comment by adamfarley** [comment]
If this is now closed, the associated tests will now be unexcluded.
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1376
