### ISSUE TITLE
jcmd GC.class_histogram takes any parameter without error

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6781]
`jcmd <vmid> GC.class_histogram` can take a parameter according to the help output, but any parameter is accepted and there is no indication if the parameter is having any affect on  the output.

```
GC.class_histogram: Obtain heap information about a Java process
 Format: GC.class_histogram [options]
 Options: -all : include all objects, including dead objects
```

**Comment by pshipton** [comment]
@pdbain-ibm @JasonFengJ9

**Comment by pshipton** [comment]
Note `Thread.print` does not have the same problem.

**Comment by pshipton** [comment]
jmap kind of has the same problem, it takes any parameter starting with `-histo` such as `-histo:bogus` or `-histo-bogus`

**Comment by JasonFengJ9** [comment]
Will have a look.
