### ISSUE TITLE
MauveMultiThreadLoadTest_special_28 and 29 timeout on Windows

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6782]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/57
MauveMultiThreadLoadTest_special_28 (Mode610-OSRG)
29 (Mode612-OSRG_28)
```
LT  06:25:04.956 - Completed 82.7%. Number of tests started=2349085 (+11103)
LT  06:25:24.972 - Completed 83.1%. Number of tests started=2360035 (+10950)
LT  06:25:44.988 - Completed 83.5%. Number of tests started=2372614 (+12579)
LT  06:26:05.003 - Completed 83.9%. Number of tests started=2382950 (+10336)
STF 06:26:16.020 - Heartbeat: Process LT  is still running
STF 06:26:17.052 - **FAILED** Process LT  has timed out
```

I expect this is a configuration problem, these sub-tests need more time to complete.
This problem is not intermittent, the timeout occurs in every run although I've only linked to the latest failure.

**Comment by pshipton** [comment]
@Mesbah-Alam @llxia

**Comment by Mesbah-Alam** [comment]
@pshipton - just making sure, have the tests been excluded already?

**Comment by pshipton** [comment]
@Mesbah-Alam The tests are not excluded, they still ran last night as per the link the description. I was thinking to exclude them because I thought they were taking too long for the machines we have available, but then realized the time reported included the time waiting for the test to be restarted or aborted.

**Comment by Mesbah-Alam** [comment]
@pshipton - the test configuration has been updated; timeout increased :  https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/283

**Comment by pshipton** [comment]
Thanks. I'll go ahead and close this assuming the problem is fixed.
