### ISSUE TITLE
macOS: Inputting Japanese to Passive components cause crash

### ISSUE THREAD

**Issue by takiguc** [eclipse/openj9#6814]
Java -version output
--------------------
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190806_306 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)

Summary of problem
------------------

Java was crashed by following instruction.
1. Add Japanese input source into macOS
   See https://support.apple.com, then type "input sources" in "Search Support" field
   You may see "Type in another language on your Mac with input sources"
2. Download following files via:
   (Please see "4. Sample Code")
   https://docs.oracle.com/javase/8/docs/technotes/guides/imf/api-tutorial.html
   ActiveClient.java IMFDemo.java LWTextComponent.java PeeredTextArea.java
3. Compile *.java files
4. Move input focus to "Lightweight component. passive client"
5. Change input source to "Hiragana" on right top on desktop
6. Press "a" key, then Java will be crashed

Note:
I could not recreate this issue on OpenJDK Hotspot:
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

Diagnostic files
----------------

Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00000000040A23C0 Handler2=00000000042B5D90 InaccessibleAddress=0000000000000000
RDI=000000000893E700 RSI=0000000000000000 RAX=0000000000000000 RBX=000000000893E700
RCX=00007FCD4D80D620 RDX=00000000041ECBDA R8=00007FFEEC5518E0 R9=00007FFEEC551780
R10=00000000042CDE96 R11=00007FCD4A5CB966 R12=00007FCD509278A0 R13=0000000004216470
R14=0000000008C130B0 R15=0000000008A3E648
RIP=000000000408F960 GS=0000 FS=0000 RSP=00007FFEEC551520
RFlags=0000000000010246 CS=002B RBP=00007FFEEC5515D0 ERR=0000000000000004
TRAPNO=000000040000000E CPU=0000000000040000 FAULTVADDR=0000000000000000
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 bff0000000000000 (f: 0.000000, d: -1.000000e+00)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM7 00000000fffffffe (f: 4294967296.000000, d: 2.121996e-314)
XMM8 000000000000000f (f: 15.000000, d: 7.410985e-323)
XMM9 0000000000000037 (f: 55.000000, d: 2.717361e-322)
XMM10 0b0a090809080100 (f: 151519488.000000, d: 1.733947e-255)
XMM11 000000000000000a (f: 10.000000, d: 4.940656e-323)
XMM12 ff4c4c4cff4c4c4c (f: 4283190272.000000, d: -1.552466e+305)
XMM13 00ff00ff00ff00ff (f: 16711935.000000, d: 7.064161e-304)
XMM14 0002000200020002 (f: 131074.000000, d: 2.781385e-309)
XMM15 0002000200020002 (f: 131074.000000, d: 2.781385e-309)
Module=/xxxxxx/jdk-11.0.4+11/Contents/Home/lib/compressedrefs/libj9vm29.dylib
Module_base_address=0000000004000000 Symbol=runCallInMethod
Symbol_address=000000000408F790
Target=2_90_20190806_306 (Mac OS X 10.14.6)
CPU=amd64 (4 logical CPUs) (0x200000000 RAM)

If you need core and javacore, please let me know.

**Comment by DanHeidinga** [comment]
@keithc-ca Can you take a look at this?

**Comment by keithc-ca** [comment]
I was able to reproduce this with a local build of jdk11 created today.

**Comment by takiguc** [comment]
Thanks.
Please let me know if additional testing is required.
