### ISSUE TITLE
Create query to determine if SCC is the Default SCC

### ISSUE THREAD

**Issue by dsouzai** [eclipse/openj9#6826]
It would be useful to have a query to determine whether the SCC being used is an SCC created via the `-Xshareclasses` option, or the default SCC. One use case would be making heuristic decisions based on this information (eg https://github.com/eclipse/openj9/pull/6734).

**Comment by dsouzai** [comment]
From what I've been told, the query would just be a wrapper around 
```
J9_ARE_ALL_BITS_SET(jitConfig->javaVM->sharedClassConfig->runtimeFlags, J9SHR_RUNTIMEFLAG_ENABLE_CACHE_NON_BOOT_CLASSES)
```

**Comment by Samantha-Rempel** [comment]
Currently working on this issue
