### ISSUE TITLE
AdoptOpenJDK 11.0.4 OpenJ9 for zLinux is slow to start

### ISSUE THREAD

**Issue by toshiona** [eclipse/openj9#6844]
AdoptOpenJDK 11.0.4 OpenJ9 for zLinux is slow to start.
Average time of "java -version" with 10 trials is 14.3975 second on RHEL7 (real 14.3975, user 0.1841, sys 14.2488)
11.0.2 and 11.0.3 also have the problem.

11GA and 11.0.1 don't have the problem.
1.8.0_222 doesn't have the problem.
Hotspot doesn't have the problem.

This problem is not solid. It can recreate about 90%.

strace shows too many mmap/munmap/futex.
Please let me know how to gather data.

Environment:
  RHEL7.7 and Ubuntu 16.04
  Memory 8GB
  System z12 LPAR

# 11.0.4
$ strace -f -c ./java -version
...
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux s390x-64-Bit Compressed References 20190717_304 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 52.80   20.113981       22549       892       149 futex
 43.05   16.400684          30    544858           munmap
  4.11    1.565893           3    545005           mmap
  0.01    0.002721           5       572       447 open
  0.01    0.002548           5       504           pread64
  0.01    0.002101           6       380           read
  0.00    0.001884           5       357           sched_yield
  0.00    0.001762           4       450       398 stat
  0.00    0.001365           3       453           mprotect
  0.00    0.000394           3       136           close
  0.00    0.000382           4        94           rt_sigprocmask
  0.00    0.000264           3       105           fstat
  0.00    0.000136           9        16           madvise
  0.00    0.000133           3        53           sched_get_priority_min
  0.00    0.000127           2        53           sched_get_priority_max
...
------ ----------- ----------- --------- --------- ----------------
100.00   38.095749               1094257      1001 total

# 1.8.0_222
$ strace -f -c ./java -version
...
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20190717_371 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1 based on jdk8u222-b10)
...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 92.69    0.262223         580       452        76 futex
  1.93    0.005459           4      1238           read
  1.01    0.002844           5       564       439 open
  0.76    0.002155           3       797           lseek
  0.73    0.002065           4       487       391 stat
  0.54    0.001541           6       278           sched_yield
  0.52    0.001459           3       507           mprotect
  0.45    0.001271          12       105           munmap
  0.31    0.000886           4       212           mmap
  0.13    0.000380           3       137           close
...
------ ----------- ----------- --------- --------- ----------------
100.00    0.282903                  5457       912 total

#11.0.4 Hotspot
$ strace -f -c ./java -version
...
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 88.24    0.104503         214       489       109 futex
  2.11    0.002499          11       236       141 open
  2.02    0.002393           7       366           pread64
  1.57    0.001865           5       413           mmap
  1.26    0.001490           5       313           mprotect
  0.86    0.001023           5       195           gettid
  0.71    0.000846           7       122           munmap
  0.60    0.000715           7        96           read
  0.47    0.000561           4       143       129 stat
...
------ ----------- ----------- --------- --------- ----------------
100.00    0.118432                  2891       385 total

#11.0.3 and 11.0.2 also have the problem (on Ubuntu 16.04 since old version didn't start on RHEL7)
$ time ./java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.0, JRE 11 Linux s390x-64-Bit Compressed References 20190417_218 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5cc996a803 based on jdk-11.0.3+7)

real	0m7.789s
user	0m0.178s
sys	0m7.522s

$ time ./java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.0, JRE 11 Linux s390x-64-Bit Compressed References 20190130_127 (JIT enabled, AOT enabled)
OpenJ9   - 04890c300
OMR      - d2f4534b
JCL      - 50b45cd160 based on jdk-11.0.2+8)

real	0m16.800s
user	0m0.213s
sys	0m16.355s

#11GA and 11.0.1 don't have the problem (on Ubuntu 16.04 since old version didn't start on RHEL7)
$ time ./java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux s390x-64-Bit Compressed References 20181020_68 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - f62696f378 based on jdk-11.0.1+13)

real	0m0.142s
user	0m0.130s
sys	0m0.010s

$ time ./java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.10.0, JRE 11 Linux s390x-64-Bit Compressed References 20181003_43 (JIT enabled, AOT enabled)
OpenJ9   - e44c4716
OMR      - 32df9563
JCL      - eeda2c2d02 based on jdk-11+28)

real	0m0.145s
user	0m0.133s
sys	0m0.010s

**Comment by DanHeidinga** [comment]
@dnakamura Can you take a look at this?

**Comment by pshipton** [comment]
@dmitripivkine any update on this? Is this related to https://github.com/eclipse/openj9/issues/7115 ? Tentatively moving this to the next release, as it's getting late to be making any risky fixes.

**Comment by dmitripivkine** [comment]
> @dmitripivkine any update on this? Is this related to #7115 ? Tentatively moving this to the next release, as it's getting late to be making any risky fixes.

Yes, there are two independent problems:
 - https://github.com/eclipse/openj9/issues/7115
 - very slow available memory search (reported for example here https://github.com/eclipse/openj9/issues/6228)

If we solve https://github.com/eclipse/openj9/issues/7115 second problem would not be exposed.
We are working on improving memory search path too

**Comment by dmitripivkine** [comment]
Hello @toshiona,

I believe this problem is fixed. Would you please try again in your convenience? You can get JMV to test latest from https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9

Thank you.

**Comment by toshiona** [comment]
Thank you for the information.
Yes, the problem has been fixed. I checked this with

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+4-201912021941)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-b25f8b08b, JRE 11 Linux s390x-64-Bit Compressed References 20191202_406 (JIT enabled, AOT enabled)
OpenJ9   - b25f8b08b
OMR      - 97da8ad70
JCL      - 682588fef2 based on jdk-11.0.6+4)
