### ISSUE TITLE
[0.16.0] Release

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#6871]
Milestone: https://github.com/eclipse/openj9/milestone/10

Branching from build https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/625/ :
```
#625 - Nightly 
27-Aug-2019 10:11 PM
OpenJ9: 118dac7
OMR: d49eff1
OpenJDK8: ​efd7298 ​- ​openj9-openjdk-jdk8 
OpenJDK11: 259a016 -...
```

**Comment by pshipton** [comment]
openj9-0.16.0-m2: Eclipse OpenJ9 v0.16.0 Milestone 2

Repo SHAs
OpenJ9: c577be8
OMR: d49eff1

**Comment by pshipton** [comment]
Eclipse OpenJ9 v0.16.0

Repo SHAs
OpenJ9: 867dab4
OMR: d4c85c3
