### ISSUE TITLE
Command !J9ConstantPool does not work for  Java 8 SR 5 FP 40

### ISSUE THREAD

**Issue by manqingl** [eclipse/openj9#6887]
I am using the jdmpview from Java 8 SR 5 FP 40 to debug a system core file from the same Java version:

> !j9method 0x022F8490
J9Method at 0x22f8490 {
  Fields for J9Method:
        0x0: U8 * bytecodes = !j9x 0x00007FDA18137B38
        0x8: struct J9ConstantPool * constantPool = !j9constantpool 0x00000000022F7894
        0x10: void * methodRunAddress = !j9x 0x0000000000000005
        0x18: void * extra = !j9x 0x000000000000176F
}
Signature: java/net/HttpURLConnection.setRequestMethod(Ljava/lang/String;)V !bytecodes 0x00000000022F8490
ROM Method: !j9rommethod 0x00007FDA18137B24
Next Method: !j9method 0x00000000022F84B0
> !j9constantpool 0x00000000022F7894
J9ConstantPool at 0x22f7894 {
  Fields for J9ConstantPool:
        0x0: struct J9Class * ramClass = !j9class 0x181371A000000000 // <FAULT>
        0x8: struct J9ROMConstantPoolItem * romConstantPool = !j9romconstantpoolitem 0x0000000000007FDA
}
>

The output from !j9constantpool 0x00000000022F7894 is obviously bad for the ramClass field.

I believe the memory is fine because the implementation of !J9Method should be getting the j9class from the constantpool.

**Comment by manqingl** [comment]
@keithc-ca : please have a look

**Comment by keithc-ca** [comment]
The bottom four bits of the `constantPool` field are used as flags and should be masked before printing the suggested `!j9constantpool` command.

**Comment by gacholio** [comment]
For consistency, don't assume 4 bits, but use the badly-named constant from here:

`#define J9_CP_FROM_METHOD(method) ((J9ConstantPool *) ((UDATA)((method)->constantPool) & ~J9_STARTPC_STATUS))
`

**Comment by gacholio** [comment]
One thing we don't want is to display the CP value with the tag bits removed, so the output would have to be different than normal structures.

`0x8: struct J9ConstantPool * constantPool = 0x00000000022F7894 (!j9constantpool 0x00000000022F7890)`

or make !j9constantpool special, and do the masking for you.

**Comment by gacholio** [comment]
Better yet, make it work like !j9object, so it does print the masked value in the command, but also show the flag bits as a separate fake field.

**Comment by keithc-ca** [comment]
@gacholio I'm not sure I understand your suggestion. Is this what you'd like to see?
```
> !j9method 0x022F8490
J9Method at 0x22f8490 {
  Fields for J9Method:
    0x0: U8 * bytecodes = !j9x 0x00007FDA18137B38
    0x8: struct J9ConstantPool * constantPool = !j9constantpool 0x00000000022F7890 (flags = 0x4)
    0x10: void * methodRunAddress = !j9x 0x0000000000000005
    0x18: void * extra = !j9x 0x000000000000176F
} 
```

**Comment by gacholio** [comment]
Yes, that's actually less confusing than the j9object output (which makes flags appear to be another field in the struct).
