### ISSUE TITLE
Jython NullPointerException in PythonInterpreter with OpenJ9-JDK12+

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#6920]
In **Jython (versions 2.5.3 and 2.7.1)**, NullPointerException (**NPE**) is seen with the latest OpenJ9-JDK12 nightly build when executing [PythonInterpreter.exec(String s)](https://github.com/jythontools/jython/blob/df6350d63370f566a768dd02ec3cc69a606025fa/src/org/python/util/PythonInterpreter.java#L261-L268). The NPE is not seen in either OpenJ9-JDK11 or OpenJDK-JDK12.

### Testcase (SimpleTest.java):

```
import org.python.util.PythonInterpreter;
import org.python.core.*;

public class SimpleTest {
   public static void main(String []args) throws PyException
   {
       PythonInterpreter pi = new PythonInterpreter();
   }
}
```

### Compile and run:

```
# Compile
$JAVA_HOME/bin/javac -cp jython-standalone-2.5.3.jar SimpleTest.java

# Run SimpleTest
$JAVA_HOME/bin/java -cp jython-standalone-2.5.3.jar:. SimpleTest
```

**jython-standalone-2.5.3.jar**: https://mvnrepository.com/artifact/org.python/jython-standalone/2.5.3
**jython-standalone-2.7.1.jar**: https://mvnrepository.com/artifact/org.python/jython-standalone/2.7.1

### OpenJ9 JDK11 output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.google.common.base.internal.Finalizer (file:/root/npe_interpreter_exec_jython/jython-standalone-2.5.3.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of org.python.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### OpenJ9 JDK12 output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.google.common.base.internal.Finalizer (file:/root/npe_interpreter_exec_jython/jython-standalone-2.5.3.jar) to field java.lang.Thread.inheritableThreadLocals
WARNING: Please consider reporting this to the maintainers of org.python.google.common.base.internal.Finalizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" Exception in thread "main" java.lang.NullPointerException
	at org.python.core.Py.recursiveIsInstance(Py.java:1934)
	at org.python.core.Py.isInstance(Py.java:1894)
	at org.python.core.__builtin__.isinstance(__builtin__.java:696)
	at org.python.core.Py.displayException(Py.java:1082)
	at org.python.core.PyException.printStackTrace(PyException.java:79)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:873)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:866)
	at java.base/java.lang.Thread.uncaughtException(Thread.java:1341)
```

Note: `WARNING`(s) can be ignored since they occur in both OpenJ9-JDK11 and OpenJ9-JDK12.

**Comment by babsingh** [comment]
Attn: @TiborBeres @DanHeidinga

**Comment by pshipton** [comment]
Does the same problem occur with JDK13 builds?

**Comment by babsingh** [comment]
> Does the same problem occur with JDK13 builds?

Yes, it happens with OpenJ9 JDK13 and doesn't happen with Hotspot JDK13. NPE is an aftereffect of other exceptions: `ClassCastException -> Method.invoke (InvocationTargetException) ->  NPE`. I will post more details in the context of Jython later.

**Comment by babsingh** [comment]
### Summary

@TiborBeres The issue is in the Jython source code. [jython-standalone-2.7.2a1+.jar](https://ibm.box.com/s/b40rysm2j4bk4x21sgnyxps7p71h9bub) is built using the latest Jython source code, which contains the fix. Can you verify if the fix works for you?

### Details: Issue & Fix

- The `NullPointerException` happens because of the following exceptions: `ClassCastException` -> `InvocationTargetException` -> `PyException` -> `NullPointerException`. The `InvocationTargetException` and other exceptions occur because the `ClassCastException` is thrown while executing `Method.invoke`.

- `ClassCastException` happens when an instance of `PyObject` is being cast to `PyJavaType` in `PyJavaType.handleMroError`.
```
        for (MROMergeState mergee : toMerge) {
            for (int i = mergee.next; i < mergee.mro.length; i++) {
                if (mergee.mro[i] == PyObject.TYPE <-- Check fails when mergee.mro[0] is an instance of PyType; "instanceof" should be used instead of `==`.
                        || mergee.mro[i] == PyType.fromClass(Object.class)) {
                    continue;
                }
                if (winner == null) {
                    // Pick an arbitrary class to be added to the mro next and break the conflict.
                    // If method name conflicts were allowed between methods added to Java types,
                    // it would go first, but that's prevented, so being a winner doesn't actually
                    // get it anything
                    winner = (PyJavaType)mergee.mro[i];
                }
                inConflict.add((PyJavaType)mergee.mro[i]); <-- Shouldn't be executed if mergee.mro[i] is an instanceof PyObject.
            }
        }
```

- **Relationships:**
    - **PyObject**: `public class PyObject implements Serializable`
    - **PyType**: `public class PyType extends PyObject implements Serializable, Traverseproc`
    - **PyJavaType**: `public class PyJavaType extends PyType {`

- This issue is not seen in Hotspot JDKs and OpenJ9 JDK11-. A slightly different code path in Jython is taken in OpenJ9 JDK12+, which leads to the above exceptions. I haven't investigated why a different code path is taken in OpenJ9 JDK12+ since the above code, from where the `ClassCastException`, is incorrect.

- In the above code, `==` won't do class type checks properly. Instead, `instanceof` should be used. Since `==` is used for checking the class type, the check fails, and the code associated to the `ClassCastException` gets executed. 

- In Jython versions **2.5.3** and **2.7.1** (latest release), `==` gets used in `PyJavaType.handleMroError` for a class type check, which is the source of the `ClassCastException`. In Jython's Github repo, `==` gets replaced with `instanceof` in [PyJavaType.handleMroError](https://github.com/jythontools/jython/blob/38a80c032234889ce0dcad013e4505ba82af5615/src/org/python/core/PyJavaType.java#L226-L250) (**FIX** in the latest source code). This change was performed in the following commit: https://github.com/jythontools/jython/commit/057a2c6fa9cb00a88f4bf8a8de23cd2576977bab. It is associated to the following Jython bug: https://bugs.jython.org/issue2445.

- To verify the above fix, I built a standalone Jython jar using the latest Jython source code (https://github.com/jythontools/jython), and found that the NPE no longer happens in OpenJ9 JDK12+.

**Comment by TiborBeres** [comment]
@babsingh the new jython.jar did fix the issue. Thanks!

**Comment by babsingh** [comment]
Closing the issue since a fix exists in the latest Jython source code.
- [Fixed PyJavaType.handleMroError](https://github.com/jythontools/jython/blob/38a80c032234889ce0dcad013e4505ba82af5615/src/org/python/core/PyJavaType.java#L226-L250) is part of jythontools/jython@057a2c6.
- Related Jython bug: https://bugs.jython.org/issue2445.
