### ISSUE TITLE
openjdk8_j9_special.system -Xgcpolicy:gencon -Xquickstart gpf

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6945]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/236

10:21:42  FAILED test targets:
10:21:42  	DaaLoadTest_daa1_special_27
10:21:42  	DaaLoadTest_all_special_27

03:24:08  variation: Mode615
03:24:08  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xquickstart -Xjit 

```
03:24:13  DLT stderr Unhandled exception
03:24:13  DLT stderr Type=Segmentation error vmState=0x00000000
03:24:13  DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
03:24:13  DLT stderr Handler1=00007FE490B7E330 Handler2=00007FE490477B50 InaccessibleAddress=0000000000000012
03:24:13  DLT stderr RDI=0000000000000000 RSI=0000000000A95FF0 RAX=0000000000000000 RBX=0000000000A95FF0
03:24:13  DLT stderr RCX=0000000000000000 RDX=0000000000001000 R8=0000000000000001 R9=0000000000000000
03:24:13  DLT stderr R10=00000000FFF0BFE8 R11=0000000000000000 R12=0000000000000000 R13=0000000000000002
03:24:13  DLT stderr R14=00007FE438E12CF8 R15=00007FE491CDB020
03:24:13  DLT stderr RIP=00007FE484FB5776 GS=0000 FS=0000 RSP=00007FE491CDACA0
03:24:13  DLT stderr EFlags=0000000000010246 CS=0033 RBP=0000000000001000 ERR=0000000000000004
03:24:13  DLT stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000012
03:24:13  DLT stderr xmm0 0000000000a720e0 (f: 10952928.000000, d: 5.411465e-317)
03:24:13  DLT stderr xmm1 0000000047e15f80 (f: 1205952384.000000, d: 5.958196e-315)
03:24:13  DLT stderr xmm2 00007fe491cdb820 (f: 2446178304.000000, d: 6.947535e-310)
03:24:13  DLT stderr xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
03:24:13  DLT stderr xmm4 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
03:24:13  DLT stderr xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
03:24:13  DLT stderr xmm6 00000000485f3440 (f: 1214198784.000000, d: 5.998939e-315)
03:24:13  DLT stderr xmm7 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
03:24:13  DLT stderr xmm8 402f08506c58b189 (f: 1817751936.000000, d: 1.551624e+01)
03:24:13  DLT stderr xmm9 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
03:24:13  DLT stderr xmm10 becc000000000000 (f: 0.000000, d: -3.337860e-06)
03:24:13  DLT stderr xmm11 3d75474c359916f1 (f: 899225344.000000, d: 1.209543e-12)
03:24:13  DLT stderr xmm12 bec570575b61f43c (f: 1533146112.000000, d: -2.555708e-06)
03:24:13  DLT stderr xmm13 bbbd05546abbf59c (f: 1790702976.000000, d: -6.145398e-21)
03:24:13  DLT stderr xmm14 402e7f9c1e980d00 (f: 513281280.000000, d: 1.524924e+01)
03:24:13  DLT stderr xmm15 40f98e189a5be639 (f: 2589713920.000000, d: 1.046735e+05)
03:24:13  DLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
03:24:13  DLT stderr Module_base_address=00007FE484E5F000
03:24:13  DLT stderr Target=2_90_20190902_134 (Linux 2.6.32-754.11.1.el6.x86_64)
03:24:13  DLT stderr CPU=amd64 (4 logical CPUs) (0x1ec001000 RAM)
03:24:13  DLT stderr ----------- Stack Backtrace -----------
03:24:13  DLT stderr (0x00007FE484FB5776 [libj9jit29.so+0x156776])
03:24:13  DLT stderr (0x00007FE484F8427A [libj9jit29.so+0x12527a])
03:24:13  DLT stderr (0x00007FE484F8455F [libj9jit29.so+0x12555f])
03:24:13  DLT stderr (0x00007FE48507FFFF [libj9jit29.so+0x220fff])
03:24:13  DLT stderr (0x00007FE484FA1BFA [libj9jit29.so+0x142bfa])
03:24:13  DLT stderr (0x00007FE490B7F8F7 [libj9vm29.so+0xa08f7])
03:24:13  DLT stderr (0x00007FE490AF7C18 [libj9vm29.so+0x18c18])
03:24:13  DLT stderr (0x00007FE48568D818 [libj9jit29.so+0x82e818])
03:24:13  DLT stderr (0x00007FE48569EC86 [libj9jit29.so+0x83fc86])
```

**Comment by pshipton** [comment]
@andrewcraik

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/239

03:41:16  FAILED test targets:
03:41:16  	MathLoadTest_all_special_26
03:41:16  	MathLoadTest_bigdecimal_special_27

03:16:27  variation: Mode615
03:16:27  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xquickstart -Xjit 

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/238

01:16:10  FAILED test targets:
01:16:10  	LambdaLoadTest_OpenJ9_Linux_CompressedRefs_special_27

01:14:22  variation: Mode615
01:14:22  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xquickstart -Xjit 

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/240

03:59:45  FAILED test targets:
03:59:45  	MauveMultiThreadLoadTest_special_23
03:59:45  	MauveSingleInvocationLoadTest_special_23

02:21:05  variation: Mode615
02:21:05  JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xquickstart -Xjit

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/236
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/238
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/240
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/242
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/239

**Comment by pshipton** [comment]
Seems to fail on all platforms, at least all which are running these tests.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/169
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_s390x_linux_Nightly/235

**Comment by pshipton** [comment]
First failures in nightly build https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-All/628/  Aug 30, 2019 10:11:00 PM

OpenJ9: 347c34b
OMR: 5628a97
OpenJDK8: efd7298 - openj9-openjdk-jdk8
OpenJDK11: 259a016 - openj9-openjdk-jdk11

previous nightly build shas

OpenJ9: c49db01
OMR: 59bcb31
OpenJDK8: efd7298 - openj9-openjdk-jdk8
OpenJDK11: 259a016 - openj9-openjdk-jdk11

https://github.com/eclipse/openj9/compare/c49db01...347c34b
https://github.com/eclipse/openj9-omr/compare/59bcb31...5628a97

**Comment by andrewcraik** [comment]
@ymanton you had a number of merges to master - cross platform fails would not have been caused by Henry's change so your changes are next most likely. Could you take a look?

**Comment by ymanton** [comment]
Looking.

**Comment by ymanton** [comment]
Reproduced, fixing, PR soon.
