### ISSUE TITLE
Private static final field java/net/HttpURLConnection.methods corrupted.

### ISSUE THREAD

**Issue by manqingl** [eclipse/openj9#6947]
> j9statics 0x00000000022F8000
Static fields in java/net/HttpURLConnection:
       0x00000000022F85D8 DEFAULT_CHUNK_SIZE I (!j9romstaticfieldshape 0x00007FDA18137480) = 0x00001000 (4096)
       0x00000000022F85E0 followRedirects Z (!j9romstaticfieldshape 0x00007FDA181374A8) = 0x00000001 (1)
       0x00000000022F85D0 methods [Ljava/lang/String; (!j9romstaticfieldshape 0x00007FDA181374C0) = !j9object 0x0066002F006F0070 <-- BOGUS
       0x00000000022F85E8 HTTP_OK I (!j9romstaticfieldshape 0x00007FDA181374CC) = 0x000000C8 (200)
> j9object 0x0066002F006F0070
Problem running command:
null
>
From the heap, I found two objects of type java/lang/reflect/Field: both of them have the field "name" as string object "methods" and the field "clazz" as an instance of  type "java/net/HttpURLConnection"

**Comment by DanHeidinga** [comment]
If the fix isn't too risky, we should consider it for the Java 13 (0.16.0) release as well
