### ISSUE TITLE
We need to have copyrightschecker job running for JDK13. 

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#6959]
We need to have copyrightschecker job running  for JDK13
Currently, we have for 8, 11 and 12 but not for 13.  

https://ci.eclipse.org/openj9/view/Infrastructure/

**Comment by DanHeidinga** [comment]
@AdamBrousseau Can you help set this up?

**Comment by AdamBrousseau** [comment]
Unfortunately I do not have access to the CI anymore. Should be a copy paste of the 12 job.
From the [Infrastructure view](https://ci.eclipse.org/openj9/view/Infrastructure/), `New Item`
Name = CopyrightCheck-OpenJDK13
Copy From = CopyrightCheck-OpenJDK12
`OK`
Change default value of `ghprbGhRepository` param to `ibmruntimes/openj9-openjdk-jdk13`
`Save`

**Comment by smlambert** [comment]
Done.

**Comment by DanHeidinga** [comment]
Do we need a PR against the eclipse jenkins as code repo for this change to prevent it from being reverted the next time jenkins is redeployed?

**Comment by AdamBrousseau** [comment]
>Do we need a PR

No, jobs are not part of Configuration as Code (CasC). CasC handles basically everything under "Manage Jenkins" , ie. global settings.

**Comment by pshipton** [comment]
Note there is a failure```
```
12:52:31  E012: src/java.smartcardio/unix/native/libj2pcsc/MUSCLE/COPYING: GPLv2 is present but Classpath exception is missing
12:52:31  Did not find src/java.smartcardio/unix/native/libj2pcsc/MUSCLE/COPYING in known failures file /home/jenkins/jenkins-agent/workspace/CopyrightCheck-OpenJDK13/workdir/ibmruntimes/openj9-openjdk-jdk13.git/copyrightCheck.known.failures, treating as error

**Comment by archanaNogriya** [comment]
Thanks, let me check those failures, seems to be a new one.

**Comment by archanaNogriya** [comment]
after investigation, it seems src/java.smartcardio/unix/native/libj2pcsc/MUSCLE/COPYING is only a legal file which is causing this failure and as this file explain the files which is under GPL V2 but does not have classpath exception does not exist in the path system and does not includes into JDK build. hence we decided to keep this file in to exclude list for our copyrighstChecker.
