### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/LFCaching/LFMultiThreadCachingTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#6963]
Failure link
------------

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/259a016054953a431bbcb198848372c7830116ad/test/jdk/java/lang/invoke/LFCaching/LFMultiThreadCachingTest.java#L1 (JDK11)
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/c85b84056711e44d349a1d967eca1e7ace723566/jdk/test/java/lang/invoke/LFCaching/LFMultiThreadCachingTest.java#L1 (JDK8) 
are both consistently failing on openj9 builds (Hotspot unaffected)
- test category, openjdk
- OS/architecture, all platforms
```
15:35:14  openjdk version "1.8.0_232"
15:35:14  OpenJDK Runtime Environment (build 1.8.0_232-201909030344-b03)
15:35:14  Eclipse OpenJ9 VM (build master-cc749fa0a, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190903_405 (JIT enabled, AOT enabled)
15:35:14  OpenJ9   - cc749fa0a
15:35:14  OMR      - 5628a974
15:35:14  JCL      - efd729851b based on jdk8u232-b03)
```

Optional info
-------------

- intermittent failure (no): 
- new test:  
- Possibly related to https://github.com/eclipse/openj9/issues/6768
- `setAccessbile()` appears to be broken for openj9. I have not yet confirmed this however.

Failure output (captured from console output)
---------------------------------------------
```
STDOUT:
15:37:07  -Dseed=7805373624086692045
15:37:07  -DtestLimit=2000
15:37:07  STDERR:
15:37:07  java.lang.Error: Unexpected exception
15:37:07  	at LambdaFormTestCase.<clinit>(LambdaFormTestCase.java:73)
15:37:07  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:37:07  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:37:07  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:37:07  	at java.lang.reflect.Method.invoke(Method.java:498)
15:37:07  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:37:07  	at java.lang.Thread.run(Thread.java:819)
15:37:07  Caused by: java.lang.NoSuchFieldException: debugName
15:37:07  	at java.lang.Class.getDeclaredField(Class.java:820)
15:37:07  	at LambdaFormTestCase.<clinit>(LambdaFormTestCase.java:67)
15:37:07  	... 6 more
15:37:07  STATUS:Failed.`main' threw exception: java.lang.Error: Unexpected exception
```

**Comment by pshipton** [comment]
I expect this test is using internals that don't apply to OpenJ9
```
 java.lang.NoSuchFieldException: debugName
15:37:07  	at java.lang.Class.getDeclaredField(Class.java:820)
```

**Comment by M-Davies** [comment]
I also suspected this was the case based on similar issues (https://github.com/eclipse/openj9/issues/6700, https://github.com/eclipse/openj9/issues/6660). I'll close this and add it to the permanent exclusions list

**Comment by M-Davies** [comment]
java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java also fails in the same way. Will exclude this too
