### ISSUE TITLE
OpenJ9 ub16-390-2 went offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6975]
ub16-390-2 went offline while running system testing, around 4am. It needs to be brought back online.
https://ci.eclipse.org/openj9/view/all/job/Test_openjdk8_j9_special.system_s390x_linux_Nightly/260
https://ci.eclipse.org/openj9/computer/ub16-390-2/

**Comment by AdamBrousseau** [comment]
I pinged @vivkong. She says there's a planned outage this weekend so she will follow up on Monday.
That tells me it may come back after the outage (possibility). I will follow up with her then.

**Comment by AdamBrousseau** [comment]
All 390 back online now.
