### ISSUE TITLE
AArch64 pipeline builds fail w/ DDR

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#6979]
The AArch64 pipeline builds fail while building the Java classes for DDR, presumably because DDR isn't available yet on AArch64 (#5221).

Attached is the failing console output lest the CI link vanishes ->  [cf2.txt](https://github.com/eclipse/openj9/files/3580392/cf2.txt)

I believe the remedy is to configure with `--disable-ddr`.  @keithc-ca, can you confirm if that will fix this problem?

**Comment by 0xdaryl** [comment]
FYI : @knn-k @Akira1Saitoh

**Comment by keithc-ca** [comment]
> I believe the remedy is to configure with --disable-ddr. @keithc-ca, can you confirm if that will fix this problem?

No, DDR should already be disabled in that build (it is still the default for aarch64). The problem is that tests don't recognize that the JDK being tested doesn't support DDR.

**Comment by 0xdaryl** [comment]
@smlambert @llxia : can I provide an `excluded_tests:` in the YAML file for AArch64 to have it skip the DDR_Test ?  If so, what is the syntax I should use?

**Comment by llxia** [comment]
To exclude, two changes are needed:
- in build.xml, skip test compilation if it is aarch64 
https://github.com/eclipse/openj9/blob/77b3ec8449d1bbb4c6eecb53e73f56d64441054c/test/functional/DDR_Test/build.xml#L111
- in playlist.xml, add `^arch.aarch64` in `platformRequirements`
https://github.com/eclipse/openj9/blob/77b3ec8449d1bbb4c6eecb53e73f56d64441054c/test/functional/DDR_Test/playlist.xml#L49

**Comment by keithc-ca** [comment]
A better solution might be to look for `j9ddr.jar` in the JDK being tested.

**Comment by knn-k** [comment]
AArch64 runtime does not have j9ddr.jar nor the lib/ddr directory now.

**Comment by keithc-ca** [comment]
That's my point, if the test only tried to build if j9ddr.jar can be found, it would adapt properly.

**Comment by knn-k** [comment]
I think this can be closed now.
We still need `--disable-ddr` in cross-build environment, and that is tracked by #8814.

**Comment by 0xdaryl** [comment]
Resolved.
