### ISSUE TITLE
Run special.system testing on the weekends

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6982]
special.system testing, which runs the system testing in many different "modes"`*` takes considerable machine time to run. OpenJ9 nightly builds run special.system for JDK8 on all the platforms which have enough machines to support it. There is spare machine time on the weekends, when committers are not typically running PR testing or causing OMR acceptance builds. We can use this spare machine time to run additional special.system test builds to improve the coverage for JDK11, JDK13+, and the JDK8 platforms that don't run nightly.

`*` modes are different sets of command line options

**Comment by pshipton** [comment]
The currently blocker for setting this up is that special.system tests which don't run nightly are excluded in the defaults.yml file. I'm hoping we can find a way to keep the nightly builds the same while having a weekend build with more coverage.

**Comment by pshipton** [comment]
@llxia @smlambert @DanHeidinga

**Comment by pshipton** [comment]
The special.system tests run in parallel. Some of the parallel jobs run much quicker than others. We should also investigate splitting the longest running jobs to get more parallelization.

**Comment by llxia** [comment]
- `defaults.yml` is used and controlled in the upstream build/pipeline to trigger downstream builds. Test builds do not use it. @AdamBrousseau should have more inside on this.

- I think a better solution is to set artifactory properly so we can get nightly SDK. Similar to https://api.adoptopenjdk.net/ In this way, we can configure to run any test build at any time.

**Comment by smlambert** [comment]
I would very much like to see more ways into accessing sdk builds on artifactory (leveraging the features of artifactory more whole-heartedly).

This may nicely address the need stated above of 'give me the latest nightly build' (artifactoryserver/spec/nightlyTimeStamp or ?lastModified), but also to allow for easier triaging and reproduction of issues by devs (artifactoryserver/prNumber to get builds from pr builds), etc.  

Tagging @R-Santhir as it relates to an efficiency issue we have been discussing called 'Persistent Test Material on OpenJ9 Test runs'

**Comment by smlambert** [comment]
Also a note on the defaults.yml, I have noticed that some jobs that will never get used are being generated nightly on the internal repo.  This makes it more difficult to see the jobs that are in use (and one can not simply delete them, as each night they are spawned again).  It may be good to revisit how we define which jobs are auto-generated so that it is more flexible, but as Lan mentioned, we do not use the defaults.yml stuff, so I may misunderstand what is possible.

**Comment by pshipton** [comment]
While we ponder a better way, I've set up a build using a copy of the defaults.yml file with the excludes removed. https://ci.eclipse.org/openj9/job/Pipeline-Special-System-JDK11/

**Comment by pshipton** [comment]
Since we have a working solution, I'll close this.
