### ISSUE TITLE
DDR not supported by exploded-image

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#6998]
Using the JDK11 Dockerfile and adding the test dependencies needed to build and execute tests by running the following commands:

```
apt-get install -qq -y --no-install-recommends ant ant-contrib perl
echo yes | cpan install JSON Text::CSV XML::Parser
```

Then trying to build the tests:

```
cd /java/openj9-openjdk-jdk11/openj9/test/TestConfig
export BUILD_LIST=functional
make -f run_configure.mk
make compile
```

The test compilation fails at this point:

```
compile:
     [echo] Ant version is Apache Ant(TM) version 1.9.6 compiled on July 20 2018
     [echo] ============COMPILER SETTINGS============
     [echo] ===fork:                         yes
     [echo] ===executable:                   /java/openj9-openjdk-jdk11/build/linux-s390x-normal-server-release/jdk/bin/javac
     [echo] ===debug:                        on
     [echo] ===destdir:                      /java/openj9-openjdk-jdk11/openj9/test/TestConfig/../../jvmtest/functional/DDR_Test
    [javac] Compiling 54 source files to /java/openj9-openjdk-jdk11/openj9/test/functional/DDR_Test/bin
    [javac] /java/openj9-openjdk-jdk11/openj9/test/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java:60: error: package com.ibm.j9ddr.tools.ddrinteractive does not exist
    [javac] import com.ibm.j9ddr.tools.ddrinteractive.Context;
    [javac]                                          ^
    [javac] /java/openj9-openjdk-jdk11/openj9/test/functional/DDR_Test/src/j9vm/test/ddrext/AutoRun.java:310: error: cannot find symbol
    [javac]     public static void runTest(Context ctx, PrintStream out, String testCaseList) {
```

It seems like the same errors encountered in #3366. Removing the `DDR_Test` directory and running `make compile` works around the problem.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
See also #6994.

**Comment by pshipton** [comment]
Since DDR is supported and enabled for zLinux, it seems strange the DDR tests cannot compile.

**Comment by keithc-ca** [comment]
It appears `TEST_JDK_HOME` was improperly specified as
```
/java/openj9-openjdk-jdk11/build/linux-s390x-normal-server-release/jdk
```
when it should have been
```
/java/openj9-openjdk-jdk11/build/linux-s390x-normal-server-release/images/jdk
```
The former does not support DDR while the latter should (if it was enabled at configuration time).

**Comment by DanHeidinga** [comment]
> The former does not support DDR while the latter should (if it was enabled at configuration time).

Why doesn't DDR work for the build in `/jdk`?

**Comment by fjeremic** [comment]
I've just tested with:

```
/java/openj9-openjdk-jdk11/build/linux-s390x-normal-server-release/images/jdk
```

And everything is working as expected. Interesting caveat. I'd also like to understand why `/jdk` does not work.

**Comment by keithc-ca** [comment]
> Why doesn't DDR work for the build in `/jdk`?

I was under the impression that `/jdk` (as opposed to `/images/jdk`) was not _expected_ to be a full JDK - it only needed to be capable enough to build `/images/jdk`, etc. Given that belief, I never arranged for DDR artifacts to be present in `/jdk`. The comment [1] suggests otherwise. Let's repurpose this issue to fix that.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/make/Main.gmk#L951

**Comment by keithc-ca** [comment]
Fixed via the three PRs linked above; closing.
