### ISSUE TITLE
Dockerfile for buildenv jdk11 x86_64 image uses jdk10

### ISSUE THREAD

**Issue by gyuuu** [eclipse/openj9#7036]
[Dockerfile for **jdk11** x86_64](https://raw.githubusercontent.com/eclipse/openj9/master/buildenv/docker/jdk11/x86_64/ubuntu16/Dockerfile) installs **jdk 10** to this folder: **/root/bootjdk10**

The relevant section of the dockerfile:
```
# Download and install boot JDK from AdoptOpenJDK
RUN cd /root \
  && wget -O bootjdk10.tar.gz "https://api.adoptopenjdk.net/v2/binary/releases/openjdk10?openjdk_impl=openj9&os=linux&arch=x64&release=latest&type=jdk" \
  && tar -xzf bootjdk10.tar.gz \
  && rm -f bootjdk10.tar.gz \
  && mv $(ls | grep -i jdk) bootjdk10

# Set environment variable JAVA_HOME, and prepend ${JAVA_HOME}/bin to PATH
ENV JAVA_HOME="/root/bootjdk10"
```

Runing **java -version** in the image built with this file outputs this:
```
openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 10 Linux amd64-64-Bit Compressed References 20180813_102 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13)
```

**Comment by pshipton** [comment]
jdk10 is used to build jdk11. Is there a problem?

**Comment by pshipton** [comment]
Try running `./java -version` instead

**Comment by gyuuu** [comment]
> Try running `./java -version` instead

I did, please check to output in my first comment.

And the **arm version** of this file **uses this download link** [https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk](https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk)

**Updating to that link, java -version** outputs:
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

**Comment by gyuuu** [comment]
> Try running `./java -version` instead

Oh, I see why you replied with this. I did run java -version in the docker image with **docker run {imagehash} java -version**

**Comment by pshipton** [comment]
We could build jdk11 using jdk11, as is done for arm, but jdk11 isn't available at all or for download when we first start building it so the previous java version is used. The docker file puts the previous version on the path, but that doesn't mean it isn't building jdk11. You can run jdk11 from the build/<platform>/images/jdk directory after it is built.

**Comment by gyuuu** [comment]
Seems like I **misunderstood the purpose of those files**, despite the fact that the folder name **buildenv** is quite obvious. 
I thought these are used to build docker images for running applications with openj9, sorry for that
