### ISSUE TITLE
openjdk11_j9_extended.functional_ppc64_aix testSCCMLSoftmx_1 not found Stored JITHINT attached data

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7045]
```
04:58:31  To rebuild the failed test in a jenkins job, copy the following link and fill out the <Jenkins URL> and <FAILED test target>:
04:58:31  <Jenkins URL>/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&TARGET=<FAILED test target>
```
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/132
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/133
testSCCMLSoftmx_1 
```
>> Required condition was not found: [Output match: Stored JITHINT attached data]
```

Last pass
OpenJ9: 92ad03e
OMR: 7e9584e
OpenJDK8: efd7298 - openj9-openjdk-jdk8
OpenJDK11: 3c31c8c - openj9-openjdk-jdk11

First failure
OpenJ9: b2e5ef8
OMR: 7e9584e
OpenJDK8: e4489bd - openj9-openjdk-jdk8
OpenJDK11: 3c31c8c - openj9-openjdk-jdk11

https://github.com/eclipse/openj9/compare/92ad03e...b2e5ef8
Likely https://github.com/eclipse/openj9/pull/7021
@mpirvu @hangshao0

**Comment by ymanton** [comment]
This is caused by a compiler bug. The stack location containing the hint we fetch from the SCC is read and tested for `!=0` before it is written to, so we intermittently take the wrong path and try to update a non-existent hint, which fails.

**Comment by mpirvu** [comment]
> This is caused by a compiler bug

@ymanton, while waiting for a compiler fix, is it possible to circumvent the bug by changing the code slightly?

**Comment by mpirvu** [comment]
What if we change
```
      uint32_t scHintData = getHint(vmThread, method);
      uint16_t *hintFlags = (uint16_t *)&scHintData;
      uint16_t *hintCount = ((uint16_t *)&scHintData) + 1; // Flags and new count field needs to be in contiguous location to be stored into sharecache

      const uint32_t scHintDataLength = sizeof(scHintData);

      if (*hintFlags == 0) // If no prior hints exist, we can perform a "storeAttachedData" operation
```
into
```
      uint32_t scHintData = getHint(vmThread, method);
...
      if (scHintData  == 0) // If no prior hints exist, we can perform a "storeAttachedData" operation
```

**Comment by ymanton** [comment]
Yes I can give that a try.
