### ISSUE TITLE
Why does Z use `splitWarmAndColdBlocks` and other codegens do not?

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#7049]
According to [1] and [2] the Z codegen will end up executing the `splitWarmAndColdBlocks` function in [3] which seems to traverse the treetops looking for the first cold block that is not followed by any warm blocks. It then inserts a `TR::GoTo` between this first cold block and the next block.

I assume this is historic code from when we used to split warm and cold blocks into different code caches? I do not think we do that anymore and such code may have been deprecated. In this case I do not see the value of performing the `SplitWarmAndColdBlocksPhase`.

We also do not do this on any other codegen. I'm wondering if anyone knows the history behind this as I want to slate it for deprecation.

[1] https://github.com/eclipse/openj9/blob/d6574267193c6bb495b9b0d04fdcddec5c57553b/runtime/compiler/z/codegen/CodeGenPhaseToPerform.hpp#L45
[2] https://github.com/eclipse/openj9/blob/d6574267193c6bb495b9b0d04fdcddec5c57553b/runtime/compiler/z/codegen/J9CodeGenerator.hpp#L234
[3] https://github.com/eclipse/openj9/blob/d6574267193c6bb495b9b0d04fdcddec5c57553b/runtime/compiler/codegen/J9CodeGenerator.cpp#L2270-L2403

**Comment by fjeremic** [comment]
Tagging a few people (@joransiu @0xdaryl @dsouzai @mpirvu) who many be knowledgeable in the area .

**Comment by mpirvu** [comment]
I don't know either and I can only guess it was done on Z because of some experiments that showed some improvements. In theory the idea sounds good: keep all the hot code together to improve cache and tlb locality.

**Comment by joransiu** [comment]
Yeah, that was the theory.  I vaguely recall we had measured 1-2% from Tiered Code Caches support over a decade ago: (separate code caches for hot/scorchinng methods + splitting warm/code blocks within a method).  I believe more "recent" measurements when we got rid of TCC showed performance benefits were a wash?

**Comment by fjeremic** [comment]
The function seems to have eroded though. It doesn't perform any "split". It simply seems to insert a `TR::GoTo`. According to calls to `allocateCodeMemory` no one ever seems to allocate any cold code caches either. I'm thinking this phase is dead, or so it appears at least.

**Comment by fjeremic** [comment]
For future reference the performance evaluation was done in https://github.com/eclipse/openj9/pull/7102#issuecomment-532699293 which showed this phase has no effect on throughput performance.
