### ISSUE TITLE
JVM_ socket functions should handle EINTR

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#705]
All the JVM_ functions related to socket operations should deal with EINTR, similarly to the file operations.

**Comment by pshipton** [comment]
Although it seems many (most?) of the JVM_ socket functions aren't actually used, so only the funtions being used need to be fixed.

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this as well?

**Comment by theresa-m** [comment]
These are all the socket related JVM_ methods I've found and it looks like none of them are being called:

- JVM_Accept: not called
- JVM_Connect: not called
- JVM_Listen: not called
- JVM_Recv: not called
- JVM_RecvFrom: not called
- JVM_Send: not called
- JVM_SendTo: not called
- JVM_Socket: not called
- JVM_SocketAvailable: not called
- JVM_SocketClose: not called
- JVM_InitializeSocketLibrary: not called

**Comment by pdbain-ibm** [comment]
Adding a link to the issue to remove Harmony: https://github.com/eclipse/openj9/issues/529

**Comment by pshipton** [comment]
@theresa-m they may not be called on Java 9, but at least JVM_SocketAvailable is called on Java 8. Please check if there is anything else.

**Comment by theresa-m** [comment]
Woops I'm looking in the wrong repos. All the above are referenced in Java 8, but none are referenced in Java 9.
