### ISSUE TITLE
has support for "ibm.cl.verbose=*ClassName" been dropped?

### ISSUE THREAD

**Issue by sadaaithal** [eclipse/openj9#7053]
Hi

ibm.cl.verbose feature was convinient for troubleshooting classloader problems. 

This used to work in most of IBM J9 VM's.. 
Example:

```
c:\Users\saithal>C:\Work\ibm_eclipse\ibm_sdk80\jre\bin\java -showversion -Dibm.cl.verbose=*HelloWorld HelloWorld
java version "1.8.0"
Java(TM) SE Runtime Environment (build pwa6480sr4fp1-20170215_01(SR4 FP1))
IBM J9 VM (build 2.8, JRE 1.8.0 Windows 10 amd64-64 Compressed References 20170209_336038 (JIT enabled, AOT enabled)
J9VM - R28_20170209_0201_B336038
JIT  - tr.r14.java.green_20170125_131456
GC   - R28_20170209_0201_B336038_CMPRSS
J9CL - 20170209_336038)
JCL - 20170215_01 based on Oracle jdk8u121-b13

ExtClassLoader attempting to find HelloWorld
ExtClassLoader using classpath C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\access-bridge-64.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\cldrdata.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\CmpCrmf.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dnsns.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dtfj-interface.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dtfj.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dtfjview.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\gskikm.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\healthcenter.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmcac.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmcmsprovider.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmjcefips.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmjceprovider.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmkeycert.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmpkcs11impl.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmsaslprovider.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\IBMSecureRandom.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmxmlcrypto.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmxmldsigprovider.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmxmlencprovider.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\jaccess.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\localedata.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\nashorn.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\traceformat.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\xmlencfw.jar;C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\zipfs.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\access-bridge-64.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\cldrdata.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\CmpCrmf.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dnsns.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dtfj-interface.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dtfj.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\dtfjview.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\gskikm.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\healthcenter.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmcac.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmcmsprovider.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmjcefips.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmjceprovider.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmkeycert.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmpkcs11impl.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmsaslprovider.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\IBMSecureRandom.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmxmlcrypto.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmxmldsigprovider.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\ibmxmlencprovider.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\jaccess.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\localedata.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\nashorn.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\traceformat.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\xmlencfw.jar
ExtClassLoader could not find HelloWorld.class in C:\Work\ibm_eclipse\ibm_sdk80\jre\lib\ext\zipfs.jar
ExtClassLoader could not find HelloWorld

AppClassLoader attempting to find HelloWorld
AppClassLoader using classpath C:\Users\saithal
AppClassLoader found HelloWorld.class in C:\Users\saithal
AppClassLoader found HelloWorld


HelloWorld
```

This no longer works in 1.8 Open J9. 
I have one on Linux with the following version this doesnt work

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b03)
Eclipse OpenJ9 VM (build openj9-0.14.0, JRE 1.8.0 Linux amd64-64-Bit 20190417_251 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5590c4f818 based on jdk8u212-b03)

So I downloaded the latest Open J9 version - that is v12.
And it doesnt work there as well

```
c:\Users\saithal>C:\Work\SDK_64\jdk-12.0.2+10-jre\bin\java -showversion -Dibm.cl.verbose=*HelloWorld HelloWorld
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 12 Windows 10 amd64-64-Bit Compressed References 20190718_139 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - 06c2cc3322 based on jdk-12.0.2+10)
HelloWorld
```

This is a good to have feature. 
If this cannot be added, could you let me know if there's an equivalent that I should use. 

thank you!
sada

**Comment by pshipton** [comment]
The feature is still part of IBM Java, but it wasn't ported to the OpenJDK extensions for OpenJ9.

**Comment by adamfarley** [comment]
Taking a look at this now.

**Comment by adamfarley** [comment]
The code works on OpenJDK8 on OpenJ9, but doesn't work on Openjdk9+. Because modularity.

Information such as whether a class was loaded and where it physically is on the disk can be obtained via the "-verbose:class" command line option.

However, the following information can't be gotten via that option:

- Which ClassLoader/s tried to load that class.
- What each ClassLoaders' classpath was.
- What happened when each ClassLoader tried to access each location on the classapath.

Will see if we can get that info via other means before we start cracking on porting code.

(P.S. Simply porting the code as-is, even with significant changes, doesn't produce the info from their current classes. Because modularity.)

**Comment by adamfarley** [comment]
The bad news is that there seems no way to get the information without this option.

The good news is I figured out how to make the option work again.

Once I've received approval to contribute the code, I'll create a PR.

**Comment by adamfarley** [comment]
OpenJDK Bug raised: https://bugs.openjdk.java.net/browse/JDK-8232773

**Comment by adamfarley** [comment]
FYI: Still chasing this. Some progress, though no commit yet.

**Comment by adamfarley** [comment]
After some investigation and emails with the OpenJDK community, it seems this feature will not be accepted into upstream OpenJDK.

The change set required to add the feature into a modularity JDK is linked in the OpenJDK bug above, and a custom build could be generated with this change is the debug output is needed.

After asking around, it doesn't seem as if there is sufficient demand for this change set to justify adding it into Extensions, so the usual OpenJDKx with OpenJ9 builds will not have this change set unless that changes.

The good news is that there are still ways to get some of the information.

The identity of the ClassLoader that loaded a class can be obtained via:

```
x.getClass().getClassLoader().getName();
```

The location that a class was loaded from can be obtained by searching through the output from a java command-line execution using the "-verbose:class" command-line option.

To generate some debug output from URLClassPath as it tries to load classes, set the system property "sun.misc.URLClassPath.debug" to a non-null value.

Further debug output can be retrieved the hard way through core files. The community suggests jcmdand something called "Unified JVM Logging" could also be useful, though I don't have details.

Opening the floor to thoughts from the room.

**Comment by DanHeidinga** [comment]
@adamfarley For the alternatives that were presented by the OpenJDK community, how many of them work on OpenJ9?  
Does Healthcenter provide the equivalent info to the JFR events they mentioned?
Does the jcmd utility provide that functionality on OpenJ9?
Do the -Xlog options work?

It would be good to test these on OpenJ9 and figure out what info is available and then circle back to @sadaaithal to see if the existing options solve his issue.

**Comment by adamfarley** [comment]
@DanHeidinga
- Alternatives - Except for jcmd and Xlog, all of the options I mentioned are useful and seem to work find on OpenJ9 as they are Class Library based.
- Healthcenter - I don't know, as I wasn't aware Healthcenter was supported with OpenJDK on OpenJ9. Are we encouraging people to use Healthcenter with OpenJDK on OpenJ9?
- jcmd - On further examination, I don't believe so. It appears that the primary value in this, from a ClassLoader perspective, is to send JFR commands, which I don't believe OpenJ9 is set up to work with. It can generate some debug output, like stack traces, but I don't see a use for that in this case.
- Xlog - This appears to work, but some trial runs with basic options (e.g. -Xlog:all) doesn't appear to give additional classloading information.

**Comment by DanHeidinga** [comment]
We support the healthcenter tool as much as we can and encourage its use.  There are some difficulties in getting updated agents but those will hopefully be resolved in the future.

For Xlog, is the information equivalent for the classloading case?

**Comment by adamfarley** [comment]
Thanks for the update on Healthcenter.

As for Xlog, the answer is no; the information is not equivalent.

a simple testcase shows no output for -Xlog:all on OpenJ9, unless you get the format wrong (in which case it tells you how to use -Xlog correctly).

On Hotspot, -Xlog:all provides a lot of information, such as class validation, and the location that the class was loaded from.

Also, OpenJ9 says "-Xlog" on its own is an incorrect use of the option. Hotspot correctly identifies -Xlog as equal to -Xlog:all.

**Comment by pshipton** [comment]
Note that `-Xlog` for OpenJ9 is currently a totally different option than for Hotspot. For OpenJ9 it controls which types of messages are sent to the OS console.
https://www.eclipse.org/openj9/docs/xlog/

**Comment by hangshao0** [comment]
> The code works on OpenJDK8 on OpenJ9, but doesn't work on Openjdk9+. Because modularity.

I have an impression that the code of "ibm.cl.verbose" is patched to URLClassLoader only on Java 8. On Java 9 and up, patching both URLClassLoader and BuiltinClassLoader with the "ibm.cl.verbose" code should make it work.

**Comment by adamfarley** [comment]
@hangshao0 - I mentioned in a subsequent comment that I found a way to make it work again. Perhaps I wasn't clear that I found a way to make it work *on modularity OpenJDKs*.

Modularity Java has a different structure for class loading, and required different messages, several extra debug methods, etc etc. Short version, if you added my change set (the one in the OpenJDK bug) into the JCL, it will now produce legible debug messages for classloading on modularity OpenJDKs.

**Comment by hangshao0** [comment]
Ah, I see.

**Comment by adamfarley** [comment]
@sadaaithal - Here is the resolution for this issue. Please review and let me know your thoughts.

*Summary*
- The command line option will not be accepted by the OpenJDK community upstream.
- This code makes CL option work (as jdk.cl.verbose) on jdk11, and can be used to create custom debug builds:
http://cr.openjdk.java.net/~afarley/8232773/webrev/
- Some of the information formerly provided by the CL option can be supplied by Healthcenter, x.getClass().getClassLoader().getName(), -verbose:class, -Dsun.misc.URLClassPath.debug=true, and core file analysis.

Note: a more detailed breakdown of the last point can be found here:
https://github.com/eclipse/openj9/issues/7053#issuecomment-577680372

**Comment by sadaaithal** [comment]
@adamfarley 
thanks for the details adam. i will try this one out on a local setup soon. 
for now, this issue can be closed given that we have other ways of getting the same info as "ibm.cl.verbose"
