### ISSUE TITLE
ARM: Crash during JIT compilation in OMR::Register::incTotalUseCount()

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#706]
On an ARM build of OpenJDK/OpenJ9 with directToJNI disabled, the JVM sometimes crashes during JIT compilation at the following location.  I used SPECjvm98 _228_jack to recreate this problem, but I see the same problem in some other benchmark programs trying to compile different Java methods.

> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x561ff460 (LWP 2407)]
> 0x75bbdfac in OMR::Register::incTotalUseCount(unsigned int) ()
>    from /home/pi/openj9/jdk/lib/libj9jit29.so
> (gdb) where
> #0  0x75bbdfac in OMR::Register::incTotalUseCount(unsigned int) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #1  0x75d9d5ac in generateTrg1Src2Instruction(TR::CodeGenerator*, TR_ARMOpCodes, TR::Node*, TR::Register*, TR::Register*, TR::Register*, TR::Instruction*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #2  0x75daf5e4 in OMR::ARM::TreeEvaluator::iandEvaluator(TR::Node*, TR::CodeGenerator*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #3  0x75bacb98 in OMR::CodeGenerator::evaluate(TR::Node*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #4  0x75db33e4 in OMR::ARM::TreeEvaluator::compareIntsForEquality(TR_ARMConditionCode, TR::Node*, TR::CodeGenerator*, TR::SymbolReference*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #5  0x75db39e0 in OMR::ARM::TreeEvaluator::ificmpeqEvaluator(TR::Node*, TR::CodeGenerator*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #6  0x75bacb98 in OMR::CodeGenerator::evaluate(TR::Node*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #7  0x75828938 in J9::CodeGenerator::doInstructionSelection() () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #8  0x75bb9ad8 in OMR::CodeGenPhase::performInstructionSelectionPhase(TR::CodeGenerator*, TR::CodeGenPhase*) () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #9  0x75bb87cc in OMR::CodeGenPhase::performAll() () from /home/pi/openj9/jdk/lib/libj9jit29.so
> #10 0x75bb6c74 in OMR::CodeGenerator::generateCode() () from /home/pi/openj9/jdk/lib/libj9jit29.so

**Comment by JamesKingdon** [comment]
Failing to generate an iand, I wonder how on earth that could go wrong! Many thanks for reporting the problem.

**Comment by knn-k** [comment]
I am trying to get a trace file for this, but it has not been successful yet because it is kind of timing-dependent.

**Comment by knn-k** [comment]
Root cause identified.  Evaluators for acmplt and acmpge are missing in the ARM version.

**Comment by knn-k** [comment]
I should have closed this issue earlier.  This was fixed by the change in OMR.

**Comment by JamesKingdon** [comment]
Many thanks @knn-k
