### ISSUE TITLE
Increase in number of messages in JITServer AOT mode

### ISSUE THREAD

**Issue by dmitry-ten** [eclipse/openj9#7072]
Messages `VM_isSameOrSuperClass` and `ClassEnv_getROMClassRefName` are now the 2 most frequent messages when running AcmeAir in AOT mode.
The first one is a new message and deals with determining if two classes are identical or one is a superclass of another. I wonder if we can just use `TR_J9ServerVM::isInstanceOf` here.
The second one seems to be an old message but the frequency increased after the rebase.

Will investigate how to reduce the number of these messages.

**Comment by dmitry-ten** [comment]
@mpirvu FYI.

**Comment by mpirvu** [comment]
For `VM_isSameOrSuperClass` I think you can use something similar to the implementation of `TR_J9ServerVM::instanceOfOrCheckCast(J9Class *instanceClass, J9Class* castClass)`
The difference is that you don't have to check for interfaces. I am unsure about arrays; the VM code doesn't seem to care about arrays.
Another filter that can be done is to check whether the two classes have the same classloader. If they don't then they cannot be related.

**Comment by mpirvu** [comment]
For `ClassEnv_getROMClassRefName` the key lines are
```
   J9ConstantPool *ramCP = reinterpret_cast<J9ConstantPool *>(comp->fej9()->getConstantPoolFromClass(clazz));
   J9ROMConstantPoolItem *romCP = ramCP->romConstantPool;
```
If the `romConstantPool` resides completely in the RomClass associated with the j9clazz given as parameter, then we cam compute the offset of `romConstantPool' from the beginning of the RomClass and cache that value for each j9class.

**Comment by mpirvu** [comment]
Those two messages have disappeared now, so this issue is fixed.
