### ISSUE TITLE
AArch64 pipeline builds failing because ‘cent7-aarch64-1’ is offline

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7083]
This appears to have been the case for a couple of days now.  Here's an example build:
https://ci.eclipse.org/openj9/job/Build_JDK11_aarch64_linux_xl_Personal/27/

@AdamBrousseau : would you mind having a look please?

@knn-k FYI

**Comment by jdekonin** [comment]
I had opened a ticket with Packet which is now resolved.  Machine is back online and taking jobs.  This issue can close.

**Comment by 0xdaryl** [comment]
Thanks @jdekonin !

**Comment by 0xdaryl** [comment]
I think something else needs to happen on this machine.  It is now stuck at:
```
19:39:04  Still waiting to schedule task
19:39:04  Waiting for next available executor on ‘cent7-aarch64-1’
```

**Comment by jdekonin** [comment]
I rebooted and its reconnected again.

**Comment by 0xdaryl** [comment]
Machine is reachable again.  Thanks.
