### ISSUE TITLE
Add Protobuf 3.7.1 to plinux,zlinux,xlinux

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#7099]
Protobuf 3.7.1 needs to be installed to plinux,zlinux,xlinux build-machines / docker-containers because it is needed to build JITServer (JITaaS) code.
Attn: @cwesMills @AdamBrousseau

**Comment by jdekonin** [comment]
This issue can be closed as pr has been delivered.  @mpirvu, I don't see a specific issue raised for zlinux requirement.  I've attached the 390 change and x86 update from 3.5.1 to 3.7.1 to this issue as well.  Can you modify the issue abstract accordingly or a new issue as you see fit.  I am good either way.

**Comment by mpirvu** [comment]
> Can you modify the issue abstract accordingly or a new issue as you see fit. 

I have changed the title and abstract to refer to all linux platforms

**Comment by dmitry-ten** [comment]
@mpirvu this issue can be closed, since protobuf has been removed from JITServer.
