### ISSUE TITLE
test/jdk/java/lang/StackWalker/ReflectionFrames.java contribution

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7124]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/4041598f624e2222be156557efbe508b2b682ae9/test/jdk/java/lang/StackWalker/ReflectionFrames.java#L1 is failing for openj9 (see https://github.com/eclipse/openj9/issues/6724).

- [x] Identify implementation frames to ignore https://github.com/eclipse/openj9/issues/6724#issuecomment-521627809
- [ ] Fix test case to ignore the frames specific to each implementation

**Comment by pdbain** [comment]
> Identify which implementation is incorrect

Neither is "incorrect"; each has additional implementation-dependent stack frames which are allowed but not specified by the API.  The test case should ignore these implementation-dependent frames.

**Comment by M-Davies** [comment]
@pdbain updated ^

**Comment by M-Davies** [comment]
Some frames might be cleared up by https://github.com/eclipse/openj9/pull/3627. Will build and test with this to check

**Comment by M-Davies** [comment]
Building with that PR failed

**Comment by M-Davies** [comment]
The `StackWalker` class has an option for `StackWalker.getInstance()` called `SHOW_HIDDEN_FRAMES` which, when used with `SHOW_REFLECT_FRAMES`, hides frames that are implementation specific.

This implies that the frames were supposed to be hidden by default but weren't for some reason because the failing tests were running without `SHOW_HIDDEN_FRAMES` or `SHOW_REFLECT_FRAMES` enabled.

**Comment by M-Davies** [comment]
This functionality should already be enabled considering the code in the constructor of `StackInspector` here: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/4041598f624e2222be156557efbe508b2b682ae9/test/jdk/java/lang/StackWalker/ReflectionFrames.java#L726 

@pdbain thoughts?

**Comment by pshipton** [comment]
OpenJ9 doesn't use the OpenJDK implemention for the StackWalker,  you have to look at the OpenJ9 code https://github.com/eclipse/openj9/blob/43f86dc478ddbddf25f1b640804baa49dc765dcb/jcl/src/java.base/share/classes/java/lang/StackWalker.java

**Comment by M-Davies** [comment]
Looking at the code for both HS and J9, this seems like a lot of effort to fix just one test. The test is only accounting for Hotspot frames to appear and there is no current function within the test that can filter out frames that are OpenJ9 specific (this would have to be made from scratch). OpenJ9 has a very different StackWalker class compared to Hotspot so the structure of the StackInspector class in the test would have to be changed too.

In addition to this,  any change made to the test would have to be approved upstream and I find it unlikely that it will be accepted by the community since we would, essentially, be modifying the test towards one implementation.

Closing this issue for the reasons stated above...
