### ISSUE TITLE
AArch64: Implement recognized java_nio_Bits_keepAlive and java_lang_ref_Reference_reachabilityFence

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7137]
Provide an inlined version of the recognized methods:
```
java_nio_Bits_keepAlive
java_lang_ref_Reference_reachabilityFence
```
Consult the semantics on other architectures to understand what needs to be done.

**Comment by sahithiponangi** [comment]
@0xdaryl I tried to get a successful build with TR_ASSERT_FATAL and checked logs with a sample program which I think will trigger the function(`inlineDirectCall`) I made changes in. 
`TR_ASSERT_FATAL` output could not be found in the log files. So I checked for how/when `inlineDirectCall` is called, but I didn't see it being called at all (except in a function in `Power` -> `directCallEvaluator`).
`directCallEvaluator` in Power and AArch64 do not match. Please let me know how to proceed.
