### ISSUE TITLE
AArch64 pipeline builds failing

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7160]
Currently, AArch64 pipeline builds are failing with simply:
```
ERROR: script returned exit code -2
Finished: FAILURE
```
It seems like things were going well up until the very end.

Example: https://ci.eclipse.org/openj9/job/Build_JDK11_aarch64_linux_xl_Personal/32/

@AdamBrousseau : could you take a peek when you have a chance please?

@knn-k @jdekonin : fyi

**Comment by AdamBrousseau** [comment]
New one
```
11:05:43  Creating support/test/jdk/jtreg/native/lib/libTestNative.so from 1 file(s)
11:05:43  Creating support/test/jdk/jtreg/native/bin/sanity_SimpleNativeLauncher from 1 file(s)
11:05:44  Updating images/sec-bin.zip
11:11:08  process apparently never started in /home/jenkins/workspace/Build_JDK11_aarch64_linux_xl_Personal@tmp/durable-4a5fc512
11:11:08  (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
```

**Comment by jdekonin** [comment]
This isn't a failure in the build pipeline code.  We are catching a failure in the `make all` step [1].  Comparing to a successful job [2], I'd say its failing at the stage of using the buildjvm (minimal jvm built from these sources) to compile either support classes or jmods.  

I tried downloading the diagnostic files but there wasn't anything present, so no help there.

1. https://github.com/eclipse/openj9/blob/097d2eca033634b70c36f522115a3b43f110d771/buildenv/jenkins/common/build.groovy#L266
2. https://ci.eclipse.org/openj9/job/Build_JDK11_aarch64_linux_xl_Personal/31/consoleFull

**Comment by AdamBrousseau** [comment]
@0xdaryl is this still an issue?

**Comment by 0xdaryl** [comment]
Resolved.
