### ISSUE TITLE
Implement `TerminatingThreadLocal` as required by JTReg Test Failure: jdk/internal/misc/TerminatingThreadLocal/TestTerminatingThreadLocal.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#7167]
Failure link
------------
Rebuild Link: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=jdk/internal/misc/TerminatingThreadLocal/TestTerminatingThreadLocal.java&TARGET=jdk_custom_0
- test category: openjdk
- OS/architecture: all
- version: 11, 13
- JVM: openj9 only

Optional info
-------------
- intermittent failure: No
- regression or new test: Regression

Failure output (captured from console output)
---------------------------------------------
```
14:54:51  java.lang.AssertionError: Expected terminated values: [42] but got: []
14:54:51  	at TestTerminatingThreadLocal.ttlTest(TestTerminatingThreadLocal.java:86)
14:54:51  	at TestTerminatingThreadLocal.ttlTestSet(TestTerminatingThreadLocal.java:48)
14:54:51  	at TestTerminatingThreadLocal.main(TestTerminatingThreadLocal.java:41)
14:54:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:54:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
14:54:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:54:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
14:54:51  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
14:54:51  	at java.base/java.lang.Thread.run(Thread.java:831)
```

After further investigation, it would seem that this method
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/8bf2a8166185765e9c6ddbffb66d1adbee67fd16/test/jdk/jdk/internal/misc/TerminatingThreadLocal/TestTerminatingThreadLocal.java#L66 is not being called by any of the test cases, so `terminatedValues` remains empty and causes the test to fail.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1369

**Comment by DanHeidinga** [comment]
This looks to be the OpenJDK code for TerminatingThreadLocal which I'm not sure we implement (yet) in OpenJ9: https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/8bf2a8166185765e9c6ddbffb66d1adbee67fd16/src/java.base/share/classes/jdk/internal/misc/TerminatingThreadLocal.java

**Comment by adam-thorpe** [comment]
I will add this to the list of openj9 permanent excludes then.

**Comment by DanHeidinga** [comment]
Reopening as this is highlighting something we're missing which should have been implemented

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you take a look at this?  We may need some help from @andrew-m-leonard and co to describe what we should be doing to support TerminatingThreadLocal.  

Likely we're missing some processing of these?  / all? thread locals on Thread death

**Comment by JasonFengJ9** [comment]
Sure, will look into it.
