### ISSUE TITLE
JIT code cache MemoryPool MBean usage reported as 0 bytes via JMX

### ISSUE THREAD

**Issue by paulcheeseman** [eclipse/openj9#7171]
I'm still seeing the problem described in #5418, despite the fix that was applied to address that issue.

The following screenshot is from IBM Java 8.0.5.40 on Windows:

![JmxIssue](https://user-images.githubusercontent.com/32541517/65326761-1c771400-dbaa-11e9-90bc-34ef3b968c92.png)

**Comment by pshipton** [comment]
@LinHu2016

**Comment by pshipton** [comment]
@mpirvu

**Comment by mpirvu** [comment]
I have instrumented `updateNonHeapMemoryPoolSizes(J9JavaVM *vm, J9JavaLangManagementData *mgmt, BOOLEAN isGCEND)` and verified that
`mgmt->nonHeapMemoryPools[JIT_CODECACHE].postCollectionUsed`
and
`mgmt->nonHeapMemoryPools[JIT_CODECACHE].preCollectionUsed`
are correctly updated, yet jconsole shows a value of 0. My conclusion is that jconsole reads the value it prints from another source.
@LinHu2016 any clues?

**Comment by paulcheeseman** [comment]
Here's a testcase that doesn't involve jconsole:

```
import java.lang.management.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.nio.file.*;
import java.io.*;

public class JITJMXTest {
	public static void main(String[] args) {
		// Record the current time and trigger a javacore
		SimpleDateFormat javacoreDateFormat = new SimpleDateFormat("yyyyMMdd.HHmmss");
		String javacoreTimestamp = javacoreDateFormat.format(new Date());
		com.ibm.jvm.Dump.JavaDump();
		
		// Find the javacore file
		File[] matches = new File(".").listFiles(new FilenameFilter() {
			public boolean accept(File dir, String name) {
				return name.startsWith("javacore") && name.contains(javacoreTimestamp) && name.endsWith(".txt");
			}
		});
		
		if (matches.length != 1) {
			System.out.println("Error: Could not locate javacore");
			System.exit(1);
		}
		
		File javacoreFile = matches[0];
		
		System.out.println();
		System.out.println("================================================================================");
		System.out.println("Jit code cache data from " + javacoreFile.getName());
		System.out.println("================================================================================");
		
		// Print the lines describing the code cache
		try (BufferedReader reader = new BufferedReader(new FileReader(javacoreFile))) {
			String line = null;
			boolean printLine = false;
			while ((line = reader.readLine()) != null) {
				if (line.equals("1STSEGTYPE     JIT Code Cache")) {
					printLine = true;
				}
			
				if (printLine) {
					System.out.println(line);
				}
			
				if (line.contains("1STSEGLIMIT    Allocation limit:")) {
					printLine = false;
				}			
			}
		} catch (Exception e) {
			System.out.println("Error: Could not read from javacore file: " + e);
		}
		
		javacoreFile.delete();
		
		System.out.println();
		System.out.println("================================================================================");
		System.out.println("JIT code cache data from MXBean");
		System.out.println("================================================================================");
				
		// Print the code cache info from the MXBean
		for (MemoryPoolMXBean memoryPoolMXBean : ManagementFactory.getMemoryPoolMXBeans()) {
			String name = memoryPoolMXBean.getName();
			if (name.equals("JIT code cache")) {
				System.out.println(memoryPoolMXBean.getUsage());
			}
		}		
	}
}
```

It produces output like this:

```
c:\>java JITJMXTest
JVMDUMP034I User requested Java dump using 'c:\javacore.20190924.130355.20944.0001.txt' through com.ibm.jvm.Dump.JavaDump
JVMDUMP010I Java dump written to c:\javacore.20190924.130355.20944.0001.txt

================================================================================
Jit code cache data from javacore.20190924.130355.20944.0001.txt
================================================================================
1STSEGTYPE     JIT Code Cache
NULL           segment            start              alloc              end                type       size
1STSEGMENT     0x000000000F657008 0x000000004E600000 0x000000004E606F80 0x000000005E600000 0x00000068 0x0000000010000000
NULL
1STSEGTOTAL    Total memory:                   268435456 (0x0000000010000000)
1STSEGINUSE    Total memory in use:                28544 (0x0000000000006F80)
1STSEGFREE     Total memory free:              268406912 (0x000000000FFF9080)
1STSEGLIMIT    Allocation limit:               268435456 (0x0000000010000000)

================================================================================
JIT code cache data from MXBean
================================================================================
init = 268435456(262144K) used = 0(0K) committed = 268435456(262144K) max = 268435456(262144K)
```

Note the difference between `Total memory in use` in the javacore output and `used` in the MXBean output.

**Comment by LinHu2016** [comment]
the issue has been identified, JCL native has different code to retrieve nonHeap memory size for function memoryPoolMXBean.getUsage()/getPeakUsage() (initialize, GCStart and GCEnd use another code, which has been updated in previous PR(https://github.com/eclipse/openj9/pull/5496)), this issue would affect memoryPoolMXBean.getUsage()/getPeakUsage() on all of platform, it would not affect GarbageCollectionNotificationInfo and GarbageCollectorMXBean.getLastGcInfo(). I am working on the fix.

**Comment by LinHu2016** [comment]
@mpirvu I am trying to update JCL native to use the new code cache call back to retrieve code cache used size, just like we did in JCL initialize, GCStart, GCEnd and javadump), but new update need to invoke the callback from java mutator runtime( unlike before it is called from STW), I experience the crash during calling the callback in mutator runtime, looks the invalid segment is still in the segment list, any suggestion for the case? Thanks

**Comment by mpirvu** [comment]
@LinHu2016 You mention "invalid segment". For 64-bit SDKs there should be a single Code Cache segment that is setup during JVM bootstrap. The segment should remain valid until the very end of the program. Does your crash happen during JVM bootstrap or shutdown?

**Comment by LinHu2016** [comment]
@mpirvu it would crush at getCodeCacheWarmAlloc module on all of platforms and anytime after receiving getUsage call, it makes me think either segment address or TR::CodeCache structure address, which is stored in the beginning of the segment, was wrong, but after crush the javadump outputs the correct informantion, I will try to debug it.

Unhandled exception
Type=Segmentation error vmState=0x00040000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=000000000F2A4ED0 Handler2=000000000F4CEC20 InaccessibleAddress=0000000000000040
RDI=0000000000000040 RSI=0000000000000000 RAX=0000000016D73020 RBX=0000000016C73020
RCX=00007FE59C013A20 RDX=0000000000000000 R8=000000000F493828 R9=0000000000000100
R10=0000000000000020 R11=0000000000000000 R12=00007FE5A0034A68 R13=00007FE59C042F30
R14=00007FE59C077220 R15=0000000000000040
RIP=000000000F6CB7B0 GS=0000 FS=0000 RSP=00007000034EA268
RFlags=0000000000010202 CS=002B RBP=00007000034EA2F0 ERR=0000004000000004
TRAPNO=000000040000000E CPU=0040000000040000 FAULTVADDR=0000000000000040
XMM0 000000000f3f9d08 (f: 255827200.000000, d: 1.263954e-315)
XMM1 000000001c5b2d80 (f: 475737472.000000, d: 2.350455e-315)
XMM2 000e1781000e1781 (f: 923521.000000, d: 1.959708e-308)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 bfba4e7300000000 (f: 0.000000, d: -1.027595e-01)
XMM6 000fffffffffffff (f: 4294967296.000000, d: 2.225074e-308)
XMM7 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
XMM8 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
XMM9 4f48d376dffed51f (f: 3758019840.000000, d: 8.772761e+73)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 ca62c1d6ca62c1d6 (f: 3395469824.000000, d: -2.193092e+50)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=/Users/linhu@ca.ibm.com/Downloads/j2sdk-image/jre/lib/compressedrefs/libj9jit29.dylib
Module_base_address=000000000F65C000 Symbol=getCodeCacheWarmAlloc
Symbol_address=000000000F6CB7B0
Target=2_90_20190924_43 (Mac OS X 10.13.6)
CPU=amd64 (8 logical CPUs) (0x400000000 RAM)
----------- Stack Backtrace -----------
---------------------------------------

**Comment by LinHu2016** [comment]
@mpirvu please ignore previous comments, it was my fault to pass the wrong segment.

**Comment by LinHu2016** [comment]
![Screen Shot 2019-09-26 at 4 41 38 PM](https://user-images.githubusercontent.com/18031118/65723853-3c607900-e07d-11e9-9a4b-58140b82d56c.png)
testing local build
