### ISSUE TITLE
JTReg Failure: java/lang/invoke/VarHandles/VarHandleTestReflection.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7172]
Failure link
------------

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/8bf2a8166185765e9c6ddbffb66d1adbee67fd16/test/jdk/java/lang/invoke/VarHandles/VarHandleTestReflection.java#L1 consistantly fails for JDK11-openj9 and JDK13-openj9
- test category openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows
```
13:45:13  openjdk version "11.0.5" 2019-10-15
13:45:13  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+7-201909161809)
13:45:13  Eclipse OpenJ9 VM AdoptOpenJDK (build master-c4d0e5132, JRE 11 Linux amd64-64-Bit Compressed References 20190916_334 (JIT enabled, AOT enabled)
13:45:13  OpenJ9   - c4d0e5132
13:45:13  OMR      - 265676ac
13:45:13  JCL      - 2d77cb2d93 based on jdk-11.0.5+7)
```

Optional info
-------------
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Error output is cut down as all failures are `NullPointerExceptions`
- Rerun job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=java/lang/invoke/VarHandles/VarHandleTestReflection.java&TARGET=jdk_custom_0

Failure output (captured from console output)
---------------------------------------------
```
13:47:50  test VarHandleTestReflection.reflectAsFromFindVirtual(GET): failure
13:47:50  java.lang.NullPointerException
13:47:50  	at java.base/java.lang.invoke.MethodHandles$Lookup.checkSecurity(MethodHandles.java:1416)
13:47:50  	at java.base/java.lang.invoke.MethodHandles$Lookup.revealDirect(MethodHandles.java:1346)
13:47:50  	at VarHandleTestReflection.reflectAsFromFindVirtual(VarHandleTestReflection.java:110)
13:47:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:47:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:47:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:47:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:47:50  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
13:47:50  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
13:47:50  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
13:47:50  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
13:47:50  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
13:47:50  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
13:47:50  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
13:47:50  	at org.testng.TestRunner.run(TestRunner.java:623)
13:47:50  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
13:47:50  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
13:47:50  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
13:47:50  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
13:47:50  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
13:47:50  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
13:47:50  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
13:47:50  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
13:47:50  	at org.testng.TestNG.run(TestNG.java:1018)
13:47:50  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
13:47:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:47:50  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:47:50  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:47:50  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:47:50  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
13:47:50  	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by mikezhang1234567890** [comment]
Taking a look at this.

**Comment by mikezhang1234567890** [comment]
Seems like it only throws an error when ran with the jtreg harness. Running the tests with TestNG or simply running the commands jtreg outputs throws no NullPointerException.

**Comment by M-Davies** [comment]
It should be default... It is when I run the test locally at least. That's odd it isn't for Jenkins however

**Comment by M-Davies** [comment]
By default, `agentvm` is enabled for Adopt's jenkins
https://github.com/AdoptOpenJDK/openjdk-tests/blob/4cd6de10de77bba2c8cbc1bd17f6bf2c93162be3/openjdk/openjdk.mk#L56

**Comment by mikezhang1234567890** [comment]
Sorry, I meant it defaults to `othervm` when neither `agentvm` nor `othervm` is specified, as detailed at https://openjdk.java.net/jtreg/command-help.html under Test Mode Options.

**Comment by mikezhang1234567890** [comment]
In both the tests that fail (`reflectAsFromFindVirtual` and `reflectAsFromVarHandleInvoker`) the referenceClass of the method handle created is null. 

When the tests are run with the `agentvm` option, there is a security manager, so we run into a NullPointerException in `MethodHandles.checkSecurity()` method since `referenceClass` is null. When we don't have the `agentvm` option, `System.getSecurityManager()` returns null and we don't run that branch of code.

**Comment by M-Davies** [comment]
@mikezhang1234567890 Is it a problem that branch of code doesn't get run? If it isn't, could we potentially specify in the test that it needs to be run with `-othervm` rather than the Adopt default of `-agentvm`?

**Comment by mikezhang1234567890** [comment]
@M-Davies It's a problem with our MethodHandle code. Will have a fix soon hopefully.
