### ISSUE TITLE
Special system testing is failing to download from artifactory

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7179]
When running a dedicated special system test job on the weekend, linux, linuxxl and mac get errors downloading from artifactory. This seems to consistently happen, as it happened on past weekends as well.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Special-System-JDK13/2/
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Special-System-JDK11/4/

**Comment by pshipton** [comment]
@llxia @smlambert @jdekonin @AdamBrousseau

**Comment by AdamBrousseau** [comment]
I wonder if the parallel tests overload Artifactory.
```
00:01:46.813  get jdk binary...
00:01:46.813  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz
00:04:57.188  curl error code: 56. Sleep 300 secs, then retry 1...
00:09:57.477  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz
00:09:57.477  curl error code: 23. Sleep 300 secs, then retry 2...
00:14:56.330  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz
00:14:56.330  curl error code: 23. Sleep 300 secs, then retry 3...
00:19:59.737  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz
00:19:59.737  curl error code: 23. Sleep 300 secs, then retry 4...
00:25:03.394  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz
00:25:03.394  curl error code: 23. Sleep 300 secs, then retry 5...
00:29:53.022  curl -OLJks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz
00:29:53.022  curl error code: 23
00:29:53.022  Failed to retrieve https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz, exiting. This is what we received of the file and MD5 sum:
00:29:53.022  ls: cannot access 'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz': No such file or directory
00:29:53.022  md5sum: 'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_xl_Personal/136/OpenJ9-JDK11-x86-64_linux_xl-20190922-083539.tar.gz': No such file or directory
```

**Comment by pshipton** [comment]
Could be. They seem to work fine when running on jdk8 as part of the nightly build, but I expect not all parallel jobs get to run at the same time due to lack of available machines.

**Comment by AdamBrousseau** [comment]
Curl error code 56
```
Failure in receiving network data. Receiving data over the network is a crucial part of most curl operations and when curl gets an error from the lowest networking layers that the receiving of data failed, this exit status gets returned. To pinpoint why this happens, some serious digging is usually required. Start with enabling verbose mode, do tracing and if possible check the network traffic with a tool like Wireshark or similar.
```
Curl error code 23
```
Write error. Curl could not write data to a local filesystem or similar. curl receives data chunk by chunk from the network and it stores it like at (or writes it to stdout), one piece at a time. If that write action gets an error, this is the exit status.
```
I'll look at the machine(s) to see if there is anything obvious about space or permissions.

**Comment by AdamBrousseau** [comment]
Saw another build had code 18 instead of 56 on the first fail
>Partial file. Only a part of the file was transferred. When the transfer is considered complete, curl will verify that it actually received the same amount of data that it was told before-hand that it was going to get. If the two numbers do not match, this is the error code. It could mean that curl got fewer bytes than advertised or that it got more. curl itself cannot know which number that is wrong or which is correct. If any.

**Comment by llxia** [comment]
I do not think parallel tests overload Artifactory. I haven't seen this issue occur internally. I suspect this is due to the limited bandwidth with our network (i.e., UNB). When all parallel jobs start downloading at the same time, we do not have enough bandwidth to handle them.

I can tweak the script to delay starting each child build in parallel. For example,

```
Waiting 0 seconds before starting parallel build daaLoadTest
[Pipeline] sleep
No need to sleep any longer
[Pipeline] echo
Waiting 60 seconds before starting parallel build lambdaLoadTest
[Pipeline] sleep
Sleeping for 1 min 0 sec
[Pipeline] echo
Waiting 120 seconds before starting parallel build mathLoadTest
[Pipeline] sleep
Sleeping for 2 min 0 sec
[Pipeline] echo
Waiting 180 seconds before starting parallel build mauveLoadTest
[Pipeline] sleep
Sleeping for 3 min 0 sec
[Pipeline] echo
Waiting 240 seconds before starting parallel build otherLoadTest
...
```

This tweak only deduces the risk of overload happening within parallel jobs. It does not guarantee overload will not happen. Maybe we should think about how to properly fix this issue.

**Comment by pshipton** [comment]
Not a fan of adding a delay like this. I think the delay would have to be longer, such as 5min between children, since the artifactory download takes a long time. The delay doesn't account for multiple platforms starting parallel testing at the same time, such as linux and linuxxl and perhaps osx. It will unnecessary slow down platforms that don't have a bandwidth issue.

The only thing that comes to mind is to have machines at UNB download via a server at UNB that serializes the requests to the artifactory server.

**Comment by AdamBrousseau** [comment]
related #2637 #8425
