### ISSUE TITLE
JTReg Failure: java/lang/invoke/VarargsArrayTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7183]
Failure link
------------

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/502ab02dbda2e8b021cffedc3f52e25246cdeec1/test/jdk/java/lang/invoke/VarargsArrayTest.java#L1 is failing for JDK8-openj9, JDK11-openj9 and JDK13-openj9 (hotspot unaffected).
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac

Optional info
-------------

- intermittent failure (no): 
- New test:  
- Part of the excluded AdoptOpenJDK/openjdk-tests#585

Failure output (captured from console output)
---------------------------------------------
Output is from JDK11 (the error is message is nearly the exact same for JDK8 and 13.
```
13:56:18  STDOUT:
13:56:18  STDERR:
13:56:18  java.lang.InternalError: Compile stub invoked! Apart from deliberate reflective access, this should not happen. Please report this to the project so it can be addressed
13:56:18  	at java.base/java.lang.invoke.OpenJDKCompileStub.OpenJDKCompileStubThrowError(OpenJDKCompileStub.java:38)
13:56:18  	at java.base/java.lang.invoke.MethodHandle.intrinsicName(MethodHandle.java:1394)
13:56:18  	at java.base/java.lang.invoke.MethodHandleImpl.makeIntrinsic(MethodHandleImpl.java:1444)
13:56:18  	at java.base/java.lang.invoke.MethodHandleImpl.varargsArray(MethodHandleImpl.java:1582)
13:56:18  	at java.base/java.lang.invoke.MethodHandleHelper.varargsArray(MethodHandleHelper.java:44)
13:56:18  	at VarargsArrayTest.testVarargsArray(VarargsArrayTest.java:70)
13:56:18  	at VarargsArrayTest.test(VarargsArrayTest.java:61)
13:56:18  	at VarargsArrayTest$$Lambda$32.0000000000000000.run(Unknown Source)
13:56:18  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor$$Lambda$33.0000000000000000.run(Unknown Source)
13:56:18  	at jdk.testlibrary.Utils.filterException(Utils.java:285)
13:56:18  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
13:56:18  	at VarargsArrayTest.main(VarargsArrayTest.java:57)
13:56:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:56:18  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:56:18  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:56:18  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13:56:18  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:56:18  	at java.base/java.lang.Thread.run(Thread.java:831)
```
Rerun job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=java/lang/invoke/VarargsArrayTest.java&TARGET=jdk_custom_0

[openjdk_test_output.tar.gz](https://github.com/eclipse/openj9/files/3642207/openjdk_test_output.tar.gz)

**Comment by pshipton** [comment]
I think this test is using internals that don't apply to OpenJ9.
@DanHeidinga

**Comment by DanHeidinga** [comment]
I agree.  The test grovels into the internals of the OpenJDK MethodHandle implementation which is why it's throwing a `java.lang.InternalError: Compile stub invoked!`
