### ISSUE TITLE
Inconsistent env var names for disabling inlining of isAssignableFrom

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/openj9#7194]
x86:

TR_DisableInliningOfIsAssignableFrom

(https://github.com/eclipse/openj9/blob/master/runtime/compiler/x/codegen/J9CodeGenerator.cpp#L399)

p, Z:

TR_disableInlineIsAssignableFrom

(https://github.com/eclipse/openj9/blob/master/runtime/compiler/z/codegen/J9TreeEvaluator.cpp#L8824 and in p the file is too long to give a link)

**Comment by fjeremic** [comment]
Any preference to which we should use?

**Comment by JamesKingdon** [comment]
Not really, but it would probably make sense to change the x86 version to match the other two.
