### ISSUE TITLE
Jenkins jobs can't run, waiting on worker

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7199]
Seems there is a bunch of OMR acceptance stuff sitting on worker-1 and worker-2, and all PR testing is queued up for over an hour `Waiting for next available executor on ‘worker’`.

All I see for the Pipeline-OMR-Acceptance jobs on the workers is 
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/1626/ which failed due to `Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun`.

Do I need to kill all the Pipeline-OMR-Acceptance jobs sitting on the workers?

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
I went ahead and killed them, things seem to be flowing again.

**Comment by AdamBrousseau** [comment]
Yea we have 6 executor slots across 2 worker machines. Sometimes things get funny and builds will continue to occupy an executor even though the build is failed. I used to occasionally notice and kill these. We could look at adding some kind of check for this in the cleanup job but it's another hack. We should look at opening/finding a Jenkins issue for this.
