### ISSUE TITLE
Remove _registerSaveDescription field from Instruction class

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7203]
The `_registerSaveDescription` field in `J9Instruction.hpp` is no longer used, and neither are its getters and setters.  Remove them.

There is an identical field in the parent OMRInstruction.hpp that is also no longer used (see issue eclipse/omr#4350).  Between these two issues, we can save 16 bytes per Instruction.

**Comment by 0xdaryl** [comment]
@AidanHa , would you mind handling this please?

**Comment by AidanHa** [comment]
Sure, I have some PRs' in works at the moment, but I can get this one done.
