### ISSUE TITLE
Eclipse 4.13 Crashing on startup with OpenJ9 JVM

### ISSUE THREAD

**Issue by TehAppKiller** [eclipse/openj9#7204]
Java -version output
--------------------

OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Windows 7 amd64-64-Bit 20190717_36 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)

Summary of problem
------------------

Hello,

I use OpenJ9 JVM (from AdoptJDK) on my x64 Win7 computer.

Eclipse 4.12 was working with it
but it does not work anymore on Eclipse 4.13.

I already reported a bug on Eclipse bugs tracker:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551091
yet, as it may be related to openJ9, here is a report too.

I tried:
- jdk8u202-b08 : Crash
- jdk-11.0.3+7 : Crash
- jdk-11.0.4+11 : Crash

while it works with hotspot (jdk-11.0.4+11 provided by AdoptJDK).

Thanks.

Diagnostic files
----------------

Core dump: https://we.tl/t-E1wB8S5UoQ

[eclipse_openJ9_crash.zip](https://github.com/eclipse/openj9/files/3647334/eclipse_openJ9_crash.zip)

**Comment by pshipton** [comment]
javacore indicates a gpf in the swt library. Pls try running with `-Xcheck:jni` to see if that catches the problem.

**Comment by TehAppKiller** [comment]
> 
> 
> javacore indicates a gpf in the swt library. Pls try running with `-Xcheck:jni` to see if that catches the problem.

Arg added it to eclipse.ini
Same crash ; Not sure what I should send you back...
New jit dump is quite smaller:
[jitdump.20190924.160139.5444.0004.dmp.zip](https://github.com/eclipse/openj9/files/3647595/jitdump.20190924.160139.5444.0004.dmp.zip)

**Comment by DanHeidinga** [comment]
Is there any output on stderr?  `-Xcheck:jni` writes its warnings / output to the stderr stream

**Comment by TehAppKiller** [comment]
> 
> 
> Is there any output on stderr? `-Xcheck:jni` writes its warnings / output to the stderr stream

Eclipse crashes so I cannot read console.
When launching Eclipse from cmd line, nothing output in this console.
Or maybe is there another way ?

**Comment by TehAppKiller** [comment]
Hi,

The final problem (eclipse crash on startup) seems to have been fixed by Eclipse team (see Eclipse bug tracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=551091 ).

Now, whether the error fixed should crash or not Eclipse (hotspot does not crash) is not up to me to decide.

Thanks for your help.

**Comment by DanHeidinga** [comment]
Closing as the bug has been fixed by the IDE
