### ISSUE TITLE
Eliminate `VM_getClassNameSignatureFromMethod` messages

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#7217]
`VM_getClassNameSignatureFromMethod` appear in the implementation of `sampleSignature(TR_OpaqueMethodBlock * aMethod, char *buf, int32_t bufLen, TR_Memory *trMemory_unused)`
They could be eliminated by using the cache on j9methods and j9classes we keep at the JITServer

**Comment by dmitry-ten** [comment]
I'll work on this.

**Comment by dmitry-ten** [comment]
@mpirvu this can be closed, since https://github.com/eclipse/openj9/pull/11328 addressed this issue.

**Comment by mpirvu** [comment]
Solved by #11328, so closing
