### ISSUE TITLE
do you use k8s deploy jenkins ?

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#7218]
Hi,

i deploy jenkins use docker , not use k8s ,   jenkins memory always up,

about 10GB,
do you use jenkins-slave ?

do you use k8s deploy jenkins ?

**Comment by pshipton** [comment]
@15838028035 this project is about OpenJ9. The Eclipse foundation supplies Jenkins to the project, and I'm not sure how it is deployed. There is this recent blog about running Jenkins with OpenJ9 if that is helpful. https://blog.openj9.org/2019/09/17/comparing-jenkins-startup-in-docker/
