### ISSUE TITLE
Build_JDKnext_x86-64_windows No rule to make target 'java.desktop<cr>'

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7248]
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_windows_OpenJDK/63
```
08:31:04  + make all
08:31:30  Building target 'all' in configuration 'windows-x86_64-server-release'
08:31:30  Compiling 8 files for BUILD_TOOLS_LANGTOOLS
08:31:30  make[2]: *** No rule to make target 'java.desktop
', needed by 'openj9.dtfj'.  Stop.
```

**Comment by pshipton** [comment]
@andrew-m-leonard 
I'll restart it just in case.
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_windows_OpenJDK/64/

OpenJ9: 896a36e
OMR: c30a477
OpenJDKnext: 4127695 - openj9-openjdk-jdk

previous build
OpenJ9: 9514041
OMR: 7e9584e
OpenJDKnext: da32c68 - openj9-openjdk-jdk

https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/da32c68...4127695

**Comment by pshipton** [comment]
The restarted job failed the same way.

**Comment by andrew-m-leonard** [comment]
The auto-merge conflicts for jdkNext were resolved yesterday, hence quite a lot of backlog'd changes would have been pulled in. It's at jdk-14+16 now.

**Comment by pshipton** [comment]
@andrew-m-leonard ok, but Windows doesn't build any more, so we can't promote openj9-staging. It's not clear from your comment, are you looking at the problem?

**Comment by andrew-m-leonard** [comment]
@pshipton Adam Thorpe in my team is looking at this...

**Comment by adam-thorpe** [comment]
These test builds are using JDK12 to build next (14), which is causing at least this issue?

**Comment by adam-thorpe** [comment]
Looking at other acceptance jobs, they are all using JDK12. My understanding is that you cannot build JDK 14 with anything below 13

**Comment by pshipton** [comment]
The java.desktop problem occurred first, while jdk12 was still permitted as a bootjdk for jdk14. Then the bootjdk requirements were updated to require jdk13. We'll get the machines and builds updated to use jdk13, and see if this problem still occurs.

**Comment by adam-thorpe** [comment]
Okay, because I've been setting up a windows environment and I am able to get to a further step in the build process locally, so I am not sure what the issue is just yet.

**Comment by pshipton** [comment]
@adam-thorpe we've gotten jdk13 installed and updated the jdk14 builds to use it. The `java.desktop<cr>` problem still occurs.
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_windows_OpenJDK/70

**Comment by adam-thorpe** [comment]
Thats odd but okay I'll look into it and see if I can spot the difference between this and my local machine

**Comment by adam-thorpe** [comment]
I can't seem to recreate the issue locally, and cannot test on another jenkins instance since they do not have boot JDK 13 so cannot determine if this is an isolated problem or not. One difference I did note was that eclipse is using cygwin v2.10.0, whereas the latest version is 3.0.7. Since cygwin does not support old versions, I cannot install this locally to test whether something in the older version is causing a problem.

**Comment by adam-thorpe** [comment]
Testing on hyc runtimes jenkins with the first failing SHAs does not replicate the issue: https://hyc-runtimes-jenkins.swg-devops.com/job/Build_JDKnext_x86-64_windows_Personal/17/console (using cygwin 2.11.0).

**Comment by andrew-m-leonard** [comment]
This commit caused the issue: https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/fcbc07f47ad02b560345459bafe0e071ecc980b3
I'm suspecting a combination of this and possibly the significance of the <cr> in the dependency, so 'java.desktop' is defined, but not 'java.desktop<cr>' and I would hazzard a guess on non-windows platforms the <cr> is ignored so they match...?

**Comment by andrew-m-leonard** [comment]
The generated module-deps.gmk for openj9 modules has <cr>'s in it:
```
22:17:22  DEPS_openj9.dtfj := java.base java.desktop
 java.logging
 java.xml
 openj9.traceformat
22:17:22  TRANSITIVE_MODULES_openj9.dtfj := java.base java.desktop
 java.logging
22:17:22  DEPS_openj9.dtfjview := java.base openj9.dtfj
 java.logging
22:17:22  TRANSITIVE_MODULES_openj9.dtfjview := java.base
22:17:22  DEPS_openj9.gpu := java.base java.base
 openj9.cuda
```

**Comment by pshipton** [comment]
There is a new blocking problem now, #7500

**Comment by pshipton** [comment]
The blocker is resolved.

**Comment by pshipton** [comment]
Fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/145
