### ISSUE TITLE
DaaLoadTest or SharedClasses crash vmState=0x0002000f

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7300]
First occurrence see https://github.com/eclipse/openj9/issues/7276#issuecomment-536573381 and the other comments in that issue.
DaaLoadTest_daa1_special_22

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/369
DaaLoadTest_all_special_22
variation: Mode687
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:gencon -Xaggressive 
```
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x0002000f
DLT stderr Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFC8B85B457 ContextFlags=0010005f
DLT stderr Handler1=00007FFC8BAAC6C0 Handler2=00007FFC8C03CB00 InaccessibleReadAddress=0000000084723318
DLT stderr RDI=000000000DF73AC0 RSI=0000000084723300 RAX=0000000000BB73E0 RBX=0000000000000000
DLT stderr RCX=0000000001620130 RDX=000000000EE77AD8 R8=0000000023DDEA68 R9=0000000023DDEA88
DLT stderr R10=0000000023DDEFF0 R11=00000000072DC1E0 R12=0000000000000000 R13=0000000000000000
DLT stderr R14=00000000016200A0 R15=0000000001ADAE50
DLT stderr RIP=00007FFC8B85B457 RSP=0000000023DDE9B0 RBP=0000000000000000 GS=002B
DLT stderr FS=0053 ES=002B DS=002B
DLT stderr XMM0 43e0000000000000 (f: 0.000000, d: 9.223372e+018)
DLT stderr XMM1 bf2e302be03ce543 (f: 3762087168.000000, d: -2.303175e-004)
DLT stderr XMM2 3f2e5d24f64f6339 (f: 4132397824.000000, d: 2.316578e-004)
DLT stderr XMM3 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-001)
DLT stderr XMM4 402fe28022000000 (f: 570425344.000000, d: 1.594238e+001)
DLT stderr XMM5 3f2e5cb39384c221 (f: 2474951168.000000, d: 2.316446e-004)
DLT stderr XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
DLT stderr Module=C:\Users\jenkins\workspace\Test_openjdk8_j9_special.system_x86-64_windows_Nightly\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9gc29.dll
DLT stderr Module_base_address=00007FFC8B6A0000 Offset_in_DLL=00000000001bb457
DLT stderr Target=2_90_20190930_162 (Windows Server 2012 R2 6.3 build 9600)
DLT stderr CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
```

https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/daaLoadTest&JenkinsFile=openjdk_x86-64_windows&TARGET=DaaLoadTest_all_special_22&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_windows_Nightly/162/OpenJ9-JDK8-x86-64_windows-20191001-031444.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_windows_Nightly/162/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by dmitripivkine** [comment]
I will double check what it is

**Comment by dmitripivkine** [comment]
yes, it is the same failure we observed before:
```
Checking THREAD STACKS...
  <gc check (1): from debugger: THREAD STACKS: slot 1ac8800(1adae50) -> f80555c8: class pointer not in a class segment>
  <gc check (2): from debugger: THREAD STACKS: slot 1ad3c00(1afb910) -> f8096f40: class pointer not in a class segment>

<1ac8800> For pinning array U8(0x01) num internal pointer stack slots U8(0x00)
<1ac8800> Before object slot walk &address : 0x0000000001ADAE50 address : 0x00000000F80555C8 bp 0x0000000001ADAEC8 offset of first internal ptr I16(0xFF88)
<1ac8800> After object slot walk for pinning array with &address : 0x0000000001ADAE50 old address 0x00000000F80555C8 new address 0x00000000F80555C8 displacement IDATA(0x0000000000000000)
<1ac8800> For pinning array U8(0x00) num internal pointer stack slots U8(0x00)
<1ac8800> 		I-Slot: : t17[0x0000000001ADAE38] = 0x00000000FF2BE218
<1ac8800> 		I-Slot: : t16[0x0000000001ADAE40] = 0x00000000FF2BE278
<1ac8800> 		I-Slot: : t15[0x0000000001ADAE48] = 0x0000000059B6FBE6
<1ac8800> 		I-Slot: : t14[0x0000000001ADAE50] = 0x00000000F80555C8
```

**Comment by dmitripivkine** [comment]
@r30shah would you please confirm this is the problem you are looking to?

**Comment by r30shah** [comment]
Yes, @dmitripivkine I think this is the same issue I am looking into right now, Internally I can reproduce on Linux x86 1/100 and working in getting the tracelog of the bad method which is `{com/ibm/dataaccess/PackedDecimal.packedDecimalBinaryOp(I[BII[BII[BIIZ)V}{very-hot}` .

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_xl_Nightly/163
DaaLoadTest_daa1_0
JVM_OPTIONS: -Xnocompressedrefs

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_mac_Nightly/212
DaaLoadTest_all_special_22
variation: Mode687
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:gencon -Xaggressive

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/165
SharedClasses.SCM01.MultiThreadMultiCL_0
```
MTM2 stderr Type=Segmentation error vmState=0x0002000f
MTM2 stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
MTM2 stderr Handler1=00007F23364FAFB0 Handler2=00007F2335DF6B50 InaccessibleAddress=000000000000001A
MTM2 stderr RDI=00007F233003BE80 RSI=00007F22B80056B8 RAX=00007F2330013F58 RBX=0000000000000000
MTM2 stderr RCX=00007F22F812F1F8 RDX=00007F22F812F230 R8=00007F22F812F200 R9=00007F22F812F208
MTM2 stderr R10=00007F22F2823ED2 R11=00007F233003BDF0 R12=00007F22F812F230 R13=00007F22F812F1F8
MTM2 stderr R14=00007F233003BDF0 R15=00007F232949D050
MTM2 stderr RIP=00007F23344A57A7 GS=0000 FS=0000 RSP=00007F22F812F140
MTM2 stderr EFlags=0000000000010246 CS=0033 RBP=00007F2330077900 ERR=0000000000000004
MTM2 stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=000000000000001A
MTM2 stderr xmm0 00007f233475fac0 (f: 880147136.000000, d: 6.906503e-310)
MTM2 stderr xmm1 0000000700000007 (f: 7.000000, d: 1.485397e-313)
MTM2 stderr xmm2 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
MTM2 stderr xmm3 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
MTM2 stderr xmm4 3d6357df270cc516 (f: 655148288.000000, d: 5.497682e-13)
MTM2 stderr xmm5 3feb400000000000 (f: 0.000000, d: 8.515625e-01)
MTM2 stderr xmm6 3ff2c9fb4d812ca0 (f: 1300311168.000000, d: 1.174312e+00)
MTM2 stderr xmm7 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
MTM2 stderr xmm8 401b1549d29f2855 (f: 3533645824.000000, d: 6.770789e+00)
MTM2 stderr xmm9 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
MTM2 stderr xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM2 stderr xmm11 3d635816bc5ca07e (f: 3160186880.000000, d: 5.497923e-13)
MTM2 stderr xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM2 stderr xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MTM2 stderr xmm14 401bb9d3beb8c600 (f: 3199780352.000000, d: 6.931472e+00)
MTM2 stderr xmm15 0000000046b73e38 (f: 1186414080.000000, d: 5.861665e-315)
MTM2 stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdkbinary/j2sdk-image/jre/lib/amd64/default/libj9gc29.so
MTM2 stderr Module_base_address=00007F2334293000
MTM2 stderr Target=2_90_20191006_167 (Linux 2.6.32-754.11.1.el6.x86_64)
MTM2 stderr CPU=amd64 (4 logical CPUs) (0x1ec001000 RAM)
MTM2 stderr ----------- Stack Backtrace -----------
MTM2 stderr (0x00007F23344A57A7 [libj9gc29.so+0x2127a7])
MTM2 stderr (0x00007F233442BAD3 [libj9gc29.so+0x198ad3])
MTM2 stderr (0x00007F233444085D [libj9gc29.so+0x1ad85d])
MTM2 stderr (0x00007F233499004F [libj9jit29.so+0x22904f])
MTM2 stderr (0x00007F2334FA4AAF [libj9jit29.so+0x83daaf])
MTM2 stderr (0x00007F2334FA4F1C [libj9jit29.so+0x83df1c])
MTM2 stderr (0x00007F2334FA5CCC [libj9jit29.so+0x83eccc])
MTM2 stderr (0x00007F233652A6BE [libj9vm29.so+0xcc6be])
MTM2 stderr (0x00007F23342D22A6 [libj9gc29.so+0x3f2a6])
MTM2 stderr (0x00007F23342C6C9D [libj9gc29.so+0x33c9d])
MTM2 stderr (0x00007F23342C59DF [libj9gc29.so+0x329df])
MTM2 stderr (0x00007F23342C84C2 [libj9gc29.so+0x354c2])
MTM2 stderr (0x00007F2334438F38 [libj9gc29.so+0x1a5f38])
MTM2 stderr (0x00007F23343C0CFB [libj9gc29.so+0x12dcfb])
MTM2 stderr (0x00007F23343C07F1 [libj9gc29.so+0x12d7f1])
MTM2 stderr (0x00007F2335DF78B3 [libj9prt29.so+0x1f8b3])
MTM2 stderr (0x00007F23343C037C [libj9gc29.so+0x12d37c])
MTM2 stderr (0x00007F2336251156 [libj9thr29.so+0xe156])
MTM2 stderr (0x0000003545A07AA1 [libpthread.so.0+0x7aa1])
MTM2 stderr clone+0x6d (0x00000035456E8C4D [libc.so.6+0xe8c4d])
```
https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&JenkinsFile=openjdk_x86-64_linux_xl&TARGET=SharedClasses.SCM01.MultiThreadMultiCL_0&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_xl_Nightly/167/OpenJ9-JDK8-x86-64_linux_xl-20191007-021944.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_xl_Nightly/167/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_xl_Nightly/161
SharedClasses.SCM23.MultiThreadMultiCL_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/170
SharedClasses.SCM01.MultiThreadMultiCL_0

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/171
SharedClasses.SCM01.MultiThreadMultiCL_0
```
MTM1 stderr 00007F2CF8287C00: Invalid class pointer in thread Thread-16843
MTM1 stderr 00007F2CF8287C00:	O-Slot=00007F2C800C6F68
MTM1 stderr 00007F2CF8287C00:	O-Slot value=00007F2CF5452D50
MTM1 stderr 00007F2CF8287C00:	PC=00007F2CC4F0A1EE
MTM1 stderr 00007F2CF8287C00:	framesWalked=2
MTM1 stderr 00007F2CF8287C00:	arg0EA=00007F2C800C6FB8
MTM1 stderr 00007F2CF8287C00:	walkSP=00007F2C800C6DA0
MTM1 stderr 00007F2CF8287C00:	literals=0000000000000000
MTM1 stderr 00007F2CF8287C00:	jitInfo=00007F2CBE7E0BB8
MTM1 stderr 00007F2CF8287C00:	method=00007F2CF812E080 (java/lang/ClassLoader.loadClassHelper(Ljava/lang/String;ZZ)Ljava/lang/Class;) (JIT)
MTM1 stderr 00007F2CF8287C00:	stack=00007F2C800C00A0-00007F2C800C71F0
MTM1 stderr 04:20:53.449 0x7f2cf8287c00    j9mm.479    *   ** ASSERTION FAILED ** at ../../gc_glue_java/ConcurrentMarkingDelegate.cpp:57: ((MM_StackSlotValidator(0, object, stackLocation, walkState).validate(data->env)))
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/423
DaaLoadTest_daa1_special_22
```
DLT stderr Corruption in Evacuate at 00000000FF37B068: calculated object size 13457753273411521540 larger then available 13062040, Forwarded Header at 00000000243AF0F8
DLT stderr 11:31:32.758 0x1ec8d00    j9mm.141    *   ** ASSERTION FAILED ** at Scavenger.cpp:1334: ((false))
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/177
SharedClasses.SCM23.MultiCL_0

**Comment by r30shah** [comment]
From the investigation internally found the root cause of the failure. 
Problem lies in the following piece of the code. 
https://github.com/eclipse/omr/blob/38f103bba7f41fd5e85ccedd9b7ac2f01f5cea53/compiler/il/OMRBlock.cpp#L1166-L1180
Basically function from the above code creates a symbol reference with correct flags on it. But it was missing one case. 
To highlight how these failed pasting a snippet from the log of a failing method here.
```
n1n BBStart block_x
n2n    GlRegDeps()
n3n       aRegLoad R1 (internal Pointer)
...
n4n aiadd
n3n    => aRegLoad R1
n5n    iconst <some constant>
...
SPLIT POINT
...
n6n SomeNode
n4n    => aiadd
```
In the above case, when `splitPostGRA` encounters the `n4n` which is itself creates an internal pointer and requires to be un-commoned  across split point, it calls the above function to generate symbol reference with appropriate flags which in this case a symRef which is internal pointer. Also as we are creating an internal pointer, it needs to know the corresponding pinning array slot. Which in above case should already be available with the symbol reference of node `n3n` so when generating a new symbol reference for `n4n` it just needs to set the pinning array symbol from getting it from symbol reference of `n3n`. What happens with above case is that, it sees `aRegLoad` as the first child which is not array reference, but does not see if it contains symbol reference which is internal pointer and ends up creating a new pinning array symbol by storing `n3n` to java stack marking it as pinning array slot, which actually stores internal pointer there marking that slot as holding valid object. So letter GC while walking fails encountering an invalid object in the marked object slot.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/180
```
Corruption in Evacuate at 00007FA130FCDBD0: calculated object size 140329751656384 larger then available 9264, Forwarded Header at 00007FA0F995E230
04:20:14.966 0x7fa0c0003a00    j9mm.141    *   ** ASSERTION FAILED ** at Scavenger.cpp:1334: ((false))
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/182
SharedClasses.SCM01.MultiThreadMultiCL_0
```
MTM2 stderr Corruption in Evacuate at 00007F133781E090: calculated object size 139719983321272 larger then available 401264, Forwarded Header at 00007F12D3FFC230
MTM2 stderr 04:32:46.917 0x7f12c8003a00    j9mm.141    *   ** ASSERTION FAILED ** at Scavenger.cpp:1371: ((false))
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_xl_Nightly/177
SharedClasses.SCM23.MultiThreadMultiCL_0
Type=Segmentation error vmState=0x0002000f

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/187
SharedClasses.SCM01.SingleCL_0
Type=Segmentation error vmState=0x0002000f

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/187
SharedClasses.SCM01.SingleCL_0
Type=Segmentation error vmState=0x0002000f

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_x86-64_linux_xl_Nightly/80
SharedClasses.SCM23.MultiThreadMultiCL_0
Type=Segmentation error vmState=0x0002000f

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/192
SharedClasses.SCM01.MultiThreadMultiCL_0
Type=Segmentation error vmState=0x0002000f

**Comment by r30shah** [comment]
I have opened up PR to address the segmentation faults in GC seen on x86 due to JProfiling. 
https://github.com/eclipse/omr/pull/4535

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/194
SharedClasses.SCM23.MultiCL_0
```
MCL3 stderr Corruption in Evacuate at 00007FD46F02EE90: calculated object size 140549836537840 larger then available 4464, Forwarded Header at 00007FD43D65B2D0
MCL3 stderr 05:14:47.160 0x7fd3f8003a00    j9mm.141    *   ** ASSERTION FAILED ** at Scavenger.cpp:1334: ((false))
```

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_xl_Nightly/191
SharedClasses.SCM23.MultiThreadMultiCL_0
Type=Segmentation error vmState=0x0002000f

**Comment by fjeremic** [comment]
@r30shah I would imagine this one is fixed via the JProfiling fixes right?

**Comment by r30shah** [comment]
Yeah this one should be fixed by https://github.com/eclipse/omr/commit/7eb746e4983a5bc9b6ca54dc1307b036c345910d

**Comment by pshipton** [comment]
Closing, we can reopen if it's seen again.
