### ISSUE TITLE
Deprecate trailingZerosQuadWordAtATime

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#7318]
This API was implemented as a prototype to the Data Access Accelerator (DAA) library however the corresponding Java code was never delivered I believe (we should check this). We currently don't envision additions to the DAA library and as such the remanence of this prototype can be removed.

We should also take this opportunity to remove any such related APIs within DAA for which the Java implementations do not exist.

**Comment by VermaSh** [comment]
Found two additional APIs within DAA for which the Java implementations do not exist:
- `trailingZerosByteAtATime`
- `trailingZeros`
