### ISSUE TITLE
Determine whether Unsafe.defineAnonymousClasses should re-transform/redefine-able

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#7354]
Classes loaded by `Unsafe.defineAnonymousClasses` are not presented to the ClassFileLoadHook.  We need to determine if they should accessible to JVMTI at all - ie: thru retransformation / redefinition.

**Comment by pshipton** [comment]
@DanHeidinga is there a particular target you want for this? I'll move it to the next milestone for now, and if deferred again then into the backlog.

**Comment by DanHeidinga** [comment]
Basic idea: create a Java agent that stores the Instrumentation instance where the Main program can get it.  In the Main program, get Unsafe and use `defineAnonymousClass` to create a VM anon class.

Then test whether:
* `Instrumentation.getAllLoadedClasses` includes the VM anon class
* `Instrumentation.isModifiableClass` returns true or false for the VM anon class
* `Instrumentation.retransformClasses` throws or successfully changes the class.  Often easiest to test by redefining a method that returns a constant integer to it returns a new value.
* `Instrumentation.redefineClasses` throws or successfully changes the class.  Very similar to `retransformClasses` except no Transformer is required.

Description for how to write an agent https://www.baeldung.com/java-instrumentation

Run this test on JDK8, JDK11, JDK14, and JDK15 to compare the results.  It may be necessary to switch from `sun.misc.Unsafe` to `jdk.internal.misc.Unsafe` for Java 11+.

**Comment by DanHeidinga** [comment]
We'll want to test both J9 and the RI to ensure we have consistent behaviour in each release

**Comment by mikezhang1234567890** [comment]
I can take a look at this.

**Comment by mikezhang1234567890** [comment]
In Java 11, 14, and 15, an anonymous class is in the set returned by `getAllLoadedClasses` for both OpenJ9 and Hotspot, and it is non modifiable.

Also in OpenJ9 Java 11+, there is an issue with access when trying to get reflective access to the dummy class for `Method.invoke` resulting in:
```
Exception in thread "main" java.lang.IllegalAccessException: class TestAnon cannot access class DummyClass/0000000000000000 (in module java.base) because module java.base does not export  to unnamed module @d804bccf
```

In Java 8, the anonymous class is modifiable, and retransformation and redefinition works as expected (I changed the return value for a function returning an integer) on Hotspot. On OpenJ9, retransformation did not work, and the `transform` method  did not seem to be called at all.

I'm looking further into these two issues so that the OpenJ9 behaviour can be brought in line with the RI behaviour.

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 What's left here?  I'd like to get this closed out for the Aug 9 code split and the 0.22.0 release

**Comment by mikezhang1234567890** [comment]
>does not export to unnamed module implies there's a package name that should be listed there. Are we not handling the unnamed package correctly?

OpenJ9 isn't assigning the package of the host class to the anonymous class, while Hotspot is. Working on adding the package to the anonymous class name if the class loader for the host class is the system class loader.

**Comment by DanHeidinga** [comment]
@mikezhang1234567890 Any update on this?  We're fast approaching the new code split date of Aug 16

**Comment by pshipton** [comment]
@DanHeidinga @mikezhang1234567890 with the merges above, can this be closed?

**Comment by DanHeidinga** [comment]
not that I'm aware of.  @mikezhang1234567890 ?

**Comment by mikezhang1234567890** [comment]
Nothing else I'm aware of either.
