### ISSUE TITLE
openjdk13_j9_extended.functional FAILED: testLoadingClasses :  Child exited with non-zero stats expected:<0> but was:<1>

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7360]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_windows_Nightly/58/consoleFull

https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_xl_Nightly/57/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
06:35:49  Exception in thread "Thread-27" java.lang.AssertionError: TEST_STATUS=TEST_FAILED : org.openj9.test.classRelationshipVerifier.TestClassRelationshipVerifier
06:35:49  	at org.testng.Assert.fail(Assert.java:96)
06:35:49  	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile$StreamDumper.run(TestLoadingClassesFromJarfile.java:251)
06:35:49  FAILED: testLoadingClasses
06:35:49  java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
06:35:49  	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
06:35:49  	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
06:35:49  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
06:35:49  	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
06:35:49  	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:203)
06:35:49  	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:115)
06:35:49  	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:80)
06:35:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:35:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:35:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:35:49  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
06:35:49  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
06:35:49  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
06:35:49  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
06:35:49  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
06:35:49  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
06:35:49  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
06:35:49  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
06:35:49  	at org.testng.TestRunner.run(TestRunner.java:505)
06:35:49  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
06:35:49  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
06:35:49  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
06:35:49  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
06:35:49  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
06:35:49  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
06:35:49  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
06:35:49  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
06:35:49  	at org.testng.TestNG.runSuites(TestNG.java:1049)
06:35:49  	at org.testng.TestNG.run(TestNG.java:1017)
06:35:49  	at org.testng.TestNG.privateMain(TestNG.java:1354)
06:35:49  	at org.testng.TestNG.main(TestNG.java:1323)
06:35:49  
06:35:49  
06:35:49  ===============================================
06:35:49      testvmcheck
06:35:49      Tests run: 1, Failures: 1, Skips: 0
06:35:49  ===============================================
```

It appears similar with https://github.com/eclipse/openj9/issues/834.
Now it is across platforms.

**Comment by sharon-wang** [comment]
looking into this

**Comment by sharon-wang** [comment]
It looks like `testvmcheck` is failing on TestClassRelationshipVerifier because of some missing libraries. The test command for `testvmcheck` does not include the path to native test libs, nor does it include `asm-all.jar`, both of which are required for TestClassRelationshipVerifier.

Additionally, `-Xverify:all` is used by `testvmcheck`, however TestClassRelationshipVerifier uses `-XX:+ClassRelationshipVerifier`, which is incompatible with `-Xverify:all` (JVM initialization fails if both options are used).

Would it be best to exclude TestClassRelationshipVerifier from `testvmcheck`?

**Comment by pshipton** [comment]
> Would it be best to exclude TestClassRelationshipVerifier from testvmcheck?

I can't say I fully understand what is going on. testvmcheck is supposed to load all the classes on the sun.boot.class.path, and I'm not sure how TestClassRelationshipVerifier gets on the boot path. However, excluding TestClassRelationshipVerifier from the test is fine with me. 

I don't expect the `-Xverify:all` is related, the class only has to load.

**Comment by sharon-wang** [comment]
`org.openj9.test.*` classes are loaded in testvmcheck, but it appears that TestClassRelationshipVerifier is the only one failing. Will look a bit further into why this is occurring

**Comment by pshipton** [comment]
It's fine to just exclude this class. Is there anything special about TestClassRelationshipVerifier.java that might benefit from being tested with `-Xverify:all` or `-Xcheck:vm`? I think not.

**Comment by sharon-wang** [comment]
Opened https://github.com/eclipse/openj9/pull/7381 which excludes TestClassRelationshipVerifier from TestLoadingClassesFromJarfile (testvmcheck).
