### ISSUE TITLE
ppc64le Calendar.getInstance incorrect timezone

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7364]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/476
MauveMultiThreadLoadTest_special_26
variation: Mode612-OSRG
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation 
ub16p8j96
```
LT  00:01:28.208 - Test failed
LT    Failure num.  = 1
LT    Test number   = 3189
LT    Test details  = 'Mauve[gnu.testlet.java.util.Calendar.getInstance]'
LT    Suite number  = 0
LT    Thread number = 11
LT  >>> Captured test output >>>
LT  FAIL: gnu.testlet.java.util.Calendar.getInstance: () (number 0)
LT  got sun.util.calendar.ZoneInfo[id="America/Toronto",offset=-18000000,dstSavings=3600000,useDaylight=true,transitions=231,lastRule=java.util.SimpleTimeZone[id=America/Toronto,offset=-18000000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]] but expected java.util.SimpleTimeZone[id=GMT,offset=0,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,startTimeMode=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0,endTimeMode=0]
```

https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/mauveLoadTest&JenkinsFile=openjdk_ppc64le_linux&TARGET=MauveMultiThreadLoadTest_special_26&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Nightly/165/OpenJ9-JDK8-ppc64le_linux-20191006-022305.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Nightly/165/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by JasonFengJ9** [comment]
This is a legacy test, not much info from the result file, no stacktrace, no core file, etc.
Find `gnu/testlet/java/util/Calendar/getInstance.java` in an internal `mauve.jar` file. The test code snippet in question seems as following:
```
    Calendar c = Calendar.getInstance();
    harness.check(c.getTimeZone(), java.util.TimeZone.getDefault());
```
Most of time `Calendar.getInstance().getTimeZone()` and `java.util.TimeZone.getDefault()` should return current time zone and they are same. However this is a multi-thread load test, if there is a thread setting a different timezone between these two method calls, the returning timezone might be different. 
A sample test code setting a specific timezone:
```
    // Create a custom TimeZone with a daylight-time period.
    SimpleTimeZone stz = new SimpleTimeZone(60 * 60 * 1000, "MyZone",
                    Calendar.MARCH, -1, Calendar.SUNDAY, 2 * 60 * 60 * 1000,
                    Calendar.OCTOBER, -1, Calendar.SUNDAY, 2 * 60 * 60 * 1000);

    // Register the timezone as the default:
    TimeZone.setDefault(stz);
```
I think this is a test issue.

**Comment by pshipton** [comment]
@Mesbah-Alam can you pls exclude this test.

**Comment by pshipton** [comment]
Should be resolved by https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/299
