### ISSUE TITLE
JTReg Test Failure: java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7412]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/b44d19c4cbca42541aef5132f21870c1b924a68c/test/jdk/java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java#L1 fails for JDK11/13-openj9 only. 
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac
```
11:40:56  openjdk version "11.0.5" 2019-10-15
11:40:56  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9)
11:40:56  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0-m2, JRE 11 Linux amd64-64-Bit Compressed References 20191007_350 (JIT enabled, AOT enabled)
11:40:56  OpenJ9   - 23b8b11b4
11:40:56  OMR      - 20db4fbc
11:40:56  JCL      - c210c1e1a3 based on jdk-11.0.5+9)
```

Optional info
-------------

- intermittent failure (no): 
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- Test is searching for `ClassLoader.class` constructor and can't find it (returns `NoSuchMethodException`)

Failure output (captured from console output)
---------------------------------------------
```
11:44:46  STDOUT:
11:44:46  [TestNG] Running:
11:44:46    java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java
11:44:46  
11:44:46  test ModuleSetAccessibleTest.testJavaLangClass(): failure
11:44:46  java.lang.NoSuchMethodException: java.lang.Class.<init>(java.lang.ClassLoader, java.lang.Class)
11:44:46  	at java.base/java.lang.Class.newNoSuchMethodException(Class.java:638)
11:44:46  	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:810)
11:44:46  	at ModuleSetAccessibleTest.testJavaLangClass(ModuleSetAccessibleTest.java:150)
11:44:46  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:44:46  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:44:46  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:44:46  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:44:46  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
11:44:46  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
11:44:46  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
11:44:46  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
11:44:46  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
11:44:46  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
11:44:46  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
11:44:46  	at org.testng.TestRunner.run(TestRunner.java:623)
11:44:46  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
11:44:46  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
11:44:46  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
11:44:46  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
11:44:46  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
11:44:46  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
11:44:46  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
11:44:46  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
11:44:46  	at org.testng.TestNG.run(TestNG.java:1018)
11:44:46  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
11:44:46  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
11:44:46  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11:44:46  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11:44:46  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:44:46  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
11:44:46  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
11:44:46  	at java.base/java.lang.Thread.run(Thread.java:831)
11:44:46  test ModuleSetAccessibleTest.testPrivateConstructorInExportedPackage(): success
11:44:46  test ModuleSetAccessibleTest.testPrivateFieldInExportedPackage(): success
11:44:46  test ModuleSetAccessibleTest.testPrivateMethodInExportedPackage(): success
11:44:46  test ModuleSetAccessibleTest.testPublicConstructorInNonExportedPackage(): success
11:44:46  test ModuleSetAccessibleTest.testPublicFieldInNonExportedPackage(): success
11:44:46  
11:44:46  ===============================================
11:44:46  java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java
11:44:46  Total tests run: 6, Failures: 1, Skips: 0
11:44:46  ===============================================
```

Rerun job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java&TARGET=jdk_custom_0

**Comment by pshipton** [comment]
I don't think this is an OpenJ9 issue, but a test issue. Trying to use an implementation detail not included by OpenJ9.

**Comment by JasonFengJ9** [comment]
The test code snippet in question [1]:
```
    /**
     * Test that the Class constructor cannot be make accessible.
     */
    public void testJavaLangClass() throws Exception {

        // non-public constructor
        Constructor<?> ctor
            = Class.class.getDeclaredConstructor(ClassLoader.class, Class.class);
        AccessibleObject[] ctors = { ctor };

        try {
            ctor.setAccessible(true);
            assertTrue(false);
        } catch (SecurityException expected) { }

        try {
            AccessibleObject.setAccessible(ctors, true);
            assertTrue(false);
        } catch (SecurityException expected) { }

        // should succeed
        ctor.setAccessible(false);
        AccessibleObject.setAccessible(ctors, false);

    }
```

This sub-test targets specifically `java.lang.Class` non-public constructor which `OpenJ9` doesn't implement. I think this test can be commented out if rest of tests in `ModuleSetAccessibleTest` are still valuable.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/642d34017ca53a506a2b94a2cdae000470870f8f/test/jdk/java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java#L143-L167

**Comment by M-Davies** [comment]
@JasonFengJ9 The problem is that this sub-test should be feasible for both openj9 and hotspot. A different class constructor could be used that is shared by hotspot and openj9. I thought of doing `Constructor<?> ctor = Class.class.getDeclaredConstructor(StringBuilder.class, String.class);` (or `StringBuffer.class`) but that appears to produce a similar error in both hotspot and openj9. Another class would need to be used (perhaps `Thread` and `ThreadGroup`?)

**Comment by JasonFengJ9** [comment]
@M-Davies this is a test specifically for `java.lang.Class` constructors. 

As per `java.lang.reflect.Constructor.setAccessible()` javadoc [1]
_A SecurityException is also thrown if this object is a Constructor object for the class Class and flag is true._

So `Thread.class` or `ThreadGroup.class` won't fit the purpose. There is no same non-public `java.lang.Class` constructors between `OpenJ9` and `RI`. A workaround would be something like:
```
if (OpenJ9) {
  ctor = Class.class.getDeclaredConstructor();
} else {
  ctor = Class.class.getDeclaredConstructor(ClassLoader.class, Class.class);
}
```

[1] https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Constructor.html#setAccessible(boolean)

**Comment by M-Davies** [comment]
@JasonFengJ9 perhaps something like this? 
```
if (System.getProperty("java.vm.name").contains("OpenJ9")) {
  ctor = Class.class.getDeclaredConstructor();
} else {
  ctor = Class.class.getDeclaredConstructor(ClassLoader.class, Class.class);
}
```

**Comment by JasonFengJ9** [comment]
Looks reasonable to me, @M-Davies

**Comment by smlambert** [comment]
This is a proposed change to an openjdk test.  Changes to openjdk tests would happen in the openjdk project, not the extensions repo.  I do not want us to carry any test changes in the extensions repo.  I am not sure how likely it will be to push the proposed change that checks for an openj9 implementation to the openjdk repo.  

@M-Davies - you can discuss with @andrew-m-leonard regarding such a change.  It may be that we end up marking this test as permanently exclude if a fix can not be submitted to the upstream openjdk project.

**Comment by JasonFengJ9** [comment]
I believe so, it is in your initial post [1] 😄 
Thanks @smlambert team made it easy.

[1] https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java&TARGET=jdk_custom_0

**Comment by M-Davies** [comment]
@JasonFengJ9 @smlambert tests pass remotely for me. Will have a chat with @andrew-m-leonard about contributing this to openjdk

**Comment by M-Davies** [comment]
Since openjdk are unlikely to accept an implementation specific change to a test and the test is not absolutely crucial to the support of openj9, I will permanently exclude this test under the banner of unsuitable for openj9

**Comment by M-Davies** [comment]
FYI, `java/lang/reflect/AccessibleObject/TrySetAccessibleTest.java` fails the same way for JDK11/13-openj9 (uses hotspot `getDeclaredConstructor(ClassLoader.class, Class.class)`). Will perm exclude this too
