### ISSUE TITLE
Misplaced #ifdef in `TR_J9VMBase::get()`

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#7423]
`TR_J9VMBase::get(...)` has a `#if defined(J9VM_INTERP_AOT_COMPILE_SUPPORT)` statement that guards JITServer specific code:
https://github.com/eclipse/openj9/blob/master/runtime/compiler/env/VMJ9.cpp#L597

The #ifdef that refers to AOT should only guard AOT specific code

**Comment by a7ehuo** [comment]
I'll make the change.
