### ISSUE TITLE
Apache Flink fails to start with OpenJ9 versions of AdoptOpenJDK because 'T' unit is not supported by -XX:MaxDirectMemorySize

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#7427]
Hello,

While trying to run Apache Flink with AdoptOpenJDK with OpenJ9 instead of AdopOpenJDK with HotSpot, the JVM failed to start with the following error:

```
[root@ip-10-8-29-86 flink]# cat flink-flink-taskexecutor-0-ip-10-8-29-86.eu-west-2.compute.internal.out
JVMJ9VM013W Initialization error in function VMInitStages(0): Parse error for -XX:MaxDirectMemorySize= - option malformed.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

We found that this error occurs because Apache Flink starts the JVM with the following option: **-XX:MaxDirectMemorySize=8388607T**, and this is hard-coded, as one can see at line 65 of https://github.com/apache/flink/blob/master/flink-dist/src/main/flink-bin/bin/taskmanager.sh

And the root cause seems to be that OpenJ9 does not supports '**T**' (Terabytes) unit, see for example with a recent nightly build of AdoptOpenJDK 11 on Linux:

```
$ ./java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9-201910091831)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-531d15d38, JRE 11 Linux amd64-64-Bit Compressed References 20191009_352 (JIT enabled, AOT enabled)
OpenJ9   - 531d15d38
OMR      - 606cb8e9
JCL      - 642d34017c based on jdk-11.0.5+9)
$ ./java -XX:MaxDirectMemorySize=1T -version
JVMJ9VM013W Initialization error in function VMInitStages(0): Parse error for -XX:MaxDirectMemorySize= - option malformed.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

whereas this variant works:

```
$ ./java -XX:MaxDirectMemorySize=1024G -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9-201910091831)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-531d15d38, JRE 11 Linux amd64-64-Bit Compressed References 20191009_352 (JIT enabled, AOT enabled)
OpenJ9   - 531d15d38
OMR      - 606cb8e9
JCL      - 642d34017c based on jdk-11.0.5+9)
```

and HotSpot has no issue with "T" unit:

```
$ ./java -XX:MaxDirectMemorySize=1T -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9-201910091809)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+9-201910091809, mixed mode)
```

We can by-pass this OpenJ9 issue by patching our Apache Flink installation.

Anyway, would it be possible to fix OpenJ9 to make it support '**T**' unit, so as to avoid future adopters to fall into that trap and maybe discard OpenJ9 as a viable alternative to Hotpot? 

Kind regards,
Alexandre Vermeerbergen

**Comment by DanHeidinga** [comment]
Change should be straightforward - add a new case for "T" / "t" to: https://github.com/eclipse/openj9/blob/8ecd11892bc38f416ba474076ca6c815da699e8f/runtime/util/vmargs.c#L578-L610

**Comment by avermeer** [comment]
Hello Guys,

Thank you very much for the very fast reactions.
If the fix is trivial, why waiting for January release ?

Alexandre Vermeerbergen

**Comment by DanHeidinga** [comment]
The `0.17.0` release is targeted to Oct 18th and we've passed the Milestone 2 build date.  At this point the release is pretty locked down unless there are issues in the release stream.

For a change like this, we need to implement, test and review it before it makes it into `master`.  If after that, there's still time, we'll look at getting it into the 0.17.0 release but can't promise

**Comment by avermeer** [comment]
Fair, thanks !

**Comment by DanHeidinga** [comment]
@avermeer If you're interested in contributing to OpenJ9, this might be a good issue to pick up.  Let me know and we can work thru the required changes.

**Comment by avermeer** [comment]
Thanks for the offering. Do you have a contributor's newcomers documentation to provide detail about how to setup a git branch, coding guidelines, compiling & testing requirements before sending a PR?

Alexandre Vermeerbergen

**Comment by pshipton** [comment]
The contributing guidelines are here https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md

Build instructions are here https://github.com/eclipse/openj9/tree/master/doc/build-instructions

The change is straight forward, I was just looking for existing test cases that might need updating.

**Comment by pshipton** [comment]
@avermeer are you going to look into fixing this problem as an exercise in how it's done, or should I go ahead?

**Comment by avermeer** [comment]
@pshipton thanks for reminding me about this. Let's say I'm going to immerse myself in the exercise from tomorrow, until next Monday (12th of November). 

If I fail to grasp the way to make this contribution before 12th of November, then I'll pass my turn for this incident (which matters to me, even if tweaking Apache Flink startup options is a working by-pass), and maybe I'll try later with a less sensitive incident to train myself on contribution process.

Is that alright for you?

Kind regards,
Alexandre Vermeerbergen

**Comment by pshipton** [comment]
@avermeer sounds good.

**Comment by avermeer** [comment]
Hello,

Just to give some news about my attempt to contribute this fix:
* I successfully built a Java8u232 OpenJ9 using build instructions (based on Docker) on my CentOS Linux x64 box
* I would like to begin by extending the unit tests to add the 'T' unit, and make sure it fails until I implement support for 'T' unit.

However, it is not very clear how to run tests:
1. I tried typing:
    `make test`
    but I got the following error:

```
Building OpenJDK for target 'test' in configuration 'linux-x86_64-normal-server-release'

## Starting langtools
## Finished langtools (build time 00:00:01)

/usr/bin/make -s VERBOSE="-s" LOG_LEVEL="warn" -I /root/openj9-openjdk-jdk8/make/common -f /root/openj9-openjdk-jdk8/closed/openssl.gmk SPEC=/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/spec.gmk
/usr/bin/make -s VERBOSE="-s" LOG_LEVEL="warn" -I /root/openj9-openjdk-jdk8/make/common -f /root/openj9-openjdk-jdk8/closed/OpenJ9.gmk SPEC=/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/spec.gmk build-j9
Staging OpenJ9 sourcetools in /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm
Ensuring version information is up-to-date
Staging OpenJ9 jcl in /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm
Staging OpenJ9 runtime in /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm
Staging OpenJ9 OMR in /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm
Running OpenJ9 preprocessors with OPENJ9_BUILDSPEC: linux_x86-64_cmprssptrs
J9VM version: 58d4907
Universal Makefile Adapter - for J9, version 2.5.1

Reading constant pool from ./oti/vmconstantpool.xml
Found 7 flags used, declaring runtime constants.
        #define JCL_RTFLAG_DEFAULT 0x1 (useCount=221)
        #define JCL_RTFLAG_INTERP_HOT_CODE_REPLACEMENT 0x2 (useCount=1)
        #define JCL_RTFLAG_JIT_NEW_INSTANCE_PROTOTYPE 0x40 (useCount=1)
        #define JCL_RTFLAG_OPT_METHOD_HANDLE 0x10 (useCount=102)
        #define JCL_RTFLAG_OPT_MODULE 0x8 (useCount=10)
        #define JCL_RTFLAG_OPT_PANAMA 0x20 (useCount=2)
        #define JCL_RTFLAG_OPT_REFLECT 0x4 (useCount=16)
Generating header file Generating JCL constant pool definitions for Java 8

************************************************

        Total # of locales processed:           19
        Total # of NLS Files processed:         399
        Total # of messages processed:          35784

        Total # of header files generated:      0
        Total # of unchanged header files:      21
        Total # of properties files generated:  0
        Total # of unchanged properties files:  19
        Total # of errors:                      0

************************************************

Complete
Compiling OpenJ9 in /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Creating file oti/jilconsts.inc
Creating file oti/jilvalues.m4
J9_VERSION:           29
TR_BUILD_NAME:        58d4907
J9SRC:                /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/..
JIT_SRCBASE:          /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/..
JIT_OBJBASE:          /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../objs
JIT_DLL_DIR:          /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/..
OMR_DIR:              /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../omr
BUILD_CONFIG:         prod
NUMBER_OF_PROCESSORS:
VERSION_MAJOR:        8
ENABLE_GPU:
CUDA_HOME:
GDK_HOME:
SUCCESS - All files are up-to-date
OpenJ9 compile complete
/usr/bin/make -s VERBOSE="-s" LOG_LEVEL="warn" -I /root/openj9-openjdk-jdk8/make/common -f /root/openj9-openjdk-jdk8/closed/OpenJ9.gmk SPEC=/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/spec.gmk stage_openj9_build_jdk
## Starting corba
## Finished corba (build time 00:00:00)

## Starting jaxp
## Finished jaxp (build time 00:00:01)

## Starting jaxws
## Finished jaxws (build time 00:00:02)

## Starting jdk
## Finished jdk (build time 00:00:07)

## Starting demos
## Finished demos (build time 00:00:01)

## Starting nashorn
## Finished nashorn (build time 00:00:00)

## Starting images
## Finished images (build time 00:00:35)

## Starting test
/usr/bin/make -k -C  ../jdk/test  TEST=jdk_core jdk_core
make[2]: Entering directory '/root/openj9-openjdk-jdk8/jdk/test'
echo "Running tests: jdk_core"
Running tests: jdk_core
for each in jdk_core; do \
        /usr/bin/make -j 1 TEST_SELECTION=":$each" UNIQUE_DIR=$each jtreg_tests; \
done
make[3]: Entering directory '/root/openj9-openjdk-jdk8/jdk/test'
make[3]: Leaving directory '/root/openj9-openjdk-jdk8/jdk/test'
make[3]: *** No rule to make target '/java/re/jtreg/4.1/promoted/latest/binaries/jtreg', needed by '/java/re/jtreg/4.1/promoted/latest/binaries/jtreg/bin/jtreg'.
make[3]: Target 'jtreg_tests' not remade because of errors.
make[2]: *** [jdk_core] Error 2
Makefile:254: recipe for target 'jdk_core' failed
make[2]: Leaving directory '/root/openj9-openjdk-jdk8/jdk/test'
make[1]: *** [jdk_core] Error 2
Makefile:80: recipe for target 'jdk_core' failed
/usr/bin/make -k -C  ../langtools/test  JT_JAVA=/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image JTREG_HOME= UNIQUE_DIR=langtools_jtreg TEST=jtreg jtreg
make[2]: Entering directory '/root/openj9-openjdk-jdk8/langtools/test'
make[2]: *** No rule to make target '/bin/jtreg', needed by 'check-jtreg'.
if [ -r /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/jtreg/status.txt ]; then \
    echo ; echo "Summary of jtreg test failures" ; \
    cat /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/jtreg/JTreport/text/summary.txt | \
        grep -v 'Not run' | grep -v 'Passed' ; \
    echo ; \
    exit `cat /root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/jtreg/status.txt` ; \
fi
make[2]: Target 'jtreg' not remade because of errors.
make[2]: Leaving directory '/root/openj9-openjdk-jdk8/langtools/test'
make[1]: *** [langtools_jtreg] Error 2
make[1]: Target 'default' not remade because of errors.
Makefile:77: recipe for target 'langtools_jtreg' failed
## Finished test (build time 00:00:00)

----- Build times -------
Start 2019-11-09 15:44:03
End   2019-11-09 15:44:58
00:00:00 corba
00:00:01 demos
00:00:35 images
00:00:01 jaxp
00:00:02 jaxws
00:00:07 jdk
00:00:01 langtools
00:00:00 nashorn
00:00:00 test
00:00:55 TOTAL
-------------------------
Finished building OpenJDK for target 'test'
```
  Am I missing something to successfully run tests after a successful `make all` ?

  2. You mentioned that I need to define `JVMINIT_UNIT_TEST` to run the tests related to VM arguments, but it is not clear how I'm supposed to do this: you don't mean that I should modify `jvminit.c` and un-comment the following line, isn't it ?

`  /*#define JVMINIT_UNIT_TEST*/`

   So what is the _right_ way to enable this unit test and to run it?

  3. To contribute my fix, I need to create a pull request, hence to create a branch. Is there any naming convention which I should follow for the branch?

Sorry if my questions sound trivial, newbie here :)

Kind regards,
Alexandre

**Comment by pshipton** [comment]
1) The quick start quick for buildingand running tests is https://github.com/eclipse/openj9/blob/master/test/README.md but see (2).

2) For this particular change, which is not tested in the typical way, the correct way to test it is to uncomment the line by modifying `jvminit.c` as you mentioned, and then build the JVM. Run the testing by running `java` with any arguments (or none).

3) There isn't any naming convention for naming branches.

**Comment by avermeer** [comment]
Too bad ability to test is not part of the Docker image for building OpenJ9.
Anyway, I tried it, I found that:
* The quick start fails to mention that one needs to download an OpenJ9-based JDK8 (not Large heap, at least this is what I deduced from the cryptic mention to `JDK8 Linux x86-64 cmprssptrs OpenJ9 SDK` and then extract it so its path is `/my/openj9/jdk` directory.
* The quick start also fails to mention a dependency on Apache Ant. I downloaded latest version, then I set ANT_HOME to its extract location, I added to PATH the path of previously downloaded JDK8 (otherwise `ant` fails to run because its latest version requires Java8, while OpenJ9 JDK8 Docker build image only contains a JDK7), and run: `ant -f fetch.xml -Ddest=system` in its ANT_HOME directory)
* In spite of all these "guessed" additions to OpenJ9 JDK8 Docker build image, the make compile step fails with the following error:

```
make[1]: Leaving directory '/root/openj9-openjdk-jdk8/openj9/test'
ant -f scripts/build_test.xml -DTEST_ROOT=/root/openj9-openjdk-jdk8/openj9/test/TestConfig/.. -DBUILD_ROOT=/root/openj9-openjdk-jdk8/openj9/test/TestConfig/../../jvmtest -DJDK_VERSION=8 -DJDK_IMPL=openj9 -DJCL_VERSION=latest -DBUILD_LIST= -DRESOURCES_DIR=/root/openj9-openjdk-jdk8/openj9/test/TestConfig/../../jvmtest/TestConfig/resources -DPLATFORM=linux_x86-64_cr -DTEST_JDK_HOME=/my/openj9/jdk -DJVM_VERSION=openjdk8-openj9
Buildfile: /root/openj9-openjdk-jdk8/openj9/test/TestConfig/scripts/build_test.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

BUILD FAILED
/root/openj9-openjdk-jdk8/openj9/test/TestConfig/scripts/build_test.xml:37: Problem: failed to create task or type var
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.


Total time: 0 seconds
makefile:82: recipe for target 'compile' failed
make: *** [compile] Error 1
```

I must confess that I don't know sure what to do from here to fix this... any clue?

**Comment by avermeer** [comment]
Forget about previous comment:I have read the instructions too quickly (more details on prerequisites are provided after the Quick Start first lines, however I'm still concerned that default OpenJ9 Docker build image does not contain prerequisites for tests, maybe I'll contribute to improve this later).

**Comment by pshipton** [comment]
Note there is another set of Docker files which include what is needed for test.
https://github.com/eclipse/openj9/tree/master/buildenv/jenkins/docker-slaves/x86

We are slowly working towards auto-generating these Docker files, and replacing the ones in https://github.com/eclipse/openj9/tree/master/buildenv/docker, but nobody has any time to work on it.

**Comment by avermeer** [comment]
@pshipton  thanks a lot, I used the steps found in Docker file at: https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/docker-slaves/x86/centos6.9/Dockerfile to install Apache Ant 1.10.5 (instead of 1.7.1 documented in Prerequisites, sounds like [Prerequisites page](https://github.com/eclipse/openj9/blob/master/test/docs/Prerequisites.md) is not at all up to date, right?)

results: tests now compile and run !

However, I'm a bit frustrated, since with unmodified OpenJDK11 with OpenJ9, I get this result:

`TOTAL: 231   EXECUTED: 141   PASSED: 102   FAILED: 39   DISABLED: 3   SKIPPED: 87`

So that I can hardly use these tests to tell whether not not my changes are breaking something.

So I added my unit tests to `jvminit.c`, put my fix in `vmargs.c`, undefined the famous define in `jvminit.c`, compiled everything, got "SUCCESS" on my added unit tests - but some FAILED on other unrelated tests... isn't that weird? and last, I reverted the define from `jvminit.c`...

... and I committed my change to my branch and sent my first pull request for an OpenJ9 code change, see https://github.com/eclipse/openj9/pull/7738 !

If that's Okay, then i'll open a documentation issue to update https://www.eclipse.org/openj9/docs/x_jvm_commands/ to mention support for 't' and 'T' suffixes, but [CONTRIBUTING](https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md) says that in such case, I should add doc:externals tag to this issue, and I do not see how I could add such tag: am I again missing something?

**Comment by pshipton** [comment]
There are binaries created in the test image, what you created before running `make test`, that are required for some of the tests. An example, the test binaries from the last nightly build are https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_x86-64_linux_Nightly/200/native-test-libs.tar.gz

Here is an example test run https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/192

Seems the test binaries need to be located as the same level as the JVM in a directory called `native-test-libs`.

For the labels, a non-committer can only add labels when creating an Issue, but I've added the `doc:externals` label.

**Comment by pshipton** [comment]
Also note I can run Pull Request testing from the Pull Request to ensure the change doesn't break existing tests. I'll do that after you address my 64-bit comment.

**Comment by avermeer** [comment]
@pshipton I do not see your 64-bit comment, neither in current incident page, nor in my pull request's page, am I looking at the wrong place?

Trying to guess what this 64-bit comment might be: do you mean that 't' / 'T' suffix should not be added for 32-bits versions of OpenJ9, because 1T is larger than the memory that a 32-bit version can address?

If this is your concern, then I can change `vmargs.c` to make it only available for 64-bit builds (and change `jvminit.c `accordingly). In such case, I will also have to make it clear in the documentation update that this suffix only applies to 64-bit versions of OpenJ9.

Last question: you are right, my make test main failures are caused by missing native-related stuff. I'll try this later, but I feel that another incident is needed to track what's missing in build instructions (and in Docker images) to have both build & test doable for newbies committers without entering into lengthy discussions with other OpenJ9 more "aware" committers. Would you mind me creating some dedicated issues to track this need of documentation & materials?

**Comment by pshipton** [comment]
>  I do not see your 64-bit comment

My bad, I created the comment but left it in pending state. I see you've fixed it already so I won't bother adding it now.

**Comment by pshipton** [comment]
> Would you mind me creating some dedicated issues to track this need of documentation & materials?

Not at all, thanks for going through this exercise and following up to improve the project.

**Comment by avermeer** [comment]
Finally, today a new nightly build is available at AdoptOpenJDK with this fix, and indeed:

```
$  ./java -XX:MaxDirectMemorySize=1T -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-201911220430-b09)
Eclipse OpenJ9 VM (build master-df07672ec, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191122_449 (JIT enabled, AOT enabled)
OpenJ9   - df07672ec
OMR      - 1e4b62426
JCL      - f6352f08a86 based on jdk8u232-b09)
```

and:

```
$  ./java -XX:MaxDirectMemorySize=1T -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+4-201911211910)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-8191bb836, JRE 11 Linux amd64-64-Bit Compressed References 20191121_371 (JIT enabled, AOT enabled)
OpenJ9   - 8191bb836
OMR      - 1e4b62426
JCL      - f7e4f4e762 based on jdk-11.0.6+4)
```

which is definitely much better than the JVMJ9VM013W Initialization error which we got before this fix.

Apache Flink users choosing OpenJ9 will soon have a better experience (once 0.18.0 will be officially released).

I am too lazy to try non-LTS versions such as Java 12 & Java 13...

You know what: I'm happy !

And for people reading this who are not yet contributors to OpenJ9: try contributing, it's a nice experience, the community helps newbies with lots of goodwill.

Even if your C/C++ is like mine: a bit rusty :)
