### ISSUE TITLE
Create automated process in the open to refresh extensions repo with openjdk changes 

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#744]
Create job configuration on Eclipse openj9 CI (ci.eclipse.org/openj9) Jenkins to run "mirror" script - https://github.ibm.com/open-class-libraries/openjdk-build/blob/master/git-hg/update8.sh

(Note : this is bash script)

It requires the jenkins job to provide 2 variables

$GITHUB_IBM (eg https://github.ibm.com/open-class-libraries)
$J9REPOSITORY (eg openJDK8u152-b16-update-test)

**Comment by archanaNogriya** [comment]
Something similar we tried in our local jenkin: https://hyc-rt-openjdk-jenkins.swg-devops.com/job/Update_OpenJ9/configure

#!/bin/groovy

pipeline {
    agent {
        node {
            label 'ibmsdk-build-slave'
        }
    }
    environment {
        GIT_REPO = 'openjdk-build'
        JAVATEST_CREDENTIAL = '732fdbf7-acee-4835-bb43-5ebfef51e44b'
    }
    stages {
        stage('Setup') {
            steps {
                echo 'Setup..'
                script {
                    if (fileExists("${GIT_REPO}")) {
                        dir("${GIT_REPO}") {
                            deleteDir()
                        }
                    }
                }
                sh("mkdir ${GIT_REPO}")
            }    
        }
        stage('Clone') {
            steps {
                echo('Clone..')
                dir("${GIT_REPO}") {
                    git changelog: false, credentialsId: "${JAVATEST_CREDENTIAL}", poll: false, url: "git@github.ibm.com:open-class-libraries/${GIT_REPO}.git"
                }
            }
        }           
        stage('Update') {
            steps {
                echo('Update')
                dir("${GIT_REPO}/git-hg") {
                    sh("bash update8.sh")
                }
            }
        }
    }
}

**Comment by archanaNogriya** [comment]
@AdamBrousseau

**Comment by DanHeidinga** [comment]
@archanaNogriya Can you open an issue at one of or both of the extensions projects - https://github.com/ibmruntimes/openj9-openjdk-jdk9 and https://github.com/ibmruntimes/openj9-openjdk-jdk8

It belongs at those projects as it relates to updating their source repos.

Closing it here.

**Comment by archanaNogriya** [comment]
@DanHeidinga @AdamBrousseau which jenkin this should go then?

**Comment by AdamBrousseau** [comment]
The job should run at our project's Jenkins instance provided by Eclipse
https://ci.eclipse.org/openj9/
