### ISSUE TITLE
Failing JDK11.0.5+10_openj9-0.17.0 Extended System Test: SharedClasses.SCM23.MultiThread

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#7489]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_x86-64_windows/50/tapResults/
Test Category: extended system
OS/Architecture: openjdk_x86-64_windows & mac_x86-64
OpenJDK Version: 11.0.5+10_openj9-0.17.0
Public Build SHAs:
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+9)

Optional info
-------------

Intermittent failure: No
Regression or new test: Regression

Failure output (captured from console output)
---------------------------------------------
MT2 10:40:47 >> Loaded 19000 classes...
STF 10:41:06.586 - **FAILED** Process MT4 has timed out
STF 10:41:06.586 - Collecting dumps for: MT4
STF 10:41:49.937 - Using procdump.exe to generate .DMP files
STF 10:41:49.946 - Running command: C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\jvmtest\system\systemtest_prereqs\windows_sysinternals\procdump.exe -accepteula -ma 324
STF 10:41:49.946 - Redirecting stderr to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results/5.MT4.jvmdump.stderr
STF 10:41:49.946 - Redirecting stdout to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results/5.MT4.jvmdump.stdout
STF 10:41:50.868 - Pausing for 30 seconds
STF 10:42:20.870 - Process MT4 (pid 324) is no longer running. Abandoning dump collection.
MT2 10:41:17 >> --> Threads 19200 to 19500 <--
MT2 10:42:02 >> --> Threads 19500 to 19800 <--
MT3 10:41:16 >> --> Threads 18300 to 18600 <--
MT3 10:42:10 >> --> Threads 18600 to 18900 <--
MT4 10:41:50 >> Loaded 20000 classes...
STF 10:42:20.873 - Monitoring Report Summary:
STF 10:42:20.873 -   o Process MT1 ended with the expected exit code (0)
STF 10:42:20.873 -   o Process MT2 is still running
STF 10:42:20.873 -   o Process MT3 is still running
STF 10:42:20.873 -   o Process MT4 has timed out
STF 10:42:20.873 -   o Process MT5 ended with the expected exit code (0)
STF 10:42:20.878 - Killing processes: MT1 MT2 MT3 MT4 MT5
STF 10:42:20.879 -   o Process MT5 is not running
STF 10:42:24.428 - Using powershell to kill MT3
STF 10:42:24.430 - Running command: cmd /c echo | powershell Stop-Process 280
STF 10:42:24.430 - Redirecting stderr to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results\kill_powershell.stderr
STF 10:42:24.430 - Redirecting stdout to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results\kill_powershell.stdout
STF 10:42:26.438 -   o Process MT3 killed
MT3 10:42:24 >> --> Threads 18900 to 19200 <--
MT3 10:42:25 >> Loaded 19000 classes...
STF 10:42:26.439 -   o Process MT2 is not running
STF 10:42:26.439 -   o Process MT4 is not running
STF 10:42:26.440 -   o Process MT1 is not running
**FAILED** at step 5 (Start java processes using LoaderSlaveMultiThread). Expected return value=0 Actual=1 at C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/execute.pl line 123.
STF 10:42:26.972 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 10:42:26.972 - 
STF 10:42:26.972 - ====================   T E A R D O W N   ====================
STF 10:42:26.972 - Running teardown: perl C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/tearDown.pl
STF 10:42:27.291 - 
STF 10:42:27.291 - +------ Step 8 - Destroy cache
STF 10:42:27.291 - | Destroy specific shared classes cache
STF 10:42:27.291 - |   Options:        -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\openjdk-tests\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0\20191016-084058-SharedClasses\results\caches${cacheOperation}
STF 10:42:27.291 - |   CacheName:      SCC_SysTest_Workload_Cache
STF 10:42:27.291 - |   CacheDir:       C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\openjdk-tests\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0\20191016-084058-SharedClasses\results\caches
STF 10:42:27.356 - |   CacheOperation: ,destroy
STF 10:42:27.356 - |
STF 10:42:27.357 - Running command: C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdkbinary/j2sdk-image/bin/java -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\openjdk-tests\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0\20191016-084058-SharedClasses\results\caches,destroy
STF 10:42:27.357 - Redirecting stderr to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results/8.SCC.stderr
STF 10:42:27.357 - Redirecting stdout to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results/8.SCC.stdout
STF 10:42:27.397 - Monitoring processes: SCC
SCC stderr JVMSHRC806I Compressed references persistent shared cache "SCC_SysTest_Workload_Cache" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
STF 10:42:27.739 - Monitoring Report Summary:
STF 10:42:27.739 -   o Process SCC ended with the expected exit code (1)
STF 10:42:27.740 - 
STF 10:42:27.740 - +------ Step 9 - Destroy cache
STF 10:42:27.740 - | Destroy specific non-persistent shared classes cache
STF 10:42:27.740 - |   Options:        -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\openjdk-tests\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0\20191016-084058-SharedClasses\results\caches${cacheOperation}
STF 10:42:27.740 - |   CacheName:      SCC_SysTest_Workload_Cache
STF 10:42:27.740 - |   CacheDir:       C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\openjdk-tests\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0\20191016-084058-SharedClasses\results\caches
STF 10:42:27.740 - |   CacheOperation: ,destroy,nonpersistent
STF 10:42:27.740 - |
STF 10:42:27.740 - Running command: C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdkbinary/j2sdk-image/bin/java -Xshareclasses:name=SCC_SysTest_Workload_Cache,cacheDir=C:\Users\jenkins\workspace\Test_openjdk11_j9_extended.system_x86-64_windows\openjdk-tests\TestConfig\test_output_15712344018643\SharedClasses.SCM23.MultiThread_0\20191016-084058-SharedClasses\results\caches,destroy,nonpersistent
STF 10:42:27.740 - Redirecting stderr to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results/9.SCC.stderr
STF 10:42:27.740 - Redirecting stdout to C:/Users/jenkins/workspace/Test_openjdk11_j9_extended.system_x86-64_windows/openjdk-tests/TestConfig/test_output_15712344018643/SharedClasses.SCM23.MultiThread_0/20191016-084058-SharedClasses/results/9.SCC.stdout
STF 10:42:27.744 - Monitoring processes: SCC
SCC stderr JVMSHRC023E Cache does not exist
STF 10:42:28.044 - Monitoring Report Summary:
STF 10:42:28.044 -   o Process SCC ended with the expected exit code (1)
STF 10:42:28.044 - TEARDOWN stage completed
STF 10:42:28.075 - 
STF 10:42:28.075 - =====================   R E S U L T S   =====================
STF 10:42:28.075 - Stage results:
STF 10:42:28.075 -   setUp:     pass
STF 10:42:28.075 -   execute:  *fail*
STF 10:42:28.075 -   teardown:  pass
STF 10:42:28.075 - 
STF 10:42:28.075 - Overall result: **FAILED**

SharedClasses.SCM23.MultiThread_0_FAILED

**Comment by archanaNogriya** [comment]
Resubmitted Grinder job is for the same test suit with the same build.
**openjdk_x86-64_windows :** https://ci.adoptopenjdk.net/job/Grinder/816/consoleFull.
**Customized SDK URL:** https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/357/artifact/workspace/target/OpenJDK11U-jdk_x64_windows_openj9_11.0.5_10_openj9-0.17.0.zip

**openjdk_x86-64_mac:** https://ci.adoptopenjdk.net/job/Grinder/816/consoleFull.
**Customized SDK URL:** https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/371/artifact/workspace/target/OpenJDK11U-jdk_x64_mac_openj9_11.0.5_10_openj9-0.17.0.tar.gz

**Comment by archanaNogriya** [comment]
@andrew-m-leonard mentioned that this issue has been seen couple of times not running correctly in the Adopt environment cause slow machines in this particular case.

It works perfectly fine in internal jenkins. Hence I would not call this Openj9 issue at all.

I will close this issue.

**Comment by pshipton** [comment]
Related to https://github.com/eclipse/openj9/issues/7178
The system test has been updated, it should no longer time out but instead run for ~10min.
