### ISSUE TITLE
code issue in mminit.cpp?

### ISSUE THREAD

**Issue by zheddie** [eclipse/openj9#7502]
@pshipton  , Hi Peter, I am reading the source code , and got one question on mminit.cpp line 2979,2980 as below:
```
    bool hwSupported = j9sysinfo_processor_has_feature(&processorDesc, J9PORT_S390_FEATURE_GUARDED_STORAGE) && j9sysinfo_processor_has_feature(&processorDesc, J9PORT_S390_FEATURE_SIDE_EFFECT_ACCESS);
```
Not sure why this kind of S390 code wasn't quoted  by #ifdef for S390 system?  This may cause all other platforms give out false on extensions->concurrentScavengerHWSupport field.

Let me know if I missed anything . thanks.

**Comment by zheddie** [comment]
hmmm. Or may be only S390 system have HW support of scavenger?  😄

**Comment by DanHeidinga** [comment]
> Or may be only S390 system have HW support of scavenger?

That's correct.  The `J9PORT_S390_FEATURE_GUARDED_STORAGE` flag is only ever enabled on 390 machines.  Every other platform will return false.

See code on 390 testing the hw for support:
https://github.com/eclipse/openj9/blob/fc0de283a29b33d73813abc58d1fb52f65246dd7/runtime/port/unix/j9sysinfo.c#L1082-L1093
