### ISSUE TITLE
OpenJ9 MSI Installer show GNU v2 (+GNU with classpath exception) license instead of EPL v2.0 & Apache License v2.0

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#7516]
Hello,

I have tried for the first time to install OpenJ9 using the MSI Installer provided at this place:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u232-b09_openj9-0.17.0/OpenJDK8U-jdk_x64_windows_openj9_8u232b09_openj9-0.17.0.msi

(this is the default link when one opens the download page for OpenJ9 at https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9) 

I have been shocked to see that in the panel where the installer prompts the user to accept the License, only GPL V2 and GPL V2 with Classpath exception licenses are mentioned.

I have read OpenJ9 contributor's documentation (at https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md), and the following is clearly mentioned:

> Eclipse OpenJ9 is dual-licensed under the Eclipse Public License v2.0 and the Apache License v2.0

It seems to be that OpenJ9 MSI installer is giving a wrong message: it should show EPL v2.0 & Apache License v2.0 first, and add the GPL v2 with Classpath exception  - but not GPLv2 since as far as I understand, OpenJ9 source code has no such "pure GPL v2"-licensed code.

GPL V2 is usually seen as "viral license", so it would be a shame to see OpenJ9's team efforts to have a clean source base (compared to the huge mix of licenses in HotSpot sources) being ignored by end-users.

Could this license prompting be fixed in next OpenJ9 release - that is to say unless I misunderstand OpenJ9 licensing ?

Kind regards,
Alexandre Vermeerbergen

**Comment by pshipton** [comment]
@avermeer OpenJ9 itself is Eclipse/Apache licensed, but the builds are OpenJDK + OpenJ9 and OpenJDK is GPL V2 and GPL V2 with Classpath exception, plus other licenses.

Any problem with the installer should be reported to the AdoptOpenJDK.net project.
https://github.com/AdoptOpenJDK/openjdk-build/issues

**Comment by pshipton** [comment]
Copying the license from an OpenJ9 file below. Note the second paragraph.
```
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at https://www.eclipse.org/legal/epl-2.0/
 * or the Apache License, Version 2.0 which accompanies this distribution and
 * is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following
 * Secondary Licenses when the conditions for such availability set
 * forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
 * General Public License, version 2 with the GNU Classpath
 * Exception [1] and GNU General Public License, version 2 with the
 * OpenJDK Assembly Exception [2].
```

**Comment by pshipton** [comment]
This is not an OpenJ9 problem. The question has been answered. Closing.

**Comment by avermeer** [comment]
Okay, created https://github.com/AdoptOpenJDK/openjdk-build/issues/1375, since it's an AdoptOpenJDK issue, not an OpenJ9 one, to request alternative licensing of AdoptOpenJDK with OpenJ9 binaries distributions.

**Comment by avermeer** [comment]
My issue on AdoptOpenJDK side was closed with an [answer telling that as a downstream provider, they cannot change the license](https://github.com/AdoptOpenJDK/openjdk-build/issues/1375#issuecomment-552231579). 

Looks like an egg-and-chicken problem: you (OpenJ9) seem to say that it's not an OpenJ9 issue but seem to imply that the organization in charge of turning OpenJ9 into a full Java distribution (AdoptOpenJDK) chose GPLv2 while they could have chosen ASL or EPL, and they say it's not up to them as "a downstream provider", implying that you (OpenJ9 community) upstream provider made this license as it is today.

I must confess that this later interpretation could be the right one, since when I follow OpenJ9 build instructions, it leads to a binary distribution with a LICENSE file in its root, which is a concatenation of GPLv2 and the "CLASSPATH" EXCEPTION TO THE GPL.

I am nuts, or missing something that could explain why nobody care to "fix" the license for OpenJ9 to make its ASL or EPL with the "CLASSPATH" EXCEPTION TO THE GPL, i.e., a neat differentiator vs. HotSpot distribution, given that HotSpot itself is mostly GPLv2 (with a few GPLv3 and more exotic licenses in its source files) ?

Alexandre

**Comment by pshipton** [comment]
The GPLv2 LICENSE file in the build comes from OpenJDK project and build process. Do I understand correctly the concern is that the LICENSE file doesn't mention the OpenJ9 parts?

The LICENSE for OpenJ9 is https://github.com/eclipse/openj9/blob/master/LICENSE but I agree this file doesn't get included in the binary. What does get included is the openj9-notices.html file. Is this insufficient?

**Comment by avermeer** [comment]
@pshipton my understanding is that OpenJDK with OpenJ9 binaries only use the Java Class libraries from OpenJDK (and these later have "CLASSPATH" EXCEPTION TO THE GPL), and that OpenJ9 completely replaces the GPLv2-licensed HotSpot.

So, why do we end with a GPLv2 to license the result of OpenJ9 + the Java standard libraries? 

I have the feeling that this is not making justice to the very clean OpenJ9 sources' licenses (have a look to HotSpot sources, it's a big mix of many licenses...), isn't it ?

**Comment by pshipton** [comment]
Agreed, we should have a GPLv2 with "CLASSPATH" EXCEPTION + OpenJ9 licensed binary.
The LICENSE file contains a `"CLASSPATH" EXCEPTION TO THE GPL` section.

**Comment by DanHeidinga** [comment]
> Agreed, the binary produced should be GPLv2 with "CLASSPATH" EXCEPTION + OpenJ9 licensed binary.

Was going to respond to this but @mstoodle already said it better in https://github.com/AdoptOpenJDK/openjdk-build/issues/1375#issuecomment-552300730.

I think we can close this issue.

**Comment by avermeer** [comment]
Wait... are you meaning that it's okay for OpenJDK OpenJ9 distribution to have a GPLv2 while it does not include HotSpot?

Why leaving a copyleft license if binaries don't need it ?

**Comment by DanHeidinga** [comment]
My understanding is the OpenJDK code we connect with carries a GPLv2+Classpath license.  We replace the pure GPLv2 Hotspot engine with a compatibly licensed (EPLv2+secondary licenses clause) OpenJ9 engine.

Doing this doesn't change the license of the rest of the OpenJDK code we work with.  The final binary still needs to respect the GPLv2+Classpath license of the OpenJDK code.
