### ISSUE TITLE
Build failure with J9ClassEnv.cpp

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#7518]
Two calls to `inROMClass()` in `J9::ClassEnv::getROMClassRefName()` cause a build failure when you enable `TR_ASSERT()` as shown below:

>/root/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/compiler/../compiler/env/J9ClassEnv.cpp: In member function 'uint8_t* J9::ClassEnv::getROMClassRefName(TR::Compilation*, TR_OpaqueClassBlock*, uint32_t, int&)':
>/root/openj9-openjdk-jdk11/build/linux-aarch64-normal-server-release/vm/compiler/../compiler/env/J9ClassEnv.cpp:520:14: error: 'inROMClass' was not declared in this scope
>    TR_ASSERT(inROMClass(romFieldRef), "field ref must be in ROM class");

**Comment by a7ehuo** [comment]
Will remove the `TR_ASSERTs` for now.  `TR_ASSERTs` are added in #7292 but `inROMClass()` is not declared/defined for `ClassEnv`.
