### ISSUE TITLE
sanity.openjdk native_sanity

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7521]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly/1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux_Nightly/1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/1
`Use -nativepath to specify the location of native code`

**Comment by pshipton** [comment]
@llxia @smlambert what do we need to do to setup these tests properly?

**Comment by smlambert** [comment]
These tests use the openjdk native test libs (built and available from AdoptOpenJDK, related https://github.com/AdoptOpenJDK/openjdk-build/pull/1251).  Presumably those native test images are also being built at OpenJ9 (if the builds scripts run 'make all'), just not being archived anywhere for retrieval.

<img width="537" alt="Screen Shot 2019-10-20 at 12 14 11 PM" src="https://user-images.githubusercontent.com/2836948/67162591-52d3ba80-f333-11e9-839b-c605fb964ea3.png">

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
We have the native-test-libs.tar.gz archived with every build and specified as part of the CUSTOMIZED_SDK_URL. It's working for functionality tests. Seems something needs to be done to specify `-nativepath`.

**Comment by sophia-guo** [comment]
Yes, native-test-libs.tar.gz is only the functional(openj9) native test lib. These tests need openjdk native test libs. In AdoptOpenjdk openj9 build the testImage includes both functional native test libs and jdk native test libs.
<img width="585" alt="Screen Shot 2019-10-21 at 8 59 20 AM" src="https://user-images.githubusercontent.com/18030625/67207271-33936680-f3e1-11e9-95f6-6b16842be617.png">

**Comment by smlambert** [comment]
Yes, please note the difference between the test natives created as part of building openjdk test directory used by openjdk tests, versus the variety of openj9 test natives that are historically built and used by functional tests.

openjdk vs functional - 2 completely different groups of test material

**Comment by pshipton** [comment]
@jdekonin we need to include the openjdk directory in the native-test-libs.tar.gz

**Comment by jdekonin** [comment]
Where/how are these natives located/generated in JDK8?

**Comment by smlambert** [comment]
jdk8 is different than jdk10+ builds
 
in jdk8 'make all' would build test native libs, in jdk10+ explicit make target to build them 'make test-image' and new requirement to use cmdline option -nativetestpath to run them

I presume details are in the various readme's off of http://openjdk.java.net/groups/build/ and by looking at the makefiles in the extensions repo

**Comment by smlambert** [comment]
@pshipton - in the immediate term, I was thinking to shift this jdk_native_sanity target to the 'special' level, along with jdk_math_jre target (discussed in different issue) so neither test target would be executed in the OpenJ9 (which only runs 'sanity' and 'extended' levels).  

Longer term, it is still a good idea for this to be resolved by building the openjdk test images at OpenJ9.

**Comment by pshipton** [comment]
Note we didn't get failures in jdk8 testing, the failures were in jdk11. It seems the problem is we need to run 'make test-image' in addition to `make all`. Seems easy enough to fix.

**Comment by smlambert** [comment]
ok, for now I will just move the jre testing to special unless I hear differently in this issue

**Comment by adam-thorpe** [comment]
The build jobs at openj9 are creating the jdk test lib if I am not mistaken:
```
22:38:44  Creating support/test/jdk/jtreg/native/lib/libInheritedChannel.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/lib/libDirectIO.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/lib/libstringPlatformChars.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/lib/libnativeLibraryTest.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/lib/libTestNative.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/lib/libsanity_SimpleNativeLib.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/lib/libsanity_SimpleNativeLib2.so from 1 file(s)
22:38:44  Creating support/test/jdk/jtreg/native/bin/sanity_SimpleNativeLauncher from 1 file(s)
```
However they are not being added into the native-test-libs.gz.tar archive, it is only grabbing the functional native test lib:
`tar -C build/linux-s390x-normal-server-release/images/ -zcvf native-test-libs.tar.gz test/openj9 --transform s,test/openj9,native-test-libs,`
This problem also applies to hyc runtimes jenkins.

**Comment by sophia-guo** [comment]
I believe this is fixed and can be closed?

**Comment by pshipton** [comment]
Should be.
