### ISSUE TITLE
Outlined new allocation support?

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7550]
There are remnants of support for outlined new allocations throughout the OpenJ9 (and OMR) JIT:

1.  X86 : some remnants of old helpers in OMR only.  Looks like this was ripped out at some point.
2.  Power : "enabled" pre-Power 8 for OptServer, disabled on Power 8 and beyond
3.  Z : "disabled for now" is the comment, which is several years old.
4.  ARM/AArch64 : never implemented

So at the moment this is only enabled pre-Power 8 for OptServer.

Is this feature still relevant and useful?  @gita-omr @andrewcraik @fjeremic @knn-k @vijaysun-omr 

If not, I propose we remove it.

**Comment by vijaysun-omr** [comment]
I doubt this will be worth anything on today's cpus with improved cache characteristics. I would be fine with removing it.

**Comment by gita-omr** [comment]
If it's only in pre-Power 8 I am fine with removing it. But could you please remind me what exactly it does? Thanks.

**Comment by 0xdaryl** [comment]
My recollection is that it was an i-cache saving optimization that moved many of the instructions that the JIT would normally inline to allocate an object into a helper that could be shared across multiple allocation sites.  This is an optimized sequence and still faster than calling the full VM helper to figure out how to do the allocation.  But someone correct me if I'm wrong.

**Comment by fjeremic** [comment]
I also agree we can remove this. The benefit of outlining such a sequence is unlikely to give measurable performance benefit.

**Comment by 0xdaryl** [comment]
Thanks for your input.  I created a new beginner issue #7555 to track this removal.  Closing this now.
