### ISSUE TITLE
Segmentation error on agent attachment

### ISSUE THREAD

**Issue by raphw** [eclipse/openj9#7565]
Java -version output
--------------------

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit Compressed References 20191016_358 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

Summary of problem
------------------

Segmentation error since Java 11 (does not happen in Java 8 build). Also happens in recent Java 13 version. Can be easily and stabaly reproduced by building https://github.com/raphw/byte-buddy with `./mvnw verify -Pintegration`.

The problem accurs in a routine that redefines the `LambdaMetafactory` to instrument lambda expressions. The failing test is `AgentBuilderDefaultApplicationTest::testInstanceCapturingLambda` which needs to be enabled for OpenJ9 by removing `hotSpot = true`.

Diagnostic files
----------------

[javacore.20191023.114820.10889.0002.txt](https://github.com/eclipse/openj9/files/3761695/javacore.20191023.114820.10889.0002.txt)
[jitdump.20191023.114820.10889.0004.dmp.txt](https://github.com/eclipse/openj9/files/3761701/jitdump.20191023.114820.10889.0004.dmp.txt)
[Snap.20191023.114820.10889.0003.trc.txt](https://github.com/eclipse/openj9/files/3761702/Snap.20191023.114820.10889.0003.trc.txt)

Dump: https://drive.google.com/file/d/1MdFOIhSha2p2l-3t4ny2g_2pc2aqRqJ0/view?usp=sharing

**Comment by tajila** [comment]
The crash occurs in `fixUnsafeMethods` specifically at https://github.com/eclipse/openj9/blob/master/runtime/vm/classsupport.c#L1538.

`							bytecodes[pc] = JBinvokespecial;`

The class being defined is an anonymous class. The bytecode value  at that `pc` can be read, but the issues seems to be writing to that address

**Comment by DanHeidinga** [comment]
@tajila Is the anonymous class in the SCC?  There were recent changes to allow them to be cached which may be interacting poorly with the `fixUnsafeMethods()` call.  It may need to occur earlier if the classes are to be cached.

**Comment by tajila** [comment]
@DanHeidinga Yes the romClass is in the SCC. We'll need to modify this path for anonClasses.

**Comment by DanHeidinga** [comment]
@tajila I thought this was fixed already.  Can you link to the PR that fixes it?

**Comment by tajila** [comment]
Here is the PR that fixes this issue, https://github.com/eclipse/openj9/pull/7666
