### ISSUE TITLE
Breakpoint is not recognized in a try with resources on return statement

### ISSUE THREAD

**Issue by JBertaux** [eclipse/openj9#7591]
Java -version output
--------------------
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```
Summary of problem
------------------
When I put a breakpoint on a return statement in a try with resources this breakpoint is not recognized and so it does not stop on the breakpoint. When I change to HotSpot in the same version 11.0.4, it stops at the breakpoint.
I use IntelliJ IDEA 2019.2.3 (Ultimate Edition).
I tried with the parameters `-Xnojit -Xnoaot` but I have the same issue.

Code example:
```java
    private ConsumerRecords<String, String> consumeStringFromDlq() {
        var consumerPropsDlq = KafkaTestUtils.consumerProps(GROUP_NAME, "true", embeddedKafka.getEmbeddedKafka());
        consumerPropsDlq.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        consumerPropsDlq.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        consumerPropsDlq.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        var cfDlq = new DefaultKafkaConsumerFactory<>(consumerPropsDlq, new StringDeserializer(), new StringDeserializer());
        try (var consumerDlq = cfDlq.createConsumer()) {
            consumerDlq.subscribe(List.of(DLQ_TOPIC));
            return consumerDlq.poll(Duration.ofMillis(10_000)); // <- HERE
        }
    }
```

**Comment by mikezhang1234567890** [comment]
Taking a look at this.

**Comment by pshipton** [comment]
@mikezhang1234567890 any updates?

**Comment by mikezhang1234567890** [comment]
When Intellij tries to create the breakpoint it needs to create a ClassWriter at some point, which needs to get the constant pool. On OpenJ9, when trying to get a `CONSTANT_MethodHandle_info` entry, the `reference_index` value refers to an invalid index.

Still trying to figure out what why the value is wrong.
