### ISSUE TITLE
Fix `Stop using the J9VM_JIT_32BIT_USES64BIT_REGISTERS from m4 asm (#7572)` so it can be re-applied

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#7602]
https://github.com/eclipse/openj9/pull/7600 had to revert the change as it broke zOS 31.

**Comment by DanHeidinga** [comment]
Fyi @dnakamura @pshipton

**Comment by DanHeidinga** [comment]
Possibly a stupid question but would a search / replace of `[` & `]` with `{`  & `}`in the jit m4 files solve the problem as well?  Might be a faster and cleaner solution

**Comment by dnakamura** [comment]
Yes was discussing the issue with gac over lunch and we decided it probably makes sense to change the jit quoting style.  However since I also have a version which cleans up some of the M4 code  passing internal builds, I will likely go forward with that as well

**Comment by DanHeidinga** [comment]
@dnakamura Has this been fixed?  Can you link it to the relevant PR?

**Comment by fjeremic** [comment]
> @dnakamura Has this been fixed? Can you link it to the relevant PR?

Issue has been fixed in #7664. @dnakamura let's make sure to add a "Fixes: #7664" tag in the PR next time so we properly associate the issue with the PR that fixes it. Thanks!
