### ISSUE TITLE
Identifying changes which require release documentation

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#761]
Some changes should be called out in release documentation because of a change in behavior. Similarly new features, or options, can be documented as What's New. 

Two ideas for tracking these:

1) create new labels such as doc:releasenote and doc:whatsnew to tag Pull Requests. These labels are easy to add to Pull Requests. The downside is a query will find all the tagged pull requests and it won't be simple to tell which ones are in which releases. Queries can be created based on release dates to find merges, it should be possible to construct appropriate queries.

2) create one or more Issues and update these with references to Pull Requests that meet the criteria. When a release occurs the Issues are closed and new ones are opened. The downside is you need to find the Issues to update.

**Comment by SueChaplain** [comment]
Perhaps we can take inspiration from here: https://nodejs.org/en/blog/release/v8.9.2/    ??

Spoke briefly to Gibson and there is tooling behind it. He's now aware of this issue and will hopefully join the conversation.

**Comment by SueChaplain** [comment]
@gibfan - are you able to join this discussion please?

**Comment by DanHeidinga** [comment]
I've created the two new labels requested.  As the plan is to use the github release, we can call out all items with those tags in the release item.

Closing this now.

**Comment by SueChaplain** [comment]
@danheidinga - I've some concerns that the process of pulling out the changes could be arduous, but let's give it a go and see if the experience highlights some better opportunities.

**Comment by DanHeidinga** [comment]
Agreed and understood.  I think we need to try out some of these processes and see how they go.  Some will be painful, some easily automated, and others will need to change.  Time will tell which is which.
