### ISSUE TITLE
Enable AIX DDR support for Java 13 and later

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7612]
AIX DDR support is disabled in #7613

**Comment by JasonFengJ9** [comment]
Are we considering to disable the failing tests until `AIX` DDR support is enabled?

**Comment by keithc-ca** [comment]
> Are we considering to disable the failing tests until `AIX` DDR support is enabled?

That seems like a reasonable plan. Can you put a PR together to do that? Please connect it to this issue so we don't forget to re-enable the tests later.

**Comment by pshipton** [comment]
We can only disable these tests if the excludes are specified to AIX JDK13.

**Comment by JasonFengJ9** [comment]
A few `DDR` test buckets observed: 
1. https://github.com/eclipse/openj9/tree/master/test/functional/DDR_Test
2. https://github.com/eclipse/openj9/tree/master/test/functional/cmdLineTests/modularityddrtests
3. https://github.com/eclipse/openj9/tree/master/test/functional/cmdLineTests/shrcdbgddrext
4. https://github.com/eclipse/openj9/tree/master/test/functional/cmdLineTests/classesdbgddrext
5. https://github.com/eclipse/openj9/tree/master/test/functional/cmdLineTests/callsitedbgddrext

Any more? @keithc-ca

**Comment by keithc-ca** [comment]
> Any more? @keithc-ca

I haven't looked myself so I don't know, that seems like a good start at least.

**Comment by keithc-ca** [comment]
https://github.com/eclipse/omr/pull/4661 and https://github.com/eclipse/openj9/pull/8055 should address this.

**Comment by pshipton** [comment]
The changes are merged.
