### ISSUE TITLE
Extend testing for SCC checkURLTimestamps/noCheckURLTimestamps options

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#7627]
> Are we missing test coverage in this area? 

I don't think test cases of empty url array or url array with invalid urls were added when introducing `-Xshareclasses:checkURLTimestamps/-Xshareclasses:noCheckURLTimestamps`

_Originally posted by @hangshao0 in https://github.com/eclipse/openj9/pull/7615#issuecomment-547477445_

**Comment by DanHeidinga** [comment]
FYI @hangshao0 Can you get this added to the SCC plan?

**Comment by pshipton** [comment]
The test was failing in some cases, I've reverted it while we figure it out.
`>> Required condition was not found: [Output match: Entering with url 0000000000000000]`
