### ISSUE TITLE
Define baseline target environment for AOT compilations

### ISSUE THREAD

**Issue by dsouzai** [eclipse/openj9#7635]
Currently, the target environment of AOT code is essentially the host environment. However, the need for defining some baseline target environment has risen with the arrival of the multi-layer SCC feature. The point of having multi-layer SCCs is to facilitate having SCCs in different layers in Docker images; images that are, by design, portable. While the AOT Header validation [1] does validate that the processors and other features are compatible, there are some problems - problems which have always been there; it's just that generally in a single SCC world, the SCC does not move from the machine on which it was generated.

The problems generally stem from the processor validations. Specifically:
1. If the SCC is generated on machine A which is newer than machine B, it is possible that a JVM on machine B will not be able to use the SCC. While this certainly the right thing to do, it does mean that whoever wishes to build these SCC layers needs to find some old machine to populate the SCCs to ensure the widest coverage.
2. If the SCC is generated on a machine B which is *older* than machine A, then while the AOT code will likely be loaded on machine A, it is also possible that the JVM will add new AOT code to the SCC using features that were available on machine A but not on machine B. Now, if we were to use the updated SCC on machine B, we would just load the code because when we validated the SCC on machine A, we only check whether the features of machine A are a superset of machine B and we never update the AOT Header with this super set. As such we might run code that isn't compatible on machine B.

The way to deal with both problems is to do what all static compilers do. Define some baseline target environment with the reasonably widest possible coverage. This depends on https://github.com/eclipse/omr/issues/4518 (and associated OpenJ9 changes that will have to follow).

Obviously there are some subtleties that have to be considered. For example, because the generated AOT code is also run on the machine on which it is generated in a normal cold run, the features of host have to be a superset of a baseline target environment; otherwise the host becomes the baseline target environment. Another example is, in the second run, if the code in the SCC was generated on a machine who's features are a subset of the baseline target environment, then the AOT code should again only be targeted to use only the features specified in the SCC.

This is also relevant for JITServer, as the target of the compilation could be a machine that is different from where the compilation occurs.

<hr/>

[1] https://github.com/eclipse/openj9/blob/dc7b78cbd099a1188d018d9b43c2d4e51933d8a3/runtime/compiler/runtime/RelocationRuntime.cpp#L1022

<hr/>

1 - By "optional dynamic relocatable compilation", I mean the decision to compile some method is made at runtime (dynamic) and the decision to generate position independent code for a particular compilation (relocatable compilation) is also made at runtime (optional).

**Comment by dsouzai** [comment]
fyi @mstoodle @ymanton @vijaysun-omr

**Comment by vijaysun-omr** [comment]
Thanks, is the next step to discuss the OMR issue at an OMR architecture meeting ?

**Comment by dsouzai** [comment]
Yeah I asked that https://github.com/eclipse/omr/issues/4518 be added to the architecture meeting.

That said, after an offline discussion with @mpirvu, maybe going down that road isn't absolutely necessary. Since it isn't particularly likely that a portable SCC is not going to be in a container of some sort, Marius suggested that using an option to inform the JVM that the current run is the "populate SCC" run should be sufficient. 

Such an option would cause the global target environment to be set to some base level, which would result in even the JIT'd code targeting that arch level; however, because this run would be part of the container build step whose main purpose is to populate the SCC, it doesn't matter too much if the JIT'd code's quality isn't the best.

I think the subtleties still remain in the multi-SCC world. 

1. If an TR_AOTHeader already exists, then we need to make the base level whatever the level of the TR_AOTHeader is in the first run. 
2. We would need to prevent new AOT code from being added to the SCC in the second run unless we were certain it didn't use features that were not available when the previous SCCs were generated.

What do you think @mstoodle @ymanton ?

**Comment by dsouzai** [comment]
Closing this in favour of the discussion in https://github.com/eclipse/openj9/issues/7966
