### ISSUE TITLE
-Xtrace resume trigger does not work on all threads

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#7644]
Java -version output
--------------------

```
> jdk8u232-b09/bin/java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20191016_439 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)
```

Summary of problem
------------------

When using `-Xtrace`, according to the documentation [1] the `resume` trigger should resume tracing on all threads. However this does not seem to work. Using the following testcase and the above Java version:

```
public class Test {
    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < Integer.parseInt(args[0]); ++i) {
            foo();
            Thread.sleep(100);
        }
    }

    public static String foo() {
        try {
            throw new Exception("Test exception");
        } catch (Throwable t) {
            return t.getStackTrace()[0].toString();
        }
    }
}
```

Running with `resume` using the following command built with the option builder [2] we get nothing printed to STDERR:

```
java "-Xtrace:print=j9mm.353,resumecount=1,trigger=tpnid{j9mm.353,resume,100}" Test 40
```

However replacing `resume` with `resumethis` we do start to see printout:

```
java "-Xtrace:print=j9mm.353,resumecount=1,trigger=tpnid{j9mm.353,resumethis,100}" Test 40
```

According to the documentation `resume` is supposed to enable tracing on all threads, and `resumethis` is supposed to enable tracing only on the current thread, so I would have expected both of them to start printing trace points out. This is not the case.

[1] https://www.eclipse.org/openj9/docs/xtrace/#resume
[2] https://www.eclipse.org/openj9/tools/xtrace_option_builder.html?tracepoint_id_0=tp_dest_select_0%3Dprint%26tp_id_0%3Dj9mm.353&trigger_tracepoint_0=trig_tp_tpnid_0%3Dj9mm.353%26trig_tp_act_0%3Dresume%26trig_delay_0%3D100&buffer_size_units=k&disable_predefined=1&trace_initially_disabled=1&sleep_time=30000&buffer_size=8&dynamic_buffers=1&output_generations=1&wrap_in_quotes=1

Diagnostic files
----------------

N/A

OutOfMemoryError: Java Heap Space
---------------------------------

N/A

**Comment by keithc-ca** [comment]
I believe the behavior matches the documentation. In the table of actions for groups and tracepoint IDs, it says:

* resume - Resume all tracing (except for threads that are suspended by the action of the resumecount property and Trace.suspendThis() calls).
* resumethis - Decrement the suspend count for this thread. If the suspend count is zero or less, resume tracing for this thread.

I interpret this to mean the `resumecount=1` suboption requires use of `resumethis` to enable tracing.

If you want to use `resume` in the tpnid, you should use `suspend`, but that will enable tracing for all threads after any thread reaches the tracepoint.

**Comment by fjeremic** [comment]
Thanks for the explanation @keithc-ca. Do you think it is worth adding a warning/error in the Xtrace Option Builder to warn the user about using `resume` within a group when `resumecount=1` is active?

**Comment by fjeremic** [comment]
I see, ok I think this issue will be searchable in case anyone encounters similar issues. I don't think a change is required. Thanks for the help!
