### ISSUE TITLE
Intermittent issue with GC during idle cycle

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#7679]
This problem was reported by @siruslan on Slack https://openj9.slack.com/archives/C8312LCV9/p1571941456051800?thread_ts=1568771742.039800&cid=C8312LCV9
It appears the heap does not go down during the idle cycle when the program is sitting idle.
Code for the program is: https://github.com/jelastic/java-vertical-scaling-test/blob/514b78d07a31b79424d5889780e2c41d813efcae/src/com/jelastic/verticalscaling/Load.java#L49
During active cycle the program runs `Load.simple()` which creates a `LinkedList` of `String` array objects. After the active cycle is over, LinkedList goes out of scope and is available for garbage collection.

I ran the program multiple times and observed that once in a while idle gc cycle is not clearing the heap.
I have captured the core file, jit and gc verbose logs after the 'vm idle' gc cycle is completed.

Program output:
```
$ /home/ashu/data/builds/jdk8u232-b09/bin/java -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=1 -Xmx2G -Xjit:verbose={compilePerformance},verbose={jitState},vlog=jit.log,waitTimeToEnterDeepIdleMode=20000 -Xverbosegclog "-Xdump:system+java+snap:events=user+throw+systhrow,filter=java/lang/OutOfMemoryError,range=1..3,request=exclusive+prepwalk+serial+preempt" -jar app.jar 10 1
Press <Enter> to start the load test

03:46:42 -> Init: 8M Used: 83M Committed: 108M Max: 2048M 
03:46:45 -> Init: 8M Used: 189M Committed: 236M Max: 2048M 
03:46:48 -> Init: 8M Used: 289M Committed: 380M Max: 2048M 
03:46:51 -> Init: 8M Used: 401M Committed: 464M Max: 2048M 
03:46:54 -> Init: 8M Used: 510M Committed: 648M Max: 2048M 
03:46:57 -> Init: 8M Used: 623M Committed: 760M Max: 2048M 
03:47:00 -> Init: 8M Used: 736M Committed: 892M Max: 2048M 
03:47:03 -> Init: 8M Used: 852M Committed: 1048M Max: 2048M 
03:47:06 -> Init: 8M Used: 963M Committed: 1220M Max: 2048M 
03:47:09 -> Init: 8M Used: 1065M Committed: 1384M Max: 2048M 
total time = 32695, ms
done
03:47:12 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:15 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:18 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:21 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:24 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:27 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:30 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:33 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:36 -> Init: 8M Used: 1192M Committed: 1430M Max: 2048M 
03:47:39 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:47:42 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:47:45 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:47:48 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:47:51 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:47:54 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:47:57 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:00 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:03 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:06 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
JVMDUMP039I Processing dump event "user", detail "" at 2019/11/01 15:48:07 - please wait.
JVMDUMP032I JVM requested System dump using '/home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/core.20191101.154807.27126.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/core.20191101.154807.27126.0001.dmp
03:48:18 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
JVMDUMP032I JVM requested Java dump using '/home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/javacore.20191101.154807.27126.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/javacore.20191101.154807.27126.0002.txt
JVMDUMP032I JVM requested Java dump using '/home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/javacore.20191101.154807.27126.0003.txt' in response to an event
JVMDUMP010I Java dump written to /home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/javacore.20191101.154807.27126.0003.txt
JVMDUMP032I JVM requested Snap dump using '/home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/Snap.20191101.154807.27126.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /home/ashu/data/IBM/ashu-mehra/java-vertical-scaling-test/dist/Snap.20191101.154807.27126.0004.trc
JVMDUMP013I Processed dump event "user", detail "".
03:48:21 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:24 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:27 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:30 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:33 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:36 -> Init: 8M Used: 1189M Committed: 1617M Max: 2048M 
03:48:39 -> Init: 8M Used: 157M Committed: 1617M Max: 2048M 
03:48:42 -> Init: 8M Used: 157M Committed: 1617M Max: 2048M 
03:48:45 -> Init: 8M Used: 157M Committed: 1617M Max: 2048M 
03:48:48 -> Init: 8M Used: 157M Committed: 1617M Max: 2048M 
03:48:51 -> Init: 8M Used: 157M Committed: 1617M Max: 2048M
```

Part of the output before `done` corresponds to active cycle, and after that the program is sitting idle and just printing heap stats every 3 secs.
Once the idle cycle starts, VM goes into idle in around 25 secs (5 secs to go into idle and then 20 secs for deep idle). At this point `vm idle` gc cycle is triggered at `15:47:37861` but as can be seen in the output `Used` heap does not come down.
In normal case, after `vm idle` gc cycle `Used` heap comes down to around 150-250 mb.
Corresponding verbose gc output:
```
<exclusive-start id="1118" timestamp="2019-11-01T15:47:37.861" intervalms="25837.846">
  <response-info timems="0.076" idlems="0.076" threads="0" lastid="0000000002666200" lastname="VM Runtime State Listener" />
</exclusive-start>
<sys-start reason="vm idle" id="1119" timestamp="2019-11-01T15:47:37.861" intervalms="58190.657" />
<gc-start id="1120" type="global" contextid="1116" timestamp="2019-11-01T15:47:37.861">
  <mem-info id="1121" free="249875368" total="1499463680" percent="16">
    <mem type="nursery" free="35799808" total="328466432" percent="10">
      <mem type="allocate" free="35799808" total="164233216" percent="21" />
      <mem type="survivor" free="0" total="164233216" percent="0" />
    </mem>
    <mem type="tenure" free="214075560" total="1170997248" percent="18">
      <mem type="soa" free="202366120" total="1159287808" percent="17" />
      <mem type="loa" free="11709440" total="11709440" percent="100" />
    </mem>
    <remembered-set count="55" />
  </mem-info>
</gc-start>
<allocation-stats totalBytes="106542480" >
  <allocated-bytes non-tlh="4224" tlh="106538256" />
  <largest-consumer threadName="main" threadId="000000000257D700" bytes="106518008" />
</allocation-stats>
<concurrent-halted id="1122" timestamp="2019-11-01T15:47:37.863">
  <halted state="Complete" status="trace only" />
  <traced bytesTarget="965693607" bytesTotal="20384" bytesByMutator="8772" bytesByHelper="11612" percent="0" />
  <cards cleaned="0" thresholdBytes="27384694" />
</concurrent-halted>
<gc-op id="1123" type="rs-scan" timems="5.449" contextid="1116" timestamp="2019-11-01T15:47:37.871">
  <scan objectsFound="26" bytesTraced="2536" workStackOverflowCount="0" />
</gc-op>
<gc-op id="1124" type="card-cleaning" timems="744.445" contextid="1116" timestamp="2019-11-01T15:47:38.615">
  <card-cleaning cardsCleaned="3" bytesTraced="1082131712" workStackOverflowCount="0" />
</gc-op>
<gc-op id="1125" type="mark" timems="7.264" contextid="1116" timestamp="2019-11-01T15:47:38.623">
  <trace-info objectcount="9581" scancount="6999" scanbytes="178152" />
  <finalization candidates="10" enqueued="0" />
  <references type="soft" candidates="119" cleared="0" enqueued="0" dynamicThreshold="9" maxThreshold="32" />
  <references type="weak" candidates="16" cleared="0" enqueued="0" />
  <references type="phantom" candidates="6" cleared="0" enqueued="0" />
  <stringconstants candidates="1379" cleared="0"  />
</gc-op>
<gc-op id="1126" type="classunload" timems="0.319" contextid="1116" timestamp="2019-11-01T15:47:38.624">
  <classunload-info classloadercandidates="4" classloadersunloaded="0" classesunloaded="0" anonymousclassesunloaded="0" quiescems="0.000" setupms="0.319" scanms="0.000" postms="0.000" />
</gc-op>
<gc-op id="1127" type="sweep" timems="16.796" contextid="1116" timestamp="2019-11-01T15:47:38.641" />
<mem-info id="1128" free="252556432" total="1499463680" percent="16">
  <mem type="nursery" free="38477824" total="328466432" percent="11">
    <mem type="allocate" free="38477824" total="164233216" percent="23" />
    <mem type="survivor" free="0" total="164233216" percent="0" />
  </mem>
  <mem type="tenure" free="214078608" total="1170997248" percent="18" micro-fragmented="268" macro-fragmented="1250136">
    <mem type="soa" free="202369168" total="1159287808" percent="17" />
    <mem type="loa" free="11709440" total="11709440" percent="100" />
  </mem>
  <remembered-set count="55" />
</mem-info>
<gc-op id="1129" type="compact" timems="874.415" contextid="1116" timestamp="2019-11-01T15:47:39.516">
  <compact-info movecount="105208" movebytes="166693464" reason="forced gc with compaction" />
</gc-op>
<heap-resize id="1130" type="expand" space="tenure" amount="196018176" count="1" timems="0.034" reason="insufficient free space following gc" timestamp="2019-11-01T15:47:39.516" />
<gc-end id="1131" type="global" contextid="1116" durationms="1655.499" usertimems="4932.686" systemtimems="503.847" timestamp="2019-11-01T15:47:39.516" activeThreads="4">
  <mem-info id="1132" free="448587024" total="1695481856" percent="26">
    <mem type="nursery" free="38476384" total="328466432" percent="11">
      <mem type="allocate" free="38476384" total="164233216" percent="23" />
      <mem type="survivor" free="0" total="164233216" percent="0" />
    </mem>
    <mem type="tenure" free="410110640" total="1367015424" percent="30">
      <mem type="soa" free="396441264" total="1353346048" percent="29" />
      <mem type="loa" free="13669376" total="13669376" percent="100" />
    </mem>
    <remembered-set count="55" />
  </mem-info>
</gc-end>
<cycle-end id="1133" type="global" contextid="1116" timestamp="2019-11-01T15:47:39.517" />
<sys-end id="1134" timestamp="2019-11-01T15:47:39.517" />
<exclusive-end id="1135" timestamp="2019-11-01T15:47:39.517" durationms="1656.322" />

<heap-resize id="1136" type="release free pages" space="tenure" amount="410087424" count="1" timems="0.034" reason="idle" timestamp="2019-11-01T15:47:39.517" />
```

After the sweep cycle there is not much change in the free tenure heap. Moreover there is an expansion happening because of `insufficient free space following gc` which should not happen during 'vm idle' cycle.

Loading the core file into Eclipse Memory Analyzer, I noticed a `java.util.LinkedList` unreachable object at `0x80019090` accounting for almost 1GB of retained heap.
In normal case this would have been garbage collected during `vm idle` gc cycle.

Files: 
[jit.log.20191101.154639.27126.txt](https://github.com/eclipse/openj9/files/3799685/jit.log.20191101.154639.27126.txt)
[verbosegc.20191101.154639.27126.txt](https://github.com/eclipse/openj9/files/3799686/verbosegc.20191101.154639.27126.txt)
Link to core file https://drive.google.com/open?id=1dTGKxhovHor8LgnvDLFeTICdqtQHBQlN

**Comment by ashu-mehra** [comment]
@amicic can you please take a look at this and provide your comments.

**Comment by amicic** [comment]
Concurrent Global GC has been in progress (In this particular run, which is the variable that makes this intermittent), when idle is detected:

```
<concurrent-kickoff id="1114" timestamp="2019-11-01T15:47:11.993">
  <kickoff reason="threshold reached" targetBytes="965693607" thresholdFreeBytes="69514984"  remainingFree="69509888" tenureFreeBytes="214075680" nurseryFreeBytes="69509888" />
</concurrent-kickoff>
<exclusive-start id="1115" timestamp="2019-11-01T15:47:12.023" intervalms="2153.462">
  <response-info timems="0.051" idlems="0.051" threads="0" lastid="000000000257D700" lastname="main" />
</exclusive-start>
<cycle-start id="1116" type="global" contextid="0" timestamp="2019-11-01T15:47:12.023" intervalms="4398.657" />
<exclusive-end id="1117" timestamp="2019-11-01T15:47:12.023" durationms="0.156" />
```

It's started while app was still active, and the linked list has already been identified as live. (Not necessarily all the elements of the list have been identified as live prior to idle detection, but the root of the list for sure is).

Forced System GC will just complete the cycle (find the rest of the elements of the list) and significant memory is released.

There are two things we can do:
1) force completion of concurrent global GC by a timer - I'm not sure why it's not happening already, since we have a background GC thread that is supposed to finish the cycle, and eventually trigger final STW. Final STW is probably only triggered by allocation tax mechanism, but since allocation stops, the final STW is never triggered.
2) call another System GC (if first one lands during active Concurrent Global GC).

**Comment by amicic** [comment]
To confirm that's the source of the problem, you can run with -Xgc:noConcurrentMark (and combine with slightly  different total heap sizing, like +/- 20%)

**Comment by ashu-mehra** [comment]
@amicic Ran multiple times with `-Xgc:noConcurrentMark` and it seems to work fine so far.

**Comment by amicic** [comment]
OK, we'll have a look at this, and see if we can make the transition of Concurrent Mark to STW occur even without allocation activity, which then will almost sure make the system GC run from scratch and free the memory as expected.

**Comment by siruslan** [comment]
Some updates from my side - I tested OpenJ9 with different options:

- common: `-Xmx3g -Xms32m -XX:+UseCompressedOops` 

- option 1: `-XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=1 -Xjit:waitTimeToEnterDeepIdleMode=1000`

- option 2: `-XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=10 -Xjit:waitTimeToEnterDeepIdleMode=1000`

- option 3: `-XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=10 -Xjit:waitTimeToEnterDeepIdleMode=10000`

- option 4: `-XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle -XX:IdleTuningMinIdleWaitTime=10 -Xjit:waitTimeToEnterDeepIdleMode=10000 -Xgc:noConcurrentMark`

[Simple test](https://github.com/jelastic/java-vertical-scaling-test/blob/master/src/com/jelastic/verticalscaling/Load.java#L49) provides the following results:
<img width="761" alt="Screenshot 2019-11-13 at 13 41 03" src="https://user-images.githubusercontent.com/277990/68761413-ac6e9280-061c-11ea-904b-4da9c7375886.png">

[More advanced test](https://github.com/jelastic/java-vertical-scaling-test/blob/master/src/com/jelastic/verticalscaling/Load.java#L64):
<img width="768" alt="Screenshot 2019-11-13 at 13 43 48" src="https://user-images.githubusercontent.com/277990/68761475-ce681500-061c-11ea-9cb7-a6709f800dcd.png">
 
So, we can conclude that vertical scaling works fine at OpenJ9 and the real used resources are properly tracked at the container level. The speed of memory release depends on the specified options.

**Comment by ashu-mehra** [comment]
@siruslan thanks for running the tests and confirming the behaviour.

**Comment by ashu-mehra** [comment]
@amicic I also mentioned in my first comment: `there is an expansion happening because of insufficient free space following gc which should not happen during 'vm idle' cycle.`. Would this also be taken care of by https://github.com/eclipse/omr/pull/4564, or is it a separate issue?

**Comment by amicic** [comment]
It's a sperate issue. However, this expansion will not increase resident size - the area will be uncommited. Hence, I see it as a minor issue, not worthy of extra complications in the code.

**Comment by RSalman** [comment]
This will actually be taken care of as a result of this change

**Comment by RSalman** [comment]
The expansion was a result of the same issue since we weren't freeing any memory

**Comment by amicic** [comment]
Right, in this specific scenario, since GC freed enough memory to conform with minf critera, it will not expand.

But in general, this change will not prevent further expansions, if not enough memory is freed. Not ideal, but still relatively benign, as I already explained.

**Comment by pshipton** [comment]
Can this issue be closed? Otherwise, what is left to do, and when will it be done?

**Comment by ashu-mehra** [comment]
Yes, it can be closed.
