### ISSUE TITLE
AdoptOpenJDK ppc64le builds broken since Dec 4

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9#769]
First failing build is here: https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_ppc64le_linux/67/

```
as --noexecstack -maltivec -a64 -mppc64   --defsym TR_HOST_POWER=1 --defsym TR_HOST_64BIT=1 --defsym BITVECTOR_64BIT=1 --defsym LINUX=1 --defsym TR_TARGET_POWER=1 --defsym TR_TARGET_64BIT=1 -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr/include_core' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr/thread' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr/gc/include' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/trj9/p/' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/trj9/p' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/trj9' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr/compiler/p/' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr/compiler/p' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr/compiler' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../omr' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/..' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../codert_vm' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../gc_include' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../include' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../gc_glue_java' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../jit_vm' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../nls' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../oti' -I'/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../util' -o /home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../objs/compiler/trj9/p/runtime/ebb.o /home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../objs/compiler/trj9/p/runtime/ebb.o.s
/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/trj9/build/rules/gnu/common.mk:66: recipe for target '/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/../objs/compiler/trj9/p/runtime/ebb.o' failed
make[7]: Leaving directory '/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/vm/compiler/trj9'
Makefile:82: recipe for target 'trj9' failed
```

The failure message isn't particularly helpful :( .

Given the target that fails is one of the JIT's .spp files, my suspicion would be the following PR merged on Dec 4: https://github.com/eclipse/openj9/pull/666 . But I have trouble understsanding how the AIX build configuration files, which were the only files changed in that PR, impacted how the JIT builds on ppc linux.

Nevertheless, I've asked @alenbadel to kick off the investigation. If anyone has other suggestions for culprits, please speak up!

**Comment by zl-wang** [comment]
I didn't see why #666 can impact PPCLE build either.  But it appeared there is a problem with the PR checklist such that it were not caught if #666 would break.  The triggered CI build was only amd64 ... not testing the right stuffs (POWER .spp files handling).

**Comment by gdams** [comment]
Any progress with this? It's currently stopping us pushing nightlies out at AdoptOpenJDK

**Comment by mstoodle** [comment]
And please note that it's currently stopping AdoptOpenJDK from publishing *any* nightly build (because it has to pass on all platforms to be published)

**Comment by alenbadel** [comment]
Updating to this. 

I'm able to build successfully on Linux PPC64LE on AdoptOpenJDK when disabling freetype. (Using '--skip-freetype')
It fail when the option is not used. 

I see that AdoptOpenJDK's AIX builds also use '--skip-freetype'. 

All builds conducted internally have been passing for the week with this change. On all  Linux PPC64LE, Linux PPC64 and AIX. The OpenJ9 PPC64LE CompressedRefs which contains this commit have also been passing since this change was committed. 

Looking at OpenJ9's make files, they don't lead to me think that AIX make files and config files are being used when intentionally building on Linux PPC64LE. Therefore I think there might be a configuration issue on the AdoptOpenJDK, where freetype may not be configuring the build with the correct system details. 

I don't know if '--skip-freetype' is a suitable solution for adoptOpenJ9, let me know if it isn't. I assume it can be done since the adoptOpenJ9 AIX builds are currently using them.

**Comment by gdams** [comment]
This issue doesn't look like a freetype error to me? `--skip-freetype` is just used to fetch the system version of freetype (installed with apt) rather than downloading it at build time and making it

**Comment by alenbadel** [comment]
Attached is the successfully ran build. 
[openjdk8_ppcle.txt](https://github.com/eclipse/openj9/files/1545812/openjdk8_ppcle.txt)

**Comment by adamfarley** [comment]
This looks like the same issue, FYI, so I closed it as a duplicate:

https://github.com/eclipse/openj9/issues/797

**Comment by DanHeidinga** [comment]
The error messages in #797 may be slightly clearer:
```
... runtime/ebb.o.s: Assembler messages:
... runtime/ebb.o.s:337: Error: operand out of range (3 is not between 0 and 1)
... runtime/ebb.o.s:337: Error: missing operand
```

**Comment by alenbadel** [comment]
Running the builds locally, I do believe the builds are identical to what is being used in the failures above. They were installed using the Ansible script ubuntu.yml 

I was able to successfully build 

openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-root_2017_12_10_11_15-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64 Compressed References 20171210_000000 (JIT enabled, AOT enabled)
OpenJ9   - 1665291
OMR      - 45adab4
OpenJDK  - 2dd07a4 based on )

While on OpenJdk9 I'm failing at a point much later than what's seen in the official builds above. Past the "OpenJ9 compile complete" stage and failing at 

Creating images/jmods/java.desktop.jmod
Creating support/demos/image/applets/WireFrame/WireFrame.jar
CreateJmods.gmk:133: recipe for target '/root/abadel/workspace/openjdk-build/openjdk/build/linux-ppc64le-normal-server-release/images/jmods/java.xml.crypto.jmod' failed
make/Main.gmk:307: recipe for target 'java.xml.crypto-jmod' failed
Creating support/demos/image/jfc/SwingApplet/SwingApplet.jar
Creating support/demos/image/jfc/CodePointIM/CodePointIM.jar
Creating support/demos/image/applets/MoleculeViewer/MoleculeViewer.jar
Creating support/demos/image/jfc/TransparentRuler/TransparentRuler.jar
Creating support/demos/image/jfc/Notepad/Notepad.jar
Creating support/demos/image/jfc/SampleTree/SampleTree.jar
Creating support/demos/image/jfc/TableExample/TableExample.jar
Creating support/demos/image/jfc/FileChooserDemo/FileChooserDemo.jar
Creating support/demos/image/jfc/Metalworks/Metalworks.jar
Creating support/demos/image/jfc/Font2DTest/Font2DTest.jar

ERROR: Build failed for target 'images' in configuration 'linux-ppc64le-normal-server-release' (exit code 2) 
Stopping sjavac server

**Comment by alenbadel** [comment]
This was all because the version of the assembler "as" on the AdoptOpenJDK machines are a bit newer than the version we are using. 

It was complaining on the following instruction
cmpli 0, 3, 0

or in ebb.spp
cmpli 0,3,0

The version of the assembler we are using internally will not complain when a 32-bit context is assumed (usually an extra bit is used tell). This should be processed as a cmplwi. 

The fix should be changing the cmpli cr0, r3, 0 with cmplwi cr0,r3,0 in ebb.spp. 

Fixing and testing. Should be in by end of the day.

**Comment by alenbadel** [comment]
ETA 11:59PM EST Monday December 11. Testing issues came up.

**Comment by alenbadel** [comment]
Made all changes appropriate. All internal builds passed. 

Should be ready to merge. Please take a look to PR 801.

**Comment by alenbadel** [comment]
Verifying - I was able to run the PPCLE64 Linux builds successfully on adoptOpenJDK's machines.

**Comment by gdams** [comment]
please not that we are still seeing failures: https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_ppc64le_linux/74/console

**Comment by DanHeidinga** [comment]
@gdams That looks to be a different cause:
```
Exception in thread "main" java/lang/module/FindException: java.io.UTFDataFormatException: malformed input around byte 1587
	at jdk/internal/module/ModulePath.scan (java.base@9/ModulePath.java:255)
	at jdk/internal/module/ModulePath.scanNextEntry (java.base@9/ModulePath.java:192)
	at jdk/internal/module/ModulePath.find (java.base@9/ModulePath.java:156)
	at java/lang/module/ModuleFinder$1.lambda$find$0 (java.base@9/ModuleFinder.java:195)
	at java/lang/module/ModuleFinder$1$$Lambda$1/000000007C2D5350.run (java.base@9/Unknown Source:4294967295)
	at java/security/AccessController.doPrivileged (java.base@9/AccessController.java:638)
	at java/lang/module/ModuleFinder$1.find (java.base@9/ModuleFinder.java:196)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:146)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:218)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
make[3]: *** [/home/jenkins/workspace/openjdk9_openj9_build_ppc64le_linux/openjdk/build/linux-ppc64le-normal-server-release/images/jmods/java.xml.crypto.jmod] Error 1
```

Reopening this issue to continue to investigate the failing build.

**Comment by gdams** [comment]
This is now fixed and can be closed

**Comment by zl-wang** [comment]
this build failure appeared to be random and intermittent.  it is not related to #666 at all.
have we pinned it down why? we certainly don't want to come back to it over and over again.

**Comment by DanHeidinga** [comment]
The builds started failing when the machines were upgraded (?) / modified to use `gcc 6.3.x`.  The passing builds were on `gcc 4.8.5`.  

We'll need to work with the Adopt community to set a gcc level for ppcle or ensure that OpenJ9 builds use the older gcc level.

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_ppc64le_linux/76/console running with gcc 4.8.x

**Comment by DanHeidinga** [comment]
The build using `gcc 4.8.5` passed.  Closing this issue out.
