### ISSUE TITLE
Nashorn 15x Slower With openj9-0.17.0 Java11_vs openj9-0.17.0 Java8

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#7692]
Hello OpenJ9 community,

I have been told about a 12x performance hit impacting one of our applications when testing the same Java application built with JDK8 running with openj9-0.17.0 Java8 versus running it with openj9-0.17.0 Java11 on 64-bit Linux (CentOS 7.6).

I was surprised of this large difference, because I though that openj9 was the "main engine", and that the surrounding Java 8 vs. Java 11 would just change the set of available class libraries + more syntax sugar with Java 11.

I have a sample to reproduce this issue (don't mind the apparent uselessness of the Javascript, it's here to reproduce our issue that occurs on a more complex program).

Please note that this issue differs from #5371 because here I am not comparing HotSpot vs. OpenJ9 Nashorn performances, but OpenJ9 Java8 vs. OpenJ9 Java11 for a same VM version.

Test material
--------------

- JavascriptTest.java, link: https://github.com/avermeer/OpenJ9Issues/blob/master/Nashorn15x_Slower_WithOpenJ9_Java11_vs_OpenJ9_Java8/JavascriptTest.java
- test.js, link: https://github.com/avermeer/OpenJ9Issues/blob/master/Nashorn15x_Slower_WithOpenJ9_Java11_vs_OpenJ9_Java8/test.js

Steps to reproduce the issue
--------------------------------

1. Compile JavascriptTest.java with any JDK8 compiler
2. Run the following test with AdoptOpenJDK 8u232 with OpenJ9 and with AdoptOpenJDK 11.0.5 with OpenJ9:
     `java -cp . JavascriptTest test.js`

Sample results
------------------
On an Amazon m3.large instance (2 Core of a Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz) running CentOS 7.6:

With AdoptOpenJDK 8u232 with OpenJ9:

> [root@ip-172-31-32-163 mnt]# ./Java8u232-OpenJ9/bin/java -version
> openjdk version "1.8.0_232"
> OpenJDK Runtime Environment (build 1.8.0_232-b09)
> Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
> OpenJ9   - 77c1cf708
> OMR      - 20db4fbc
> JCL      - 97b5ec8f383 based on jdk8u232-b09)
> 
> [root@ip-172-31-32-163 mnt]# ./Java8u232-OpenJ9/bin/java -cp . JavascriptTest test.js
> 5610
> [root@ip-172-31-32-163 mnt]# ./Java8u232-OpenJ9/bin/java -cp . JavascriptTest test.js
> 5705
> [root@ip-172-31-32-163 mnt]# ./Java8u232-OpenJ9/bin/java -cp . JavascriptTest test.js
> 6038
> [root@ip-172-31-32-163 mnt]# ./Java8u232-OpenJ9/bin/java -cp . JavascriptTest test.js
> 5618
> [root@ip-172-31-32-163 mnt]# ./Java8u232-OpenJ9/bin/java -cp . JavascriptTest test.js
> 5689

=> Average 5732 ms with openj9-0.17.0 java 8

Wuth AdoptOpenJDK 11.0.5 with OpenJ9:

> [root@ip-172-31-32-163 mnt]# ./Java1105-OpenJ9/bin/java -version
> openjdk version "11.0.5" 2019-10-15
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
> Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit Compressed References 20191016_358 (JIT enabled, AOT enabled)
> OpenJ9   - 77c1cf708
> OMR      - 20db4fbc
> JCL      - 2a7af5674b based on jdk-11.0.5+10)
> 
> 
> [root@ip-172-31-32-163 mnt]# ./Java1105-OpenJ9/bin/java -cp . JavascriptTest test.js
> Warning: Nashorn engine is planned to be removed from a future JDK release
> 80557
> [root@ip-172-31-32-163 mnt]# ./Java1105-OpenJ9/bin/java -cp . JavascriptTest test.js
> Warning: Nashorn engine is planned to be removed from a future JDK release
> 89117
> [root@ip-172-31-32-163 mnt]# ./Java1105-OpenJ9/bin/java -cp . JavascriptTest test.js
> Warning: Nashorn engine is planned to be removed from a future JDK release
> 86910
> [root@ip-172-31-32-163 mnt]# ./Java1105-OpenJ9/bin/java -cp . JavascriptTest test.js
> Warning: Nashorn engine is planned to be removed from a future JDK release
> 90677
> [root@ip-172-31-32-163 mnt]# ./Java1105-OpenJ9/bin/java -cp . JavascriptTest test.js
> Warning: Nashorn engine is planned to be removed from a future JDK release
> 89783

=> Average 87408 ms with openj9-0.17.0 java 8

**Comment by pshipton** [comment]
@andrewcraik can you please take a look.

**Comment by dmitripivkine** [comment]
Most likely it is unrelated but make sense to double check: default maximum object heap size (-Xmx) has been changed from 512m in Java 8 to 25% of RAM available on machine in Java 11. If this app is sensitive somehow to object heap size so you might need to specify -Xmx value explicitly

**Comment by avermeer** [comment]
Hello @dmitripivkine ,

My test machine has 7GB RAM,  25% of this size is much higher than 512m.
I tried running the same test adding `-Xxmx=512m` option, leading to same results.

Kind regards,
Alexandre

**Comment by ashu-mehra** [comment]
@avermeer I see similar performance degradation with hotspot as well.

Java 8:
```
$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

$ java JavascriptTest test.js
2054
```

Java 11:
```
$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

$ java JavascriptTest test.js
Warning: Nashorn engine is planned to be removed from a future JDK release
51123
```

**Comment by ashu-mehra** [comment]
I guess this most likely points to something wrong with the JavaScript engine in Java 11

**Comment by andrewcraik** [comment]
We will take a look, but a few of the regular contributors / collaborators are at a conference today and tomorrow so we may not have answers for a couple of days. I would note that java 11 and java 8 have very different implementations of some core data structures and in general more use of method handles etc in the newer Java level. The performance should be good, but Java 11 has not been run as extensively as Java 8 as applications are migrating so it is possible there some things that are not optimal. Anyway we will take a look shortly - we do want to investigate these issues and fix anything obviously broke in OpenJ9

FYI @BeverlyXu could you have an initial look perhaps?

**Comment by BeverlyXu** [comment]
I was able to reproduce the problem on a Broadwell machine 

> Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                72
On-line CPU(s) list:   0-71
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
>

I used the exact same build for java8 and java11. My numbers are

> [jbench@kermit 7692]$ ./jdk8u232-b09/jre/bin/java -cp . JavascriptTest test.js
3416
[jbench@kermit 7692]$ ./jdk8u232-b09/jre/bin/java -cp . JavascriptTest test.js
2570

>[jbench@kermit 7692]$ ./jdk-11.0.5+10-jre/bin/java -cp . JavascriptTest test.js
Warning: Nashorn engine is planned to be removed from a future JDK release
48828
[jbench@kermit 7692]$ ./jdk-11.0.5+10-jre/bin/java -cp . JavascriptTest test.js
Warning: Nashorn engine is planned to be removed from a future JDK release
47277

I also tried with the latest java13 build
>openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 13 Linux amd64-64-Bit Compressed References 20191021_96 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 74a8738189 based on jdk-13.0.1+9)

I saw a slight improvement with java13 over java11, but still far from java8:
>[jbench@kermit 7692]$ ./jdk-13.0.1+9-jre/bin/java -cp . JavascriptTest test.js
Warning: Nashorn engine is planned to be removed from a future JDK release
45478
[jbench@kermit 7692]$ ./jdk-13.0.1+9-jre/bin/java -cp . JavascriptTest test.js
Warning: Nashorn engine is planned to be removed from a future JDK release
44514

Next, I'll take some profiles and look into this issue further.

**Comment by BeverlyXu** [comment]
We have looked at the perf profiles and the verbose logs, and we have a theory of where the problem might be -- we see a lot more methods being compiled at "hot" level in the slower run, and that's problematic if there is not enough re-use of these hot compiles. Our next todo is to sample the callstack and hopefully it will give us a clear caller-callee picture, so we can find out where the problem came from.

**Comment by avermeer** [comment]
Okay, but unless I am mistaking, current comments do not quite hint about why same OpenJ9 0.17.0 VM has so different behavior between java 8 vs java 11 with regard to submitted Nashorn sample.

Any idea of what might explain such difference?

**Comment by BeverlyXu** [comment]
We provided the update to let the interested parties know that we are making progress. Once our theory is confirmed, we can put in more details. We don't want to write anything prematurely, only to find it untrue later.

**Comment by avermeer** [comment]
Hello @BeverlyXu,

Do you have any update on this topic to share?
Any hope of improvement for 0.18.0 release?

Kind regards,
Alexandre

**Comment by BeverlyXu** [comment]
Hi Alexandre,
We initially thought the problem is in our inlining mechanism, that some methods should have been inlined but didn't. But a few experiments indicated that's unlikely to be the root cause. We later used the standalone jjs tool to look at the bytecode generated by the js engine, and the size of the bytecode generated by java11 is 100X larger than that of java8. This leads us to suspect that the nashorn engine itself might behave differently. We are swapping the JCL classes now, trying to prove this theory. Given the massive changes b/w these two releases, we do have lots of moving pieces, and decent amount of code to go through. Even if the root cause may not be in the JIT, we still want to help at least point you to the direction of where to raise this issue. We will let you know when we have more information. 

Cheers,
Beverly

**Comment by testn** [comment]
Is this related?

https://stackoverflow.com/questions/51601107/nashorn-performance-on-jdk-9-and-jdk-10

**Comment by BeverlyXu** [comment]
We looked further into the classes itself. Our original thought was to swap the nashorn classes b/w java8 and java11, i.e. patching the java11 jdk with java8 nashorn.jar file at runtime, but the module system prevented us from doing so. This is because in java11, the nashorn classes has dependencies on other classes. Here are a few example of such dependency from the module graph
```jdk.scripting.nashorn requires java.logging jrt:/java.logging
jdk.scripting.nashorn requires java.scripting jrt:/java.scripting
jdk.scripting.nashorn requires jdk.dynalink jrt:/jdk.dynalink
jdk.dynalink binds jdk.scripting.nashorn jrt:/jdk.scripting.nashorn
java.scripting binds jdk.scripting.nashorn jrt:/jdk.scripting.nashorn
```

So while we couldn't conclusively say that nashorn is to blame here, we are more and more convinced that's the case. We also noticed that the same regression is seen in OpenJDK. So we would recommend asking the nashorn team to take a look.

**Comment by andrewcraik** [comment]
@DanHeidinga given that this slow down happens on both JVMs this seems to be something to discuss with the Nashorn team. If we don't hear anything further, this seems like something that should be closed since it doesn't seem to be OpenJ9 specific.

**Comment by andrewcraik** [comment]
closing per previous comment given lack of activity.
