### ISSUE TITLE
rtc001 ASSERTION FAILED at compiler/runtime/IProfiler.cpp:4215

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7696]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/191
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/193
cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_0
```
Testing: rtc001
Test start time: 2019/11/05 00:43:29 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/java" -Xcompressedrefs -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation  -Xdump      -agentlib:jvmtitest=test:rtc001 -Dsun.reflect.noInflation=true  -cp "/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/openjdk-tests/TestConfig/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar:/home/jenkins/workspace/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/openjdk-tests/TestConfig/../../jvmtest/TestConfig/lib/asm-all.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 0 milliseconds
Time spent executing: 7003 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/1]:	testUnsafeAccess
 [OUT] Retransforming sun.reflect.GeneratedMethodAccessor6
 [ERR] 05:43:33.378 0x35300   j9jit.19     *   ** ASSERTION FAILED ** at /home/jenkins/jenkins-agent/workspace/Build_JDK8_ppc64le_linux_Nightly/build/linux-ppc64le-normal-server-release/vm/compiler/../compiler/runtime/IProfiler.cpp:4215: ((0 ))
 ```

https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_ppc64le_linux&TARGET=cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_0&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Nightly/195/OpenJ9-JDK8-ppc64le_linux-20191105-032027.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Nightly/195/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&JenkinsFile=openjdk_x86-64_linux_xl&TARGET=cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_0&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_xl_Nightly/197/OpenJ9-JDK8-x86-64_linux_xl-20191105-031855.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_xl_Nightly/197/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by pshipton** [comment]
I also saw this problem in a personal build on AIX yesterday (431938).
On AIX it didn't reproduce in 250 runs.

**Comment by andrewcraik** [comment]
so the assert is saying we are getting IProfiler data for a bytecode the JIT is not expecting - could someone have a look at the IProfiler buffer to see what the bytecode was that we were getting data for? Not sure how we would get such invalid data. Maybe there was a redefinition or something? Not sure but it is really a case where the JIT doesn't know what the data is.... Have there been any changes recently to IProfiling?

**Comment by pshipton** [comment]
Can't guarantee the change was introduced yesterday, but here are the changes
https://github.com/eclipse/openj9/compare/208f6de...200fc54
other components didn't change.

**Comment by DanHeidinga** [comment]
My guess is it's related to the change to stop converting invokevirtual -> invokespecial for unsafe classes.  Java 8 will now see the `invokePrivateMethod` in addition to the `initialVirtualMethod`.

Likely need a change to https://github.com/eclipse/openj9/blob/eb34cfa086458315a5842237d1c08aa2cc81e303/runtime/compiler/runtime/IProfiler.cpp#L4159 to handle `invokePrivateMethod` as well.

I'll put together a PR for that this afternoon

**Comment by DanHeidinga** [comment]
See https://github.com/DanHeidinga/openj9/pull/new/djh/iprofiler

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/192
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/194
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/190

**Comment by pshipton** [comment]
Reopening as this still occurs after #7697 as merged. The assert occurred again in the nightly build last night. The build has OpenJ9 sha 66556b4 which is the merge of #7697. 

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/193
` [ERR] 05:10:11.330 0xce6f200   j9jit.19     *   ** ASSERTION FAILED ** at /Users/jenkins/workspace/Build_JDK8_x86-64_mac_Nightly/build/macosx-x86_64-normal-server-release/vm/compiler/../compiler/runtime/IProfiler.cpp:4216: ((0 ))`

**Comment by DanHeidinga** [comment]
Opened a PR to try and make it easier to detect what's going wrong here - #7719

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/194
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/194
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/192

**Comment by pshipton** [comment]
Friday night:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/195
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/195
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/193

Saturday night:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/196
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/198
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/194

Sunday night:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_mac_Nightly/197
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/199
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/195

**Comment by DanHeidinga** [comment]
Once https://github.com/eclipse/openj9/pull/7719 is merged, it will be easier to debug the failures

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/196
`09:47:56.510778957 *0x226ae800 j9jit.48            Exception  * Unrecognized bytecode (pc=0x26017b84, bc=144) cursor 0x226bff7a in buffer 0x1 of size 1022`
@DanHeidinga

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/197

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/198

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/199

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/200
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/201

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/203

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/204

**Comment by gacholio** [comment]
> [](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-32_windows_Nightly/196)
> `09:47:56.510778957 *0x226ae800 j9jit.48 Exception * Unrecognized bytecode (pc=0x26017b84, bc=144) cursor 0x226bff7a in buffer 0x1 of size 1022`

Looked at the buffer for this one:

5c c3 df 24 01 ifnull
87 c3 df 24 00 20 ef 25 08 0b ef 25 ec 2d 79 71 invokevirtual
8e c3 df 24 00 20 ef 25 08 0b ef 25 ec 2d 79 71 invokevirtual
94 c3 df 24 00 f1 ee 25 08 0b ef 25 ec 2d 79 71 invokevirtual
ba 75 df 24 4c ea ee 25 invokespecial
c4 75 df 24 00 f3 ee 25 4c ea ee 25 ec 2d 79 71 invokevirtual
ea 91 df 24 01 ifcmplt
07 92 df 24 01 ifcmple
19 92 df 24 b0 f2 ee 25 invokestatic
cb 75 df 24 00 ifeq
d2 75 df 24 00 f3 ee 25 4c ea ee 25 ec 2d 79 71 invokevirtual
51 92 df 24 c0 f2 ee 25 invokespecial
54 91 df 24 00 ifle
64 91 df 24 00 f8 ee 25 90 f2 ee 25 ec 2d 79 71 invokevirtual
54 99 df 24 74 f6 ee 25 invokespecial
58 92 df 24 00 f8 ee 25 c0 f2 ee 25 ec 2d 79 71 invokevirtual
9b c3 df 24 00 20 ef 25 08 0b ef 25 ec 2d 79 71 invokevirtual
7a 77 df 24 00 ifeq
80 77 df 24 00 d9 6b 22 6c ea ee 25 ec 2d 79 71 invokevirtual
83 77 df 24 01 iflt
96 7d df 24 9c eb ee 25 invokespecial
29 78 df 24 7c ea ee 25 invokespecial
30 78 df 24 00 41 ef 25 7c ea ee 25 ec 2d 79 71 invokevirtual
91 3c e0 24 00 41 ef 25 ec 43 ef 25 ec 2d 79 71 invokevirtual
37 78 df 24 00 41 ef 25 7c ea ee 25 9c 43 ef 25 invokevirtual
3e 78 df 24 00 04 ef 25 7c ea ee 25 64 06 ef 25 invokevirtual
45 78 df 24 00 ifeq
4c 78 df 24 00 f3 ee 25 7c ea ee 25 c0 f2 ee 25 invokevirtual
c1 0a 03 26 8c f9 04 26 c8 0a 03 26 8c f9 04 26 invokevirtual
cd 0a 03 26 00 ff 04 26 8c f9 04 26 78 fe 04 26 invokevirtual
d4 0a 03 26 00 ae 6b 22 8c f9 04 26 ac a4 6b 22 invokevirtual
df 0a 03 26 00 6f 6d 22 8c f9 04 26 90 72 6d 22 invokevirtual
fd 4e 00 26 74 54 00 26 invokespecial
1d 4f 00 26 01 ifnotnull
29 4f 00 26 00 fd 04 26 checkcast
2d 4f 00 26 00 ifnull
35 4f 00 26 01 ifcmpeq
40 4f 00 26 00 fd 04 26 84 54 00 26 ec 2d 79 71 invokevirtual
d0 14 03 26 00 ae 6b 22 88 fc 04 26 ec 2d 79 71 invokevirtual
d6 14 03 26 00 6f 6d 22 88 fc 04 26 ec 2d 79 71 invokevirtual
e1 14 03 26 88 fc 04 26 invokespecial
a5 1d 03 26 ec ff 04 26 invokespecial
e8 14 03 26 00 6f 6d 22 invokespecial
88 fc 04 26 ec 2d 79 71 invokevirtual
75 56 00 26 74 7b 01 26 invokespecial
95 56 00 26 01 ifnonnull
a1 56 00 26 00 01 05 26 checkcast
a5 56 00 26 00 ifnull
ad 56 00 26 01 ifcmpeq
b8 56 00 26 00 01 05 26 invokespecial <- call to com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe.b()Z, returns constant
84 7b 01 26 ec 2d 79 71 <- initial virtual method
bb 56 00 26 84 7b 01 26 invokespecial <- call immediately after

The bytecodes for the two final invokespecials are:

   40 invokespecial 3 com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe.b()Z
   43 invokespecial 17 java/lang/Boolean.<init>(Z)V

The bogus entry after looks like it might have a method as data:

> !j9method 0x71792dec
J9Method at 0x71792dec {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x00000000
	0x4: class J9ConstantPool* constantPool = !j9constantpool 0x00000000
	0x8: void* methodRunAddress = !j9x 0x00000002
	0xc: void* extra = !j9x 0x00000000
}

2 is the initial virtual method. The PC does not map to a method, and does contain 0x90 (144) which is causing the assertion.

**Comment by gacholio** [comment]
This looks like confusion between invokevirtual and invokespecial - it looks like someone overwrote the bytecode after it had been profiled.

260056b8 PC
26050100 Class
26017B84 Calling method
71792DEC Target method

Searching for PC=0x260056B8 in VM=0x00F51A00...
!j9method 0x260179B4 sun/reflect/GeneratedMethodAccessor6.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
Bytecode PC offset = 0x00000028
> !bytecodes 0x260179B4
  Name: invoke
  Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
  Access Flags (1030001): public 
  Max Stack: 7
  Caught Exceptions (3):
     start   end   handler   catch type
     -----   ---   -------   ----------
     16  40  47   java/lang/ClassCastException
     16  40  47   java/lang/NullPointerException
     40  43  59   java/lang/Throwable
  Thrown Exceptions (1):
java/lang/reflect/InvocationTargetException  Argument Count: 3
  Temp Count: 0

    0 newdup 16 java/lang/Boolean
    3 dup 
    4 aload1 
    5 ifnonnull 16
    8 newdup 6 java/lang/NullPointerException
   11 dup 
   12 invokespecial 9 java/lang/NullPointerException.<init>()V
   15 athrow 
   16 aload1 
   17 checkcast 2 com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe
   20 aload2 
   21 ifnull 40
   24 aload2 
   25 arraylength 
   26 sipush 0
   29 ificmpeq 40
   32 newdup 7 java/lang/IllegalArgumentException
   35 dup 
   36 invokespecial 10 java/lang/IllegalArgumentException.<init>()V
   39 athrow 
   40 invokespecial 3 com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe.b()Z
   43 invokespecial 17 java/lang/Boolean.<init>(Z)V
   46 return1 
   47 invokespecial 15 java/lang/Object.toString()Ljava/lang/String;
   50 new 7 java/lang/IllegalArgumentException
   53 dupx1 
   54 swap 
   55 invokespecial 11 java/lang/IllegalArgumentException.<init>(Ljava/lang/String;)V
   58 athrow 
   59 new 8 java/lang/reflect/InvocationTargetException
   62 dupx1 
   63 swap 
   64 invokespecial 12 java/lang/reflect/InvocationTargetException.<init>(Ljava/lang/Throwable;)V
   67 athrow 
> !j9class 0x26050100
J9Class at 0x26050100 {
  Fields for J9Class:
	0x0: U32 eyecatcher = 0x99669966 (2573637990)
	0x4: class J9ROMClass* romClass = !j9romclass 0x26031CD0
	0x8: void** superclasses = !j9x 0x2604FCC0
	0xc: U32 classDepthAndFlags = 0x000E0001 (917505)
	0x10: U32 classDepthWithFlags = 0x00000000 (0)
	0x14: U32 classFlags = 0x00000000 (0)
	0x18: class J9ClassLoader* classLoader = !j9classloader 0x21F79FA4
	0x1c: class J9Object* classObject = !j9object 0x01790970 // java/lang/Class
	0x20: volatile U32 initializeStatus = 0x00000001 (1)
	0x24: class J9Method* ramMethods = !j9method 0x2604FFEC // com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe.<init>()V
	0x28: U32* ramStatics = !j9x 0x00000000
	0x2c: class J9Class* arrayClass = !j9class 0x00000000
	0x30: U32 totalInstanceSize = 0x00000004 (4)
	0x34: class J9ITable* lastITable = !j9itable 0x71785220
	0x38: U32* instanceDescription = !j9x 0x00000001
	0x3c: U32* instanceLeafDescription = !j9x 0x00000001
	0x40: U32 instanceHotFieldDescription = 0x00000000 (0)
	0x44: U32 selfReferencingField1 = 0x00000000 (0)
	0x48: U32 selfReferencingField2 = 0x00000000 (0)
	0x4c: class J9Method* initializerCache = !j9method 0x00000000
	0x50: U32 romableAotITable = 0x71301B20 (1898978080)
	0x54: U32 packageID = 0x260311B1 (637735345)
	0x58: class J9Module* module = !j9module 0x00000000
	0x5c: class J9Class* subclassTraversalLink = !j9class 0x2602B100 // java/util/ComparableTimSort
	0x60: class J9Class* subclassTraversalReverseLink = !j9class 0x2602B200 // java/lang/Class$ClassReflectNullPlaceHolder
	0x64: void** iTable = !j9x 0x00000000
	0x68: U32 castClassCache = 0x00000000 (0)
	0x6c: void** jniIDs = !j9x 0x226B4DE0
	0x70: U32 lockOffset = 0x00000004 (4)
	0x74: U32 newInstanceCount = 0x00000001 (1)
	0x78: I32 backfillOffset = 0x00000008 (8)
	0x7c: class J9Class* replacedClass = !j9class 0x00000000
	0x80: U32 finalizeLinkOffset = 0x00000000 (0)
	0x84: class J9Class* nextClassInSegment = !j9class 0x2604FF00 // com/ibm/jvmti/tests/util/SubTest
	0x88: U32* ramConstantPool = !j9x 0x26050010
	0x8c: void** callSites = !j9x 0x00000000
	0x90: void** methodTypes = !j9x 0x00000000
	0x94: void** varHandleMethodTypes = !j9x 0x00000000
	0x98: class J9VMCustomSpinOptions* customSpinOption = !j9vmcustomspinoptions 0x00000000
	0x9c: void** staticSplitMethodTable = !j9x 0x00000000
	0xa0: void** specialSplitMethodTable = !j9x 0x00000000
	0xa4: class J9JITExceptionTable* jitMetaDataList = !j9jitexceptiontable 0x00000000
	0xa8: class J9Class* gcLink = !j9class 0x00000000
	0xac: class J9Class* hostClass = !j9class 0x26050100 // com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe
	0xb0: class J9FlattenedClassCache* flattenedClassCache = !j9flattenedclasscache 0x00000000
}
Class name: com/ibm/jvmti/tests/retransformClasses/rtc001_testUnsafe
> !j9method 0x26017B84
J9Method at 0x26017b84 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x26005690
	0x4: class J9ConstantPool* constantPool = !j9constantpool 0x26017AE0
	0x8: void* methodRunAddress = !j9x 0x00000006
	0xc: void* extra = !j9x 0x00000001
}
Signature: sun/reflect/GeneratedMethodAccessor6.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; !bytecodes 0x26017B84
> !j9method 0x71792DEC
J9Method at 0x71792dec {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x00000000
	0x4: class J9ConstantPool* constantPool = !j9constantpool 0x00000000
	0x8: void* methodRunAddress = !j9x 0x00000002 <- initialVirtualMethod
	0xc: void* extra = !j9x 0x00000000
}

**Comment by gacholio** [comment]
When the profile was emitted, the bytecode was invokevirtual. By the time the profiler sees the method, the bytecode has been rewritten to invokespecial.

**Comment by gacholio** [comment]
@tajila said we're not doing the translation anymore, but we still appear to do it for HCR classes (for no good reason). I'm sure removing that will fix the problem.

**Comment by gacholio** [comment]
I suspect the iprofiler is running without VM access (so does not get blocked during HCR).

@mpirvu This seems like it might be an issue in the future.

**Comment by gacholio** [comment]
Part of the problem here is that the fix was applied to all affected classes, not just the ones that were explicitly redefined, so bytecodes that were not replaced were being modified.
