### ISSUE TITLE
J9::ClassEnv::enumerateFields() is not handled by JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#7724]
`J9::ClassEnv::enumerateFields()` needs a different implementation at JITServer. At the very least the JITServer should send a message to the client to populate the TR::TypeLayout info.

**Comment by a7ehuo** [comment]
I will take a look at this one.

**Comment by dmitry-ten** [comment]
I'm working on this one now.

**Comment by mpirvu** [comment]
Fixed by #11233
