### ISSUE TITLE
Priorities for project - discussion

### ISSUE THREAD

**Issue by jonathanwoodford** [eclipse/openj9#773]

**Comment by jonathanwoodford** [comment]
What enhancements / function would be of value?
Which platforms are of most interest?
...etc.

**Comment by pshipton** [comment]
Issue that should be fixed:
- #732

**Comment by pshipton** [comment]
I'm closing this since there hasn't been any discussion in this Issue. The `enhancement` label exists already https://github.com/eclipse/openj9/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement.  

There are also issues open for ARM #53 #66 #712, and Mac #36
