### ISSUE TITLE
VM native lookupJava8Package() is redundant

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7734]
In `Java 9+ --illegal-access=permit` is turned on by default. This opens each package (that existed in `Java 8`) to ALL-UNNAMED unless `illegal-access=deny` is specified. This is for easy mitigation to modularity Java levels.

There is a `jdk8_packages.dat` [1] containing such `Java 8` packages to be exported to unnamed modules. `jdk.internal.module.ModuleBootstrap.addIllegalAccess()` [2] invokes `jdk.internal.module.IllegalAccessMaps.generate()` [3] which reads/parses/saves this dat file, and calls `jla.addOpensToAllUnnamed()` [4] for each package. This leads to https://github.com/eclipse/openj9/blob/bcdabd73d29359586b2a2294f0c2b47eea9e1541/runtime/j9vm/java11vmi.c#L1130 which invokes https://github.com/eclipse/openj9/blob/bcdabd73d29359586b2a2294f0c2b47eea9e1541/runtime/j9vm/java11vmi.c#L1147 for such packages.

Hence each `J9Package->exportToAllUnnamed` is set to true, and https://github.com/eclipse/openj9/blob/bcdabd73d29359586b2a2294f0c2b47eea9e1541/runtime/util/modularityHelper.c#L205 returns true for those `jdk8` packages at https://github.com/eclipse/openj9/blob/bcdabd73d29359586b2a2294f0c2b47eea9e1541/runtime/util/modularityHelper.c#L214-L218 before hitting https://github.com/eclipse/openj9/blob/bcdabd73d29359586b2a2294f0c2b47eea9e1541/runtime/util/modularityHelper.c#L237.

It appears there is no need to perform `lookupJava8Package()` within VM natives.

@tajila any insights?

fyi @DanHeidinga 

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/jdk/internal/module/jdk8_packages.dat
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/5961cb4f17facbc7824e7550ca475916ebe93f38/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java#L743-L838
[3] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/5961cb4f17facbc7824e7550ca475916ebe93f38/src/java.base/share/classes/jdk/internal/module/IllegalAccessMaps.java#L75-L112
[4] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/5961cb4f17facbc7824e7550ca475916ebe93f38/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java#L831-L834

**Comment by tajila** [comment]
@JasonFengJ9 you are correct, `lookupJava8Package()` is not needed. I wasn't aware of `jdk8_packages.dat` at that time that native was implemented.

**Comment by tajila** [comment]
The corresponding /runtime/oti/j9java8packages.* can also be removed

**Comment by JasonFengJ9** [comment]
Thanks @tajila , will submit the PR for the removal.

**Comment by tajila** [comment]
@JasonFengJ9 There are tests in ` test/Java9andUp/src/org/openj9/test/access/staticAccessChecks/*` that ensure we have the correct behaviour regarding jdk8 packages. You can use these to verify that the `lookupJava8Package()` is no longer needed.

**Comment by JasonFengJ9** [comment]
@tajila yes, I verified that #7808 still passes those tests.
