### ISSUE TITLE
Remove assignments of FIND_ARG_IN_VMARGS inside if condition

### ISSUE THREAD

**Issue by AlenBadel** [eclipse/openj9#7746]
Per https://github.com/eclipse/openj9/issues/7667

Removing assignments inside if condition when FIND_ARG_IN_VMARGS is called. 

Eg 
https://github.com/eclipse/openj9/blob/64087aac0b0836c32ac35d503187912206a98104/runtime/shared/shrclssup.c#L60

@pshipton Suggests that assignments inside conditional braces is against the "unoffical" coding guidelines. Should this be promoted to some sort of official document? 
https://github.com/eclipse/openj9/pull/7722#discussion_r343891272

**Comment by pshipton** [comment]
It's part of the OMR coding standards, for if statements.
https://github.com/eclipse/omr/blob/master/doc/CodingStandard.md
`Never combine an assignment and a test, except in a while condition. In a while loop, always use an explicit test.`

OpenJ9 doesn't have official coding standards, but I've seen references to the OMR ones.

**Comment by pshipton** [comment]
There are a couple in shrclssup.c , one in jvminit.c , and more (8) in the JIT J9Options.cpp

**Comment by pshipton** [comment]
> Should this be promoted to some sort of official document?

The different groups of developers can't agree on a standard, I think we gave up trying to define one. We welcome anyone who wants to volunteer to try and create some standards.

**Comment by AlenBadel** [comment]
@pshipton Found the last of these calls. Once this PR is in we can close this issue. https://github.com/eclipse/openj9/pull/8589

**Comment by pshipton** [comment]
You can use https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
I've updated the PR to do so.
