### ISSUE TITLE
aix71-p8-5 to 10 needs libc++ installed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7798]
AIX Java 13 requires libc++ on the machines. 1-4 have been fine, I expect it needs to be installed on 5-10.
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.functional_ppc64_aix_Nightly/23
```
09:40:10  Run /home/u0020236/workspace/Test_openjdk13_j9_sanity.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/bin/java -version
09:40:10  libjvm.so preloadLibrary(/home/u0020236/workspace/Test_openjdk13_j9_sanity.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so): 	0509-022 Cannot load module /home/u0020236/workspace/Test_openjdk13_j9_sanity.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/l.
09:40:10  	0509-150   Dependent module libc++.a(cxxabi_64.o) could not be loaded.
09:40:10  	0509-022 Cannot load module libc++.a(cxxabi_64.o).
09:40:10  	0509-026 System error: A file or directory in the path name does not exist.
09:40:10  	0509-022 Cannot load module /home/u0020236/workspace/Test_openjdk13_j9_sanity.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/l.
09:40:10  	0509-150   Dependent module /home/u0020236/workspace/Test_openjdk13_j9_sanity.functional_ppc64_aix_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/l could not be loaded.
09:40:10  libjvm.so failed to load: j9vm29
```

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
I've set 5, 6, 8, 10 offline. 7 and 9 are still running jobs, I'll take them offline when they are done.

**Comment by jdekonin** [comment]
libc++ isn't installed on 1-4

**Comment by pshipton** [comment]
@jdekonin the jobs have been passing on the 1-4 machines. The build from the 18th was fine. I don't believe any code related to this changed.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Build-Test-JDK13/121/

**Comment by pshipton** [comment]
There is an issue about needing libc++ https://github.com/eclipse/openj9/issues/7579
Dan said: "While looking into this, I ran across this IBM APAR for AIX that provides details on how to install libc++: https://www-01.ibm.com/support/docview.wss?uid=swg1IJ12155"

**Comment by jdekonin** [comment]
Confirmed (not that it was needed) on 1-4
```
bash-4.4# lslpp -l | grep c++
  libc++.rte                16.1.0.0  COMMITTED  IBM XL C++ Runtime for AIX 7.1
```

Thanks for the link and pointer to the requirement.  I'll make sure this gets added to the Adopt playbooks too.

**Comment by jdekonin** [comment]
This gets installed via xlc16 which are installed on 1-4; 5 is also now good if you wish to test to confirm.  The others are in progress.

**Comment by pshipton** [comment]
Jenkins was restarted, all the AIX were re-enabled. I've disabled 6-10 again and left 5 enabled. If it doesn't work we'll know soon enough.

**Comment by jdekonin** [comment]
6-10 now have xlc16 and libc++.rte installed.  This issue can be closed once confirmed and/or machines are enabled. (which I need a committer to do...thanks)
