### ISSUE TITLE
Create a launcher for the JITServer process

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#7800]
Currently, JITServer is launched with a java command like this: `java -XX:StartAsJITServer  extra_JVM_args`
It may be better to create a specific launcher, called, say `jitserver`, that under the covers will invoke java with the appropriate arguments. Of course, the launcher could be invoked with any other options that openj9 recognizes. 
An example of a generic launcher can be found here: https://github.com/eclipse/openj9/blob/master/runtime/tests/redirector/genericlauncher/genlauncher.c

**Comment by mpirvu** [comment]
Attn: @ashu-mehra

**Comment by DanHeidinga** [comment]
As part of this, I would like to see the `-XX:StartAsJITServer` option removed.  The custom launcher can make calls to start the server rather than passing this option to the jvm launcher apis.

**Comment by ashu-mehra** [comment]
@DanHeidinga it is not clear what exactly the custom laucher needs to do here. Are you suggesting the custom launcher should not use the option `-XX:StartAsJITServer` when invoking `JNI_CreateJavaVM`. In that case how would the JIT start in `server` mode?

**Comment by DanHeidinga** [comment]
> Are you suggesting the custom launcher should not use the option -XX:StartAsJITServer when invoking JNI_CreateJavaVM

Correct.  The `-XX:StartAsJITServer` option is an attractive nuisance as it will encourage users to add extra options that don't make sense if calling `java` in jit server mode.

By not supporting the option, and only providing an executable, we have a better user story that clearly differentiates the server from the client.

Once `JNI_CreateJavaVM` has been called, the `jitserver` executable can make calls against that VM - either JNI style calls or lookup a particular entrypoint (`JITSERVER_xxxxxx` maybe?) or cast it appropriate and call through the J9InternalVMFunctions table

**Comment by mpirvu** [comment]
When we get back from `JNI_CreateJavaVM` has any Java code been executed?
In the current implemention the JITServer is not allowed to run any Java code. Basically the JITServer stops the VM initialization process when jitHookVMInitialized() is called.
We need to know that this is a JITServer instance very early on because we allocate our JITServer data structures differently in onLoadInternal() and aboutToBootstrap()

**Comment by ashu-mehra** [comment]
@DanHeidinga we do run Java code and methods get compiled during VM initialisation. In that case having a launcher that starts the JITServer after calling `JNI_CreateJavaVM` does not look feasible without passing a flag to indicate JIT not to compile the methods during startup, which is no different than passing `-XX:StartAsJITServer`.

**Comment by ashu-mehra** [comment]
@DanHeidinga @mpirvu any comments/suggestions on how to take it further?

**Comment by mpirvu** [comment]
Personally I don't view the existence of -XX:StartAsJITServer as a nuisance. Users don't have to know about it because it will be used under the covers by the launcher (which is a binary) and we don't have to document it.

**Comment by mpirvu** [comment]
One more thing: the launcher needs to accept options to be able to specify the JITServer port, timeout and ssl. We could filter out and reject any other options, though problem determination will be hindered.

**Comment by DanHeidinga** [comment]
After thinking further on this, and discussing with @gacholio, the right way to approach this is to avoid using `JNI_CreateJavaVM` as the `jitserver` isn't a Java VM - it, is after all, a jit server.

A better approach is to add a new exported function to the JVM named `JITServer_StartServer()` that starts the jitserver.  This can continue to be implemented in the background with the equivalent of a call to `JNI_CreateJavaVM` that passes a new "isJitServer" boolean to differentiate between the two cases.

This will allow the `jitserver` to evolve its own starting / stopping logic independent of the creating a JVM in the future.

One additional constraint on this design - we'll need to add a check that ensures we prevent a user from calling `JITServer_StartServer()` in this process if `JNI_CreateJavaVM` has already been called and vice versa.

**Comment by gacholio** [comment]
I'd be tempted to call the new function "create server" rather than "start" and let the start happen via an indirect function call from the server object (presumably it'll be like a JavaVM or JNIEnv).

**Comment by DanHeidinga** [comment]
Thanks @gacholio - update my comment to use `JITServer_CreateServer`

**Comment by ashu-mehra** [comment]
If the intention is to avoid JVM startup, then why not export `JITServer_CreateServer()` from the JIT library rather than adding it to VM, but that would imply completely decoupling JITServer from the VM.

**Comment by DanHeidinga** [comment]
> If the intention is to avoid JVM startup, then why not export JITServer_CreateServer() from the JIT library rather than adding it to VM, but that would imply completely decoupling JITServer from the VM.

My understanding, and please correct me if I'm wrong, is that the jitserver depends on VM data structures such as J9VMThread, J9JavaVM, etc so it makes sense to keep the function in the JVM library.

Longer term, I'd like to see our existing set of dlls collapsed in a much smaller set (ideally 1).

**Comment by ashu-mehra** [comment]
ok, so for now I will just add `JITServer_CreateServer()` to VM which would just be a wrapper around `JNI_CreateJavaVM` and then we can continue evolving the API to have its own course of startup.
Is that ok?

**Comment by DanHeidinga** [comment]
That sounds like the right starting point.  I'd like to see the implementation of `JNI_CreateJavaVM` be moved to a new `JNI_CreateJavaVM_impl` function that takes an additional boolean to indicate jitserver or not.  The existing code will be a passthru that passes false, the new `JITServer_CreateServer` will pass true.

**Comment by keithc-ca** [comment]
Another point to keep in mind as we head down this path of a new, but different style of launcher, is that we'll have to repeat all the special build steps that are required to build an executable (e.g. code-signing on OSX).
