### ISSUE TITLE
s390x Dockerfile cannot complete the configure step

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#7807]
Following the change from #7465 the s390x Ubuntu18 Dockerfile [1] cannot complete the configure step. There are two issues:

```
configure:30707: /usr/bin/gcc -O0 -g3   conftest.c  >&5
/usr/local/bin/../libexec/gcc/s390x-ibm-linux-gnu/7.4.0/cc1: error while loading shared libraries: libmpc.so.3: cannot open shared object file: No such file or directory
configure:30711: $? = 1
configure:30749: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "jdk8"
| #define PACKAGE_STRING "OpenJDK jdk8"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.java.net"
| #define PACKAGE_URL "http://openjdk.java.net"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:30754: error: in `/root/openj9-openjdk-jdk8':
configure:30756: error: C compiler cannot create executables
See `config.log' for more details
```

This one can be fixed by installing the package via:

```
apt-get install -y libmpc-dev
```

And the subsequent issue:

```
configure:30707: /usr/bin/gcc -O0 -g3   conftest.c  >&5
/usr/local/bin/../libexec/gcc/s390x-ibm-linux-gnu/7.4.0/cc1: error while loading shared libraries: libmpfr.so.4: cannot open shared object file: No such file or directory
configure:30711: $? = 1
configure:30749: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "jdk8"
| #define PACKAGE_STRING "OpenJDK jdk8"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.java.net"
| #define PACKAGE_URL "http://openjdk.java.net"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:30754: error: in `/root/openj9-openjdk-jdk8':
configure:30756: error: C compiler cannot create executables
See `config.log' for more details
```

This one can be fixed by introducing a symlink:

```
ln -s /usr/lib/s390x-linux-gnu/libmpfr.so.6 /usr/lib/s390x-linux-gnu/libmpfr.so.4
```

I have not checked whether Ubuntu16 is broken, and I have not checked other platforms either. @babsingh did we verify the Dockerfiles across the architectures when the original change was made? If you can list which Dockerfiles you tried with I can try the rest and verify we can still build.

[1] https://github.com/eclipse/openj9/blob/59df6b6e8655207077a333ef7ff6f7cc9fee7225/buildenv/docker/jdk8/s390x/ubuntu18/Dockerfile

**Comment by babsingh** [comment]
The changes were taken from the Dockerfile(s) used in the Jenkins builds: https://github.com/eclipse/openj9/tree/master/buildenv/jenkins/docker-slaves. I verified the generation of the Docker containers but I didn't built the full JDK in those containers. I assumed those changes should be good since they are used daily in our Jenkins builds. Referring to https://github.com/eclipse/openj9/pull/4568, I missed to include `libmpc3` on `s390x` platforms. I think `x86` and `ppc` Dockerfiles should work fine. @AdamBrousseau Can you confirm?

**Comment by fjeremic** [comment]
Shameless plug at #5781 again. We really need to deprecate one set of these Dockerfiles and just use a single set which we actually test that it is working. Here is a recent list of issues/PRs encountered every several months when something breaks:

[1] https://github.com/eclipse/openj9/issues/6995
[2] https://github.com/eclipse/openj9/issues/4208
[3] https://github.com/eclipse/openj9/pull/7159
[4] https://github.com/eclipse/openj9/pull/7185
[5] https://github.com/eclipse/openj9/issues/5238
[6] https://github.com/eclipse/openj9/issues/6998
[7] https://github.com/eclipse/openj9/issues/7036

@pshipton FYI. Should we still push towards having one set of tested Dockerfiles so we don't keep running into these issues and errors are caught at the PR level when things are changed rather than at user time when someone attempts to use the Dockerfile?

Alternatively can we add testing against the buildenv/docker/* Dockerfiles across all platforms we support to ensure they are always working?

**Comment by pshipton** [comment]
@fjeremic it is still in plan to have one set of Dockerfiles, there just are no resources to work on it atm.

**Comment by fjeremic** [comment]
> @fjeremic it is still in plan to have one set of Dockerfiles, there just are no resources to work on it atm.

Is this work tracked in #5781 still?

**Comment by pshipton** [comment]
> Is this work tracked in #5781 still?

Yes, but Keith hasn't had time to look at it recently due to higher priority issues.
