### ISSUE TITLE
Thread.suspend()/resume() deprecated for removal in Java 14

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7817]
Java 14 is deprecating Thread/ThreadGroup.suspend()/resume() for removal. OpenJ9 needs to add the deprecated flag to these methods for Java 14. 

In the future, tests which use these methods will need to be re-written or removed once the methods are removed.

    Thread.suspend()
    Thread.resume()
    ThreadGroup.suspend()
    ThreadGroup.resume()
    ThreadGroup.allowThreadSuspension(boolean)

These methods will be removed in a future release.

**Comment by DanHeidinga** [comment]
This will affect some of the DDR extensions as well, likely the timeout command

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by pshipton** [comment]
> This will affect some of the DDR extensions as well, likely the timeout command

@DanHeidinga I don't find any use of suspend/resume in OpenJ9 code. Is there anything further to do for this Issue, besides possibly warning creators of DDR extensions to avoid these deprecated APIs?

**Comment by DanHeidinga** [comment]
Turns out we removed that extension prior to open sourcing as it wasn't used.  Nothing further required here
