### ISSUE TITLE
J9vmTest_0 Expected to read shared ROMClass before j9bcu.205

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7829]
Failing in OMR acceptance build.

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_OMR/350
J9vmTest_0
+++ j9vm.test.romclasscreation.NewROMCreationAfterModifyingExistingClassTest: +++
[j9vmtest.txt](https://github.com/eclipse/openj9/files/3876289/j9vmtest.txt)

**Comment by pshipton** [comment]
@hangshao0 can you pls take a look. Note this failure is in the same test run as https://github.com/eclipse/openj9/issues/7827

**Comment by hangshao0** [comment]
```
JVMSHRC241E Error: unable to delete shared class cache file
JVMSHRC336E Port layer error code = -100
JVMSHRC337E Platform error message: (32) The process cannot access the file because it is being used by another process.
JVMSHRC430I Failed to remove current generation of shared class cache "sharedcc_LOCAL SERVICE"
...
...
ERROR: Expected to read shared ROMClass before j9bcu.205!
*** Test FAILED *** (j9vm.test.romclasscreation.NewROMCreationAfterModifyingExistingClass
```

Looking that the testing code, it expects to see j9shr.150 (Trc_SHR_RMI_storeNew_Event2) before j9bcu.205 for the same class. If not, it fails. 

This test is using a shared cache with default name, which is "sharedcc_LOCAL SERVICE". 
As I mentioned here: https://github.com/eclipse/openj9/issues/7827#issuecomment-557711083, the cache "sharedcc_LOCAL SERVICE" is left behind by a previous build and it is already 100%. No new data can be stored into this cache so we didn't see  j9shr.150.

**Comment by hangshao0** [comment]
It is more robust to use `-Xshareclasses:name=<testName>` rather than using the default name to start up this test.

**Comment by pshipton** [comment]
> It is more robust to use -Xshareclasses:name=<testName> rather than using the default name to start up this test.

I can't tell from your comment if you are fixing it, can you please create a PR to make this change.

**Comment by hangshao0** [comment]
I will fix it
