### ISSUE TITLE
JVM ignores Interrupt signal when debugger is attached

### ISSUE THREAD

**Issue by prakaashkpk** [eclipse/openj9#785]
JVM tends to ignore interrupt signal received by a thread when debugger is attached. 

See the following test case
```
public class ThreadTest {
    public static void main(String[] args) throws InterruptedException {
        long start=System.currentTimeMillis();
        Thread.currentThread().interrupt();
        try {
            Thread.sleep(20000L);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        System.out.println("Time: " + (System.currentTimeMillis() - start) + " ms");
    }
}
```

Test 1(Without JDB attached):
```
$ java ThreadTest
Interruptting
> Thread enterring sleep for 3 Seconds
Exception in thread "main" java.lang.InterruptedException
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:909)
	at ThreadTest.main(ThreadTest.java:8)
```

Test 2(With JDB attached):
```
$ java -agentlib:jdwp=transport=dt_socket,server=y,address=12345 ThreadTest
Listening for transport dt_socket at address: 12345
Interruptting
> Thread enterring sleep for 3 Seconds
< Thread Sleeping end
Time: 9789 ms
```

Test 2 didn't throw InterruptedException when JDB is attached and stepped through code.

**Comment by DanHeidinga** [comment]
Marking this as high priority as it affects users ability to debug their code.

**Comment by prakaashkpk** [comment]
Any progress on this ?

**Comment by pdbain-ibm** [comment]
Working on it now...

**Comment by pdbain-ibm** [comment]
@prakaashkpk I'm having trouble reproducing your issue.  Could you send me more detail on reproducing this? 

Testing with:
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.openj9.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171225_374449 (JIT enabled, AOT enabled)
OpenJ9   - 4f77dce
OMR      - 9beb3de
OpenJDK  - f1a22d1 based on jdk-9+181)

I ran:
$ java -agentlib:jdwp=transport=dt_socket,server=y,address=12345 ThreadTest & jdb -attach 12345
[1] 31422
Listening for transport dt_socket at address: 12345
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
Initializing jdb ...
VM Started: No frames on the current call stack
main[1] main[1] stop at ThreadTest:3
Deferring breakpoint ThreadTest:3.
It will be set after the class is loaded.
main[1] next
> Set deferred breakpoint ThreadTest:3
Breakpoint hit: "thread=main", ThreadTest.main(), line=3 bci=0
3            long start=System.currentTimeMillis();
main[1] !!
next
> 
Step completed: "thread=main", ThreadTest.main(), line=4 bci=4
4            Thread.currentThread().interrupt();
main[1] !!
next
> 
Step completed: "thread=main", ThreadTest.main(), line=6 bci=10
6                Thread.sleep(20000L);
main[1] !!
next
> 
Step completed: "thread=main", ThreadTest.main(), line=7 bci=19
7            } catch (InterruptedException e) {
main[1] !!
next
> 
Step completed: "thread=main", ThreadTest.main(), line=9 bci=20
9                e.printStackTrace();
main[1] !!
next
java.lang.InterruptedException
	at java.lang.Thread.sleep(java.base@9-internal/Native Method)
	at java.lang.Thread.sleep(java.base@9-internal/Thread.java:965)
> 	at ThreadTest.main(ThreadTest.java:6)
Step completed: "thread=main", ThreadTest.main(), line=11 bci=24
11            System.out.println("Time: " + (System.currentTimeMillis() - start) + " ms");
main[1] !!
next
Time: 11007 ms
> 
Step completed: "thread=main", ThreadTest.main(), line=12 bci=55
12        }
main[1] !!
next
> 
The application exited
[1]+  Done                    java -agentlib:jdwp=transport=dt_socket,server=y,address=12345 ThreadTest

**Comment by pdbain-ibm** [comment]
Tested OpenJ9 Java 9 on Linux X86 Redhat 7 and Ubuntu 14.  Passed.
Tested same platforms, Java 7.1 (IBM J9 VM (build 2.7, JRE 1.7.0 Linux amd64-64 Compressed References 20161004_321107). Test failed.
Tested Java 8 with jvm.28 (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170608_351672).  

There appears to be a difference between the jvm.29 and jvm.28 VMs in this regard.  Investigating.

**Comment by pdbain-ibm** [comment]
Looking at the Java 8 backtrace:
#0  monitor_wait_original (self=0x7ffff0007600, monitor=0x7ffff004e7a0, millis=0, nanos=0, interruptible=8396800) at ../omr/thread/common/j9thread.c:4140
#1  0x00007ffff5ace606 in monitor_wait (monitor=0x7ffff004e7a0, millis=0, nanos=0, interruptible=8396800) at ../omr/thread/common/j9thread.c:4085
#2  0x00007ffff5ace541 in j9thread_monitor_wait_interruptable (monitor=0x7ffff004e7a0, millis=0, nanos=0) at ../omr/thread/common/j9thread.c:4015
#3  0x00007fffee7bc8d6 in jvmtiRawMonitorWait (env=0x7ffff0066d28, monitor=0x7ffff004e7a0, millis=0) at jvmtiRawMonitor.c:179
#4  0x00007fffed91c5c4 in jdwp::AgentMonitor::Wait(long long) const () from /team/pdbain/vm/test/jvmxa6480_28/jre/lib/amd64/libjdwp.so
#5  0x00007fffed922ce2 in jdwp::EventDispatcher::PostEventSet(JNIEnv_*, jdwp::EventComposer*, jdwpEventKind) ()
   from /team/pdbain/vm/test/jvmxa6480_28/jre/lib/amd64/libjdwp.so
#6  0x00007fffed93469e in jdwp::RequestManager::HandleSingleStep(_jvmtiEnv*, JNIEnv_*, _jobject*, _jmethodID*, long long) ()
   from /team/pdbain/vm/test/jvmxa6480_28/jre/lib/amd64/libjdwp.so
#7  0x00007fffee7af051 in jvmtiHookSingleStep (hook=0x7ffff7f54280, eventNum=50, eventData=0x7ffff6cb3670, userData=0x7ffff0066d28) at jvmtiHook.c:911
#8  0x00007ffff58bfbef in J9HookDispatch (hookInterface=0x7ffff7f54280, taggedEventNum=50, eventData=0x7ffff6cb3670) at ../omr/hookable/hookable.cpp:176
#9  0x00007ffff5d23cbe in VM_DebugBytecodeInterpreter::singleStep (this=0x7ffff6cb3780, _sp=@0x7ffff6cb36f0: 0x6bf668, 

monitor_wait_original() clears the J9THREAD_FLAG_INTERRUPTED flag and returns J9THREAD_INTERRUPTED.

**Comment by pdbain-ibm** [comment]
Note that IBM Java 8 and below uses the Harmony JDWP, while OpenJ9 and IBM Java 9 use the OpenJDK version.
Tested with IBM Java 9, but it throws an exception:
$ jdb -attach 5678
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
	at java.net.Socket.connect(Socket.java:546)
	at com.sun.tools.jdi.SocketTransportService.attach(SocketTransportService.java:222)
	at com.sun.tools.jdi.GenericAttachingConnector.attach(GenericAttachingConnector.java:116)
	at com.sun.tools.jdi.SocketAttachingConnector.attach(SocketAttachingConnector.java:90)
	at com.sun.tools.example.debug.tty.VMConnection.attachTarget(VMConnection.java:349)
	at com.sun.tools.example.debug.tty.VMConnection.open(VMConnection.java:159)
	at com.sun.tools.example.debug.tty.Env.init(Env.java:55)
	at com.sun.tools.example.debug.tty.TTY.main(TTY.java:1045)

**Comment by pdbain-ibm** [comment]
Tested with OpenJ9 Java 8, also passed.

**Comment by pdbain-ibm** [comment]
[testfiles.zip](https://github.com/eclipse/openj9/files/1635316/testfiles.zip)
These are the files I used to test.  Run the test like so:
$ bash runt

**Comment by pdbain-ibm** [comment]
As this is not an issue with OpenJ9, please close this issue.

**Comment by prakaashkpk** [comment]
Closing this issue as it doesn't occur with OpenJ9. 
Thanks @pdbain-ibm for the help.
