### ISSUE TITLE
Remove java.logging from j9jcl's java.management classes

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#786]
If we can remove the "requires java.logging" from the j9jcl java.management's module-info.java.extra file (along with the need for it), then we won't need the Extensions changes to GenModuleInfoSource.java anymore.

Additionally:

I explored the possibility of contributing the GenModuleInfoSource.java changes to the OpenJDK community. They responded by reiterating that the code is intended to be used only for platform-specific module-info.java changes, and that they agreed at the file's creation that module dependencies should not change between platforms. So this functionality should not be here. This leads me to conclude that is is OpenJ9 that should change, and Dan Heidinga also thinks this.

**Comment by DanHeidinga** [comment]
Links to the OpenJDK discussion about @adamfarley's proposed patch.  Please note these are direct links to OJDK mailing lists:
http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-December/013403.html
http://mail.openjdk.java.net/pipermail/core-libs-dev/2017-December/050364.html

Given the discussion from OJDK that they've deliberately avoided adding this capability, OJ9 should look at other ways to access "java.logging".

Maybe using Class.forName or equivalent to look up the classes at runtime?  More investigation required.

**Comment by DanHeidinga** [comment]
Marking this as medium priority as it reduces the # of patches required by OpenJ9.

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this?

**Comment by adamfarley** [comment]
Thanks @theresa-m :)
