### ISSUE TITLE
AdoptOpenJDK AIX build broken today

### ISSUE THREAD

**Issue by mstoodle** [eclipse/openj9#787]
https://ci.adoptopenjdk.net/blue/organizations/jenkins/openjdk8_openj9_build_ppc64_aix/detail/openjdk8_openj9_build_ppc64_aix/20/pipeline/

Previous build (yesterday) passed.

Build fails here (hard to tell from the output what is running, but presuming others will be familiar with this part of the output:
```
Creating file oti/jilvalues.m4

    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.


m4:pnathelp.m4:phelpers.m4:330 more than 4096 bytes of argument text
<looks like contents of the file pasted>
```

Weird thing is that those two files mentioned (pnathelp.m4, phelpers.m4) haven't changed since the initial OpenJ9 contributions 2 months ago (and probably for longer than that)...

**Comment by DanHeidinga** [comment]
We use M4 to preprocess handwritten files into assembly code.  Any of the `XXnathelp.m4` files are platform-specific versions of native helpers aka methods provided by the VM for the JIT to call at runtime.

Looking at the build history https://ci.adoptopenjdk.net/blue/organizations/jenkins/openjdk8_openj9_build_ppc64_aix/activity shows that it fails on `build-osuosl-ppc64-aix-71-1` but passes on `build-osuosl-ppc64-aix-71-2`.

I wonder if there are different versions of M4 installed on the passing vs failing machines.  Does anyone (@mstoodle @jdekonin @smlambert others?) have access to the machines to check the version of M4?

**Comment by mstoodle** [comment]
Thanks @DanHeidinga .

I have asked George Adams to respond to that question; I think he's most familiar with their setups.

**Comment by jdekonin** [comment]
Both machines appear to be running the default /usr/bin/css/m4 as installed with the level of operating system.  I am not sure how to detail which package installs it on AIX; 'm4 --version' doesn't work.  

On the system I use to compile its 'GNU M4 1.4.6'.

**Comment by DanHeidinga** [comment]
As the current machines aren't controlled by Ansible (yet), George has copied the `m4` from the working machine to the other machine and launched a build: https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_ppc64_aix/48/console

We'll know soon enough whether that's the issue or not.

**Comment by DanHeidinga** [comment]
Copying `m4` wasn't sufficient.  George has installed GNU m4 v.1.4.17 and launched a new test build: https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_ppc64_aix/21/console

**Comment by DanHeidinga** [comment]
Installing GNU m4 seems to have done the trick.  I'll close this out once the build completes.

Many thanks to George for helping us track this down!

**Comment by gdams** [comment]
This can be closed now. Both jdk8 and jdk9 are passing again

**Comment by mstoodle** [comment]
Thanks everyone!
