### ISSUE TITLE
OpenJ9 JIT should finally concede that the value of NULL == 0

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#7870]
I discovered that there are still places in the JIT that either assert or check that the value of NULL expected by the JIT is zero.  You can find these by grepping for `NULLVALUE`.

These are remnants of some of the earliest amoeba-like code in Testarossa when, strangely enough, the "NULL" value in J9 at the time wasn't zero.  Given that nearly 20 years has passed when the value was fixed at zero and the fact that many places already assume it to be zero without checking, the "NULL" value is unlikely to be changed any time soon.

The task here is to sweep through the compiler code and deprecate uses of `NULLVALUE` assuming the value to be zero.  Fold or delete code as necessary.

**Comment by 0xdaryl** [comment]
Editor's note: `NULL` in this context is the value of Java's NULL as represented in the JVM, not the C++ `NULL`.

**Comment by rohitp27** [comment]
@0xdaryl 
I'd like to take this up if someone's not already working on it. Could you point me towards local build instructions if available to test before making the PR?

**Comment by 0xdaryl** [comment]
Thanks for your offer @rohitp27.  I'm not aware of anyone taking this on, so please feel free to make this your first contribution.

You can find instructions for building OpenJ9 here -> https://www.eclipse.org/openj9/oj9_build.html

Please also read through the Contribution Guidelines to get started -> https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md

**Comment by rohitp27** [comment]
Thanks. Will get started.

**Comment by rohitp27** [comment]
@0xdaryl 

Hey, I was wondering about the source of the UPPER_IMMED and LOWER_IMMED constants. If I understand correctly they are the lower and upper bounds for what can be stored in the registers. Maybe I'm missing something.

Could you point me to a resource I could use to find the right answer? Apologies if this is a noob question.
