### ISSUE TITLE
Turn off OMR promote_merge tags

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7902]
We should turn off the promote_merge tagging for OMR promotion. They just create a lot of noise, I don't believe we've ever needed to use these tags. Some promotes I do manually, all of them lately, and these don't get any tags.

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by DanHeidinga** [comment]
Agreed.  They aren't used and generate a lot of noise in the tags of the repo.
