### ISSUE TITLE
Add MALLOCOPTIONS=multiheap,buckets to AIX Java Launcher

### ISSUE THREAD

**Issue by ashbm5** [eclipse/openj9#7908]
Investigations into performance problems in cryptographic operations that use OpenSSL indicate that AIX performs poorly for multi-threaded crypto operations due to malloc behavior. This issue can be mitigated by setting `export MALLOCOPTIONS=multiheap,buckets` in the command line.

Would like to have that option set by the Java Launcher at start up so that the customer doesn't have to set it manually to get the performance benefits.

FYI @pshipton @zl-wang

**Comment by pshipton** [comment]
This seems the appropriate place.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/680fa0e62db685d579f625bc2369be784983922e/jdk/src/solaris/bin/java_md_solinux.c#L353

We will of course have to create JVMs with and without the environment variable set and do a performance comparison to see what else is affected.

**Comment by pshipton** [comment]
Actually, this seems a better place
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/680fa0e62db685d579f625bc2369be784983922e/jdk/src/share/bin/java.c#L650

**Comment by DanHeidinga** [comment]
@ashbm5 Have you been able to start on the patch as suggested by Peter in the previous comment?

**Comment by DanHeidinga** [comment]
@pshipton included a link to the right location to modify the launcher code in https://github.com/eclipse/openj9/issues/7908#issuecomment-559607808

If you can get an initial patch together that modifies that function, we can help tune the implementation through reviews.

**Comment by shanchao95** [comment]
/ibmruntimes/openj9-openjdk-jdk8#366

**Comment by keithc-ca** [comment]
Where are the malloc calls? Can we arrange to reuse allocated blocks more effectively avoiding the performance problem?

**Comment by zl-wang** [comment]
> Where are the malloc calls? Can we arrange to reuse allocated blocks more effectively avoiding the performance problem?

relevant to this PR,  malloc/free calls are inside OpenSSL code.  How to reuse? thread-private memory is a potential solution.  Even with that, you probably need to prepare for bigger re-allocations if they were needed. All nitty gritty loose ends to tie up, associated with that. The ultimate question is:  who can do it and is willing to do it?  And, eventually whether the (platform specific and unique) solution is acceptable to the community.

**Comment by keithc-ca** [comment]
I was thinking along the lines of the reuse that happens in [1] which would benefit all platforms.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/closed/adds/jdk/src/share/classes/sun/security/provider/NativeDigest.java

**Comment by pshipton** [comment]
Note https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/366 is opened to address adding MALLOCOPTIONS

**Comment by zl-wang** [comment]
That doesn't look like reuse to me. Maybe you can have multiple objects of that type.  In any case, it is irksome to see that many synchronized methods.

**Comment by zl-wang** [comment]
@pshipton  I supposed this trickles into both JDK build, but I heard OpenJ9 build didn't have LDR_CNTRL set (to use 64KB pages everywhere on AIX).  I assumed it is set in the same place.

**Comment by pshipton** [comment]
We were setting LDR_CNTRL, but it was removed https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/237 as it seemed to be causing problems on the OpenJ9 AIX machines.

We are setting the base text/data load address https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/349

**Comment by zl-wang** [comment]
I didn't mean the build process, but JDK runtime to use 64KB pages, similar to this PR's MALLOCOPTIONS.  e.g.

setenv("LDR_CNTRL", "TEXTPSIZE=64K@DATAPSIZE=64K@STACKPSIZE=64K", ..);

Something like that.

**Comment by pshipton** [comment]
Can you get somebody to open a PR with this change please.

**Comment by zl-wang** [comment]
yes sure, but I need some clarifications.  I am somewhat confused as earlier indicated.
that 64KB page thing (LDR_CNTRL) was done since java6 sr5 on AIX.  if this MALLOCOPTIONS stuff were meant to be in both JDK builds (assuming it is done in the same place as LDR_CNTRL), it should be already there.  that is the point I tried getting at. However, I heard OpenJ9 build didn't use 64KB pages at runtime (it could be due to overall OS setting).  That is where I got confused.

If LDR_CNTRL is not in OpenJ9 build at all, it means there is a separate file for [the other JDK] setting it. I can open an issue to get this done in OpenJ9 side in that case.

**Comment by pshipton** [comment]
The OpenJ9 builds use the source at https://github.com/ibmruntimes/openj9-openjdk-jdk8. There is no mention of LDR_CNTRL or MALLOCOPTIONS in this source. It's a copy of the OpenJDK code, with a small number of patches to support OpenJ9 and some performance enhancements. 

This is different from IBM Java builds which use private source. I'm not sure what this source does, it could very well set LDR_CNTRL and MALLOCOPTIONS.

**Comment by zl-wang** [comment]
Thanks for the clarification.  MALLOCOPTIONS has never been set in either.
It looks like:
1) we need another PR to get MALLOCOPTIONS into IBM java;
2) yet another PR to get LDR_CNTRL to be added here for OpenJDK;

**Comment by pshipton** [comment]
Adding MALLOCOPTIONS was completed, although it caused #8842 and the setting is being modified to `MALLOCOPTIONS=multiheap`.

https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/366
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/272
https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/21
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/175
