### ISSUE TITLE
CMake does not properly find NASM on osx

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#7933]
For whatever reason, when searching for the NASM executable, CMake ignores `PATH` and only searches a fixed set of directories. This means that if you have an alternate version of NASM on the path, it will be ignored, and the system NASM will be used.  To make matters worse, the system nasm appears to be incompatible with cmake, as it does not recognize  'macho64` as a valid output format (it only has `macho`) .

As a workarround `EXTRA_CMAKE_ARGS="-DCMAKE_ASM_NASM_COMPILER=/path/to/nasm"` can be specified on the openjdk make command line

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
Is this an issue for a Java versions? My macbook, for example, is running Catalina 10.15.1 which only supports 64-bit code so `macho64` should be the only valid output format (and probably redundant). Java8 must be built on an older version of OSX: does this apply only in that case (where both 32-bit and 64-bit binaries are supported)?

**Comment by dnakamura** [comment]
Issue has been resolved by having the openjdk  build scripts pass in the path to nasm

**Comment by keithc-ca** [comment]
e.g. https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/190 and friends
