### ISSUE TITLE
JEP 359: Records preview

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#7945]
This JEP includes OpenJ9 support for the `record` class attribute and JCL methods that will access this information. See links for more information:
https://openjdk.java.net/jeps/359
http://cr.openjdk.java.net/~gbierman/jep359/jep359-20191125/specs/records-jvms.html
http://cr.openjdk.java.net/~iris/se/14/build/latest/api/java.base/java/lang/Class.html#getRecordComponents()

---

**Related pull requests:**

(APPROVED) cfdumper: https://github.com/eclipse/openj9/pull/8391
(MERGED) Class.getRecordComponents + tests + classformat tests: https://github.com/eclipse/openj9/pull/8351
(MERGED) TKG update for asm 7.3: https://github.com/eclipse/openj9/pull/8200
(MERGED) VM support and Class.isRecord: https://github.com/eclipse/openj9/pull/8061

All progress: https://github.com/theresa-m/openj9/tree/records

---

**VM changes:**
- [x] record flag as part of `J9ROMClass:extraModifiers`. If a record attribute is found in the class file, the flag should be set.
- [x] record attribute vm
  - [x] add component information to `J9ROMClass:optionalInfo` (ROMClassWriter)
  - [x] ClassFileOracle: walk attributes, store record information for ROMClassWriter
  - [x] static verification in cfreader
  - [x] record attribute structure information to cfr.h
- [x] cfdumper (ClassFileWriter, main, romclasswalk)
- [x] record class restrictions from JEP:
  - [x] records cannot be abstract
- [x] ~~DDR support~~ (attribute information not displayed)

**JCL support:**
- [x] new `java.lang.Class` method `isRecord` 
- [x] new `java.lang.Class` method `getRecordComponents`
- [x] native stubs (JVM_GetRecordComponents and JVM_IsRecord, renaming to keep consistent with java.lang.Class natives)

**Testing:**
- [x] functional tests for new `java.lang.Class` methods (set --enable-preview in build/playlist files)
  - [x] `isRecord` tests
  - [x] simple `getRecordComponents` tests
  - [x] `getRecordComponents` tests with bytecode manipulation _(ASM 7.3 has record support)_
- [x] class file verification tests for records tried the following based on spec/jep: _(tests with strikethrough saved in my `records_verificationtests` branch in case they are needed later)_
  - [x] ~~no more than one record attribute per class~~ _(not in RI implementation)_
  - [x] ~~record classes must be final~~ _(not in RI implementation)_
  - [x] record classes  cannot be abstract
  - [x] ~~There may be at most one of each of the 3 attribute types in a record_component_info structure~~ _(not in RI implementation)_
  - [x] ~~cannot declare any instance fields that are not components~~ _(not in RI implementation)_
- [x] cfdumper tests (manually - see pull request for details)
- [x] ~~ddr tests~~ (attribute information not displayed)

**Comment by JasonFengJ9** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/87/tapResults/
```
===============================================
Running test cmdLineTester_libpathTestRtf_0 ...
===============================================
cmdLineTester_libpathTestRtf_0 Start Time: Sun Dec  8 08:01:41 2019 Epoch Time (ms): 1575806501023
variation: NoOptions
JVM_OPTIONS: -Xcompressedrefs 
Parsing exclude list...
  add excludes for [all]
  add excludes for [linux_x86-64_cr]
DONE in 0 ms.
*** Starting test suite: LIBPATH Rtf test intended for PMR56610 (CMVC 201272) ***
Testing: PMR testcase with Rtf/RtfChild involved
Test start time: 2019/12/08 08:01:42 Atlantic Standard Time
Running command: /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/openjdkbinary/j2sdk-image/bin/java -Xcompressedrefs -Dcom.sun.management.jmxremote -cp /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/libpathTest/libpathTest.jar org.openj9.test.libpath.Rtf /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/openjdkbinary/j2sdk-image/bin/java /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_x86-64_linux_OpenJDK/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/libpathTest/libpathTest.jar
Time spent starting: 102 milliseconds
Time spent executing: 1156 milliseconds
Test result: FAILED
Output from test:
 [ERR] Exception in thread "main" java/lang/InternalError: Compile stub invoked! For JEP 359 support see https://github.com/eclipse/openj9/pull/7946
 [ERR] 	at java/lang/Class.isRecord (java.base@9/Class.java:4466)
 [ERR] 	at java/io/ObjectStreamClass.isRecord (java.base@9/ObjectStreamClass.java:484)
```

**Comment by theresa-m** [comment]
Issues with setting `isRecord` to false to fix this? Otherwise `isRecord` support should be ready early this week.

**Comment by DanHeidinga** [comment]
> Issues with setting isRecord to return false to fix this?

That seems like a reasonable way to stub it, as long as the proper fix is coming very quickly

**Comment by theresa-m** [comment]
pr for isRecord returning false: https://github.com/eclipse/openj9/pull/8030

**Comment by theresa-m** [comment]
PR with vm changes and Class.isRecord implementation: https://github.com/eclipse/openj9/pull/8061

**Comment by adam-thorpe** [comment]
Excluded a bunch of `java/io/Serializable/records` until this is fully implemented

**Comment by theresa-m** [comment]
Thanks @adam-thorpe I've confirmed that those tests should be passing when https://github.com/eclipse/openj9/pull/8351 is merged
