### ISSUE TITLE
Function Support library for BigInteger and BigDecimal: StrictBigNumberMath

### ISSUE THREAD

**Issue by PowerUser1234** [eclipse/openj9#795]
**The way things are with java's included libraries at the moment has it that there isn't a numberStrictMath class for BigInteger and BigDecimal.**

There needs to be, so that users can perform non-integer exponentiation, for the nth root, where n
is an integer or a rational number. It should also probably include a square root.  It should include a method to calculate Euler's constant (e) to BigInteger decimal places.

It needs to include sin, cos, tan, asin, acos, atan (obverse and inverse) trignometry.
There should be these 6 trigonometry methods, but with degree versions and radians versions,
for 12 such methods in the end.

And of course there needs to be a pi calculator, for BigInteger decimal places.  The methods
all need to be static as well, for static importing.

**Comment by pshipton** [comment]
Similar to #794 - If you're concerned that the Java language itself is remiss in not supporting more flexible operations then this is not the right forum to report that. Rather, I encourage you to submit a Java Specification Request (JSR) as part of the Java Community Process (at https://jcp.org) to describe your proposal, motivations, and expected outcome. This will be reviewed and evaluated by the Java community. That is the proper procedure for influencing changes in the Java language itself, and should they be accepted the OpenJ9 project will implement them as any compliant JVM would.
