### ISSUE TITLE
openjdk11 acceptance can't find test jobs for new platforms

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7970]
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_ppc64le_linux_xl/31
`ERROR: No item named Test_openjdk11_j9_sanity.functional_ppc64le_linux_xl_OpenJDK11 found`

https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK11_s390x_linux_xl/29
`ERROR: No item named Test_openjdk11_j9_sanity.functional_s390x_linux_xl_OpenJDK11 found`

**Comment by pshipton** [comment]
@llxia @AdamBrousseau

**Comment by AdamBrousseau** [comment]
The test jobs are autogenerated so that would indicate the test autogen job has been failing.
Likely due to script approvals which Shelley mentioned yesterday. 
https://ci.eclipse.org/openj9/job/Test_Job_Auto_Gen/
Appears the last one passed so it's probably resolved now if you relaunch.

**Comment by llxia** [comment]
yes, we updated the script yesterday. It looks like the auto gen job was triggered before the script got approved. As mentioned above, please try again.

**Comment by pshipton** [comment]
Started a new build https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OpenJDK11-Acceptance/45/

**Comment by pshipton** [comment]
The re-run worked as expected.
