### ISSUE TITLE
Install CMake on OSX machines

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#7980]

**Comment by dnakamura** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Any particular version? Or is the one installed via homebrew fine? Will this be required for OMR OSX machines as well?

I just added cmake via brew on osx1011-x86-1 and its v3.15.5.

**Comment by DanHeidinga** [comment]
@dnakamura Is there a minimum required version of cmake?  I had thought zOS had the oldest version and so set the minimum but I can't find it written down anywhere

**Comment by dnakamura** [comment]
@DanHeidinga yes zos is our oldest cmake at 3.4. ( I do have a port of 3.9.x but its not particularly well tested)

**Comment by DanHeidinga** [comment]
> Any particular version? Or is the one installed via homebrew fine?

It's newer than the minimum version.  @dnakamura Are you aware of any incompatibilities between 3.4 and 3.15?  Is @jdekonin good to proceed with rolling this out to the remaining machines?

**Comment by dnakamura** [comment]
Cmake is generally pretty good about incompatibilities.  If behaviour of an existing feature is changed, they introduce a new flag for it (which will be set to off via `cmake_minimum_required()`). The only thing that tends to bite you is inadvertently using new functionality

**Comment by rajdeepsingh1** [comment]
CMake v3.17 has been installed on all OSX machines:
```
   osx1011-x86-1 (upgrade from v3.15to v3.17))
   osx1011-x86-2
   osx1013-x86-3 - upgraded from v3.12 to v.315
   osx1013-x86-4 - upgraded from v3.12 to v.315
   osx1014-x86-1
   osx1014-x86-2
   osx1014-x86-3

**Comment by jdekonin** [comment]
@DanHeidinga this work was completed by @rajdeepsingh1.  This issue can be closed.
