### ISSUE TITLE
All UNB x and p machine offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8017]
`ssh: Could not resolve hostname cent6-x64-2: Name or service not known`

**Comment by pshipton** [comment]
@jdekonin 
Not sure if this is expected downtime?

**Comment by jdekonin** [comment]
Definitely not expected downtime.  Any maintenance would be well advertised.  Everything seems to be online at the moment.

**Comment by pshipton** [comment]
@jdekonin This is happening again. We'll see how it looks in the morning.

**Comment by jdekonin** [comment]
Seems DNS isn't working again.  @Rajdeepsingh1 and I have updated all machines in the `/etc/hosts`, so everything but cent6-x64-1 is online again.

reminder cent6-x64-1 is being rebuilt.
