### ISSUE TITLE
Class.forName method allows to create invalid arrays

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#802]
Accordingly to The Java Virtual Machine Specification (4.4.1 The CONSTANT_Class_info Structure), "An array type descriptor is valid only if it represents 255 or fewer dimensions". But using the following program it is possible to circumvent that rule:

public class A {

	public static void main(String[] args) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 256; i++) {
            sb.append('[');
        }
        sb.append("Ljava.lang.String;");
        String name = sb.toString();
        Class<?> c;
        try {
            c = Class.forName(name);
            System.err.println("ERROR: could create " + c);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
	}

}

**Affected versions (compiled from repository):**

openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-_2017_12_06_11_34-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171206_000000 (JIT enabled, AOT enabled)
OpenJ9   - ed54836
OMR      - addcf79
OpenJDK  - 8685bef based on jdk8u152-b16)

Steps to reproduce:

	1. Compile above program
	2. Run it using openj9 java

**Current result:**

ERROR: could create class [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Ljava.lang.String;

**Expected result:**

java.lang.ClassNotFoundException: [[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Ljava/lang/String;
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at A.main(A.java:12)

**Comment by DanHeidinga** [comment]
My understanding (and I'll need to check the specs again) is that in Java 8, the VM spec mandates that the Constant_Class can only express an array with 255 dimensions while arrays created with Class.forName are only limited by VM implementation limits.

This may have changed in Java 9.

**Comment by felipepontes-research** [comment]
I found a test case (test_newInstance from test/functional/Java8andUp/src/org/openj9/test/java/lang/reflect/Test_Array.java) that fails if an array with 256 dimensions is created using Array.newInstance method. Should the behavior of Class.forName be different?

**Comment by pdbain-ibm** [comment]
Further to https://github.com/eclipse/openj9/issues/802#issuecomment-351175591, the Java 11 language spec says nothing about array dimension limits. 

However, the Java 11 VM spec **4.3.2 Field Descriptors**: "A field descriptor representing an array type is valid only if it represents a type with 255 or fewer dimensions."

**4.9.1. Static Constraints** says that `anewarray` cannot be used to create arrays of dimension greater than 255 dimensions. 

Further, **4.11 Limitations of the Java Virtual Machine** states:

> The number of dimensions in an array is limited to 255 by the size of the dimensions opcode of the multianewarray instruction and by the constraints imposed on the multianewarray, anewarray, and newarray instructions (§4.9.1, §4.9.2).

**Comment by pdbain-ibm** [comment]
The code in https://github.com/eclipse/openj9/issues/802#issue-281356032 creates an array _type_ with more than 255 dimensions, but I do not believe there is a way to create an _instance_ of the type, since there is no constructor for the type.

**Comment by pdbain-ibm** [comment]
@non-conformances-research @DanHeidinga your thoughts?  See also 
https://github.com/eclipse/openj9/issues/3049#issuecomment-444885274.

**Comment by DanHeidinga** [comment]
@pdbain-ibm I dug through the internal history because I remembered changes in this area.  Turns out that prior to Java 8, the array dimension limit was implementation defined.  I think we just missed this case when we update the other places - like Array.newArray().

We should add the limit in Class.forName to be consistent with the RI.

**Comment by pdbain-ibm** [comment]
Would you like me to do that?

**Comment by DanHeidinga** [comment]
https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/runtime/jcl/common/reflecthelp.c#L1207-L1208

https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/runtime/vm/FastJNI_java_lang_reflect_Array.cpp#L42-L43
