### ISSUE TITLE
Enable compressed references with AArch64 JIT

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#8026]
Ensure the AArch64 JIT works with a compressed references heap.  This is mainly work to handle a non-native size pointer in the compiler and JIT runtime.  The precise details of what to do and where are hard to enumerate here, but consulting the code in the P, Z, and X code generators and runtime where special handling for compressed references are in place is a starting point.

**Comment by 0xdaryl** [comment]
@knn-k @Akira1Saitoh

**Comment by knn-k** [comment]
I think this can be closed now.
We have seen no issues that are specific to the compressed refs build.

**Comment by 0xdaryl** [comment]
Agree.  Closing.
