### ISSUE TITLE
Trying to figure out how to run JIT casting tests 

### ISSUE THREAD

**Issue by VermaSh** [eclipse/openj9#8043]
Is it possible to run just [jit.test.jitt.castingTest](https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/test/functional/JIT_Test/testng.xml#L59)?

**Comment by pshipton** [comment]
It's possible to run just the jitt test. I don't know enough about the test itself to know if there is an easy way to run just a sub-test.

@llxia in case you know.

**Comment by smlambert** [comment]
For your local runs or in your branch you could modify the [playlist.xml](https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/test/functional/JIT_Test/playlist.xml#L92) to remove all other tests from the test targets like [jit_jitt](https://github.com/eclipse/openj9/blob/2f295ea91cdd97ff37eb5d164fc63014ea718bc7/test/functional/JIT_Test/playlist.xml#L79) that call castingTest then run that target locally (make -f run_configure.mk, make compile, make _jit_jitt), or in a Grinder that points to your openj9 branch where you've made that modification.

**Comment by VermaSh** [comment]
ah ok. Modifying the playlist route should be good for now. thanks!

i'll leave the issue open in case anyone does know of an easier way
