### ISSUE TITLE
Failing JTReg: java/nio/Buffer/LimitDirectMemoryNegativeTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#8065]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/7fb21dfc7efc922f36a5d207115d567516aee92b/test/jdk/java/nio/Buffer/LimitDirectMemoryNegativeTest.java#L1 and https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/9c25debd395b89cc3d7d100106983dfa30b125c9/test/jdk/java/nio/Buffer/LimitDirectMemoryNegativeTest.java#L1 fail for JDK11/13-openj9 (hotspot unaffected)
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac 
```
JDK11
15:56:10  openjdk version "11.0.6" 2020-01-14
15:56:10  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+6-201912091932)
15:56:10  Eclipse OpenJ9 VM AdoptOpenJDK (build master-f154b35e4, JRE 11 Linux amd64-64-Bit Compressed References 20191209_395 (JIT enabled, AOT enabled)
15:56:10  OpenJ9   - f154b35e4
15:56:10  OMR      - 7b2e5df4e
15:56:10  JCL      - d24795242d based on jdk-11.0.6+6)

JDK13
15:56:19  openjdk version "13.0.1" 2019-10-15
15:56:19  OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9-201912100510)
15:56:19  Eclipse OpenJ9 VM AdoptOpenJDK (build master-db1ce597b, JRE 13 Linux amd64-64-Bit Compressed References 20191210_119 (JIT enabled, AOT enabled)
15:56:19  OpenJ9   - db1ce597b
15:56:19  OMR      - 50e115ff2
15:56:19  JCL      - 9c25debd39 based on jdk-13.0.1+9)
```

Optional info
-------------
- intermittent failure (no): 
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- This is likely Hotspot specific for now as the error messages are always going to be different between J9 and HS. 

Failure output (captured from console output)
---------------------------------------------
```
15:57:54  STDERR:
15:57:54   stdout: [];
15:57:54   stderr: [Exception in thread "main" java.lang.IllegalArgumentException: missing size argument
15:57:54  	at LimitDirectMemoryNegativeTest.main(LimitDirectMemoryNegativeTest.java:51)
15:57:54  ]
15:57:54   exitValue = 1
15:57:54  
15:57:54  java.lang.RuntimeException: 'Improperly specified VM option 'MaxDirectMemorySize=foo' missing from stdout/stderr 
15:57:54  
15:57:54  	at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:150)
15:57:54  	at LimitDirectMemoryNegativeTest.main(LimitDirectMemoryNegativeTest.java:57)
15:57:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:57:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:57:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:57:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
15:57:54  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
15:57:54  	at java.base/java.lang.Thread.run(Thread.java:834)
15:57:54  
15:57:54  JavaTest Message: Test threw exception: java.lang.RuntimeException
15:57:54  JavaTest Message: shutting down test

15:57:54  STDOUT:
15:57:54  Command line: [/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -cp /home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15760798641637/jdk_custom_0/work/classes/0/java/nio/Buffer/LimitDirectMemoryNegativeTest.d:/home/jenkins/workspace/Grinder/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/nio/Buffer:/home/jenkins/workspace/Grinder/openjdk-tests/TKG/test_output_15760798641637/jdk_custom_0/work/classes/0/test/lib:/home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Grinder/jvmtest/openjdk/jtreg/lib/jtreg.jar -ea -esa -Xmx512m -Xcompressedrefs -XX:MaxDirectMemorySize=foo LimitDirectMemoryNegativeTest ]
```
Rerun JDK11 job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/nio/Buffer/LimitDirectMemoryNegativeTest.java&TARGET=jdk_custom_0

**Comment by M-Davies** [comment]
Futhermore, `@requires (os.arch == "x86_64") | (os.arch == "amd64") | (os.arch == "sparcv9")` is present. 

@requires
Express a dependence on characteristics of the system being tested, which is supported by jtreg framework. 

`os.arch == "sparcv9"` is likely referring to solaris machines, making the test unique to Hotspot (since I don't believe OpenJ9 is supported on solaris)

@pshipton would you agree with this?

**Comment by pshipton** [comment]
> os.arch == "sparcv9" is likely referring to solaris machines

yes

> making the test unique to Hotspot

no, the conditions are ORed so sparcv9 is just one possibility

**Comment by M-Davies** [comment]
> This is likely Hotspot specific for now as the error messages are always going to be different between J9 and HS.
> 

Perm excluded
