### ISSUE TITLE
Truncated strings are untruncated when serialized by Groovy JsonBuilder

### ISSUE THREAD

**Issue by codeman38** [eclipse/openj9#8102]
Java -version output
--------------------
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)

Summary of problem
------------------
In OpenJ9, Groovy's JsonBuilder implementation exhibits a bug in which a string that has been produced by truncating a larger string is incorrectly serialized as the original full-length string. There's a good chance that this may occur in serializers other than JsonBuilder as well; however, I cannot trigger the bug by outputting the truncated string directly, calling `toString` on it, or even interpolating it into another string using Groovy's `$` notation.

Diagnostic files
----------------

Here's a Groovy script that reliably reproduces the issue using Groovy 2.5.8 and OpenJ9 1.8:

```
import groovy.json.JsonBuilder;

String sentence = "This is the original full-length string."
String word1 = sentence.substring(0, 4)
String word2 = sentence.substring(5, 7)

println "The first word is '${word1}' (length ${word1.length()})."
println "The second word is '${word2}' (length ${word2.length()})."

def builder = new JsonBuilder();
builder([word1, word2])
println builder
```

Expected output:
```
The first word is 'This' (length 4).
The second word is 'is' (length 2).
["This","is"]
```

Actual output under OpenJ9 1.8.0_232:
```
The first word is 'This' (length 4).
The second word is 'is' (length 2).
["This is the original full-length string.","is"]
```

**Comment by andrewcraik** [comment]
I believe this is a bug in Groovy. The Groovy source @ version 2.5.8 includes a class `DirectFastStringService` which directly reads the char[] of java/lang/String using Unsafe:
```
@Override
    public char[] toCharArray(String string) {
        return (char[]) UNSAFE.getObject(string, STRING_VALUE_FIELD_OFFSET);
    }
```

The OpenJ9 string implementation differs in internal operational details from the one found in OpenJDK builds using HotSpot. As a result directly reading an internal field of the class is not guaranteed to produce the same behaviour.

The Groovy project needs to modify their code to correctly handle the details of the OpenJ9 Java 8 string class.

**Comment by andrewcraik** [comment]
@pshipton I think this is a close from our side - not sure if we want to liase with Groovy?

**Comment by pshipton** [comment]
@codeman38 if you use OpenJ9 Java 11 or later then it works, since the internal String representation matches OpenJDK. For Java 8, you can specify the Java option `-Djava.lang.string.substring.nocopy=true`, which can be done via an environment variable
`export OPENJ9_JAVA_OPTIONS=-Djava.lang.string.substring.nocopy=true`.

**Comment by DanHeidinga** [comment]
Closing based on the conclusions above

**Comment by pshipton** [comment]
One thing we should do here is document `-Djava.lang.string.substring.nocopy=true`. I'll go ahead and do that. Created docs issue https://github.com/eclipse/openj9-docs/issues/469
