### ISSUE TITLE
cent6-x64-1 missing boot jdk(s?)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8146]
Disabled it.

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_Nightly/234
`--with-boot-jdk=/usr/lib/jvm/jdk-11`
```
22:27:42  configure: Found potential Boot JDK using configure arguments
22:27:42  configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
```

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_cm_OpenJDK11/35
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_OpenJDK11/36

**Comment by pshipton** [comment]
@jdekonin

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK13_x86-64_linux_Nightly/146
also failed due to
```
23:21:44  Creating jdk image
23:22:05  java.io.UncheckedIOException: java.io.IOException: No space left on device
```

**Comment by jdekonin** [comment]
jdk-11 wasn't as expected.  I fixed the directory name to be as expected.

@rajdeepsingh1 will be addressing the space issue.

**Comment by rajdeepsingh1** [comment]
@pshipton 

Space issue should now be resolved.

`cent6-x64-1` IP has changed from `x.x.x.188` to `x.x.x.208`

This will require a change in the `Configure` section on Jenkins for the machine, which I do not have access to ( it's configured in Jenkins under IP rather than hostname I believe).

**Comment by rajdeepsingh1** [comment]
`cent6-x64-1` is now online in Jenkins
