### ISSUE TITLE
Support for option -XX:+PrintCodeCache

### ISSUE THREAD

**Issue by dagonblanco** [eclipse/openj9#8184]
I'd like to debug code cache utilization on some environments, and found this option documented for the Oracle JDK (for example here). For me, the most relevant part is that it will print the max size of the code cache used during execution.

I've been testing and it seems this option is not supported in openJ9... is that right? Is there an equivalent option to show this information? I know I can see the currently used code cache in a java dump, but it's really the max value that I'm interested in...

Thanks and greetings!

**Comment by pshipton** [comment]
@mstoodle can you pls find someone to address this question.

**Comment by mstoodle** [comment]
Sample output appears to be something like, which I assume is printed during shutdown:
```
CodeCache: size=245760Kb used=1059Kb max_used=1070Kb free=244700Kb
 bounds [0x0000000115c19000, 0x0000000115e89000, 0x0000000124c19000]
 total_blobs=221 nmethods=3 adapters=136
 compilation: enabled
```

@mpirvu will know best the diagnostic options available here. I know there is some `-Xjit:verbose` settings that provide some of this information on the fly, and there's the environment variable `TR_PrintCompMem=1` that displays how much memory is in use at shutdown, but I'm not sure if there's a way to get the maximum code memory throughout the run.

Even if there isn't, we could look at presenting the kind of information that Hotspot provides when that option is specified, at least of the ones that are relevant for OpenJ9 (not sure about "total_blobs" or "adapters").

**Comment by pshipton** [comment]
> we could look at presenting the kind of information that Hotspot provides when that option is specified

Tentatively assigned to the next milestone. This is not a commitment.

**Comment by mpirvu** [comment]
Setting `TR_PrintCompMem=1` environment variable will print code cache utilization at shutdown on stderr. E.g.:
```
Allocated memory for code cache = 2048 KB       Limit = 262144 KB
cache 000000000FB45B20 has 2079808 bytes empty
Code Cache @000000000FB45B20 flags=0x0 almostFull=0
   cold-warm hole size        =  2079808 bytes
   warmCodeAlloc=00007FFB1C603560 coldCodeAlloc=00007FFB1C7FF1A0
   trampoline free space = 0 (temp=0)
```
About the "max_used" value. In Openj9 once a code cache is allocated it is never deallocated. Code fragments from the code cache can be deallocated and openj9 keeps track of them for reuse, but the memory is not released back to the OS.
A code cache has two allocation pointers: (1) `warmCodeAlloc` which grows from the beginning of code cache towards the end and (2) `coldCodeAlloc` which grows from the end of the codecache towards the begining. Between these two pointers there is a hole of free (unused) space. 
When allocating space for a new compiled method, the JIT will first try to find a previously dellocated code fragment and reuse that. If there isn't any, it will allocate space in that hole of free space between warmCodeAlloc and coldCodeAlloc. 
Given this algorithm and the fact that warmCodeAlloc and coldCodeAlloc never go back I would say that maximum space used can be fairly well approximated by `codeCacheSize - cold_warm_hole_size`

**Comment by mstoodle** [comment]
So, in the example above, that would mean 2,097,152 - 2,079,808 or 17,344 bytes , right @mpirvu :) ?

**Comment by mpirvu** [comment]
> in the example above, that would mean 2,097,152 - 2,079,808 or 17,344 bytes

correct.

**Comment by SueChaplain** [comment]
Does this require a doc: external label please?

**Comment by dagonblanco** [comment]
I seem to have missed the notifications for this issue, and when I get back, it's already done!!!
Wow, great support and response! Thanks to everyone for such a quick solution!
