### ISSUE TITLE
Failing JTReg: jdk/test/java/lang/Runtime/loadLibrary/LoadLibraryTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#8194]
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/fbdf154d48bce04892f6d1a2e6fccd291fafdc1e/jdk/test/java/lang/Runtime/loadLibrary/LoadLibraryTest.java#L1 has been failing since 31/12/2019 on jdk8-openj9
- test category, openjdk
- test target name, jdk_lang
- OS/architecture, generic-all

Optional info
-------------
- intermittent failure (no): 
- ~Not yet excluded~ See comment
- New test. Added as part of https://bugs.openjdk.java.net/browse/JDK-8231584
```
LAST PASSING (30/12/2019)
05:00:42  openjdk version "1.8.0_242"
05:00:42  OpenJDK Runtime Environment (build 1.8.0_242-201912300430-b04)
05:00:42  Eclipse OpenJ9 VM (build master-1551b60f0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191230_483 (JIT enabled, AOT enabled)
05:00:42  OpenJ9   - 1551b60f0
05:00:42  OMR      - ce7fdb230
05:00:42  JCL      - b2a1abf9261 based on jdk8u242-b04)

FIRST FAILING (31/12/2019) 
17:43:20  openjdk version "1.8.0_242"
17:43:20  OpenJDK Runtime Environment (build 1.8.0_242-201912311717-b05)
17:43:20  Eclipse OpenJ9 VM (build master-a873af9c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191231_484 (JIT enabled, AOT enabled)
17:43:20  OpenJ9   - a873af9c2
17:43:20  OMR      - ce7fdb230
17:43:20  JCL      - fbdf154d48b based on jdk8u242-b05)
```

Failure output (captured from console output)
---------------------------------------------
```
- Stack Trace

Program `/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 1265544ms).    

- Standard Output

Command line: [/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac -d classes /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target2.java /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target.java]
--- ProcessLog ---
cmd: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac -d classes /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target2.java /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_linux/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target.java
exitvalue: 0
stderr: 
stdout: 


findLibrary someLibrary
Thread1 load
Thread2 load
Timeout refired 960 times
```
Archive: [Runtime.zip](https://github.com/eclipse/openj9/files/4019059/Runtime.zip)
Rerun: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=jdk/test/java/lang/Runtime/loadLibrary/LoadLibraryTest.java&TARGET=jdk_custom_0

**Comment by pshipton** [comment]
The OpenJ9 changes are https://github.com/eclipse/openj9/compare/1551b60f0...a873af9c2 however they only affect JITServer, which is not enabled in the builds (`#if defined(JITSERVER_SUPPORT)`), so they aren'y the cause of the regression.

There were also JCL changes
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/b2a1abf9261...fbdf154d48b
Once of the changes is `Deadlock with ClassLoader.findLibrary and System.loadLibrary call` which adds a fix and the LoadLibraryTest.java

@JasonFengJ9

**Comment by M-Davies** [comment]
Failure is occuring again in the nightlies. Will exclude and investigate

**Comment by M-Davies** [comment]
The test is trying load two [class targets](https://github.com/ibmruntimes/openj9-openjdk-jdk8/tree/fbdf154d48bce04892f6d1a2e6fccd291fafdc1e/jdk/test/java/lang/Runtime/loadLibrary/src) by constructing its own URL to the class directory. The failure cause is a deadlock of the two running threads created by the test. Note, the words lock and monitor are the same when talking about the use of threads here.

- Thread 1 acquires uses `synchronized`[1] to acquire a lock and sets itself as `ready`. Then it notifies the other threads and goes into a `wait()` state (releasing the lock).
-  Thread 2, as the next thread in priority, loads and executes `Target.java` and `findLibrary()` from the test class loader (note, when loading `Target`, a STDOUT call straight afterwards is not executed). Then waits for Thread 1 to release it's lock. Thread 2 does not enter a wait state so the lock is neutral at the moment.
- Thread 1 is ready when `findLibrary()` is executed (ignoring the while loop checking if it isn't ready), notifies all threads and then runs the `Thread1 load` STDOUT call as seen in the output above. 
- Seeing as neither Thread 1 or Thread 2 are in wait at this point, they both execute the same function (`someLibLoad()`) at the same time, probably causing the deadlock and subsequent timeout. 

Perhaps another wait() call is needed somewhere to allow this test to pass? None of this explains why the test is unique to OpenJ9 however...

[1] https://www.geeksforgeeks.org/synchronized-in-java/

**Comment by JasonFengJ9** [comment]
This is a new test and it appears there was a JVM change as well. OpenJDK hotspot`jdk8u242-b02` hangs in this test but `jdk8u242-b05` passes.
So this is not a test problem.

**Comment by JasonFengJ9** [comment]
The direct cause of hang is the synchronized method: https://github.com/eclipse/openj9/blob/f280e85ef7b223bd5fe90d410c4d590641083be9/jcl/src/java.base/share/classes/java/lang/ClassLoader.java#L1875

Need find a way to remove this synchronization on `ClassLoader`.

**Comment by M-Davies** [comment]
What if only part of the method was synchronised? Specifically when it tries to find or load a library?

**Comment by JasonFengJ9** [comment]
> What if only part of the method was synchronised?

Yeah, that's the usual direction for this kind of problem.

**Comment by M-Davies** [comment]
Thank you both 😄

**Comment by adam-thorpe** [comment]
Test is still failing on jdk8 mac and mac xl with what appears to be a slightly different error, can this be re-opened:
```
Stacktrace
Program `/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960322ms).    
Standard Output
Command line: [/Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/javac -d classes /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target.java /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target2.java]
--- ProcessLog ---
cmd: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdkbinary/j2sdk-image/Contents/Home/bin/../bin/javac -d classes /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target.java /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/openjdk-tests/openjdk/openjdk-jdk/jdk/test/java/lang/Runtime/loadLibrary/src/Target2.java
exitvalue: 0
stderr: 
stdout: 


findLibrary someLibrary
Thread1 load
findLibrary awt
Thread2 load
Timeout refired 960 times
    
Standard Error
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
```

**Comment by pshipton** [comment]
@adam-thorpe this is a different problem, likely a test issue. Can you please open a new Issue for it.
