### ISSUE TITLE
Strip debug info from jitserver executable generated by OpenJ9

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#8219]
Executable `jitserver` launcher generated as part of OpenJ9 build process is not stripped of debug info, the way shared libraries are.

Note that in uma based build system the shared libraries are stripped of debug info by this [code](https://github.com/eclipse/openj9/blob/14d1f89b9ee42deab3690efe11e0deb4e81c8096/runtime/makelib/targets.mk.linux.inc.ftl#L50).

Stripping of debug-info should happen in cmake build systems as well, both for shared libraries and executables.

**Comment by ashu-mehra** [comment]
I did a build locally and I noticed that the `jitserver` executable in the jdk is stripped off the debug info, both with uma and cmake.
@keithc-ca are you aware of any change to strip debug info from the executables?

**Comment by keithc-ca** [comment]
It's still not stripped in my build:
```
keithc@up16keithc1:~/space/jdk11/build/linux-ppc64le-normal-server-release$ file images/jdk/bin/jitserver 
images/jdk/bin/jitserver: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=9891712ee07ef2cf05a79e77d02afe1662b67c66, not stripped
```

**Comment by ashu-mehra** [comment]
@keithc-ca 
But it shows there is no `debug info` in there. If debug info is there, it shows up `with debug_info` string in the output, like this:

`file jitserver
jitserver: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=36588a46d1a02733103795e72f4412741606bc23, with debug_info, not stripped`

The `not stripped` is present for other executables as well in my build.

In your output `debug_info` is missing which indicates it got stripped of it. Can you please compare the size of the executable under the final image and one present in the build workspace

I did the build for java 8 and noticed this difference:

in build workspace:
```
ashu@camass1:~/data/ashu-mehra/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm$ file jitserver
jitserver: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=36588a46d1a02733103795e72f4412741606bc23, with debug_info, not stripped
ashu@camass1:~/data/ashu-mehra/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm$ ls -l jitserver
-rwxrwxr-x 1 ashu ashu 44456 Feb 27 21:44 jitserver
```

in final image:
```
ashu@camass1:~/data/ashu-mehra/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin$ file jitserver
jitserver: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=36588a46d1a02733103795e72f4412741606bc23, not stripped
ashu@camass1:~/data/ashu-mehra/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin$ ls -l jitserver
-rwxr-xr-x 1 ashu ashu 13096 Feb 27 21:58 jitserver
```

**Comment by keithc-ca** [comment]
The key information is the part of `file` output that says `not stripped`;
if you say `strip images/j2sdk-image/bin/jitserver` it will get smaller.

**Comment by ashu-mehra** [comment]
One solution to strip libraries and executables of debug info in cmake is to add following code in `openj9/runtime/CMakeLists.txt` similar to what we have in [OMR](https://github.com/eclipse/omr/blob/250665b8ad62de18b019bb29cb5531fa097227a6/cmake/modules/platform/toolcfg/gnu.cmake#L99-L104):

```
 set(CMAKE_SHARED_LIBRARY_SUFFIX "${J9VM_SHARED_LIBRARY_SUFFIX}")
 
+function(strip_debug_info tgt)
+        set(exe_file "$<TARGET_FILE:${tgt}>")
+        set(dbg_file "$<TARGET_FILE:${tgt}>.dbg")
+        add_custom_command(
+               TARGET "${tgt}"
+               POST_BUILD
+               COMMAND "${CMAKE_OBJCOPY}" --only-keep-debug "${exe_file}" "${dbg_file}"
+               COMMAND "${CMAKE_OBJCOPY}" --strip-debug "${exe_file}"
+               COMMAND "${CMAKE_OBJCOPY}" "--add-gnu-debuglink=${dbg_file}" "${exe_file}"
+        )
+endfunction(strip_debug_info)
+
 ###
 ### Begin the definitions of our modules
 ###
```

and then update `CMakeLists.txt` in each module to call this function, eg in `jitserver_launcher/CMakeLists.txt`:
```
                ${CMAKE_DL_LIBS}
 )
 
+strip_debug_info(jitserver)
+
 install(
        TARGETS jitserver
        RUNTIME DESTINATION ${j9vm_SOURCE_DIR}
```

@keithc-ca what is your opinion?

**Comment by keithc-ca** [comment]
We will want the debug information for all shared libraries; it may make sense to do the same for all executables as well, not just jitserver.

**Comment by ashu-mehra** [comment]
@keithc-ca yes, that's the intention. I showed the `jitserver_launcher` change as an example.
We would have to do similar change for all modules that generate shared library/executable.

**Comment by ashu-mehra** [comment]
@keithc-ca Is that change okay with you?

**Comment by keithc-ca** [comment]
I would hope that the changes will be in a small number of locations (ideally, one) that will do the right thing for executables and shared libraries. The cmake solution should respect `OMR_SEPARATE_DEBUG_INFO`.

**Comment by ashu-mehra** [comment]
> I would hope that the changes will be in a small number of locations (ideally, one)

I can't seem to find any way to do this at a single location. Do you have any ideas?

> The cmake solution should respect OMR_SEPARATE_DEBUG_INFO.

I am not sure what role `OMR_SEPARATE_DEBUG_INFO` is playing here. Its [default value](https://github.com/eclipse/omr/blob/37e6cd9e63dff9a984fe81423f6570678fd5ebe7/cmake/modules/OmrDDRSupport.cmake#L38) is `OFF` and is never set to `ON`. Only place it is used is [`omr/cmake/modules/OmrDDRSupport.cmake`](https://github.com/eclipse/omr/blob/37e6cd9e63dff9a984fe81423f6570678fd5ebe7/cmake/modules/OmrDDRSupport.cmake#L152) to determine if debug info needs to be separated.

Does separating debug info prevent DDR from working?
  If yes, how does it work in non-cmake build where we do seem to be stripping out debug info?

**Comment by keithc-ca** [comment]
Setting `OMR_SEPARATE_DEBUG_INFO=ON` doesn't break DDR as far as I'm aware.
My suggestion is that for better integration with openjdk, openj9 would like `OMR_SEPARATE_DEBUG_INFO` to apply to all executables and shared libraries - not _just_ those examined by `ddrgen`. It was my plan to make that change as a follow on to https://github.com/eclipse/openj9/pull/8693 and for consistency with the makefile behavior.

**Comment by ashu-mehra** [comment]
> It was my plan to make that change as a follow on to #8693 and for consistency with the makefile behavior.

Would your plan then fix this issue as well?

**Comment by keithc-ca** [comment]
> > It was my plan to make that change as a follow on to #8693 and for consistency with the makefile behavior.
> 
> Would your plan then fix this issue as well?

No, removing debug information doesn't strip an executable completely. I think this should focus on arranging that `jitserver` is stripped (completely) by the time it makes its way into a jdk image.

**Comment by ashu-mehra** [comment]
In my Java 11 build on Linux x86, I don't see the executables or shared libraries completely stripped in the jdk image, only the debug info is stripped.

```
$ file java
java: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=3e173c5dfdc498f9fade20f0be0588ce49c780fb, not stripped
$ file jdmpview 
jdmpview: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=950ca5a59ba033a474d8165fce5239810305de6d, not stripped
$ $ file libj9vm29.so 
libj9vm29.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2be5678c734d9a3a75bddf2ba5a29097968031bd, not stripped
```

If we want to strip completely, then I guess we should do it for all the artifacts, not just `jitserver` executable.

**Comment by keithc-ca** [comment]
Native artifacts are stripped by using `$(STRIP) $(STRIPFLAGS)`; on Linux `STRIPFLAGS` is `-g` unless overridden in `custom-spec.gmk`. The `-g` option removes debug information (if it were not already removed by `objcopy --strip-debug`). Adding `STRIPFLAGS :=` to `custom-spec.gmk` strips native artifacts completely. For now we don't need to worry about stripping completely, but we should be extracting the debug information and running `objcopy --strip-debug` which will shrink the `jitserver` executable (like we do for shared libraries).

**Comment by ashu-mehra** [comment]
https://github.com/eclipse/openj9/pull/8754 fixes this issue for UMA builds.

In cmake builds, currently we are not stripping the libraries or executables and implementing that is beyond the scope of this issue as it only targets `jitserver` executable.

**Comment by ashu-mehra** [comment]
Closing this issue.

**Comment by pshipton** [comment]
Note we can use keywords in the PR to auto-close the Issue when the PR is merged.
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
