### ISSUE TITLE
ArrayDeque constructor crashes the JVM

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#8221]
ArrayDeque constructor throws OutOfMemoryError when executing the following program:

```
import java.util.ArrayDeque;
public class A {
    public static void main(String[] args) {
        new ArrayDeque(Integer.MAX_VALUE);
    }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java

**Current result:**
```
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.ArrayDeque.allocateElements (ArrayDeque.java:147)
    at java.util.ArrayDeque.<init> (ArrayDeque.java:203)
    at A.main (Main.java:4)
```

**Expected result:**

An ArrayDeque object.

**Comment by dmitripivkine** [comment]
Please note that `-Xmx` value (maximum heap size) for OpenJ9 Java 8 is 512m. HotSpot has a larger value. Please try `-Xmx2G` for your run. Also OpenJ9 Java 11 has `-Xmx` set to 25% of RAM available (same behaviour as HotSpot) - your can try it as well.
