### ISSUE TITLE
Hashtable constructor crashes the JVM

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#8222]
Hashtable constructor throws OutOfMemoryError when executing the following program:

```
import java.util.Hashtable;
public class A {
    public static void main(String[] args) {
        new Hashtable(Integer.MAX_VALUE);
    }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java

**Current result:**

```
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.Hashtable.<init> (Hashtable.java:191)
    at java.util.Hashtable.<init> (Hashtable.java:204)
    at A.main (A.java:4)
```

**Expected result:**

A Hashtable object.

**Comment by pshipton** [comment]
See https://github.com/eclipse/openj9/issues/8221#issuecomment-571717655

**Comment by non-conformances-research** [comment]
This OutOfMemoryError still hapens for jdk8u275-b01_openj9-0.23.0 though issue #3475 has already been fixed. Similar issues #6449, #8221, #8223, and #8224 are alll fixed after #3475 implementation.

**Comment by pshipton** [comment]
It doesn't work with -Xmx8g, but it does with -Xmx9g so this isn't reporting a problem, just user error for not making the heap size big enough.

**Comment by pshipton** [comment]
@dmitripivkine fyi
