### ISSUE TITLE
IdentityHashMap constructor crashes the JVM

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#8223]
IdentityHashMap constructor throws OutOfMemoryError when executing the following program:

```
import java.util.IdentityHashMap;
public class A {
    public static void main(String[] args) {
        new IdentityHashMap(Integer.MAX_VALUE);
    }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java

**Current result:**

```
Caused by: java.lang.OutOfMemoryError: Java heap space
    at java.util.IdentityHashMap.init (IdentityHashMap.java:255)
    at java.util.IdentityHashMap.<init> (IdentityHashMap.java:227)
    at A.main (A.java:4)
```

**Expected result:**

An IdentityHashMap object.

**Comment by pshipton** [comment]
See https://github.com/eclipse/openj9/issues/8221#issuecomment-571717655
