### ISSUE TITLE
Use single flag to enable JITServer changes

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#8229]
Currently JIT enables JITServer changes using a flag `JITSERVER_SUPPORT`, but the uma build system used by the VM does not allow to use this flag. The flag added in `j9.flags` file to enable JITServer in the VM translates to a compile time flag `J9VM_BUILD_JITSERVER`.
Use of these two flags is unnecessary and source of confusion. It would be better to remove one of them and use the other consistently throughout the code base.

**Comment by ashu-mehra** [comment]
Currently the flag propagation for enabling JITServer support in JIT and VM works as follows:

**JIT side:**
When user specifies `--enable-jitserver` option at the configure step (when building OpenJ9 with Adopt makefiles), then the makefile [closed/OpenJ9.mk](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/75dba088c45e515fbfe4c7afa6671b77e68d000f/closed/OpenJ9.gmk#L426) sets an env variable `JITSERVER_SUPPORT=1`.
This variable is used internally by JIT makefiles like [compiler/build/files/common.mk](https://github.com/eclipse/openj9/blob/79aa8cfe4ae439efbe6b933a238fdf79fda4f347/runtime/compiler/build/files/common.mk#L386) to select additional files for compilation. In addition, [compiler/build/toolcfg/gnu/common.mk](https://github.com/eclipse/openj9/blob/79aa8cfe4ae439efbe6b933a238fdf79fda4f347/runtime/compiler/build/toolcfg/gnu/common.mk#L142) also defines a compile time macro `JITSERVER_SUPPORT` if env variable `JITSERVER_SUPPORT` is defined.
Therefore the JITServer related code in JIT is protected by `JITSERVER_SUPPORT` macro.

**VM side:**
In the VM `j9.flags` defines a new flag `build_jitserver`. Its value is set to false by default in `core.feature` file.
When user specifies `--enable-jitserver` option at the configure step (when building OpenJ9 with Adopt makefiles), then the makefile [closed/OpenJ9.mk](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/75dba088c45e515fbfe4c7afa6671b77e68d000f/closed/OpenJ9.gmk#L220)  sets `build_jitserver` to true. This causes the uma infrastructure to define a new macro `J9VM_BUILD_JITSERVER` in `j9cfg.h` file.
However, since we wanted to use the same macro as being used by JIT (i.e. JITSERVER_SUPPORT), following code was added to [j9cfg.h](https://github.com/eclipse/openj9/blob/79aa8cfe4ae439efbe6b933a238fdf79fda4f347/runtime/include/j9cfg.h.ftl#L73):
```
#if defined(J9VM_BUILD_JITSERVER)
#ifndef JITSERVER_SUPPORT
#define JITSERVER_SUPPORT
#endif
#endif 
```
This allowed the JITServer related code in VM to be protected by same macro `JITSERVER_SUPPORT` as used by JIT.

The UMA on VM side which uses the name of the flag in `j9.flags` file to generate the macro, and I am not sure if there is any way to configure it to generate a macro named `JITSERVER_SUPPORT`. If there is, then we can get rid of `J9VM_BUILD_JITSERVER`.

If not, then only other way I can think of is to replace `JITSERVER_SUPPORT` macro (both in VM and JIT) with something that uma can generate.

@DanHeidinga @keithc-ca can you please provide your suggestions on this.

**Comment by keithc-ca** [comment]
The most straight-forward strategy that occurs to me is to just use `J9VM_BUILD_JITSERVER` throughout (that is remove all occurrences of `JITSERVER_SUPPORT`).

**Comment by DanHeidinga** [comment]
I agree with Keith - using the option defined in the `j9.flags` is the right approach.  If I had my pick, I probably would have used an `opt_` flag rather than a `build_` flag but either would work

**Comment by ashu-mehra** [comment]
thanks @keithc-ca @DanHeidinga I will change `JITSERVER_SUPPORT` macro to `J9VM_BUILD_JITSERVER`. As we are changing the macro, I can also update it to `opt_` instead of `build_`.

Just to be clear, I don't think we need to change the env variable set by Adopt makefiles as it is required by JIT to select files for compilation, as in https://github.com/eclipse/openj9/blob/79aa8cfe4ae439efbe6b933a238fdf79fda4f347/runtime/compiler/build/files/common.mk#L386

**Comment by keithc-ca** [comment]
I think the makefiles and cmake files should be changed as well for consistency.

**Comment by ashu-mehra** [comment]
okay

**Comment by ashu-mehra** [comment]
@mpirvu fyi
