### ISSUE TITLE
plinux protobuf undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8257]
`libj9jit29.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`

The JVM was built on ub16-ppcle-1

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64le_linux_Nightly/258
ub16p8j96

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Nightly/254/
ub16p8j91

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64le_linux_Nightly/255/
ub16-ppcle-2

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Nightly/255
ub16p8j94

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly/435/
ub16p8j91

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly/431/
ub16p8j93

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly/433/
ub16p8j91

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_ppc64le_linux_Nightly/432
ub16-ppcle-3

**Comment by pshipton** [comment]
The system testing in the PR passed on ub16p8j92 and ub16p8j94
sanity.functional passed on ub16p8j96 and extended.functional on ub16-ppcle-2
The JVM was built on ub16p8j96

I suspect the problem is related to the machine where the JVM was built.

@mpirvu I expect we should disable JITServer on plinux until this is sorted out.

**Comment by pshipton** [comment]
Reverted via https://github.com/eclipse/openj9/pull/8258

**Comment by mpirvu** [comment]
A couple of days ago we determined that this kind of a problem is due to the presence of an older protobuf package on the machine when we try try to install version 3.7.1. The solution is to uninstall the older version before installing the new one.

I am ok with temporarily reverting the change though.

**Comment by pshipton** [comment]
@jdekonin this should be fixed with priority as it's blocking enabling JIT server on plinux. All the machines should be checked.

**Comment by jdekonin** [comment]
I've reinstalled protobuf on all the machines this past monday as @dchopra001 pointed out when there was a problem with #8145.

I have this output on the machine ub16p8j91 -> ub16p8j96, so I believe these are setup correctly.

```
jenkins@ub16p8j91:/tmp/jdk$ protoc --version
libprotoc 3.7.1
jenkins@ub16p8j91:/tmp/jdk$ ldconfig -p | grep proto
	libprotobuf.so.9 (libc6,64bit) => /usr/lib/powerpc64le-linux-gnu/libprotobuf.so.9
	libprotobuf-lite.so.9 (libc6,64bit) => /usr/lib/powerpc64le-linux-gnu/libprotobuf-lite.so.9
	libmirprotobuf.so.3 (libc6,64bit) => /usr/lib/powerpc64le-linux-gnu/libmirprotobuf.so.3
	libgstdataprotocol-0.10.so.0 (libc6,64bit) => /usr/lib/powerpc64le-linux-gnu/libgstdataprotocol-0.10.so.0
	libgstdataprotocol-0.10.so (libc6,64bit) => /usr/lib/powerpc64le-linux-gnu/libgstdataprotocol-0.10.so
```

ub16-ppcle-1 -> 3 aren't listing libprotobuf in the ldconfig output though, looking at why it didn't work the first time.

**Comment by mpirvu** [comment]
@jdekonin It's ok for `ldconfig` to not display any proto related output because we only need the static library (at compile time). This is what I have on one of my Linux machines:
```
root@JITaaSDocker1:/usr/local/lib# ls *proto*
libprotobuf.a   libprotobuf-lite.a   libprotoc.a
libprotobuf.la  libprotobuf-lite.la  libprotoc.la
```
The presence of libprotobuf.so.9 in your example is suspicious. On another machine on which I have protobuf v3.5.1. with dynamic libraries I see `libprotoc.so.15` being present.
Looking on the internet, `libprotobuf10` seems to correspond to v3.0.0-9`, so I am guessing that `libprotobuf.so.9` is v2.x.x.

**Comment by jdekonin** [comment]
I was just getting back to this today.  I manually ran a compile on ub16-ppcle-1 with `--enable-jitserver` and then tested on ub16p8j91.  I don't appear to encounter the same `undefined symbol` failure.

I didn't change anything though.  Opened #8426 to enable.  I suggest we hit it with lots of PR builds though.

**Comment by pshipton** [comment]
Still happening with ub16-ppcle-2, I've disabled the machine.

**Comment by dchopra001** [comment]
I'm seeing this issue on Z as well:
```12:14:21  JVMJ9VM011W Unable to load j9jit29: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_s390x_linux_jit_Personal/openjdkbinary/j2sdk-image/jre/lib/s390x/compressedrefs/libj9jit29.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```

This is on `rhel7s390xrt14-1`

**Comment by pshipton** [comment]
@dchopra001 that is an IBM problem, pls report an infrastructure issue internally to IBM.
I assume you are building s390x_linux_jit, because otherwise JITServer isn't enabled for z by default.

**Comment by pshipton** [comment]
ub16-ppcle-2 hopefully fixed now.

**Comment by pshipton** [comment]
@jdekonin ub16-ppcle-2 still has the same problem, I've disabled/disconnected it again.

**Comment by jdekonin** [comment]
Thank you @llxia for launching a grinder for me to verify this is fixed.
https://ci.eclipse.org/openj9/job/Grinder/643/consoleFull
This sanity functional testing is using last nights JDK11 build with `--enable-jitserver` in use.
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_Nightly/295/consoleFull

**Comment by DanHeidinga** [comment]
@JasonFengJ9 is seeing this issue on xLinux https://github.com/eclipse/openj9/issues/8550

**Comment by pshipton** [comment]
@jdekonin the problem occurs when the JVM is built on ub16-ppcle-2. If the JVM is built on a working machine, it can run anywhere.

**Comment by jdekonin** [comment]
Test manually and I believe this machine is functional now.  I reenabled in jenkins.

**Comment by pshipton** [comment]
Ok, will reopen if a problem is seen again.

**Comment by AdamBrousseau** [comment]
Wondering if we should change the compile jobs to run `java -Xjit -version` instead? This would cause the compile to fail RED rather than passing and continuing onto test.
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/common/build.groovy#L276

**Comment by JasonFengJ9** [comment]
> Wondering if we should change the compile jobs to run java -Xjit -version instead? This would cause the compile to fail RED rather than passing and continuing onto test.

Internal builds need this check, a bunch of test buckets are still failing due to the same bad build.

**Comment by pshipton** [comment]
Why does `java -Xjit -version` cause a failure? -Xjit is the default and `java -version` already prints a message about the missing symbol, but it doesn't cause failure.

**Comment by AdamBrousseau** [comment]
IIUC, when java -version fails to load the jit it defaults back to running without it and exits 0. If you use the option, when it fails it fails hard.
```
$ ./jdk/bin/java -version && echo $?
JVMJ9VM011W Unable to load j9jit29: /tmp/jdk/lib/compressedrefs/libj9jit29.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
openjdk version "14-internal" 2020-03-17
OpenJDK Runtime Environment (build 14-internal+0-adhoc.jenkins.BuildJDK14x86-64linuxNightly)
Eclipse OpenJ9 VM (build ibm_sdk-df22f7ee4f, JRE 14 Linux amd64-64-Bit Compressed References 20200220_34 (JIT disabled, AOT disabled)
OpenJ9   - df22f7ee4f
OMR      - 83ba4e770
JCL      - 2baf17d18e3 based on jdk-14+36)
0
$ ./jdk/bin/java -Xjit -version && echo $?
JVMJ9VM011W Unable to load j9jit29: /tmp/jdk/lib/compressedrefs/libj9jit29.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
JVMJ9VM004E Cannot load library required by: -Xjit
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by pshipton** [comment]
Ok, pls make it so.
