### ISSUE TITLE
JDK10: Impelement BoundMethodHandle.speciesData_LLLL().factory() method

### ISSUE THREAD

**Issue by yongja79** [eclipse/openj9#826]
An error occurs when making openj9 with openjdk10

```
ERROR: Build failed for target 'all' in configuration 'linux-x86_64-normal-server-release' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target jdk_modules_java.base__the.java.base_batch:
/root/openJDK10-J9-mirror/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java:781: error: cannot find symbol
                        BoundMethodHandle.speciesData_LLLL().factory().invokeBasic(type, form,
                                                            ^
  symbol:   method factory()
  location: class BoundMethodHandle.SpeciesData
/root/openJDK10-J9-mirror/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java:785: error: cannot find symbol
                        BoundMethodHandle.speciesData_LLL().factory().invokeBasic(type, form,
                                                           ^
  symbol:   method factory()
  location: class BoundMethodHandle.SpeciesData
/root/openJDK10-J9-mirror/src/java.base/share/classes/java/lang/invoke/MethodHandleImpl.java:1094: error: cannot find symbol
            mh = (BoundMethodHandle) data.factory().invokeBasic(type, form, (Object) target, (Object) exType,
   ... (rest of output omitted)

* All command lines available in /root/openJDK10-J9-mirror/build/linux-x86_64-normal-server-release/make-support/failure-logs.
=== End of repeated output ===
```

BoundMethodHandle itself doesn't appear to have the method factory() but it extends the new class java.lang.invoke.ClassSpecializer which does. As openj9 has yet implemented ClassSpecializer this may be related to issue #824 but raising a separate issue to highlight that the factory() method is needed by other classes

**Comment by DanHeidinga** [comment]
OpenJ9 has it's own implementation of `java.lang.invoke.MethodHandle` and subclasses.  It doesn't use the OpenJDK implementation.  We reuse parts of the java.lang.invoke package so the approach OpenJ9 has taken has been to provide compile stubs for methods that are only necessary to compile with OpenJDK while independently implementing equivalent classes for necessary functionality.

FYI @JasonFengJ9

**Comment by JasonFengJ9** [comment]
Will check if a compile stub is sufficient here.

**Comment by JasonFengJ9** [comment]
@yongja79 is there a way to share your `Java 10` extension repo such that I can reproduce the compilation failures?

**Comment by JasonFengJ9** [comment]
This issue can be closed by PR https://github.com/eclipse/openj9/pull/852.
