### ISSUE TITLE
Latest version unusable for MC servers.

### ISSUE THREAD

**Issue by Zilacon** [eclipse/openj9#8266]
Hello, ive recently updated to the Jan 7th version which ran fine/fast but threw JVM9 errors on the console. I updated today in hopes that was fixed, and while the JVM errors were fixed and the plugins that were crashing no longer have problems...

The load times practically shot through the roof. A server that took 1m 40s to load on the Jan 7th version now takes 26m 10s on the Jan 9th version.

Its struggling to load up small 2-3KB plugins, completely freezes for minutes for each plugin/mod being loaded up.

(No java expert, cant give specific details, thankfully other people helped track down the problem in my last issue. Hoping for the same with this one :) )

Reproduced on 4 different minecraft server softwares with 5 versions of MC. 1.5.2/1.6.4/1.7.10/1.12.2/1.13.2

**Comment by mstoodle** [comment]
Hi @zilacon, sorry to hear about your experience.

To get us started, would you be able to send us the specific version information for before and after the problem? i.e. run `java -version` on the two builds you tried and paste the output into this issue?

**Comment by Zilacon** [comment]
I just extract the tar into a folder and run it from there.
The build that gives JVM errors is: OpenJDK8U-jre_x64_linux_openj9_2020-01-07-17-06.tar.gz
The build that doesnt have the errors but has terrible start speed is: OpenJDK8U-jre_x64_linux_openj9_2020-01-09-14-19.tar.gz

Errors i got on the 7th version are:
```
01-08 14:18:28 [SEVERE] [Minecraft] Error occurred while enabling TekkitCustomizer v1.6 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException
    at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:310)
    at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:303)
    at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:132)
    at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:30)
    at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:14)
    at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:18)
    at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:43)
    at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:12)
    at org.bukkit.craftbukkit.v1_6_R3.inventory.RecipeIterator.next(RecipeIterator.java:35)
    at org.bukkit.craftbukkit.v1_6_R3.inventory.RecipeIterator.next(RecipeIterator.java:11)
    at me.ryanhamshire.TekkitCustomizer.TekkitCustomizer.loadConfiguration(TekkitCustomizer.java:127)
    at me.ryanhamshire.TekkitCustomizer.TekkitCustomizer.onEnable(TekkitCustomizer.java:97)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:467)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:278)
    at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:260)
    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:521)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:428)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:224)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:141)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
```

```
01-08 14:17:58 [INFO] [mcMMO] Enabling mcMMO v1.4.08-b3544
01-08 14:17:59 [SEVERE] [mcMMO] There was an error while enabling mcMMO!
01-08 14:17:59 [SEVERE] [Minecraft] java.lang.ArrayIndexOutOfBoundsException
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:310)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:303)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:132)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:30)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:14)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:18)
01-08 14:17:59 [SEVERE] [Minecraft] 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:43)
01-08 14:17:59 [SEVERE] [Minecraft] 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:12)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.inventory.RecipeIterator.next(RecipeIterator.java:35)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.inventory.RecipeIterator.next(RecipeIterator.java:11)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.getRecipesFor(CraftServer.java:915)
01-08 14:17:59 [SEVERE] [Minecraft] 	at com.gmail.nossr50.skills.repair.Repair.getRepairAndSalvageQuantities(Repair.java:85)
01-08 14:17:59 [SEVERE] [Minecraft] 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
01-08 14:17:59 [SEVERE] [Minecraft] 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
01-08 14:17:59 [SEVERE] [Minecraft] 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
01-08 14:17:59 [SEVERE] [Minecraft] 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:424)
01-08 14:17:59 [SEVERE] [Minecraft] 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:467)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:278)
01-08 14:17:59 [SEVERE] [Minecraft] 	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:260)
01-08 14:17:59 [SEVERE] [Minecraft] 	at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:30)
01-08 14:17:59 [SEVERE] [Minecraft] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
01-08 14:17:59 [SEVERE] [Minecraft] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
01-08 14:17:59 [SEVERE] [Minecraft] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
01-08 14:17:59 [SEVERE] [Minecraft] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01-08 14:17:59 [SEVERE] [Minecraft] 	at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
01-08 14:17:59 [SEVERE] [Minecraft] 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
01-08 14:17:59 [SEVERE] [Minecraft] 	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:817)
01-08 14:17:59 [SEVERE] [Minecraft] 	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
01-08 14:17:59 [SEVERE] [Minecraft] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:222)
01-08 14:17:59 [SEVERE] [Minecraft] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:141)
01-08 14:17:59 [SEVERE] [Minecraft] 	at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
01-08 14:17:59 [INFO] [mcMMO] Disabling mcMMO v1.4.08-b3544
01-08 14:17:59 [SEVERE] [Minecraft] Error occurred while disabling mcMMO v1.4.08-b3544 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:148)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:137)
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:219)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:491)
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:402)
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:467)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.loadPlugin(CraftServer.java:278)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.enablePlugins(CraftServer.java:260)
	at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:817)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:222)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:141)
	at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.bukkit.craftbukkit.v1_6_R3.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:28)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.getOfflinePlayer(CraftServer.java:1097)
	at org.bukkit.craftbukkit.v1_6_R3.CraftServer.getOfflinePlayer(CraftServer.java:1073)
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133)
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121)
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:43)
	... 22 more
```

Both of these errors are not present in the current version, so im guessing they are resolved. But the fix to them may also be the cause of the current load time problem.

**Comment by pshipton** [comment]
These builds correspond to 

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-202001051023-b05)
Eclipse OpenJ9 VM (build master-22f699eba, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200105_489 (JIT enabled, AOT enabled)
OpenJ9   - 22f699eba
OMR      - ce7fdb230
JCL      - fbdf154d based on jdk8u242-b05)

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-202001090431-b06)
Eclipse OpenJ9 VM (build master-9771d87a4, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200109_492 (JIT enabled, AOT enabled)
OpenJ9   - 9771d87a4
OMR      - 4d5712b26
JCL      - a9857e68ed based on jdk8u242-b06)

Changes:
https://github.com/eclipse/openj9/compare/22f699eba...9771d87a4
https://github.com/eclipse/openj9-omr/compare/ce7fdb230...4d5712b26
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/fbdf154d...a9857e68ed

**Comment by pshipton** [comment]
@Zilacon could you please give https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b06_openj9-0.18.0-m2/OpenJDK8U-jdk_x64_linux_openj9_8u242b06_openj9-0.18.0-m2.tar.gz a try. This is our Milestone 2 build for the upcoming January release.

**Comment by Zilacon** [comment]
Same problem, no errors but the load time is insane.

**Comment by pshipton** [comment]
@DanHeidinga fyi

**Comment by Zilacon** [comment]
Yeah i relaunched 5 times to make sure. The 7th version loads fast (1m 40s) i downloaded the october version listed on the release page and that loads in 1m10s. But the current version takes 8m-20m (depends on the server size in mods).

It seems to freeze up on every mod/plugin it loads up. It goes to load it then just pauses for 10-30s and then goes to the next thing and repeats.

Im sorry i cant give more detailed information, this is running on a brand new install of ubuntu so the only thing i have on it is OJ9 and the files to the servers at the moment. And i lack any technical knowledge to go into more depth.

**Comment by pshipton** [comment]
There are some additional builds between 2020-01-07-17-06 and 2020-01-09-14-19. Can you please try these so we can narrow down the change list.
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-01-09-03-36/OpenJDK8U-jdk_x64_linux_openj9_2020-01-09-03-36.tar.gz
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-01-09-14-19/OpenJDK8U-jdk_x64_linux_openj9_2020-01-09-14-19.tar.gz

**Comment by pshipton** [comment]
09-03-36
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-202001081501-b05)
Eclipse OpenJ9 VM (build master-a025fcd7e, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200108_491 (JIT enabled, AOT enabled)
OpenJ9   - a025fcd7e
OMR      - 4d5712b26
JCL      - fb0665a9 based on jdk8u242-b05)

09-14-19
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-202001090431-b06)
Eclipse OpenJ9 VM (build master-9771d87a4, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200109_492 (JIT enabled, AOT enabled)
OpenJ9   - 9771d87a4
OMR      - 4d5712b26
JCL      - a9857e68ed based on jdk8u242-b06)

**Comment by pshipton** [comment]
Sorry, one of those is the same one you already tried, so just 09-03-36.

**Comment by Zilacon** [comment]
09-03-36 took 1m 32s to start.

**Comment by pshipton** [comment]
Changes:
a025fcd...9771d87
ibmruntimes/openj9-openjdk-jdk8@fb0665a9...a9857e6

**Comment by pshipton** [comment]
Since the problem also occurs in the 0.18 branch, it seems like one of
- Fix JVMTI getConstantPool and getBytecodes output
- Move synchronized to native method CLassLoader.loadLibraryWithPath
- Add launcher for JITServer

I've created a 0.18 build without the first two changes https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-0.18.0-Build8/7
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_Personal/649/OpenJ9-JDK8-x86-64_linux-20200110-050435.tar.gz

Created another without the third change (JITServer)
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-0.18.0-Build8/8
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_Personal/650/OpenJ9-JDK8-x86-64_linux-20200110-053730.tar.gz

Can you please try these two builds.

**Comment by Zilacon** [comment]
050435  (2m 43s)
053730  (9m 38s)
Hmm, ill just use the 09-03-36 one for now cause that continuously starts in 1m 20-40s

**Comment by DanHeidinga** [comment]
@pshipton Do the two builds you created on the 0.18 branch include https://github.com/eclipse/openj9/pull/7788 ?  It's the Class#getMethods change that was backed out...

**Comment by pshipton** [comment]
My intention was not to include #7788 by rebuilding from the v0.18.0-release branch, but after double checking it seems I messed it up. I've started a new build from the latest release content.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-0.18.0-Build8/11/

**Comment by pshipton** [comment]
@Zilacon if Dan is correct, pls try this latest Adopt build, which should have the problem resolved.

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-01-10-12-29/OpenJDK8U-jdk_x64_linux_openj9_2020-01-10-12-29.tar.gz

**Comment by Zilacon** [comment]
2m 53s
1m 42s after cache file remade
So... Fixed?
Appreciate the help as always :)

**Comment by pshipton** [comment]
I'd like to keep this open to confirm the 0.18.0 release is good. Although I built something manually, there is an automated build scheduled for Saturday which I'll ask if it's good once the build is available.

**Comment by pshipton** [comment]
@Zilacon could you pls try the following build. This is an OpenJ9 test build with the 0.18.0 pre-release content. If this works I will close this issue.
https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_x86-64_linux_Release/26/OpenJ9-JDK8-x86-64_linux-20200111-133526.tar.gz

**Comment by Zilacon** [comment]
That build you sent just now loads faster then all the other builds (1m 02s) :D

1.8.0_242-201912020430-b01 launches the YogscastComplete pack with no issues (Specicially it seems its causing problems with the Thaumcraft mod) All latest versions do not work. Even the one you just sent me.

I didnt find this out until now as like i said im setting up a new server and testing each server 1 by 1 and working out their problems.
Do i talk about this other problem here or open a new issue for it?

**Comment by pshipton** [comment]
@Zilacon we can re-purpose this issue. Can you please narrow down the last working build and the first failing build. Then we can look at the smallest set of changes to figure out what caused the problem. The build you have is the Dec 2 download from AdoptOpenJDK.net. I'd search by taking a build in the middle, say Dec 18. If it works, pick a new build in the middle between Dec 18 and Jan 7. If it doesn't work, pick a build in the middle between Dec 2 and 18. Continue this way until it's narrowed down.

**Comment by Zilacon** [comment]
That will take me a bit XD
But yeah i can try to narrow it down.

**Comment by Zilacon** [comment]
Guess one of my developers accidentally fixed the issue by fixing another issue on the server wrapper.
Cause now its starting with no problems.
So yeah, thanks for your help with the other problems! Hopefully thats the last of them.
