### ISSUE TITLE
JDK 13 : sanity.perf jobs failing in all platforms 

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#8269]
Failure link : https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_sanity.perf_ppc64le_linux/4/console
------------

Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc):  sanity.perf
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): sanity.perf
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): All supported Platforms
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced:  
20:50:42  Run /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdkbinary/j2sdk-image/bin/java -version
20:50:42  openjdk version "13.0.1" 2019-10-15
20:50:42  OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
20:50:42  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0-m2, JRE 13 Linux ppc64le-64-Bit Compressed References 20200109_145 (JIT enabled, AOT enabled)
20:50:42  OpenJ9   - b8fe61937
20:50:42  OMR      - 7a1b0239a
20:50:42  JCL      - 03236d9eee based on jdk-13.0.1+9)
Optional info
-------------

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output (captured from console output)
---------------------------------------------
20:51:24      [javac] Compiling 8 source files to /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/bumblebench
20:51:24      [javac] warning: [options] bootstrap class path not set in conjunction with -source 6
20:51:24      [javac] error: Source option 6 is no longer supported. Use 7 or later.
20:51:24      [javac] error: Target option 6 is no longer supported. Use 7 or later.
20:51:24  
20:51:24  BUILD FAILED
20:51:24  /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
20:51:24  /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/build.xml:31: The following error occurred while executing this line:
20:51:24  /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/build.xml:59: The following error occurred while executing this line:
20:51:24  /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/build.xml:49: The following error occurred while executing this line:
20:51:24  /home/jenkins/workspace/Test_openjdk13_j9_sanity.perf_ppc64le_linux/openjdk-tests/perf/bumbleBench/bumblebench/build.xml:47: Compile failed; see the compiler error output for details.
20:51:24  
20:51:24  Total time: 3 seconds
20:51:24  1
20:51:24  makefile:79: recipe for target 'compile' failed
20:51:24  make: *** [compile] Error 1
[Pipeline] }
20:51:24  $ ssh-agent -k
20:51:24  unset SSH_AUTH_SOCK;
20:51:24  unset SSH_AGENT_PID;
20:51:24  echo Agent pid 27860 killed;
20:51:25  [ssh-agent] Stopped.
[Pipeline] // sshagent

**Comment by pshipton** [comment]
@smlambert @llxia can you please help with this.

**Comment by archanaNogriya** [comment]
Moving this issue to https://github.com/AdoptOpenJDK/openjdk-tests/issues/1541.
