### ISSUE TITLE
PR builds: Also support "depends" on a repo/branch

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#827]
Currently we can launch PR builds with dependent changes that are in an open PR at omr, openj9-omr or openj9-openjdk-jdk9. There is a use case to launch a PR build against a branch instead of an open PR. For example, when the dependent or breaking PR has been merged in OMR and can't promote through OMR-Acceptance.

More info on dependent changes
https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/README.md#dependent-changes

If we can temporarily survive without this feature, it would be nice to finish off #660, #851 first. Which will commit all the build code in.

**Comment by DanHeidinga** [comment]
We've survived this long without it so I view as an enhancement.  Delaying until those PRs are merged is fine as long we are able to close those out in a reasonable time frame

**Comment by DanHeidinga** [comment]
Bumping the priority on this as we're seeing more OpenJ9 PRs with dependent OMR changes that can't be built as the OMR change has already been merged.
