### ISSUE TITLE
Test_openjdk8_j9_special.functional_x86-64_linux : Malformed target-specific variable definition.

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#8270]
Failure link : https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.functional_x86-64_linux/123/console
------------

Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): special.functional
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): 
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): x86-64_linux
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 

Optional info
-------------

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output (captured from console output)
---------------------------------------------
Test name : openjdk-tests/functional/JIT_Test

15:05:24  make[3]: Entering directory `/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional/JIT_Test'
15:05:24  autoGen.mk:758: *** Malformed target-specific variable definition.  Stop.
15:05:24  make[3]: Leaving directory `/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional/JIT_Test'
15:05:24  make[2]: *** [compile-JIT_Test] Error 2
15:05:24  make[2]: Leaving directory `/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests/functional'
15:05:24  make[1]: *** [compile-functional] Error 2
15:05:24  make[1]: Leaving directory `/home/jenkins/workspace/Test_openjdk8_j9_special.functional_x86-64_linux/openjdk-tests'
15:05:24  make: *** [compile-..] Error 2

**Comment by pshipton** [comment]
@smlambert @llxia can you please help with this.

**Comment by archanaNogriya** [comment]
I am closing this issue, as the issue has been moved to https://github.com/AdoptOpenJDK/openjdk-tests/issues/1540
