### ISSUE TITLE
Test_openjdk8_j9_special.openjdk_x86-64_mac : jdk_math_jre failure 

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#8271]
Failure link : https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_special.openjdk_x86-64_mac/34/console
------------

Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): 
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): jdk_math_jre
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): x86-64_mac
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 
19:03:35  openjdk version "1.8.0_242"
19:03:35  OpenJDK Runtime Environment (build 1.8.0_242-202001091537-b06)
19:03:35  Eclipse OpenJ9 VM (build openj9-0.18.0-m2, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200109_425 (JIT enabled, AOT enabled)
19:03:35  OpenJ9   - b8fe61937
19:03:35  OMR      - 7a1b0239a
19:03:35  JCL      - adc46a9f58 based on jdk8u242-b06)

Optional info
-------------

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output (captured from console output)
---------------------------------------------
**jdk_math_jre_0**

19:05:39  ===============================================
19:05:39  Running test jdk_math_jre_0 ...
19:05:39  ===============================================
19:05:39  jdk_math_jre_0 Start Time: Thu Jan  9 19:05:39 2020 Epoch Time (ms): 1578596739466
19:05:39  "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdkbinary/j2sdk-image//Contents/Home/bin/..//bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdkbinary/j2sdk-image//Contents/Home/bin/..//bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
19:05:40  
19:05:40  Attempting to destroy all caches in cacheDir /Users/jenkins/javasharedresources/
19:05:40  
19:05:40  JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
19:05:40  JVMSHRC005I No shared class caches available
19:05:40  cache cleanup done
19:05:40  variation: NoOptions
19:05:40  JVM_OPTIONS: -Xcompressedrefs 
19:05:40  { itercnt=1; \
19:05:40  	mkdir -p "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_1578596738618/jdk_math_jre_0"; \
19:05:40  	cd "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_1578596738618/jdk_math_jre_0"; \
19:05:40  	"/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdkbinary/j2sdk-image//Contents/Home/bin/..//bin/java" -Xmx512m -jar "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../../jvmtest/openjdk/jtreg/lib/jtreg.jar" \
19:05:40  	-agentvm -a -ea -esa -v:fail,error,time,nopass -retain:fail,error,*.dmp,javacore.*,heapdump.*,*.trc -ignore:quiet -timeoutFactor:8 -xml:verify -concurrency:2 -vmoptions:"-Xmx512m -Xcompressedrefs " \
19:05:40  	-w ""/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_1578596738618/jdk_math_jre_0"/work" \
19:05:40  	-r "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../../jvmtest/openjdk/report" \
19:05:40  	-compilejdk:"/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdkbinary/j2sdk-image//Contents/Home/bin/../" \
19:05:40  	-jdk:"/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdkbinary/j2re-image" \
19:05:40  	-exclude:"/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../openjdk/openjdk-jdk/jdk/test/ProblemList.txt" \
19:05:40  	-exclude:"/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../../jvmtest/openjdk/ProblemList_openjdk8-openj9.txt" \
19:05:40  	"/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../openjdk/openjdk-jdk/jdk/test:jdk_math"; \
19:05:40  	if [ $? -eq 0 ] ; then echo ""; echo "jdk_math_jre_0""_PASSED"; echo ""; cd /Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/..;  else echo ""; echo "jdk_math_jre_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdk-tests/TKG/../TKG/test_output_1578596738618/TestTargetResult";
19:05:44  Error: cannot determine version for JDK: /Users/jenkins/workspace/Test_openjdk8_j9_special.openjdk_x86-64_mac/openjdkbinary/j2re-image
19:05:46  
19:05:46  jdk_math_jre_0_FAILED

**Comment by pshipton** [comment]
@smlambert @llxia can you please help with this.

**Comment by llxia** [comment]
dup of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1525
