### ISSUE TITLE
JDK11 : Multiple test failing under sanity.system.

### ISSUE THREAD

**Issue by archanaNogriya** [eclipse/openj9#8273]
Failure link : https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_aarch64_linux_xl/27/console
------------

Public link to the failing test
and ideally extracting relevant info from the failed run (just enough info to [run a Grinder](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Grinder-Build-on-Jenkins)), include:
- test category, in Grinder equates to BUILD_LIST (functional, systemtest, openjdk, etc): 
sanity.system
- test target name, in Grinder equates to TARGET (testCaseName from playlist.xml, jdk_lang, jdk_net, etc): 
JlinkTest_RequiredMod_0_FAILED, 
JlinkTest_AddModLimitMod_0, 
CpMpJlinkTest_0
JlinkPluginOpt_GenOptTest_0
LayersTest_0
CLTest_0
CLTestImage_0
CLLoadTest_0
ClassLoadingTest_0
NioLoadTest_0
ClassLoadingTest_ConcurrentScavenge_0
MachineInfo_0
- OS/architecture, in Grinder equates to Jenkinsfile (openjdk_x86-64_linux, openjdk_x86-64_windows, etc): aarch64_linux_xl

- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 

Optional info
-------------

- intermittent failure (yes|no): 
- regression or new test:  
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
----------------------------
Java version:
15:29:17  GEN stderr openjdk version "11.0.6" 2020-01-14
15:29:17  GEN stderr OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+9)
15:29:17  GEN stderr Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0-m2, JRE 11 Linux aarch64-64-Bit 20200109_41 (JIT disabled, AOT disabled)
15:29:17  GEN stderr OpenJ9   - b8fe61937
15:29:17  GEN stderr OMR      - 7a1b0239a
15:29:17  GEN stderr JCL      - 3e61f7298a based on jdk-11.0.6+9)
------------------
Failure output (captured from console output)
---------------------------------------------

FAILED test targets:
15:30:03  	DaaLoadTest_daa1_0
15:30:03  	DaaLoadTest_daa2_0
15:30:03  	DaaLoadTest_daa3_0
15:30:03  	DaaLoadTest_daa1_ConcurrentScavenge_0
15:30:03  	DaaLoadTest_daa2_ConcurrentScavenge_0
15:30:03  	DaaLoadTest_daa3_ConcurrentScavenge_0
15:30:03  	TestJlmRemoteClassNoAuth_0
15:30:03  	TestJlmRemoteMemoryAuth_0
15:30:03  	TestJlmRemoteMemoryNoAuth_0
15:30:03  	TestIBMJlmLocal_0
15:30:03  	TestIBMJlmRemoteClassAuth_0
15:30:03  	TestIBMJlmRemoteClassNoAuth_0
15:30:03  	TestIBMJlmRemoteMemoryAuth_0
15:30:03  	TestIBMJlmRemoteMemoryNoAuth_0
15:30:03  	LambdaLoadTest_ConcurrentScavenge_0
15:30:03  	MathLoadTest_autosimd_0
15:30:03  	MathLoadTest_bigdecimal_0
15:30:03  	MathLoadTest_autosimd_ConcurrentScavenge_0
15:30:03  	MathLoadTest_bigdecimal_ConcurrentScavenge_0
15:30:03  	MauveSingleThreadLoadTest_OpenJ9_0
15:30:03  	MauveSingleInvocationLoadTest_OpenJ9_0
15:30:03  	MauveMultiThreadLoadTest_0
15:30:03  	CpMpTest_CpMp_0
15:30:03  	CpMpTest_MP_0
15:30:03  	CpMpTest2_0
15:30:03  	CpMpTest3_0
15:30:03  	CpMpModularJarTest_0
15:30:03  	CpMpModularJarTest2_0
15:30:03  	CpMpModularJarTest3_0
15:30:03  	JDKInternalAPIsTest_0
15:30:03  	AutomaticModulesTest1_0
15:30:03  	AutomaticModulesTest2_0
15:30:03  	AutomaticModulesTest_ImpliedReadabilityTest1_0
15:30:03  	AutomaticModulesTest_ImpliedReadabilityTest2_0
15:30:03  	AutomaticModulesTest_ImpliedReadabilityTest3_0
15:30:03  	ServiceLoadersTest_0
15:30:03  	PatchModuleTest_PlatformMod_0
15:30:03  	PatchModuleTest_AppMod_0
15:30:03  	PatchModuleTest_UnexportedType_0
15:30:03  	PatchModuleTest_Advanced_0
15:30:03  	PatchModuleImgTest_PlatformMod_0
15:30:03  	PatchModuleImgTest_AppMod_0
15:30:03  	PatchModuleImgTest_UnexportedType_0
15:30:03  	PatchModuleImgTest_Advanced_0
15:30:03  	UpgradeModPathTest_ExpDir_0
15:30:03  	UpgradeModPathTest_ExpDirImg_0
15:30:03  	UpgradeModPathTest_Jarred_0
15:30:03  	UpgradeModPathTest_JarredImg_0
15:30:03  	JlinkTest_RequiredMod_0
15:30:03  	JlinkTest_AddModLimitMod_0
15:30:03  	CpMpJlinkTest_0
15:30:03  	JlinkPluginOpt_GenOptTest_0
15:30:03  	LayersTest_0
15:30:03  	CLTest_0
15:30:03  	CLTestImage_0
15:30:03  	CLLoadTest_0
15:30:03  	ClassLoadingTest_0
15:30:03  	NioLoadTest_0
15:30:03  	ClassLoadingTest_ConcurrentScavenge_0
15:30:03  
15:30:03  TOTAL: 75   EXECUTED: 67   PASSED: 8   FAILED: 59   DISABLED: 6   SKIPPED: 2

Common error -
15:29:58  GEN stderr openjdk version "11.0.6" 2020-01-14
15:29:58  GEN stderr OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+9)
15:29:58  GEN stderr Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0-m2, JRE 11 Linux aarch64-64-Bit 20200109_41 (JIT disabled, AOT disabled)
15:29:58  GEN stderr OpenJ9   - b8fe61937
15:29:58  GEN stderr OMR      - 7a1b0239a
15:29:58  GEN stderr JCL      - 3e61f7298a based on jdk-11.0.6+9)
15:29:58  GEN stderr 
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.<init>(JavaVersion.java:101)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.environment.JavaVersion.getInstance(JavaVersion.java:115)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.environment.StfEnvironmentCore.primaryJvm(StfEnvironmentCore.java:490)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:228)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.findProjectDependencies(ClassPathConfigurator.java:196)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.runner.ClassPathConfigurator.configureClassLoader(ClassPathConfigurator.java:75)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.executeTest(StfRunner.java:195)
15:29:58  GEN stderr 	at net.adoptopenjdk.stf.runner.StfRunner.main(StfRunner.java:69)
15:29:58  Generation failed
---------------------------

Rerunning one of failure test DaaLoadTest_daa1_0 in the grinder to see if that makes a difference.
https://ci.adoptopenjdk.net/job/Grinder/1684/ : Failed

**Comment by pshipton** [comment]
aarch64 is not yet a supported it platform, it should not be built as part of the 0.18 release, or any builds triaged yet. It's not expect to be ready for release until June.

**Comment by archanaNogriya** [comment]
Thanks Peter, I should have noticed that. I will close this.
