### ISSUE TITLE
aix71-p8-6 came online and failed to run jobs

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8279]
Whatever was keeping aix71-p8-6 offline stopped working. It came online, many jobs tried to run on it and failed. I believe that is expected as it's not setup to run jenkins jobs. I've disabled it again, but whenever jenkins restarts it's going to come online again.

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
I brought it back online because I thought it was capable of running jobs.  Setup is clearly not identical to 7-9.  @AdamBrousseau when you have time can you please reset this image and I can rebuild.

**Comment by pshipton** [comment]
@jdekonin we should test these things in advance, rather than wasting overnight build time.
