### ISSUE TITLE
MemoryPool MBean for JIT Code Cache always reports 0M Used

### ISSUE THREAD

**Issue by PhilWakelin** [eclipse/openj9#8285]
Java -version output
--------------------
java.fullversion: 8.0.6.0 - pmz6480sr6-20191107_01(SR6) JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20191106_432135 (JIT enabled, AOT enabled) OpenJ9 - f0b6be7 OMR - 18d8f94 IBM - 233dfb5
Environment: z/OS V2R3

Summary of problem
------------------
At startup of a Liberty JVM in CICS TS, the MemoryPool MBean reports 0 storage usage for the JIT Code Cache. This is a regression from previous behaviour and is reproducible

Test case output (from MBean)
JIT code cache: init=256M max=256M used=0M committed=256M

Java Core reports the following Usage for the JIT Code Cache 

2MEMUSER       +--JIT: 305,169,471 bytes / 1517 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 268,435,456 bytes / 1 allocation
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 18,874,944 bytes / 9 allocations
...
1STSEGTYPE     JIT Code Cache
NULL           segment            start              alloc              end                type       size
1STSEGMENT     0x000000508C793878 0x000000509D600000 0x000000509F15D9A0 0x00000050AD600000 0x00000068 0x0000000010000000

The JConsole UI also reports 0 bytes used for the corresponding used field in the MemoryPool bean.

**Comment by PhilWakelin** [comment]
Raised in error, as this is still being dealt with in issue https://github.com/eclipse/openj9/issues/7171

**Comment by pshipton** [comment]
Right, the fix is in SR6 FP5. @PhilWakelin do you have access to get an advance copy of SR6 FP5 to confirm it's working?
