### ISSUE TITLE
JEP-370 Foreign-Memory Access API

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#8292]
### JEP-370 Foreign-Memory Access API (Incubator)
https://openjdk.java.net/jeps/370
> The foreign-memory access API will initially be provided as an incubating module, named jdk.incubator.foreign, in a package of the same name.

### Documentation for `jdk.incubator.foreign`
http://cr.openjdk.java.net/~mcimadamore/panama/memaccess_javadoc/jdk/incubator/foreign/package-summary.html

### Code for `jdk.incubator.foreign`
https://github.com/ibmruntimes/openj9-openjdk-jdk14/tree/openj9/src/jdk.incubator.foreign/share/classes/jdk/incubator/foreign

### OpenJ9 Support for `jdk.incubator.foreign`

OpenJ9 has its own `MethodHandle` implementation. The following is required in order to support `jdk.incubator.foreign`:

1. Implement [jdk.internal.access.JavaLangInvokeAccess](https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/src/java.base/share/classes/jdk/internal/access/JavaLangInvokeAccess.java) interface (`java.lang.invoke.JavaLangInvokeAccessImpl`).
    - It gets used by [jdk.incubator.foreign.MemoryHandles](https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/src/jdk.incubator.foreign/share/classes/jdk/incubator/foreign/MemoryHandles.java) and [jdk.internal.foreign.LayoutPath](https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/fd8259d4bc7ccf587baa80c63295e58711842cb7/src/jdk.incubator.foreign/share/classes/jdk/internal/foreign/LayoutPath.java).
    - Only the following [JavaLangInvokeAccess](https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/src/java.base/share/classes/jdk/internal/access/JavaLangInvokeAccess.java) methods are needed:
        ```
        JavaLangInvokeAccess.memoryAddressViewVarHandle
        JavaLangInvokeAccess.memoryAddressCarrier
        JavaLangInvokeAccess.memoryAddressByteOrder
        JavaLangInvokeAccess.memoryAddressOffset
        JavaLangInvokeAccess.memoryAddressStrides
        ```
2. Set the implementation of `JavaLangInvokeAccess` in `SharedSecrets`:
    ```
    java.lang.System.afterClinitInitialization {
        ...
        jdk.internal.access.SharedSecrets.setJavaLangInvokeAccess(new JavaLangInvokeAccessImpl());
        ...
    }
    ```
3. We will need to implement `java.lang.invoke.MemoryAddressViewVarHandle`. `JavaLangInvokeAccess.memoryAddressViewVarHandle` returns an instance of `MemoryAddressViewVarHandle`. `MemoryAddressViewVarHandle` should be similar to [java.lang.invoke.ByteBufferViewVarHandle](https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/ByteBufferViewVarHandle.java).

### Deadline

Code needs to be delivered for this feature by 7th February 2020; before the next cut-off date.

### Note

There is ongoing work to consume the OpenJDK `MethodHandle` implementation in OpenJ9 (@fengxue-IS Will this work be complete by the above deadline? If yes, we can avoid all this work). This work will deprecate OpenJ9's custom implementation of `MethodHandle` and allow us to support the `jdk.incubator.foreign` package without any additional OpenJ9-specific changes. The changes proposed in this issue will need to be removed once OpenJ9 utilizes the OpenJDK `MethodHandle` implementation.

**Comment by babsingh** [comment]
fyi - @DanHeidinga @tajila

**Comment by babsingh** [comment]
@DanHeidinga Shall I implement the above design?

**Comment by DanHeidinga** [comment]
@babsingh and I discussed.  He's going to take another look at the OpenJDK code and see if we can reuse the `MemoryAddressViewVarHandle` implementation by adding support for any new MH / Unsafe / etc calls used by it.

**Comment by babsingh** [comment]
> Reuse the `MemoryAddressViewVarHandle` implementation by adding support for any new `MH` / `Unsafe` / etc calls used by it

Here are the changes to accomplish the above task:
- OpenJ9 changes: https://github.com/eclipse/openj9/pull/8330
- OpenJDK changes: https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/6

**Comment by babsingh** [comment]
JEP-370 test-suites pass completely with the below changes. 
1. https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/6: ` Allow GENSRC_VARHANDLES in OpenJ9`
2. https://github.com/eclipse/openj9/pull/8330: `Support JEP-370 (Part 1)`
3. https://github.com/eclipse/openj9/pull/8460: `Support for CP String patching`
4. https://github.com/eclipse/openj9/pull/8414: `JEP-370 Implementation (Part 2)`
5. https://github.com/eclipse/openj9/pull/8501: `JEP-370 Implementation (Part 3)`

JEP-370 test-suites log output (no failures): [jep370_tests21.log](https://github.com/eclipse/openj9/files/4156546/jep370_tests21.log).

Also, personal builds with sanity testing pass with no failures.

fyi - @DanHeidinga @fengxue-IS @tajila
