### ISSUE TITLE
Building Quarkus with Openj9 Java SDK8 failed with project 'quarkus-documentation'

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#8303]
The process of building Quarkus with Openj9 Java SDK8 failed with project ' quarkus-documentation'. The process hung when doing 

```
Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-stdlib/9.2.6.0/jruby-stdlib-9.2.6.0.jar (11 MB at 3.6 MB/s)

or:
Downloaded from central: https://repo.maven.apache.org/maven2/org/jruby/jruby-core/9.2.6.0/jruby-core-9.2.6.0.jar (10 MB at 1.5 MB/s)
```
Originally failure job:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1046/console

Rerun link with only project quarkus-documentation enabled:
https://ci.adoptopenjdk.net//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=external/quarkus&PLATFORM=x86-64_linux&TARGET=quarkus_java_test&SDK_RESOURCE=nightly&DOCKER_REQUIRED=true&ADOPTOPENJDK_REPO=https://github.com/sophia-guo/openjdk-tests.git&ADOPTOPENJDK_BRANCH=hang

**Comment by sophia-guo** [comment]
The curious thing is during the process this specific download actually happened twice. First time succeed and second time hang. If using wget download directly it will always succeed.  It just looks like hang during the download but most probably there is some other hidden issue .

**Comment by smlambert** [comment]
Are we able to reduce the maven test list to just quarkus:documentation and see the hang?  If so, can we reconfirm that it passes without issue on hotspot (I know it passed when it was first tried, but want to confirm is still the case).

**Comment by sophia-guo** [comment]
Yes, the rerun link mentioned before is using my personal branch : hang, which will only build against project quarkus:documentation. Also using this branch against hotspot didn't hit the hang issue. 

https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1060/console

**Comment by smlambert** [comment]
Maybe can add --debug maven option to see if any additional clues on what is happening

**Comment by sophia-guo** [comment]
Build with --debug:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1069/ 

Note: This issue happened to latest release openjdk8-openj9 dockerimage:

```
05:03:49  JAVA_BIN is: /opt/java/openjdk/bin
05:03:49  openjdk version "1.8.0_222"
05:03:49  OpenJDK Runtime Environment (build 1.8.0_222-b10)
05:03:49  Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
05:03:49  OpenJ9   - 0f66c6431
05:03:49  OMR      - ec782f26
05:03:49  JCL      - f147086df1e based on jdk8u222-b10)
```

Rerun with nightly openjdk8-openj9 dockerimage do not hit this issue

```
04:53:01  JAVA_BIN is: /opt/java/openjdk/bin
04:53:01  openjdk version "1.8.0_242"
04:53:01  OpenJDK Runtime Environment (build 1.8.0_242-202001020429-b05)
04:53:01  Eclipse OpenJ9 VM (build master-a873af9c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200102_486 (JIT enabled, AOT enabled)
04:53:01  OpenJ9   - a873af9c2
04:53:01  OMR      - ce7fdb230
04:53:01  JCL      - fbdf154d48b based on jdk8u242-b05)
```
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1068/consoleFull

Triggered a job using nightly openjdk8-openj9 dockerimage to see if it will hit issue #8237 
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder_Sandbox/1070/

**Comment by pshipton** [comment]
@keithc-ca already discovered that #8237 is fixed by using the latest jdk8 release. There is still an issue with jdk11, which is being fixed.

**Comment by keithc-ca** [comment]
Based on the [comment](https://github.com/eclipse/openj9/issues/8303#issuecomment-574982736) above, should this not be closed?

**Comment by DanHeidinga** [comment]
@sophia-guo Does this occur with OpenJ9 JDK 11?

**Comment by sophia-guo** [comment]
Same as jdk8. Running by former release jdk11 job will hang. With recent nightly one no hang issue:

JDK8 version:

```
12:02:33  JAVA_BIN is: /opt/java/openjdk/bin
12:02:34  openjdk version "11.0.4" 2019-07-16
12:02:34  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
12:02:34  Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
12:02:34  OpenJ9   - 0f66c6431
12:02:34  OMR      - ec782f26
12:02:34  JCL      - fa49279450 based on jdk-11.0.4+11)
```
build:
https://ci.adoptopenjdk.net/job/Grinder_Sandbox/1072/

JDK11:

```
12:35:24  openjdk version "11.0.6" 2020-01-14
12:35:24  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+9-202001012124)
12:35:24  Eclipse OpenJ9 VM AdoptOpenJDK (build master-a873af9c2, JRE 11 Linux amd64-64-Bit Compressed References 20200101_416 (JIT enabled, AOT enabled)
12:35:24  OpenJ9   - a873af9c2
12:35:24  OMR      - ce7fdb230
12:35:24  JCL      - 15f5dcd507 based on jdk-11.0.6+9)
12:35:24  /quarkus
```
build:
https://ci.adoptopenjdk.net/job/Grinder_Sandbox/1073/

**Comment by keithc-ca** [comment]
Both of those jobs appeared to completed downloading all jars.
The job for jdk11 completed successfully; @sophia-guo aborted the job for jdk8.
What remains to be done before this issue can be closed?

**Comment by sophia-guo** [comment]
My bad.

JDK8 should be JDK11 release version. Make it clear I have edited the comment https://github.com/eclipse/openj9/issues/8303#issuecomment-575266950. 

The job with JDK11 release was cancelled for 'hang' problem.

**Comment by DanHeidinga** [comment]
Based on what I've understood, this isn't an issue with the nightly builds.  Closing
