### ISSUE TITLE
Validate OpenJDK extensions ObjectInputStream patch

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8311]
The OpenJDK extensions for OpenJ9 contain a patch to ObjectInputStream to cache the ClassLoader. The latest OpenJDK code has modified ObjectInputStream, and the patch needs to be validated that it is still correct and properly covers the different code paths.

The changes to java/io/ObjectInputStream.java are currrently in the openj9-staging branch.  One way to view the changes is to visit https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/openj9...openj9-staging#files_bucket and search for ObjectInputStream

Looking at ObjectInputStream.java, this comparison shows the original OpenJ9 patch. https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/14b4bda..b1e19eb

The changes made to OpenJDK ObjectInputStream.java
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/14b4bda..de2fa87

The merge correction
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/c327995

The resulting latest ObjectInputStream.java with OpenJ9 patch applied
https://github.com/ibmruntimes/openj9-openjdk-jdk8/compare/14b4bda..e6095d9

**Comment by cathyzhyi** [comment]
@vijaysun-omr  and I stared at the patches and our conclusion is that the patch looks good 
1)  It's functionally correct

The new patch from openjdk created a wrapper ```private final Object readObject(Class<?> type)```
which can be merged with our old wrapper  ```private Object readObjectImpl(Class caller)```
 and becomes  ```private final Object readObject(Class<?> type, Class caller)```

2) doesn't disable the existing opt to `readObject()` 

JIT still replaces `readObject()` with `redirectedReadObject(ObjectInputStream iStream, Class caller)`.  Notice this opt currently doesn't apply to the new API `readString()` but it's easy to do so with some work.

**Comment by pshipton** [comment]
Thanks, I've promoted the latest OpenJDK content.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/8318
