### ISSUE TITLE
OpenJ9: java.lang.ref.Reference.clear() unexpectedly called

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8322]
https://github.com/AdoptOpenJDK/openjdk-support/issues/42

**Comment by pshipton** [comment]
@dmitripivkine can you pls take a look, and put any response into the AdoptOpenJDK issue, not here.

**Comment by dmitripivkine** [comment]
@LinHu2016 Would you please take a look too. There was your change https://github.com/eclipse/openj9/pull/900

**Comment by dmitripivkine** [comment]
I would like to discuss here before answer in original item:
GC does not `clear()` directly so there is no problem. `clear()` is called from `enqueue()' (which is Java code). The update https://github.com/eclipse/openj9/pull/900 has been requested by spec change for Java 9 and according it seems reference must be cleared before enqueued.
@DanHeidinga Any comments?

**Comment by jcflack** [comment]
In the `hg.openjdk.java.net/jdk9` sources, the spec change was handled by, yes, clearing the reference before it is enqueued, but *by directly clearing the field, not by calling the `clear` virtual method*.

http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/65464a307408/src/java.base/share/classes/java/lang/ref/Reference.java#l301

This was the commit:

http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/bc1bf2be03bc

I am not sure why it would be done differently here.

**Comment by DanHeidinga** [comment]
Looking at our `clear()` method, it does two things: set the referent to null and change the state: https://github.com/eclipse/openj9/blob/9555017657333e4d865011e144e136b22fb1b8f1/jcl/src/java.base/share/classes/java/lang/ref/Reference.java#L117-L125

We can move that to a `clearImpl()` method and call it from both `enqueue` and from `clear`.  This keeps the correct state change behaviour and avoids the concern about the GC causing `clear` to be called.

**Comment by jcflack** [comment]
That approach sounds like the right approach; for the benefit of future archaeologists, I would just amend the description to say "the concern about `enqueue` causing `clear` to be called." (GC already Does The Right Thing.)

**Comment by DanHeidinga** [comment]
> (GC already Does The Right Thing.)

When I look through our code, the referent is nulled by the GC calling `enqueueImpl()` which eventually calls `enqueue`.  The GC isn't directly nulling the slot as it also requires a state field to be modified.   Our approach was to commonize that logic in java.
