### ISSUE TITLE
ASSERTION FAILED at ./MarkingScheme.hpp:71

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8341]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_Nightly/255
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_linux_xl_Nightly/255
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly/258
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_windows_Nightly/255
TestJlmRemoteMemoryAuth_SE80_Linux_0
TestJlmRemoteClassNoAuth_SE80_Linux_0
TestJlmRemoteThreadNoAuth_SE80_Linux_0
TestJlmRemoteMemoryNoAuth_SE80_Linux_0
TestJlmRemoteClassNoAuth_SE80_0
ASSERTION FAILED ** at ./MarkingScheme.hpp:71: ((false))

**Comment by gacholio** [comment]
I believe this will be fixed by reverting https://github.com/eclipse/omr/pull/4725

May also need https://github.com/eclipse/omr/pull/4737 to be merged.

**Comment by pshipton** [comment]
Also causing failures in extended.system testing.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_Nightly/257/
ObjectTreeLoadTest_0

**Comment by pshipton** [comment]
@liqunl

**Comment by liqunl** [comment]
I have reverted the change in https://github.com/eclipse/omr/pull/4739.

**Comment by liqunl** [comment]
Looking at one internal failure, it seems like we failed to heapify a local object. This is just a theory based on analysis of a core dump. I'm trying to get a trace log from a bad method.

**Comment by cathyzhyi** [comment]
@liqunl Is this issue still needed?

**Comment by liqunl** [comment]
No, this can be closed as the problematic change had been reverted and then re-enabled with a fix. See issue https://github.com/eclipse/omr/issues/4740

**Comment by cathyzhyi** [comment]
@pshipton Hey Peter, could you help to close this one? Thanks!
