### ISSUE TITLE
curl: (56) GnuTLS recv error (-54): Error in the pull function

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8343]
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/50/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
03:10:29  get jdk binary...
03:10:29  curl -OLJSks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_s390x_linux_xl_Nightly/51/OpenJ9-JDK11-s390x_linux_xl-20200120-032032.tar.gz
03:14:09  curl: (56) GnuTLS recv error (-54): Error in the pull function.
03:14:09  curl error code: 56. Sleep 300 secs, then retry 1...
03:19:05  curl -OLJSks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_s390x_linux_xl_Nightly/51/OpenJ9-JDK11-s390x_linux_xl-20200120-032032.tar.gz
03:19:05  curl: (23) Failed writing body (0 != 15601)
03:19:05  curl error code: 23. Sleep 300 secs, then retry 2...
03:24:16  curl -OLJSks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK11_s390x_linux_xl_Nightly/51/OpenJ9-JDK11-s390x_linux_xl-20200120-032032.tar.gz
03:24:16  curl: (23) Failed writing body (0 != 15601)
```

**Comment by jdekonin** [comment]
File is clearly present as other pipelines have successfully retrieved and used the same binary download.  I found this doing a google search, might be how we have git compiled if it was indeed compiled from source and not via package manager.

Failure happened on ub16-390-6 (or ub16-390-2) once the updated machines configuration is posted.

https://devopscube.com/gnutls-handshake-failed-aws-codecommit/

**Comment by AdamBrousseau** [comment]
similar #7900 ?
We saw similar errors recently internally on the zlinux Fyre machines. Hasn't been seen since the network for those instances was fixed, at least not that I am aware.

**Comment by pshipton** [comment]
This is happening quite often and interfering with proper testing and promoting acceptance build.

**Comment by AdamBrousseau** [comment]
re: git
This is curl-ing the file from Artifactory. Nothing to do with Git.

Could be how we're compiling curl
- https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/006a98886918ce9b00d083edda13c016957a8c2d/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/curl/tasks/main.yml
- https://stackoverflow.com/questions/38378914/git-error-rpc-failed-curl-56-gnutls

Although, looking at the zlinux machines, seems they aren't using playbook curl since version doesn't match
```
jenkins@openj902:~$ curl --version
curl 7.47.0 (s390x-ibm-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```
Not sure what to do. Could remove the -s from the curl and/or add -v temporarily. Could build our own retry & delay since the error seems to change after the build-in retry kicks in.

**Comment by AdamBrousseau** [comment]
Opened https://github.com/AdoptOpenJDK/openjdk-tests/pull/1572 to help debug curl side.

**Comment by pshipton** [comment]
On the bright side, while this occurred quite a bit two nights ago, we didn't see any of these last night.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly/272

**Comment by AdamBrousseau** [comment]
My [change](https://github.com/AdoptOpenJDK/openjdk-tests/pull/1572) was just merged so the next time this happens we will hopefully have useful output.

**Comment by pshipton** [comment]
This hasn't re-occurred so I'll close it.
