### ISSUE TITLE
Allow double mapping by default on Linux Platforms

### ISSUE THREAD

**Issue by bragaigor** [eclipse/openj9#8349]
Created this issue to keep track of updates needed to allow double mapping by default on Linux platforms. None of the PRs depend on each other, this is just to organize the updates.

OMR: https://github.com/eclipse/omr/pull/4735 - merged

OpenJ9: https://github.com/eclipse/openj9/pull/8350 - merged

OpenJDK-tests: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1560 - merged

OpenJ9-docs: https://github.com/eclipse/openj9-docs/pull/476 - merged

**Comment by bragaigor** [comment]
All required updates have been merged. Closing this issue.

**Comment by pshipton** [comment]
Note I believe this change is causing failures that started in the builds last night.
https://github.com/eclipse/openj9/issues/8385
https://github.com/eclipse/openj9/issues/8386

Unless these can be quickly fixed or we can justify excluding them, my preference is to back out the change until we are ready to pass all the tests. The OpenJ9 model is to always remain green (pass all the tests).

**Comment by amicic** [comment]
https://github.com/eclipse/openj9/issues/8385 has not been resolved yet. For the most part we understand the problem and have a candidate fix https://github.com/eclipse/omr/pull/4806 but it's still being scrutinized.

More personal builds have been done and no more problems have been discovered.

So we are close to re-enabled double mapping by default, but it does not seem like it will be occur before 0.19 split (my understanding it's this coming weekend).

If so, documentation update https://github.com/eclipse/openj9-docs/pull/476 should be deferred for next release @pmhayward
