### ISSUE TITLE
Investigate stack slot gaps for argument save area in private linkage

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#8360]
Using the following program as a test bucket we compile it on Linux on Z and take a look at the log:
```
class Test {
    public static void main(String[] args) {
        System.out.println(foo(200l, 3.14159, -10, 6.67300,
                               200l, 3.14159, -10, 6.67300));
        System.out.println(foo(200l, 3.14159, -10, 6.67300,
                               200l, 3.14159, -10, 6.67300));
    }

    public static long foo(long a, double b, int c, double d,
                           long e, double f, int g, double h) {
        return a == e && b == f && c == g && d == h ? 1 : 0;
    }
}
```

The trace log for `foo` when ran with the following options:
```
java "-Xjit:limit={Test.foo*}(tracefull,tracecg,log=log.trace,count=1,lastoptindex=0),disableasynccompilation" Test
```

We can see some gaps in the locations where arguments are placed on the stack:
```
     0x3ff69cc2ee0 00000000 [     0x3ff68ce9e80] e3 10 50 60 00 04          LG      GPR1,#369 96(GPR5)
     0x3ff69cc2ee6 00000006 [     0x3ff68cea040] 68 00 50 50                LD      FPR0,#370 80(GPR5)
     0x3ff69cc2eea 0000000a [     0x3ff68cea1e0] 58 20 50 48                L       GPR2,#371 72(GPR5)
     0x3ff69cc2eee 0000000e [     0x3ff68cea380] 68 20 50 38                LD      FPR2,#372 56(GPR5)
     0x3ff69cc2ef2 00000012 [     0x3ff68cea520] e3 30 50 28 00 04          LG      GPR3,#373 40(GPR5)
     0x3ff69cc2ef8 00000018 [     0x3ff68cea6c0] 68 40 50 18                LD      FPR4,#374 24(GPR5)
     0x3ff69cc2efc 0000001c [     0x3ff68cea860] 68 60 50 00                LD      FPR6,#375 0(GPR5)
     0x3ff69cc2f00 00000020 [     0x3ff68c63980]                            PROC
     0x3ff69cc2f00 00000020 [     0x3ff68ced1a0] e3 e0 5f f8 ff 24          STG     GPR14,#388 -8(GPR5)
     0x3ff69cc2f06 00000026 [     0x3ff68ced340] e3 50 5f c8 ff 71          LAY     GPR5,#389 -56(GPR5)
     0x3ff69cc2f0c 0000002c [     0x3ff68ced4e0] e3 50 d0 50 00 21          CLG     GPR5,#390 80(GPR13)
     0x3ff69cc2f12 00000032 [     0x3ff68ced680] a7 44 01 65                BRC     BM(0x4), Snippet Label L0036, labelTargetAddr=0x000003FF69CC2FD4
     0x3ff69cc2f16 00000036 [     0x3ff68ced870]                            Label L0037:
     0x3ff69cc2f16 00000036 [     0x3ff68ceda40] e3 10 50 98 00 24          STG     GPR1,#391 152(GPR5)
     0x3ff69cc2f1c 0000003c [     0x3ff68cedbe0] 60 00 50 88                STD     FPR0,#392 136(GPR5)
     0x3ff69cc2f20 00000040 [     0x3ff68cedd80] 50 20 50 80                ST      GPR2,#393 128(GPR5)
     0x3ff69cc2f24 00000044 [     0x3ff68cedf20] 60 20 50 70                STD     FPR2,#394 112(GPR5)
     0x3ff69cc2f28 00000048 [     0x3ff68cee0c0] e3 30 50 60 00 24          STG     GPR3,#395 96(GPR5)
     0x3ff69cc2f2e 0000004e [     0x3ff68cee260] 60 40 50 50                STD     FPR4,#396 80(GPR5)
     0x3ff69cc2f32 00000052 [     0x3ff68cee400] 60 60 50 38                STD     FPR6,#397 56(GPR5)
```

It would appear that the interpreter entry point may be forcing our hand here. The offsets seem to be 16-byte aligned at times. For example distance between FPR0 and GPR1 is 16 bytes. Digging further the offsets seem to be set in [1] [2] [3] on various platforms.

It seems baked right into the code that we want `long` and `double` arguments to take up 2x8 == 16 byte slots on 64-bit.

[1] https://github.com/eclipse/openj9/blob/d736b4f9722d5b5be2a483573d4bd3c15a8685e0/runtime/compiler/z/codegen/S390PrivateLinkage.cpp#L3382-L3401
[2] https://github.com/eclipse/openj9/blob/d736b4f9722d5b5be2a483573d4bd3c15a8685e0/runtime/compiler/p/codegen/PPCPrivateLinkage.cpp#L583-L597
[3] https://github.com/eclipse/openj9/blob/d736b4f9722d5b5be2a483573d4bd3c15a8685e0/runtime/compiler/x/amd64/codegen/AMD64PrivateLinkage.cpp#L711-L715

**Comment by fjeremic** [comment]
@joransiu FYI this is the reason why stack slots look spread apart. @gacholio / @DanHeidinga I think we have to follow the interpreter convention for the incoming arguments. Do you might know why `long` and `double` arguments need 16 byte slots on 64-bit?

**Comment by DanHeidinga** [comment]
Primitive longs and doubles always consume two stackslots.  This is required by the jvm specification.

**Comment by gacholio** [comment]
And, as always, the data is stored in the lower address slot, as ints are on 64-bit.

**Comment by fjeremic** [comment]
> Primitive longs and doubles always consume two stackslots. This is required by the jvm specification.

Is a stack slot defined as 32-bit or 64-bit?

**Comment by gacholio** [comment]
A `slot` is a uintptr_t.  The reason for the spec is that the classfile has no idea whether it's going to run on 32/64/128 bit, so all slot numbers are pointer-size agnostic.

**Comment by gacholio** [comment]
For reference, here's the VM code that loads a long from the stack:

https://github.com/eclipse/openj9/blob/41598c546e17c9c84e1557a5dbf731f7da18a52e/runtime/vm/BytecodeInterpreter.hpp#L4748-L4759

Note the -1 on line 4754.

**Comment by fjeremic** [comment]
Thanks for the explanations, that makes sense now. I'll summarize this in a small comment which we can add near the JIT code so it is not a complete mystery to the next person who reads it.

**Comment by fjeremic** [comment]
Just for reference the following section in the specification talks about `long` and `double` variables taking up two stack slots:

> A value of type long or type double occupies two consecutive local variables. Such a value may only be addressed using the lesser index. For example, a value of type double stored in the local variable array at index n actually occupies the local variables with indices n and n+1; however, the local variable at index n+1 cannot be loaded from. It can be stored into. However, doing so invalidates the contents of local variable n.
>
> The Java Virtual Machine does not require n to be even. In intuitive terms, values of types long and double need not be 64-bit aligned in the local variables array. Implementors are free to decide the appropriate way to represent such values using the two local variables reserved for the value. 

[1] https://docs.oracle.com/javase/specs/jvms/se12/html/jvms-2.html#jvms-2.6.1
