### ISSUE TITLE
Update machine type determination on Linux on Z

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#837]
@jjohnst-us updated the machine type termination on z/TPF to use `uname`. We are currently using 

```
FILE * fp = fopen("/proc/cpuinfo", "r");
```

Which is not as robust. We should consolidate the two `#ifdefs` and use the same logic via `uname` to determine the processor ID on Linux.

See https://github.com/eclipse/openj9/pull/810#issuecomment-351414302 for more information.

**Comment by joransiu** [comment]
I wonder if zTPF's uname is unique here.  I ran the `uname()` on RedHat and SLES, and `utsname.machine` is `s390x` instead of the machine code.

**Comment by fjeremic** [comment]
Interesting. It must be unique to z/TPF then. Are you aware of any similar utility we can use? The current `fopen` seems at least to me not like a robust solution.

**Comment by fjeremic** [comment]
This code has been removed as part of the new processor detection improvements.
