### ISSUE TITLE
openjdk.sanity xlinux ERROR: No Xvfb installations defined

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8376]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_linux_Personal/1
cent6-x64-6
`12:41:53  ERROR: No Xvfb installations defined, please define one in the configuration. Once defined you’ll need to choose one under Advanced options for Xvfb plugin job settings and save job configuration.`

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/issues/7520 mentioned Xvfb, which was supposed to be resolved by eclipse-cbi/jiro#61 but apparently not.

@jdekonin @smlambert Seems we need Xvfb

**Comment by smlambert** [comment]
To resolve this error on a machine we have admin access to, one would go to Manage Jenkins -> Global Tool Configuration (at the bottom of the page) and add a default xvfb installation (as shown):

<img width="1176" alt="Screen Shot 2020-01-22 at 4 32 32 PM" src="https://user-images.githubusercontent.com/2836948/72936276-da670600-3d34-11ea-9c54-51bf3412a1b8.png">

**Comment by DanHeidinga** [comment]
Is this something we need an Eclipse bug opened for?

**Comment by pshipton** [comment]
@smlambert I think you were going to help resolve this?

**Comment by smlambert** [comment]
https://github.com/eclipse-cbi/jiro/issues/92

**Comment by pshipton** [comment]
Testing change here
https://ci.eclipse.org/openj9/view/Test/job/Grinder/688/

**Comment by pshipton** [comment]
The xlinux build has passed. Thanks Shelley.
