### ISSUE TITLE
Mauve tests hanging with -Xgcpolicy:balanced

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8386]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_ppc64le_linux_Nightly/1088
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/1031
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_s390x_linux_Nightly/1082
**MauveMultiThreadLoadTest_special_13**
variation: Mode551
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced 
**MauveMultiThreadLoadTest_special_14**
variation: Mode553
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xgcpolicy:balanced -Xjit:count=0 
**MauveMultiThreadLoadTest_special_15**
variation: Mode554
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:balanced -XXgc:tarokEnableExpensiveAssertions,fvtest_tarokPGCRotateCollectors -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve 
**MauveMultiThreadLoadTest_special_16**
variation: Mode556
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:balanced -Xquickstart -Xjit 
**MauveMultiThreadLoadTest_special_17**
variation: Mode557
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xgcpolicy:balanced -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0

MauveSingleInvocationLoadTest_special_13
MauveSingleInvocationLoadTest_special_14
MauveSingleInvocationLoadTest_special_15
MauveSingleInvocationLoadTest_special_16
MauveSingleInvocationLoadTest_special_17

The tests are hanging.

Changes from previous passing nightly build
1f23268...229e6e2
https://github.com/eclipse/omr/compare/e1b09af...ab53ed3

**Comment by pshipton** [comment]
@amicic @bragaigor could this also be a double mapping problem?

**Comment by amicic** [comment]
quite possible

**Comment by amicic** [comment]
I was able to reproduce this. Seems like a shutdown problems. Not a deadlock though. A thread is spinning. From gdb stacktrace not clear where, but CPU profile shows this (not so suprising): 

```
  34.88%  load-0           libj9gc29.so        [.] _ZN21MM_VLHGCAccessBarrier28jniGetPrimitiveArrayCriticalEP10J9VMThreadP7_jarrayPh
   8.81%  load-0           libj9vm29.so        [.] getBooleanField
   8.63%  load-0           libj9vm29.so        [.] getIntField
   7.23%  load-0           libzip.so           [.] Java_java_util_zip_Deflater_deflateBytes
   6.70%  load-0           libj9vm29.so        [.] getObjectField
   4.59%  load-0           perf-17921.map      [.] 0x00007f399ebc3304
   4.43%  load-0           perf-17921.map      [.] 0x00007f399ebc3086
   2.87%  load-0           perf-17921.map      [.] 0x00007f399ebc30a0
   2.58%  load-0           libj9gc29.so        [.] j9gc_objaccess_jniGetPrimitiveArrayCritical
   1.65%  load-0           libj9gc29.so        [.] _ZN22GC_ArrayletObjectModel17getArrayletLayoutEP7J9Classmm
```
