### ISSUE TITLE
Support Notarization of Adopt builds before Feb 22

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#8389]
There are some recent OpenJDK changes to support code signing of libraries and executables on OSX during the build process:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/1107ec4d46350db528981359ce5ebc44da45f907

Unfortunately, the OpenJ9 libraries are not participating correctly in this as seen in this build output (search for the "issues" section):
https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma113/v4/e2/4d/24/e24d24c7-ead4-4b8d-2943-22278eb2344e/developer_log.json?accessKey=1580001662_8949096374711730461_x6qivsPfqECZ0WKcb317EFz6nYuCGrT1%2FuakOdih3AW2cuhHoA5XVzTHYB%2BF2vyVqJ3ny6V9HGgOS3mg6auFGAF39McbJOuOtO4g4NejnRSxvLHpJPUNRAzQZ0L5fHd0NklP1Jhonvz68fZlg70TDxvW4hYIgTcQt13PeXQGFXQ%3D

The task here is to enable the code signing for OpenJ9 libraries and executables.

**Comment by DanHeidinga** [comment]
@gdams can you confirm the date Adopt is aiming to have the notarization work complete?  I wrote down Feb 22 following our discussion but google is indicating Feb 3.  I suspect I wrote it down wrong but confirmation would be appreciated :)

**Comment by keithc-ca** [comment]
See also:
- https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/9
- https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/165
- https://github.com/AdoptOpenJDK/openjdk-build/pull/1510

**Comment by keithc-ca** [comment]
@DanHeidinga I can't access the second URL in description (at apple.com). Can you provide a sample of that build output or a better URL?

**Comment by DanHeidinga** [comment]
I don't have a cached copy of that information.  It was showing the warnings / errors when submitting a build to the apple notarization service that indicated the OpenJ9 libraries were not notarized & didn't have secured timestamps(?).

Maybe @gdams has a more recent link he can share?

**Comment by keithc-ca** [comment]
The changes linked above omitted signing `libcrypto.dylib` for builds configured with `--enable-openssl-bundling` - that was addressed by:
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/371
* https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/372 (for 0.18.1)
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/261
* https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/262 (for 0.18.1)
* https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/11
* https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/167
