### ISSUE TITLE
OpenJDK8-OpenJ9 Windows sun.management.FileSystem.isAccessUserOnly(File) incorrectly returns false

### ISSUE THREAD

**Issue by brianeray** [eclipse/openj9#8393]
Java -version output
--------------------
Problem Java:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20191016_492 (JIT enabled, AOT
enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)
```

Control Java 1:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```

Control Java 2:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Zulu 8.42.0.21-CA-win64) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.21-CA-win64) (build 25.232-b18, mixed mode)
```

Summary of problem
------------------
On Windows, specifically Windows 8.1 Pro and by some inference Windows Server 2012 R2 Standard, the implementaton of `sun.management.FileSystem.isAccessUserOnly(File)` is returning `false` under the OpenJ9 build given the following NT filesystem ACLs:

```
c:>icacls zzTestUserOnlyFile.txt
zzTestUserOnlyFile.txt BLAH\SomeWinUser:(R,W)
```

Ie the file is readable and writeable only by `BLAH\SomeWinUser`. This user is also the owner of the file.

This causes a downstream blocker when trying to configure a pseudosecure JMX port via locked-down password and access files--in this case for Tomcat testing--in that the JVM thinks that the password file is not sufficiently restricted and immediately exits.

Diagnostic files
----------------
I used a Groovy 2.5.8 shell, the script below, and the three JDKs mentioned above to isolate the problem.

```
import sun.management.FileSystem

fs = FileSystem.open()
isAccessUserOnly = fs.isAccessUserOnly( new File( "./zzTestUserOnlyFile.txt" ) )
println "isAccessUserOnly=$isAccessUserOnly"
```

And for each JVM + JDK,

```
isAccessUserOnly=false  //OpenJ9
isAccessUserOnly=true  //HotSpot
isAccessUserOnly=true  //Zulu HotSpot, for good measure
```

In larger context of the Tomcat use case it chokes thus.

```
Error: Password file read access must be restricted: C:/Tomcat8.5/conf/jmx2.password
sun.management.AgentConfigurationError
	at sun.management.jmxremote.ConnectorBootstrap.checkPasswordFile(ConnectorBootstrap.java:577)
	at sun.management.jmxremote.ConnectorBootstrap.startRemoteConnectorServer(ConnectorBootstrap.java:426)
	at sun.management.Agent.startAgent(Agent.java:262)
	at sun.management.Agent.startAgent(Agent.java:452)
	at java.lang.System.startSNMPAgent(Native Method)
	at java.lang.Thread.completeInitialization(Thread.java:168)
	at java.lang.J9VMInternals.completeInitialization(J9VMInternals.java:74)
```

**Comment by brianeray** [comment]
@pshipton this is my first issue for this project. If it requires any further replication or information, let me know.

**Comment by pshipton** [comment]
Does it not happen on Windows 10, or you just don't know?

**Comment by brianeray** [comment]
Good idea. I have some Win 10 Enterprise VMs available. Testing on one of them ...

Yes. Replicated exactly.

```
isAccessUserOnly=false  //OpenJ9
isAccessUserOnly=true   //HotSpot
isAccessUserOnly=true   //Zulu HotSpot
```

As a side note anybody attempting replication should be running as the file owner (to simulate my Tomcat use case), otherwise the two HotSpot runs will not run to completion but rather throw `IOException: Access is denied` while OpenJ9 still finishes and returns `false`.

That may be another clue. Perhaps that J9 code path is short-circuited, not looking at the file at all. I'd anticipate that `IOException` across the board with all three Javas when running as somebody other than the file owner.

**Comment by pshipton** [comment]
I got `zzTest.txt PETE2019W1\Administrator:(R,W)` setup, but isAccessUserOnly is returning false with Hotspot. I'll try creating a non-Administrator user.

**Comment by brianeray** [comment]
That'll align more closely with the user in my case; which is a less-privileged service user in this Active Domain.

**Comment by pshipton** [comment]
That worked, I've managed to recreate the isAccessUserOnly difference in behavior.

**Comment by brianeray** [comment]
Awesome! So it's not just some crazy idiosyncracy on my end.

Another scenario testing the inverse. This file is pretty much readable to anybody.

```
c:>icacls zzTestWideOpenFile.txt
zzTestWideOpenFile.txt BUILTIN\Administrators:(I)(F)
                       NT AUTHORITY\SYSTEM:(I)(F)
                       BUILTIN\Users:(I)(RX)
                       NT AUTHORITY\Authenticated Users:(I)(M)
```

Behavior as expected across the board.

```
isAccessUserOnly=false //OpenJ9
isAccessUserOnly=false //HotSpot
isAccessUserOnly=false //Zulu HotSpot
```

**Comment by brianeray** [comment]
Last test since realizing I'm one GA build behind the times.

```
java -version

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Windows 8.1 amd64-64-Bit Compressed References 20200122_564 (JIT enabled, AOT
enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)
```

Behavior in the "bug" use case is identical to 232.

```
isAccessUserOnly=false //OpenJ9 0.18.1/1.8.0_242-b08
```

**Comment by pshipton** [comment]
I now understand why it doesn't work. Basically OpenJ9 has it's own implementation of the FileSystemImpl natives, and it's not implemented properly for Windows.

**Comment by brianeray** [comment]
Interesting. If it's a `FileSystemImpl` [like the one here](https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/windows/native/sun/management/FileSystemImpl.c), that layer was the point at which I had to abort "bench debugging." C and Win32 are outside my expertise.
