### ISSUE TITLE
 MauveMultiThreadLoadTest_0 NPE PropertyDescriptor.constructorTest2

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8396]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_s390x_linux_xl_Nightly/52
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_ppc64le_linux_Nightly/267
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_Nightly/268
MauveMultiThreadLoadTest_0
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_s390x_linux_Nightly/264
MauveSingleThreadLoadTest_OpenJ9_0
MauveMultiThreadLoadTest_0
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-32_windows_Nightly/265
MauveSingleThreadLoadTest_OpenJ9_0
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Nightly/744
MauveMultiThreadLoadTest_special_13 
```
LT  00:41:22.471 - First failure detected by thread: load-13. Not creating dumps as no dump generation is requested for this load test
LT  00:41:22.471 - Test failed
LT    Failure num.  = 1
LT    Test number   = 16
LT    Test details  = 'Mauve[gnu.testlet.java.beans.PropertyDescriptor.constructorTest2]'
LT    Suite number  = 0
LT    Thread number = 13
...
LT  Test failed:
LT  java.lang.NullPointerException
LT  	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:106)
LT  	at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:71)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest2.constructor1Tests(constructorTest2.java:600)
LT  	at gnu.testlet.java.beans.PropertyDescriptor.constructorTest2.test(constructorTest2.java:700)
LT  	at sun.reflect.GeneratedMethodAccessor2664.invoke(Unknown Source)
LT  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.lang.reflect.Method.invoke(Method.java:498)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
LT  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
LT  	at java.lang.Thread.run(Thread.java:821)
```

We've seen this before but it was fixed https://github.com/eclipse/openj9/issues/6145

Changes https://github.com/eclipse/openj9/compare/229e6e2...a055a16

**Comment by pshipton** [comment]
@andrewcraik can you pls take a look, and either quickly fixed or the problematic change reverted until it can be.

**Comment by andrewcraik** [comment]
A few things landed yesterday so we'll have a look and see what's up

**Comment by hzongaro** [comment]
Shelley @smlambert  was gracious enough to launch some Grinder runs for me based on the https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_s390x_linux_xl_Nightly/52 failure for `MauveMultiThreadLoadTest_0`.

- **[Base run](https://ci.eclipse.org/openj9/view/Test/job/Grinder/612/):**  66/100 failures
- **[`aternary` generation in Escape Analysis disabled](https://ci.eclipse.org/openj9/view/Test/job/Grinder/614/):**  60/100 failures
- **[-Xjit:disableCFGSimplification](https://ci.eclipse.org/openj9/view/Test/job/Grinder/616):** 0/100 failures

So I think that suggests this issue and issue #8397 are duplicates of one another.
