### ISSUE TITLE
Cannot contact win2012r2-x86-5 

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8398]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly/265

Pls check the machine to ensure it is reachable and if it needs any manual cleanup.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
Rebooted.  Machine is back online and taking jobs.
