### ISSUE TITLE
Java 8 x64: Running application causes a segmentation error vmState=0x000503ff 

### ISSUE THREAD

**Issue by MNeuling** [eclipse/openj9#8404]
Java -version output
--------------------
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200122_564 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)

Summary of problem
------------------
My Java application crashes with Java 8 Update 242 b08 with J9 VM 0.18.1 on Windows.
The previous Java version 8 Update 232 b09 with J9 VM 0.17.0 has no problem to run it.

Unhandled exception
Type=Segmentation error vmState=0x000503ff
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFD0AFF0113 ContextFlags=0010005f
Handler1=0000000051EFBC30 Handler2=00007FFD15D5C910 InaccessibleReadAddress=00000000242E0000
RDI=0000000000CB3ED0 RSI=00000000ADD66466 RAX=000000000000536D RBX=0000000003157700
RCX=000000000000536D RDX=00000000242E0000 R8=FFFFFFFFED4602A4 R9=000000000000002F
R10=00007FFD17F68AB0 R11=0000000000000000 R12=000000000FB0CE68 R13=0000000000C92130
R14=0000000000000000 R15=000000000000FFFC
RIP=00007FFD0AFF0113 RSP=00000000110D8730 RBP=00000000110D8760 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000041a00000 (f: 1101004800.000000, d: 5.439686e-315)
XMM1 000000003dcccccd (f: 1036831936.000000, d: 5.122630e-315)
XMM2 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
XMM3 412e848000000000 (f: 0.000000, d: 1.000000e+006)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\ProgramData\DAKOSY\AppStart\java\j9\x64\1.8.242-b08\jdk8u242-b08-jre\bin\compressedrefs\j9vm29.dll
Module_base_address=00007FFD0AFA0000 Offset_in_DLL=0000000000050113

Method_being_compiled=com/sun/proxy/$Proxy1.hashCode()I
Target=2_90_20200122_564 (Windows 10 10.0 build 18363)
CPU=amd64 (16 logical CPUs) (0x7ea446000 RAM)
----------- Stack Backtrace -----------
(0x00007FFD0AFF0113 [j9vm29+0x50113])
J9_CreateJavaVM+0x90742 (0x00007FFD0B0B8602 [j9vm29+0x118602])
(0x00007FFD0AFF0265 [j9vm29+0x50265])
(0x00007FFD0B00ECF7 [j9vm29+0x6ecf7])
(0x00007FFD0B011390 [j9vm29+0x71390])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5bfc84 (0x00000000525034D4 [j9jit29+0x6534d4])
Java_java_lang_invoke_InterfaceHandle_convertITableIndexToVTableIndex+0x45c (0x0000000051F3A9AC [j9jit29+0x8a9ac])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa2f02 (0x0000000051FE6752 [j9jit29+0x136752])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa6b78 (0x0000000051FEA3C8 [j9jit29+0x13a3c8])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa0b8d (0x0000000051FE43DD [j9jit29+0x1343dd])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa52e2 (0x0000000051FE8B32 [j9jit29+0x138b32])
Java_java_lang_invoke_MutableCallSite_invalidate+0xa3cf3 (0x0000000051FE7543 [j9jit29+0x137543])
Java_java_lang_invoke_MutableCallSite_invalidate+0xac822 (0x0000000051FF0072 [j9jit29+0x140072])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7f426 (0x0000000051FC2C76 [j9jit29+0x112c76])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7d826 (0x0000000051FC1076 [j9jit29+0x111076])
Java_java_lang_invoke_MutableCallSite_invalidate+0x367e9e (0x00000000522AB6EE [j9jit29+0x3fb6ee])
Java_java_lang_invoke_MutableCallSite_invalidate+0x36a1ea (0x00000000522ADA3A [j9jit29+0x3fda3a])
Java_java_lang_invoke_MutableCallSite_invalidate+0x360a09 (0x00000000522A4259 [j9jit29+0x3f4259])
Java_java_lang_invoke_MutableCallSite_invalidate+0x35dce1 (0x00000000522A1531 [j9jit29+0x3f1531])
Java_java_lang_invoke_MutableCallSite_invalidate+0x3603d2 (0x00000000522A3C22 [j9jit29+0x3f3c22])
Java_java_lang_invoke_MutableCallSite_invalidate+0x404d49 (0x0000000052348599 [j9jit29+0x498599])
Java_java_lang_invoke_MutableCallSite_invalidate+0x405876 (0x00000000523490C6 [j9jit29+0x4990c6])
Java_java_lang_invoke_MutableCallSite_invalidate+0x262b8b (0x00000000521A63DB [j9jit29+0x2f63db])
(0x0000000051F06F26 [j9jit29+0x56f26])
(0x0000000051F08AAB [j9jit29+0x58aab])
j9port_init_library+0x2b116 (0x00007FFD15D5DAE6 [j9prt29+0x2dae6])
j9port_init_library+0x2b314 (0x00007FFD15D5DCE4 [j9prt29+0x2dce4])
(0x0000000051F0934C [j9jit29+0x5934c])
(0x0000000051F09912 [j9jit29+0x59912])
(0x0000000051F0467A [j9jit29+0x5467a])
(0x0000000051F0762E [j9jit29+0x5762e])
j9port_init_library+0x2b34f (0x00007FFD15D5DD1F [j9prt29+0x2dd1f])
(0x0000000051F08EFD [j9jit29+0x58efd])
omrthread_detach+0x1fd (0x00007FFD23DD5D6D [J9THR29+0x5d6d])
_endthreadex+0x43 (0x0000000053A81D9F [msvcr100+0x21d9f])
_endthreadex+0xdf (0x0000000053A81E3B [msvcr100+0x21e3b])
BaseThreadInitThunk+0x14 (0x00007FFD52397BD4 [KERNEL32+0x17bd4])
RtlUserThreadStart+0x21 (0x00007FFD5268CED1 [ntdll+0x6ced1])
---------------------------------------
JVMDUMP039I Speicherauszugsereignis "gpf", Detail "" um 2020/01/24 17:31:54 - bitte warten.
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von System mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\core.20200124.173154.9988.0001.dmp" an
JVMDUMP010I Speicherauszug von System in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\core.20200124.173154.9988.0001.dmp geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Java mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\javacore.20200124.173154.9988.0002.txt" an
JVMDUMP010I Speicherauszug von Java in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065

c353d431777e0618146de7fde51dca9c0dbd77be056\content\javacore.20200124.173154.9988.0002.txt geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Snap mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\Snap.20200124.173154.9988.0003.trc" an
JVMDUMP010I Speicherauszug von Snap in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\Snap.20200124.173154.9988.0003.trc geschrieben
JVMDUMP007I JVM fordert JIT-Speicherauszug mit "C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\jitdump.20200124.173154.9988.0004.dmp" an.
JVMDUMP010I Speicherauszug von JIT in C:\ProgramData\DAKOSY\AppStart\app\a8d0d16745cfb805ed065c353d431777e0618146de7fde51dca9c0dbd77be056\content\jitdump.20200124.173154.9988.0004.dmp geschrieben
JVMDUMP013I Speicherauszugsereignis "gpf", Detail "" wurde verarbeitet.

Diagnostic files
----------------
[dumps-without-core-20200124.173154.zip](https://github.com/eclipse/openj9/files/4109744/dumps-without-core-20200124.173154.zip)

The compressed core dump ist too big (about 116 MB). Please write if you need it.

**Comment by DanHeidinga** [comment]
fyi @andrewcraik

**Comment by andrewcraik** [comment]
@liqunl could you take a look since this looks 292 related?

**Comment by liqunl** [comment]
The jitdump is empty, @MNeuling How reproducible is this? Is there a small test case that I can use to reproduce the failure on my own? Otherwise could you upload the core dump?

**Comment by MNeuling** [comment]
I ran the application again in the eclipse IDE. Now the jitdump is no longer empty. 
It's not easy to build a small test case. The problem occurs while massive CDI processing. 

[dumps-without-core-20200127.132221.4868.0003.zip](https://github.com/eclipse/openj9/files/4117172/dumps-without-core-20200127.132221.4868.0003.zip)

**Comment by liqunl** [comment]
@MNeuling a jitdump records replay of the crashed compilation. In this jitdump, the compilation has finished without crash. There isn't MethodHandle related trees. I suspect some methods have to be inlined in order to reproduce the crash. Could you run the application with the following java option?
```
-Xjit:{com/sun/proxy/$Proxy1.hashCode()I}(traceFull,log=trace)
```
Then upload the trace log. The name will be `trace.xxx`, i.e. `trace.` followed by thread id, process id and time stamp, order is not specified.

Also, could you also try a run with `-Xjit:disableJProfiling`? I've seen crashes with similar call stack in jprofiler related issue, not sure if they're related but it's worth trying.

**Comment by MNeuling** [comment]
@liqunl I've tried both options.
The first run with option ```-Xjit:{com/sun/proxy/$Proxy1.hashCode()I}(traceFull,log=trace)``` doesn't crash. (see trace file)
[trace-13852.5987.20200128.110627.13852.zip](https://github.com/eclipse/openj9/files/4121869/trace-13852.5987.20200128.110627.13852.zip)

The second run with option ```-Xjit:disableJProfiling``` crashed like running without this option.
[dump-no-jprofiling-20200128.110742.18332.0003.zip](https://github.com/eclipse/openj9/files/4121889/dump-no-jprofiling-20200128.110742.18332.0003.zip)

**Comment by JasonFengJ9** [comment]
This is seen in internal builds as well.
```
05:07:06      [javac] Type=Segmentation error vmState=0x000503ff
05:07:06      [javac] Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=0000000070BF9CF9 ContextFlags=0010005f
05:07:06      [javac] Handler1=0000000070BBBBF0 Handler2=00007FF91D17CCF0 InaccessibleReadAddress=FFFFFFFFEDA580EE
05:07:06      [javac] RDI=0000000001C7D600 RSI=000000000F38E420 RAX=000000000F38E478 RBX=00007FF64D620000
05:07:06      [javac] RCX=0000000000000000 RDX=0000000000E95538 R8=0000000000000001 R9=0000000000000008
05:07:06      [javac] R10=00007FF91BC8CB28 R11=000000000F388550 R12=000000000EAEAF60 R13=FFFFFFFFDDFC0000
05:07:06      [javac] R14=FFFFFFFFEDA580F0 R15=00000000000000FC
05:07:06      [javac] RIP=0000000070BF9CF9 RSP=000000000F388560 RBP=000000000FA980E6 GS=002B
05:07:06      [javac] FS=0053 ES=002B DS=002B
05:07:06      [javac] XMM0 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
05:07:06      [javac] XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM2 000000003f400000 (f: 1061158912.000000, d: 5.242822e-315)
05:07:06      [javac] XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
05:07:06      [javac] Module=C:\Users\jenkins\workspace\Test_openjdk8_j9_sanity.x86-64_windows_Nightly\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9jit29.dll
05:07:06      [javac] Module_base_address=0000000070B70000 Offset_in_DLL=0000000000089cf9
05:07:06      [javac] 
05:07:06      [javac] Method_being_compiled=java/lang/StringCoding.decode(Ljava/lang/String;[BII)[C
05:07:06      [javac] Target=2_90_20200127_300 (Windows Server 2016 10.0 build 14393)
05:07:06      [javac] CPU=amd64 (8 logical CPUs) (0x3fff9a000 RAM)
05:07:06      [javac] ----------- Stack Backtrace -----------
05:07:06      [javac] Java_java_lang_invoke_InterfaceHandle_convertITableIndexToVTableIndex+0x439 (0x0000000070BF9CF9 [j9jit29+0x89cf9])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x9da52 (0x0000000070CA0642 [j9jit29+0x130642])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0xa16c8 (0x0000000070CA42B8 [j9jit29+0x1342b8])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x9ba0a (0x0000000070C9E5FA [j9jit29+0x12e5fa])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x36337a (0x0000000070F65F6A [j9jit29+0x3f5f6a])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x36541a (0x0000000070F6800A [j9jit29+0x3f800a])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x35bd39 (0x0000000070F5E929 [j9jit29+0x3ee929])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x359011 (0x0000000070F5BC01 [j9jit29+0x3ebc01])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x35b702 (0x0000000070F5E2F2 [j9jit29+0x3ee2f2])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x3ff329 (0x0000000071001F19 [j9jit29+0x491f19])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x3ffe56 (0x0000000071002A46 [j9jit29+0x492a46])
05:07:06      [javac] Java_java_lang_invoke_MutableCallSite_invalidate+0x2608eb (0x0000000070E634DB [j9jit29+0x2f34db])
05:07:06      [javac] (0x0000000070BC6EE6 [j9jit29+0x56ee6])
05:07:06      [javac] (0x0000000070BC8A6B [j9jit29+0x58a6b])
05:07:06      [javac] j9port_init_library+0x1b4f6 (0x00007FF91D17DEC6 [j9prt29+0x1dec6])
05:07:06      [javac] j9port_init_library+0x1b6f4 (0x00007FF91D17E0C4 [j9prt29+0x1e0c4])
05:07:06      [javac] (0x0000000070BC930C [j9jit29+0x5930c])
05:07:06      [javac] (0x0000000070BC98D2 [j9jit29+0x598d2])
05:07:06      [javac] (0x0000000070BC463A [j9jit29+0x5463a])
05:07:06      [javac] (0x0000000070BC75EE [j9jit29+0x575ee])
05:07:06      [javac] j9port_init_library+0x1b72f (0x00007FF91D17E0FF [j9prt29+0x1e0ff])
05:07:06      [javac] (0x0000000070BC8EBD [j9jit29+0x58ebd])
05:07:06      [javac] omrthread_detach+0x1fd (0x00007FF91DB75D6D [J9THR29+0x5d6d])
05:07:06      [javac] _endthreadex+0x43 (0x00000000716D1D9F [MSVCR100+0x21d9f])
05:07:06      [javac] _endthreadex+0xdf (0x00000000716D1E3B [MSVCR100+0x21e3b])
05:07:06      [javac] BaseThreadInitThunk+0x14 (0x00007FF9254C84D4 [KERNEL32+0x84d4])
05:07:06      [javac] RtlUserThreadStart+0x21 (0x00007FF927F3E8B1 [ntdll+0x6e8b1])
05:07:06      [javac] ---------------------------------------
05:07:06      [javac] JVMDUMP039I Processing dump event "gpf", detail "" at 2020/01/28 02:07:16 - please wait.  
05:07:34  BUILD FAILED
```

**Comment by liqunl** [comment]
@MNeuling Does the application crash every time without the trace option? Are you able to get a trace log from a failed run? If you're not able to get a trace log from a failed run, we still need a core dump to investigate. @pshipton Is there a way for user to upload a large core file (116MB)?

**Comment by liqunl** [comment]
Since this is also seen in the internal testing, I'll look at the internal failure.

**Comment by MNeuling** [comment]
@liqunl Yes, it crashes every time I start it without trace option. I have created a multipart zip archive containing the core dump from the crash two days before. To upload the part files I had to add the extension **.zip** to each file name. Please remove the **.zip** extension from each file and before you try to open it. 

[core.20200127.132221.4868.0001.zip.001.zip](https://github.com/eclipse/openj9/files/4127339/core.20200127.132221.4868.0001.zip.001.zip)
[core.20200127.132221.4868.0001.zip.002.zip](https://github.com/eclipse/openj9/files/4127341/core.20200127.132221.4868.0001.zip.002.zip)
[core.20200127.132221.4868.0001.zip.003.zip](https://github.com/eclipse/openj9/files/4127342/core.20200127.132221.4868.0001.zip.003.zip)
[core.20200127.132221.4868.0001.zip.004.zip](https://github.com/eclipse/openj9/files/4127343/core.20200127.132221.4868.0001.zip.004.zip)
[core.20200127.132221.4868.0001.zip.005.zip](https://github.com/eclipse/openj9/files/4127344/core.20200127.132221.4868.0001.zip.005.zip)
[core.20200127.132221.4868.0001.zip.006.zip](https://github.com/eclipse/openj9/files/4127345/core.20200127.132221.4868.0001.zip.006.zip)
[core.20200127.132221.4868.0001.zip.007.zip](https://github.com/eclipse/openj9/files/4127346/core.20200127.132221.4868.0001.zip.007.zip)
[core.20200127.132221.4868.0001.zip.008.zip](https://github.com/eclipse/openj9/files/4127347/core.20200127.132221.4868.0001.zip.008.zip)
[core.20200127.132221.4868.0001.zip.009.zip](https://github.com/eclipse/openj9/files/4127348/core.20200127.132221.4868.0001.zip.009.zip)
[core.20200127.132221.4868.0001.zip.010.zip](https://github.com/eclipse/openj9/files/4127349/core.20200127.132221.4868.0001.zip.010.zip)
[core.20200127.132221.4868.0001.zip.011.zip](https://github.com/eclipse/openj9/files/4127350/core.20200127.132221.4868.0001.zip.011.zip)
[core.20200127.132221.4868.0001.zip.012.zip](https://github.com/eclipse/openj9/files/4127351/core.20200127.132221.4868.0001.zip.012.zip)
[core.20200127.132221.4868.0001.zip.013.zip](https://github.com/eclipse/openj9/files/4127352/core.20200127.132221.4868.0001.zip.013.zip)
[core.20200127.132221.4868.0001.zip.014.zip](https://github.com/eclipse/openj9/files/4127353/core.20200127.132221.4868.0001.zip.014.zip)

**Comment by liqunl** [comment]
I think the internal one is very likely a dup of #7890, as the offset of each frame is very close. I'm trying to compile a windows build with pdb files such that I can open the core of this issue.

**Comment by liqunl** [comment]
@MNeuling We have another windows issue related aot, could you try `-Xjit:dontUsePersistentIprofiler -Xaot:dontUsePersistentIprofiler` to see if the failure goes away?

**Comment by dsouzai** [comment]
> could you take a look since this looks 292 related?

@andrewcraik on Windows you can't trust the backtrace; because there's no .pdb files the backtrace writer takes the extremely sparse set of exported symbols and runs with it.

**Comment by MNeuling** [comment]
> 
> 
> @MNeuling We have another windows issue related aot, could you try `-Xjit:dontUsePersistentIprofiler -Xaot:dontUsePersistentIprofiler` to see if the failure goes away?

@liqunl Yes if I use these options the application starts without an error.

**Comment by liqunl** [comment]
@MNeuling Thanks for trying the options for us. This issue is a dup of #7890.
