### ISSUE TITLE
OpenJ9 should consider setting java.vendor.version for Java 10

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#842]
As per http://openjdk.java.net/jeps/322 OpenJ9 should consider setting java.vendor.version for Java 10 and later. TDB what it gets set to.

**Comment by JasonFengJ9** [comment]
Latest `Java 10 b36` doesn't set this system property yet.

**Comment by pshipton** [comment]
An OpenJDK build won't necessarily set it to anything, as its for a vendor like Oracle, OpenJ9, IBM to use.

**Comment by JasonFengJ9** [comment]
Agreed. Just did a quick check, Oracle `Java 10 EA b35` hasn't added this system property either.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you give this another look?

**Comment by JasonFengJ9** [comment]
Sure, will do.

**Comment by JasonFengJ9** [comment]
Oracle `Java 10 EA b46` sets `java.vendor.version = 18.3`, in addition another new system property is `java.version.date` as per http://openjdk.java.net/jeps/322. 
```
java.version.date — The general-availability (GA) date of this release, in ISO-8601 YYYY-MM-DD format. For early-access releases this will be the intended GA date, i.e., some date in the future.
java.vendor.version — An implementor-specific product version string, optionally assigned by the individual or organization that produces a specific implementation. If not assigned at build time then it has no value; otherwise, its value is a non-empty string that matches the regular expression \p{Graph}+.
```

P.S. OpenJDK `Java 10 b44` doesn't set property `java.vendor.version`.

The question is: what value will be set for `OpenJ9`?

**Comment by DanHeidinga** [comment]
We should be setting the openj9 release version in that property

**Comment by JasonFengJ9** [comment]
Is the OpenJ9 release version `OPENJ9_TAG`?

**Comment by DanHeidinga** [comment]
I believe so, if OPENJ9_TAG is set

**Comment by pshipton** [comment]
java.vm.version is already set to OPENJ9_TAG, we don't need to set java.vendor.version to the same thing. If we don't have anything to set it to we can just leave it unset (or also set it to `18.3`). I assume OpenJDK leaves it unset and its only set in an Oracle build?

**Comment by JasonFengJ9** [comment]
That's correct, `OpenJDK` leaves it unset and it is only set in an `Oracle Java 10` build.
Are we going to hardcode it to `18.3`? it might need different values for `Java 10 & 11`.

**Comment by pshipton** [comment]
I'm not sure we should set it to anything. I'd be happy to leave it empty for now. If needed for compatibility with Oracle builds we could set it to the appropriate value, i.e. `18.3` for Java 10 and `18.9` for Java 11, etc.

**Comment by JasonFengJ9** [comment]
All right, just set it to an empty string then.

**Comment by pshipton** [comment]
In an OpenJDK build, is it set to an empty string, or undefined?

**Comment by JasonFengJ9** [comment]
It is undefined within an `OpenJDK` build however as the comment earlier this is a vendor specific setting.

**Comment by pshipton** [comment]
I don't know any reason to define it as an empty String. If we're not going to set a value, it should be undefined similarly to OpenJDK builds.

**Comment by DanHeidinga** [comment]
Agreed  - we should either set it to the OpenJ9 version or leave it undefined.

**Comment by DanHeidinga** [comment]
Let's go with leaving it undefined.
