### ISSUE TITLE
OpenJ9 Planned Maintenance outages 2020

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#8424]
Sample list of some of the activities that would occur with a planned maintenance event.

- KVM host maintenance
- machine update (validate and/or trigger; reboot where kernel changes are pending)
- artifactory cleanup, as required
- jenkins job cleanup, as required

@rajdeep-singh @pshipton, any other activities you would add to this list.  Note that most of the activities here will mean little or no downtime to daily or pull request builds, the exception being where artifactory or KVM host updates require a restart.

**Comment by vsebe** [comment]
Update jenkins shell to `/bin/bash` on Ubuntu 16 machines. Currently `SHELL=/bin/sh`.

**Comment by jdekonin** [comment]
https://github.com/eclipse/openj9/issues/8373 - updates to openssl or full updates to ppcle systems.
