### ISSUE TITLE
aix71-p8-1 through 4 offline

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8432]
aix71-p8-1 through 4 and offline. These are the only machines that can build the JVM.

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
Seems these expired yesterday.  Working to restore/renew.  Hopefully @AdamBrousseau will have aix71-p8-1 back online shortly because we had an image of it.  The other 3 will take longer as they need to be rebuilt. Images are only good for restoring the host it was created from.

**Comment by pshipton** [comment]
aix71-p8-1 is working for builds.

**Comment by pshipton** [comment]
I removed the ci.role.test from aix71-p8-1

**Comment by AdamBrousseau** [comment]
Opened https://github.com/eclipse-cbi/jiro/pull/79 to take care of the label in the event of a restart/redeploy.

**Comment by AdamBrousseau** [comment]
Update:
- `#1` restored from image. In the farm for build-only
- 5,7,8 in use for test
- openj9 2,3,4 omr 1,2 recreated. Will need to be setup from scratch
- `#9` loaned to OMR

**Comment by pshipton** [comment]
On aix71-p8-1 we're missing a bootjdk to build jdk15 (jdknext). Pls also check for a bootjdk for jdk14.
`00:45:46  configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK`

**Comment by jdekonin** [comment]
jdk13 is present now.  jdk14 and jdknext both reference this as the bootjdk.

```
bash-4.4# /usr/java13_64/bin/java -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 13 AIX ppc64-64-Bit Compressed References 20200118_101 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 9c5a41bd5f based on jdk-13.0.2+8)
```
