### ISSUE TITLE
Error occurred for request PUT /artifactory

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8434]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259
osx1011-x86-1
```
05:06:33  Recording test results
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
05:06:43  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259/SHA.txt
[Pipeline] publishBuildInfo
05:06:45  Deploying build info to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
05:06:45  Deploying build descriptor to: https://140-211-168-230-openstack.osuosl.org/artifactory/api/build
05:06:45  Build successfully deployed. Browse it in Artifactory under https://140-211-168-230-openstack.osuosl.org/artifactory/webapp/builds/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259
05:06:45  Sending request for build retention, deleting build artifacts, max number of builds to store: 20.
[Pipeline] echo
05:06:46  Test output artifactory URL:'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259/'
[Pipeline] sh
05:06:49  + tar -zcf functional_test_output.tar.gz ./openjdk-tests/TKG/test_output_15801900908727 ./openjdk-tests/TKG/test_output_15801907603570
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
05:14:51  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259/functional_test_output.tar.gz
06:13:19  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259/functional_test_output.tar.gz;build.parentNumber=1216;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.timestamp=1580184204336;build.name=Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly;build.number=259 HTTP/1.1: Read timed out.
06:13:19  Attempting retry #1
07:19:05  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259/functional_test_output.tar.gz;build.parentNumber=1216;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.timestamp=1580184204336;build.name=Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly;build.number=259 HTTP/1.1: Read timed out.
07:19:05  Attempting retry #2
08:17:50  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly/259/functional_test_output.tar.gz;build.parentNumber=1216;build.parentName=Pipeline_Build_Test_JDK11_x86-64_mac;build.timestamp=1580184204336;build.name=Test_openjdk11_j9_extended.functional_x86-64_mac_Nightly;build.number=259 HTTP/1.1. Received status code 504 and message: Gateway Time-out.
08:17:50  Attempting retry #1
Aborted by Peter Shipton
```

**Comment by pshipton** [comment]
@AdamBrousseau

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_extended.functional_x86-64_mac_OpenJDK/98

**Comment by AdamBrousseau** [comment]
Failed on different machines. Looks like it was attempting to retry but was just hung doing so.

**Comment by pshipton** [comment]
Maybe related?

The following has been uploading for the last ~2 hours.
https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64le_linux_Personal/672
```
14:43:20  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Personal/672/OpenJ9-JDK8-ppc64le_linux-20200129-185738.tar.gz
14:43:27  [consumer_1] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64le_linux_Personal/672/test-images.tar.gz
```

**Comment by pshipton** [comment]
More. Could artifactory be out of space, or having problems?
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64le_linux_Personal/80
```
14:40:39  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_extended.functional_ppc64le_linux_Personal/80/functional_test_output.tar.gz
```
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_ppc64le_linux_Personal/9
```
14:37:10  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk11_j9_sanity.system_ppc64le_linux_Personal/9/system_test_output.tar.gz
```

**Comment by pshipton** [comment]
All UNB machines, perhaps just temporary connectivity problems.

**Comment by pshipton** [comment]
Seems all testing is now failing due to artifactory problems.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Nightly/265/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/263/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_linux_Nightly/259/
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly/271/
etc

**Comment by pshipton** [comment]
It seems passing testing are transffering results to artifactory, not sure when that started to occur. @llxia mentioned KEEP_REPORTDIR may be set to true. Looking at artifactory space reports, it started creeping up around Dec 19th.
@smlambert fyi

**Comment by pshipton** [comment]
Seems https://github.com/eclipse/openj9/pull/7780 may be related.

**Comment by pshipton** [comment]
Even PR testing is uploading test results to artifactory.

**Comment by llxia** [comment]
Due to space limitation in Artifactory, I think we should set  `KEEP_REPORTDIR ` to true for test builds that need JUnit test results only (i.e., openjdk test builds).

**Comment by pshipton** [comment]
@jdekonin fyi

**Comment by AdamBrousseau** [comment]
I can work on adding `KEEP_REPORTDIR` based on test target. Similar to what I did in #8421 . @llxia Is the sanity.openjdk suite the only one where this is really needed?

**Comment by pshipton** [comment]
We also need to clean up artifactory and reduce the space being used. Ideally removing the passing test results while keeping the failing results. It seems possible the recent artifactory problems are related to it being so full.

**Comment by llxia** [comment]
> I can work on adding KEEP_REPORTDIR based on test target. Similar to what I did in #8421 . @llxia Is the sanity.openjdk suite the only one where this is really needed?

I think we should set true for all openjdk builds, not limited to sanity.openjdk only. I am not sure what is the plan to run other openjdk tests, but `extended.openjdk` and `special.openjdk` jobs are created in OpenJ9 Jenkins. For example, 
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.openjdk_ppc64_aix_Nightly/

**Comment by AdamBrousseau** [comment]
No runs on that job. I don't think we run other openjdk levels at the moment. Pete can confirm. Can add the others now or later.

**Comment by AdamBrousseau** [comment]
Last night's issues were unrelated to original issue in desc.
Root cause
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1585
Artifacts are no longer getting compressed. Stewart is working on a fix.
I'm still going through trying to find offending files.

**Comment by pshipton** [comment]
The first goal is to get sanity.openjdk working at OpenJ9, issues blocking that are in https://github.com/eclipse/openj9/projects/14. Once sanity is working we could try other levels as well.

**Comment by pshipton** [comment]
The original problem is still happening.
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14/5
```
04:46:10  Test output artifactory URL:'https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14/5/'
[Pipeline] sh
04:46:13  + tar -cf - ./openjdk-tests/TKG/test_output_15804475385388 ./openjdk-tests/TKG/test_output_15804482377405
04:46:13  + gzip -9
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload; see: https://jenkins.io/redirect/pipeline-cps-method-mismatches/
05:16:19  [consumer_0] Deploying artifact: https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Test/Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14/5/functional_test_output.tar.gz
07:04:41  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Test/Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14/5/functional_test_output.tar.gz;build.parentNumber=9;build.parentName=Pipeline_Build_Test_JDK14_x86-64_mac;build.timestamp=1580443407990;build.name=Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14;build.number=5 HTTP/1.1: Read timed out.
07:04:41  Attempting retry #1
08:48:06  Error occurred for request PUT /artifactory/ci-eclipse-openj9/Test/Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14/5/functional_test_output.tar.gz;build.parentNumber=9;build.parentName=Pipeline_Build_Test_JDK14_x86-64_mac;build.timestamp=1580443407990;build.name=Test_openjdk14_j9_extended.functional_x86-64_mac_OpenJDK14;build.number=5 HTTP/1.1: Read timed out.
08:48:06  Attempting retry #2
```

**Comment by AdamBrousseau** [comment]
The one in the first link is 5GB. Odd to me because there were no test failures. Possibly resolved by #8459 .

**Comment by AdamBrousseau** [comment]
Pretty sure 8459 will resolve our space issues. Test artifacts were ranging from 500M to 5G. Manually cleaned up a bunch of builds. Space isn't reported as being recovered yet. Hopefully it will after a few cycles otherwise we may need a reboot or more investigation.

**Comment by AdamBrousseau** [comment]
Can this be closed?

**Comment by pshipton** [comment]
If I close it then it will probably happen again.
