### ISSUE TITLE
Fix issues relating to jitserver

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/openj9#8449]
In the discussion before https://github.com/eclipse/openj9/pull/7940 was merged, several issues were deferred:

- [x]  #8219
- [x]  #8220
- [x]  #8228
- [x]  #8229

These issues should be resolved before jitserver ceases to be considered a 'tech preview'.

**Comment by keithc-ca** [comment]
FYI @ashu-mehra @mpirvu

**Comment by pshipton** [comment]
We're past Milestone 2 for the 0.20.0 release, moving this forward to the next release.

**Comment by mpirvu** [comment]
All referenced issues are implemented now, hence closing.
