### ISSUE TITLE
Building OpenJ9 OpenJDK8 on Windows 64bits platforms

### ISSUE THREAD

**Issue by vsebe** [eclipse/openj9#845]
**Requirements:**
See https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/README-builds.html for OpenJDK8 requirements:
- [JDK7 Windows x64](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html)
- [Microsoft Visual Studio Professional 2010](https://www.visualstudio.com/vs/older-downloads/)
- [cygwin for 64-bit version](https://cygwin.com/install.html) (all Developer category packages + zip, unzip, cpio packages)
- [freetype2](https://www.freetype.org/download.html) v2.3 or newer

OpenJ9 requires [Freemarker v2.3.8](https://sourceforge.net/projects/freemarker/files/freemarker/2.3.8/) in addition to the OpenJDK8 requirements 

Open a cygwin64 terminal:
- download freetype2 and unpack it

```
cd /cygdive/c/temp
wget https://download.savannah.gnu.org/releases/freetype/freetype-2.8.1.tar.gz
tar --one-top-level=/cygdrive/c/temp/freetype --strip-components=1 -xzf freetype-2.8.1.tar.gz
```

- build freetype dynamic and static libraries:
open **Visual Studio Command Prompt (VS2010)**( see C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Visual Studio 2010\Visual Studio Tools) and run:

```
cd c:\temp
msbuild.exe C:/temp/freetype/builds/windows/vc2010/freetype.vcxproj  /p:PlatformToolset=v100  /p:Configuration="Release Multithreaded"  /p:Platform=x64  /p:ConfigurationType=DynamicLibrary  /p:TargetName=freetype  /p:OutDir="C:/temp/freetype/lib64/"  /p:IntDir="C:/temp/freetype/obj64/" > freetype.log
msbuild.exe C:/temp/freetype/builds/windows/vc2010/freetype.vcxproj  /p:PlatformToolset=v100  /p:Configuration="Release Multithreaded"  /p:Platform=x64  /p:ConfigurationType=StaticLibrary  /p:TargetName=freetype  /p:OutDir="C:/temp/freetype/lib64/"  /p:IntDir="C:/temp/freetype/obj64/" >> freetype.log
```

NB: check freetype.log for errors

- get sources:
```
git clone https://github.com/ibmruntimes/openj9-openjdk-jdk8
cd openj9-openjdk-jdk8
bash get_source.sh
```
- configure:
Assuming all resources are available in C:\temp -> /cygdrive/c/temp

`bash configure --disable-ccache --with-boot-jdk=/cygdrive/c/temp/jdk7 --with-freemarker-jar=/cygdrive/c/temp/freemarker.jar --with-freetype-include=/cygdrive/c/temp/freetype/include --with-freetype-lib=/cygdrive/c/temp/freetype/lib64`

- build:
`make images`

- verify:

```
 ./build/windows-x86_64-normal-server-release/images/j2sdk-image/bin/java -version
openjdk version "1.8.0-internal"
```

output: 

```
OpenJDK Runtime Environment (build 1.8.0-internal-Administrator_2017_12_14_15_20-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64 Compressed References 20171214_000000 (JIT enabled, AOT enabled)
OpenJ9   - b8ac7e1747
OMR      - 101e793f
OpenJDK  - 2597cd5c6f based on jdk8u152-b16)
```

**Comment by pshipton** [comment]
@SueChaplain fyi

**Comment by SueChaplain** [comment]
Great progress @vsebe - I'll get the detailed build instructions updated and ready for review.

**Comment by SueChaplain** [comment]
PR raised to add the Win section: https://github.com/eclipse/openj9/pull/857
I based the updates off the V9 instructions, merging in the changes from this issue.  I haven't had a chance to test the process myself as I'll be finishing for Christmas today. I can get a machine set up to test when I am back or alternatively someone else is welcome to test and pass me any updates.
@DanHeidinga I recall you tested the V9 instructions for Windows, so perhaps you would like to verify these for V8?

**Comment by vsebe** [comment]
In addition to the above requirements, OpenJ9 requires:
- Debugging Tools (available with [Windows 7 SDK](https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit))
- [Visual Studio 2010 Service Pack 1](https://support.microsoft.com/en-us/help/983509/description-of-visual-studio-2010-service-pack-1)

Users should add the path to the debugging tools to the INCLUDE and LIB environment variables (run in the cmd.exe):
```
set INCLUDE ="C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc";%INCLUDE%
set LIB="C:\Program Files\Debugging Tools for Windows (x64)\sdk\lib";%LIB%;
```

attn @SueChaplain

**Comment by SueChaplain** [comment]
@vsebe
Just for clarification ... there are a huge number of options on the Windows 7 SDK link for the Debugging tools (page https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit). Do you mean this option:

"Get the standalone debugging tools for Windows XP as part of Windows 7 SDK" (near the bottom of the page) ... if so, would this be a better link to use? https://www.microsoft.com/download/confirmation.aspx?id=8279

**Comment by vsebe** [comment]
@SueChaplain that link will do.

**Comment by SueChaplain** [comment]
@vsebe Hi - still trying to find time to finish this testing and nearly made it today. The instructions seem to work fine, although I struggled a bit trying to start the VSstudio command prompt (eventually got there with a cygstart -o command, which might be worth documenting). I made it all the way through to the final `make`, but that ends with a build error: 
`.....\vm\windbg\wdbgext.h(52) : fatal error C1083: Cannot open include file 'wdbgexts.h' : No such file or directory .. `

Any thoughts? Where does wdbgexts.h file come from? Just wondering if I missed something or it can't find it rather than a real build error.

**Comment by pshipton** [comment]
I also think we should wait on https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/116 and ensure the build still works once this change (and the equivalent change for Java 8) is delivered. It requires mingw to be installed, which should come with cygwin.

**Comment by vsebe** [comment]
@SueChaplain there is a shortcut available for the VS 2010 Command Prompt: Start -> Microsoft Visual Studio 10  -> Visual Studio Command Prompt 2010.

**Comment by SueChaplain** [comment]
@pshipton - agreed

@vsebe - I'm still having some trouble getting Cygwin to find the debugging tools. If I set INCLUDE and LIB via a cmd.exe (as per your earlier comment) it does not persist into the Cygwin environment (or any other cmd.exe). So, instead I set it in the control panel, where it does appear in `env` when you start a new Cygwin window. However, the paths are the Windows format c:\..\..\ and not the cygwin format cygdrive/c/../.., which is, I think, the reason why it fails to find the tools. Cygwin converts only some environment variables automatically (https://cygwin.com/cygwin-ug-net/setup-env.html). I also tried to export them inside cygwin in a format it might like:
```
export INCLUDE=cygdrive/c/Program\ Files/Debugging\ Tools\ for\ Windows\ \(x64\)/sdk/inc
export LIB=cygdrive/c/Program\ Files/Debugging\ Tools\ for\ Windows\ \(x64\)/sdk/lib
```
They appear correctly in `env`, but the build still fails to find the debugging tools. Not sure what is different between mine and your environment. I'm attempting this on a Windows 8.1 image. Any thoughts?

**Comment by vsebe** [comment]
@SueChaplain the INCLUDE and LIB have to use windows paths not cygwin when using cygwin bash:

export INCLUDE ="C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc"
export LIB="C:\Program Files\Debugging Tools for Windows (x64)\sdk\lib"

They also can be set as [system environment variables](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx) : go to Start -> Control Panel -> System and Security ->System ->Advanced system settings, in the System Properties pop-up window click on the "Environment Variables" button to open the Environment Variables window.  Click on the New... button to create a new variable:

Variable Name: INCLUDE
Variable value: C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc

or use the Browse Directory... button

If an INCLUDE system variable exists click on the Edit... button to update the variable. 
Add a new entry (on Windows 10) or concatenate to the existing value (on older Windows versions) the following: "C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc"

Similarly, set LIB.

Restart your computer.
This is a one time setting.

**Comment by SueChaplain** [comment]
Yeah I did all of that @vsebe except rebooting the machine. I'll give that a go :-)

**Comment by pshipton** [comment]
Not sure the reboot is necessary, opening a new Visual Studio Command Prompt should be sufficient. You could verify the variables are set as expected in the new environment.

**Comment by SueChaplain** [comment]
Yes I did. If you set them via the control panel, open a new cygwin terminal and type `env`, they are there but the `make` fails to find wdbgexts.h (error above). So I tried to set them up in cygwin in the format it prefers for PATH etc, but no joy. I've no time to pursue this today but maybe we should wait until the mingw work is complete.

**Comment by pdbain-ibm** [comment]
mingw is in progress: waiting for https://github.com/eclipse/openj9/pull/1099 to be merged, then another (dependent) pair of pull requests.

**Comment by pshipton** [comment]
mingw is now being used for OpenJ9 Windows builds.

**Comment by SueChaplain** [comment]
@pshipton Is all the mingw work done now? It would be good to get the testing done and update/complete the build documentation in this PR.

I found the code here: https://sourceforge.net/projects/mingw/files/latest/download?source=files
Who can provide some install/config notes please?
I'm happy to test the process if no-one else can, although it might take me a week or two to fit it in.

**Comment by pshipton** [comment]
@SueChaplain yes all the mingw work is done now. I don't think anything additional is required because mingw is installed with cygwin, although perhaps this needs to be specified when cygwin is installed.
@vsebe @pdbain-ibm please confirm.

**Comment by pdbain-ibm** [comment]
Cygwin must be installed with the developer package, but no other special setup is required.

**Comment by SueChaplain** [comment]
@pdbain-ibm @vsebe 

To get this finally finished:

- So I need to remove the pre-reqs for VStudio and service pack 1.
- What is the mingw command to build the Freetype dynamic and static libraries please? 

Anything else? Thanks

**Comment by pshipton** [comment]
@SueChaplain VisualStudio is still the main compiler. mingw must be present because its used to compile ~3 files which are part of OpenJ9. The build instructions do not change, except to mention mingw being installed along with cygwin, as per https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V9.md
```
Included in this package is mingw, a minimalist subset of GNU tools for Microsoft Windows. OpenJ9 uses the mingw/GCC compiler and is tested with version 6.4.0 of same. Other versions are expected to work also. 
```

**Comment by SueChaplain** [comment]
@pshipton If mingw is part of the devel set in Cygwin, does it even need a mention at all? (The wording is also a little confusing) 

Can we just merge this as is and fix up after if necessary?

**Comment by pshipton** [comment]
ymanton's comments should be addressed first, since he tried the process and had feedback. I think mingw is worth a mention, feel free to fix the wording.
