### ISSUE TITLE
JEP 358 design and implementation notes

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8450]
## Overview of JEP 358: Helpful NullPointerExceptions

JEP 358 [1] provides extended messages for the NullPointerException (NPE) generated by JVM.

Current NPE comes with a non-null message supplied in a constructor or `null` particularly when it was created by the JVM.  An NPE stacktrace contains the method, filename, and line number where the NPE occurred. However a single line of code may contain several access paths, each one is potentially the source of that NPE, and there is no hint about the actual offending path.

This JEP implementation aims to pinpoint the source of such NPE and identify its root cause.

### Java command-line option to enable/disable the feature
This JEP feature can be toggled with `-XX:{+|-}ShowCodeDetailsInExceptionMessages`. It is not enabled by default at `Java 14`.

### NPE extended message description
When this feature is enabled and the JVM is about to throw an NPE, a detailed message is computed in two parts:
The first part is the consequence of this NPE, i.e., which action could not be performed because of a `null` bytecode instruction.
The second part is the reason for the NPE, i..e., which part of the source code pushed that `null` reference onto the operand stack.

An example message produced from a statement `a.b.c.i = 99` might look like following:
```
Exception in thread "main" java.lang.NullPointerException: 
        Cannot read field "c" because "a.b" is null
    at Prog.main(Prog.java:5)
```
in which the 1st part of the NPE message is _Cannot read field "c"_, and the 2nd part is _because "a.b" is null_.

More message details accordingly to the bytecode executed:

bytecode | 1st part
-- | --
`aload` (`iaload/faload/aaload/baload/caload/saload/laload/daload`) | Cannot load from `<element type>` array
`arraylength` | Cannot read the array length
`astore` (`iastore/fastore/aastore/bastore/castore/sastore/lastore/dastore`) | Cannot store to `<element type>` array
`athrow` | Cannot throw exception
`getfield` | Cannot read field `<field name>`
`invokeinterface`, `invokespecial`, `invokevirtual` | Cannot invoke `<method>`
`monitorenter` | Cannot enter synchronized block
`monitorexit` | Cannot exit synchronized block
`putfield` | Cannot assign field `<field name>`
Any other bytecode | N/A

bytecode | 2nd part
-- | --
`aconst_null` | `null`
`aaload` | the instruction pushed the array reference followed by `[`, then the instruction pushed the index, then append `]`
`iconst_*`, `bipush`, `sipush` | the constant value
`getfield` | the instruction pushed the reference, followed by `.<field name>`
`getstatic` | `<class name>.<field name>`
`invokeinterface`, `invokevirtual`, `invokespecial`, `invokestatic` | the return value of `<method>`, or `<method>` if no first part message.
`iload*`, `aload*` | `this` for local variable `0`, the variable name if a local variable table is available, otherwise `<parameter i >` or `<local i >`.
Any other bytecode | N/A

## VM design notes

The NPE message 1st part can be determined by the bytecode being executed, the 2nd part message has to be computed based on past bytecodes already finished.
Considering the complexity work for the 2nd part message computing, VM design and implementation is going to be in two phases, first step is to provide the NPE message 1st part, then the message 2nd part. 

### Construct NPE message 1st part 

The first part of extended NPE message can be computed just based on the bytecode `methodPC` where the NPE is thrown. 

This `methodPC` is stored at first element of `java.lang.Throwable.walkback` within current exception object by `BytecodeInterpreter.hpp:inlThrowableFillInStackTrace()` or `Fast_java_lang_Throwable_fillInStackTrace`. It can be retrieved along with the `ROM` `method`/`class` containing this `methodPC` using the algorithm in `exceptiondescribe.c:iterateStackTrace()`. 

To prepare the framework for the NPE part 2 message generation,  a function `getCompleteNPEMessage()` is to be added within `rtverify.c`, and take advantage of `verifier` stack structure and parsing algorithm. 
This function performs following:
1. if the bytecode is one of `iaload/faload/aaload/baload/caload/saload/laload/daload`, `iastore/fastore/aastore/bastore/castore/sastore/lastore/dastore`, `arraylength`, `athrow`, `monitorenter`, or `monitorexit`, a specific message can be constructed accordingly just based on the bytecode itself;
2. if the bytecode is `getfield` or `putfield`, the field `name/sig` can be retrieved based on the bytecode and the field index;
3. if the bytecode is `invokeinterface`,  `JBinvokeinterface2`, `invokespecial`, or `invokevirtual`, the method name can be retrieved based on the bytecode and the method index;
4. `NULL` for any other bytecodes. 

### Computing NPE message 2nd part

To compute NPE message 2nd part, the `class`/`method`/`field` putting `null` into the stack have to be identified.

#### An example
First start with an example with following code snippet:
```
	Object obj = new Object();
	Object[][] objsTwoDimen = new Object[2][];
	try {
		objsTwoDimen[1][3] = obj;
	} catch (NullPointerException e) {
		e.printStackTrace();
	}
```

A JVM w/o this JEP produces following NPE:
```
java.lang.NullPointerException
	at a.se.java_lang_npe.MiniNullPointerExceptionTest.demo_aastore(MiniNullPointerExceptionTest.java:29)
	at a.se.java_lang_npe.MiniNullPointerExceptionTest.testAll(MiniNullPointerExceptionTest.java:12)
	at a.se.java_lang_npe.MiniNullPointerExceptionTest.main(MiniNullPointerExceptionTest.java:893)
```

With the JEP, the NPE is expected to be:
```
java.lang.NullPointerException: Cannot store to object array because "objsTwoDimen[1]" is null
	at a.se.java_lang_npe.MiniNullPointerExceptionTest.demo_aastore(MiniNullPointerExceptionTest.java:29)
	at a.se.java_lang_npe.MiniNullPointerExceptionTest.testAll(MiniNullPointerExceptionTest.java:12)
	at a.se.java_lang_npe.MiniNullPointerExceptionTest.main(MiniNullPointerExceptionTest.java:893)
```

This NPE message is going to be computed when VM discovers a `null` object reference in the stack, and maps it to a message like above.
The bytecode in question  is:
```
    0 JBnewdup 35 java/lang/Object
    3 JBdup 
    4 JBinvokespecial 36 java/lang/Object.<init>()V
    7 JBastore1 
    8 JBiconst2 
    9 JBanewarray 39 [Ljava/lang/Object;
   12 JBastore2 
   13 JBaload2   <-- loads objsTwoDimen which is not null
   14 JBiconst1 
   15 JBaaload   <-- loads objsTwoDimen[1] which is null
   16 JBiconst3 
   17 JBaload1 
   18 JBaastore   <-- NPE to be thrown
```

NPE is to be thrown at `18 JBaastore` due to a `null` loaded by `15 JBaaload` which loads a reference from an array, the array reference is loaded by `13 JBaload2`.
`13 JBaload2` can be used to a local variable `objsTwoDimen` or `<local2>` if the actual variable name is not available in the class file;
`14 JBiconst1 ` is the array first dimension index `1`;
`15 JBaaload` loads the array first dimension;
`16 JBiconst3` is the array second dimension index which is not need for NPE message computing;
`17 JBaload1 ` is the value to be stored which is not need either;

#### stack structure similar with verifier stack
To retrieve info above for NPE message computing, an approach proposed is to create/update a stack structure similar with the verifier stack in `rtverify.c:verifyBytecodes()`.

When the NPE is thrown at `18 JBaastore`, the stack looks like:
```
stackTop  -->  [                      ]
                [ 0x0              ]    <-- put by `17 JBaload1`
                [ 0x21             ]     <-- put by `16 JBiconst3`
                [ 0x1000000 ]     <-- put by `15 JBaaload`
                [ 0x21             ]     <-- put by `14 JBiconst1`
stackBase --> [ 0x2000000 ]     <-- put by `13 JBaload2`
```
Note: the value in the stack is bytecode simplified verification defines (different from those verifier type system, just enough to support stack manuniplaution), not actual bytecode.
The number and order of the top stack contents match the operand stack required by `18 JBaastore`, i.e., `..., arrayref, index, value → ...`.

Further down the stack, the number and order of the stack contents match the operand stack required by `15 JBaaload`, i.e., `..., arrayref, index → ..., value`.

At last, the local variable `objsTwoDimen` can be retrieved via `13 JBaload2` or `<local2>` if the actual variable name is not available in the class file, the array index is `1`, hence `objsTwoDimen[1]` was `null` caused NPE. Along with NPE message part 1, `Cannot store to object array because "objsTwoDimen[1]" is null` is computed.

For cases like this, all related info can be kept within the stack, however when the stack can't keep such info, another call can be started and aim for the bytecode offset putting `arrayref` onto the stack recursively until the complete info is retrieved.

#### mapping the stack to bytecode
As demonstrated above example, the stack content are for stack modification purpose, and doesn't have the actual bytecode.

To keep track the bytecode putting the values to the stack, another stack structure with **same** size will be created which keeps the bytecode offset in current ROM method (there might be multiple same bytecodes hence the offset pinpoints the bytecode specified)

For the example above, the bytecode offset stack looks like:
```
offsetStackTop  -->  [                      ]
                [ 17             ]    --> points to `17 JBaload1`
                [ 16             ]     --> points to `16 JBiconst3`
                [ 15             ]     --> points to `15 JBaaload`
                [ 14             ]     --> points to `14 JBiconst1`
offsetStackBase --> [ 13 ]     --> points to `13 JBaload2`
```
These bytecode offset stack values are saved while manipulating the stack structure parsing the bytecode. 

#### implementation details

1. The stack structure parsing the bytecode is similar with verifier stack but with minimum type system to support the parsing algorithm, most of verifier utility methods (e.g. `vrfyhelp.c` & `rtverify.c`) won't be used;
2. Similarly a separated stack map structure is to be created based on the bytecode and determine the branch targets which is expected to be simpler than the verifier counterpart created by `simulateStack()` or `decompressStackMaps()`;
3. The stack is to keep earlier bytecode contents particularly for typical cases like `aaload`, when that is not possible, a recursive call is to be invoked to find the earlier stack contents which usually are POPed in verifier stack operation;

RI has inconsistent message output, will have to build testcases for those JTReg test scenarios and also those not covered by JTReg.

## Performance consideration
Performance impact is not expected when the feature is not enabled.
The performance hit with this feature enabled depends on the number of NPEs thrown by the application but should not be significant.

## Security consideration
This feature doesn't provide more source code info besides those already available in the NPE stacktrace without this feature except specific `NULL` value of individual field/method identified.
No extra security measurement is required. 

## Compatibility consideration
This feature is not enabled by default, and doesn't affect existing application. There is no migration effort required. 
When this feature is enabled, it only affects the application/tools depending on the exact format or message of the NPE.

## Test Plan

JTReg tests [2]:
```
NPEInHiddenTopFrameTest.java
NullPointerExceptionTest.java
SuppressMessagesTest.java
```
Note: due to RI inconsistent messages and OpenJ9 doesn't match them all, JTReg tests can't be run directly.

## Documentation
A doc issue is required.

@DanHeidinga @gacholio @pshipton please comment.

[1] https://openjdk.java.net/jeps/358
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/test/hotspot/jtreg/runtime/exceptionMsgs/NullPointerException/

**Comment by pshipton** [comment]
I don't expect this will be resolved in 0.20, moving it forward.

**Comment by JasonFengJ9** [comment]
**Computing NPE message 2nd part** section has been updated. (sorry for the stack digram format which looks off after browser rendering)

fyi @DanHeidinga @gacholio

**Comment by gacholio** [comment]
You definitely need a bytecode walk to do this, but I'm not the sure the verifier keeps the information you need at the moment (it doesn't care where something came from, it just tracks the shape of the stack).

**Comment by JasonFengJ9** [comment]
> it doesn't care where something came from, it just tracks the shape of the stack

That's correct, the content of verifier stack doesn't have the actual bytecode, I am proposing another bytecode stack to track the bytecode offset within the ROM method while `verifyBytecodes()` is building the verifier stack, i.e., saving current bytecode offset in the bytecode stack at same time of updating verifier stack. This can reuse `verifyBytecodes()` structure and algorithm.

**Comment by gacholio** [comment]
You are planning to call the verifier again to get this information, rather than caching it on the class, I assume?

**Comment by JasonFengJ9** [comment]
Yeah, I am planning to invoke `verifyBytecodes()` recursively to find the bytecode info backward considering the code is in the exception throwing path and the feature is off by default.
The number of recursive call is not expected high except some complex use cases which is not normal usage.

The verification stack caching will need keep all possible branch path, and also require development of a way to traverse the path like verifier. I feel this approach can be explored further if the performance is a concern when the feature becomes default.

**Comment by JasonFengJ9** [comment]
Updated the section "Computing NPE message 2nd part" to reflect that current approach moves further away from verifier.

fyi @DanHeidinga

**Comment by pshipton** [comment]
As this won't be completed for the 0.21 release, moving forward.

**Comment by DanHeidinga** [comment]
This won't be complete for 0.22, moving forward

**Comment by tajila** [comment]
@JasonFengJ9 Is this complete?

**Comment by JasonFengJ9** [comment]
@tajila yes, this is done.
Closing.
