### ISSUE TITLE
cent6-x64-5/6/7 are marked offline

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8451]
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_OMR/465/console
```
20:07:52  cent6-x64-7 was marked offline: Connection was broken: java.io.EOFException
```

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_OMR/473/console
```
20:06:14  cent6-x64-6 was marked offline: Connection was broken: java.io.EOFException
```

This is not really a test failure.
@pshipton could you replace the tag with infra instead? thanks.

**Comment by AdamBrousseau** [comment]
Default java not found on the system. Likely related to gcc7 upgrade. cc @jdekonin 
![image](https://user-images.githubusercontent.com/6430052/73457803-41427b80-4342-11ea-99ed-e24dc5d2336b.png)
I see a playbook run in the bash history.
```
... ansible/playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --skip-tags "CPAN,Openssl,Security,Swap_File,gcc_48"
```

**Comment by AdamBrousseau** [comment]
dup #8455

**Comment by pshipton** [comment]
Joe responded in #8455 so I'll close this one as a dup.
