### ISSUE TITLE
SIGINT signal being ignored for Apache Kafka when zookeeper is down

### ISSUE THREAD

**Issue by iamavieira** [eclipse/openj9#8458]
java -version output
--------------------
openjdk 11.0.6 2020-01-14                                                                                                                                                                            OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)                                                                                                                            OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
--------------------
OS distribuition:   
                                                                                                                                                             Distributor ID: Ubuntu                                                                                                                                                                               Description:  Ubuntu 18.04.3 LTS                                                                                                                                                                   Release:  18.04                                                                                                                                                                                
--------------------------
SIGINT signal being ignored for Apache Kafka when zookeeper is down
------------------
[Download](https://www.apache.org/dyn/closer.cgi?path=/kafka/2.4.0/kafka_2.12-2.4.0.tgz) the 2.4.0 release and un-tar it:

> tar -xzf kafka_2.12-2.4.0.tgz
> cd kafka_2.12-2.4.0

Start Zookeeper:
bin/zookeeper-server-start.sh config/zookeeper.properties

Start Kafka:
bin/kafka-server-start.sh config/server.properties

Ctrl + C zookeeper process
wait for zookeeper to shutdown

Ctrl + C kafka process
![kafka](https://user-images.githubusercontent.com/34105342/73456787-4a871480-4351-11ea-92c5-ef1d05738015.png)

Kafka process won`t go down and instead connection to zookeeper will be retried.

With connection restablished, process will sucessfully go down.

I expected that the program would be shutdown, regardless of the status of zookeeper.

Am I wrong in assuming that?

**Comment by DanHeidinga** [comment]
@iamavieira The `java -version` output doesn't appear to be from an OpenJ9-based JDK.  Can you retest with OpenJ9 builds from AdoptOpenJDK and confirm this still occurs?

**Comment by pshipton** [comment]
It seems this question would be better asked to Kafka. The JVM is passing the signal to the app, it's up to the app how the signal is handled.
