### ISSUE TITLE
Windows configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8470]
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Nightly/283
win2012r2-x86-2
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-32_windows_Nightly/281
win2012r2-x86-3
```
22:22:53  configure: Using microsoft C compiler version 16.00.40219.01 [Microsoft (R) C/C++ Optimizing Compiler Version 16.00.40219.01 for x64]
22:22:56  checking whether the C compiler works... no
22:22:56  configure: error: in `/cygdrive/c/Users/jenkins/workspace/Build_JDK8_x86-64_windows_Nightly':
22:22:56  configure: error: C compiler cannot create executables
```

https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_windows_Nightly/286/
win2012r2-x86-6
https://ci.eclipse.org/openj9/job/Build_JDK14_x86-64_windows_OpenJDK14/5
win2012r2-x86-1
```
22:24:41  configure: Using microsoft C compiler version 19.15.26726 [Microsoft (R) C/C++ Optimizing Compiler Version 19.15.26726 for x64]
22:24:43  checking whether the C compiler works... no
22:24:43  configure: error: in `/cygdrive/c/Users/jenkins/workspace/Build_JDK14_x86-64_windows_OpenJDK14':
22:24:43  configure: error: C compiler cannot create executables
```

**Comment by pshipton** [comment]
@jdekonin guessing your Windows tinkering broke it.

**Comment by jdekonin** [comment]
I unset the TEMP env var in the machine config on win2012r2-x86-6 if you can direct a compile job at it I'd appreciate that.  I logged on each machine, 1-3 appeared fine, but 4-6 each had a “something really bad happened” windows.

I hadn't made any changes on the machines at all.

**Comment by pshipton** [comment]
Fixed via https://github.com/eclipse-cbi/jiro/pull/81 I hope. Meanwhile I've fixed the machine manually.
