### ISSUE TITLE
AArch64 MemoryReference crash with no base register set

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#8475]
There are circumstances where AArch64 memory references are being created without a base and index register, leading to crashes in the JIT.

For example, running SPECjbb2005 results in the following tree after GVP:
```
java -Xjit:optlevel=warm,count=0,limit={*PepTest.testClone*} -cp jbb.jar:check.jar spec.jbb.JBBmain -propfile SPECjbb.props


 n174n    (  0)  NULLCHK on n1616n [#32]                                                              [    0xffff2c492620] bci=[-1,124,-] rc=0 vc=1144 vn=- li=15 udi=- nc=1
 n173n    (  1)    acalli  java/util/Hashtable.clone()Ljava/lang/Object;[#317  unresolved virtual Method] [flags 0x400 0x0 ]  [    0xffff2c4925d0] bci=[-1,124,-] rc=1 vc=1144 vn=- li=15 udi=- nc=2
 n172n    (  1)      aloadi  <vft-symbol>[#238  Shadow] [flags 0x18607 0x0 ] (X!=0 sharedMemory )     [    0xffff2c492580] bci=[-1,124,-] rc=1 vc=1144 vn=- li=15 udi=- nc=1 flg=0x4
 n171n    (  1)        aconst NULL (X==0 X>=0 sharedMemory )                                          [    0xffff2c492530] bci=[-1,123,-] rc=1 vc=1144 vn=- li=15 udi=- nc=0 flg=0x102
 n1616n   (  1)      aconst NULL                                                                      [    0xffff2c58e8d0] bci=[-1,0,-] rc=1 vc=1144 vn=- li=- udi=- nc=0
```
This results in a memory reference being created without a base or index register. 

The memory reference logic needs to be hardened such that memory references are always created with a valid form (with at least a base register, or PC-relative).  While instrumenting the code to investigate the origin of this crash I did discover a few other memory references being created that did not have a base or index register set, yet they did not crash.

This implementation should live in OMR.  I'm opening the issue here because I can easily reproduce a failure in OpenJ9.

@knn-k

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/4801 to fix this.
