### ISSUE TITLE
Get Test_J9VMInternals:test_checkPackageAccess running for at least Java 8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#849]
Sanity test org.openj9.test.java.lang.Test_J9VMInternals:test_checkPackageAccess is excluded for both Java 8 & 9. For starters, it needs to be evaluated for Java 8 to determine why it is failing, and then fixed. Once Java 8 is fixed we can determine the proper action for Java 9.

**Comment by DanHeidinga** [comment]
@pdbain-ibm mentioned he was looking at this

**Comment by pdbain-ibm** [comment]
Changes for https://github.com/eclipse/openj9/pull/579 may affect this.

**Comment by pshipton** [comment]
#579 is a Java 9 issue, while primarily this issue is to ensure the test is working on Java 8.

**Comment by pdbain-ibm** [comment]
For the record:
This test mucks around with classloaders, so we need to be careful about triggering classloading
and with the classpath.

So far, have determined that testng.jar must go on the bootstrap classpath.

**Comment by pshipton** [comment]
> So far, have determined that testng.jar must go on the bootstrap classpath.

FYI An alternative is to grant testng.jar java.security.AllPermission, which is effectively what putting testng.jar on the bootstrap classpath is doing. See "Grant Entries" and `-Djava.security.policy` in
https://docs.oracle.com/javase/8/docs/technotes/guides/security/PolicyFiles.html

**Comment by pdbain-ibm** [comment]
Fixed the ad-hoc classloader to handle special cases (e.g. the testNG classes) specially.

Running the test class directly under testNG fails (probably because of testNG's reflection),
so I split the implementation into a separate class and provide a simple driver class to testNG.

Got it working.  Running a personal build now.

**Comment by pdbain-ibm** [comment]
Fixed Java 8.  Java 9 is blocked by https://github.com/eclipse/openj9/issues/1015.

**Comment by pshipton** [comment]
Removed the test failure label as this is a test issue.

**Comment by pshipton** [comment]
The fix is in #1013
