### ISSUE TITLE
Collections.addAll must throw a NullPointerException

### ISSUE THREAD

**Issue by non-conformances-research** [eclipse/openj9#8499]
Specification of Collections.addAll method (https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#addAll-java.util.Collection-T...-) defines that a NullPointerException must be thrown when elements are null. However above program does not throw any exception.

```
import java.util.ArrayList;
import java.util.Collections;

public class A {
    public static void main(String[] args) {
        int[] x = null;
        Collections.addAll(new ArrayList(), x);
    }
}
```

**Affected versions:**

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux amd64-64 Compressed References 20180315_120 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)

**Steps to reproduce:**

	1. Compile above program
	2. Run it using Eclipse OpenJ9 java

**Current result:**

No exception thrown.

**Expected result:**

NullPointerException thrown.

**Comment by pshipton** [comment]
java.util.Collections is OpenJDK code, not OpenJ9 code, please open this Issue at the OpenJDK project.
