### ISSUE TITLE
Test Output unclear

### ISSUE THREAD

**Issue by Scott-Young-6746** [eclipse/openj9#85]
After following the instructions in test/README for testing a built JDK, the test output does not show:
* Number of completed tests
* Number of passing tests
* Number of failing tests

Instead, the final output after the verbose running output is: **`All Tests Completed`** which does not clearly indicate if all tests passed or not.

**Comment by smlambert** [comment]
Can I get you to give a bit more information about what instructions you followed?  Once you set your environment variables and setup test dependencies, did you run "make test", or some combination of sub-targets? 

Also, can you post to this issue the last 20-30 lines of test output that you are seeing please?

**Comment by Scott-Young-6746** [comment]
I ran the rull test suite with the following instructions starting from the top level directory after the project was compiled:
* **`cd openj9/test/TestConfig`**
* **`export JAVA_BIN=~/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/images/jdk/bin`**
* **`export SPEC=linux_x86-64`**
* **`make -f run_configure.mk`**
* **`make getdependency`**
* **`make test`**

**Comment by smlambert** [comment]
Well, for sure we need to update the README with some additional information, such as how long it takes to run all of the tests, and some guidance on what sub-targets are most useful for different user stories.  If you are an openj9 developer, the sanity target is very useful, as it runs a subset of tests and takes ~20min.  The entire suite that gets exercised with "make test" will take hours if run locally/serially.  

You would be looking in your test output for a "test targets summary" line, an example of running a shorter set of tests below:

TEST TARGETS SUMMARY
+++++++++++++++++++++++++++++++++++++++++++++++
TOTAL: 11   PASS: 7   FAIL: 4   SKIP: 0

PASSED test targets:
    JLM_Tests_IBMinternal_SE90_0
    JLM_Tests_IBMinternal_SE90_1
    JLM_Tests_class_SE90_0
    JLM_Tests_class_SE90_1
    JLM_Tests_interface_SE90_0
    JLM_Tests_interface_SE90_1
    testSoftMxLocal_SE90_2

FAILED test targets:
    testSoftMxLocal_SE90_0
    testSoftMxLocal_SE90_1
    testSoftMxLocal_SE90_3
    OpenJDK_math_0
+++++++++++++++++++++++++++++++++++++++++++++++
All Tests Completed


If you ran all of the tests, you'd probably need to scroll up quite a lot of lines from the "All Tests Completed" text to see it, as the output lists the test suites that pass/fail/skipped.  

If you don't find that summary line, can you please try and run "make sanity" or "make test_JLM_Tests" to execute a smaller set of tests and report back what you see for output.  

Thanks!

**Comment by TianyuZuo** [comment]
This is my test result after running 
```
    cd openj9/test/TestConfig
    export JAVA_BIN=~/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/images/jdk/bin
    export SPEC=linux_x86-64
    make -f run_configure.mk
    make getdependency
    make test
```

```
+++++++++++++++++++++++++++++++++++++++++++++++
TOTAL: 734   PASS: 135   FAIL: 599   SKIP: 0

PASSED test targets:
	AttachAPISanity_SE90_0
	CtorBCVTests_SE90_0
	J9vmTest_SE90_2
	J9vmTest_SE90_4
	J9vmTest_SE90_5
	JCL_Test_JIT_Helper_SE90_0
	JCL_Test_Package_SE90_0
	JCL_Test_SE90_0
	JCL_Test_SE90_1
	JLM_Tests_IBMinternal_SE90_0
	JLM_Tests_IBMinternal_SE90_1
	JLM_Tests_class_SE90_0
	JLM_Tests_class_SE90_1
	JLM_Tests_interface_SE90_0
	JLM_Tests_interface_SE90_1
	NoSuchMethodTests_SE90_0
	SharedClassesSysVTesting_SE90_0
	TestArrayCopy_SE90_2
	TestArrayCopy_SE90_3
	TestFlushReflectionCache_SE90_0
	TestRefreshGCSpecialClassesCache_NOBCI_SE90_0
	fibTest_SE90_0
	floatSanityTests_SE90_0
	floatSanityTests_SE90_2
	generalSanityTest_SE90_0
	hanoiTestTM_HEAVY_SE90_0
	hanoiTestTM_MEDIUM_SE90_0
	hanoiTestTM_NATIVE_SE90_0
	hanoiTest_SE90_0
	jit_jar_SE90_0
	jit_jitt_SE90_0
	jit_jitt_SE90_1
	jit_jitt_SE90_2
	jit_jitt_SE90_3
	jit_tr_SE90_0
	jit_vich_SE90_0
	memleaksTest_SE90_0
	pthreadDestructor_SE90_0
	reattachAfterExit_SE90_0
	regressionFastresolve_mode150_SE90_0
	stringConcatOptTest_SE90_0
	testInvokeSpecialInsideInterface_SE90_0
	testReflectInvoke_SE90_0
	testStringInterning_SE90_1
	CallerSensitiveGetCallerClassTest_0
	ContendedFieldsTests_90_0
	ContendedFieldsTests_90_1
	ContendedFieldsTests_90_2
	ContendedFieldsTests_90_3
	HashConsistency_SE90_0
	HashPerformance_SE90_0
	IllegalAccessProtectedMethodTest_SE90_0
	SoftmxRASTest1_SE90_2
	SoftmxRASTest2_SE90_2
	StackWalkerTest_0
	StackWalkerTest_1
	TestAttachAPIEnabling_SE90_0
	TestAttachErrorHandling_SE90_0
	TestFileLocking_SE90_0
	TestGCClassWithStaticRetransformInBalanced_SE90_0
	TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_SE90_0
	TestSoftMxCallBackExtend_SE90_1
	TestSoftMxCallBackOOM_SE90_1
	ThreadRegressionTests_SE90_3
	ThreadRegressionTests_SE90_4
	VarHandleInvokerTest_0
	VarHandleInvokerTest_1
	VarHandle_0
	View-BE-OffHeap_0
	View-BE-OnHeap_0
	View-LE-OffHeap_0
	View-LE-OnHeap_0
	badUTF8inJNI_SE90_1
	badUTF8inJNI_SE90_2
	gcNotificationTest_Balanced_SE90_0
	gcNotificationTest_Balanced_SE90_1
	gcNotificationTest_GenCon_SE90_0
	gcNotificationTest_GenCon_SE90_1
	gcNotificationTest_Metronome_SE90_0
	gcNotificationTest_Metronome_SE90_1
	gcNotificationTest_OptAvgpause_SE90_0
	gcNotificationTest_OptAvgpause_SE90_1
	gcNotificationTest_Optthruput_SE90_0
	gcNotificationTest_Optthruput_SE90_1
	generalExtendedTest_SE90_0
	jit_hwWarm_SE90_0
	jit_hw_SE90_0
	jit_hw_SE90_1
	jit_hw_SE90_2
	jniOnLoadExceptions_SE90_1
	jniOnLoadExceptions_SE90_3
	jniOnLoadExceptions_SE90_4
	memoryCategories_SE90_0
	reflect_getMethods_SE90_0
	regressionBucketDefault_SE90_1
	testClassLoadingDelegation_SE90_0
	testContendedClassLoading_SE90_0
	testCpuUtilization_testMxBean_SE90_0
	testCpuUtilization_testSingleCpuLoadObject_SE90_0
	testDefaultDisclaimMemory_SE90_2
	testExample_SE90_0
	testSoftMxDisclaimMemory_GC_SE90_2
	testSoftMxDisclaimMemory_LP4k_SE90_2
	testSoftMxDisclaimMemory_LP64k_SE90_2
	testSoftMxDisclaimMemory_SE90_2
	testSoftMxDisclaimMemory_zlinux_31_SE90_2
	testSoftMxDisclaimMemory_zlinux_64_SE90_2
	testSoftMxLocal_LP4k_SE90_2
	testSoftMxLocal_LP64k_SE90_2
	testSoftMxLocal_SE90_2
	testSoftMxLocal_zlinux_31_SE90_2
	testSoftMxLocal_zlinux_64_SE90_2
	testSoftMxNotDisclaimMemory_SE90_2
	testSoftMxNotDisclaimMemory_zlinux_31_SE90_2
	testSoftMxNotDisclaimMemory_zlinux_64_SE90_2
	testSoftMxRemote_LP4k_SE90_2
	testSoftMxRemote_LP64k_SE90_2
	testSoftMxRemote_SE90_2
	testSoftMxRemote_zlinux_31_SE90_2
	testSoftMxRemote_zlinux_64_SE90_2
	testSoftMxUserScenario_SE90_2
	testvmcheck_SE90_0
	testvmcheck_SE90_3
	testvmcheck_SE90_4
	testvmcheck_SE90_6
	threadMXBeanTestSuite1_SE90_2
	threadMXBeanTestSuite1_SE90_3
	threadMXBeanTestSuite1_SE90_6
	threadMXBeanTestSuite1_SE90_7
	threadMXBeanTestSuite2_SE90_2
	threadMXBeanTestSuite2_SE90_3
	threadMXBeanTimedParkTest_SE90_2
	threadMXBeanTimedParkTest_SE90_3
	threadMXBeanTimersTest_SE90_2
	threadMXBeanTimersTest_SE90_3

FAILED test targets:
	TestArrayCopy_SE90_0
	TestArrayCopy_SE90_1
	TestFlushReflectionCache_SE90_1
	TestFlushReflectionCache_SE90_2
	TestRefreshGCSpecialClassesCache_NOBCI_SE90_1
	finalizerTest_SE90_0
	floatSanityTests_SE90_1
	hanoiTestTM_SHOULDFAIL_SE90_0
	jit_jitt_XCEEHDLR_SE90_0
	jit_jitt_XCEEHDLR_SE90_1
	jit_jitt_XCEEHDLR_SE90_2
	jit_jitt_XCEEHDLR_SE90_3
	jsr335_interfacePrivateMethod_mode100_SE90_0
	jsr335_interfaceStaticMethod_SE90_0
	regressionFastresolve_mode110_SE90_0
	testStringInterning_SE90_0
	SVT_LoadTest.AnnotationsLoadTest_0
        .....
	threadMXBeanTimersTest_SE90_0
	threadMXBeanTimersTest_SE90_1
	OpenJDK_math_0
+++++++++++++++++++++++++++++++++++++++++++++++
All Tests Completed

**Comment by mgaudet** [comment]
I'm sort of with @Scott-Young-6746; IMO, it might be nice to see the counts much closer to the end of the output.

**Comment by smlambert** [comment]
Makes sense, thanks for input.  We can definitely move (or repeat) this line:
+++++++++++++++++++++++++++++++++++++++++++++++
TOTAL: xxx   PASS: xxx   FAIL: xxx   SKIP: xxx

to just above the final lines:
+++++++++++++++++++++++++++++++++++++++++++++++
All Tests Completed

**Comment by smlambert** [comment]
fyi @renfeiw
