### ISSUE TITLE
Remove "IBM Confidential" from jvm.xml.ftl

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#850]
runtime/jvm.xml.ftl contains processing for "IBM Confidential" which needs to be removed from OpenJ9.  A portion of the code in jvm.xml is not needed for OpenJ9 and should be moved internal to IBM.

```
<!-- exclude IBM Confidential source -->
<delete verbose="true">
	<fileset dir="${r"${j9jcl.dir}"}">
		<contains text="IBM Confidential" casesensitive="false" ignorewhitespace="true" />
	</fileset>
</delete>
```

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Can you take a look at this?  We need to move this functionality out of OpenJ9 and into IBM's internal build system.  We can't close out the initial CQ (and do a release) until this is complete

**Comment by JasonFengJ9** [comment]
Looking at it. It appears `runtime/jvm.xml.ftl` is used by non-openj9 builds hence it can be moved from `OpenJ9` to internal repo.
