### ISSUE TITLE
Eliminate VM_getNewArrayTypeFromClass message

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8506]
Currently, for the `getNewArrayTypeFromClass()` the JITServer sends a message to the client to extract the desired information. We would like to eliminate that message.
The implementation of `getNewArrayTypeFromClass()` is:

```
int32_t
TR_J9VM::getNewArrayTypeFromClass(TR_OpaqueClassBlock *clazz)
   {
   struct J9Class ** arrayClasses = &_jitConfig->javaVM->booleanArrayClass;
   for (int32_t i = 0; i < 8; ++i)
      {
      if ((void*)convertClassPtrToClassOffset(arrayClasses[i]) == (void*)clazz)
         return i + 4;
      }
   return -1;
   }
```
So, there is a set of eight pointers in javaVM and the code iterates through them to find a match. The JITServer could do the same if those pointers were cached in the client session data and they are at VMInfo._arrayTypeClasses[8];

These steps are also needed, to make sure we have cached the VMinfo
```
  JITServer::ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
   auto *vmInfo = _compInfoPT->getClientData()->getOrCacheVMInfo(stream);
```

**Comment by mpirvu** [comment]
@chrisc66 Could you please look into this issue? Thanks

**Comment by chrisc66** [comment]
Looking into this issue... 

In brief, we want to eliminate `VM_getNewArrayTypeFromClass` message between JITServer and client. 

When JITServer asks client to `getNewArrayTypeFromClass` for the first time, it should cache this information in `ClientSessionData` and reads from the cache later.

**Comment by mpirvu** [comment]
> When JITServer asks client to getNewArrayTypeFromClass for the first time, it should cache this information in ClientSessionData and reads from the cache later.

The information may be already cached from a different query. The code I pasted above should take care of this.
```
   JITServer::ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
   auto *vmInfo = _compInfoPT->getClientData()->getOrCacheVMInfo(stream);
```
