### ISSUE TITLE
Crash in Adopt OpenJDK 11.0.6 with OpenJ9

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#8507]
Java -version output
--------------------
Quoting the Adopt issue:
>I found the bug in the 11.0.5 (0.17.0) and downloaded the 11.0.6 today (the 0.18.1) to confirm if the bug is still active.

>Full output of "java -version":
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857d2
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

Summary of problem
------------------
Issue raised in https://github.com/AdoptOpenJDK/openjdk-build/issues/1526 

MS Windows 10 - 64 bit
Adopt OpenJDK 11.0.6 OpenJ9 - 64 bit

I can force a crash with the following class if starting with the OpenJ9 version of Adopt. (It usually crashes before output line "10000" within seconds, highest I've seen was "15000" before crashing)
The "crash" is the abrupt stopping of the JVM with no message what so ever (shutdown hook is not called), nor a crash log.

Running this with the Adopt OpenJDK 11.0.6 Hotspot version it works just fine, just like OpenJDK's do not make a Problem of this.

```
public class CrashTest { private static int sCount = 0;
public static void main(String[] args) throws Exception {
	System.err.println( "CrashTest.main(): Start " );
	while( true ) {
		long lCount = (++sCount);
		if ( (lCount % 5000) == 0 ) System.err.println( "CrashTest.main(): Start " + lCount );
		testNullPtr();
	}
}

public static void testNullPtr() {
	try {
		Object lObject = null;
		lObject.getClass();
	} catch( Exception pEx ) {
	}
}
}
```

Please ensure the Adopt item gets updated with any status as we work to resolve this.

Zip of the test case available in https://github.com/AdoptOpenJDK/openjdk-build/issues/1526#issuecomment-582463043

**Comment by pshipton** [comment]
I haven't been able to reproduce this.

**Comment by pshipton** [comment]
The Adopt issue has been closed, caused by anti-virus software.
