### ISSUE TITLE
Delete J9AOTConfig

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8514]
`J9AOTConfig` is a data structure that mimics `JITConfig` for the most part, but it includes some specific fields:
```
	struct J9AOTCallbackFunctionTable* callbackFunctionTable;
	UDATA virtualCodeBaseAddress;
	UDATA virtualDataBaseAddress;
	UDATA trampolineOffset;
	UDATA methodTrampolineOffset;
	I_32  ( *aotWalkRelocations)(struct J9JavaVM *javaVM, struct J9JITExceptionTable *exceptionTable, struct J9AOTWalkRelocationInfo *walkRelocationInfo, void *extra) ;
	U_8* jxeBuffer;
	UDATA remainingSizeJxeBuffer;
	void* firstClassLocation;
	void* aotCompilationInfo;
```
All, except the last field above, are no longer used.
It makes sense to add the `aotCompilationInfo` field to `JITConfig` and then delete `J9AOTConfig`

**Comment by mpirvu** [comment]
FYI @mstoodle

**Comment by mstoodle** [comment]
I believe this data structure dates back to jar2jxe days when we supported running AOT code without an active JIT (so you would only load the "runtime" bits of the JIT that deal with supporting the execution of compiled code). I think we would do this differently if we ever wanted to support the same kind of execution mode, so I think it's ok to proceed as you have proposed.
