### ISSUE TITLE
win2012r2-x86-5  (offline)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8521]
some machine were offline, but I restarted the jenkins agent and they are online now, except I can't get win2012r2-x86-5 back online. Pls reboot it or something.

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Rebooted, its back online.

**Comment by pshipton** [comment]
@jdekonin it went offline again during testing last night.

**Comment by jdekonin** [comment]
Rebooted and back online.
