### ISSUE TITLE
xlinux switch to gcc 7.5 causing protobuf undefined symbol

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8534]
https://github.com/eclipse/openj9/pull/8443 caused a protobuf undefined symbol on xlinux.

`undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev`

https://github.com/eclipse/openj9/pull/8533 reverts back to gcc 7.3 while we sort it out.

I expect https://github.com/eclipse/openj9/pull/8486 "Remove protobuf from JITServer" will resolve it, but not sure how long before it gets merged.

**Comment by pshipton** [comment]
@jdekonin @mpirvu

**Comment by mpirvu** [comment]
The work to remove protobuf is underway, but it's not simple and I expect to take a few weeks.
