### ISSUE TITLE
Reduce number of VM_stackWalkerMaySkipFrames messages

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8544]
These messages comes from `stackWalkerMaySkipFrames(TR_OpaqueMethodBlock *method, TR_OpaqueClassBlock *methodClass)` and the TR_J9VM implementation is:
```
bool
TR_J9VM::stackWalkerMaySkipFrames(TR_OpaqueMethodBlock *method, TR_OpaqueClassBlock *methodClass)
   {
   if(!method)
      return false;

   TR::VMAccessCriticalSection stackWalkerMaySkipFrames(this);
   if (vmThread()->javaVM->jlrMethodInvoke == NULL || ((J9Method *)method) == vmThread()->javaVM->jlrMethodInvoke )
      return true;

   if(!methodClass)
      return false;

   if ( ( vmThread()->javaVM->jlrAccessibleObject != NULL) &&
          TR_J9VM::isInstanceOf( methodClass, (TR_OpaqueClassBlock*) J9VM_J9CLASS_FROM_JCLASS(vmThread(), vmThread()->javaVM->jlrAccessibleObject),false) )
      return true;

#if defined(J9VM_OPT_SIDECAR)
   if ( ( vmThread()->javaVM->srMethodAccessor != NULL) &&
          TR_J9VM::isInstanceOf(methodClass, (TR_OpaqueClassBlock*) J9VM_J9CLASS_FROM_JCLASS(vmThread(), vmThread()->javaVM->srMethodAccessor), false) )
      return true;

   if ( ( vmThread()->javaVM->srConstructorAccessor != NULL) &&
          TR_J9VM::isInstanceOf(methodClass, (TR_OpaqueClassBlock*) J9VM_J9CLASS_FROM_JCLASS(vmThread(), vmThread()->javaVM->srConstructorAccessor), false) )
      return true;
#endif // J9VM_OPT_SIDECAR

   return false;
   }
```

We can do some optimizations to reduce the number of VM_stackWalkerMaySkipFrames messages:

1) If `method == false` we can return `false without a message
2) If we have `javaVM->jlrMethodInvoke` we can do more tests (and hopefully return early) without sending a message. This field we may not be set, so are allowed to cache it only after it has been set (I believe it's going to be set very early on). (note: this field is set to `java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;`
3) If `methodClass == false` we can return `false` without sending a message
4) Caching `javaVM->jlrAccessibleObject`. This is an object that represents a class. Because objects can move, we should try to cache the j9class instead (`(TR_OpaqueClassBlock*) J9VM_J9CLASS_FROM_JCLASS(vmThread(), vmThread()->javaVM->jlrAccessibleObject)`. We do have the mechanism that deals with class unloading and redefinition, so we should be fine. 
5) Same idea as for (4) we could cache the j9class obtained from `javaVM->srMethodAccessor` and from `javaVM->srMethodAccessor`
6) An alternative for 4-5 is to cache the results of the `TR_J9VM::isInstanceOf` queries (basically, for any class that has passed to one or more of the three `isInstanceOf` filters we memorize the outcome in the hash that we have on classes; we need 3 values, yes, no, maybe). This solution may or may not be save more messages so it needs to be measured.

**Comment by mpirvu** [comment]
@chrisc66 could you please look into this issue? Thanks

**Comment by chrisc66** [comment]
Looking into this issue, thanks.

**Comment by chrisc66** [comment]
A PR has been created for this issue. 
https://github.com/eclipse/openj9/pull/8680

**Comment by mpirvu** [comment]
PR was delivered
