### ISSUE TITLE
Override `transformJlrMethodInvoke()` at JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8547]
The implementation of `TR_J9VM::transformJlrMethodInvoke()` accesses `javaVM->jlrMethodInvoke` which is not safe to do at the server side. We must get the value from the client. Once we get a non-null value we can cache it to avoid future messages.

**Comment by harryyu1994** [comment]
I can take on this on the side. Priority is still fixing defects.

**Comment by harryyu1994** [comment]
We have a corresponding `TR_J9ServerVM` override for JITServer.
```
bool
TR_J9ServerVM::transformJlrMethodInvoke(J9Method *callerMethod, J9Class *callerClass)
   {
   JITServer::ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
   stream->write(JITServer::MessageType::VM_transformJlrMethodInvoke, callerMethod, callerClass);
   return std::get<0>(stream->read<bool>());
   }
```

I think this one can be closed.
