### ISSUE TITLE
jdknext (jdk15) functional tests failing to build

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8551]
Fails for all platforms.
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/124
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK-Acceptance/167
```
09:52:42  compile:
09:52:42       [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018
09:52:42       [echo] ============COMPILER SETTINGS============
09:52:42       [echo] ===fork:                         yes
09:52:42       [echo] ===executable:                   /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdkbinary/j2sdk-image/bin/javac
09:52:42       [echo] ===debug:                        on
09:52:42       [echo] ===destdir:                      /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/TKG/../../jvmtest/functional/Java14andUp
09:52:42      [javac] Compiling 1 source file to /home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_OpenJDK/openjdk-tests/functional/Java14andUp/bin
09:52:42      [javac] error: invalid source release 14 with --enable-preview
09:52:42      [javac]   (preview language features are only supported for release 15)
```

**Comment by pshipton** [comment]
@llxia @smlambert

**Comment by llxia** [comment]
based on the msg above, we need to remove `--enable-preview`  :

https://github.com/eclipse/openj9/blob/6a356f99b267a850c1c62f0dff89875a8456680f/test/functional/Java14andUp/build.xml#L54

https://github.com/eclipse/openj9/blob/6a356f99b267a850c1c62f0dff89875a8456680f/test/functional/Java14andUp/playlist.xml#L32

@LongyuZhang  could you help with this issue? Thanks

**Comment by llxia** [comment]
PR #8564 is merged. Please try jdknext build again.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OpenJDK-Acceptance/169/

**Comment by smlambert** [comment]
Can this be closed now?
