### ISSUE TITLE
InterpreterEmulator must implement all bytecodes

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#8553]
> > @cathyzhyi Does this handle all bytecodes now? I took a quick look and didn't see `invokedynamic` in the list - is it handled specially?
> 
> This code is for method handle inlining and only needs to handle bytecodes exists in method handle thunk.

Unfortunately, that can be any legal bytecode.  Users bytcode agents can modify classes in the ClassFileLoadHook (basically, before we've loaded them) and insert arbitrary code into these methods, or into methods that get inlined into them.

We can't know a priori which bytecodes will be in the thunks.

_Originally posted by @DanHeidinga in https://github.com/eclipse/openj9/pull/8512#issuecomment-583466189_

**Comment by DanHeidinga** [comment]
@cathyzhyi The above still needs to be addressed.  I've opened a new issue to ensure it's handled.

fyi @andrewcraik

**Comment by andrewcraik** [comment]
@DanHeidinga I believe we are talking about the bytecodes in the thunk archetypes which are not from users and are constrained and do not support redefinition etc at present. With changes to the 292 implementation we will look at which ones we need to support when we see that implementation in more detail.

**Comment by DanHeidinga** [comment]
Users are able to modify classes prior to load using the ClassFileLoadHook.  We are also able to modify them when changing the java code.  Today's hardcoded subset is brittle and easy to break.  

Given the user pain, it would be better to add support for all bytecodes - even if it was just to abort the compilation for unexpected bytecodes

**Comment by andrewcraik** [comment]
Sure I'm fine with an abort of ilgen - @cathyzhyi could you sort that with some good diagnostics so we know about them. Custom bytecode in thunk archetypes is not likely to work too well in general so a compile abort makes sense.
