### ISSUE TITLE
C compiler cannot create executables on s390x using jdk8 u16 Dockerfile

### ISSUE THREAD

**Issue by VermaSh** [eclipse/openj9#8556]
I am getting a failure when running `bash configure --with-freemarker-jar=/root/freemarker.jar`

```
configure: Using gcc C compiler version 7.4.0 [gcc (GCC) 7.4.0]
checking whether the C compiler works... no
configure: error: in `/root/openj9-openjdk-jdk8':
configure: error: C compiler cannot create executables
See `config.log' for more details
configure exiting with result code 77
```
Creating a symlink as mentioned here https://github.com/eclipse/openj9/issues/7807 does not seem to solve the issue. It seems to be missing `libmpc3`

**Comment by keithc-ca** [comment]
You would think that if `libmpc3` were required for gcc to create executables that it would be a prerequisite of the gcc package, but apparently it isn't.
