### ISSUE TITLE
Cannot run Eclipse with OpenJ9 0.18.1 for macOS

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#8558]
Java 11 OpenJ9 0.18.1 for macOS fails to start Eclipse with a dialog "Failed to create the Java Virtual Machine." on macOS 10.15.3 Catalina.
```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20200122_450 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
```

0.17.0 works fine in the same environment.
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191016_371 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```

Is this related to Issue #3371, or a different new problem?

**Comment by knn-k** [comment]
0.18.1 large heap does not work, either.

**Comment by pshipton** [comment]
This might be better raised at AdoptOpenJDK. I suspect it's related to notarization of the builds, in which case Adopt would have to create a new build of 0.18.1 which is notarized.

**Comment by smlambert** [comment]
https://github.com/AdoptOpenJDK/openjdk-support/issues/52

**Comment by knn-k** [comment]
Ah, I didn't check the issues at AdoptOpenJDK.  Thanks.

**Comment by pshipton** [comment]
@knn-k can you please try the latest nightly build from Adopt and see if it works.

**Comment by knn-k** [comment]
@pshipton The latest nightly builds I can see in https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9 are dated February 7.
I tried the following, and it failed in the same way as the latest release 0.18.1.
OpenJDK11U-jdk_x64_mac_openj9_2020-02-07-02-19.pkg

**Comment by pshipton** [comment]
Ok, the nightly build problem was supposed to have been fixed, but apparently not yet.

**Comment by knn-k** [comment]
I can run Eclipse IDE with the latest build for macOS at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/477/artifact/workspace/target/OpenJDK11U-jdk_x64_mac_openj9_2020-02-17-19-07.pkg .
