### ISSUE TITLE
JTReg Test Failure: java/lang/invoke/DropLookupModeTest.java and java/lang/invoke/lookup/LookupClassTest.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#8570]
Failure link
------------
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk14_j9_sanity.openjdk_x86-64_mac/3/consoleFull
- test category: sanity.openjdk
- OS/architecture: jdk14 - all

Optional info
-------------
- intermittent failure (yes|no): no
- regression or new test: new test

Failure output (captured from console output)
---------------------------------------------
- DropLookupModeTest.java
New sub-test `testUnconditionalLookup`
https://bugs.openjdk.java.net/browse/JDK-8173978 - Not sure if you're allowed to read this or not, but explains the code/test change.
New test: https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/test/jdk/java/lang/invoke/DropLookupModeTest.java
```
test DropLookupModeTest.testUnconditionalLookup(java.lang.Object/publicLookup, class java.lang.Object): failure
test DropLookupModeTest.testUnconditionalLookup(java.lang.String/public, class java.lang.String): failure
test DropLookupModeTest.testUnconditionalLookup(DropLookupModeTest/public, class DropLookupModeTest): failure
00:12:09  java.lang.AssertionError: expected [true] but found [false]
00:12:09  	at org.testng.Assert.fail(Assert.java:94)
00:12:09  	at org.testng.Assert.failNotEquals(Assert.java:496)
00:12:09  	at org.testng.Assert.assertTrue(Assert.java:42)
00:12:09  	at org.testng.Assert.assertTrue(Assert.java:52)
00:12:09  	at DropLookupModeTest.testUnconditionalLookup(DropLookupModeTest.java:125)
```

- LookupClassTest.java
Whole new test introduced in jdk14
https://bugs.openjdk.java.net/browse/JDK-8173975
https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/test/jdk/java/lang/invoke/lookup/LookupClassTest.java
```
test LookupClassTest.arrayLookupClass(): failure
Method LookupClassTest.arrayLookupClass()[pri:0, instance:LookupClassTest@22c922d1] should have thrown an exception of type class java.lang.IllegalArgumentException

test LookupClassTest.primitiveLookupClass(): failure
Method LookupClassTest.primitiveLookupClass()[pri:0, instance:LookupClassTest@22c922d1] should have thrown an exception of type class java.lang.IllegalArgumentException

test LookupClassTest.voidLookupClass(): failure
org.testng.TestException: 
Method LookupClassTest.voidLookupClass()[pri:0, instance:LookupClassTest@22c922d1] should have thrown an exception of type class java.lang.IllegalArgumentException
```

**Comment by DanHeidinga** [comment]
fyi @ChengJin01 - this is related to the PR you're working on

**Comment by ChengJin01** [comment]
@DanHeidinga, this issue has been addressed in #8657, which will cover all the Jtreg tests related to lookup as follows:
```
[1]test/jdk/java/lang/invoke/MethodHandles/privateLookupIn/Driver.java
[2]test/jdk/java/lang/invoke/lookup/LookupClassTest.java
[3]test/jdk/java/lang/invoke/AccessControlTest.java
[4]test/jdk/java/lang/invoke/modules/m3/jdk/test/ModuleAccessTest.java
[5]test/jdk/java/lang/invoke/DropLookupModeTest.java
```

**Comment by ChengJin01** [comment]
All jtreg test failures here with Lookup have been fixed (see https://github.com/eclipse/openj9/issues/8571#issuecomment-594156246)
and all tests here passed with the latest code in #8657 as follows:

[1]export JDK_CUSTOM_TARGET=test/jdk/java/lang/invoke/lookup/LookupClassTest.java
[jtreg_LookupClassTest_log.txt](https://github.com/eclipse/openj9/files/4283526/jtreg_LookupClassTest_log.txt)
```
PASSED test targets:
        jdk_custom_0

TOTAL: 1   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 0
ALL TESTS PASSED
```
[2]export JDK_CUSTOM_TARGET=test/jdk/java/lang/invoke/DropLookupModeTest.java
(fixed two failing test cases against the Java 14 Spec with UNCONDITIONAL)
[jtreg_DropLookupModeTest_log.txt](https://github.com/eclipse/openj9/files/4283527/jtreg_DropLookupModeTest_log.txt)
```
PASSED test targets:
        jdk_custom_0

TOTAL: 1   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 0
ALL TESTS PASSED
```

The code change will be modified accordingly if any update from Oracle as `Lookup:in()`
Now I will launch personal builds to deal with the internal tests.

**Comment by ChengJin01** [comment]
I modified the code in `Lookup::in()` to call `accessClass()` to check the accessibility of the requested lookup class (as explicitly required in Java 14), all jtreg tests still passed with the new changes.
[jtreg_Lookup_tests_log.txt](https://github.com/eclipse/openj9/files/4289699/jtreg_Lookup_tests_log.txt)
