### ISSUE TITLE
Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.cs.ext")

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#859]
@aguibert mentioned a problem running Liberty on OpenJ9 Java 9

```
>Stack Dump = java.lang.ExceptionInInitializerError
>    at java.lang.J9VMInternals.ensureError(java.base@9-internal/J9VMInternals.java:191)
>    at java.lang.J9VMInternals.recordInitializationFailure(java.base@9-internal/J9VMInternals.java:180)
>    at java.nio.charset.Charset.lookupExtendedCharset(java.base@9-internal/Charset.java:456)
>    at java.nio.charset.Charset.lookup2(java.base@9-internal/Charset.java:486)
>    at java.nio.charset.Charset.lookup(java.base@9-internal/Charset.java:474)
>    at java.nio.charset.Charset.forName(java.base@9-internal/Charset.java:538)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.findCharsetNameFor(java.xml@9-internal/Encodings.java:402)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.findCharsetNameFor(java.xml@9-internal/Encodings.java:438)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.loadEncodingInfo(java.xml@9-internal/Encodings.java:466)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.<init>(java.xml@9-internal/Encodings.java:324)
>    at com.sun.org.apache.xml.internal.serializer.Encodings$EncodingInfos.<init>(java.xml@9-internal/Encodings.java:312)
>    at com.sun.org.apache.xml.internal.serializer.Encodings.<clinit>(java.xml@9-internal/Encodings.java:580)
>    at com.sun.org.apache.xml.internal.serializer.ToStream.<init>(java.xml@9-internal/ToStream.java:135)
>    at com.sun.org.apache.xml.internal.serializer.ToXMLStream.<init>(java.xml@9-internal/ToXMLStream.java:65)
>    at com.sun.org.apache.xalan.internal.xsltc.runtime.output.TransletOutputHandlerFactory.getSerializationHandler(java.xml@9-internal/TransletOutputHandlerFactory.java:163)
>    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getOutputHandler(java.xml@9-internal/TransformerImpl.java:472)
>    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(java.xml@9-internal/TransformerImpl.java:361)
>    at com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator.generateXML(PluginGenerator.java:756)
>    at com.ibm.ws.webcontainer.osgi.mbeans.GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:159)
>    at com.ibm.ws.webcontainer.osgi.mbeans.GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:261)
>    at com.ibm.ws.webserver.plugin.runtime.listeners.GeneratePluginConfigListener$1.run(GeneratePluginConfigListener.java:285)
>    at java.util.concurrent.Executors$RunnableAdapter.call(java.base@9-internal/Executors.java:514)
>    at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:264)
>    at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1167)
>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:641)
>    at java.lang.Thread.run(java.base@9-internal/Thread.java:835)
>Caused by: java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.cs.ext")
>    at java.security.AccessController.throwACE(java.base@9-internal/AccessController.java:176)
>    at java.security.AccessController.checkPermissionHelper(java.base@9-internal/AccessController.java:236)
>    at java.security.AccessController.checkPermission(java.base@9-internal/AccessController.java:371)
>    at java.lang.SecurityManager.checkPermission(java.base@9-internal/SecurityManager.java:558)
>    at java.lang.SecurityManager.checkPackageAccess(java.base@9-internal/SecurityManager.java:1534)
>    at java.lang.J9VMInternals$2.run(java.base@9-internal/J9VMInternals.java:311)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:664)
>    at java.lang.J9VMInternals.checkPackageAccess(java.base@9-internal/J9VMInternals.java:307)
>    at java.lang.ClassLoader.defineClassImpl(java.base@9-internal/Native Method)
>    at java.lang.ClassLoader.defineClass(java.base@9-internal/ClassLoader.java:445)
>    at java.lang.ClassLoader.defineClass(java.base@9-internal/ClassLoader.java:1985)
>    at java.security.SecureClassLoader.defineClass(java.base@9-internal/SecureClassLoader.java:206)
>    at jdk.internal.loader.BuiltinClassLoader.defineClass(java.base@9-internal/BuiltinClassLoader.java:1021)
>    at jdk.internal.loader.BuiltinClassLoader.lambda$findClassInModuleOrNull$4(java.base@9-internal/BuiltinClassLoader.java:865)
>    at jdk.internal.loader.BuiltinClassLoader$$Lambda$155.00000000B0AFBFA0.run(Unknown Source)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:638)
>    at jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(java.base@9-internal/BuiltinClassLoader.java:866)
>    at jdk.internal.loader.BuiltinClassLoader.findClass(java.base@9-internal/BuiltinClassLoader.java:733)
>    at java.lang.ClassLoader.loadClassHelper(java.base@9-internal/ClassLoader.java:1131)
>    at java.lang.Class.forName(java.base@9-internal/Class.java:442)
>    at java.util.ServiceLoader.lambda$loadProvider$1(java.base@9-internal/ServiceLoader.java:852)
>    at java.util.ServiceLoader$$Lambda$154.00000000B0AF9BC0.run(Unknown Source)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:694)
>    at java.util.ServiceLoader.loadProvider(java.base@9-internal/ServiceLoader.java:854)
>    at java.util.ServiceLoader.access$600(java.base@9-internal/ServiceLoader.java:390)
>    at java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(java.base@9-internal/ServiceLoader.java:1071)
>    at java.util.ServiceLoader$2.hasNext(java.base@9-internal/ServiceLoader.java:1294)
>    at java.util.ServiceLoader$3.hasNext(java.base@9-internal/ServiceLoader.java:1379)
>    at java.nio.charset.Charset$ExtendedProviderHolder$1.run(java.base@9-internal/Charset.java:442)
>    at java.nio.charset.Charset$ExtendedProviderHolder$1.run(java.base@9-internal/Charset.java:436)
>    at java.security.AccessController.doPrivileged(java.base@9-internal/AccessController.java:638)
>    at java.nio.charset.Charset$ExtendedProviderHolder.extendedProviders(java.base@9-internal/Charset.java:436)
>    at java.nio.charset.Charset$ExtendedProviderHolder.<clinit>(java.base@9-internal/Charset.java:433)
```

**Comment by JasonFengJ9** [comment]
Is there a testcase to reproduce this `AccessControlException`? 
In addition, what version of OpenJ9 build was used in this failing case?

**Comment by pshipton** [comment]
It was the Windows openj9 build from ibuild 373839 (Dec 18).
Perhaps @aguibert can supply a Liberty FAT test. 

I think you could create a simple test by putting a call to java.nio.charset.Charset.forName() in a bootstrap class, and then calling the bootstrap code form an application class, and running the whole thing with -Djava.security.manager

**Comment by JasonFengJ9** [comment]
Added `java.nio.charset.Charset.forName("UTF-16")` within `j.l.System.getProperty()`, then invoke it from an application class, and run with `-Djava.security.manager`, the methods finished successfully without throwing an `AccessControlException`.
A testcase is required for further investigation.

**Comment by pshipton** [comment]
Might need a more obscure charset name. Can you confirm SecurityManager.checkPackageAccess() was called with "sun.nio.cs.ext"? Try "ISO2022" or something else from the sun.nio.cs.ext package.

**Comment by JasonFengJ9** [comment]
Yeah, that did the trick. An `AccessControlException` is thrown.

**Comment by JasonFengJ9** [comment]
Package `sun.nio.cs.ext` belongs to module `jdk.charsets` which is loaded by `platform classloader`. `OpenJ9` seems not loading the package/classes via bootstrap classloader which has permission to load protected packages like `sun.nio.cs.ext`, hence the classes loaded are subject to security check and eventually failed with `AccessControlException`.

**Comment by JasonFengJ9** [comment]
Further about the comment above:
The modules loaded by `platform classloader` should not have all permissions like those loaded by `boot classloader`, hence loading the module/class in question via boostrap classloader is not the answer to this failure.

Looked further and compared RI and OpenJ9 output when running the testcase with `-Djava.security.debug=all`, RI has following security debug output `access: access allowed ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.cs")` while OpenJ9 failed with `access: (Thread[main,5,main])access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.cs.ext")`. 

There is a `permission java.lang.RuntimePermission "accessClassInPackage.sun.nio.cs";` granted to the codeBase of `jdk.charsets` in both RI and OpenJ9 java policy file. 

Note that module `jdk.charsets` in both RI and OpenJ9 provide extended charset classes in package `sun.nio.cs.ext` instead of `sun.nio.cs`. RI doesn't have classes within package `sun.nio.cs`.

In addition, adding `permission java.lang.RuntimePermission "accessClassInPackage.sun.nio.cs.ext";` within OpenJ9 java policy makes the testcase pass.

It appears there is a difference between RI and OpenJ9 when performing package access check.

**Comment by DanHeidinga** [comment]
Good find @JasonFengJ9!  FYI @hangshao0 as I believe you were looking at a package access check related issue as well.

**Comment by JasonFengJ9** [comment]
RI throws `AccessControlException` when changing the package within `permission java.lang.RuntimePermission "accessClassInPackage.sun.nio.cs"` from `sun.nio.cs` to either `sun.nio` or `sun.nio.cs.ext`. It appears this permission granted to module `jdk.charsets` is for accessing the class within package `sun.nio.cs` in module `java.base` and not for the classes in package `sun.nio.cs.ext` in module `jdk.charsets`.

There is no package access check for the class within package `sun.nio.cs.ext` in module `jdk.charsets`. It seems there is no package access check for class resolution in same module which makes sense though I haven't found such explicit statement in modularity specification.

A quick experiment shows that skipping package access check for class resolution in same module can make the testcase pass. Need further investigation to confirm this approach.

Regarding the problem @hangshao0 investigating, it occurred at Java 8 hence not affected by modularity related issues.
