### ISSUE TITLE
AdoptOpenJDK (build 11.0.6+10) is too slow to response

### ISSUE THREAD

**Issue by RuiBaiXYZ** [eclipse/openj9#8593]
cat /etc/redhat-release 
--------------------
CentOS Linux release 8.1.1911 (Core)

uname -r
--------------------
4.18.0-147.5.1.el8_1.x86_64

java -version
--------------------
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

strace -f -c java -version
--------------------
strace: Process 11037 attached
strace: Process 11038 attached
strace: Process 11346 attached
strace: Process 11347 attached
strace: Process 11348 attached
strace: Process 11349 attached
strace: Process 11350 attached
strace: Process 11351 attached
strace: Process 11352 attached
strace: Process 11353 attached
strace: Process 11354 attached
strace: Process 11355 attached
strace: Process 11356 attached
strace: Process 11357 attached
strace: Process 11358 attached
strace: Process 11359 attached
strace: Process 11360 attached
strace: Process 11361 attached
strace: Process 11362 attached
strace: Process 11363 attached
strace: Process 11364 attached
strace: Process 11365 attached
strace: Process 11366 attached
strace: Process 11367 attached
strace: Process 11368 attached
strace: Process 11369 attached
strace: Process 11370 attached
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
strace: Process 11371 attached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 78.75    0.406082         132      3057       730 futex
  8.21    0.042312           2     16406           munmap
  6.34    0.032685           1     16584           mmap
  6.00    0.030918           1     21749           mprotect
  0.12    0.000619           1       415       238 openat
  0.10    0.000538           2       223           read
  0.09    0.000447           1       372           sched_yield
  0.06    0.000328           1       246       182 stat
  0.05    0.000266           1       190           close
  0.04    0.000214           1       165           fstat
  0.04    0.000186          12        15           socket
  0.04    0.000185          23         8           sendmmsg
  0.03    0.000171          10        16           poll
  0.02    0.000128           0       274           rt_sigprocmask
  0.02    0.000090           4        22         4 connect
  0.01    0.000069           2        29           set_robust_list
  0.01    0.000056           2        28           clone
  0.01    0.000054           0        62           fcntl
  0.01    0.000044           8         5           setsockopt
  0.01    0.000030           1        27           sched_setscheduler
  0.01    0.000029           0        56           sched_get_priority_max
  0.01    0.000029           0        56           sched_get_priority_min
  0.00    0.000025           1        22           statfs
  0.00    0.000022           0        23           lseek
  0.00    0.000021           0        30           prctl
  0.00    0.000020           3         6         1 access
  0.00    0.000020           1        19           prlimit64
  0.00    0.000015           0        44           gettid
  0.00    0.000009           1         8           getcwd
  0.00    0.000007           0        25           getpid
  0.00    0.000007           0         8           geteuid
  0.00    0.000005           1         4           sysinfo
  0.00    0.000004           0        29           rt_sigaction
  0.00    0.000004           0         5           getuid
  0.00    0.000004           0         6           sched_getaffinity
  0.00    0.000002           2         1           ioctl
  0.00    0.000002           0         4           uname
  0.00    0.000002           2         1           getrusage
  0.00    0.000001           1         1           fstatfs
  0.00    0.000000           0         7           write
  0.00    0.000000           0         2           lstat
  0.00    0.000000           0         4           brk
  0.00    0.000000           0         1           pread64
  0.00    0.000000           0        26           madvise
  0.00    0.000000           0         4           sendto
  0.00    0.000000           0        14           recvmsg
  0.00    0.000000           0         4           bind
  0.00    0.000000           0        12           getsockname
  0.00    0.000000           0         2           getsockopt
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         2           kill
  0.00    0.000000           0         3           readlink
  0.00    0.000000           0         1           getgid
  0.00    0.000000           0         1           getegid
  0.00    0.000000           0         1           mlock
  0.00    0.000000           0         2         1 arch_prctl
  0.00    0.000000           0         6           getdents64
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0        30           clock_gettime
  0.00    0.000000           0         1           clock_getres
  0.00    0.000000           0         2           get_mempolicy
  0.00    0.000000           0         2           ppoll
------ ----------- ----------- --------- --------- ----------------
100.00    0.515650                 60370      1156 total

Summary of problem
------------------
When I typed "java -version" at the console, it took a long time to response.
I do not konow wether this is an issue of AdoptOpenJDK , nor any dependency package should be installed.

Thanks for your help.

**Comment by pshipton** [comment]
@RuiBaiXYZ what happens if you try the Large Heap (XL) variation? 
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9
I suspect the slow startup time with the compressed refs variation is related to troubles searching for memory for the object heap.

With the slow JVM, please run `java -Xdump:java:events=vmstart -version` which will create a text file starting with `javacore` which you can attach to this Issue.

**Comment by RuiBaiXYZ** [comment]
@pshipton Thanks for your reply.
Please refer to the attachment to confirm the detail of the command `java -Xdump:java:events=vmstart -version`.

[javacore.20200219.100124.17634.0001.txt](https://github.com/eclipse/openj9/files/4222756/javacore.20200219.100124.17634.0001.txt)

And below is the console output.

JVMDUMP039I Processing dump event "vmstart", detail "" at 2020/02/19 10:01:24 - please wait.
JVMDUMP032I JVM requested Java dump using '/home/coder/javasharedresources/javacore.20200219.100124.17634.0001.txt' in response to an event
JVMDUMP010I Java dump written to /home/coder/javasharedresources/javacore.20200219.100124.17634.0001.txt
JVMDUMP013I Processed dump event "vmstart", detail "".
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

I will try the large heap version later. Thanks for your help.

**Comment by pshipton** [comment]
The javacore indicates the object heap was placed at 0x417CA0000, which isn't ideal, but suggests a work around. You can try running the JVM you have with the option `-Xgc:preferredHeapBase=0x418000000`. 

I created a `CentOS Linux release 8.1.1911 (Core)` machine (uname -r is different 4.18.0-147.3.1.el8_1.x86_64), and wasn't able to reproduce the problem. I got a heap base of 0xE0000000).

It would be interesting to see the contents of `/proc/<pid>/maps`, where `<pid>` is the pid of the running java process. You can do this by running `java "-Xdump:tool:events=vmstart,exec=sleep 100" -version &`, which will print the pid, like `[1] 2916`. Then you can `cat /proc/<pid>/maps > javamaps.txt` to capture the data.

**Comment by pshipton** [comment]
I updated my machine to 4.18.0-147.5.1.el8_1.x86_64 and still can't reproduce the problem.

**Comment by RuiBaiXYZ** [comment]
Here is the output of `cat /proc/<pid>/maps`.

$ `java "-Xdump:tool:events=vmstart,exec=sleep 100" -version &`
[1] 26384
$ `cat /proc/26384/maps > javamaps-26384.txt`

[javamaps-26384.txt](https://github.com/eclipse/openj9/files/4223380/javamaps-26384.txt)

$ JVMDUMP039I Processing dump event "vmstart", detail "" at 2020/02/19 14:01:51 - please wait.
JVMDUMP007I JVM Requesting Tool dump using 'sleep 100'
JVMDUMP011I Tool dump created process 26490
JVMDUMP013I Processed dump event "vmstart", detail "".
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

[1]+  Done                    java "-Xdump:tool:events=vmstart,exec=sleep 100" -version

@pshipton , Thank you.

**Comment by pshipton** [comment]
There is nothing in the proc/maps which indicates why such a high memory allocation was required. @dmitripivkine do you have any suggestions? We may need to enable some debugging output in the code. 

@RuiBaiXYZ Does `-Xgc:preferredHeapBase=0x418000000` fix the slow startup problem?

**Comment by dmitripivkine** [comment]
Object heap memory has been allocated with top address at 32 GB (0x0000000800000000):
```
1STHEAPREGION  0x00007F310C0C0C60 0x0000000417CA0000 0x00000004182A0000 0x0000000000600000 Generational/Tenured Region 
1STHEAPREGION  0x00007F310C0C0450 0x00000007FFE00000 0x00000007FFF00000 0x0000000000100000 Generational/Nursery Region 
1STHEAPREGION  0x00007F310C0BFC40 0x00000007FFF00000 0x0000000800000000 0x0000000000100000 Generational/Nursery Region 
```
This is optimum behaviour and it means the memory for Object Heap has been allocated **at first request**. However I noticed that requested maximum Object heap size is 16780754944 bytes (slightly under 16GB). This is Java 11 so default  `-Xmx` value is selected as 25% of RAM available on machine (so I guess 64GB total). If it is not intended `-Xmx<size>` option should be used explicitly.

Well, it does not explain why startup time is slow but it might be related indirectly.  Would you please try start JVM with smaller heap?

Also javacore tells us the heap range `[0x417CA0000,0x800000000]` and usually it is one line in mmap file. But there are three in this case:
```
417ca0000-4182a0000 rw-p 00000000 00:00 0 
4182a0000-7ffe00000 ---p 00000000 00:00 0 
7ffe00000-800000000 rw-p 00000000 00:00 0 
```

**Comment by dmitripivkine** [comment]
>Also javacore tells us the heap range [0x417CA0000,0x800000000] and usually it is one line in mmap file. But there are three in this case:

Looks like is normal. We do have the same behaviour on our test machine

**Comment by dmitripivkine** [comment]
> > Also javacore tells us the heap range [0x417CA0000,0x800000000] and usually it is one line in mmap file. But there are three in this case:
> 
> Looks like this is normal. We do have the same behaviour on our test machine

The line in the middle represents uncommitted part of Tenure (Old Space). This is normal

**Comment by RuiBaiXYZ** [comment]
> @RuiBaiXYZ Does `-Xgc:preferredHeapBase=0x418000000` fix the slow startup problem?

@pshipton After add jvm argument `-Xgc:preferredHeapBase=0x418000000`, this phenomenon still exists I think.

`$time java -version -Xgc:preferredHeapBase=0x418000000`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m13.254s
user	0m0.058s
sys	0m0.051s

`$time java -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m15.360s
user	0m0.074s
sys	0m0.038s

**Comment by pshipton** [comment]
Pls try Dmitri's suggestion as well, `java -Xmx8g -version` to see if that makes any difference. If not, you can try smaller sizes.

If that doesn't help, what about `java -Xshareclasses:none -version`.

**Comment by RuiBaiXYZ** [comment]
`$ time java -Xmx8g -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m5.697s
user	0m0.068s
sys	0m0.042s

`$time java -Xmx1g -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m13.631s
user	0m0.099s
sys	0m0.037s

`$time java -Xmx512m -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m24.410s
user	0m0.086s
sys	0m0.048s

`time java -Xshareclasses:none -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m18.592s
user	0m0.083s
sys	0m0.042s

`$time java -Xmx8g -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m14.521s
user	0m0.065s
sys	0m0.047s


It seems to have no effect. Wether this related to my workstation's hardware or installed software?
`$lspci` 
00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 0d)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 0d)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile) (rev 02)
00:04.0 Signal processing controller: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (rev 0d)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 (rev 10)
00:15.1 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #1 (rev 10)
00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
00:17.0 SATA controller: Intel Corporation Cannon Lake Mobile PCH SATA AHCI Controller (rev 10)
00:1b.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #21 (rev f0)
00:1c.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #1 (rev f0)
00:1c.5 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #6 (rev f0)
00:1c.6 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #7 (rev f0)
00:1f.0 ISA bridge: Intel Corporation Device a30e (rev 10)
00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (7) I219-LM (rev 10)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Lexa XT [Radeon PRO WX 3200]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Baffin HDMI/DP Audio [Radeon RX 550 640SP / RX 560/560X]
02:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983
03:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
04:00.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
04:01.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
04:02.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
04:04.0 PCI bridge: Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge 4C 2018] (rev 06)
05:00.0 System peripheral: Intel Corporation JHL7540 Thunderbolt 3 NHI [Titan Ridge 4C 2018] (rev 06)
39:00.0 USB controller: Intel Corporation JHL7540 Thunderbolt 3 USB Controller [Titan Ridge 4C 2018] (rev 06)
6e:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5260 PCI Express Card Reader (rev 01)
6f:00.0 Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)

**Comment by RuiBaiXYZ** [comment]
I created a virtual machine via VM Player with parameters:

- Memory 8GB
- Processors 2

Sadly, virtual machine has the same phenomenon. 

`# cat /etc/redhat-release`
CentOS Linux release 8.1.1911 (Core) 
`# uname -r`
4.18.0-147.5.1.el8_1.x86_64
`# time java -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit 20200122_403 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m15.860s
user	0m0.047s
sys	0m0.043s

`# java -Xdump:java:events=vmstart -version`
JVMDUMP039I Processing dump event "vmstart", detail "" at 2020/02/20 11:49:02 - please wait.
JVMDUMP032I JVM requested Java dump using '/root/javacore.20200220.114902.3048.0001.txt' in response to an event
JVMDUMP010I Java dump written to /root/javacore.20200220.114902.3048.0001.txt
JVMDUMP013I Processed dump event "vmstart", detail "".
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit 20200122_403 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

[javacore.20200220.114902.3048.0001.txt](https://github.com/eclipse/openj9/files/4228702/javacore.20200220.114902.3048.0001.txt)

`# time java -Xmx1g -version`
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit 20200122_403 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m30.768s
user	0m0.052s
sys	0m0.044s

**Comment by RuiBaiXYZ** [comment]
I guess the reason is memory. 
My workstation's memory is 64GB, the  phenomenon occured.

While I created another virtual machine, via VM Player, allocated 4GB memory, every thing goes well.

And now, reinstalled my workstation with following steps:

1. Install from CentOS-8.1.1911-x86_64-dvd1.iso
2. `dnf -y update`
3. `dnf -y group install "Development Tools"`
4. reboot
5. `mkdir -p /usr/java`
6. `mv jdk-11.0.6+10/ /usr/java/`
7. `alternatives --install /usr/bin/java java /usr/java/jdk-11.0.6+10/bin/java 2`
8. `alternatives --config java`  --> select 2
9. time java -version
    real    0m40.209s

The first time it expended 40 seconds.

**Comment by pshipton** [comment]
Pls try the Large Heap build.

**Comment by RuiBaiXYZ** [comment]
I am so sorry.
Tried with `OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.6_10_openj9-0.18.1.tar.gz`, still need 40 seconds.

`# time java -Xdump:java:events=vmstart -version`
JVMDUMP039I Processing dump event "vmstart", detail "" at 2020/02/20 21:44:37 - please wait.
JVMDUMP032I JVM requested Java dump using '/home/coder/javacore.20200220.214437.6784.0001.txt' in response to an event
JVMDUMP010I Java dump written to /home/coder/javacore.20200220.214437.6784.0001.txt
JVMDUMP013I Processed dump event "vmstart", detail "".
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit 20200122_403 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

real	0m40.380s
user	0m0.172s
sys	0m0.056s

[javacore.20200220.214437.6784.0001.txt](https://github.com/eclipse/openj9/files/4231039/javacore.20200220.214437.6784.0001.txt)

**Comment by pshipton** [comment]
Pls run `java -verbose:init -version` which might help identify where the time is being spent.

**Comment by pshipton** [comment]
Guessing again at where the problem might be, there is something else you can try to onfirm.

Using the Large Heap JVM:
- `bin/java -Xdump:system:events=vmstart` to produce a core* file
- `bin/jdmpview -core <core file>`
- copy and paste the output from `!findvm` and add ` | grep RAS` to end. For example, `!findvm` might show `!j9javavm 0x00007F97AC00DC50` so I want to see the output from `!j9javavm 0x00007F97AC00DC50 | grep RAS`

**Comment by pshipton** [comment]
One other idea, pls try `java -Xint -version`

**Comment by RuiBaiXYZ** [comment]
> Pls run `java -verbose:init -version` which might help identify where the time is being spent.

Attachement is the console output of large heap verion.

[java-verbose-init-version.txt](https://github.com/eclipse/openj9/files/4233301/java-verbose-init-version.txt)

**Comment by pshipton** [comment]
This looks like the culprit.
```
	for library VMInitStages...
		enabled network query to determine host name and IP address for RAS.
		completed with rc=0 in 40041709949 nano sec.
```

Does running with `-XX:-ReadIPInfoForRAS` fix it? Seems your network isn't setup properly.

**Comment by RuiBaiXYZ** [comment]
@pshipton  Great, solved with `-XX:-ReadIPInfoForRAS`. 

I think this is due to network restriction of china. 
But can you tell to me that why need to determine network for RAS, and what is the host name/IP , or the pursose of this mechanism.

Thank you very much.

**Comment by RuiBaiXYZ** [comment]
Additional question.
Suppose because of the network.
Yesterday, the virtual machine(4GB Memory) was created on workstation, they had the same network and the same jdk version. Virtual machine was normal to response, but workstation was slow. I think there may be some reasons, sadly, but I do not know how do investigate.

**Comment by RuiBaiXYZ** [comment]
> @pshipton Great, solved with `-XX:-ReadIPInfoForRAS`.
> 
> I think this is due to network restriction in China.
> But can you tell to me that why need to determine network for RAS, and what is the host name/IP , or the pursose of this mechanism.

I found this link [-XX:[+|-]ReadIPInfoForRAS](https://www.eclipse.org/openj9/docs/xxreadipinfoforras/
)

**Comment by pshipton** [comment]
> I found this link -XX:[+|-]ReadIPInfoForRAS

Yes, the JVM just stores the information so it's available in a system core file. It can be useful for diagnosing some types of problems.

**Comment by RuiBaiXYZ** [comment]
Is there any solution to close globally.  As  `-XX:-ReadIPInfoForRAS`.
I tried with JAVA_OPTS but no effect.

**Comment by JasonFengJ9** [comment]
> I tried with JAVA_OPTS but no effect.

`OPENJ9_JAVA_OPTIONS` can set the command line option environment variables.

**Comment by RuiBaiXYZ** [comment]
@JasonFengJ9 Great, successfully set environment variables with `OPENJ9_JAVA_OPTIONS`.
Thanks.
