### ISSUE TITLE
Slight performance degradation in time to first request between 232-b09 and 242-b08

### ISSUE THREAD

**Issue by dettmoney** [eclipse/openj9#8607]
Java -version output
--------------------
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
Eclipse OpenJ9 VM (build openj9-0.18.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200122_511 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - 8cf8a30581 based on jdk8u242-b08)

Summary of problem
------------------
I have a test that I run that measures time to respond to first request for WebSphere Liberty involving a very simple REST application. Between 232-b09 and 242-b08, the time has gone up about 10ms from 1.044 to 1.054 seconds on average. I'm using a shared class cache in both cases.

Diagnostic files
----------------
N/A

OutOfMemoryError: Java Heap Space
---------------------------------
N/A

**Comment by DanHeidinga** [comment]
@dettmoney Can you provide the `java -version` output for the 232-b09 version as well?  It makes it easier for us to look at the changes between the two versions as the output includes the OpenJ9 git SHAs

**Comment by dettmoney** [comment]
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)

**Comment by DanHeidinga** [comment]
Thanks @dettmoney.

That's 4 months worth of changes so there's a lot to look at.  Can you share the application?  Having access to run it will help to track down the regression.

fyi @andrewcraik @vijaysun-omr

**Comment by DanHeidinga** [comment]
Had an offline conversation with @dettmoney and connected him to Piyush to help narrow the window for when the regression was introduced

**Comment by mpirvu** [comment]
There is a good chance this is a dup of #8660

**Comment by dettmoney** [comment]
I tried my test with the 03-09 nightly from adoptopenjdk - regression is gone and we've actually gained from the previous 232b09 level. This issue can be closed
