### ISSUE TITLE
Java Crypto APIs fails on Windows machines without the "Microsoft Visual C++ 2013 Redistributable" 

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#8618]
Hello,

When installing AdoptOpenJDK 11 with OpenJ9 on a Windows machine having no "Microsoft Visual C++ 2013 Redistributable" installed, Java applications relying on Java Cryptographic API fail to run.

We traced the issue and found that the root cause of it is that in OpenJ9 0.16.0, `libcrypto-1_1-x64.dll` is linked with old visual studio runtime, and that this runtime is not part of the AdoptOpenJDK 11.0.6 OpenJ9 distribution.

Here's the precise version we used:
```
>java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
```

OpenJ9 DLLs are linked on Windows with recent visual studio.

They rely on `vcruntime140.dll`, and this DLL is redistributed, which is the expected behavior for AdoptOpenJDK OpenJ9 for Windows.

However, `libcrypto-1_1-x64.dll` (part of OpenSSL) is linked with `MSVCR120.dll`, and this DLL is not redistributed.

This raises an issue on computers not having the "Microsoft Visual C++ 2013 Redistributable" installed.

Would it be possible to use a recent visual studio to build libcrypto-1_1-x64.dll?

Knd regards,
Alexandre Vermeerbergen

**Comment by pshipton** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-build/issues/1556 and I'll close this one.

**Comment by avermeer** [comment]
Thank you very much, this wasn't clear to me on which list this had to be opened
