### ISSUE TITLE
Using OPENJ9_JAVA_OPTIONS versus JAVA_OPTS causes confusion

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#8641]
This issue is to discuss whether OpenJ9 should support (not ignore JAVA_OPTS), as recently there have been 3 separate users that have tried to use JAVA_OPTS and have hit difficulties.  (https://github.com/eclipse/openj9/issues/8619 is one example).

JAVA_OPTS="-Xmx8000m" option is not recognized by OpenJ9, so you have to use OPENJ9_JAVA_OPTIONS="-Xmx8000m".  

Is this something that we can or should be addressing to minimize user confusion?

**Comment by DanHeidinga** [comment]
Historically, I believe we've avoided supporting `JAVA_OPTS` to allow frameworks & scripts to set Hotspot-specific options there and J9-specific ones in `OPENJ9_JAVA_OPTIONS`.

It may be time to revisit that decision.  

The caveat here being what to do with environments that used the flexibility to specify options separately.  We may want a graceful fallback to ignore unrecognized options in `JAVA_OPTS` for migration compatibility.  Or not if we can determine the flexibility wasn't extensively used.

**Comment by DanHeidinga** [comment]
Assigning to Milestone 20 as we should make a decision on this before that release

**Comment by mstoodle** [comment]
Another possibility might be to by default ignore unrecognized options specifically during `JAVA_OPTS` processing (is that easy to do?) . Then `-XX:-IgnoreUnrecognizedVMOptions` could override this behaviour if the user really wants to know when they're using a bad option.

Backwards compatibility requires an option to *not* process `JAVA_OPTS` entirely, doesn't it? There could be different (perfectly valid) tuning options there...

**Comment by pshipton** [comment]
> Assigning to Milestone 20 as we should make a decision on this before that release

@DanHeidinga any objections to moving this forward? It's too late to make changes to support JAVA_OPTS, and I don't see this assigned to anyone.

**Comment by DanHeidinga** [comment]
Agreed.  Moving it forward as we haven't had a chance to resolve this yet

**Comment by DanHeidinga** [comment]
Moving this to the next milestone but we should do this (and should have already done it).

OpenJ9 should accept both options unconditionally.  I don't see an migration concerns raised so far and so we'll do the simple thing to make this work

**Comment by pshipton** [comment]
I'll work on the suggestions in the draft PR for the next release.
