### ISSUE TITLE
Startup time regression from 0.17 to 0.18.1 openj9 release

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8660]
Startup time of Liberty application server has increased some 5-8% from release 0.17 to release 0.18.1. Looking at the verbose logs I see fewer AOT compilations with 0.18.1.
In release 0.17 a change was delivered to lower the invocation counts for a SCC (shared-class-cache) cold run in order to generate more AOT bodies. This change improved start-up time.
Subsequently, PR #7703 enabled this reduction of invocation counts only if
`J9_SHARED_CACHE_DEFAULT_BOOT_SHARING(jitConfig->javaVM) == true`
This in turn is defined as:
```
#if defined(OPENJ9_BUILD)
#define J9_SHARED_CACHE_DEFAULT_BOOT_SHARING(vm) TRUE
#else /* defined(OPENJ9_BUILD) */
#define J9_SHARED_CACHE_DEFAULT_BOOT_SHARING(vm) FALSE
#endif /* defined(OPENJ9_BUILD) */
```

However, instrumentation of the code shows that OPENJ9_BUILD is not defined

**Comment by pshipton** [comment]
It's defined when compiling the VM here
https://github.com/eclipse/openj9/blob/5f64d16f35681782bcda4c81f236eadc354e2d68/runtime/makelib/targets.mk.ftl#L97
but I don't think that includes the JIT.

**Comment by vijaysun-omr** [comment]
@dsouzai fyi

**Comment by dsouzai** [comment]
Essentially all we want is to only lower the counts if both of the following are true:

1. The JVM is OpenJDK+OpenJ9 (and not some other JVM like the IBM SDK)
2. The SCC the JVM is using is not the default SCC

@pshipton what is the best way of querying for that?

**Comment by hangshao0** [comment]
>1. The JVM is OpenJDK+OpenJ9 (and not some other JVM like the IBM SDK)

If OPENJ9_BUILD is defined, it is OpenJDK+OpenJ9

> 2. The SCC the JVM is using is not the default SCC

Check J9SHR_RUNTIMEFLAG_ENABLE_CACHE_NON_BOOT_CLASSES in javaVM->sharedClassConfig->runtimeFlags. If it is set, it is not the default SCC.

**Comment by mpirvu** [comment]
Current JIT code has the following tests:
```
                  if (J9_SHARED_CACHE_DEFAULT_BOOT_SHARING(jitConfig->javaVM) &&
                      J9_ARE_ALL_BITS_SET(jitConfig->javaVM->sharedClassConfig->runtimeFlags, J9SHR_RUNTIMEFLAG_ENABLE_CACHE_NON_BOOT_CLASSES))
```
and the problem is that `OPENJ9_BUILD` does not appear to be defined to the JIT code.
In PR #8668 I am changing the JIT makefiles to add that definition.
