### ISSUE TITLE
j9_sanity.openjdk getJtreg : [exec] gzip: jtreg-4.2.0-tip.tar.gz: not in gzip format

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8684]
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/297`.
This also happened in a few other platform builds.

Optional info
-------------

Intermittent failure

Failure output (captured from console output)
---------------------------------------------

```
00:19:59  getJtreg:
00:19:59      [mkdir] Created dir: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/jvmtest/openjdk
00:20:01       [exec] gzip: jtreg-4.2.0-tip.tar.gz: not in gzip format
00:20:01  
00:20:01  BUILD FAILED
00:20:01  /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
00:20:01  /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/openjdk-tests/openjdk/build.xml:162: The following error occurred while executing this line:
00:20:01  /Users/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_Nightly/openjdk-tests/openjdk/build.xml:38: exec returned: 1
00:20:01  
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau @llxia @smlambert

**Comment by pshipton** [comment]
I didn't see this in the OpenJ9 builds last night. Since this only occurs in internal builds I wonder if it needs to be an OpenJ9 issue.

**Comment by AdamBrousseau** [comment]
Yea I see lots of these today, yesterday it was
```
02:24:21.566  getJtreg:
02:24:21.566      [mkdir] Created dir: C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.openjdk_x86-64_windows_xl_Nightly\jvmtest\openjdk
02:24:42.399       [exec] curl: (18) transfer closed with 75135 bytes remaining to read
```
It's about 50% failure rate on last night's build.

**Comment by AdamBrousseau** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/blob/39b183dfea8842e443aa8da9b2c3d3425486897e/openjdk/build.xml#L36
I can curl and untar the file fine so possibly some overnight networking issues? Odd to see so many over 2 nights though.

**Comment by AdamBrousseau** [comment]
Opened failure-cause-management/0017a981-435f-4e74-b155-8c35e5e631b0/ to track internally.

**Comment by AdamBrousseau** [comment]
I also see at least 5 different clone/curl failures over the past 2 nights in various stages of the test builds. Seems more so on zlinux but not restricted, also see some on Windows.

**Comment by smlambert** [comment]
ci.adoptopenjdk.net has been experiencing issues lately and we pull jtreg from a job on that server

(related to https://openj9.slack.com/archives/CDS7QE9HB/p1582915253009400 - mucho crashes in openjdk j9 runs that then fill up Jenkins master and take out the server, see related: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1659 and of course fixing this recent openj9 issue that is causing all of these crashes in sanity.openjdk suite)

**Comment by smlambert** [comment]
FYI, ci.adoptopenjdk.net is being upgraded and rebooted today (to address some of these recent issues).
The openj9 crashes that were causing the artifact bloat is also addressed.

There are workarounds for this jtreg failure if people are drastically affected (though I will imagine its less so at the openj9 server, as Pete mentioned, not running openjdk tests regularly at openj9 yet).

**Comment by JasonFengJ9** [comment]
A quick note that this failure wasn't seen in recent internal builds.
Will close if it stays that way for next day or two.

**Comment by smlambert** [comment]
That failure will only occur when the AdoptOpenJDK Jenkins server is down (which should be never, but has happened recently due to storage issues).  The first of 2 actions to address the storage issue has been delivered today, the 2nd will be delivered after this months release is completed, so the server should be even more solid after that.

**Comment by JasonFengJ9** [comment]
@smlambert thanks for the insights.
Closing.
