### ISSUE TITLE
RH zlinux build machines are very slow building jdk8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8696]
It seems the builds on the new RH zlinux machines are taking 2 hours. The old machines took about 20min usually.

https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/303/ - UB16 - 18min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/304/ - UB16 - 17min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/305/ - UB16 - 17min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/306/ - UB16 - 70min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/307/ - UB16 - 24min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/308/ - RH7 - 120min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/309/ - RH7 - 120min
https://ci.eclipse.org/openj9/job/Build_JDK8_s390x_linux_Nightly/310/ - RH7 - 120min

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment]
UB16
```
22:56:45  ----- Build times -------
22:56:45  Start 2020-02-25 03:40:24
22:56:45  End   2020-02-25 03:56:45
22:56:45  00:00:09 corba
22:56:45  00:00:10 demos
22:56:45  00:01:12 docs
22:56:45  00:01:12 images
22:56:45  00:00:07 jaxp
22:56:45  00:00:10 jaxws
22:56:45  00:01:44 jdk
22:56:45  00:00:21 langtools
22:56:45  00:00:05 nashorn
22:56:45  00:16:21 TOTAL
```

RH7
```
00:04:13  ----- Build times -------
00:04:13  Start 2020-02-25 22:13:07
00:04:13  End   2020-02-26 00:04:03
00:04:13  00:02:25 corba
00:04:13  00:00:17 demos
00:04:13  00:40:53 docs
00:04:13  00:11:02 images
00:04:13  00:03:40 jaxp
00:04:13  00:04:10 jaxws
00:04:13  00:30:54 jdk
00:04:13  00:05:36 langtools
00:04:13  00:01:37 nashorn
00:04:13  01:50:56 TOTAL
```

**Comment by AdamBrousseau** [comment]
Note the Java11+ builds are fast. I see the same behaviour internally. Something about JDK8?

**Comment by pshipton** [comment]
@AdamBrousseau What jdk8 boot jdk is being used?

**Comment by pshipton** [comment]
i.e. I suspect the boot jdk is a Hotspot version that doesn't have a JIT, pls update it to an OpenJ9 version.

**Comment by pshipton** [comment]
To answer my own question:

`openjdk version "1.8.0_242" OpenJDK Runtime Environment (build 1.8.0_242-b08) OpenJDK 64-Bit Zero VM (build 25.242-b08, interpreted mode)  (at /usr/lib/jvm/adoptojdk-java-s390x-80)`

**Comment by AdamBrousseau** [comment]
I will update with OpenJ9 JDK8 0.18.1

**Comment by AdamBrousseau** [comment]
Updated symlink to point to OpenJ9 jdk8 0.18.1

**Comment by pshipton** [comment]
Much better now
```
18:05:05  ----- Build times -------
18:05:05  Start 2020-03-02 17:52:28
18:05:05  End   2020-03-02 18:05:05
18:05:05  00:00:08 corba
18:05:05  00:00:09 demos
18:05:05  00:00:54 docs
18:05:05  00:00:58 images
18:05:05  00:00:06 jaxp
18:05:05  00:00:09 jaxws
18:05:05  00:01:37 jdk
18:05:05  00:00:20 langtools
18:05:05  00:00:04 nashorn
18:05:05  00:12:37 TOTAL
18:05:05  -------------------------
```
