### ISSUE TITLE
Are there any ways to track all of openj9 call stacks when a java "hello world" running?

### ISSUE THREAD

**Issue by aaltonenzhang** [eclipse/openj9#870]

**Comment by pshipton** [comment]
I'm not sure exactly what you are looking for. You can get the call stacks from a particular  moment in time by using `kill -QUIT <pid>` to send a signal to the JVM process. By default this will generate a file called a javacore, which contains all of the java call stacks. 

Let me know what it is you are trying to do and I might have other suggestions.

**Comment by aaltonenzhang** [comment]
Actually, what I want is to get all of VM call stacks(c/c++ methods, e.g. JNI_CreateJavaVM()) when a java app run in it, not java stacks.

**Comment by pshipton** [comment]
You'll need to  use a native debugger like gdb for that.

**Comment by fjeremic** [comment]
> You'll need to use a native debugger like gdb for that.

Do we build with debug symbols by default even in prod builds?
