### ISSUE TITLE
Feature request: Allow default javacore file name for jcmd Dump.java

### ISSUE THREAD

**Issue by kgibm** [eclipse/openj9#8721]
Using jcmd with Dump.java without a filename gives an error and its help shows that a file name is required:
```
$ jcmd 2440 Dump.java
Error: Error in command
Error: wrong number of arguments
$ jcmd 2440 help Dump.java
Dump.java: Create a javacore file.
 Format: Dump.java <file path>
 <file path> is mandatory: there is no default.
 Relative paths are resolved to the target's working directory.
 The dump agent may choose a different file path if the requested file exists.
```
It would be nice if Dump.java allowed using the default (or `-Xdump`-configured) javacore name format and directory. This would be valuable because the user wouldn't have to worry about creating a unique file name (if the command is executed multiple times), allows tools that expect the default javacore file name format, avoids the user needing to know the default javacore directory to write to, and allows for easier customization of the javacore name or directory using JVM configuration.

**Comment by JasonFengJ9** [comment]
It does make sense to allow `Dump.java` using the default settings like `-Xdump` with default settings.
Similarly this can apply to `Dump.snap` and `Dump.system` as well.

**Comment by kgibm** [comment]
Thank you.
