### ISSUE TITLE
protobuf license missing from LICENSE and longabout.html

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8733]
protobuf is not listed in
- https://github.com/eclipse/openj9/blob/master/LICENSE
- https://github.com/eclipse/openj9/blob/master/longabout.html

The fix also needs to be delivered to the v0.19.0-release branch.

**Comment by pshipton** [comment]
@mpirvu can you create a PR to fix this please.

**Comment by mpirvu** [comment]
@pshipton 
Current version of `LICENSE` file includes the description for:
```
H. musl
Copyright (c) 2005-2014 Rich Felker, et al.
```
but this is not listed in the beggining:
```
Subject to the following notices:

1.      Eclipse OMR is provided under the Eclipse Public License 2 and secondary GPLv2 license (section A) or the Apache version 2 license (section B).
2.      Unicode 6.0 & Unicode 8.0 are provided under the Unicode licence below (section C).
3.      MurmurHash3 is provided under the MurmurHash3 license below (section D).
4.      libffi is provided under the libffi license below (section E).
5.      zlib is provided under the zlib license below (section F).
6.      CuTest is provided under the CuTest license below (section G).
```
Either I'll have to add `musl` at position 7, or remove the license blurb for musl at the end. Please advise.

**Comment by pshipton** [comment]
Pls add `musl` at position 7.
