### ISSUE TITLE
rh7-390-3 seems to be flaky

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8738]
I've seen rh7-390-3 become unavailable before. Perhaps other machines as well, but I didn't keep track. Opening this to track if it's always the rh7-390-3 machine.

https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_OMR/495
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_Personal/466
'Cannot contact rh7-390-3: java.lang.InterruptedException'

**Comment by pshipton** [comment]
Disabling rh7-390-3 for now.

**Comment by AdamBrousseau** [comment]
Possibly same as what Adopt is seeing.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1154

**Comment by AdamBrousseau** [comment]
```
00:13:42.876  Compiling 2 files for BUILD_DDR_STUBS
00:13:43.681  Compiling 5019 files for BUILD_J9DDR_MAIN_CLASSES
00:14:07.709  Cannot contact rh7-390-3: java.lang.InterruptedException
00:22:43.469  wrapper script does not seem to be touching the log file in /home/jenkins/workspace/Build_JDK11_s390x_linux_OMR@tmp/durable-814eb484
00:22:43.469  (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
[Pipeline] sh
...
[Pipeline] End of Pipeline
ERROR: script returned exit code -1
Finished: FAILURE
```

**Comment by pshipton** [comment]
When it falls over, it also causes https://github.com/eclipse/openj9/issues/8729

**Comment by AdamBrousseau** [comment]
from `/var/log/messages`
Matching the time the 466 build fell over
```
Mar  3 13:49:37 openj902 journal: IBM Java[50407]: JVMJ9VM007E Command-line option unrecognised: -Xshare:dump
Mar  3 13:57:51 openj902 iucvserv: Receive OPNCLOUD 0.0.0.1  /sbin/modprobe vmcp sent from IUCV client.
Mar  3 13:57:51 openj902 iucvserv: /etc/iucv_authorized_userid exists, check authorization.
Mar  3 13:57:51 openj902 iucvserv: senduserid=OPNCLOUD, authuserid=OPNCLOUD, len=8
Mar  3 13:57:51 openj902 iucvserv: Will execute the linux command  /sbin/modprobe vmcp  2>&1; echo iucvcmdrc=$? sent from IUCV client.
Mar  3 13:57:51 openj902 iucvserv: result length=52, send message length=52,#012 modprobe: FATAL: Module vmcp not found.#012iucvcmdrc=1
Mar  3 14:00:15 openj902 kernel: Initializing cgroup subsys cpuset
Mar  3 14:00:15 openj902 kernel: Initializing cgroup subsys cpu
Mar  3 14:00:15 openj902 kernel: Initializing cgroup subsys cpuacct
Mar  3 14:00:15 openj902 kernel: Linux version 3.10.0-1062.12.1.el7.s390x (mockbuild@s390-005.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Thu Dec 12 06:45:30 EST 2019
Mar  3 14:00:15 openj902 kernel: setup: Linux is running as a z/VM guest operating system in 64-bit mode
Mar  3 14:00:15 openj902 kernel: setup: Reserving 161MB of memory at 8031MB for crashkernel (System RAM: 8192MB)
Mar  3 14:00:15 openj902 kernel: Write protected kernel read-only data: 9976k
Mar  3 14:00:15 openj902 kernel: Zone ranges:
Mar  3 14:00:15 openj902 kernel:  DMA      [mem 0x00000000-0x7fffffff]
Mar  3 14:00:15 openj902 kernel:  Normal   [mem 0x80000000-0x1ffffffff]
```
Looks like machine has restarted? I'm not an expert on these messages. I can grab the file.

**Comment by pshipton** [comment]
Restarting is consistent with the behavior we are seeing. The machine becomes available in jenkins again with a recent date/time for starting the agent `[03/03/20 15:30:11] Launching agent`

**Comment by pshipton** [comment]
Even though I disconnected it, it's active in the builds again. Perhaps I need to take it offline and disconnect it.

**Comment by pshipton** [comment]
Here's one on rh7-390-2
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_xl_Nightly/93

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/93
rh7-390-4

**Comment by AdamBrousseau** [comment]
@jdekonin thought it may be ulimits. I see a diff between the ub16 and these machines.
ub16: `max user processes              (-u) 32152`
rh7: `max user processes              (-u) 4096`
The rest seem similar.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_OMR/502
rh7-390-2

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_Nightly/315
rh7-390-1

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Build_JDK11_s390x_linux_OpenJDK11/49
rh7-390-1

**Comment by jdekonin** [comment]
@pshipton, are there still problems with the RH7 390 machines?

**Comment by pshipton** [comment]
I haven't seen any problems for some time.
