### ISSUE TITLE
xlinux jdmpview on AIX core uses little endian search

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8749]
Using OpenJ9 0.18.1 JDK11 release, I created a core file on AIX, on vmstop from running nothing in particular. `java -Xdump:system:events=vmstop`

Running jdmpview on xlinux, the command `findptr 0xb1234567,0x30000000,0x30000040,,,` shows it's looking for the little endian ptr `issuing: find 0x674523b1,0x30000000,0x30000040,,,1` which doesn't seem correct considering the core file is big endian.

May be related to #8748

**Comment by pshipton** [comment]
@keithc-ca fyi

**Comment by pshipton** [comment]
May be related to #8748

**Comment by keithc-ca** [comment]
This is unrelated to #8748.

**Comment by mikezhang1234567890** [comment]
Taking a look at this issue.

**Comment by keithc-ca** [comment]
@mikezhang1234567890
You may want to have a look at https://github.com/keithc-ca/openj9/tree/findptr

**Comment by pshipton** [comment]
@mikezhang1234567890 is there any outlook on a fix for this? Otherwise I'll move it forward to the next milestone.

**Comment by mikezhang1234567890** [comment]
Yes, should have a fix ready soon.
