### ISSUE TITLE
Java 11 on Windows x86

### ISSUE THREAD

**Issue by MariusVolkhart** [eclipse/openj9#8773]
This is a feature request to support OpenJ9 with Java 11 on Windows x86.

## Current state
Currently, the OpenJ9 [build docs for Java 8](https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md#windows) indicate support for Windows x86, but the [docs for Java 11](https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V11.md#windows) and on do not.

The folks at AdoptOpenJDK [have indicated](https://github.com/AdoptOpenJDK/openjdk-build/issues/1506#issuecomment-579706184) that without official support from OpenJ9, they will not produce x86 binaries - certainly a reasonable position.

I have been unable to find any information as to why OpenJ9 with Java 11 on Windows x86 is not supported while Java 8 is.

## The case for x86 support
OpenJ9 touts a "Low memory footprint" and "Fast startup time" as signature reasons for choosing OpenJ9 over other VMs like HotSpot. One of the places where these benefits have a noticeable impact is on smaller, less-beefy machines. Machines running Windows x86 are typically those types of machines.

Enterprise environments continue to have many Windows x86 machines deployed, even running Windows 10. Indeed, many of the benefits that OpenJ9 offers for cloud applications are also relevant inside of enterprises, where virtual servers and desktops continue to play a major role.

As a result, Windows x86 is not just a legacy deployment target that exists only to run apps from 6 years ago. It remains an actively supported platform, and new software continues to be written for it.

## The case for Java 11
Project Jigsaw in Java 9, and the Java module system it introduced is amongst the biggest changes the Java ecosystem has seen since Java 8. It changed how developers are able to package and deploy Java applications. Library authors create multi-targeting libraries and define modules for their code. Application developers use `jlink` or `jpackage` to create custom runtime images. Having only a Java 8 option available for OpenJ9 on Windows x86 means developers are unable to take advantage of these features. Java 11 is the only LTS option available that supports modules and the changes they bring.

## Conclusion
Supporting OpenJ9 with Java 11 on Windows x86 gives developers an avenue to use the module system on resource-constrained environments outside of the cloud. It allows developers to update their tooling, knowledge, and processes to accommodate the inevitable future.

The AdoptOpenJDK folks seem willing to build for Windows x86 assuming there is support from the OpenJ9 project.

Making the Open J9 Java 11 LTS release available on Windows x86 gives enterprise developers a more modern deployment option without having to choose between ideal runtime and modern development environment.

**Comment by DanHeidinga** [comment]
> Indeed, many of the benefits that OpenJ9 offers for cloud applications are also relevant inside of enterprises, where virtual servers and desktops continue to play a major role.

+1

@MariusVolkhart I'm sympathetic to your desire to have JDK11 OpenJ9 builds on 32-bit windows.  The benefits of OpenJ9 are hugely important for constrained environments and I've made the same arguments that developers desktops are very similar to cloud environments.

Unfortunately, the market share of 32bit systems is quite small and continues to shrink.  See data from https://www.pcbenchmarks.net/os-marketshare.html (updated in March 2020) which shows Windows 10 32 bit at 0.62% of the market and Windows 7 32 bit at 0.65% of the market and has a graph showing the very small segment that is 32bit.

Data from Stream's hardware survey (https://store.steampowered.com/hwsurvey/) shows a similar picture - 32 bit windows 10 is 0.16% and windows 7 is 0.74%.

The biggest determiner for not supporting 32 bit versions of Windows is project resources.  There are only so many Windows machines in our build farm and only so many people maintain those machines.  Add in time to triage builds, fix bugs, and generally treat it as a first class platform, and a new platform is a big commitment.

This may be an area we'd revisit if hardware (or cloud machines) was donated for this purpose and there was a commitment to help with the build triage.  If that's interesting to you, then we may be better to have a higher bandwidth conversation via a phone call or webex about the options here.

**Comment by MariusVolkhart** [comment]
Thanks for the response @DanHeidinga . I appreciate the position you are in, and that you took the time to respond. Having a project member indicate the likelihood of this feature is helpful. I'm going to close this issue.

Thank you all for the work you're doing on the VM and the talks you give detailing the inner workings! I'm excited for OpenJ9 to see more usage.

**Comment by DanHeidinga** [comment]
Thanks for the kind words @MariusVolkhart.

If you, or anyone, wants to contribute hw & time to bring up a new platform we can work together to make that happen.
