### ISSUE TITLE
osx1011-x86-1 wget Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8794]
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_special.system_x86-64_mac_Personal/29
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_mac_Nightly/296
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/304
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_mac_Nightly/305
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_sanity.system_x86-64_mac_Nightly/29
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_mac_Personal/170
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_mac_Nightly/306
osx1011-x86-1
```
16:26:14  configure-asm:
16:26:14       [echo] Executing macro download-file
16:26:14       [echo] File to download: https://repository.ow2.org/nexus/content/repositories/releases/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
16:26:14       [echo] Destination: /Users/jenkins/workspace/Test_openjdk14_j9_special.system_x86-64_mac_Personal/openjdk-tests/systemtest_prereqs/asm-7.3.1/asm-7.3.1.jar
16:26:14       [echo] Download tool: wget
16:26:14      [mkdir] Created dir: /Users/jenkins/workspace/Test_openjdk14_j9_special.system_x86-64_mac_Personal/openjdk-tests/systemtest_prereqs/asm-7.3.1
16:26:14       [exec] dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
16:26:14       [exec]   Referenced from: /usr/local/bin/wget
16:26:14       [exec]   Reason: image not found
16:26:14       [exec] Result: 133
16:26:14  
16:26:14  print-asm-location:
16:26:14  
16:26:14  print-asm-error:
16:26:14       [echo] ERROR: Cannot find asm-7.3.1.jar at /Users/jenkins/workspace/Test_openjdk14_j9_special.system_x86-64_mac_Personal/openjdk-tests/systemtest_prereqs/asm-7.3.1/asm-7.3.1.jar
```

**Comment by pshipton** [comment]
@jdekonin not sure if this is a machine problem or a temporary hickup.
```
16:26:14       [exec] dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
16:26:14       [exec]   Referenced from: /usr/local/bin/wget
```

**Comment by pshipton** [comment]
Disabled the machine for now.

**Comment by jdekonin** [comment]
Last passed job of the failing jobs above for osx1011-x86-1 was on Feb 25th.  There has been no ssh logons to this system since then, nor any planned (or unplanned) maintenance.

I performed a `brew upgrade wget` and manually running wget on asm-7.3.1.jar works as expected.

Respin of a failing job shows its gets passed the previous failing spot.  I'll leave the machine active.
https://ci.eclipse.org/openj9/view/all/job/Grinder/647/console
