### ISSUE TITLE
testJITServer test failures

### ISSUE THREAD

**Issue by ymanton** [eclipse/openj9#8806]
This issue tracks the large number of failures in the `testJITServer` test target, which was introduced recently (#8041) but is currently disabled (#8805).

The list of failures includes:

- #8653
- #8674
- #8708
- #8726
- #8769
- #8770
- #8788

**Comment by harryyu1994** [comment]
This change (https://github.com/eclipse/openj9/pull/8811) will likely fix all the testJITServer failures. I will verify once Adopt gets it in its builds.

**Comment by harryyu1994** [comment]
@ymanton I think we can re-enable the JITServer tests now as the failures should be fixed by #8811.

**Comment by ymanton** [comment]
I'll submit a PR shortly.

**Comment by ymanton** [comment]
Tests were re-enabled in https://github.com/eclipse/openj9/pull/8775 ages ago so this is resolved.
