### ISSUE TITLE
JDK8: OpenJ9 & OMR repos do not "tag" a release level

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#881]
For "releases" eg.JDK8, a "tagged" level is required for consumers eg.Adopt to be able to pull the appropriate level to build for example an OpenJ9-JDK8 build...?

**Comment by DanHeidinga** [comment]
Thanks for opening this Andrew.  

Given the 0.8 release is in progress, we need to figure out the branching / tagging story for OpenJ9 and the Extension repos and document the way this will work, at least how we'll try and tackle it for the first release.

**Comment by DanHeidinga** [comment]
Covered in the release process: https://github.com/eclipse/openj9/blob/master/doc/processes/release_process.md
