### ISSUE TITLE
AIX builds are missing debug symbols

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8821]
Looking at the last nightly builds for AIX, there isn't any debug image artifact.

https://ci.eclipse.org/openj9/job/Build_JDK8_ppc64_aix_Nightly/329/
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64_aix_Nightly/322/
https://ci.eclipse.org/openj9/job/Build_JDK14_ppc64_aix_Nightly/13/

Even when that is fixed, the debug image contains OpenJ9 debug symbols, but nothing from OpenJDK.

**Comment by keithc-ca** [comment]
The default on AIX (at least for jdk11) is for `configure` to assume
```
--with-native-debug-symbols=internal
```
which yields no separate (external) debug information files to be collected into a debug-image.

**Comment by pshipton** [comment]
We'll want the above jdk8 - 14 PRs in the release branches for 0.20.0 as well.

**Comment by keithc-ca** [comment]
> We'll want the above jdk8 - 14 PRs in the release branches for 0.20.0 as well.

Created.

**Comment by pshipton** [comment]
@keithc-ca I believe this is resolved now and can be closed.

**Comment by keithc-ca** [comment]
If you're happy, I'm happy. ;-)
