### ISSUE TITLE
Runtime compressed references

### ISSUE THREAD

**Issue by gacholio** [eclipse/openj9#8847]
Runtime compressed references is a new feature which will allow a single VM to operate in compressed and non-compressed mode, as opposed to the current solution which packages two separate VMs and switches them via the redirector.

The upshot of this is that compile-time checks for compressed references are no longer allowed. This document will provide a guide for migrating to the runtime strategy.

In the old world, code like this was permissible:
```
#if defined(OMR_GC_COMPRESSED_POINTERS)
   code for compressed
#else
   code for full pointers
#endif

#if !defined(OMR_GC_COMPRESSED_POINTERS)
   code for full
#endif
```
This pattern is no longer allowed in the code, with one exception - there are structures which define fields that only appear in compressed or uncompressed builds.

In `!defined` pattern is replaced by a new flag (in order to allow for both compressed and uncompressed fields to be defined in the same build):
```
#if defined(OMR_GC_FULL_POINTERS)
   code for full
#endif
```
The "mixed mode" builds will define both `OMR_GC_COMPRESSED_POINTERS` and `OMR_GC_FULL_POINTERS`. Any code accessing optional fields must also be gated on the same option.

Performing the runtime test for compressed refs differs by component. Note that in the current single mode builds, the runtime test has no cost, as it is defined to be a compile-time true or false. The caveat is that both sides of the runtime test must be compileable whether the compressed or full flags are set.

*VM*

Replace ifdeffed code with the appropriate query of:
```
J9VMTHREAD_COMPRESS_OBJECT_REFERENCES(vmThread)
J9JAVAVM_COMPRESS_OBJECT_REFERENCES(javaVM)
```

*GC*

Replace ifdeffed code with the appropriate query of:
```
env->compressObjectReferences()
extensions->compressObjectReferences()
```

Replace pointer arithmetic and dereferences of `fj9object_t` and `fomrobject_t` with uses of the static and instance APIs on `GC_SlotObject`.

*JIT*

Replace ifdeffed code with the appropriate query of:
```
TR::Compiler->om.compressObjectReferences()
```

*DDR*

`J9BuildFlags.gc_compressedPointers` -> `J9ObjectHelper.compressObjectReferences`
`J9Object.SIZEOF` -> `J9ObjectHelper.headerSize()`
`object.clazz()` -> `J9ObjectHelper.rawClazz(object)`
`array.size()` -> `J9IndexableObjectHelper.rawSize(array)`
`J9IndexableObjectDiscontiguous.SIZEOF` -> `J9IndexableObjectHelper.discontiguousHeaderSize()`
`J9IndexableObjectContiguous.SIZEOF` -> `J9IndexableObjectHelper.contiguousHeaderSize()`

Doc issue https://github.com/eclipse/openj9-docs/issues/739

**Comment by pshipton** [comment]
@gacholio can we close this now?
