### ISSUE TITLE
Create some Ubuntu 18 machines for x, p, z

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8849]
We'd like to have some Ubuntu 18.04 LTS machines available for testing the GC double mapping feature. What I'm thinking initially is to convert 2 UB16 machines for each platform to UB18. These machines cannot be used for build, only for test. Build machines for x, z are CentOS/RHEL anyway, and p will be there soon.

**Comment by pshipton** [comment]
@DanHeidinga @amicic @bragaigor @jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
I'll add it to my todo list.

**Comment by jdekonin** [comment]
390 - upgrade and rename on jenkins; ub16-390-3 and ub16-390-4
x86 - upgrade and rename on jenkins/image; ub16x64j99 and ub16x64j910

PPCLE - Compiles are still on UB16 so until these move to CENT7 (#7191 which is currently blocked) upgrading any ub16 systems will take away from the number available to do build.  Are you good with removing 2 of the 9 systems for build @pshipton or should we wait for PPCLE for now?  ub16p8j95 and ub16p8j96 to be upgraded and renamed on jenkins and within the image.

**Comment by jdekonin** [comment]
ub16x64j99 and ub16x64j910 soon to be ub18-x86-1 and ub18-x86-2 are disabled in jenkins.
ub16-390-3 and ub16-390-4 soon to be ub18-390-1 and ub18-390-2 are disabled in jenkins.
ub16p8j95 and ub16p8j96 soon to be ub18-ppcle-1 and ub18-ppcle-2 are disabled in jenkins.

**Comment by rajdeepsingh1** [comment]
**X86**
`ub16x64j99` and `ub16x64j910 ` have been updated from UB16 to UB18
- hostnames are now `ub18-x86-1` and `ub18-x86-2`
- updated hostnames on aliases, hosts, and kvm virsh definitions

**PPCLE**
`ub16p8j95` and `ub16p8j96` have been updated from UB16 to UB18
- hostnames are now `ub18-ppcle-1` and `ub18-ppcle-2`
- updated hostnames on aliases, hosts, and kvm virsh definitions

**390**
- updated `ub16-390-3` and `ub16-390-4` from UB16 to UB18
- hostnames are now 1ub18-390-1` and `ub18-390-2`


--

Once the PR is merged machines should be back online in Jenkins.

**Comment by jdekonin** [comment]
4 of the 6 are online. ub18-x86-1 and ub18-x86-2 fail to connect to jenkins because the slave.jar downloading is failing to wget.

`wget -qO slave.jar https://ci.eclipse.org/openj9/jnlpJars/slave.jar ; exec java -jar slave.jar`

```
ERROR: cannot verify ci.eclipse.org's certificate, issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to ci.eclipse.org insecurely, use `--no-check-certificate'.
```

The same method isn't a problem for ub18-ppcle-1, so there must be something different between machines.

**Comment by pshipton** [comment]
Getting build failures, at least on z and p. Disabling the machines.
```
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/AdoptOpenJDK/openjdk-tests.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: /usr/local/libexec/git-core/git-remote-https: /usr/lib/powerpc64le-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/local/libexec/git-core/git-remote-https)
```

**Comment by jdekonin** [comment]
I found indicators that libcurl4 and git don't work together.

I have added libcurl3; manually its working for me now.  Any of the p or z machines can be tested via grinder.

`apt-get install libcurl3 --auto-remove -y`

**Comment by pshipton** [comment]
Now we get
```
14:15:49  ./openjdk-tests/get.sh: line 267: curl: command not found
14:15:49  curl error code: 127. Sleep 300 secs, then retry 1...
```

**Comment by jdekonin** [comment]
So this was an upgrade and not a fresh install; git was installed via playbook at v2.15.  Ubuntu18 default is v2.17.  I removed the previously compiled v2.15 and put curl and libcurl4 back on.  Seems to resolve the issue.

https://ci.eclipse.org/openj9/view/Test/job/Grinder/847/console

**Comment by pshipton** [comment]
Seems to be working now.
