### ISSUE TITLE
pahole on OpenJ9 libraries

### ISSUE THREAD

**Issue by ashu-mehra** [eclipse/openj9#885]
Poke-a-hole ([pahole](https://lwn.net/Articles/335942/)) is an object-file analysis tool to find the size of the data structures, and the holes caused due to aligning the data elements to the word-size of the CPU by the compiler.

I ran pahole on a set of libraries in OpenJ9.
```
libffi29.so.dbg
libj9dmp29.so.dbg
libj9gc29.so.dbg
libj9gcchk29.so.dbg
libj9hookable29.so.dbg
libj9jnichk29.so.dbg
libj9jvmti29.so.dbg
libj9prt29.so.dbg
libj9shr29.so.dbg
libj9thr29.so.dbg
libj9trc29.so.dbg
libj9vm29.so.dbg
libj9vmchk29.so.dbg
libj9vrb29.so.dbg
libj9zlib29.so.dbg
libjclse7b_29.so.dbg
libjsig.so.dbg
libjvm.so.dbg
libomrsig.so.dbg
```
I used `--packable` option to get the summary of possible data structure that can be packed to save the size of the data structure.
Result of running `pahole` is summarized below. Second field indicates current size of the structure. Third field is the packed size (Note that there are options in `pahole` to generate the layout of the packed structure). Last field is the difference between 3rd and 2nd field.

| Structure name | Current size | Packed Size | Bytes saved |
| --- | --- | --- | --- |
|  MM_GCExtensionsBase  |  27312  |  26864  |  448  | 
|  TR_UseDefInfo  |  4608  |  4184  |  424  | 
|  TR_RegisterCandidates  |  4568  |  4200  |  368  | 
|  TR_Dominators  |  4480  |  4264  |  216  | 
|  TR_J9SharedCache  |  104  |  0  |  104  | 
|  MM_Scavenger  |  760  |  656  |  104  | 
|  TR_DebugExt  |  4584  |  4488  |  96  | 
|  MM_HeapRegionDescriptorVLHGC  |  952  |  872  |  80  | 
|  MM_CopyForwardScheme  |  280  |  216  |  64  | 
|  TR_BlockFrequencyInfo  |  48  |  0  |  48  | 
|  MM_ConcurrentGC  |  1240  |  1192  |  48  | 
|  GC_ObjectHeapBufferedIterator  |  2224  |  2184  |  40  | 
|  MM_EnvironmentBase  |  10136  |  10104  |  32  | 
|  GC_ParallelObjectHeapIterator  |  2360  |  2328  |  32  | 
|  TR_Rematerialization  |  144  |  120  |  24  | 
|  TR_RelocationRuntime  |  320  |  296  |  24  | 
|  TR_IProfiler  |  224  |  200  |  24  | 
|  TR_InterferenceGraph  |  80  |  56  |  24  | 
|  SH_OSCache  |  168  |  144  |  24  | 
|  SH_CompositeCacheImpl  |  408  |  384  |  24  | 
|  MM_GCExtensions  |  28408  |  28384  |  24  | 
|  MM_AllocateDescription  |  120  |  96  |  24  | 
|  TR_VirtualGuard  |  120  |  104  |  16  | 
|  TR_ShrinkWrap  |  152  |  136  |  16  | 
|  TR_PartialRedundancy  |  192  |  176  |  16  | 
|  TR_OrderBlocks  |  96  |  80  |  16  | 
|  TR_LoopUnroller  |  272  |  256  |  16  | 
|  TR_J9VMBase  |  112  |  96  |  16  | 
|  TR_J9ByteCodeIlGenerator  |  432  |  416  |  16  | 
|  TR_EscapeAnalysis  |  296  |  280  |  16  | 
|  TR_CallTarget  |  176  |  160  |  16  | 
|  TR_CallSite  |  368  |  352  |  16  | 
|  SH_Manager  |  136  |  120  |  16  | 
|  ROMClassCreationContext  |  1872  |  1856  |  16  | 
|  PlatformWalkData  |  432  |  416  |  16  | 
|  OMRPortPlatformGlobals  |  632  |  616  |  16  | 
|  NeedsPeekingHeuristic  |  72  |  56  |  16  | 
|  MM_Scheduler  |  360  |  344  |  16  | 
|  MM_RealtimeGC  |  344  |  328  |  16  | 
|  MM_CollectionStatisticsStandard  |  176  |  160  |  16  | 
|  J9JavaLangManagementData  |  2344  |  2328  |  16  | 
|  internal_state  |  5928  |  5912  |  16  | 
|  GC_ObjectHeapIteratorAddressOrderedList  |  64  |  48  |  16  | 
|  ComparingCursor  |  256  |  240  |  16  | 
|  z_stream_s  |  112  |  104  |  8  | 
|  X  |  40  |  32  |  8  | 
|  vmX  |  24  |  16  |  8  | 
|  VirtualGuardPair  |  40  |  32  |  8  | 
|  VGLoopInfo  |  32  |  24  |  8  | 
|  UtTracePointIterator  |  152  |  144  |  8  | 
|  UtThreadData  |  88  |  80  |  8  | 
|  UtSubscription  |  96  |  88  |  8  | 
|  UtDeferredConfigInfo  |  56  |  48  |  8  | 
|  TR_X86PaddingTable  |  24  |  16  |  8  | 
|  TR_VirtualGuardTailSplitter  |  56  |  48  |  8  | 
|  TR_Structure  |  80  |  72  |  8  | 
|  TR_StoreTreeInfo  |  64  |  56  |  8  | 
|  TR_SPMDKernelParallelizer  |  512  |  504  |  8  | 
|  TR_ResolvedJ9Method  |  184  |  176  |  8  | 
|  TR_RelocationRecordProfiledInlinedMethodPrivateData  |  40  |  32  |  8  | 
|  TR_RelocationRecordPointerPrivateData  |  32  |  24  |  8  | 
|  TR_RegionStructure  |  208  |  200  |  8  | 
|  TR_RedundantAsyncCheckRemoval  |  64  |  56  |  8  | 
|  TR_RecompilationProfiler  |  48  |  40  |  8  | 
|  TR_PrexArgument  |  32  |  24  |  8  | 
|  TR_PersistentProfileInfo  |  80  |  72  |  8  | 
|  TR_PersistentJittedBodyInfo  |  80  |  72  |  8  | 
|  TR_PersistentFieldInfo  |  48  |  40  |  8  | 
|  TR_OutlinedInstructions  |  112  |  104  |  8  | 
|  TR_OSRMethodData  |  232  |  224  |  8  | 
|  TR_OptimizationPlan  |  64  |  56  |  8  | 
|  TR_MovableStore  |  88  |  80  |  8  | 
|  TR_MethodEvent  |  56  |  48  |  8  | 
|  TR_LoopVersioner  |  648  |  640  |  8  | 
|  TR_LoopStrider  |  560  |  552  |  8  | 
|  TR_LocalAnalysisInfo  |  88  |  80  |  8  | 
|  TR_LiveRangeSplitter  |  80  |  72  |  8  | 
|  TR_InlinerBase  |  176  |  168  |  8  | 
|  TR_HWProfiler  |  232  |  224  |  8  | 
|  TR_HashTab  |  72  |  64  |  8  | 
|  TR_GlobalRegisterAllocator  |  328  |  320  |  8  | 
|  TR_FlowSensitiveEscapeAnalysis  |  384  |  376  |  8  | 
|  TR_FirstUseOfLoad  |  32  |  24  |  8  | 
|  TR_FilterBST  |  80  |  72  |  8  | 
|  TR_FieldPrivatizer  |  696  |  688  |  8  | 
|  TR_ExpressionPropagation  |  64  |  56  |  8  | 
|  TR_EstimateCodeSize  |  72  |  64  |  8  | 
|  TR_DominatorVerifier  |  56  |  48  |  8  | 
|  TR_Debug  |  200  |  192  |  8  | 
|  TR_DataFlowAnalysis  |  80  |  72  |  8  | 
|  TR_CopyPropagation  |  176  |  168  |  8  | 
|  TR_CISCTransformer  |  816  |  808  |  8  | 
|  TR_CISCNodeRegion  |  72  |  64  |  8  | 
|  TR_CISCNode  |  176  |  168  |  8  | 
|  TR_CISCHash  |  32  |  24  |  8  | 
|  TR_CISCGraph  |  368  |  360  |  8  | 
|  TR_BasicDFSetAnalysis<TR_SingleBitContainer*>  |  200  |  192  |  8  | 
|  TR_BasicDFSetAnalysis<TR_BitVector*>  |  200  |  192  |  8  | 
|  TR_arraycopySequentialStores  |  304  |  296  |  8  | 
|  TR_AnnotationBase  |  32  |  24  |  8  | 
|  subscription  |  72  |  64  |  8  | 
|  SRPKeyProducer  |  48  |  40  |  8  | 
|  SH_OSCachesysv  |  304  |  296  |  8  | 
|  SH_CacheMap  |  296  |  288  |  8  | 
|  RecognizedBigDecimalMethods  |  32  |  24  |  8  | 
|  queue  |  72  |  64  |  8  | 
|  PreservedRegisterInfo  |  40  |  32  |  8  | 
|  OMR_VMThread  |  184  |  176  |  8  | 
|  OMR_TraceThread  |  64  |  56  |  8  | 
|  omrthread_attr  |  48  |  40  |  8  | 
|  OMRMemCategory  |  48  |  40  |  8  | 
|  ObjectFieldInfo  |  96  |  88  |  8  | 
|  NamedCounterInfo  |  48  |  40  |  8  | 
|  MM_VerboseHandlerOutputRealtime  |  712  |  704  |  8  | 
|  MM_TLHAllocationSupport  |  80  |  72  |  8  | 
|  MM_SegregatedAllocationInterface  |  3256  |  3248  |  8  | 
|  MM_SchedulingDelegate  |  304  |  296  |  8  | 
|  MM_PhysicalSubArenaVirtualMemory  |  120  |  112  |  8  | 
|  MM_PartialMarkingScheme  |  104  |  96  |  8  | 
|  MM_ParallelGlobalGC  |  472  |  464  |  8  | 
|  MM_MemorySubSpace  |  552  |  544  |  8  | 
|  MM_MarkingDelegate  |  48  |  40  |  8  | 
|  MM_LargeObjectAllocateStats  |  1032  |  1024  |  8  | 
|  MM_HeapResizeStats  |  160  |  152  |  8  | 
|  MM_HeapRegionDescriptor  |  144  |  136  |  8  | 
|  MM_HeapRegionDataForCompactVLHGC  |  104  |  96  |  8  | 
|  MM_GlobalMarkingScheme  |  104  |  96  |  8  | 
|  MM_ExcessiveGCCheckFreeSpaceEvent  |  88  |  80  |  8  | 
|  MM_EnvironmentRealtime  |  10224  |  10216  |  8  | 
|  MM_CycleState  |  112  |  104  |  8  | 
|  MM_ConcurrentGCStats  |  224  |  216  |  8  | 
|  MM_ConcurrentCardTable  |  304  |  296  |  8  | 
|  MethodSpecTable  |  72  |  64  |  8  | 
|  MethodContextInfo  |  184  |  176  |  8  | 
|  jvmtiStackInfoExtended  |  32  |  24  |  8  | 
|  jvmtiStackInfo  |  32  |  24  |  8  | 
|  jvmtiSharedCacheInfo  |  72  |  64  |  8  | 
|  jvmtiLocalVariableEntry  |  48  |  40  |  8  | 
|  jvmtiHeapReferenceInfoStackLocal  |  48  |  40  |  8  | 
|  jvmtiExtensionFunctionInfo  |  56  |  48  |  8  | 
|  jvmtiExtensionEventInfo  |  40  |  32  |  8  | 
|  JavaCoreDumpWriter  |  136  |  128  |  8  | 
|  J9VerboseSettings  |  32  |  24  |  8  | 
|  J9ThreadLibrary  |  1576  |  1568  |  8  | 
|  j9shmem_handle  |  80  |  72  |  8  | 
|  J9SharedClassTransaction  |  200  |  192  |  8  | 
|  J9MemoryPoolData  |  160  |  152  |  8  | 
|  J9JVMTIObjectTagMatch  |  56  |  48  |  8  | 
|  J9JVMTIHeapData  |  216  |  208  |  8  | 
|  J9JVMTIExtensionFunctionInfo  |  56  |  48  |  8  | 
|  J9JVMTIExtensionEventInfo  |  40  |  32  |  8  | 
|  J9CurrentSignal  |  32  |  24  |  8  | 
|  J9CfrAttributeRuntimeVisibleTypeAnnotations  |  48  |  40  |  8  | 
|  J9CfrAttributeRuntimeVisibleParameterAnnotations  |  48  |  40  |  8  | 
|  J9CfrAttributeRuntimeVisibleAnnotations  |  48  |  40  |  8  | 
|  J9CfrAttributeMethodParameters  |  40  |  32  |  8  | 
|  J9CfrAttributeCode  |  72  |  64  |  8  | 
|  J9CfrAnnotationElementArray  |  24  |  16  |  8  | 
|  J9CfrAnnotation  |  24  |  16  |  8  | 
|  _IO_FILE  |  216  |  208  |  8  | 
|  gz_header_s  |  80  |  72  |  8  | 
|  GC_ObjectHeapIteratorSegregated  |  64  |  56  |  8  | 
|  flock  |  32  |  24  |  8  | 
|  CpuSelfThreadUtilization  |  104  |  96  |  8  | 
|  CompileParameters  |  88  |  80  |  8  | 
|  ClassFileWriter  |  96  |  88  |  8  | 
|  ClassFileOracle  |  176  |  168  |  8  | 
|  Candidate  |  256  |  248  |  8  | 
|  TR_J9InlinerPolicy  |  32  |  25  |  7  | 
|  MM_VerboseTraceOutput  |  40  |  33  |  7  | 
|  MM_StaccatoAccessBarrier  |  80  |  73  |  7  | 
|  MM_MarkMap  |  128  |  121  |  7  | 
|  TR_PatchNOPedGuardSiteOnClassPreInitialize  |  56  |  52  |  4  | 
|  TR_OptAnnotation  |  40  |  36  |  4  | 
|  TR_AbstractProfilerInfo  |  24  |  20  |  4  | 
|  MM_WorkPacketsVLHGC  |  504  |  500  |  4  | 
|  MM_VLHGCIncrementStats  |  1432  |  1428  |  4  | 
|  MM_VerboseWriterStreamOutput  |  48  |  44  |  4  | 
|  MM_VerboseStandardStreamOutput  |  40  |  36  |  4  | 
|  MM_StaccatoGC  |  344  |  340  |  4  | 
|  MM_VerboseWriterTrace  |  40  |  38  |  2  |
|  |  |  |  |
| Total | 144216 | 140514 | 3702 |

I understand many of these structured would be transient, but I think some of them would persist during JVM lifetime and are probably worth investigating further.
Also note that JIT library is missing in the above list, as my version of `pahole` generated lot of errors when processing the JIT library.

**Comment by pdbain-ibm** [comment]
ObjectFieldInfo is transient, as is J9VerboseSettings.

**Comment by DanHeidinga** [comment]
This is an interesting analysis - thanks @ashu-mehra!  There's actually very little waste due to alignment which is a testament to the effort of the team to be aware of structure packing.

In addition to looking at structures are transient, it would be worth focusing on structures that have high #'s of allocations.  16 bytes waste on a structure that's allocated once per jvm matters less than one which is allocated 100's (or more) times

**Comment by DanHeidinga** [comment]
Closing this as no update in several months.
