### ISSUE TITLE
jdk14 Thread.interrupt() before Thread start, after Thread stop

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8916]
Release notes for Java 14 contain the following.

`The specification for java.lang.Thread::interrupt allows for an implementation to only track the interrupt state for live threads, and previously this is what occurred. As of this release, the interrupt state of a Thread is always available, and if you interrupt a thread t before it is started, or after it has terminated, the query t.isInterrupted() will return true.`

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by DanHeidinga** [comment]
@theresa-m Can you take a look at this?

**Comment by theresa-m** [comment]
Yes I can take a look.

**Comment by theresa-m** [comment]
This is ready for another review.
