### ISSUE TITLE
JNI library crashes with OpenJ9 

### ISSUE THREAD

**Issue by marschall** [eclipse/openj9#892]
I'm not sure if this is the right forum.

I have JNI code compiled against OpenJDK 9. If I run the code with OpenJDK 9 it works fine. If I run it against OpenJ9 it crashes. If I recompile it against OpenJ9 it works. My understanding is recompilation should not be necessary and a compiled library should be portable across JVMs without recompilation.

This is the crash log

```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=00007F5A1CD43310 Handler2=00007F5A17DBFCE0 InaccessibleAddress=00000000FFFCA8C0
RDI=0000000001F47000 RSI=000000000000001F RAX=00007F5A1DC6C610 RBX=00007F5A188682A5
RCX=00000000FFFCA8C0 RDX=0000000001F1D5B8 R8=0000000000000008 R9=0000000000000000
R10=0000000000000000 R11=0000000000000000 R12=00000000020F1EE8 R13=00000007FFE506F8
R14=0000000001BDFA00 R15=00000007FFE504F8
RIP=00007F5A1CCD5EFB GS=0000 FS=0000 RSP=00007F5A1DC6C280
EFlags=0000000000010206 CS=0033 RBP=00007F5A18868296 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFFCA8C0
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 00007f5900000000 (f: 0.000000, d: 6.917918e-310)
xmm2 000000740000006e (f: 110.000000, d: 2.461515e-312)
xmm3 43e0000000000000 (f: 0.000000, d: 9.223372e+18)
xmm4 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
xmm5 7fffffffffffffff (f: 4294967296.000000, d: nan)
xmm6 4029545f10ff058a (f: 285148544.000000, d: 1.266479e+01)
xmm7 4029545f10ff058a (f: 285148544.000000, d: 1.266479e+01)
xmm8 4029545e615a8c5a (f: 1633324160.000000, d: 1.266478e+01)
xmm9 3fea831b57679028 (f: 1466404864.000000, d: 8.285042e-01)
xmm10 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
xmm11 3cc6000000000000 (f: 0.000000, d: 6.106227e-16)
xmm12 bc65d40000000000 (f: 0.000000, d: -9.466440e-18)
xmm13 4028f40b5ed97f00 (f: 1591312128.000000, d: 1.247665e+01)
xmm14 bba5622237779c0a (f: 930585600.000000, d: -2.264049e-21)
xmm15 4028f40b5ed97f00 (f: 1591312128.000000, d: 1.247665e+01)
Module=/home/marschall/bin/java/openj9-9-181/lib/compressedrefs/libj9vm29.so
Module_base_address=00007F5A1CCAD000
Target=2_90_20171027_36 (Linux 4.13.0-21-generic)
CPU=amd64 (8 logical CPUs) (0xfb6d23000 RAM)
----------- Stack Backtrace -----------
(0x00007F5A1CCD5EFB [libj9vm29.so+0x28efb])
(0x00007F5A1CCBFA4B [libj9vm29.so+0x12a4b])
(0x00007F5A1CD7BF62 [libj9vm29.so+0xcef62])
```
And the produced files:

* [javacore.20180107.153400.8296.0002.txt](https://github.com/eclipse/openj9/files/1609844/javacore.20180107.153400.8296.0002.txt)
* [jitdump.20180107.153400.8296.0004.dmp.txt](https://github.com/eclipse/openj9/files/1609847/jitdump.20180107.153400.8296.0004.dmp.txt)
* [Snap.20180107.153400.8296.0003.trc.txt](https://github.com/eclipse/openj9/files/1609850/Snap.20180107.153400.8296.0003.trc.txt)

I had to rename the .trc and .dmp files to .txt so GitHub would allow me to upload them.

I can provide a full core dump but that's 720 MB, I don't know where I should upload that.

The system is 64bit Ubuntu 17.10 with GLIBC 2.26 and GCC  6.4.0.

```
$/lib/x86_64-linux-gnu/libc.so.6 
GNU C Library (Ubuntu GLIBC 2.26-0ubuntu2) stable release version 2.26, by Roland McGrath et al.
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 6.4.0 20171010.
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
```

Kernel version is 4.13.0

```
$uname -r
4.13.0-21-generic
```

OpenJ9 is from https://adoptopenjdk.net/releases.html

```
$java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20171027_36 (JIT enabled, AOT enabled)
OpenJ9   - 292f272
OMR      - 9ea665d
OpenJDK  - 640ef65 based on )
```

The JNI code can be found here https://github.com/marschall/getrandom-provider/blob/master/getrandom-provider/src/main/c/com_github_marschall_getrandom_Getrandom.c

**Comment by DanHeidinga** [comment]
Can you run with `-Xcheck:jni`?  This option validates the parameters passed to the JNI function and determines if all the JNI rules (exception checks, etc) have been followed.  If there is an issue in the JNI code, this makes it easier to find the root cause.

**Comment by DanHeidinga** [comment]
Based on the javacore, the java stack looks like its crashing in 
```
4XESTACKTRACE                at com/google/common/util/concurrent/AbstractFuture$UnsafeAtomicHelper.casListeners(AbstractFuture.java:1002)
4XESTACKTRACE                at com/google/common/util/concurrent/AbstractFuture.clearListeners(AbstractFuture.java:883)
4XESTACKTRACE                at com/google/common/util/concurrent/AbstractFuture.complete(AbstractFuture.java:789)
1INTERNAL                    Unable to walk in-flight data on call stack

```
This isn't always 100% accurate so we'd need the core to be able to investigate further.

Can you zip the core file and upload it to somewhere like Box, Dropbox, etc?

**Comment by marschall** [comment]
I can do that but it may take a few days.

**Comment by marschall** [comment]
I can no longer reproduce the issue :-/

When I run `-Xcheck:jni` on OpenJDK I get

```
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
```

I believe these are issues in OpenJDK code as is ever call `CallStaticObjectMethod`.

When I run `-Xcheck:jni` on OpenJ9 I only get

```
JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
```

In the interest of completeness here is the core dump

https://www.dropbox.com/s/yx445ghpj55jrii/core.20180107.153400.8296.0001.dmp?dl=0

I'm really at a loss here, maybe a background update fixed some component. I guess this can be closed.

**Comment by DanHeidinga** [comment]
> I guess this issue can be closed.

To (eventually) close the loop - I took a quick look at the core and nothing jumped out at me.  The core predates DDR being enabled for OpenJ9 so there wasn't a lot to see.

Please reopen if this occurs again and we'll take another crack at it.
