### ISSUE TITLE
Replace GenerateJLIClassesPlugin.java with blank file.

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#893]
In the Extensions for OpenJDK for Eclipse OpenJ9 project, we modify a number of OpenJDK classes to make the OpenJDK project compatible with OpenJ9.

One of those classes is GenerateJLIClassesPlugin, which we disable. We disable it because the code required to make it work is Hotspot-specific, and leaving it active but nonfunctional breaks JLink.

To remove this change from extensions, but not cripple jlink, we need to find a way to disable this class from OpenJ9. The simplest way to do this is to replace that class with a blank file (plus a copyright statement) in j9jcl.

I've included the pull request for this: https://github.com/eclipse/openj9/pull/895

Note: Do not accept this change until after Shelley Lambert, or someone else, has found a way to exclude the GenerateJLIClassesPluginTest test from our (AdoptOpenJDK) testing, as removing this class will break that test.

@smlambert - Please review and respond.

**Comment by adamfarley** [comment]
P.S. I ran the build locally before creating the pull request, and it appears the travis CI build passed as well.

**Comment by smlambert** [comment]
Yes, there is a way to exclude an individual test that is part of the openjdk regression suite, through the ProblemList.txt file.  For now, we are sharing that file for both implementations (hotspot / openj9), however nothing stops us from maintaining two separate files.  

Is this expected to be a permanent state of exclusion, or is this blank file story only a way to temporarily address the issue?

**Comment by adamfarley** [comment]
I have no reason to believe OpenJ9 will support the code required to run this plugin, so let's say "long-term or permanent".

**Comment by DanHeidinga** [comment]
To expand on Adam's comment - the JLI plugin generates MethodHandle-related classes for use by OpenJDK's MethodHandle implementation.  As OpenJ9 has its own implementation of MH, we don't need / can't use this plugin.

**Comment by smlambert** [comment]
Ok, I have created https://github.com/AdoptOpenJDK/openjdk-tests/issues/206 to address this, but you do not need to hold up this PR, as we currently are not running the group of tests where that test case resides.  When we turn them on, we will exclude that particular one.
