### ISSUE TITLE
Reduce number of VM_getROMMethodFromRAMMethod messages

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#8958]
The `VM_getROMMethodFromRAMMethod` message is used by the JITServer in the following frontend method:
```
J9ROMMethod *
TR_J9ServerVM::getROMMethodFromRAMMethod(J9Method *ramMethod)
   {
   JITServer::ServerStream *stream = _compInfoPT->getMethodBeingCompiled()->_stream;
   stream->write(JITServer::MessageType::VM_getROMMethodFromRAMMethod, ramMethod);
   return std::get<0>(stream->read<J9ROMMethod *>());
   }
```
During an AcmeAir benchmark run with AOT enabled I see 450-650 such messages.
We should use ` PersistentUnorderedMap<J9Method*, J9MethodInfo> _J9MethodMap;` cache to extract the romMethod and only if there is a miss in the cache, issue a message.

**Comment by dmitry-ten** [comment]
If no one is working on this yet, I'll do it

**Comment by mpirvu** [comment]
@dmitry-ten Please do. Much appreciated.
