### ISSUE TITLE
Windows Unable to delete openjdkbinary

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8965]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_OMR/483
win2012r2-x86-6
```
jenkins.util.io.CompositeIOException: Unable to delete 'C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.functional_x86-64_windows_OMR\openjdkbinary'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
```

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
Cleanup job must've taken care of it as there was no directory present.  I rebooted the system for good measure.
