### ISSUE TITLE
AArch64: Failure in system test SC_Softmx_JitAot_Linux_0

### ISSUE THREAD

**Issue by knn-k** [eclipse/openj9#8966]
Failure link
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_aarch64_linux_Personal/4/
SC_Softmx_JitAot_Linux_0

The test runs the VM with `-Xscmaxaot10k -Xscmaxjitdata10k`, and expects the AOT data space to be full.  But the file `stderr_combined.txt` says the JIT data store is full instead with AArch64, as shown below.
```
[-Xshareclasses persistent cache enabled]
[-Xshareclasses verbose output enabled]
JVMSHRC236I Created shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMSHRC168I Total shared class bytes read=6513136. Total bytes stored=6229620
JVMSHRC818I Total unstored bytes due to the setting of shared cache soft max is 0. Unstored AOT bytes due to the setting of -Xscmaxaot is 0. Unstored JIT bytes due to the setting of -Xscmaxjitdata is 1380352.
[-Xshareclasses persistent cache enabled]
[-Xshareclasses verbose output enabled]
JVMSHRC237I Opened shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC246I Attached shared classes persistent cache SCC_SysTest_Workload_Cache
JVMSHRC765I Memory page protection on runtime data, string read-write data and partially filled pages is successfully enabled
JVMSHRC774I The space for JIT data in shared cache "SCC_SysTest_Workload_Cache" is full.
JVMSHRC168I Total shared class bytes read=10141164. Total bytes stored=4182444
JVMSHRC818I Total unstored bytes due to the setting of shared cache soft max is 0. Unstored AOT bytes due to the setting of -Xscmaxaot is 0. Unstored JIT bytes due to the setting of -Xscmaxjitdata is 1355776.
```

AOT is enabled in the AArch64 runtime.

**Comment by pshipton** [comment]
@Mesbah-Alam can you help fix this please.

**Comment by knn-k** [comment]
Note that the AArch64 JIT does not have the support for recompilation yet.

**Comment by 0xdaryl** [comment]
@Mesbah-Alam : do you have any suggestions for how we can resolve this problem?  If this test relies on JIT recompilation in order to run successfully then it shouldn't be run on AArch64 because recompilation support is not available yet.

**Comment by knn-k** [comment]
Possibly related: #9003
Java methods don't get AOTed on the AArch64 test server as expected in `testDDRExt_SharedClasses_openj9_0`.  `printStats` says `# AOT Methods = 0`.
Running the same test on a local AArch64 machine finishes successfully, and the shared class cache contains 229 AOT methods.

Timing-dependent?

**Comment by Mesbah-Alam** [comment]
From the [description](https://github.com/eclipse/openj9-systemtest/blob/241d151cebae8b9bdedd671287db6b29bdde0972/openj9.test.sharedClasses/src/test.sharedClasses/net/openj9/stf/SharedClassesWorkloadTest_Softmx_Increase_JitAot.java#L52 ) of the test: 

1) Start 2 Jvms that run workload processes with options `-XX:SharedCacheHardLimit=20m, 
     -Xshareclasses:addtestjithints,verbose -Xscmaxaot10k -Xscmaxjitdata10k -Xjit:count=0`. 
 
Both Jvms run mini-mix load tests with the expectation to generate aot and jit data, and fill up the aot and jit space in the cache. 
     
 2) Once Jvm1 and Jvm2 finish, check that the AOT and JIT space is full. Also, record the cache stats at this point, which should give us the number of bytes written in AOT and JIT data space. 
<-- Here's where the test fails, as @knn-k points out above too. 

The test expects both AOT and JIT data space to be full after step two. It validates that by combining the standard err file of jvm1 (run in step1) and jvm2 (run in step 2) and looking for the two messages in the combined file: 

```
JVMSHRC774I The space for JIT data in shared cache "SCC_SysTest_Workload_Cache" is full
```

```
JVMSHRC773I The space for AOT data in shared cache "SCC_SysTest_Workload_Cache" is full
```

Why is JIT data space not being filled up by the test on AArch64 platform? Is it expected behaviour? If not, does it indicate a real failure? Or are we using wrong options in jvm1 and jvm2 for AArch64 to generate JIT data? 

@knn-k @0xdaryl

**Comment by knn-k** [comment]
JIT data space is filled up by the test.  It is AOT data space which is not filled up, although AOT is enabled and working on AArch64.
Another test in #9003 also shows a case where the shared class cache contains no AOT method.

There must be a (AArch64-specific?) condition of not storing AOT method in the cache.

**Comment by Mesbah-Alam** [comment]
"JIT data space is filled up by the test. It is AOT data space which is not filled up" - correct. I've fixed my comment above.

**Comment by knn-k** [comment]
This test runs the VM with the options described in @Mesbah-Alam's comment above.  AArch64 VM does not store AOT methods in the cache.

AOT methods are stored when I added `-Xquickstart` to the options.  With the option at the end of the output from the VM looks like:
```
JVMSHRC168I Total shared class bytes read=5552. Total bytes stored=10347808
JVMSHRC818I Total unstored bytes due to the setting of shared cache soft max is 0. Unstored AOT bytes due to the setting of -Xscmaxaot is 6553600. Unstored JIT bytes due to the setting of -Xscmaxjitdata is 262144.
```
`printStats` shows that there are some AOT methods in the cache in this case.

**Comment by knn-k** [comment]
I can make this test pass by setting `IBM_JAVA_OPTIONS=-Xquickstart`, either on cent7-aarch64-1 or in my development environment.

When `-Xquickstart` is not specified, `TR::CompilationInfoPerThreadBase::preCompilationTasks()` never sets `canDoRelocatableCompile` to `true` on AArch64, and that prevents AOT compilation.
https://github.com/eclipse/openj9/blob/a602362e531657487f72f78305221c439612152a/runtime/compiler/control/CompilationThread.cpp#L7138-L7153

**Comment by knn-k** [comment]
I opened https://github.com/AdoptOpenJDK/openjdk-tests/pull/1717 for excluding this test.

**Comment by knn-k** [comment]
This test has been excluded.  Removed the Milestone tag from this issue.

**Comment by knn-k** [comment]
My local testing shows that the AArch64 runtime passes this test now.

**Comment by knn-k** [comment]
This test case has been enabled, and the latest test result is successful.
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.system_aarch64_linux/172/tapResults/

Closing.
