### ISSUE TITLE
Add 10 new AIX machines supplied by IBM Cloud

### ISSUE THREAD

**Issue by jdekonin** [eclipse/openj9#8979]
fyi @pshipton @rajdeepsingh1

Raj and I have a list of the 12 systems supplied via IBM Cloud.  10 are for OpenJ9 and 2 are for OMR.  These systems need to be brought online within the next week or two before we release the current PDP systems.  We won't release these systems until the new ones are confirmed functional and stable.

Systems to be retired : aix71-p8-1 -> aix71-p8-10 (sad since we just rebuilt a number of these too)

**Comment by jdekonin** [comment]
No build or test labels on that jiro PR.  So should be good to test jenkins connectivity and the machines once merged.  A new VPN connection needs to be setup as well.

**Comment by jdekonin** [comment]
@Rajdeep Singh added 10 new/replacement AIX machines to the OpenJ9 node pool yesterday.  Thanks Raj.

I believe targeting a machine with each of the test options should be sufficient as the machines should be identical.  Machines added :  aix71-p8-11 -> aix71-p8-20

Asked via slack for a committer to launch and @pshipton was first on scene.  Thanks Peter!
sanity.functional jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Grinder/736/console
extended.functional jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Grinder/7376console
sanity.system jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Grinder/738/console
extended.system jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Grinder/739/console

Seems there are failures that I need to investigate.
```
Can't open perl script "/home/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/system/daaLoadTest/..//stf/stf.core/scripts/stf.pl": A file or directory in the path name does not exist.
```

**Comment by jdekonin** [comment]
Respin 2 failures
sanity.system jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Grinder/749/
extended.system jdk11 - https://ci.eclipse.org/openj9/view/Test/job/Grinder/751/

There wasn't a default compiler on the path.

**Comment by jdekonin** [comment]
All but aix71-p8-20 have been made live for build and test.  I'll need to put in a PR to the jiro repo to make the configuration persistent across jenkins restarts.  I've remove the build and test labels from aix71-p8-1 -> aix71-p8-10, they are still in jenkins.  I won't remove until there is agreement.

**Comment by rajdeep** [comment]
@jdekonin, I think you intended to mention someone else in this discussion. I have unsubscribed myself from this thread.

**Comment by jdekonin** [comment]
fyi @rajdeepsingh1

This PR enables 11-20 for build and test while disabling 1-10.  There has only been an bootjdk issue with jdk13 on 11 which I fixed quickly.
https://github.com/eclipse-cbi/jiro/pull/97

Once this goes through I don't have to do the manual change on the nodes to keep 11-20 active.

Remaining task is to return 1-10 once the release is complete end of the week.
- [ ] remove from configuration xml
- [ ] send email to return systems to IBM

**Comment by jdekonin** [comment]
Remove returned machines from configuration.
https://github.com/eclipse-cbi/jiro/pull/98

**Comment by jdekonin** [comment]
This work is completed with the PR merge.
