### ISSUE TITLE
javadoc contains unsupported extensions

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#898]
The javadoc created as part of the OpenJ9 build, found in `build/<platform>/docs`, contains extensions which are not supported on OpenJ9.
 - OpenJDK management extensions, com.sun.management

See also ibmruntimes/openj9-openjdk-jdk8#21

**Comment by lumpfish** [comment]
The current openj9 build creates javadoc for the com.sun.management package in docs/jre/api/management/extension.

@pshipton - are you expecting the javadoc for com.ibm.lang.management to replace the com.sun.management javadoc in docs/jre/api/management/extension or that it be added as a package under docs/platform/management as specified in https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/20?

**Comment by pshipton** [comment]
@lumpfish the non-applicable to OpenJ9 com.sun.management javadoc must be removed. The Openj9 com.ibm.lang.management interfaces should be added as this package. Some of the OpenJ9 implementation (specifically GarbageCollectorMXBean, OperatingSystemMXBean, UnixOperatingSystemMXBean) implement the com.sun.management interfaces, and this needs to be reflected in the javadoc.

**Comment by pshipton** [comment]
> Some of the OpenJ9 implementation (specifically GarbageCollectorMXBean, OperatingSystemMXBean, UnixOperatingSystemMXBean) implement the com.sun.management interfaces, and this needs to be reflected in the javadoc.

I expect these OpenJDK interface classes can just remain as part of the javadoc generation.

**Comment by pshipton** [comment]
I believe this is now fixed for all versions.

https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/342
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/212
https://github.com/ibmruntimes/openj9-openjdk-jdk13/pull/32
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/156
