### ISSUE TITLE
Override ObjectModel::areValueTypesEnabled() for JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#9004]
`ObjectModel::areValueTypesEnabled() ` is a new query added in PR #8919 and it needs to be overridden at JITServer.

**Comment by mpirvu** [comment]
`areValueTypesEnabled()` has the following definition:

```
BOOLEAN
areValueTypesEnabled(J9JavaVM *vm)
{
	return J9_ARE_ALL_BITS_SET(vm->extendedRuntimeFlags2, J9_EXTENDED_RUNTIME2_ENABLE_VALHALLA);
}
```
Thus, it checks a bit on javaVM->extendedRuntimeFlags2.
This flag is set during JVM bootstrap in `processVMArgsFromFirstToLast(J9JavaVM * vm)` and it does not change.

The solution here is to add another field `_extendedRuntimeFlags2` in VMInfo and send it with VMInfo. Then, retrieve the desired value from VMinfo required.

**Comment by chrisc66** [comment]
Thanks, a PR is opened for this issue.
