### ISSUE TITLE
JDK15 jdk_lang_0_FAILED AssertionError: Native library loaded. Expected: JNI_OnUnload not invoked

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9018]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_ppc64_aix_Nightly/107`
```
03:44:34  openjdk version "15-internal" 2020-09-15
03:44:34  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDKnextppc64aixNightly)
03:44:34  Eclipse OpenJ9 VM (build ibm_sdk-0852f80a4a, JRE 15 AIX ppc64-64-Bit Compressed References 20200328_174 (JIT enabled, AOT enabled)
03:44:34  OpenJ9   - 0852f80a4a
03:44:34  OMR      - e9bed7888
03:44:34  JCL      - 7aba5c409a9 based on jdk-15+16)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
05:19:11  JVMJNCK001I JNI check utility installed. Use -Xcheck:jni:help for usage
05:19:11  java.lang.AssertionError: Native library loaded.  Expected: JNI_OnUnload not invoked
05:19:11  	at java.base/jdk.internal.loader.NativeLibrariesTest.assertTrue(NativeLibrariesTest.java:132)
05:19:11  	at java.base/jdk.internal.loader.NativeLibrariesTest.runTest(NativeLibrariesTest.java:69)
05:19:11  	at Main.main(Main.java:46)
05:19:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:19:11  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:19:11  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:19:11  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
05:19:11  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
05:19:11  	at java.base/java.lang.Thread.run(Thread.java:835)
05:19:11  
05:19:11  JavaTest Message: Test threw exception: java.lang.AssertionError: Native library loaded.  Expected: JNI_OnUnload not invoked
05:19:11  JavaTest Message: shutting down test
```

To rebuild, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64_aix&TARGET=jdk_lang_0

**Comment by DanHeidinga** [comment]
@JasonFengJ9 think this is related to the JDK15 native library changes?

**Comment by JasonFengJ9** [comment]
@DanHeidinga agreed, will have a look.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Is there a PR for this that I'm not finding?  Looking for an update on how this will complete for JDK15

**Comment by JasonFengJ9** [comment]
@DanHeidinga I don't have a PR for this yet, was interrupted by other workitems. Will pick it up.

**Comment by JasonFengJ9** [comment]
This test [1] mainly is to verify that the `JNI_Onload` & `JNI_OnUnload` of a non-jni native library introduced in JDK15 are not invoked when the library is loaded/unloaded. This test has to be run as part of `java.base/jdk.internal.loader` package [2]. Technically this is a test for hotspot internals. The flag `jdk.internal.loader.NativeLibraries.isJNI` [3] is passed to JCL native but not passed to any `JVM_` methods hence `OpenJ9` doesn't have this information to determine if `JNI_Onload` or `JNI_OnUnload` should be invoked.
It will be nice to reuse native library loading mechanism implemented by `jdk.internal.loader.NativeLibraries` just like we reuse `jdk.internal.loader.BootLoader` etc. Attempted to emulate `hotspot vm NativeLibraries` native behaviour however I don't have a working prototype yet.
I would propose moving this issue to next release based on following observations:
1. This is a hotspot internal test;
2. There is no other `OpenJ9 JDK15` native library loading functionality problem related to this issue.




[1] https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/37b152c56252eacfc7d5e29ba6e82bd4732fdf0c/test/jdk/jdk/internal/loader/NativeLibraries/java.base/jdk/internal/loader/NativeLibrariesTest.java#L69-L82
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/37b152c56252eacfc7d5e29ba6e82bd4732fdf0c/test/jdk/jdk/internal/loader/NativeLibraries/Main.java#L27
[3] https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/37b152c56252eacfc7d5e29ba6e82bd4732fdf0c/src/java.base/share/classes/jdk/internal/loader/NativeLibraries.java#L64
