### ISSUE TITLE
JEP 331 capability available when using metronome GC, but no events are sent

### ISSUE THREAD

**Issue by PhilippLengauer** [eclipse/openj9#9045]
The capability for JEP331 (https://docs.oracle.com/en/java/javase/11/docs/specs/jvmti.html#jvmtiCapabilities - can_generate_sampled_object_alloc_events) is available and can successfully be requested when using the metronome GC. However, not a single event is sent. According to the JVMTI spec, in such a case, the capability should (1) be not part of the available capabilites and (2) requesting that capability should result in an error, both is not the case. Alternatively, events could be sent as expected.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 @dmitripivkine

**Comment by JasonFengJ9** [comment]
This is a limitation as per https://www.eclipse.org/openj9/docs/version0.15/

```
 Restrictions: JEP 331 is implemented for OpenJ9 with the following limitations:
    The balanced and metronome garbage collection policies are not supported.
```

@DanHeidinga should we throw an error according to GC policy specified?

**Comment by DanHeidinga** [comment]
We should remove it from the available categories for the unsupported policies and error if requested

**Comment by dmitripivkine** [comment]
@LinHu2016 FYI

**Comment by pshipton** [comment]
Reopening as the fix was reverted since it broke compilation on jdk8.
