### ISSUE TITLE
Dockerfile pointed to by Build Instructions uses an invalid AdoptOpenJDK API on s390x

### ISSUE THREAD

**Issue by PushkarBettadpur** [eclipse/openj9#9057]
In trying to setup OpenJDK with OpenJ9 on zLinux, one of the steps in the Dockerfile contains the following command

https://github.com/eclipse/openj9/blob/6fbf525428bc0578d75f4c40549430cb089b2791/buildenv/docker/jdk8/s390x/ubuntu16/Dockerfile#L85

It seems the API is incorrect as I get the following error

```
Step 7/10 : RUN cd /root   && wget -O bootjdk8.tar.gz https://api.adoptopenjdk.net/openjdk8-openj9/releases/s390x_linux/latest/binary   && tar -xzf bootjdk8.tar.gz   && rm -f bootjdk8.tar.gz   && ls | grep -i jdk | xargs -I % sh -c 'mv % bootjdk8'
 ---> Running in 97085bc9266f
--2020-03-31 15:28:19--  https://api.adoptopenjdk.net/openjdk8-openj9/releases/s390x_linux/latest/binary
Resolving api.adoptopenjdk.net (api.adoptopenjdk.net)... 104.17.159.60, 104.17.158.60
Connecting to api.adoptopenjdk.net (api.adoptopenjdk.net)|104.17.159.60|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-03-31 15:28:20 ERROR 404: Not Found.
```

It seems that this version of the API is deprecated and we should likely move to v3? https://api.adoptopenjdk.net/swagger-ui/

**Comment by DanHeidinga** [comment]
> It seems that this version of the API is deprecated and we should likely move to v3?

+1

fyi @keithc-ca for inclusion in the Docker file update work

**Comment by keithc-ca** [comment]
The [script](https://github.com/keithc-ca/openj9/blob/docker/buildenv/docker/mkdocker.sh#L509) I'm working on already uses v3 API.
