### ISSUE TITLE
AArch64: java/lang/String/UnicodeCasingTest.java.UnicodeCasingTest timeout failure

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse/openj9#9081]
Failure link
------------

https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/104/testReport/junit/java_lang_String_UnicodeCasingTest/java/UnicodeCasingTest/

- test category, sanity.openjdk
- OS/architecture, aarch_64

```
09:47:53  openjdk version "11.0.7" 2020-04-14
09:47:53  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+9-202003310000)
09:47:53  Eclipse OpenJ9 VM AdoptOpenJDK (build master-c529318aa, JRE 11 Linux aarch64-64-Bit Compressed References 20200331_256 (JIT enabled, AOT enabled)
09:47:53  OpenJ9   - c529318aa
09:47:53  OMR      - 0ecff81ea
09:47:53  JCL      - 34c3dd7d55 based on jdk-11.0.7+9)
```

Optional info
-------------

- intermittent failure (yes): 

Failure output (captured from console output)
---------------------------------------------

```
10:29:35  ACTION: main -- Error. Agent error: java.lang.Exception: Agent 20 timed out with a timeout of 1600 seconds; check console log for any additional details
```

This test is known to intermittently timeout on aarch64. We will add this test to the exclude list and revisit later.

**Comment by knn-k** [comment]
I opened AdoptOpenJDK/openjdk-tests#1848 to enable this test back again for AArch64.
JIT recompilation is enabled, and it is fast enough now for the timeout of 1600 seconds.

**Comment by knn-k** [comment]
The test passed on AArch64 in https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux/183/.
Closing.
