### ISSUE TITLE
Pull Request builds for z/p linux (test sanity)

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#91]
Similar to #24, we need pull request builds setup on our [Jenkins](https://ci.eclipse.org/openj9/) instance.

- Builds should compile and run the sanity test target.
- [Linux-ppc64le](https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/)
- [Linux-s390x](https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_390-64_cmprssptrs/)
- Whitelist OpenJ9 committers to trigger builds manually using trigger phrase (need this list)
- Trigger phrase `jenkins test sanity` case insensitive for all platforms
    - `jenkins test sanity plinux`
    - `jenkins test sanity zlinux`
- Trigger based on Github hook (not polling)
    - [Eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522322) to request Repo hook

**Comment by AdamBrousseau** [comment]
Do we want to archive the sdk from the build so developers can download it if needed?

**Comment by pshipton** [comment]
OpenJ9 does not create binaries. Archiving the sdk and making it available violates that, although convenient.
@mstoodle

**Comment by smlambert** [comment]
To be clear, archiving the artifacts of the build is temporary (done within the Jenkinsfile / pipeline script).  What ever we choose to archive, will be available only for as long as we keep the Jenkins workspaces around, which is configurable (last 5 builds, last 3 days, etc).  We plan to archive the test output to make it easier for developers to debug issues, should there be any...

**Comment by AdamBrousseau** [comment]
@pshipton is this a policy we decided on or a legal roadblock?

**Comment by pshipton** [comment]
It is a legal issue. As per the Eclipse project proposal https://projects.eclipse.org/proposals/eclipse-openj9 OpenJ9 is a source code only project that does not distribute binaries. The binaries include OpenJDK and other third party code which is available under different licenses from OpenJ9.

**Comment by AdamBrousseau** [comment]
Eclipse Bug resolved, we now have a webhook. I have added (am adding) the current OpenJ9 committers to the whitelist (admin list). See description for trigger phrases.

Unfortunately the PR Builder plugin is not honouring the global config admin list, I therefore had to add the list to every PR job we have configured to use the plugin. Hopefully this can be resolved.

Ideally we would whitelist the github team but there is no support for teams right now, only orgs
https://github.com/jenkinsci/ghprb-plugin/issues/160

**Comment by AdamBrousseau** [comment]
@jduimovich has confirmed hosting the binaries is not an issue. AdoptOpenJDK is the official distribution channel for the binaries not OpenJ9. However, we are storing the artifacts temporarily for the purposes of build/test. We are only building using the same methods anyone else can do themselves.

If there are no more objections I will add the bits to the job to archive the PR sdks back to Jenkins.
