### ISSUE TITLE
JDK10: value() method added to String.java to be implemented

### ISSUE THREAD

**Issue by yongja79** [eclipse/openj9#912]
Trying to compile OpenJ9 with Openjdk10 gives the following error:-

``` 
/root/openJDK10-J9-mirror/src/java.base/share/classes/java/lang/StringCoding.java:948: error: cannot find symbol
        return encodeUTF8(s.coder(), s.value(), false);
                                      ^
  symbol:   method value()
  location: variable s of type String
 ```

This is caused by OpenJ9 implementation of String.java (openj9/jcl/src/java.base/share/classes/java/lang/String.java) not having an implementation of the value() method.

**Comment by DanHeidinga** [comment]
FYI @JasonFengJ9

**Comment by andrew-m-leonard** [comment]
So i've managed to come up with an impl for String.value() that works, The JDK code that is called during ZipCoder invocation is wanting to obtain the "raw" value of the String. So I copied some of the J9 getBytes() code to uncompress the value and return that as a byte[], and it seems to work. Here's what I added to openj9/jcl/src/java.base/share/classes/java/lang/String.java :
```
byte[] value() {
               int currentLength = lengthInternal();

               byte[] retValue = null;
               // Check if the String is compressed
               if (enableCompression && (compressionFlag == null || count >= 0)) {
                       if (value.length != currentLength) {
                               retValue = new byte[currentLength];
                               compressedArrayCopy(value, 0, retValue, 0, currentLength);
                       }
               } else {
                       if (value.length != currentLength << 1) {
                               retValue = new byte[currentLength << 1];
                               decompressedArrayCopy(value, 0, retValue, 0, currentLength);
                       }
               }

               if (retValue == null) {
                      retValue = Arrays.copyOf(value,value.length);
               }

               return retValue;
       }
```

**Comment by pshipton** [comment]
What happens if you try the impl "return value;" ?

**Comment by andrew-m-leonard** [comment]
The jmod zip file is corrupt, because the string returned for filenames is garbage, I think because "value" is a compressed byte...

**Comment by JasonFengJ9** [comment]
@yongja79 please provide a link to latest `Java 10` extension repo link such that I can reproduce the issue particularly mentioned above "corrupted filename when creating jmod zip file".
