### ISSUE TITLE
p, x linux crashes in OMR acceptance, blocking build

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9144]
vmState=0x000514ff
vmState [0x514ff]: {J9VMSTATE_JIT_CODEGEN} {globalValuePropagation}
vmState=0x000509ff
vmState [0x509ff]: {J9VMSTATE_JIT_CODEGEN} {localValuePropagation}

Seems caused by https://github.com/eclipse/omr/pull/4959

https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/1890/

https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_xl_OMR/136/
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64le_linux_OMR/542/
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_OMR/548/
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_OMR/540/
https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_cm_OMR/541/

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_OMR/500/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_xl_OMR/115/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_OMR/482/
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_OMR/477/

@fjeremic collected the following from https://ci.eclipse.org/openj9/job/Build_JDK11_x86-64_linux_xl_OMR/548
```
>>> printBackTrace2
JITServerHelpers::getRemoteROMClassIfCached(ClientSessionData*, J9Class*) + 71 in section .text of /tmp/jdk/lib/default/libj9jit29.so
J9::ClassEnv::classHasIllegalStaticFinalFieldModification(TR_OpaqueClassBlock*) + 24 in section .text of /tmp/jdk/lib/default/libj9jit29.so
constrainIfcmpeqne(OMR::ValuePropagation*, TR::Node*, bool) + 7903 in section .text of /tmp/jdk/lib/default/libj9jit29.so
OMR::ValuePropagation::transformUnsafeCopyMemoryCall(TR::Node*) + 797 in section .text of /tmp/jdk/lib/default/libj9jit29.so
OMR::ValuePropagation::launchNode(TR::Node*, TR::Node*, int) + 449 in section .text of /tmp/jdk/lib/default/libj9jit29.so
TR::GlobalValuePropagation::processBlock(TR_StructureSubGraphNode*, bool, bool) + 190 in section .text of /tmp/jdk/lib/default/libj9jit29.so
TR::GlobalValuePropagation::determineConstraints() + 312 in section .text of /tmp/jdk/lib/default/libj9jit29.so
TR::GlobalValuePropagation::determineConstraints() + 312 in section .text of /tmp/jdk/lib/default/libj9jit29.so
TR::GlobalValuePropagation::determineConstraints() + 312 in section .text of /tmp/jdk/lib/default/libj9jit29.so
```

@chrisc66 fyi

**Comment by mpirvu** [comment]
I find it strange that `JITServerHelpers::getRemoteROMClassIfCached` is called on a non-jitserver run

**Comment by chrisc66** [comment]
Looking into this...

**Comment by mpirvu** [comment]
The error is actually in openj9 in `J9::ClassEnv::containesZeroOrOneConcreteClass(TR::Compilation *comp, List<TR_PersistentClassInfo>* subClasses)`
This is a query that was added recently, but it misses a runtime check to verify whether the code is executed at the JITServer or not.

**Comment by mpirvu** [comment]
@chrisc66 Fix is coming in https://github.com/eclipse/openj9/pull/9145
