### ISSUE TITLE
Compiler for aarch64 is gcc 7.4 but should be gcc 7.5

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9159]
A recent build of aarch64 shows gcc 7.4 but gcc 7.5 should be used as per the other linux platforms.

[2020-04-05T13:28:47.824Z] * Toolchain:      gcc (GNU Compiler Collection)
[2020-04-05T13:28:47.824Z] * C Compiler:     Version 7.4.0 (at /usr/local/bin/gcc)
[2020-04-05T13:28:47.824Z] * C++ Compiler:   Version 7.4.0 (at /usr/local/bin/g++)

**Comment by pshipton** [comment]
@jdekonin

**Comment by knn-k** [comment]
What about the Docker files in https://github.com/eclipse/openj9/tree/master/buildenv/docker/jdk11 ?
The file for AArch64 uses GCC 7.3.1.  Other platforms use GCC 7.3 or 7.4, too.

**Comment by pshipton** [comment]
We haven't really been supporting the docker files. You can update them if you want. @keithc-ca has a [script](https://github.com/keithc-ca/openj9/blob/docker/buildenv/docker/mkdocker.sh#L509) which will generate them all, which will be delivered in the future when it's ready to replace the existing docker files.

**Comment by keithc-ca** [comment]
That script does not support AArch64 yet, and I think such support should be added after the initial version is merged. Cross-compiling would be a big addition. I suggest we update the existing AArch64 dockerfiles in the meantime.

**Comment by knn-k** [comment]
OK.  I opened https://github.com/eclipse/openj9/issues/9181 so that I can revisit it later.

**Comment by jdekonin** [comment]
I don't like where the Adopt playbook installs gcc too.  By default it unpacks a precompiled binary (on cent7?) to /usr/local/gcc.  As this doesn't allow for more than one version on the machine I compiled it myself with the default configure options except for `--prefix=/usr/local/gcc-7.5.0`.  

06:19:13  * C Compiler:     Version 7.5.0 (at /usr/local/gcc-7.5.0/bin/gcc)
06:19:13  * C++ Compiler:   Version 7.5.0 (at /usr/local/gcc-7.5.0/bin/g++)

I also added `/usr/local/gcc-7.4.0` for consistency.  The PR simply adds gcc-7.5.0 directory to the front of the PATH.

**Comment by jdekonin** [comment]
I also updated the `~/.bashrc` so if you are accessing this machine directly @knn-k you will get gcc-7.5 as default now.

**Comment by knn-k** [comment]
OK, I can see `gcc (GCC) 7.5.0` by running `gcc --version` now.
