### ISSUE TITLE
Ensure vm anon classes loaded before java.base have a module set

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#9183]
Code that should be setting the java.base module walks all the loaded classes in the `vm->systemClassLoader` which does a walk of the Class Segments processing those with the matching classloader: https://github.com/eclipse/openj9/blob/c80af2e8aba83e2adeacd3741aeaf9275a81a946/runtime/j9vm/java11vmi.c#L806-L812

VM Anonymous classes - those loaded by Unsafe.defineAnonymousClass - will have a different loader in their memory segments and will be missed by that `allClassesNextDo` walk.

_Originally posted by @DanHeidinga in https://github.com/eclipse/openj9/issues/8993#issuecomment-604571456_

**Comment by JasonFengJ9** [comment]
Will attempt a testcase to expose the issue.
