### ISSUE TITLE
Add a TraceAssert to `inlineAllocateIndexableObject` and similar helpers to validate class doesn't have `J9ClassContainsUnflattenedFlattenables` set

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#9200]
I'd like to see TraceAssert added to `inlineAllocateIndexableObject` and similar helpers to validate that we're not passing any classes that have the `J9ClassContainsUnflattenedFlattenables` bit set.

The assert should be guarded by `J9VM_OPT_VALHALLA_VALUE_TYPES`.  FYI @tajila

_Originally posted by @DanHeidinga in https://github.com/eclipse/openj9/pull/9139/files_

**Comment by tajila** [comment]
You can assign this to me

**Comment by gacholio** [comment]
Adding trace to such an obviously high traffic area of the code seems like a bad idea to me.

**Comment by DanHeidinga** [comment]
I don't want it permanently there - just for the development phase - and only under the VALHALLA define.

Better to catch any issues early at dev time then find them late.

**Comment by gacholio** [comment]
Suggest immediately opening the item to remove it when this gets merged.

**Comment by tajila** [comment]
@DanHeidinga There are some technical challenges to adding a tracepoint in `inlineAllocateIndexableObject` and `inlineAllocateIndexableValueTypeObject`. Those helpers live in ObjectAllocationAPI.hpp and are only used in VMHelpers.hpp (with the changes in #9804). 

None of the existing VMHelper have tracepoints. Attempting to inlcude the vm tracespoints causes issues when the inline functions are used in GC code, and vice versa when using the GC tracepoints. Other than using a tracepoint via a function table I'm not sure there is a simple way to add it.

The change in #9804 ensures that in all the cases where we do not know what kind of array we are allocating, these cases all use the new inlineallocate VMhelper. The helper performs the appropriate tests to ensure that all classes with the  `J9ClassContainsUnflattenedFlattenables` have to go through the slow path. As long as we have consistent usage of this helper we should never hit the case where an unflattenedvalue type is allocated incorrectly.

**Comment by gacholio** [comment]
@DanHeidinga Recommend closing this with no action.

**Comment by DanHeidinga** [comment]
Agreed.  I still have a concern about how to add tracepoints to these header files but that's a separate issue
