### ISSUE TITLE
Race condition in the presence of class unloading

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#9212]
JITServer keeps caches with information about classes/methods. At the beginning of each compilation the client will send to the server the list of classes that have been unloaded/replaced and the server  will delete those classes (and associated information) from its caches. 
A compilation thread at the server works in isolation from the client, but from time to time it may send a message to the client to query for needed information. If the client unloaded classes, it will inform the server to abort the compilation instead of replying to the query. The fact that the server worked internally while the client unloaded some class is irrelevant. It's like the client delayed the unloading of the classes until the exact moment the server decided to ask the client something.

However, with multiple compilation threads there is a race condition. One compilation thread (at the server) could access a cache and get a pointer to a class/method/classloader and then proceed to do something with it. Meanwhile, class unloading/redefinition happens at the client and this information is sent at the server with a new compilation request. The class is purged from the cache, but the first compilation thread may now work on invalid data (until it decides to ask the client a question). Note that when accessing the internal caches we always have a classCacheMonitor in hand. The problem happens when we acquire this monitor, retrieve some pointer to some cached data and then release the monitor: the data that the pointer points to may become stale. One way to deal with this issue is to always retrieve information from caches by value. Even then, we cannot retrieve some value from caches, release the classCacheMonitor, do something with that value and then acquire classCacheMonitor again expecting entries to be consistent with the previous retrieve operation. With great care these scenarios could be avoided, but the process is too error prone.

**Comment by mpirvu** [comment]
Conceptually, the solution to this problem is to control when classes can be deleted from the caches at the server by using some RWMutex, let's call it `classUnloadRWMonitor`. Compilation threads at the server would hold `classUnloadRWMonitor` for reading and release it only when it's safe from their point of view. The thread that deletes classes from the caches needs to lock `classUnloadRWMonitor` for writing. `classUnloadRWMonitor` needs to be allocated when the clientSession is created and stored into the clientSession. It will be deleted together with the clientSession. 
I see three implementations possible:
1) Compilation threads hold `classUnloadRWMonitor` throughout the entire compilation process. This would block the thread that wants to delete classes from the caches the longest, but maybe situation is not that bad because sooner or later a compilation thread will send a message to the client and find out that class unloading has occurred, thus failing the compilation in progress. We must make sure to release `classUnloadRWMonitor` whenever an exception is thrown.
2) Compilation threads hold `classUnloadRWMonitor` but release it whenever they send a message to the client and reacquire it when they receive the reply. This unlocks the monitor sooner because we don't wait for the network round trip like in the previous case. The problem with this solution is that all those acquire/release cycles may add a lot of overhead.
3) Like in (1), compilation threads hold `classUnloadRWMonitor` throughout the entire compilation process, but an additional flag, say `_classUnloadingAttempt` indicates whether some thread is about to delete classes from the caches. This flag needs to be marked volatile. When a message is about to be sent a compilation thread would check `_classUnloadingAttempt` and if `true', it will release `classUnloadRWMonitor` and abort the compilation itself, rather than waiting for the abort decision from the client. If `_classUnloadingAttempt` is `false, the thread proceeds normally keeping `classUnloadRWMonitor` locked for reading. The thread that deletes classes from the caches sets `_classUnloadingAttempt` just before acquiring `classUnloadRWMonitor` for writing and resets this flag right after it acquired `classUnloadRWMonitor`for writing.

**Comment by dmitripivkine** [comment]
This is completely orthogonal and I am not sure is it applicable however might be it helps FYI: Class unloading can be prevented is any of roots discovered by GC (for example o-slot in Java stack) points directly to class object. I believe we do have case already when java stack frame iterator returns back out-of-stack range addresses to be scanned as o-slots

**Comment by mpirvu** [comment]
Solved by #9243, hence closing.
