### ISSUE TITLE
DaaLoadTest MathLoadTest special crash vmState=0x00000000

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9215]
https://ci.eclipse.org/openj9/view/Test/job/Grinder/767
special.system aarch64 XL

DaaLoadTest_daa1_special_6
variation: Mode113
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:gencon -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xmn512k -Xnocompressedrefs 

DaaLoadTest_daa2_special_2
variation: Mode104
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optthruput -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve -Xnocompressedrefs 

DaaLoadTest_daa3_special_9
variation: Mode140
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optthruput -Xshareclasses -Xjit -Xnocompressedrefs 

DaaLoadTest_all_special_3
variation: Mode107
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0 -Xnocompressedrefs 

DaaLoadTest_all_special_8
variation: Mode122
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optavgpause -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xnocompressedrefs 
** This one is a bus error **

MathLoadTest_all_special_2
variation: Mode104
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optthruput -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve -Xnocompressedrefs 

MathLoadTest_all_special_8
variation: Mode122
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optavgpause -Xjit:count=0,optlevel=warm,gcOnResolve,rtResolve -Xnocompressedrefs 
** This one is a bus error **

MathLoadTest_bigdecimal_special_2
variation: Mode104
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optthruput -Xjit:count=0,optlevel=hot,gcOnResolve,rtResolve -Xnocompressedrefs

**Comment by Akira1Saitoh** [comment]
All cases except `DaaLoadTest_daa3_special9` crash when multiple threads are invoking a unresolved virtual method. We need to obtain a lock before entering critical section inside `_virtualUnresolvedHelper` as ppc does.

https://github.com/eclipse/openj9/blob/bcf1c1ab794256db837a24032b96240546e95c52/runtime/compiler/p/runtime/PicBuilder.spp#L2244-L2247

**Comment by Akira1Saitoh** [comment]
`DaaLoadTest_daa3_special9` crashes inside `old_fast_jitLookupInterfaceMethod` because `itableOffset` is 0. Looks like required memory barrier is **missing** in `_interfaceCallHelper` for aarch64. After an interface method is resolved and `itableOffset` is written to the memory, we need to issue a memory barrier to prevent other threads from seeing old value of that memory area as ppc does.
https://github.com/eclipse/openj9/blob/bcf1c1ab794256db837a24032b96240546e95c52/runtime/compiler/p/runtime/PicBuilder.spp#L2354-L2370

**Comment by knn-k** [comment]
#9237 fixes the thread safety issue with unresolved virtual method calls.

**Comment by pshipton** [comment]
Another crash in DaaLoadTest_daa3_special_3
https://ci.eclipse.org/openj9/view/Test/job/Grinder/803
special.system XL 0.20.0 build
variation: Mode107
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:count=0 -Xnocompressedrefs 

```
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00000000
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
DLT stderr Handler1=0000FFFFAC26C9C0 Handler2=0000FFFFAC129C9C InaccessibleAddress=0000FFFF00000018
DLT stderr R0=0000FFFF00000000 R1=0000FFF96704BFE0 R2=0000FFF933BF0AA4 R3=0000FFF9338C6408
DLT stderr R4=0000000000000000 R5=0000FFF9338C6408 R6=0000000000000000 R7=0000000000000000
DLT stderr R8=0000FFF933BF0AA4 R9=0000FFF9339EF704 R10=0000FFF933BF0B40 R11=0000FFF933BF0BE4
DLT stderr R12=0000000000000003 R13=0000FFF7300079B8 R14=0000FFF8F9672536 R15=0000FFFFA7A157FC
DLT stderr R16=0000FFFFA7510880 R17=0000FFFFAD0EAE1C R18=0000FFF968000710 R19=0000FFFFA896B000
DLT stderr R20=0000FFF730007A20 R21=0000FFFFA8341000 R22=0000FFFFA8500300 R23=0000000000000000
DLT stderr R24=0000FFF96716B570 R25=0000000000000000 R26=0000000000000000 R27=0000000000000000
DLT stderr R28=0000FFF7EAADE4B0 R29=390C49467251F800 R30=0000FFF933BF0BE4 R31=0000FFF7EAADE300
DLT stderr PC=0000FFFFA75108C0 SP=0000FFF7EAADE300 PSTATE=0000000020000000
DLT stderr V0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V1 000000003e3ab283 (f: 1044034176.000000, d: 5.158214e-315)
DLT stderr V2 0000000036380597 (f: 909641088.000000, d: 4.494224e-315)
DLT stderr V3 000000003dab7ca2 (f: 1034648768.000000, d: 5.111844e-315)
DLT stderr V4 000000003b55cf36 (f: 995479360.000000, d: 4.918321e-315)
DLT stderr V5 000000003917f7d1 (f: 957872064.000000, d: 4.732517e-315)
DLT stderr V6 0000000041800000 (f: 1098907648.000000, d: 5.429325e-315)
DLT stderr V7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V16 3fd999999997fa04 (f: 2576873984.000000, d: 4.000000e-01)
DLT stderr V17 3fd2492494229359 (f: 2485293824.000000, d: 2.857143e-01)
DLT stderr V18 3fcc71c51d8e78af (f: 495876256.000000, d: 2.222220e-01)
DLT stderr V19 3fc7466496cb03de (f: 2529887232.000000, d: 1.818357e-01)
DLT stderr V20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr V31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/lib/default/libj9jit29.so
DLT stderr Module_base_address=0000FFFFA72E0000
DLT stderr Target=2_90_20200415_13 (Linux 4.14.0-115.2.2.el7a.aarch64)
DLT stderr CPU=aarch64 (96 logical CPUs) (0x1fcd7e0000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr (0x0000FFFFAC145790 [libj9prt29.so+0x35790])
DLT stderr (0x0000FFFFAC12AE9C [libj9prt29.so+0x1ae9c])
DLT stderr (0x0000FFFFAC14580C [libj9prt29.so+0x3580c])
DLT stderr (0x0000FFFFAC145928 [libj9prt29.so+0x35928])
DLT stderr (0x0000FFFFAC12AE9C [libj9prt29.so+0x1ae9c])
DLT stderr (0x0000FFFFAC145674 [libj9prt29.so+0x35674])
DLT stderr (0x0000FFFFAC26C158 [libj9vm29.so+0x7c158])
DLT stderr ---------------------------------------
```

**Comment by knn-k** [comment]
I ran DaaLoadTest_daa3_special_3 20 times on test-packet-armv8-ubuntu-16-04, and saw no failures.

**Comment by knn-k** [comment]
It is difficult to say for sure, but PR #9282 should have resolved the crash with DaaLoadTest_daa3_special_3.  It was a crash in `_virtualUnresolvedHelper` in PicBuilder.spp, related to rewriting the `J9TR_UVCSnippet_method` field in the snippet.

**Comment by knn-k** [comment]
I think this issue can be closed.
I haven't seen crashes with DaaLoadTest and MathLoadTest after #9282 is merged.
