### ISSUE TITLE
Stream version incompatible with JITServer

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#9266]
While running sanity with verbose messages enabled I observed this message popping up:
`#JITServer: Stream version incompatible: JITServer expected version 17626562560768 received 35459249995776`

This should not happen because the client JVM and JITServer are from the exact same build. The version which supposedly the server received is completely bogus.
the only theory I have so far is that somehow the server is reading some leftovers from a previous message that was not completely read.

This issue is not fatal because the server will abort that message and clear its caches if it needs to, but something is not working right.

**Comment by a7ehuo** [comment]
I will take a look at this next.

**Comment by a7ehuo** [comment]
Reproduced once. The incompatible version is detected when the server received the message type `7 (clientSessionTerminate)`. The client sends `clientSessionTerminate` when it stops the compilation threads.  Regardless, the full version in the message MetaData should either be 0 or the correct one. I'll add some check at the client and see how it goes. One defensive code could be added is to add `_cMsg.clearFullVersion()` in `writeError` for `MessageType::connectionTerminate`. 

```
stream 0x7f8fa8ba36e8: readCompileRequest: serverVersion=0x100801000300 != clientVersion=0x204800000000. message type 7
getJITServerFullVersion 0x100801000300: getJITServerVersion 0x1000300, CONFIGURATION_FLAGS 0x1008
Assertion failed at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/net/StreamExceptions.hpp:123: false
	serverVersion=0x100801000300 != clientVersion=0x204800000000
```

**Comment by mpirvu** [comment]
Or, instead of clearing the version we could actually write the correct version with `_cMsg.setFullVersion(getJITServerVersion(), CONFIGURATION_FLAGS);` like we do for `buildCompileRequest(T... args)`
I agree that the version should have already been there because nobody overwrites it.
Another mistake that I see is that we don't write the number of datapoints which is 0 in this case (metadata is not followed by any datapoints)

**Comment by a7ehuo** [comment]
Gathered more information at the client side. I don't see `MetaData` constructor is triggered.  The members of `MetaData` are not initialled properly[1]. But as long as compilation request message is built and sent by the current stream,  `_version` and `_config` are set to the proper values. However, when sending `MessageType::clientSessionTerminate` message, a new `ClientStream` is created which is not used for any compilation request [2].  It looks to me `clearFullVersion()` should be added to `Message` constructor. 

[1]
```
===============================================
Running test jit_vich_0 ...
===============================================
...
(message type 7 clientSessionTerminate) stream 0x7f401b5b11a0: _cMsg.fullVersion 0x100009548, getJITServerFullVersion 0x100801000300. _versionCheckStatus 0

StringPeepholeTest_0_PASSED
...

===============================================
Running test jit_vich_0 ...
===============================================
...
(message type 7 clientSessionTerminate) stream 0x7f446425d1a0: _cMsg.fullVersion 0xd4a531400007f44, getJITServerFullVersion 0x100801000300. _versionCheckStatus 0

jit_vich_0_PASSED
...
```

[2]
https://github.com/eclipse/openj9/blob/c18a9cf1d9b70707a4344d7d4110a89cd67939a1/runtime/compiler/control/CompilationThread.cpp#L3518-L3522
