### ISSUE TITLE
`InvalidDataTypeException: UDATA contains value larger than Integer.MAX_VALUE` DDR issue decoding lookswitch

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#9294]
> The problem can be reproduced locally but jdmpview/DDR has got problem in decoding the specified class.
> 
> ```
> 
> > !bytecodes 0x00000000026C4F98
>   Name: getJarArray
>   Signature: ([Ljava/net/URL;[Ljava/net/URL;[Ljava/net/URL;Ljava/io/File;)[Ljava/net/URL;
>   Access Flags (1260002): private 
>   Max Stack: 5
>   Thrown Exceptions (1):
> java/net/MalformedURLException  Argument Count: 5
>   Temp Count: 47
> 
>     0 iconst5 
>     1 istore 10
>     3 iconst5 
> ...
>   298 lookupswitch pairs 1
>         default        637
>               4Problem running command:
> com.ibm.j9ddr.CorruptDataException: com.ibm.j9ddr.InvalidDataTypeException: UDATA contains value larger than Integer.MAX_VALUE
> ```

@keithc-ca fyi the `InvalidDataTypeException: UDATA contains value larger than Integer.MAX_VALUE` which needs to be fixed in the DDR code.

_Originally posted by @pshipton in https://github.com/eclipse/openj9/issues/9271#issuecomment-615443047_

**Comment by DanHeidinga** [comment]
@keithc-ca assigned to you as Peter tagged you for it.  Otherwise, @mikezhang1234567890 might be able to take a look at it

**Comment by keithc-ca** [comment]
The problem appears to be that [ByteCodeDumper](https://github.com/eclipse/openj9/blob/master/debugtools/DDR_VM/src/com/ibm/j9ddr/vm29/tools/ddrinteractive/commands/ByteCodeDumper.java#L369) is treating values and offsets as unsigned contrary to the VM spec. Things go wrong when a case target instruction precedes the `tableswitch` instruction.

**Comment by pshipton** [comment]
@ChengJin01 I've merged the fix just now, if you want to verify the problem no longer occurs once a JVM with the fix is available.

**Comment by ChengJin01** [comment]
@pshipton ,  I'll check this later to see how it goes once it is ready for downloading in nightly builds.
