### ISSUE TITLE
Dockerfile for zLinux can "fail to fetch" while building

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#930]
Attempting to build a docker image with the openj9 Dockerfile for jdk9 on zLinux can result in the following error:

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/xenial/universe/source/by-hash/SHA256/e201ab73d77c0208d5dcd4844b6215bc5e18b49d9f9b58d0fb627c47c0438ecd  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

This results in nothing that can be used. 

Attempting a rebuild results in this error:

E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/main/libx/libx11/libx11-6_1.6.3-1ubuntu2_s390x.deb  Connection failed
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Adding --fix-missing does indeed appear to prevent the problem. Are there any objections to making this a part of the Dockerfile?

Pull request: https://github.com/eclipse/openj9/pull/929

**Comment by DanHeidinga** [comment]
@adamfarley Why does `--fix-missing` prevent the problem?

We've previously closed a similar issue as being due to old version of apt / proxies between the client and the apt-server.  See https://github.com/eclipse/openj9/issues/14

**Comment by DanHeidinga** [comment]
My reading of the description:
```
--fix-missing
Ignore missing packages; If packages cannot be retrieved or fail the integrity check after retrieval (corrupted package files), hold back those packages and handle the result. Use of this option together with -f may produce an error in some situations. If a package is selected for installation (particularly if it is mentioned on the command line) and it could not be downloaded then it will be silently held back. Configuration Item: APT::Get::Fix-Missing.
```
indicates we'd be left with an incomplete docker image.

**Comment by adamfarley** [comment]
I assumed "fix missing" actually "fixed" things. An assumption on my part. RTM :)

Thanks for the quick response. Closing the issue.
