### ISSUE TITLE
jdk14 build manual need to update with correct develop kit directory

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#9300]
In the [Building OpenJDK Version 14 with OpenJ9](https://www.eclipse.org/openj9/oj9_build.html#version-14 ) the produced develop kit directory is mentioned as `build/<platform>/images/jdk` where `<platform>` refers to `linux-x86_64-normal-server-release`. 

@AdamBrousseau mentioned for newer version `<platform>` should be`linux-x86_64-server-release`.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9-website/issues/246 to fix the website and https://github.com/eclipse/openj9/pull/9311 to fix the OpenJ9 docs.
