### ISSUE TITLE
OpenJ9 [Win64 Hammer Compressed Pointers] 80  FAILED: testLoadingClasses

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#931]
Test has never passed on Windows.

Log file is:
===============================================
Running test testvmcheck_0 ...
===============================================
test with NoOptions
{ "C:/temp/bld_375906/j2sdk-image/jre/bin\\java"  -Xcompressedrefs  \
-cp "C:/temp/bld_375906/openj9/test///..//jvmtest\\TestConfig\\resources;C:/temp/bld_375906/openj9/test///..//jvmtest\\TestConfig\\lib\\testng.jar;C:/temp/bld_375906/openj9/test///..//jvmtest\\TestConfig\\lib\\jcommander.jar;C:/temp/bld_375906/openj9/test///..//jvmtest\\Java8andUp\\GeneralTest.jar" \
org.testng.TestNG -d "C:/temp/bld_375906/openj9/test/TestConfig/test_output_1515874166\\testvmcheck_0" "C:/temp/bld_375906/openj9/test///..//jvmtest\\Java8andUp\\testng.xml" \
-testnames testvmcheck \
-groups level.extended \
-excludegroups d.*.win_x86-64_cmprssptrs,d.*.arch.x86,d.*.os.win,d.*.bits.64,d.*.generic-all; \
if [ $? -eq 0 ] ; then echo "testvmcheck_0""_PASSED"; else echo "testvmcheck_0""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
[XmlSuite] [WARN] 'parallel' value 'false' is deprecated, default value will be used instead: 'none'.
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is C:/temp/bld_375906/openj9/test/\\TestConfig\\resources\\excludes\\latest_exclude_SE80.txt
...
... TestNG 6.10 by C�dric Beust (cedric@beust.com)
...

[TestNG] Running:
  C:\temp\bld_375906\openj9\jvmtest\Java8andUp\testng.xml

[TestLoadingClassesFromJarfile] [WARN] C:\temp\bld_375906\j2sdk-image\jre\bin\compressedrefs\jclSC180\vm.jar does not exist
[TestLoadingClassesFromJarfile] [WARN] C:\temp\bld_375906\j2sdk-image\jre\lib\se-service.jar does not exist
Exception in thread "Thread-165" java.lang.AssertionError: TEST_STATUS=TEST_FAILED : com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$24
	at org.testng.Assert.fail(Assert.java:94)
	at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile$StreamDumper.run(TestLoadingClassesFromJarfile.java:232)
FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)

**Comment by pshipton** [comment]
I think this is the same issue as #834

**Comment by pshipton** [comment]
@pdbain-ibm please close this if you agree its the same issue as #834. I can remove the jdk9 label from #834.

**Comment by pdbain-ibm** [comment]
Looks the same.
