### ISSUE TITLE
OpenJDK macos and AIX quarterly builds have too much content

### ISSUE THREAD

**Issue by sxa** [eclipse/openj9#9318]
Raised by a user in the slack channel shared with AdoptOpenJDK and OpenJ9 ... Adopt issue is at https://github.com/AdoptOpenJDK/openjdk-build/issues/1699

The downloads of JDK11 and JDK8 (probably 14 too) on macos and AIX seem to be very large relative to the previous quarterly releases.

From @pshipton in the slack channel: `From a quick look I think we're talking about MacOS, which now has a number of .dSYM files in the build that weren't there in the last release.`

**Comment by keithc-ca** [comment]
AdoptOpenJDK/openjdk-build#1703 should address the macos part of this.

**Comment by keithc-ca** [comment]
This should be fixed via AdoptOpenJDK/openjdk-build#1703.

**Comment by sxa** [comment]
I have initiated the following to verify - we can check what sizes the artifacts are when complete:
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1008/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/880/

**Comment by DanHeidinga** [comment]
With the IBM SDK, we had an automated job that checked that the SDK hadn't grown in size by more than small delta and flagged new files / removed files.

Is it worth adding a similar job to the Adopt pipelines to catch the SDK binaries haven't become too large?

**Comment by sxa** [comment]
Yes :-) This had already been suggested somewhere but I see it's not explicily in the retrospective item so please add it as a comment to https://github.com/AdoptOpenJDK/TSC/issues/151

**Comment by DanHeidinga** [comment]
Done https://github.com/AdoptOpenJDK/TSC/issues/151#issuecomment-619005073

**Comment by keithc-ca** [comment]
Looking at https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1008/artifact/target/, I only see a hotspot build for AIX. The build appears to be complete: are we assuming that the changes affect the openj9 variant for AIX similarly?

**Comment by sxa** [comment]
MIssing J9 builds are due to https://github.com/eclipse/openj9/issues/9369
