### ISSUE TITLE
compressed references heap limit difference

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#9319]
Why is it that if I take a compressed references build (for example [1]) the maximum heap it will allow me to specify is `-Xmx57g`?  But, if I explicitly add the `-Xcompressedrefs` command-line option I can push that to `-Xmx63g`?  I thought `-Xcompressedrefs` is the default so I would expect no difference in behaviour.

```
$ bin/java -Xmx63g Hello
Selected VM [default] does not exist.
This JVM package only includes the '-Xcompressedrefs' configuration. Please run the VM without specifying the '-Xnocompressedrefs' option or by specifying the '-Xcompressedrefs' option.
To compile the other configuration, please run configure with '--with-noncompressedrefs.

$ bin/java -Xcompressedrefs -Xmx63g Hello
Hello!
```

It is like the first case looks for the non-compressed refs VM at a lower heap threshold than what the compressed refs build will actually allow.  I have long remembered that the true limit for compressed refs with a shift of 4 is 57g which seems to be what the default case is looking for.

I wondering what the explanation is for this difference?

@amicic @dmitripivkine 

[1] https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10_openj9-0.20.0/OpenJDK11U-jdk_x64_linux_openj9_11.0.7_10_openj9-0.20.0.tar.gz

**Comment by dmitripivkine** [comment]
This rudiment comes from redirector support for combined compressed/full build. The value of 57g is a threshold when full 64-bit JVM has been automatically selected. However if `-Xcompressedrefs` is selected explicitly Compressed Refs JVM would be running regardless and heap size is limited by virtual memory provided by OS (with potential risk to get native OOM run time).
As far as we are close to have run-time selection CR/Full for running JVM I believe it will inherit current redirector behaviour. And yes, this is an intention
