### ISSUE TITLE
OpenJ9 [Win64 Hammer Compressed Pointers] 80 External  doesn't run

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#934]
New test, never passed.

@vsebe FYI

Looks like a path/commandline issue:

Command line is:

C:/cygwin64/bin/bash.exe -l -c " rm -rf /cygdrive/c/temp/bld_375906 && mkdir -p /cygdrive/c/temp/bld_375906 && cd /cygdrive/c/temp/bld_375906 && export JAVASVT_ROOT=/cygdrive/l/HEAD_368073/javasvt && export JAVASVT_PREREQS_ROOT=/cygdrive/l/HEAD_368073/javasvt_prereqs && export TEMP_ROOT=/cygdrive/c/temp/bld_375906 && scp linuxnfs.ottawa.ibm.com:/bluebird/builds/bld_375906/sdk/wa6480_openj9.zip /cygdrive/c/temp/bld_375906 && unzip -q /cygdrive/c/temp/bld_375906/wa6480_openj9.zip -d /cygdrive/c/temp/bld_375906 && git clone -b ibm_sdk_integration git@github.ibm.com:runtimes/openj9.git ./openj9 && cd ./openj9 && git checkout 04b088f && scp -r linuxnfs.ottawa.ibm.com:/bluebird/builds/bld_375906/test/* ./test && cd ./test/TestConfig && if [ 'win_x86-64_cmprssptrs' = linux_ppc-64_cmprssptrs_le_gcc -o 'win_x86-64_cmprssptrs' = linux_ppc-64_le_gcc ]; then export SPEC=linux_ppc-64_cmprssptrs_le; else export SPEC=win_x86-64_cmprssptrs; fi && export JAVA_BIN=C:/temp/bld_375906/j2sdk-image/jre/bin && export JAVA_VERSION=SE80 && make -f run_configure.mk && make compile && make external && cd w:\\builds\\bld_375906 && rm -rf /cygdrive/c/temp/bld_375906"

End of log is:

compile:
     [echo] Ant version is Apache Ant(TM) version 1.10.1 compiled on February 2 2017
     [echo] ============COMPILER SETTINGS============
     [echo] ===fork:				yes
     [echo] ===executable:			C:/temp/bld_375906/j2sdk-image/jre/bin/../../bin/javac
     [echo] ===debug:				on
     [echo] ===destdir:				C:/temp/bld_375906/openj9/test///..//jvmtest/cmdline_options_testresources
    [javac] Compiling 38 source files to C:\temp\bld_375906\openj9\test\cmdline_options_testresources\bin
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:37: warning: CallerSensitive is internal proprietary API and may be removed in a future release
    [javac] 	@sun.reflect.CallerSensitive
    [javac] 	            ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:42: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			sun.reflect.Reflection.getCallerClass();
    [javac] 			           ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:63: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			sun.reflect.Reflection.getCallerClass();
    [javac] 			           ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:80: warning: CallerSensitive is internal proprietary API and may be removed in a future release
    [javac] 	@sun.reflect.CallerSensitive
    [javac] 	            ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:85: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			sun.reflect.Reflection.getCallerClass();
    [javac] 			           ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:102: warning: CallerSensitive is internal proprietary API and may be removed in a future release
    [javac] 	@sun.reflect.CallerSensitive
    [javac] 	            ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:107: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			cls = sun.reflect.Reflection.getCallerClass();
    [javac] 			                 ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:132: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			sun.reflect.Reflection.getCallerClass();
    [javac] 			           ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:149: warning: CallerSensitive is internal proprietary API and may be removed in a future release
    [javac] 	@sun.reflect.CallerSensitive
    [javac] 	            ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:192: warning: CallerSensitive is internal proprietary API and may be removed in a future release
    [javac] 	@sun.reflect.CallerSensitive
    [javac] 	            ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\GetCallerClassTests.java:215: warning: CallerSensitive is internal proprietary API and may be removed in a future release
    [javac] 	@sun.reflect.CallerSensitive
    [javac] 	            ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\RefectionMHTests.java:72: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			method = sun.reflect.Reflection.class.getDeclaredMethod("getCallerClass");
    [javac] 			                    ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\RefectionMHTests.java:73: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			method.invoke(sun.reflect.Reflection.class);
    [javac] 			                         ^
    [javac] C:\temp\bld_375906\openj9\test\cmdline_options_testresources\src_80\com\ibm\j9\getcallerclass\RefectionMHTests.java:140: warning: Reflection is internal proprietary API and may be removed in a future release
    [javac] 			methodHandle = lookup.findStatic(sun.reflect.Reflection.class, "getCallerClass", methodType);
    [javac] 			                                            ^
    [javac] 14 warnings

dist:
      [jar] Building jar: C:\temp\bld_375906\openj9\jvmtest\cmdline_options_testresources\cmdlinetestresources.jar
     [copy] Copying 1 file to C:\temp\bld_375906\openj9\jvmtest\cmdline_options_testresources

clean:
   [delete] Deleting directory C:\temp\bld_375906\openj9\test\cmdline_options_testresources\bin

build:

BUILD SUCCESSFUL
Total time: 5 minutes 26 seconds
Running make 4.2.1
set JAVA_BIN to C:/temp/bld_375906/j2sdk-image/jre/bin
set SPEC to win_x86-64_cmprssptrs
set JAVA_VERSION to SE80
set SRC_ROOT to C:/temp/bld_375906/openj9/test/
set BUILD_ROOT to C:/temp/bld_375906/openj9/test///..//jvmtest
set JCL_VERSION to latest
make: Nothing to be done for 'external'.
/usr/bin/bash: line 0: cd: w:buildsbld_375906: No such file or directory

<axxon-message>
    Disconnected from remote host.
</axxon-message>

**Comment by vsebe** [comment]
@llxia FYI

**Comment by llxia** [comment]
Close this defect as we updated testkitgen.
Please reopen, if you see the failure still exists.
