### ISSUE TITLE
ExtendedMemoryMXBeanImpl can cause a ClassLoader leak

### ISSUE THREAD

**Issue by jhanders34** [eclipse/openj9#9343]
com.ibm.lang.management.internal.ExtendedMemoryMXBeanImpl can cause an application ClassLoader to leak when an application is stopped and the ClassLoader is allowed to garbage collect.  The leak comes when addNotificationListener is called on a Thread whose context ClassLoader is set to an application ClassLoader.  When that ClassLoader is allowed to garbage collect, it will be kept in memory by the MemoryNotificationThread that is started when addNotificationListener is called.  This happens because MemoryNotificationThread inherits the ClassLoader of the Thread that started it.

To resolve this issue, I can come up with two solutions:

1.  Update the context ClassLoader of the Thread when it is created to be the ExtendedMemoryMXBeanImpl.class.getClassLoader()
2.  Update the Class to have a Thread field that is created during class initialization, i.e. private final Thread notifier = new MemoryNotificationThread(this);

My preference is #1 since #2 doesn't guarantee that the Class is not loaded by a Thread that doesn't have an application ClassLoader as its context ClassLoader.  So if that is the case, then you would need to do #1 potentially as well in the constructor.

**Comment by jhanders34** [comment]
I see this problem in both OpenJ9 and IBM JDKs.

**Comment by DanHeidinga** [comment]
@jhanders34 do you have a reproducible test case that can be shared with us?  It'll make it easier to validate any fix

**Comment by jhanders34** [comment]
Here is a simple test case that shows the problem:

```
import java.lang.management.ManagementFactory;
import java.lang.management.MemoryMXBean;
import java.lang.ref.WeakReference;
import java.net.URL;
import java.net.URLClassLoader;

import javax.management.Notification;
import javax.management.NotificationEmitter;
import javax.management.NotificationListener;

public class MemoryMXBeanLeak implements NotificationListener {
    
    public static void main(String[] args) throws Exception {

        URLClassLoader ucl = new URLClassLoader(new URL[0]);
        ClassLoader oldCL = Thread.currentThread().getContextClassLoader();
        // if you comment out this next line you will not see the leak.
        Thread.currentThread().setContextClassLoader(ucl);
        MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();
        NotificationEmitter notifEmitter = (NotificationEmitter) memoryBean;
        notifEmitter.addNotificationListener(new MemoryMXBeanLeak(), null, null);
        Thread.currentThread().setContextClassLoader(oldCL);
        WeakReference<ClassLoader> ref = new WeakReference<>(ucl);
        ucl = null;
        for (int i = 0; i < 10; ++i) {
            System.out.println("calling system gc");
            System.gc();
            Thread.sleep(1000);
            if (ref.get() == null) {
                break;
            }
        }
        if (ref.get() != null) {
            System.out.println("ClassLoader leaked");
        } else {
            System.out.println("ClassLoader didn't leaked");
        }
    }

    @Override
    public void handleNotification(Notification notification, Object handback) {   }
}
```

**Comment by jhanders34** [comment]
If this same pattern is used in other Java provided MXBeans, those should be fixed as well.  The above test case may be able to show those as well just by changing the MXBean getter that is called on ManagementFactory.
