### ISSUE TITLE
Jenkins PR builds fail if a dependent change has been merged

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#935]
Sometimes a dependent PR may be opened the dependent OMR PR may be merged before any committer has had a chance to review or launch a Jenkins build on the PR. An example of this can be found in https://github.com/eclipse/openj9/pull/896. When this happens we are no longer able to launch any Jenkins PR builds. Using the aforementioned PR the following builds did not work:

```
Jenkins test sanity all
```

or

```
Jenkins test sanity all depends eclipse/omr#2205
```

The former fails because it seems to be building against the a "clean" version of OMR which does not contain the dependent change because it won't build until the OpenJ9 PR has been merged. The latter fails because the dependent PR has been merged and we fail to fetch git refs for the PR.

It would be great to get this fixed so we can continue to launch "depends" PR builds even after a dependent change has been merged.

**Comment by fjeremic** [comment]
@AdamBrousseau does `Jenkins test sanity all` build against eclipse/openj9-omr/openj9 or eclipse/openj9-omr/master? It seems as if it's the former, in which case we hav ea chicken and egg type problem where we cannot launch PR dependent builds after an OMR dependent change has been merged.

**Comment by AdamBrousseau** [comment]
>does Jenkins test sanity all build against eclipse/openj9-omr/openj9 or eclipse/openj9-omr/master?

`eclipse/openj9-omr/openj9`
I think we can consider this a dup of #827

**Comment by fjeremic** [comment]
Ah I did not know about #827. You're right this is a duplicate. Closing this issue. We can continue discussion on #827 if needed.
