### ISSUE TITLE
ASSERTION FAILED ** at ConcurrentCardTable.cpp:1443

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9352]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/348
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_windows_Nightly/346
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.system_x86-64_windows_Nightly/71
DaaLoadTest_all_ConcurrentScavenge_0
```
DLT 00:18:12.956 - Completed 9.9%. Number of tests started=711 (+370)
DLT stderr 04:18:16.054 0x7ff10c55af00    j9mm.107    *   ** ASSERTION FAILED ** at ConcurrentCardTable.cpp:1443: ((false && (_extensions->isOld(object))))
```

**Comment by dmitripivkine** [comment]
@amicic FYI

**Comment by amicic** [comment]
Those builds just got 2 of my changes:
https://github.com/eclipse/omr/pull/5112
https://github.com/eclipse/openj9/pull/9330
Suspecting on OMR one.

**Comment by dmitripivkine** [comment]
The manifestation of the problem under investigation is a collision between Concurrent Mark and Concurrent Scavenge. Initial range for Concurrent Mark has not been initialized properly. As a result part of Mark Map related to Nursery has not been initialized completely (with 0xffffs). This allows Concurrent Mark to put Nursery object to the work packet... and assertion has been triggered eventually.

**Comment by pshipton** [comment]
Any chance to revert the problematic fix today (or fix it), so the tests aren't failing all weekend?

**Comment by amicic** [comment]
I can confirm that problem is due to https://github.com/eclipse/omr/pull/5112.
I'll need some time to figure out why. We should revert it.

**Comment by pshipton** [comment]
There is a revert button in the PR which I believe can be used by anyone to create the revert PR.

**Comment by dmitripivkine** [comment]
I believe revert fixed this issue.
@pshipton If it is true, can this item be closed?

**Comment by pshipton** [comment]
Yup, fixed now.
