### ISSUE TITLE
Register assumptions for classHasIllegalStaticFinalFieldModification events

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#9364]
PR #2580 has added a new type of runtime assumption, `RuntimeAssumptionOnStaticFinalFieldModification`, that is added to the RAT during CHTable.commit(). However, the JITClient code that performs the CHTable commit was not updated to process this type of assumption.
The list of classes for which one of their final fields was folded during the current compilation is kept in `comp._classForStaticFinalFieldModification`. This is collected during compilation at the server. The server needs to send this list to the client (together with all the other CHTable related data) and the client needs to add corresponding runtime assumptions during CHTable.commit
Also, compilations need to fail if we find that any class inside `comp._classForStaticFinalFieldModification` list had their static field modified.

**Comment by mpirvu** [comment]
Attn: @harryyu1994

**Comment by harryyu1994** [comment]
Looks like `addClassForOSRRedefinition(clazz)` was called on JITServer as well, we probably need to send this list (_classForOSRRedefinition) over to the client as well. Unless it's ready done, let me double check.
```
/*
 * Adds the provided TR_OpaqueClassBlock to the set of those to trigger OSR Guard patching
 * on a static final field modification.
 */
void
J9::Compilation::addClassForStaticFinalFieldModification(TR_OpaqueClassBlock *clazz)
   {
   // Class redefinition can also modify static final fields
   addClassForOSRRedefinition(clazz);

   for (uint32_t i = 0; i < _classForStaticFinalFieldModification.size(); ++i)
      if (_classForStaticFinalFieldModification[i] == clazz)
         return;

   _classForStaticFinalFieldModification.add(clazz);
   }
```

**Comment by harryyu1994** [comment]
Yep it's already done
```cpp
   std::vector<TR_OpaqueClassBlock*> &classesForOSRRedefinition = std::get<7>(data);
```
Now I just need to add a similar one for `_classForStaticFinalFieldModification`

**Comment by mpirvu** [comment]
Fixed by 9396
