### ISSUE TITLE
Support docker on centos:7 or rhel:7 for s390x

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9372]
See https://github.com/eclipse/openj9/pull/9371

rhel:7 is the build platform for zlinux.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by keithc-ca** [comment]
The list of [available s390x OS images](https://hub.docker.com/search?q=&type=image&category=os&architecture=s390x) doesn't include centos or rhel. Will fedora suffice?

**Comment by pshipton** [comment]
I don't know much about Fedora. We want glibc version 2.17 or lower to match CentOS/RHEL 7. If you can find a release that meets that criteria then it's worth a shot.

**Comment by pshipton** [comment]
fedora:20 contains glibc 2.18

**Comment by pshipton** [comment]
Seems the lowest for zlinux is fedora:28, but on x86 this contains glibc 2.17

**Comment by pshipton** [comment]
Fixed my previous comment, should have been glibc 2.27, which is worse than Ubuntu 16 (equivalent to Ubuntu 18).

**Comment by pshipton** [comment]
Unless you have other ideas I'll close this, seems Ubuntu 16 is as good as it gets.
