### ISSUE TITLE
OpenJ9 Java 8 on Windows doesn't compile on VS10 Pro (before SP1)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#938]
Due to a recent omr change https://github.com/eclipse/omr/pull/2206

openjdk\build\windows-x86_64-normal-server-release\vm\omr\compiler\x/runtime/X86Runtime.hpp(80) : error C3861: '_xgetbv': identifier not found

@vsebe

**Comment by 0dvictor** [comment]
https://github.com/eclipse/openj9/issues/845 may need to be updated as well.

**Comment by vsebe** [comment]
Updated 9.28..28.162.180 - win2008x64rt1

Microsoft Visual Studio 2010
Version 10.0.40219.1 SP1Rel
Microsoft .NET Framework
Version 4.7.02053 SP1Rel

Rebuilt openj-openjdk-jdk8:

```
j9build@win2008x64rt1 /cygdrive/c/temp/bld_376037/openjdk
$ build/windows-x86_64-normal-server-release/images/j2sdk-image/bin/java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-j9build_2018_01_15_20_07-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Windows Server 2008 R2 amd64-64 Compressed References 20180115_000000 (JIT enabled, AOT enabled)
OpenJ9   - 881ddbc6
OMR      - abc15c85
OpenJDK  - 5c30d051e1 based on jdk8u152-b16)


```

**Comment by vsebe** [comment]
9.28.161.140 - win7x64rt1
9.28.161.153 - win10x64rt2
9.28.162.183 - win10x64rt1
are done too
