### ISSUE TITLE
Enable paranoid opt. check for jitdumps resulting from crashes in the optimizer

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#9386]
I'd like to propose that we enable the `TR_EnableParanoidOptCheck` option when we are generating a recompilation jitdump resulting from a crash whose VMState determines we are somewhere in the optimizer. 

Personally I think this change should be made as I don't see too much of a downside to it, and a large benefit that can potentially identify structural problems found in the trees/CFG before an optimization runs. This can further aid the developers by having an assumption that the tree shapes, reference counts, and the CFG are valid before an optimization starts.

Before making this change I'd like to get input from resident experts in the area of the optimizer for their thoughts, so subscribing @andrewcraik @cathyzhyi @vijaysun-omr for input.

**Comment by fjeremic** [comment]
This issue has been encountered in #8992 where developers requested that paranoid opt checks be enabled for a crash in area of usedef analysis.

**Comment by fjeremic** [comment]
@andrewcraik @cathyzhyi @vijaysun-omr any thoughts on this?

**Comment by andrewcraik** [comment]
It seems a reasonable thing to do from my perspective.

**Comment by cathyzhyi** [comment]
Sounds reasonable to me as well.

**Comment by vijaysun-omr** [comment]
Yes, seems like a valid place for paranoidOptCheck to run...it does run the risk of "getting in the way" of the original crash but surely we would'nt have two independent bugs in the same compile and so using the option to catch it as early as possible seems right.
