### ISSUE TITLE
Class verification LocalVariableTypeTable string equality

### ISSUE THREAD

**Issue by theresa-m** [eclipse/openj9#9405]
https://github.com/eclipse/openj9/pull/9347#pullrequestreview-402332454

Validate this against RI before implementing.

**Comment by theresa-m** [comment]
I created a class file with duplicate UTF8 entries in the constant pool, and LVT / LVTT entries that are duplicates in strings but not indices.

```
Constant pool:
...
#29 = Utf8               map
...
#32 = Utf8               map

LocalVariableTable:
Start  Length  Slot  Name   Signature
   17       2     3   map   Ljava/util/Map;      <---- name refers to #29
   17       2     3   map   Ljava/util/Map;      <---- name refers to #32

LocalVariableTypeTable:
Start  Length  Slot  Name   Signature
   17       2     3   map   Ljava/util/Map<Ljava/lang/String;TT;>;      <---- name refers to #29
   17       2     3   map   Ljava/util/Map<Ljava/lang/String;TT;>;      <---- name refers to #32
```


Results: The RI does not throw an error during class loading. OpenJ9 has identical behavior.

@DanHeidinga is there anything else you want me to check around string equality before I close this?

**Comment by DanHeidinga** [comment]
Which version of the RI was used in the test?  JDK 8, 11 or something else?

**Comment by theresa-m** [comment]
Java 14.

**Comment by theresa-m** [comment]
I've confirmed the same behavior for 8 & 11.

**Comment by DanHeidinga** [comment]
I think we can close this
