### ISSUE TITLE
ChaCha20/OutputSizeTest Need at least 2048 bytes of space in output buffer

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9429]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly/24
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_windows_Nightly/22
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_Nightly/44 (ub18-ppcle-1)
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/44 (ub16x64j92)

com/sun/crypto/provider/Cipher/ChaCha20/OutputSizeTest.java
```
00:25:57  STDERR:
00:25:57  javax.crypto.ShortBufferException: Need at least 2048 bytes of space in output buffer
00:25:57  	at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:760)
00:25:57  	at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
00:25:57  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
00:25:57  	at OutputSizeTest.testMultiPartAEADDec(OutputSizeTest.java:151)
00:25:57  	at OutputSizeTest.main(OutputSizeTest.java:49)
00:25:57  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:25:57  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:25:57  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:25:57  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:25:57  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
00:25:57  	at java.base/java.lang.Thread.run(Thread.java:834)
00:25:57  
00:25:57  JavaTest Message: Test threw exception: javax.crypto.ShortBufferException
00:25:57  JavaTest Message: shutting down test
00:25:57  
00:25:57  STDOUT:
00:25:57  CTBuf: java.nio.DirectByteBuffer[pos=1024 lim=1024 cap=2064]
00:25:57  PTBuf: java.nio.DirectByteBuffer[pos=1024 lim=2048 cap=2048]
```

**Comment by pshipton** [comment]
Grinder to repeat the failure
https://ci.eclipse.org/openj9/job/Grinder/868 - failed (ub18-ppcle-1)

Grinder with `-Djdk.nativeChaCha20=false`
https://ci.eclipse.org/openj9/job/Grinder/869 - passsed (ub18-ppcle-1)

@ashbm5 @samasri another ChaCha20/OutputSizeTest failure. We got new jdk11 material,  although I don't see any change to the test class itself.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/a534361...82fd27f

I've opened a PR to temporarily exclude the failing test until it can be fixed.
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1764

**Comment by samasri** [comment]
Okay, we'll look into it.

**Comment by samasri** [comment]
This issue is happening because [the ChaCha20 update function](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/2d171f8/closed/src/java.base/share/classes/com/sun/crypto/provider/NativeChaCha20Cipher.java#L636-L644) returns an output byte array the same size as the input, even if it did not encrypt the data yet.

For example, if a client tries to encrypt 1KB of data with update, the update function stores the input in its own internal buffer without encrypting it, but it returns a 1KB array as output. So the client might think those bytes are encrypted and provides a smaller output array for the final call. But the final call requires a big output array to hold all the input.

**Comment by keithc-ca** [comment]
`NativeChaCha20Cipher.EngineAEADDec` appears to capture the entire input in a `ByteArrayOutputStream`: if the input is large (think gigabytes) this is not reasonable.

**Comment by samasri** [comment]
Good point @keithc-ca 
Would you want us to work on this within this PR/issue or should we make a new issue for it? We would prefer to do it in a different issue because a different person will be working on that (so it's easier to separate PRs).

**Comment by keithc-ca** [comment]
Yes, I think it makes sense to work on that in a separate issue.

**Comment by pshipton** [comment]
Opened https://github.com/AdoptOpenJDK/openjdk-tests/pull/1784 to re-include the test.

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/305
https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/54
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/205
