### ISSUE TITLE
Return message of NoClassDefFoundError with slashes

### ISSUE THREAD

**Issue by Thihup** [eclipse/openj9#9433]
Hello!

In Hotspot, the NoClassDefFoundError returns the class that doesn't exist with slashes, while the OpenJ9 returns with dots.
I'd like to know if there is an option to return the class name with slashes.

```shell
➜  hotspot/bin/java -cp . com.somepackage.Main
com/somepackage/SomeClass
false
➜  openj9/bin/java -cp . com.somepackage.Main                                     
com.somepackage.SomeClass
true
```
```java
package com.somepackage;

public class Main {
    public static void main(String[] args){      
        boolean example = true;
        try {
            new com.somepackage.SomeClass();
        } catch (NoClassDefFoundError error) {
            if ("com/somepackage/SomeClass".equals(error.getMessage())) {
                example = false;
            }
            System.out.println(error.getMessage());
        }
        System.out.println(example);
    }
}
```

**Comment by pshipton** [comment]
There is no current option that does this.

**Comment by DanHeidinga** [comment]
> I'd like to know if there is an option to return the class name with slashes.

@Thihup Can you tell us a bit about what kind of problems this is causing?

**Comment by Thihup** [comment]
> > I'd like to know if there is an option to return the class name with slashes.
> 
> @Thihup Can you tell us a bit about what kind of problems this is causing?

@DanHeidinga Sure! I have a legacy application that does a check like in the example to verify if some class isn't in runtime. Because of it the application can't startup correctly.

I have done some experiments and this is the main problem using the OpenJ9 instead of HotSpot. 
I wonder if adding a flag to the VM startup would be a possible solution.

**Comment by Thihup** [comment]
We've reworked the logic were it was used and now it is not necessary anymore. I'll close this issue
