### ISSUE TITLE
classRelationshipVerifierTests_0_FAILED : -XX:+ClassRelationshipVerifier cannot be used if -Xfuture or if -Xverify:all is enabled

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9435]
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.functional_s390x_linux_xl_Nightly/63`:
```
22:55:54  openjdk version "11.0.8-internal" 2020-07-14
22:55:54  OpenJDK Runtime Environment (build 11.0.8-internal+0-adhoc.jenkins.BuildJDK11s390xlinuxxlNightly)
22:55:54  Eclipse OpenJ9 VM (build ibm_sdk-1a1ee6bf19, JRE 11 Linux s390x-64-Bit 20200502_71 (JIT enabled, AOT enabled)
22:55:54  OpenJ9   - 1a1ee6bf19
22:55:54  OMR      - 4e9428844
22:55:54  JCL      - 82fd27fc4c5 based on jdk-11.0.8+1)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test classRelationshipVerifierTests_0 ...
===============================================
classRelationshipVerifierTests_0 Start Time: Sat May  2 23:17:45 2020 Epoch Time (ms): 1588475865206
variation: NoOptions
JVM_OPTIONS:  -Xfuture --enable-preview
JVMJ9VM013W Initialization error in function j9bcv29(7): -XX:+ClassRelationshipVerifier cannot be used if -Xfuture or if -Xverify:all is enabled
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

classRelationshipVerifierTests_0_FAILED
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=s390x_linux_xl&TARGET=classRelationshipVerifierTests_0

**Comment by DanHeidinga** [comment]
@sharon-wang can you look into this?

**Comment by sharon-wang** [comment]
Looking into it!

**Comment by sharon-wang** [comment]
Since `-Xfuture` is included in `JVM_OPTIONS`, a JVM error is expected, since `-XX:+ClassRelationshipVerifier` cannot be enabled alongside `-Xfuture` or `-Xverify:all`.

Looking at `JVM_OPTIONS:  -Xfuture --enable-preview`, are these the default options for tests on this platform, or was this a JDKNext test? 

If `-Xfuture` is commonly used with sanity tests, perhaps the test level for `classRelationshipVerifierTests` could be changed to `extended` instead of `sanity` as a partial fix. Currently, there is no trivial way to exclude/disable a test based on `JDK_OPTIONS` used.

**Comment by JasonFengJ9** [comment]
@sharon-wang this is a JDK11 test.

**Comment by DanHeidinga** [comment]
`-Xfuture` is surprising as a default test option.  @llxia any idea why this became the default?

**Comment by llxia** [comment]
These test jobs are auto-generated in `Test_Job_Auto_Gen` job using testJobTemplate. And `-Xfuture` is only added for JCK https://github.com/AdoptOpenJDK/openjdk-tests/blob/64208f5880ddefc82bff6cfbc9b5797226603eb2/buildenv/jenkins/testJobTemplate#L122

Reran `Test_Job_Auto_Gen/16792/` and it generated correct `Test_openjdk11_j9_sanity.functional_s390x_linux_xl_Nightly` without `EXTRA_OPTIONS`.  And exiting job history seems fine to me. We do not have enough job history to investigate what went wrong for the above job.

I increased the job history for now.

**Comment by pshipton** [comment]
Closing as some temporary hiccup adding `-Xfurture` .

**Comment by llxia** [comment]
Found out the problem. PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/1767

**Comment by JasonFengJ9** [comment]
It happened again at latest nightly build `Test_openjdk11_j9_sanity.functional_s390x_linux_xl_Nightly/64`:
```
===============================================
Running test classRelationshipVerifierTests_0 ...
===============================================
classRelationshipVerifierTests_0 Start Time: Sun May  3 19:27:10 2020 Epoch Time (ms): 1588559230406
variation: NoOptions
JVM_OPTIONS:  -Xfuture --enable-preview
JVMJ9VM013W Initialization error in function j9bcv29(7): -XX:+ClassRelationshipVerifier cannot be used if -Xfuture or if -Xverify:all is enabled
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by smlambert** [comment]
Once https://bugs.eclipse.org/bugs/show_bug.cgi?id=562706 is resolved, Lan's fix from https://github.com/AdoptOpenJDK/openjdk-tests/pull/1767 will be applied.

**Comment by llxia** [comment]
Test_openjdk11_j9_sanity.functional_s390x_linux_xl_Nightly/65 on May 4th is normal.

**Comment by JasonFengJ9** [comment]
yeah, build 65 is green. I was following the top pipeline job which is one day older and last night pipeline build just appears now.
Thanks the fix.
