### ISSUE TITLE
JDK15 zLinux : testSCCMLTests1_openj9_0_FAILED & testSCCMLTests1_openj9_0_FAILED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9437]
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.functional_s390x_linux_xl_Nightly/64`:
```
21:57:06  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxxlNightly)
21:57:06  Eclipse OpenJ9 VM (build ibm_sdk-1a1ee6bf19, JRE 15 Linux s390x-64-Bit 20200502_71 (JIT enabled, AOT enabled)
21:57:06  OpenJ9   - 1a1ee6bf19
21:57:06  OMR      - 4e9428844
21:57:06  JCL      - d8b6e277bae based on jdk-15+18)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
Testing: Test 18: JAZZ 31882 -Xshareclasses:verboseIO testing
Test start time: 2020/05/02 19:18:01 Pacific Standard Time
Running command: "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_xl_Nightly/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs -Xfuture --enable-preview -Xshareclasses:name=ShareClassesCMLTests,reset,verboseIO -version
Time spent starting: 2 milliseconds
Time spent executing: 462 milliseconds
Test result: FAILED

Testing: Test 18: JAZZ 31882 -Xshareclasses:verboseIO testing
Test start time: 2020/05/02 19:18:01 Pacific Standard Time
Running command: "/home/jenkins/workspace/Test_openjdknext_j9_sanity.functional_s390x_linux_xl_Nightly/openjdkbinary/j2sdk-image/bin/java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs -Xfuture --enable-preview -Xshareclasses:name=ShareClassesCMLTests,reset,verboseIO -version
Time spent starting: 2 milliseconds
Time spent executing: 462 milliseconds
Test result: FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
23:13:06  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=s390x_linux_xl&TARGET=testSCCMLTests1_openj9_0
23:13:06  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=s390x_linux_xl&TARGET=testSCCMLModularity_0

**Comment by pshipton** [comment]
Possibly related to the addition of `-Xfuture`

**Comment by pshipton** [comment]
Closing as some temporary hiccup adding `-Xfurture` https://github.com/eclipse/openj9/issues/9435#issuecomment-623649679, pls reopen if it still occurs.
