### ISSUE TITLE
JDK15 : OpenJ9 support for JNI & raw NativeLibraries

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9442]
JDK15 `jdk.internal.loader.NativeLibraries` introduced another way to load native libraries besides existing `JNI` library approach. From the source history, this is related to project `Panama`. 

Existing `JNI` library loading stays same for `System::loadLibrary` (and its friends `Runtime::load` & `Runtime::loadLibrary`). 

1. Support of auto-unloading.  The loaded native libraries are unloaded when the class loader is reclaimed;
2. Support of linking of native method.  See JNI spec;
3. Restriction on a native library that can only be loaded by one class loader;
4. Each class loader manages its own set of native libraries. The same JNI native library cannot be loaded into more than one class loader.

The new `raw` NativeLibrary has the following properties:
1. Native libraries loaded in this `raw` NativeLibraries instance are not `JNI` native libraries.  Hence `JNI_OnLoad` and `JNI_OnUnload` will be ignored.  No support for linking of native method;
2. Native libraries not auto-unloaded.  They may be explicitly unloaded via `NativeLibraries::unload`;
3. No relationship with class loaders.

Currently there is no breakage due to the new NativeLibrary except https://github.com/eclipse/openj9/issues/9018 in which the failure is due to `OpenJ9` invoked `JNI_OnLoad/JNI_OnUnload` functions.

The initial direction is to break up current native library `load/link/bind` into at least two phases, one is the loading which is expected to be common and shared by both `JNI` and `raw` native libraries, the other is `link/bind` for `JNI` libraries or some other way (TBD) for `raw` libraries.

fyi @DanHeidinga @tajila

**Comment by pshipton** [comment]
I note openjdk test jdk/internal/loader/NativeLibraries/Main.java is failing, which is likely realated to this.
```
java.lang.AssertionError: Native library loaded.  Expected: JNI_OnUnload not invoked
	at java.base/jdk.internal.loader.NativeLibrariesTest.assertTrue(NativeLibrariesTest.java:132)
	at java.base/jdk.internal.loader.NativeLibrariesTest.runTest(NativeLibrariesTest.java:69)
	at Main.main(Main.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:851)
```

**Comment by JasonFengJ9** [comment]
Yeah, that's #9018.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Is there anything needed here for JDK15?

**Comment by JasonFengJ9** [comment]
@DanHeidinga this is same as https://github.com/eclipse/openj9/issues/9018, can be moved to next release as well.
