### ISSUE TITLE
SplittableRandomTest.testBoundedDoubles() expected [0] but found [1]

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9445]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_s390x_linux_xl_Nightly/25
java/util/SplittableRandom/SplittableRandomTest.java
ub18-390-2
```
22:25:57  test SplittableRandomTest.testBoundedDoubles(): failure
22:25:57  java.lang.AssertionError: expected [0] but found [1]
22:25:57  	at org.testng.Assert.fail(Assert.java:94)
22:25:57  	at org.testng.Assert.failNotEquals(Assert.java:496)
22:25:57  	at org.testng.Assert.assertEquals(Assert.java:125)
22:25:57  	at org.testng.Assert.assertEquals(Assert.java:372)
22:25:57  	at org.testng.Assert.assertEquals(Assert.java:382)
22:25:57  	at SplittableRandomTest.testBoundedDoubles(SplittableRandomTest.java:491)
```

**Comment by pshipton** [comment]
fyi https://github.com/eclipse/openj9/issues/4613
Same test but NPE.

**Comment by pshipton** [comment]
@fjeremic

**Comment by fjeremic** [comment]
@PushkarBettadpur can you please take a look at this one? It looks to only fail on the one machine. The test seems to take like 40 seconds to finish so it should be quick to reproduce. You may need to request access to that machine.

**Comment by pshipton** [comment]
I'm guessing it occurs on both ub18-390-1 and ub18-390-2, just not the ub16 machines. I believe all the machines are the same except for the OS.

**Comment by pshipton** [comment]
Similarly https://github.com/eclipse/openj9/issues/9354 only occurs on ub18, possibly the same issue.

**Comment by PushkarBettadpur** [comment]
Took a stab at this and found it to be fairly reproducible on `ub18-390-2`. 

As it turns out, it seems like @pshipton was right and the issue is likely the same as https://github.com/eclipse/openj9/issues/9354. I applied Rahil's fixes and re-ran the test and observed no more failures.

**Comment by pshipton** [comment]
Closing as a dup of https://github.com/eclipse/openj9/issues/9354 which is now fixed via https://github.com/eclipse/openj9/pull/9662
