### ISSUE TITLE
Feature request: Enhance jextract to package DTFJ JARs

### ISSUE THREAD

**Issue by kgibm** [eclipse/openj9#9448]
The [IBM Eclipse DTFJ Update Site](https://developer.ibm.com/javasdk/tools/) packages static versions of DTFJ JARs that [may not work on all dumps](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558984). This is used primarily by users of [Eclipse Memory Analyzer Tool](https://www.eclipse.org/mat/).

It would be nice if jextract packaged DTFJ JARs in case the [manual work-around](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558984#c1) to get MAT to work needs to be used.

**Comment by ajohnson1** [comment]
It's a security risk though, as the customer would be submitting code (the packaged DTFJ JARs) which would then be executed inside IBM. 

Currently it seems that the jar is unsigned:
```
C:\Users\UserName\Downloads\OpenJDK8U-jdk_x64_windows_openj9_8u265b01_openj9-0.21.0\jdk8u265-b01\jre\lib\ext>..\..\..\bin\jarsigner -verify dtfj.jar

jar is unsigned.
```
If the jar was signed when the SDK was produced, and the signature was verified and the source was confirmed as being trusted before executing the code then that might be a little better. Or else match using a secure hash against that of a known good distribution.

**Comment by kgibm** [comment]
Thanks for the follow-up on this Andrew, I forgot about it. I agree. I wrote this before I understood these issues well. The correct solution is to discover the version of the JVM that produced the dump and then download the matching JARs from trusted sources.
