### ISSUE TITLE
New JCL Flag: OPENJDK_METHODHANDLES

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#9456]
I wanted to add a new flag, `OPENJDK_METHODHANDLES`, to toggle between the OpenJ9 and OpenJDK MethodHandle(s).

I was looking at jpp_configuration.xml:
https://github.com/eclipse/openj9/blob/875226b3db8cc5cdbcf0ca5f73419e800d7963ed/jcl/jpp_configuration.xml#L54-L59

`SIDECAR18-SE` configuration is the lowest dependency, which gets inherited by every Java version (Java 8 to Java 15).

Will adding `OPENJDK_METHODHANDLES` to the above `flags` list enable it across every Java version?

Does `OPENJDK_METHODHANDLES` need to declared elsewhere before being used?

@pshipton or @JasonFengJ9 Do you have answers for the above questions?

fyi @fengxue-IS

**Comment by JasonFengJ9** [comment]
> Will adding OPENJDK_METHODHANDLES to the above flags list enable it across every Java version?

That's correct. 

> Does OPENJDK_METHODHANDLES need to declared elsewhere before being used?

Just decorate the code required with `/*[IF OPENJDK_METHODHANDLES ]*/`.

**Comment by babsingh** [comment]
The new JCL flag is introduced in https://github.com/eclipse/openj9/pull/9496.
