### ISSUE TITLE
Unexpected java.lang.ClassCastException during Annotation processing and high level of parallelism

### ISSUE THREAD

**Issue by offerbaruch** [eclipse/openj9#9457]
Java -version output
--------------------

was able to reproduce with both IBM java and adoptOpenJdk but only on s390x or IBM z/OS:

```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20200416_593 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - cfa47e66cd5 based on jdk8u252-b09)

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.15 - pxz6480sr5fp15-20180502_01(SR5 FP15))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux s390x-64 Compressed References 20180425_385365 (JIT enabled, AOT enabled)
OpenJ9   - a7ffbfe
OMR      - a531219
IBM      - 59ef3dc)
JCL - 20180425_01 based on Oracle jdk8u171-b11
```

Summary of problem
------------------

During Annotation handling at a high parallelism getting different unexpected exceptions.
Worst case scenario is actually when we don't get an exceptions and the annotations are not being processed correctly which can cause **data loss**!

One of the exceptions is ClassCastException on the first return statement which is easy to see it is probably not a coding issue:

```
public <A extends Annotation> A getAnnotation(Class<A> annotationType) {
    checkNotNull(annotationType);
    for (Annotation annotation : annotations) {
      if (annotationType.isInstance(annotation)) {
        return annotationType.cast(annotation);
      }
    }
    return null;
}
```

Reducing the parallelism of the code reduces the chances of failures.
When removing the parallelism of the code we can't reproduce.
There are many other exceptions that happens on the original code but I believe they are all the same root cause.

Diagnostic files
----------------
No crashes - just exceptions.

Please find the attached zip file that contains a relatively small program (compared to the production application that is suffering from this) that allows to reproduce this issue on s390x (z/Linux). I was not able to reproduce on other platforms such on x64 or Windows 10.
[openj9-ibm-soundness-1.0-SNAPSHOT.zip](https://github.com/eclipse/openj9/files/4582637/openj9-ibm-soundness-1.0-SNAPSHOT.zip)

To run simply unzip on a z/Linux (s390x) machine set JAVA_HOME to an openJ9 based JRE and run the following command:
`bin/openj9-ibm-soundness`

Attached please also find an example output of this program:
[output.txt](https://github.com/eclipse/openj9/files/4582667/output.txt)
I believe the java.lang.NullPointerException and other exceptions I am seeing around this code are all the same root cause. but it is harder to be convinced that they are not code issues.

the program doesn't always reproduce the issue. But I would say one of 3 runs in my case generates these exceptions.

I am running this on a SLES 12-SP3 machine with 4 processors and 4GB of memory:
```
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

```

OutOfMemoryError: Java Heap Space
---------------------------------

No out of memory

**Comment by gacholio** [comment]
Reproduced locally with the latest IBM build.

**Comment by offerbaruch** [comment]
> Reproduced locally with the latest IBM build.

Reproduced on z/Linux or another platform?

**Comment by gacholio** [comment]
On zlinux, yes - I haven't tried elsewhere. I'm currently running without the JIT, which has so far been successful.

**Comment by manqingl** [comment]
This issue shows up with Java 8 SR 6 FP7 zLinux, so we need an APAR for this one.  I am not sure about other Java versions and platforms.

**Comment by offerbaruch** [comment]
`I do have a 2 PMRs opened with IBM about this. one from the customer side and one from my (ISV) side. does this help?

**Comment by gacholio** [comment]
That's where the APAR will go - please provide @manqingl with the details internally.

**Comment by offerbaruch** [comment]
Sent via email to @manqingl

**Comment by gacholio** [comment]
No failures on xLinux in many runs.

No failures on zLinux without JIT (in fewer runs as it's a lot slower).

**Comment by gacholio** [comment]
@fjeremic I'll see if I can limit it down a bit, but you may have a better plan of attack.

**Comment by fjeremic** [comment]
> @fjeremic I'll see if I can limit it down a bit, but you may have a better plan of attack.

Thanks. I've reproduced the issue and limited down. The minimal reproduction is with the following option:

```
export JAVA_OPTS="'-Xjit:limit={com/google/common/reflect/Parameter.getAnnotation(Ljava/lang/Class;)Ljava/lang/annotation/Annotation;}(tracefull,log=log.trace,lastoptindex=0,optlevel=cold)'"
```

The only heavy lifting we do in there is to inline `Class.isInstance` into a `TR::instanceOf` check. The test passes with `disableInlineInstanceOf` and fails every time without it. These are the checks we inline:

```
Initial result = 0
instanceof:Maximum Profiled Classes = 3
aload reg contains ref: 1
Cast Class runtimeVariable
instanceof: Class Not Evaluated. Evaluating it
aload reg contains ref: 0
instanceof: Emitting NullTest
instanceof: Loading Object Class
instanceof: Emitting Class Equality Test
Emitting CastClassCacheTest
instanceof: Emitting Super Class Test, Cast Class Depth = -1
Emitting Dynamic Cache for CastClass and ObjectClass
Requested Bytes = 128
instanceof: Internal Control Flow in OOL : false
```

I'm going to hand the investigation off to our resident expert in the area. @r30shah could you please take a look at this? I'll touch base with you offline to pass over the setup.

**Comment by offerbaruch** [comment]
Hello everyone,

Any progress made on this issue?

**Comment by r30shah** [comment]
@offerbaruch  I am looking into probable cause of the failure. Will be able to provide update on the problem and fix soon. For the time being you can try using `-Xjit:maxOnsiteCacheSlotForInstanceOf=0` option and see if it works. On test case from https://github.com/eclipse/openj9/issues/9457#issuecomment-624318283 , I was able to avoid the failure. For context, that option just disables additional optimization in instanceOf. Regular instanceOf opts will still be done

**Comment by offerbaruch** [comment]
Thank you @r30shah .
We have a larger test which produces more exceptions and errors along the ClasCastException but that is harder to share as it requires more infrastructure around it.
We have tried the setting on the comment you mentioned, that did not resolve all of symptoms though.
I will try this one as well and let you know how it goes.

**Comment by r30shah** [comment]
> We have tried the setting on the comment you mentioned, that did not resolve all of symptoms though.

Interesting, How do you set up the option `disableInlineInstanceOf`, my suggestion in https://github.com/eclipse/openj9/issues/9457#issuecomment-624755876 just disables a sub-set of what `disableInlineInstanceOf` does so if it still fails with that, there is no point of using `maxOnsiteCacheSlotForInstanceOf=0`.

**Comment by offerbaruch** [comment]
> > We have tried the setting on the comment you mentioned, that did not resolve all of symptoms though.
> 
> Interesting, How do you set up the option `disableInlineInstanceOf`, my suggestion in [#9457 (comment)](https://github.com/eclipse/openj9/issues/9457#issuecomment-624755876) just disables a sub-set of what `disableInlineInstanceOf` does so if it still fails with that, there is no point of using `maxOnsiteCacheSlotForInstanceOf=0`.

We only tested the JAVA_OPTS mentioned in the comment. nothing else.

**Comment by r30shah** [comment]
Ahh, kk, so you have not used `disableInlineInstanceOf` probably then. If that is the case, I recommend add `-Xjit:maxOnsiteCacheSlotForInstanceOf=0` to your `JAVA_OPTS`. I think this would make failures go away.

**Comment by offerbaruch** [comment]
Hi,

We tested our larger test case with the `-Xjit:maxOnsiteCacheSlotForInstanceOf=0` and were not able to reproduce the issue with this java option.

**Comment by r30shah** [comment]
Thanks a lot @offerbaruch  for verifying that. I am looking into one potential issue with that opt. I will keep posted.

**Comment by r30shah** [comment]
Found the problem. Summarizing the issue here. 

An `instanceOf` node in OpenJ9 has generally two children, first one is the object we are checking (Here it is `annotation`) and second one is the **Class (CastClass)** with which we are checking relation of this object (Here it is Class of `annotationType`). 
In this case, the CastClass is runtime variable, so on runtime we load the class of the `annotationType` and depending on type of it (Regular Class/Interface, etc) we execute runtime tests. If we find that `annotationType` is Interface at runtime, we do not have much options in terms of inlined fast tests to avoid a slow JIT helper call to get the results. For this reason on IBM Z we have added a onsite (at that particular instanceOf site) cache to store the result of previous helper call, which we would check next time, if it fails all the inline tests and is about to make a slow helper call. 
Problem occurred in this highly paralleled work-load where I am assuming, it was executing the same `instanceOf` site in  more than 500 threads, which would have caused a race condition in caching  the results (We store `J9Class` of both object and CastClass and next time check both slot). This race condition would have caused unexpected data in the cache looking at which it would have taken wrong decision (Returning true when `annotation` is not instanceOf `annotationType`). 

So problem was that we were loading/storing associated castClass and Object Class separately from the memory, which for 64-Bit JVM should be done so that it is quadword block concurrent. I have tested a fix that uses `LPQ` and `STPQ` which  loads and stores from the memory in quadword block boundary and do not see the failure. 
Working on polishing this fix, creating a PR soon

**Comment by gacholio** [comment]
What about 31-bit?

**Comment by r30shah** [comment]
@gacholio  My mistake in previous comment, This scenario will cause issue on 31-Bit JVM as well , though I think fix for that would not need LPQ/STPQ. Working through getting a fix.

**Comment by offerbaruch** [comment]
Hello @r30shah , thank you for all the details.
I understand you have identified the root cause. I have 2 questions:
1. When will a fix be available for customers to download?
2. Can you please provide me with an official workaround for this issue that a customer can implement with minimal impact on performance?

As I mentioned this is a high severity issue and can cause serious damage (not just unexpected exceptions) as we are making decisions based on these values.

Thanks in advance,
Offer Baruch

**Comment by r30shah** [comment]
@offerbaruch  I understand your concerns. I am going to open up Pull Request by end of this week, and I am expecting this to get merged in couple of days once the Pull Request is opened. Regarding to Fix available for customer, let me see if I can reply on the PMR you opened. But I am expecting that to be available in next release. 
With respect to workaround, it is disabling that codegen optimization which is causing the issue which you can do by specifying following JIT option.

`-Xjit:maxOnsiteCacheSlotForInstanceOf=0`

This will have minimal impact on the performance.  I am expecting an APAR (official workaround) to be available around the same time when fix will be merged.

**Comment by offerbaruch** [comment]
Thank you everyone for jumping on this.
It is very much appreciated.

**Comment by DanHeidinga** [comment]
@offerbaruch @r30shah IBM PMR discussions are better handled in the IBM PMR system and with the Service Engineers working the case.  The OpenJ9 project focuses on the technical issues and project's delivery.  We can't comment on or commit to IBM deliveries in this project

**Comment by manqingl** [comment]
@offerbaruch @r30shah For service related issues, please open a new case according to the link below (search for text "Open the Case via email"):

https://w3-connections.ibm.com/wikis/home?lang=en-gb#!/wiki/W7f1f0fb5ec8a_452b_b99e_1b9fa042d769/page/Reporting%20Java%20Issues

**Comment by offerbaruch** [comment]
> @offerbaruch @r30shah For service related issues, please open a new case according to the link below (search for text "Open the Case via email"):
> 
> https://w3-connections.ibm.com/wikis/home?lang=en-gb#!/wiki/W7f1f0fb5ec8a_452b_b99e_1b9fa042d769/page/Reporting%20Java%20Issues

Not sure what you mean @manqingl . what do I need to open exactly?
anyway, w3 is the IBM internal portal. I don't have access to it.

**Comment by manqingl** [comment]
> 
> 
> > @offerbaruch @r30shah For service related issues, please open a new case according to the link below (search for text "Open the Case via email"):
> > https://w3-connections.ibm.com/wikis/home?lang=en-gb#!/wiki/W7f1f0fb5ec8a_452b_b99e_1b9fa042d769/page/Reporting%20Java%20Issues
> 
> Not sure what you mean @manqingl . what do I need to open exactly?
> anyway, w3 is the IBM internal portal. I don't have access to it.

OK.  @klangman Could you please help address the issue from JIT service perspective?  Please consult with @r30shah for details of the APAR/fix.
