### ISSUE TITLE
Itemize and size the work to port AArch64 to JDK8

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#9458]
While AArch64 on OpenJ9 was being developed on JDK11, there were some community inquiries for JDK8 support (that I will link here if I can find them).  Regardless, it may make sense to round out platform support on JDK8.

This issue tracks the work to investigate the work involved and to come up with a sizing.  If the work is straightforward enough it might actually be completed as part of this process.

The OpenJ9 community can then be approached with the benefits and whether an additional platform can be contained within the existing infrastructure.

**Comment by 0xdaryl** [comment]
We have put some effort into this in the past.  See https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/307

The discovery was that the JDK8 class libraries are built differently and that led to some complications.  As our focus was JDK11 at the time we did not stand by to investigate and resolve.  Obviously we will have to revisit this as part of this effort.

**Comment by knn-k** [comment]
I opened #10262 earlier today, which is already merged.
I also updated https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/307.

**Comment by knn-k** [comment]
There is a problem that needs to be solved, around `strncpy()` in runtime/rastrace/trclog.c.
The configure script for JDK 8 does not accept the `--disable-warnings-as-errors-openj9` option.

Related issue: #4486

**Comment by knn-k** [comment]
I opened #10278 for the problem with trclog.c above.

**Comment by knn-k** [comment]
Adding build pipeline for JDK 8: https://github.com/eclipse/openj9/pull/10291

**Comment by knn-k** [comment]
Update Build_Instructions_V8.md: #10311

**Comment by knn-k** [comment]
I think this issue can be closed.

**Comment by 0xdaryl** [comment]
Done.
