### ISSUE TITLE
OpenJ9 build failure using Docker on macOS

### ISSUE THREAD

**Issue by OscarQQ** [eclipse/openj9#9481]
I used the script from [https://github.com/eclipse/openj9/blob/master/buildenv/docker/mkdocker.sh](https://github.com/eclipse/openj9/blob/master/buildenv/docker/mkdocker.sh ) and this command `bash mkdocker.sh --tag=openj9 --dist=ubuntu --version=16.04 --build` to build OpenJ9
but I am getting the following error: 
```
error: pack-objects died of signal 9
error: failed to run repack
The command '/bin/sh -c mkdir /home/jenkins/openjdk_cache && cd /home/jenkins/openjdk_cache && git init --bare && git remote add jdk8 https://github.com/ibmruntimes/openj9-openjdk-jdk8.git && git config remote.jdk8.tagopt --no-tags && git remote add jdk11 https://github.com/ibmruntimes/openj9-openjdk-jdk11.git && git config remote.jdk11.tagopt --no-tags && git remote add jdk14 https://github.com/ibmruntimes/openj9-openjdk-jdk14.git && git config remote.jdk14.tagopt --no-tags && git remote add jdknext https://github.com/ibmruntimes/openj9-openjdk-jdk.git && git config remote.jdknext.tagopt --no-tags && git remote add omr https://github.com/eclipse/openj9-omr.git && git config remote.omr.tagopt --no-tags && git remote add openj9 https://github.com/eclipse/openj9.git && git config remote.openj9.tagopt --no-tags && echo Fetching repository cache... && git fetch jdk14 && git fetch --all && echo Shrinking repository cache... && git gc --aggressive --prune=all' returned a non-zero code: 255
```
<img width="1125" alt="Screen Shot 2020-05-06 at 1 45 05 PM" src="https://user-images.githubusercontent.com/42520890/81236224-8f09f800-8fb1-11ea-86db-2068b30fa88d.png">

**Comment by fjeremic** [comment]
@keithc-ca FYI. Perhaps we should be fetching at `--depth 1` in the Dockerfile? I don't see a reason for fetch the whole history.

**Comment by pshipton** [comment]
@keithc-ca fyi

I don't think `error: pack-objects died of signal 9` indicates a problem with the docker script. It may be a problem with your machine running out of memory resource. There is a suggestion in https://stackoverflow.com/questions/18831788/git-error-cant-push-to-github-pack-objects-died-of-signal-9 which may help. You can use `--print` instead of `--build` to create the script, which you can then edit as necessary.

**Comment by OscarQQ** [comment]
Commenting out line 646 `echo " && git gc --aggressive --prune=all"` at mkdocker.sh, it will work

**Comment by keithc-ca** [comment]
That invocation of `git gc` shrinks the reference repository from well over 2GB to more like 400M. It isn't necessary to function, it just makes the docker image that much smaller.

Using `git fetch --depth=1` would not change that much.
