### ISSUE TITLE
Investigate optimizations to vmThreadListMutex

### ISSUE THREAD

**Issue by gacholio** [eclipse/openj9#9484]
Catalog uses of vmThreadListMutex with an eye towards allowing multiple readers/single writer.

**Comment by gacholio** [comment]
@DanHeidinga @andrewcraik

**Comment by gacholio** [comment]
This is the data I got from Dan:
```
 %MISS     GETS   NONREC     SLOW      REC    TIER2    TIER3 %UTIL AVER_HTM  MON-NAME
     2     8446     8446      205        0   330649    10092     3   569775  [00007F915C005E08] VM thread list
```

The slow acquire is a tiny portion of the overall mutex use.

These are the basic uses of the mutex:

**Walking the thread list (mutex to prevent it from being modified)**

Typically very small hold times.

**Ensuring thread liveness / preventing exclusive**

Extremely uncommon, mostly JVMTI.

**Modifying the thread list**

Again, small hold time, and cannot be avoided.

**Exclusive VM access (i.e. GC)**

The mutex is held for the entirety of the exclusive.

**Comment by gacholio** [comment]
The seemingly large hold time on this monitor is almost certainly the exclusive case.

Given that the rwmutex code also uses a monitor in its implementation, it would not speed up any of the non-exclusive cases (there would be equal contention on the internal monitor).

It's my opinion that this is not worth any further investigation -  the hold time in the JLM data is misleading.

@DanHeidinga @andrewcraik Do you agree?

**Comment by andrewcraik** [comment]
FYI @vijaysun-omr 

You could well be right @gacholio however I don't think @liqunl and I understand the situation in this benchmark well enough yet to agree or disagree. We do see this as very hot and we do know that minimizeUserCPU to reduce spinning helped about 7% so there is clearly lock badness. As you say, refactoring to a reader-writer lock may not be the right solution, but I don't feel confident yet to say exactly what is going on.

**Comment by DanHeidinga** [comment]
@gacholio I also mischaracterized the workload in our earlier discussion - the test isn't a startup scenario but rather an IO-heavy thruput one.  

For startup, I'd expect to see thread creation and global gcs potentially completing.  For thruput, that would be less likely.

**Comment by gacholio** [comment]
The slow case is only 2% of the total use, so I don't see spinning optimizations having much effect on this monitor.

**Comment by gacholio** [comment]
Spinning opts would also have no effect on hold time (which I assume is how the monitor list was sorted to make this one appear to be important).

**Comment by andrewcraik** [comment]
The sort order is the miss % which is the ratio of GETS to MISSes (eg how often we fail to enter and have to block). I think the spinning opts would reduce the amount of time spent in spin2 so we might waste less path length getting in (if I understand this output). As I say I am not certain enough of what the operations are that are causing the lock to be taken to be sure what the right fix is just yet. @gacholio could be right, but I don't feel qualified to express an opinion as yet.

**Comment by gacholio** [comment]
The most likely "non-essential" use of the monitor would be the beans - maybe see if those are being used excessively.

**Comment by andrewcraik** [comment]
@gacholio Which beans and how would I know they were being used excessively? Happy to try and investigate if you can provide some guidance on what/how to take a look.

**Comment by gacholio** [comment]
`ThreadMXBean` is the bean in question.

**Comment by vijaysun-omr** [comment]
That is an interesting point @gacholio raises. Maybe we can get an scs (call flow) profile and see if ThreadMXBean apis are being called.

**Comment by andrewcraik** [comment]
No signs of ThreadMXBean or other MBeans/MXBeans being used from an SCS thanks to @liqunl. Going to check the verbose GC log to see about global collects to try and explain the lock usage.

**Comment by gacholio** [comment]
Any JVMTI agents?

**Comment by gacholio** [comment]
The JIT sampler also walks the thread list - perhaps disable that, though I'm not sure what performance implications that would have overall.

**Comment by vijaysun-omr** [comment]
Is this mutex acquired on the code path where a new TLH is acquired ?

**Comment by gacholio** [comment]
Not that I can see.

**Comment by liqunl** [comment]
> The JIT sampler also walks the thread list - perhaps disable that, though I'm not sure what performance implications that would have overall.

Thanks for suggestion. The slow gets on VM Thread list is caused by JIT sampler.

**Comment by gacholio** [comment]
As we've accounted for the slow gets and determined that changing the mutex type would not be valuable, I'm going to close this.
