### ISSUE TITLE
Validate this Java 9+ code to get the java.version is correct

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#9500]
https://github.com/eclipse/openj9/blob/184592249e47b4bee8079914abdda946bbd66b21/jcl/src/java.base/share/classes/java/lang/System.java#L620-L635

Returns a hardcoded "1.9.0" which seems wrong for other releases and as the version shouldn't start with "1."

**Comment by pshipton** [comment]
It was added in 2016 by @hangshao0 with the following commit message, the purpose appears to be in order to run a legacy benchmark. I expect we can delete the code.
```
In order not to break application that assumes java.version to be 1.x.x,
make getProperty("java.version") to return "1.9.0" when
-Duse.legacy.version is set and the caller class module is null
```

**Comment by pshipton** [comment]
I'll create a PR to remove the obsolete code.

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/pull/9503
