### ISSUE TITLE
[GC/RISC-V] Jenkins agent crashed on stage4/QEMU when running test jobs

### ISSUE THREAD

**Issue by ChengJin01** [eclipse/openj9#9501]
When running a Jenkins agent on a Fedora_stage4/QEMU box to attempt to run a test against the JDK, the Jenkins agent keeps crashing somewhere in GC with the following output:
```
INFO: Connected
Unhandled exception
Type=Segmentation error vmState=0x0002000f <-----  J9VMSTATE_GC  0x20000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
Handler1=0000002000AC6F78 Handler2=0000002000B91186 InaccessibleAddress=4965766965636572
PC=4965766965636572 RA=000000200156C22E SP=00000020032711A0 GP=0000002AAAAAC800
TP=00000020032738F0 T0=0000000000000001 T1=00000020032712D8 T2=00000020700009CF
S0=000000200FC9C054 S1=00000000D1F7DF00 A0=000000200FC9C054 A1=00000020032711B0
A2=0000000000000100 A3=00000020016458F8 A4=00000020032712D8 A5=0000002000A19910
A6=0000000000000001 A7=00000020015FD26E S2=00000020032711B0 S3=0000000000000001
S4=0000000000000001 S5=0000002003271580 S6=00000020032714B8 S7=00000020032714C0
S8=0000000000000000 S9=0000000000046700 S10=00000020032715F8 S11=0000000000000004
T3=4965766965636572 T4=0000000000000018 T5=0000000000043588 T6=0000000000000001
PC=4965766965636572
FT0 3fd27616c9496e0b (f: 3377032704.000000, d: 2.884576e-01)
FT1 bfe7154748bef6c8 (f: 1220474624.000000, d: -7.213475e-01)
FT2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FA0 00000000c2c7a05b (f: 3267862528.000000, d: 1.614539e-314)
FA1 c062000000000000 (f: 0.000000, d: -1.440000e+02)
FA2 bfdffffef20a4123 (f: 4060758272.000000, d: -4.999997e-01)
FA3 bfdffffef20a4123 (f: 4060758272.000000, d: -4.999997e-01)
FA4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FA5 c058f40b60000000 (f: 1610612736.000000, d: -9.981319e+01)
FA6 00000000d244fbf8 (f: 3527736320.000000, d: 1.742933e-314)
FA7 00000000d2008c38 (f: 3523251200.000000, d: 1.740717e-314)
FS2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FS11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FT11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
FCSR 0000000000000001 (f: 1.000000, d: 4.940656e-324)
Target=2_90_20200505_46 (Linux 4.19.0-rc8)
CPU=riscv (4 logical CPUs) (0xb8379000 RAM)
----------- Stack Backtrace -----------
(0x0000002000BA4F9C [libj9prt29.so+0x28f9c])
```

FYI:  @DanHeidinga , @sxa , @LinHu2016

**Comment by ChengJin01** [comment]
@sxa , please also set up a Fedora_rawhide/QEMU box to see whether the jenkins agent still crashed with the build cross-compiled with Fedora_rawhide.

**Comment by dmitripivkine** [comment]
There is virtually impossible to debug GC issues without DDR support. In this case however few can speculate `InaccessibleAddress=4965766965636572` is actually `PC=4965766965636572`. I looked to Snap traces for this failure and I know that crashed thread doing roots scan for Scavenger.
This failure looks like bad dynamic link(?). GC itself does not calculate an address to jump

**Comment by ChengJin01** [comment]
I am able to reproduce the crash remotely on the stage4/QEMU offered by @sxa. What happened is: the jenkins agent already successfully got started with connection to the test job waiting for the test job, in which case the crash occurred soon when the test job was launched remotely.

With the extracted snaptrace, it looks like "GC has completed RememberedSet scan and start root scan, it might be related with bad linkage, which GC calls something external but address was not provided properly at linkaggre stage" (from @LinHu2016 )

Given that DDR is required to investigate the issue on GC,  I will help to create a build with DDR support on stage4/QEMU with the cross-build as the build-JDK (at least 2 days to finish) locally and upload the build to the remote  stage4/QEMU box to see how it goes.

**Comment by ChengJin01** [comment]
@LinHu2016  & @dmitripivkine, the generated dump (with DDR) were placed in internal team folder at `cjin/jobs_2020/riscv_dumps`

I already verified the DDR in the dumps which seems fine as follows:
e.g.
```
bin/jdmpview -core  core.20200511.192749.28418.0001.dmp
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

Warning: native libraries are not available for core.20200511.192749.28418.0001.dmp
For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) : 

Source : file://.../ddr_dumps/core.20200511.192749.28418.0001.dmp
	*0 : PID: 28508 : JRE 11 Linux riscv-64 (build 11.0.8-internal+0-adhoc.chengjin.openj9-openjdk-jdk11)

> !threads
	!stack 0x00005f00	!j9vmthread 0x00005f00	!j9thread 0x2004006e50	tid 0x6f03 (28419) // (main)
	!stack 0x000e6c00	!j9vmthread 0x000e6c00	!j9thread 0x2004007840	tid 0x6f06 (28422) // (Common-Cleaner)
...

> !stack 0x00515c00
<515c00> 	!j9method 0x000000000008FA00   java/nio/HeapByteBuffer.<init>(II)V
<515c00> 	!j9method 0x000000000008DE70   java/nio/ByteBuffer.allocate(I)Ljava/nio/ByteBuffer;
<515c00> 	!j9method 0x000000000049AE00   org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.processWrite(Ljava/nio/ByteBuffer;)V
<515c00> 	!j9method 0x000000000049AD40   org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.processQueuedWrites()V
<515c00> 	!j9method 0x000000000049ACE0   org/jenkinsci/remoting/protocol/impl/SSLEngineFilterLayer.doSend(Ljava/nio/ByteBuffer;)V
<515c00> 	!j9method 0x00000000004C75E8   org/jenkinsci/remoting/protocol/ProtocolStack$Ptr.doSend(Ljava/nio/ByteBuffer;)V
<515c00> 	!j9method 0x000000000049C910   org/jenkinsci/remoting/protocol/ApplicationLayer.write(Ljava/nio/ByteBuffer;)V
<515c00> 	!j9method 0x00000000004C6358   org/jenkinsci/remoting/protocol/impl/ChannelApplicationLayer$ByteBufferCommandTransport.write(Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
<515c00> 	!j9method 0x00000000004C62F0   hudson/remoting/AbstractByteBufferCommandTransport.write(Lhudson/remoting/Command;Z)V

> !stackslots 0x00515c00                                          
<515c00> *** BEGIN STACK WALK, flags = 00400001 walkThread = 0x0000000000515C00 ***
<515c00> 	ITERATE_O_SLOTS
<515c00> 	RECORD_BYTECODE_PC_OFFSET
<515c00> Initial values: walkSP = 0x000000000051F5D0, PC = 0x000000200F729D26, literals = 0x000000000008FA00, A0 = 0x000000000051F628, j2iFrame = 0x0000000000000000, ELS = 0x00000020030CB560, decomp = 0x0000000000000000
<515c00> Bytecode frame: bp = 0x000000000051F610, sp = 0x000000000051F5D0, pc = 0x000000200F729D26, cp = 0x00000000000900C0, arg0EA = 0x000000000051F628, flags = 0x0000000000000000
<515c00> 	Method: java/nio/HeapByteBuffer.<init>(II)V !j9method 0x000000000008FA00
<515c00> 	Bytecode index = 6 <-------
<515c00> 	Using local mapper
<515c00> 	Locals starting at 0x000000000051F628 for 0x0000000000000003 slots
<515c00> 		O-Slot: a0[0x000000000051F628] = 0x00000000FFEE8EA8
<515c00> 		I-Slot: a1[0x000000000051F620] = 0x0000000000004145 <----
<515c00> 		I-Slot: a2[0x000000000051F618] = 0x0000000000004145 <----

>  !j9method 0x000000000008FA00
J9Method at 0x8fa00 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x000000200F729D20
	0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x00000000000900C0 (flags = 0x0)
	0x10: void* methodRunAddress = !j9x 0x0000000000000007
	0x18: void* extra = !j9x 0x0000000000000001
}
Signature: java/nio/HeapByteBuffer.<init>(II)V !bytecodes 0x000000000008FA00
ROM Method: !j9rommethod 0x000000200F729D0C
Next Method: !j9method 0x000000000008FA20
> bytecodes 0x000000000008FA00
Unrecognised command: bytecodes
> !bytecodes 0x000000000008FA00
  Name: <init>
  Signature: (II)V
  Access Flags (1040000): default 
  Max Stack: 7
  Argument Count: 3
  Temp Count: 0

    0 aload0 
    1 iconstm1 
    2 iconst0 
    3 iload2 
    4 iload1 
    5 iload1 
    6 newarray byte <---------------
    8 iconst0 
    9 invokespecial 3 java/nio/ByteBuffer.<init>(IIII[BI)V
   12 aload0 
   13 getstatic 4 java/nio/HeapByteBuffer.ARRAY_BASE_OFFSET J
   16 putfield 5 java/nio/HeapByteBuffer.address J
   19 returnFromConstructor 
```
against the genereated source code at` ./support/gensrc/java.base/java/nio/HeapByteBuffer.java`
```
59     HeapByteBuffer(int cap, int lim) {            // package-private
 60 
 61         super(-1, 0, lim, cap, new byte[cap], 0); <----------  new byte[0x4145]
 62         /*
 63         hb = new byte[cap];
 64         offset = 0;
 65         */
 66         this.address = ARRAY_BASE_OFFSET;
```
So, it looks like the crash was related to inlineAllocateIndexableObject or J9AllocateIndexableObject at runtime/vm/BytecodeInterpreter.hpp
```
	newarray(REGISTER_ARGS_LIST)
	{
		VM_BytecodeAction rc = EXECUTE_BYTECODE;
		U_8 arrayType = _pc[1];
		I_32 size = *(I_32*)_sp;
		if (J9_UNEXPECTED(size < 0)) {
			rc = THROW_NEGATIVE_ARRAY_SIZE;
		} else {
			J9Class *arrayClass = (&(_vm->booleanArrayClass))[arrayType - 4];
---> j9object_t instance = _objectAllocate.inlineAllocateIndexableObject(_currentThread, arrayClass, (U_32)size);
			if (NULL == instance) {
				updateVMStruct(REGISTER_ARGS);
----> instance = _vm->memoryManagerFunctions->J9AllocateIndexableObject(_currentThread, arrayClass, (U_32)size, J9_GC_ALLOCATE_OBJECT_INSTRUMENTABLE);
				VMStructHasBeenUpdated(REGISTER_ARGS);
				if (J9_UNEXPECTED(NULL == instance)) {
					rc = THROW_HEAP_OOM;
					goto done;
				}
			}
			_pc += 2;
			*(j9object_t*)_sp = instance;
		}
```

**Comment by dmitripivkine** [comment]
If crash still occur in GC this no surprise on top level it can be traced to object allocation. The failure an attempt to allocate is a trigger to GC.

**Comment by dmitripivkine** [comment]
Do we have any native debugger for RISC-V? Would be nice to have c-stack and registers for 2-3 frames before crash (for both cores)

**Comment by ChengJin01** [comment]
> Do we have any native debugger for RISC-V? Would be nice to have c-stack and registers for 2-3 frames before crash (for both cores)

@dmitripivkine , the current environment is set up on `Fedora_stage4`, which has no gdb (no package offered for this version / I used to compile a gdb debugger from the FSF source but it doesn't work well to show the native stacktraces).  The gdb on `Fedora_rawhide` works/should be sufficient to show the native stacktraces (but can't be debugged with single step for some reason).

I already requested @sxa to set up another environment on `Fedora_rawhide` to see whether the crash can be reproduced out there. If so, I can create a debug build to see how it goes in gdb.

**Comment by dmitripivkine** [comment]
Ok, thank you. In one of cores I can guess (more or less) where it crashed but have no idea why. It is very different than usual crashes in GC. Another unusual thing is that according trace points crashed thread continues operations for a while. Crashed early in Scavenger thread was available (at least on sync points) and GC cycle / Exclusive has been completed successfully

**Comment by ChengJin01** [comment]
> ... Another unusual thing is that according trace points crashed thread continues operations for a while. Crashed early in Scavenger thread was available (at least on sync points) and GC cycle / Exclusive has been completed successfully.

@dmitripivkine , yes this is how the test works: 
1) at first, the jenkins agent is launched on `Fedora_stage4 ` to connect with the remote website and is waiting out there for further operations from the website after successful connection.
2) then we press the "Build Now" button on the website for the test job, in which case the VM crashes in GC during the connection.

So the problem happens when the building job gets started while the VM on `Fedora_stage4` has been there for a while.

**Comment by dmitripivkine** [comment]
I have very strong suspicion that crash in Scavenger occur an attempt to copy object very first time. And most likely it is the same for very first crash in this item. I don't see actual reason at the moment - related GC structures looks correct.

**Comment by dmitripivkine** [comment]
@ChengJin01 The is bizarre thing, but I start look to content of registers at the moment of crash and I see familiar references to `LargeObjectAllocateStats.cpp`. This immediately associates with logarithm calculation function. And as you remember we use to have problem with this using simulator. Would you please dig in this direction? Is an alternative on RISC-V to calculate it (for example command vs. system library call)? We use to have problem with saving/restoring Float Point registers on OS context switching in the past. Can it be a similar problem? Should something extra to be configured for the run?

**Comment by ChengJin01** [comment]
Talked to @dmitripivkine offline. We might as well to try to comment out the invocation of `log` (system call) for Large Objects Stats Allocation (needs @LinHu2016 help with this) to see how it goes with the hack.

**Comment by ChengJin01** [comment]
@dmitripivkine & @LinHu2016,
1) I checked the cross-build on the remote `Fedora_raw/QEMU` and there was no crash when attempting to run the test job (there was missing -C with `tar` when decompressing the downloaded jdk which should be fixed in the test script)

2) with `GCExtensionsBase.hpp line 1395 , processLargeAllocateStats(false) /* turn off processLargeAllocateStats by default */
`,  the cross-build with the patch from @LinHu2016 worked good on the remote F`edora_stage4/QEMU` and ended up with the same result as on `Fedora_raw/QEMU`
```
[chengjin@stage4 will-riscv-openj9-test]$ ls -l
total 238040
-rw-rw-r--  1 chengjin chengjin 243495880 May 12 23:11 riscv-jdk11.2005122310.tar.gz
drwxrwxr-x  2 chengjin chengjin      4096 May 15 19:59 test_jdk

[chengjin@stage4 will-riscv-openj9-test]$ tar -xzf riscv-jdk11.2005122310.tar.gz
[chengjin@stage4 will-riscv-openj9-test]$ jdk/bin/java -version
openjdk version "11.0.8-internal" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8-internal+0-adhoc.jenkins.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-8ce5570c6, JRE 11 Linux riscv-64-Bit Compressed References 20200512_49 (JIT disabled, AOT disabled)
OpenJ9   - 8ce5570c6
OMR      - ac5f4ec2c
JCL      - 302b1b522a based on jdk-11.0.8+1)
```

3) with `GCExtensionsBase.hpp line 1395 , processLargeAllocateStats(true) /* turn on processLargeAllocateStats by default */
`,  the cross-build with the same patch also ended up with the same result as  2)

So it seems the crash issue was pretty much caused by the calculation of `log `function in GC.

**Comment by dmitripivkine** [comment]
> So it seems the crash issue was pretty much caused by the calculation of log function in GC.

Seems crash relates (intermittently) with system library call of 'log()' from GC code

**Comment by ChengJin01** [comment]
@dmitripivkine & @LinHu2016,  
Even though the problem was only detected on `Fedora_stage4 `(never occurred on `Fedora_raw`), it is hard to determine whether the `log() ` call literally works correctly on `Fedora_raw `(probably still ended up with wrong value but never went out of the scope).  Given that this type of Linux-based OS is brand-new and might be not quite mature as compared to other platforms, it is difficult to convince the Fedora/RISC-V developers unless there is strong evidence to prove the value of log() goes wrong in some case (Do we have a simple example to verify the result on Fedora?)

Under such circumstance,  I am wondering whether there is way around or approach specific to RISC-V at this point in case something similar occurs in GC on Fedora_raw or other RISC-V OS in the near future.

**Comment by dmitripivkine** [comment]
'log()' calculation is a fundamental part of system library. I don't see any reason we should modify correct code to have "workaround" for bogus environment

**Comment by dmitripivkine** [comment]
>unless there is strong evidence to prove the return value of log() goes wrong in some case

Thread crashed an attempt to *call* system library with PC `NULL` or garbage. It is hard to tell about "wrong" value in this case

**Comment by ChengJin01** [comment]
Just talked to @dmitripivkine, to rule out the possibility with the cross-compilation, I will generate a build directly on stage4/QEMU to see whether how it goes. If it still crashes on GC in the same way, then the crash has nothing to do with the cross-compilers.

**Comment by dmitripivkine** [comment]
We can disable Large Object Allocation Stats feature for RISC-V platform. This might be inconvenient as any exception but doable. 
However this is direct violation of c++ spec requirements. By tolerating this we don't know what failed next. sqrt()? exp()? Is this problem limited to math functions only or it is wider?
And what is most scary that intermittence of the problem. If I am understanding problem correctly there were number of `log()` calls at the time of initialization of these classes - with success (@LinHu2016 - is it correct?). And failure with broken dynamic link looks like connectivity issue - and fundamentally much worse than "returning wrong value for log()". 
If it is a case disabling GC feature is not a solution just postponing of the problem to the future with potential wasting resources for hard debugging.
Another possibility we can check can we find some workaround at compilation stage. For example is it possible to "inline" system functions (like embedder do for "stand-alone" image)? Any other compilation options?

**Comment by dmitripivkine** [comment]
After discussion with @ChengJin01 and reading compiler manual we decided we can try two experiments:
- use `__builtin_logf()` instead `logf()`
- use `log()` (ISO C90 function) instead of `logf()` (ISO C99 function) (based on idea there is no problem (?) with `sqrt()` - also ISO C90 function)

**Comment by LinHu2016** [comment]
> We can disable Large Object Allocation Stats feature for RISC-V platform. This might be inconvenient as any exception but doable.
> However this is direct violation of c++ spec requirements. By tolerating this we don't know what failed next. sqrt()? exp()? Is this problem limited to math functions only or it is wider?
> And what is most scary that intermittence of the problem. If I am understanding problem correctly there were number of `log()` calls at the time of initialization of these classes - with success (@LinHu2016 - is it correct?). And failure with broken dynamic link looks like connectivity issue - and fundamentally much worse than "returning wrong value for log()".
> If it is a case disabling GC feature is not a solution just postponing of the problem to the future with potential wasting resources for hard debugging.
> Another possibility we can check can we find some workaround at compilation stage. For example is it possible to "inline" system functions (like embedders do for "stand-alone" image)? Any other compilation options?

yes, there are a couple of log() calls at the jvm initialization, also base on javacore the crash was happened at no. 1xx local GC(did not crash at first GC), the crash might be sensitive about the value of argument.

**Comment by LinHu2016** [comment]
> After discussion with @ChengJin01 and reading compiler manual we decided we can try two experiments:
> 
>     * use `__builtin_logf()` instead `logf()`
> 
>     * use `log()` (ISO C90 function) instead of `logf()` (ISO C99 function) (based on idea there is no problem (?) with `sqrt()` - also ISO C90 function)

we might not try to use log() instead of logf(), because we had the issue also on risc-v, which log(double arg) return wrong result, when the arg are the certain sizes.

**Comment by dmitripivkine** [comment]
> we might not try to use log() instead of logf(), because we had the issue also on risc-v, which log(double arg) return wrong result, when the arg are the certain sizes.

I believe the problem was use `log()` with float argument. If, for example as a test, we change all related variable types to `double` it should work.

**Comment by LinHu2016** [comment]
In https://github.com/eclipse/omr/pull/4812, we replaced log() pow() with logf() powf(), due to the issue on OpenEmbedded(for risc-v), which log(double) in line 1100 0f LargeObjectAllocateStats.cpp returned wrong value for the specific argument. I am afraid that using log(double) might cause the problem on  OpenEmbedded(for risc-v) in future.

**Comment by dmitripivkine** [comment]
> eclipse/omr#4812

Well, please try built in versions of functions first, like `__builtin_logf()`, and check does it check dynamic link problem.

**Comment by ChengJin01** [comment]
Currently the crash of the agent can not be reproduced on stage4 even with the failing cross-build previously compiled for some reason. @sxa will check with William tomorrow to see whether there is any change in the test environment.

**Comment by ChengJin01** [comment]
@sxa,    given that the agent on stage4 (after rebooting) is quite stable in downloading the required jdk from the remote site,  I will consider to close the issue for now as nothing can be determined out there due to these incomplete information.  We should keep an eye on this issue and reopen if the crash reoccurs next time. Or we can leave this open for a while if any.

**Comment by sxa** [comment]
Based on https://ci.adoptopenjdk.net/job/will-riscv-openj9-test/46/console the JVM is looking quite stable now, so I'm happy to close (I don't seem to have permissions to close it myself) :-)

**Comment by dmitripivkine** [comment]
Thank you
