### ISSUE TITLE
JEP 384 Records (second preview)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9529]
https://openjdk.java.net/jeps/384

**Comment by pshipton** [comment]
@DanHeidinga @theresa-m fyi

**Comment by theresa-m** [comment]
I don't believe there are any JVM changes required for this JEP.

**Comment by DanHeidinga** [comment]
We'll need to confirm OpenJ9 handles Reflection field writing operations correctly for Records - see https://github.com/eclipse/openj9/issues/9929
