### ISSUE TITLE
No item named Test_openjdk8_j9_sanity.functional_x86-64_linux_cm_OpenJDK8

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9534]
https://ci.eclipse.org/openj9/job/Pipeline_Build_Test_JDK8_x86-64_linux_cm/1094
```
23:51:35  Failed in branch sanity.functional
23:51:35  Failed in branch sanity.openjdk
```

**Comment by pshipton** [comment]
@AdamBrousseau We need to create some new jobs for OpenJDK8+ now that cmake sanity.functional and openjdk are enabled?

**Comment by AdamBrousseau** [comment]
Try again now. There was a change to the test script that required admin approval. It should work now.
https://ci.eclipse.org/openj9/view/Test/job/Test_Job_Auto_Gen/

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Pipeline-OpenJDK8-Acceptance/47/
