### ISSUE TITLE
Process is terminated before JVMTI event callback VMDeath completes

### ISSUE THREAD

**Issue by quijote** [eclipse/openj9#9558]
I noticed that our JVMTI agent sometimes did not properly shutdown when used together with IBM/OpenJ9 JVM.

I reproduced the problem with a simple JVMTI agent that just registers a VMDeath callback and then sleep for a second there before printing a message.

    static void VMDeath(jvmtiEnv *jvmti_env, JNIEnv* jni_env) {
        fprintf(stderr, "Enter VMDeath\n");
        std::this_thread::sleep_for(std::chrono::milliseconds(1000));
        fprintf(stderr, "Exit VMDeath\n");
    }

[IncompleteVmDeathReproducer.zip](https://github.com/eclipse/openj9/files/4627563/IncompleteVmDeathReproducer.zip)

VMDeath callback is not run to completion each time I run this agent together with the following Java code:

    public static void main(String[] args) throws Exception {
        final CountDownLatch latch = new CountDownLatch(1);
        Thread thread = new Thread() {
            public void run() {
                // Trigger VMDeath in main thread
                latch.countDown();
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                // Before VMDeath completes call System.exit
                System.exit(0);
            }
        };
        thread.setDaemon(true);
        thread.start();
        latch.await();
    }

This just prints

    Enter VMDeath

before process dies.

With Hotspot JVM I get the expected result:

    Enter VMDeath
    Exit VMDeath

**Comment by gacholio** [comment]
Looking at the code, System.exit() definitely wins over DestroyJavaVM. I'll see if I can determine the RI behaviour in this case (e.g. if the VMDeath handler blocks forever, does System.exit wait indefinitely?).

**Comment by gacholio** [comment]
The answer to the above is yes - if the handler blocks forever, the exit does not take place.
