### ISSUE TITLE
UNB network issues are preventing nightly testing

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9560]
This also affects testing during the day. Although it mostly works because of the reduced load, it's quite a bit slower to test on the UNB platforms.

Since the night of May 12th, we're not getting nightly coverage of the platforms tested at UNB: xlinux, mac, most plinux. The problems appear to be network related, related to github.com. I've included some stats below that @AdamBrousseau collected.

https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/906
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All-11/169
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-JDK14/104

- Transfer speeds on git fetch around 20KiB/s
- Affecting all UNB machines (x/p/osx) (OpenJ9 & OMR)
- Can pull Adopt binaries fine (Backed by amazonaws) 4MB/s
- Started Tuesday May 12 (Looking at OMR farm)
  - Last good build May 11 7:33pm
  - First bad build May 12 12:22pm (Still passed)
  - Even worse by 5:03pm (Timed out git clone after 10 minutes)
OpenJ9
x
- Good May 11 10:55am (4min to do full clones of openj9 and omr in get_sources.sh)
- Bad May 12 11:57am (18.5min for the same clones)
p
- Good May 11 8:46 am - 4min
- Bad May 12 11:57am - 19min
- Ugly May 13 2:37pm - 1 hour
osx
- Good May 11 6:06pm - 5min
- Bad May 12 11:57am - 18min
- Ugly May 13 1:04pm - 58min

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by pshipton** [comment]
I've disabled a number of machines at UNB, in the hopes the remaining machines will get more network time and be less likely to time out.

- cent6-x64-5 cent6-x64-6 cent6-x64-7 
- cent7-ppcle-5 cent7-ppcle-6
- osx1014-x86-1 osx1014-x86-2 osx1014-x86-3 
- ub16p8j91 ub16p8j92 ub16p8j93 ub16p8j94
- ub16x64j91 ub16x64j92 ub16x64j94 ub16x64j95 ub16x64j96 ub16x64j97 ub16x64j98
- ub18-ppcle-1 ub18-ppcle-2
- ub18-x86-1 ub18-x86-2

**Comment by pshipton** [comment]
I don't think disabling the machines made any difference, so I've brought them back online.

**Comment by pshipton** [comment]
Seems all the UNB machines have gone offline in jenkins at some point over the (long) weekend.

**Comment by AdamBrousseau** [comment]
I think there are 2 issues here. The first, worker-1, which is the proxy was offline because the slave.jar cannot be downloaded and therefore the slave cannot launch. When I run the curl by hand on the slave.jar it times out with `Could not resolve host: ci.eclipse.org`. I have downloaded the jar manually for now and the slave is back online. I think this ties back to the Eclipse issues I saw go through my email.

The UNB machines offline I believe is a second issue. I disconnected/reconnected the vpn but it will not connect. Can't even ping ping casa.cs.unb.ca. I've pinged the UNB folk again.

**Comment by AdamBrousseau** [comment]
I take that back, worker-1 just needed a reboot.

**Comment by pshipton** [comment]
Machines are online now, but all the builds at UNB still failed uploading to OSU `Failed to deploy file. Status code: 403`

**Comment by pshipton** [comment]
Artifactory issues are still blocking all builds. Adam is looking at it, says "something is wrong" with the Artifactory server.

**Comment by AdamBrousseau** [comment]
Worker had a bad entry for the localhost in /etc/hosts. All resolved now. UNB network issue is also resolved. I think this can be closed.
