### ISSUE TITLE
cmdLineTester_GCRegressionTests output cleanup

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#9569]
cmdLineTester_GCRegressionTests prints out a large amount of unnecessary output (In the example below, from iteration 1 to iteration 1057). We need to cleanup the output.

```
03:20:05  Testing: softwareRead  
03:20:05  Test start time: 2020/05/13 03:19:51 Eastern Standard Time
03:20:05  Running command: "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_cm_Nightly/openjdkbinary/j2sdk-image/bin/java"   -Xdump:system:none -cp "/Users/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_mac_cm_Nightly/openjdk-tests/TKG/../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" VMBench.GPTests.GPTest   softwareRead
03:20:05  Time spent starting: 18 milliseconds
03:20:21  Time spent executing: 60539 milliseconds
03:20:21  Test result: PASSED
03:20:21  Output from test:
03:20:21   [OUT] Calibrating live object array size...
03:20:21   [OUT] Set live object array size to 1922
03:20:21   [OUT] Command line to reproduce this run: com.ibm.tests.garbagecollector.TestClassLoaderMain 1922 50 -
03:20:21   [OUT] Allocating array (iteration 1)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 2)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 3)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 4)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 5)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 6)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 7)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 8)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 9)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Allocating array (iteration 10)
...
03:20:21   [OUT] Allocating array (iteration 1057)
03:20:21   [OUT] i=0
03:20:21   [OUT] i=1000
03:20:21   [OUT] Successful test run! (1057 iterations)
03:20:21  >> Success condition was found: [Output match: Successful test run!]
```
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_mac_cm_Nightly/3/consoleFull

https://github.com/eclipse/openj9/blob/6650475c2f0c9b3cf348b4c5baa0a0b466d1e1a9/test/functional/cmdLineTests/gcRegressionTests/src/com/ibm/tests/garbagecollector/TestClassLoaderMain.java#L132-L138

**Comment by gacholio** [comment]
The best solution would be to not capture the output on success (for any test, or perhaps set some kind of limit). Parse the output for the success tag, but don't put it in the console output.

**Comment by JCodyA** [comment]
Hello!  I've been looking at this and it may be a good task for me, but I'm a bit new to this.  I don't completely understand what the goal should be.  Should I edit the code so it doesn't output all the extra info and just the success tag at the end?  I noticed a few functions involved with the System.out calls.

**Comment by llxia** [comment]
Thanks for helping @JCodyA !

According to the [cmdlinetester](https://github.com/eclipse/openj9/blob/6650475c2f0c9b3cf348b4c5baa0a0b466d1e1a9/test/functional/cmdline_options_tester/src/TestSuite.java#L85), It looks like we can just remove `-verbose` in 
https://github.com/eclipse/openj9/blob/6650475c2f0c9b3cf348b4c5baa0a0b466d1e1a9/test/functional/cmdLineTests/gcRegressionTests/playlist.xml#L36

https://github.com/eclipse/openj9/blob/6650475c2f0c9b3cf348b4c5baa0a0b466d1e1a9/test/functional/cmdLineTests/gcRegressionTests/playlist.xml#L56

Could you give it a try? You can test the change locally or [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/). Thank you!

**Comment by JCodyA** [comment]
Sure thing!  I'll open a [WIP] pull request.

**Comment by llxia** [comment]
The issue is fixed in https://github.com/eclipse/openj9/pull/11712
