### ISSUE TITLE
jvmtitests_hcr_OSRG Selected VM [default] by option -Xnocompressedrefs does not exist.

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9579]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_ppc64le_linux_Nightly/375
cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_0
```
variation: Mode107-OSRG -Xnocompressedrefs
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation -Xnocompressedrefs 
Selected VM [default] by option -Xnocompressedrefs does not exist.
```

Caused by https://github.com/eclipse/openj9/pull/9551

**Comment by pshipton** [comment]
@llxia @smlambert

**Comment by llxia** [comment]
I will take a look

**Comment by llxia** [comment]
`Mode110-OSR ` runs on the same platform as `Mode110`. This is why `cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_1` (Mode110-OSRG -Xnocompressedrefs) got skipped as expected in above build.

`cmdLineTester_jvmtitests_hcr_OSRG_nongold_SE80_0` (above failed test) runs `Mode107-OSRG `. Should `Mode107-OSRG ` run on the same platform as `Mode107`? My assumption is yes, but this is not the case in ottawa.csv

In ottawa.csv, the values match do not match for linux_ppc-64_le and linux_ppc-64_cmprssptrs_le

|  | linux_ppc-64_le | linux_ppc-64_cmprssptrs_le  | 
|:-:|:-:|:-:|
| Mode107  |  yes |  no | 
| Mode107-OSRG | no  | yes  |

Is my assumption correct?

**Comment by llxia** [comment]
Some background info:
The test worked before because TKG added `-Xnocompressedrefs` or `-Xcompressedrefs` option as default based on SPEC. Since we removed this logic, jvm options in tests only depend on `<variation>`.  #9551 is to fix the issue where `Mode107-OSRG` does not contain `-Xnocompressedrefs` and this is needed for ibm SDK.

**Comment by pshipton** [comment]
Mode107-OSRG should be same platforms as Mode107 (i.e. XL), it's an error in the ottawa.csv.
While Mode 607* or 6xx* is the opposite.
