### ISSUE TITLE
Vanilla Minecraft tick time longer 5ms than hotspot

### ISSUE THREAD

**Issue by 1a2s3d4f1** [eclipse/openj9#9594]
Java -version output
--------------------
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Windows 7 amd64-64-Bit Compre
sed References 20200422_667 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5e623848e9 based on jdk8u252-b09)

Summary of problem
------------------
Running vanilla minecraft 1.15.2 on openj9 ,[tick time](https://minecraft.gamepedia.com/Tick) longer 5 ms than hotspot.

JVM option:
openj9:-Xmx1024M -Xms512M -Xjit:disableGuardedStaticFinalFieldFolding
hotspot -Xmx1024M -Xms512M -XX:+UseG1GC

![2020-05-16_09 48 52](https://user-images.githubusercontent.com/40121560/82109286-3d0e6280-9767-11ea-9a68-772cdab9457b.png)
Running on openj9:

![2020-05-16_09 54 37](https://user-images.githubusercontent.com/40121560/82109313-78109600-9767-11ea-8e22-1b1d872299f3.png)
openj9 30ms 
hotspot 25ms 
It is my jvm options problem?

Diagnostic files
----------------

get jit verbose log and gc log:
[verbosegc.20200516.095016.2412.txt](https://github.com/eclipse/openj9/files/4637766/verbosegc.20200516.095016.2412.txt)
[LogVerbos.20200516.095016.zip](https://github.com/eclipse/openj9/files/4637767/LogVerbos.20200516.095016.zip)

**Comment by KsRyY** [comment]
# My Testing Result
Prior Statment: All three tests below are the results after a 30s warmup, captured when standing still.

My Computer:
```
CPU: Intel Core i5-8265U @ 1.60GHz
GPU: Intel UHD Graphics 620
```

## OpenJ9 r0.20.0 (Java8)
`java -version` output:
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200422_667 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 5e623848e9 based on jdk8u252-b09)
```

JVM Option: `-Xjit:disableGuardedStaticFinalFieldFolding`

Screenshot:
![8u262_OpenJ9-r0.20.png](https://i.loli.net/2020/05/23/TZflGBmIANJonF5.png)

## OpenJ9 Nightly (about a week or so ago)
`java -version` output:
```
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-202005121838-b02)
Eclipse OpenJ9 VM (build master-c14f6b26e, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200512_688 (JIT enabled, AOT enabled)
OpenJ9   - c14f6b26e
OMR      - cd259de5a
JCL      - 4dcdf539 based on jdk8u262-b02)
```

JVM Option: None.

Screenshot:
![8u262_OpenJ9-Nightly.png](https://i.loli.net/2020/05/23/RZMo4j7W5e1ug6S.png)

## HotSpot
`java -version` output:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

JVM Option: None.

Screenshot:
![8u251_HotSpot.png](https://i.loli.net/2020/05/23/GHFspkMUCoj6BIz.png)

## Result
The average MSPT of all three tests is about 11ms, all with small fluctuation. I can't reproduce your problem.

**Comment by 1a2s3d4f1** [comment]
now  I can't reproduce this problem
