### ISSUE TITLE
Openj9 jdk8 web site build instructions have broken links

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9#9603]
The eclipse/openj9 instructions for building jdk8 (https://www.eclipse.org/openj9/oj9_build.html#version-8) have broken links to dockerfiles.

Should the instructions should now instruct people to use https://github.com/eclipse/openj9/blob/master/buildenv/docker/mkdocker.sh?

**Comment by pshipton** [comment]
This is reported here https://github.com/eclipse/openj9-website/issues/250
I expect the problem updating the website is that switching to the [new website](https://eclipse.github.io/openj9-website/) is imminent. The new website doesn't contain build instructions.
