### ISSUE TITLE
Enable SelfTuningScratchMemoryUsageBeforeCompile when there is no swap space

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#9616]
When `enableSelfTuningScratchMemoryUsageBeforeCompile` option is enabled the JIT looks at the amount of free physical memory at the beginning of a compilation and sets a limit for the scratch memory (the amount of memory a compilation thread is allowed to use) slightly less than the amount of physical memory. When a compilation tries to use more than its allotted limit, the JIT aborts that compilation and retries it at a lower optimization level. 
When the machine has swap space enabled, even though there is not enough physical memory, compilations can still use a lot of memory because of the swapping mechanism. Thus, while safer, `-Xjit:enableSelfTuningScratchMemoryUsageBeforeCompile` could make many compilations to be downgraded, resulting in lower throughput in the long run. This is why this option is not enabled by default. 
However, with swap disabled, using `enableSelfTuningScratchMemoryUsageBeforeCompile` is probably a good idea and it will reduce/eliminate the cases when the JVM (or container the JVM is running in) is killed because of a native OOM. 
All I need is a way to detect from inside the JVM whether or not swap is enabled on the machine.

See #4050 for more details on this issue.

**Comment by mpirvu** [comment]
Attn: @ashu-mehra, since you have more experience with information that can be extracted from a cgroup.

**Comment by edrevo** [comment]
Another (proably easier) option would be to include this self tuning option if -Xtune:virtualized is set, since disabling swap is something common in container environments.

**Comment by ashu-mehra** [comment]
`omrsysinfo_get_memory_info` provides swap information and it seems to be retrieving swap memory in the container as well.

https://github.com/eclipse/omr/blob/4712be2311a0625625bdc48d75d2589b1bfab312/include_core/omrport.h#L603-L604
https://github.com/eclipse/omr/blob/4712be2311a0625625bdc48d75d2589b1bfab312/port/unix/omrsysinfo.c#L2576
https://github.com/eclipse/omr/blob/4712be2311a0625625bdc48d75d2589b1bfab312/port/unix/omrsysinfo.c#L2707-L2719

**Comment by pwagland** [comment]
Thanks for implementing this. Is there any way to see if this has worked, that is, is there any way to print out the options currently in use? Either from code, or from the command line?

**Comment by mpirvu** [comment]
@pwagland You can generate a verbose log by providing the following command line options `-Xjit:verbose={compilePerformance},vlog=/tmp/vlog.txt`. The verbose log includes (among other things) lines for compilation starts and compilation ends. Example:
```
 (cold) Compiling sun/reflect/Reflection.getCallerClass()Ljava/lang/Class;  OrdinaryMethod j9m=000000000004E6D8 t=0 compThreadID=0 memLimit=262144 KB freePhysicalMemory=281 MB
+ (cold) sun/reflect/Reflection.getCallerClass()Ljava/lang/Class; @ 00007F08D7A3403C-00007F08D7A34167 OrdinaryMethod - Q_SZ=1 Q_SZI=1 QW=2 j9m=000000000004E6D8 bcsz=2 JNI time=610us mem=[region=704 system=16384]KB compThreadID=0 CpuLoad=13%(1%avg) JvmCpu=0%
```
```
 (warm) Compiling java/lang/Long.parseLong(Ljava/lang/String;I)J  OrdinaryMethod j9m=000000000006C3A0 t=46517 compThreadID=1 memLimit=96627 KB freePhysicalMemory=98 MB
+ (warm) java/lang/Long.parseLong(Ljava/lang/String;I)J @ 00007F08D8990220-00007F08D8991E95 OrdinaryMethod C Q_SZ=5 Q_SZI=0 QW=80 j9m=000000000006C3A0 bcsz=272 OSR time=157166us mem=[region=8576 system=16384]KB compThreadID=1 CpuLoad=375%(46%avg) JvmCpu=413%
```
The two sets shown above contain two events each: one compilation start and one compilation end (the latter starts with a `+` sign). The information you are looking for is present in the compilation start line. For the first set we see `memLimit=262144 KB freePhysicalMemory=281 MB`. Because there is enough free memory available the compilation is allowed to use 262144KB=256MB of memory (this is the default). The second set was collected later into the run and the amount of free memory available to the container has decreased: `freePhysicalMemory=98 MB`. In this case the JIT will lower the cap on memory it can use to `memLimit=96627 KB`
