### ISSUE TITLE
JEP 383 Foreign-Memory Access API (Second Incubator)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9625]
https://openjdk.java.net/jeps/383

**Comment by pshipton** [comment]
@DanHeidinga fyi

**Comment by DanHeidinga** [comment]
@babsingh can you take a look at this?  There's some changes since the previous incubation of this feature

**Comment by babsingh** [comment]
> can you take a look at this?

yes ... already working on it.

**Comment by babsingh** [comment]
This issue can be closed. JEP383 is complete. Related pull requests: https://github.com/eclipse/openj9/pull/9697, https://github.com/eclipse/openj9/pull/9865, https://github.com/eclipse/openj9/pull/10239, https://github.com/eclipse/openj9/pull/10274, https://github.com/eclipse/openj9/pull/10400, https://github.com/eclipse/openj9/pull/10402 and https://github.com/ibmruntimes/openj9-openjdk-jdk15/pull/11.
