### ISSUE TITLE
JEP 360 Sealed Classes (Preview)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9626]
https://openjdk.java.net/jeps/360

**Comment by pshipton** [comment]
@tajila @DanHeidinga fyi

**Comment by tajila** [comment]
Here are some draft specs:
http://cr.openjdk.java.net/~dlsmith/jep360/jep360-20200421/specs/sealed-types-jls.html
http://cr.openjdk.java.net/~dlsmith/jep360/jep360-20200421/specs/sealed-types-jvms.html

The main JVM change is the `PermittedSubtypes` class attribute. This attribute contains a list of permitted subtypes. When loading a class, if that class has a supertype that contains the `PermittedSubtypes` attribute, then the current class must be in that list or ICCE is thrown.

There are some spec changes here, http://cr.openjdk.java.net/~dlsmith/jep360/jep360-20200421/specs/class-loading-jvms.html, that dont seem directly related to this JEP, but may have been proposed as a result of it.

**Comment by DanHeidinga** [comment]
@theresa-m did the initial review on the specs for me and indicated there was nothing concerning in the specs.

We'll have to connect out side the issue to see who can pick up this JEP

**Comment by theresa-m** [comment]
I can pick this up.

**Comment by theresa-m** [comment]
A list to help me keep track of this work:

**VM changes:**
- [ ] PermittedSubtypes attribute
  - [ ] If ACC_FINAL is not set, there should not be a permittedSubclasses attribute
- [ ] New classloading restrictions
- [ ] Class redefinition mods
- [ ] cfdumper (ClassFileWriter, main, romclasswalk)

**JCL support:**
- [ ] new java.lang.Class method: java.lang.constant.ClassDesc[] getPermittedSubclasses()
- [ ] new java.langClass method: boolean isSealed()

**Testing:**
- [ ]  functional tests for new java.lang.Class methods (set --enable-preview in build/playlist files)
- [ ] class file verification
- [ ] class loading tests
- [ ] cfdumper tests

**Comment by theresa-m** [comment]
Are there any more recent specs for this? When verifying against the RI it seems that the naming has changed (PermittedSubtypes is now PermittedSubclasses).

**Comment by pshipton** [comment]
See http://cr.openjdk.java.net/~iris/se/15/latestSpec/java-se-15-annex-3.html

**Comment by theresa-m** [comment]
All vm changes for this JEP are merged. The final pull request for DDR support will likely be open slightly after the August 9th code split.

**Comment by DanHeidinga** [comment]
@theresa-m has the DDR sealed classes PR been opened?

**Comment by theresa-m** [comment]
Not yet. I will finish it up this week.
