### ISSUE TITLE
Accelerate getStringUTF8Length for compressed strings

### ISSUE THREAD

**Issue by fjeremic** [eclipse/openj9#963]
While investigating a profile of a webserver workload `getStringUTF8Length` seem to bubble to the top of the VM module. Taking a look at the implementation:

https://github.com/eclipse/openj9/blob/e49c539beff43c6d4f8dea3ab5f39eaaa5e86c2e/runtime/vm/stringhelpers.cpp#L440-L459

It appears there is room for improvement here. Looking at the disassembly for the function in the profile (won't paste here as it's quite large) it seems even for the compressed String case we do checks against length 2 and length 3 UTF8 surrogates. This is unnecessary.

I suspect the reason for this is because the parameter type is `U_16` so we zero extend the byte we load and the compiler couldn't optimize it. To fix this we simply need an `I_8` version of `encodedUTF8Length` witch simplified logic.

**Comment by pshipton** [comment]
Agreed the check could be simpler but even for compressed strings 0x00 and > 0x7f still needs 2 bytes

**Comment by fjeremic** [comment]
> Agreed the check could be simpler but even for compressed strings 0x00 and > 0x7f still needs 2 bytes when encoded in modified utf8.

Unfortunate side-effect. I will continue to dig. Perhaps there are places where we don't really need UTF8 explicitly and can get away with ISO-8859-1. In such cases compressed Strings don't need the 0x00 and 0x7F checks. I haven't seen those pop up in profiles though yet so I can't tell if this is worth the investment.
