### ISSUE TITLE
AIX jdk11 jtreg java/lang/ProcessBuilder/Basic_id0: environment contains "MALLOCOPTIONS=multiheap,considersize"

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#9640]
Failure link
------------
J9 is adding MALLOCOPTIONS=multiheap,considersize, to system LIBPATH, which this test checks.
If this is correct, then we will need to patch the test:
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/66/console
```
'LIBPATH=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/jli:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/../lib:/usr/lib:/usr/lib,MALLOCOPTIONS=multiheap,considersize,'< not equal to 'LIBPATH=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/server:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/lib/jli:/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64_aix/openjdkbinary/j2sdk-image/../lib:/usr/lib,'
```

**Comment by pshipton** [comment]
It's not correct. MALLOCOPTIONS should be added to the environment, but not the LIBPATH.

**Comment by pshipton** [comment]
This was spotted earlier in https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64_aix_Nightly/36

**Comment by pshipton** [comment]
I don't think MALLOCOPTIONS is in the LIBPATH, it's just in the environment, which is correct behavior. We added this intentionally, https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/287

**Comment by pshipton** [comment]
The test creates an empty environment, adds the LIBPATH, and expects the child process to only contain the same LIBPATH. However it also contains the MALLOCOPTIONS since that is set by the JDK.

@andrew-m-leonard you mentioned patching the test. Why would this one get patched when many others have been excluded instead?

**Comment by andrew-m-leonard** [comment]
> The test creates an empty environment, adds the LIBPATH, and expects the child process to only contain the same LIBPATH. However it also contains the MALLOCOPTIONS since that is set by the JDK.
> 
> @andrew-m-leonard you mentioned patching the test. Why would this one get patched when many others have been excluded instead?
@pshipton 
Probably because I wasn't thinking what I was saying! :-) However, the test in question the processBuilder.Basic, (https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/d6ccd89fcb7d919ffa2949b82ff0dec305f6f1a8/test/jdk/java/lang/ProcessBuilder/Basic.java)
Performs many many tests under this single testcase, so excluding it will exclude just about all the ProcessBuilder testing... as you can see it's a very big test...
So if a single simple patch is possible we could, but i'm happy if you want to just exclude...?

**Comment by pshipton** [comment]
I'm good to patch it to keep the test running. I was just wondering your reasoning.

**Comment by DanHeidinga** [comment]
@andrew-m-leonard is this something you can fix?  It would be good to get the test passing for v0.20.0

**Comment by andrew-m-leonard** [comment]
@DanHeidinga presume you mean for v0.21.0?

**Comment by DanHeidinga** [comment]
Yes, typo on my part

**Comment by andrew-m-leonard** [comment]
@DanHeidinga 
> @andrew-m-leonard is this something you can fix? It would be good to get the test passing for v0.21.0

MALLOCOPTIONS issue fixed: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/310

..however, the test still fails due to a different issue: https://github.com/eclipse/openj9/issues/8504
This is the last failure.. as Simon mentioned if the openj9 code can simply check if /usr/lib is already in the LIBPATH it would fix the problem.

**Comment by DanHeidinga** [comment]
I pulled together a PR to address this https://github.com/eclipse/openj9/pull/9814

**Comment by pshipton** [comment]
The PR addresses #8504. Since this issue has been fixed, closing it.
