### ISSUE TITLE
sigquit not handled after Apache Kafka installs handlers for TERM, INT and HUP

### ISSUE THREAD

**Issue by smithwil** [eclipse/openj9#9654]
SIGQUIT is often used to ask the JVM to take a javacore or other
dumps.

Apache Kafka has some code that installs signal handlers for signals TERM, INT and HUP, but not QUIT.

https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/LoggingSignalHandler.java

With earlier J9 versions, Apache Kafka users could still send sigquit
to the J9 JVM to request dumps, and it was handled as a "user" dump event.
With the latest AdoptOpenJDK 8, the sigquit is not handled and this
way of requesting dumps no longer works.

The Apache Kafka signal handler set up code has been copied into a
small standalone testcase that recreates this issue.

Issue is seen with:

openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200427_544 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 6a92a55d72 based on jdk8u252-b09)

Issue was also seen with the above version, on Linux x86 64-bit.

Issue was NOT seen with:

openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190205_147 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)

Recreate instructions - see attached testcase source:

[LoggingSignalHandler.java.txt](https://github.com/eclipse/openj9/files/4669327/LoggingSignalHandler.java.txt)
[Main.java.txt](https://github.com/eclipse/openj9/files/4669328/Main.java.txt)

javac Main.java
javac LoggingSignalHandler.java
java Main &      ### program runs in background -- note the PID
kill -3 <pid>    ### use pid reported on console in previous step

Result: the sigquit sent by kill command is not handled, no dump event
is process by the J9 JVM

Expected behaviour:  JVMDUMP039I Processing dump event "user"... and
JVM produces a javacore dump. Older AdoptOpenJDK 8 builds do produce
the dump as expected, but the latest version reported above does not
handle the quit signal.

Clearly the signal handler set up code is using reflection to access
sun.misc classes and this is not part of the Java API. However, it is
done by Apache Kafka, which is widely used, and it used to work.

**Comment by smithwil** [comment]
a similar issue was fixed before in #1984

**Comment by pshipton** [comment]
@babsingh fyi

**Comment by babsingh** [comment]
https://github.com/eclipse/omr/pull/5269 is supposed to fix this issue. It was merged in OMR yesterday. It still needs to promote to [openj9-omr's openj9 branch](https://github.com/eclipse/openj9-omr/commits/openj9) before it becomes available in the Adopt builds. I will notify again when the fix is available in the Adopt builds. At that point, I will request @smithwil to validate the fix and close this issue.

**Comment by pshipton** [comment]
The omr change has promoted.

**Comment by babsingh** [comment]
@smithwil The fix is available in [OpenJ9 nightly builds](https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9) (7 June 2020 ++). Can you please verify the fix and close this issue?

**Comment by smithwil** [comment]
Verified with OpenJDK8U-jre_x64_linux_openj9_2020-06-09-04-56.tar.gz nightly build.

This build successfully produced a javacore triggered by `kill -3 <pid>` when running the testcase attached to this issue.

**Comment by dnwe** [comment]
@babsingh / @smithwil is it feasible to have the testcase included in the openj9 regression suite so this is asserted each release going forward?

**Comment by babsingh** [comment]
@smithwil @dnwe To catch the failures reported here, the new tests were added in the OMR sanity suite, via https://github.com/eclipse/omr/pull/5304. OpenJ9 is built on top of OMR, and OpenJ9 uses OMR's signal handling library. Those tests should be run regularly before new changes are ported from OMR to OpenJ9.

**Comment by dnwe** [comment]
@babsingh perfect, thank you!
