### ISSUE TITLE
jdk15 openjdk String/concat failures

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9656]
https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/204/
java/lang/String/concat/CompactStringsInitialCoder.java.CompactStringsInitialCoder
java/lang/String/concat/ImplicitStringConcat.java.ImplicitStringConcat
java/lang/String/concat/ImplicitStringConcatArgCount.java.ImplicitStringConcatArgCount
java/lang/String/concat/ImplicitStringConcatAssignLHS.java.ImplicitStringConcatAssignLHS
java/lang/String/concat/ImplicitStringConcatBoundaries.java.ImplicitStringConcatBoundaries
java/lang/String/concat/ImplicitStringConcatMany.java.ImplicitStringConcatMany
java/lang/String/concat/ImplicitStringConcatManyLongs.java.ImplicitStringConcatManyLongs
java/lang/String/concat/ImplicitStringConcatOrder.java.ImplicitStringConcatOrder
java/lang/String/concat/ImplicitStringConcatShapes.java.ImplicitStringConcatShapes
java/lang/String/concat/StringConcatFactoryInvariants.java.StringConcatFactoryInvariants
java/lang/String/concat/StringConcatFactoryRepeatedConstants.java.StringConcatFactoryRepeatedConstants
java/lang/String/concat/WithSecurityManager.java.WithSecurityManager

```
23:13:08  Caused by: java.lang.IllegalArgumentException: Illegal Lookup object - originated from java.lang.invoke: java.lang.invoke.StringConcatFactory$MethodHandleStringBuilderStrategy
23:13:08  	at java.base/java.lang.invoke.MethodHandles$Lookup.<init>(MethodHandles.java:156)
23:13:08  	at java.base/java.lang.invoke.MethodHandles$Lookup.<init>(MethodHandles.java:169)
23:13:08  	at java.base/java.lang.invoke.MethodHandles$Lookup.<init>(MethodHandles.java:177)
23:13:08  	at java.base/java.lang.invoke.MethodHandles.lookup(MethodHandles.java:2022)
23:13:08  	at java.base/java.lang.invoke.StringConcatFactory$MethodHandleStringBuilderStrategy.<clinit>(StringConcatFactory.java:1430)
```

**Comment by pshipton** [comment]
@JasonFengJ9 @DanHeidinga fyi

**Comment by DanHeidinga** [comment]
I'm surprised to see that works on Hotspot.  We deliberately introduced code to make that illegal.  I wonder when they removed it (and if they meant to?)

**Comment by DanHeidinga** [comment]
@andrew-m-leonard Can you ask about this on the OpenJDK mailing lists?  I'm surprised to see a lookup() object created for a privileged package and would have expected JDK15 to contain a check, like (based on our code) this:
```
if (lookupClass.getName().startsWith("java.lang.invoke.")) {
```

**Comment by JasonFengJ9** [comment]
Discussed with @DanHeidinga , excluding these tests while the investigation is pending.

**Comment by andrew-m-leonard** [comment]
@DanHeidinga @JasonFengJ9 I was trying to understand the problem, so ran these tests on latest, and the tests all pass now, so I think they have resolved the issue.

**Comment by DanHeidinga** [comment]
@andrew-m-leonard can you confirm that the equivalent of the check above that the Lookup isn't the `java.lang.invoke` package is still occurring for all Lookup constructors?

A question about it should be raised on the core-dev openjdk mailing list as it's a surprising change from previous releases that may have slipped thru.

**Comment by andrew-m-leonard** [comment]
Can you explain what this means, I don't understand where to look...?! the above stacktrace line numbers do not correlate to lines in MethodHandles.java
What method in MethodHandles do I need to look at?

**Comment by DanHeidinga** [comment]
MethodHandles.lookup() should call a MethodHandles$Lookup constructor that used to check and throw an if the lookupClass was in the `java.lang.invoke` package.  We need to know if that check has deliberately or accidentally removed.

**Comment by pshipton** [comment]
The test failures no longer occur.

**Comment by JasonFengJ9** [comment]
Note that the tests in question have been excluded. To run a grinder against these tests, a personal repo re-enabling them is required.

**Comment by JasonFengJ9** [comment]
@andrew-m-leonard could you verify latest JCL against https://github.com/JasonFengJ9/openjdk-tests/tree/enablestringconcat?

**Comment by pshipton** [comment]
There are a number of new failures now https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Personal/2/
```
13:53:01  test TestAdaptVarHandles.testBadCollectCoordinatesNegativePos(): failure
13:53:01  java.lang.AssertionError: java.lang.IllegalArgumentException: Illegal Lookup object - originated from java.lang.invoke: java.lang.invoke.MemoryAccessVarHandleGenerator
13:53:01  	at java.base/java.lang.invoke.MemoryAccessVarHandleGenerator.generateHandleFactory(MemoryAccessVarHandleGenerator.java:173)
13:53:01  	at java.base/java.lang.invoke.VarHandles.lambda$makeMemoryAddressViewHandle$0(VarHandles.java:331)
13:53:01  	at java.base/java.lang.invoke.VarHandles$$Lambda$36/0000000000000000.apply(Unknown Source)
13:53:01  	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
13:53:01  	at java.base/java.lang.invoke.VarHandles.makeMemoryAddressViewHandle(VarHandles.java:329)
13:53:01  	at java.base/java.lang.invoke.MethodHandleImpl$1.memoryAccessVarHandle(MethodHandleImpl.java:1807)
13:53:01  	at jdk.incubator.foreign/jdk.internal.foreign.LayoutPath.dereferenceHandle(LayoutPath.java:144)
13:53:01  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.lambda$varHandle$2(MemoryLayout.java:367)
13:53:01  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout$$Lambda$30/0000000000000000.apply(Unknown Source)
13:53:01  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.computePathOp(MemoryLayout.java:411)
13:53:01  	at jdk.incubator.foreign/jdk.incubator.foreign.MemoryLayout.varHandle(MemoryLayout.java:367)
13:53:01  	at TestAdaptVarHandles.testBadCollectCoordinatesNegativePos(TestAdaptVarHandles.java:367)
```


java/foreign/TestAdaptVarHandles.java.TestAdaptVarHandles
java/foreign/TestAddressHandle.java.TestAddressHandle
java/foreign/TestMemoryAccess.java.TestMemoryAccess
java/foreign/TestMemoryAlignment.java.TestMemoryAlignment
java/foreign/TestMemoryCopy.java.TestMemoryCopy
java/foreign/TestNative.java.TestNative
java/foreign/TestRebase.java.TestRebase
java/foreign/TestSegments.java.TestSegments
java/foreign/TestSharedAccess.java.TestSharedAccess
java/foreign/TestSlices.java.TestSlices
java/foreign/TestSpliterator.java.TestSpliterator
java/foreign/TestTypeAccess.java.TestTypeAccess
java/foreign/TestVarHandleCombinators.java.TestVarHandleCombinators

**Comment by pshipton** [comment]
> the above stacktrace line numbers do not correlate to lines in MethodHandles.java

OpenJ9 implements some of the classes like MethodHandles. 
https://github.com/eclipse/openj9/tree/master/jcl/src/java.base/share/classes/java/lang/invoke

The code in github contains java preprocessor directives, the files need to run through the preprocessor before the line numbers match up. It's easiest to look in the src.zip for files included there, otherwise 
- there is an Eclipse plugin that runs the processor on the code, or it can be done manually
- run the OpenJ9 build and find the preprocessed source in the intermediate files

**Comment by pshipton** [comment]
The OpenJ9 code doing the check is here, 
https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/invoke/MethodHandles.java#L197

**Comment by andrew-m-leonard** [comment]
MethodHandles.lookup() from java.lang.invoke priviledged class "bug" reported: https://bugs.openjdk.java.net/browse/JDK-8246281

**Comment by andrew-m-leonard** [comment]
Response from Mandy Chung (Oracle) : 
This change is intentional. java.lang.invoke.* classes are growing beyond the method handle machinery. Without the capability of creating Lookup object on java.lang.invoke, the only way is to use the all-power trusted lookup (IMPL_LOOKUP). Besides StringConcatFactory, j.l.invoke.InvokerBytecodeGenerator and MemoryAccessVarHandleGenerator classes create the lookup on itself and define the hidden classes. Lookup object on j.l.invoke class should not be leaked to untrusted code.

**Comment by DanHeidinga** [comment]
Thanks for following up on that.  I'll have to dig into the old internal issues to validate why it's OK to allow this access.

**Comment by DanHeidinga** [comment]
@JasonFengJ9 Has this been fixed in OpenJ9?  I recall discussions with you and Andrew about what was needed but don't see a PR attached to this issue and we're coming up on the code split

**Comment by JasonFengJ9** [comment]
@DanHeidinga I have a draft PR, will submit it for reviewing.

**Comment by adamfarley** [comment]
This looks like the same issue.

https://trss.adoptopenjdk.net/output/test?id=5f2b94ba0bec7975ae1294e4

Will hold off on excluding the test given the PR is about to go in.

**Comment by pshipton** [comment]
Unexcluded the tests via https://github.com/adoptium/aqa-tests/pull/4212
