### ISSUE TITLE
jdk15 sun/misc/UnsafeFieldOffsets.java Compilation failed

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9657]
https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/204/
sun/misc/UnsafeFieldOffsets.java
Compilation failed
```
13:25:46  /home/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_s390x_linux_Personal/openjdk-tests/openjdk/openjdk-jdk/test/jdk/sun/misc/UnsafeFieldOffsets.java:72: error: exception IllegalAccessException is never thrown in body of corresponding try statement
13:25:46          } catch (IllegalAccessException e) {
13:25:46            ^
```

**Comment by pshipton** [comment]
@JasonFengJ9 fyi

**Comment by pshipton** [comment]
Seems `MethodHandles.lookup().defineHiddenClass(bytes, true).lookupClass();` is expected to declare IllegalAccessException, so this is related to https://github.com/eclipse/openj9/issues/9328

**Comment by JasonFengJ9** [comment]
Will have a look.

**Comment by JasonFengJ9** [comment]
> Seems MethodHandles.lookup().defineHiddenClass(bytes, true).lookupClass(); is expected to declare IllegalAccessException

Did a quick try to throw `IllegalAccessException` when the caller `hasFullPrivilegeAccess()` returns false. The compilation finished but the test failed afterwards like other JEP 371 Hidden Classes tests https://github.com/eclipse/openj9/issues/9328.

Am going to exclude them after consulting with @hangshao0 .

**Comment by DanHeidinga** [comment]
> Am going to exclude them after consulting with @hangshao0 .

Are these tests ready to be re-included?  @hangshao0 @JasonFengJ9

**Comment by hangshao0** [comment]
> Are these tests ready to be re-included?

Not yet.

**Comment by hangshao0** [comment]
But they are already re-enabled by https://github.com/AdoptOpenJDK/openjdk-tests/pull/1925

**Comment by DanHeidinga** [comment]
Thanks @hangshao0.  I had missed that PR.  I guess the next question is - are they passing now?

**Comment by hangshao0** [comment]
>  are they passing now?

I don't think they are all passing now.

**Comment by JasonFengJ9** [comment]
> are they passing now?

`jdk15 sun/misc/UnsafeFieldOffsets.java` in this issue passes now as per `harness.trace` output:
```
2020-08-05T00:12:11-0400 Test starting: sun/misc/UnsafeFieldOffsets.java
2020-08-05T00:12:13-0400 Test finished: sun/misc/UnsafeFieldOffsets.java: Passed. Execution successful
```
@DanHeidinga  I think this issue can be closed.

Other hidden class related failures are related to https://github.com/eclipse/openj9/issues/9328, can be examined and raised when its implementation is complete.
