### ISSUE TITLE
Add ability and use reference repo for OpenJ9 and OMR

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9699]
When running a build, the openjdk repo clone uses a reference repo, but I don't see any reference repos used when cloning OpenJ9 and OMR. Cloning these takes considerably longer time than cloning openjdk with the reference repo. I didn't measure it, but on osx the openjdk clone seemed less than 20 sec, while the get_source printed 246 sec.

We could add support to specify references repos to the get_source.sh script, create them on the build machines, and specify them when calling the script.

`bash ./get_source.sh --openssl-version=1.1.1g -openj9-repo=https://github.com/eclipse/openj9.git -openj9-branch=master -openj9-sha=ed1de5d77a8c2fe017a352702ea33969cef6cfa5 -omr-repo=https://github.com/eclipse/openj9-omr.git -omr-branch=openj9 -omr-sha=d1bdd554528ed3f8f1263a8bfc0c930e680f251f`

**Comment by pshipton** [comment]
@AdamBrousseau @jdekonin

**Comment by AdamBrousseau** [comment]
#6744

**Comment by pshipton** [comment]
Closing this, added the infra tag to the existing Issue.
