### ISSUE TITLE
Create documentation about Shared classes cache and AOT compilation

### ISSUE THREAD

**Issue by deesebas** [eclipse/openj9#97]
Is there doc around -Xshareclasses and AOT compilation in OpenJ9? If not, can we reuse existing material to create these?

In general, it looks like OpenJ9 needs some sort of User Guide and documentation around how to use the various jvm (and possibly jit?) options (developers may not always want to look at the code to figure these out).

https://stackoverflow.com/questions/46343352/how-to-use-aot-compiler-in-openj9/46347665#46347665

**Comment by doveye** [comment]
Hi @deesebas. We've actually just separated out the doc for the J9 VM from the rest of the IBM SDK documentation - that will be the starting point for OpenJ9 users.

Intro page: https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/j9vm_reference.html
-Xshareclasses topic: https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.vm.9.0.doc/docs/xshareclasses.html
 General shared classes section (you might want to use the table of contents :) ): https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.vm.9.0.doc/docs/shrc.html

As the intro page says, the longer-term goal is for OpenJ9 doc in the community.

**Comment by deesebas** [comment]
Thanks @doveye!
