### ISSUE TITLE
cmdLineTester_SCHelperCompatibilityTests_win NoClassDefFoundError CustomPartitioningURLClassLoader$FoundAtIndex

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9707]
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0/1 - win2012r2-x86-1
cmdLineTester_SCHelperCompatibilityTests_win_0

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_windows_Nightly_testList_0/1 - win2012r2-x86-1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_x86-64_windows_Nightly_testList_0/1 - win2012r2-x86-1
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_sanity.functional_x86-64_windows_Nightly_testList_0/1 - win2012r2-x86-3
cmdLineTester_SCHelperCompatibilityTests_win_1
```
Testing: HelperCompatibilityTest 12
Test start time: 2020/05/26 22:15:19 Central Standard Time
Running command: "C:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0/openjdkbinary/j2sdk-image\\bin\\java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=HelperCompatibilityTests -Xbootclasspath/a:./Utils;. PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest -testfile "C:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0/openjdk-tests///..//jvmtest\functional\cmdLineTests\shareClassTests\SCHelperCompatibilityTests\props_win/Test11.props" -javacdir C:/Users/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-32_windows_Nightly_testList_0/openjdkbinary/j2sdk-image/bin
Time spent starting: 0 milliseconds
Time spent executing: 656 milliseconds
Test result: FAILED
 [ERR] Exception in thread "main" java.lang.NoClassDefFoundError: CustomClassloaders.CustomPartitioningURLClassLoader$FoundAtIndex
 [ERR] 	at CustomClassloaders.CustomPartitioningURLClassLoader.<init>(CustomPartitioningURLClassLoader.java:64)
 [ERR] 	at PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.executeTest(PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.java:128)
 [ERR] 	at PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.run(PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.java:113)
 [ERR] 	at PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.main(PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.java:52)
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]
```
Additional tests fail similarly.
Number of FAILED tests: 6 out of 33

**Comment by pshipton** [comment]
Although it appears to fail every time in the nightly, win32 failed in the OpenJDK8 acceptance build, but not win64. In the last OMR acceptance build, neither failed.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-32_windows_OpenJDK8_testList_0/1 - win2012r2-x86-4
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/1967

Changes between the nightly build and the previously working OMR acceptance build as follows.
https://ci.eclipse.org/openj9/job/Pipeline-OMR-Acceptance/1966/
https://github.com/eclipse/openj9/compare/0e0f9c0ba...8b12f595
https://github.com/AdoptOpenJDK/openjdk-tests/compare/6443697d...b1470c6c

Grinder to see if this failure can be repeated.
https://ci.eclipse.org/openj9/job/Grinder/880 - win2012r2-x86-2 - passed

@llxia any ideas what may have caused this? It seems to have been caused by introduction of parallel testing.

**Comment by pshipton** [comment]
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_windows_OpenJDK_testList_0/1
win2012r2-x86-1

**Comment by llxia** [comment]
I cannot reproduce this using parallel: https://ci.eclipse.org/openj9/job/Grinder/884/

@renfeiw can you take a look as well?

**Comment by llxia** [comment]
reran the build mentioned in https://github.com/eclipse/openj9/issues/9707#issuecomment-634810174
https://ci.eclipse.org/openj9/job/Test_openjdknext_j9_sanity.functional_x86-64_windows_OpenJDK_testList_0/2/

**Comment by renfeiw** [comment]
One possible reason that triggers the issue is the character limit issue, since the parallel build introduces longer build names than the regular one. 

Here is difference in commands for the test case HelperCompatibilityTest 12.

passed case:
```
Running command: "C:/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image\\bin\\java"  -Xjit -Xgcpolicy:gencon -Xnocompressedrefs  -Xshareclasses:name=HelperCompatibilityTests -Xbootclasspath/a:./Utils;. PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest -testfile "C:/Users/jenkins/workspace/Grinder/openjdk-tests///..//jvmtest\functional\cmdLineTests\shareClassTests\SCHelperCompatibilityTests\props_win/Test11.props" -javacdir C:/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin
``` 

failed case:
```
Running command: "C:/Users/jenkins/workspace/Test_openjdk14_j9_sanity.functional_x86-64_windows_Nightly_testList_0/openjdkbinary/j2sdk-image\\bin\\java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses:name=HelperCompatibilityTests -Xbootclasspath/a:./Utils;. PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest -testfile "C:/Users/jenkins/workspace/Test_openjdk14_j9_sanity.functional_x86-64_windows_Nightly_testList_0/openjdk-tests///..//jvmtest\functional\cmdLineTests\shareClassTests\SCHelperCompatibilityTests\props_win/Test11.props" -javacdir C:/Users/jenkins/workspace/Test_openjdk14_j9_sanity.functional_x86-64_windows_Nightly_testList_0/openjdkbinary/j2sdk-image/bin
```

**Comment by pshipton** [comment]
Not sure. The class `CustomClassloaders/CustomPartitioningURLClassLoader$FoundAtIndex.class` is actually slightly shorter than the test name `PartitioningURLClassPathHelperURLHelperStaleEntryCompatibilityTest.class`. If the test can be found, then FoundAtIndex should also work. The class file is there in the artifact.

However it does make sense this is the problem. The entire path is longer than 255 characters (262), and maybe there is a 255 char limit somewhere. We can rename the test to see if it helps.

I've created a commit to use shorter names, and if it's working I can try a fake Nightly build with it.
https://github.com/pshipton/openj9/commit/bdfa5b6

**Comment by pshipton** [comment]
My grinder worked, so I've started https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/207 which should appear as a Nightly build.

**Comment by pshipton** [comment]
The build passed so I've created the PR https://github.com/eclipse/openj9/pull/9721
