### ISSUE TITLE
Switch to default to CMake builds for JDK 11 on OSX

### ISSUE THREAD

**Issue by dnakamura** [eclipse/openj9#9709]
Issue for tracking imminent switch, to default to cmake on osx for jdk 11

Parent issue: #9195

PRs which perform the switch:
#9304
#9713
ibmruntimes/openj9-openjdk-jdk11#308

**Comment by pshipton** [comment]
As discussed on the OpenJ9 call today, we'd also like to introduce changes to the default.yml and the jenkins code to have another type of osx build that doesn't use cmake. We'd leave the default "osx" build as-is to switch to cmake via https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/308, but add another build like "osxncm" that disables cmake.

**Comment by dnakamura** [comment]
@pshipton  Implemented via #9713. ALthough the build is `osxuma` to avoid visual similarity to `osxcm`

**Comment by keithc-ca** [comment]
All the linked PRs have been merged: closing.
