### ISSUE TITLE
Convert OMR Acceptance build to use new Jenkins Pipeline Code

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#972]
[Pipeline-OMR-Acceptance](https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/)
Related #660 

Currently the code is in the groovy sandbox in the job config. Should be relatively straight forward to add a Jenkins file that reuses the new code.

**Comment by AdamBrousseau** [comment]
The existing OMR Acceptance build tests JDK9 sanity, when I add the pipeline code for this do we want 8 or 9 or both? @pshipton @DanHeidinga

**Comment by pshipton** [comment]
+1 for both, as we don't want omr updates to break either one.

**Comment by DanHeidinga** [comment]
Will the 8 & 9 builds be run in parallel or serially?  If parallel, I concur with Peter (assuming we have sufficient machines to keep build times to a reasonable length of time)

**Comment by AdamBrousseau** [comment]
Parallel

**Comment by AdamBrousseau** [comment]
Now that we have stable 10 sanity builds, do we want to add 10 to the OMR acceptance build or replace 9 with 10? We usually only run 2-3/day (every OMR PR merge). The current builds (z/p JDK9) usually take about 2 hours. @DanHeidinga @pshipton

**Comment by DanHeidinga** [comment]
As JDK9 is already out of support, we should be transitioning our builds to do both 8 & 10.

**Comment by AdamBrousseau** [comment]
Done.
