### ISSUE TITLE
Remove PUBLIC_BUILD macros in JIT

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/openj9#9729]
As far as I can tell, `PUBLIC_BUILD` is not defined anywhere in JIT builds (it is a historical macro that predates open-sourcing this code).  This macro should be removed from the code base and code folded assuming it is **NOT** defined.

**Comment by alexey-anufriev** [comment]
@0xdaryl, I have done a PR with requested changes, hopefully it meets the requirements.
