### ISSUE TITLE
jdk8 ProcessorMXBean is not a properly installed MXBean

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9733]
As we are getting closer to publishing javadoc (https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/414) which will include it, we should consider what to do about com.ibm.lang.management.ProcessorMXBean. Probably just delete the code.

This is not a properly installed MXBean, it's not included in com.ibm.java.lang.management.internal.ManagementUtils. This class is available in jdk8 only, excluded in higher versions. The implementation was never approved as something the project wanted to support, and the implementation was never completed.

The code is directly callable via `new com.ibm.lang.management.internal.ProcessorMXBeanImpl()`, but otherwise I don't think it can be used. It provides the following APIs:

getNumberPhysicalCPUs()
getNumberOnlineCPUs()
getNumberBoundCPUs()
getNumberTargetCPUs()
setNumberActiveCPUs()

**Comment by pshipton** [comment]
@DanHeidinga fyi

**Comment by DanHeidinga** [comment]
I'm OK with deleting it.  Those are interesting apis but we need to add them in a way that's tested and supported.  The current ProcessorMXBean isn't the right way
