### ISSUE TITLE
Add timeout blocks to JenkinsFiles

### ISSUE THREAD

**Issue by AdamBrousseau** [eclipse/openj9#974]
Sometimes builds hang for various reasons. We should add timeout blocks to either an entire build or per stage so that things aren't running longer than they should and require manual cancelling.

**Comment by vsebe** [comment]
> 1. Do we wrap low level build steps or higher level steps or both 
I would prefer at a higher level. The get source has indirectly timeout for git commands.

**Comment by vsebe** [comment]
@smlambert restricting sanity and extended test pipeline builds to 8 hours.

**Comment by AdamBrousseau** [comment]
Here is an example of a random hang that I cannot explain. This one happened outside of the timeout blocks that were added
https://ci.eclipse.org/openj9/view/Sandbox/job/PullRequest-Sanity-JDK10-linux_390-64_cmprssptrs-OpenJ9/24/console
```
Using variables file: buildenv/jenkins/variables/defaults.yml
[Pipeline] readYaml
[Pipeline] echo
Using OPENJDK_REPO = https://github.com/ibmruntimes/openj9-openjdk-jdk10.git OPENJDK_BRANCH = openj9 OPENJDK_SHA = 
[Pipeline] echo
Using OPENJ9_REPO =  OPENJ9_BRANCH =  OPENJ9_SHA = 
Using OMR_REPO =  OMR_BRANCH =  OMR_SHA = 
[Pipeline] echo
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // node
[Pipeline] node
Running on ub16-390-1 in /home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-JDK10-linux_390-64_cmprssptrs-OpenJ9
```

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/openj9/view/Pull%20Requests/job/PullRequest-Compile-JDK10-aix_ppc-64_cmprssptrs-OpenJ9/8/console
