### ISSUE TITLE
All AIX machines offline in jenkins

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9759]

**Comment by pshipton** [comment]
@jdekonin @AdamBrousseau

**Comment by jdekonin** [comment]
I think the VPN was okay, but the machines are not reachable.

I've sent an email to our contact; waiting reply.  We do not have a method for rebooting these ourselves atm.

**Comment by jdekonin** [comment]
There was a power failure; teams are working to restore it.  @AdamBrousseau, @rajdeepsingh1 and I are on the email chain.  When we have been advised one of us will verify they have come back online, which should happen automatically.

**Comment by pshipton** [comment]
They are back online now.

**Comment by pshipton** [comment]
Now the machines are failing to download the JDKs.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/541
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_ppc64_aix_OMR/546
```
17:05:02  get jdk binary...
17:05:02  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_ppc64_aix_OMR/617/OpenJ9-JDK8-ppc64_aix-20200601-201213.tar.gz
18:20:21  curl: (56) OpenSSL SSL_read: Error 0
18:20:21  curl error code: 56. Sleep 300 secs, then retry 1...
```

**Comment by AdamBrousseau** [comment]
Network is horribly slow. 12KB/s download from OSU Artifactory. I can download from Adopt (AWS) fast (25MB/s). Other machines pull from Artifactory fine. Tried a reboot on `#1`, didn't help. I will email back the site support.

**Comment by jdekonin** [comment]
Email from our contact states that service has not been 100% restored as of yet, so what we have is what we have for the time being.

**Comment by pshipton** [comment]
The subsequent nightly builds and omr acceptance ran fine, I'll go ahead and close until another problem surfaces.
