### ISSUE TITLE
Windows 32 bit version is not built Large address aware

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9774]
Duplicated from https://github.com/AdoptOpenJDK/openjdk-support/issues/115

- Platform and architecture (e.g. Linux/x64:
Windows W32

- Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.:
Both jdk8u252-b09 jdk8u232-b09

- Variant e.g. HotSpot or OpenJ9:
OpenJ9

- Have you tested it with other vendors' java:
Yes IBM version is Large address aware

- Steps to reproduce:
dumpbin /headers java.exe |grep -i large
or
dumpbin /headers nlnotes.exe |grep -i large

If nothing found can't handle >2GB address

- Error messsage and/or description of what is not working as expected:
The openJDK J9 32 bit version is not built Large address aware and therefore cannot address memory > 2 GB and so the command fails. The headers output does not have this line in it:
`Application can handle large (>2GB) addresses`
dumpbin /headers nlnotes.exe |grep -i large
or
dumpbin /headers java.exe |grep -i large

**Comment by pshipton** [comment]
References

https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=vs-2017

https://github.com/eclipse/openj9/blob/master/runtime/makelib/targets.mk.win.inc.ftl#L119

I don't find any occurrences of `/LARGEADDRESSAWARE` in the openjdk8 repo.

**Comment by DanHeidinga** [comment]
@pshipton does this apply to Hotspot as well?  If so we should talk to @andrew-m-leonard about trying to get the change upstreamed.

**Comment by pshipton** [comment]
Yes I will, after I confirm it's working.
