### ISSUE TITLE
Install VS2019 for Java 15 Windows builds

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9805]
The default compiler for Java 15 is VS2019. It needs to be installed on at least one machine so we can test OpenJ9 with it, and then once confirmed working, rolled out to them all. Since it's the default for Java 15, if it doesn't just work with OpenJ9 we'll need to configure Java 15 (next) to build with an older version until it's working.

**Comment by pshipton** [comment]
@jdekonin

**Comment by jdekonin** [comment]
Adopt playbook updates for this found here : 
https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1481

**Comment by jdekonin** [comment]
Installed VS2019 on win2012r2-x86-6.  It appears to be under 3G total.

- [ ] win2012r2-x86-1
- [ ] win2012r2-x86-2
- [ ] win2012r2-x86-3
- [ ] win2012r2-x86-4
- [ ] win2012r2-x86-5
- [ ] win2012r2-x86-6

**Comment by jdekonin** [comment]
Opened #10303 to help address space issues that this is going to have with the addition of VS2013 (#10129) and VS2019.

**Comment by pshipton** [comment]
Note we don't need VS2010 once moved to VS2013. We can stage the move. i.e. start on one machine, remove the build label, remove 2010, install 2013, ensure the JVM can build on 2013 and pass testing. Add back the build label to this machine, do the other machines one by one.

**Comment by pshipton** [comment]
The above suggestion temporarily allows some builds to use 2013 and some to use 2010, but ideally this time period will be minimized. The `-Xinternalversion` option shows which version of the compiler was used to build.

**Comment by pshipton** [comment]
Ah, I guess supporting both 2010 and 2013 at the same time isn't feasible due to the settings in defaults.yml. In this case, remove the build labels from the 2010 machines and commit to updating at least a couple of machines in the same day.

**Comment by jdekonin** [comment]
We are constantly on the edge with space on these systems.  Even with the compile juggling the systems are only going to have ~10G free.  While that is an option, the bit of extra space would avoid future failures due to lack of space.

**Comment by pshipton** [comment]
Yup, just thinking of alternatives for (a) you don't get additional space in time for the Java 15 release which is coming up quicly, or (b) you don't get additional space ever.

**Comment by jdekonin** [comment]
Work is complete, waiting on fix for #9967.
