### ISSUE TITLE
Move OSX JDK8 builds to a newer OS

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9806]
I believe Adopt is building OSX on an OS newer than 10.11 now, which jdk8 has been modified to support. @sxa can you please confirm which one.

The OpenJ9 build should be moved to match. The JDK8 build instructions are already updated. https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md

**Comment by pshipton** [comment]
@jdekonin

**Comment by keithc-ca** [comment]
10.14 should be fine, but I think it make sense to use the latest version of Xcode available for Mohave, which according to the site you referenced, is 11.2.1.

**Comment by DanHeidinga** [comment]
Does moving to a new xcode release require changes to the Extensions repo?  We should aim to match the OpenJDK build compilers when possible to minimize Extension patches

**Comment by keithc-ca** [comment]
I don't expect any changes will be required to extension repos. They all build with 10.3 (on 10.14 Mohave) now and they all build as-is with 11.4 (on 10.15 Catalina) for me.

**Comment by pshipton** [comment]
From https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1400 we get the following information. @jdekonin is this sufficient to recreate the build environment?

This is the Xcode version we use to build JDK8u. Note it is full Xcode rather than the command line tools:

build-macstadium-macos1014-x64-1:~ administrator$ xcodebuild -version
Xcode 10.3
Build version 10G8

**Comment by pshipton** [comment]
@keithc-ca since we can obviously build with xcode versions < 11.4, and are using this older version to build the releases, I think the build instructions need to be updated.

**Comment by keithc-ca** [comment]
See #9933.

**Comment by jdekonin** [comment]
We can go with xcode version 10.3 yes.

**Comment by jdekonin** [comment]
I have a system that Pav Salimon setup for me with 10.14.6 and xcode 10.3.  bootjdk is 
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
Eclipse OpenJ9 VM (build openj9-0.20.0, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200416_527 (JIT enabled, AOT enabled)
```

Using this configure cmdln : `bash configure --with-freemarker-jar=/Users/jenkins/freemarker.jar --with-boot-jdk=/Users/jenkins/bootjdks/adoptojdk-java-8 --disable-zip-debug-info --with-toolchain-type=clang`

My compile keeps getting hung here 
```
Generating DDR pointer class source files
Generating DDR structure stub source files
Generating DDR pointer and structure class files
superset directory name : /Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/vm/
superset file name : superset.dat
Writing generated classes to /Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/jdk/ddr/gensrc/com/ibm/j9ddr/vm29/pointer/g
superset directory name : /Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/vm/
superset file name : superset.dat
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
Writing generated classes to /Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/jdk/ddr/gensrc/com/ibm/j9ddr/vm29/structure
2020-06-26 11:54:46.152 java[65437:156754] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for
Unhandled structure type: big_int_unionPointer->i128 __int128
Processing complete
Processing complete
```

This appears to be the process that never comes back when I walk through the ps output.
```
/Users/jenkins/bootjdks/adoptojdk-java-8/bin/java -Xms64M -Xmx1600M -XX:ThreadStackSize=1536 -XX:PermSize=32m -XX:MaxPermSize=160m -XX:-PrintVMOptions -XX:-UnlockDiagnosticVMOptions -XX:-LogVMOutput -cp /Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/jdk/ddr/tools:/Users/jenkins/workspace/openj9-openjdk-jdk8/openj9/debugtools/DDR_VM/src com.ibm.j9ddr.tools.ClassGenerator --blob=/Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/vm/j9ddr.dat --out=/Users/jenkins/workspace/openj9-openjdk-jdk8/build/macosx-x86_64-normal-server-release/jdk/ddr/classes
```

**Comment by pshipton** [comment]
@keithc-ca ^

**Comment by keithc-ca** [comment]
That hang looks like #9425.

**Comment by jdekonin** [comment]
@olvap377 can you please setup these 3 systems with 10.14.6 and xcode 10.3.  Thanks.

- [ ] osx1014-x86-1 @ 10.14.3 currently
- [ ] osx1014-x86-2 @ 10.14.3 currently
- [ ] osx1014-x86-3 @ 10.14.6 already

**Comment by jdekonin** [comment]
@pshipton @DanHeidinga what do you want to do about JDK11 and newer releases?  I would assume they should be moved up to use the same as long as that works?  Currently JDK11+ is targeted at 10.13 systems and using toolchain 9.4

For JDK8, MACOSX_DEPLOYMENT_TARGET is set to 10.9.0.  For JDK11+, MACOSX_DEPLOYMENT_TARGET should be set to 10.13.0?

Do you want to keep any systems on older levels or have all 6 systems at 10.14.6 and capable of compile & test for all releases?

**Comment by pshipton** [comment]
For JDK11, https://adoptopenjdk.net/supported_platforms.html shows 10.10+ is supported.

**Comment by pshipton** [comment]
What Adopt is using for JDK11+ https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1400#issuecomment-657462754

**Comment by jdekonin** [comment]
Why would we use an older version of xcode on the newer release?  That doesn't make sense to me.  I asked in https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1400

I can update the env for MACOSX_DEPLOYMENT_TARGET to be 10.10.0 for all releases.

**Comment by pshipton** [comment]
Are you sure xcode 10.3 is newer than clang 10? You need to get the clang version from xcode 10.3 to compare.

**Comment by jdekonin** [comment]
I think we are fine with the setup we have then.  No sense in adding a second toolchain to the machines.

```
osxrt9:~ jenkins$ xcodebuild -version
Xcode 10.3
Build version 10G8
osxrt9:~ jenkins$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by olvap377** [comment]
osx1014-x86-1 - updated to 10.14.6
 osx1014-x86-2 - updated to 10.14.6
 osx1014-x86-3 - installed latest 10.14.6 updates

Removing `CommandLineTools` next and installing `Xcode 10.3`

**Comment by olvap377** [comment]
All 3 machines now have `Xcode`
```
osx1014-x86-1:~ jenkins$ xcodebuild -version
Xcode 10.3
Build version 10G8
```

**Comment by olvap377** [comment]
PR merged, this should be good to close

**Comment by jdekonin** [comment]
Actually I think there is some cleanup here to perform first.

We have 2 macs @ 10.11, 2 @ 10.13 and 3 @ 10.14.  What kind of version distribution do we want to maintain for test coverage?  Or do we just want to have everything at 10.14 and newer?

**Comment by jdekonin** [comment]
@pshipton any comment on my previous question?

**Comment by pshipton** [comment]
I'd prefer to keep what we have for distributed testing. If where is some problem keeping the older machines let me know.

**Comment by jdekonin** [comment]
There is no problem keeping the older machines that I am aware of.  So I guess this issue is complete and can be closed.
