### ISSUE TITLE
Disable building JITServer for XL build

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#9824]
There are a few `testJITServer` test failures with XL bulids [1]. There is not much value using `JITServer` in large heap builds. It's preferred to disable building JITServer for `ppc64le_linux_xl` and `x86-64_linux_xl`.  Currently  `ppc64le_linux_xl` and `x86-64_linux_xl` build config extend from  `ppc64le_linux` and `x86-64_linux`. To exclude `--enable-jitserver` flag, XL builds might need not to extend from the non-XL build. 

[1]

- [#9629 testJITServer NoClassDefFoundError: java.lang.ref.Cleaner$Cleanable ](https://github.com/eclipse/openj9/issues/9629)
- [#9440 JDK8 testJITServer_1 : NPE at sun.misc.MetaIndex.mayContain(MetaIndex.java:242) ](https://github.com/eclipse/openj9/issues/9440)
- [#9197 testJITServer_1 String.indexOf NullPointerException and Failed to properly start client](https://github.com/eclipse/openj9/issues/9197)
- [#9191 JDK15 testJITServer_1 testServerUnreachableForAWhile AssertionError ](https://github.com/eclipse/openj9/issues/9191)

[2]

https://github.com/eclipse/openj9/blob/1f34b29d93b9af09b53b55e7a1a923d5a19eceed/buildenv/jenkins/variables/defaults.yml#L320-L325

**Comment by a7ehuo** [comment]
@AdamBrousseau @mpirvu FYI

**Comment by mpirvu** [comment]
Somehow I would prefer to disable just the testing and not the building. I know that in theory we shouldn't build what we don't test, but I hope this to be a temporary solution until we get JITServer defects under control at which point we will re-enable XL testing.

**Comment by a7ehuo** [comment]
> Somehow I would prefer to disable just the testing and not the building

I'll look at the possibility of disabling the test for XL build.

**Comment by AdamBrousseau** [comment]
You can disable all the testing in the variable file. There are examples elsewhere in the file you just have to list all the targets. I can put in a PR tonight if there isn't one by then.

**Comment by a7ehuo** [comment]
Thanks @AdamBrousseau . #9828 is created to skip this test for XL builds. No need to disable building JITServer for XL builds. Close this issue.
