### ISSUE TITLE
xlinux jdk11 cmake Unknown option: concurrentScavenge

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9832]
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_x86-64_linux_cm_Nightly/1
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_x86-64_linux_cm_Nightly/1
`JVMJ9GC040E Unknown option: concurrentScavenge`

**Comment by pshipton** [comment]
@dnakamura

**Comment by dnakamura** [comment]
See #9836

**Comment by pshipton** [comment]
Closing as a dup of #8667
