### ISSUE TITLE
-XX:+UseLargePages option does not have an effect on performance

### ISSUE THREAD

**Issue by BeverlyXu** [eclipse/openj9#9843]
I was investigating a performance issue on Java 11 and found the option `-XX:+UseLargePages` doesn't have any impact on the Liberty performance. 

I've conducted the following experiments.

- Experiment 1 OpenJ9 `no largepage options`
  `throughput score: 5598`
    However /proc/meminfo shows hugepages being rsvd and used. 

- Experiment 2 OpenJ9 `-XX:-UseLargePages` or `-XX:+UseLargePages`
    `throughput score: on par with Experiment 1`
    However /proc/meminfo shows hugepages being rsvd and used in _**both cases**_

- Experiment 3 **_Hotspot_** `-XX:-UseLargePages`
   /proc/meminfo shows CORRECTLY hugepages are not being used

- Experiment 4 OpenJ9 `-Xlp:codecache:pagesize=2M -Xlp:objectheap:pagesize=2M`
    `throughput score: 5943.6`
    +6% improvement from Experiment 1

- Experiment 5 OpenJ9 `-Xlp:codecache:pagesize=4K -Xlp:objectheap:pagesize=4K`
    `throughput score: 5539, on par with Experiment 1`
    Hugepages correctly disabled, no usage in /proc/meminfo

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Linux amd64-64-Bit Compressed References 20200122_441 (JIT enabled, AOT enabled)
OpenJ9 - 51a5857d2
OMR - 7a1b0239a
JCL - da35e0c380 based on jdk-11.0.6+10)

**Conclusion**: When using `UseLargePages` option on OpenJ9, the OS shows the application reserves and uses hugepages, but it doesn't have any improvement on performance. When we force the 2M pagesize using IBM option, the J9 performance improved about 6%, as expected. And when we disable `UseLargePages` in J9, OS still shows hugepages being used, while Hotspot shows no hugepages being used.

**Comment by DanHeidinga** [comment]
Closing as suggested in https://github.com/eclipse/openj9/issues/9843#issuecomment-642239012
