### ISSUE TITLE
Enable testJITServer tests for ppc64le_linux_jit builds

### ISSUE THREAD

**Issue by a7ehuo** [eclipse/openj9#9852]
This is a placeholder to track the work item to enable `testJITServer` tests for `ppc64le_linux_jit` builds.

As mentioned in https://github.com/eclipse/openj9/pull/9828#issuecomment-642254063, `testJITServer_0/1` are disabled for both `ppc64le_linux_jit` and `ppc64le_linux` builds. Preferably they should be enabled in `ppc64le_linux_jit` but not `ppc64le_linux` next.  Maybe we could add `arch.ppc` to `platformRequirements` but also check if `JITAAS` is set in `TEST_FLAG`  besides of if the `jitserver` launcher exists under `bin` before starting the tests.

**Comment by dmitry-ten** [comment]
Now that JITServer tests on power pass, `testJITServer` tests should also be enabled for both `ppc64le_linux_jit` and `ppc64le_linux` builds to match the behavior of `x86` tests.

**Comment by dmitry-ten** [comment]
@mpirvu fyi.
