### ISSUE TITLE
Compile xlinux jdk15+ on CentOS 7

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9855]
jdk15 xlinux should compile on CentOS 7.
Older versions may change as well, but this is not yet decided.
fyi https://github.com/AdoptOpenJDK/openjdk-build/issues/1819

**Comment by pshipton** [comment]
@jdekonin

**Comment by rajdeepsingh1** [comment]
6 cent7 x machines have been created and ready to be added to Jenkins.

https://github.com/eclipse-cbi/jiro/pull/117

**Comment by rajdeepsingh1** [comment]
@pshipton machines are now online in Jenkins:

cent7-x64-1
cent7-x64-2
cent7-x64-3
cent7-x64-4
cent7-x64-5
cent7-x64-6

**Comment by jdekonin** [comment]
Updating reference repos
https://ci.eclipse.org/openj9/view/Infrastructure/job/Update-Reference-Repos/557/
