### ISSUE TITLE
Enable tracepoints in our inlined headers

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#9886]
There are some technical challenges to adding a tracepoint in `inlineAllocateIndexableObject` and `inlineAllocateIndexableValueTypeObject` - basically in any API that lives in one of the helper header files like: ObjectAllocationAPI.hpp and are only used in VMHelpers.hpp.

None of the existing VMHelper have tracepoints. Attempting to inlcude the vm tracespoints causes issues when the inline functions are used in GC code, and vice versa when using the GC tracepoints. Other than using a tracepoint via a function table I'm not sure there is a simple way to add it.

_Originally posted by @tajila in and modified here by @DanHeidinga https://github.com/eclipse/openj9/issues/9200#issuecomment-643403140_

**Comment by gacholio** [comment]
These are all high-performance inline functions, so they're really not appropriate places to put tracepoints in general.

**Comment by DanHeidinga** [comment]
I think there are slow paths / exceptions / etc in those functions that are appropriate to trace but I'm willing to close this for now until we have one of those points to argue over.
