### ISSUE TITLE
VM's version of JVMTI (11.0.0), it needs JVMTI 15.0[.0]

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9889]
Occurred running jdk11 cmake testing, but I suspect it's not cmake specific. Not sure why the regular system tests didn't fail.

Full build https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/218/

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_cm_Personal_testList_1/1
```
===============================================
Running test cmdLineTester_jvmtitests_hcr_OSRG_nongold_0 ...
===============================================
cmdLineTester_jvmtitests_hcr_OSRG_nongold_0 Start Time: Mon Jun 15 17:34:18 2020 Epoch Time (ms): 1592256858413
variation: Mode107-OSRG
JVM_OPTIONS:  -Xgcpolicy:optthruput -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,onthrow=no.pkg.foo,launch=echo -Xjit:enableOSR,enableOSROnGuardFailure,count=1,disableAsyncCompilation 
ERROR: This jdwp native library will not work with this VM's version of JVMTI (11.0.0), it needs JVMTI 15.0[.0].

cmdLineTester_jvmtitests_hcr_OSRG_nongold_0_FAILED
```

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_cm_Personal_testList_0/1/
TestRefreshGCSpecialClassesCache_NOBCI_JIT_ON_0
TestRefreshGCSpecialClassesCache_BCI_FAST_HCR_2
TestRefreshGCSpecialClassesCache_BCI_EXTENDED_HCR_1

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_cm_Personal_otherLoadTest/1
ClassLoadingTest_special_3
ClassLoadingTest_special_24

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_cm_Personal_daaLoadTest/1
DaaLoadTest_daa1_special_3
DaaLoadTest_daa1_special_24
etc.

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_special.system_x86-64_linux_xl_cm_Personal_mathLoadTest/1
MathLoadTest_all_special_3
MathLoadTest_all_special_23
etc.

**Comment by pshipton** [comment]
@JasonFengJ9

**Comment by JasonFengJ9** [comment]
It seems `JVMTI_VERSION` (now it is `JVMTI_VERSION_15`) picked up by `JDK11 JCL jdwp` natives.
