### ISSUE TITLE
The flsanity test suite is obsolete and should be removed

### ISSUE THREAD

**Issue by hangshao0** [eclipse/openj9#99]
Also the following functions in util_api.h has declaration only:

I_32 helperDoubleArcCos(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleArcSin(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleArcTan(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleArcTan2Double(ESDOUBLE *a, ESDOUBLE *b, ESDOUBLE *c);
I_32 helperDoubleExp(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleIEEERemainderDouble(ESDOUBLE *a, ESDOUBLE *b, ESDOUBLE *c);
I_32 helperDoubleLn(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoublePowDouble(ESDOUBLE * a, ESDOUBLE * b, ESDOUBLE * c);
I_32 helperDoubleRint(ESDOUBLE * a, ESDOUBLE * b);
I_32 helperDoubleCeil(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleCos(ESDOUBLE * a, ESDOUBLE * b);
I_32 helperDoubleFloor(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleSin(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleSqrt(ESDOUBLE *a, ESDOUBLE *b);
I_32 helperDoubleTan(ESDOUBLE * a, ESDOUBLE * b);

The implementations are removed (file flttrig.c/flttrigcldc.c does not exist anymore), so there is no need to keep the declarations.

**Comment by pshipton** [comment]
FYI https://help.github.com/articles/closing-issues-using-keywords/
Issues can be closed automatically when the Pull Request is merged.

**Comment by hangshao0** [comment]
> FYI https://help.github.com/articles/closing-issues-using-keywords/
> Issues can be closed automatically when the Pull Request is merged.

Thanks for letting me know.
