### ISSUE TITLE
JEP 320 Remove the Java EE and CORBA Modules

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#992]
https://bugs.openjdk.java.net/browse/JDK-8189188

This is an "Epic" to contain requirements for supporting this JEP on OpenJ9.

**Comment by pshipton** [comment]
@smlambert @llxia note this will affect Java 11 testing. Anything that uses "--add-modules java.se.ee" will need to be fixed. Likely rewritten to avoid use of the java.se.ee code, since it won't exist. Otherwise the tests will have to add an EE implementation from elsewhere, such as Eclipse Jakarta EE.

**Comment by irinarada** [comment]
@llxia can we fix this so we can progress with the compiler update testing - see 1684?
 @smlambert FYI

**Comment by llxia** [comment]
@irinarada yep, we are working on #2071.

**Comment by llxia** [comment]
fyi, test result is updated on #1684.

**Comment by pshipton** [comment]
@llxia is all the testing work for this completed?

**Comment by llxia** [comment]
yes, openj9 testing work for this is completed.
