### ISSUE TITLE
Investigate caching Class#getSimpleName & #getCanonicalName

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#9963]
Investigate whether we can cache these results so they don't have to be re-calculated over and over.

To avoid increasing the size of the java.lang.Class objects, the names can be cached in the ReflectCache for each class.

This will need footprint measurements as well as some microbenches to validate the benefits

**Comment by alexey-anufriev** [comment]
hi @DanHeidinga, could you please assign this issue to me?

**Comment by pshipton** [comment]
https://github.com/eclipse/openj9/pull/10930 was reverted due to https://github.com/eclipse/openj9/issues/11040
