### ISSUE TITLE
The nightly build (jdk-9+181-20 on January 22 2018) has different behaviors from OpenJDK

### ISSUE THREAD

**Issue by tianxiaogu** [eclipse/openj9#999]
[C0.class (via Google Drive)](https://drive.google.com/open?id=1CdaiP02IUO32hKKbilQIQiFhm2hRg97d) triggers different behaviors on OpenJDK and OpenJ9.

The nightly build (jdk-9+181-20 on January 22 2018) throws an exception in default mode,
where OpenJDK (head) exits normally.

This bug may relate to #997. I am not sure whether this is a bug of OpenJDK or OpenJ9.

OpenJ9-JDK9
```
$ ./jdk-9+181/bin/java C0
Exception in thread "main" java.lang.NegativeArraySizeException
	at C0.main(Unknown Source)
$ ./jdk-9+181/bin/java -Xcomp C0
Exception in thread "main" java.lang.NegativeArraySizeException
	at C0.main(Unknown Source)
$ ./jdk-9+181/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20180122_95 (JIT enabled, AOT enabled)
OpenJ9   - d38352e
OMR      - cfd2f17
OpenJDK  - be5903d based on jdk-9+181)
```

OpenJDK
```
$ ./openjdk/jdk/build/linux-x86_64-normal-server-release/jdk/bin/java C0
$ echo $?
0
$ ./openjdk/jdk/build/linux-x86_64-normal-server-release/jdk/bin/java --version
openjdk 10-internal 2018-03-20
OpenJDK Runtime Environment (build 10-internal+0-adhoc.t.jdk)
OpenJDK 64-Bit Server VM (build 10-internal+0-adhoc.t.jdk, mixed mode)
```

Oracle JDK 9.0.4
```
$ ./jdk-9.0.4/bin/java C0
$ echo $?
0
$ ./jdk-9.0.4/bin/java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

**Comment by pshipton** [comment]
What happens when you run `./jdk-9+181/bin/java -Xint C0`?

**Comment by tianxiaogu** [comment]
@pshipton The same exception is thrown with `./jdk-9+181/bin/java -Xint C0`.

```
$ ../jdk-9+181/bin/java -Xint C0
Exception in thread "main" java.lang.NegativeArraySizeException
        at C0.main(Unknown Source)
```

**Comment by dnakamura** [comment]
The bytecodes causing the issue (truncated for clarity)
```
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=6, locals=2, args_size=1
.....
        35: invokestatic  #22                 // Method M1:()C
        38: anewarray     #24                 // class java/lang/Float
```
```
  public static char M1();
    descriptor: ()C
    flags: (0x0009) ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: sipush        5260
         3: ineg
         4: ireturn
```

Which would approximately correspond to the following java code
```
class C0 {
	public static main(string[] args){
		....
		new float[M1()];
		...
	}
	public static char M1(){
		return -5260;
	}
}
```
However I suspect that if you fed this to javac it would add an implicit `i2c` instruction to the end of M1

The issue here is that internally the JVM only operates on int types, and will sign extend or truncate as needed on loads and stores. My suspicion is that Oracle is implicitly truncating  to a `char` as part of the `iret`, even though, on first glance, there doesn't appear to be any requirement to do so in the spec. @DanHeidinga  is this something we want to do anyway in order to match Oracles behavior?

**Comment by pshipton** [comment]
A char is a 16-bit unsigned integer. 

This simple test prints 60276.
```
		System.out.println((int)(char)-5260);
```

**Comment by DanHeidinga** [comment]
I know @gacholio has looked into similar issues in the past.  Let's take advantage of being colocated and discuss in person.  @dnakamura Can you book a meeting today?

And we'll make sure to update this after the discussion.

**Comment by DanHeidinga** [comment]
Looking at the Java 9 JVMS for `ireturn`, it states:

```
Prior to pushing value onto the operand stack of the frame of the invoker, it may have to be converted. If the return type of the invoked method was byte, char, or short, then value is converted from int to the return type as if by execution of i2b, i2c, or i2s, respectively. If the return type of the invoked method was boolean, then value is narrowed from int to boolean by taking the bitwise AND of value and 1.
```

https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-6.html#jvms-6.5.ireturn

We can do this by either:
* Looking at the return type in the `JBreturn1` bytecode (expensive)
* Adding new internal bytecodes to return `c`, `s`, `b`, `z`.  The verifier will also need to be updated.  As will the JIT and potentially the jit return bytecodes, though we may get away with a single one if the compiled code can ensure the conversion has already occurred.

**Comment by dnakamura** [comment]
I have a solution which does fix the test case (https://github.com/dnakamura/openj9/tree/ret_opcode).  Although I'm not sure its the right solution, and of course it needs to add jit support

**Comment by pshipton** [comment]
It would be easier if a WIP Pull Request is created for the changes.

**Comment by DanHeidinga** [comment]
@dnakamura Can you outline the next steps on this?

**Comment by dnakamura** [comment]
Currently the code for executing the new bytecodes is in place. I have changes which will cause the new bytecodes to be emitted, and updates to the verifier.  Currently waiting on support in the jit for the new bytecodes. Perhaps  @andrewcraik  or @fjeremic  can provide more details for the jit part

**Comment by DanHeidinga** [comment]
Can you open a WIP PR for the remaining VM changes so we can get them reviewed and ready to merge as soon as the jit support is ready?

**Comment by DanHeidinga** [comment]
https://github.com/eclipse/openj9/pull/1831 resolves this issue
